MagickCore: annotate.c File Reference
annotate.c File Reference
#include "magick/studio.h"
#include "magick/annotate.h"
#include "magick/attribute.h"
#include "magick/cache-private.h"
#include "magick/cache-view.h"
#include "magick/channel.h"
#include "magick/client.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colorspace-private.h"
#include "magick/composite.h"
#include "magick/composite-private.h"
#include "magick/constitute.h"
#include "magick/draw.h"
#include "magick/draw-private.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/image-private.h"
#include "magick/log.h"
#include "magick/quantum.h"
#include "magick/quantum-private.h"
#include "magick/pixel-accessor.h"
#include "magick/policy.h"
#include "magick/property.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/statistic.h"
#include "magick/string_.h"
#include "magick/token.h"
#include "magick/token-private.h"
#include "magick/transform.h"
#include "magick/type.h"
#include "magick/utility.h"
#include "magick/xwindow-private.h"
Data Structures
struct _GraphemeInfo
Typedefs
typedef struct _GraphemeInfo GraphemeInfo
Functions
static MagickBooleanType RenderType (Image *, const DrawInfo *, const PointInfo *, TypeMetric *)
static MagickBooleanType RenderPostscript (Image *, const DrawInfo *, const PointInfo *, TypeMetric *)
static MagickBooleanType RenderFreetype (Image *, const DrawInfo *, const char *, const PointInfo *, TypeMetric *)
static MagickBooleanType RenderX11 (Image *, const DrawInfo *, const PointInfo *, TypeMetric *)
MagickExport MagickBooleanType AnnotateComponentGenesis (void)
MagickExport void AnnotateComponentTerminus (void)
MagickExport MagickBooleanType AnnotateImage (Image *image, const DrawInfo *draw_info)
MagickExport ssize_t FormatMagickCaption (Image *image, DrawInfo *draw_info, const MagickBooleanType split, TypeMetric *metrics, char **caption)
MagickExport MagickBooleanType GetMultilineTypeMetrics (Image *image, const DrawInfo *draw_info, TypeMetric *metrics)
MagickExport MagickBooleanType GetTypeMetrics (Image *image, const DrawInfo *draw_info, TypeMetric *metrics)
static MagickBooleanType RenderFreetype (Image *image, const DrawInfo *draw_info, const char *magick_unused(encoding), const PointInfo *offset, TypeMetric *metrics)
static char * EscapeParenthesis (const char *source)
Variables
static SemaphoreInfo * annotate_semaphore = (SemaphoreInfo *) NULL
Typedef Documentation
GraphemeInfo
typedef struct _GraphemeInfo GraphemeInfo
Function Documentation
AnnotateComponentGenesis()
MagickExport MagickBooleanType AnnotateComponentGenesis (void)
References AllocateSemaphoreInfo(), annotate_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
AnnotateComponentTerminus()
MagickExport void AnnotateComponentTerminus (void)
References ActivateSemaphoreInfo(), annotate_semaphore, and DestroySemaphoreInfo().
Referenced by MagickCoreTerminus().
AnnotateImage()
MagickExport MagickBooleanType AnnotateImage (Image * image, const DrawInfo * draw_info)
References AcquireQuantumMemory(), _DrawInfo::affine, _DrawInfo::align, _TypeMetric::ascent, CastDoubleToUnsigned(), CenterAlign, CenterGravity, CloneDrawInfo(), CloneString(), _Image::colorspace, _Image::debug, _DrawInfo::decorate, _TypeMetric::descent, DestroyDrawInfo(), DestroyString(), DirectClass, DrawImage(), EastGravity, _Image::exception, _Image::filename, _DrawInfo::fill, FormatLocaleString(), _DrawInfo::geometry, GetMagickModule, GetTypeMetrics(), _DrawInfo::gravity, _RectangleInfo::height, _DrawInfo::interline_spacing, IsGrayColorspace(), LeftAlign, LineThroughDecoration, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickPathExtent, MagickTrue, MaxTextExtent, NorthEastGravity, NorthGravity, NorthWestGravity, _PixelPacket::opacity, _TypeMetric::origin, OverlineDecoration, _Image::page, ParseGeometry(), ParsePageGeometry(), _DrawInfo::pointsize, _DrawInfo::primitive, _GeometryInfo::psi, QueryColorname(), RelinquishMagickMemory(), RenderType(), RightAlign, _AffineMatrix::rx, _AffineMatrix::ry, SetGeometry(), SetGeometryInfo(), SetImageColorspace(), SetImageStorageClass(), _DrawInfo::signature, _Image::signature, SouthEastGravity, SouthGravity, SouthWestGravity, sRGBColorspace, StaticGravity, _DrawInfo::stroke, SVGCompliance, _AffineMatrix::sx, _AffineMatrix::sy, _DrawInfo::text, TraceEvent, TransparentOpacity, _AffineMatrix::tx, _AffineMatrix::ty, UndefinedGravity, _DrawInfo::undercolor, _TypeMetric::underline_position, _TypeMetric::underline_thickness, UnderlineDecoration, WestGravity, _TypeMetric::width, _RectangleInfo::width, _PointInfo::x, _RectangleInfo::x, _GeometryInfo::xi, _PointInfo::y, and _RectangleInfo::y.
Referenced by DrawPrimitive(), MontageImageList(), and PolaroidImage().
EscapeParenthesis()
static char * EscapeParenthesis (const char * source) static
References AcquireQuantumMemory(), MaxTextExtent, ResourceLimitFatalError, and ThrowFatalException.
Referenced by RenderPostscript().
FormatMagickCaption()
MagickExport ssize_t FormatMagickCaption (Image * image, DrawInfo * draw_info, const MagickBooleanType split, TypeMetric * metrics, char ** caption)
References AcquireString(), CastDoubleToUnsigned(), ConcatenateMagickString(), CopyMagickString(), DestroyString(), GetTypeMetrics(), GetUTFCode(), GetUTFOctets(), IsUTFSpace(), MagickFalse, _DrawInfo::stroke_width, _DrawInfo::text, and _TypeMetric::width.
Referenced by PolaroidImage().
GetMultilineTypeMetrics()
MagickExport MagickBooleanType GetMultilineTypeMetrics (Image * image, const DrawInfo * draw_info, TypeMetric * metrics)
References AcquireMagickResource(), _TypeMetric::ascent, CloneDrawInfo(), _Image::debug, _TypeMetric::descent, DestroyDrawInfo(), DestroyString(), _DrawInfo::direction, _Image::exception, _Image::filename, GetMagickModule, GetTypeMetrics(), _TypeMetric::height, HeightResource, ImageError, _DrawInfo::interline_spacing, LogMagickEvent(), MagickCoreSignature, MagickFalse, RelinquishMagickMemory(), _DrawInfo::render, _DrawInfo::signature, _Image::signature, StringToStrings(), _DrawInfo::text, ThrowMagickException(), TraceEvent, UndefinedDirection, _TypeMetric::width, and WidthResource.
GetTypeMetrics()
MagickExport MagickBooleanType GetTypeMetrics (Image * image, const DrawInfo * draw_info, TypeMetric * metrics)
References AnnotateEvent, _TypeMetric::ascent, _TypeMetric::bounds, CloneDrawInfo(), _Image::debug, _TypeMetric::descent, DestroyDrawInfo(), _DrawInfo::direction, _Image::filename, GetMagickModule, _TypeMetric::height, LogMagickEvent(), MagickCoreSignature, MagickFalse, _TypeMetric::max_advance, _TypeMetric::origin, _TypeMetric::pixels_per_em, _DrawInfo::render, RenderType(), _DrawInfo::signature, _Image::signature, _DrawInfo::text, TraceEvent, UndefinedDirection, _TypeMetric::underline_position, _TypeMetric::underline_thickness, _TypeMetric::width, _PointInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by AnnotateImage(), FormatMagickCaption(), GetMultilineTypeMetrics(), MontageImageList(), and RenderMVGContent().
RenderFreetype() [1/2]
static MagickBooleanType RenderFreetype (Image * , const DrawInfo * , const char * , const PointInfo * , TypeMetric *)
Referenced by RenderType().
RenderFreetype() [2/2]
static MagickBooleanType RenderFreetype (Image * image, const DrawInfo * draw_info, const char * magick_unusedencoding, const PointInfo * offset, TypeMetric * metrics) static
References _Image::exception, _DrawInfo::font, GetMagickModule, MissingDelegateWarning, RenderPostscript(), and ThrowMagickException().
RenderPostscript()
static MagickBooleanType RenderPostscript (Image * image, const DrawInfo * draw_info, const PointInfo * offset, TypeMetric * metrics)
References AcquireAuthenticCacheView(), AcquireImageInfo(), AcquireUniqueFileResource(), _DrawInfo::affine, AnnotateEvent, _ImageInfo::antialias, _TypeMetric::ascent, _PixelPacket::blue, _TypeMetric::bounds, CastDoubleToLong(), CatchException(), ClampToQuantum(), CloneString(), _Image::columns, CompositeImage(), _Image::debug, DefaultResolution, _DrawInfo::density, _ImageInfo::density, _TypeMetric::descent, DestroyCacheView(), DestroyImage(), DestroyImageInfo(), DestroyString(), EscapeParenthesis(), _Image::exception, ExpandAffine(), _ImageInfo::filename, FileOpenError, _DrawInfo::fill, _DrawInfo::font, FormatLocaleFile(), FormatLocaleString(), GetCacheViewAuthenticPixels(), GetFillColor(), GetImageBoundingBox(), GetMagickModule, GetPixelIntensity(), _PixelPacket::green, _TypeMetric::height, _RectangleInfo::height, LogMagickEvent(), magick_restrict, MagickEpsilon, MagickFalse, MagickTrue, _Image::matte, _TypeMetric::max_advance, MaxTextExtent, _PixelPacket::opacity, OpaqueAlphaChannel, OverCompositeOp, _ImageInfo::page, ParseGeometry(), _TypeMetric::pixels_per_em, _DrawInfo::pointsize, QuantumRange, ReadImage(), _PixelPacket::red, RelinquishUniqueFileResource(), _DrawInfo::render, _GeometryInfo::rho, _Image::rows, _AffineMatrix::rx, _AffineMatrix::ry, SetImageAlphaChannel(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelRed, _GeometryInfo::sigma, SigmaValue, _AffineMatrix::sx, _AffineMatrix::sy, SyncCacheViewAuthenticPixels(), _DrawInfo::text, _DrawInfo::text_antialias, ThrowFileException, TransformImage(), TransparentOpacity, _TypeMetric::underline_position, _TypeMetric::underline_thickness, _TypeMetric::width, _RectangleInfo::width, _PointInfo::x, _RectangleInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _RectangleInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by RenderFreetype(), and RenderType().
RenderType()
static MagickBooleanType RenderType (Image * image, const DrawInfo * draw_info, const PointInfo * offset, TypeMetric * metrics) static
References AcquireExceptionInfo(), CloneDrawInfo(), CloneString(), DestroyDrawInfo(), DestroyExceptionInfo(), DestroyString(), _DrawInfo::encoding, _TypeInfo::encoding, _Image::exception, _DrawInfo::face, _TypeInfo::face, _DrawInfo::family, _TypeInfo::family, _DrawInfo::font, GetMagickModule, GetPolicyValue(), GetTypeInfo(), GetTypeInfoByFamily(), _TypeInfo::glyphs, IsPathAccessible(), LocaleCompare(), MagickFalse, _DrawInfo::metrics, _TypeInfo::metrics, RelinquishMagickMemory(), RenderFreetype(), RenderPostscript(), RenderX11(), _DrawInfo::stretch, StringToArgv(), _DrawInfo::style, ThrowMagickException(), TypeWarning, and _DrawInfo::weight.
Referenced by AnnotateImage(), and GetTypeMetrics().
RenderX11()
static MagickBooleanType RenderX11 (Image * image, const DrawInfo * draw_info, const PointInfo * offset, TypeMetric * metrics)
References ActivateSemaphoreInfo(), annotate_semaphore, LockSemaphoreInfo(), UnlockSemaphoreInfo(), and XRenderImage().
Referenced by RenderType().
Variable Documentation
annotate_semaphore
SemaphoreInfo* annotate_semaphore = (SemaphoreInfo *) NULL static
Referenced by AnnotateComponentGenesis(), AnnotateComponentTerminus(), and RenderX11().