MagickCore: annotate.h File Reference
annotate.h File Reference
#include "magick/draw.h"
Functions
MagickExport MagickBooleanType AnnotateComponentGenesis (void)
MagickExport MagickBooleanType AnnotateImage (Image *, const DrawInfo *)
MagickExport MagickBooleanType GetMultilineTypeMetrics (Image *, const DrawInfo *, TypeMetric *)
MagickExport MagickBooleanType GetTypeMetrics (Image *, const DrawInfo *, TypeMetric *)
MagickExport ssize_t FormatMagickCaption (Image *, DrawInfo *, const MagickBooleanType, TypeMetric *, char **)
MagickExport void AnnotateComponentTerminus (void)
Function Documentation
AnnotateComponentGenesis()
MagickExport MagickBooleanType AnnotateComponentGenesis (void)
AnnotateComponentTerminus()
MagickExport void AnnotateComponentTerminus (void)
References ActivateSemaphoreInfo(), annotate_semaphore, and DestroySemaphoreInfo().
Referenced by MagickCoreTerminus().
AnnotateImage()
MagickExport MagickBooleanType AnnotateImage (Image * , const DrawInfo *)
FormatMagickCaption()
MagickExport ssize_t FormatMagickCaption (Image * image, DrawInfo * draw_info, const MagickBooleanType, TypeMetric * metrics, char ** caption)
References AcquireString(), CastDoubleToUnsigned(), ConcatenateMagickString(), CopyMagickString(), DestroyString(), GetTypeMetrics(), GetUTFCode(), GetUTFOctets(), IsUTFSpace(), MagickFalse, _DrawInfo::stroke_width, _DrawInfo::text, and _TypeMetric::width.
Referenced by PolaroidImage().
GetMultilineTypeMetrics()
MagickExport MagickBooleanType GetMultilineTypeMetrics (Image * , const DrawInfo * , TypeMetric *)
GetTypeMetrics()
MagickExport MagickBooleanType GetTypeMetrics (Image * image, const DrawInfo * draw_info, TypeMetric * metrics)
References AnnotateEvent, _TypeMetric::ascent, _TypeMetric::bounds, CloneDrawInfo(), _Image::debug, _TypeMetric::descent, DestroyDrawInfo(), _DrawInfo::direction, _Image::filename, GetMagickModule, _TypeMetric::height, LogMagickEvent(), MagickCoreSignature, MagickFalse, _TypeMetric::max_advance, _TypeMetric::origin, _TypeMetric::pixels_per_em, _DrawInfo::render, RenderType(), _DrawInfo::signature, _Image::signature, _DrawInfo::text, TraceEvent, UndefinedDirection, _TypeMetric::underline_position, _TypeMetric::underline_thickness, _TypeMetric::width, _PointInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by AnnotateImage(), FormatMagickCaption(), GetMultilineTypeMetrics(), MontageImageList(), and RenderMVGContent().