MagickCore: artifact.c File Reference
artifact.c File Reference
#include "magick/studio.h"
#include "magick/artifact.h"
#include "magick/cache.h"
#include "magick/color.h"
#include "magick/compare.h"
#include "magick/constitute.h"
#include "magick/draw.h"
#include "magick/effect.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/fx.h"
#include "magick/fx-private.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/image.h"
#include "magick/layer.h"
#include "magick/list.h"
#include "magick/memory_.h"
#include "magick/monitor.h"
#include "magick/montage.h"
#include "magick/option.h"
#include "magick/profile.h"
#include "magick/quantum.h"
#include "magick/resource_.h"
#include "magick/splay-tree.h"
#include "magick/signature-private.h"
#include "magick/statistic.h"
#include "magick/string_.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/xml-tree.h"
Functions
MagickExport MagickBooleanType CloneImageArtifacts (Image *image, const Image *clone_image)
MagickExport MagickBooleanType DefineImageArtifact (Image *image, const char *artifact)
MagickExport MagickBooleanType DeleteImageArtifact (Image *image, const char *artifact)
MagickExport void DestroyImageArtifacts (Image *image)
MagickExport const char * GetImageArtifact (const Image *image, const char *artifact)
MagickExport char * GetNextImageArtifact (const Image *image)
MagickExport char * RemoveImageArtifact (Image *image, const char *artifact)
MagickExport void ResetImageArtifactIterator (const Image *image)
MagickExport MagickBooleanType SetImageArtifact (Image *image, const char *artifact, const char *value)
Function Documentation
CloneImageArtifacts()
MagickExport MagickBooleanType CloneImageArtifacts (Image * image, const Image * clone_image)
References _Image::artifacts, CloneSplayTree(), ConstantString(), _Image::debug, DestroyImageArtifacts(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::signature, and TraceEvent.
Referenced by CloneImage(), CoalesceImages(), and DisposeImages().
DefineImageArtifact()
MagickExport MagickBooleanType DefineImageArtifact (Image * image, const char * artifact)
References CopyMagickString(), MaxTextExtent, and SetImageArtifact().
DeleteImageArtifact()
MagickExport MagickBooleanType DeleteImageArtifact (Image * image, const char * artifact)
References _Image::artifacts, _Image::debug, DeleteNodeFromSplayTree(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
Referenced by AcquireResizeFilter(), and SetImageArtifact().
DestroyImageArtifacts()
MagickExport void DestroyImageArtifacts (Image * image)
References _Image::artifacts, _Image::debug, DestroySplayTree(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
Referenced by CloneImageArtifacts(), and DestroyImage().
GetImageArtifact()
MagickExport const char * GetImageArtifact (const Image * image, const char * artifact)
References _Image::artifacts, _Image::debug, _Image::filename, GetMagickModule, GetNextValueInSplayTree(), GetValueFromSplayTree(), LogMagickEvent(), MagickCoreSignature, MagickFalse, ResetSplayTreeIterator(), _Image::signature, and TraceEvent.
Referenced by AcquireResizeFilter(), AddNoiseImageChannel(), AutoThresholdImage(), CloneImages(), CompareImageChannels(), ComplexImages(), CompositeImageChannel(), ConnectedComponentsImage(), DeskewImage(), DistortImage(), DrawClipPath(), DrawPatternPath(), DrawPolygonPrimitive(), FloydSteinbergDither(), FxGetSymbol(), GenerateCoefficients(), GetEdgeBackgroundFactor(), GetEdgeBoundingBox(), GetImageBoundingBox(), GetImageProperty(), GetMagickProperty(), GetMagickPropertyLetter(), GradientImage(), HoughLineImage(), IdentifyImage(), InterpretImageFilename(), InterpretImageProperties(), ModulateImage(), MorphologyApply(), MorphologyImageChannel(), RenderMVGContent(), SampleImage(), SetImageType(), SetResampleFilter(), SimilarityMetricImage(), and SparseColorImage().
GetNextImageArtifact()
MagickExport char * GetNextImageArtifact (const Image * image)
References _Image::artifacts, _Image::debug, _Image::filename, GetMagickModule, GetNextKeyInSplayTree(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
Referenced by IdentifyImage(), and InterpretImageProperties().
RemoveImageArtifact()
MagickExport char * RemoveImageArtifact (Image * image, const char * artifact)
References _Image::artifacts, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, RemoveNodeFromSplayTree(), _Image::signature, and TraceEvent.
ResetImageArtifactIterator()
MagickExport void ResetImageArtifactIterator (const Image * image)
References _Image::artifacts, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, ResetSplayTreeIterator(), _Image::signature, and TraceEvent.
Referenced by IdentifyImage(), and InterpretImageProperties().
SetImageArtifact()
MagickExport MagickBooleanType SetImageArtifact (Image * image, const char * artifact, const char * value)
References AddValueToSplayTree(), _Image::artifacts, CompareSplayTreeString(), ConstantString(), _Image::debug, DeleteImageArtifact(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, NewSplayTree(), RelinquishMagickMemory(), _Image::signature, and TraceEvent.
Referenced by DefineImageArtifact(), DeskewImage(), GetMagickProperty(), GetMagickPropertyLetter(), RenderMVGContent(), SketchImage(), StripImage(), and SyncImageSettings().