MagickCore: artifact.h File Reference
artifact.h File Reference
Functions
MagickExport char * GetNextImageArtifact (const Image *)
MagickExport char * RemoveImageArtifact (Image *, const char *)
MagickExport const char * GetImageArtifact (const Image *, const char *)
MagickExport MagickBooleanType CloneImageArtifacts (Image *, const Image *)
MagickExport MagickBooleanType DefineImageArtifact (Image *, const char *)
MagickExport MagickBooleanType DeleteImageArtifact (Image *, const char *)
MagickExport MagickBooleanType SetImageArtifact (Image *, const char *, const char *)
MagickExport void DestroyImageArtifacts (Image *)
MagickExport void ResetImageArtifactIterator (const Image *)
Function Documentation
CloneImageArtifacts()
MagickExport MagickBooleanType CloneImageArtifacts (Image * , const Image *)
DefineImageArtifact()
MagickExport MagickBooleanType DefineImageArtifact (Image * , const char *)
DeleteImageArtifact()
MagickExport MagickBooleanType DeleteImageArtifact (Image * , const char *)
DestroyImageArtifacts()
MagickExport void DestroyImageArtifacts (Image *)
GetImageArtifact()
MagickExport const char * GetImageArtifact (const Image * image, const char * artifact)
References _Image::artifacts, _Image::debug, _Image::filename, GetMagickModule, GetNextValueInSplayTree(), GetValueFromSplayTree(), LogMagickEvent(), MagickCoreSignature, MagickFalse, ResetSplayTreeIterator(), _Image::signature, and TraceEvent.
Referenced by AcquireResizeFilter(), AddNoiseImageChannel(), AutoThresholdImage(), CloneImages(), CompareImageChannels(), ComplexImages(), CompositeImageChannel(), ConnectedComponentsImage(), DeskewImage(), DistortImage(), DrawClipPath(), DrawPatternPath(), DrawPolygonPrimitive(), FloydSteinbergDither(), FxGetSymbol(), GenerateCoefficients(), GetEdgeBackgroundFactor(), GetEdgeBoundingBox(), GetImageBoundingBox(), GetImageProperty(), GetMagickProperty(), GetMagickPropertyLetter(), GradientImage(), HoughLineImage(), IdentifyImage(), InterpretImageFilename(), InterpretImageProperties(), ModulateImage(), MorphologyApply(), MorphologyImageChannel(), RenderMVGContent(), SampleImage(), SetImageType(), SetResampleFilter(), SimilarityMetricImage(), and SparseColorImage().
GetNextImageArtifact()
MagickExport char * GetNextImageArtifact (const Image *)
RemoveImageArtifact()
MagickExport char * RemoveImageArtifact (Image * image, const char * artifact)
References _Image::artifacts, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, RemoveNodeFromSplayTree(), _Image::signature, and TraceEvent.
ResetImageArtifactIterator()
MagickExport void ResetImageArtifactIterator (const Image * image)
References _Image::artifacts, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, ResetSplayTreeIterator(), _Image::signature, and TraceEvent.
Referenced by IdentifyImage(), and InterpretImageProperties().
SetImageArtifact()
MagickExport MagickBooleanType SetImageArtifact (Image * image, const char * artifact, const char * value)
References AddValueToSplayTree(), _Image::artifacts, CompareSplayTreeString(), ConstantString(), _Image::debug, DeleteImageArtifact(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, NewSplayTree(), RelinquishMagickMemory(), _Image::signature, and TraceEvent.
Referenced by DefineImageArtifact(), DeskewImage(), GetMagickProperty(), GetMagickPropertyLetter(), RenderMVGContent(), SketchImage(), StripImage(), and SyncImageSettings().