MagickCore: attribute.c File Reference
attribute.c File Reference
#include "magick/studio.h"
#include "magick/artifact.h"
#include "magick/attribute.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/cache.h"
#include "magick/cache-private.h"
#include "magick/cache-view.h"
#include "magick/client.h"
#include "magick/channel.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colormap.h"
#include "magick/colormap-private.h"
#include "magick/colorspace.h"
#include "magick/colorspace-private.h"
#include "magick/composite.h"
#include "magick/composite-private.h"
#include "magick/constitute.h"
#include "magick/deprecate.h"
#include "magick/draw.h"
#include "magick/draw-private.h"
#include "magick/effect.h"
#include "magick/enhance.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/geometry.h"
#include "magick/histogram.h"
#include "magick/identify.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/log.h"
#include "magick/memory_.h"
#include "magick/magick.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/option.h"
#include "magick/paint.h"
#include "magick/pixel.h"
#include "magick/pixel-private.h"
#include "magick/property.h"
#include "magick/quantize.h"
#include "magick/random_.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/segment.h"
#include "magick/splay-tree.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/thread-private.h"
#include "magick/threshold.h"
#include "magick/transform.h"
#include "magick/utility.h"
Data Structures
struct _EdgeInfo
Typedefs
typedef struct _EdgeInfo EdgeInfo
Functions
static double GetEdgeBackgroundFactor (const Image *image, const CacheView *image_view, const GravityType gravity, const size_t width, const size_t height, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo *exception)
static double GetMinEdgeBackgroundFactor (const EdgeInfo *edge)
static RectangleInfo GetEdgeBoundingBox (const Image *image, ExceptionInfo *exception)
MagickExport RectangleInfo GetImageBoundingBox (const Image *image, ExceptionInfo *exception)
MagickExport size_t GetImageDepth (const Image *image, ExceptionInfo *exception)
MagickExport size_t GetImageChannelDepth (const Image *image, const ChannelType channel, ExceptionInfo *exception)
MagickExport size_t GetImageQuantumDepth (const Image *image, const MagickBooleanType constrain)
MagickExport ImageType GetImageType (const Image *image, ExceptionInfo *exception)
MagickExport ImageType IdentifyImageGray (const Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType IdentifyImageMonochrome (const Image *image, ExceptionInfo *exception)
MagickExport ImageType IdentifyImageType (const Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType IsGrayImage (const Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType IsMonochromeImage (const Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType IsOpaqueImage (const Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType SetImageDepth (Image *image, const size_t depth)
MagickExport MagickBooleanType SetImageChannelDepth (Image *image, const ChannelType channel, const size_t depth)
MagickExport MagickBooleanType SetImageType (Image *image, const ImageType type)
Typedef Documentation
EdgeInfo
typedef struct _EdgeInfo EdgeInfo
Function Documentation
GetEdgeBackgroundFactor()
static double GetEdgeBackgroundFactor (const Image * image, const CacheView * image_view, const GravityType gravity, const size_t width, const size_t height, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo * exception) static
References AcquireVirtualCacheView(), _Image::columns, CropImage(), DestroyCacheView(), DestroyImage(), EastGravity, GetCacheViewVirtualPixels(), GetImageArtifact(), GetMagickPixelPacket(), GravityAdjustGeometry(), _RectangleInfo::height, IsMagickColorSimilar(), MagickFalse, NorthEastGravity, NorthGravity, NorthWestGravity, QueryMagickColor(), _Image::rows, SetMagickPixelPacket(), SouthEastGravity, SouthGravity, SouthWestGravity, WestGravity, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by GetEdgeBoundingBox().
GetEdgeBoundingBox()
static RectangleInfo GetEdgeBoundingBox (const Image * image, ExceptionInfo * exception) static
References AcquireVirtualCacheView(), _EdgeInfo::bottom, CloneImage(), _Image::debug, DestroyCacheView(), DestroyImage(), EastGravity, _Image::filename, GetEdgeBackgroundFactor(), GetImageArtifact(), GetMagickModule, GetMinEdgeBackgroundFactor(), _RectangleInfo::height, _EdgeInfo::left, LogMagickEvent(), MagickCoreSignature, MagickEpsilon, MagickFalse, MagickMax, MagickMin, MagickTrue, NorthEastGravity, NorthGravity, NorthWestGravity, OptionWarning, _Image::page, ParseAbsoluteGeometry(), _EdgeInfo::right, SetGeometry(), _Image::signature, SouthGravity, SouthWestGravity, StringToDouble(), ThrowMagickException(), _EdgeInfo::top, TraceEvent, WestGravity, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by GetImageBoundingBox().
GetImageBoundingBox()
MagickExport RectangleInfo GetImageBoundingBox (const Image * image, ExceptionInfo * exception)
References AcquireVirtualCacheView(), _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetEdgeBoundingBox(), GetImageArtifact(), GetMagickModule, GetMagickPixelPacket(), _RectangleInfo::height, IsMagickColorSimilar(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, OptionWarning, _Image::rows, SetMagickPixelPacket(), _Image::signature, ThrowMagickException(), TraceEvent, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by DeskewImage(), GetMagickProperty(), GetMagickPropertyLetter(), RenderPostscript(), and TrimImage().
GetImageChannelDepth()
MagickExport size_t GetImageChannelDepth (const Image * image, const ChannelType channel, ExceptionInfo * exception)
References AcquireQuantumMemory(), AcquireVirtualCacheView(), _PixelPacket::blue, BlueChannel, CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DisableMSCWarning, _Image::filename, GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickResourceLimit(), GetOpenMPThreadId(), GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, GetQuantumRange(), _PixelPacket::green, GreenChannel, IndexChannel, IsPixelAtDepth(), LogMagickEvent(), magick_restrict, MAGICKCORE_QUANTUM_DEPTH, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, MaxMap, OpacityChannel, PseudoClass, QuantumRange, _PixelPacket::red, RedChannel, RelinquishMagickMemory(), ResourceLimitFatalError, RestoreMSCWarning, _Image::rows, ScaleAnyToQuantum(), ScaleQuantumToAny(), _Image::signature, _Image::storage_class, ThreadResource, ThrowFatalException, and TraceEvent.
Referenced by FxChannelStatistics(), FxGetSymbol(), and GetImageDepth().
GetImageDepth()
MagickExport size_t GetImageDepth (const Image * image, ExceptionInfo * exception)
References CompositeChannels, and GetImageChannelDepth().
Referenced by GetMagickProperty(), and IdentifyImage().
GetImageQuantumDepth()
MagickExport size_t GetImageQuantumDepth (const Image * image, const MagickBooleanType constrain)
References _Image::depth, MAGICKCORE_QUANTUM_DEPTH, MagickFalse, and MagickMin.
GetImageType()
MagickExport ImageType GetImageType (const Image * image, ExceptionInfo * exception)
References BilevelType, CMYKColorspace, ColorSeparationMatteType, ColorSeparationType, _Image::colorspace, _Image::debug, _Image::filename, GetMagickModule, GrayscaleMatteType, GrayscaleType, IsGrayImage(), IsMonochromeImage(), IsPaletteImage(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::matte, PaletteMatteType, PaletteType, _Image::signature, TraceEvent, TrueColorMatteType, and TrueColorType.
GetMinEdgeBackgroundFactor()
static double GetMinEdgeBackgroundFactor (const EdgeInfo * edge) inline static
References _EdgeInfo::bottom, _EdgeInfo::left, MagickMin, _EdgeInfo::right, and _EdgeInfo::top.
Referenced by GetEdgeBoundingBox().
IdentifyImageGray()
MagickExport ImageType IdentifyImageGray (const Image * image, ExceptionInfo * exception)
References AcquireVirtualCacheView(), BilevelType, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GrayscaleMatteType, GrayscaleType, IsPixelGray(), IsPixelMonochrome(), IssRGBCompatibleColorspace(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::matte, _Image::rows, _Image::signature, TraceEvent, _Image::type, and UndefinedType.
Referenced by IdentifyImageType().
IdentifyImageMonochrome()
MagickExport MagickBooleanType IdentifyImageMonochrome (const Image * image, ExceptionInfo * exception)
References AcquireVirtualCacheView(), BilevelType, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, IsPixelMonochrome(), IssRGBCompatibleColorspace(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::rows, _Image::signature, TraceEvent, _Image::type, and UndefinedType.
Referenced by IdentifyImageType().
IdentifyImageType()
MagickExport ImageType IdentifyImageType (const Image * image, ExceptionInfo * exception)
References BilevelType, CMYKColorspace, ColorSeparationMatteType, ColorSeparationType, _Image::colorspace, _Image::debug, _Image::filename, GetMagickModule, GrayscaleMatteType, GrayscaleType, IdentifyImageGray(), IdentifyImageMonochrome(), IdentifyPaletteImage(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::matte, PaletteMatteType, PaletteType, _Image::signature, TraceEvent, TrueColorMatteType, TrueColorType, and UndefinedType.
Referenced by GetImageColorspaceType(), GetMagickProperty(), and IdentifyImage().
IsGrayImage()
MagickExport MagickBooleanType IsGrayImage (const Image * image, ExceptionInfo * exception)
References BilevelType, GrayscaleMatteType, GrayscaleType, magick_unreferenced, MagickCoreSignature, MagickFalse, MagickTrue, _Image::signature, and _Image::type.
Referenced by ForwardFourierTransformImage(), GetImageType(), and InverseFourierTransformImage().
IsMonochromeImage()
MagickExport MagickBooleanType IsMonochromeImage (const Image * image, ExceptionInfo * exception)
References BilevelType, magick_unreferenced, MagickCoreSignature, MagickFalse, MagickTrue, _Image::signature, and _Image::type.
Referenced by GetImageType().
IsOpaqueImage()
MagickExport MagickBooleanType IsOpaqueImage (const Image * image, ExceptionInfo * exception)
References AcquireVirtualCacheView(), _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelOpacity, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OpaqueOpacity, _Image::rows, _Image::signature, and TraceEvent.
Referenced by GetMagickProperty().
SetImageChannelDepth()
MagickExport MagickBooleanType SetImageChannelDepth (Image * image, const ChannelType channel, const size_t depth)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), _PixelPacket::blue, BlueChannel, ClampPixel(), _Image::colormap, _Image::colors, _Image::columns, _Image::debug, _Image::depth, DestroyCacheView(), DisableMSCWarning, _Image::exception, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelOpacity, GetPixelRed, GetQuantumRange(), _PixelPacket::green, GreenChannel, LogMagickEvent(), magick_restrict, MAGICKCORE_QUANTUM_DEPTH, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, MaxMap, _PixelPacket::opacity, OpacityChannel, PseudoClass, QuantumRange, _PixelPacket::red, RedChannel, RelinquishMagickMemory(), ResourceLimitFatalError, RestoreMSCWarning, _Image::rows, ScaleAnyToQuantum(), ScaleQuantumToAny(), SetPixelBlue, SetPixelGreen, SetPixelOpacity, SetPixelRed, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), ThrowFatalException, and TraceEvent.
Referenced by SetImageDepth().
SetImageDepth()
MagickExport MagickBooleanType SetImageDepth (Image * image, const size_t depth)
References CompositeChannels, and SetImageChannelDepth().
SetImageType()
MagickExport MagickBooleanType SetImageType (Image * image, const ImageType type)
References AcquireImageInfo(), AcquireQuantizeInfo(), AlphaChannel, BilevelImageChannel(), BilevelType, CMYKColorspace, _Image::colors, ColorSeparationMatteType, ColorSeparationType, _QuantizeInfo::colorspace, _Image::debug, DestroyImageInfo(), DestroyQuantizeInfo(), DirectClass, _Image::dither, _ImageInfo::dither, GetImageArtifact(), GetMagickModule, GRAYColorspace, GrayscaleMatteType, GrayscaleType, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, NormalizeImage(), _QuantizeInfo::number_colors, OpaqueAlphaChannel, OptimizeType, PaletteBilevelMatteType, PaletteMatteType, PaletteType, QuantizeImage(), QuantumRange, SetImageAlphaChannel(), SetImageOption(), SetImageStorageClass(), _Image::signature, sRGBColorspace, _Image::storage_class, TraceEvent, TransformImageColorspace(), TransparentColorspace, TrueColorMatteType, TrueColorType, _Image::type, and UndefinedType.
Referenced by CycleColormapImage(), and HuffmanEncodeImage().