MagickCore: attribute.h File Reference
attribute.h File Reference
#include "magick/image.h"
#include "magick/exception.h"
Functions
MagickExport ImageType GetImageType (const Image *, ExceptionInfo *)
MagickExport ImageType IdentifyImageGray (const Image *, ExceptionInfo *)
MagickExport ImageType IdentifyImageType (const Image *, ExceptionInfo *)
MagickExport MagickBooleanType IdentifyImageMonochrome (const Image *, ExceptionInfo *)
MagickExport MagickBooleanType IsGrayImage (const Image *, ExceptionInfo *)
MagickExport MagickBooleanType IsMonochromeImage (const Image *, ExceptionInfo *)
MagickExport MagickBooleanType IsOpaqueImage (const Image *, ExceptionInfo *)
MagickExport MagickBooleanType SetImageChannelDepth (Image *, const ChannelType, const size_t)
MagickExport MagickBooleanType SetImageDepth (Image *, const size_t)
MagickExport MagickBooleanType SetImageType (Image *, const ImageType)
MagickExport RectangleInfo GetImageBoundingBox (const Image *, ExceptionInfo *exception)
MagickExport size_t GetImageChannelDepth (const Image *, const ChannelType, ExceptionInfo *)
MagickExport size_t GetImageDepth (const Image *, ExceptionInfo *)
MagickExport size_t GetImageQuantumDepth (const Image *, const MagickBooleanType)
Function Documentation
GetImageBoundingBox()
MagickExport RectangleInfo GetImageBoundingBox (const Image * image, ExceptionInfo * exception)
References AcquireVirtualCacheView(), _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetEdgeBoundingBox(), GetImageArtifact(), GetMagickModule, GetMagickPixelPacket(), _RectangleInfo::height, IsMagickColorSimilar(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, OptionWarning, _Image::rows, SetMagickPixelPacket(), _Image::signature, ThrowMagickException(), TraceEvent, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by DeskewImage(), GetMagickProperty(), GetMagickPropertyLetter(), RenderPostscript(), and TrimImage().
GetImageChannelDepth()
MagickExport size_t GetImageChannelDepth (const Image * , const ChannelType, ExceptionInfo *)
GetImageDepth()
MagickExport size_t GetImageDepth (const Image * , ExceptionInfo *)
GetImageQuantumDepth()
MagickExport size_t GetImageQuantumDepth (const Image * image, const MagickBooleanType)
References _Image::depth, MAGICKCORE_QUANTUM_DEPTH, MagickFalse, and MagickMin.
GetImageType()
MagickExport ImageType GetImageType (const Image * , ExceptionInfo *)
IdentifyImageGray()
MagickExport ImageType IdentifyImageGray (const Image * , ExceptionInfo *)
IdentifyImageMonochrome()
MagickExport MagickBooleanType IdentifyImageMonochrome (const Image * , ExceptionInfo *)
IdentifyImageType()
MagickExport ImageType IdentifyImageType (const Image * image, ExceptionInfo * exception)
References BilevelType, CMYKColorspace, ColorSeparationMatteType, ColorSeparationType, _Image::colorspace, _Image::debug, _Image::filename, GetMagickModule, GrayscaleMatteType, GrayscaleType, IdentifyImageGray(), IdentifyImageMonochrome(), IdentifyPaletteImage(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::matte, PaletteMatteType, PaletteType, _Image::signature, TraceEvent, TrueColorMatteType, TrueColorType, and UndefinedType.
Referenced by GetImageColorspaceType(), GetMagickProperty(), and IdentifyImage().
IsGrayImage()
MagickExport MagickBooleanType IsGrayImage (const Image * , ExceptionInfo *)
IsMonochromeImage()
MagickExport MagickBooleanType IsMonochromeImage (const Image * , ExceptionInfo *)
IsOpaqueImage()
MagickExport MagickBooleanType IsOpaqueImage (const Image * , ExceptionInfo *)
SetImageChannelDepth()
MagickExport MagickBooleanType SetImageChannelDepth (Image * , const ChannelType, const size_t)
SetImageDepth()
MagickExport MagickBooleanType SetImageDepth (Image * , const size_t)
SetImageType()
MagickExport MagickBooleanType SetImageType (Image * image, const ImageType)
References AcquireImageInfo(), AcquireQuantizeInfo(), AlphaChannel, BilevelImageChannel(), BilevelType, CMYKColorspace, _Image::colors, ColorSeparationMatteType, ColorSeparationType, _QuantizeInfo::colorspace, _Image::debug, DestroyImageInfo(), DestroyQuantizeInfo(), DirectClass, _Image::dither, _ImageInfo::dither, GetImageArtifact(), GetMagickModule, GRAYColorspace, GrayscaleMatteType, GrayscaleType, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, NormalizeImage(), _QuantizeInfo::number_colors, OpaqueAlphaChannel, OptimizeType, PaletteBilevelMatteType, PaletteMatteType, PaletteType, QuantizeImage(), QuantumRange, SetImageAlphaChannel(), SetImageOption(), SetImageStorageClass(), _Image::signature, sRGBColorspace, _Image::storage_class, TraceEvent, TransformImageColorspace(), TransparentColorspace, TrueColorMatteType, TrueColorType, _Image::type, and UndefinedType.
Referenced by CycleColormapImage(), and HuffmanEncodeImage().