MagickCore: blob-private.h File Reference
blob-private.h File Reference
#include "magick/image.h"
#include "magick/stream.h"
#include "magick/nt-base-private.h"
Macros
#define MagickMinBlobExtent 32767L
Typedefs
typedef int *(* BlobFifo) (const Image *, const void *, const size_t)
Enumerations
enum BlobMode {
UndefinedBlobMode , ReadBlobMode , ReadBinaryBlobMode , WriteBlobMode ,
WriteBinaryBlobMode , AppendBlobMode , AppendBinaryBlobMode
}
enum StreamType {
UndefinedStream , FileStream , StandardStream , PipeStream ,
ZipStream , BZipStream , FifoStream , BlobStream
}
Functions
MagickExport BlobInfo * CloneBlobInfo (const BlobInfo *)
MagickExport BlobInfo * ReferenceBlob (BlobInfo *)
MagickExport char * ReadBlobString (Image *, char *)
MagickExport const struct stat * GetBlobProperties (const Image *)
MagickExport const void * ReadBlobStream (Image *, const size_t, void *magick_restrict, ssize_t *) magick_hot_spot
MagickExport double ReadBlobDouble (Image *)
MagickExport float ReadBlobFloat (Image *)
MagickExport int EOFBlob (const Image *)
MagickExport int ErrorBlob (const Image *)
MagickExport int ReadBlobByte (Image *)
MagickExport MagickBooleanType CloseBlob (Image *)
MagickExport MagickBooleanType DiscardBlobBytes (Image *, const MagickSizeType)
MagickExport MagickBooleanType OpenBlob (const ImageInfo *, Image *, const BlobMode, ExceptionInfo *)
MagickExport MagickBooleanType SetBlobExtent (Image *, const MagickSizeType)
MagickExport MagickBooleanType UnmapBlob (void *, const size_t)
MagickExport MagickOffsetType SeekBlob (Image *, const MagickOffsetType, const int)
MagickExport MagickOffsetType TellBlob (const Image *)
MagickExport MagickSizeType ReadBlobLongLong (Image *)
MagickExport MagickSizeType ReadBlobMSBLongLong (Image *)
MagickExport signed int ReadBlobLSBSignedLong (Image *)
MagickExport signed int ReadBlobMSBSignedLong (Image *)
MagickExport signed int ReadBlobSignedLong (Image *)
MagickExport signed short ReadBlobLSBSignedShort (Image *)
MagickExport signed short ReadBlobMSBSignedShort (Image *)
MagickExport signed short ReadBlobSignedShort (Image *)
MagickExport ssize_t ReadBlob (Image *, const size_t, unsigned char *)
MagickExport ssize_t WriteBlob (Image *, const size_t, const unsigned char *)
MagickExport ssize_t WriteBlobByte (Image *, const unsigned char)
MagickExport ssize_t WriteBlobFloat (Image *, const float)
MagickExport ssize_t WriteBlobLong (Image *, const unsigned int)
MagickExport ssize_t WriteBlobShort (Image *, const unsigned short)
MagickExport ssize_t WriteBlobLSBLong (Image *, const unsigned int)
MagickExport ssize_t WriteBlobLSBShort (Image *, const unsigned short)
MagickExport ssize_t WriteBlobLSBSignedLong (Image *, const signed int)
MagickExport ssize_t WriteBlobLSBSignedShort (Image *, const signed short)
MagickExport ssize_t WriteBlobMSBLong (Image *, const unsigned int)
MagickExport ssize_t WriteBlobMSBLongLong (Image *, const MagickSizeType)
MagickExport ssize_t WriteBlobMSBShort (Image *, const unsigned short)
MagickExport ssize_t WriteBlobMSBSignedLong (Image *, const signed int)
MagickExport ssize_t WriteBlobMSBSignedShort (Image *, const signed short)
MagickExport ssize_t WriteBlobString (Image *, const char *)
MagickExport unsigned char * DetachBlob (BlobInfo *)
MagickExport unsigned char * MapBlob (int, const MapMode, const MagickOffsetType, const size_t)
MagickExport unsigned int ReadBlobLong (Image *)
MagickExport unsigned int ReadBlobLSBLong (Image *)
MagickExport unsigned int ReadBlobMSBLong (Image *)
MagickExport unsigned short ReadBlobShort (Image *)
MagickExport unsigned short ReadBlobLSBShort (Image *)
MagickExport unsigned short ReadBlobMSBShort (Image *)
MagickExport void AttachBlob (BlobInfo *, const void *, const size_t)
MagickExport void GetBlobInfo (BlobInfo *)
MagickExport void MSBOrderLong (unsigned char *, const size_t)
MagickExport void MSBOrderShort (unsigned char *, const size_t)
MagickPrivate void DisassociateBlob (Image *)
Macro Definition Documentation
MagickMinBlobExtent
#define MagickMinBlobExtent 32767L
Typedef Documentation
BlobFifo
typedef int *(* BlobFifo) (const Image *, const void *, const size_t)
Enumeration Type Documentation
BlobMode
enum BlobMode
Enumerator
UndefinedBlobMode
ReadBlobMode
ReadBinaryBlobMode
WriteBlobMode
WriteBinaryBlobMode
AppendBlobMode
AppendBinaryBlobMode
StreamType
enum StreamType
Enumerator
UndefinedStream
FileStream
StandardStream
PipeStream
ZipStream
BZipStream
FifoStream
BlobStream
Function Documentation
AttachBlob()
MagickExport void AttachBlob (BlobInfo * , const void * , const size_t)
CloneBlobInfo()
MagickExport BlobInfo * CloneBlobInfo (const BlobInfo *)
Referenced by AcquireImage(), and CloneImage().
CloseBlob()
MagickExport MagickBooleanType CloseBlob (Image *)
Referenced by DestroyStreamInfo(), ReadImage(), RenderHoughLines(), SetImageInfo(), and WriteImage().
DetachBlob()
MagickExport unsigned char * DetachBlob (BlobInfo *)
DisassociateBlob()
MagickPrivate void DisassociateBlob (Image * image)
References _Image::blob, CloneBlobInfo(), _Image::debug, DestroyBlob(), _Image::filename, GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _BlobInfo::signature, _Image::signature, TraceEvent, and UnlockSemaphoreInfo().
Referenced by DisassociateImageStream().
DiscardBlobBytes()
MagickExport MagickBooleanType DiscardBlobBytes (Image * , const MagickSizeType)
EOFBlob()
MagickExport int EOFBlob (const Image *)
ErrorBlob()
MagickExport int ErrorBlob (const Image *)
GetBlobInfo()
MagickExport void GetBlobInfo (BlobInfo *)
GetBlobProperties()
MagickExport const struct stat * GetBlobProperties (const Image * image)
References _Image::blob, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _BlobInfo::properties, _Image::signature, and TraceEvent.
Referenced by ReadImage().
MapBlob()
MagickExport unsigned char * MapBlob (int file, const MapMode, const MagickOffsetType, const size_t)
References IOMode, MAP_FAILED, ReadMode, and WriteMode.
Referenced by AcquireCacheNexusPixels(), AcquireMatrixInfo(), AcquireStreamPixels(), AcquireVirtualMemory(), ConfigureFileToStringInfo(), FileToBlob(), FileToXML(), OpenBlob(), OpenPixelCache(), and SetBlobExtent().
MSBOrderLong()
MagickExport void MSBOrderLong (unsigned char * , const size_t)
MSBOrderShort()
MagickExport void MSBOrderShort (unsigned char * p, const size_t)
OpenBlob()
MagickExport MagickBooleanType OpenBlob (const ImageInfo * , Image * , const BlobMode, ExceptionInfo *)
Referenced by OpenStream(), ReadImage(), RenderHoughLines(), SetImageInfo(), and WriteImage().
ReadBlob()
MagickExport ssize_t ReadBlob (Image * , const size_t, unsigned char *)
Referenced by SetImageInfo().
ReadBlobByte()
MagickExport int ReadBlobByte (Image * image)
References _Image::blob, FileStream, magick_restrict, MagickCoreSignature, PipeStream, ReadBlobStream(), _Image::signature, StandardStream, _BlobInfo::type, and UndefinedStream.
Referenced by ReadBlobString().
ReadBlobDouble()
MagickExport double ReadBlobDouble (Image * image)
References ReadBlobLongLong().
ReadBlobFloat()
MagickExport float ReadBlobFloat (Image * image)
References ReadBlobLong().
ReadBlobLong()
MagickExport unsigned int ReadBlobLong (Image *)
ReadBlobLongLong()
MagickExport MagickSizeType ReadBlobLongLong (Image *)
ReadBlobLSBLong()
MagickExport unsigned int ReadBlobLSBLong (Image *)
ReadBlobLSBShort()
MagickExport unsigned short ReadBlobLSBShort (Image *)
ReadBlobLSBSignedLong()
MagickExport signed int ReadBlobLSBSignedLong (Image *)
ReadBlobLSBSignedShort()
MagickExport signed short ReadBlobLSBSignedShort (Image *)
ReadBlobMSBLong()
MagickExport unsigned int ReadBlobMSBLong (Image * image)
References MagickCoreSignature, ReadBlobStream(), and _Image::signature.
Referenced by ReadBlobMSBSignedLong().
ReadBlobMSBLongLong()
MagickExport MagickSizeType ReadBlobMSBLongLong (Image * image)
References MagickCoreSignature, MagickULLConstant, ReadBlobStream(), and _Image::signature.
ReadBlobMSBShort()
MagickExport unsigned short ReadBlobMSBShort (Image * image)
References MagickCoreSignature, ReadBlobStream(), and _Image::signature.
Referenced by ReadBlobMSBSignedShort().
ReadBlobMSBSignedLong()
MagickExport signed int ReadBlobMSBSignedLong (Image *)
ReadBlobMSBSignedShort()
MagickExport signed short ReadBlobMSBSignedShort (Image *)
ReadBlobShort()
MagickExport unsigned short ReadBlobShort (Image *)
ReadBlobSignedLong()
MagickExport signed int ReadBlobSignedLong (Image * image)
References ReadBlobLong().
ReadBlobSignedShort()
MagickExport signed short ReadBlobSignedShort (Image * image)
References ReadBlobShort().
ReadBlobStream()
MagickExport const void * ReadBlobStream (Image * , const size_t, void * magick_restrict, ssize_t *)
ReadBlobString()
MagickExport char * ReadBlobString (Image * image, char * string)
References MagickCoreSignature, MaxTextExtent, ReadBlobByte(), and _Image::signature.
ReferenceBlob()
MagickExport BlobInfo * ReferenceBlob (BlobInfo * blob)
References _BlobInfo::debug, GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _BlobInfo::reference_count, _BlobInfo::semaphore, _BlobInfo::signature, TraceEvent, and UnlockSemaphoreInfo().
Referenced by AcquireNextImage(), CloneImage(), DuplicateBlob(), and SyncNextImageInList().
SeekBlob()
MagickExport MagickOffsetType SeekBlob (Image * , const MagickOffsetType, const int)
Referenced by SetImageInfo().
SetBlobExtent()
MagickExport MagickBooleanType SetBlobExtent (Image * , const MagickSizeType)
TellBlob()
MagickExport MagickOffsetType TellBlob (const Image * image)
References _Image::blob, BlobStream, BZipStream, _Image::debug, FifoStream, _Image::filename, FileStream, GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, PipeStream, _Image::signature, StandardStream, TraceEvent, _BlobInfo::type, UndefinedStream, and ZipStream.
Referenced by SeekBlob().
UnmapBlob()
MagickExport MagickBooleanType UnmapBlob (void * map, const size_t)
References MagickFalse, and MagickTrue.
Referenced by ConfigureFileToStringInfo(), DestroyBlob(), DestroyMagickMemory(), DestroyMatrixInfo(), DetachBlob(), FileToBlob(), FileToXML(), RelinquishCacheNexusPixels(), RelinquishPixelCachePixels(), RelinquishStreamPixels(), RelinquishVirtualMemory(), and SetBlobExtent().
WriteBlob()
MagickExport ssize_t WriteBlob (Image * , const size_t, const unsigned char *)
Referenced by Ascii85Flush(), and WriteStreamImage().
WriteBlobByte()
MagickExport ssize_t WriteBlobByte (Image * , const unsigned char)
Referenced by Ascii85Encode(), Ascii85Flush(), HuffmanEncodeImage(), LZWEncodeImage(), and PackbitsEncodeImage().
WriteBlobFloat()
MagickExport ssize_t WriteBlobFloat (Image * , const float)
WriteBlobLong()
MagickExport ssize_t WriteBlobLong (Image * , const unsigned int)
WriteBlobLSBLong()
MagickExport ssize_t WriteBlobLSBLong (Image * , const unsigned int)
WriteBlobLSBShort()
MagickExport ssize_t WriteBlobLSBShort (Image * , const unsigned short)
WriteBlobLSBSignedLong()
MagickExport ssize_t WriteBlobLSBSignedLong (Image * , const signed int)
WriteBlobLSBSignedShort()
MagickExport ssize_t WriteBlobLSBSignedShort (Image * , const signed short)
WriteBlobMSBLong()
MagickExport ssize_t WriteBlobMSBLong (Image * , const unsigned int)
WriteBlobMSBLongLong()
MagickExport ssize_t WriteBlobMSBLongLong (Image * , const MagickSizeType)
WriteBlobMSBShort()
MagickExport ssize_t WriteBlobMSBShort (Image * , const unsigned short)
WriteBlobMSBSignedLong()
MagickExport ssize_t WriteBlobMSBSignedLong (Image * , const signed int)
WriteBlobMSBSignedShort()
MagickExport ssize_t WriteBlobMSBSignedShort (Image * , const signed short)
WriteBlobShort()
MagickExport ssize_t WriteBlobShort (Image * , const unsigned short)
WriteBlobString()
MagickExport ssize_t WriteBlobString (Image * image, const char * string)
References MagickCoreSignature, _Image::signature, and WriteBlobStream().