MagickCore: blob.c File Reference
blob.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/cache.h"
#include "magick/client.h"
#include "magick/constitute.h"
#include "magick/delegate.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/geometry.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/locale_.h"
#include "magick/log.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/nt-base-private.h"
#include "magick/option.h"
#include "magick/policy.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/timer-private.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/utility-private.h"
Data Structures
union FileInfo
struct _BlobInfo
Macros
#define MagickMaxBlobExtent 65541
#define MAP_FAILED ((void *) -1)
Typedefs
typedef union FileInfo FileInfo
Functions
static int SyncBlob (Image *)
MagickExport void AttachBlob (BlobInfo *blob_info, const void *blob, const size_t length)
MagickExport MagickBooleanType BlobToFile (char *filename, const void *blob, const size_t length, ExceptionInfo *exception)
MagickExport Image * BlobToImage (const ImageInfo *image_info, const void *blob, const size_t length, ExceptionInfo *exception)
MagickExport BlobInfo * CloneBlobInfo (const BlobInfo *blob_info)
static void ThrowBlobException (BlobInfo *blob_info)
MagickExport MagickBooleanType CloseBlob (Image *image)
MagickExport void DestroyBlob (Image *image)
MagickExport unsigned char * DetachBlob (BlobInfo *blob_info)
MagickPrivate void DisassociateBlob (Image *image)
MagickExport MagickBooleanType DiscardBlobBytes (Image *image, const MagickSizeType length)
MagickExport void DuplicateBlob (Image *image, const Image *duplicate)
MagickExport int EOFBlob (const Image *image)
MagickExport int ErrorBlob (const Image *image)
MagickExport unsigned char * FileToBlob (const char *filename, const size_t extent, size_t *length, ExceptionInfo *exception)
static ssize_t WriteBlobStream (Image *image, const size_t length, const unsigned char *magick_restrict data)
MagickExport MagickBooleanType FileToImage (Image *image, const char *filename)
MagickExport MagickBooleanType GetBlobError (const Image *image)
MagickExport FILE * GetBlobFileHandle (const Image *image)
MagickExport void GetBlobInfo (BlobInfo *blob_info)
MagickExport const struct stat * GetBlobProperties (const Image *image)
MagickExport MagickSizeType GetBlobSize (const Image *image)
MagickExport unsigned char * GetBlobStreamData (const Image *image)
MagickExport StreamHandler GetBlobStreamHandler (const Image *image)
MagickExport unsigned char * ImageToBlob (const ImageInfo *image_info, Image *image, size_t *length, ExceptionInfo *exception)
MagickExport MagickBooleanType ImageToFile (Image *image, char *filename, ExceptionInfo *exception)
MagickExport unsigned char * ImagesToBlob (const ImageInfo *image_info, Image *images, size_t *length, ExceptionInfo *exception)
MagickExport MagickBooleanType InjectImageBlob (const ImageInfo *image_info, Image *image, Image *inject_image, const char *format, ExceptionInfo *exception)
MagickExport MagickBooleanType IsBlobExempt (const Image *image)
MagickExport MagickBooleanType IsBlobSeekable (const Image *image)
MagickExport MagickBooleanType IsBlobTemporary (const Image *image)
MagickExport unsigned char * MapBlob (int file, const MapMode mode, const MagickOffsetType offset, const size_t length)
MagickExport void MSBOrderLong (unsigned char *buffer, const size_t length)
MagickExport void MSBOrderShort (unsigned char *p, const size_t length)
static MagickBooleanType SetStreamBuffering (const ImageInfo *image_info, Image *image)
MagickExport MagickBooleanType OpenBlob (const ImageInfo *image_info, Image *image, const BlobMode mode, ExceptionInfo *exception)
static size_t PingStream (const Image *magick_unused(image), const void *magick_unused(pixels), const size_t columns)
MagickExport Image * PingBlob (const ImageInfo *image_info, const void *blob, const size_t length, ExceptionInfo *exception)
MagickExport ssize_t ReadBlob (Image *image, const size_t length, unsigned char *data)
MagickExport int ReadBlobByte (Image *image)
MagickExport double ReadBlobDouble (Image *image)
MagickExport float ReadBlobFloat (Image *image)
MagickExport unsigned int ReadBlobLong (Image *image)
MagickExport MagickSizeType ReadBlobLongLong (Image *image)
MagickExport unsigned short ReadBlobShort (Image *image)
MagickExport unsigned int ReadBlobLSBLong (Image *image)
MagickExport signed int ReadBlobLSBSignedLong (Image *image)
MagickExport unsigned short ReadBlobLSBShort (Image *image)
MagickExport signed short ReadBlobLSBSignedShort (Image *image)
MagickExport unsigned int ReadBlobMSBLong (Image *image)
MagickExport MagickSizeType ReadBlobMSBLongLong (Image *image)
MagickExport unsigned short ReadBlobMSBShort (Image *image)
MagickExport signed int ReadBlobMSBSignedLong (Image *image)
MagickExport signed short ReadBlobMSBSignedShort (Image *image)
MagickExport signed int ReadBlobSignedLong (Image *image)
MagickExport signed short ReadBlobSignedShort (Image *image)
MagickExport magick_hot_spot const void * ReadBlobStream (Image *image, const size_t length, void *magick_restrict data, ssize_t *count)
MagickExport char * ReadBlobString (Image *image, char *string)
MagickExport BlobInfo * ReferenceBlob (BlobInfo *blob)
MagickExport MagickOffsetType SeekBlob (Image *image, const MagickOffsetType offset, const int whence)
MagickExport void SetBlobExempt (Image *image, const MagickBooleanType exempt)
MagickExport MagickBooleanType SetBlobExtent (Image *image, const MagickSizeType extent)
MagickExport MagickOffsetType TellBlob (const Image *image)
MagickExport MagickBooleanType UnmapBlob (void *map, const size_t length)
MagickExport ssize_t WriteBlob (Image *image, const size_t length, const unsigned char *data)
MagickExport ssize_t WriteBlobByte (Image *image, const unsigned char value)
MagickExport ssize_t WriteBlobFloat (Image *image, const float value)
MagickExport ssize_t WriteBlobLong (Image *image, const unsigned int value)
MagickExport ssize_t WriteBlobShort (Image *image, const unsigned short value)
MagickExport ssize_t WriteBlobLSBLong (Image *image, const unsigned int value)
MagickExport ssize_t WriteBlobLSBShort (Image *image, const unsigned short value)
MagickExport ssize_t WriteBlobLSBSignedLong (Image *image, const signed int value)
MagickExport ssize_t WriteBlobLSBSignedShort (Image *image, const signed short value)
MagickExport ssize_t WriteBlobMSBLong (Image *image, const unsigned int value)
MagickExport ssize_t WriteBlobMSBLongLong (Image *image, const MagickSizeType value)
MagickExport ssize_t WriteBlobMSBShort (Image *image, const unsigned short value)
MagickExport ssize_t WriteBlobMSBSignedLong (Image *image, const signed int value)
MagickExport ssize_t WriteBlobMSBSignedShort (Image *image, const signed short value)
MagickExport ssize_t WriteBlobString (Image *image, const char *string)
Macro Definition Documentation
MagickMaxBlobExtent
#define MagickMaxBlobExtent 65541
MAP_FAILED
#define MAP_FAILED ((void *) -1)
Typedef Documentation
FileInfo
typedef union FileInfo FileInfo
Function Documentation
AttachBlob()
MagickExport void AttachBlob (BlobInfo * blob_info, const void * blob, const size_t length)
References BlobStream, _BlobInfo::data, _BlobInfo::debug, _BlobInfo::extent, FileInfo::file, _BlobInfo::file_info, GetMagickModule, _BlobInfo::length, LogMagickEvent(), MagickFalse, MagickMaxBlobExtent, _BlobInfo::mapped, _BlobInfo::offset, _BlobInfo::quantum, TraceEvent, and _BlobInfo::type.
Referenced by OpenBlob().
BlobToFile()
MagickExport MagickBooleanType BlobToFile (char * filename, const void * blob, const size_t length, ExceptionInfo * exception)
References AcquireUniqueFileResource(), BlobError, GetMagickModule, LogMagickEvent(), MAGICK_SSIZE_MAX, MagickFalse, MagickMin, MagickTrue, O_BINARY, open_utf8(), S_MODE, ThrowFileException, and TraceEvent.
Referenced by BlobToImage(), and PingBlob().
BlobToImage()
MagickExport Image * BlobToImage (const ImageInfo * image_info, const void * blob, const size_t length, ExceptionInfo * exception)
References _Image::blob, _ImageInfo::blob, BlobError, BlobToFile(), CloneImageInfo(), CopyMagickString(), _ImageInfo::debug, DestroyImageInfo(), DetachBlob(), _Image::filename, _ImageInfo::filename, FormatLocaleString(), GetFirstImageInList(), GetMagickBlobSupport(), GetMagickInfo(), GetMagickModule, GetNextImageInList(), _ImageInfo::length, LogMagickEvent(), _Image::magick, _ImageInfo::magick, _Image::magick_filename, MagickCoreSignature, MagickFalse, MagickPathExtent, MaxTextExtent, MissingDelegateError, _MagickInfo::name, ReadImage(), RelinquishUniqueFileResource(), SetImageInfo(), _ImageInfo::signature, ThrowMagickException(), and TraceEvent.
Referenced by ClipImagePath(), and ReadInlineImage().
CloneBlobInfo()
MagickExport BlobInfo * CloneBlobInfo (const BlobInfo * blob_info)
References AcquireMagickMemory(), AcquireMagickResource(), GetBlobInfo(), _BlobInfo::length, LockSemaphoreInfo(), MagickFalse, _BlobInfo::mapped, MapResource, _BlobInfo::reference_count, _BlobInfo::semaphore, and UnlockSemaphoreInfo().
Referenced by DisassociateBlob(), and InjectImageBlob().
CloseBlob()
MagickExport MagickBooleanType CloseBlob (Image * image)
References _Image::blob, BlobStream, BZipStream, _Image::debug, DetachBlob(), _Image::extent, FifoStream, _Image::filename, FileStream, GetBlobSize(), GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, PipeStream, _Image::signature, StandardStream, SyncBlob(), ThrowBlobException(), TraceEvent, UndefinedStream, and ZipStream.
Referenced by DestroyBlob(), ImagesToBlob(), and ImageToBlob().
DestroyBlob()
MagickExport void DestroyBlob (Image * image)
References _Image::blob, CloseBlob(), _Image::debug, DestroySemaphoreInfo(), _Image::filename, GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, MapResource, RelinquishMagickMemory(), RelinquishMagickResource(), _BlobInfo::signature, _Image::signature, TraceEvent, UnlockSemaphoreInfo(), and UnmapBlob().
Referenced by AcquireNextImage(), DestroyImage(), DisassociateBlob(), DuplicateBlob(), InjectImageBlob(), and SyncNextImageInList().
DetachBlob()
MagickExport unsigned char * DetachBlob (BlobInfo * blob_info)
References _BlobInfo::data, _BlobInfo::debug, _BlobInfo::eof, _BlobInfo::error, _BlobInfo::exempt, FileInfo::file, _BlobInfo::file_info, GetMagickModule, _BlobInfo::length, LogMagickEvent(), MagickFalse, _BlobInfo::mapped, MapResource, _BlobInfo::offset, RelinquishMagickResource(), _BlobInfo::stream, TraceEvent, _BlobInfo::type, UndefinedStream, and UnmapBlob().
Referenced by BlobToImage(), CloseBlob(), ImagesToBlob(), ImageToBlob(), OpenBlob(), PingBlob(), SetBlobExtent(), and WriteBlob().
DisassociateBlob()
MagickPrivate void DisassociateBlob (Image * image)
References _Image::blob, CloneBlobInfo(), _Image::debug, DestroyBlob(), _Image::filename, GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _BlobInfo::signature, _Image::signature, TraceEvent, and UnlockSemaphoreInfo().
Referenced by DisassociateImageStream().
DiscardBlobBytes()
MagickExport MagickBooleanType DiscardBlobBytes (Image * image, const MagickSizeType length)
References MagickCoreSignature, MagickFalse, MagickMin, MagickMinBufferExtent, MagickTrue, ReadBlobStream(), and _Image::signature.
DuplicateBlob()
MagickExport void DuplicateBlob (Image * image, const Image * duplicate)
References _Image::blob, _Image::debug, DestroyBlob(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, ReferenceBlob(), _Image::signature, and TraceEvent.
EOFBlob()
MagickExport int EOFBlob (const Image * image)
References _Image::blob, BlobStream, BZipStream, _Image::debug, FifoStream, FileStream, GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, PipeStream, _Image::signature, StandardStream, TraceEvent, _BlobInfo::type, UndefinedStream, and ZipStream.
ErrorBlob()
MagickExport int ErrorBlob (const Image * image)
References _Image::blob, BlobStream, BZipStream, _Image::debug, FifoStream, FileStream, GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, PipeStream, _Image::signature, StandardStream, TraceEvent, _BlobInfo::type, UndefinedStream, and ZipStream.
FileToBlob()
MagickExport unsigned char * FileToBlob (const char * filename, const size_t extent, size_t * length, ExceptionInfo * exception)
References AcquireQuantumMemory(), BlobError, GetMagickModule, GetPathAttributes(), IsRightsAuthorized(), LocaleCompare(), LogMagickEvent(), MAGICK_SSIZE_MAX, MagickFalse, MagickMaxBufferExtent, MagickMin, MapBlob(), MaxTextExtent, O_BINARY, open_utf8(), PathPolicyDomain, PolicyError, ReadMode, ReadPolicyRights, RelinquishMagickMemory(), ResizeQuantumMemory(), ResourceLimitError, S_ISDIR, ThrowFileException, ThrowMagickException(), TraceEvent, and UnmapBlob().
Referenced by FileToString(), FileToStringInfo(), GetConfigureBlob(), ImagesToBlob(), and ImageToBlob().
FileToImage()
MagickExport MagickBooleanType FileToImage (Image * image, const char * filename)
References AcquireQuantumMemory(), BlobError, _Image::exception, GetMagickModule, IsRightsAuthorized(), LocaleCompare(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickMaxBufferExtent, MagickMin, MagickTrue, O_BINARY, open_utf8(), PathPolicyDomain, PolicyError, RelinquishMagickMemory(), ResourceLimitError, _Image::signature, ThrowFileException, ThrowMagickException(), TraceEvent, WriteBlobStream(), and WritePolicyRights.
GetBlobError()
MagickExport MagickBooleanType GetBlobError (const Image * image)
References _Image::blob, _Image::debug, _BlobInfo::error_number, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, _BlobInfo::status, and TraceEvent.
Referenced by ReadImage(), and WriteImage().
GetBlobFileHandle()
MagickExport FILE * GetBlobFileHandle (const Image * image)
References _Image::blob, FileInfo::file, _BlobInfo::file_info, MagickCoreSignature, and _Image::signature.
GetBlobInfo()
MagickExport void GetBlobInfo (BlobInfo * blob_info)
References AllocateSemaphoreInfo(), _BlobInfo::debug, GetMagickTime(), IsEventLogging(), MagickCoreSignature, MagickMaxBlobExtent, _BlobInfo::properties, _BlobInfo::quantum, _BlobInfo::reference_count, _BlobInfo::semaphore, _BlobInfo::signature, _BlobInfo::type, and UndefinedStream.
Referenced by CloneBlobInfo().
GetBlobProperties()
MagickExport const struct stat * GetBlobProperties (const Image * image)
References _Image::blob, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _BlobInfo::properties, _Image::signature, and TraceEvent.
Referenced by ReadImage().
GetBlobSize()
MagickExport MagickSizeType GetBlobSize (const Image * image)
References _Image::blob, BlobStream, BZipStream, _Image::debug, FifoStream, _Image::filename, FileStream, GetMagickModule, GetPathAttributes(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, PipeStream, _Image::signature, StandardStream, TraceEvent, UndefinedStream, and ZipStream.
Referenced by CloseBlob(), FxGetSymbol(), GetMagickProperty(), GetMagickPropertyLetter(), OpenBlob(), PreviewImage(), RenderHoughLines(), SizeBlob(), and ThumbnailImage().
GetBlobStreamData()
MagickExport unsigned char * GetBlobStreamData (const Image * image)
References _Image::blob, _BlobInfo::data, MagickCoreSignature, and _Image::signature.
Referenced by RenderHoughLines().
GetBlobStreamHandler()
MagickExport StreamHandler GetBlobStreamHandler (const Image * image)
References _Image::blob, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, _BlobInfo::stream, and TraceEvent.
Referenced by QueueAuthenticPixelsStream(), and SyncAuthenticPixelsStream().
ImagesToBlob()
MagickExport unsigned char * ImagesToBlob (const ImageInfo * image_info, Image * images, size_t * length, ExceptionInfo * exception)
References AcquireQuantumMemory(), AcquireUniqueFileResource(), _Image::blob, _ImageInfo::blob, CloneImageInfo(), CloseBlob(), CopyMagickString(), _ImageInfo::debug, DestroyImageInfo(), DetachBlob(), _Image::exception, _BlobInfo::exempt, _ImageInfo::file, _Image::filename, _ImageInfo::filename, FileOpenError, FileToBlob(), FormatLocaleString(), GetImageListLength(), GetMagickAdjoin(), GetMagickBlobSupport(), GetMagickInfo(), GetMagickModule, ImageToBlob(), InheritException(), _BlobInfo::length, _ImageInfo::length, LogMagickEvent(), _Image::magick, _ImageInfo::magick, MagickCoreSignature, MagickFalse, MagickMaxBlobExtent, MagickTrue, MaxTextExtent, MissingDelegateError, RelinquishMagickMemory(), RelinquishUniqueFileResource(), ResizeQuantumMemory(), ResourceLimitError, SetImageInfo(), _Image::signature, _ImageInfo::signature, ThrowFileException, ThrowMagickException(), TraceEvent, and WriteImages().
ImageToBlob()
MagickExport unsigned char * ImageToBlob (const ImageInfo * image_info, Image * image, size_t * length, ExceptionInfo * exception)
References AcquireQuantumMemory(), AcquireUniqueFileResource(), _ImageInfo::adjoin, _Image::blob, _ImageInfo::blob, BlobError, CloneImageInfo(), CloseBlob(), CopyMagickString(), _ImageInfo::debug, DestroyImageInfo(), DetachBlob(), _Image::exception, _BlobInfo::exempt, _ImageInfo::file, _Image::filename, _ImageInfo::filename, FileToBlob(), FormatLocaleString(), GetMagickBlobSupport(), GetMagickInfo(), GetMagickModule, InheritException(), _BlobInfo::length, _ImageInfo::length, LogMagickEvent(), _Image::magick, _ImageInfo::magick, MagickCoreSignature, MagickFalse, MagickMaxBlobExtent, MagickTrue, MaxTextExtent, MissingDelegateError, RelinquishMagickMemory(), RelinquishUniqueFileResource(), ResizeQuantumMemory(), ResourceLimitError, SetImageInfo(), _Image::signature, _ImageInfo::signature, ThrowFileException, ThrowMagickException(), TraceEvent, and WriteImage().
Referenced by ImagesToBlob().
ImageToFile()
MagickExport MagickBooleanType ImageToFile (Image * image, char * filename, ExceptionInfo * exception)
References AcquireQuantumMemory(), AcquireUniqueFileResource(), _Image::blob, BlobError, _Image::debug, GetMagickModule, LocaleCompare(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickMaxBufferExtent, MagickMin, MagickTrue, O_BINARY, open_utf8(), ReadBlobStream(), RelinquishMagickMemory(), ResourceLimitError, S_MODE, _Image::signature, ThrowFileException, ThrowMagickException(), TraceEvent, _BlobInfo::type, and UndefinedStream.
Referenced by ReadImage(), SetImageInfo(), and WriteImage().
InjectImageBlob()
MagickExport MagickBooleanType InjectImageBlob (const ImageInfo * image_info, Image * image, Image * inject_image, const char * format, ExceptionInfo * exception)
References AcquireQuantumMemory(), AcquireUniqueFileResource(), _Image::blob, CloneBlobInfo(), CloneImage(), CloneImageInfo(), CopyMagickString(), _Image::debug, DestroyBlob(), DestroyImage(), DestroyImageInfo(), _Image::filename, _ImageInfo::filename, FileOpenError, FormatLocaleString(), GetMagickModule, LogMagickEvent(), _ImageInfo::magick, MagickCoreSignature, MagickFalse, MagickMaxBufferExtent, MagickMin, MagickTrue, MaxTextExtent, O_BINARY, open_utf8(), RelinquishMagickMemory(), RelinquishUniqueFileResource(), ResourceLimitError, SetImageInfoFile(), _Image::signature, _ImageInfo::signature, ThrowBinaryException, ThrowFileException, TraceEvent, WriteBlobStream(), and WriteImage().
IsBlobExempt()
MagickExport MagickBooleanType IsBlobExempt (const Image * image)
References _Image::blob, _Image::debug, _BlobInfo::exempt, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
Referenced by SetImageInfo().
IsBlobSeekable()
MagickExport MagickBooleanType IsBlobSeekable (const Image * image)
References _Image::blob, BlobStream, BZipStream, _Image::debug, FifoStream, _Image::filename, FileStream, GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, PipeStream, _Image::signature, StandardStream, TraceEvent, UndefinedStream, and ZipStream.
Referenced by ReadImage(), SetImageInfo(), and WriteImage().
IsBlobTemporary()
MagickExport MagickBooleanType IsBlobTemporary (const Image * image)
References _Image::blob, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, _BlobInfo::temporary, and TraceEvent.
Referenced by ReadImage().
MapBlob()
MagickExport unsigned char * MapBlob (int file, const MapMode mode, const MagickOffsetType offset, const size_t length)
References IOMode, MAP_FAILED, ReadMode, and WriteMode.
Referenced by AcquireCacheNexusPixels(), AcquireMatrixInfo(), AcquireStreamPixels(), AcquireVirtualMemory(), ConfigureFileToStringInfo(), FileToBlob(), FileToXML(), OpenBlob(), OpenPixelCache(), and SetBlobExtent().
MSBOrderLong()
MagickExport void MSBOrderLong (unsigned char * buffer, const size_t length)
MSBOrderShort()
MagickExport void MSBOrderShort (unsigned char * p, const size_t length)
OpenBlob()
MagickExport MagickBooleanType OpenBlob (const ImageInfo * image_info, Image * image, const BlobMode mode, ExceptionInfo * exception)
References AcquireExceptionInfo(), AcquireMagickResource(), _ImageInfo::adjoin, AppendBinaryBlobMode, AppendBlobMode, AttachBlob(), _Image::blob, _ImageInfo::blob, BlobError, BlobEvent, BZipStream, CopyMagickString(), _ImageInfo::debug, DestroyExceptionInfo(), DestroyString(), DetachBlob(), ExtensionPath, FifoStream, _ImageInfo::file, _Image::filename, _ImageInfo::filename, FileStream, fopen_utf8(), FormatLocaleString(), GetBlobSize(), GetMagickBlobSupport(), GetMagickInfo(), GetMagickModule, GetNextImageInList(), GetPathAttributes(), GetPathComponent(), GetPreviousImageInList(), InterpretImageFilename(), IsGeometry(), IsRightsAuthorized(), _ImageInfo::length, LocaleCompare(), LocaleNCompare(), LogMagickEvent(), _ImageInfo::magick, magick_restrict, MagickCoreSignature, MagickFalse, MagickMaxBufferExtent, MagickTrue, MapBlob(), MapResource, MaxTextExtent, PathPolicyDomain, PipeStream, PolicyError, popen_utf8(), ReadBinaryBlobMode, ReadBlobMode, ReadMode, ReadPolicyRights, RelinquishMagickResource(), RootPath, SanitizeString(), _Image::scene, SetApplicationType(), SetStreamBuffering(), _Image::signature, _ImageInfo::signature, StandardStream, _BlobInfo::stream, _ImageInfo::stream, StringToLong(), _ImageInfo::synchronize, ThrowFileException, ThrowMagickException(), TraceEvent, UndefinedStream, WriteBinaryBlobMode, WriteBlobMode, WritePolicyRights, and ZipStream.
PingBlob()
MagickExport Image * PingBlob (const ImageInfo * image_info, const void * blob, const size_t length, ExceptionInfo * exception)
References _Image::blob, _ImageInfo::blob, BlobError, BlobToFile(), CloneImageInfo(), CopyMagickString(), _ImageInfo::debug, DestroyImageInfo(), DetachBlob(), _Image::filename, _ImageInfo::filename, FormatLocaleString(), GetFirstImageInList(), GetMagickBlobSupport(), GetMagickInfo(), GetMagickModule, GetNextImageInList(), _ImageInfo::length, LogMagickEvent(), _Image::magick, _ImageInfo::magick, _Image::magick_filename, MagickCoreSignature, MagickFalse, MagickPathExtent, MagickTrue, MaxTextExtent, MissingDelegateError, _MagickInfo::name, _ImageInfo::ping, PingStream(), ReadStream(), RelinquishUniqueFileResource(), SetImageInfo(), _ImageInfo::signature, ThrowMagickException(), and TraceEvent.
PingStream()
static size_t PingStream (const Image * magick_unusedimage, const void * magick_unusedpixels, const size_t columns) static
References magick_unreferenced.
Referenced by PingBlob().
ReadBlob()
MagickExport ssize_t ReadBlob (Image * image, const size_t length, unsigned char * data)
References _Image::blob, BlobStream, BZipStream, FifoStream, FileStream, magick_restrict, MagickCoreSignature, MagickFalse, MagickMaxBufferExtent, MagickMin, MagickTrue, PipeStream, _Image::signature, StandardStream, ThrowBlobException(), _BlobInfo::type, UndefinedStream, and ZipStream.
Referenced by ReadBlobStream().
ReadBlobByte()
MagickExport int ReadBlobByte (Image * image)
References _Image::blob, FileStream, magick_restrict, MagickCoreSignature, PipeStream, ReadBlobStream(), _Image::signature, StandardStream, _BlobInfo::type, and UndefinedStream.
Referenced by ReadBlobString().
ReadBlobDouble()
MagickExport double ReadBlobDouble (Image * image)
References ReadBlobLongLong().
ReadBlobFloat()
MagickExport float ReadBlobFloat (Image * image)
References ReadBlobLong().
ReadBlobLong()
MagickExport unsigned int ReadBlobLong (Image * image)
References _Image::endian, LSBEndian, MagickCoreSignature, ReadBlobStream(), and _Image::signature.
Referenced by ReadBlobFloat(), and ReadBlobSignedLong().
ReadBlobLongLong()
MagickExport MagickSizeType ReadBlobLongLong (Image * image)
References _Image::endian, LSBEndian, MagickCoreSignature, MagickULLConstant, ReadBlobStream(), and _Image::signature.
Referenced by ReadBlobDouble().
ReadBlobLSBLong()
MagickExport unsigned int ReadBlobLSBLong (Image * image)
References MagickCoreSignature, ReadBlobStream(), and _Image::signature.
Referenced by ReadBlobLSBSignedLong().
ReadBlobLSBShort()
MagickExport unsigned short ReadBlobLSBShort (Image * image)
References MagickCoreSignature, ReadBlobStream(), and _Image::signature.
Referenced by ReadBlobLSBSignedShort().
ReadBlobLSBSignedLong()
MagickExport signed int ReadBlobLSBSignedLong (Image * image)
References ReadBlobLSBLong().
ReadBlobLSBSignedShort()
MagickExport signed short ReadBlobLSBSignedShort (Image * image)
References ReadBlobLSBShort().
ReadBlobMSBLong()
MagickExport unsigned int ReadBlobMSBLong (Image * image)
References MagickCoreSignature, ReadBlobStream(), and _Image::signature.
Referenced by ReadBlobMSBSignedLong().
ReadBlobMSBLongLong()
MagickExport MagickSizeType ReadBlobMSBLongLong (Image * image)
References MagickCoreSignature, MagickULLConstant, ReadBlobStream(), and _Image::signature.
ReadBlobMSBShort()
MagickExport unsigned short ReadBlobMSBShort (Image * image)
References MagickCoreSignature, ReadBlobStream(), and _Image::signature.
Referenced by ReadBlobMSBSignedShort().
ReadBlobMSBSignedLong()
MagickExport signed int ReadBlobMSBSignedLong (Image * image)
References ReadBlobMSBLong().
ReadBlobMSBSignedShort()
MagickExport signed short ReadBlobMSBSignedShort (Image * image)
References ReadBlobMSBShort().
ReadBlobShort()
MagickExport unsigned short ReadBlobShort (Image * image)
References _Image::endian, LSBEndian, MagickCoreSignature, ReadBlobStream(), and _Image::signature.
Referenced by ReadBlobSignedShort().
ReadBlobSignedLong()
MagickExport signed int ReadBlobSignedLong (Image * image)
References ReadBlobLong().
ReadBlobSignedShort()
MagickExport signed short ReadBlobSignedShort (Image * image)
References ReadBlobShort().
ReadBlobStream()
MagickExport magick_hot_spot const void * ReadBlobStream (Image * image, const size_t length, void *magick_restrict data, ssize_t * count)
References _Image::blob, BlobStream, magick_restrict, MagickCoreSignature, MagickMin, MagickTrue, ReadBlob(), _Image::signature, _BlobInfo::type, and UndefinedStream.
Referenced by DiscardBlobBytes(), ImageToFile(), ReadBlobByte(), ReadBlobLong(), ReadBlobLongLong(), ReadBlobLSBLong(), ReadBlobLSBShort(), ReadBlobMSBLong(), ReadBlobMSBLongLong(), ReadBlobMSBShort(), and ReadBlobShort().
ReadBlobString()
MagickExport char * ReadBlobString (Image * image, char * string)
References MagickCoreSignature, MaxTextExtent, ReadBlobByte(), and _Image::signature.
ReferenceBlob()
MagickExport BlobInfo * ReferenceBlob (BlobInfo * blob)
References _BlobInfo::debug, GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _BlobInfo::reference_count, _BlobInfo::semaphore, _BlobInfo::signature, TraceEvent, and UnlockSemaphoreInfo().
Referenced by AcquireNextImage(), CloneImage(), DuplicateBlob(), and SyncNextImageInList().
SeekBlob()
MagickExport MagickOffsetType SeekBlob (Image * image, const MagickOffsetType offset, const int whence)
References _Image::blob, BlobStream, BZipStream, _Image::debug, FifoStream, _Image::filename, FileStream, GetMagickModule, LogMagickEvent(), magick_restrict, MAGICK_SSIZE_MAX, MAGICK_SSIZE_MIN, MagickCoreSignature, MagickFalse, PipeStream, _Image::signature, StandardStream, TellBlob(), TraceEvent, _BlobInfo::type, UndefinedStream, and ZipStream.
Referenced by SetBlobExtent().
SetBlobExempt()
MagickExport void SetBlobExempt (Image * image, const MagickBooleanType exempt)
References _Image::blob, _Image::debug, _BlobInfo::exempt, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
Referenced by AcquireImage().
SetBlobExtent()
MagickExport MagickBooleanType SetBlobExtent (Image * image, const MagickSizeType extent)
References AcquireMagickResource(), _Image::blob, BlobStream, BZipStream, _Image::debug, DetachBlob(), FifoStream, _Image::filename, FileStream, GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, MapBlob(), MapResource, PipeStream, RelinquishMagickResource(), ResizeQuantumMemory(), SeekBlob(), _Image::signature, StandardStream, SyncBlob(), TraceEvent, _BlobInfo::type, UndefinedStream, UnmapBlob(), WriteMode, and ZipStream.
Referenced by WriteBlobStream().
SetStreamBuffering()
static MagickBooleanType SetStreamBuffering (const ImageInfo * image_info, Image * image) inline static
References _Image::blob, FileInfo::file, _BlobInfo::file_info, GetImageOption(), MagickFalse, MagickMinBufferExtent, MagickTrue, and StringToUnsignedLong().
Referenced by OpenBlob().
SyncBlob()
static int SyncBlob (Image * image) static
References _Image::blob, BlobStream, BZipStream, _Image::debug, FifoStream, _Image::filename, FileStream, GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, PipeStream, _Image::signature, StandardStream, TraceEvent, _BlobInfo::type, UndefinedStream, and ZipStream.
Referenced by CloseBlob(), SetBlobExtent(), and WriteBlob().
TellBlob()
MagickExport MagickOffsetType TellBlob (const Image * image)
References _Image::blob, BlobStream, BZipStream, _Image::debug, FifoStream, _Image::filename, FileStream, GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, PipeStream, _Image::signature, StandardStream, TraceEvent, _BlobInfo::type, UndefinedStream, and ZipStream.
Referenced by SeekBlob().
ThrowBlobException()
static void ThrowBlobException (BlobInfo * blob_info) inline static
References _BlobInfo::error_number, MagickFalse, MagickTrue, and _BlobInfo::status.
Referenced by CloseBlob(), ReadBlob(), WriteBlob(), and WriteBlobByte().
UnmapBlob()
MagickExport MagickBooleanType UnmapBlob (void * map, const size_t length)
References MagickFalse, and MagickTrue.
Referenced by ConfigureFileToStringInfo(), DestroyBlob(), DestroyMagickMemory(), DestroyMatrixInfo(), DetachBlob(), FileToBlob(), FileToXML(), RelinquishCacheNexusPixels(), RelinquishPixelCachePixels(), RelinquishStreamPixels(), RelinquishVirtualMemory(), and SetBlobExtent().
WriteBlob()
MagickExport ssize_t WriteBlob (Image * image, const size_t length, const unsigned char * data)
References _Image::blob, BlobStream, BZipStream, DetachBlob(), FifoStream, FileStream, magick_restrict, MagickCoreSignature, MagickFalse, MagickMaxBufferExtent, MagickMin, PipeStream, ResizeQuantumMemory(), _Image::signature, StandardStream, SyncBlob(), ThrowBlobException(), _BlobInfo::type, UndefinedStream, and ZipStream.
Referenced by WriteBlobStream().
WriteBlobByte()
MagickExport ssize_t WriteBlobByte (Image * image, const unsigned char value)
References _Image::blob, FileStream, magick_restrict, MagickCoreSignature, PipeStream, _Image::signature, StandardStream, ThrowBlobException(), _BlobInfo::type, UndefinedStream, and WriteBlobStream().
WriteBlobFloat()
MagickExport ssize_t WriteBlobFloat (Image * image, const float value)
References WriteBlobLong().
WriteBlobLong()
MagickExport ssize_t WriteBlobLong (Image * image, const unsigned int value)
References _Image::endian, LSBEndian, MagickCoreSignature, _Image::signature, and WriteBlobStream().
Referenced by WriteBlobFloat().
WriteBlobLSBLong()
MagickExport ssize_t WriteBlobLSBLong (Image * image, const unsigned int value)
References MagickCoreSignature, _Image::signature, and WriteBlobStream().
WriteBlobLSBShort()
MagickExport ssize_t WriteBlobLSBShort (Image * image, const unsigned short value)
References MagickCoreSignature, _Image::signature, and WriteBlobStream().
WriteBlobLSBSignedLong()
MagickExport ssize_t WriteBlobLSBSignedLong (Image * image, const signed int value)
References MagickCoreSignature, _Image::signature, and WriteBlobStream().
WriteBlobLSBSignedShort()
MagickExport ssize_t WriteBlobLSBSignedShort (Image * image, const signed short value)
References MagickCoreSignature, _Image::signature, and WriteBlobStream().
WriteBlobMSBLong()
MagickExport ssize_t WriteBlobMSBLong (Image * image, const unsigned int value)
References MagickCoreSignature, _Image::signature, and WriteBlobStream().
WriteBlobMSBLongLong()
MagickExport ssize_t WriteBlobMSBLongLong (Image * image, const MagickSizeType value)
References MagickCoreSignature, _Image::signature, and WriteBlobStream().
WriteBlobMSBShort()
MagickExport ssize_t WriteBlobMSBShort (Image * image, const unsigned short value)
References MagickCoreSignature, _Image::signature, and WriteBlobStream().
WriteBlobMSBSignedLong()
MagickExport ssize_t WriteBlobMSBSignedLong (Image * image, const signed int value)
References MagickCoreSignature, _Image::signature, and WriteBlobStream().
WriteBlobMSBSignedShort()
MagickExport ssize_t WriteBlobMSBSignedShort (Image * image, const signed short value)
References MagickCoreSignature, _Image::signature, and WriteBlobStream().
WriteBlobShort()
MagickExport ssize_t WriteBlobShort (Image * image, const unsigned short value)
References _Image::endian, LSBEndian, MagickCoreSignature, _Image::signature, and WriteBlobStream().
WriteBlobStream()
static ssize_t WriteBlobStream (Image * image, const size_t length, const unsigned char *magick_restrict data) inline static
References _Image::blob, BlobStream, _BlobInfo::extent, magick_restrict, MagickFalse, SetBlobExtent(), _BlobInfo::type, UndefinedStream, and WriteBlob().
Referenced by FileToImage(), InjectImageBlob(), WriteBlobByte(), WriteBlobLong(), WriteBlobLSBLong(), WriteBlobLSBShort(), WriteBlobLSBSignedLong(), WriteBlobLSBSignedShort(), WriteBlobMSBLong(), WriteBlobMSBLongLong(), WriteBlobMSBShort(), WriteBlobMSBSignedLong(), WriteBlobMSBSignedShort(), WriteBlobShort(), and WriteBlobString().
WriteBlobString()
MagickExport ssize_t WriteBlobString (Image * image, const char * string)
References MagickCoreSignature, _Image::signature, and WriteBlobStream().