MagickCore: cache.h File Reference
cache.h File Reference
#include "magick/blob.h"
Enumerations
enum CacheType {
UndefinedCache , MemoryCache , MapCache , DiskCache ,
PingCache , DistributedCache
}
Functions
MagickExport CacheType GetImagePixelCacheType (const Image *)
MagickExport const char * GetPixelCacheFilename (const Image *)
MagickExport const IndexPacket * GetVirtualIndexQueue (const Image *)
MagickExport const PixelPacket * GetVirtualPixels (const Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
MagickExport const PixelPacket * GetVirtualPixelQueue (const Image *)
MagickExport const void * AcquirePixelCachePixels (const Image *, MagickSizeType *, ExceptionInfo *)
MagickExport IndexPacket * GetAuthenticIndexQueue (const Image *)
MagickExport MagickBooleanType CacheComponentGenesis (void)
MagickExport MagickBooleanType GetOneVirtualMagickPixel (const Image *, const ssize_t, const ssize_t, MagickPixelPacket *, ExceptionInfo *)
MagickExport MagickBooleanType GetOneVirtualPixel (const Image *, const ssize_t, const ssize_t, PixelPacket *, ExceptionInfo *)
MagickExport MagickBooleanType GetOneVirtualMethodPixel (const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, PixelPacket *, ExceptionInfo *)
MagickExport MagickBooleanType GetOneAuthenticPixel (Image *, const ssize_t, const ssize_t, PixelPacket *, ExceptionInfo *)
MagickExport MagickBooleanType PersistPixelCache (Image *, const char *, const MagickBooleanType, MagickOffsetType *, ExceptionInfo *)
MagickExport MagickBooleanType SyncAuthenticPixels (Image *, ExceptionInfo *)
MagickExport MagickSizeType GetImageExtent (const Image *)
MagickExport PixelPacket * GetAuthenticPixels (Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
MagickExport PixelPacket * GetAuthenticPixelQueue (const Image *)
MagickExport PixelPacket * QueueAuthenticPixels (Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
MagickExport VirtualPixelMethod GetPixelCacheVirtualMethod (const Image *)
MagickExport VirtualPixelMethod SetPixelCacheVirtualMethod (const Image *, const VirtualPixelMethod)
MagickExport void CacheComponentTerminus (void)
MagickExport void * GetPixelCachePixels (Image *, MagickSizeType *, ExceptionInfo *)
Enumeration Type Documentation
CacheType
enum CacheType
Enumerator
UndefinedCache
MemoryCache
MapCache
DiskCache
PingCache
DistributedCache
Function Documentation
AcquirePixelCachePixels()
MagickExport const void * AcquirePixelCachePixels (const Image * image, MagickSizeType * length, ExceptionInfo * exception)
References _Image::cache, magick_restrict, MagickCoreSignature, MapCache, MemoryCache, _ExceptionInfo::signature, and _Image::signature.
Referenced by ResetImagePixels().
CacheComponentGenesis()
MagickExport MagickBooleanType CacheComponentGenesis (void)
CacheComponentTerminus()
MagickExport void CacheComponentTerminus (void)
GetAuthenticIndexQueue()
MagickExport IndexPacket * GetAuthenticIndexQueue (const Image * image)
References _Image::cache, GetOpenMPThreadId(), magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by GetIndexes(), ImportCharPixel(), ImportDoublePixel(), ImportFloatPixel(), ImportIntegerPixel(), ImportLongPixel(), ImportQuantumPixel(), ImportQuantumPixels(), ImportShortPixel(), RandomChannelThresholdImage(), SetImage(), ThresholdImage(), ThresholdImageChannel(), and WriteDistributeCacheIndexes().
GetAuthenticPixelQueue()
MagickExport PixelPacket * GetAuthenticPixelQueue (const Image *)
GetAuthenticPixels()
MagickExport PixelPacket * GetAuthenticPixels (Image * , const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
GetImageExtent()
MagickExport MagickSizeType GetImageExtent (const Image * image)
References _Image::cache, _Image::debug, _Image::filename, GetMagickModule, GetOpenMPThreadId(), GetPixelCacheNexusExtent(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
Referenced by ExportQuantumPixels(), ImportQuantumPixels(), and StreamImagePixels().
GetImagePixelCacheType()
MagickExport CacheType GetImagePixelCacheType (const Image * image)
References _Image::cache, magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by GetPixelCacheTileSize(), and GetPixelCacheType().
GetOneAuthenticPixel()
MagickExport MagickBooleanType GetOneAuthenticPixel (Image * , const ssize_t, const ssize_t, PixelPacket * , ExceptionInfo *)
GetOneVirtualMagickPixel()
MagickExport MagickBooleanType GetOneVirtualMagickPixel (const Image * , const ssize_t, const ssize_t, MagickPixelPacket * , ExceptionInfo *)
GetOneVirtualMethodPixel()
MagickExport MagickBooleanType GetOneVirtualMethodPixel (const Image * , const VirtualPixelMethod, const ssize_t, const ssize_t, PixelPacket * , ExceptionInfo *)
GetOneVirtualPixel()
MagickExport MagickBooleanType GetOneVirtualPixel (const Image * , const ssize_t, const ssize_t, PixelPacket * , ExceptionInfo *)
GetPixelCacheFilename()
MagickExport const char * GetPixelCacheFilename (const Image * image)
References _Image::cache, magick_restrict, MagickCoreSignature, and _Image::signature.
GetPixelCachePixels()
MagickExport void * GetPixelCachePixels (Image * image, MagickSizeType * length, ExceptionInfo * exception)
References _Image::cache, magick_restrict, MagickCoreSignature, MapCache, MemoryCache, _ExceptionInfo::signature, and _Image::signature.
GetPixelCacheVirtualMethod()
MagickExport VirtualPixelMethod GetPixelCacheVirtualMethod (const Image *)
GetVirtualIndexQueue()
MagickExport const IndexPacket * GetVirtualIndexQueue (const Image * image)
References _Image::cache, GetOpenMPThreadId(), GetVirtualIndexesFromNexus(), magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by AcquireIndexes(), CompareImageBounds(), ExportCharPixel(), ExportDoublePixel(), ExportFloatPixel(), ExportIntegerPixel(), ExportLongPixel(), ExportQuantumPixel(), ExportQuantumPixels(), ExportShortPixel(), GetImageChannelKurtosis(), GetImageChannelMoments(), GetImageChannelRange(), GetImageChannelStatistics(), GetLocationStatistics(), IdentifyImage(), InterpolateMagickPixelPacket(), InterpolatePixelColor(), ReadDistributeCacheIndexes(), and StreamImagePixels().
GetVirtualPixelQueue()
MagickExport const PixelPacket * GetVirtualPixelQueue (const Image * image)
References _Image::cache, GetOpenMPThreadId(), GetVirtualPixelsNexus(), magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by AcquirePixels(), and ExportQuantumPixels().
GetVirtualPixels()
MagickExport const PixelPacket * GetVirtualPixels (const Image * , const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
PersistPixelCache()
MagickExport MagickBooleanType PersistPixelCache (Image * , const char * , const MagickBooleanType, MagickOffsetType * , ExceptionInfo *)
QueueAuthenticPixels()
MagickExport PixelPacket * QueueAuthenticPixels (Image * image, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo * exception)
References _Image::cache, GetOpenMPThreadId(), magick_restrict, MagickCoreSignature, MagickFalse, QueueAuthenticPixelCacheNexus(), and _Image::signature.
Referenced by SetImage(), SetImagePixels(), and StereoAnaglyphImage().
SetPixelCacheVirtualMethod()
MagickExport VirtualPixelMethod SetPixelCacheVirtualMethod (const Image * image, const VirtualPixelMethod)
References _Image::background_color, BackgroundVirtualPixelMethod, _Image::cache, _Image::colorspace, _Image::columns, _Image::debug, _Image::filename, GetMagickModule, IsGrayColorspace(), IsPixelGray(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, _Image::matte, _PixelPacket::opacity, OpaqueOpacity, _Image::rows, SetCacheAlphaChannel(), SetImageColorspace(), _Image::signature, sRGBColorspace, TraceEvent, and TransparentVirtualPixelMethod.
Referenced by SetImageVirtualPixelMethod().
SyncAuthenticPixels()
MagickExport MagickBooleanType SyncAuthenticPixels (Image * image, ExceptionInfo * exception)
References _Image::cache, GetOpenMPThreadId(), magick_restrict, MagickCoreSignature, _Image::signature, and SyncAuthenticPixelCacheNexus().
Referenced by ClearBounds(), ColorFloodfillImage(), ImportCharPixel(), ImportDoublePixel(), ImportFloatPixel(), ImportIntegerPixel(), ImportLongPixel(), ImportQuantumPixel(), ImportShortPixel(), MatteFloodfillImage(), OpaqueImage(), RandomChannelThresholdImage(), SetImage(), StereoAnaglyphImage(), SyncImagePixels(), ThresholdImage(), ThresholdImageChannel(), TransparentImage(), WriteDistributeCacheIndexes(), and WriteDistributeCachePixels().