MagickCore: cache-private.h File Reference
cache-private.h File Reference
#include <time.h>
#include "magick/cache.h"
#include "magick/distribute-cache.h"
#include "magick/opencl-private.h"
#include "magick/random_.h"
#include "magick/thread-private.h"
#include "magick/semaphore.h"
Data Structures
struct _CacheMethods
struct _NexusInfo
struct _OpenCLCacheInfo
struct _CacheInfo
Typedefs
typedef void * Cache
typedef const IndexPacket *(* GetVirtualIndexesFromHandler) (const Image *)
typedef IndexPacket *(* GetAuthenticIndexesFromHandler) (const Image *)
typedef MagickBooleanType(* GetOneAuthenticPixelFromHandler) (Image *, const ssize_t, const ssize_t, PixelPacket *, ExceptionInfo *)
typedef MagickBooleanType(*)(* GetOneVirtualPixelFromHandler) (const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, PixelPacket *, ExceptionInfo *)
typedef MagickBooleanType(*)(*)(* SyncAuthenticPixelsHandler) (Image *, ExceptionInfo *)
typedef const PixelPacket *(* GetVirtualPixelHandler) (const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
typedef const PixelPacket *(*) *(* GetVirtualPixelsHandler) (const Image *)
typedef PixelPacket *(* GetAuthenticPixelsHandler) (Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
typedef PixelPacket *(* GetAuthenticPixelsFromHandler) (const Image *)
typedef PixelPacket *(* QueueAuthenticPixelsHandler) (Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
typedef void(* DestroyPixelHandler) (Image *)
typedef struct _CacheMethods CacheMethods
typedef struct _NexusInfo NexusInfo
typedef struct _OpenCLCacheInfo OpenCLCacheInfo
typedef struct _CacheInfo CacheInfo
Functions
MagickExport Cache AcquirePixelCache (const size_t)
MagickExport Cache ClonePixelCache (const Cache)
MagickExport Cache DestroyPixelCache (Cache)
MagickExport Cache ReferencePixelCache (Cache)
MagickExport CacheType GetPixelCacheType (const Image *)
MagickExport ClassType GetPixelCacheStorageClass (const Cache)
MagickExport ColorspaceType GetPixelCacheColorspace (const Cache)
MagickExport const IndexPacket * GetVirtualIndexesFromNexus (const Cache, NexusInfo *)
MagickExport const PixelPacket * GetVirtualPixelCacheNexus (const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, const size_t, const size_t, NexusInfo *, ExceptionInfo *) magick_hot_spot
MagickExport const PixelPacket * GetVirtualPixelsNexus (const Cache, NexusInfo *)
MagickExport MagickBooleanType SyncAuthenticPixelCacheNexus (Image *, NexusInfo *magick_restrict, ExceptionInfo *) magick_hot_spot
MagickExport MagickSizeType GetPixelCacheNexusExtent (const Cache, NexusInfo *)
MagickExport NexusInfo ** AcquirePixelCacheNexus (const size_t)
MagickExport NexusInfo ** DestroyPixelCacheNexus (NexusInfo **, const size_t)
MagickExport PixelPacket * GetAuthenticPixelCacheNexus (Image *, const ssize_t, const ssize_t, const size_t, const size_t, NexusInfo *, ExceptionInfo *) magick_hot_spot
MagickExport PixelPacket * QueueAuthenticPixel (Image *, const ssize_t, const ssize_t, const size_t, const size_t, const MagickBooleanType, NexusInfo *, ExceptionInfo *)
MagickExport PixelPacket * QueueAuthenticPixelCacheNexus (Image *, const ssize_t, const ssize_t, const size_t, const size_t, const MagickBooleanType, NexusInfo *, ExceptionInfo *) magick_hot_spot
MagickExport size_t GetPixelCacheChannels (const Cache)
MagickExport void ClonePixelCacheMethods (Cache, const Cache)
MagickExport void GetPixelCacheTileSize (const Image *, size_t *, size_t *)
MagickExport void GetPixelCacheMethods (CacheMethods *)
MagickExport void SetPixelCacheMethods (Cache, CacheMethods *)
MagickPrivate void ResetPixelCacheEpoch (void)
MagickPrivate MagickBooleanType SyncImagePixelCache (Image *, ExceptionInfo *)
Typedef Documentation
Cache
typedef void* Cache
CacheInfo
typedef struct _CacheInfo CacheInfo
CacheMethods
typedef struct _CacheMethods CacheMethods
DestroyPixelHandler
typedef void(* DestroyPixelHandler) (Image *)
GetAuthenticIndexesFromHandler
typedef IndexPacket *(* GetAuthenticIndexesFromHandler) (const Image *)
GetAuthenticPixelsFromHandler
typedef PixelPacket *(* GetAuthenticPixelsFromHandler) (const Image *)
GetAuthenticPixelsHandler
typedef PixelPacket *(* GetAuthenticPixelsHandler) (Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
GetOneAuthenticPixelFromHandler
typedef MagickBooleanType(* GetOneAuthenticPixelFromHandler) (Image *, const ssize_t, const ssize_t, PixelPacket *, ExceptionInfo *)
GetOneVirtualPixelFromHandler
typedef MagickBooleanType(*)(* GetOneVirtualPixelFromHandler) (const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, PixelPacket *, ExceptionInfo *)
GetVirtualIndexesFromHandler
typedef const IndexPacket *(* GetVirtualIndexesFromHandler) (const Image *)
GetVirtualPixelHandler
typedef const PixelPacket *(* GetVirtualPixelHandler) (const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
GetVirtualPixelsHandler
typedef const PixelPacket *(*) *(* GetVirtualPixelsHandler) (const Image *)
NexusInfo
typedef struct _NexusInfo NexusInfo
OpenCLCacheInfo
typedef struct _OpenCLCacheInfo OpenCLCacheInfo
QueueAuthenticPixelsHandler
typedef PixelPacket *(* QueueAuthenticPixelsHandler) (Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
SyncAuthenticPixelsHandler
typedef MagickBooleanType(*)(*)(* SyncAuthenticPixelsHandler) (Image *, ExceptionInfo *)
Function Documentation
AcquirePixelCache()
MagickExport Cache AcquirePixelCache (const size_t)
Referenced by AcquireImage(), and ReadStream().
AcquirePixelCacheNexus()
MagickExport NexusInfo ** AcquirePixelCacheNexus (const size_t)
Referenced by AcquireVirtualCacheView(), and CloneCacheView().
ClonePixelCache()
MagickExport Cache ClonePixelCache (const Cache)
Referenced by CloneImage().
ClonePixelCacheMethods()
MagickExport void ClonePixelCacheMethods (Cache , const Cache)
Referenced by AcquireImage().
DestroyPixelCache()
MagickExport Cache DestroyPixelCache (Cache)
Referenced by DestroyImageInfo().
DestroyPixelCacheNexus()
MagickExport NexusInfo ** DestroyPixelCacheNexus (NexusInfo ** nexus_info, const size_t)
References RelinquishAlignedMemory(), RelinquishCacheNexusPixels(), RelinquishMagickMemory(), and _NexusInfo::signature.
Referenced by ClipPixelCacheNexus(), ClonePixelCacheRepository(), DestroyCacheView(), DestroyPixelCache(), DestroyPixelStream(), and MaskPixelCacheNexus().
GetAuthenticPixelCacheNexus()
MagickExport PixelPacket * GetAuthenticPixelCacheNexus (Image * , const ssize_t, const ssize_t, const size_t, const size_t, NexusInfo * , ExceptionInfo *)
Referenced by GetCacheViewAuthenticPixels(), and GetOneCacheViewAuthenticPixel().
GetPixelCacheChannels()
MagickExport size_t GetPixelCacheChannels (const Cache)
References GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, and TraceEvent.
Referenced by GetCacheViewChannels().
GetPixelCacheColorspace()
MagickExport ColorspaceType GetPixelCacheColorspace (const Cache)
References GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, and TraceEvent.
Referenced by GetCacheViewColorspace().
GetPixelCacheMethods()
MagickExport void GetPixelCacheMethods (CacheMethods *)
Referenced by ReadStream().
GetPixelCacheNexusExtent()
MagickExport MagickSizeType GetPixelCacheNexusExtent (const Cache, NexusInfo * nexus_info)
References _RectangleInfo::height, magick_restrict, MagickCoreSignature, _NexusInfo::region, and _RectangleInfo::width.
Referenced by GetCacheViewExtent(), and GetImageExtent().
GetPixelCacheStorageClass()
MagickExport ClassType GetPixelCacheStorageClass (const Cache)
References GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, and TraceEvent.
Referenced by GetCacheViewStorageClass().
GetPixelCacheTileSize()
MagickExport void GetPixelCacheTileSize (const Image * , size_t * , size_t *)
Referenced by IntegralRotateImage().
GetPixelCacheType()
MagickExport CacheType GetPixelCacheType (const Image * image)
References GetImagePixelCacheType().
GetVirtualIndexesFromNexus()
MagickExport const IndexPacket * GetVirtualIndexesFromNexus (const Cache, NexusInfo * nexus_info)
References _NexusInfo::indexes, magick_restrict, MagickCoreSignature, and UndefinedClass.
Referenced by GetCacheViewVirtualIndexQueue(), GetOneVirtualMagickPixel(), GetVirtualIndexesFromCache(), GetVirtualIndexQueue(), and GetVirtualPixelCacheNexus().
GetVirtualPixelCacheNexus()
MagickExport const PixelPacket * GetVirtualPixelCacheNexus (const Image * , const VirtualPixelMethod, const ssize_t, const ssize_t, const size_t, const size_t, NexusInfo * , ExceptionInfo *)
Referenced by GetCacheViewVirtualPixels(), GetOneCacheViewVirtualMethodPixel(), and GetOneCacheViewVirtualPixel().
GetVirtualPixelsNexus()
MagickExport const PixelPacket * GetVirtualPixelsNexus (const Cache, NexusInfo * nexus_info)
References magick_restrict, MagickCoreSignature, _NexusInfo::pixels, and UndefinedClass.
Referenced by GetCacheViewVirtualPixelQueue(), GetVirtualPixelQueue(), and GetVirtualPixelsCache().
QueueAuthenticPixel()
MagickExport PixelPacket * QueueAuthenticPixel (Image * , const ssize_t, const ssize_t, const size_t, const size_t, const MagickBooleanType, NexusInfo * , ExceptionInfo *)
QueueAuthenticPixelCacheNexus()
MagickExport PixelPacket * QueueAuthenticPixelCacheNexus (Image * image, const ssize_t, const ssize_t, const size_t, const size_t, const MagickBooleanType, NexusInfo * nexus_info, ExceptionInfo * exception)
References _Image::cache, CacheError, _Image::clip_mask, _Image::filename, GetImagePixelCache(), GetMagickModule, magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::mask, SetPixelCacheNexusPixels(), _Image::signature, ThrowMagickException(), and WriteMode.
Referenced by GetAuthenticPixelCacheNexus(), QueueAuthenticPixel(), QueueAuthenticPixels(), QueueAuthenticPixelsCache(), and QueueCacheViewAuthenticPixels().
ReferencePixelCache()
MagickExport Cache ReferencePixelCache (Cache cache)
References LockSemaphoreInfo(), magick_restrict, MagickCoreSignature, and UnlockSemaphoreInfo().
Referenced by CloneImage(), and CloneImageInfo().
ResetPixelCacheEpoch()
MagickPrivate void ResetPixelCacheEpoch (void)
References cache_epoch.
Referenced by SetMagickResourceLimit().
SetPixelCacheMethods()
MagickExport void SetPixelCacheMethods (Cache cache, CacheMethods * cache_methods)
References _CacheMethods::destroy_pixel_handler, _CacheMethods::get_authentic_indexes_from_handler, _CacheMethods::get_authentic_pixels_from_handler, _CacheMethods::get_authentic_pixels_handler, _CacheMethods::get_one_authentic_pixel_from_handler, _CacheMethods::get_one_virtual_pixel_from_handler, _CacheMethods::get_virtual_indexes_from_handler, _CacheMethods::get_virtual_pixel_handler, GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, _CacheMethods::queue_authentic_pixels_handler, _CacheMethods::sync_authentic_pixels_handler, and TraceEvent.
Referenced by ReadStream().
SyncAuthenticPixelCacheNexus()
MagickExport MagickBooleanType SyncAuthenticPixelCacheNexus (Image * , NexusInfo * magick_restrict, ExceptionInfo *)
Referenced by SyncCacheViewAuthenticPixels().
SyncImagePixelCache()
MagickPrivate MagickBooleanType SyncImagePixelCache (Image * image, ExceptionInfo * exception)
References GetImagePixelCache(), magick_restrict, MagickFalse, and MagickTrue.
Referenced by OpenDistributeCache(), SetImageAlphaChannel(), SetImageColorspace(), SetImageExtent(), SetImageGray(), SetImageMonochrome(), and SetImageStorageClass().