MagickCore: cache-view.h File Reference
cache-view.h File Reference
#include "magick/pixel.h"
Typedefs
typedef struct _CacheView CacheView
Enumerations
enum VirtualPixelMethod {
UndefinedVirtualPixelMethod , BackgroundVirtualPixelMethod , ConstantVirtualPixelMethod , DitherVirtualPixelMethod ,
EdgeVirtualPixelMethod , MirrorVirtualPixelMethod , RandomVirtualPixelMethod , TileVirtualPixelMethod ,
TransparentVirtualPixelMethod , MaskVirtualPixelMethod , BlackVirtualPixelMethod , GrayVirtualPixelMethod ,
WhiteVirtualPixelMethod , HorizontalTileVirtualPixelMethod , VerticalTileVirtualPixelMethod , HorizontalTileEdgeVirtualPixelMethod ,
VerticalTileEdgeVirtualPixelMethod , CheckerTileVirtualPixelMethod
}
Functions
MagickExport CacheView * AcquireAuthenticCacheView (const Image *, ExceptionInfo *)
MagickExport CacheView * AcquireCacheView (const Image *)
MagickExport CacheView * AcquireVirtualCacheView (const Image *, ExceptionInfo *)
MagickExport CacheView * CloneCacheView (const CacheView *)
MagickExport CacheView * DestroyCacheView (CacheView *)
MagickExport ClassType GetCacheViewStorageClass (const CacheView *) magick_attribute((__pure__))
MagickExport ColorspaceType GetCacheViewColorspace (const CacheView *) magick_attribute((__pure__))
MagickExport const IndexPacket * GetCacheViewVirtualIndexQueue (const CacheView *) magick_attribute((__pure__))
MagickExport const PixelPacket * GetCacheViewVirtualPixels (const CacheView *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *) magick_hot_spot
MagickExport const PixelPacket * GetCacheViewVirtualPixelQueue (const CacheView *) magick_hot_spot
MagickExport ExceptionInfo * GetCacheViewException (const CacheView *) magick_attribute((__pure__))
MagickExport IndexPacket * GetCacheViewAuthenticIndexQueue (CacheView *) magick_attribute((__pure__))
MagickExport MagickBooleanType GetOneCacheViewAuthenticPixel (const CacheView *magick_restrict, const ssize_t, const ssize_t, PixelPacket *magick_restrict, ExceptionInfo *)
MagickExport MagickBooleanType GetOneCacheViewVirtualMethodPixel (const CacheView *, const VirtualPixelMethod, const ssize_t, const ssize_t, PixelPacket *, ExceptionInfo *)
MagickExport MagickBooleanType GetOneCacheViewVirtualPixel (const CacheView *magick_restrict, const ssize_t, const ssize_t, PixelPacket *magick_restrict, ExceptionInfo *)
MagickExport MagickBooleanType SetCacheViewStorageClass (CacheView *, const ClassType)
MagickExport MagickBooleanType SetCacheViewVirtualPixelMethod (CacheView *magick_restrict, const VirtualPixelMethod)
MagickExport MagickBooleanType SyncCacheViewAuthenticPixels (CacheView *magick_restrict, ExceptionInfo *) magick_hot_spot
MagickExport MagickSizeType GetCacheViewExtent (const CacheView *)
MagickExport size_t GetCacheViewChannels (const CacheView *)
MagickExport PixelPacket * GetCacheViewAuthenticPixelQueue (CacheView *) magick_hot_spot
MagickExport PixelPacket * GetCacheViewAuthenticPixels (CacheView *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *) magick_hot_spot
MagickExport PixelPacket * QueueCacheViewAuthenticPixels (CacheView *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *) magick_hot_spot
Typedef Documentation
CacheView
typedef struct _CacheView CacheView
Enumeration Type Documentation
VirtualPixelMethod
enum VirtualPixelMethod
Enumerator
UndefinedVirtualPixelMethod
BackgroundVirtualPixelMethod
ConstantVirtualPixelMethod
DitherVirtualPixelMethod
EdgeVirtualPixelMethod
MirrorVirtualPixelMethod
RandomVirtualPixelMethod
TileVirtualPixelMethod
TransparentVirtualPixelMethod
MaskVirtualPixelMethod
BlackVirtualPixelMethod
GrayVirtualPixelMethod
WhiteVirtualPixelMethod
HorizontalTileVirtualPixelMethod
VerticalTileVirtualPixelMethod
HorizontalTileEdgeVirtualPixelMethod
VerticalTileEdgeVirtualPixelMethod
CheckerTileVirtualPixelMethod
Function Documentation
AcquireAuthenticCacheView()
MagickExport CacheView * AcquireAuthenticCacheView (const Image * , ExceptionInfo *)
AcquireCacheView()
MagickExport CacheView * AcquireCacheView (const Image *)
AcquireVirtualCacheView()
MagickExport CacheView * AcquireVirtualCacheView (const Image * , ExceptionInfo *)
CloneCacheView()
MagickExport CacheView * CloneCacheView (const CacheView *)
DestroyCacheView()
MagickExport CacheView * DestroyCacheView (CacheView * cache_view)
References _CacheView::debug, DestroyImage(), DestroyPixelCacheNexus(), _Image::filename, GetMagickModule, _CacheView::image, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheView::nexus_info, _CacheView::number_threads, RelinquishAlignedMemory(), _CacheView::signature, and TraceEvent.
Referenced by AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), AddNoiseImageChannel(), AppendImages(), AssignImageColors(), AutoThresholdImage(), BilevelImageChannel(), BlackThresholdImageChannel(), BlueShiftImage(), CannyEdgeImage(), CheckImageColors(), ChopImage(), ClampImageChannel(), Classify(), ClassifyImageColors(), CloseCacheView(), ClutImageChannel(), ColorDecisionListImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImageChannels(), ComplexImages(), CompositeImageChannel(), ConnectedComponentsImage(), ConsolidateCMYKImages(), ContrastImage(), ContrastStretchImageChannel(), CopyImagePixels(), CopyImageRegion(), CropImage(), CycleColormapImage(), DespeckleImage(), DestroyFxInfo(), DestroyImageView(), DestroyResampleFilter(), DistortImage(), DitherImage(), DrawAffineImage(), DrawPolygonPrimitive(), DrawPrimitive(), EnhanceImage(), EqualizeImageChannel(), EvaluateImageChannel(), EvaluateImages(), ExcerptImage(), FilterImageChannel(), FlipImage(), FloodfillPaintImage(), FlopImage(), FloydSteinbergDither(), FrameImage(), FunctionImageChannel(), FxImageChannel(), GammaImageChannel(), GetAbsoluteDistortion(), GetEdgeBackgroundFactor(), GetEdgeBoundingBox(), GetFuzzDistortion(), GetImageBackgroundColor(), GetImageBoundingBox(), GetImageChannelDepth(), GetImageChannelFeatures(), GetImageQuantizeError(), GetImageTotalInkDensity(), GetMeanAbsoluteDistortion(), GetMeanErrorPerPixel(), GetMeanSquaredDistortion(), GetNormalizedCrossCorrelationDistortion(), GetPeakAbsoluteDistortion(), GetSimilarityMetric(), GrayscaleImage(), HaldClutImageChannel(), HorizontalFilter(), HoughLineImage(), HuffmanDecodeImage(), IdentifyImageGray(), IdentifyImageMonochrome(), ImplodeImage(), IntegralRotateImage(), InterpolateMagickPixelPacket(), InterpolativeResizeImage(), IsHighDynamicRangeImage(), IsHistogramImage(), IsImagesEqual(), IsImageSimilar(), IsOpaqueImage(), KuwaharaImageChannel(), LevelImageChannel(), LevelizeImageChannel(), LocalContrastImage(), MagnifyImage(), MatrixToImage(), MeanShiftImage(), ModulateImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImageChannel(), NegateImageChannel(), NewMagickImage(), OilPaintImage(), OpaquePaintImageChannel(), OrderedPosterizeImageChannel(), PerceptibleImageChannel(), PlasmaImage(), PolynomialImageChannel(), PosterizeImageChannel(), ProfileImage(), RadonTransform(), RaiseImage(), RandomThresholdImageChannel(), RenderPostscript(), ResamplePixelColor(), ResetImagePixels(), RGBTransformImage(), RotationalBlurImageChannel(), SampleImage(), ScaleImage(), SelectiveBlurImageChannel(), SeparateImageChannel(), SepiaToneImage(), SetCacheAlphaChannel(), SetGrayscaleImage(), SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageChannelDepth(), SetImageColor(), SetImageGray(), SetImageMonochrome(), SetImageOpacity(), ShadeImage(), ShadowImage(), SigmoidalContrastImageChannel(), SignatureImage(), SimilarityMetricImage(), SketchImage(), SmushImages(), SmushXGap(), SmushYGap(), SolarizeImageChannel(), SortColormapByIntensity(), SparseColorImage(), SpliceImage(), SpreadImage(), StatisticImageChannel(), SteganoImage(), SwirlImage(), SyncImage(), TextureImage(), TintImage(), TransformRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), TransposeImage(), TransverseImage(), UniqueImageColors(), UnsharpMaskImageChannel(), VerticalFilter(), WaveImage(), WaveletDenoiseImage(), WhiteThresholdImageChannel(), XShearImage(), and YShearImage().
GetCacheViewAuthenticIndexQueue()
MagickExport IndexPacket * GetCacheViewAuthenticIndexQueue (CacheView * cache_view)
References _Image::cache, GetOpenMPThreadId(), _CacheView::image, _NexusInfo::indexes, MagickCoreSignature, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), AddNoiseImageChannel(), AppendImages(), AssignImageColors(), BilevelImageChannel(), BlackThresholdImageChannel(), ChopImage(), ClampImageChannel(), Classify(), ClutImageChannel(), ColorMatrixImage(), CombineImages(), CompareImageChannels(), CompositeImageChannel(), ConnectedComponentsImage(), ConsolidateCMYKImages(), ContrastStretchImageChannel(), CopyImagePixels(), CopyImageRegion(), CropImage(), CycleColormapImage(), DespeckleImage(), DistortImage(), DrawAffineImage(), DrawGradientImage(), EqualizeImageChannel(), EvaluateImageChannel(), EvaluateImages(), ExcerptImage(), FilterImageChannel(), FlipImage(), FloodfillPaintImage(), FlopImage(), FloydSteinbergDither(), FrameImage(), FunctionImageChannel(), FxImageChannel(), GammaImageChannel(), GetCacheViewIndexes(), GetImageQuantizeError(), GetImageViewAuthenticIndexes(), HaldClutImageChannel(), HorizontalFilter(), HuffmanDecodeImage(), ImplodeImage(), ImportQuantumPixels(), IntegralRotateImage(), InterpolativeResizeImage(), KuwaharaImageChannel(), LevelImageChannel(), LevelizeImageChannel(), MagnifyImage(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImageChannel(), NegateImageChannel(), NewMagickImage(), OilPaintImage(), OpaquePaintImageChannel(), OrderedPosterizeImageChannel(), PerceptibleImageChannel(), PolynomialImageChannel(), PosterizeImageChannel(), ProfileImage(), RandomThresholdImageChannel(), ResamplePixelColor(), ResetImagePixels(), RGBTransformImage(), RiemersmaDither(), RotationalBlurImageChannel(), SampleImage(), ScaleImage(), SelectiveBlurImageChannel(), SeparateImageChannel(), SetGrayscaleImage(), SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageColor(), SigmoidalContrastImageChannel(), SketchImage(), SortColormapByIntensity(), SparseColorImage(), SpliceImage(), SpreadImage(), StatisticImageChannel(), SwirlImage(), SyncImage(), TextureImage(), TransformRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), TransposeImage(), TransverseImage(), UniqueColorsToImage(), UnsharpMaskImageChannel(), VerticalFilter(), WaveImage(), WaveletDenoiseImage(), WhiteThresholdImageChannel(), XShearImage(), and YShearImage().
GetCacheViewAuthenticPixelQueue()
MagickExport PixelPacket * GetCacheViewAuthenticPixelQueue (CacheView *)
GetCacheViewAuthenticPixels()
MagickExport PixelPacket * GetCacheViewAuthenticPixels (CacheView * , const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
GetCacheViewChannels()
MagickExport size_t GetCacheViewChannels (const CacheView * cache_view)
References _Image::cache, _CacheView::debug, _Image::filename, GetMagickModule, GetPixelCacheChannels(), _CacheView::image, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheView::signature, and TraceEvent.
GetCacheViewColorspace()
MagickExport ColorspaceType GetCacheViewColorspace (const CacheView * cache_view)
References _Image::cache, _CacheView::debug, _Image::filename, GetMagickModule, GetPixelCacheColorspace(), _CacheView::image, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheView::signature, and TraceEvent.
GetCacheViewException()
MagickExport ExceptionInfo * GetCacheViewException (const CacheView * cache_view)
References _CacheView::debug, _Image::exception, _Image::filename, GetMagickModule, _CacheView::image, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheView::signature, and TraceEvent.
Referenced by DuplexTransferImageViewIterator(), GetCacheView(), GetCacheViewPixels(), SetCacheViewPixels(), SetImageViewIterator(), SyncCacheView(), SyncCacheViewPixels(), TransferImageViewIterator(), and UpdateImageViewIterator().
GetCacheViewExtent()
MagickExport MagickSizeType GetCacheViewExtent (const CacheView * cache_view)
References _Image::cache, _CacheView::debug, _Image::filename, GetMagickModule, GetOpenMPThreadId(), GetPixelCacheNexusExtent(), _CacheView::image, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheView::nexus_info, _CacheView::number_threads, _CacheView::signature, and TraceEvent.
Referenced by ExportQuantumPixels(), and ImportQuantumPixels().
GetCacheViewStorageClass()
MagickExport ClassType GetCacheViewStorageClass (const CacheView * cache_view)
References _Image::cache, _CacheView::debug, _Image::filename, GetMagickModule, GetPixelCacheStorageClass(), _CacheView::image, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheView::signature, and TraceEvent.
GetCacheViewVirtualIndexQueue()
MagickExport const IndexPacket * GetCacheViewVirtualIndexQueue (const CacheView * cache_view)
References _Image::cache, GetOpenMPThreadId(), GetVirtualIndexesFromNexus(), _CacheView::image, MagickCoreSignature, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by AcquireCacheViewIndexes(), AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), AddNoiseImageChannel(), AppendImages(), CheckImageColors(), ClassifyImageColors(), ColorMatrixImage(), CompareImageChannels(), CompositeImageChannel(), ConnectedComponentsImage(), CopyImagePixels(), CopyImageRegion(), CropImage(), DespeckleImage(), EqualizeImageChannel(), EvaluateImages(), ExportQuantumPixels(), FilterImageChannel(), FlipImage(), FloodfillPaintImage(), FlopImage(), GetAbsoluteDistortion(), GetFuzzDistortion(), GetImageBoundingBox(), GetImageChannelDepth(), GetImageChannelFeatures(), GetImageTotalInkDensity(), GetImageViewVirtualIndexes(), GetMeanAbsoluteDistortion(), GetMeanErrorPerPixel(), GetMeanSquaredDistortion(), GetNormalizedCrossCorrelationDistortion(), GetPeakAbsoluteDistortion(), GetSimilarityMetric(), HorizontalFilter(), IntegralRotateImage(), InterpolateMagickPixelPacket(), InterpolatePixelColor(), IsHighDynamicRangeImage(), IsHistogramImage(), IsImagesEqual(), IsImageSimilar(), MagnifyImage(), MeanShiftImage(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImageChannel(), OilPaintImage(), PolynomialImageChannel(), ResamplePixelColor(), RotationalBlurImageChannel(), ScaleImage(), SelectiveBlurImageChannel(), StatisticImageChannel(), TextureImage(), UnsharpMaskImageChannel(), VerticalFilter(), and WaveletDenoiseImage().
GetCacheViewVirtualPixelQueue()
MagickExport const PixelPacket * GetCacheViewVirtualPixelQueue (const CacheView * cache_view)
References _Image::cache, GetOpenMPThreadId(), GetVirtualPixelsNexus(), _CacheView::image, MagickCoreSignature, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by ExportQuantumPixels(), and GetImageViewVirtualPixels().
GetCacheViewVirtualPixels()
MagickExport const PixelPacket * GetCacheViewVirtualPixels (const CacheView * , const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
GetOneCacheViewAuthenticPixel()
MagickExport MagickBooleanType GetOneCacheViewAuthenticPixel (const CacheView * magick_restrict, const ssize_t, const ssize_t, PixelPacket * magick_restrict, ExceptionInfo *)
GetOneCacheViewVirtualMethodPixel()
MagickExport MagickBooleanType GetOneCacheViewVirtualMethodPixel (const CacheView * , const VirtualPixelMethod, const ssize_t, const ssize_t, PixelPacket * , ExceptionInfo *)
GetOneCacheViewVirtualPixel()
MagickExport MagickBooleanType GetOneCacheViewVirtualPixel (const CacheView * magick_restrict, const ssize_t, const ssize_t, PixelPacket * magick_restrict, ExceptionInfo *)
QueueCacheViewAuthenticPixels()
MagickExport PixelPacket * QueueCacheViewAuthenticPixels (CacheView * cache_view, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo * exception)
References GetOpenMPThreadId(), _CacheView::image, MagickCoreSignature, MagickFalse, _CacheView::nexus_info, _CacheView::number_threads, QueueAuthenticPixelCacheNexus(), and _CacheView::signature.
Referenced by AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AppendImages(), BlueShiftImage(), ChopImage(), ColorizeImage(), CompareImageChannels(), ComplexImages(), CompositeImageChannel(), ConnectedComponentsImage(), ConsolidateCMYKImages(), CropImage(), DistortImage(), EnhanceImage(), EvaluateImages(), FlipImage(), FlopImage(), FrameImage(), HorizontalFilter(), HuffmanDecodeImage(), IntegralRotateImage(), InterpolativeResizeImage(), KuwaharaImageChannel(), MagnifyImage(), MatrixToImage(), NewMagickImage(), OilPaintImage(), PlasmaImageProxy(), PolynomialImageChannel(), ResetImagePixels(), SampleImage(), ScaleImage(), SepiaToneImage(), SetCacheViewPixels(), SetImageBackgroundColor(), SetImageColor(), ShadeImage(), SketchImage(), SpliceImage(), SpreadImage(), StatisticImageChannel(), TextureImage(), TintImage(), TransposeImage(), TransverseImage(), UniqueColorsToImage(), VerticalFilter(), and WaveImage().
SetCacheViewStorageClass()
MagickExport MagickBooleanType SetCacheViewStorageClass (CacheView * , const ClassType)
SetCacheViewVirtualPixelMethod()
MagickExport MagickBooleanType SetCacheViewVirtualPixelMethod (CacheView * magick_restrict, const VirtualPixelMethod)
SyncCacheViewAuthenticPixels()
MagickExport MagickBooleanType SyncCacheViewAuthenticPixels (CacheView * magick_restrict, ExceptionInfo *)