MagickCore: cache.c File Reference
cache.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/cache.h"
#include "magick/cache-private.h"
#include "magick/color-private.h"
#include "magick/colorspace.h"
#include "magick/colorspace-private.h"
#include "magick/composite-private.h"
#include "magick/distribute-cache-private.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/geometry.h"
#include "magick/list.h"
#include "magick/log.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/memory-private.h"
#include "magick/nt-base-private.h"
#include "magick/option.h"
#include "magick/pixel.h"
#include "magick/pixel-accessor.h"
#include "magick/pixel-private.h"
#include "magick/policy.h"
#include "magick/quantum.h"
#include "magick/random_.h"
#include "magick/registry.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/splay-tree.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/thread-private.h"
#include "magick/timer-private.h"
#include "magick/utility.h"
#include "magick/utility-private.h"
Data Structures
struct _MagickModulo
Macros
#define CacheTick(offset, extent) QuantumTick((MagickOffsetType) offset,extent)
#define IsFileDescriptorLimitExceeded()
#define MaxCacheThreads ((size_t) GetMagickResourceLimit(ThreadResource))
#define cache_number_threads(source, destination, chunk, multithreaded)
Typedefs
typedef struct _MagickModulo MagickModulo
Functions
static Cache GetImagePixelCache (Image *, const MagickBooleanType, ExceptionInfo *) magick_hot_spot
static const IndexPacket * GetVirtualIndexesFromCache (const Image *)
static const PixelPacket * GetVirtualPixelCache (const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
static const PixelPacket * GetVirtualPixelsCache (const Image *)
static MagickBooleanType GetOneAuthenticPixelFromCache (Image *, const ssize_t, const ssize_t, PixelPacket *, ExceptionInfo *)
static MagickBooleanType GetOneVirtualPixelFromCache (const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, PixelPacket *, ExceptionInfo *)
static MagickBooleanType OpenPixelCache (Image *, const MapMode, ExceptionInfo *)
static MagickBooleanType OpenPixelCacheOnDisk (CacheInfo *, const MapMode)
static MagickBooleanType ReadPixelCacheIndexes (CacheInfo *magick_restrict, NexusInfo *magick_restrict, ExceptionInfo *)
static MagickBooleanType ReadPixelCachePixels (CacheInfo *magick_restrict, NexusInfo *magick_restrict, ExceptionInfo *)
static MagickBooleanType SyncAuthenticPixelsCache (Image *, ExceptionInfo *)
static MagickBooleanType WritePixelCacheIndexes (CacheInfo *, NexusInfo *magick_restrict, ExceptionInfo *)
static MagickBooleanType WritePixelCachePixels (CacheInfo *, NexusInfo *magick_restrict, ExceptionInfo *)
static PixelPacket * GetAuthenticPixelsCache (Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
static PixelPacket * QueueAuthenticPixelsCache (Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
static PixelPacket * SetPixelCacheNexusPixels (const CacheInfo *magick_restrict, const MapMode, const ssize_t, const ssize_t, const size_t, const size_t, const MagickBooleanType, NexusInfo *magick_restrict, ExceptionInfo *) magick_hot_spot
MagickExport Cache AcquirePixelCache (const size_t number_threads)
MagickExport NexusInfo ** AcquirePixelCacheNexus (const size_t number_threads)
MagickExport const void * AcquirePixelCachePixels (const Image *image, MagickSizeType *length, ExceptionInfo *exception)
MagickExport MagickBooleanType CacheComponentGenesis (void)
MagickExport void CacheComponentTerminus (void)
static MagickBooleanType ClipPixelCacheNexus (Image *image, NexusInfo *nexus_info, ExceptionInfo *exception)
MagickExport Cache ClonePixelCache (const Cache cache)
MagickExport void ClonePixelCacheMethods (Cache clone, const Cache cache)
static MagickBooleanType ClonePixelCacheOnDisk (CacheInfo *magick_restrict cache_info, CacheInfo *magick_restrict clone_info)
static MagickBooleanType ClonePixelCacheRepository (CacheInfo *magick_restrict clone_info, CacheInfo *magick_restrict cache_info, ExceptionInfo *exception)
static void DestroyImagePixelCache (Image *image)
MagickExport void DestroyImagePixels (Image *image)
static MagickBooleanType ClosePixelCacheOnDisk (CacheInfo *cache_info)
static void RelinquishPixelCachePixels (CacheInfo *cache_info)
MagickExport Cache DestroyPixelCache (Cache cache)
static void RelinquishCacheNexusPixels (NexusInfo *nexus_info)
MagickExport NexusInfo ** DestroyPixelCacheNexus (NexusInfo **nexus_info, const size_t number_threads)
static IndexPacket * GetAuthenticIndexesFromCache (const Image *image)
MagickExport IndexPacket * GetAuthenticIndexQueue (const Image *image)
MagickExport PixelPacket * GetAuthenticPixelCacheNexus (Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, NexusInfo *nexus_info, ExceptionInfo *exception)
static PixelPacket * GetAuthenticPixelsFromCache (const Image *image)
MagickExport PixelPacket * GetAuthenticPixelQueue (const Image *image)
MagickExport PixelPacket * GetAuthenticPixels (Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport MagickSizeType GetImageExtent (const Image *image)
static MagickBooleanType ValidatePixelCacheMorphology (const Image *magick_restrict image)
MagickExport CacheType GetPixelCacheType (const Image *image)
MagickExport CacheType GetImagePixelCacheType (const Image *image)
MagickExport MagickBooleanType GetOneAuthenticPixel (Image *image, const ssize_t x, const ssize_t y, PixelPacket *pixel, ExceptionInfo *exception)
MagickExport MagickBooleanType GetOneVirtualMagickPixel (const Image *image, const ssize_t x, const ssize_t y, MagickPixelPacket *pixel, ExceptionInfo *exception)
MagickExport MagickBooleanType GetOneVirtualMethodPixel (const Image *image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, PixelPacket *pixel, ExceptionInfo *exception)
MagickExport MagickBooleanType GetOneVirtualPixel (const Image *image, const ssize_t x, const ssize_t y, PixelPacket *pixel, ExceptionInfo *exception)
MagickExport size_t GetPixelCacheChannels (const Cache cache)
MagickExport ColorspaceType GetPixelCacheColorspace (const Cache cache)
MagickExport const char * GetPixelCacheFilename (const Image *image)
MagickExport void GetPixelCacheMethods (CacheMethods *cache_methods)
MagickExport MagickSizeType GetPixelCacheNexusExtent (const Cache cache, NexusInfo *nexus_info)
MagickExport void * GetPixelCachePixels (Image *image, MagickSizeType *length, ExceptionInfo *exception)
MagickExport ClassType GetPixelCacheStorageClass (const Cache cache)
MagickExport void GetPixelCacheTileSize (const Image *image, size_t *width, size_t *height)
MagickExport VirtualPixelMethod GetPixelCacheVirtualMethod (const Image *image)
MagickExport const IndexPacket * GetVirtualIndexesFromNexus (const Cache cache, NexusInfo *nexus_info)
MagickExport const IndexPacket * GetVirtualIndexQueue (const Image *image)
static ssize_t DitherX (const ssize_t x, const size_t columns)
static ssize_t DitherY (const ssize_t y, const size_t rows)
static ssize_t EdgeX (const ssize_t x, const size_t columns)
static ssize_t EdgeY (const ssize_t y, const size_t rows)
static ssize_t RandomX (RandomInfo *random_info, const size_t columns)
static ssize_t RandomY (RandomInfo *random_info, const size_t rows)
static MagickModulo VirtualPixelModulo (const ssize_t offset, const size_t extent)
MagickExport const PixelPacket * GetVirtualPixelCacheNexus (const Image *image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, NexusInfo *nexus_info, ExceptionInfo *exception)
MagickExport const PixelPacket * GetVirtualPixelQueue (const Image *image)
MagickExport const PixelPacket * GetVirtualPixels (const Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport const PixelPacket * GetVirtualPixelsNexus (const Cache cache, NexusInfo *nexus_info)
static void ApplyPixelCompositeMask (const MagickPixelPacket *p, const MagickRealType alpha, const MagickPixelPacket *q, const MagickRealType beta, MagickPixelPacket *composite)
static MagickBooleanType MaskPixelCacheNexus (Image *image, NexusInfo *nexus_info, ExceptionInfo *exception)
static MagickOffsetType WritePixelCacheRegion (const CacheInfo *magick_restrict cache_info, const MagickOffsetType offset, const MagickSizeType length, const unsigned char *magick_restrict buffer)
static MagickBooleanType SetPixelCacheExtent (Image *image, MagickSizeType length)
MagickExport MagickBooleanType PersistPixelCache (Image *image, const char *filename, const MagickBooleanType attach, MagickOffsetType *offset, ExceptionInfo *exception)
MagickExport PixelPacket * QueueAuthenticPixel (Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, const MagickBooleanType clone, NexusInfo *nexus_info, ExceptionInfo *exception)
MagickExport PixelPacket * QueueAuthenticPixelCacheNexus (Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, const MagickBooleanType clone, NexusInfo *nexus_info, ExceptionInfo *exception)
MagickExport PixelPacket * QueueAuthenticPixels (Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
static MagickOffsetType ReadPixelCacheRegion (const CacheInfo *magick_restrict cache_info, const MagickOffsetType offset, const MagickSizeType length, unsigned char *magick_restrict buffer)
static MagickBooleanType ReadPixelCacheIndexes (CacheInfo *magick_restrict cache_info, NexusInfo *magick_restrict nexus_info, ExceptionInfo *exception)
static MagickBooleanType ReadPixelCachePixels (CacheInfo *magick_restrict cache_info, NexusInfo *magick_restrict nexus_info, ExceptionInfo *exception)
MagickExport Cache ReferencePixelCache (Cache cache)
MagickPrivate void ResetPixelCacheEpoch (void)
MagickExport void SetPixelCacheMethods (Cache cache, CacheMethods *cache_methods)
static MagickBooleanType AcquireCacheNexusPixels (const CacheInfo *magick_restrict cache_info, const MagickSizeType length, NexusInfo *magick_restrict nexus_info, ExceptionInfo *exception)
static void PrefetchPixelCacheNexusPixels (const NexusInfo *nexus_info, const MapMode mode)
static MagickBooleanType ValidatePixelOffset (const ssize_t x, const size_t a)
static PixelPacket * SetPixelCacheNexusPixels (const CacheInfo *magick_restrict cache_info, const MapMode mode, const ssize_t x, const ssize_t y, const size_t width, const size_t height, const MagickBooleanType buffered, NexusInfo *magick_restrict nexus_info, ExceptionInfo *exception)
static MagickBooleanType SetCacheAlphaChannel (Image *image, const Quantum opacity)
MagickExport VirtualPixelMethod SetPixelCacheVirtualMethod (const Image *image, const VirtualPixelMethod virtual_pixel_method)
MagickExport MagickBooleanType SyncAuthenticPixelCacheNexus (Image *image, NexusInfo *magick_restrict nexus_info, ExceptionInfo *exception)
MagickExport MagickBooleanType SyncAuthenticPixels (Image *image, ExceptionInfo *exception)
MagickPrivate MagickBooleanType SyncImagePixelCache (Image *image, ExceptionInfo *exception)
static MagickBooleanType WritePixelCacheIndexes (CacheInfo *cache_info, NexusInfo *magick_restrict nexus_info, ExceptionInfo *exception)
static MagickBooleanType WritePixelCachePixels (CacheInfo *cache_info, NexusInfo *magick_restrict nexus_info, ExceptionInfo *exception)
Variables
static SemaphoreInfo * cache_semaphore = (SemaphoreInfo *) NULL
static ssize_t cache_anonymous_memory = (-1)
static time_t cache_epoch = 0
static ssize_t DitherMatrix [64]
Macro Definition Documentation
cache_number_threads
#define cache_number_threads (source, destination, chunk, multithreaded)
Value:
  num_threads((multithreaded) == 0 ? 1 : \
    (((source)->type != MemoryCache) && ((source)->type != MapCache)) || \
    (((destination)->type != MemoryCache) && ((destination)->type != MapCache)) ? \
    MagickMax(MagickMin(GetMagickResourceLimit(ThreadResource),2),1) : \
    MagickMax(MagickMin((ssize_t) GetMagickResourceLimit(ThreadResource),(ssize_t) (chunk)/256),1))
CacheTick
#define CacheTick (offset, extent) QuantumTick((MagickOffsetType) offset,extent)
IsFileDescriptorLimitExceeded
#define IsFileDescriptorLimitExceeded ()
Value:
  (GetMagickResource(FileResource) > \
  GetMagickResourceLimit(FileResource) ? MagickTrue : MagickFalse)
MaxCacheThreads
#define MaxCacheThreads ((size_t) GetMagickResourceLimit(ThreadResource))
Typedef Documentation
MagickModulo
typedef struct _MagickModulo MagickModulo
Function Documentation
AcquireCacheNexusPixels()
static MagickBooleanType AcquireCacheNexusPixels (const CacheInfo *magick_restrict cache_info, const MagickSizeType length, NexusInfo *magick_restrict nexus_info, ExceptionInfo * exception) inline static
References AcquireAlignedMemory(), cache_anonymous_memory, GetMagickModule, IOMode, MagickAssumeAligned, MagickFalse, MagickTrue, MapBlob(), ResourceLimitError, and ThrowMagickException().
Referenced by SetPixelCacheNexusPixels().
AcquirePixelCache()
MagickExport Cache AcquirePixelCache (const size_t number_threads)
References AcquireAlignedMemory(), AcquirePixelCacheNexus(), AllocateSemaphoreInfo(), DestroyString(), GetEnvironmentValue(), GetMagickResourceLimit(), GetMagickThreadId(), GetOpenMPMaximumThreads(), GetPolicyValue(), HeightResource, IOMode, IsEventLogging(), IsStringTrue(), magick_restrict, MAGICK_SSIZE_MAX, MagickCoreSignature, MagickMin, ResourceLimitFatalError, sRGBColorspace, ThreadResource, ThrowFatalException, UndefinedCache, and WidthResource.
Referenced by ClonePixelCache().
AcquirePixelCacheNexus()
MagickExport NexusInfo ** AcquirePixelCacheNexus (const size_t number_threads)
References AcquireAlignedMemory(), AcquireQuantumMemory(), magick_restrict, MagickAssumeAligned, MagickCoreSignature, ResourceLimitFatalError, and ThrowFatalException.
Referenced by AcquirePixelCache(), ClipPixelCacheNexus(), ClonePixelCacheRepository(), and MaskPixelCacheNexus().
AcquirePixelCachePixels()
MagickExport const void * AcquirePixelCachePixels (const Image * image, MagickSizeType * length, ExceptionInfo * exception)
References _Image::cache, magick_restrict, MagickCoreSignature, MapCache, MemoryCache, _ExceptionInfo::signature, and _Image::signature.
Referenced by ResetImagePixels().
ApplyPixelCompositeMask()
static void ApplyPixelCompositeMask (const MagickPixelPacket * p, const MagickRealType alpha, const MagickPixelPacket * q, const MagickRealType beta, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, MagickEpsilon, MagickOver_(), PerceptibleReciprocal(), QuantumScale, _MagickPixelPacket::red, and TransparentOpacity.
Referenced by MaskPixelCacheNexus().
CacheComponentGenesis()
MagickExport MagickBooleanType CacheComponentGenesis (void)
References AllocateSemaphoreInfo(), cache_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
CacheComponentTerminus()
MagickExport void CacheComponentTerminus (void)
References ActivateSemaphoreInfo(), cache_semaphore, and DestroySemaphoreInfo().
Referenced by MagickCoreTerminus().
ClipPixelCacheNexus()
static MagickBooleanType ClipPixelCacheNexus (Image * image, NexusInfo * nexus_info, ExceptionInfo * exception) static
References AcquirePixelCacheNexus(), _Image::cache, _Image::clip_mask, _Image::debug, DestroyPixelCacheNexus(), _Image::filename, GetAuthenticPixelCacheNexus(), GetMagickModule, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetVirtualPixelCacheNexus(), _RectangleInfo::height, _NexusInfo::indexes, LogMagickEvent(), magick_restrict, MagickEpsilon, MagickFalse, MagickOver_(), MagickTrue, MaskVirtualPixelMethod, _NexusInfo::pixels, PseudoClass, QuantumScale, _NexusInfo::region, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _Image::storage_class, TraceEvent, _NexusInfo::virtual_nexus, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by SyncAuthenticPixelCacheNexus().
ClonePixelCache()
MagickExport Cache ClonePixelCache (const Cache cache)
References AcquirePixelCache(), GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, and TraceEvent.
Referenced by GetImagePixelCache(), and PersistPixelCache().
ClonePixelCacheMethods()
MagickExport void ClonePixelCacheMethods (Cache clone, const Cache cache)
References GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, and TraceEvent.
ClonePixelCacheOnDisk()
static MagickBooleanType ClonePixelCacheOnDisk (CacheInfo *magick_restrict cache_info, CacheInfo *magick_restrict clone_info) static
References AcquireQuantumMemory(), IOMode, MagickFalse, MagickMaxBufferExtent, MagickMin, MagickTrue, OpenPixelCacheOnDisk(), ReadMode, RelinquishMagickMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by ClonePixelCacheRepository().
ClonePixelCacheRepository()
static MagickBooleanType ClonePixelCacheRepository (CacheInfo *magick_restrict clone_info, CacheInfo *magick_restrict cache_info, ExceptionInfo * exception) static
References AcquirePixelCacheNexus(), CacheEvent, ClonePixelCacheOnDisk(), CommandOptionToMnemonic(), DestroyPixelCacheNexus(), DiskCache, FormatLocaleString(), GetMagickModule, GetOpenMPThreadId(), LogMagickEvent(), magick_restrict, MagickCacheOptions, MagickFalse, MagickMin, MagickTrue, MapCache, MaxTextExtent, MemoryCache, PingCache, ReadMode, ReadPixelCacheIndexes(), ReadPixelCachePixels(), SetPixelCacheNexusPixels(), WriteMode, WritePixelCacheIndexes(), and WritePixelCachePixels().
Referenced by GetImagePixelCache(), OpenPixelCache(), and PersistPixelCache().
ClosePixelCacheOnDisk()
static MagickBooleanType ClosePixelCacheOnDisk (CacheInfo * cache_info) static
References _CacheInfo::file, FileResource, MagickFalse, MagickTrue, and RelinquishMagickResource().
Referenced by GetImagePixelCache(), OpenPixelCache(), OpenPixelCacheOnDisk(), ReadPixelCacheIndexes(), ReadPixelCachePixels(), RelinquishPixelCachePixels(), WritePixelCacheIndexes(), and WritePixelCachePixels().
DestroyImagePixelCache()
static void DestroyImagePixelCache (Image * image) static
References _Image::cache, _Image::debug, DestroyPixelCache(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
Referenced by GetPixelCacheMethods().
DestroyImagePixels()
MagickExport void DestroyImagePixels (Image * image)
References _Image::cache, _Image::debug, DestroyPixelCache(), _Image::filename, GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
Referenced by DestroyImage().
DestroyPixelCache()
MagickExport Cache DestroyPixelCache (Cache cache)
References CacheEvent, DestroyDistributeCacheInfo(), DestroyPixelCacheNexus(), DestroyRandomInfo(), DestroySemaphoreInfo(), FormatLocaleString(), GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MaxTextExtent, RelinquishAlignedMemory(), RelinquishPixelCachePixels(), TraceEvent, and UnlockSemaphoreInfo().
Referenced by DestroyImagePixelCache(), DestroyImagePixels(), GetImagePixelCache(), and PersistPixelCache().
DestroyPixelCacheNexus()
MagickExport NexusInfo ** DestroyPixelCacheNexus (NexusInfo ** nexus_info, const size_t number_threads)
References RelinquishAlignedMemory(), RelinquishCacheNexusPixels(), RelinquishMagickMemory(), and _NexusInfo::signature.
Referenced by ClipPixelCacheNexus(), ClonePixelCacheRepository(), DestroyCacheView(), DestroyPixelCache(), DestroyPixelStream(), and MaskPixelCacheNexus().
DitherX()
static ssize_t DitherX (const ssize_t x, const size_t columns) inline static
References DitherMatrix.
Referenced by GetVirtualPixelCacheNexus().
DitherY()
static ssize_t DitherY (const ssize_t y, const size_t rows) inline static
References DitherMatrix.
Referenced by GetVirtualPixelCacheNexus().
EdgeX()
static ssize_t EdgeX (const ssize_t x, const size_t columns) inline static
Referenced by GetVirtualPixelCacheNexus().
EdgeY()
static ssize_t EdgeY (const ssize_t y, const size_t rows) inline static
Referenced by GetVirtualPixelCacheNexus().
GetAuthenticIndexesFromCache()
static IndexPacket * GetAuthenticIndexesFromCache (const Image * image) static
References _Image::cache, GetOpenMPThreadId(), magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by GetPixelCacheMethods().
GetAuthenticIndexQueue()
MagickExport IndexPacket * GetAuthenticIndexQueue (const Image * image)
References _Image::cache, GetOpenMPThreadId(), magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by GetIndexes(), ImportCharPixel(), ImportDoublePixel(), ImportFloatPixel(), ImportIntegerPixel(), ImportLongPixel(), ImportQuantumPixel(), ImportQuantumPixels(), ImportShortPixel(), RandomChannelThresholdImage(), SetImage(), ThresholdImage(), ThresholdImageChannel(), and WriteDistributeCacheIndexes().
GetAuthenticPixelCacheNexus()
MagickExport PixelPacket * GetAuthenticPixelCacheNexus (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, NexusInfo * nexus_info, ExceptionInfo * exception)
References _NexusInfo::authentic_pixel_cache, _Image::cache, magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, QueueAuthenticPixelCacheNexus(), ReadPixelCacheIndexes(), ReadPixelCachePixels(), and _Image::signature.
Referenced by ClipPixelCacheNexus(), GetAuthenticPixels(), GetAuthenticPixelsCache(), GetOneAuthenticPixelFromCache(), and MaskPixelCacheNexus().
GetAuthenticPixelQueue()
MagickExport PixelPacket * GetAuthenticPixelQueue (const Image * image)
References _Image::cache, GetOpenMPThreadId(), magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by ExportQuantumPixels(), GetPixels(), ImportQuantumPixels(), and StreamImagePixels().
GetAuthenticPixels()
MagickExport PixelPacket * GetAuthenticPixels (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception)
References _Image::cache, GetAuthenticPixelCacheNexus(), GetOpenMPThreadId(), magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by ClearBounds(), ColorFloodfillImage(), GetImagePixels(), ImportCharPixel(), ImportDoublePixel(), ImportFloatPixel(), ImportIntegerPixel(), ImportLongPixel(), ImportQuantumPixel(), ImportShortPixel(), MatteFloodfillImage(), OpaqueImage(), RandomChannelThresholdImage(), ThresholdImage(), ThresholdImageChannel(), TransparentImage(), WriteDistributeCacheIndexes(), and WriteDistributeCachePixels().
GetAuthenticPixelsCache()
static PixelPacket * GetAuthenticPixelsCache (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception) static
References _Image::cache, GetAuthenticPixelCacheNexus(), GetOpenMPThreadId(), magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by GetOneAuthenticPixel(), and GetPixelCacheMethods().
GetAuthenticPixelsFromCache()
static PixelPacket * GetAuthenticPixelsFromCache (const Image * image) static
References _Image::cache, GetOpenMPThreadId(), magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by GetPixelCacheMethods().
GetImageExtent()
MagickExport MagickSizeType GetImageExtent (const Image * image)
References _Image::cache, _Image::debug, _Image::filename, GetMagickModule, GetOpenMPThreadId(), GetPixelCacheNexusExtent(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
Referenced by ExportQuantumPixels(), ImportQuantumPixels(), and StreamImagePixels().
GetImagePixelCache()
static Cache GetImagePixelCache (Image * image, const MagickBooleanType clone, ExceptionInfo * exception) static
References AllocateSemaphoreInfo(), _Image::cache, cache_epoch, ClonePixelCache(), ClonePixelCacheRepository(), ClosePixelCacheOnDisk(), DestroyPixelCache(), DestroySemaphoreInfo(), GetMagickResourceLimit(), GetMagickTime(), IOMode, LockSemaphoreInfo(), magick_restrict, MagickDelay(), MagickFalse, MagickResourceInfinity, MagickTrue, OpenPixelCache(), ReadMode, _Image::reference_count, ResourceLimitFatalError, _Image::semaphore, ThrottleResource, ThrowFatalException, TimeResource, _Image::type, UndefinedType, UnlockSemaphoreInfo(), and ValidatePixelCacheMorphology().
Referenced by QueueAuthenticPixelCacheNexus(), and SyncImagePixelCache().
GetImagePixelCacheType()
MagickExport CacheType GetImagePixelCacheType (const Image * image)
References _Image::cache, magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by GetPixelCacheTileSize(), and GetPixelCacheType().
GetOneAuthenticPixel()
MagickExport MagickBooleanType GetOneAuthenticPixel (Image * image, const ssize_t x, const ssize_t y, PixelPacket * pixel, ExceptionInfo * exception)
References _Image::background_color, _Image::cache, GetAuthenticPixelsCache(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, and _Image::signature.
Referenced by GetOnePixel().
GetOneAuthenticPixelFromCache()
static MagickBooleanType GetOneAuthenticPixelFromCache (Image * image, const ssize_t x, const ssize_t y, PixelPacket * pixel, ExceptionInfo * exception) static
References _Image::background_color, _Image::cache, GetAuthenticPixelCacheNexus(), GetOpenMPThreadId(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, and _Image::signature.
Referenced by GetPixelCacheMethods().
GetOneVirtualMagickPixel()
MagickExport MagickBooleanType GetOneVirtualMagickPixel (const Image * image, const ssize_t x, const ssize_t y, MagickPixelPacket * pixel, ExceptionInfo * exception)
References _Image::cache, GetMagickPixelPacket(), GetOpenMPThreadId(), GetPixelCacheVirtualMethod(), GetVirtualIndexesFromNexus(), GetVirtualPixelCacheNexus(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, SetMagickPixelPacket(), and _Image::signature.
Referenced by AcquireOneMagickPixel(), CompositeImageChannel(), and DrawPrimitive().
GetOneVirtualMethodPixel()
MagickExport MagickBooleanType GetOneVirtualMethodPixel (const Image * image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, PixelPacket * pixel, ExceptionInfo * exception)
References _Image::background_color, _Image::cache, GetOpenMPThreadId(), GetVirtualPixelCacheNexus(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, and _Image::signature.
Referenced by AcquireOneVirtualPixel(), GetFillColor(), and GetStrokeColor().
GetOneVirtualPixel()
MagickExport MagickBooleanType GetOneVirtualPixel (const Image * image, const ssize_t x, const ssize_t y, PixelPacket * pixel, ExceptionInfo * exception)
References _Image::background_color, _Image::cache, GetOpenMPThreadId(), GetPixelCacheVirtualMethod(), GetVirtualPixelCacheNexus(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, and _Image::signature.
Referenced by AcquireOnePixel().
GetOneVirtualPixelFromCache()
static MagickBooleanType GetOneVirtualPixelFromCache (const Image * image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, PixelPacket * pixel, ExceptionInfo * exception)
References _Image::background_color, _Image::cache, GetOpenMPThreadId(), GetVirtualPixelCacheNexus(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, and _Image::signature.
Referenced by GetPixelCacheMethods().
GetPixelCacheChannels()
MagickExport size_t GetPixelCacheChannels (const Cache cache)
References GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, and TraceEvent.
Referenced by GetCacheViewChannels().
GetPixelCacheColorspace()
MagickExport ColorspaceType GetPixelCacheColorspace (const Cache cache)
References GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, and TraceEvent.
Referenced by GetCacheViewColorspace().
GetPixelCacheFilename()
MagickExport const char * GetPixelCacheFilename (const Image * image)
References _Image::cache, magick_restrict, MagickCoreSignature, and _Image::signature.
GetPixelCacheMethods()
MagickExport void GetPixelCacheMethods (CacheMethods * cache_methods)
References _CacheMethods::destroy_pixel_handler, DestroyImagePixelCache(), _CacheMethods::get_authentic_indexes_from_handler, _CacheMethods::get_authentic_pixels_from_handler, _CacheMethods::get_authentic_pixels_handler, _CacheMethods::get_one_authentic_pixel_from_handler, _CacheMethods::get_one_virtual_pixel_from_handler, _CacheMethods::get_virtual_indexes_from_handler, _CacheMethods::get_virtual_pixel_handler, _CacheMethods::get_virtual_pixels_handler, GetAuthenticIndexesFromCache(), GetAuthenticPixelsCache(), GetAuthenticPixelsFromCache(), GetOneAuthenticPixelFromCache(), GetOneVirtualPixelFromCache(), GetVirtualIndexesFromCache(), GetVirtualPixelCache(), GetVirtualPixelsCache(), _CacheMethods::queue_authentic_pixels_handler, QueueAuthenticPixelsCache(), _CacheMethods::sync_authentic_pixels_handler, and SyncAuthenticPixelsCache().
GetPixelCacheNexusExtent()
MagickExport MagickSizeType GetPixelCacheNexusExtent (const Cache cache, NexusInfo * nexus_info)
References _RectangleInfo::height, magick_restrict, MagickCoreSignature, _NexusInfo::region, and _RectangleInfo::width.
Referenced by GetCacheViewExtent(), and GetImageExtent().
GetPixelCachePixels()
MagickExport void * GetPixelCachePixels (Image * image, MagickSizeType * length, ExceptionInfo * exception)
References _Image::cache, magick_restrict, MagickCoreSignature, MapCache, MemoryCache, _ExceptionInfo::signature, and _Image::signature.
GetPixelCacheStorageClass()
MagickExport ClassType GetPixelCacheStorageClass (const Cache cache)
References GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, and TraceEvent.
Referenced by GetCacheViewStorageClass().
GetPixelCacheTileSize()
MagickExport void GetPixelCacheTileSize (const Image * image, size_t * width, size_t * height)
References _Image::debug, DiskCache, _Image::filename, GetImagePixelCacheType(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
GetPixelCacheType()
MagickExport CacheType GetPixelCacheType (const Image * image)
References GetImagePixelCacheType().
GetPixelCacheVirtualMethod()
MagickExport VirtualPixelMethod GetPixelCacheVirtualMethod (const Image * image)
References _Image::cache, magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by GetImageVirtualPixelMethod(), GetOneVirtualMagickPixel(), GetOneVirtualPixel(), and GetVirtualPixels().
GetVirtualIndexesFromCache()
static const IndexPacket * GetVirtualIndexesFromCache (const Image * image) static
References _Image::cache, GetOpenMPThreadId(), GetVirtualIndexesFromNexus(), magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by GetPixelCacheMethods().
GetVirtualIndexesFromNexus()
MagickExport const IndexPacket * GetVirtualIndexesFromNexus (const Cache cache, NexusInfo * nexus_info)
References _NexusInfo::indexes, magick_restrict, MagickCoreSignature, and UndefinedClass.
Referenced by GetCacheViewVirtualIndexQueue(), GetOneVirtualMagickPixel(), GetVirtualIndexesFromCache(), GetVirtualIndexQueue(), and GetVirtualPixelCacheNexus().
GetVirtualIndexQueue()
MagickExport const IndexPacket * GetVirtualIndexQueue (const Image * image)
References _Image::cache, GetOpenMPThreadId(), GetVirtualIndexesFromNexus(), magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by AcquireIndexes(), CompareImageBounds(), ExportCharPixel(), ExportDoublePixel(), ExportFloatPixel(), ExportIntegerPixel(), ExportLongPixel(), ExportQuantumPixel(), ExportQuantumPixels(), ExportShortPixel(), GetImageChannelKurtosis(), GetImageChannelMoments(), GetImageChannelRange(), GetImageChannelStatistics(), GetLocationStatistics(), IdentifyImage(), InterpolateMagickPixelPacket(), InterpolatePixelColor(), ReadDistributeCacheIndexes(), and StreamImagePixels().
GetVirtualPixelCache()
static const PixelPacket * GetVirtualPixelCache (const Image * image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception) static
References _Image::cache, GetOpenMPThreadId(), GetVirtualPixelCacheNexus(), magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by GetPixelCacheMethods().
GetVirtualPixelCacheNexus()
MagickExport const PixelPacket * GetVirtualPixelCacheNexus (const Image * image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, NexusInfo * nexus_info, ExceptionInfo * exception)
References AcquireRandomInfo(), _NexusInfo::authentic_pixel_cache, _Image::background_color, BackgroundVirtualPixelMethod, BlackVirtualPixelMethod, _Image::cache, CheckerTileVirtualPixelMethod, _Image::clip_mask, CMYKColorspace, ConstantVirtualPixelMethod, DitherVirtualPixelMethod, DitherX(), DitherY(), EdgeVirtualPixelMethod, EdgeX(), EdgeY(), GetVirtualIndexesFromNexus(), GetVirtualPixelCacheNexus(), GrayVirtualPixelMethod, _RectangleInfo::height, HorizontalTileEdgeVirtualPixelMethod, HorizontalTileVirtualPixelMethod, _NexusInfo::indexes, magick_restrict, MagickCoreSignature, MagickFalse, MagickMin, MagickTrue, _Image::mask, MaskVirtualPixelMethod, MirrorVirtualPixelMethod, OpaqueOpacity, PseudoClass, QuantumRange, _MagickModulo::quotient, RandomVirtualPixelMethod, RandomX(), RandomY(), ReadMode, ReadPixelCacheIndexes(), ReadPixelCachePixels(), _NexusInfo::region, _MagickModulo::remainder, SetPixelBlue, SetPixelCacheNexusPixels(), SetPixelGreen, SetPixelOpacity, SetPixelRed, _Image::signature, TileVirtualPixelMethod, TransparentOpacity, TransparentVirtualPixelMethod, UndefinedCache, UndefinedVirtualPixelMethod, VerticalTileEdgeVirtualPixelMethod, VerticalTileVirtualPixelMethod, _NexusInfo::virtual_nexus, VirtualPixelModulo(), WhiteVirtualPixelMethod, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by ClipPixelCacheNexus(), GetOneVirtualMagickPixel(), GetOneVirtualMethodPixel(), GetOneVirtualPixel(), GetOneVirtualPixelFromCache(), GetVirtualPixelCache(), GetVirtualPixelCacheNexus(), GetVirtualPixels(), and MaskPixelCacheNexus().
GetVirtualPixelQueue()
MagickExport const PixelPacket * GetVirtualPixelQueue (const Image * image)
References _Image::cache, GetOpenMPThreadId(), GetVirtualPixelsNexus(), magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by AcquirePixels(), and ExportQuantumPixels().
GetVirtualPixels()
MagickExport const PixelPacket * GetVirtualPixels (const Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception)
References _Image::cache, GetOpenMPThreadId(), GetPixelCacheVirtualMethod(), GetVirtualPixelCacheNexus(), magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by AcquireImagePixels(), ColorFloodfillImage(), CompareImageBounds(), ExportCharPixel(), ExportDoublePixel(), ExportFloatPixel(), ExportIntegerPixel(), ExportLongPixel(), ExportQuantumPixel(), ExportShortPixel(), GetImageChannelKurtosis(), GetImageChannelMoments(), GetImageChannelRange(), GetImageChannelStatistics(), GetImageDynamicThreshold(), GetLocationStatistics(), HuffmanEncodeImage(), IdentifyImage(), InitializeHistogram(), InterpolatePixelColor(), IsBoundsCleared(), LinearStretchImage(), MatteFloodfillImage(), PrintChannelLocations(), ReadDistributeCacheIndexes(), ReadDistributeCachePixels(), and StereoAnaglyphImage().
GetVirtualPixelsCache()
static const PixelPacket * GetVirtualPixelsCache (const Image * image)
References _Image::cache, GetOpenMPThreadId(), GetVirtualPixelsNexus(), magick_restrict, MagickCoreSignature, and _Image::signature.
Referenced by GetPixelCacheMethods().
GetVirtualPixelsNexus()
MagickExport const PixelPacket * GetVirtualPixelsNexus (const Cache cache, NexusInfo * nexus_info)
References magick_restrict, MagickCoreSignature, _NexusInfo::pixels, and UndefinedClass.
Referenced by GetCacheViewVirtualPixelQueue(), GetVirtualPixelQueue(), and GetVirtualPixelsCache().
MaskPixelCacheNexus()
static MagickBooleanType MaskPixelCacheNexus (Image * image, NexusInfo * nexus_info, ExceptionInfo * exception) static
References AcquirePixelCacheNexus(), ApplyPixelCompositeMask(), _MagickPixelPacket::blue, _Image::cache, ClampToQuantum(), _Image::debug, DestroyPixelCacheNexus(), _Image::exception, _Image::filename, GetAuthenticPixelCacheNexus(), GetMagickModule, GetMagickPixelPacket(), GetPixelIndex, GetPixelIntensity(), GetVirtualPixelCacheNexus(), _MagickPixelPacket::green, _RectangleInfo::height, _NexusInfo::indexes, LogMagickEvent(), magick_restrict, MagickFalse, MagickTrue, _Image::mask, MaskVirtualPixelMethod, _MagickPixelPacket::opacity, _NexusInfo::pixels, PseudoClass, _MagickPixelPacket::red, _NexusInfo::region, SetMagickPixelPacket(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _Image::storage_class, TraceEvent, _NexusInfo::virtual_nexus, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by SyncAuthenticPixelCacheNexus().
OpenPixelCache()
static MagickBooleanType OpenPixelCache (Image * image, const MapMode mode, ExceptionInfo * exception)
References AcquireAlignedMemory(), AcquireDistributeCacheInfo(), AcquireMagickResource(), AreaResource, _Image::cache, cache_anonymous_memory, CacheError, CacheEvent, _Image::channels, ClonePixelCacheRepository(), ClosePixelCacheOnDisk(), CMYKColorspace, _Image::colorspace, _Image::columns, CommandOptionToMnemonic(), _Image::debug, DestroyDistributeCacheInfo(), DestroyString(), DiskCache, DiskResource, DistributedCache, _Image::filename, FormatLocaleString(), FormatMagickSize(), GetDistributeCacheFile(), GetDistributeCacheHostname(), GetDistributeCachePort(), GetImageListLength(), GetImageRegistry(), GetMagickModule, GetMagickResourceLimit(), GetPolicyValue(), ImageError, IOMode, ListLengthResource, LocaleCompare(), LogMagickEvent(), magick_restrict, MagickAssumeAligned, MagickCacheOptions, MagickCoreSignature, MagickFalse, MagickResourceInfinity, MagickTrue, MapBlob(), MapCache, MapResource, MaxTextExtent, MemoryCache, MemoryResource, MissingDelegateError, _Image::offset, OpenDistributePixelCache(), OpenPixelCacheOnDisk(), PersistMode, _Image::ping, PingCache, PseudoClass, ReadMode, RelinquishMagickResource(), RelinquishPixelCachePixels(), ResourceLimitError, _Image::rows, _Image::scene, SetPixelCacheExtent(), _Image::signature, _Image::storage_class, StringRegistryType, ThrowBinaryException, ThrowFileException, ThrowMagickException(), TraceEvent, UndefinedCache, and UndefinedClass.
Referenced by GetImagePixelCache(), and PersistPixelCache().
OpenPixelCacheOnDisk()
static MagickBooleanType OpenPixelCacheOnDisk (CacheInfo * cache_info, const MapMode mode)
References AcquireMagickResource(), AcquireUniqueFileResource(), _CacheInfo::cache_filename, ClosePixelCacheOnDisk(), _CacheInfo::disk_mode, _CacheInfo::file, FileResource, IOMode, MagickFalse, MagickTrue, O_BINARY, open_utf8(), ReadMode, S_MODE, and WriteMode.
Referenced by ClonePixelCacheOnDisk(), OpenPixelCache(), ReadPixelCacheIndexes(), ReadPixelCachePixels(), WritePixelCacheIndexes(), and WritePixelCachePixels().
PersistPixelCache()
MagickExport MagickBooleanType PersistPixelCache (Image * image, const char * filename, const MagickBooleanType attach, MagickOffsetType * offset, ExceptionInfo * exception)
References AcquireMagickResource(), _Image::cache, CacheError, CacheEvent, ClonePixelCache(), ClonePixelCacheRepository(), CopyMagickString(), _Image::debug, DestroyPixelCache(), DiskCache, DiskResource, _Image::filename, GetMagickModule, GetMagickPageSize(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, MapCache, MaxTextExtent, OpenPixelCache(), PersistMode, ReadMode, _Image::signature, ThrowMagickException(), and TraceEvent.
PrefetchPixelCacheNexusPixels()
static void PrefetchPixelCacheNexusPixels (const NexusInfo * nexus_info, const MapMode mode) inline static
References CACHE_LINE_SIZE, _NexusInfo::length, MagickCachePrefetch, _NexusInfo::pixels, and ReadMode.
Referenced by SetPixelCacheNexusPixels().
QueueAuthenticPixel()
MagickExport PixelPacket * QueueAuthenticPixel (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, const MagickBooleanType clone, NexusInfo * nexus_info, ExceptionInfo * exception)
References QueueAuthenticPixelCacheNexus().
QueueAuthenticPixelCacheNexus()
MagickExport PixelPacket * QueueAuthenticPixelCacheNexus (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, const MagickBooleanType clone, NexusInfo * nexus_info, ExceptionInfo * exception)
References _Image::cache, CacheError, _Image::clip_mask, _Image::filename, GetImagePixelCache(), GetMagickModule, magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::mask, SetPixelCacheNexusPixels(), _Image::signature, ThrowMagickException(), and WriteMode.
Referenced by GetAuthenticPixelCacheNexus(), QueueAuthenticPixel(), QueueAuthenticPixels(), QueueAuthenticPixelsCache(), and QueueCacheViewAuthenticPixels().
QueueAuthenticPixels()
MagickExport PixelPacket * QueueAuthenticPixels (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception)
References _Image::cache, GetOpenMPThreadId(), magick_restrict, MagickCoreSignature, MagickFalse, QueueAuthenticPixelCacheNexus(), and _Image::signature.
Referenced by SetImage(), SetImagePixels(), and StereoAnaglyphImage().
QueueAuthenticPixelsCache()
static PixelPacket * QueueAuthenticPixelsCache (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception)
References _Image::cache, GetOpenMPThreadId(), magick_restrict, MagickCoreSignature, MagickFalse, QueueAuthenticPixelCacheNexus(), and _Image::signature.
Referenced by GetPixelCacheMethods().
RandomX()
static ssize_t RandomX (RandomInfo * random_info, const size_t columns) inline static
References GetPseudoRandomValue(), and random_info.
Referenced by GetVirtualPixelCacheNexus().
RandomY()
static ssize_t RandomY (RandomInfo * random_info, const size_t rows) inline static
References GetPseudoRandomValue(), and random_info.
Referenced by GetVirtualPixelCacheNexus().
ReadPixelCacheIndexes() [1/2]
static MagickBooleanType ReadPixelCacheIndexes (CacheInfo *magick_restrict cache_info, NexusInfo *magick_restrict nexus_info, ExceptionInfo * exception) static
References CacheError, CacheEvent, CacheTick, ClosePixelCacheOnDisk(), DiskCache, DistributedCache, FileOpenError, GetMagickModule, _RectangleInfo::height, IOMode, IsFileDescriptorLimitExceeded, LockSemaphoreInfo(), LogMagickEvent(), magick_restrict, MagickFalse, MagickMaxBufferExtent, MagickTrue, MapCache, MemoryCache, OpenPixelCacheOnDisk(), ReadDistributePixelCacheIndexes(), ReadPixelCacheRegion(), ThrowFileException, UnlockSemaphoreInfo(), and _RectangleInfo::y.
ReadPixelCacheIndexes() [2/2]
static MagickBooleanType ReadPixelCacheIndexes (CacheInfo * magick_restrict, NexusInfo * magick_restrict, ExceptionInfo *)
Referenced by ClonePixelCacheRepository(), GetAuthenticPixelCacheNexus(), and GetVirtualPixelCacheNexus().
ReadPixelCachePixels() [1/2]
static MagickBooleanType ReadPixelCachePixels (CacheInfo *magick_restrict cache_info, NexusInfo *magick_restrict nexus_info, ExceptionInfo * exception) static
References CacheError, CacheEvent, CacheTick, ClosePixelCacheOnDisk(), DiskCache, DistributedCache, FileOpenError, GetMagickModule, _RectangleInfo::height, IOMode, IsFileDescriptorLimitExceeded, LockSemaphoreInfo(), LogMagickEvent(), magick_restrict, MagickFalse, MagickMaxBufferExtent, MagickTrue, MapCache, MemoryCache, OpenPixelCacheOnDisk(), ReadDistributePixelCachePixels(), ReadPixelCacheRegion(), ThrowFileException, UnlockSemaphoreInfo(), and _RectangleInfo::y.
ReadPixelCachePixels() [2/2]
static MagickBooleanType ReadPixelCachePixels (CacheInfo * magick_restrict, NexusInfo * magick_restrict, ExceptionInfo *)
Referenced by ClonePixelCacheRepository(), GetAuthenticPixelCacheNexus(), and GetVirtualPixelCacheNexus().
ReadPixelCacheRegion()
static MagickOffsetType ReadPixelCacheRegion (const CacheInfo *magick_restrict cache_info, const MagickOffsetType offset, const MagickSizeType length, unsigned char *magick_restrict buffer) inline static
References MAGICK_SSIZE_MAX, and MagickMin.
Referenced by ReadPixelCacheIndexes(), and ReadPixelCachePixels().
ReferencePixelCache()
MagickExport Cache ReferencePixelCache (Cache cache)
References LockSemaphoreInfo(), magick_restrict, MagickCoreSignature, and UnlockSemaphoreInfo().
Referenced by CloneImage(), and CloneImageInfo().
RelinquishCacheNexusPixels()
static void RelinquishCacheNexusPixels (NexusInfo * nexus_info) inline static
References _NexusInfo::cache, _NexusInfo::indexes, _NexusInfo::length, MagickFalse, _NexusInfo::mapped, _NexusInfo::pixels, RelinquishAlignedMemory(), and UnmapBlob().
Referenced by DestroyPixelCacheNexus(), and SetPixelCacheNexusPixels().
RelinquishPixelCachePixels()
static void RelinquishPixelCachePixels (CacheInfo * cache_info) inline static
References _CacheInfo::cache_filename, ClosePixelCacheOnDisk(), DiskCache, DiskResource, DistributedCache, _CacheInfo::file, _CacheInfo::indexes, _CacheInfo::length, MagickFalse, MapCache, _CacheInfo::mapped, MapResource, MemoryCache, MemoryResource, _CacheInfo::mode, PersistMode, _CacheInfo::pixels, ReadMode, RelinquishAlignedMemory(), RelinquishDistributePixelCache(), RelinquishMagickResource(), RelinquishUniqueFileResource(), _CacheInfo::server_info, _CacheInfo::type, UndefinedCache, and UnmapBlob().
Referenced by DestroyPixelCache(), and OpenPixelCache().
ResetPixelCacheEpoch()
MagickPrivate void ResetPixelCacheEpoch (void)
References cache_epoch.
Referenced by SetMagickResourceLimit().
SetCacheAlphaChannel()
static MagickBooleanType SetCacheAlphaChannel (Image * image, const Quantum opacity) static
References AcquireVirtualCacheView(), _Image::cache, _Image::columns, _Image::debug, DestroyCacheView(), _Image::exception, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _Image::rows, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by SetPixelCacheVirtualMethod().
SetPixelCacheExtent()
static MagickBooleanType SetPixelCacheExtent (Image * image, MagickSizeType length) static
References _Image::cache, CacheEvent, _Image::debug, FormatLocaleString(), FormatMagickSize(), GetMagickModule, LogMagickEvent(), magick_restrict, MagickFalse, MagickTrue, MaxTextExtent, and WritePixelCacheRegion().
Referenced by OpenPixelCache().
SetPixelCacheMethods()
MagickExport void SetPixelCacheMethods (Cache cache, CacheMethods * cache_methods)
References _CacheMethods::destroy_pixel_handler, _CacheMethods::get_authentic_indexes_from_handler, _CacheMethods::get_authentic_pixels_from_handler, _CacheMethods::get_authentic_pixels_handler, _CacheMethods::get_one_authentic_pixel_from_handler, _CacheMethods::get_one_virtual_pixel_from_handler, _CacheMethods::get_virtual_indexes_from_handler, _CacheMethods::get_virtual_pixel_handler, GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, _CacheMethods::queue_authentic_pixels_handler, _CacheMethods::sync_authentic_pixels_handler, and TraceEvent.
Referenced by ReadStream().
SetPixelCacheNexusPixels() [1/2]
static PixelPacket * SetPixelCacheNexusPixels (const CacheInfo *magick_restrict cache_info, const MapMode mode, const ssize_t x, const ssize_t y, const size_t width, const size_t height, const MagickBooleanType buffered, NexusInfo *magick_restrict nexus_info, ExceptionInfo * exception) static
References AcquireCacheNexusPixels(), CacheError, GetMagickModule, ImageError, _CacheInfo::indexes, MagickCoreSignature, MagickFalse, MagickMax, MagickTrue, MapCache, MemoryCache, PingCache, PrefetchPixelCacheNexusPixels(), RelinquishCacheNexusPixels(), ThrowMagickException(), UndefinedCache, and ValidatePixelOffset().
SetPixelCacheNexusPixels() [2/2]
static PixelPacket * SetPixelCacheNexusPixels (const CacheInfo * magick_restrict, const MapMode, const ssize_t, const ssize_t, const size_t, const size_t, const MagickBooleanType, NexusInfo * magick_restrict, ExceptionInfo *)
Referenced by ClonePixelCacheRepository(), GetVirtualPixelCacheNexus(), and QueueAuthenticPixelCacheNexus().
SetPixelCacheVirtualMethod()
MagickExport VirtualPixelMethod SetPixelCacheVirtualMethod (const Image * image, const VirtualPixelMethod virtual_pixel_method)
References _Image::background_color, BackgroundVirtualPixelMethod, _Image::cache, _Image::colorspace, _Image::columns, _Image::debug, _Image::filename, GetMagickModule, IsGrayColorspace(), IsPixelGray(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, _Image::matte, _PixelPacket::opacity, OpaqueOpacity, _Image::rows, SetCacheAlphaChannel(), SetImageColorspace(), _Image::signature, sRGBColorspace, TraceEvent, and TransparentVirtualPixelMethod.
Referenced by SetImageVirtualPixelMethod().
SyncAuthenticPixelCacheNexus()
MagickExport MagickBooleanType SyncAuthenticPixelCacheNexus (Image * image, NexusInfo *magick_restrict nexus_info, ExceptionInfo * exception)
References _Image::cache, CacheError, _Image::clip_mask, ClipPixelCacheNexus(), DirectClass, _Image::filename, magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::mask, MaskPixelCacheNexus(), _Image::signature, _Image::storage_class, _Image::taint, ThrowBinaryException, UndefinedCache, WritePixelCacheIndexes(), and WritePixelCachePixels().
Referenced by SyncAuthenticPixels(), and SyncAuthenticPixelsCache().
SyncAuthenticPixels()
MagickExport MagickBooleanType SyncAuthenticPixels (Image * image, ExceptionInfo * exception)
References _Image::cache, GetOpenMPThreadId(), magick_restrict, MagickCoreSignature, _Image::signature, and SyncAuthenticPixelCacheNexus().
Referenced by ClearBounds(), ColorFloodfillImage(), ImportCharPixel(), ImportDoublePixel(), ImportFloatPixel(), ImportIntegerPixel(), ImportLongPixel(), ImportQuantumPixel(), ImportShortPixel(), MatteFloodfillImage(), OpaqueImage(), RandomChannelThresholdImage(), SetImage(), StereoAnaglyphImage(), SyncImagePixels(), ThresholdImage(), ThresholdImageChannel(), TransparentImage(), WriteDistributeCacheIndexes(), and WriteDistributeCachePixels().
SyncAuthenticPixelsCache()
static MagickBooleanType SyncAuthenticPixelsCache (Image * image, ExceptionInfo * exception)
References _Image::cache, GetOpenMPThreadId(), magick_restrict, MagickCoreSignature, _Image::signature, and SyncAuthenticPixelCacheNexus().
Referenced by GetPixelCacheMethods().
SyncImagePixelCache()
MagickPrivate MagickBooleanType SyncImagePixelCache (Image * image, ExceptionInfo * exception)
References GetImagePixelCache(), magick_restrict, MagickFalse, and MagickTrue.
Referenced by OpenDistributeCache(), SetImageAlphaChannel(), SetImageColorspace(), SetImageExtent(), SetImageGray(), SetImageMonochrome(), and SetImageStorageClass().
ValidatePixelCacheMorphology()
static MagickBooleanType ValidatePixelCacheMorphology (const Image *magick_restrict image) inline static
References magick_restrict, MagickFalse, and MagickTrue.
Referenced by GetImagePixelCache().
ValidatePixelOffset()
static MagickBooleanType ValidatePixelOffset (const ssize_t x, const size_t a) inline static
References MAGICK_SSIZE_MAX, MAGICK_SSIZE_MIN, MagickFalse, and MagickTrue.
Referenced by SetPixelCacheNexusPixels().
VirtualPixelModulo()
static MagickModulo VirtualPixelModulo (const ssize_t offset, const size_t extent) inline static
References _MagickModulo::quotient, and _MagickModulo::remainder.
Referenced by GetVirtualPixelCacheNexus().
WritePixelCacheIndexes() [1/2]
static MagickBooleanType WritePixelCacheIndexes (CacheInfo * , NexusInfo * magick_restrict, ExceptionInfo *)
Referenced by ClonePixelCacheRepository(), and SyncAuthenticPixelCacheNexus().
WritePixelCacheIndexes() [2/2]
static MagickBooleanType WritePixelCacheIndexes (CacheInfo * cache_info, NexusInfo *magick_restrict nexus_info, ExceptionInfo * exception) static
References _CacheInfo::active_index_channel, _CacheInfo::cache_filename, CacheError, CacheEvent, CacheTick, ClosePixelCacheOnDisk(), _CacheInfo::columns, _CacheInfo::debug, DiskCache, DistributedCache, _CacheInfo::file_semaphore, _CacheInfo::filename, FileOpenError, GetMagickModule, _RectangleInfo::height, _CacheInfo::indexes, IOMode, IsFileDescriptorLimitExceeded, LockSemaphoreInfo(), LogMagickEvent(), magick_restrict, MagickFalse, MagickMaxBufferExtent, MagickTrue, MapCache, MemoryCache, _CacheInfo::offset, OpenPixelCacheOnDisk(), _CacheInfo::rows, _CacheInfo::server_info, ThrowFileException, _CacheInfo::type, UnlockSemaphoreInfo(), WriteDistributePixelCacheIndexes(), WritePixelCacheRegion(), and _RectangleInfo::y.
WritePixelCachePixels() [1/2]
static MagickBooleanType WritePixelCachePixels (CacheInfo * , NexusInfo * magick_restrict, ExceptionInfo *)
Referenced by ClonePixelCacheRepository(), and SyncAuthenticPixelCacheNexus().
WritePixelCachePixels() [2/2]
static MagickBooleanType WritePixelCachePixels (CacheInfo * cache_info, NexusInfo *magick_restrict nexus_info, ExceptionInfo * exception) static
References _CacheInfo::cache_filename, CacheError, CacheEvent, CacheTick, ClosePixelCacheOnDisk(), _CacheInfo::columns, _CacheInfo::debug, DiskCache, DistributedCache, _CacheInfo::file_semaphore, _CacheInfo::filename, FileOpenError, GetMagickModule, _RectangleInfo::height, IOMode, IsFileDescriptorLimitExceeded, LockSemaphoreInfo(), LogMagickEvent(), magick_restrict, MagickFalse, MagickMaxBufferExtent, MagickTrue, MapCache, MemoryCache, _CacheInfo::offset, OpenPixelCacheOnDisk(), _CacheInfo::pixels, _CacheInfo::rows, _CacheInfo::server_info, ThrowFileException, _CacheInfo::type, UnlockSemaphoreInfo(), WriteDistributePixelCachePixels(), WritePixelCacheRegion(), and _RectangleInfo::y.
WritePixelCacheRegion()
static MagickOffsetType WritePixelCacheRegion (const CacheInfo *magick_restrict cache_info, const MagickOffsetType offset, const MagickSizeType length, const unsigned char *magick_restrict buffer) inline static
References MAGICK_SSIZE_MAX, and MagickMin.
Referenced by SetPixelCacheExtent(), WritePixelCacheIndexes(), and WritePixelCachePixels().
Variable Documentation
cache_anonymous_memory
ssize_t cache_anonymous_memory = (-1) static
Referenced by AcquireCacheNexusPixels(), and OpenPixelCache().
cache_epoch
time_t cache_epoch = 0 static
Referenced by GetImagePixelCache(), and ResetPixelCacheEpoch().
cache_semaphore
SemaphoreInfo* cache_semaphore = (SemaphoreInfo *) NULL static
Referenced by CacheComponentGenesis(), and CacheComponentTerminus().
DitherMatrix
ssize_t DitherMatrix[64] static
Initial value:
=
  {
     0,  48,  12,  60,   3,  51,  15,  63,
    32,  16,  44,  28,  35,  19,  47,  31,
     8,  56,   4,  52,  11,  59,   7,  55,
    40,  24,  36,  20,  43,  27,  39,  23,
     2,  50,  14,  62,   1,  49,  13,  61,
    34,  18,  46,  30,  33,  17,  45,  29,
    10,  58,   6,  54,   9,  57,   5,  53,
    42,  26,  38,  22,  41,  25,  37,  21
  }
Referenced by DitherX(), and DitherY().