MagickCore: cache-view.c File Reference
cache-view.c File Reference
#include "magick/studio.h"
#include "magick/cache.h"
#include "magick/cache-private.h"
#include "magick/cache-view.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/memory-private.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/resource_.h"
#include "magick/string_.h"
#include "magick/thread-private.h"
Data Structures
struct _CacheView
Functions
MagickExport CacheView * AcquireAuthenticCacheView (const Image *image, ExceptionInfo *exception)
MagickExport CacheView * AcquireCacheView (const Image *image)
MagickExport CacheView * AcquireVirtualCacheView (const Image *image, ExceptionInfo *exception)
MagickExport CacheView * CloneCacheView (const CacheView *cache_view)
MagickExport CacheView * DestroyCacheView (CacheView *cache_view)
MagickExport size_t GetCacheViewChannels (const CacheView *cache_view)
MagickExport ColorspaceType GetCacheViewColorspace (const CacheView *cache_view)
MagickExport ExceptionInfo * GetCacheViewException (const CacheView *cache_view)
MagickExport MagickSizeType GetCacheViewExtent (const CacheView *cache_view)
MagickExport ClassType GetCacheViewStorageClass (const CacheView *cache_view)
MagickExport PixelPacket * GetCacheViewAuthenticPixels (CacheView *cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport MagickBooleanType GetOneCacheViewAuthenticPixel (const CacheView *magick_restrict cache_view, const ssize_t x, const ssize_t y, PixelPacket *magick_restrict pixel, ExceptionInfo *exception)
MagickExport IndexPacket * GetCacheViewAuthenticIndexQueue (CacheView *cache_view)
MagickExport PixelPacket * GetCacheViewAuthenticPixelQueue (CacheView *cache_view)
MagickExport const IndexPacket * GetCacheViewVirtualIndexQueue (const CacheView *cache_view)
MagickExport const PixelPacket * GetCacheViewVirtualPixelQueue (const CacheView *cache_view)
MagickExport const PixelPacket * GetCacheViewVirtualPixels (const CacheView *cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport MagickBooleanType GetOneCacheViewVirtualPixel (const CacheView *magick_restrict cache_view, const ssize_t x, const ssize_t y, PixelPacket *magick_restrict pixel, ExceptionInfo *exception)
MagickExport MagickBooleanType GetOneCacheViewVirtualMethodPixel (const CacheView *cache_view, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, PixelPacket *pixel, ExceptionInfo *exception)
MagickExport PixelPacket * QueueCacheViewAuthenticPixels (CacheView *cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport MagickBooleanType SetCacheViewStorageClass (CacheView *cache_view, const ClassType storage_class)
MagickExport MagickBooleanType SetCacheViewVirtualPixelMethod (CacheView *magick_restrict cache_view, const VirtualPixelMethod virtual_pixel_method)
MagickExport MagickBooleanType SyncCacheViewAuthenticPixels (CacheView *magick_restrict cache_view, ExceptionInfo *exception)
Function Documentation
AcquireAuthenticCacheView()
MagickExport CacheView * AcquireAuthenticCacheView (const Image * image, ExceptionInfo * exception)
References AcquireVirtualCacheView(), and magick_restrict.
Referenced by AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), AddNoiseImageChannel(), AppendImages(), AssignImageColors(), BilevelImageChannel(), BlackThresholdImageChannel(), BlueShiftImage(), CannyEdgeImage(), ChopImage(), ClampImageChannel(), Classify(), ClutImageChannel(), ColorDecisionListImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImageChannels(), ComplexImages(), CompositeImageChannel(), ConnectedComponentsImage(), ConsolidateCMYKImages(), ContrastImage(), ContrastStretchImageChannel(), CopyImagePixels(), CopyImageRegion(), CropImage(), CycleColormapImage(), DespeckleImage(), DistortImage(), DitherImage(), DrawAffineImage(), DrawGradientImage(), DrawPolygonPrimitive(), DrawPrimitive(), EnhanceImage(), EqualizeImageChannel(), EvaluateImageChannel(), EvaluateImages(), ExcerptImage(), FilterImageChannel(), FlipImage(), FloodfillPaintImage(), FlopImage(), FloydSteinbergDither(), FrameImage(), FunctionImageChannel(), FxImageChannel(), GammaImageChannel(), GrayscaleImage(), HaldClutImageChannel(), HorizontalFilter(), HuffmanDecodeImage(), ImplodeImage(), IntegralRotateImage(), InterpolativeResizeImage(), KuwaharaImageChannel(), LevelImageChannel(), LevelizeImageChannel(), LocalContrastImage(), MagnifyImage(), MatrixToImage(), MeanShiftImage(), ModulateImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImageChannel(), NegateImageChannel(), NewMagickImage(), OilPaintImage(), OpaquePaintImageChannel(), OrderedPosterizeImageChannel(), PerceptibleImageChannel(), PlasmaImage(), PolynomialImageChannel(), PosterizeImageChannel(), ProfileImage(), RaiseImage(), RandomThresholdImageChannel(), RenderPostscript(), ResetImagePixels(), RGBTransformImage(), RotationalBlurImageChannel(), SampleImage(), ScaleImage(), SelectiveBlurImageChannel(), SeparateImageChannel(), SepiaToneImage(), SetGrayscaleImage(), SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageChannelDepth(), SetImageColor(), SetImageOpacity(), ShadeImage(), ShadowImage(), SigmoidalContrastImageChannel(), SketchImage(), SolarizeImageChannel(), SortColormapByIntensity(), SparseColorImage(), SpliceImage(), SpreadImage(), StatisticImageChannel(), SteganoImage(), SwirlImage(), SyncImage(), TextureImage(), TintImage(), TransformRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), TransposeImage(), TransverseImage(), UnsharpMaskImageChannel(), VerticalFilter(), WaveImage(), WaveletDenoiseImage(), WhiteThresholdImageChannel(), XShearImage(), and YShearImage().
AcquireCacheView()
MagickExport CacheView * AcquireCacheView (const Image * image)
References AcquireVirtualCacheView().
AcquireVirtualCacheView()
MagickExport CacheView * AcquireVirtualCacheView (const Image * image, ExceptionInfo * exception)
References AcquireAlignedMemory(), AcquirePixelCacheNexus(), CacheFatalError, _Image::debug, _Image::filename, GetImageVirtualPixelMethod(), GetMagickModule, GetMagickResourceLimit(), GetOpenMPMaximumThreads(), IsEventLogging(), LogMagickEvent(), magick_restrict, magick_unreferenced, MagickAssumeAligned, MagickCoreSignature, MagickFalse, ReferenceImage(), ResourceLimitFatalError, _Image::signature, ThreadResource, ThrowFatalException, and TraceEvent.
Referenced by AcquireAuthenticCacheView(), AcquireCacheView(), AcquireFxInfo(), AcquireResampleFilter(), AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), AddNoiseImageChannel(), AppendImages(), AutoThresholdImage(), BlueShiftImage(), CannyEdgeImage(), CheckImageColors(), ChopImage(), Classify(), ClassifyImageColors(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImageChannels(), ComplexImages(), CompositeImageChannel(), ConnectedComponentsImage(), ConsolidateCMYKImages(), CopyImagePixels(), CopyImageRegion(), CropImage(), DespeckleImage(), DrawAffineImage(), EqualizeImageChannel(), EvaluateImages(), ExcerptImage(), FilterImageChannel(), FlipImage(), FloodfillPaintImage(), FlopImage(), FrameImage(), GetAbsoluteDistortion(), GetEdgeBackgroundFactor(), GetEdgeBoundingBox(), GetFuzzDistortion(), GetImageBackgroundColor(), GetImageBoundingBox(), GetImageChannelDepth(), GetImageChannelFeatures(), GetImageQuantizeError(), GetImageTotalInkDensity(), GetMeanAbsoluteDistortion(), GetMeanErrorPerPixel(), GetMeanSquaredDistortion(), GetNormalizedCrossCorrelationDistortion(), GetPeakAbsoluteDistortion(), GetSimilarityMetric(), HorizontalFilter(), HoughLineImage(), IdentifyImageGray(), IdentifyImageMonochrome(), ImplodeImage(), IntegralRotateImage(), InterpolateMagickPixelPacket(), InterpolativeResizeImage(), IsHighDynamicRangeImage(), IsHistogramImage(), IsImagesEqual(), IsImageSimilar(), IsOpaqueImage(), KuwaharaImageChannel(), LocalContrastImage(), MagnifyImage(), MeanShiftImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImageChannel(), NewImageView(), NewImageViewRegion(), OilPaintImage(), OpenCacheView(), PlasmaImage(), PolynomialImageChannel(), RadonTransform(), ResamplePixelColor(), RotationalBlurImageChannel(), SampleImage(), ScaleImage(), SelectiveBlurImageChannel(), SepiaToneImage(), SetCacheAlphaChannel(), SetImageGray(), SetImageMonochrome(), ShadeImage(), SignatureImage(), SimilarityMetricImage(), SmushImages(), SmushXGap(), SmushYGap(), SpliceImage(), SpreadImage(), StatisticImageChannel(), SteganoImage(), SwirlImage(), TextureImage(), TintImage(), TransposeImage(), TransverseImage(), UniqueImageColors(), UnsharpMaskImageChannel(), VerticalFilter(), and WaveImage().
CloneCacheView()
MagickExport CacheView * CloneCacheView (const CacheView * cache_view)
References AcquireAlignedMemory(), AcquirePixelCacheNexus(), _CacheView::debug, _Image::filename, GetMagickModule, _CacheView::image, LogMagickEvent(), magick_restrict, MagickAssumeAligned, MagickCoreSignature, MagickFalse, _CacheView::number_threads, ReferenceImage(), ResourceLimitFatalError, _CacheView::signature, ThrowFatalException, TraceEvent, and _CacheView::virtual_pixel_method.
Referenced by CloneImageView().
DestroyCacheView()
MagickExport CacheView * DestroyCacheView (CacheView * cache_view)
References _CacheView::debug, DestroyImage(), DestroyPixelCacheNexus(), _Image::filename, GetMagickModule, _CacheView::image, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheView::nexus_info, _CacheView::number_threads, RelinquishAlignedMemory(), _CacheView::signature, and TraceEvent.
Referenced by AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), AddNoiseImageChannel(), AppendImages(), AssignImageColors(), AutoThresholdImage(), BilevelImageChannel(), BlackThresholdImageChannel(), BlueShiftImage(), CannyEdgeImage(), CheckImageColors(), ChopImage(), ClampImageChannel(), Classify(), ClassifyImageColors(), CloseCacheView(), ClutImageChannel(), ColorDecisionListImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImageChannels(), ComplexImages(), CompositeImageChannel(), ConnectedComponentsImage(), ConsolidateCMYKImages(), ContrastImage(), ContrastStretchImageChannel(), CopyImagePixels(), CopyImageRegion(), CropImage(), CycleColormapImage(), DespeckleImage(), DestroyFxInfo(), DestroyImageView(), DestroyResampleFilter(), DistortImage(), DitherImage(), DrawAffineImage(), DrawPolygonPrimitive(), DrawPrimitive(), EnhanceImage(), EqualizeImageChannel(), EvaluateImageChannel(), EvaluateImages(), ExcerptImage(), FilterImageChannel(), FlipImage(), FloodfillPaintImage(), FlopImage(), FloydSteinbergDither(), FrameImage(), FunctionImageChannel(), FxImageChannel(), GammaImageChannel(), GetAbsoluteDistortion(), GetEdgeBackgroundFactor(), GetEdgeBoundingBox(), GetFuzzDistortion(), GetImageBackgroundColor(), GetImageBoundingBox(), GetImageChannelDepth(), GetImageChannelFeatures(), GetImageQuantizeError(), GetImageTotalInkDensity(), GetMeanAbsoluteDistortion(), GetMeanErrorPerPixel(), GetMeanSquaredDistortion(), GetNormalizedCrossCorrelationDistortion(), GetPeakAbsoluteDistortion(), GetSimilarityMetric(), GrayscaleImage(), HaldClutImageChannel(), HorizontalFilter(), HoughLineImage(), HuffmanDecodeImage(), IdentifyImageGray(), IdentifyImageMonochrome(), ImplodeImage(), IntegralRotateImage(), InterpolateMagickPixelPacket(), InterpolativeResizeImage(), IsHighDynamicRangeImage(), IsHistogramImage(), IsImagesEqual(), IsImageSimilar(), IsOpaqueImage(), KuwaharaImageChannel(), LevelImageChannel(), LevelizeImageChannel(), LocalContrastImage(), MagnifyImage(), MatrixToImage(), MeanShiftImage(), ModulateImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImageChannel(), NegateImageChannel(), NewMagickImage(), OilPaintImage(), OpaquePaintImageChannel(), OrderedPosterizeImageChannel(), PerceptibleImageChannel(), PlasmaImage(), PolynomialImageChannel(), PosterizeImageChannel(), ProfileImage(), RadonTransform(), RaiseImage(), RandomThresholdImageChannel(), RenderPostscript(), ResamplePixelColor(), ResetImagePixels(), RGBTransformImage(), RotationalBlurImageChannel(), SampleImage(), ScaleImage(), SelectiveBlurImageChannel(), SeparateImageChannel(), SepiaToneImage(), SetCacheAlphaChannel(), SetGrayscaleImage(), SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageChannelDepth(), SetImageColor(), SetImageGray(), SetImageMonochrome(), SetImageOpacity(), ShadeImage(), ShadowImage(), SigmoidalContrastImageChannel(), SignatureImage(), SimilarityMetricImage(), SketchImage(), SmushImages(), SmushXGap(), SmushYGap(), SolarizeImageChannel(), SortColormapByIntensity(), SparseColorImage(), SpliceImage(), SpreadImage(), StatisticImageChannel(), SteganoImage(), SwirlImage(), SyncImage(), TextureImage(), TintImage(), TransformRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), TransposeImage(), TransverseImage(), UniqueImageColors(), UnsharpMaskImageChannel(), VerticalFilter(), WaveImage(), WaveletDenoiseImage(), WhiteThresholdImageChannel(), XShearImage(), and YShearImage().
GetCacheViewAuthenticIndexQueue()
MagickExport IndexPacket * GetCacheViewAuthenticIndexQueue (CacheView * cache_view)
References _Image::cache, GetOpenMPThreadId(), _CacheView::image, _NexusInfo::indexes, MagickCoreSignature, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), AddNoiseImageChannel(), AppendImages(), AssignImageColors(), BilevelImageChannel(), BlackThresholdImageChannel(), ChopImage(), ClampImageChannel(), Classify(), ClutImageChannel(), ColorMatrixImage(), CombineImages(), CompareImageChannels(), CompositeImageChannel(), ConnectedComponentsImage(), ConsolidateCMYKImages(), ContrastStretchImageChannel(), CopyImagePixels(), CopyImageRegion(), CropImage(), CycleColormapImage(), DespeckleImage(), DistortImage(), DrawAffineImage(), DrawGradientImage(), EqualizeImageChannel(), EvaluateImageChannel(), EvaluateImages(), ExcerptImage(), FilterImageChannel(), FlipImage(), FloodfillPaintImage(), FlopImage(), FloydSteinbergDither(), FrameImage(), FunctionImageChannel(), FxImageChannel(), GammaImageChannel(), GetCacheViewIndexes(), GetImageQuantizeError(), GetImageViewAuthenticIndexes(), HaldClutImageChannel(), HorizontalFilter(), HuffmanDecodeImage(), ImplodeImage(), ImportQuantumPixels(), IntegralRotateImage(), InterpolativeResizeImage(), KuwaharaImageChannel(), LevelImageChannel(), LevelizeImageChannel(), MagnifyImage(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImageChannel(), NegateImageChannel(), NewMagickImage(), OilPaintImage(), OpaquePaintImageChannel(), OrderedPosterizeImageChannel(), PerceptibleImageChannel(), PolynomialImageChannel(), PosterizeImageChannel(), ProfileImage(), RandomThresholdImageChannel(), ResamplePixelColor(), ResetImagePixels(), RGBTransformImage(), RiemersmaDither(), RotationalBlurImageChannel(), SampleImage(), ScaleImage(), SelectiveBlurImageChannel(), SeparateImageChannel(), SetGrayscaleImage(), SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageColor(), SigmoidalContrastImageChannel(), SketchImage(), SortColormapByIntensity(), SparseColorImage(), SpliceImage(), SpreadImage(), StatisticImageChannel(), SwirlImage(), SyncImage(), TextureImage(), TransformRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), TransposeImage(), TransverseImage(), UniqueColorsToImage(), UnsharpMaskImageChannel(), VerticalFilter(), WaveImage(), WaveletDenoiseImage(), WhiteThresholdImageChannel(), XShearImage(), and YShearImage().
GetCacheViewAuthenticPixelQueue()
MagickExport PixelPacket * GetCacheViewAuthenticPixelQueue (CacheView * cache_view)
References _Image::cache, GetOpenMPThreadId(), _CacheView::image, MagickCoreSignature, _CacheView::nexus_info, _CacheView::number_threads, _NexusInfo::pixels, and _CacheView::signature.
Referenced by GetImageViewAuthenticPixels(), and ImportQuantumPixels().
GetCacheViewAuthenticPixels()
MagickExport PixelPacket * GetCacheViewAuthenticPixels (CacheView * cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception)
References GetAuthenticPixelCacheNexus(), GetOpenMPThreadId(), _CacheView::image, MagickCoreSignature, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by AdaptiveThresholdImage(), AddNoiseImageChannel(), AssignImageColors(), BilevelImageChannel(), BlackThresholdImageChannel(), CannyEdgeImage(), ClampImageChannel(), Classify(), ClutImageChannel(), ColorDecisionListImage(), ColorMatrixImage(), CombineImages(), CompositeImageChannel(), ConnectedComponentsImage(), ConsolidateCMYKImages(), ContrastImage(), ContrastStretchImageChannel(), CopyImagePixels(), CopyImageRegion(), CycleColormapImage(), DespeckleImage(), DrawAffineImage(), DrawGradientImage(), DrawPolygonPrimitive(), DrawPrimitive(), DuplexTransferImageViewIterator(), EqualizeImageChannel(), EvaluateImageChannel(), ExcerptImage(), FilterImageChannel(), FloodfillPaintImage(), FloydSteinbergDither(), FunctionImageChannel(), FxImageChannel(), GammaImageChannel(), GetCacheView(), GetCacheViewPixels(), GrayscaleImage(), HaldClutImageChannel(), ImplodeImage(), LevelImageChannel(), LevelizeImageChannel(), LocalContrastImage(), MeanShiftImage(), ModulateImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImageChannel(), NegateImageChannel(), OpaquePaintImageChannel(), OrderedPosterizeImageChannel(), PerceptibleImageChannel(), PosterizeImageChannel(), ProfileImage(), RaiseImage(), RandomThresholdImageChannel(), RenderPostscript(), RGBTransformImage(), RiemersmaDither(), RotationalBlurImageChannel(), SelectiveBlurImageChannel(), SeparateImageChannel(), SetCacheAlphaChannel(), SetGrayscaleImage(), SetImageAlphaChannel(), SetImageChannelDepth(), SetImageOpacity(), SetImageViewIterator(), ShadowImage(), SigmoidalContrastImageChannel(), SimilarityMetricImage(), SolarizeImageChannel(), SortColormapByIntensity(), SparseColorImage(), SteganoImage(), SwirlImage(), SyncImage(), TraceEdges(), TransferImageViewIterator(), TransformRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), UnsharpMaskImageChannel(), UpdateImageViewIterator(), WaveletDenoiseImage(), WhiteThresholdImageChannel(), XShearImage(), and YShearImage().
GetCacheViewChannels()
MagickExport size_t GetCacheViewChannels (const CacheView * cache_view)
References _Image::cache, _CacheView::debug, _Image::filename, GetMagickModule, GetPixelCacheChannels(), _CacheView::image, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheView::signature, and TraceEvent.
GetCacheViewColorspace()
MagickExport ColorspaceType GetCacheViewColorspace (const CacheView * cache_view)
References _Image::cache, _CacheView::debug, _Image::filename, GetMagickModule, GetPixelCacheColorspace(), _CacheView::image, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheView::signature, and TraceEvent.
GetCacheViewException()
MagickExport ExceptionInfo * GetCacheViewException (const CacheView * cache_view)
References _CacheView::debug, _Image::exception, _Image::filename, GetMagickModule, _CacheView::image, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheView::signature, and TraceEvent.
Referenced by DuplexTransferImageViewIterator(), GetCacheView(), GetCacheViewPixels(), SetCacheViewPixels(), SetImageViewIterator(), SyncCacheView(), SyncCacheViewPixels(), TransferImageViewIterator(), and UpdateImageViewIterator().
GetCacheViewExtent()
MagickExport MagickSizeType GetCacheViewExtent (const CacheView * cache_view)
References _Image::cache, _CacheView::debug, _Image::filename, GetMagickModule, GetOpenMPThreadId(), GetPixelCacheNexusExtent(), _CacheView::image, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheView::nexus_info, _CacheView::number_threads, _CacheView::signature, and TraceEvent.
Referenced by ExportQuantumPixels(), and ImportQuantumPixels().
GetCacheViewStorageClass()
MagickExport ClassType GetCacheViewStorageClass (const CacheView * cache_view)
References _Image::cache, _CacheView::debug, _Image::filename, GetMagickModule, GetPixelCacheStorageClass(), _CacheView::image, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheView::signature, and TraceEvent.
GetCacheViewVirtualIndexQueue()
MagickExport const IndexPacket * GetCacheViewVirtualIndexQueue (const CacheView * cache_view)
References _Image::cache, GetOpenMPThreadId(), GetVirtualIndexesFromNexus(), _CacheView::image, MagickCoreSignature, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by AcquireCacheViewIndexes(), AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), AddNoiseImageChannel(), AppendImages(), CheckImageColors(), ClassifyImageColors(), ColorMatrixImage(), CompareImageChannels(), CompositeImageChannel(), ConnectedComponentsImage(), CopyImagePixels(), CopyImageRegion(), CropImage(), DespeckleImage(), EqualizeImageChannel(), EvaluateImages(), ExportQuantumPixels(), FilterImageChannel(), FlipImage(), FloodfillPaintImage(), FlopImage(), GetAbsoluteDistortion(), GetFuzzDistortion(), GetImageBoundingBox(), GetImageChannelDepth(), GetImageChannelFeatures(), GetImageTotalInkDensity(), GetImageViewVirtualIndexes(), GetMeanAbsoluteDistortion(), GetMeanErrorPerPixel(), GetMeanSquaredDistortion(), GetNormalizedCrossCorrelationDistortion(), GetPeakAbsoluteDistortion(), GetSimilarityMetric(), HorizontalFilter(), IntegralRotateImage(), InterpolateMagickPixelPacket(), InterpolatePixelColor(), IsHighDynamicRangeImage(), IsHistogramImage(), IsImagesEqual(), IsImageSimilar(), MagnifyImage(), MeanShiftImage(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImageChannel(), OilPaintImage(), PolynomialImageChannel(), ResamplePixelColor(), RotationalBlurImageChannel(), ScaleImage(), SelectiveBlurImageChannel(), StatisticImageChannel(), TextureImage(), UnsharpMaskImageChannel(), VerticalFilter(), and WaveletDenoiseImage().
GetCacheViewVirtualPixelQueue()
MagickExport const PixelPacket * GetCacheViewVirtualPixelQueue (const CacheView * cache_view)
References _Image::cache, GetOpenMPThreadId(), GetVirtualPixelsNexus(), _CacheView::image, MagickCoreSignature, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by ExportQuantumPixels(), and GetImageViewVirtualPixels().
GetCacheViewVirtualPixels()
MagickExport const PixelPacket * GetCacheViewVirtualPixels (const CacheView * cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception)
References GetOpenMPThreadId(), GetVirtualPixelCacheNexus(), _CacheView::image, MagickCoreSignature, _CacheView::nexus_info, _CacheView::number_threads, _CacheView::signature, and _CacheView::virtual_pixel_method.
Referenced by AcquireCacheViewPixels(), AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), AddNoiseImageChannel(), AppendImages(), AutoThresholdImage(), BlueShiftImage(), CannyEdgeImage(), CheckImageColors(), ChopImage(), Classify(), ClassifyImageColors(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImageChannels(), ComplexImages(), CompositeImageChannel(), ConnectedComponentsImage(), ConsolidateCMYKImages(), ContrastStretchImageChannel(), CopyImagePixels(), CopyImageRegion(), CropImage(), DespeckleImage(), DuplexTransferImageViewIterator(), EnhanceImage(), EqualizeImageChannel(), EvaluateImages(), ExcerptImage(), FilterImageChannel(), FlipImage(), FloodfillPaintImage(), FlopImage(), GetAbsoluteDistortion(), GetEdgeBackgroundFactor(), GetFuzzDistortion(), GetImageBackgroundColor(), GetImageBoundingBox(), GetImageChannelDepth(), GetImageChannelFeatures(), GetImageQuantizeError(), GetImageTotalInkDensity(), GetImageViewIterator(), GetMeanAbsoluteDistortion(), GetMeanErrorPerPixel(), GetMeanSquaredDistortion(), GetNormalizedCrossCorrelationDistortion(), GetPeakAbsoluteDistortion(), GetSimilarityMetric(), HorizontalFilter(), HoughLineImage(), IdentifyImageGray(), IdentifyImageMonochrome(), IntegralRotateImage(), InterpolateMagickPixelPacket(), InterpolatePixelColor(), IsHighDynamicRangeImage(), IsHistogramImage(), IsImagesEqual(), IsImageSimilar(), IsOpaqueImage(), KuwaharaImageChannel(), LocalContrastImage(), MagnifyImage(), MeanShiftImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), OilPaintImage(), PolynomialImageChannel(), RadonTransform(), ResamplePixelColor(), SampleImage(), ScaleImage(), SelectiveBlurImageChannel(), SepiaToneImage(), SetImageGray(), SetImageMonochrome(), ShadeImage(), SignatureImage(), SmushXGap(), SmushYGap(), SpliceImage(), StatisticImageChannel(), TextureImage(), TintImage(), TransferImageViewIterator(), TransposeImage(), TransverseImage(), UnsharpMaskImageChannel(), and VerticalFilter().
GetOneCacheViewAuthenticPixel()
MagickExport MagickBooleanType GetOneCacheViewAuthenticPixel (const CacheView *magick_restrict cache_view, const ssize_t x, const ssize_t y, PixelPacket *magick_restrict pixel, ExceptionInfo * exception)
References GetAuthenticPixelCacheNexus(), GetOpenMPThreadId(), magick_restrict, MagickCoreSignature, MagickFalse, and MagickTrue.
GetOneCacheViewVirtualMethodPixel()
MagickExport MagickBooleanType GetOneCacheViewVirtualMethodPixel (const CacheView * cache_view, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, PixelPacket * pixel, ExceptionInfo * exception)
References _Image::background_color, GetOpenMPThreadId(), GetVirtualPixelCacheNexus(), _CacheView::image, magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _CacheView::nexus_info, _CacheView::number_threads, and _CacheView::signature.
Referenced by AcquireOneCacheViewVirtualPixel().
GetOneCacheViewVirtualPixel()
MagickExport MagickBooleanType GetOneCacheViewVirtualPixel (const CacheView *magick_restrict cache_view, const ssize_t x, const ssize_t y, PixelPacket *magick_restrict pixel, ExceptionInfo * exception)
References GetOpenMPThreadId(), GetVirtualPixelCacheNexus(), magick_restrict, MagickCoreSignature, MagickFalse, and MagickTrue.
Referenced by AcquireOneCacheViewPixel(), DrawPrimitive(), MeanShiftImage(), MotionBlurImageChannel(), PlasmaImageProxy(), RotationalBlurImageChannel(), and SteganoImage().
QueueCacheViewAuthenticPixels()
MagickExport PixelPacket * QueueCacheViewAuthenticPixels (CacheView * cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception)
References GetOpenMPThreadId(), _CacheView::image, MagickCoreSignature, MagickFalse, _CacheView::nexus_info, _CacheView::number_threads, QueueAuthenticPixelCacheNexus(), and _CacheView::signature.
Referenced by AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AppendImages(), BlueShiftImage(), ChopImage(), ColorizeImage(), CompareImageChannels(), ComplexImages(), CompositeImageChannel(), ConnectedComponentsImage(), ConsolidateCMYKImages(), CropImage(), DistortImage(), EnhanceImage(), EvaluateImages(), FlipImage(), FlopImage(), FrameImage(), HorizontalFilter(), HuffmanDecodeImage(), IntegralRotateImage(), InterpolativeResizeImage(), KuwaharaImageChannel(), MagnifyImage(), MatrixToImage(), NewMagickImage(), OilPaintImage(), PlasmaImageProxy(), PolynomialImageChannel(), ResetImagePixels(), SampleImage(), ScaleImage(), SepiaToneImage(), SetCacheViewPixels(), SetImageBackgroundColor(), SetImageColor(), ShadeImage(), SketchImage(), SpliceImage(), SpreadImage(), StatisticImageChannel(), TextureImage(), TintImage(), TransposeImage(), TransverseImage(), UniqueColorsToImage(), VerticalFilter(), and WaveImage().
SetCacheViewStorageClass()
MagickExport MagickBooleanType SetCacheViewStorageClass (CacheView * cache_view, const ClassType storage_class)
References _CacheView::debug, _Image::filename, GetMagickModule, _CacheView::image, LogMagickEvent(), MagickCoreSignature, MagickFalse, SetImageStorageClass(), _CacheView::signature, and TraceEvent.
SetCacheViewVirtualPixelMethod()
MagickExport MagickBooleanType SetCacheViewVirtualPixelMethod (CacheView *magick_restrict cache_view, const VirtualPixelMethod virtual_pixel_method)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, and TraceEvent.
Referenced by SetResampleFilterVirtualPixelMethod(), and WaveImage().
SyncCacheViewAuthenticPixels()
MagickExport MagickBooleanType SyncCacheViewAuthenticPixels (CacheView *magick_restrict cache_view, ExceptionInfo * exception)
References GetOpenMPThreadId(), MagickCoreSignature, and SyncAuthenticPixelCacheNexus().
Referenced by AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), AddNoiseImageChannel(), AppendImages(), AssignImageColors(), BilevelImageChannel(), BlackThresholdImageChannel(), BlueShiftImage(), CannyEdgeImage(), ChopImage(), ClampImageChannel(), Classify(), ClutImageChannel(), ColorDecisionListImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImageChannels(), ComplexImages(), CompositeImageChannel(), ConnectedComponentsImage(), ConsolidateCMYKImages(), ContrastImage(), ContrastStretchImageChannel(), CopyImagePixels(), CopyImageRegion(), CropImage(), CycleColormapImage(), DespeckleImage(), DistortImage(), DrawAffineImage(), DrawPolygonPrimitive(), DrawPrimitive(), DuplexTransferImageViewIterator(), EnhanceImage(), EqualizeImageChannel(), EvaluateImageChannel(), EvaluateImages(), ExcerptImage(), FilterImageChannel(), FlipImage(), FloodfillPaintImage(), FlopImage(), FloydSteinbergDither(), FrameImage(), FunctionImageChannel(), FxImageChannel(), GammaImageChannel(), GrayscaleImage(), HaldClutImageChannel(), HorizontalFilter(), HuffmanDecodeImage(), ImplodeImage(), IntegralRotateImage(), InterpolativeResizeImage(), KuwaharaImageChannel(), LevelImageChannel(), LevelizeImageChannel(), LocalContrastImage(), MagnifyImage(), MatrixToImage(), MeanShiftImage(), ModulateImage(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImageChannel(), NegateImageChannel(), NewMagickImage(), OilPaintImage(), OpaquePaintImageChannel(), OrderedPosterizeImageChannel(), PerceptibleImageChannel(), PlasmaImageProxy(), PolynomialImageChannel(), PosterizeImageChannel(), ProfileImage(), RaiseImage(), RandomThresholdImageChannel(), RenderPostscript(), ResetImagePixels(), RGBTransformImage(), RiemersmaDither(), RotationalBlurImageChannel(), SampleImage(), ScaleImage(), SelectiveBlurImageChannel(), SeparateImageChannel(), SepiaToneImage(), SetCacheAlphaChannel(), SetGrayscaleImage(), SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageChannelDepth(), SetImageColor(), SetImageOpacity(), SetImageViewIterator(), ShadeImage(), ShadowImage(), SigmoidalContrastImageChannel(), SimilarityMetricImage(), SketchImage(), SolarizeImageChannel(), SortColormapByIntensity(), SparseColorImage(), SpliceImage(), SpreadImage(), StatisticImageChannel(), SteganoImage(), SwirlImage(), SyncCacheView(), SyncCacheViewPixels(), SyncImage(), TextureImage(), TintImage(), TraceEdges(), TransferImageViewIterator(), TransformRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), TransposeImage(), TransverseImage(), UniqueColorsToImage(), UnsharpMaskImageChannel(), UpdateImageViewIterator(), VerticalFilter(), WaveImage(), WaveletDenoiseImage(), WhiteThresholdImageChannel(), XShearImage(), and YShearImage().