MagickCore: channel.h File Reference
channel.h File Reference
#include "magick/image.h"
Functions
MagickExport Image * CombineImages (const Image *, const ChannelType, ExceptionInfo *)
MagickExport Image * SeparateImage (const Image *, const ChannelType, ExceptionInfo *)
MagickExport Image * SeparateImages (const Image *, const ChannelType, ExceptionInfo *)
MagickExport MagickBooleanType GetImageAlphaChannel (const Image *)
MagickExport MagickBooleanType SeparateImageChannel (Image *, const ChannelType)
MagickExport MagickBooleanType SetImageAlphaChannel (Image *, const AlphaChannelType)
Function Documentation
CombineImages()
MagickExport Image * CombineImages (const Image * , const ChannelType, ExceptionInfo *)
GetImageAlphaChannel()
MagickExport MagickBooleanType GetImageAlphaChannel (const Image *)
SeparateImage()
MagickExport Image * SeparateImage (const Image * , const ChannelType, ExceptionInfo *)
SeparateImageChannel()
MagickExport MagickBooleanType SeparateImageChannel (Image * , const ChannelType)
SeparateImages()
MagickExport Image * SeparateImages (const Image * image, const ChannelType, ExceptionInfo * exception)
References AlphaChannel, AppendImageToList(), BlackChannel, BlueChannel, CloneImage(), CMYKColorspace, _Image::colorspace, _Image::debug, _Image::filename, GetMagickModule, GreenChannel, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, NewImageList(), RedChannel, SeparateImageChannel(), _Image::signature, TraceEvent, and TrueAlphaChannel.
SetImageAlphaChannel()
MagickExport MagickBooleanType SetImageAlphaChannel (Image * image, const AlphaChannelType)
References AcquireAuthenticCacheView(), ActivateAlphaChannel, AssociateAlphaChannel, _Image::background_color, BackgroundAlphaChannel, _PixelPacket::blue, ClampToQuantum(), CMYKColorspace, _Image::colorspace, _Image::columns, ConvertRGBToCMYK(), CopyAlphaChannel, DeactivateAlphaChannel, _Image::debug, DestroyCacheView(), DirectClass, DisassociateAlphaChannel, _Image::exception, ExtractAlphaChannel, FlattenAlphaChannel, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickPixelPacket(), GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelRed, GrayChannels, _PixelPacket::green, LevelColorsImage(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickOver_(), MagickTrue, _Image::matte, _PixelPacket::opacity, OpaqueAlphaChannel, OpaqueOpacity, PerceptibleReciprocal(), QuantumRange, QuantumScale, _PixelPacket::red, RemoveAlphaChannel, ResetAlphaChannel, _Image::rows, SeparateImageChannel(), SetAlphaChannel, SetImageOpacity(), SetImageStorageClass(), SetMagickPixelPacket(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelPacket(), SetPixelRed, ShapeAlphaChannel, _Image::signature, SyncCacheViewAuthenticPixels(), SyncImagePixelCache(), TraceEvent, TransparentAlphaChannel, TransparentOpacity, TrueAlphaChannel, and UndefinedAlphaChannel.
Referenced by CannyEdgeImage(), ClearBounds(), ClutImageChannel(), ColorFloodfillImage(), ColorizeImage(), CompareImageChannels(), CompositeImageChannel(), DistortResizeImage(), DrawPrimitive(), FloodfillPaintImage(), FrameImage(), HaldClutImageChannel(), MatteFloodfillImage(), MorphologyApply(), PolaroidImage(), RenderMVGContent(), RenderPostscript(), SeparateImageChannel(), SetImageBackgroundColor(), SetImageType(), ShadowImage(), ShearImage(), ShearRotateImage(), SimilarityMetricImage(), ThumbnailImage(), TransparentImage(), TransparentPaintImage(), and TransparentPaintImageChroma().