MagickCore: cipher.c File Reference
cipher.c File Reference
#include "magick/studio.h"
#include "magick/cache.h"
#include "magick/cipher.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/hashmap.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/memory_.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/property.h"
#include "magick/quantum-private.h"
#include "magick/registry.h"
#include "magick/semaphore.h"
#include "magick/signature-private.h"
#include "magick/splay-tree.h"
#include "magick/statistic.h"
#include "magick/string_.h"
Functions
MagickExport MagickBooleanType DecipherImage (Image *image, const char *passphrase, ExceptionInfo *exception)
MagickExport MagickBooleanType PasskeyDecipherImage (Image *image, const StringInfo *passkey, ExceptionInfo *exception)
MagickExport MagickBooleanType EncipherImage (Image *image, const char *passphrase, ExceptionInfo *exception)
MagickExport MagickBooleanType PasskeyEncipherImage (Image *image, const StringInfo *passkey, ExceptionInfo *exception)
Function Documentation
DecipherImage()
MagickExport MagickBooleanType DecipherImage (Image * image, const char * passphrase, ExceptionInfo * exception)
References _Image::debug, _Image::filename, GetMagickModule, ImageError, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ExceptionInfo::signature, _Image::signature, ThrowBinaryException, and TraceEvent.
EncipherImage()
MagickExport MagickBooleanType EncipherImage (Image * image, const char * passphrase, ExceptionInfo * exception)
References _Image::debug, _Image::filename, GetMagickModule, ImageError, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ExceptionInfo::signature, _Image::signature, ThrowBinaryException, and TraceEvent.
PasskeyDecipherImage()
MagickExport MagickBooleanType PasskeyDecipherImage (Image * image, const StringInfo * passkey, ExceptionInfo * exception)
References _Image::debug, _Image::filename, GetMagickModule, ImageError, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ExceptionInfo::signature, _Image::signature, ThrowBinaryException, and TraceEvent.
PasskeyEncipherImage()
MagickExport MagickBooleanType PasskeyEncipherImage (Image * image, const StringInfo * passkey, ExceptionInfo * exception)
References _Image::debug, _Image::filename, GetMagickModule, ImageError, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ExceptionInfo::signature, _Image::signature, ThrowBinaryException, and TraceEvent.