MagickCore: client.c File Reference
client.c File Reference
#include "magick/studio.h"
#include "magick/client.h"
#include "magick/log.h"
#include "magick/string_.h"
Functions
MagickExport const char * GetClientName (void)
MagickExport const char * GetClientPath (void)
MagickExport const char * SetClientName (const char *name)
MagickExport const char * SetClientPath (const char *path)
Function Documentation
GetClientName()
MagickExport const char * GetClientName (void)
References SetClientName().
Referenced by DefaultErrorHandler(), DefaultFatalErrorHandler(), DefaultWarningHandler(), LocaleFatalErrorHandler(), TranslateEvent(), and TranslateFilename().
GetClientPath()
MagickExport const char * GetClientPath (void)
References SetClientPath().
Referenced by GetConfigureBlob(), and GetConfigurePaths().
SetClientName()
MagickExport const char * SetClientName (const char * name)
References ConfigureEvent, CopyMagickString(), GetMagickModule, and LogMagickEvent().
Referenced by GetClientName(), and MagickCoreGenesis().
SetClientPath()
MagickExport const char * SetClientPath (const char * path)
References ConfigureEvent, CopyMagickString(), GetMagickModule, LogMagickEvent(), and MaxTextExtent.
Referenced by GetClientPath(), and MagickCoreGenesis().