MagickCore: client.h File Reference
client.h File Reference
Functions
MagickExport const char * GetClientPath (void) magick_attribute((__const__))
MagickExport const char * GetClientName (void) magick_attribute((__const__))
MagickExport const char * SetClientName (const char *)
MagickExport const char * SetClientPath (const char *)
Function Documentation
GetClientName()
MagickExport const char * GetClientName (void)
GetClientPath()
MagickExport const char * GetClientPath (void)
SetClientName()
MagickExport const char * SetClientName (const char *)
SetClientPath()
MagickExport const char * SetClientPath (const char * path)
References ConfigureEvent, CopyMagickString(), GetMagickModule, LogMagickEvent(), and MaxTextExtent.
Referenced by GetClientPath(), and MagickCoreGenesis().