MagickCore: coder.h File Reference
coder.h File Reference
Data Structures
struct _CoderInfo
Typedefs
typedef struct _CoderInfo CoderInfo
Functions
MagickExport char ** GetCoderList (const char *, size_t *, ExceptionInfo *)
MagickExport const CoderInfo * GetCoderInfo (const char *, ExceptionInfo *)
MagickExport const CoderInfo ** GetCoderInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport MagickBooleanType CoderComponentGenesis (void)
MagickExport MagickBooleanType ListCoderInfo (FILE *, ExceptionInfo *)
MagickExport void CoderComponentTerminus (void)
Typedef Documentation
CoderInfo
typedef struct _CoderInfo CoderInfo
Function Documentation
CoderComponentGenesis()
MagickExport MagickBooleanType CoderComponentGenesis (void)
CoderComponentTerminus()
MagickExport void CoderComponentTerminus (void)
References ActivateSemaphoreInfo(), coder_cache, coder_semaphore, DestroySemaphoreInfo(), DestroySplayTree(), LockSemaphoreInfo(), and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
GetCoderInfo()
MagickExport const CoderInfo * GetCoderInfo (const char * , ExceptionInfo *)
GetCoderInfoList()
MagickExport const CoderInfo ** GetCoderInfoList (const char * pattern, size_t * number_coders, ExceptionInfo * exception)
References AcquireQuantumMemory(), coder_cache, coder_semaphore, CoderInfoCompare(), GetCoderInfo(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _CoderInfo::name, ResetSplayTreeIterator(), _CoderInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListCoderInfo().
GetCoderList()
MagickExport char ** GetCoderList (const char * pattern, size_t * number_coders, ExceptionInfo * exception)
References AcquireQuantumMemory(), coder_cache, coder_semaphore, CoderCompare(), ConstantString(), GetCoderInfo(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _CoderInfo::name, ResetSplayTreeIterator(), _CoderInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
ListCoderInfo()
MagickExport MagickBooleanType ListCoderInfo (FILE * file, ExceptionInfo * exception)
References FormatLocaleFile(), GetCoderInfoList(), LocaleCompare(), MagickFalse, MagickTrue, _CoderInfo::path, and RelinquishMagickMemory().