MagickCore: coder.c File Reference
coder.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/client.h"
#include "magick/coder.h"
#include "magick/configure.h"
#include "magick/draw.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/hashmap.h"
#include "magick/log.h"
#include "magick/memory_.h"
#include "magick/option.h"
#include "magick/semaphore.h"
#include "magick/string_.h"
#include "magick/splay-tree.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/xml-tree.h"
#include "magick/xml-tree-private.h"
Data Structures
struct _CoderMapInfo
Macros
#define MagickCoderFilename "coder.xml"
Typedefs
typedef struct _CoderMapInfo CoderMapInfo
Functions
static MagickBooleanType IsCoderTreeInstantiated (ExceptionInfo *)
static MagickBooleanType LoadCoderCache (SplayTreeInfo *, const char *, const char *, const size_t, ExceptionInfo *)
static void * DestroyCoderNode (void *coder_info)
static SplayTreeInfo * AcquireCoderCache (const char *filename, ExceptionInfo *exception)
MagickExport MagickBooleanType CoderComponentGenesis (void)
MagickExport void CoderComponentTerminus (void)
MagickExport const CoderInfo * GetCoderInfo (const char *name, ExceptionInfo *exception)
static int CoderInfoCompare (const void *x, const void *y)
MagickExport const CoderInfo ** GetCoderInfoList (const char *pattern, size_t *number_coders, ExceptionInfo *exception)
static int CoderCompare (const void *x, const void *y)
MagickExport char ** GetCoderList (const char *pattern, size_t *number_coders, ExceptionInfo *exception)
MagickExport MagickBooleanType ListCoderInfo (FILE *file, ExceptionInfo *exception)
Variables
static const CoderMapInfo CoderMap []
static SemaphoreInfo * coder_semaphore = (SemaphoreInfo *) NULL
static SplayTreeInfo * coder_cache = (SplayTreeInfo *) NULL
Macro Definition Documentation
MagickCoderFilename
#define MagickCoderFilename "coder.xml"
Typedef Documentation
CoderMapInfo
typedef struct _CoderMapInfo CoderMapInfo
Function Documentation
AcquireCoderCache()
static SplayTreeInfo * AcquireCoderCache (const char * filename, ExceptionInfo * exception) static
References AcquireMagickMemory(), AddValueToSplayTree(), CoderMap, CompareSplayTreeString(), ConstantString(), DestroyCoderNode(), DestroyConfigureOptions(), _CoderInfo::exempt, GetConfigureOptions(), GetMagickModule, GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), LoadCoderCache(), _CoderMapInfo::magick, _CoderInfo::magick, MagickCoreSignature, MagickFalse, MagickTrue, _CoderMapInfo::name, _CoderInfo::name, NewSplayTree(), _CoderInfo::path, RelinquishMagickMemory(), ResourceLimitError, ResourceLimitFatalError, _CoderInfo::signature, ThrowFatalException, and ThrowMagickException().
Referenced by IsCoderTreeInstantiated().
CoderCompare()
static int CoderCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetCoderList().
CoderComponentGenesis()
MagickExport MagickBooleanType CoderComponentGenesis (void)
References AllocateSemaphoreInfo(), coder_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
CoderComponentTerminus()
MagickExport void CoderComponentTerminus (void)
References ActivateSemaphoreInfo(), coder_cache, coder_semaphore, DestroySemaphoreInfo(), DestroySplayTree(), LockSemaphoreInfo(), and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
CoderInfoCompare()
static int CoderInfoCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetCoderInfoList().
DestroyCoderNode()
static void * DestroyCoderNode (void * coder_info) static
References DestroyString(), _CoderInfo::exempt, _CoderInfo::magick, MagickFalse, _CoderInfo::name, _CoderInfo::path, and RelinquishMagickMemory().
Referenced by AcquireCoderCache().
GetCoderInfo()
MagickExport const CoderInfo * GetCoderInfo (const char * name, ExceptionInfo * exception)
References coder_cache, GetRootValueFromSplayTree(), GetValueFromSplayTree(), IsCoderTreeInstantiated(), LocaleCompare(), and MagickFalse.
Referenced by GetCoderInfoList(), GetCoderList(), and RegisterStaticModule().
GetCoderInfoList()
MagickExport const CoderInfo ** GetCoderInfoList (const char * pattern, size_t * number_coders, ExceptionInfo * exception)
References AcquireQuantumMemory(), coder_cache, coder_semaphore, CoderInfoCompare(), GetCoderInfo(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _CoderInfo::name, ResetSplayTreeIterator(), _CoderInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListCoderInfo().
GetCoderList()
MagickExport char ** GetCoderList (const char * pattern, size_t * number_coders, ExceptionInfo * exception)
References AcquireQuantumMemory(), coder_cache, coder_semaphore, CoderCompare(), ConstantString(), GetCoderInfo(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _CoderInfo::name, ResetSplayTreeIterator(), _CoderInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
IsCoderTreeInstantiated()
static MagickBooleanType IsCoderTreeInstantiated (ExceptionInfo * exception) static
References AcquireCoderCache(), ActivateSemaphoreInfo(), coder_cache, coder_semaphore, LockSemaphoreInfo(), MagickCoderFilename, MagickFalse, MagickTrue, and UnlockSemaphoreInfo().
Referenced by GetCoderInfo().
ListCoderInfo()
MagickExport MagickBooleanType ListCoderInfo (FILE * file, ExceptionInfo * exception)
References FormatLocaleFile(), GetCoderInfoList(), LocaleCompare(), MagickFalse, MagickTrue, _CoderInfo::path, and RelinquishMagickMemory().
LoadCoderCache()
static MagickBooleanType LoadCoderCache (SplayTreeInfo * cache, const char * xml, const char * filename, const size_t depth, ExceptionInfo * exception) static
References AcquireMagickMemory(), AcquireString(), AddValueToSplayTree(), ConcatenateMagickString(), ConfigureError, ConfigureEvent, ConstantString(), CopyMagickString(), DirectorySeparator, _CoderInfo::exempt, FileToXML(), GetMagickModule, GetNextToken(), GetPathComponent(), HeadPath, IsMagickTrue(), LoadCoderCache(), LocaleCompare(), LocaleNCompare(), LogMagickEvent(), _CoderInfo::magick, MagickCoreSignature, MagickFalse, MagickMaxRecursionDepth, MagickTrue, MaxTextExtent, _CoderInfo::name, _CoderInfo::path, RelinquishMagickMemory(), ResourceLimitError, ResourceLimitFatalError, _CoderInfo::signature, _CoderInfo::stealth, ThrowFatalException, and ThrowMagickException().
Referenced by AcquireCoderCache(), and LoadCoderCache().
Variable Documentation
coder_cache
SplayTreeInfo* coder_cache = (SplayTreeInfo *) NULL static
Referenced by CoderComponentTerminus(), GetCoderInfo(), GetCoderInfoList(), GetCoderList(), and IsCoderTreeInstantiated().
coder_semaphore
SemaphoreInfo* coder_semaphore = (SemaphoreInfo *) NULL static
Referenced by CoderComponentGenesis(), CoderComponentTerminus(), GetCoderInfoList(), GetCoderList(), and IsCoderTreeInstantiated().
CoderMap
const CoderMapInfo CoderMap[] static
Referenced by AcquireCoderCache().