MagickCore: colormap.c File Reference
colormap.c File Reference
#include "magick/studio.h"
#include "magick/attribute.h"
#include "magick/blob.h"
#include "magick/cache-view.h"
#include "magick/cache.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colormap.h"
#include "magick/colormap-private.h"
#include "magick/client.h"
#include "magick/configure.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/image-private.h"
#include "magick/memory_.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/option.h"
#include "magick/pixel-accessor.h"
#include "magick/pixel-private.h"
#include "magick/quantize.h"
#include "magick/quantum.h"
#include "magick/semaphore.h"
#include "magick/resource_.h"
#include "magick/string_.h"
#include "magick/thread-private.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/xml-tree.h"
Functions
MagickExport MagickBooleanType AcquireImageColormap (Image *image, const size_t colors)
MagickExport MagickBooleanType CycleColormapImage (Image *image, const ssize_t displace)
static int IntensityCompare (const void *x, const void *y)
MagickExport MagickBooleanType SortColormapByIntensity (Image *image)
Function Documentation
AcquireImageColormap()
MagickExport MagickBooleanType AcquireImageColormap (Image * image, const size_t colors)
References AcquireQuantumMemory(), _PixelPacket::blue, _Image::colormap, _Image::colors, _Image::debug, DirectClass, _Image::filename, GetMagickModule, _PixelPacket::green, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickMax, MaxColormapSize, _PixelPacket::opacity, OpaqueOpacity, PseudoClass, QuantumRange, _PixelPacket::red, ResizeQuantumMemory(), ResourceLimitError, SetImageStorageClass(), _Image::signature, _Image::storage_class, ThrowBinaryImageException, and TraceEvent.
Referenced by AllocateImageColormap(), AssignImageColors(), Classify(), ConnectedComponentsImage(), RandomChannelThresholdImage(), RandomThresholdImageChannel(), SetGrayscaleImage(), ThresholdImage(), and ThresholdImageChannel().
CycleColormapImage()
MagickExport MagickBooleanType CycleColormapImage (Image * image, const ssize_t displace)
References AcquireAuthenticCacheView(), _Image::colormap, _Image::colors, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelIndex, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, PaletteType, _Image::rows, SetImageType(), SetPixelIndex, SetPixelRGBO, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), and TraceEvent.
IntensityCompare()
static int IntensityCompare (const void * x, const void * y) static
References PixelPacketIntensity().
Referenced by SortColormapByIntensity().
SortColormapByIntensity()
MagickExport MagickBooleanType SortColormapByIntensity (Image * image)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), _Image::colormap, _Image::colors, _Image::columns, ConstrainColormapIndex(), _Image::debug, DestroyCacheView(), _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelIndex, IntensityCompare(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _PixelPacket::opacity, PseudoClass, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetPixelIndex, SetPixelRGBO, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), ThrowBinaryException, and TraceEvent.