MagickCore: color.h File Reference
color.h File Reference
#include "magick/pixel.h"
#include "magick/exception.h"
Data Structures
struct _ColorInfo
struct _ErrorInfo
Typedefs
typedef struct _ColorInfo ColorInfo
typedef struct _ErrorInfo ErrorInfo
Enumerations
enum ComplianceType {
UndefinedCompliance , NoCompliance = 0x0000 , CSSCompliance = 0x0001 , SVGCompliance = 0x0001 ,
X11Compliance = 0x0002 , XPMCompliance = 0x0004 , MVGCompliance = 0x0008 , AllCompliance = 0x7fffffff
}
Functions
MagickExport char ** GetColorList (const char *, size_t *, ExceptionInfo *)
MagickExport const ColorInfo * GetColorInfo (const char *, ExceptionInfo *)
MagickExport const ColorInfo ** GetColorInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport MagickBooleanType ColorComponentGenesis (void)
MagickExport MagickBooleanType IsColorSimilar (const Image *, const PixelPacket *, const PixelPacket *)
MagickExport MagickBooleanType IsImageSimilar (const Image *, const Image *, ssize_t *x, ssize_t *y, ExceptionInfo *)
MagickExport MagickBooleanType IsMagickColorSimilar (const MagickPixelPacket *, const MagickPixelPacket *)
MagickExport MagickBooleanType IsOpacitySimilar (const Image *, const PixelPacket *, const PixelPacket *)
MagickExport MagickBooleanType ListColorInfo (FILE *, ExceptionInfo *)
MagickExport MagickBooleanType QueryColorCompliance (const char *, const ComplianceType, PixelPacket *, ExceptionInfo *)
MagickExport MagickBooleanType QueryColorDatabase (const char *, PixelPacket *, ExceptionInfo *)
MagickExport MagickBooleanType QueryColorname (const Image *, const PixelPacket *, const ComplianceType, char *, ExceptionInfo *)
MagickExport MagickBooleanType QueryMagickColorCompliance (const char *, const ComplianceType, MagickPixelPacket *, ExceptionInfo *)
MagickExport MagickBooleanType QueryMagickColor (const char *, MagickPixelPacket *, ExceptionInfo *)
MagickExport MagickBooleanType QueryMagickColorname (const Image *, const MagickPixelPacket *, const ComplianceType, char *, ExceptionInfo *)
MagickExport void ColorComponentTerminus (void)
MagickExport void ConcatenateColorComponent (const MagickPixelPacket *, const ChannelType, const ComplianceType, char *)
MagickExport void GetColorTuple (const MagickPixelPacket *, const MagickBooleanType, char *)
Typedef Documentation
ColorInfo
typedef struct _ColorInfo ColorInfo
ErrorInfo
typedef struct _ErrorInfo ErrorInfo
Enumeration Type Documentation
ComplianceType
enum ComplianceType
Enumerator
UndefinedCompliance
NoCompliance
CSSCompliance
SVGCompliance
X11Compliance
XPMCompliance
MVGCompliance
AllCompliance
Function Documentation
ColorComponentGenesis()
MagickExport MagickBooleanType ColorComponentGenesis (void)
ColorComponentTerminus()
MagickExport void ColorComponentTerminus (void)
ConcatenateColorComponent()
MagickExport void ConcatenateColorComponent (const MagickPixelPacket * , const ChannelType, const ComplianceType, char *)
GetColorInfo()
MagickExport const ColorInfo * GetColorInfo (const char * , ExceptionInfo *)
GetColorInfoList()
MagickExport const ColorInfo ** GetColorInfoList (const char * pattern, size_t * number_colors, ExceptionInfo * exception)
References AcquireQuantumMemory(), color_cache, color_semaphore, ColorInfoCompare(), GetColorInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _ColorInfo::name, ResetLinkedListIterator(), _ColorInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListColorInfo().
GetColorList()
MagickExport char ** GetColorList (const char * pattern, size_t * number_colors, ExceptionInfo * exception)
References AcquireQuantumMemory(), color_cache, color_semaphore, ColorCompare(), ConstantString(), GetColorInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _ColorInfo::name, ResetLinkedListIterator(), _ColorInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
GetColorTuple()
MagickExport void GetColorTuple (const MagickPixelPacket * pixel, const MagickBooleanType, char * tuple)
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, CommandOptionToMnemonic(), ConcatenateColorComponent(), ConcatenateMagickString(), ConcatentateHexColorComponent(), _MagickPixelPacket::depth, GetMagickModule, GrayChannel, GRAYColorspace, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, LinearGRAYColorspace, LocaleLower(), LogMagickEvent(), MagickColorspaceOptions, MagickFalse, _MagickPixelPacket::matte, MaxTextExtent, _MagickPixelPacket::opacity, OpacityChannel, _MagickPixelPacket::red, RedChannel, SVGCompliance, SVGCompliant, and TraceEvent.
Referenced by ConnectedComponentsImage(), GetImageProperty(), GetNumberColors(), IdentifyImage(), ListColorInfo(), and QueryMagickColorname().
IsColorSimilar()
MagickExport MagickBooleanType IsColorSimilar (const Image * , const PixelPacket * , const PixelPacket *)
IsImageSimilar()
MagickExport MagickBooleanType IsImageSimilar (const Image * , const Image * , ssize_t * x, ssize_t * y, ExceptionInfo *)
IsMagickColorSimilar()
MagickExport MagickBooleanType IsMagickColorSimilar (const MagickPixelPacket * , const MagickPixelPacket *)
IsOpacitySimilar()
MagickExport MagickBooleanType IsOpacitySimilar (const Image * , const PixelPacket * , const PixelPacket *)
ListColorInfo()
MagickExport MagickBooleanType ListColorInfo (FILE * , ExceptionInfo *)
QueryColorCompliance()
MagickExport MagickBooleanType QueryColorCompliance (const char * , const ComplianceType, PixelPacket * , ExceptionInfo *)
QueryColorDatabase()
MagickExport MagickBooleanType QueryColorDatabase (const char * , PixelPacket * , ExceptionInfo *)
QueryColorname()
MagickExport MagickBooleanType QueryColorname (const Image * , const PixelPacket * , const ComplianceType, char * , ExceptionInfo *)
QueryMagickColor()
MagickExport MagickBooleanType QueryMagickColor (const char * , MagickPixelPacket * , ExceptionInfo *)
QueryMagickColorCompliance()
MagickExport MagickBooleanType QueryMagickColorCompliance (const char * , const ComplianceType, MagickPixelPacket * , ExceptionInfo *)
QueryMagickColorname()
MagickExport MagickBooleanType QueryMagickColorname (const Image * image, const MagickPixelPacket * color, const ComplianceType, char * name, ExceptionInfo * exception)
References _MagickPixelPacket::blue, _ColorInfo::color, color_cache, _MagickPixelPacket::colorspace, _ColorInfo::compliance, CopyMagickString(), _Image::depth, _MagickPixelPacket::depth, GetColorInfo(), GetColorTuple(), GetNextValueInLinkedList(), _MagickPixelPacket::green, IssRGBColorspace(), MagickFalse, MagickMin, MagickTrue, _Image::matte, _MagickPixelPacket::matte, MaxTextExtent, _ColorInfo::name, _MagickPixelPacket::opacity, OpaqueOpacity, _MagickPixelPacket::red, ResetLinkedListIterator(), SVGCompliance, and XPMCompliance.
Referenced by GetImageProperty(), GetNumberColors(), IdentifyImage(), and QueryColorname().