MagickCore: colormap-private.h File Reference
colormap-private.h File Reference
#include "magick/image.h"
#include "magick/color.h"
#include "magick/exception-private.h"
Functions
static IndexPacket ConstrainColormapIndex (Image *image, const ssize_t index)
static MagickBooleanType IsValidColormapIndex (Image *image, const ssize_t index, IndexPacket *target, ExceptionInfo *exception)
Function Documentation
ConstrainColormapIndex()
static IndexPacket ConstrainColormapIndex (Image * image, const ssize_t index) inline static
References _Image::colors, CorruptImageError, _Image::exception, _Image::filename, GetMagickModule, _ExceptionInfo::severity, and ThrowMagickException().
Referenced by SortColormapByIntensity(), and ValidateColormapIndex().
IsValidColormapIndex()
static MagickBooleanType IsValidColormapIndex (Image * image, const ssize_t index, IndexPacket * target, ExceptionInfo * exception) inline static
References _Image::colors, CorruptImageError, _Image::exception, _Image::filename, GetMagickModule, MagickFalse, MagickTrue, _ExceptionInfo::severity, and ThrowMagickException().