MagickCore: colorspace-private.h File Reference
colorspace-private.h File Reference
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/pixel.h"
#include "magick/pixel-accessor.h"
Functions
static void ConvertCMYKToRGB (MagickPixelPacket *pixel)
static void ConvertRGBToCMYK (MagickPixelPacket *pixel)
static MagickBooleanType IsCMYKColorspace (const ColorspaceType colorspace)
static MagickBooleanType IsGrayColorspace (const ColorspaceType colorspace)
static MagickBooleanType IsHueCompatibleColorspace (const ColorspaceType colorspace)
static MagickBooleanType IsRGBColorspace (const ColorspaceType colorspace)
static MagickBooleanType IssRGBColorspace (const ColorspaceType colorspace)
static MagickBooleanType IssRGBCompatibleColorspace (const ColorspaceType colorspace)
static MagickBooleanType IsYCbCrCompatibleColorspace (const ColorspaceType colorspace)
Function Documentation
ConvertCMYKToRGB()
static void ConvertCMYKToRGB (MagickPixelPacket * pixel) inline static
References _MagickPixelPacket::blue, _MagickPixelPacket::green, _MagickPixelPacket::index, QuantumRange, QuantumScale, and _MagickPixelPacket::red.
Referenced by ConformMagickPixelPacket(), and TransformRGBImage().
ConvertRGBToCMYK()
static void ConvertRGBToCMYK (MagickPixelPacket * pixel) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, DecodePixelGamma(), _MagickPixelPacket::green, _MagickPixelPacket::index, MagickEpsilon, PerceptibleReciprocal(), QuantumRange, QuantumScale, _MagickPixelPacket::red, and sRGBColorspace.
Referenced by CompareImageChannels(), CompositeImageChannel(), ConformMagickPixelPacket(), DistortImage(), FloodfillPaintImage(), FrameImage(), RGBTransformImage(), SetImageAlphaChannel(), SetImageBackgroundColor(), XShearImage(), and YShearImage().
IsCMYKColorspace()
static MagickBooleanType IsCMYKColorspace (const ColorspaceType colorspace) inline static
References CMYKColorspace, MagickFalse, and MagickTrue.
IsGrayColorspace()
static MagickBooleanType IsGrayColorspace (const ColorspaceType colorspace) inline static
References GRAYColorspace, LinearGRAYColorspace, MagickFalse, MagickTrue, Rec601LumaColorspace, and Rec709LumaColorspace.
Referenced by AddNoiseImageChannel(), AnnotateImage(), BilevelImageChannel(), BlackThresholdImageChannel(), ClutImageChannel(), ColorizeImage(), CombineImages(), ConformMagickPixelPacket(), DistortImage(), DrawPrimitive(), FloodfillPaintImage(), FrameImage(), GetQuantumType(), HaldClutImageChannel(), LevelColorsImageChannel(), MagickPixelIntensity(), MagickPixelIntensityToQuantum(), MagickPixelLuma(), MagickPixelLuminance(), SetImageBackgroundColor(), SetImageColorspace(), SetImageGray(), SetImageMonochrome(), SetPixelCacheVirtualMethod(), ShadowImage(), SolarizeImageChannel(), TintImage(), and WhiteThresholdImageChannel().
IsHueCompatibleColorspace()
static MagickBooleanType IsHueCompatibleColorspace (const ColorspaceType colorspace) inline static
References HCLColorspace, HCLpColorspace, HSBColorspace, HSIColorspace, HSLColorspace, HSVColorspace, MagickFalse, and MagickTrue.
Referenced by ConcatenateColorComponent(), IsColorSimilar(), and IsMagickColorSimilar().
IsRGBColorspace()
static MagickBooleanType IsRGBColorspace (const ColorspaceType colorspace) inline static
References LinearGRAYColorspace, MagickFalse, MagickTrue, RGBColorspace, and scRGBColorspace.
Referenced by SetImageColorspace().
IssRGBColorspace()
static MagickBooleanType IssRGBColorspace (const ColorspaceType colorspace) inline static
References MagickFalse, MagickTrue, sRGBColorspace, and TransparentColorspace.
Referenced by QueryMagickColorname(), and TransformImageColorspace().
IssRGBCompatibleColorspace()
static MagickBooleanType IssRGBCompatibleColorspace (const ColorspaceType colorspace) inline static
References GRAYColorspace, LinearGRAYColorspace, MagickFalse, MagickTrue, RGBColorspace, scRGBColorspace, sRGBColorspace, and TransparentColorspace.
Referenced by AssignImageColors(), ClassifyImageColors(), CombineImages(), ConcatenateColorComponent(), ConformMagickPixelPacket(), IdentifyImageGray(), IdentifyImageMonochrome(), IsMagickGray(), ModulateImage(), SetImageGray(), and SetImageMonochrome().
IsYCbCrCompatibleColorspace()
static MagickBooleanType IsYCbCrCompatibleColorspace (const ColorspaceType colorspace) inline static
References MagickFalse, MagickTrue, Rec601YCbCrColorspace, Rec709YCbCrColorspace, and YCbCrColorspace.