MagickCore: colorspace.h File Reference
colorspace.h File Reference
Enumerations
enum ColorspaceType {
UndefinedColorspace , RGBColorspace , GRAYColorspace , TransparentColorspace ,
OHTAColorspace , LabColorspace , XYZColorspace , YCbCrColorspace ,
YCCColorspace , YIQColorspace , YPbPrColorspace , YUVColorspace ,
CMYKColorspace , sRGBColorspace , HSBColorspace , HSLColorspace ,
HWBColorspace , Rec601LumaColorspace , Rec601YCbCrColorspace , Rec709LumaColorspace ,
Rec709YCbCrColorspace , LogColorspace , CMYColorspace , LuvColorspace ,
HCLColorspace , LCHColorspace , LMSColorspace , LCHabColorspace ,
LCHuvColorspace , scRGBColorspace , HSIColorspace , HSVColorspace ,
HCLpColorspace , YDbDrColorspace , xyYColorspace , LinearGRAYColorspace
}
Functions
MagickExport ColorspaceType GetImageColorspaceType (const Image *, ExceptionInfo *)
MagickExport MagickBooleanType RGBTransformImage (Image *, const ColorspaceType)
MagickExport MagickBooleanType SetImageColorspace (Image *, const ColorspaceType)
MagickExport MagickBooleanType SetImageGray (Image *, ExceptionInfo *)
MagickExport MagickBooleanType SetImageMonochrome (Image *, ExceptionInfo *)
MagickExport MagickBooleanType TransformImageColorspace (Image *, const ColorspaceType)
MagickExport MagickBooleanType TransformRGBImage (Image *, const ColorspaceType)
Enumeration Type Documentation
ColorspaceType
enum ColorspaceType
Enumerator
UndefinedColorspace
RGBColorspace
GRAYColorspace
TransparentColorspace
OHTAColorspace
LabColorspace
XYZColorspace
YCbCrColorspace
YCCColorspace
YIQColorspace
YPbPrColorspace
YUVColorspace
CMYKColorspace
sRGBColorspace
HSBColorspace
HSLColorspace
HWBColorspace
Rec601LumaColorspace
Rec601YCbCrColorspace
Rec709LumaColorspace
Rec709YCbCrColorspace
LogColorspace
CMYColorspace
LuvColorspace
HCLColorspace
LCHColorspace
LMSColorspace
LCHabColorspace
LCHuvColorspace
scRGBColorspace
HSIColorspace
HSVColorspace
HCLpColorspace
YDbDrColorspace
xyYColorspace
LinearGRAYColorspace
Function Documentation
GetImageColorspaceType()
MagickExport ColorspaceType GetImageColorspaceType (const Image * image, ExceptionInfo * exception)
References BilevelType, _Image::colorspace, _Image::debug, _Image::filename, GetMagickModule, GRAYColorspace, GrayscaleMatteType, GrayscaleType, IdentifyImageType(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
RGBTransformImage()
MagickExport MagickBooleanType RGBTransformImage (Image * , const ColorspaceType)
SetImageColorspace()
MagickExport MagickBooleanType SetImageColorspace (Image * , const ColorspaceType)
SetImageGray()
MagickExport MagickBooleanType SetImageGray (Image * , ExceptionInfo *)
SetImageMonochrome()
MagickExport MagickBooleanType SetImageMonochrome (Image * , ExceptionInfo *)
TransformImageColorspace()
MagickExport MagickBooleanType TransformImageColorspace (Image * , const ColorspaceType)
TransformRGBImage()
MagickExport MagickBooleanType TransformRGBImage (Image * image, const ColorspaceType)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), _MagickPixelPacket::blue, _PixelPacket::blue, ClampToQuantum(), CMYColorspace, CMYKColorspace, _Image::colormap, _Image::colors, _Image::columns, ConvertCMYKToRGB(), ConvertCMYToRGB(), ConvertHCLpToRGB(), ConvertHCLToRGB(), ConvertHSBToRGB(), ConvertHSIToRGB(), ConvertHSLToRGB(), ConvertHSVToRGB(), ConvertHWBToRGB(), ConvertLabToRGB(), ConvertLCHabToRGB(), ConvertLCHuvToRGB(), ConvertLMSToRGB(), ConvertLuvToRGB(), ConvertxyYToRGB(), ConvertXYZToRGB(), ConvertYCbCrToRGB(), ConvertYDbDrToRGB(), ConvertYIQToRGB(), ConvertYPbPrToRGB(), ConvertYUVToRGB(), _Image::debug, DestroyCacheView(), DirectClass, DisplayGamma, EncodePixelGamma(), _Image::exception, _Image::filename, FilmGamma, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetImageProperty(), GetMagickModule, GetMagickPixelPacket(), GetPixelBlue, GetPixelGreen, GetPixelRed, GRAYColorspace, _MagickPixelPacket::green, _PixelPacket::green, HCLColorspace, HCLpColorspace, HSBColorspace, HSIColorspace, HSLColorspace, HSVColorspace, HWBColorspace, LabColorspace, LCHabColorspace, LCHColorspace, LCHuvColorspace, LinearGRAYColorspace, LMSColorspace, LogColorspace, LogMagickEvent(), LuvColorspace, magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, MaxMap, OHTAColorspace, PerceptibleReciprocal(), _Image::progress_monitor, PseudoClass, QuantumRange, QuantumScale, Rec601LumaColorspace, Rec601YCbCrColorspace, Rec709LumaColorspace, Rec709YCbCrColorspace, _MagickPixelPacket::red, _PixelPacket::red, ReferenceBlack, ReferenceWhite, RelinquishMagickMemory(), ResourceLimitError, RGBColorspace, RoundToYCC(), _Image::rows, scRGBColorspace, SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacket(), SetPixelBlue, SetPixelGreen, SetPixelPacket(), SetPixelRed, _Image::signature, sRGBColorspace, _Image::storage_class, StringToDouble(), SyncCacheViewAuthenticPixels(), SyncImage(), ThrowBinaryException, TraceEvent, TransformRGBImageTag, _TransformPacket::x, xyYColorspace, XYZColorspace, _TransformPacket::y, YCbCrColorspace, YCCColorspace, YDbDrColorspace, YIQColorspace, YPbPrColorspace, YUVColorspace, and _TransformPacket::z.
Referenced by TransformImageColorspace().