MagickCore: color-private.h File Reference
color-private.h File Reference
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/color.h"
#include "magick/colorspace-private.h"
#include "magick/exception-private.h"
#include "magick/pixel-accessor.h"
Functions
MagickPrivate MagickBooleanType IsIntensitySimilar (const Image *, const PixelPacket *, const PixelPacket *)
static double GetFuzzyColorDistance (const Image *p, const Image *q)
static MagickBooleanType IsColorEqual (const PixelPacket *p, const PixelPacket *q)
static MagickBooleanType IsMagickColorEqual (const MagickPixelPacket *p, const MagickPixelPacket *q)
static MagickBooleanType IsMagickGray (const MagickPixelPacket *pixel)
static MagickRealType MagickPixelIntensity (const MagickPixelPacket *pixel)
static Quantum MagickPixelIntensityToQuantum (const MagickPixelPacket *pixel)
static MagickRealType MagickPixelLuma (const MagickPixelPacket *pixel)
static MagickRealType MagickPixelLuminance (const MagickPixelPacket *pixel)
Function Documentation
GetFuzzyColorDistance()
static double GetFuzzyColorDistance (const Image * p, const Image * q) inline static
References _Image::fuzz, MagickMax, and MagickSQ1_2.
Referenced by CompareImageChannels(), and GetAbsoluteDistortion().
IsColorEqual()
static MagickBooleanType IsColorEqual (const PixelPacket * p, const PixelPacket * q) inline static
References AbsolutePixelValue(), _PixelPacket::blue, _PixelPacket::green, MagickEpsilon, MagickFalse, MagickTrue, and _PixelPacket::red.
IsIntensitySimilar()
MagickPrivate MagickBooleanType IsIntensitySimilar (const Image * image, const PixelPacket * p, const PixelPacket * q)
References _Image::fuzz, GetPixelIntensity(), MagickFalse, MagickMax, MagickSQ1_2, and MagickTrue.
IsMagickColorEqual()
static MagickBooleanType IsMagickColorEqual (const MagickPixelPacket * p, const MagickPixelPacket * q) inline static
References AbsolutePixelValue(), _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, MagickEpsilon, MagickFalse, MagickTrue, _MagickPixelPacket::matte, _MagickPixelPacket::opacity, OpaqueOpacity, _MagickPixelPacket::red, and TransparentOpacity.
Referenced by IsMagickColorSimilar().
IsMagickGray()
static MagickBooleanType IsMagickGray (const MagickPixelPacket * pixel) inline static
References AbsolutePixelValue(), _MagickPixelPacket::blue, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, IssRGBCompatibleColorspace(), MagickEpsilon, MagickFalse, MagickTrue, and _MagickPixelPacket::red.
Referenced by BlackThresholdImageChannel(), ConformMagickPixelPacket(), ThresholdImageChannel(), and WhiteThresholdImageChannel().
MagickPixelIntensity()
static MagickRealType MagickPixelIntensity (const MagickPixelPacket * pixel) inline static
References _MagickPixelPacket::blue, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, IsGrayColorspace(), MagickFalse, and _MagickPixelPacket::red.
Referenced by ClutImageChannel(), CompositeBumpmap(), CompositeDarkenIntensity(), CompositeLightenIntensity(), and IntensityCompare().
MagickPixelIntensityToQuantum()
static Quantum MagickPixelIntensityToQuantum (const MagickPixelPacket * pixel) inline static
References _MagickPixelPacket::blue, ClampToQuantum(), _MagickPixelPacket::colorspace, _MagickPixelPacket::green, IsGrayColorspace(), MagickFalse, and _MagickPixelPacket::red.
Referenced by ClutImageChannel(), and CompositeImageChannel().
MagickPixelLuma()
static MagickRealType MagickPixelLuma (const MagickPixelPacket * pixel) inline static
References _MagickPixelPacket::blue, _MagickPixelPacket::colorspace, EncodePixelGamma(), _MagickPixelPacket::green, IsGrayColorspace(), MagickFalse, _MagickPixelPacket::red, and sRGBColorspace.
Referenced by InterpolateMagickPixelPacket(), InterpolatePixelColor(), and KuwaharaImageChannel().
MagickPixelLuminance()
static MagickRealType MagickPixelLuminance (const MagickPixelPacket * pixel) inline static
References _MagickPixelPacket::blue, _MagickPixelPacket::colorspace, DecodePixelGamma(), _MagickPixelPacket::green, IsGrayColorspace(), MagickFalse, _MagickPixelPacket::red, and sRGBColorspace.