MagickCore: colormap.h File Reference
colormap.h File Reference
Functions
MagickExport MagickBooleanType AcquireImageColormap (Image *, const size_t)
MagickExport MagickBooleanType CycleColormapImage (Image *, const ssize_t)
MagickExport MagickBooleanType SortColormapByIntensity (Image *)
Function Documentation
AcquireImageColormap()
MagickExport MagickBooleanType AcquireImageColormap (Image * , const size_t)
CycleColormapImage()
MagickExport MagickBooleanType CycleColormapImage (Image * , const ssize_t)
SortColormapByIntensity()
MagickExport MagickBooleanType SortColormapByIntensity (Image * image)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), _Image::colormap, _Image::colors, _Image::columns, ConstrainColormapIndex(), _Image::debug, DestroyCacheView(), _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelIndex, IntensityCompare(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _PixelPacket::opacity, PseudoClass, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetPixelIndex, SetPixelRGBO, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), ThrowBinaryException, and TraceEvent.