MagickCore: color.c File Reference
color.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/cache-view.h"
#include "magick/cache.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colorspace-private.h"
#include "magick/client.h"
#include "magick/configure.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/image-private.h"
#include "magick/memory_.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/option.h"
#include "magick/pixel-private.h"
#include "magick/quantize.h"
#include "magick/quantum.h"
#include "magick/semaphore.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/xml-tree.h"
#include "magick/xml-tree-private.h"
Data Structures
struct _ColormapInfo
Macros
#define ColorFilename "colors.xml"
#define SVGCompliant(component)
#define SVGEpsilon 1.0e-6
#define SearchImageText " Searching image... "
Typedefs
typedef struct _ColormapInfo ColormapInfo
Functions
static MagickBooleanType IsColorCacheInstantiated (ExceptionInfo *)
static MagickBooleanType LoadColorCache (LinkedListInfo *, const char *, const char *, const size_t, ExceptionInfo *)
static LinkedListInfo * AcquireColorCache (const char *filename, ExceptionInfo *exception)
MagickExport MagickBooleanType ColorComponentGenesis (void)
static void * DestroyColorElement (void *color_info)
MagickExport void ColorComponentTerminus (void)
MagickExport const ColorInfo * GetColorCompliance (const char *name, const ComplianceType compliance, ExceptionInfo *exception)
MagickExport const ColorInfo * GetColorInfo (const char *name, ExceptionInfo *exception)
static MagickBooleanType IsSVGCompliant (const MagickPixelPacket *pixel)
MagickExport void ConcatenateColorComponent (const MagickPixelPacket *pixel, const ChannelType channel, const ComplianceType compliance, char *tuple)
static int ColorInfoCompare (const void *x, const void *y)
MagickExport const ColorInfo ** GetColorInfoList (const char *pattern, size_t *number_colors, ExceptionInfo *exception)
static int ColorCompare (const void *x, const void *y)
MagickExport char ** GetColorList (const char *pattern, size_t *number_colors, ExceptionInfo *exception)
static void ConcatentateHexColorComponent (const MagickPixelPacket *pixel, const ChannelType channel, char *tuple)
MagickExport void GetColorTuple (const MagickPixelPacket *pixel, const MagickBooleanType hex, char *tuple)
MagickExport MagickBooleanType IsColorSimilar (const Image *image, const PixelPacket *p, const PixelPacket *q)
MagickExport MagickBooleanType IsImageSimilar (const Image *image, const Image *target_image, ssize_t *x_offset, ssize_t *y_offset, ExceptionInfo *exception)
MagickPrivate MagickBooleanType IsIntensitySimilar (const Image *image, const PixelPacket *p, const PixelPacket *q)
MagickExport MagickBooleanType IsMagickColorSimilar (const MagickPixelPacket *p, const MagickPixelPacket *q)
MagickExport MagickBooleanType IsOpacitySimilar (const Image *image, const PixelPacket *p, const PixelPacket *q)
MagickExport MagickBooleanType ListColorInfo (FILE *file, ExceptionInfo *exception)
MagickExport MagickBooleanType QueryColorCompliance (const char *name, const ComplianceType compliance, PixelPacket *color, ExceptionInfo *exception)
MagickExport MagickBooleanType QueryColorDatabase (const char *name, PixelPacket *color, ExceptionInfo *exception)
MagickExport MagickBooleanType QueryColorname (const Image *image, const PixelPacket *color, const ComplianceType compliance, char *name, ExceptionInfo *exception)
static MagickStatusType ParseCSSColor (const char *magick_restrict color, GeometryInfo *geometry_info)
MagickExport MagickBooleanType QueryMagickColorCompliance (const char *name, const ComplianceType compliance, MagickPixelPacket *color, ExceptionInfo *exception)
MagickExport MagickBooleanType QueryMagickColor (const char *name, MagickPixelPacket *color, ExceptionInfo *exception)
MagickExport MagickBooleanType QueryMagickColorname (const Image *image, const MagickPixelPacket *color, const ComplianceType compliance, char *name, ExceptionInfo *exception)
Variables
static const ColormapInfo Colormap []
static LinkedListInfo * color_cache = (LinkedListInfo *) NULL
static SemaphoreInfo * color_semaphore = (SemaphoreInfo *) NULL
Macro Definition Documentation
ColorFilename
#define ColorFilename "colors.xml"
SearchImageText
#define SearchImageText " Searching image... "
SVGCompliant
#define SVGCompliant (component)
Value:
  ((double) \
  ScaleCharToQuantum(ScaleQuantumToChar(ClampToQuantum(component))))
SVGEpsilon
#define SVGEpsilon 1.0e-6
Typedef Documentation
ColormapInfo
typedef struct _ColormapInfo ColormapInfo
Function Documentation
AcquireColorCache()
static LinkedListInfo * AcquireColorCache (const char * filename, ExceptionInfo * exception) static
References AcquireMagickMemory(), _ColormapInfo::alpha, AppendValueToLinkedList(), _MagickPixelPacket::blue, _ColorInfo::color, Colormap, _ColormapInfo::compliance, _ColorInfo::compliance, DestroyConfigureOptions(), _ColorInfo::exempt, GetConfigureOptions(), GetMagickModule, GetMagickPixelPacket(), GetNextValueInLinkedList(), GetPixelBlue, GetPixelGreen, GetPixelRed, GetStringInfoDatum(), GetStringInfoPath(), _MagickPixelPacket::green, LoadColorCache(), MagickCoreSignature, MagickFalse, MagickTrue, _ColormapInfo::name, _ColorInfo::name, NewLinkedList(), _MagickPixelPacket::opacity, _ColorInfo::path, QuantumRange, _MagickPixelPacket::red, ResourceLimitError, ResourceLimitFatalError, _ColorInfo::signature, ThrowFatalException, and ThrowMagickException().
Referenced by IsColorCacheInstantiated().
ColorCompare()
static int ColorCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetColorList().
ColorComponentGenesis()
MagickExport MagickBooleanType ColorComponentGenesis (void)
References AllocateSemaphoreInfo(), color_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
ColorComponentTerminus()
MagickExport void ColorComponentTerminus (void)
References ActivateSemaphoreInfo(), color_cache, color_semaphore, DestroyColorElement(), DestroyLinkedList(), DestroySemaphoreInfo(), LockSemaphoreInfo(), and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
ColorInfoCompare()
static int ColorInfoCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetColorInfoList().
ConcatenateColorComponent()
MagickExport void ConcatenateColorComponent (const MagickPixelPacket * pixel, const ChannelType channel, const ComplianceType compliance, char * tuple)
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, _MagickPixelPacket::colorspace, ConcatenateMagickString(), _MagickPixelPacket::depth, FormatLocaleString(), GetMagickPrecision(), _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, IsHueCompatibleColorspace(), IssRGBCompatibleColorspace(), IsSVGCompliant(), LabColorspace, MagickFalse, MagickPathExtent, NoCompliance, _MagickPixelPacket::opacity, QuantumRange, QuantumScale, _MagickPixelPacket::red, and RedChannel.
Referenced by GetColorTuple(), GetNumberColors(), and IdentifyImage().
ConcatentateHexColorComponent()
static void ConcatentateHexColorComponent (const MagickPixelPacket * pixel, const ChannelType channel, char * tuple) static
References _MagickPixelPacket::blue, BlueChannel, ClampToQuantum(), ConcatenateMagickString(), _MagickPixelPacket::depth, FormatLocaleString(), _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, MaxTextExtent, _MagickPixelPacket::opacity, OpacityChannel, QuantumRange, _MagickPixelPacket::red, and RedChannel.
Referenced by GetColorTuple().
DestroyColorElement()
static void * DestroyColorElement (void * color_info) static
References DestroyString(), _ColorInfo::exempt, MagickFalse, _ColorInfo::name, _ColorInfo::path, and RelinquishMagickMemory().
Referenced by ColorComponentTerminus().
GetColorCompliance()
MagickExport const ColorInfo * GetColorCompliance (const char * name, const ComplianceType compliance, ExceptionInfo * exception)
References color_cache, color_semaphore, _ColorInfo::compliance, CopyMagickString(), GetMagickModule, GetNextValueInLinkedList(), InsertValueInLinkedList(), IsColorCacheInstantiated(), LocaleCompare(), LockSemaphoreInfo(), MagickFalse, MaxTextExtent, _ColorInfo::name, OptionWarning, RemoveElementByValueFromLinkedList(), ResetLinkedListIterator(), ThrowMagickException(), and UnlockSemaphoreInfo().
Referenced by GetColorInfo(), and QueryMagickColorCompliance().
GetColorInfo()
MagickExport const ColorInfo * GetColorInfo (const char * name, ExceptionInfo * exception)
References AllCompliance, and GetColorCompliance().
Referenced by GetColorInfoList(), GetColorList(), and QueryMagickColorname().
GetColorInfoList()
MagickExport const ColorInfo ** GetColorInfoList (const char * pattern, size_t * number_colors, ExceptionInfo * exception)
References AcquireQuantumMemory(), color_cache, color_semaphore, ColorInfoCompare(), GetColorInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _ColorInfo::name, ResetLinkedListIterator(), _ColorInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListColorInfo().
GetColorList()
MagickExport char ** GetColorList (const char * pattern, size_t * number_colors, ExceptionInfo * exception)
References AcquireQuantumMemory(), color_cache, color_semaphore, ColorCompare(), ConstantString(), GetColorInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _ColorInfo::name, ResetLinkedListIterator(), _ColorInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
GetColorTuple()
MagickExport void GetColorTuple (const MagickPixelPacket * pixel, const MagickBooleanType hex, char * tuple)
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, CommandOptionToMnemonic(), ConcatenateColorComponent(), ConcatenateMagickString(), ConcatentateHexColorComponent(), _MagickPixelPacket::depth, GetMagickModule, GrayChannel, GRAYColorspace, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, LinearGRAYColorspace, LocaleLower(), LogMagickEvent(), MagickColorspaceOptions, MagickFalse, _MagickPixelPacket::matte, MaxTextExtent, _MagickPixelPacket::opacity, OpacityChannel, _MagickPixelPacket::red, RedChannel, SVGCompliance, SVGCompliant, and TraceEvent.
Referenced by ConnectedComponentsImage(), GetImageProperty(), GetNumberColors(), IdentifyImage(), ListColorInfo(), and QueryMagickColorname().
IsColorCacheInstantiated()
static MagickBooleanType IsColorCacheInstantiated (ExceptionInfo * exception) static
References AcquireColorCache(), ActivateSemaphoreInfo(), color_cache, color_semaphore, ColorFilename, LockSemaphoreInfo(), MagickFalse, MagickTrue, and UnlockSemaphoreInfo().
Referenced by GetColorCompliance().
IsColorSimilar()
MagickExport MagickBooleanType IsColorSimilar (const Image * image, const PixelPacket * p, const PixelPacket * q)
References _PixelPacket::blue, _Image::colorspace, _Image::fuzz, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelOpacity, GetPixelRed, _PixelPacket::green, IsHueCompatibleColorspace(), MagickEpsilon, MagickFalse, MagickMax, MagickSQ1_2, MagickTrue, _Image::matte, _PixelPacket::opacity, OpaqueOpacity, QuantumRange, and QuantumScale.
Referenced by ColorFloodfillImage(), ConnectedComponentsImage(), DrawPrimitive(), FuzzyColorCompare(), MatteFloodfillImage(), OpaqueImage(), and TransparentImage().
IsImageSimilar()
MagickExport MagickBooleanType IsImageSimilar (const Image * image, const Image * target_image, ssize_t * x_offset, ssize_t * y_offset, ExceptionInfo * exception)
References AcquireVirtualCacheView(), _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), IsMagickColorSimilar(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::progress_monitor, _Image::rows, SearchImageText, SetImageProgress(), SetMagickPixelPacket(), _Image::signature, and TraceEvent.
IsIntensitySimilar()
MagickPrivate MagickBooleanType IsIntensitySimilar (const Image * image, const PixelPacket * p, const PixelPacket * q)
References _Image::fuzz, GetPixelIntensity(), MagickFalse, MagickMax, MagickSQ1_2, and MagickTrue.
IsMagickColorSimilar()
MagickExport MagickBooleanType IsMagickColorSimilar (const MagickPixelPacket * p, const MagickPixelPacket * q)
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::fuzz, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelOpacity, _MagickPixelPacket::green, _MagickPixelPacket::index, IsHueCompatibleColorspace(), IsMagickColorEqual(), MagickEpsilon, MagickFalse, MagickMax, MagickSQ1_2, MagickTrue, _MagickPixelPacket::matte, _MagickPixelPacket::opacity, OpaqueOpacity, QuantumRange, QuantumScale, and _MagickPixelPacket::red.
Referenced by CompareImageChannels(), ComparePixels(), CompositeImageChannel(), ConnectedComponentsImage(), FloodfillPaintImage(), GetEdgeBackgroundFactor(), GetImageBoundingBox(), IsImageSimilar(), OpaquePaintImageChannel(), and TransparentPaintImage().
IsOpacitySimilar()
MagickExport MagickBooleanType IsOpacitySimilar (const Image * image, const PixelPacket * p, const PixelPacket * q)
References _Image::fuzz, GetPixelOpacity, MagickFalse, MagickMax, MagickSQ1_2, MagickTrue, and _Image::matte.
Referenced by FuzzyOpacityCompare().
IsSVGCompliant()
static MagickBooleanType IsSVGCompliant (const MagickPixelPacket * pixel) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, MagickFalse, MagickTrue, _MagickPixelPacket::red, SVGCompliant, and SVGEpsilon.
Referenced by ConcatenateColorComponent().
ListColorInfo()
MagickExport MagickBooleanType ListColorInfo (FILE * file, ExceptionInfo * exception)
References FormatLocaleFile(), GetColorInfoList(), GetColorTuple(), LocaleCompare(), MagickFalse, MagickTrue, MaxTextExtent, _ColorInfo::path, RelinquishMagickMemory(), SVGCompliance, X11Compliance, and XPMCompliance.
LoadColorCache()
static MagickBooleanType LoadColorCache (LinkedListInfo * cache, const char * xml, const char * filename, const size_t depth, ExceptionInfo * exception) static
References AcquireMagickMemory(), AcquireString(), AppendValueToLinkedList(), _ColorInfo::color, _ColorInfo::compliance, ConcatenateMagickString(), ConfigureError, ConfigureEvent, ConstantString(), CopyMagickString(), DirectorySeparator, _ColorInfo::exempt, FileToXML(), GetMagickModule, GetNextToken(), GetPathComponent(), HeadPath, IsMagickTrue(), LoadColorCache(), LocaleCompare(), LocaleNCompare(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickMaxRecursionDepth, MagickTrue, MaxTextExtent, _ColorInfo::name, _ColorInfo::path, QueryMagickColor(), RelinquishMagickMemory(), ResourceLimitError, ResourceLimitFatalError, _ColorInfo::signature, _ColorInfo::stealth, StringLocateSubstring(), SVGCompliance, ThrowFatalException, ThrowMagickException(), X11Compliance, and XPMCompliance.
Referenced by AcquireColorCache(), and LoadColorCache().
ParseCSSColor()
static MagickStatusType ParseCSSColor (const char *magick_restrict color, GeometryInfo * geometry_info) static
References AlphaValue, _GeometryInfo::chi, ChiValue, LocaleNCompare(), NoValue, _GeometryInfo::psi, PsiValue, _GeometryInfo::rho, RhoValue, SetGeometryInfo(), _GeometryInfo::sigma, SigmaValue, StringToDouble(), _GeometryInfo::xi, and XiValue.
Referenced by QueryMagickColorCompliance().
QueryColorCompliance()
MagickExport MagickBooleanType QueryColorCompliance (const char * name, const ComplianceType compliance, PixelPacket * color, ExceptionInfo * exception)
References _MagickPixelPacket::blue, ClampToQuantum(), CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, MagickMin, _MagickPixelPacket::opacity, QuantumRange, QuantumScale, QueryMagickColorCompliance(), _MagickPixelPacket::red, SetPixelBlue, SetPixelGreen, SetPixelOpacity, and SetPixelRed.
Referenced by DrawClippingMask(), DrawCompositeMask(), and QueryColorDatabase().
QueryColorDatabase()
MagickExport MagickBooleanType QueryColorDatabase (const char * name, PixelPacket * color, ExceptionInfo * exception)
References AllCompliance, and QueryColorCompliance().
Referenced by AcquireImage(), DrawBoundingRectangles(), DrawPatternPath(), GetDrawInfo(), GetImageInfo(), MontageImageList(), PolaroidImage(), PreviewImage(), RenderMVGContent(), SetImageProperty(), ShadowImage(), SyncImageSettings(), and VignetteImage().
QueryColorname()
MagickExport MagickBooleanType QueryColorname (const Image * image, const PixelPacket * color, const ComplianceType compliance, char * name, ExceptionInfo * exception)
References GetMagickPixelPacket(), QueryMagickColorname(), and SetMagickPixelPacket().
Referenced by AnnotateImage(), and IdentifyImage().
QueryMagickColor()
MagickExport MagickBooleanType QueryMagickColor (const char * name, MagickPixelPacket * color, ExceptionInfo * exception)
References AllCompliance, and QueryMagickColorCompliance().
Referenced by CompareImageChannels(), ConnectedComponentsImage(), FxGetSymbol(), GetEdgeBackgroundFactor(), LoadColorCache(), and QueryMagickColorCompliance().
QueryMagickColorCompliance()
MagickExport MagickBooleanType QueryMagickColorCompliance (const char * name, const ComplianceType compliance, MagickPixelPacket * color, ExceptionInfo * exception)
References AcquireString(), AlphaValue, BackgroundColor, _LongPixelPacket::blue, _MagickPixelPacket::blue, _PixelPacket::blue, _GeometryInfo::chi, ChiValue, ClampToQuantum(), CMYKColorspace, _ColorInfo::color, _MagickPixelPacket::colorspace, ConvertHCLToRGB(), ConvertHSBToRGB(), ConvertHSLToRGB(), ConvertHSVToRGB(), ConvertHWBToRGB(), CopyMagickString(), _MagickPixelPacket::depth, DestroyString(), GetColorCompliance(), GetMagickModule, GetMagickPixelPacket(), GetQuantumRange(), GRAYColorspace, _LongPixelPacket::green, _MagickPixelPacket::green, _PixelPacket::green, HCLColorspace, HSBColorspace, HSLColorspace, HSVColorspace, HWBColorspace, _MagickPixelPacket::index, LabColorspace, LocaleCompare(), LocaleLower(), LocaleNCompare(), LogMagickEvent(), MagickColorspaceOptions, MagickFalse, MagickTrue, _MagickPixelPacket::matte, MaxTextExtent, _LongPixelPacket::opacity, _MagickPixelPacket::opacity, OpaqueOpacity, OptionWarning, ParseCommandOption(), ParseCSSColor(), _GeometryInfo::psi, PsiValue, QuantumRange, QueryMagickColor(), _LongPixelPacket::red, _MagickPixelPacket::red, _PixelPacket::red, RGBColorspace, _GeometryInfo::rho, RhoValue, ScaleAnyToQuantum(), _GeometryInfo::sigma, SigmaValue, sRGBColorspace, SubstituteString(), ThrowMagickException(), TraceEvent, _GeometryInfo::xi, and XiValue.
Referenced by QueryColorCompliance(), and QueryMagickColor().
QueryMagickColorname()
MagickExport MagickBooleanType QueryMagickColorname (const Image * image, const MagickPixelPacket * color, const ComplianceType compliance, char * name, ExceptionInfo * exception)
References _MagickPixelPacket::blue, _ColorInfo::color, color_cache, _MagickPixelPacket::colorspace, _ColorInfo::compliance, CopyMagickString(), _Image::depth, _MagickPixelPacket::depth, GetColorInfo(), GetColorTuple(), GetNextValueInLinkedList(), _MagickPixelPacket::green, IssRGBColorspace(), MagickFalse, MagickMin, MagickTrue, _Image::matte, _MagickPixelPacket::matte, MaxTextExtent, _ColorInfo::name, _MagickPixelPacket::opacity, OpaqueOpacity, _MagickPixelPacket::red, ResetLinkedListIterator(), SVGCompliance, and XPMCompliance.
Referenced by GetImageProperty(), GetNumberColors(), IdentifyImage(), and QueryColorname().
Variable Documentation
color_cache
LinkedListInfo* color_cache = (LinkedListInfo *) NULL static
Referenced by ColorComponentTerminus(), GetColorCompliance(), GetColorInfoList(), GetColorList(), IsColorCacheInstantiated(), and QueryMagickColorname().
color_semaphore
SemaphoreInfo* color_semaphore = (SemaphoreInfo *) NULL static
Referenced by ColorComponentGenesis(), ColorComponentTerminus(), GetColorCompliance(), GetColorInfoList(), GetColorList(), and IsColorCacheInstantiated().
Colormap
const ColormapInfo Colormap[] static
Referenced by AcquireColorCache().