MagickCore: composite.c File Reference
composite.c File Reference
#include "magick/studio.h"
#include "magick/accelerate-private.h"
#include "magick/artifact.h"
#include "magick/cache-view.h"
#include "magick/channel.h"
#include "magick/client.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colorspace.h"
#include "magick/colorspace-private.h"
#include "magick/composite.h"
#include "magick/composite-private.h"
#include "magick/constitute.h"
#include "magick/draw.h"
#include "magick/fx.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/log.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/memory_.h"
#include "magick/option.h"
#include "magick/pixel-private.h"
#include "magick/property.h"
#include "magick/quantum.h"
#include "magick/resample.h"
#include "magick/resource_.h"
#include "magick/string_.h"
#include "magick/thread-private.h"
#include "magick/threshold.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/version.h"
Macros
#define CompositeImageTag "Composite/Image"
#define TextureImageTag "Texture/Image"
Functions
static MagickRealType Atop (const MagickRealType p, const MagickRealType Sa, const MagickRealType q, const MagickRealType magick_unused(Da))
static void CompositeAtop (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
static void CompositeBumpmap (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
static void CompositeClear (const MagickPixelPacket *q, MagickPixelPacket *composite)
static MagickRealType ColorBurn (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da)
static void CompositeColorBurn (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
static MagickRealType ColorDodge (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da)
static void CompositeColorDodge (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
static MagickRealType Darken (const MagickRealType p, const MagickRealType alpha, const MagickRealType q, const MagickRealType beta)
static void CompositeDarken (const MagickPixelPacket *p, const MagickPixelPacket *q, const ChannelType channel, MagickPixelPacket *composite)
static void CompositeDarkenIntensity (const MagickPixelPacket *p, const MagickPixelPacket *q, const ChannelType channel, MagickPixelPacket *composite)
static MagickRealType Difference (const MagickRealType p, const MagickRealType Sa, const MagickRealType q, const MagickRealType Da)
static void CompositeDifference (const MagickPixelPacket *p, const MagickPixelPacket *q, const ChannelType channel, MagickPixelPacket *composite)
static MagickRealType Divide (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da)
static void CompositeDivide (const MagickPixelPacket *p, const MagickPixelPacket *q, const ChannelType channel, MagickPixelPacket *composite)
static MagickRealType Exclusion (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da)
static void CompositeExclusion (const MagickPixelPacket *p, const MagickPixelPacket *q, const ChannelType channel, MagickPixelPacket *composite)
static MagickRealType HardLight (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da)
static void CompositeHardLight (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
static MagickRealType HardMix (const MagickRealType Sca, const MagickRealType Dca)
static void CompositeHardMix (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
static void HCLComposite (const double hue, const double chroma, const double luma, MagickRealType *red, MagickRealType *green, MagickRealType *blue)
static void CompositeHCL (const MagickRealType red, const MagickRealType green, const MagickRealType blue, double *hue, double *chroma, double *luma)
static MagickRealType In (const MagickRealType p, const MagickRealType Sa, const MagickRealType magick_unused(q), const MagickRealType Da)
static void CompositeIn (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
static MagickRealType Lighten (const MagickRealType p, const MagickRealType alpha, const MagickRealType q, const MagickRealType beta)
static void CompositeLighten (const MagickPixelPacket *p, const MagickPixelPacket *q, const ChannelType channel, MagickPixelPacket *composite)
static void CompositeLightenIntensity (const MagickPixelPacket *p, const MagickPixelPacket *q, const ChannelType channel, MagickPixelPacket *composite)
static void CompositeLinearDodge (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
static MagickRealType LinearBurn (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da)
static void CompositeLinearBurn (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
static MagickRealType LinearLight (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da)
static void CompositeLinearLight (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
static MagickRealType Mathematics (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da, const GeometryInfo *geometry_info)
static void CompositeMathematics (const MagickPixelPacket *p, const MagickPixelPacket *q, const ChannelType channel, const GeometryInfo *args, MagickPixelPacket *composite)
static void CompositePlus (const MagickPixelPacket *p, const MagickPixelPacket *q, const ChannelType channel, MagickPixelPacket *composite)
static MagickRealType Minus (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType magick_unused(Da))
static void CompositeMinus (const MagickPixelPacket *p, const MagickPixelPacket *q, const ChannelType channel, MagickPixelPacket *composite)
static MagickRealType ModulusAdd (const MagickRealType Sc, const MagickRealType Sa, const MagickRealType Dc, const MagickRealType Da)
static void CompositeModulusAdd (const MagickPixelPacket *p, const MagickPixelPacket *q, const ChannelType channel, MagickPixelPacket *composite)
static MagickRealType ModulusSubtract (const MagickRealType Sc, const MagickRealType Sa, const MagickRealType Dc, const MagickRealType Da)
static void CompositeModulusSubtract (const MagickPixelPacket *p, const MagickPixelPacket *q, const ChannelType channel, MagickPixelPacket *composite)
static MagickRealType Multiply (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da)
static void CompositeMultiply (const MagickPixelPacket *p, const MagickPixelPacket *q, const ChannelType channel, MagickPixelPacket *composite)
static MagickRealType Out (const MagickRealType p, const MagickRealType Sa, const MagickRealType magick_unused(q), const MagickRealType Da)
static void CompositeOut (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
static MagickRealType PegtopLight (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da)
static void CompositePegtopLight (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
static MagickRealType PinLight (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da)
static void CompositePinLight (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
static MagickRealType Screen (const MagickRealType Sca, const MagickRealType Dca)
static void CompositeScreen (const MagickPixelPacket *p, const MagickPixelPacket *q, const ChannelType channel, MagickPixelPacket *composite)
static MagickRealType SoftLight (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da)
static void CompositeSoftLight (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
static MagickRealType Threshold (const MagickRealType p, const MagickRealType q, const MagickRealType threshold, const MagickRealType amount)
static void CompositeThreshold (const MagickPixelPacket *p, const MagickPixelPacket *q, const MagickRealType threshold, const MagickRealType amount, MagickPixelPacket *composite)
static MagickRealType VividLight (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da)
static void CompositeVividLight (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
static MagickRealType Xor (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da)
static void CompositeXor (const MagickPixelPacket *p, const MagickPixelPacket *q, MagickPixelPacket *composite)
MagickExport MagickBooleanType CompositeImage (Image *image, const CompositeOperator compose, const Image *source_image, const ssize_t x_offset, const ssize_t y_offset)
MagickExport MagickBooleanType CompositeImageChannel (Image *image, const ChannelType channel, const CompositeOperator compose, const Image *composite, const ssize_t x_offset, const ssize_t y_offset)
MagickExport MagickBooleanType TextureImage (Image *image, const Image *texture)
Macro Definition Documentation
CompositeImageTag
#define CompositeImageTag "Composite/Image"
TextureImageTag
#define TextureImageTag "Texture/Image"
Function Documentation
Atop()
static MagickRealType Atop (const MagickRealType p, const MagickRealType Sa, const MagickRealType q, const MagickRealType magick_unusedDa) inline static
References magick_unreferenced.
Referenced by CompositeAtop().
ColorBurn()
static MagickRealType ColorBurn (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da) static
References MagickEpsilon, MagickMin, and PerceptibleReciprocal().
Referenced by CompositeColorBurn().
ColorDodge()
static MagickRealType ColorDodge (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da) static
References MagickEpsilon, MagickMin, and PerceptibleReciprocal().
Referenced by CompositeColorDodge().
CompositeAtop()
static void CompositeAtop (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References Atop(), _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, _MagickPixelPacket::opacity, QuantumScale, and _MagickPixelPacket::red.
Referenced by CompositeImageChannel().
CompositeBumpmap()
static void CompositeBumpmap (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, MagickPixelIntensity(), _MagickPixelPacket::opacity, QuantumScale, and _MagickPixelPacket::red.
Referenced by CompositeImageChannel().
CompositeClear()
static void CompositeClear (const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, _MagickPixelPacket::opacity, _MagickPixelPacket::red, and TransparentOpacity.
Referenced by CompositeImageChannel().
CompositeColorBurn()
static void CompositeColorBurn (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, ColorBurn(), _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, MagickEpsilon, _MagickPixelPacket::opacity, QuantumRange, QuantumScale, _MagickPixelPacket::red, and RoundToUnity().
Referenced by CompositeImageChannel().
CompositeColorDodge()
static void CompositeColorDodge (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, ColorDodge(), _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, MagickEpsilon, _MagickPixelPacket::opacity, QuantumRange, QuantumScale, _MagickPixelPacket::red, and RoundToUnity().
Referenced by CompositeImageChannel().
CompositeDarken()
static void CompositeDarken (const MagickPixelPacket * p, const MagickPixelPacket * q, const ChannelType channel, MagickPixelPacket * composite) inline static
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, Darken(), _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, MagickMax, MagickMin, _MagickPixelPacket::opacity, PerceptibleReciprocal(), QuantumScale, _MagickPixelPacket::red, RedChannel, and SyncChannels.
Referenced by CompositeImageChannel().
CompositeDarkenIntensity()
static void CompositeDarkenIntensity (const MagickPixelPacket * p, const MagickPixelPacket * q, const ChannelType channel, MagickPixelPacket * composite) inline static
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, MagickPixelIntensity(), _MagickPixelPacket::opacity, QuantumScale, _MagickPixelPacket::red, RedChannel, and SyncChannels.
Referenced by CompositeImageChannel().
CompositeDifference()
static void CompositeDifference (const MagickPixelPacket * p, const MagickPixelPacket * q, const ChannelType channel, MagickPixelPacket * composite) inline static
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, Difference(), _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, _MagickPixelPacket::opacity, PerceptibleReciprocal(), QuantumRange, QuantumScale, _MagickPixelPacket::red, RedChannel, RoundToUnity(), and SyncChannels.
Referenced by CompositeImageChannel().
CompositeDivide()
static void CompositeDivide (const MagickPixelPacket * p, const MagickPixelPacket * q, const ChannelType channel, MagickPixelPacket * composite) inline static
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, Divide(), _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, MagickEpsilon, _MagickPixelPacket::opacity, QuantumRange, QuantumScale, _MagickPixelPacket::red, RedChannel, RoundToUnity(), and SyncChannels.
Referenced by CompositeImageChannel().
CompositeExclusion()
static void CompositeExclusion (const MagickPixelPacket * p, const MagickPixelPacket * q, const ChannelType channel, MagickPixelPacket * composite) inline static
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, Exclusion(), _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, MagickEpsilon, _MagickPixelPacket::opacity, QuantumRange, QuantumScale, _MagickPixelPacket::red, RedChannel, RoundToUnity(), and SyncChannels.
Referenced by CompositeImageChannel().
CompositeHardLight()
static void CompositeHardLight (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, HardLight(), _MagickPixelPacket::index, MagickEpsilon, _MagickPixelPacket::opacity, QuantumRange, QuantumScale, _MagickPixelPacket::red, and RoundToUnity().
Referenced by CompositeImageChannel().
CompositeHardMix()
static void CompositeHardMix (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, HardMix(), _MagickPixelPacket::index, MagickEpsilon, _MagickPixelPacket::opacity, QuantumRange, QuantumScale, _MagickPixelPacket::red, and RoundToUnity().
Referenced by CompositeImageChannel().
CompositeHCL()
static void CompositeHCL (const MagickRealType red, const MagickRealType green, const MagickRealType blue, double * hue, double * chroma, double * luma) static
References MagickMax, MagickMin, and QuantumScale.
Referenced by CompositeImageChannel().
CompositeImage()
MagickExport MagickBooleanType CompositeImage (Image * image, const CompositeOperator compose, const Image * source_image, const ssize_t x_offset, const ssize_t y_offset)
References CompositeImageChannel(), and DefaultChannels.
Referenced by CoalesceImages(), CompareImageChannels(), CompareImageLayers(), CompositeCanvas(), DisposeImages(), DistortResizeImage(), DrawPrimitive(), ExtentImage(), FrameImage(), MergeImageLayers(), MontageImageList(), OptimizeImageTransparency(), PolaroidImage(), RenderPostscript(), SketchImage(), SmushImages(), TextureImage(), and VignetteImage().
CompositeImageChannel()
MagickExport MagickBooleanType CompositeImageChannel (Image * image, const ChannelType channel, const CompositeOperator compose, const Image * composite, const ssize_t x_offset, const ssize_t y_offset)
References AcquireAuthenticCacheView(), AcquireResampleFilter(), AcquireVirtualCacheView(), AspectValue, AtopCompositeOp, BlendCompositeOp, _MagickPixelPacket::blue, BlurCompositeOp, BumpmapCompositeOp, ChangeMaskCompositeOp, ClampPixel(), ClampToQuantum(), ClearCompositeOp, CloneImage(), CMYKColorspace, ColorBurnCompositeOp, ColorDodgeCompositeOp, ColorizeCompositeOp, _Image::colorspace, _MagickPixelPacket::colorspace, _Image::columns, CompositeAtop(), CompositeBumpmap(), CompositeClear(), CompositeColorBurn(), CompositeColorDodge(), CompositeDarken(), CompositeDarkenIntensity(), CompositeDifference(), CompositeDivide(), CompositeExclusion(), CompositeHardLight(), CompositeHardMix(), CompositeHCL(), CompositeImageTag, CompositeIn(), CompositeLighten(), CompositeLightenIntensity(), CompositeLinearBurn(), CompositeLinearDodge(), CompositeLinearLight(), CompositeMathematics(), CompositeMinus(), CompositeModulusAdd(), CompositeModulusSubtract(), CompositeMultiply(), CompositeOut(), CompositePegtopLight(), CompositePinLight(), CompositePlus(), CompositeScreen(), CompositeSoftLight(), CompositeThreshold(), CompositeVividLight(), CompositeXor(), ConvertRGBToCMYK(), CopyBlackCompositeOp, CopyBlueCompositeOp, CopyCompositeOp, CopyCyanCompositeOp, CopyGreenCompositeOp, CopyMagentaCompositeOp, CopyOpacityCompositeOp, CopyRedCompositeOp, CopyYellowCompositeOp, DarkenCompositeOp, DarkenIntensityCompositeOp, _Image::debug, DegreesToRadians(), DestroyCacheView(), DestroyImage(), DestroyResampleFilter(), DifferenceCompositeOp, DirectClass, DisplaceCompositeOp, DissolveCompositeOp, DistortCompositeOp, DivideDstCompositeOp, DivideSrcCompositeOp, DstAtopCompositeOp, DstCompositeOp, DstInCompositeOp, DstOutCompositeOp, DstOverCompositeOp, _Image::exception, ExclusionCompositeOp, _Image::filename, GaussianFilter, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetImageArtifact(), GetMagickModule, GetMagickPixelPacket(), GetOneVirtualMagickPixel(), GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _MagickPixelPacket::green, HardLightCompositeOp, HardMixCompositeOp, HCLComposite(), HeightValue, HueCompositeOp, InCompositeOp, _MagickPixelPacket::index, InterpolateMagickPixelPacket(), IsMagickColorSimilar(), IsMagickTrue(), LightenCompositeOp, LightenIntensityCompositeOp, LinearBurnCompositeOp, LinearDodgeCompositeOp, LinearLightCompositeOp, LogMagickEvent(), LuminizeCompositeOp, magick_restrict, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickPixelCompositeBlend(), MagickPixelCompositeOver(), MagickPixelIntensityToQuantum(), MagickTrue, MathematicsCompositeOp, _Image::matte, _MagickPixelPacket::matte, MinusDstCompositeOp, MinusSrcCompositeOp, ModulateCompositeOp, ModulusAddCompositeOp, ModulusSubtractCompositeOp, MultiplyCompositeOp, NoCompositeOp, NoValue, _MagickPixelPacket::opacity, OpaqueAlphaChannel, OpaqueOpacity, OptionWarning, OutCompositeOp, OverCompositeOp, OverlayCompositeOp, ParseGeometry(), PegtopLightCompositeOp, PercentValue, PinLightCompositeOp, PlusCompositeOp, _Image::progress_monitor, _GeometryInfo::psi, QuantumRange, QuantumScale, QueueCacheViewAuthenticPixels(), _MagickPixelPacket::red, ReplaceCompositeOp, ResamplePixelColor(), _GeometryInfo::rho, _Image::rows, SaturateCompositeOp, ScaleResampleFilter(), ScreenCompositeOp, SetGeometryInfo(), SetImageAlphaChannel(), SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelPacket(), SetPixelRed, SetResampleFilter(), _GeometryInfo::sigma, SigmaValue, _Image::signature, SoftLightCompositeOp, SrcAtopCompositeOp, SrcCompositeOp, SrcInCompositeOp, SrcOutCompositeOp, SrcOverCompositeOp, StereoCompositeOp, SyncCacheViewAuthenticPixels(), ThresholdCompositeOp, ThrowMagickException(), TraceEvent, TransparentOpacity, UndefinedInterpolatePixel, VividLightCompositeOp, WidthValue, _PointInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _GeometryInfo::xi, XorCompositeOp, XValue, _PointInfo::y, _SegmentInfo::y1, _SegmentInfo::y2, and YValue.
Referenced by CompositeImage(), and MorphologyApply().
CompositeIn()
static void CompositeIn (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, In(), _MagickPixelPacket::index, _MagickPixelPacket::opacity, PerceptibleReciprocal(), QuantumRange, QuantumScale, and _MagickPixelPacket::red.
Referenced by CompositeImageChannel().
CompositeLighten()
static void CompositeLighten (const MagickPixelPacket * p, const MagickPixelPacket * q, const ChannelType channel, MagickPixelPacket * composite) inline static
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, Lighten(), MagickMax, MagickMin, _MagickPixelPacket::opacity, PerceptibleReciprocal(), QuantumScale, _MagickPixelPacket::red, RedChannel, and SyncChannels.
Referenced by CompositeImageChannel().
CompositeLightenIntensity()
static void CompositeLightenIntensity (const MagickPixelPacket * p, const MagickPixelPacket * q, const ChannelType channel, MagickPixelPacket * composite) inline static
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, MagickPixelIntensity(), _MagickPixelPacket::opacity, QuantumScale, _MagickPixelPacket::red, RedChannel, and SyncChannels.
Referenced by CompositeImageChannel().
CompositeLinearBurn()
static void CompositeLinearBurn (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, LinearBurn(), MagickEpsilon, _MagickPixelPacket::opacity, QuantumRange, QuantumScale, _MagickPixelPacket::red, and RoundToUnity().
Referenced by CompositeImageChannel().
CompositeLinearDodge()
static void CompositeLinearDodge (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, _MagickPixelPacket::opacity, PerceptibleReciprocal(), QuantumRange, QuantumScale, _MagickPixelPacket::red, and RoundToUnity().
Referenced by CompositeImageChannel().
CompositeLinearLight()
static void CompositeLinearLight (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, LinearLight(), MagickEpsilon, _MagickPixelPacket::opacity, QuantumRange, QuantumScale, _MagickPixelPacket::red, and RoundToUnity().
Referenced by CompositeImageChannel().
CompositeMathematics()
static void CompositeMathematics (const MagickPixelPacket * p, const MagickPixelPacket * q, const ChannelType channel, const GeometryInfo * args, MagickPixelPacket * composite) inline static
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, MagickEpsilon, Mathematics(), _MagickPixelPacket::opacity, QuantumRange, QuantumScale, _MagickPixelPacket::red, RedChannel, RoundToUnity(), and SyncChannels.
Referenced by CompositeImageChannel().
CompositeMinus()
static void CompositeMinus (const MagickPixelPacket * p, const MagickPixelPacket * q, const ChannelType channel, MagickPixelPacket * composite) inline static
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, Minus(), _MagickPixelPacket::opacity, PerceptibleReciprocal(), QuantumRange, QuantumScale, _MagickPixelPacket::red, RedChannel, RoundToUnity(), and SyncChannels.
Referenced by CompositeImageChannel().
CompositeModulusAdd()
static void CompositeModulusAdd (const MagickPixelPacket * p, const MagickPixelPacket * q, const ChannelType channel, MagickPixelPacket * composite) inline static
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, ModulusAdd(), _MagickPixelPacket::opacity, PerceptibleReciprocal(), QuantumRange, QuantumScale, _MagickPixelPacket::red, RedChannel, RoundToUnity(), and SyncChannels.
Referenced by CompositeImageChannel().
CompositeModulusSubtract()
static void CompositeModulusSubtract (const MagickPixelPacket * p, const MagickPixelPacket * q, const ChannelType channel, MagickPixelPacket * composite) inline static
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, ModulusSubtract(), _MagickPixelPacket::opacity, PerceptibleReciprocal(), QuantumRange, QuantumScale, _MagickPixelPacket::red, RedChannel, RoundToUnity(), and SyncChannels.
Referenced by CompositeImageChannel().
CompositeMultiply()
static void CompositeMultiply (const MagickPixelPacket * p, const MagickPixelPacket * q, const ChannelType channel, MagickPixelPacket * composite) inline static
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, MagickEpsilon, Multiply(), _MagickPixelPacket::opacity, QuantumRange, QuantumScale, _MagickPixelPacket::red, RedChannel, RoundToUnity(), and SyncChannels.
Referenced by CompositeImageChannel().
CompositeOut()
static void CompositeOut (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, _MagickPixelPacket::opacity, Out(), PerceptibleReciprocal(), QuantumRange, QuantumScale, and _MagickPixelPacket::red.
Referenced by CompositeImageChannel().
CompositePegtopLight()
static void CompositePegtopLight (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, MagickEpsilon, _MagickPixelPacket::opacity, PegtopLight(), QuantumRange, QuantumScale, _MagickPixelPacket::red, and RoundToUnity().
Referenced by CompositeImageChannel().
CompositePinLight()
static void CompositePinLight (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, MagickEpsilon, _MagickPixelPacket::opacity, PinLight(), QuantumRange, QuantumScale, _MagickPixelPacket::red, and RoundToUnity().
Referenced by CompositeImageChannel().
CompositePlus()
static void CompositePlus (const MagickPixelPacket * p, const MagickPixelPacket * q, const ChannelType channel, MagickPixelPacket * composite) inline static
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, MagickPixelCompositePlus(), _MagickPixelPacket::opacity, QuantumRange, _MagickPixelPacket::red, RedChannel, and SyncChannels.
Referenced by CompositeImageChannel().
CompositeScreen()
static void CompositeScreen (const MagickPixelPacket * p, const MagickPixelPacket * q, const ChannelType channel, MagickPixelPacket * composite) inline static
References AlphaChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, MagickEpsilon, _MagickPixelPacket::opacity, QuantumRange, QuantumScale, _MagickPixelPacket::red, RedChannel, RoundToUnity(), Screen(), and SyncChannels.
Referenced by CompositeImageChannel().
CompositeSoftLight()
static void CompositeSoftLight (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, MagickEpsilon, _MagickPixelPacket::opacity, QuantumRange, QuantumScale, _MagickPixelPacket::red, RoundToUnity(), and SoftLight().
Referenced by CompositeImageChannel().
CompositeThreshold()
static void CompositeThreshold (const MagickPixelPacket * p, const MagickPixelPacket * q, const MagickRealType threshold, const MagickRealType amount, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, _MagickPixelPacket::opacity, QuantumRange, _MagickPixelPacket::red, and Threshold().
Referenced by CompositeImageChannel().
CompositeVividLight()
static void CompositeVividLight (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, MagickEpsilon, _MagickPixelPacket::opacity, QuantumRange, QuantumScale, _MagickPixelPacket::red, RoundToUnity(), and VividLight().
Referenced by CompositeImageChannel().
CompositeXor()
static void CompositeXor (const MagickPixelPacket * p, const MagickPixelPacket * q, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, _MagickPixelPacket::opacity, PerceptibleReciprocal(), QuantumRange, QuantumScale, _MagickPixelPacket::red, and Xor().
Referenced by CompositeImageChannel().
Darken()
static MagickRealType Darken (const MagickRealType p, const MagickRealType alpha, const MagickRealType q, const MagickRealType beta) inline static
References MagickOver_().
Referenced by CompositeDarken().
Difference()
static MagickRealType Difference (const MagickRealType p, const MagickRealType Sa, const MagickRealType q, const MagickRealType Da) inline static
References MagickMin.
Referenced by CompositeDifference().
Divide()
static MagickRealType Divide (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da) static
References MagickEpsilon, and PerceptibleReciprocal().
Referenced by CompositeDivide().
Exclusion()
static MagickRealType Exclusion (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da) static
Referenced by CompositeExclusion().
HardLight()
static MagickRealType HardLight (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da) static
Referenced by CompositeHardLight().
HardMix()
static MagickRealType HardMix (const MagickRealType Sca, const MagickRealType Dca) static
References QuantumRange.
Referenced by CompositeHardMix().
HCLComposite()
static void HCLComposite (const double hue, const double chroma, const double luma, MagickRealType * red, MagickRealType * green, MagickRealType * blue) static
References QuantumRange.
Referenced by CompositeImageChannel().
In()
static MagickRealType In (const MagickRealType p, const MagickRealType Sa, const MagickRealType magick_unusedq, const MagickRealType Da) inline static
References magick_unreferenced.
Referenced by CompositeIn().
Lighten()
static MagickRealType Lighten (const MagickRealType p, const MagickRealType alpha, const MagickRealType q, const MagickRealType beta) inline static
References MagickOver_().
Referenced by CompositeLighten().
LinearBurn()
static MagickRealType LinearBurn (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da) inline static
Referenced by CompositeLinearBurn().
LinearLight()
static MagickRealType LinearLight (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da) inline static
Referenced by CompositeLinearLight().
Mathematics()
static MagickRealType Mathematics (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da, const GeometryInfo * geometry_info) inline static
References _GeometryInfo::psi, _GeometryInfo::rho, _GeometryInfo::sigma, and _GeometryInfo::xi.
Referenced by CompositeMathematics().
Minus()
static MagickRealType Minus (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType magick_unusedDa) inline static
References magick_unreferenced.
Referenced by CompositeMinus().
ModulusAdd()
static MagickRealType ModulusAdd (const MagickRealType Sc, const MagickRealType Sa, const MagickRealType Dc, const MagickRealType Da) inline static
References QuantumRange.
Referenced by CompositeModulusAdd().
ModulusSubtract()
static MagickRealType ModulusSubtract (const MagickRealType Sc, const MagickRealType Sa, const MagickRealType Dc, const MagickRealType Da) inline static
References QuantumRange.
Referenced by CompositeModulusSubtract().
Multiply()
static MagickRealType Multiply (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da) inline static
Referenced by CompositeMultiply().
Out()
static MagickRealType Out (const MagickRealType p, const MagickRealType Sa, const MagickRealType magick_unusedq, const MagickRealType Da) inline static
References magick_unreferenced.
Referenced by CompositeOut().
PegtopLight()
static MagickRealType PegtopLight (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da) static
References MagickEpsilon, and PerceptibleReciprocal().
Referenced by CompositePegtopLight().
PinLight()
static MagickRealType PinLight (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da) static
Referenced by CompositePinLight().
Screen()
static MagickRealType Screen (const MagickRealType Sca, const MagickRealType Dca) inline static
Referenced by CompositeScreen().
SoftLight()
static MagickRealType SoftLight (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da) static
References PerceptibleReciprocal().
Referenced by CompositeSoftLight().
TextureImage()
MagickExport MagickBooleanType TextureImage (Image * image, const Image * texture)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::compose, CompositeImage(), CopyCompositeOp, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OverCompositeOp, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetImageStorageClass(), SetImageVirtualPixelMethod(), _Image::signature, SyncCacheViewAuthenticPixels(), TextureImageTag, _Image::tile_offset, TileVirtualPixelMethod, TraceEvent, TransformImageColorspace(), _RectangleInfo::x, and _RectangleInfo::y.
Referenced by MontageImageList().
Threshold()
static MagickRealType Threshold (const MagickRealType p, const MagickRealType q, const MagickRealType threshold, const MagickRealType amount) inline static
Referenced by CompositeThreshold().
VividLight()
static MagickRealType VividLight (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da) static
References MagickEpsilon, and PerceptibleReciprocal().
Referenced by CompositeVividLight().
Xor()
static MagickRealType Xor (const MagickRealType Sca, const MagickRealType Sa, const MagickRealType Dca, const MagickRealType Da) static
Referenced by CompositeXor().