MagickCore: compare.h File Reference
compare.h File Reference
#include "magick/image.h"
Enumerations
enum MetricType {
UndefinedMetric , AbsoluteErrorMetric , MeanAbsoluteErrorMetric , MeanErrorPerPixelMetric ,
MeanSquaredErrorMetric , PeakAbsoluteErrorMetric , PeakSignalToNoiseRatioMetric , RootMeanSquaredErrorMetric ,
NormalizedCrossCorrelationErrorMetric , FuzzErrorMetric , UndefinedErrorMetric = 0 , PerceptualHashErrorMetric = 0xff
}
Functions
MagickExport double * GetImageChannelDistortions (Image *, const Image *, const MetricType, ExceptionInfo *)
MagickExport Image * CompareImageChannels (Image *, const Image *, const ChannelType, const MetricType, double *, ExceptionInfo *)
MagickExport Image * CompareImages (Image *, const Image *, const MetricType, double *, ExceptionInfo *)
MagickExport Image * SimilarityImage (Image *, const Image *, RectangleInfo *, double *, ExceptionInfo *)
MagickExport Image * SimilarityMetricImage (Image *, const Image *, const MetricType, RectangleInfo *, double *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageChannelDistortion (Image *, const Image *, const ChannelType, const MetricType, double *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageDistortion (Image *, const Image *, const MetricType, double *, ExceptionInfo *)
MagickExport MagickBooleanType IsImagesEqual (Image *, const Image *)
Enumeration Type Documentation
MetricType
enum MetricType
Enumerator
UndefinedMetric
AbsoluteErrorMetric
MeanAbsoluteErrorMetric
MeanErrorPerPixelMetric
MeanSquaredErrorMetric
PeakAbsoluteErrorMetric
PeakSignalToNoiseRatioMetric
RootMeanSquaredErrorMetric
NormalizedCrossCorrelationErrorMetric
FuzzErrorMetric
UndefinedErrorMetric
PerceptualHashErrorMetric
Function Documentation
CompareImageChannels()
MagickExport Image * CompareImageChannels (Image * , const Image * , const ChannelType, const MetricType, double * , ExceptionInfo *)
CompareImages()
MagickExport Image * CompareImages (Image * , const Image * , const MetricType, double * , ExceptionInfo *)
GetImageChannelDistortion()
MagickExport MagickBooleanType GetImageChannelDistortion (Image * , const Image * , const ChannelType, const MetricType, double * , ExceptionInfo *)
GetImageChannelDistortions()
MagickExport double * GetImageChannelDistortions (Image * image, const Image * reconstruct_image, const MetricType, ExceptionInfo * exception)
References AbsoluteErrorMetric, AcquireQuantumMemory(), CompositeChannels, _Image::debug, _Image::exception, _Image::filename, FuzzErrorMetric, GetAbsoluteDistortion(), GetFuzzDistortion(), GetMagickModule, GetMeanAbsoluteDistortion(), GetMeanErrorPerPixel(), GetMeanSquaredDistortion(), GetNormalizedCrossCorrelationDistortion(), GetPeakAbsoluteDistortion(), GetPeakSignalToNoiseRatio(), GetPerceptualHashDistortion(), GetRootMeanSquaredDistortion(), ImageError, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, MeanAbsoluteErrorMetric, MeanErrorPerPixelMetric, MeanSquaredErrorMetric, NormalizedCrossCorrelationErrorMetric, PeakAbsoluteErrorMetric, PeakSignalToNoiseRatioMetric, PerceptualHashErrorMetric, RelinquishMagickMemory(), ResourceLimitFatalError, RootMeanSquaredErrorMetric, _Image::signature, ThrowFatalException, ThrowMagickException(), TraceEvent, and ValidateImageMorphology().
GetImageDistortion()
MagickExport MagickBooleanType GetImageDistortion (Image * , const Image * , const MetricType, double * , ExceptionInfo *)
IsImagesEqual()
MagickExport MagickBooleanType IsImagesEqual (Image * image, const Image * reconstruct_image)
References AcquireVirtualCacheView(), CMYKColorspace, _Image::colorspace, _Image::columns, DestroyCacheView(), _Image::error, _Image::exception, _Image::filename, GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, ImageError, magick_restrict, MagickCoreSignature, MagickFalse, MagickMax, MagickTrue, _Image::matte, _ErrorInfo::mean_error_per_pixel, _ErrorInfo::normalized_maximum_error, _ErrorInfo::normalized_mean_error, PerceptibleReciprocal(), QuantumScale, _Image::rows, _Image::signature, ThrowBinaryException, and ValidateImageMorphology().
SimilarityImage()
MagickExport Image * SimilarityImage (Image * , const Image * , RectangleInfo * , double * , ExceptionInfo *)
SimilarityMetricImage()
MagickExport Image * SimilarityMetricImage (Image * image, const Image * reference, const MetricType, RectangleInfo * offset, double * similarity_metric, ExceptionInfo * exception)
References AcquireVirtualCacheView(), ClampToQuantum(), CloneImage(), _Image::columns, DeactivateAlphaChannel, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticPixels(), GetImageArtifact(), GetMagickModule, GetPixelRed, GetSimilarityMetric(), ImageError, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickMaximumValue, MagickMin, MagickTrue, NormalizedCrossCorrelationErrorMetric, PerceptualHashErrorMetric, _Image::progress_monitor, QuantumRange, _Image::rows, SetGeometry(), SetImageAlphaChannel(), SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SimilarityImageTag, StringToDouble(), SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, UndefinedErrorMetric, ValidateImageMorphology(), _RectangleInfo::x, and _RectangleInfo::y.
Referenced by SimilarityImage().