MagickCore: composite.h File Reference
composite.h File Reference
Macros
#define AddCompositeOp ModulusAddCompositeOp
#define SubtractCompositeOp ModulusSubtractCompositeOp
#define MinusCompositeOp MinusDstCompositeOp
#define DivideCompositeOp DivideDstCompositeOp
Enumerations
enum CompositeOperator {
UndefinedCompositeOp , NoCompositeOp , ModulusAddCompositeOp , AtopCompositeOp ,
BlendCompositeOp , BumpmapCompositeOp , ChangeMaskCompositeOp , ClearCompositeOp ,
ColorBurnCompositeOp , ColorDodgeCompositeOp , ColorizeCompositeOp , CopyBlackCompositeOp ,
CopyBlueCompositeOp , CopyCompositeOp , CopyCyanCompositeOp , CopyGreenCompositeOp ,
CopyMagentaCompositeOp , CopyOpacityCompositeOp , CopyRedCompositeOp , CopyYellowCompositeOp ,
DarkenCompositeOp , DstAtopCompositeOp , DstCompositeOp , DstInCompositeOp ,
DstOutCompositeOp , DstOverCompositeOp , DifferenceCompositeOp , DisplaceCompositeOp ,
DissolveCompositeOp , ExclusionCompositeOp , HardLightCompositeOp , HueCompositeOp ,
InCompositeOp , LightenCompositeOp , LinearLightCompositeOp , LuminizeCompositeOp ,
MinusDstCompositeOp , ModulateCompositeOp , MultiplyCompositeOp , OutCompositeOp ,
OverCompositeOp , OverlayCompositeOp , PlusCompositeOp , ReplaceCompositeOp ,
SaturateCompositeOp , ScreenCompositeOp , SoftLightCompositeOp , SrcAtopCompositeOp ,
SrcCompositeOp , SrcInCompositeOp , SrcOutCompositeOp , SrcOverCompositeOp ,
ModulusSubtractCompositeOp , ThresholdCompositeOp , XorCompositeOp , DivideDstCompositeOp ,
DistortCompositeOp , BlurCompositeOp , PegtopLightCompositeOp , VividLightCompositeOp ,
PinLightCompositeOp , LinearDodgeCompositeOp , LinearBurnCompositeOp , MathematicsCompositeOp ,
DivideSrcCompositeOp , MinusSrcCompositeOp , DarkenIntensityCompositeOp , LightenIntensityCompositeOp ,
HardMixCompositeOp , StereoCompositeOp
}
Functions
MagickExport MagickBooleanType CompositeImage (Image *, const CompositeOperator, const Image *, const ssize_t, const ssize_t)
MagickExport MagickBooleanType CompositeImageChannel (Image *, const ChannelType, const CompositeOperator, const Image *, const ssize_t, const ssize_t)
MagickExport MagickBooleanType TextureImage (Image *, const Image *)
Macro Definition Documentation
AddCompositeOp
#define AddCompositeOp ModulusAddCompositeOp
DivideCompositeOp
#define DivideCompositeOp DivideDstCompositeOp
MinusCompositeOp
#define MinusCompositeOp MinusDstCompositeOp
SubtractCompositeOp
#define SubtractCompositeOp ModulusSubtractCompositeOp
Enumeration Type Documentation
CompositeOperator
enum CompositeOperator
Enumerator
UndefinedCompositeOp
NoCompositeOp
ModulusAddCompositeOp
AtopCompositeOp
BlendCompositeOp
BumpmapCompositeOp
ChangeMaskCompositeOp
ClearCompositeOp
ColorBurnCompositeOp
ColorDodgeCompositeOp
ColorizeCompositeOp
CopyBlackCompositeOp
CopyBlueCompositeOp
CopyCompositeOp
CopyCyanCompositeOp
CopyGreenCompositeOp
CopyMagentaCompositeOp
CopyOpacityCompositeOp
CopyRedCompositeOp
CopyYellowCompositeOp
DarkenCompositeOp
DstAtopCompositeOp
DstCompositeOp
DstInCompositeOp
DstOutCompositeOp
DstOverCompositeOp
DifferenceCompositeOp
DisplaceCompositeOp
DissolveCompositeOp
ExclusionCompositeOp
HardLightCompositeOp
HueCompositeOp
InCompositeOp
LightenCompositeOp
LinearLightCompositeOp
LuminizeCompositeOp
MinusDstCompositeOp
ModulateCompositeOp
MultiplyCompositeOp
OutCompositeOp
OverCompositeOp
OverlayCompositeOp
PlusCompositeOp
ReplaceCompositeOp
SaturateCompositeOp
ScreenCompositeOp
SoftLightCompositeOp
SrcAtopCompositeOp
SrcCompositeOp
SrcInCompositeOp
SrcOutCompositeOp
SrcOverCompositeOp
ModulusSubtractCompositeOp
ThresholdCompositeOp
XorCompositeOp
DivideDstCompositeOp
DistortCompositeOp
BlurCompositeOp
PegtopLightCompositeOp
VividLightCompositeOp
PinLightCompositeOp
LinearDodgeCompositeOp
LinearBurnCompositeOp
MathematicsCompositeOp
DivideSrcCompositeOp
MinusSrcCompositeOp
DarkenIntensityCompositeOp
LightenIntensityCompositeOp
HardMixCompositeOp
StereoCompositeOp
Function Documentation
CompositeImage()
MagickExport MagickBooleanType CompositeImage (Image * , const CompositeOperator, const Image * , const ssize_t, const ssize_t)
CompositeImageChannel()
MagickExport MagickBooleanType CompositeImageChannel (Image * , const ChannelType, const CompositeOperator, const Image * , const ssize_t, const ssize_t)
TextureImage()
MagickExport MagickBooleanType TextureImage (Image * image, const Image * texture)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::compose, CompositeImage(), CopyCompositeOp, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OverCompositeOp, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetImageStorageClass(), SetImageVirtualPixelMethod(), _Image::signature, SyncCacheViewAuthenticPixels(), TextureImageTag, _Image::tile_offset, TileVirtualPixelMethod, TraceEvent, TransformImageColorspace(), _RectangleInfo::x, and _RectangleInfo::y.
Referenced by MontageImageList().