MagickCore: composite-private.h File Reference
composite-private.h File Reference
#include "magick/color.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/pixel-private.h"
Functions
static MagickRealType RoundToUnity (const MagickRealType value)
static MagickRealType MagickOver_ (const MagickRealType p, const MagickRealType alpha, const MagickRealType q, const MagickRealType beta)
static void MagickCompositeOver (const PixelPacket *p, const MagickRealType alpha, const PixelPacket *q, const MagickRealType beta, PixelPacket *composite)
static void MagickPixelCompositeOver (const MagickPixelPacket *p, const MagickRealType alpha, const MagickPixelPacket *q, const MagickRealType beta, MagickPixelPacket *composite)
static void MagickPixelCompositePlus (const MagickPixelPacket *p, const MagickRealType alpha, const MagickPixelPacket *q, const MagickRealType beta, MagickPixelPacket *composite)
static void MagickPixelCompositeBlend (const MagickPixelPacket *p, const MagickRealType alpha, const MagickPixelPacket *q, const MagickRealType beta, MagickPixelPacket *composite)
static void MagickPixelCompositeAreaBlend (const MagickPixelPacket *p, const MagickRealType alpha, const MagickPixelPacket *q, const MagickRealType beta, const MagickRealType area, MagickPixelPacket *composite)
Function Documentation
MagickCompositeOver()
static void MagickCompositeOver (const PixelPacket * p, const MagickRealType alpha, const PixelPacket * q, const MagickRealType beta, PixelPacket * composite) inline static
References ClampToQuantum(), GetPixelBlue, GetPixelGreen, GetPixelRed, MagickOver_(), PerceptibleReciprocal(), QuantumRange, QuantumScale, RoundToUnity(), SetPixelBlue, SetPixelGreen, SetPixelOpacity, and SetPixelRed.
Referenced by ColorFloodfillImage(), DrawPolygonPrimitive(), and DrawPrimitive().
MagickOver_()
static MagickRealType MagickOver_ (const MagickRealType p, const MagickRealType alpha, const MagickRealType q, const MagickRealType beta) inline static
References QuantumScale.
Referenced by ApplyPixelCompositeMask(), ClipPixelCacheNexus(), Darken(), Lighten(), MagickCompositeOver(), MagickPixelCompositeOver(), and SetImageAlphaChannel().
MagickPixelCompositeAreaBlend()
static void MagickPixelCompositeAreaBlend (const MagickPixelPacket * p, const MagickRealType alpha, const MagickPixelPacket * q, const MagickRealType beta, const MagickRealType area, MagickPixelPacket * composite) inline static
References MagickPixelCompositePlus(), and QuantumRange.
Referenced by HaldClutImageChannel(), XShearImage(), and YShearImage().
MagickPixelCompositeBlend()
static void MagickPixelCompositeBlend (const MagickPixelPacket * p, const MagickRealType alpha, const MagickPixelPacket * q, const MagickRealType beta, MagickPixelPacket * composite) inline static
References MagickPixelCompositePlus(), _MagickPixelPacket::opacity, and QuantumRange.
Referenced by CompositeImageChannel(), DistortImage(), and DrawGradientImage().
MagickPixelCompositeOver()
static void MagickPixelCompositeOver (const MagickPixelPacket * p, const MagickRealType alpha, const MagickPixelPacket * q, const MagickRealType beta, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, MagickOver_(), _MagickPixelPacket::opacity, PerceptibleReciprocal(), QuantumRange, QuantumScale, _MagickPixelPacket::red, and RoundToUnity().
Referenced by CompositeImageChannel(), and DrawAffineImage().
MagickPixelCompositePlus()
static void MagickPixelCompositePlus (const MagickPixelPacket * p, const MagickRealType alpha, const MagickPixelPacket * q, const MagickRealType beta, MagickPixelPacket * composite) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, _MagickPixelPacket::opacity, PerceptibleReciprocal(), QuantumRange, QuantumScale, _MagickPixelPacket::red, and RoundToUnity().
Referenced by CompositePlus(), MagickPixelCompositeAreaBlend(), and MagickPixelCompositeBlend().
RoundToUnity()
static MagickRealType RoundToUnity (const MagickRealType value) inline static
Referenced by CompositeColorBurn(), CompositeColorDodge(), CompositeDifference(), CompositeDivide(), CompositeExclusion(), CompositeHardLight(), CompositeHardMix(), CompositeLinearBurn(), CompositeLinearDodge(), CompositeLinearLight(), CompositeMathematics(), CompositeMinus(), CompositeModulusAdd(), CompositeModulusSubtract(), CompositeMultiply(), CompositePegtopLight(), CompositePinLight(), CompositeScreen(), CompositeSoftLight(), CompositeVividLight(), MagickCompositeOver(), MagickPixelCompositeOver(), and MagickPixelCompositePlus().