MagickCore: compress.h File Reference
compress.h File Reference
Typedefs
typedef struct _Ascii85Info Ascii85Info
Enumerations
enum CompressionType {
UndefinedCompression , NoCompression , BZipCompression , DXT1Compression ,
DXT3Compression , DXT5Compression , FaxCompression , Group4Compression ,
JPEGCompression , JPEG2000Compression , LosslessJPEGCompression , LZWCompression ,
RLECompression , ZipCompression , ZipSCompression , PizCompression ,
Pxr24Compression , B44Compression , B44ACompression , LZMACompression ,
JBIG1Compression , JBIG2Compression , ZstdCompression , WebPCompression
}
Functions
MagickExport MagickBooleanType HuffmanDecodeImage (Image *)
MagickExport MagickBooleanType HuffmanEncodeImage (const ImageInfo *, Image *, Image *)
MagickExport MagickBooleanType LZWEncodeImage (Image *, const size_t, unsigned char *magick_restrict)
MagickExport MagickBooleanType PackbitsEncodeImage (Image *, const size_t, unsigned char *magick_restrict)
MagickExport MagickBooleanType ZLIBEncodeImage (Image *, const size_t, unsigned char *magick_restrict)
MagickExport void Ascii85Encode (Image *, const unsigned char)
MagickExport void Ascii85Flush (Image *)
MagickExport void Ascii85Initialize (Image *)
Typedef Documentation
Ascii85Info
typedef struct _Ascii85Info Ascii85Info
Enumeration Type Documentation
CompressionType
enum CompressionType
Enumerator
UndefinedCompression
NoCompression
BZipCompression
DXT1Compression
DXT3Compression
DXT5Compression
FaxCompression
Group4Compression
JPEGCompression
JPEG2000Compression
LosslessJPEGCompression
LZWCompression
RLECompression
ZipCompression
ZipSCompression
PizCompression
Pxr24Compression
B44Compression
B44ACompression
LZMACompression
JBIG1Compression
JBIG2Compression
ZstdCompression
WebPCompression
Function Documentation
Ascii85Encode()
MagickExport void Ascii85Encode (Image * , const unsigned char)
Ascii85Flush()
MagickExport void Ascii85Flush (Image *)
Ascii85Initialize()
MagickExport void Ascii85Initialize (Image * image)
References AcquireMagickMemory(), _Image::ascii85, _Ascii85Info::line_break, MaxLineExtent, _Ascii85Info::offset, ResourceLimitFatalError, and ThrowFatalException.
Referenced by CloneImage(), and HuffmanEncodeImage().
HuffmanDecodeImage()
MagickExport MagickBooleanType HuffmanDecodeImage (Image *)
HuffmanEncodeImage()
MagickExport MagickBooleanType HuffmanEncodeImage (const ImageInfo * , Image * , Image *)
LZWEncodeImage()
MagickExport MagickBooleanType LZWEncodeImage (Image * , const size_t, unsigned char * magick_restrict)
PackbitsEncodeImage()
MagickExport MagickBooleanType PackbitsEncodeImage (Image * , const size_t, unsigned char * magick_restrict)
ZLIBEncodeImage()
MagickExport MagickBooleanType ZLIBEncodeImage (Image * , const size_t, unsigned char * magick_restrict)