MagickCore: configure.c File Reference
configure.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/client.h"
#include "magick/configure.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/hashmap.h"
#include "magick/log.h"
#include "magick/memory_.h"
#include "magick/nt-base-private.h"
#include "magick/semaphore.h"
#include "magick/string_.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/version.h"
#include "magick/xml-tree.h"
#include "magick/xml-tree-private.h"
Data Structures
struct _ConfigureMapInfo
Macros
#define ConfigureFilename "configure.xml"
#define RegistryKey "ConfigurePath"
#define MagickCoreDLL "CORE_RL_magick_.dll"
#define MagickCoreDebugDLL "CORE_DB_magick_.dll"
Typedefs
typedef struct _ConfigureMapInfo ConfigureMapInfo
Functions
static MagickBooleanType IsConfigureCacheInstantiated (ExceptionInfo *)
static MagickBooleanType LoadConfigureCache (LinkedListInfo *, const char *, const char *, const size_t, ExceptionInfo *)
static void AddConfigureKey (LinkedListInfo *cache, const char *path, const char *name, const char *value)
static LinkedListInfo * AcquireConfigureCache (const char *filename, ExceptionInfo *exception)
MagickExport MagickBooleanType ConfigureComponentGenesis (void)
static void * DestroyConfigureElement (void *configure_info)
MagickExport void ConfigureComponentTerminus (void)
static void * DestroyOptions (void *option)
MagickExport LinkedListInfo * DestroyConfigureOptions (LinkedListInfo *options)
MagickExport const ConfigureInfo * GetConfigureInfo (const char *name, ExceptionInfo *exception)
static int ConfigureInfoCompare (const void *x, const void *y)
MagickExport const ConfigureInfo ** GetConfigureInfoList (const char *pattern, size_t *number_options, ExceptionInfo *exception)
static int ConfigureCompare (const void *x, const void *y)
MagickExport char ** GetConfigureList (const char *pattern, size_t *number_options, ExceptionInfo *exception)
MagickExport char * GetConfigureOption (const char *option)
MagickExport LinkedListInfo * GetConfigureOptions (const char *filename, ExceptionInfo *exception)
MagickExport LinkedListInfo * GetConfigurePaths (const char *filename, ExceptionInfo *exception)
MagickExport const char * GetConfigureValue (const ConfigureInfo *configure_info)
MagickExport MagickBooleanType ListConfigureInfo (FILE *file, ExceptionInfo *exception)
Variables
static LinkedListInfo * configure_cache = (LinkedListInfo *) NULL
static SemaphoreInfo * configure_semaphore = (SemaphoreInfo *) NULL
Macro Definition Documentation
ConfigureFilename
#define ConfigureFilename "configure.xml"
MagickCoreDebugDLL
#define MagickCoreDebugDLL "CORE_DB_magick_.dll"
MagickCoreDLL
#define MagickCoreDLL "CORE_RL_magick_.dll"
RegistryKey
#define RegistryKey "ConfigurePath"
Typedef Documentation
ConfigureMapInfo
typedef struct _ConfigureMapInfo ConfigureMapInfo
Function Documentation
AcquireConfigureCache()
static LinkedListInfo * AcquireConfigureCache (const char * filename, ExceptionInfo * exception) static
References AddConfigureKey(), DestroyConfigureOptions(), GetConfigureOptions(), GetMagickDelegates(), GetMagickFeatures(), GetMagickQuantumDepth(), GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), LoadConfigureCache(), MagickTrue, NewLinkedList(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by IsConfigureCacheInstantiated().
AddConfigureKey()
static void AddConfigureKey (LinkedListInfo * cache, const char * path, const char * name, const char * value) inline static
References AcquireMagickMemory(), AppendValueToLinkedList(), _ConfigureInfo::exempt, MagickCoreSignature, MagickTrue, _ConfigureInfo::name, _ConfigureInfo::path, _ConfigureInfo::signature, and _ConfigureInfo::value.
Referenced by AcquireConfigureCache().
ConfigureCompare()
static int ConfigureCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetConfigureList().
ConfigureComponentGenesis()
MagickExport MagickBooleanType ConfigureComponentGenesis (void)
References AllocateSemaphoreInfo(), configure_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
ConfigureComponentTerminus()
MagickExport void ConfigureComponentTerminus (void)
References ActivateSemaphoreInfo(), configure_cache, configure_semaphore, DestroyConfigureElement(), DestroyLinkedList(), DestroySemaphoreInfo(), LockSemaphoreInfo(), and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
ConfigureInfoCompare()
static int ConfigureInfoCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetConfigureInfoList().
DestroyConfigureElement()
static void * DestroyConfigureElement (void * configure_info) static
References DestroyString(), _ConfigureInfo::exempt, MagickFalse, _ConfigureInfo::name, _ConfigureInfo::path, RelinquishMagickMemory(), and _ConfigureInfo::value.
Referenced by ConfigureComponentTerminus().
DestroyConfigureOptions()
MagickExport LinkedListInfo * DestroyConfigureOptions (LinkedListInfo * options)
References DestroyLinkedList(), and DestroyOptions().
Referenced by AcquireCoderCache(), AcquireColorCache(), AcquireConfigureCache(), AcquireDelegateCache(), AcquireMagicCache(), AcquireMimeCache(), AcquirePolicyCache(), AcquireTypeCache(), GetThresholdMap(), and ListThresholdMaps().
DestroyOptions()
static void * DestroyOptions (void * option) static
References DestroyStringInfo().
Referenced by DestroyConfigureOptions().
GetConfigureInfo()
MagickExport const ConfigureInfo * GetConfigureInfo (const char * name, ExceptionInfo * exception)
References configure_cache, configure_semaphore, GetNextValueInLinkedList(), InsertValueInLinkedList(), IsConfigureCacheInstantiated(), LocaleCompare(), LockSemaphoreInfo(), MagickFalse, _ConfigureInfo::name, RemoveElementByValueFromLinkedList(), ResetLinkedListIterator(), and UnlockSemaphoreInfo().
Referenced by GetConfigureInfoList(), GetConfigureList(), and GetConfigureOption().
GetConfigureInfoList()
MagickExport const ConfigureInfo ** GetConfigureInfoList (const char * pattern, size_t * number_options, ExceptionInfo * exception)
References AcquireQuantumMemory(), configure_cache, configure_semaphore, ConfigureInfoCompare(), GetConfigureInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _ConfigureInfo::name, ResetLinkedListIterator(), _ConfigureInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListConfigureInfo().
GetConfigureList()
MagickExport char ** GetConfigureList (const char * pattern, size_t * number_options, ExceptionInfo * exception)
References AcquireQuantumMemory(), configure_cache, configure_semaphore, ConfigureCompare(), ConstantString(), GetConfigureInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _ConfigureInfo::name, ResetLinkedListIterator(), _ConfigureInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
GetConfigureOption()
MagickExport char * GetConfigureOption (const char * option)
References AcquireExceptionInfo(), ConstantString(), DestroyExceptionInfo(), GetConfigureInfo(), GetConfigureValue(), GetMagickModule, LogMagickEvent(), and TraceEvent.
GetConfigureOptions()
MagickExport LinkedListInfo * GetConfigureOptions (const char * filename, ExceptionInfo * exception)
References AcquireStringInfo(), AppendValueToLinkedList(), ConfigureEvent, ConfigureFileToStringInfo(), ConfigureWarning, CopyMagickString(), DestroyLinkedList(), FormatLocaleString(), GetConfigurePaths(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), LogMagickEvent(), MaxTextExtent, NewLinkedList(), RelinquishMagickMemory(), ResetLinkedListIterator(), SetStringInfoDatum(), SetStringInfoLength(), SetStringInfoPath(), ThrowMagickException(), and TraceEvent.
Referenced by AcquireCoderCache(), AcquireColorCache(), AcquireConfigureCache(), AcquireDelegateCache(), AcquireMagicCache(), AcquireMimeCache(), AcquirePolicyCache(), AcquireTypeCache(), GetThresholdMap(), and ListThresholdMaps().
GetConfigurePaths()
MagickExport LinkedListInfo * GetConfigurePaths (const char * filename, ExceptionInfo * exception)
References AppendValueToLinkedList(), ChopPathComponents(), ConcatenateMagickString(), ConfigureWarning, ConstantString(), CopyMagickString(), DestroyString(), DirectoryListSeparator, DirectorySeparator, FormatLocaleString(), GetClientPath(), GetEnvironmentValue(), GetMagickModule, GetNumberOfElementsInLinkedList(), LogMagickEvent(), MAGICKCORE_CONFIGURE_PATH, MAGICKCORE_CONFIGURE_RELATIVE_PATH, MAGICKCORE_DOCUMENTATION_PATH, MAGICKCORE_SHARE_PATH, MAGICKCORE_SHARE_RELATIVE_PATH, MagickCoreDebugDLL, MagickCoreDLL, MagickFalse, MaxTextExtent, NewLinkedList(), RegistryKey, RelinquishMagickMemory(), ThrowMagickException(), and TraceEvent.
Referenced by GetConfigureOptions(), GetLocaleOptions(), and GetMagickHomeURL().
GetConfigureValue()
MagickExport const char * GetConfigureValue (const ConfigureInfo * configure_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _ConfigureInfo::signature, TraceEvent, and _ConfigureInfo::value.
Referenced by GetConfigureOption().
IsConfigureCacheInstantiated()
static MagickBooleanType IsConfigureCacheInstantiated (ExceptionInfo * exception) static
References AcquireConfigureCache(), ActivateSemaphoreInfo(), configure_cache, configure_semaphore, ConfigureFilename, LockSemaphoreInfo(), MagickFalse, MagickTrue, and UnlockSemaphoreInfo().
Referenced by GetConfigureInfo().
ListConfigureInfo()
MagickExport MagickBooleanType ListConfigureInfo (FILE * file, ExceptionInfo * exception)
References FormatLocaleFile(), GetConfigureInfoList(), LocaleCompare(), MagickFalse, MagickTrue, _ConfigureInfo::path, and RelinquishMagickMemory().
LoadConfigureCache()
static MagickBooleanType LoadConfigureCache (LinkedListInfo * cache, const char * xml, const char * filename, const size_t depth, ExceptionInfo * exception) static
References AcquireQuantumMemory(), AcquireString(), AppendValueToLinkedList(), ConcatenateMagickString(), ConfigureError, ConfigureEvent, ConstantString(), CopyMagickString(), DirectorySeparator, _ConfigureInfo::exempt, FileToXML(), GetMagickModule, GetNextToken(), GetPathComponent(), HeadPath, IsMagickTrue(), LoadConfigureCache(), LocaleCompare(), LocaleNCompare(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickMaxRecursionDepth, MagickTrue, MaxTextExtent, _ConfigureInfo::name, _ConfigureInfo::path, RelinquishMagickMemory(), ResourceLimitError, ResourceLimitFatalError, _ConfigureInfo::signature, _ConfigureInfo::stealth, ThrowFatalException, ThrowMagickException(), and _ConfigureInfo::value.
Referenced by AcquireConfigureCache(), and LoadConfigureCache().
Variable Documentation
configure_cache
LinkedListInfo* configure_cache = (LinkedListInfo *) NULL static
Referenced by ConfigureComponentTerminus(), GetConfigureInfo(), GetConfigureInfoList(), GetConfigureList(), and IsConfigureCacheInstantiated().
configure_semaphore
SemaphoreInfo* configure_semaphore = (SemaphoreInfo *) NULL static
Referenced by ConfigureComponentGenesis(), ConfigureComponentTerminus(), GetConfigureInfo(), GetConfigureInfoList(), GetConfigureList(), and IsConfigureCacheInstantiated().