MagickCore: configure.h File Reference
configure.h File Reference
#include "magick/hashmap.h"
Data Structures
struct _ConfigureInfo
Typedefs
typedef struct _ConfigureInfo ConfigureInfo
Functions
MagickExport char ** GetConfigureList (const char *, size_t *, ExceptionInfo *)
MagickExport char * GetConfigureOption (const char *)
MagickExport const char * GetConfigureValue (const ConfigureInfo *)
MagickExport const ConfigureInfo * GetConfigureInfo (const char *, ExceptionInfo *)
MagickExport const ConfigureInfo ** GetConfigureInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport LinkedListInfo * DestroyConfigureOptions (LinkedListInfo *)
MagickExport LinkedListInfo * GetConfigurePaths (const char *, ExceptionInfo *)
MagickExport LinkedListInfo * GetConfigureOptions (const char *, ExceptionInfo *)
MagickExport MagickBooleanType ConfigureComponentGenesis (void)
MagickExport MagickBooleanType ListConfigureInfo (FILE *, ExceptionInfo *)
MagickExport void ConfigureComponentTerminus (void)
Typedef Documentation
ConfigureInfo
typedef struct _ConfigureInfo ConfigureInfo
Function Documentation
ConfigureComponentGenesis()
MagickExport MagickBooleanType ConfigureComponentGenesis (void)
ConfigureComponentTerminus()
MagickExport void ConfigureComponentTerminus (void)
References ActivateSemaphoreInfo(), configure_cache, configure_semaphore, DestroyConfigureElement(), DestroyLinkedList(), DestroySemaphoreInfo(), LockSemaphoreInfo(), and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
DestroyConfigureOptions()
MagickExport LinkedListInfo * DestroyConfigureOptions (LinkedListInfo *)
GetConfigureInfo()
MagickExport const ConfigureInfo * GetConfigureInfo (const char * , ExceptionInfo *)
GetConfigureInfoList()
MagickExport const ConfigureInfo ** GetConfigureInfoList (const char * pattern, size_t * number_options, ExceptionInfo * exception)
References AcquireQuantumMemory(), configure_cache, configure_semaphore, ConfigureInfoCompare(), GetConfigureInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _ConfigureInfo::name, ResetLinkedListIterator(), _ConfigureInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListConfigureInfo().
GetConfigureList()
MagickExport char ** GetConfigureList (const char * , size_t * , ExceptionInfo *)
GetConfigureOption()
MagickExport char * GetConfigureOption (const char * option)
References AcquireExceptionInfo(), ConstantString(), DestroyExceptionInfo(), GetConfigureInfo(), GetConfigureValue(), GetMagickModule, LogMagickEvent(), and TraceEvent.
GetConfigureOptions()
MagickExport LinkedListInfo * GetConfigureOptions (const char * filename, ExceptionInfo * exception)
References AcquireStringInfo(), AppendValueToLinkedList(), ConfigureEvent, ConfigureFileToStringInfo(), ConfigureWarning, CopyMagickString(), DestroyLinkedList(), FormatLocaleString(), GetConfigurePaths(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), LogMagickEvent(), MaxTextExtent, NewLinkedList(), RelinquishMagickMemory(), ResetLinkedListIterator(), SetStringInfoDatum(), SetStringInfoLength(), SetStringInfoPath(), ThrowMagickException(), and TraceEvent.
Referenced by AcquireCoderCache(), AcquireColorCache(), AcquireConfigureCache(), AcquireDelegateCache(), AcquireMagicCache(), AcquireMimeCache(), AcquirePolicyCache(), AcquireTypeCache(), GetThresholdMap(), and ListThresholdMaps().
GetConfigurePaths()
MagickExport LinkedListInfo * GetConfigurePaths (const char * , ExceptionInfo *)
GetConfigureValue()
MagickExport const char * GetConfigureValue (const ConfigureInfo * configure_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _ConfigureInfo::signature, TraceEvent, and _ConfigureInfo::value.
Referenced by GetConfigureOption().
ListConfigureInfo()
MagickExport MagickBooleanType ListConfigureInfo (FILE * file, ExceptionInfo * exception)
References FormatLocaleFile(), GetConfigureInfoList(), LocaleCompare(), MagickFalse, MagickTrue, _ConfigureInfo::path, and RelinquishMagickMemory().