MagickCore: constitute.c File Reference
constitute.c File Reference
#include "magick/studio.h"
#include "magick/attribute.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/cache.h"
#include "magick/client.h"
#include "magick/coder.h"
#include "magick/colorspace-private.h"
#include "magick/constitute.h"
#include "magick/delegate.h"
#include "magick/geometry.h"
#include "magick/identify.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/option.h"
#include "magick/pixel.h"
#include "magick/policy.h"
#include "magick/profile.h"
#include "magick/property.h"
#include "magick/quantum.h"
#include "magick/resize.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/statistic.h"
#include "magick/stream.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/timer.h"
#include "magick/token.h"
#include "magick/transform.h"
#include "magick/utility.h"
Macros
#define MaxReadRecursionDepth 100
#define WriteImageTag "Write/Image"
Functions
MagickExport Image * ConstituteImage (const size_t columns, const size_t rows, const char *map, const StorageType storage, const void *pixels, ExceptionInfo *exception)
static size_t PingStream (const Image *magick_unused(image), const void *magick_unused(pixels), const size_t columns)
MagickExport Image * PingImage (const ImageInfo *image_info, ExceptionInfo *exception)
MagickExport Image * PingImages (const ImageInfo *image_info, ExceptionInfo *exception)
static MagickBooleanType IsCoderAuthorized (const char *coder, const PolicyRights rights, ExceptionInfo *exception)
MagickExport Image * ReadImage (const ImageInfo *image_info, ExceptionInfo *exception)
MagickExport Image * ReadImages (const ImageInfo *image_info, ExceptionInfo *exception)
MagickExport Image * ReadInlineImage (const ImageInfo *image_info, const char *content, ExceptionInfo *exception)
MagickExport MagickBooleanType WriteImage (const ImageInfo *image_info, Image *image)
MagickExport MagickBooleanType WriteImages (const ImageInfo *image_info, Image *images, const char *filename, ExceptionInfo *exception)
Macro Definition Documentation
MaxReadRecursionDepth
#define MaxReadRecursionDepth 100
WriteImageTag
#define WriteImageTag "Write/Image"
Function Documentation
ConstituteImage()
MagickExport Image * ConstituteImage (const size_t columns, const size_t rows, const char * map, const StorageType storage, const void * pixels, ExceptionInfo * exception)
References AcquireImage(), CharPixel, CMYKColorspace, _Image::colorspace, _Image::depth, DestroyImage(), DoublePixel, _Image::exception, FloatPixel, GetMagickModule, GRAYColorspace, ImportImagePixels(), InheritException(), LogMagickEvent(), LongPixel, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, ResetImagePixels(), SetImageExtent(), ShortPixel, _ExceptionInfo::signature, and TraceEvent.
IsCoderAuthorized()
static MagickBooleanType IsCoderAuthorized (const char * coder, const PolicyRights rights, ExceptionInfo * exception) static
References CoderPolicyDomain, GetMagickModule, IsRightsAuthorized(), MagickFalse, MagickTrue, PolicyError, and ThrowMagickException().
Referenced by ReadImage(), and WriteImage().
PingImage()
MagickExport Image * PingImage (const ImageInfo * image_info, ExceptionInfo * exception)
References CloneImageInfo(), _ImageInfo::debug, DestroyImageInfo(), _ImageInfo::filename, GetMagickModule, IdentifyImage(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _ImageInfo::ping, PingStream(), ReadStream(), ResetTimer(), _ImageInfo::signature, _Image::timer, TraceEvent, and _ImageInfo::verbose.
Referenced by PingImages().
PingImages()
MagickExport Image * PingImages (const ImageInfo * image_info, ExceptionInfo * exception)
References AcquireExceptionInfo(), AppendImageToList(), CloneImageInfo(), CopyMagickString(), _ImageInfo::debug, DestroyExceptionInfo(), DestroyImageInfo(), _ImageInfo::filename, GetMagickModule, InterpretImageFilename(), LocaleCompare(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MaxTextExtent, NewImageList(), _ImageInfo::number_scenes, PingImage(), _ImageInfo::scene, SetImageInfo(), _ImageInfo::signature, and TraceEvent.
PingStream()
static size_t PingStream (const Image * magick_unusedimage, const void * magick_unusedpixels, const size_t columns) static
References magick_unreferenced.
Referenced by PingImage().
ReadImage()
MagickExport Image * ReadImage (const ImageInfo * image_info, ExceptionInfo * exception)
References AcquireExceptionInfo(), AcquireImage(), _Image::blur, CastDoubleToLong(), CloneImageInfo(), CloneImages(), CloseBlob(), _Image::color_profile, _Image::columns, CopyMagickString(), CorruptImageError, CropImage(), _ImageInfo::debug, DecoderThreadSupport, _Image::delay, DeleteImageProperty(), DestroyExceptionInfo(), DestroyImage(), DestroyImageInfo(), DestroyImageList(), DestroyString(), _Image::dispose, _ImageInfo::endian, ErrorException, ExceptionEvent, _ImageInfo::extract, _Image::filename, _ImageInfo::filename, FileOpenError, _Image::filter, FormatMagickTime(), GetBlobError(), GetBlobProperties(), GetDelegateInfo(), GetDelegateThreadSupport(), GetFirstImageInList(), GetImageDecoder(), GetImageListLength(), GetImageOption(), GetImageProfile(), GetImageProperty(), GetMagickEndianSupport(), GetMagickInfo(), GetMagickModule, GetMagickRawSupport(), GetMagickSeekableStream(), GetMagickThreadSupport(), GetNextImageInList(), GetPathComponent(), GetStringInfoDatum(), GetStringInfoLength(), GreaterValue, _RectangleInfo::height, HeightValue, IdentifyImage(), ImageToFile(), _ProfileInfo::info, InterpretImageProperties(), InvokeDelegate(), _Image::iptc_profile, IsBlobSeekable(), IsBlobTemporary(), IsCoderAuthorized(), IsPathAccessible(), IsSceneGeometry(), _ProfileInfo::length, LessValue, LocaleCompare(), LockSemaphoreInfo(), LogMagickEvent(), LSBEndian, _Image::magick, _ImageInfo::magick, _Image::magick_columns, _Image::magick_filename, _Image::magick_rows, MagickCoreSignature, MagickDisposeOptions, MagickFalse, MagickPath, MagickResolutionOptions, MagickTrue, MaxTextExtent, MissingDelegateError, MSBEndian, NewImageList(), OpenBlob(), _Image::orientation, _Image::page, ParseAbsoluteGeometry(), ParseCommandOption(), ParseGeometry(), ParseRegionGeometry(), PolicyError, ReadBinaryBlobMode, ReadPolicyRights, RelinquishUniqueFileResource(), ReplaceImageInList(), ResizeImage(), _GeometryInfo::rho, _Image::rows, _ImageInfo::scenes, _DelegateInfo::semaphore, _MagickInfo::semaphore, SetGeometry(), SetImageInfo(), SetImageProperty(), _ExceptionInfo::severity, _GeometryInfo::sigma, SigmaValue, _ImageInfo::signature, _ImageInfo::stream, StringToLong(), _Image::taint, _ImageInfo::temporary, ThrowFileException, ThrowMagickException(), ThrowReaderException, _Image::ticks_per_second, TraceEvent, UndefinedEndian, _Image::units, UnlockSemaphoreInfo(), _ImageInfo::verbose, _RectangleInfo::width, WidthValue, _Image::x_resolution, XValue, _Image::y_resolution, and YValue.
Referenced by BlobToImage(), DrawPrimitive(), IdentifyImage(), MontageImageList(), PreviewImage(), ReadImages(), ReadStream(), and RenderPostscript().
ReadImages()
MagickExport Image * ReadImages (const ImageInfo * image_info, ExceptionInfo * exception)
References AcquireExceptionInfo(), AppendImageToList(), CloneImageInfo(), CopyMagickString(), _ImageInfo::debug, DestroyExceptionInfo(), DestroyImageInfo(), _ImageInfo::filename, GetMagickModule, InterpretImageFilename(), LocaleCompare(), LogMagickEvent(), _ImageInfo::magick, MagickCoreSignature, MagickFalse, MaxTextExtent, NewImageList(), _ImageInfo::number_scenes, ReadImage(), _ImageInfo::scene, SetImageInfo(), _ImageInfo::signature, and TraceEvent.
ReadInlineImage()
MagickExport Image * ReadInlineImage (const ImageInfo * image_info, const char * content, ExceptionInfo * exception)
References Base64Decode(), BlobToImage(), CloneImageInfo(), CorruptImageError, DestroyImageInfo(), _ImageInfo::filename, LocaleNCompare(), _ImageInfo::magick, MagickPathExtent, NewImageList(), RelinquishMagickMemory(), SetImageInfoProgressMonitor(), and ThrowReaderException.
Referenced by DrawPrimitive().
WriteImage()
MagickExport MagickBooleanType WriteImage (const ImageInfo * image_info, Image * image)
References AcquireExceptionInfo(), AcquireUniqueFilename(), _ImageInfo::adjoin, _ImageInfo::affirm, _Image::clip_mask, CloneImageInfo(), CloseBlob(), CopyMagickString(), _Image::debug, DestroyExceptionInfo(), DestroyImageInfo(), DisassociateImageStream(), EncoderThreadSupport, _Image::endian, _ImageInfo::endian, _Image::exception, ExtensionPath, _Image::filename, _ImageInfo::filename, FileOpenError, GetBlobError(), GetDelegateInfo(), GetDelegateMode(), GetDelegateThreadSupport(), GetImageEncoder(), GetImageOption(), GetMagickEndianSupport(), GetMagickInfo(), GetMagickModule, GetMagickRawSupport(), GetMagickSeekableStream(), GetMagickThreadSupport(), GetNextImageInList(), GetPathComponent(), GetPreviousImageInList(), IdentifyImage(), ImageToFile(), InvokeDelegate(), IsBlobSeekable(), IsCoderAuthorized(), IsMagickTrue(), IsPathAccessible(), IsTaintImage(), LocaleCompare(), LockSemaphoreInfo(), LogMagickEvent(), LSBEndian, _Image::magick, _ImageInfo::magick, _Image::magick_filename, MagickCoreSignature, MagickFalse, MagickTrue, MaxTextExtent, MissingDelegateError, MissingDelegateWarning, MSBEndian, OpenBlob(), OptionError, _ImageInfo::page, PolicyError, ReadBinaryBlobMode, RelinquishUniqueFileResource(), _DelegateInfo::semaphore, _MagickInfo::semaphore, SetImageInfo(), _ExceptionInfo::severity, _Image::signature, _ImageInfo::signature, SyncImageProfiles(), ThrowMagickException(), ThrowWriterException, TraceEvent, UndefinedEndian, UnlockSemaphoreInfo(), _ImageInfo::verbose, WriteBinaryBlobMode, and WritePolicyRights.
Referenced by ImageToBlob(), InjectImageBlob(), InvokeDelegate(), PreviewImage(), WriteImages(), and WriteStream().
WriteImages()
MagickExport MagickBooleanType WriteImages (const ImageInfo * image_info, Image * images, const char * filename, ExceptionInfo * exception)
References AcquireExceptionInfo(), _ImageInfo::adjoin, _Image::client_data, CloneImageInfo(), CopyMagickString(), _Image::debug, DestroyExceptionInfo(), DestroyImageInfo(), _Image::filename, _ImageInfo::filename, GetFirstImageInList(), GetImageException(), GetImageListLength(), GetMagickModule, GetNextImageInList(), LogMagickEvent(), _Image::magick, _ImageInfo::magick, MagickCoreSignature, MagickFalse, MagickTrue, MaxTextExtent, _Image::scene, SetImageInfo(), SetImageProgress(), SetImageProgressMonitor(), _Image::signature, _ImageInfo::signature, TraceEvent, WriteImage(), and WriteImageTag.
Referenced by ImagesToBlob().