MagickCore: constitute.h File Reference
constitute.h File Reference
Enumerations
enum StorageType {
UndefinedPixel , CharPixel , DoublePixel , FloatPixel ,
IntegerPixel , LongPixel , QuantumPixel , ShortPixel
}
Functions
MagickExport Image * ConstituteImage (const size_t, const size_t, const char *, const StorageType, const void *, ExceptionInfo *)
MagickExport Image * PingImage (const ImageInfo *, ExceptionInfo *)
MagickExport Image * PingImages (const ImageInfo *, ExceptionInfo *)
MagickExport Image * ReadImage (const ImageInfo *, ExceptionInfo *)
MagickExport Image * ReadImages (const ImageInfo *, ExceptionInfo *)
MagickExport Image * ReadInlineImage (const ImageInfo *, const char *, ExceptionInfo *)
MagickExport MagickBooleanType WriteImage (const ImageInfo *, Image *)
MagickExport MagickBooleanType WriteImages (const ImageInfo *, Image *, const char *, ExceptionInfo *)
Enumeration Type Documentation
StorageType
enum StorageType
Enumerator
UndefinedPixel
CharPixel
DoublePixel
FloatPixel
IntegerPixel
LongPixel
QuantumPixel
ShortPixel
Function Documentation
ConstituteImage()
MagickExport Image * ConstituteImage (const size_t, const size_t, const char * , const StorageType, const void * , ExceptionInfo *)
PingImage()
MagickExport Image * PingImage (const ImageInfo * , ExceptionInfo *)
PingImages()
MagickExport Image * PingImages (const ImageInfo * , ExceptionInfo *)
ReadImage()
MagickExport Image * ReadImage (const ImageInfo * , ExceptionInfo *)
ReadImages()
MagickExport Image * ReadImages (const ImageInfo * , ExceptionInfo *)
ReadInlineImage()
MagickExport Image * ReadInlineImage (const ImageInfo * image_info, const char * content, ExceptionInfo * exception)
References Base64Decode(), BlobToImage(), CloneImageInfo(), CorruptImageError, DestroyImageInfo(), _ImageInfo::filename, LocaleNCompare(), _ImageInfo::magick, MagickPathExtent, NewImageList(), RelinquishMagickMemory(), SetImageInfoProgressMonitor(), and ThrowReaderException.
Referenced by DrawPrimitive().
WriteImage()
MagickExport MagickBooleanType WriteImage (const ImageInfo * , Image *)
WriteImages()
MagickExport MagickBooleanType WriteImages (const ImageInfo * image_info, Image * images, const char * filename, ExceptionInfo * exception)
References AcquireExceptionInfo(), _ImageInfo::adjoin, _Image::client_data, CloneImageInfo(), CopyMagickString(), _Image::debug, DestroyExceptionInfo(), DestroyImageInfo(), _Image::filename, _ImageInfo::filename, GetFirstImageInList(), GetImageException(), GetImageListLength(), GetMagickModule, GetNextImageInList(), LogMagickEvent(), _Image::magick, _ImageInfo::magick, MagickCoreSignature, MagickFalse, MagickTrue, MaxTextExtent, _Image::scene, SetImageInfo(), SetImageProgress(), SetImageProgressMonitor(), _Image::signature, _ImageInfo::signature, TraceEvent, WriteImage(), and WriteImageTag.
Referenced by ImagesToBlob().