MagickCore: decorate.h File Reference
decorate.h File Reference
Data Structures
struct _FrameInfo
Typedefs
typedef struct _FrameInfo FrameInfo
Functions
MagickExport Image * BorderImage (const Image *, const RectangleInfo *, ExceptionInfo *)
MagickExport Image * FrameImage (const Image *, const FrameInfo *, ExceptionInfo *)
MagickExport MagickBooleanType RaiseImage (Image *, const RectangleInfo *, const MagickBooleanType)
Typedef Documentation
FrameInfo
typedef struct _FrameInfo FrameInfo
Function Documentation
BorderImage()
MagickExport Image * BorderImage (const Image * , const RectangleInfo * , ExceptionInfo *)
FrameImage()
MagickExport Image * FrameImage (const Image * image, const FrameInfo * frame_info, ExceptionInfo * exception)
References AccentuateModulate, AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, _Image::border_color, CloneImage(), CMYKColorspace, _Image::colorspace, _MagickPixelPacket::colorspace, _Image::columns, _Image::compose, CompositeImage(), ConvertRGBToCMYK(), _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, FrameImageTag, GetCacheViewAuthenticIndexQueue(), GetMagickModule, GetMagickPixelPacket(), _MagickPixelPacket::green, _FrameInfo::height, _RectangleInfo::height, HighlightModulate, InheritException(), _FrameInfo::inner_bevel, IsGrayColorspace(), IsPixelGray(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _Image::matte_color, _MagickPixelPacket::opacity, _PixelPacket::opacity, OpaqueAlphaChannel, OpaqueOpacity, OptionError, _FrameInfo::outer_bevel, _Image::page, _Image::progress_monitor, QuantumRange, QuantumScale, QueueCacheViewAuthenticPixels(), _MagickPixelPacket::red, _Image::rows, SetImageAlphaChannel(), SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacket(), SetPixelPacket(), ShadowModulate, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, TroughModulate, _FrameInfo::width, _RectangleInfo::width, _FrameInfo::x, and _FrameInfo::y.
Referenced by BorderImage(), and MontageImageList().
RaiseImage()
MagickExport MagickBooleanType RaiseImage (Image * image, const RectangleInfo * raise_info, const MagickBooleanType)
References AccentuateFactor, AcquireAuthenticCacheView(), ClampToQuantum(), _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelRed, _RectangleInfo::height, HighlightFactor, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, OptionError, _Image::progress_monitor, QuantumRange, QuantumScale, RaiseImageTag, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelRed, ShadowFactor, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowBinaryException, TraceEvent, TroughFactor, and _RectangleInfo::width.
Referenced by PreviewImage().