MagickCore: delegate.c File Reference
delegate.c File Reference
#include "magick/studio.h"
#include "magick/artifact.h"
#include "magick/attribute.h"
#include "magick/blob.h"
#include "magick/client.h"
#include "magick/configure.h"
#include "magick/constitute.h"
#include "magick/delegate.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/hashmap.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/memory_.h"
#include "magick/nt-base-private.h"
#include "magick/option.h"
#include "magick/policy.h"
#include "magick/property.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/signature.h"
#include "magick/string_.h"
#include "magick/token.h"
#include "magick/token-private.h"
#include "magick/utility.h"
#include "magick/utility-private.h"
#include "magick/xml-tree.h"
#include "magick/xml-tree-private.h"
Macros
#define DelegateFilename "delegates.xml"
#define ExtendInterpretText(string_length)
#define AppendKeyValue2Text(key, value)
#define AppendString2Text(string)
Functions
static MagickBooleanType IsDelegateCacheInstantiated (ExceptionInfo *)
static MagickBooleanType LoadDelegateCache (LinkedListInfo *, const char *, const char *, const size_t, ExceptionInfo *)
static LinkedListInfo * AcquireDelegateCache (const char *filename, ExceptionInfo *exception)
MagickExport MagickBooleanType DelegateComponentGenesis (void)
static void * DestroyDelegate (void *delegate_info)
MagickExport void DelegateComponentTerminus (void)
MagickExport int ExternalDelegateCommand (const MagickBooleanType asynchronous, const MagickBooleanType verbose, const char *command, char *message, ExceptionInfo *exception)
static char * GetMagickPropertyLetter (const ImageInfo *image_info, Image *image, const char letter)
static char * InterpretDelegateProperties (const ImageInfo *image_info, Image *image, const char *embed_text)
MagickExport char * GetDelegateCommand (const ImageInfo *image_info, Image *image, const char *decode, const char *encode, ExceptionInfo *exception)
MagickExport const char * GetDelegateCommands (const DelegateInfo *delegate_info)
MagickExport const DelegateInfo * GetDelegateInfo (const char *decode, const char *encode, ExceptionInfo *exception)
static int DelegateInfoCompare (const void *x, const void *y)
MagickExport const DelegateInfo ** GetDelegateInfoList (const char *pattern, size_t *number_delegates, ExceptionInfo *exception)
static int DelegateCompare (const void *x, const void *y)
MagickExport char ** GetDelegateList (const char *pattern, size_t *number_delegates, ExceptionInfo *exception)
MagickExport ssize_t GetDelegateMode (const DelegateInfo *delegate_info)
MagickExport MagickBooleanType GetDelegateThreadSupport (const DelegateInfo *delegate_info)
static MagickBooleanType CopyDelegateFile (const char *source, const char *destination, const MagickBooleanType overwrite)
MagickExport MagickBooleanType InvokeDelegate (ImageInfo *image_info, Image *image, const char *decode, const char *encode, ExceptionInfo *exception)
MagickExport MagickBooleanType ListDelegateInfo (FILE *file, ExceptionInfo *exception)
Variables
static const char * DelegateMap
static LinkedListInfo * delegate_cache = (LinkedListInfo *) NULL
static SemaphoreInfo * delegate_semaphore = (SemaphoreInfo *) NULL
Macro Definition Documentation
AppendKeyValue2Text
#define AppendKeyValue2Text (key, value)
Value:
{ \
  size_t length=strlen(key)+strlen(value)+2; \
  if ((size_t) (q-interpret_text+length+1) >= extent) \
    { \
      extent+=length; \
      interpret_text=(char *) ResizeQuantumMemory(interpret_text,extent+ \
        MaxTextExtent,sizeof(*interpret_text)); \
      if (interpret_text == (char *) NULL) \
        return((char *) NULL); \
      q=interpret_text+strlen(interpret_text); \
     } \
   q+=FormatLocaleString(q,extent,"%s=%s\n",(key),(value)); \
}
AppendString2Text
#define AppendString2Text (string)
Value:
{ \
  size_t length=strlen((string)); \
  if ((size_t) (q-interpret_text+length+1) >= extent) \
    { \
      extent+=length; \
      interpret_text=(char *) ResizeQuantumMemory(interpret_text,extent+ \
        MaxTextExtent,sizeof(*interpret_text)); \
      if (interpret_text == (char *) NULL) \
        return((char *) NULL); \
      q=interpret_text+strlen(interpret_text); \
    } \
  (void) CopyMagickString(q,(string),extent); \
  q+=length; \
}
DelegateFilename
#define DelegateFilename "delegates.xml"
ExtendInterpretText
#define ExtendInterpretText (string_length)
Value:
{ \
  size_t length=(string_length); \
  if ((size_t) (q-interpret_text+length+1) >= extent) \
    { \
      extent+=length; \
      interpret_text=(char *) ResizeQuantumMemory(interpret_text,extent+ \
        MaxTextExtent,sizeof(*interpret_text)); \
      if (interpret_text == (char *) NULL) \
        return((char *) NULL); \
      q=interpret_text+strlen(interpret_text); \
   } \
}
Function Documentation
AcquireDelegateCache()
static LinkedListInfo * AcquireDelegateCache (const char * filename, ExceptionInfo * exception) static
References DelegateMap, DestroyConfigureOptions(), GetConfigureOptions(), GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), IsLinkedListEmpty(), LoadDelegateCache(), MagickFalse, MagickTrue, NewLinkedList(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by IsDelegateCacheInstantiated().
CopyDelegateFile()
static MagickBooleanType CopyDelegateFile (const char * source, const char * destination, const MagickBooleanType overwrite) static
References AcquireQuantumMemory(), GetPathAttributes(), MagickFalse, MagickMaxBufferExtent, MagickMin, MagickTrue, O_BINARY, open_utf8(), RelinquishMagickMemory(), and S_MODE.
Referenced by InvokeDelegate().
DelegateCompare()
static int DelegateCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetDelegateList().
DelegateComponentGenesis()
MagickExport MagickBooleanType DelegateComponentGenesis (void)
References AllocateSemaphoreInfo(), delegate_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
DelegateComponentTerminus()
MagickExport void DelegateComponentTerminus (void)
References ActivateSemaphoreInfo(), delegate_cache, delegate_semaphore, DestroyDelegate(), DestroyLinkedList(), DestroySemaphoreInfo(), LockSemaphoreInfo(), and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
DelegateInfoCompare()
static int DelegateInfoCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetDelegateInfoList().
DestroyDelegate()
static void * DestroyDelegate (void * delegate_info) static
References _DelegateInfo::commands, _DelegateInfo::decode, DestroySemaphoreInfo(), DestroyString(), _DelegateInfo::encode, _DelegateInfo::path, RelinquishMagickMemory(), and _DelegateInfo::semaphore.
Referenced by DelegateComponentTerminus().
ExternalDelegateCommand()
MagickExport int ExternalDelegateCommand (const MagickBooleanType asynchronous, const MagickBooleanType verbose, const char * command, char * message, ExceptionInfo * exception)
References ConcatenateMagickString(), CopyMagickString(), DelegateError, DelegatePolicyDomain, DestroyString(), ExecutePolicyRights, FormatLocaleFile(), GetMagickModule, IsRightsAuthorized(), MagickFalse, MagickMin, MagickPathExtent, MaxTextExtent, PolicyError, popen_utf8(), RelinquishMagickMemory(), SanitizeString(), StringToArgv(), and ThrowMagickException().
Referenced by InvokeDelegate(), and SystemCommand().
GetDelegateCommand()
MagickExport char * GetDelegateCommand (const ImageInfo * image_info, Image * image, const char * decode, const char * encode, ExceptionInfo * exception)
References _DelegateInfo::commands, _Image::debug, DelegateError, DestroyString(), _Image::filename, GetDelegateInfo(), GetMagickModule, InterpretDelegateProperties(), LogMagickEvent(), MagickCoreSignature, MagickFalse, RelinquishMagickMemory(), ResourceLimitError, _Image::signature, _ImageInfo::signature, StringToList(), ThrowMagickException(), and TraceEvent.
GetDelegateCommands()
MagickExport const char * GetDelegateCommands (const DelegateInfo * delegate_info)
References _DelegateInfo::commands, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _DelegateInfo::signature, and TraceEvent.
GetDelegateInfo()
MagickExport const DelegateInfo * GetDelegateInfo (const char * decode, const char * encode, ExceptionInfo * exception)
References _DelegateInfo::decode, delegate_cache, delegate_semaphore, _DelegateInfo::encode, GetNextValueInLinkedList(), InsertValueInLinkedList(), IsDelegateCacheInstantiated(), LocaleCompare(), LockSemaphoreInfo(), MagickFalse, _DelegateInfo::mode, RemoveElementByValueFromLinkedList(), ResetLinkedListIterator(), and UnlockSemaphoreInfo().
Referenced by GetDelegateCommand(), GetDelegateInfoList(), GetDelegateList(), InvokeDelegate(), ReadImage(), SetImageInfo(), and WriteImage().
GetDelegateInfoList()
MagickExport const DelegateInfo ** GetDelegateInfoList (const char * pattern, size_t * number_delegates, ExceptionInfo * exception)
References AcquireQuantumMemory(), _DelegateInfo::decode, delegate_cache, delegate_semaphore, DelegateInfoCompare(), _DelegateInfo::encode, GetDelegateInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, ResetLinkedListIterator(), _DelegateInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListDelegateInfo().
GetDelegateList()
MagickExport char ** GetDelegateList (const char * pattern, size_t * number_delegates, ExceptionInfo * exception)
References AcquireQuantumMemory(), ConstantString(), _DelegateInfo::decode, delegate_cache, delegate_semaphore, DelegateCompare(), _DelegateInfo::encode, GetDelegateInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, ResetLinkedListIterator(), _DelegateInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
GetDelegateMode()
MagickExport ssize_t GetDelegateMode (const DelegateInfo * delegate_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _DelegateInfo::mode, _DelegateInfo::signature, and TraceEvent.
Referenced by WriteImage().
GetDelegateThreadSupport()
MagickExport MagickBooleanType GetDelegateThreadSupport (const DelegateInfo * delegate_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _DelegateInfo::signature, _DelegateInfo::thread_support, and TraceEvent.
Referenced by ReadImage(), and WriteImage().
GetMagickPropertyLetter()
static char * GetMagickPropertyLetter (const ImageInfo * image_info, Image * image, const char letter) static
References _ImageInfo::authenticate, BasePath, _Image::colorspace, _Image::columns, CommandOptionToMnemonic(), _Image::compression, CopyMagickString(), _Image::debug, _Image::delay, _Image::depth, _Image::dispose, _Image::exception, ExtensionPath, _Image::extent, _Image::filename, _ImageInfo::filename, FormatLocaleString(), FormatMagickSize(), GetBlobSize(), GetImageBoundingBox(), GetImageIndexInList(), GetImageListLength(), GetImageProperty(), GetMagickModule, GetPathComponent(), GRAYColorspace, HeadPath, _RectangleInfo::height, _Image::iterations, LogMagickEvent(), _Image::magick, _Image::magick_columns, _Image::magick_filename, _Image::magick_rows, MagickBooleanOptions, MagickClassOptions, MagickColorspaceOptions, MagickCompressOptions, MAGICKCORE_QUANTUM_DEPTH, MagickCoreSignature, MagickDisposeOptions, MagickEpsilon, MagickFalse, MagickResolutionOptions, _Image::matte, MaxTextExtent, _ImageInfo::number_scenes, _Image::page, _Image::quality, _Image::rows, SanitizeDelegateString(), _Image::scene, _ImageInfo::scene, SetImageGray(), _Image::signature, SignatureImage(), _Image::storage_class, TailPath, TraceEvent, _ImageInfo::unique, _Image::units, _RectangleInfo::width, _RectangleInfo::x, _Image::x_resolution, _RectangleInfo::y, _Image::y_resolution, and _ImageInfo::zero.
Referenced by InterpretDelegateProperties().
InterpretDelegateProperties()
static char * InterpretDelegateProperties (const ImageInfo * image_info, Image * image, const char * embed_text) static
References AcquireString(), AppendString2Text, ConstantString(), _Image::debug, DestroyString(), _Image::exception, ExtendInterpretText, _Image::filename, GetMagickModule, GetMagickPropertyLetter(), LocaleNCompare(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, MaxTextExtent, OptionWarning, _Image::signature, ThrowMagickException(), and TraceEvent.
Referenced by GetDelegateCommand(), and InvokeDelegate().
InvokeDelegate()
MagickExport MagickBooleanType InvokeDelegate (ImageInfo * image_info, Image * image, const char * decode, const char * encode, ExceptionInfo * exception)
References access_utf8(), AcquireUniqueFilename(), AcquireUniqueSymbolicLink(), _ImageInfo::adjoin, CloneImageInfo(), _DelegateInfo::commands, CopyDelegateFile(), CopyMagickString(), _Image::debug, _DelegateInfo::decode, DelegateError, DelegatePolicyDomain, DestroyImageInfo(), DestroyString(), _DelegateInfo::encode, ExecutePolicyRights, ExternalDelegateCommand(), _Image::filename, _ImageInfo::filename, FileOpenError, FormatLocaleString(), GetDelegateInfo(), GetImageListLength(), GetMagickModule, GetNextImageInList(), InterpretDelegateProperties(), IsRightsAuthorized(), LocaleCompare(), LocaleUpper(), LogMagickEvent(), _Image::magick, _ImageInfo::magick, MagickCoreSignature, MagickDelay(), MagickFalse, MagickTrue, MaxTextExtent, _DelegateInfo::mode, PolicyError, RelinquishMagickMemory(), RelinquishUniqueFileResource(), ResourceLimitError, SetImageInfo(), _Image::signature, _ImageInfo::signature, _DelegateInfo::spawn, StringToList(), _ImageInfo::temporary, ThrowFileException, ThrowMagickException(), TraceEvent, _ImageInfo::unique, _ImageInfo::verbose, WriteImage(), and _ImageInfo::zero.
Referenced by ReadImage(), and WriteImage().
IsDelegateCacheInstantiated()
static MagickBooleanType IsDelegateCacheInstantiated (ExceptionInfo * exception) static
References AcquireDelegateCache(), ActivateSemaphoreInfo(), delegate_cache, delegate_semaphore, DelegateFilename, LockSemaphoreInfo(), MagickFalse, MagickTrue, and UnlockSemaphoreInfo().
Referenced by GetDelegateInfo().
ListDelegateInfo()
MagickExport MagickBooleanType ListDelegateInfo (FILE * file, ExceptionInfo * exception)
References ConcatenateMagickString(), CopyMagickString(), DestroyString(), FormatLocaleFile(), GetDelegateInfoList(), LocaleCompare(), MagickFalse, MagickTrue, MaxTextExtent, _DelegateInfo::path, RelinquishMagickMemory(), StringToList(), and StripString().
LoadDelegateCache()
static MagickBooleanType LoadDelegateCache (LinkedListInfo * cache, const char * xml, const char * filename, const size_t depth, ExceptionInfo * exception)
References AcquireQuantumMemory(), AcquireString(), AllocateSemaphoreInfo(), AppendValueToLinkedList(), _DelegateInfo::commands, ConcatenateMagickString(), ConfigureError, ConfigureEvent, ConstantString(), CopyMagickString(), _DelegateInfo::decode, DirectorySeparator, _DelegateInfo::encode, FileToXML(), GetMagickModule, GetNextToken(), GetPathComponent(), HeadPath, IsMagickTrue(), LoadDelegateCache(), LocaleCompare(), LocaleNCompare(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickMaxRecursionDepth, MagickTrue, MaxTextExtent, _DelegateInfo::mode, _DelegateInfo::path, RelinquishMagickMemory(), ResourceLimitError, ResourceLimitFatalError, _DelegateInfo::semaphore, _DelegateInfo::signature, _DelegateInfo::spawn, _DelegateInfo::stealth, SubstituteString(), _DelegateInfo::thread_support, ThrowFatalException, and ThrowMagickException().
Referenced by AcquireDelegateCache(), and LoadDelegateCache().
Variable Documentation
delegate_cache
LinkedListInfo* delegate_cache = (LinkedListInfo *) NULL static
Referenced by DelegateComponentTerminus(), GetDelegateInfo(), GetDelegateInfoList(), GetDelegateList(), and IsDelegateCacheInstantiated().
delegate_semaphore
SemaphoreInfo* delegate_semaphore = (SemaphoreInfo *) NULL static
Referenced by DelegateComponentGenesis(), DelegateComponentTerminus(), GetDelegateInfo(), GetDelegateInfoList(), GetDelegateList(), and IsDelegateCacheInstantiated().
DelegateMap
const char* DelegateMap static
Referenced by AcquireDelegateCache().