MagickCore: delegate.h File Reference
delegate.h File Reference
#include <stdarg.h>
#include "magick/semaphore.h"
Data Structures
struct _DelegateInfo
Typedefs
typedef struct _DelegateInfo DelegateInfo
Functions
MagickExport char * GetDelegateCommand (const ImageInfo *, Image *, const char *, const char *, ExceptionInfo *)
MagickExport char ** GetDelegateList (const char *, size_t *, ExceptionInfo *)
MagickExport const char * GetDelegateCommands (const DelegateInfo *)
MagickExport const DelegateInfo * GetDelegateInfo (const char *, const char *, ExceptionInfo *exception)
MagickExport const DelegateInfo ** GetDelegateInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport int ExternalDelegateCommand (const MagickBooleanType, const MagickBooleanType, const char *, char *, ExceptionInfo *)
MagickExport ssize_t GetDelegateMode (const DelegateInfo *)
MagickExport MagickBooleanType DelegateComponentGenesis (void)
MagickExport MagickBooleanType GetDelegateThreadSupport (const DelegateInfo *)
MagickExport MagickBooleanType InvokeDelegate (ImageInfo *, Image *, const char *, const char *, ExceptionInfo *)
MagickExport MagickBooleanType ListDelegateInfo (FILE *, ExceptionInfo *)
MagickExport void DelegateComponentTerminus (void)
Typedef Documentation
DelegateInfo
typedef struct _DelegateInfo DelegateInfo
Function Documentation
DelegateComponentGenesis()
MagickExport MagickBooleanType DelegateComponentGenesis (void)
DelegateComponentTerminus()
MagickExport void DelegateComponentTerminus (void)
References ActivateSemaphoreInfo(), delegate_cache, delegate_semaphore, DestroyDelegate(), DestroyLinkedList(), DestroySemaphoreInfo(), LockSemaphoreInfo(), and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
ExternalDelegateCommand()
MagickExport int ExternalDelegateCommand (const MagickBooleanType, const MagickBooleanType, const char * command, char * message, ExceptionInfo * exception)
References ConcatenateMagickString(), CopyMagickString(), DelegateError, DelegatePolicyDomain, DestroyString(), ExecutePolicyRights, FormatLocaleFile(), GetMagickModule, IsRightsAuthorized(), MagickFalse, MagickMin, MagickPathExtent, MaxTextExtent, PolicyError, popen_utf8(), RelinquishMagickMemory(), SanitizeString(), StringToArgv(), and ThrowMagickException().
Referenced by InvokeDelegate(), and SystemCommand().
GetDelegateCommand()
MagickExport char * GetDelegateCommand (const ImageInfo * , Image * , const char * , const char * , ExceptionInfo *)
GetDelegateCommands()
MagickExport const char * GetDelegateCommands (const DelegateInfo * delegate_info)
References _DelegateInfo::commands, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _DelegateInfo::signature, and TraceEvent.
GetDelegateInfo()
MagickExport const DelegateInfo * GetDelegateInfo (const char * , const char * , ExceptionInfo * exception)
GetDelegateInfoList()
MagickExport const DelegateInfo ** GetDelegateInfoList (const char * pattern, size_t * number_delegates, ExceptionInfo * exception)
References AcquireQuantumMemory(), _DelegateInfo::decode, delegate_cache, delegate_semaphore, DelegateInfoCompare(), _DelegateInfo::encode, GetDelegateInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, ResetLinkedListIterator(), _DelegateInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListDelegateInfo().
GetDelegateList()
MagickExport char ** GetDelegateList (const char * pattern, size_t * number_delegates, ExceptionInfo * exception)
References AcquireQuantumMemory(), ConstantString(), _DelegateInfo::decode, delegate_cache, delegate_semaphore, DelegateCompare(), _DelegateInfo::encode, GetDelegateInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, ResetLinkedListIterator(), _DelegateInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
GetDelegateMode()
MagickExport ssize_t GetDelegateMode (const DelegateInfo * delegate_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _DelegateInfo::mode, _DelegateInfo::signature, and TraceEvent.
Referenced by WriteImage().
GetDelegateThreadSupport()
MagickExport MagickBooleanType GetDelegateThreadSupport (const DelegateInfo *)
InvokeDelegate()
MagickExport MagickBooleanType InvokeDelegate (ImageInfo * , Image * , const char * , const char * , ExceptionInfo *)
ListDelegateInfo()
MagickExport MagickBooleanType ListDelegateInfo (FILE * file, ExceptionInfo * exception)
References ConcatenateMagickString(), CopyMagickString(), DestroyString(), FormatLocaleFile(), GetDelegateInfoList(), LocaleCompare(), MagickFalse, MagickTrue, MaxTextExtent, _DelegateInfo::path, RelinquishMagickMemory(), StringToList(), and StripString().