MagickCore: deprecate.h File Reference
deprecate.h File Reference
#include <stdarg.h>
#include "magick/blob.h"
#include "magick/cache-view.h"
#include "magick/draw.h"
#include "magick/constitute.h"
#include "magick/magick-config.h"
#include "magick/pixel.h"
#include "magick/quantize.h"
#include "magick/quantum.h"
#include "magick/registry.h"
#include "magick/semaphore.h"
Data Structures
struct _ImageAttribute
Macros
#define magick_attribute(x) /*nothing*/
#define Downscale(quantum) ScaleQuantumToChar(quantum)
#define LABColorspace LabColorspace
#define CompressPixelGamma(pixel) DecodePixelGamma(pixel)
#define DecodesRGBGamma(pixel) DecodePixelGamma(pixel)
#define EncodesRGBGamma(pixel) EncodePixelGamma(pixel)
#define ExpandPixelGamma(pixel) EncodePixelGamma(pixel)
#define Intensity(color) PixelIntensityToQuantum(color)
#define LiberateUniqueFileResource(resource) RelinquishUniqueFileResource(resource)
#define LiberateMagickResource(resource) RelinquishMagickResource(resource)
#define LiberateSemaphore(semaphore) RelinquishSemaphore(semaphore)
#define MagickHuge 3.4e+38F
#define MaxRGB QuantumRange /* deprecated */
#define QuantumDepth MAGICKCORE_QUANTUM_DEPTH
#define RunlengthEncodedCompression RLECompression
#define Upscale(value) ScaleCharToQuantum(value)
#define XDownscale(value) ScaleShortToQuantum(value)
#define XUpscale(quantum) ScaleQuantumToShort(quantum)
Typedefs
typedef MagickOffsetType ExtendedSignedIntegralType
typedef MagickSizeType ExtendedUnsignedIntegralType
typedef MagickRealType ExtendedRationalType
typedef struct _ViewInfo ViewInfo
typedef MagickBooleanType(* MonitorHandler) (const char *, const MagickOffsetType, const MagickSizeType, ExceptionInfo *)
typedef struct _ImageAttribute ImageAttribute
Enumerations
enum MagickLayerMethod { UndefinedMagickLayerMethod }
Functions
MagickExport CacheView * CloseCacheView (CacheView *) magick_attribute((deprecated))
MagickExport CacheView * OpenCacheView (const Image *) magick_attribute((deprecated))
MagickExport char * AllocateString (const char *) magick_attribute((deprecated))
MagickExport char * InterpretImageAttributes (const ImageInfo *, Image *, const char *) magick_attribute((deprecated))
MagickExport char * PostscriptGeometry (const char *) magick_attribute((deprecated))
MagickExport char * TranslateText (const ImageInfo *, Image *, const char *) magick_attribute((deprecated))
MagickExport const ImageAttribute * GetImageAttribute (const Image *, const char *)
MagickExport const ImageAttribute * GetImageClippingPathAttribute (Image *) magick_attribute((deprecated))
MagickExport const ImageAttribute * GetNextImageAttribute (const Image *) magick_attribute((deprecated))
MagickExport const IndexPacket * AcquireCacheViewIndexes (const CacheView *) magick_attribute((deprecated))
MagickExport const IndexPacket * AcquireIndexes (const Image *) magick_attribute((deprecated))
MagickExport const PixelPacket * AcquirePixels (const Image *) magick_attribute((deprecated))
MagickExport const PixelPacket * AcquireCacheViewPixels (const CacheView *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *) magick_attribute((deprecated))
MagickExport const PixelPacket * AcquireImagePixels (const Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *) magick_attribute((deprecated))
MagickExport FILE * OpenMagickStream (const char *, const char *)
MagickExport Image * AllocateImage (const ImageInfo *) magick_attribute((deprecated))
MagickExport Image * AverageImages (const Image *, ExceptionInfo *)
MagickExport Image * ExtractSubimageFromImage (Image *, const Image *, ExceptionInfo *) magick_attribute((deprecated))
MagickExport Image * GetImageFromMagickRegistry (const char *, ssize_t *id, ExceptionInfo *) magick_attribute((deprecated))
MagickExport Image * GetImageList (const Image *, const ssize_t, ExceptionInfo *) magick_attribute((deprecated))
MagickExport Image * GetNextImage (const Image *) magick_attribute((deprecated))
MagickExport Image * GetPreviousImage (const Image *) magick_attribute((deprecated))
MagickExport Image * FlattenImages (Image *, ExceptionInfo *) magick_attribute((deprecated))
MagickExport Image * MaximumImages (const Image *, ExceptionInfo *)
MagickExport Image * MedianFilterImage (const Image *, const double, ExceptionInfo *)
MagickExport Image * ModeImage (const Image *, const double, ExceptionInfo *)
MagickExport Image * MinimumImages (const Image *, ExceptionInfo *)
MagickExport Image * MosaicImages (Image *, ExceptionInfo *) magick_attribute((deprecated))
MagickExport Image * PopImageList (Image **) magick_attribute((deprecated))
MagickExport Image * RadialBlurImage (const Image *, const double, ExceptionInfo *) magick_attribute((deprecated))
MagickExport Image * RadialBlurImageChannel (const Image *, const ChannelType, const double, ExceptionInfo *) magick_attribute((deprecated))
MagickExport Image * RecolorImage (const Image *, const size_t, const double *, ExceptionInfo *) magick_attribute((deprecated))
MagickExport Image * ReduceNoiseImage (const Image *, const double, ExceptionInfo *)
MagickExport Image * ShiftImageList (Image **) magick_attribute((deprecated))
MagickExport Image * SpliceImageList (Image *, const ssize_t, const size_t, const Image *, ExceptionInfo *) magick_attribute((deprecated))
MagickExport Image * ZoomImage (const Image *, const size_t, const size_t, ExceptionInfo *) magick_attribute((deprecated))
MagickExport IndexPacket * GetCacheViewIndexes (CacheView *) magick_attribute((deprecated))
MagickExport IndexPacket * GetIndexes (const Image *) magick_attribute((deprecated))
MagickExport IndexPacket ValidateColormapIndex (Image *, const size_t) magick_attribute((deprecated))
MagickExport int GetImageGeometry (Image *, const char *, const unsigned int, RectangleInfo *) magick_attribute((deprecated))
MagickExport int ParseImageGeometry (const char *, ssize_t *, ssize_t *, size_t *, size_t *) magick_attribute((deprecated))
MagickExport int SystemCommand (const MagickBooleanType, const MagickBooleanType, const char *, ExceptionInfo *) magick_attribute((deprecated))
MagickExport MagickBooleanType AcquireOneCacheViewPixel (const CacheView *, const ssize_t, const ssize_t, PixelPacket *, ExceptionInfo *) magick_attribute((deprecated))
MagickExport MagickBooleanType AcquireOneCacheViewVirtualPixel (const CacheView *, const VirtualPixelMethod, const ssize_t, const ssize_t, PixelPacket *, ExceptionInfo *) magick_attribute((deprecated))
MagickExport MagickBooleanType AffinityImage (const QuantizeInfo *, Image *, const Image *) magick_attribute((deprecated))
MagickExport MagickBooleanType AffinityImages (const QuantizeInfo *, Image *, const Image *) magick_attribute((deprecated))
MagickExport MagickBooleanType AllocateImageColormap (Image *, const size_t) magick_attribute((deprecated))
MagickExport MagickBooleanType ClipPathImage (Image *, const char *, const MagickBooleanType) magick_attribute((deprecated))
MagickExport MagickBooleanType CloneImageAttributes (Image *, const Image *) magick_attribute((deprecated))
MagickExport MagickBooleanType ColorFloodfillImage (Image *, const DrawInfo *, const PixelPacket, const ssize_t, const ssize_t, const PaintMethod) magick_attribute((deprecated))
MagickExport MagickBooleanType ConstituteComponentGenesis (void) magick_attribute((deprecated))
MagickExport MagickBooleanType DeleteImageAttribute (Image *, const char *) magick_attribute((deprecated))
MagickExport MagickBooleanType DeleteMagickRegistry (const ssize_t) magick_attribute((deprecated))
MagickExport MagickBooleanType DescribeImage (Image *, FILE *, const MagickBooleanType) magick_attribute((deprecated))
MagickExport MagickBooleanType FormatImageAttribute (Image *, const char *, const char *,...) magick_attribute((__format__(__printf__
MagickExport MagickBooleanType magick_attribute ((deprecated))
MagickExport MagickBooleanType FormatImageAttributeList (Image *, const char *, const char *, va_list) magick_attribute((__format__(__printf__
MagickExport MagickBooleanType FormatImagePropertyList (Image *, const char *, const char *, va_list) magick_attribute((__format__(__printf__
MagickExport MagickBooleanType FuzzyColorCompare (const Image *, const PixelPacket *, const PixelPacket *) magick_attribute((deprecated))
MagickExport MagickBooleanType FuzzyOpacityCompare (const Image *, const PixelPacket *, const PixelPacket *) magick_attribute((deprecated))
MagickExport MagickBooleanType InitializeModuleList (ExceptionInfo *) magick_attribute((deprecated))
MagickExport MagickBooleanType IsMagickInstantiated (void) magick_attribute((deprecated))
MagickExport MagickBooleanType LevelImageColors (Image *, const ChannelType, const MagickPixelPacket *, const MagickPixelPacket *, const MagickBooleanType) magick_attribute((deprecated))
MagickExport MagickBooleanType LoadMimeLists (const char *, ExceptionInfo *) magick_attribute((deprecated))
MagickExport MagickBooleanType MagickMonitor (const char *, const MagickOffsetType, const MagickSizeType, void *) magick_attribute((deprecated))
MagickExport MagickBooleanType MapImage (Image *, const Image *, const MagickBooleanType) magick_attribute((deprecated))
MagickExport MagickBooleanType MapImages (Image *, const Image *, const MagickBooleanType) magick_attribute((deprecated))
MagickExport MagickBooleanType MatteFloodfillImage (Image *, const PixelPacket, const Quantum, const ssize_t, const ssize_t, const PaintMethod) magick_attribute((deprecated))
MagickExport MagickBooleanType OpaqueImage (Image *, const PixelPacket, const PixelPacket) magick_attribute((deprecated))
MagickExport MagickBooleanType PaintFloodfillImage (Image *, const ChannelType, const MagickPixelPacket *, const ssize_t, const ssize_t, const DrawInfo *, const PaintMethod) magick_attribute((deprecated))
MagickExport MagickBooleanType PaintOpaqueImage (Image *, const MagickPixelPacket *, const MagickPixelPacket *) magick_attribute((deprecated))
MagickExport MagickBooleanType PaintOpaqueImageChannel (Image *, const ChannelType, const MagickPixelPacket *, const MagickPixelPacket *) magick_attribute((deprecated))
MagickExport MagickBooleanType PaintTransparentImage (Image *, const MagickPixelPacket *, const Quantum) magick_attribute((deprecated))
MagickExport MagickBooleanType SetExceptionInfo (ExceptionInfo *, ExceptionType) magick_attribute((deprecated))
MagickExport MagickBooleanType SetImageAttribute (Image *, const char *, const char *) magick_attribute((deprecated))
MagickExport MagickBooleanType SyncCacheViewPixels (CacheView *) magick_attribute((deprecated))
MagickExport MagickBooleanType SyncImagePixels (Image *) magick_attribute((deprecated))
MagickExport MagickBooleanType TransparentImage (Image *, const PixelPacket, const Quantum) magick_attribute((deprecated))
MagickExport MagickPixelPacket AcquireOneMagickPixel (const Image *, const ssize_t, const ssize_t, ExceptionInfo *) magick_attribute((deprecated))
MagickExport MonitorHandler GetMonitorHandler (void) magick_attribute((deprecated))
MagickExport MonitorHandler SetMonitorHandler (MonitorHandler) magick_attribute((deprecated))
MagickExport MagickOffsetType SizeBlob (Image *image) magick_attribute((deprecated))
MagickExport MagickPixelPacket InterpolatePixelColor (const Image *, CacheView *, const InterpolatePixelMethod, const double, const double, ExceptionInfo *) magick_attribute((deprecated))
MagickExport MagickStatusType ParseSizeGeometry (const Image *, const char *, RectangleInfo *) magick_attribute((deprecated))
MagickExport PixelPacket AcquireOnePixel (const Image *, const ssize_t, const ssize_t, ExceptionInfo *) magick_attribute((deprecated))
MagickExport PixelPacket AcquireOneVirtualPixel (const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, ExceptionInfo *) magick_attribute((deprecated))
MagickExport PixelPacket * GetCacheView (CacheView *, const ssize_t, const ssize_t, const size_t, const size_t) magick_attribute((deprecated))
MagickExport PixelPacket * GetCacheViewPixels (CacheView *, const ssize_t, const ssize_t, const size_t, const size_t) magick_attribute((deprecated))
MagickExport PixelPacket * GetImagePixels (Image *, const ssize_t, const ssize_t, const size_t, const size_t) magick_attribute((deprecated))
MagickExport PixelPacket GetOnePixel (Image *, const ssize_t, const ssize_t) magick_attribute((deprecated))
MagickExport PixelPacket * GetPixels (const Image *) magick_attribute((deprecated))
MagickExport PixelPacket * SetCacheViewPixels (CacheView *, const ssize_t, const ssize_t, const size_t, const size_t) magick_attribute((deprecated))
MagickExport PixelPacket * SetImagePixels (Image *, const ssize_t, const ssize_t, const size_t, const size_t) magick_attribute((deprecated))
MagickExport MagickRealType InversesRGBCompandor (const MagickRealType) magick_attribute((deprecated))
MagickExport MagickRealType sRGBCompandor (const MagickRealType) magick_attribute((deprecated))
MagickExport size_t GetImageListSize (const Image *) magick_attribute((deprecated))
MagickExport size_t PopImagePixels (Image *, const QuantumType, unsigned char *) magick_attribute((deprecated))
MagickExport size_t PushImagePixels (Image *, const QuantumType, const unsigned char *) magick_attribute((deprecated))
MagickExport ssize_t FormatMagickString (char *, const size_t, const char *,...) magick_attribute((__format__(__printf__
MagickExport ssize_t FormatMagickStringList (char *, const size_t, const char *, va_list) magick_attribute((__format__(__printf__
MagickExport ssize_t GetImageListIndex (const Image *) magick_attribute((deprecated))
MagickExport ssize_t SetMagickRegistry (const RegistryType, const void *, const size_t, ExceptionInfo *) magick_attribute((deprecated))
MagickExport unsigned int ChannelImage (Image *, const ChannelType) magick_attribute((deprecated))
MagickExport unsigned int ChannelThresholdImage (Image *, const char *) magick_attribute((deprecated))
MagickExport unsigned int DispatchImage (const Image *, const ssize_t, const ssize_t, const size_t, const size_t, const char *, const StorageType, void *, ExceptionInfo *) magick_attribute((deprecated))
MagickExport unsigned int FuzzyColorMatch (const PixelPacket *, const PixelPacket *, const double) magick_attribute((deprecated))
MagickExport unsigned int GetNumberScenes (const Image *) magick_attribute((deprecated))
MagickExport unsigned int GetMagickGeometry (const char *, ssize_t *, ssize_t *, size_t *, size_t *) magick_attribute((deprecated))
MagickExport unsigned int IsSubimage (const char *, const unsigned int) magick_attribute((deprecated))
MagickExport unsigned int PushImageList (Image **, const Image *, ExceptionInfo *) magick_attribute((deprecated))
MagickExport unsigned int QuantizationError (Image *) magick_attribute((deprecated))
MagickExport unsigned int RandomChannelThresholdImage (Image *, const char *, const char *, ExceptionInfo *) magick_attribute((deprecated))
MagickExport unsigned int SetImageList (Image **, const Image *, const ssize_t, ExceptionInfo *) magick_attribute((deprecated))
MagickExport unsigned int TransformColorspace (Image *, const ColorspaceType) magick_attribute((deprecated))
MagickExport unsigned int ThresholdImage (Image *, const double) magick_attribute((deprecated))
MagickExport unsigned int ThresholdImageChannel (Image *, const char *) magick_attribute((deprecated))
MagickExport unsigned int UnshiftImageList (Image **, const Image *, ExceptionInfo *) magick_attribute((deprecated))
MagickExport void * AcquireMemory (const size_t) magick_attribute((deprecated))
MagickExport void AcquireSemaphoreInfo (SemaphoreInfo **) magick_attribute((deprecated))
MagickExport void AllocateNextImage (const ImageInfo *, Image *) magick_attribute((deprecated))
MagickExport void * CloneMemory (void *, const void *, const size_t) magick_attribute((deprecated))
MagickExport void ConstituteComponentTerminus (void) magick_attribute((deprecated))
MagickExport void DestroyConstitute (void)
MagickExport void DestroyImageAttributes (Image *) magick_attribute((deprecated))
MagickExport void DestroyImages (Image *) magick_attribute((deprecated))
MagickExport void DestroyMagick (void) magick_attribute((deprecated))
MagickExport void DestroyMagickRegistry (void) magick_attribute((deprecated))
MagickExport void * GetConfigureBlob (const char *, char *, size_t *, ExceptionInfo *) magick_attribute((deprecated))
MagickExport void GetExceptionInfo (ExceptionInfo *)
MagickExport void * GetMagickRegistry (const ssize_t, RegistryType *, size_t *, ExceptionInfo *) magick_attribute((deprecated))
MagickExport void GetTokenToken (const char *, const char **, char *)
MagickExport void IdentityAffine (AffineMatrix *) magick_attribute((deprecated))
MagickExport void LiberateMemory (void **) magick_attribute((deprecated))
MagickExport void LiberateSemaphoreInfo (SemaphoreInfo **) magick_attribute((deprecated))
MagickExport void FormatString (char *, const char *,...) magick_attribute((__format__(__printf__
MagickExport void FormatStringList (char *, const char *, va_list) magick_attribute((__format__(__printf__
MagickExport void HSLTransform (const double, const double, const double, Quantum *, Quantum *, Quantum *) magick_attribute((deprecated))
MagickExport void InitializeMagick (const char *) magick_attribute((deprecated))
MagickExport void MagickIncarnate (const char *) magick_attribute((deprecated))
MagickExport void ReacquireMemory (void **, const size_t) magick_attribute((deprecated))
MagickExport void RelinquishSemaphoreInfo (SemaphoreInfo *) magick_attribute((deprecated))
MagickExport void ResetImageAttributeIterator (const Image *) magick_attribute((deprecated))
MagickExport void SetCacheThreshold (const size_t) magick_attribute((deprecated))
MagickExport void SetImage (Image *, const Quantum) magick_attribute((deprecated))
MagickExport void Strip (char *) magick_attribute((deprecated))
MagickExport void TemporaryFilename (char *) magick_attribute((deprecated))
MagickExport void TransformHSL (const Quantum, const Quantum, const Quantum, double *, double *, double *) magick_attribute((deprecated))
static double MagickEpsilonReciprocal (const double x)
static Quantum PixelIntensityToQuantum (const Image *magick_restrict image, const PixelPacket *magick_restrict pixel)
Macro Definition Documentation
CompressPixelGamma
#define CompressPixelGamma (pixel) DecodePixelGamma(pixel)
DecodesRGBGamma
#define DecodesRGBGamma (pixel) DecodePixelGamma(pixel)
Downscale
#define Downscale (quantum) ScaleQuantumToChar(quantum)
EncodesRGBGamma
#define EncodesRGBGamma (pixel) EncodePixelGamma(pixel)
ExpandPixelGamma
#define ExpandPixelGamma (pixel) EncodePixelGamma(pixel)
Intensity
#define Intensity (color) PixelIntensityToQuantum(color)
LABColorspace
#define LABColorspace LabColorspace
LiberateMagickResource
#define LiberateMagickResource (resource) RelinquishMagickResource(resource)
LiberateSemaphore
#define LiberateSemaphore (semaphore) RelinquishSemaphore(semaphore)
LiberateUniqueFileResource
#define LiberateUniqueFileResource (resource) RelinquishUniqueFileResource(resource)
magick_attribute
#define magick_attribute (x) /*nothing*/
MagickHuge
#define MagickHuge 3.4e+38F
MaxRGB
#define MaxRGB QuantumRange /* deprecated */
QuantumDepth
#define QuantumDepth MAGICKCORE_QUANTUM_DEPTH
RunlengthEncodedCompression
#define RunlengthEncodedCompression RLECompression
Upscale
#define Upscale (value) ScaleCharToQuantum(value)
XDownscale
#define XDownscale (value) ScaleShortToQuantum(value)
XUpscale
#define XUpscale (quantum) ScaleQuantumToShort(quantum)
Typedef Documentation
ExtendedRationalType
typedef MagickRealType ExtendedRationalType
ExtendedSignedIntegralType
typedef MagickOffsetType ExtendedSignedIntegralType
ExtendedUnsignedIntegralType
typedef MagickSizeType ExtendedUnsignedIntegralType
ImageAttribute
typedef struct _ImageAttribute ImageAttribute
MonitorHandler
typedef MagickBooleanType(* MonitorHandler) (const char *, const MagickOffsetType, const MagickSizeType, ExceptionInfo *)
ViewInfo
typedef struct _ViewInfo ViewInfo
Enumeration Type Documentation
MagickLayerMethod
enum MagickLayerMethod
Enumerator
UndefinedMagickLayerMethod
Function Documentation
AcquireCacheViewIndexes()
MagickExport const IndexPacket * AcquireCacheViewIndexes (const CacheView *)
AcquireCacheViewPixels()
MagickExport const PixelPacket * AcquireCacheViewPixels (const CacheView * , const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
AcquireImagePixels()
MagickExport const PixelPacket * AcquireImagePixels (const Image * image, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo * exception)
References GetVirtualPixels().
AcquireIndexes()
MagickExport const IndexPacket * AcquireIndexes (const Image * image)
References GetVirtualIndexQueue().
AcquireMemory()
MagickExport void * AcquireMemory (const size_t)
AcquireOneCacheViewPixel()
MagickExport MagickBooleanType AcquireOneCacheViewPixel (const CacheView * , const ssize_t, const ssize_t, PixelPacket * , ExceptionInfo *)
AcquireOneCacheViewVirtualPixel()
MagickExport MagickBooleanType AcquireOneCacheViewVirtualPixel (const CacheView * , const VirtualPixelMethod, const ssize_t, const ssize_t, PixelPacket * , ExceptionInfo *)
AcquireOneMagickPixel()
MagickExport MagickPixelPacket AcquireOneMagickPixel (const Image * image, const ssize_t, const ssize_t, ExceptionInfo * exception)
References GetOneVirtualMagickPixel().
AcquireOnePixel()
MagickExport PixelPacket AcquireOnePixel (const Image * , const ssize_t, const ssize_t, ExceptionInfo *)
AcquireOneVirtualPixel()
MagickExport PixelPacket AcquireOneVirtualPixel (const Image * , const VirtualPixelMethod, const ssize_t, const ssize_t, ExceptionInfo *)
AcquirePixels()
MagickExport const PixelPacket * AcquirePixels (const Image *)
AcquireSemaphoreInfo()
MagickExport void AcquireSemaphoreInfo (SemaphoreInfo **)
AffinityImage()
MagickExport MagickBooleanType AffinityImage (const QuantizeInfo * , Image * , const Image *)
AffinityImages()
MagickExport MagickBooleanType AffinityImages (const QuantizeInfo * , Image * , const Image *)
AllocateImage()
MagickExport Image * AllocateImage (const ImageInfo *)
AllocateImageColormap()
MagickExport MagickBooleanType AllocateImageColormap (Image * , const size_t)
AllocateNextImage()
MagickExport void AllocateNextImage (const ImageInfo * , Image *)
AllocateString()
MagickExport char * AllocateString (const char *)
AverageImages()
MagickExport Image * AverageImages (const Image * , ExceptionInfo *)
ChannelImage()
MagickExport unsigned int ChannelImage (Image * , const ChannelType)
ChannelThresholdImage()
MagickExport unsigned int ChannelThresholdImage (Image * , const char *)
ClipPathImage()
MagickExport MagickBooleanType ClipPathImage (Image * , const char * , const MagickBooleanType)
CloneImageAttributes()
MagickExport MagickBooleanType CloneImageAttributes (Image * , const Image *)
CloneMemory()
MagickExport void * CloneMemory (void * , const void * , const size_t)
CloseCacheView()
MagickExport CacheView * CloseCacheView (CacheView *)
ColorFloodfillImage()
MagickExport MagickBooleanType ColorFloodfillImage (Image * , const DrawInfo * , const PixelPacket, const ssize_t, const ssize_t, const PaintMethod)
ConstituteComponentGenesis()
MagickExport MagickBooleanType ConstituteComponentGenesis (void)
ConstituteComponentTerminus()
MagickExport void ConstituteComponentTerminus (void)
DeleteImageAttribute()
MagickExport MagickBooleanType DeleteImageAttribute (Image * , const char *)
DeleteMagickRegistry()
MagickExport MagickBooleanType DeleteMagickRegistry (const ssize_t)
DescribeImage()
MagickExport MagickBooleanType DescribeImage (Image * , FILE * , const MagickBooleanType)
DestroyConstitute()
MagickExport void DestroyConstitute (void)
DestroyImageAttributes()
MagickExport void DestroyImageAttributes (Image *)
DestroyImages()
MagickExport void DestroyImages (Image *)
DestroyMagick()
MagickExport void DestroyMagick (void)
DestroyMagickRegistry()
MagickExport void DestroyMagickRegistry (void)
DispatchImage()
MagickExport unsigned int DispatchImage (const Image * , const ssize_t, const ssize_t, const size_t, const size_t, const char * , const StorageType, void * , ExceptionInfo *)
ExtractSubimageFromImage()
MagickExport Image * ExtractSubimageFromImage (Image * , const Image * , ExceptionInfo *)
FlattenImages()
MagickExport Image * FlattenImages (Image * , ExceptionInfo *)
FormatImageAttribute()
MagickExport MagickBooleanType FormatImageAttribute (Image * , const char * , const char * , ...)
FormatImageAttributeList()
MagickExport MagickBooleanType FormatImageAttributeList (Image * , const char * , const char * , va_list)
FormatImagePropertyList()
MagickExport MagickBooleanType FormatImagePropertyList (Image * , const char * , const char * , va_list)
FormatMagickString()
MagickExport ssize_t FormatMagickString (char * , const size_t, const char * , ...)
FormatMagickStringList()
MagickExport ssize_t FormatMagickStringList (char * , const size_t, const char * , va_list)
FormatString()
MagickExport void FormatString (char * , const char * , ...)
FormatStringList()
MagickExport void FormatStringList (char * , const char * , va_list)
FuzzyColorCompare()
MagickExport MagickBooleanType FuzzyColorCompare (const Image * , const PixelPacket * , const PixelPacket *)
FuzzyColorMatch()
MagickExport unsigned int FuzzyColorMatch (const PixelPacket * , const PixelPacket * , const double)
FuzzyOpacityCompare()
MagickExport MagickBooleanType FuzzyOpacityCompare (const Image * , const PixelPacket * , const PixelPacket *)
GetCacheView()
MagickExport PixelPacket * GetCacheView (CacheView * , const ssize_t, const ssize_t, const size_t, const size_t)
GetCacheViewIndexes()
MagickExport IndexPacket * GetCacheViewIndexes (CacheView *)
GetCacheViewPixels()
MagickExport PixelPacket * GetCacheViewPixels (CacheView * , const ssize_t, const ssize_t, const size_t, const size_t)
GetConfigureBlob()
MagickExport void * GetConfigureBlob (const char * , char * , size_t * , ExceptionInfo *)
GetExceptionInfo()
MagickExport void GetExceptionInfo (ExceptionInfo *)
GetImageAttribute()
MagickExport const ImageAttribute * GetImageAttribute (const Image * , const char *)
GetImageClippingPathAttribute()
MagickExport const ImageAttribute * GetImageClippingPathAttribute (Image *)
GetImageFromMagickRegistry()
MagickExport Image * GetImageFromMagickRegistry (const char * , ssize_t * id, ExceptionInfo *)
GetImageGeometry()
MagickExport int GetImageGeometry (Image * , const char * , const unsigned int , RectangleInfo *)
GetImageList()
MagickExport Image * GetImageList (const Image * , const ssize_t, ExceptionInfo *)
GetImageListIndex()
MagickExport ssize_t GetImageListIndex (const Image *)
GetImageListSize()
MagickExport size_t GetImageListSize (const Image *)
GetImagePixels()
MagickExport PixelPacket * GetImagePixels (Image * , const ssize_t, const ssize_t, const size_t, const size_t)
GetIndexes()
MagickExport IndexPacket * GetIndexes (const Image *)
GetMagickGeometry()
MagickExport unsigned int GetMagickGeometry (const char * , ssize_t * , ssize_t * , size_t * , size_t *)
GetMagickRegistry()
MagickExport void * GetMagickRegistry (const ssize_t, RegistryType * , size_t * , ExceptionInfo *)
GetMonitorHandler()
MagickExport MonitorHandler GetMonitorHandler (void)
GetNextImage()
MagickExport Image * GetNextImage (const Image *)
GetNextImageAttribute()
MagickExport const ImageAttribute * GetNextImageAttribute (const Image * image)
References GetImageAttribute(), and GetNextImageProperty().
GetNumberScenes()
MagickExport unsigned int GetNumberScenes (const Image *)
GetOnePixel()
MagickExport PixelPacket GetOnePixel (Image * , const ssize_t, const ssize_t)
GetPixels()
MagickExport PixelPacket * GetPixels (const Image *)
GetPreviousImage()
MagickExport Image * GetPreviousImage (const Image *)
GetTokenToken()
MagickExport void GetTokenToken (const char * , const char ** , char *)
HSLTransform()
MagickExport void HSLTransform (const double , const double , const double , Quantum * , Quantum * , Quantum *)
IdentityAffine()
MagickExport void IdentityAffine (AffineMatrix *)
InitializeMagick()
MagickExport void InitializeMagick (const char *)
InitializeModuleList()
MagickExport MagickBooleanType InitializeModuleList (ExceptionInfo *)
InterpolatePixelColor()
MagickExport MagickPixelPacket InterpolatePixelColor (const Image * image, CacheView * image_view, const InterpolatePixelMethod, const double x, const double y, ExceptionInfo * exception)
References AverageInterpolatePixel, BicubicInterpolate(), BicubicInterpolatePixel, BilinearInterpolatePixel, _MagickPixelPacket::blue, _Image::blur, CMYKColorspace, _Image::colorspace, CubicWeightingFunction(), DestroyImage(), ExcerptImage(), _Image::filter, FilterInterpolatePixel, GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickPixelPacket(), GetPixelAlpha, GetVirtualIndexQueue(), GetVirtualPixels(), _MagickPixelPacket::green, _RectangleInfo::height, _MagickPixelPacket::index, IntegerInterpolatePixel, MagickCoreSignature, MagickFalse, MagickPixelLuma(), _Image::matte, MeshInterpolate(), MeshInterpolatePixel, NearestNeighbor(), NearestNeighborInterpolatePixel, _MagickPixelPacket::opacity, PerceptibleReciprocal(), QuantumScale, _MagickPixelPacket::red, ResizeImage(), SetMagickPixelPacket(), _Image::signature, SplineInterpolatePixel, _RectangleInfo::width, _PointInfo::x, _RectangleInfo::x, _PointInfo::y, and _RectangleInfo::y.
InterpretImageAttributes()
MagickExport char * InterpretImageAttributes (const ImageInfo * , Image * , const char *)
InversesRGBCompandor()
MagickExport MagickRealType InversesRGBCompandor (const MagickRealType)
IsMagickInstantiated()
MagickExport MagickBooleanType IsMagickInstantiated (void)
IsSubimage()
MagickExport unsigned int IsSubimage (const char * , const unsigned int)
LevelImageColors()
MagickExport MagickBooleanType LevelImageColors (Image * , const ChannelType, const MagickPixelPacket * , const MagickPixelPacket * , const MagickBooleanType)
LiberateMemory()
MagickExport void LiberateMemory (void **)
LiberateSemaphoreInfo()
MagickExport void LiberateSemaphoreInfo (SemaphoreInfo **)
LoadMimeLists()
MagickExport MagickBooleanType LoadMimeLists (const char * , ExceptionInfo *)
magick_attribute()
MagickExport void magick_attribute ((deprecated))
MagickEpsilonReciprocal()
static double MagickEpsilonReciprocal (const double x) inline static
References MagickEpsilon.
MagickIncarnate()
MagickExport void MagickIncarnate (const char *)
MagickMonitor()
MagickExport MagickBooleanType MagickMonitor (const char * , const MagickOffsetType, const MagickSizeType, void *)
MapImage()
MagickExport MagickBooleanType MapImage (Image * , const Image * , const MagickBooleanType)
MapImages()
MagickExport MagickBooleanType MapImages (Image * , const Image * , const MagickBooleanType)
MatteFloodfillImage()
MagickExport MagickBooleanType MatteFloodfillImage (Image * , const PixelPacket, const Quantum, const ssize_t, const ssize_t, const PaintMethod)
MaximumImages()
MagickExport Image * MaximumImages (const Image * , ExceptionInfo *)
MedianFilterImage()
MagickExport Image * MedianFilterImage (const Image * , const double , ExceptionInfo *)
MinimumImages()
MagickExport Image * MinimumImages (const Image * , ExceptionInfo *)
ModeImage()
MagickExport Image * ModeImage (const Image * , const double , ExceptionInfo *)
MosaicImages()
MagickExport Image * MosaicImages (Image * , ExceptionInfo *)
OpaqueImage()
MagickExport MagickBooleanType OpaqueImage (Image * , const PixelPacket, const PixelPacket)
OpenCacheView()
MagickExport CacheView * OpenCacheView (const Image * image)
References AcquireVirtualCacheView().
OpenMagickStream()
MagickExport FILE * OpenMagickStream (const char * path, const char * mode)
References RelinquishMagickMemory().
PaintFloodfillImage()
MagickExport MagickBooleanType PaintFloodfillImage (Image * , const ChannelType, const MagickPixelPacket * , const ssize_t, const ssize_t, const DrawInfo * , const PaintMethod)
PaintOpaqueImage()
MagickExport MagickBooleanType PaintOpaqueImage (Image * , const MagickPixelPacket * , const MagickPixelPacket *)
PaintOpaqueImageChannel()
MagickExport MagickBooleanType PaintOpaqueImageChannel (Image * , const ChannelType, const MagickPixelPacket * , const MagickPixelPacket *)
PaintTransparentImage()
MagickExport MagickBooleanType PaintTransparentImage (Image * , const MagickPixelPacket * , const Quantum)
ParseImageGeometry()
MagickExport int ParseImageGeometry (const char * , ssize_t * , ssize_t * , size_t * , size_t *)
ParseSizeGeometry()
MagickExport MagickStatusType ParseSizeGeometry (const Image * image, const char * geometry, RectangleInfo * region_info)
References DeprecateEvent, GetMagickModule, _RectangleInfo::height, LogMagickEvent(), ParseMetaGeometry(), SetGeometry(), _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
PixelIntensityToQuantum()
static Quantum PixelIntensityToQuantum (const Image *magick_restrict image, const PixelPacket *magick_restrict pixel) inline static
References ClampToQuantum(), and GetPixelIntensity().
PopImageList()
MagickExport Image * PopImageList (Image **)
PopImagePixels()
MagickExport size_t PopImagePixels (Image * , const QuantumType, unsigned char *)
PostscriptGeometry()
MagickExport char * PostscriptGeometry (const char *)
PushImageList()
MagickExport unsigned int PushImageList (Image ** , const Image * , ExceptionInfo *)
PushImagePixels()
MagickExport size_t PushImagePixels (Image * image, const QuantumType, const unsigned char * source)
References AcquireQuantumInfo(), DestroyQuantumInfo(), _Image::exception, and ImportQuantumPixels().
QuantizationError()
MagickExport unsigned int QuantizationError (Image *)
RadialBlurImage()
MagickExport Image * RadialBlurImage (const Image * , const double , ExceptionInfo *)
RadialBlurImageChannel()
MagickExport Image * RadialBlurImageChannel (const Image * , const ChannelType, const double , ExceptionInfo *)
RandomChannelThresholdImage()
MagickExport unsigned int RandomChannelThresholdImage (Image * , const char * , const char * , ExceptionInfo *)
ReacquireMemory()
MagickExport void ReacquireMemory (void ** , const size_t)
RecolorImage()
MagickExport Image * RecolorImage (const Image * , const size_t, const double * , ExceptionInfo *)
ReduceNoiseImage()
MagickExport Image * ReduceNoiseImage (const Image * , const double , ExceptionInfo *)
RelinquishSemaphoreInfo()
MagickExport void RelinquishSemaphoreInfo (SemaphoreInfo *)
ResetImageAttributeIterator()
MagickExport void ResetImageAttributeIterator (const Image *)
SetCacheThreshold()
MagickExport void SetCacheThreshold (const size_t)
SetCacheViewPixels()
MagickExport PixelPacket * SetCacheViewPixels (CacheView * , const ssize_t, const ssize_t, const size_t, const size_t)
SetExceptionInfo()
MagickExport MagickBooleanType SetExceptionInfo (ExceptionInfo * , ExceptionType)
SetImage()
MagickExport void SetImage (Image * , const Quantum)
SetImageAttribute()
MagickExport MagickBooleanType SetImageAttribute (Image * , const char * , const char *)
SetImageList()
MagickExport unsigned int SetImageList (Image ** , const Image * , const ssize_t, ExceptionInfo *)
SetImagePixels()
MagickExport PixelPacket * SetImagePixels (Image * image, const ssize_t, const ssize_t, const size_t, const size_t)
References _Image::exception, and QueueAuthenticPixels().
SetMagickRegistry()
MagickExport ssize_t SetMagickRegistry (const RegistryType, const void * , const size_t, ExceptionInfo *)
SetMonitorHandler()
MagickExport MonitorHandler SetMonitorHandler (MonitorHandler handler)
References monitor_handler.
ShiftImageList()
MagickExport Image * ShiftImageList (Image **)
SizeBlob()
MagickExport MagickOffsetType SizeBlob (Image * image)
References _Image::debug, DeprecateEvent, GetBlobSize(), GetMagickModule, LogMagickEvent(), and MagickFalse.
SpliceImageList()
MagickExport Image * SpliceImageList (Image * , const ssize_t, const size_t, const Image * , ExceptionInfo *)
sRGBCompandor()
MagickExport MagickRealType sRGBCompandor (const MagickRealType)
References QuantumRange, and QuantumScale.
Strip()
MagickExport void Strip (char *)
SyncCacheViewPixels()
MagickExport MagickBooleanType SyncCacheViewPixels (CacheView *)
SyncImagePixels()
MagickExport MagickBooleanType SyncImagePixels (Image *)
SystemCommand()
MagickExport int SystemCommand (const MagickBooleanType, const MagickBooleanType, const char * command, ExceptionInfo * exception)
References ExternalDelegateCommand().
TemporaryFilename()
MagickExport void TemporaryFilename (char *)
ThresholdImage()
MagickExport unsigned int ThresholdImage (Image * , const double)
ThresholdImageChannel()
MagickExport unsigned int ThresholdImageChannel (Image * , const char *)
TransformColorspace()
MagickExport unsigned int TransformColorspace (Image * , const ColorspaceType)
TransformHSL()
MagickExport void TransformHSL (const Quantum, const Quantum, const Quantum, double * hue, double * saturation, double * lightness)
References MagickMax, MagickMin, and QuantumScale.
TranslateText()
MagickExport char * TranslateText (const ImageInfo * image_info, Image * image, const char * embed_text)
References _Image::debug, DeprecateEvent, GetMagickModule, InterpretImageProperties(), LogMagickEvent(), MagickCoreSignature, MagickFalse, and _Image::signature.
TransparentImage()
MagickExport MagickBooleanType TransparentImage (Image * image, const PixelPacket, const Quantum)
References _Image::columns, _Image::debug, DeprecateEvent, _Image::exception, _Image::filename, GetAuthenticPixels(), GetMagickModule, IsColorSimilar(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OpaqueAlphaChannel, _Image::rows, SetImageAlphaChannel(), SetImageProgress(), _Image::signature, SyncAuthenticPixels(), TraceEvent, and TransparentImageTag.
UnshiftImageList()
MagickExport unsigned int UnshiftImageList (Image ** images, const Image * image, ExceptionInfo * exception)
References CloneImageList(), DeprecateEvent, GetMagickModule, LogMagickEvent(), MagickTrue, and PrependImageToList().
ValidateColormapIndex()
MagickExport IndexPacket ValidateColormapIndex (Image * image, const size_t)
References ConstrainColormapIndex(), _Image::debug, DeprecateEvent, GetMagickModule, LogMagickEvent(), and MagickFalse.
ZoomImage()
MagickExport Image * ZoomImage (const Image * image, const size_t, const size_t, ExceptionInfo * exception)
References _Image::blur, _Image::debug, _Image::filename, _Image::filter, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, ResizeImage(), _ExceptionInfo::signature, _Image::signature, and TraceEvent.