MagickCore: deprecate.c File Reference
deprecate.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/cache.h"
#include "magick/cache-view.h"
#include "magick/channel.h"
#include "magick/client.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colormap.h"
#include "magick/colormap-private.h"
#include "magick/colorspace.h"
#include "magick/colorspace-private.h"
#include "magick/composite.h"
#include "magick/composite-private.h"
#include "magick/constitute.h"
#include "magick/deprecate.h"
#include "magick/draw.h"
#include "magick/draw-private.h"
#include "magick/effect.h"
#include "magick/enhance.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/fx.h"
#include "magick/geometry.h"
#include "magick/identify.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/log.h"
#include "magick/memory_.h"
#include "magick/magick.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/morphology.h"
#include "magick/mutex.h"
#include "magick/nt-feature.h"
#include "magick/paint.h"
#include "magick/pixel.h"
#include "magick/pixel-accessor.h"
#include "magick/pixel-private.h"
#include "magick/property.h"
#include "magick/quantize.h"
#include "magick/random_.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/semaphore-private.h"
#include "magick/segment.h"
#include "magick/splay-tree.h"
#include "magick/statistic.h"
#include "magick/string_.h"
#include "magick/threshold.h"
#include "magick/thread_.h"
#include "magick/thread-private.h"
#include "magick/token.h"
#include "magick/transform.h"
#include "magick/utility.h"
Macros
#define MaxStacksize (1UL << 15)
#define PushSegmentStack(up, left, right, delta)
#define OpaqueImageTag "Opaque/Image"
#define RandomChannelThresholdImageText " RandomChannelThreshold image... "
#define ThresholdImageTag "Threshold/Image"
#define ThresholdImageTag "Threshold/Image"
#define TransparentImageTag "Transparent/Image"
Functions
MagickExport const IndexPacket * AcquireCacheViewIndexes (const CacheView *cache_view)
MagickExport const PixelPacket * AcquireCacheViewPixels (const CacheView *cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport const PixelPacket * AcquireImagePixels (const Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport const IndexPacket * AcquireIndexes (const Image *image)
MagickExport void * AcquireMemory (const size_t size)
MagickExport MagickBooleanType AcquireOneCacheViewPixel (const CacheView *cache_view, const ssize_t x, const ssize_t y, PixelPacket *pixel, ExceptionInfo *exception)
MagickExport MagickBooleanType AcquireOneCacheViewVirtualPixel (const CacheView *cache_view, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, PixelPacket *pixel, ExceptionInfo *exception)
MagickExport MagickPixelPacket AcquireOneMagickPixel (const Image *image, const ssize_t x, const ssize_t y, ExceptionInfo *exception)
MagickExport PixelPacket AcquireOnePixel (const Image *image, const ssize_t x, const ssize_t y, ExceptionInfo *exception)
MagickExport PixelPacket AcquireOneVirtualPixel (const Image *image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, ExceptionInfo *exception)
MagickExport const PixelPacket * AcquirePixels (const Image *image)
MagickExport void AcquireSemaphoreInfo (SemaphoreInfo **semaphore_info)
MagickExport MagickBooleanType AffinityImage (const QuantizeInfo *quantize_info, Image *image, const Image *affinity_image)
MagickExport MagickBooleanType AffinityImages (const QuantizeInfo *quantize_info, Image *images, const Image *affinity_image)
MagickExport Image * AllocateImage (const ImageInfo *image_info)
MagickExport MagickBooleanType AllocateImageColormap (Image *image, const size_t colors)
MagickExport void AllocateNextImage (const ImageInfo *image_info, Image *image)
MagickExport char * AllocateString (const char *source)
MagickExport Image * AverageImages (const Image *images, ExceptionInfo *exception)
MagickExport unsigned int ChannelImage (Image *image, const ChannelType channel)
MagickExport unsigned int ChannelThresholdImage (Image *image, const char *level)
MagickExport MagickBooleanType ClipPathImage (Image *image, const char *pathname, const MagickBooleanType inside)
MagickExport MagickBooleanType CloneImageAttributes (Image *image, const Image *clone_image)
MagickExport void * CloneMemory (void *destination, const void *source, const size_t size)
MagickExport CacheView * CloseCacheView (CacheView *view_info)
MagickExport MagickBooleanType ColorFloodfillImage (Image *image, const DrawInfo *draw_info, const PixelPacket target, const ssize_t x_offset, const ssize_t y_offset, const PaintMethod method)
MagickExport MagickBooleanType ConstituteComponentGenesis (void)
MagickExport void ConstituteComponentTerminus (void)
MagickExport MagickBooleanType DeleteImageAttribute (Image *image, const char *key)
MagickExport unsigned int DeleteImageList (Image *images, const ssize_t offset)
MagickExport MagickBooleanType DeleteMagickRegistry (const ssize_t id)
MagickExport void DestroyConstitute (void)
MagickExport void DestroyMagickRegistry (void)
MagickExport MagickBooleanType DescribeImage (Image *image, FILE *file, const MagickBooleanType verbose)
MagickExport void DestroyImageAttributes (Image *image)
MagickExport void DestroyImages (Image *image)
MagickExport void DestroyMagick (void)
MagickExport unsigned int DispatchImage (const Image *image, const ssize_t x_offset, const ssize_t y_offset, const size_t columns, const size_t rows, const char *map, const StorageType type, void *pixels, ExceptionInfo *exception)
static double GetSimilarityMetric (const Image *image, const Image *reference, const ssize_t x_offset, const ssize_t y_offset, const double similarity_threshold, ExceptionInfo *exception)
MagickExport Image * ExtractSubimageFromImage (Image *image, const Image *reference, ExceptionInfo *exception)
MagickExport Image * FlattenImages (Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType FormatImageAttributeList (Image *image, const char *key, const char *format, va_list operands)
MagickExport MagickBooleanType FormatImagePropertyList (Image *image, const char *property, const char *format, va_list operands)
MagickExport MagickBooleanType FormatImageAttribute (Image *image, const char *key, const char *format,...)
MagickExport ssize_t FormatMagickStringList (char *string, const size_t length, const char *format, va_list operands)
MagickExport ssize_t FormatMagickString (char *string, const size_t length, const char *format,...)
MagickExport void FormatStringList (char *string, const char *format, va_list operands)
MagickExport void FormatString (char *string, const char *format,...)
MagickExport unsigned int FuzzyColorMatch (const PixelPacket *p, const PixelPacket *q, const double fuzz)
MagickExport MagickBooleanType FuzzyColorCompare (const Image *image, const PixelPacket *p, const PixelPacket *q)
MagickExport MagickBooleanType FuzzyOpacityCompare (const Image *image, const PixelPacket *p, const PixelPacket *q)
MagickExport void * GetConfigureBlob (const char *filename, char *path, size_t *length, ExceptionInfo *exception)
MagickExport PixelPacket * GetCacheView (CacheView *cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows)
MagickExport IndexPacket * GetCacheViewIndexes (CacheView *cache_view)
MagickExport PixelPacket * GetCacheViewPixels (CacheView *cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows)
MagickExport void GetExceptionInfo (ExceptionInfo *exception)
static void * DestroyAttribute (void *attribute)
MagickExport const ImageAttribute * GetImageAttribute (const Image *image, const char *key)
MagickExport const ImageAttribute * GetImageClippingPathAttribute (Image *image)
MagickExport Image * GetImageFromMagickRegistry (const char *name, ssize_t *id, ExceptionInfo *exception)
MagickExport void * GetMagickRegistry (const ssize_t id, RegistryType *type, size_t *length, ExceptionInfo *exception)
MagickExport void GetMagickToken (const char *start, const char **end, char *token)
MagickExport int GetImageGeometry (Image *image, const char *geometry, const unsigned int size_to_fit, RectangleInfo *region_info)
MagickExport Image * GetImageList (const Image *images, const ssize_t offset, ExceptionInfo *exception)
MagickExport ssize_t GetImageListIndex (const Image *images)
MagickExport size_t GetImageListSize (const Image *images)
MagickExport PixelPacket * GetImagePixels (Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows)
MagickExport IndexPacket * GetIndexes (const Image *image)
MagickExport unsigned int GetMagickGeometry (const char *geometry, ssize_t *x, ssize_t *y, size_t *width, size_t *height)
MagickExport Image * GetNextImage (const Image *images)
MagickExport const ImageAttribute * GetNextImageAttribute (const Image *image)
MagickExport unsigned int GetNumberScenes (const Image *image)
MagickExport PixelPacket GetOnePixel (Image *image, const ssize_t x, const ssize_t y)
MagickExport PixelPacket * GetPixels (const Image *image)
MagickExport Image * GetPreviousImage (const Image *images)
static MagickRealType HueToRGB (MagickRealType m1, MagickRealType m2, MagickRealType hue)
MagickExport void HSLTransform (const double hue, const double saturation, const double lightness, Quantum *red, Quantum *green, Quantum *blue)
MagickExport void IdentityAffine (AffineMatrix *affine)
MagickExport void InitializeMagick (const char *path)
static void BicubicInterpolate (const MagickPixelPacket *pixels, const double dx, MagickPixelPacket *pixel)
static MagickRealType CubicWeightingFunction (const MagickRealType x)
static double MeshInterpolate (const PointInfo *delta, const double p, const double x, const double y)
static ssize_t NearestNeighbor (MagickRealType x)
MagickExport MagickPixelPacket InterpolatePixelColor (const Image *image, CacheView *image_view, const InterpolatePixelMethod method, const double x, const double y, ExceptionInfo *exception)
MagickExport char * InterpretImageAttributes (const ImageInfo *image_info, Image *image, const char *embed_text)
MagickExport MagickRealType InversesRGBCompandor (const MagickRealType pixel)
MagickExport MagickBooleanType IsMagickInstantiated (void)
MagickExport unsigned int IsSubimage (const char *geometry, const unsigned int pedantic)
MagickBooleanType LevelImageColors (Image *image, const ChannelType channel, const MagickPixelPacket *black_color, const MagickPixelPacket *white_color, const MagickBooleanType invert)
MagickExport void LiberateMemory (void **memory)
MagickExport void LiberateSemaphoreInfo (SemaphoreInfo **semaphore_info)
MagickExport void MagickIncarnate (const char *path)
MagickExport MagickBooleanType MagickMonitor (const char *text, const MagickOffsetType offset, const MagickSizeType span, void *magick_unused(client_data))
MagickExport MagickBooleanType MapImage (Image *image, const Image *map_image, const MagickBooleanType dither)
MagickExport MagickBooleanType MapImages (Image *images, const Image *map_image, const MagickBooleanType dither)
MagickExport MagickBooleanType MatteFloodfillImage (Image *image, const PixelPacket target, const Quantum opacity, const ssize_t x_offset, const ssize_t y_offset, const PaintMethod method)
MagickExport Image * MaximumImages (const Image *images, ExceptionInfo *exception)
MagickExport Image * MinimumImages (const Image *images, ExceptionInfo *exception)
MagickExport Image * MedianFilterImage (const Image *image, const double radius, ExceptionInfo *exception)
MagickExport Image * ModeImage (const Image *image, const double radius, ExceptionInfo *exception)
MagickExport Image * MosaicImages (Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType OpaqueImage (Image *image, const PixelPacket target, const PixelPacket fill)
MagickExport CacheView * OpenCacheView (const Image *image)
MagickExport FILE * OpenMagickStream (const char *path, const char *mode)
MagickExport MagickBooleanType PaintFloodfillImage (Image *image, const ChannelType channel, const MagickPixelPacket *target, const ssize_t x, const ssize_t y, const DrawInfo *draw_info, const PaintMethod method)
MagickExport MagickBooleanType PaintOpaqueImage (Image *image, const MagickPixelPacket *target, const MagickPixelPacket *fill)
MagickExport MagickBooleanType PaintOpaqueImageChannel (Image *image, const ChannelType channel, const MagickPixelPacket *target, const MagickPixelPacket *fill)
MagickExport MagickBooleanType PaintTransparentImage (Image *image, const MagickPixelPacket *target, const Quantum opacity)
MagickExport int ParseImageGeometry (const char *geometry, ssize_t *x, ssize_t *y, size_t *width, size_t *height)
MagickExport MagickStatusType ParseSizeGeometry (const Image *image, const char *geometry, RectangleInfo *region_info)
MagickExport Image * PopImageList (Image **images)
MagickExport size_t PopImagePixels (Image *image, const QuantumType quantum, unsigned char *destination)
MagickExport char * PostscriptGeometry (const char *page)
MagickExport unsigned int PushImageList (Image **images, const Image *image, ExceptionInfo *exception)
MagickExport size_t PushImagePixels (Image *image, const QuantumType quantum, const unsigned char *source)
MagickExport unsigned int QuantizationError (Image *image)
MagickExport Image * RadialBlurImage (const Image *image, const double angle, ExceptionInfo *exception)
MagickExport Image * RadialBlurImageChannel (const Image *image, const ChannelType channel, const double angle, ExceptionInfo *exception)
MagickExport unsigned int RandomChannelThresholdImage (Image *image, const char *channel, const char *thresholds, ExceptionInfo *exception)
MagickExport void ReacquireMemory (void **memory, const size_t size)
MagickExport Image * RecolorImage (const Image *image, const size_t order, const double *color_matrix, ExceptionInfo *exception)
MagickExport Image * ReduceNoiseImage (const Image *image, const double radius, ExceptionInfo *exception)
MagickExport void RelinquishSemaphoreInfo (SemaphoreInfo *semaphore_info)
MagickExport void ResetImageAttributeIterator (const Image *image)
MagickExport PixelPacket * SetCacheViewPixels (CacheView *cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows)
MagickExport void SetCacheThreshold (const size_t size)
MagickExport MagickBooleanType SetExceptionInfo (ExceptionInfo *exception, ExceptionType severity)
MagickExport void SetImage (Image *image, const Quantum opacity)
MagickExport MagickBooleanType SetImageAttribute (Image *image, const char *key, const char *value)
MagickExport unsigned int SetImageList (Image **images, const Image *image, const ssize_t offset, ExceptionInfo *exception)
MagickExport PixelPacket * SetImagePixels (Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows)
MagickExport ssize_t SetMagickRegistry (const RegistryType type, const void *blob, const size_t magick_unused(length), ExceptionInfo *exception)
MagickExport MonitorHandler GetMonitorHandler (void)
MagickExport MonitorHandler SetMonitorHandler (MonitorHandler handler)
MagickExport Image * ShiftImageList (Image **images)
MagickExport MagickOffsetType SizeBlob (Image *image)
MagickExport Image * SpliceImageList (Image *images, const ssize_t offset, const size_t length, const Image *splices, ExceptionInfo *exception)
MagickExport MagickRealType sRGBCompandor (const MagickRealType pixel)
MagickExport void Strip (char *message)
MagickExport MagickBooleanType SyncCacheView (CacheView *cache_view)
MagickExport MagickBooleanType SyncCacheViewPixels (CacheView *cache_view)
MagickExport MagickBooleanType SyncImagePixels (Image *image)
MagickExport int SystemCommand (const MagickBooleanType asynchronous, const MagickBooleanType verbose, const char *command, ExceptionInfo *exception)
MagickExport void TemporaryFilename (char *path)
MagickExport unsigned int ThresholdImage (Image *image, const double threshold)
MagickExport unsigned int ThresholdImageChannel (Image *image, const char *threshold)
MagickExport unsigned int TransformColorspace (Image *image, const ColorspaceType colorspace)
MagickExport void TransformHSL (const Quantum red, const Quantum green, const Quantum blue, double *hue, double *saturation, double *lightness)
MagickExport char * TranslateText (const ImageInfo *image_info, Image *image, const char *embed_text)
MagickExport MagickBooleanType TransparentImage (Image *image, const PixelPacket target, const Quantum opacity)
MagickExport unsigned int UnshiftImageList (Image **images, const Image *image, ExceptionInfo *exception)
MagickExport IndexPacket ValidateColormapIndex (Image *image, const size_t index)
MagickExport Image * ZoomImage (const Image *image, const size_t columns, const size_t rows, ExceptionInfo *exception)
Variables
static MonitorHandler monitor_handler = (MonitorHandler) NULL
Macro Definition Documentation
MaxStacksize
#define MaxStacksize (1UL << 15)
OpaqueImageTag
#define OpaqueImageTag "Opaque/Image"
PushSegmentStack
#define PushSegmentStack (up, left, right, delta)
Value:
{ \
  if (s >= (segment_stack+MaxStacksize)) \
    ThrowBinaryImageException(DrawError,"SegmentStackOverflow",image->filename) \
  else \
    { \
      if ((((up)+(delta)) >= 0) && (((up)+(delta)) < (ssize_t) image->rows)) \
        { \
          s->x1=(double) (left); \
          s->y1=(double) (up); \
          s->x2=(double) (right); \
          s->y2=(double) (delta); \
          s++; \
        } \
    } \
}
RandomChannelThresholdImageText
#define RandomChannelThresholdImageText " RandomChannelThreshold image... "
ThresholdImageTag [1/2]
#define ThresholdImageTag "Threshold/Image"
ThresholdImageTag [2/2]
#define ThresholdImageTag "Threshold/Image"
TransparentImageTag
#define TransparentImageTag "Transparent/Image"
Function Documentation
AcquireCacheViewIndexes()
MagickExport const IndexPacket * AcquireCacheViewIndexes (const CacheView * cache_view)
References GetCacheViewVirtualIndexQueue().
AcquireCacheViewPixels()
MagickExport const PixelPacket * AcquireCacheViewPixels (const CacheView * cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception)
References GetCacheViewVirtualPixels().
AcquireImagePixels()
MagickExport const PixelPacket * AcquireImagePixels (const Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception)
References GetVirtualPixels().
AcquireIndexes()
MagickExport const IndexPacket * AcquireIndexes (const Image * image)
References GetVirtualIndexQueue().
AcquireMemory()
MagickExport void * AcquireMemory (const size_t size)
References DeprecateEvent, GetMagickModule, and LogMagickEvent().
AcquireOneCacheViewPixel()
MagickExport MagickBooleanType AcquireOneCacheViewPixel (const CacheView * cache_view, const ssize_t x, const ssize_t y, PixelPacket * pixel, ExceptionInfo * exception)
References GetOneCacheViewVirtualPixel().
AcquireOneCacheViewVirtualPixel()
MagickExport MagickBooleanType AcquireOneCacheViewVirtualPixel (const CacheView * cache_view, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, PixelPacket * pixel, ExceptionInfo * exception)
References GetOneCacheViewVirtualMethodPixel().
AcquireOneMagickPixel()
MagickExport MagickPixelPacket AcquireOneMagickPixel (const Image * image, const ssize_t x, const ssize_t y, ExceptionInfo * exception)
References GetOneVirtualMagickPixel().
AcquireOnePixel()
MagickExport PixelPacket AcquireOnePixel (const Image * image, const ssize_t x, const ssize_t y, ExceptionInfo * exception)
References GetOneVirtualPixel().
AcquireOneVirtualPixel()
MagickExport PixelPacket AcquireOneVirtualPixel (const Image * image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, ExceptionInfo * exception)
References GetOneVirtualMethodPixel().
AcquirePixels()
MagickExport const PixelPacket * AcquirePixels (const Image * image)
References GetVirtualPixelQueue().
AcquireSemaphoreInfo()
MagickExport void AcquireSemaphoreInfo (SemaphoreInfo ** semaphore_info)
References AllocateSemaphoreInfo(), InitializeMagickMutex(), LockMagickMutex(), and UnlockMagickMutex().
AffinityImage()
MagickExport MagickBooleanType AffinityImage (const QuantizeInfo * quantize_info, Image * image, const Image * affinity_image)
References RemapImage().
AffinityImages()
MagickExport MagickBooleanType AffinityImages (const QuantizeInfo * quantize_info, Image * images, const Image * affinity_image)
References RemapImages().
AllocateImage()
MagickExport Image * AllocateImage (const ImageInfo * image_info)
References AcquireImage().
AllocateImageColormap()
MagickExport MagickBooleanType AllocateImageColormap (Image * image, const size_t colors)
References AcquireImageColormap().
AllocateNextImage()
MagickExport void AllocateNextImage (const ImageInfo * image_info, Image * image)
References AcquireNextImage().
AllocateString()
MagickExport char * AllocateString (const char * source)
References AcquireQuantumMemory(), CopyMagickString(), DeprecateEvent, GetMagickModule, LogMagickEvent(), MaxTextExtent, ResourceLimitFatalError, and ThrowFatalException.
AverageImages()
MagickExport Image * AverageImages (const Image * images, ExceptionInfo * exception)
References EvaluateImages(), and MeanEvaluateOperator.
BicubicInterpolate()
static void BicubicInterpolate (const MagickPixelPacket * pixels, const double dx, MagickPixelPacket * pixel) static
References _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, _MagickPixelPacket::opacity, and _MagickPixelPacket::red.
Referenced by InterpolatePixelColor().
ChannelImage()
MagickExport unsigned int ChannelImage (Image * image, const ChannelType channel)
References SeparateImageChannel().
ChannelThresholdImage()
MagickExport unsigned int ChannelThresholdImage (Image * image, const char * level)
References BilevelImageChannel(), _MagickPixelPacket::blue, BlueChannel, _Image::debug, DeprecateEvent, _Image::filename, GetMagickModule, _MagickPixelPacket::green, GreenChannel, LogMagickEvent(), MagickCoreSignature, MagickFalse, ParseGeometry(), _MagickPixelPacket::red, RedChannel, _GeometryInfo::rho, _GeometryInfo::sigma, SigmaValue, _Image::signature, TraceEvent, _GeometryInfo::xi, and XiValue.
ClipPathImage()
MagickExport MagickBooleanType ClipPathImage (Image * image, const char * pathname, const MagickBooleanType inside)
References ClipImagePath().
CloneImageAttributes()
MagickExport MagickBooleanType CloneImageAttributes (Image * image, const Image * clone_image)
References CloneImageProperties().
CloneMemory()
MagickExport void * CloneMemory (void * destination, const void * source, const size_t size)
References DeprecateEvent, GetMagickModule, and LogMagickEvent().
CloseCacheView()
MagickExport CacheView * CloseCacheView (CacheView * view_info)
References DestroyCacheView().
ColorFloodfillImage()
MagickExport MagickBooleanType ColorFloodfillImage (Image * image, const DrawInfo * draw_info, const PixelPacket target, const ssize_t x_offset, const ssize_t y_offset, const PaintMethod method)
References AcquireQuantumMemory(), CloneImage(), _Image::columns, _Image::debug, DestroyImage(), DirectClass, _Image::exception, _Image::filename, FloodfillMethod, GetAuthenticPixels(), GetFillColor(), GetMagickModule, GetPixelOpacity, GetVirtualPixels(), IsColorSimilar(), LogMagickEvent(), magick_restrict, MagickCompositeOver(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, MaxStacksize, _PixelPacket::opacity, OpaqueAlphaChannel, OpaqueOpacity, PushSegmentStack, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageAlphaChannel(), SetImageStorageClass(), _DrawInfo::signature, _Image::signature, SyncAuthenticPixels(), ThrowBinaryImageException, TraceEvent, TransparentOpacity, _SegmentInfo::x1, _SegmentInfo::x2, _SegmentInfo::y1, and _SegmentInfo::y2.
ConstituteComponentGenesis()
MagickExport MagickBooleanType ConstituteComponentGenesis (void)
References MagickTrue.
ConstituteComponentTerminus()
MagickExport void ConstituteComponentTerminus (void)
CubicWeightingFunction()
static MagickRealType CubicWeightingFunction (const MagickRealType x) inline static
References MagickMax.
Referenced by InterpolatePixelColor().
DeleteImageAttribute()
MagickExport MagickBooleanType DeleteImageAttribute (Image * image, const char * key)
References DeleteImageProperty().
DeleteImageList()
MagickExport unsigned int DeleteImageList (Image * images, const ssize_t offset)
References _Image::debug, DeleteImageFromList(), DeprecateEvent, GetMagickModule, GetNextImageInList(), GetPreviousImageInList(), LogMagickEvent(), MagickFalse, and MagickTrue.
DeleteMagickRegistry()
MagickExport MagickBooleanType DeleteMagickRegistry (const ssize_t id)
References DeleteImageRegistry(), FormatLocaleString(), and MaxTextExtent.
DescribeImage()
MagickExport MagickBooleanType DescribeImage (Image * image, FILE * file, const MagickBooleanType verbose)
References IdentifyImage().
DestroyAttribute()
static void * DestroyAttribute (void * attribute) static
References DestroyString(), RelinquishMagickMemory(), and _ImageAttribute::value.
Referenced by GetImageAttribute().
DestroyConstitute()
MagickExport void DestroyConstitute (void)
DestroyImageAttributes()
MagickExport void DestroyImageAttributes (Image * image)
References _Image::attributes, _Image::debug, DestroySplayTree(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
DestroyImages()
MagickExport void DestroyImages (Image * image)
References _Image::debug, DeprecateEvent, DestroyImageList(), GetMagickModule, LogMagickEvent(), and MagickFalse.
DestroyMagick()
MagickExport void DestroyMagick (void)
References MagickCoreTerminus().
DestroyMagickRegistry()
MagickExport void DestroyMagickRegistry (void)
References RegistryComponentTerminus().
DispatchImage()
MagickExport unsigned int DispatchImage (const Image * image, const ssize_t x_offset, const ssize_t y_offset, const size_t columns, const size_t rows, const char * map, const StorageType type, void * pixels, ExceptionInfo * exception)
References _Image::debug, DeprecateEvent, ExportImagePixels(), GetMagickModule, LogMagickEvent(), and MagickFalse.
ExtractSubimageFromImage()
MagickExport Image * ExtractSubimageFromImage (Image * image, const Image * reference, ExceptionInfo * exception)
References _Image::columns, CropImage(), _Image::fuzz, GetSimilarityMetric(), QuantumScale, _Image::rows, SetGeometry(), _RectangleInfo::x, and _RectangleInfo::y.
FlattenImages()
MagickExport Image * FlattenImages (Image * image, ExceptionInfo * exception)
References FlattenLayer, and MergeImageLayers().
FormatImageAttribute()
MagickExport MagickBooleanType FormatImageAttribute (Image * image, const char * key, const char * format, ...)
References FormatLocaleStringList(), MaxTextExtent, and SetImageProperty().
FormatImageAttributeList()
MagickExport MagickBooleanType FormatImageAttributeList (Image * image, const char * key, const char * format, va_list operands)
References MaxTextExtent, and SetImageProperty().
FormatImagePropertyList()
MagickExport MagickBooleanType FormatImagePropertyList (Image * image, const char * property, const char * format, va_list operands)
References MaxTextExtent, and SetImageProperty().
FormatMagickString()
MagickExport ssize_t FormatMagickString (char * string, const size_t length, const char * format, ...)
References FormatMagickStringList().
FormatMagickStringList()
MagickExport ssize_t FormatMagickStringList (char * string, const size_t length, const char * format, va_list operands)
Referenced by FormatMagickString().
FormatString()
MagickExport void FormatString (char * string, const char * format, ...)
References FormatLocaleStringList(), and MaxTextExtent.
FormatStringList()
MagickExport void FormatStringList (char * string, const char * format, va_list operands)
References DeprecateEvent, GetMagickModule, LogMagickEvent(), and MaxTextExtent.
FuzzyColorCompare()
MagickExport MagickBooleanType FuzzyColorCompare (const Image * image, const PixelPacket * p, const PixelPacket * q)
References DeprecateEvent, GetMagickModule, IsColorSimilar(), and LogMagickEvent().
FuzzyColorMatch()
MagickExport unsigned int FuzzyColorMatch (const PixelPacket * p, const PixelPacket * q, const double fuzz)
References _MagickPixelPacket::blue, GetPixelBlue, GetPixelGreen, GetPixelRed, _MagickPixelPacket::green, MagickFalse, MagickTrue, and _MagickPixelPacket::red.
FuzzyOpacityCompare()
MagickExport MagickBooleanType FuzzyOpacityCompare (const Image * image, const PixelPacket * p, const PixelPacket * q)
References DeprecateEvent, GetMagickModule, IsOpacitySimilar(), and LogMagickEvent().
GetCacheView()
MagickExport PixelPacket * GetCacheView (CacheView * cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows)
References GetCacheViewAuthenticPixels(), and GetCacheViewException().
GetCacheViewIndexes()
MagickExport IndexPacket * GetCacheViewIndexes (CacheView * cache_view)
References GetCacheViewAuthenticIndexQueue().
GetCacheViewPixels()
MagickExport PixelPacket * GetCacheViewPixels (CacheView * cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows)
References GetCacheViewAuthenticPixels(), and GetCacheViewException().
GetConfigureBlob()
MagickExport void * GetConfigureBlob (const char * filename, char * path, size_t * length, ExceptionInfo * exception)
References ChopPathComponents(), ConfigureWarning, CopyMagickString(), DeprecateEvent, DestroyString(), DirectorySeparator, FileToBlob(), FormatLocaleString(), GetClientPath(), GetEnvironmentValue(), GetMagickModule, IsPathAccessible(), LogMagickEvent(), MAGICKCORE_LIBRARY_PATH, MAGICKCORE_LIBRARY_RELATIVE_PATH, MagickFalse, MaxTextExtent, ThrowMagickException(), and TraceEvent.
GetExceptionInfo()
MagickExport void GetExceptionInfo (ExceptionInfo * exception)
References AllocateSemaphoreInfo(), _ExceptionInfo::exceptions, MagickCoreSignature, NewLinkedList(), _ExceptionInfo::semaphore, _ExceptionInfo::severity, _ExceptionInfo::signature, and UndefinedException.
GetImageAttribute()
MagickExport const ImageAttribute * GetImageAttribute (const Image * image, const char * key)
References AcquireMagickMemory(), AddValueToSplayTree(), _Image::attributes, CompareSplayTreeString(), ConstantString(), DeprecateEvent, DestroyAttribute(), GetImageProperty(), GetMagickModule, GetValueFromSplayTree(), _ImageAttribute::key, LogMagickEvent(), NewSplayTree(), RelinquishMagickMemory(), ResourceLimitFatalError, ThrowFatalException, and _ImageAttribute::value.
Referenced by GetImageClippingPathAttribute(), and GetNextImageAttribute().
GetImageClippingPathAttribute()
MagickExport const ImageAttribute * GetImageClippingPathAttribute (Image * image)
References GetImageAttribute().
GetImageFromMagickRegistry()
MagickExport Image * GetImageFromMagickRegistry (const char * name, ssize_t * id, ExceptionInfo * exception)
References GetImageRegistry(), and ImageRegistryType.
GetImageGeometry()
MagickExport int GetImageGeometry (Image * image, const char * geometry, const unsigned int size_to_fit, RectangleInfo * region_info)
References _Image::debug, DeprecateEvent, _Image::exception, GetMagickModule, LogMagickEvent(), MagickFalse, ParsePageGeometry(), and ParseRegionGeometry().
GetImageList()
MagickExport Image * GetImageList (const Image * images, const ssize_t offset, ExceptionInfo * exception)
References CloneImage(), _Image::debug, DeprecateEvent, GetImageFromList(), GetMagickModule, LogMagickEvent(), MagickFalse, and MagickTrue.
GetImageListIndex()
MagickExport ssize_t GetImageListIndex (const Image * images)
References _Image::debug, DeprecateEvent, GetImageIndexInList(), GetMagickModule, LogMagickEvent(), and MagickFalse.
GetImageListSize()
MagickExport size_t GetImageListSize (const Image * images)
References _Image::debug, DeprecateEvent, GetImageListLength(), GetMagickModule, LogMagickEvent(), and MagickFalse.
GetImagePixels()
MagickExport PixelPacket * GetImagePixels (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows)
References _Image::exception, and GetAuthenticPixels().
GetIndexes()
MagickExport IndexPacket * GetIndexes (const Image * image)
References GetAuthenticIndexQueue().
GetMagickGeometry()
MagickExport unsigned int GetMagickGeometry (const char * geometry, ssize_t * x, ssize_t * y, size_t * width, size_t * height)
References DeprecateEvent, GetMagickModule, LogMagickEvent(), and ParseMetaGeometry().
GetMagickRegistry()
MagickExport void * GetMagickRegistry (const ssize_t id, RegistryType * type, size_t * length, ExceptionInfo * exception)
References FormatLocaleString(), GetImageRegistry(), ImageInfoRegistryType, ImageRegistryType, MaxTextExtent, and UndefinedRegistryType.
GetMagickToken()
MagickExport void GetMagickToken (const char * start, const char ** end, char * token)
References GetNextToken().
GetMonitorHandler()
MagickExport MonitorHandler GetMonitorHandler (void)
References monitor_handler.
GetNextImage()
MagickExport Image * GetNextImage (const Image * images)
References _Image::debug, DeprecateEvent, GetMagickModule, GetNextImageInList(), LogMagickEvent(), and MagickFalse.
GetNextImageAttribute()
MagickExport const ImageAttribute * GetNextImageAttribute (const Image * image)
References GetImageAttribute(), and GetNextImageProperty().
GetNumberScenes()
MagickExport unsigned int GetNumberScenes (const Image * image)
References _Image::debug, DeprecateEvent, GetImageListLength(), GetMagickModule, LogMagickEvent(), and MagickFalse.
GetOnePixel()
MagickExport PixelPacket GetOnePixel (Image * image, const ssize_t x, const ssize_t y)
References _Image::exception, and GetOneAuthenticPixel().
GetPixels()
MagickExport PixelPacket * GetPixels (const Image * image)
References GetAuthenticPixelQueue().
GetPreviousImage()
MagickExport Image * GetPreviousImage (const Image * images)
References _Image::debug, DeprecateEvent, GetMagickModule, GetPreviousImageInList(), LogMagickEvent(), and MagickFalse.
GetSimilarityMetric()
static double GetSimilarityMetric (const Image * image, const Image * reference, const ssize_t x_offset, const ssize_t y_offset, const double similarity_threshold, ExceptionInfo * exception) static
References AcquireVirtualCacheView(), CMYKColorspace, _Image::colorspace, _Image::columns, DestroyCacheView(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, MagickFalse, _Image::matte, QuantumScale, and _Image::rows.
Referenced by ExtractSubimageFromImage().
HSLTransform()
MagickExport void HSLTransform (const double hue, const double saturation, const double lightness, Quantum * red, Quantum * green, Quantum * blue)
References ClampToQuantum(), HueToRGB(), and QuantumRange.
HueToRGB()
static MagickRealType HueToRGB (MagickRealType m1, MagickRealType m2, MagickRealType hue) inline static
Referenced by HSLTransform().
IdentityAffine()
MagickExport void IdentityAffine (AffineMatrix * affine)
References DeprecateEvent, GetMagickModule, LogMagickEvent(), _AffineMatrix::sx, _AffineMatrix::sy, and TraceEvent.
InitializeMagick()
MagickExport void InitializeMagick (const char * path)
References MagickCoreGenesis(), and MagickFalse.
InterpolatePixelColor()
MagickExport MagickPixelPacket InterpolatePixelColor (const Image * image, CacheView * image_view, const InterpolatePixelMethod method, const double x, const double y, ExceptionInfo * exception)
References AverageInterpolatePixel, BicubicInterpolate(), BicubicInterpolatePixel, BilinearInterpolatePixel, _MagickPixelPacket::blue, _Image::blur, CMYKColorspace, _Image::colorspace, CubicWeightingFunction(), DestroyImage(), ExcerptImage(), _Image::filter, FilterInterpolatePixel, GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickPixelPacket(), GetPixelAlpha, GetVirtualIndexQueue(), GetVirtualPixels(), _MagickPixelPacket::green, _RectangleInfo::height, _MagickPixelPacket::index, IntegerInterpolatePixel, MagickCoreSignature, MagickFalse, MagickPixelLuma(), _Image::matte, MeshInterpolate(), MeshInterpolatePixel, NearestNeighbor(), NearestNeighborInterpolatePixel, _MagickPixelPacket::opacity, PerceptibleReciprocal(), QuantumScale, _MagickPixelPacket::red, ResizeImage(), SetMagickPixelPacket(), _Image::signature, SplineInterpolatePixel, _RectangleInfo::width, _PointInfo::x, _RectangleInfo::x, _PointInfo::y, and _RectangleInfo::y.
InterpretImageAttributes()
MagickExport char * InterpretImageAttributes (const ImageInfo * image_info, Image * image, const char * embed_text)
References DeprecateEvent, GetMagickModule, InterpretImageProperties(), and LogMagickEvent().
InversesRGBCompandor()
MagickExport MagickRealType InversesRGBCompandor (const MagickRealType pixel)
References QuantumRange, and QuantumScale.
IsMagickInstantiated()
MagickExport MagickBooleanType IsMagickInstantiated (void)
References IsMagickCoreInstantiated().
IsSubimage()
MagickExport unsigned int IsSubimage (const char * geometry, const unsigned int pedantic)
References DeprecateEvent, GetMagickModule, LogMagickEvent(), MagickFalse, and MagickTrue.
LevelImageColors()
MagickBooleanType LevelImageColors (Image * image, const ChannelType channel, const MagickPixelPacket * black_color, const MagickPixelPacket * white_color, const MagickBooleanType invert)
References LevelColorsImageChannel().
LiberateMemory()
MagickExport void LiberateMemory (void ** memory)
References DeprecateEvent, GetMagickModule, and LogMagickEvent().
LiberateSemaphoreInfo()
MagickExport void LiberateSemaphoreInfo (SemaphoreInfo ** semaphore_info)
References DeprecateEvent, GetMagickModule, LogMagickEvent(), and UnlockSemaphoreInfo().
MagickIncarnate()
MagickExport void MagickIncarnate (const char * path)
References DeprecateEvent, GetMagickModule, LogMagickEvent(), MagickCoreGenesis(), and MagickFalse.
MagickMonitor()
MagickExport MagickBooleanType MagickMonitor (const char * text, const MagickOffsetType offset, const MagickSizeType span, void * magick_unusedclient_data)
References AcquireExceptionInfo(), DestroyExceptionInfo(), GetMagickModule, LogMagickEvent(), magick_unreferenced, MagickTrue, monitor_handler, ProcessPendingEvents(), and TraceEvent.
MapImage()
MagickExport MagickBooleanType MapImage (Image * image, const Image * map_image, const MagickBooleanType dither)
References _Image::debug, _QuantizeInfo::dither, _Image::filename, GetMagickModule, GetQuantizeInfo(), LogMagickEvent(), MagickCoreSignature, MagickFalse, RemapImage(), _Image::signature, and TraceEvent.
MapImages()
MagickExport MagickBooleanType MapImages (Image * images, const Image * map_image, const MagickBooleanType dither)
References _Image::debug, _QuantizeInfo::dither, _Image::filename, GetMagickModule, GetQuantizeInfo(), LogMagickEvent(), MagickCoreSignature, MagickFalse, RemapImages(), _Image::signature, and TraceEvent.
MatteFloodfillImage()
MagickExport MagickBooleanType MatteFloodfillImage (Image * image, const PixelPacket target, const Quantum opacity, const ssize_t x_offset, const ssize_t y_offset, const PaintMethod method)
References AcquireQuantumMemory(), CloneImage(), _Image::columns, _Image::debug, DestroyImage(), DirectClass, _Image::exception, _Image::filename, FloodfillMethod, GetAuthenticPixels(), GetMagickModule, GetPixelOpacity, GetVirtualPixels(), IsColorSimilar(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, MaxStacksize, OpaqueAlphaChannel, OpaqueOpacity, PushSegmentStack, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageAlphaChannel(), SetImageStorageClass(), _Image::signature, SyncAuthenticPixels(), ThrowBinaryImageException, TraceEvent, TransparentOpacity, _SegmentInfo::x1, _SegmentInfo::x2, _SegmentInfo::y1, and _SegmentInfo::y2.
MaximumImages()
MagickExport Image * MaximumImages (const Image * images, ExceptionInfo * exception)
References EvaluateImages(), and MinEvaluateOperator.
MedianFilterImage()
MagickExport Image * MedianFilterImage (const Image * image, const double radius, ExceptionInfo * exception)
References MedianStatistic, and StatisticImage().
MeshInterpolate()
static double MeshInterpolate (const PointInfo * delta, const double p, const double x, const double y) inline static
References _PointInfo::x, and _PointInfo::y.
Referenced by InterpolatePixelColor().
MinimumImages()
MagickExport Image * MinimumImages (const Image * images, ExceptionInfo * exception)
References EvaluateImages(), and MinEvaluateOperator.
ModeImage()
MagickExport Image * ModeImage (const Image * image, const double radius, ExceptionInfo * exception)
References ModeStatistic, and StatisticImage().
MosaicImages()
MagickExport Image * MosaicImages (Image * image, ExceptionInfo * exception)
References MergeImageLayers(), and MosaicLayer.
NearestNeighbor()
static ssize_t NearestNeighbor (MagickRealType x) inline static
Referenced by InterpolatePixelColor().
OpaqueImage()
MagickExport MagickBooleanType OpaqueImage (Image * image, const PixelPacket target, const PixelPacket fill)
References _Image::colormap, _Image::colors, _Image::columns, _Image::debug, DeprecateEvent, DirectClass, _Image::exception, _Image::filename, GetAuthenticPixels(), GetMagickModule, IsColorSimilar(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _PixelPacket::opacity, OpaqueImageTag, OpaqueOpacity, PseudoClass, _Image::rows, SetImageProgress(), _Image::signature, _Image::storage_class, SyncAuthenticPixels(), SyncImage(), and TraceEvent.
OpenCacheView()
MagickExport CacheView * OpenCacheView (const Image * image)
References AcquireVirtualCacheView().
OpenMagickStream()
MagickExport FILE * OpenMagickStream (const char * path, const char * mode)
References RelinquishMagickMemory().
PaintFloodfillImage()
MagickExport MagickBooleanType PaintFloodfillImage (Image * image, const ChannelType channel, const MagickPixelPacket * target, const ssize_t x, const ssize_t y, const DrawInfo * draw_info, const PaintMethod method)
References FloodfillMethod, FloodfillPaintImage(), MagickFalse, and MagickTrue.
PaintOpaqueImage()
MagickExport MagickBooleanType PaintOpaqueImage (Image * image, const MagickPixelPacket * target, const MagickPixelPacket * fill)
References DefaultChannels, MagickFalse, and OpaquePaintImageChannel().
PaintOpaqueImageChannel()
MagickExport MagickBooleanType PaintOpaqueImageChannel (Image * image, const ChannelType channel, const MagickPixelPacket * target, const MagickPixelPacket * fill)
References MagickFalse, and OpaquePaintImageChannel().
PaintTransparentImage()
MagickExport MagickBooleanType PaintTransparentImage (Image * image, const MagickPixelPacket * target, const Quantum opacity)
References MagickFalse, and TransparentPaintImage().
ParseImageGeometry()
MagickExport int ParseImageGeometry (const char * geometry, ssize_t * x, ssize_t * y, size_t * width, size_t * height)
References DeprecateEvent, GetMagickModule, LogMagickEvent(), and ParseMetaGeometry().
ParseSizeGeometry()
MagickExport MagickStatusType ParseSizeGeometry (const Image * image, const char * geometry, RectangleInfo * region_info)
References DeprecateEvent, GetMagickModule, _RectangleInfo::height, LogMagickEvent(), ParseMetaGeometry(), SetGeometry(), _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
PopImageList()
MagickExport Image * PopImageList (Image ** images)
References DeprecateEvent, GetMagickModule, LogMagickEvent(), and RemoveLastImageFromList().
PopImagePixels()
MagickExport size_t PopImagePixels (Image * image, const QuantumType quantum, unsigned char * destination)
References AcquireQuantumInfo(), DestroyQuantumInfo(), _Image::exception, and ExportQuantumPixels().
PostscriptGeometry()
MagickExport char * PostscriptGeometry (const char * page)
References DeprecateEvent, GetMagickModule, GetPageGeometry(), and LogMagickEvent().
PushImageList()
MagickExport unsigned int PushImageList (Image ** images, const Image * image, ExceptionInfo * exception)
References AppendImageToList(), CloneImageList(), DeprecateEvent, GetMagickModule, LogMagickEvent(), and MagickTrue.
PushImagePixels()
MagickExport size_t PushImagePixels (Image * image, const QuantumType quantum, const unsigned char * source)
References AcquireQuantumInfo(), DestroyQuantumInfo(), _Image::exception, and ImportQuantumPixels().
QuantizationError()
MagickExport unsigned int QuantizationError (Image * image)
References _Image::debug, DeprecateEvent, GetImageQuantizeError(), GetMagickModule, LogMagickEvent(), and MagickFalse.
RadialBlurImage()
MagickExport Image * RadialBlurImage (const Image * image, const double angle, ExceptionInfo * exception)
References RotationalBlurImage().
RadialBlurImageChannel()
MagickExport Image * RadialBlurImageChannel (const Image * image, const ChannelType channel, const double angle, ExceptionInfo * exception)
References RotationalBlurImageChannel().
RandomChannelThresholdImage()
MagickExport unsigned int RandomChannelThresholdImage (Image * image, const char * channel, const char * thresholds, ExceptionInfo * exception)
References AcquireImageColormap(), AcquireRandomInfo(), _Image::colormap, _Image::columns, _Image::debug, DeprecateEvent, DestroyRandomInfo(), _Image::filename, GetAuthenticIndexQueue(), GetAuthenticPixels(), GetMagickModule, GetPixelIntensity(), GetPseudoRandomValue(), LocaleCompare(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OptionError, QuantumRange, random_info, ResourceLimitError, _Image::rows, SetPixelIndex, SetPixelOpacity, SetPixelRGBO, _ExceptionInfo::signature, _Image::signature, SyncAuthenticPixels(), ThrowBinaryException, TraceEvent, and TransformEvent.
ReacquireMemory()
MagickExport void ReacquireMemory (void ** memory, const size_t size)
References AcquireMagickMemory(), DeprecateEvent, GetMagickModule, LogMagickEvent(), and RelinquishMagickMemory().
RecolorImage()
MagickExport Image * RecolorImage (const Image * image, const size_t order, const double * color_matrix, ExceptionInfo * exception)
References AcquireKernelInfo(), ColorMatrixImage(), DestroyKernelInfo(), KernelInfo::height, KernelInfo::values, and KernelInfo::width.
ReduceNoiseImage()
MagickExport Image * ReduceNoiseImage (const Image * image, const double radius, ExceptionInfo * exception)
References NonpeakStatistic, and StatisticImage().
RelinquishSemaphoreInfo()
MagickExport void RelinquishSemaphoreInfo (SemaphoreInfo * semaphore_info)
References UnlockSemaphoreInfo().
ResetImageAttributeIterator()
MagickExport void ResetImageAttributeIterator (const Image * image)
References ResetImagePropertyIterator().
SetCacheThreshold()
MagickExport void SetCacheThreshold (const size_t size)
References DeprecateEvent, GetMagickModule, LogMagickEvent(), MapResource, MemoryResource, and SetMagickResourceLimit().
SetCacheViewPixels()
MagickExport PixelPacket * SetCacheViewPixels (CacheView * cache_view, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows)
References GetCacheViewException(), and QueueCacheViewAuthenticPixels().
SetExceptionInfo()
MagickExport MagickBooleanType SetExceptionInfo (ExceptionInfo * exception, ExceptionType severity)
References ClearMagickException(), MagickTrue, and _ExceptionInfo::severity.
SetImage()
MagickExport void SetImage (Image * image, const Quantum opacity)
References _Image::background_color, CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DeprecateEvent, DirectClass, _Image::exception, GetAuthenticIndexQueue(), GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _PixelPacket::opacity, OpaqueOpacity, PseudoClass, QueueAuthenticPixels(), _Image::rows, SetImageStorageClass(), SetPixelIndex, SetPixelRGBO, _Image::signature, _Image::storage_class, SyncAuthenticPixels(), and TraceEvent.
SetImageAttribute()
MagickExport MagickBooleanType SetImageAttribute (Image * image, const char * key, const char * value)
References DeprecateEvent, GetMagickModule, LogMagickEvent(), and SetImageProperty().
SetImageList()
MagickExport unsigned int SetImageList (Image ** images, const Image * image, const ssize_t offset, ExceptionInfo * exception)
References CloneImageList(), DeprecateEvent, GetMagickModule, GetNextImageInList(), GetPreviousImageInList(), InsertImageInList(), LogMagickEvent(), MagickFalse, and MagickTrue.
SetImagePixels()
MagickExport PixelPacket * SetImagePixels (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows)
References _Image::exception, and QueueAuthenticPixels().
SetMagickRegistry()
MagickExport ssize_t SetMagickRegistry (const RegistryType type, const void * blob, const size_t magick_unusedlength, ExceptionInfo * exception)
References FormatLocaleString(), magick_unreferenced, MagickFalse, MaxTextExtent, and SetImageRegistry().
SetMonitorHandler()
MagickExport MonitorHandler SetMonitorHandler (MonitorHandler handler)
References monitor_handler.
ShiftImageList()
MagickExport Image * ShiftImageList (Image ** images)
References DeprecateEvent, GetMagickModule, LogMagickEvent(), and RemoveFirstImageFromList().
SizeBlob()
MagickExport MagickOffsetType SizeBlob (Image * image)
References _Image::debug, DeprecateEvent, GetBlobSize(), GetMagickModule, LogMagickEvent(), and MagickFalse.
SpliceImageList()
MagickExport Image * SpliceImageList (Image * images, const ssize_t offset, const size_t length, const Image * splices, ExceptionInfo * exception)
References CloneImageList(), _Image::debug, DeprecateEvent, GetMagickModule, GetNextImageInList(), GetPreviousImageInList(), LogMagickEvent(), MagickFalse, and SpliceImageIntoList().
sRGBCompandor()
MagickExport MagickRealType sRGBCompandor (const MagickRealType pixel)
References QuantumRange, and QuantumScale.
Strip()
MagickExport void Strip (char * message)
References DeprecateEvent, GetMagickModule, and LogMagickEvent().
SyncCacheView()
MagickExport MagickBooleanType SyncCacheView (CacheView * cache_view)
References GetCacheViewException(), and SyncCacheViewAuthenticPixels().
SyncCacheViewPixels()
MagickExport MagickBooleanType SyncCacheViewPixels (CacheView * cache_view)
References GetCacheViewException(), and SyncCacheViewAuthenticPixels().
SyncImagePixels()
MagickExport MagickBooleanType SyncImagePixels (Image * image)
References _Image::exception, and SyncAuthenticPixels().
SystemCommand()
MagickExport int SystemCommand (const MagickBooleanType asynchronous, const MagickBooleanType verbose, const char * command, ExceptionInfo * exception)
References ExternalDelegateCommand().
TemporaryFilename()
MagickExport void TemporaryFilename (char * path)
References AcquireUniqueFilename(), DeprecateEvent, GetMagickModule, LogMagickEvent(), and RelinquishUniqueFileResource().
ThresholdImage()
MagickExport unsigned int ThresholdImage (Image * image, const double threshold)
References AcquireImageColormap(), _Image::colormap, _Image::columns, _Image::debug, DeprecateEvent, _Image::exception, _Image::filename, GetAuthenticIndexQueue(), GetAuthenticPixels(), GetMagickModule, GetPixelIntensity(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, ResourceLimitError, _Image::rows, SetPixelIndex, SetPixelRGBO, _Image::signature, SyncAuthenticPixels(), ThrowBinaryImageException, and TraceEvent.
ThresholdImageChannel()
MagickExport unsigned int ThresholdImageChannel (Image * image, const char * threshold)
References AcquireImageColormap(), _MagickPixelPacket::blue, _PixelPacket::blue, _Image::colormap, _Image::columns, _Image::debug, DirectClass, _Image::exception, _Image::filename, GetAuthenticIndexQueue(), GetAuthenticPixels(), GetImageDynamicThreshold(), GetMagickModule, GetMagickPixelPacket(), GetPixelIntensity(), _MagickPixelPacket::green, _PixelPacket::green, IsMagickGray(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _MagickPixelPacket::opacity, OpaqueOpacity, ParseGeometry(), PercentValue, _GeometryInfo::psi, PsiValue, QuantumRange, _MagickPixelPacket::red, _PixelPacket::red, ResourceLimitError, _GeometryInfo::rho, _Image::rows, SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _GeometryInfo::sigma, SigmaValue, _Image::signature, SyncAuthenticPixels(), ThrowBinaryImageException, TraceEvent, _GeometryInfo::xi, and XiValue.
TransformColorspace()
MagickExport unsigned int TransformColorspace (Image * image, const ColorspaceType colorspace)
References _Image::debug, DeprecateEvent, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TransformImageColorspace().
TransformHSL()
MagickExport void TransformHSL (const Quantum red, const Quantum green, const Quantum blue, double * hue, double * saturation, double * lightness)
References MagickMax, MagickMin, and QuantumScale.
TranslateText()
MagickExport char * TranslateText (const ImageInfo * image_info, Image * image, const char * embed_text)
References _Image::debug, DeprecateEvent, GetMagickModule, InterpretImageProperties(), LogMagickEvent(), MagickCoreSignature, MagickFalse, and _Image::signature.
TransparentImage()
MagickExport MagickBooleanType TransparentImage (Image * image, const PixelPacket target, const Quantum opacity)
References _Image::columns, _Image::debug, DeprecateEvent, _Image::exception, _Image::filename, GetAuthenticPixels(), GetMagickModule, IsColorSimilar(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OpaqueAlphaChannel, _Image::rows, SetImageAlphaChannel(), SetImageProgress(), _Image::signature, SyncAuthenticPixels(), TraceEvent, and TransparentImageTag.
UnshiftImageList()
MagickExport unsigned int UnshiftImageList (Image ** images, const Image * image, ExceptionInfo * exception)
References CloneImageList(), DeprecateEvent, GetMagickModule, LogMagickEvent(), MagickTrue, and PrependImageToList().
ValidateColormapIndex()
MagickExport IndexPacket ValidateColormapIndex (Image * image, const size_t index)
References ConstrainColormapIndex(), _Image::debug, DeprecateEvent, GetMagickModule, LogMagickEvent(), and MagickFalse.
ZoomImage()
MagickExport Image * ZoomImage (const Image * image, const size_t columns, const size_t rows, ExceptionInfo * exception)
References _Image::blur, _Image::debug, _Image::filename, _Image::filter, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, ResizeImage(), _ExceptionInfo::signature, _Image::signature, and TraceEvent.
Variable Documentation
monitor_handler
MonitorHandler monitor_handler = (MonitorHandler) NULL static
Referenced by GetMonitorHandler(), MagickMonitor(), and SetMonitorHandler().