MagickCore: display.c File Reference
display.c File Reference
#include "magick/studio.h"
#include "magick/artifact.h"
#include "magick/attribute.h"
#include "magick/blob.h"
#include "magick/cache.h"
#include "magick/channel.h"
#include "magick/client.h"
#include "magick/color.h"
#include "magick/colorspace.h"
#include "magick/composite.h"
#include "magick/constitute.h"
#include "magick/decorate.h"
#include "magick/delegate.h"
#include "magick/display.h"
#include "magick/display-private.h"
#include "magick/distort.h"
#include "magick/draw.h"
#include "magick/effect.h"
#include "magick/enhance.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/fx.h"
#include "magick/geometry.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/log.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/montage.h"
#include "magick/nt-base-private.h"
#include "magick/option.h"
#include "magick/paint.h"
#include "magick/pixel.h"
#include "magick/pixel-private.h"
#include "magick/property.h"
#include "magick/quantum.h"
#include "magick/resize.h"
#include "magick/resource_.h"
#include "magick/shear.h"
#include "magick/segment.h"
#include "magick/statistic.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/timer-private.h"
#include "magick/transform.h"
#include "magick/threshold.h"
#include "magick/utility.h"
#include "magick/utility-private.h"
#include "magick/version.h"
#include "magick/visual-effects.h"
#include "magick/widget.h"
#include "magick/xwindow-private.h"
Functions
MagickExport MagickBooleanType DisplayImages (const ImageInfo *image_info, Image *image)
MagickExport MagickBooleanType RemoteDisplayCommand (const ImageInfo *image_info, const char *window, const char *filename, ExceptionInfo *exception)
Function Documentation
DisplayImages()
MagickExport MagickBooleanType DisplayImages (const ImageInfo * image_info, Image * image)
References _Image::debug, _Image::exception, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MissingDelegateError, _Image::signature, _ImageInfo::signature, ThrowMagickException(), and TraceEvent.
RemoteDisplayCommand()
MagickExport MagickBooleanType RemoteDisplayCommand (const ImageInfo * image_info, const char * window, const char * filename, ExceptionInfo * exception)
References _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MissingDelegateError, _ImageInfo::signature, ThrowMagickException(), and TraceEvent.