MagickCore: distort.h File Reference
distort.h File Reference
Enumerations
enum DistortImageMethod {
UndefinedDistortion , AffineDistortion , AffineProjectionDistortion , ScaleRotateTranslateDistortion ,
PerspectiveDistortion , PerspectiveProjectionDistortion , BilinearForwardDistortion , BilinearDistortion = BilinearForwardDistortion ,
BilinearReverseDistortion , PolynomialDistortion , ArcDistortion , PolarDistortion ,
DePolarDistortion , Cylinder2PlaneDistortion , Plane2CylinderDistortion , BarrelDistortion ,
BarrelInverseDistortion , ShepardsDistortion , ResizeDistortion , SentinelDistortion
}
enum SparseColorMethod {
UndefinedColorInterpolate = UndefinedDistortion , BarycentricColorInterpolate = AffineDistortion , BilinearColorInterpolate = BilinearReverseDistortion , PolynomialColorInterpolate = PolynomialDistortion ,
ShepardsColorInterpolate = ShepardsDistortion , VoronoiColorInterpolate = SentinelDistortion , InverseColorInterpolate , ManhattanColorInterpolate
}
Functions
MagickExport Image * AffineTransformImage (const Image *, const AffineMatrix *, ExceptionInfo *)
MagickExport Image * DistortImage (const Image *, const DistortImageMethod, const size_t, const double *, MagickBooleanType, ExceptionInfo *exception)
MagickExport Image * DistortResizeImage (const Image *, const size_t, const size_t, ExceptionInfo *)
MagickExport Image * RotateImage (const Image *, const double, ExceptionInfo *)
MagickExport Image * SparseColorImage (const Image *, const ChannelType, const SparseColorMethod, const size_t, const double *, ExceptionInfo *)
Enumeration Type Documentation
DistortImageMethod
enum DistortImageMethod
Enumerator
UndefinedDistortion
AffineDistortion
AffineProjectionDistortion
ScaleRotateTranslateDistortion
PerspectiveDistortion
PerspectiveProjectionDistortion
BilinearForwardDistortion
BilinearDistortion
BilinearReverseDistortion
PolynomialDistortion
ArcDistortion
PolarDistortion
DePolarDistortion
Cylinder2PlaneDistortion
Plane2CylinderDistortion
BarrelDistortion
BarrelInverseDistortion
ShepardsDistortion
ResizeDistortion
SentinelDistortion
SparseColorMethod
enum SparseColorMethod
Enumerator
UndefinedColorInterpolate
BarycentricColorInterpolate
BilinearColorInterpolate
PolynomialColorInterpolate
ShepardsColorInterpolate
VoronoiColorInterpolate
InverseColorInterpolate
ManhattanColorInterpolate
Function Documentation
AffineTransformImage()
MagickExport Image * AffineTransformImage (const Image * , const AffineMatrix * , ExceptionInfo *)
DistortImage()
MagickExport Image * DistortImage (const Image * , const DistortImageMethod, const size_t, const double * , MagickBooleanType , ExceptionInfo * exception)
DistortResizeImage()
MagickExport Image * DistortResizeImage (const Image * , const size_t, const size_t, ExceptionInfo *)
RotateImage()
MagickExport Image * RotateImage (const Image * , const double , ExceptionInfo *)
SparseColorImage()
MagickExport Image * SparseColorImage (const Image * image, const ChannelType, const SparseColorMethod, const size_t, const double * arguments, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), BarycentricColorInterpolate, BilinearColorInterpolate, _MagickPixelPacket::blue, BlueChannel, ClampPixel(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, FormatLocaleFile(), GenerateCoefficients(), GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetImageArtifact(), GetMagickModule, GetMagickPixelPacket(), _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, InheritException(), InverseColorInterpolate, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickMaximumValue, MagickTrue, ManhattanColorInterpolate, _MagickPixelPacket::opacity, OpacityChannel, _Image::progress_monitor, QuantumRange, _MagickPixelPacket::red, RedChannel, RelinquishMagickMemory(), _Image::rows, SentinelDistortion, SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacket(), SetPixelPacket(), ShepardsColorInterpolate, ShepardsDistortion, _ExceptionInfo::signature, _Image::signature, SparseColorTag, SyncCacheViewAuthenticPixels(), TraceEvent, and VoronoiColorInterpolate.