MagickCore: distribute-cache-private.h File Reference
distribute-cache-private.h File Reference
#include "magick/geometry.h"
#include "magick/exception.h"
Data Structures
struct _DistributeCacheInfo
Typedefs
typedef struct _DistributeCacheInfo DistributeCacheInfo
Functions
MagickPrivate const char * GetDistributeCacheHostname (const DistributeCacheInfo *)
MagickPrivate DistributeCacheInfo * AcquireDistributeCacheInfo (ExceptionInfo *)
MagickPrivate DistributeCacheInfo * DestroyDistributeCacheInfo (DistributeCacheInfo *)
MagickPrivate int GetDistributeCacheFile (const DistributeCacheInfo *)
MagickPrivate int GetDistributeCachePort (const DistributeCacheInfo *)
MagickPrivate MagickBooleanType OpenDistributePixelCache (DistributeCacheInfo *, Image *)
MagickPrivate MagickBooleanType RelinquishDistributePixelCache (DistributeCacheInfo *)
MagickPrivate MagickOffsetType ReadDistributePixelCacheIndexes (DistributeCacheInfo *, const RectangleInfo *, const MagickSizeType, unsigned char *)
MagickPrivate MagickOffsetType ReadDistributePixelCachePixels (DistributeCacheInfo *, const RectangleInfo *, const MagickSizeType, unsigned char *magick_restrict)
MagickPrivate MagickOffsetType WriteDistributePixelCacheIndexes (DistributeCacheInfo *, const RectangleInfo *, const MagickSizeType, const unsigned char *)
MagickPrivate MagickOffsetType WriteDistributePixelCachePixels (DistributeCacheInfo *, const RectangleInfo *, const MagickSizeType, const unsigned char *magick_restrict)
Typedef Documentation
DistributeCacheInfo
typedef struct _DistributeCacheInfo DistributeCacheInfo
Function Documentation
AcquireDistributeCacheInfo()
MagickPrivate DistributeCacheInfo * AcquireDistributeCacheInfo (ExceptionInfo *)
Referenced by OpenPixelCache().
DestroyDistributeCacheInfo()
MagickPrivate DistributeCacheInfo * DestroyDistributeCacheInfo (DistributeCacheInfo * server_info)
References CLOSE_SOCKET, _DistributeCacheInfo::file, MagickCoreSignature, RelinquishMagickMemory(), and _DistributeCacheInfo::signature.
Referenced by AcquireDistributeCacheInfo(), DestroyPixelCache(), and OpenPixelCache().
GetDistributeCacheFile()
MagickPrivate int GetDistributeCacheFile (const DistributeCacheInfo *)
Referenced by OpenPixelCache().
GetDistributeCacheHostname()
MagickPrivate const char * GetDistributeCacheHostname (const DistributeCacheInfo * server_info)
References _DistributeCacheInfo::hostname, MagickCoreSignature, and _DistributeCacheInfo::signature.
Referenced by OpenPixelCache().
GetDistributeCachePort()
MagickPrivate int GetDistributeCachePort (const DistributeCacheInfo * server_info)
References MagickCoreSignature, _DistributeCacheInfo::port, and _DistributeCacheInfo::signature.
Referenced by OpenPixelCache().
OpenDistributePixelCache()
MagickPrivate MagickBooleanType OpenDistributePixelCache (DistributeCacheInfo * , Image *)
Referenced by OpenPixelCache().
ReadDistributePixelCacheIndexes()
MagickPrivate MagickOffsetType ReadDistributePixelCacheIndexes (DistributeCacheInfo * , const RectangleInfo * , const MagickSizeType, unsigned char *)
Referenced by ReadPixelCacheIndexes().
ReadDistributePixelCachePixels()
MagickPrivate MagickOffsetType ReadDistributePixelCachePixels (DistributeCacheInfo * , const RectangleInfo * , const MagickSizeType, unsigned char * magick_restrict)
Referenced by ReadPixelCachePixels().
RelinquishDistributePixelCache()
MagickPrivate MagickBooleanType RelinquishDistributePixelCache (DistributeCacheInfo * server_info)
References dpc_read(), dpc_send(), _DistributeCacheInfo::file, MagickCoreSignature, MagickFalse, MagickTrue, MaxTextExtent, _DistributeCacheInfo::session_key, and _DistributeCacheInfo::signature.
Referenced by RelinquishPixelCachePixels().
WriteDistributePixelCacheIndexes()
MagickPrivate MagickOffsetType WriteDistributePixelCacheIndexes (DistributeCacheInfo * , const RectangleInfo * , const MagickSizeType, const unsigned char *)
Referenced by WritePixelCacheIndexes().
WriteDistributePixelCachePixels()
MagickPrivate MagickOffsetType WriteDistributePixelCachePixels (DistributeCacheInfo * , const RectangleInfo * , const MagickSizeType, const unsigned char * magick_restrict)
Referenced by WritePixelCachePixels().