MagickCore: distribute-cache.c File Reference
distribute-cache.c File Reference
#include "magick/studio.h"
#include "magick/cache.h"
#include "magick/cache-private.h"
#include "magick/distribute-cache.h"
#include "magick/distribute-cache-private.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/geometry.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/locale_.h"
#include "magick/memory_.h"
#include "magick/nt-base-private.h"
#include "magick/policy.h"
#include "magick/random_.h"
#include "magick/registry.h"
#include "magick/splay-tree.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/version.h"
#include "magick/version-private.h"
Macros
#define CLOSE_SOCKET(socket)
#define HANDLER_RETURN_TYPE void *
#define HANDLER_RETURN_VALUE (void *) NULL
#define SOCKET_TYPE int
#define LENGTH_TYPE size_t
#define send(file, buffer, length, flags) 0
#define recv(file, buffer, length, flags) 0
#define DPCHostname "127.0.0.1"
#define DPCPendingConnections 10
#define DPCPort 6668
#define DPCSessionKeyLength 8
#define MSG_NOSIGNAL 0
Functions
static MagickOffsetType dpc_read (int file, const MagickSizeType length, unsigned char *magick_restrict message)
static int ConnectPixelCacheServer (const char *hostname, const int port, size_t *session_key, ExceptionInfo *exception)
static char * GetHostname (int *port, ExceptionInfo *exception)
MagickPrivate DistributeCacheInfo * AcquireDistributeCacheInfo (ExceptionInfo *exception)
MagickPrivate DistributeCacheInfo * DestroyDistributeCacheInfo (DistributeCacheInfo *server_info)
static MagickBooleanType DestroyDistributeCache (SplayTreeInfo *registry, const size_t session_key)
static MagickOffsetType dpc_send (int file, const MagickSizeType length, const unsigned char *magick_restrict message)
static MagickBooleanType OpenDistributeCache (SplayTreeInfo *registry, int file, const size_t session_key, ExceptionInfo *exception)
static MagickBooleanType ReadDistributeCacheIndexes (SplayTreeInfo *registry, int file, const size_t session_key, ExceptionInfo *exception)
static MagickBooleanType ReadDistributeCachePixels (SplayTreeInfo *registry, int file, const size_t session_key, ExceptionInfo *exception)
static void * RelinquishImageRegistry (void *image)
static MagickBooleanType WriteDistributeCacheIndexes (SplayTreeInfo *registry, int file, const size_t session_key, ExceptionInfo *exception)
static MagickBooleanType WriteDistributeCachePixels (SplayTreeInfo *registry, int file, const size_t session_key, ExceptionInfo *exception)
static HANDLER_RETURN_TYPE DistributePixelCacheClient (void *socket)
MagickExport void DistributePixelCacheServer (const int port, ExceptionInfo *exception)
MagickPrivate int GetDistributeCacheFile (const DistributeCacheInfo *server_info)
MagickPrivate const char * GetDistributeCacheHostname (const DistributeCacheInfo *server_info)
MagickPrivate int GetDistributeCachePort (const DistributeCacheInfo *server_info)
MagickPrivate MagickBooleanType OpenDistributePixelCache (DistributeCacheInfo *server_info, Image *image)
MagickPrivate MagickOffsetType ReadDistributePixelCacheIndexes (DistributeCacheInfo *server_info, const RectangleInfo *region, const MagickSizeType length, unsigned char *indexes)
MagickPrivate MagickOffsetType ReadDistributePixelCachePixels (DistributeCacheInfo *server_info, const RectangleInfo *region, const MagickSizeType length, unsigned char *magick_restrict pixels)
MagickPrivate MagickBooleanType RelinquishDistributePixelCache (DistributeCacheInfo *server_info)
MagickPrivate MagickOffsetType WriteDistributePixelCacheIndexes (DistributeCacheInfo *server_info, const RectangleInfo *region, const MagickSizeType length, const unsigned char *indexes)
MagickPrivate MagickOffsetType WriteDistributePixelCachePixels (DistributeCacheInfo *server_info, const RectangleInfo *region, const MagickSizeType length, const unsigned char *magick_restrict pixels)
Macro Definition Documentation
CLOSE_SOCKET
#define CLOSE_SOCKET (socket)
DPCHostname
#define DPCHostname "127.0.0.1"
DPCPendingConnections
#define DPCPendingConnections 10
DPCPort
#define DPCPort 6668
DPCSessionKeyLength
#define DPCSessionKeyLength 8
HANDLER_RETURN_TYPE
#define HANDLER_RETURN_TYPE void *
HANDLER_RETURN_VALUE
#define HANDLER_RETURN_VALUE (void *) NULL
LENGTH_TYPE
#define LENGTH_TYPE size_t
MSG_NOSIGNAL
#define MSG_NOSIGNAL 0
recv
#define recv (file, buffer, length, flags) 0
send
#define send (file, buffer, length, flags) 0
SOCKET_TYPE
#define SOCKET_TYPE int
Function Documentation
AcquireDistributeCacheInfo()
MagickPrivate DistributeCacheInfo * AcquireDistributeCacheInfo (ExceptionInfo * exception)
References AcquireMagickMemory(), ConnectPixelCacheServer(), CopyMagickString(), _DistributeCacheInfo::debug, DestroyDistributeCacheInfo(), DestroyString(), _DistributeCacheInfo::file, GetHostname(), _DistributeCacheInfo::hostname, IsEventLogging(), MagickCoreSignature, MaxTextExtent, _DistributeCacheInfo::port, ResourceLimitFatalError, _DistributeCacheInfo::session_key, _DistributeCacheInfo::signature, and ThrowFatalException.
ConnectPixelCacheServer()
static int ConnectPixelCacheServer (const char * hostname, const int port, size_t * session_key, ExceptionInfo * exception) static
References AcquireStringInfo(), CacheError, CLOSE_SOCKET, DestroyString(), DestroyStringInfo(), FormatLocaleString(), GetMagickCoreSignature(), GetMagickModule, GetPolicyValue(), GetStringInfoDatum(), magick_unreferenced, MagickFalse, MagickTrue, MaxTextExtent, MissingDelegateError, recv, SOCKET_TYPE, and ThrowMagickException().
Referenced by AcquireDistributeCacheInfo().
DestroyDistributeCache()
static MagickBooleanType DestroyDistributeCache (SplayTreeInfo * registry, const size_t session_key) static
References DeleteNodeFromSplayTree(), and registry.
Referenced by DistributePixelCacheClient().
DestroyDistributeCacheInfo()
MagickPrivate DistributeCacheInfo * DestroyDistributeCacheInfo (DistributeCacheInfo * server_info)
References CLOSE_SOCKET, _DistributeCacheInfo::file, MagickCoreSignature, RelinquishMagickMemory(), and _DistributeCacheInfo::signature.
Referenced by AcquireDistributeCacheInfo(), DestroyPixelCache(), and OpenPixelCache().
DistributePixelCacheClient()
static HANDLER_RETURN_TYPE DistributePixelCacheClient (void * socket) static
References AcquireExceptionInfo(), AcquireRandomInfo(), CacheFatalError, CLOSE_SOCKET, CopyMagickString(), DestroyDistributeCache(), DestroyExceptionInfo(), DestroyRandomInfo(), DestroySplayTree(), DestroyString(), DestroyStringInfo(), dpc_read(), dpc_send(), DPCSessionKeyLength, GetMagickCoreSignature(), GetPolicyValue(), GetRandomKey(), GetStringInfoDatum(), HANDLER_RETURN_VALUE, MagickFalse, MaxTextExtent, NewSplayTree(), OpenDistributeCache(), random_info, ReadDistributeCacheIndexes(), ReadDistributeCachePixels(), registry, RelinquishImageRegistry(), SOCKET_TYPE, ThrowFatalException, WriteDistributeCacheIndexes(), and WriteDistributeCachePixels().
Referenced by DistributePixelCacheServer().
DistributePixelCacheServer()
MagickExport void DistributePixelCacheServer (const int port, ExceptionInfo * exception)
References CacheFatalError, CLOSE_SOCKET, DistributePixelCacheClient(), DPCPendingConnections, FormatLocaleString(), magick_unreferenced, MagickCoreSignature, MagickFalse, MaxTextExtent, MissingDelegateError, pthread_attr_init, pthread_create, _ExceptionInfo::signature, SOCKET_TYPE, and ThrowFatalException.
dpc_read()
static MagickOffsetType dpc_read (int file, const MagickSizeType length, unsigned char *magick_restrict message) inline static
References LENGTH_TYPE, MAGICK_SSIZE_MAX, magick_unreferenced, MagickMin, and recv.
Referenced by DistributePixelCacheClient(), OpenDistributeCache(), OpenDistributePixelCache(), ReadDistributeCacheIndexes(), ReadDistributeCachePixels(), ReadDistributePixelCacheIndexes(), ReadDistributePixelCachePixels(), RelinquishDistributePixelCache(), WriteDistributeCacheIndexes(), and WriteDistributeCachePixels().
dpc_send()
static MagickOffsetType dpc_send (int file, const MagickSizeType length, const unsigned char *magick_restrict message) inline static
References LENGTH_TYPE, MAGICK_SSIZE_MAX, magick_unreferenced, MagickMin, MSG_NOSIGNAL, and send.
Referenced by DistributePixelCacheClient(), OpenDistributePixelCache(), ReadDistributeCacheIndexes(), ReadDistributeCachePixels(), ReadDistributePixelCacheIndexes(), ReadDistributePixelCachePixels(), RelinquishDistributePixelCache(), WriteDistributePixelCacheIndexes(), and WriteDistributePixelCachePixels().
GetDistributeCacheFile()
MagickPrivate int GetDistributeCacheFile (const DistributeCacheInfo * server_info)
References _DistributeCacheInfo::file, MagickCoreSignature, and _DistributeCacheInfo::signature.
GetDistributeCacheHostname()
MagickPrivate const char * GetDistributeCacheHostname (const DistributeCacheInfo * server_info)
References _DistributeCacheInfo::hostname, MagickCoreSignature, and _DistributeCacheInfo::signature.
Referenced by OpenPixelCache().
GetDistributeCachePort()
MagickPrivate int GetDistributeCachePort (const DistributeCacheInfo * server_info)
References MagickCoreSignature, _DistributeCacheInfo::port, and _DistributeCacheInfo::signature.
Referenced by OpenPixelCache().
GetHostname()
static char * GetHostname (int * port, ExceptionInfo * exception) static
References AcquireString(), DestroyString(), DPCHostname, DPCPort, GetImageRegistry(), RelinquishMagickMemory(), StringRegistryType, StringToArgv(), StringToLong(), and SubstituteString().
Referenced by AcquireDistributeCacheInfo().
OpenDistributeCache()
static MagickBooleanType OpenDistributeCache (SplayTreeInfo * registry, int file, const size_t session_key, ExceptionInfo * exception) static
References AcquireImage(), AddValueToSplayTree(), _Image::channels, _Image::colorspace, _Image::columns, dpc_read(), MagickFalse, MaxTextExtent, registry, _Image::rows, _Image::storage_class, and SyncImagePixelCache().
Referenced by DistributePixelCacheClient().
OpenDistributePixelCache()
MagickPrivate MagickBooleanType OpenDistributePixelCache (DistributeCacheInfo * server_info, Image * image)
References _Image::channels, _Image::colorspace, _Image::columns, dpc_read(), dpc_send(), _DistributeCacheInfo::file, MagickCoreSignature, MagickFalse, MagickTrue, MaxTextExtent, _Image::rows, _DistributeCacheInfo::session_key, _DistributeCacheInfo::signature, _Image::signature, and _Image::storage_class.
ReadDistributeCacheIndexes()
static MagickBooleanType ReadDistributeCacheIndexes (SplayTreeInfo * registry, int file, const size_t session_key, ExceptionInfo * exception) static
References dpc_read(), dpc_send(), GetValueFromSplayTree(), GetVirtualIndexQueue(), GetVirtualPixels(), _RectangleInfo::height, MagickFalse, MagickTrue, MaxTextExtent, registry, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by DistributePixelCacheClient().
ReadDistributeCachePixels()
static MagickBooleanType ReadDistributeCachePixels (SplayTreeInfo * registry, int file, const size_t session_key, ExceptionInfo * exception) static
References dpc_read(), dpc_send(), GetValueFromSplayTree(), GetVirtualPixels(), _RectangleInfo::height, MagickFalse, MagickTrue, MaxTextExtent, registry, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by DistributePixelCacheClient().
ReadDistributePixelCacheIndexes()
MagickPrivate MagickOffsetType ReadDistributePixelCacheIndexes (DistributeCacheInfo * server_info, const RectangleInfo * region, const MagickSizeType length, unsigned char * indexes)
References dpc_read(), dpc_send(), _DistributeCacheInfo::file, _RectangleInfo::height, MAGICK_SSIZE_MAX, MagickCoreSignature, MaxTextExtent, _DistributeCacheInfo::session_key, _DistributeCacheInfo::signature, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
ReadDistributePixelCachePixels()
MagickPrivate MagickOffsetType ReadDistributePixelCachePixels (DistributeCacheInfo * server_info, const RectangleInfo * region, const MagickSizeType length, unsigned char *magick_restrict pixels)
References dpc_read(), dpc_send(), _DistributeCacheInfo::file, _RectangleInfo::height, MAGICK_SSIZE_MAX, MagickCoreSignature, MaxTextExtent, _DistributeCacheInfo::session_key, _DistributeCacheInfo::signature, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
RelinquishDistributePixelCache()
MagickPrivate MagickBooleanType RelinquishDistributePixelCache (DistributeCacheInfo * server_info)
References dpc_read(), dpc_send(), _DistributeCacheInfo::file, MagickCoreSignature, MagickFalse, MagickTrue, MaxTextExtent, _DistributeCacheInfo::session_key, and _DistributeCacheInfo::signature.
Referenced by RelinquishPixelCachePixels().
RelinquishImageRegistry()
static void * RelinquishImageRegistry (void * image) static
References DestroyImageList().
Referenced by DistributePixelCacheClient().
WriteDistributeCacheIndexes()
static MagickBooleanType WriteDistributeCacheIndexes (SplayTreeInfo * registry, int file, const size_t session_key, ExceptionInfo * exception) static
References dpc_read(), GetAuthenticIndexQueue(), GetAuthenticPixels(), GetValueFromSplayTree(), _RectangleInfo::height, MagickFalse, MaxTextExtent, registry, SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by DistributePixelCacheClient().
WriteDistributeCachePixels()
static MagickBooleanType WriteDistributeCachePixels (SplayTreeInfo * registry, int file, const size_t session_key, ExceptionInfo * exception) static
References dpc_read(), GetAuthenticPixels(), GetValueFromSplayTree(), _RectangleInfo::height, MagickFalse, MaxTextExtent, registry, SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by DistributePixelCacheClient().
WriteDistributePixelCacheIndexes()
MagickPrivate MagickOffsetType WriteDistributePixelCacheIndexes (DistributeCacheInfo * server_info, const RectangleInfo * region, const MagickSizeType length, const unsigned char * indexes)
References dpc_send(), _DistributeCacheInfo::file, _RectangleInfo::height, MAGICK_SSIZE_MAX, MagickCoreSignature, MaxTextExtent, _DistributeCacheInfo::session_key, _DistributeCacheInfo::signature, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
WriteDistributePixelCachePixels()
MagickPrivate MagickOffsetType WriteDistributePixelCachePixels (DistributeCacheInfo * server_info, const RectangleInfo * region, const MagickSizeType length, const unsigned char *magick_restrict pixels)
References dpc_send(), _DistributeCacheInfo::file, _RectangleInfo::height, MAGICK_SSIZE_MAX, MagickCoreSignature, MaxTextExtent, _DistributeCacheInfo::session_key, _DistributeCacheInfo::signature, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.