MagickCore: distort.c File Reference
distort.c File Reference
#include "magick/studio.h"
#include "magick/artifact.h"
#include "magick/cache.h"
#include "magick/cache-view.h"
#include "magick/channel.h"
#include "magick/color-private.h"
#include "magick/colorspace.h"
#include "magick/colorspace-private.h"
#include "magick/composite-private.h"
#include "magick/distort.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/gem.h"
#include "magick/hashmap.h"
#include "magick/image.h"
#include "magick/list.h"
#include "magick/matrix.h"
#include "magick/memory_.h"
#include "magick/monitor-private.h"
#include "magick/option.h"
#include "magick/pixel.h"
#include "magick/pixel-accessor.h"
#include "magick/pixel-private.h"
#include "magick/resample.h"
#include "magick/resample-private.h"
#include "magick/registry.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/shear.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/thread-private.h"
#include "magick/token.h"
#include "magick/transform.h"
Macros
#define DistortResizeImageTag "Distort/Image"
#define DistortImageTag "Distort/Image"
#define InitalBounds(p)
#define ExpandBounds(p)
#define ScaleFilter(F, A, B, C, D)
#define SparseColorTag "Distort/SparseColor"
Functions
static void AffineArgsToCoefficients (double *affine)
static void CoefficientsToAffineArgs (double *coeff)
static void InvertAffineCoefficients (const double *coeff, double *inverse)
static void InvertPerspectiveCoefficients (const double *coeff, double *inverse)
static size_t poly_number_terms (double order)
static double poly_basis_fn (ssize_t n, double x, double y)
static const char * poly_basis_str (ssize_t n)
static double poly_basis_dx (ssize_t n, double x, double y)
static double poly_basis_dy (ssize_t n, double x, double y)
MagickExport Image * AffineTransformImage (const Image *image, const AffineMatrix *affine_matrix, ExceptionInfo *exception)
static double MagickRound (double x)
static double * GenerateCoefficients (const Image *image, DistortImageMethod *method, const size_t number_arguments, const double *arguments, size_t number_values, ExceptionInfo *exception)
MagickExport Image * DistortResizeImage (const Image *image, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport Image * DistortImage (const Image *image, DistortImageMethod method, const size_t number_arguments, const double *arguments, MagickBooleanType bestfit, ExceptionInfo *exception)
MagickExport Image * RotateImage (const Image *image, const double degrees, ExceptionInfo *exception)
MagickExport Image * SparseColorImage (const Image *image, const ChannelType channel, const SparseColorMethod method, const size_t number_arguments, const double *arguments, ExceptionInfo *exception)
Macro Definition Documentation
DistortImageTag
#define DistortImageTag "Distort/Image"
DistortResizeImageTag
#define DistortResizeImageTag "Distort/Image"
ExpandBounds
#define ExpandBounds (p)
Value:
{ \
  /* printf("%lg,%lg -> %lg,%lg\n", s.x,s.y, d.x,d.y); */ \
  min.x = MagickMin(min.x,p.x); \
  max.x = MagickMax(max.x,p.x); \
  min.y = MagickMin(min.y,p.y); \
  max.y = MagickMax(max.y,p.y); \
}
InitalBounds
#define InitalBounds (p)
Value:
{ \
  /* printf("%lg,%lg -> %lg,%lg\n", s.x,s.y, d.x,d.y); */ \
  min.x = max.x = p.x; \
  min.y = max.y = p.y; \
}
ScaleFilter
#define ScaleFilter (F, A, B, C, D)
Value:
    ScaleResampleFilter( (F), \
      output_scaling*(A), output_scaling*(B), \
      output_scaling*(C), output_scaling*(D) )
SparseColorTag
#define SparseColorTag "Distort/SparseColor"
Function Documentation
AffineArgsToCoefficients()
static void AffineArgsToCoefficients (double * affine) inline static
Referenced by GenerateCoefficients().
AffineTransformImage()
MagickExport Image * AffineTransformImage (const Image * image, const AffineMatrix * affine_matrix, ExceptionInfo * exception)
References AffineProjectionDistortion, _Image::debug, DistortImage(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _AffineMatrix::rx, _AffineMatrix::ry, _ExceptionInfo::signature, _Image::signature, _AffineMatrix::sx, _AffineMatrix::sy, TraceEvent, _AffineMatrix::tx, and _AffineMatrix::ty.
Referenced by DeskewImage().
CoefficientsToAffineArgs()
static void CoefficientsToAffineArgs (double * coeff) inline static
Referenced by DistortImage().
DistortImage()
MagickExport Image * DistortImage (const Image * image, DistortImageMethod method, const size_t number_arguments, const double * arguments, MagickBooleanType bestfit, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), AcquireResampleFilterThreadSet(), AffineDistortion, ArcDistortion, _Image::background_color, BarrelDistortion, BarrelInverseDistortion, BilinearDistortion, BilinearForwardDistortion, BilinearReverseDistortion, CloneImage(), CMYKColorspace, CoefficientsToAffineArgs(), _Image::colorspace, _Image::columns, ConvertRGBToCMYK(), Cylinder2PlaneDistortion, _Image::debug, DePolarDistortion, DestroyCacheView(), DestroyImage(), DestroyResampleFilterThreadSet(), DirectClass, DistortImageTag, DistortResizeImage(), _Image::exception, ExpandBounds, _Image::filename, FormatLocaleFile(), FormatLocaleString(), GenerateCoefficients(), GetCacheViewAuthenticIndexQueue(), GetImageArtifact(), GetMagickModule, GetMagickPixelPacket(), GetMagickPrecision(), GetOpenMPThreadId(), _RectangleInfo::height, InheritException(), InitalBounds, InvertAffineCoefficients(), InvertPerspectiveCoefficients(), IsGrayColorspace(), IsPixelGray(), LogMagickEvent(), Magick2PI, magick_restrict, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickPI, MagickPI2, MagickPixelCompositeBlend(), MagickRound(), MagickTrue, _Image::matte, _Image::matte_color, MaxTextExtent, NoValue, _PixelPacket::opacity, OpaqueOpacity, OptionError, OptionWarning, _Image::page, ParseAbsoluteGeometry(), PerceptibleReciprocal(), PerspectiveDistortion, Plane2CylinderDistortion, PolarDistortion, poly_basis_dx(), poly_basis_dy(), poly_basis_fn(), poly_basis_str(), PolynomialDistortion, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), RelinquishMagickMemory(), ResamplePixelColor(), ResizeDistortion, ResourceLimitError, _Image::rows, ScaleFilter, SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacket(), SetPixelPacket(), ShepardsDistortion, _ExceptionInfo::signature, _Image::signature, sRGBColorspace, StringToDouble(), SyncCacheViewAuthenticPixels(), ThrowMagickException(), TraceEvent, UndefinedVirtualPixelMethod, _RectangleInfo::width, _PointInfo::x, _RectangleInfo::x, _PointInfo::y, and _RectangleInfo::y.
Referenced by AffineTransformImage(), DistortResizeImage(), and RotateImage().
DistortResizeImage()
MagickExport Image * DistortResizeImage (const Image * image, const size_t columns, const size_t rows, ExceptionInfo * exception)
References AffineDistortion, CloneImage(), _Image::columns, _Image::compose, CompositeImage(), CopyOpacityCompositeOp, CropImage(), DeactivateAlphaChannel, _Image::debug, DestroyImage(), DistortImage(), _Image::exception, _Image::filename, GetImageVirtualPixelMethod(), GetMagickModule, _RectangleInfo::height, InheritException(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OpaqueAlphaChannel, _Image::page, _Image::rows, SeparateImageChannel(), SetAlphaChannel, SetImageAlphaChannel(), SetImageVirtualPixelMethod(), _ExceptionInfo::signature, _Image::signature, TraceEvent, TransparentVirtualPixelMethod, TrueAlphaChannel, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by DistortImage().
GenerateCoefficients()
static double * GenerateCoefficients (const Image * image, DistortImageMethod * method, const size_t number_arguments, const double * arguments, size_t number_values, ExceptionInfo * exception) static
References AcquireMagickMatrix(), AcquireQuantumMemory(), AffineArgsToCoefficients(), AffineDistortion, AffineProjectionDistortion, ArcDistortion, BarrelDistortion, BarrelInverseDistortion, BilinearForwardDistortion, BilinearReverseDistortion, _Image::columns, CommandOptionToMnemonic(), Cylinder2PlaneDistortion, DegreesToRadians(), DePolarDistortion, GaussJordanElimination(), GetImageArtifact(), GetMagickModule, InvertAffineCoefficients(), InvertPerspectiveCoefficients(), LeastSquaresAddTerms(), Magick2PI, MagickDistortOptions, MagickEpsilon, MagickFalse, MagickMax, MagickMin, MagickPI, MagickPI2, MagickRound(), OptionError, _Image::page, PerspectiveDistortion, PerspectiveProjectionDistortion, Plane2CylinderDistortion, PolarDistortion, poly_basis_fn(), poly_number_terms(), PolynomialDistortion, RelinquishMagickMatrix(), RelinquishMagickMemory(), ResourceLimitError, _Image::rows, ScaleRotateTranslateDistortion, ShepardsDistortion, StringToDouble(), ThrowMagickException(), _RectangleInfo::x, and _RectangleInfo::y.
Referenced by DistortImage(), and SparseColorImage().
InvertAffineCoefficients()
static void InvertAffineCoefficients (const double * coeff, double * inverse) static
References PerceptibleReciprocal().
Referenced by DistortImage(), and GenerateCoefficients().
InvertPerspectiveCoefficients()
static void InvertPerspectiveCoefficients (const double * coeff, double * inverse) static
References PerceptibleReciprocal().
Referenced by DistortImage(), and GenerateCoefficients().
MagickRound()
static double MagickRound (double x) inline static
Referenced by DistortImage(), and GenerateCoefficients().
poly_basis_dx()
static double poly_basis_dx (ssize_t n, double x, double y) static
Referenced by DistortImage(), and poly_basis_dy().
poly_basis_dy()
static double poly_basis_dy (ssize_t n, double x, double y) static
References poly_basis_dx().
Referenced by DistortImage().
poly_basis_fn()
static double poly_basis_fn (ssize_t n, double x, double y) static
Referenced by DistortImage(), and GenerateCoefficients().
poly_basis_str()
static const char * poly_basis_str (ssize_t n) static
Referenced by DistortImage().
poly_number_terms()
static size_t poly_number_terms (double order) static
References MagickEpsilon.
Referenced by GenerateCoefficients().
RotateImage()
MagickExport Image * RotateImage (const Image * image, const double degrees, ExceptionInfo * exception)
References BackgroundVirtualPixelMethod, CloneImage(), _Image::debug, DegreesToRadians(), DestroyImage(), DistortImage(), _Image::filename, GetMagickModule, IntegralRotateImage(), LogMagickEvent(), MagickCoreSignature, MagickEpsilon, MagickFalse, MagickTrue, ScaleRotateTranslateDistortion, SetImageVirtualPixelMethod(), _ExceptionInfo::signature, _Image::signature, TraceEvent, _PointInfo::x, and _PointInfo::y.
Referenced by AutoOrientImage(), PolaroidImage(), and PreviewImage().
SparseColorImage()
MagickExport Image * SparseColorImage (const Image * image, const ChannelType channel, const SparseColorMethod method, const size_t number_arguments, const double * arguments, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), BarycentricColorInterpolate, BilinearColorInterpolate, _MagickPixelPacket::blue, BlueChannel, ClampPixel(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, FormatLocaleFile(), GenerateCoefficients(), GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetImageArtifact(), GetMagickModule, GetMagickPixelPacket(), _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, InheritException(), InverseColorInterpolate, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickMaximumValue, MagickTrue, ManhattanColorInterpolate, _MagickPixelPacket::opacity, OpacityChannel, _Image::progress_monitor, QuantumRange, _MagickPixelPacket::red, RedChannel, RelinquishMagickMemory(), _Image::rows, SentinelDistortion, SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacket(), SetPixelPacket(), ShepardsColorInterpolate, ShepardsDistortion, _ExceptionInfo::signature, _Image::signature, SparseColorTag, SyncCacheViewAuthenticPixels(), TraceEvent, and VoronoiColorInterpolate.