MagickCore: draw.c File Reference
draw.c File Reference
#include "magick/studio.h"
#include "magick/annotate.h"
#include "magick/artifact.h"
#include "magick/blob.h"
#include "magick/cache.h"
#include "magick/cache-private.h"
#include "magick/cache-view.h"
#include "magick/channel.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colorspace.h"
#include "magick/colorspace-private.h"
#include "magick/composite.h"
#include "magick/composite-private.h"
#include "magick/constitute.h"
#include "magick/draw.h"
#include "magick/draw-private.h"
#include "magick/enhance.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/log.h"
#include "magick/memory-private.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/option.h"
#include "magick/paint.h"
#include "magick/pixel-accessor.h"
#include "magick/pixel-private.h"
#include "magick/property.h"
#include "magick/resample.h"
#include "magick/resample-private.h"
#include "magick/resource_.h"
#include "magick/splay-tree.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/thread-private.h"
#include "magick/token.h"
#include "magick/transform.h"
#include "magick/utility.h"
Data Structures
struct _EdgeInfo
struct _ElementInfo
struct _MVGInfo
struct _PolygonInfo
struct _PathInfo
Macros
#define BezierQuantum 200
#define PrimitiveExtentPad 2053.0
#define MaxBezierCoordinates 67108864
#define ThrowPointExpectedException(image, token)
#define DrawCompareEdge(p, q)
#define RenderImageTag "Render/Image"
#define MaxStrokePad (6*BezierQuantum+360)
#define CheckPathExtent(pad_p, pad_q)
Typedefs
typedef struct _EdgeInfo EdgeInfo
typedef struct _ElementInfo ElementInfo
typedef struct _MVGInfo MVGInfo
typedef struct _PolygonInfo PolygonInfo
typedef struct _PathInfo PathInfo
Enumerations
enum PathInfoCode {
MoveToCode , OpenCode , GhostlineCode , LineToCode ,
EndCode
}
Functions
static Image * DrawClippingMask (Image *, const DrawInfo *, const char *, const char *, ExceptionInfo *)
static MagickBooleanType DrawStrokePolygon (Image *, const DrawInfo *, const PrimitiveInfo *)
static MagickBooleanType RenderMVGContent (Image *, const DrawInfo *, const size_t)
static MagickBooleanType TraceArc (MVGInfo *, const PointInfo, const PointInfo, const PointInfo)
static MagickBooleanType TraceArcPath (MVGInfo *, const PointInfo, const PointInfo, const PointInfo, const double, const MagickBooleanType, const MagickBooleanType)
static MagickBooleanType TraceBezier (MVGInfo *, const size_t)
static MagickBooleanType TraceCircle (MVGInfo *, const PointInfo, const PointInfo)
static MagickBooleanType TraceEllipse (MVGInfo *, const PointInfo, const PointInfo, const PointInfo)
static MagickBooleanType TraceLine (PrimitiveInfo *, const PointInfo, const PointInfo)
static MagickBooleanType TraceRectangle (PrimitiveInfo *, const PointInfo, const PointInfo)
static MagickBooleanType TraceRoundRectangle (MVGInfo *, const PointInfo, const PointInfo, PointInfo)
static MagickBooleanType TraceSquareLinecap (PrimitiveInfo *, const size_t, const double)
static PrimitiveInfo * TraceStrokePolygon (const DrawInfo *, const PrimitiveInfo *, ExceptionInfo *)
static ssize_t TracePath (Image *, MVGInfo *, const char *)
MagickExport DrawInfo * AcquireDrawInfo (void)
MagickExport DrawInfo * CloneDrawInfo (const ImageInfo *image_info, const DrawInfo *draw_info)
static PolygonInfo * DestroyPolygonInfo (PolygonInfo *polygon_info)
static int DrawCompareEdges (const void *p_edge, const void *q_edge)
static void LogPolygonInfo (const PolygonInfo *polygon_info)
static void ReversePoints (PointInfo *points, const size_t number_points)
static PolygonInfo * ConvertPathToPolygon (const PathInfo *path_info, ExceptionInfo *exception)
static void LogPathInfo (const PathInfo *path_info)
static PathInfo * ConvertPrimitiveToPath (const DrawInfo *magick_unused(draw_info), const PrimitiveInfo *primitive_info, ExceptionInfo *exception)
MagickExport DrawInfo * DestroyDrawInfo (DrawInfo *draw_info)
static SegmentInfo AffineEdge (const Image *image, const AffineMatrix *affine, const double y, const SegmentInfo *edge)
static AffineMatrix InverseAffineMatrix (const AffineMatrix *affine)
MagickExport MagickBooleanType DrawAffineImage (Image *image, const Image *source, const AffineMatrix *affine)
static MagickBooleanType DrawBoundingRectangles (Image *image, const DrawInfo *draw_info, const PolygonInfo *polygon_info)
MagickExport MagickBooleanType DrawClipPath (Image *image, const DrawInfo *draw_info, const char *id)
static Image * DrawCompositeMask (Image *image, const DrawInfo *draw_info, const char *id, const char *mask_path, ExceptionInfo *exception)
static MagickBooleanType DrawDashPolygon (const DrawInfo *draw_info, const PrimitiveInfo *primitive_info, Image *image)
static double GetStopColorOffset (const GradientInfo *gradient, const ssize_t x, const ssize_t y)
MagickExport MagickBooleanType DrawGradientImage (Image *image, const DrawInfo *draw_info)
static MagickBooleanType CheckPrimitiveExtent (MVGInfo *mvg_info, const double pad)
static double GetDrawValue (const char *magick_restrict string, char **magick_restrict sentinal)
static int MVGMacroCompare (const void *target, const void *source)
static SplayTreeInfo * GetMVGMacros (const char *primitive)
static MagickBooleanType IsPoint (const char *point)
static MagickBooleanType TracePoint (PrimitiveInfo *primitive_info, const PointInfo point)
MagickExport MagickBooleanType DrawImage (Image *image, const DrawInfo *draw_info)
MagickExport MagickBooleanType DrawPatternPath (Image *image, const DrawInfo *draw_info, const char *name, Image **pattern)
static PolygonInfo ** DestroyPolygonThreadSet (PolygonInfo **polygon_info)
static PolygonInfo ** AcquirePolygonThreadSet (const DrawInfo *draw_info, const PrimitiveInfo *primitive_info, ExceptionInfo *exception)
static size_t DestroyEdge (PolygonInfo *polygon_info, const ssize_t edge)
static double GetOpacityPixel (PolygonInfo *polygon_info, const double mid, const MagickBooleanType fill, const FillRule fill_rule, const ssize_t x, const ssize_t y, double *stroke_opacity)
static MagickBooleanType DrawPolygonPrimitive (Image *image, const DrawInfo *draw_info, const PrimitiveInfo *primitive_info)
static void LogPrimitiveInfo (const PrimitiveInfo *primitive_info)
MagickExport MagickBooleanType DrawPrimitive (Image *image, const DrawInfo *draw_info, const PrimitiveInfo *primitive_info)
static MagickBooleanType DrawRoundLinecap (Image *image, const DrawInfo *draw_info, const PrimitiveInfo *primitive_info)
MagickExport void GetAffineMatrix (AffineMatrix *affine_matrix)
MagickExport void GetDrawInfo (const ImageInfo *image_info, DrawInfo *draw_info)
static double Permutate (const ssize_t n, const ssize_t k)
Macro Definition Documentation
BezierQuantum
#define BezierQuantum 200
CheckPathExtent
#define CheckPathExtent (pad_p, pad_q)
DrawCompareEdge
#define DrawCompareEdge (p, q)
Value:
{ \
  if (((p)-(q)) < 0.0) \
    return(-1); \
  if (((p)-(q)) > 0.0) \
    return(1); \
}
MaxBezierCoordinates
#define MaxBezierCoordinates 67108864
MaxStrokePad
#define MaxStrokePad (6*BezierQuantum+360)
PrimitiveExtentPad
#define PrimitiveExtentPad 2053.0
RenderImageTag
#define RenderImageTag "Render/Image"
ThrowPointExpectedException
#define ThrowPointExpectedException (image, token)
Value:
{ \
  (void) ThrowMagickException(&(image)->exception,GetMagickModule(),DrawError, \
    "NonconformingDrawingPrimitiveDefinition","`%s'",token); \
  status=MagickFalse; \
  break; \
}
Typedef Documentation
EdgeInfo
typedef struct _EdgeInfo EdgeInfo
ElementInfo
typedef struct _ElementInfo ElementInfo
MVGInfo
typedef struct _MVGInfo MVGInfo
PathInfo
typedef struct _PathInfo PathInfo
PolygonInfo
typedef struct _PolygonInfo PolygonInfo
Enumeration Type Documentation
PathInfoCode
enum PathInfoCode
Enumerator
MoveToCode
OpenCode
GhostlineCode
LineToCode
EndCode
Function Documentation
AcquireDrawInfo()
MagickExport DrawInfo * AcquireDrawInfo (void)
References AcquireCriticalMemory(), and GetDrawInfo().
Referenced by GradientImage().
AcquirePolygonThreadSet()
static PolygonInfo ** AcquirePolygonThreadSet (const DrawInfo * draw_info, const PrimitiveInfo * primitive_info, ExceptionInfo * exception) static
References AcquireMagickMemory(), AcquireQuantumMemory(), ConvertPathToPolygon(), ConvertPrimitiveToPath(), DestroyPolygonThreadSet(), _PolygonInfo::edges, GetMagickModule, GetMagickResourceLimit(), magick_restrict, _PolygonInfo::number_edges, _EdgeInfo::number_points, _EdgeInfo::points, RelinquishMagickMemory(), ResourceLimitError, ThreadResource, and ThrowMagickException().
Referenced by DrawPolygonPrimitive().
AffineEdge()
static SegmentInfo AffineEdge (const Image * image, const AffineMatrix * affine, const double y, const SegmentInfo * edge) static
References _Image::columns, MagickEpsilon, _Image::rows, _AffineMatrix::rx, _AffineMatrix::ry, _AffineMatrix::sx, _AffineMatrix::sy, _AffineMatrix::tx, _AffineMatrix::ty, _SegmentInfo::x1, _SegmentInfo::x2, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by DrawAffineImage().
CheckPrimitiveExtent()
static MagickBooleanType CheckPrimitiveExtent (MVGInfo * mvg_info, const double pad) static
References AcquireCriticalMemory(), CastDoubleToLong(), _MVGInfo::exception, _MVGInfo::extent, GetMagickModule, MagickFalse, MagickTrue, _MVGInfo::offset, _MVGInfo::primitive_info, PrimitiveExtentPad, RelinquishMagickMemory(), ResizeQuantumMemory(), ResourceLimitError, ThrowMagickException(), and UndefinedPrimitive.
Referenced by RenderMVGContent(), TraceBezier(), TraceEllipse(), TracePath(), and TraceRoundRectangle().
CloneDrawInfo()
MagickExport DrawInfo * CloneDrawInfo (const ImageInfo * image_info, const DrawInfo * draw_info)
References AcquireCriticalMemory(), AcquireQuantumMemory(), _DrawInfo::affine, _DrawInfo::align, _DrawInfo::border_color, _DrawInfo::bounds, _DrawInfo::clip_mask, _DrawInfo::clip_path, _DrawInfo::clip_units, _DrawInfo::clipping_mask, CloneImage(), CloneString(), _DrawInfo::compliance, _DrawInfo::compose, _DrawInfo::composite_mask, _DrawInfo::dash_offset, _DrawInfo::dash_pattern, _DrawInfo::debug, _DrawInfo::decorate, _DrawInfo::density, _DrawInfo::direction, _DrawInfo::element_reference, _DrawInfo::encoding, _Image::exception, _DrawInfo::family, _DrawInfo::fill, _DrawInfo::fill_opacity, _DrawInfo::fill_pattern, _DrawInfo::fill_rule, _DrawInfo::font, _DrawInfo::geometry, GetDrawInfo(), _DrawInfo::gradient, _DrawInfo::gravity, _DrawInfo::id, _DrawInfo::interline_spacing, _DrawInfo::interword_spacing, IsEventLogging(), _DrawInfo::kerning, _DrawInfo::linecap, _DrawInfo::linejoin, MagickEpsilon, MagickTrue, _DrawInfo::metrics, _DrawInfo::miterlimit, NewImageList(), _GradientInfo::number_stops, _DrawInfo::pointsize, _DrawInfo::primitive, _DrawInfo::render, ResourceLimitFatalError, _DrawInfo::server_name, _GradientInfo::stops, _DrawInfo::stretch, _DrawInfo::stroke, _DrawInfo::stroke_antialias, _DrawInfo::stroke_opacity, _DrawInfo::stroke_pattern, _DrawInfo::stroke_width, _DrawInfo::style, _DrawInfo::text, _DrawInfo::text_antialias, ThrowFatalException, _DrawInfo::tile, _DrawInfo::undercolor, _DrawInfo::viewbox, and _DrawInfo::weight.
Referenced by AnnotateImage(), DrawBoundingRectangles(), DrawClippingMask(), DrawCompositeMask(), DrawDashPolygon(), DrawPatternPath(), DrawPrimitive(), DrawStrokePolygon(), GetMultilineTypeMetrics(), GetTypeMetrics(), MontageImageList(), PolaroidImage(), RenderHoughLines(), RenderMVGContent(), RenderType(), and VignetteImage().
ConvertPathToPolygon()
static PolygonInfo * ConvertPathToPolygon (const PathInfo * path_info, ExceptionInfo * exception) static
References AcquireMagickMemory(), AcquireQuantumMemory(), _EdgeInfo::bounds, _PathInfo::code, DestroyPolygonInfo(), _EdgeInfo::direction, DrawCompareEdges(), _PolygonInfo::edges, EndCode, GetMagickModule, _EdgeInfo::ghostline, GhostlineCode, _EdgeInfo::highwater, IsEventLogging(), LogPolygonInfo(), MagickEpsilon, MagickFalse, MagickTrue, MoveToCode, _PolygonInfo::number_edges, _EdgeInfo::number_points, OpenCode, _PathInfo::point, _EdgeInfo::points, RelinquishMagickMemory(), ResizeQuantumMemory(), ResourceLimitError, ReversePoints(), _EdgeInfo::scanline, ThrowMagickException(), _PointInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by AcquirePolygonThreadSet().
ConvertPrimitiveToPath()
static PathInfo * ConvertPrimitiveToPath (const DrawInfo * magick_unuseddraw_info, const PrimitiveInfo * primitive_info, ExceptionInfo * exception) static
References AcquireQuantumMemory(), _PrimitiveInfo::closed_subpath, _PathInfo::code, ColorPrimitive, EndCode, GetMagickModule, GhostlineCode, ImagePrimitive, IsEventLogging(), LineToCode, LogPathInfo(), magick_unreferenced, MagickEpsilon, MagickFalse, MattePrimitive, MoveToCode, OpenCode, _PathInfo::point, _PrimitiveInfo::point, PointPrimitive, _PrimitiveInfo::primitive, ResizeQuantumMemory(), ResourceLimitError, TextPrimitive, ThrowMagickException(), UndefinedPrimitive, _PointInfo::x, and _PointInfo::y.
Referenced by AcquirePolygonThreadSet().
DestroyDrawInfo()
MagickExport DrawInfo * DestroyDrawInfo (DrawInfo * draw_info)
References _DrawInfo::clip_mask, _DrawInfo::clipping_mask, _DrawInfo::composite_mask, _DrawInfo::dash_pattern, _DrawInfo::debug, _DrawInfo::density, DestroyImage(), DestroyImageInfo(), DestroyString(), _DrawInfo::encoding, _DrawInfo::family, _DrawInfo::fill_pattern, _DrawInfo::font, _DrawInfo::geometry, GetMagickModule, _DrawInfo::gradient, _DrawInfo::id, _DrawInfo::image_info, LogMagickEvent(), MagickCoreSignature, MagickFalse, _DrawInfo::metrics, _DrawInfo::primitive, RelinquishMagickMemory(), _DrawInfo::server_name, _DrawInfo::signature, _GradientInfo::stops, _DrawInfo::stroke_pattern, _DrawInfo::text, _DrawInfo::tile, and TraceEvent.
Referenced by AnnotateImage(), DrawBoundingRectangles(), DrawClippingMask(), DrawCompositeMask(), DrawDashPolygon(), DrawPatternPath(), DrawPrimitive(), DrawStrokePolygon(), GetMultilineTypeMetrics(), GetTypeMetrics(), GradientImage(), MontageImageList(), PolaroidImage(), RenderHoughLines(), RenderMVGContent(), RenderType(), and VignetteImage().
DestroyEdge()
static size_t DestroyEdge (PolygonInfo * polygon_info, const ssize_t edge) static
References _PolygonInfo::edges, _PolygonInfo::number_edges, _EdgeInfo::points, and RelinquishMagickMemory().
Referenced by GetOpacityPixel().
DestroyPolygonInfo()
static PolygonInfo * DestroyPolygonInfo (PolygonInfo * polygon_info) static
References _PolygonInfo::edges, _PolygonInfo::number_edges, _EdgeInfo::points, and RelinquishMagickMemory().
Referenced by ConvertPathToPolygon(), and DestroyPolygonThreadSet().
DestroyPolygonThreadSet()
static PolygonInfo ** DestroyPolygonThreadSet (PolygonInfo ** polygon_info) static
References DestroyPolygonInfo(), GetMagickResourceLimit(), RelinquishMagickMemory(), and ThreadResource.
Referenced by AcquirePolygonThreadSet(), and DrawPolygonPrimitive().
DrawAffineImage()
MagickExport MagickBooleanType DrawAffineImage (Image * image, const Image * source, const AffineMatrix * affine)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AffineEdge(), CastDoubleToLong(), _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickPixelPacket(), InterpolateMagickPixelPacket(), InverseAffineMatrix(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickPixelCompositeOver(), MagickTrue, _MagickPixelPacket::opacity, _Image::rows, _AffineMatrix::rx, _AffineMatrix::ry, SetImageStorageClass(), SetMagickPixelPacket(), SetPixelPacket(), _Image::signature, _AffineMatrix::sx, _AffineMatrix::sy, SyncCacheViewAuthenticPixels(), TraceEvent, _AffineMatrix::tx, _AffineMatrix::ty, UndefinedInterpolatePixel, _PointInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by DrawPrimitive().
DrawBoundingRectangles()
static MagickBooleanType DrawBoundingRectangles (Image * image, const DrawInfo * draw_info, const PolygonInfo * polygon_info) static
References _DrawInfo::affine, _EdgeInfo::bounds, CloneDrawInfo(), _Image::columns, _DrawInfo::density, DestroyDrawInfo(), _EdgeInfo::direction, DrawPrimitive(), _PolygonInfo::edges, _Image::exception, ExpandAffine(), _DrawInfo::fill, MagickFalse, MagickTrue, _PrimitiveInfo::method, _PolygonInfo::number_edges, ParseGeometry(), _PrimitiveInfo::primitive, QueryColorDatabase(), RectanglePrimitive, ReplaceMethod, _GeometryInfo::rho, _Image::rows, _GeometryInfo::sigma, SigmaValue, _DrawInfo::stroke, _DrawInfo::stroke_width, TraceRectangle(), UndefinedPrimitive, _PointInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by DrawPolygonPrimitive().
DrawClipPath()
MagickExport MagickBooleanType DrawClipPath (Image * image, const DrawInfo * draw_info, const char * id)
References _DrawInfo::clip_mask, DestroyImage(), DrawClippingMask(), _Image::exception, GetImageArtifact(), MagickFalse, and SetImageClipMask().
Referenced by RenderMVGContent().
DrawClippingMask()
static Image * DrawClippingMask (Image * image, const DrawInfo * draw_info, const char * id, const char * clip_path, ExceptionInfo * exception) static
References AcquireImage(), AllCompliance, _Image::background_color, _DrawInfo::clip_mask, _DrawInfo::clip_path, CloneDrawInfo(), CloneString(), _Image::columns, _DrawInfo::compliance, _Image::debug, DestroyDrawInfo(), DestroyImage(), DestroyString(), DrawEvent, _Image::filename, _DrawInfo::fill, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, NegateImage(), _DrawInfo::opacity, _PixelPacket::opacity, OpaqueOpacity, _DrawInfo::primitive, QueryColorCompliance(), RenderMVGContent(), _Image::rows, SeparateImageChannel(), SetImageBackgroundColor(), SetImageClipMask(), SetImageExtent(), _Image::signature, _DrawInfo::stroke, _DrawInfo::stroke_width, SVGCompliance, TraceEvent, TransparentOpacity, and TrueAlphaChannel.
Referenced by DrawClipPath(), and RenderMVGContent().
DrawCompareEdges()
static int DrawCompareEdges (const void * p_edge, const void * q_edge) static
References DrawCompareEdge.
Referenced by ConvertPathToPolygon().
DrawCompositeMask()
static Image * DrawCompositeMask (Image * image, const DrawInfo * draw_info, const char * id, const char * mask_path, ExceptionInfo * exception) static
References AcquireImage(), AllCompliance, _Image::background_color, CloneDrawInfo(), CloneString(), _Image::columns, _Image::debug, DestroyDrawInfo(), DestroyImage(), DrawEvent, _Image::filename, _DrawInfo::fill, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, NegateImage(), _DrawInfo::opacity, _PixelPacket::opacity, OpaqueOpacity, _DrawInfo::primitive, QueryColorCompliance(), RenderMVGContent(), _Image::rows, SeparateImageChannel(), SetImageBackgroundColor(), SetImageExtent(), SetImageMask(), _Image::signature, _DrawInfo::stroke, _DrawInfo::stroke_width, TraceEvent, TransparentOpacity, and TrueAlphaChannel.
Referenced by RenderMVGContent().
DrawDashPolygon()
static MagickBooleanType DrawDashPolygon (const DrawInfo * draw_info, const PrimitiveInfo * primitive_info, Image * image) static
References AcquireQuantumMemory(), _DrawInfo::affine, CloneDrawInfo(), _PrimitiveInfo::coordinates, _DrawInfo::dash_offset, _DrawInfo::dash_pattern, _Image::debug, DestroyDrawInfo(), DrawEvent, DrawStrokePolygon(), _Image::exception, ExpandAffine(), GetMagickModule, LogMagickEvent(), MagickEpsilon, MagickFalse, MagickTrue, MaxBezierCoordinates, _DrawInfo::miterlimit, PerceptibleReciprocal(), _PrimitiveInfo::point, _PrimitiveInfo::primitive, RelinquishMagickMemory(), ResourceLimitError, ThrowMagickException(), UndefinedPrimitive, _PointInfo::x, and _PointInfo::y.
Referenced by DrawPrimitive().
DrawGradientImage()
MagickExport MagickBooleanType DrawGradientImage (Image * image, const DrawInfo * draw_info)
References AcquireAuthenticCacheView(), _GradientInfo::bounding_box, CastDoubleToLong(), _StopInfo::color, _Image::columns, _Image::debug, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickPixelPacket(), GetStopColorOffset(), _DrawInfo::gradient, _GradientInfo::gradient_vector, _RectangleInfo::height, LinearGradient, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickPixelCompositeBlend(), MagickTrue, _GradientInfo::number_stops, _StopInfo::offset, PadSpread, PerceptibleReciprocal(), RadialGradient, _GradientInfo::radius, ReflectSpread, RepeatSpread, SetMagickPixelPacket(), _Image::signature, _GradientInfo::spread, _GradientInfo::stops, TraceEvent, _GradientInfo::type, UndefinedSpread, _RectangleInfo::width, _PointInfo::x, _RectangleInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _RectangleInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by GradientImage().
DrawImage()
MagickExport MagickBooleanType DrawImage (Image * image, const DrawInfo * draw_info)
References RenderMVGContent().
Referenced by AnnotateImage(), RenderHoughLines(), and VignetteImage().
DrawPatternPath()
MagickExport MagickBooleanType DrawPatternPath (Image * image, const DrawInfo * draw_info, const char * name, Image ** pattern)
References AcquireImage(), AcquireImageInfo(), AcquireString(), CloneDrawInfo(), CloneString(), _Image::debug, DestroyDrawInfo(), DestroyImage(), DestroyImageInfo(), DrawEvent, _Image::exception, _Image::filename, _DrawInfo::fill_pattern, FormatLocaleString(), GetImageArtifact(), GetMagickModule, _DrawInfo::gradient, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickGradientOptions, MaxTextExtent, ParseCommandOption(), _DrawInfo::primitive, QueryColorDatabase(), RenderMVGContent(), SetImageBackgroundColor(), _Image::signature, _ImageInfo::size, _DrawInfo::stroke_pattern, TraceEvent, and _GradientInfo::type.
Referenced by RenderMVGContent().
DrawPolygonPrimitive()
static MagickBooleanType DrawPolygonPrimitive (Image * image, const DrawInfo * draw_info, const PrimitiveInfo * primitive_info) static
References AcquireAuthenticCacheView(), AcquirePolygonThreadSet(), _DrawInfo::affine, _EdgeInfo::bounds, CastDoubleToLong(), _Image::columns, _PrimitiveInfo::coordinates, _Image::debug, DestroyCacheView(), DestroyPolygonThreadSet(), DrawBoundingRectangles(), DrawEvent, _Image::exception, ExpandAffine(), _Image::filename, _DrawInfo::fill_rule, FillToBorderMethod, FloodfillMethod, GetCacheViewAuthenticPixels(), GetFillColor(), GetImageArtifact(), GetMagickModule, GetOpacityPixel(), GetOpenMPThreadId(), GetStrokeColor(), IsStringTrue(), LogMagickEvent(), magick_restrict, MagickCompositeOver(), MagickCoreSignature, MagickFalse, MagickTrue, _PrimitiveInfo::method, _PixelPacket::opacity, _PrimitiveInfo::point, QuantumRange, _Image::rows, _DrawInfo::signature, _Image::signature, _DrawInfo::stroke_antialias, _DrawInfo::stroke_width, SyncCacheViewAuthenticPixels(), TraceEvent, _PointInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by DrawPrimitive(), DrawRoundLinecap(), and DrawStrokePolygon().
DrawPrimitive()
MagickExport MagickBooleanType DrawPrimitive (Image * image, const DrawInfo * draw_info, const PrimitiveInfo * primitive_info)
References AcquireAuthenticCacheView(), AcquireImageInfo(), _DrawInfo::affine, AnnotateImage(), _MagickPixelPacket::blue, _PixelPacket::blue, _DrawInfo::border_color, CastDoubleToLong(), _DrawInfo::clipping_mask, CloneDrawInfo(), CloneString(), _PrimitiveInfo::closed_subpath, ColorPrimitive, _Image::colorspace, _Image::columns, _DrawInfo::compliance, _DrawInfo::compose, _DrawInfo::composite_mask, CompositeImage(), CopyMagickString(), CorruptImageError, _DrawInfo::dash_pattern, _Image::debug, DefaultChannels, DestroyCacheView(), DestroyDrawInfo(), DestroyImage(), DestroyImageInfo(), DestroyImageList(), DestroyString(), DrawAffineImage(), DrawDashPolygon(), DrawEvent, DrawPolygonPrimitive(), DrawStrokePolygon(), _Image::exception, ExpandAffine(), _ImageInfo::extract, _ImageInfo::filename, FileOpenError, _DrawInfo::fill, FillToBorderMethod, _Image::filter, FloodfillMethod, FloodfillPaintImage(), FormatLocaleString(), _DrawInfo::geometry, GetCacheViewAuthenticPixels(), GetFillColor(), GetMagickInfo(), GetMagickModule, GetOneCacheViewVirtualPixel(), GetOneVirtualMagickPixel(), GetPathAttributes(), _DrawInfo::gravity, _Image::gravity, _MagickPixelPacket::green, _PixelPacket::green, ImagePrimitive, _Image::interpolate, IsColorSimilar(), IsEventLogging(), IsGrayColorspace(), IsPixelGray(), _DrawInfo::linecap, _DrawInfo::linejoin, LocaleCompare(), LocaleNCompare(), LogMagickEvent(), LogPrimitiveInfo(), _ImageInfo::magick, magick_restrict, MagickCompositeOver(), MagickEpsilon, MagickFalse, MagickPathExtent, MagickTrue, _Image::matte, MattePrimitive, MaxTextExtent, _PrimitiveInfo::method, _DrawInfo::opacity, _PixelPacket::opacity, OpacityChannel, OpaqueAlphaChannel, OpaqueOpacity, OverCompositeOp, ParseGravityGeometry(), _PrimitiveInfo::point, PointMethod, PointPrimitive, _PrimitiveInfo::primitive, ReadImage(), ReadInlineImage(), _MagickPixelPacket::red, _PixelPacket::red, RemoveFirstImageFromList(), ReplaceMethod, ResetMethod, RoundCap, RoundJoin, _Image::rows, _AffineMatrix::rx, _AffineMatrix::ry, SetGeometry(), SetImageAlphaChannel(), SetImageClipMask(), SetImageColorspace(), SetImageInfo(), SetImageMask(), SetImageOpacity(), SetImageProgressMonitor(), SetPixelOpacity, _ImageInfo::size, SrcOverCompositeOp, sRGBColorspace, _DrawInfo::stroke, _DrawInfo::stroke_pattern, _DrawInfo::stroke_width, SVGCompliance, _AffineMatrix::sx, _AffineMatrix::sy, SyncCacheViewAuthenticPixels(), _DrawInfo::text, _PrimitiveInfo::text, TextPrimitive, ThrowMagickException(), TransformImage(), TransparentOpacity, _AffineMatrix::tx, _AffineMatrix::ty, UndefinedPrimitive, _PointInfo::x, _RectangleInfo::x, _PointInfo::y, and _RectangleInfo::y.
Referenced by DrawBoundingRectangles(), and RenderMVGContent().
DrawRoundLinecap()
static MagickBooleanType DrawRoundLinecap (Image * image, const DrawInfo * draw_info, const PrimitiveInfo * primitive_info) static
References _PrimitiveInfo::coordinates, DrawPolygonPrimitive(), MagickEpsilon, _PrimitiveInfo::point, _PrimitiveInfo::primitive, UndefinedPrimitive, _PointInfo::x, and _PointInfo::y.
Referenced by DrawStrokePolygon().
DrawStrokePolygon()
static MagickBooleanType DrawStrokePolygon (Image * image, const DrawInfo * draw_info, const PrimitiveInfo * primitive_info) static
References CloneDrawInfo(), CloneImage(), _PrimitiveInfo::closed_subpath, _PrimitiveInfo::coordinates, _Image::debug, DestroyDrawInfo(), DestroyImage(), DrawEvent, DrawPolygonPrimitive(), DrawRoundLinecap(), _Image::exception, _DrawInfo::fill, _DrawInfo::fill_pattern, _DrawInfo::fill_rule, GetMagickModule, _DrawInfo::linecap, LogMagickEvent(), MagickFalse, MagickTrue, NonZeroRule, _PixelPacket::opacity, _PrimitiveInfo::primitive, RelinquishMagickMemory(), RoundCap, _DrawInfo::stroke, _DrawInfo::stroke_pattern, _DrawInfo::stroke_width, TraceStrokePolygon(), TransparentOpacity, and UndefinedPrimitive.
Referenced by DrawDashPolygon(), and DrawPrimitive().
GetAffineMatrix()
MagickExport void GetAffineMatrix (AffineMatrix * affine_matrix)
References GetMagickModule, LogMagickEvent(), _AffineMatrix::sx, _AffineMatrix::sy, and TraceEvent.
Referenced by GetDrawInfo(), ParseAffineGeometry(), and RenderMVGContent().
GetDrawInfo()
MagickExport void GetDrawInfo (const ImageInfo * image_info, DrawInfo * draw_info)
References AcquireExceptionInfo(), AcquireString(), _DrawInfo::affine, _ImageInfo::antialias, _DrawInfo::border_color, _ImageInfo::border_color, ButtCap, _DrawInfo::clip_path, CloneImageInfo(), CloneString(), _DrawInfo::compose, _DrawInfo::debug, _DrawInfo::decorate, _DrawInfo::density, _ImageInfo::density, DestroyExceptionInfo(), _DrawInfo::direction, _DrawInfo::encoding, EvenOddRule, _DrawInfo::family, _DrawInfo::fill, _DrawInfo::fill_opacity, _DrawInfo::fill_rule, _DrawInfo::font, _ImageInfo::font, GetAffineMatrix(), GetDrawValue(), GetImageOption(), GetMagickModule, _DrawInfo::gravity, _DrawInfo::image_info, _DrawInfo::interline_spacing, _DrawInfo::interword_spacing, IsEventLogging(), _DrawInfo::kerning, _DrawInfo::linecap, _DrawInfo::linejoin, LogMagickEvent(), MagickCoreSignature, MagickDirectionOptions, MagickEpsilon, MagickFalse, MagickGravityOptions, MagickStyleOptions, MagickTrue, MagickWeightOptions, MiterJoin, _DrawInfo::miterlimit, NoDecoration, _DrawInfo::opacity, _PixelPacket::opacity, OpaqueOpacity, OverCompositeOp, ParseCommandOption(), _DrawInfo::pointsize, _ImageInfo::pointsize, QueryColorDatabase(), _DrawInfo::render, _DrawInfo::server_name, _ImageInfo::server_name, _DrawInfo::signature, StringToUnsignedLong(), _DrawInfo::stroke, _DrawInfo::stroke_antialias, _DrawInfo::stroke_opacity, _DrawInfo::stroke_width, _DrawInfo::style, _DrawInfo::text_antialias, TraceEvent, TransparentOpacity, UndefinedDirection, _DrawInfo::undercolor, and _DrawInfo::weight.
Referenced by AcquireDrawInfo(), and CloneDrawInfo().
GetDrawValue()
static double GetDrawValue (const char *magick_restrict string, char **magick_restrict sentinal) inline static
References InterpretLocaleValue(), and magick_restrict.
Referenced by GetDrawInfo(), IsPoint(), RenderMVGContent(), and TracePath().
GetMVGMacros()
static SplayTreeInfo * GetMVGMacros (const char * primitive) static
References AcquireString(), AddValueToSplayTree(), ConstantString(), CopyMagickString(), DestroyString(), GetNextToken(), LocaleCompare(), MagickPathExtent, MVGMacroCompare(), NewSplayTree(), and RelinquishMagickMemory().
Referenced by RenderMVGContent().
GetOpacityPixel()
static double GetOpacityPixel (PolygonInfo * polygon_info, const double mid, const MagickBooleanType fill, const FillRule fill_rule, const ssize_t x, const ssize_t y, double * stroke_opacity) static
References _EdgeInfo::bounds, DestroyEdge(), _EdgeInfo::direction, _PolygonInfo::edges, _EdgeInfo::ghostline, _EdgeInfo::highwater, MagickAbsoluteValue, MagickEpsilon, MagickFalse, MagickMax, NonZeroRule, _PolygonInfo::number_edges, _EdgeInfo::number_points, PerceptibleReciprocal(), _EdgeInfo::points, _EdgeInfo::scanline, _PointInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by DrawPolygonPrimitive().
GetStopColorOffset()
static double GetStopColorOffset (const GradientInfo * gradient, const ssize_t x, const ssize_t y) inline static
References _GradientInfo::angle, _GradientInfo::center, DegreesToRadians(), _GradientInfo::gradient_vector, LinearGradient, PerceptibleReciprocal(), RadialGradient, _GradientInfo::radii, RepeatSpread, _GradientInfo::spread, _GradientInfo::type, UndefinedGradient, _PointInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by DrawGradientImage().
InverseAffineMatrix()
static AffineMatrix InverseAffineMatrix (const AffineMatrix * affine) static
References PerceptibleReciprocal(), _AffineMatrix::rx, _AffineMatrix::ry, _AffineMatrix::sx, _AffineMatrix::sy, _AffineMatrix::tx, and _AffineMatrix::ty.
Referenced by DrawAffineImage().
IsPoint()
static MagickBooleanType IsPoint (const char * point) inline static
References GetDrawValue(), MagickEpsilon, MagickFalse, and MagickTrue.
Referenced by RenderMVGContent(), and TracePath().
LogPathInfo()
static void LogPathInfo (const PathInfo * path_info) static
References _PathInfo::code, DrawEvent, EndCode, GetMagickModule, GhostlineCode, LineToCode, LogMagickEvent(), MoveToCode, OpenCode, _PathInfo::point, _PointInfo::x, and _PointInfo::y.
Referenced by ConvertPrimitiveToPath().
LogPolygonInfo()
static void LogPolygonInfo (const PolygonInfo * polygon_info) static
References _EdgeInfo::bounds, _EdgeInfo::direction, DrawEvent, _PolygonInfo::edges, GetMagickModule, _EdgeInfo::ghostline, LogMagickEvent(), MagickFalse, _PolygonInfo::number_edges, _EdgeInfo::number_points, _EdgeInfo::points, _PointInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by ConvertPathToPolygon().
LogPrimitiveInfo()
static void LogPrimitiveInfo (const PrimitiveInfo * primitive_info) static
References CastDoubleToLong(), ColorPrimitive, DrawEvent, GetMagickModule, ImagePrimitive, LogMagickEvent(), MagickEpsilon, MattePrimitive, _PrimitiveInfo::method, _PrimitiveInfo::point, PointPrimitive, _PrimitiveInfo::primitive, TextPrimitive, UndefinedPrimitive, _PointInfo::x, and _PointInfo::y.
Referenced by DrawPrimitive().
MVGMacroCompare()
static int MVGMacroCompare (const void * target, const void * source) static
Referenced by GetMVGMacros().
Permutate()
static double Permutate (const ssize_t n, const ssize_t k) inline static
Referenced by TraceBezier().
RenderMVGContent()
static MagickBooleanType RenderMVGContent (Image * image, const DrawInfo * draw_info, const size_t depth)
References AcquireMagickMemory(), AcquireQuantumMemory(), AcquireString(), _DrawInfo::affine, _DrawInfo::align, ArcPrimitive, BezierPrimitive, BezierQuantum, _DrawInfo::bounds, CastDoubleToLong(), CastDoubleToUnsigned(), CheckPrimitiveExtent(), CirclePrimitive, ClampToQuantum(), _DrawInfo::clip_units, _DrawInfo::clipping_mask, CloneDrawInfo(), CloneString(), _PrimitiveInfo::closed_subpath, ColorPrimitive, _Image::columns, _DrawInfo::compliance, _DrawInfo::compose, _DrawInfo::composite_mask, ConcatenateString(), _PrimitiveInfo::coordinates, CopyMagickString(), _DrawInfo::dash_offset, _DrawInfo::dash_pattern, _Image::debug, _DrawInfo::decorate, DegreesToRadians(), DestroyDrawInfo(), DestroyImage(), DestroySplayTree(), DestroyString(), DirectClass, _DrawInfo::direction, DrawClipPath(), DrawClippingMask(), DrawCompositeMask(), DrawError, DrawEvent, DrawPatternPath(), DrawPrimitive(), EllipsePrimitive, _MVGInfo::exception, _Image::exception, ExpandAffine(), _MVGInfo::extent, _Image::filename, FileToString(), _DrawInfo::fill, _DrawInfo::fill_opacity, _DrawInfo::fill_rule, FloodfillMethod, FormatLocaleString(), GetAffineMatrix(), GetDrawValue(), GetImageArtifact(), GetMagickModule, GetMVGMacros(), GetNextToken(), GetTypeMetrics(), GetValueFromSplayTree(), _DrawInfo::gradient, GradientImage(), _DrawInfo::gravity, _RectangleInfo::height, ImagePrimitive, _DrawInfo::interline_spacing, _DrawInfo::interword_spacing, IsPoint(), _DrawInfo::kerning, LinearGradient, _DrawInfo::linecap, _DrawInfo::linejoin, LinePrimitive, LocaleCompare(), LogMagickEvent(), MagickAlignOptions, MagickClipPathOptions, MagickComplianceOptions, MagickComposeOptions, MagickCoreSignature, MagickDecorateOptions, MagickDirectionOptions, MagickEpsilon, MagickFalse, MagickFillRuleOptions, MagickGravityOptions, MagickLineCapOptions, MagickLineJoinOptions, MagickMax, MagickMaxRecursionDepth, MagickMethodOptions, MagickMin, MagickPathExtent, MagickPI, MagickStretchOptions, MagickStyleOptions, MagickTrue, MagickWeightOptions, _Image::matte, MattePrimitive, MaxBezierCoordinates, MaxTextExtent, _PrimitiveInfo::method, _DrawInfo::miterlimit, ObjectBoundingBox, _MVGInfo::offset, _DrawInfo::opacity, _PixelPacket::opacity, OpaqueAlphaChannel, OpaqueOpacity, PadSpread, _Image::page, ParseCommandOption(), PathPrimitive, _MVGInfo::point, _PrimitiveInfo::point, PointPrimitive, _DrawInfo::pointsize, PolygonPrimitive, PolylinePrimitive, _DrawInfo::primitive, _PrimitiveInfo::primitive, _MVGInfo::primitive_info, PrimitiveExtentPad, QuantumRange, QueryColorDatabase(), RadialGradient, RectanglePrimitive, RelinquishMagickMemory(), _DrawInfo::render, RenderImageTag, RenderMVGContent(), ResizeQuantumMemory(), ResourceLimitError, ResourceLimitFatalError, RoundRectanglePrimitive, _Image::rows, _AffineMatrix::rx, _AffineMatrix::ry, SetImageAlphaChannel(), SetImageArtifact(), SetImageClipMask(), SetImageMask(), SetImageProgress(), SetImageStorageClass(), _DrawInfo::signature, _Image::signature, _DrawInfo::stretch, StringToLong(), StringToUnsignedLong(), _DrawInfo::stroke, _DrawInfo::stroke_antialias, _DrawInfo::stroke_opacity, _DrawInfo::stroke_width, _DrawInfo::style, SVGCompliance, _AffineMatrix::sx, _AffineMatrix::sy, _DrawInfo::text, _PrimitiveInfo::text, _DrawInfo::text_antialias, TextPrimitive, ThrowBinaryImageException, ThrowFatalException, ThrowMagickException(), ThrowPointExpectedException, TraceArc(), TraceBezier(), TraceCircle(), TraceEllipse(), TraceEvent, TraceLine(), TracePath(), TracePoint(), TraceRectangle(), TraceRoundRectangle(), TransparentOpacity, _AffineMatrix::tx, _AffineMatrix::ty, _GradientInfo::type, UndefinedPrimitive, _DrawInfo::viewbox, _DrawInfo::weight, _TypeMetric::width, _RectangleInfo::width, _PointInfo::x, _RectangleInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _RectangleInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by DrawClippingMask(), DrawCompositeMask(), DrawImage(), DrawPatternPath(), and RenderMVGContent().
ReversePoints()
static void ReversePoints (PointInfo * points, const size_t number_points) static
Referenced by ConvertPathToPolygon().
TraceArc()
static MagickBooleanType TraceArc (MVGInfo * mvg_info, const PointInfo start, const PointInfo end, const PointInfo degrees)
References TraceEllipse(), _PointInfo::x, and _PointInfo::y.
Referenced by RenderMVGContent().
TraceArcPath()
static MagickBooleanType TraceArcPath (MVGInfo * mvg_info, const PointInfo start, const PointInfo end, const PointInfo arc, const double angle, const MagickBooleanType large_arc, const MagickBooleanType sweep)
References CastDoubleToLong(), _PrimitiveInfo::closed_subpath, _PrimitiveInfo::coordinates, DegreesToRadians(), MagickEpsilon, MagickFalse, MagickPI, MagickTrue, _MVGInfo::offset, PerceptibleReciprocal(), _PrimitiveInfo::point, _PrimitiveInfo::primitive, _MVGInfo::primitive_info, TraceBezier(), TraceLine(), TracePoint(), _PointInfo::x, and _PointInfo::y.
Referenced by TracePath().
TraceBezier()
static MagickBooleanType TraceBezier (MVGInfo * mvg_info, const size_t number_coordinates)
References AcquireQuantumMemory(), BezierQuantum, CheckPrimitiveExtent(), _PrimitiveInfo::closed_subpath, _PrimitiveInfo::coordinates, _MVGInfo::exception, GetMagickModule, MAGICK_SSIZE_MAX, MagickFalse, MagickMin, MagickTrue, _MVGInfo::offset, Permutate(), _PrimitiveInfo::point, _PrimitiveInfo::primitive, _MVGInfo::primitive_info, RelinquishMagickMemory(), ResourceLimitError, ThrowMagickException(), TracePoint(), _PointInfo::x, and _PointInfo::y.
Referenced by RenderMVGContent(), TraceArcPath(), and TracePath().
TraceCircle()
static MagickBooleanType TraceCircle (MVGInfo * mvg_info, const PointInfo start, const PointInfo end)
References TraceEllipse(), _PointInfo::x, and _PointInfo::y.
Referenced by RenderMVGContent().
TraceEllipse()
static MagickBooleanType TraceEllipse (MVGInfo * mvg_info, const PointInfo center, const PointInfo radii, const PointInfo arc)
References CheckPrimitiveExtent(), _PrimitiveInfo::closed_subpath, _PrimitiveInfo::coordinates, DegreesToRadians(), MagickEpsilon, MagickFalse, MagickMax, MagickPI, MagickTrue, _MVGInfo::offset, PerceptibleReciprocal(), _PrimitiveInfo::point, _PrimitiveInfo::primitive, _MVGInfo::primitive_info, TracePoint(), _PointInfo::x, and _PointInfo::y.
Referenced by RenderMVGContent(), TraceArc(), TraceCircle(), and TraceRoundRectangle().
TraceLine()
static MagickBooleanType TraceLine (PrimitiveInfo * primitive_info, const PointInfo start, const PointInfo end)
References _PrimitiveInfo::closed_subpath, _PrimitiveInfo::coordinates, MagickEpsilon, MagickFalse, MagickTrue, PointPrimitive, _PrimitiveInfo::primitive, TracePoint(), _PointInfo::x, and _PointInfo::y.
Referenced by RenderMVGContent(), and TraceArcPath().
TracePath()
static ssize_t TracePath (Image * image, MVGInfo * mvg_info, const char * path) static
References CheckPrimitiveExtent(), _PrimitiveInfo::closed_subpath, _PrimitiveInfo::coordinates, FillToBorderMethod, GetDrawValue(), GetNextToken(), IsPoint(), MagickFalse, MagickTrue, MaxTextExtent, _PrimitiveInfo::method, _MVGInfo::offset, _PrimitiveInfo::primitive, _MVGInfo::primitive_info, PrimitiveExtentPad, StringToLong(), ThrowPointExpectedException, TraceArcPath(), TraceBezier(), TracePoint(), _PointInfo::x, and _PointInfo::y.
Referenced by RenderMVGContent().
TracePoint()
static MagickBooleanType TracePoint (PrimitiveInfo * primitive_info, const PointInfo point) inline static
References _PrimitiveInfo::closed_subpath, _PrimitiveInfo::coordinates, MagickFalse, MagickTrue, and _PrimitiveInfo::point.
Referenced by RenderMVGContent(), TraceArcPath(), TraceBezier(), TraceEllipse(), TraceLine(), TracePath(), TraceRectangle(), and TraceRoundRectangle().
TraceRectangle()
static MagickBooleanType TraceRectangle (PrimitiveInfo * primitive_info, const PointInfo start, const PointInfo end)
References _PrimitiveInfo::closed_subpath, _PrimitiveInfo::coordinates, MagickFalse, MagickTrue, _PrimitiveInfo::primitive, TracePoint(), _PointInfo::x, and _PointInfo::y.
Referenced by DrawBoundingRectangles(), and RenderMVGContent().
TraceRoundRectangle()
static MagickBooleanType TraceRoundRectangle (MVGInfo * mvg_info, const PointInfo start, const PointInfo end, PointInfo arc)
References CheckPrimitiveExtent(), _PrimitiveInfo::closed_subpath, _PrimitiveInfo::coordinates, MagickEpsilon, MagickFalse, MagickTrue, _MVGInfo::offset, _PrimitiveInfo::point, _PrimitiveInfo::primitive, _MVGInfo::primitive_info, PrimitiveExtentPad, TraceEllipse(), TracePoint(), _PointInfo::x, and _PointInfo::y.
Referenced by RenderMVGContent().
TraceSquareLinecap()
static MagickBooleanType TraceSquareLinecap (PrimitiveInfo * primitive_info, const size_t number_vertices, const double offset)
References MagickEpsilon, MagickTrue, _PrimitiveInfo::point, _PointInfo::x, and _PointInfo::y.
Referenced by TraceStrokePolygon().
TraceStrokePolygon()
static PrimitiveInfo * TraceStrokePolygon (const DrawInfo * draw_info, const PrimitiveInfo * primitive_info, ExceptionInfo * exception) static
References AcquireCriticalMemory(), AcquireQuantumMemory(), _DrawInfo::affine, BevelJoin, CastDoubleToLong(), CheckPathExtent, _PrimitiveInfo::coordinates, DegreesToRadians(), ExpandAffine(), GetMagickModule, _DrawInfo::linecap, _DrawInfo::linejoin, MagickEpsilon, MagickFalse, MagickPI, MagickTrue, MaxStrokePad, MiterJoin, _DrawInfo::miterlimit, PerceptibleReciprocal(), _PrimitiveInfo::point, _PrimitiveInfo::primitive, RelinquishMagickMemory(), ResourceLimitError, RoundCap, RoundJoin, SquareCap, _DrawInfo::stroke_width, ThrowMagickException(), TraceSquareLinecap(), UndefinedPrimitive, _PointInfo::x, and _PointInfo::y.
Referenced by DrawStrokePolygon().