MagickCore: draw.h File Reference
draw.h File Reference
#include "magick/geometry.h"
#include "magick/image.h"
#include "magick/pixel.h"
#include "magick/type.h"
#include "magick/color.h"
Data Structures
struct _PointInfo
struct _StopInfo
struct _GradientInfo
struct _ElementReference
struct _DrawInfo
struct _PrimitiveInfo
struct _TypeMetric
Typedefs
typedef struct _PointInfo PointInfo
typedef struct _StopInfo StopInfo
typedef struct _GradientInfo GradientInfo
typedef struct _ElementReference ElementReference
typedef struct _DrawInfo DrawInfo
typedef struct _PrimitiveInfo PrimitiveInfo
typedef struct _TypeMetric TypeMetric
Enumerations
enum AlignType { UndefinedAlign , LeftAlign , CenterAlign , RightAlign }
enum ClipPathUnits { UndefinedPathUnits , UserSpace , UserSpaceOnUse , ObjectBoundingBox }
enum DecorationType {
UndefinedDecoration , NoDecoration , UnderlineDecoration , OverlineDecoration ,
LineThroughDecoration
}
enum DirectionType { UndefinedDirection , RightToLeftDirection , LeftToRightDirection }
enum FillRule { UndefinedRule , EvenOddRule , NonZeroRule }
enum GradientType { UndefinedGradient , LinearGradient , RadialGradient }
enum LineCap { UndefinedCap , ButtCap , RoundCap , SquareCap }
enum LineJoin { UndefinedJoin , MiterJoin , RoundJoin , BevelJoin }
enum PaintMethod {
UndefinedMethod , PointMethod , ReplaceMethod , FloodfillMethod ,
FillToBorderMethod , ResetMethod
}
enum PrimitiveType {
UndefinedPrimitive , PointPrimitive , LinePrimitive , RectanglePrimitive ,
RoundRectanglePrimitive , ArcPrimitive , EllipsePrimitive , CirclePrimitive ,
PolylinePrimitive , PolygonPrimitive , BezierPrimitive , ColorPrimitive ,
MattePrimitive , TextPrimitive , ImagePrimitive , PathPrimitive
}
enum ReferenceType { UndefinedReference , GradientReference }
enum SpreadMethod { UndefinedSpread , PadSpread , ReflectSpread , RepeatSpread }
Functions
MagickExport DrawInfo * AcquireDrawInfo (void)
MagickExport DrawInfo * CloneDrawInfo (const ImageInfo *, const DrawInfo *)
MagickExport DrawInfo * DestroyDrawInfo (DrawInfo *)
MagickExport MagickBooleanType DrawAffineImage (Image *, const Image *, const AffineMatrix *)
MagickExport MagickBooleanType DrawClipPath (Image *, const DrawInfo *, const char *)
MagickExport MagickBooleanType DrawGradientImage (Image *, const DrawInfo *)
MagickExport MagickBooleanType DrawImage (Image *, const DrawInfo *)
MagickExport MagickBooleanType DrawPatternPath (Image *, const DrawInfo *, const char *, Image **)
MagickExport MagickBooleanType DrawPrimitive (Image *, const DrawInfo *, const PrimitiveInfo *)
MagickExport void GetAffineMatrix (AffineMatrix *)
MagickExport void GetDrawInfo (const ImageInfo *, DrawInfo *)
Typedef Documentation
DrawInfo
typedef struct _DrawInfo DrawInfo
ElementReference
typedef struct _ElementReference ElementReference
GradientInfo
typedef struct _GradientInfo GradientInfo
PointInfo
typedef struct _PointInfo PointInfo
PrimitiveInfo
typedef struct _PrimitiveInfo PrimitiveInfo
StopInfo
typedef struct _StopInfo StopInfo
TypeMetric
typedef struct _TypeMetric TypeMetric
Enumeration Type Documentation
AlignType
enum AlignType
Enumerator
UndefinedAlign
LeftAlign
CenterAlign
RightAlign
ClipPathUnits
enum ClipPathUnits
Enumerator
UndefinedPathUnits
UserSpace
UserSpaceOnUse
ObjectBoundingBox
DecorationType
enum DecorationType
Enumerator
UndefinedDecoration
NoDecoration
UnderlineDecoration
OverlineDecoration
LineThroughDecoration
DirectionType
enum DirectionType
Enumerator
UndefinedDirection
RightToLeftDirection
LeftToRightDirection
FillRule
enum FillRule
Enumerator
UndefinedRule
EvenOddRule
NonZeroRule
GradientType
enum GradientType
Enumerator
UndefinedGradient
LinearGradient
RadialGradient
LineCap
enum LineCap
Enumerator
UndefinedCap
ButtCap
RoundCap
SquareCap
LineJoin
enum LineJoin
Enumerator
UndefinedJoin
MiterJoin
RoundJoin
BevelJoin
PaintMethod
enum PaintMethod
Enumerator
UndefinedMethod
PointMethod
ReplaceMethod
FloodfillMethod
FillToBorderMethod
ResetMethod
PrimitiveType
enum PrimitiveType
Enumerator
UndefinedPrimitive
PointPrimitive
LinePrimitive
RectanglePrimitive
RoundRectanglePrimitive
ArcPrimitive
EllipsePrimitive
CirclePrimitive
PolylinePrimitive
PolygonPrimitive
BezierPrimitive
ColorPrimitive
MattePrimitive
TextPrimitive
ImagePrimitive
PathPrimitive
ReferenceType
enum ReferenceType
Enumerator
UndefinedReference
GradientReference
SpreadMethod
enum SpreadMethod
Enumerator
UndefinedSpread
PadSpread
ReflectSpread
RepeatSpread
Function Documentation
AcquireDrawInfo()
MagickExport DrawInfo * AcquireDrawInfo (void)
CloneDrawInfo()
MagickExport DrawInfo * CloneDrawInfo (const ImageInfo * , const DrawInfo *)
DestroyDrawInfo()
MagickExport DrawInfo * DestroyDrawInfo (DrawInfo * draw_info)
References _DrawInfo::clip_mask, _DrawInfo::clipping_mask, _DrawInfo::composite_mask, _DrawInfo::dash_pattern, _DrawInfo::debug, _DrawInfo::density, DestroyImage(), DestroyImageInfo(), DestroyString(), _DrawInfo::encoding, _DrawInfo::family, _DrawInfo::fill_pattern, _DrawInfo::font, _DrawInfo::geometry, GetMagickModule, _DrawInfo::gradient, _DrawInfo::id, _DrawInfo::image_info, LogMagickEvent(), MagickCoreSignature, MagickFalse, _DrawInfo::metrics, _DrawInfo::primitive, RelinquishMagickMemory(), _DrawInfo::server_name, _DrawInfo::signature, _GradientInfo::stops, _DrawInfo::stroke_pattern, _DrawInfo::text, _DrawInfo::tile, and TraceEvent.
Referenced by AnnotateImage(), DrawBoundingRectangles(), DrawClippingMask(), DrawCompositeMask(), DrawDashPolygon(), DrawPatternPath(), DrawPrimitive(), DrawStrokePolygon(), GetMultilineTypeMetrics(), GetTypeMetrics(), GradientImage(), MontageImageList(), PolaroidImage(), RenderHoughLines(), RenderMVGContent(), RenderType(), and VignetteImage().
DrawAffineImage()
MagickExport MagickBooleanType DrawAffineImage (Image * , const Image * , const AffineMatrix *)
DrawClipPath()
MagickExport MagickBooleanType DrawClipPath (Image * , const DrawInfo * , const char *)
DrawGradientImage()
MagickExport MagickBooleanType DrawGradientImage (Image * , const DrawInfo *)
DrawImage()
MagickExport MagickBooleanType DrawImage (Image * , const DrawInfo *)
DrawPatternPath()
MagickExport MagickBooleanType DrawPatternPath (Image * , const DrawInfo * , const char * , Image **)
DrawPrimitive()
MagickExport MagickBooleanType DrawPrimitive (Image * image, const DrawInfo * draw_info, const PrimitiveInfo * primitive_info)
References AcquireAuthenticCacheView(), AcquireImageInfo(), _DrawInfo::affine, AnnotateImage(), _MagickPixelPacket::blue, _PixelPacket::blue, _DrawInfo::border_color, CastDoubleToLong(), _DrawInfo::clipping_mask, CloneDrawInfo(), CloneString(), _PrimitiveInfo::closed_subpath, ColorPrimitive, _Image::colorspace, _Image::columns, _DrawInfo::compliance, _DrawInfo::compose, _DrawInfo::composite_mask, CompositeImage(), CopyMagickString(), CorruptImageError, _DrawInfo::dash_pattern, _Image::debug, DefaultChannels, DestroyCacheView(), DestroyDrawInfo(), DestroyImage(), DestroyImageInfo(), DestroyImageList(), DestroyString(), DrawAffineImage(), DrawDashPolygon(), DrawEvent, DrawPolygonPrimitive(), DrawStrokePolygon(), _Image::exception, ExpandAffine(), _ImageInfo::extract, _ImageInfo::filename, FileOpenError, _DrawInfo::fill, FillToBorderMethod, _Image::filter, FloodfillMethod, FloodfillPaintImage(), FormatLocaleString(), _DrawInfo::geometry, GetCacheViewAuthenticPixels(), GetFillColor(), GetMagickInfo(), GetMagickModule, GetOneCacheViewVirtualPixel(), GetOneVirtualMagickPixel(), GetPathAttributes(), _DrawInfo::gravity, _Image::gravity, _MagickPixelPacket::green, _PixelPacket::green, ImagePrimitive, _Image::interpolate, IsColorSimilar(), IsEventLogging(), IsGrayColorspace(), IsPixelGray(), _DrawInfo::linecap, _DrawInfo::linejoin, LocaleCompare(), LocaleNCompare(), LogMagickEvent(), LogPrimitiveInfo(), _ImageInfo::magick, magick_restrict, MagickCompositeOver(), MagickEpsilon, MagickFalse, MagickPathExtent, MagickTrue, _Image::matte, MattePrimitive, MaxTextExtent, _PrimitiveInfo::method, _DrawInfo::opacity, _PixelPacket::opacity, OpacityChannel, OpaqueAlphaChannel, OpaqueOpacity, OverCompositeOp, ParseGravityGeometry(), _PrimitiveInfo::point, PointMethod, PointPrimitive, _PrimitiveInfo::primitive, ReadImage(), ReadInlineImage(), _MagickPixelPacket::red, _PixelPacket::red, RemoveFirstImageFromList(), ReplaceMethod, ResetMethod, RoundCap, RoundJoin, _Image::rows, _AffineMatrix::rx, _AffineMatrix::ry, SetGeometry(), SetImageAlphaChannel(), SetImageClipMask(), SetImageColorspace(), SetImageInfo(), SetImageMask(), SetImageOpacity(), SetImageProgressMonitor(), SetPixelOpacity, _ImageInfo::size, SrcOverCompositeOp, sRGBColorspace, _DrawInfo::stroke, _DrawInfo::stroke_pattern, _DrawInfo::stroke_width, SVGCompliance, _AffineMatrix::sx, _AffineMatrix::sy, SyncCacheViewAuthenticPixels(), _DrawInfo::text, _PrimitiveInfo::text, TextPrimitive, ThrowMagickException(), TransformImage(), TransparentOpacity, _AffineMatrix::tx, _AffineMatrix::ty, UndefinedPrimitive, _PointInfo::x, _RectangleInfo::x, _PointInfo::y, and _RectangleInfo::y.
Referenced by DrawBoundingRectangles(), and RenderMVGContent().
GetAffineMatrix()
MagickExport void GetAffineMatrix (AffineMatrix *)
GetDrawInfo()
MagickExport void GetDrawInfo (const ImageInfo * image_info, DrawInfo * draw_info)
References AcquireExceptionInfo(), AcquireString(), _DrawInfo::affine, _ImageInfo::antialias, _DrawInfo::border_color, _ImageInfo::border_color, ButtCap, _DrawInfo::clip_path, CloneImageInfo(), CloneString(), _DrawInfo::compose, _DrawInfo::debug, _DrawInfo::decorate, _DrawInfo::density, _ImageInfo::density, DestroyExceptionInfo(), _DrawInfo::direction, _DrawInfo::encoding, EvenOddRule, _DrawInfo::family, _DrawInfo::fill, _DrawInfo::fill_opacity, _DrawInfo::fill_rule, _DrawInfo::font, _ImageInfo::font, GetAffineMatrix(), GetDrawValue(), GetImageOption(), GetMagickModule, _DrawInfo::gravity, _DrawInfo::image_info, _DrawInfo::interline_spacing, _DrawInfo::interword_spacing, IsEventLogging(), _DrawInfo::kerning, _DrawInfo::linecap, _DrawInfo::linejoin, LogMagickEvent(), MagickCoreSignature, MagickDirectionOptions, MagickEpsilon, MagickFalse, MagickGravityOptions, MagickStyleOptions, MagickTrue, MagickWeightOptions, MiterJoin, _DrawInfo::miterlimit, NoDecoration, _DrawInfo::opacity, _PixelPacket::opacity, OpaqueOpacity, OverCompositeOp, ParseCommandOption(), _DrawInfo::pointsize, _ImageInfo::pointsize, QueryColorDatabase(), _DrawInfo::render, _DrawInfo::server_name, _ImageInfo::server_name, _DrawInfo::signature, StringToUnsignedLong(), _DrawInfo::stroke, _DrawInfo::stroke_antialias, _DrawInfo::stroke_opacity, _DrawInfo::stroke_width, _DrawInfo::style, _DrawInfo::text_antialias, TraceEvent, TransparentOpacity, UndefinedDirection, _DrawInfo::undercolor, and _DrawInfo::weight.
Referenced by AcquireDrawInfo(), and CloneDrawInfo().