MagickCore: draw-private.h File Reference
draw-private.h File Reference
#include "magick/cache.h"
#include "magick/image.h"
#include "magick/memory_.h"
Functions
static MagickBooleanType GetFillColor (const DrawInfo *draw_info, const ssize_t x, const ssize_t y, PixelPacket *fill)
static MagickBooleanType GetStrokeColor (const DrawInfo *draw_info, const ssize_t x, const ssize_t y, PixelPacket *stroke)
Function Documentation
GetFillColor()
static MagickBooleanType GetFillColor (const DrawInfo * draw_info, const ssize_t x, const ssize_t y, PixelPacket * fill) inline static
References _Image::exception, _DrawInfo::fill, _DrawInfo::fill_opacity, _DrawInfo::fill_pattern, GetOneVirtualMethodPixel(), MagickEpsilon, MagickFalse, MagickTrue, _Image::matte, _PixelPacket::opacity, OpaqueOpacity, QuantumRange, QuantumScale, _Image::tile_offset, TileVirtualPixelMethod, TransparentOpacity, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by ColorFloodfillImage(), DrawPolygonPrimitive(), DrawPrimitive(), FloodfillPaintImage(), and RenderPostscript().
GetStrokeColor()
static MagickBooleanType GetStrokeColor (const DrawInfo * draw_info, const ssize_t x, const ssize_t y, PixelPacket * stroke) inline static
References _Image::exception, GetOneVirtualMethodPixel(), MagickEpsilon, MagickFalse, MagickTrue, _Image::matte, _PixelPacket::opacity, OpaqueOpacity, QuantumRange, QuantumScale, _DrawInfo::stroke, _DrawInfo::stroke_opacity, _DrawInfo::stroke_pattern, _Image::tile_offset, TileVirtualPixelMethod, TransparentOpacity, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by DrawPolygonPrimitive().