MagickCore: effect.c File Reference
effect.c File Reference
#include "magick/studio.h"
#include "magick/accelerate-private.h"
#include "magick/blob.h"
#include "magick/cache-view.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colorspace.h"
#include "magick/constitute.h"
#include "magick/decorate.h"
#include "magick/distort.h"
#include "magick/draw.h"
#include "magick/enhance.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/effect.h"
#include "magick/fx.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/log.h"
#include "magick/matrix.h"
#include "magick/memory_.h"
#include "magick/memory-private.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/montage.h"
#include "magick/morphology.h"
#include "magick/morphology-private.h"
#include "magick/opencl-private.h"
#include "magick/paint.h"
#include "magick/pixel-accessor.h"
#include "magick/pixel-private.h"
#include "magick/property.h"
#include "magick/quantize.h"
#include "magick/quantum.h"
#include "magick/random_.h"
#include "magick/random-private.h"
#include "magick/resample.h"
#include "magick/resample-private.h"
#include "magick/resize.h"
#include "magick/resource_.h"
#include "magick/segment.h"
#include "magick/shear.h"
#include "magick/signature-private.h"
#include "magick/statistic.h"
#include "magick/string_.h"
#include "magick/thread-private.h"
#include "magick/transform.h"
#include "magick/threshold.h"
Macros
#define AdaptiveBlurImageTag "Convolve/Image"
#define MagickSigma (fabs(sigma) < MagickEpsilon ? MagickEpsilon : sigma)
#define AdaptiveSharpenImageTag "Convolve/Image"
#define MagickSigma (fabs(sigma) < MagickEpsilon ? MagickEpsilon : sigma)
#define DespeckleImageTag "Despeckle/Image"
#define FilterImageTag "Filter/Image"
#define BlurImageTag "Blur/Image"
#define KuwaharaImageTag "Kiwahara/Image"
#define LocalContrastImageTag "LocalContrast/Image"
#define NumberTiles 9
#define PreviewImageTag "Preview/Image"
#define DefaultPreviewGeometry "204x204+10+10"
#define SelectiveBlurImageTag "SelectiveBlur/Image"
#define GetShadeIntensity(image, pixel) ClampPixel(GetPixelIntensity((image),(pixel)))
#define ShadeImageTag "Shade/Image"
#define SpreadImageTag "Spread/Image"
#define SharpenImageTag "Sharpen/Image"
Functions
MagickExport Image * AdaptiveBlurImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * AdaptiveBlurImageChannel (const Image *image, const ChannelType channel, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * AdaptiveSharpenImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * AdaptiveSharpenImageChannel (const Image *image, const ChannelType channel, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * BlurImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * BlurImageChannel (const Image *image, const ChannelType channel, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * ConvolveImage (const Image *image, const size_t order, const double *kernel, ExceptionInfo *exception)
MagickExport Image * ConvolveImageChannel (const Image *image, const ChannelType channel, const size_t order, const double *kernel, ExceptionInfo *exception)
static void Hull (const Image *image, const ssize_t x_offset, const ssize_t y_offset, const size_t columns, const size_t rows, const int polarity, Quantum *magick_restrict f, Quantum *magick_restrict g)
MagickExport Image * DespeckleImage (const Image *image, ExceptionInfo *exception)
MagickExport Image * EdgeImage (const Image *image, const double radius, ExceptionInfo *exception)
MagickExport Image * EmbossImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * FilterImage (const Image *image, const KernelInfo *kernel, ExceptionInfo *exception)
MagickExport Image * FilterImageChannel (const Image *image, const ChannelType channel, const KernelInfo *kernel, ExceptionInfo *exception)
MagickExport Image * GaussianBlurImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * GaussianBlurImageChannel (const Image *image, const ChannelType channel, const double radius, const double sigma, ExceptionInfo *exception)
static double * GetMotionBlurKernel (const size_t width, const double sigma)
MagickExport Image * MotionBlurImage (const Image *image, const double radius, const double sigma, const double angle, ExceptionInfo *exception)
MagickExport Image * MotionBlurImageChannel (const Image *image, const ChannelType channel, const double radius, const double sigma, const double angle, ExceptionInfo *exception)
MagickExport Image * KuwaharaImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * KuwaharaImageChannel (const Image *image, const ChannelType channel, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * LocalContrastImage (const Image *image, const double radius, const double strength, ExceptionInfo *exception)
MagickExport Image * PreviewImage (const Image *image, const PreviewType preview, ExceptionInfo *exception)
MagickExport Image * RotationalBlurImage (const Image *image, const double angle, ExceptionInfo *exception)
MagickExport Image * RotationalBlurImageChannel (const Image *image, const ChannelType channel, const double angle, ExceptionInfo *exception)
MagickExport Image * SelectiveBlurImage (const Image *image, const double radius, const double sigma, const double threshold, ExceptionInfo *exception)
MagickExport Image * SelectiveBlurImageChannel (const Image *image, const ChannelType channel, const double radius, const double sigma, const double threshold, ExceptionInfo *exception)
MagickExport Image * ShadeImage (const Image *image, const MagickBooleanType gray, const double azimuth, const double elevation, ExceptionInfo *exception)
MagickExport Image * SharpenImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * SharpenImageChannel (const Image *image, const ChannelType channel, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * SpreadImage (const Image *image, const double radius, ExceptionInfo *exception)
MagickExport Image * UnsharpMaskImage (const Image *image, const double radius, const double sigma, const double gain, const double threshold, ExceptionInfo *exception)
MagickExport Image * UnsharpMaskImageChannel (const Image *image, const ChannelType channel, const double radius, const double sigma, const double gain, const double threshold, ExceptionInfo *exception)
Macro Definition Documentation
AdaptiveBlurImageTag
#define AdaptiveBlurImageTag "Convolve/Image"
AdaptiveSharpenImageTag
#define AdaptiveSharpenImageTag "Convolve/Image"
BlurImageTag
#define BlurImageTag "Blur/Image"
DefaultPreviewGeometry
#define DefaultPreviewGeometry "204x204+10+10"
DespeckleImageTag
#define DespeckleImageTag "Despeckle/Image"
FilterImageTag
#define FilterImageTag "Filter/Image"
GetShadeIntensity
#define GetShadeIntensity (image, pixel) ClampPixel(GetPixelIntensity((image),(pixel)))
KuwaharaImageTag
#define KuwaharaImageTag "Kiwahara/Image"
LocalContrastImageTag
#define LocalContrastImageTag "LocalContrast/Image"
MagickSigma [1/2]
#define MagickSigma (fabs(sigma) < MagickEpsilon ? MagickEpsilon : sigma)
MagickSigma [2/2]
#define MagickSigma (fabs(sigma) < MagickEpsilon ? MagickEpsilon : sigma)
NumberTiles
#define NumberTiles 9
PreviewImageTag
#define PreviewImageTag "Preview/Image"
SelectiveBlurImageTag
#define SelectiveBlurImageTag "SelectiveBlur/Image"
ShadeImageTag
#define ShadeImageTag "Shade/Image"
SharpenImageTag
#define SharpenImageTag "Sharpen/Image"
SpreadImageTag
#define SpreadImageTag "Spread/Image"
Function Documentation
AdaptiveBlurImage()
MagickExport Image * AdaptiveBlurImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
References AdaptiveBlurImageChannel(), and DefaultChannels.
AdaptiveBlurImageChannel()
MagickExport Image * AdaptiveBlurImageChannel (const Image * image, const ChannelType channel, const double radius, const double sigma, ExceptionInfo * exception)
References AcquireAlignedMemory(), AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AdaptiveBlurImageTag, AutoLevelImage(), _DoublePixelPacket::blue, _MagickPixelPacket::blue, BlueChannel, BlurImage(), CastDoubleToLong(), ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, EdgeImage(), _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), GetOptimalKernelWidth2D(), GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetPixelRed, _DoublePixelPacket::green, _MagickPixelPacket::green, GreenChannel, _DoublePixelPacket::index, _MagickPixelPacket::index, IndexChannel, InheritException(), LogMagickEvent(), magick_restrict, MagickAssumeAligned, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickPI, MagickSigma, MagickTrue, _Image::matte, _DoublePixelPacket::opacity, _MagickPixelPacket::opacity, OpacityChannel, PerceptibleReciprocal(), _Image::progress_monitor, QuantumScale, QueueCacheViewAuthenticPixels(), _DoublePixelPacket::red, _MagickPixelPacket::red, RedChannel, RelinquishAlignedMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacketBias(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, and _Image::type.
Referenced by AdaptiveBlurImage().
AdaptiveSharpenImage()
MagickExport Image * AdaptiveSharpenImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
References AdaptiveSharpenImageChannel(), and DefaultChannels.
AdaptiveSharpenImageChannel()
MagickExport Image * AdaptiveSharpenImageChannel (const Image * image, const ChannelType channel, const double radius, const double sigma, ExceptionInfo * exception)
References AcquireAlignedMemory(), AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AdaptiveSharpenImageTag, AutoLevelImage(), _DoublePixelPacket::blue, _MagickPixelPacket::blue, BlueChannel, BlurImage(), CastDoubleToLong(), ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, EdgeImage(), _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), GetOptimalKernelWidth2D(), GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetPixelRed, _DoublePixelPacket::green, _MagickPixelPacket::green, GreenChannel, _DoublePixelPacket::index, _MagickPixelPacket::index, IndexChannel, InheritException(), LogMagickEvent(), magick_restrict, MagickAssumeAligned, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickPI, MagickSigma, MagickTrue, _Image::matte, _DoublePixelPacket::opacity, _MagickPixelPacket::opacity, OpacityChannel, PerceptibleReciprocal(), _Image::progress_monitor, QuantumScale, QueueCacheViewAuthenticPixels(), _DoublePixelPacket::red, _MagickPixelPacket::red, RedChannel, RelinquishAlignedMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacketBias(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, and _Image::type.
Referenced by AdaptiveSharpenImage().
BlurImage()
MagickExport Image * BlurImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
References BlurImageChannel(), and DefaultChannels.
Referenced by AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), CharcoalImage(), GetImageChannelPerceptualHash(), KuwaharaImageChannel(), PreviewImage(), and VignetteImage().
BlurImageChannel()
MagickExport Image * BlurImageChannel (const Image * image, const ChannelType channel, const double radius, const double sigma, ExceptionInfo * exception)
References AcquireKernelInfo(), ConvolveMorphology, _Image::debug, DestroyKernelInfo(), _Image::filename, FormatLocaleString(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MaxTextExtent, MorphologyImageChannel(), ResourceLimitError, _ExceptionInfo::signature, _Image::signature, ThrowImageException, and TraceEvent.
Referenced by BlurImage(), ShadowImage(), and UnsharpMaskImageChannel().
ConvolveImage()
MagickExport Image * ConvolveImage (const Image * image, const size_t order, const double * kernel, ExceptionInfo * exception)
References ConvolveImageChannel(), and DefaultChannels.
ConvolveImageChannel()
MagickExport Image * ConvolveImageChannel (const Image * image, const ChannelType channel, const size_t order, const double * kernel, ExceptionInfo * exception)
References AcquireAlignedMemory(), AcquireKernelInfo(), ConvolveMorphology, DestroyKernelInfo(), KernelInfo::height, MagickAssumeAligned, MagickCoreSignature, MorphologyImageChannel(), ResourceLimitError, KernelInfo::signature, ThrowImageException, KernelInfo::values, KernelInfo::width, KernelInfo::x, and KernelInfo::y.
Referenced by ConvolveImage().
DespeckleImage()
MagickExport Image * DespeckleImage (const Image * image, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AcquireVirtualMemory(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DespeckleImageTag, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlack, GetPixelBlue, GetPixelGreen, GetPixelOpacity, GetPixelRed, GetVirtualMemoryBlob(), Hull(), InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _Image::progress_monitor, RelinquishVirtualMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, and _Image::type.
Referenced by PreviewImage().
EdgeImage()
MagickExport Image * EdgeImage (const Image * image, const double radius, ExceptionInfo * exception)
References AcquireAlignedMemory(), AcquireKernelInfo(), ConvolveMorphology, _Image::debug, DefaultChannels, DestroyKernelInfo(), _Image::filename, GetMagickModule, GetOptimalKernelWidth1D(), KernelInfo::height, LogMagickEvent(), MagickAssumeAligned, MagickCoreSignature, MagickFalse, MorphologyImageChannel(), ResourceLimitError, _ExceptionInfo::signature, _Image::signature, KernelInfo::signature, ThrowImageException, TraceEvent, KernelInfo::values, KernelInfo::width, KernelInfo::x, and KernelInfo::y.
Referenced by AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), CharcoalImage(), PreviewImage(), and SketchImage().
EmbossImage()
MagickExport Image * EmbossImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
References AcquireAlignedMemory(), AcquireKernelInfo(), AllChannels, ConvolveMorphology, _Image::debug, DefaultChannels, DestroyKernelInfo(), EqualizeImageChannel(), _Image::filename, GetMagickModule, GetOptimalKernelWidth1D(), KernelInfo::height, LogMagickEvent(), MagickAssumeAligned, MagickCoreSignature, MagickFalse, MagickPI, MagickSigma, MorphologyImageChannel(), PerceptibleReciprocal(), ResourceLimitError, _ExceptionInfo::signature, _Image::signature, ThrowImageException, TraceEvent, KernelInfo::values, KernelInfo::width, KernelInfo::x, and KernelInfo::y.
FilterImage()
MagickExport Image * FilterImage (const Image * image, const KernelInfo * kernel, ExceptionInfo * exception)
References DefaultChannels, and FilterImageChannel().
FilterImageChannel()
MagickExport Image * FilterImageChannel (const Image * image, const ChannelType channel, const KernelInfo * kernel, ExceptionInfo * exception)
References AcquireAlignedMemory(), AcquireAuthenticCacheView(), AcquireString(), AcquireVirtualCacheView(), _DoublePixelPacket::blue, _MagickPixelPacket::blue, BlueChannel, ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, ConcatenateString(), _Image::debug, DestroyCacheView(), DestroyImage(), DestroyString(), DirectClass, _Image::exception, _Image::filename, FilterImageTag, FormatLocaleString(), GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _DoublePixelPacket::green, _MagickPixelPacket::green, GreenChannel, KernelInfo::height, _DoublePixelPacket::index, _MagickPixelPacket::index, IndexChannel, InheritException(), LogMagickEvent(), magick_restrict, MagickAssumeAligned, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, MaxTextExtent, _DoublePixelPacket::opacity, _MagickPixelPacket::opacity, OpacityChannel, OptionError, PerceptibleReciprocal(), _Image::progress_monitor, QuantumRange, QuantumScale, _DoublePixelPacket::red, _MagickPixelPacket::red, RedChannel, RelinquishAlignedMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacketBias(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, TransformEvent, _Image::type, KernelInfo::values, and KernelInfo::width.
Referenced by FilterImage().
GaussianBlurImage()
MagickExport Image * GaussianBlurImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
References DefaultChannels, and GaussianBlurImageChannel().
GaussianBlurImageChannel()
MagickExport Image * GaussianBlurImageChannel (const Image * image, const ChannelType channel, const double radius, const double sigma, ExceptionInfo * exception)
References AcquireKernelInfo(), ConvolveMorphology, _Image::debug, DestroyKernelInfo(), _Image::filename, FormatLocaleString(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MaxTextExtent, MorphologyImageChannel(), ResourceLimitError, _ExceptionInfo::signature, _Image::signature, ThrowImageException, and TraceEvent.
Referenced by GaussianBlurImage().
GetMotionBlurKernel()
static double * GetMotionBlurKernel (const size_t width, const double sigma) static
References AcquireAlignedMemory(), GetMagickModule, LogMagickEvent(), MagickAssumeAligned, MagickSigma, MagickSQ2PI, and TraceEvent.
Referenced by MotionBlurImageChannel().
Hull()
static void Hull (const Image * image, const ssize_t x_offset, const ssize_t y_offset, const size_t columns, const size_t rows, const int polarity, Quantum *magick_restrict f, Quantum *magick_restrict g) static
Referenced by DespeckleImage().
KuwaharaImage()
MagickExport Image * KuwaharaImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
References DefaultChannels, and KuwaharaImageChannel().
KuwaharaImageChannel()
MagickExport Image * KuwaharaImageChannel (const Image * image, const ChannelType channel, const double radius, const double sigma, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, BlurImage(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), GetPixelLuma(), _MagickPixelPacket::green, _RectangleInfo::height, InheritException(), InterpolateMagickPixelPacket(), KuwaharaImageTag, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickMaximumValue, MagickPixelLuma(), MagickTrue, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _MagickPixelPacket::red, _Image::rows, SetGeometry(), SetImageProgress(), SetImageStorageClass(), SetPixelPacket(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, UndefinedInterpolatePixel, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by KuwaharaImage().
LocalContrastImage()
MagickExport Image * LocalContrastImage (const Image * image, const double radius, const double strength, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AcquireVirtualMemory(), ClampToQuantum(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetMagickModule, GetOpenMPMaximumThreads(), GetOpenMPThreadId(), GetPixelBlue, GetPixelGreen, GetPixelLuma(), GetPixelRed, GetVirtualMemoryBlob(), InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickMax, MagickTrue, RelinquishVirtualMemory(), ResourceLimitError, _Image::rows, SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, and TraceEvent.
MotionBlurImage()
MagickExport Image * MotionBlurImage (const Image * image, const double radius, const double sigma, const double angle, ExceptionInfo * exception)
References DefaultChannels, and MotionBlurImageChannel().
Referenced by SketchImage().
MotionBlurImageChannel()
MagickExport Image * MotionBlurImageChannel (const Image * image, const ChannelType channel, const double radius, const double sigma, const double angle, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, _PixelPacket::blue, BlueChannel, BlurImageTag, CastDoubleToLong(), ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DegreesToRadians(), DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetMagickModule, GetMagickPixelPacket(), GetMotionBlurKernel(), GetOneCacheViewVirtualPixel(), GetOptimalKernelWidth1D(), GetPixelAlpha, GetPixelIndex, _MagickPixelPacket::green, _PixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _MagickPixelPacket::opacity, _PixelPacket::opacity, OpacityChannel, PerceptibleReciprocal(), _Image::progress_monitor, QuantumScale, _MagickPixelPacket::red, _PixelPacket::red, RedChannel, RelinquishAlignedMemory(), RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, _PointInfo::x, _OffsetInfo::x, _PointInfo::y, and _OffsetInfo::y.
Referenced by MotionBlurImage().
PreviewImage()
MagickExport Image * PreviewImage (const Image * image, const PreviewType preview, ExceptionInfo * exception)
References AcquireImageInfo(), AcquireUniqueFileResource(), AddNoisePreview, AppendImageToList(), BilevelImage(), BlurImage(), BlurPreview, BrightnessPreview, CharcoalDrawingPreview, CharcoalImage(), CloneImage(), CloneMontageInfo(), CloneString(), _QuantizeInfo::colorspace, _Image::columns, ContrastImage(), CopyMagickString(), _Image::debug, DefaultChannels, DefaultPreviewGeometry, DefaultTileFrame, DefaultTileLabel, DeleteImageProperty(), DespeckleImage(), DespecklePreview, DestroyImage(), DestroyImageInfo(), DestroyImageList(), DestroyMontageInfo(), _Image::directory, DullPreview, EdgeDetectPreview, EdgeImage(), _Image::filename, _ImageInfo::filename, _MontageInfo::filename, FormatLocaleString(), _MontageInfo::frame, GammaImageChannel(), GammaPreview, _MontageInfo::geometry, GetBlobSize(), GetMagickModule, GetQuantizeInfo(), GRAYColorspace, GrayscalePreview, _RectangleInfo::height, HuePreview, ImplodeImage(), ImplodePreview, JPEGPreview, LogMagickEvent(), _Image::magick, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte_color, MaxTextExtent, ModulateImage(), _Image::montage, MontageImages(), NewImageList(), NonpeakStatistic, _QuantizeInfo::number_colors, NumberTiles, OilPaintImage(), OilPaintPreview, ParseMetaGeometry(), PreviewImageTag, _ImageInfo::quality, QuantizeImage(), QuantizePreview, QuantumRange, QueryColorDatabase(), RaiseImage(), RaisePreview, ReadImage(), ReduceNoisePreview, RelinquishMagickMemory(), RelinquishUniqueFileResource(), ResourceLimitError, RollImage(), RollPreview, RotateImage(), RotatePreview, _Image::rows, SaturationPreview, SegmentImage(), SegmentPreview, SetGeometry(), SetImageProgress(), SetImageProgressMonitor(), SetImageProperty(), ShadeImage(), ShadePreview, _MontageInfo::shadow, SharpenImage(), SharpenPreview, ShearImage(), ShearPreview, _Image::signature, SolarizeImage(), SolarizePreview, SpiffPreview, SpreadImage(), SpreadPreview, sRGBColorspace, StatisticImage(), SwirlImage(), SwirlPreview, ThresholdPreview, ThrowImageException, ThumbnailImage(), _MontageInfo::tile, TraceEvent, WaveImage(), WavePreview, _RectangleInfo::width, WriteImage(), _RectangleInfo::x, and _RectangleInfo::y.
RotationalBlurImage()
MagickExport Image * RotationalBlurImage (const Image * image, const double angle, ExceptionInfo * exception)
References DefaultChannels, and RotationalBlurImageChannel().
Referenced by RadialBlurImage().
RotationalBlurImageChannel()
MagickExport Image * RotationalBlurImageChannel (const Image * image, const ChannelType channel, const double angle, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, _PixelPacket::blue, BlueChannel, BlurImageTag, ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DegreesToRadians(), DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetMagickModule, GetMagickPixelPacket(), GetOneCacheViewVirtualPixel(), GetPixelAlpha, _MagickPixelPacket::green, _PixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _MagickPixelPacket::opacity, _PixelPacket::opacity, OpacityChannel, PerceptibleReciprocal(), _Image::progress_monitor, QuantumScale, _MagickPixelPacket::red, _PixelPacket::red, RedChannel, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, _PointInfo::x, and _PointInfo::y.
Referenced by RadialBlurImageChannel(), and RotationalBlurImage().
SelectiveBlurImage()
MagickExport Image * SelectiveBlurImage (const Image * image, const double radius, const double sigma, const double threshold, ExceptionInfo * exception)
References DefaultChannels, and SelectiveBlurImageChannel().
SelectiveBlurImageChannel()
MagickExport Image * SelectiveBlurImageChannel (const Image * image, const ChannelType channel, const double radius, const double sigma, const double threshold, ExceptionInfo * exception)
References AcquireAlignedMemory(), AcquireAuthenticCacheView(), AcquireString(), AcquireVirtualCacheView(), _DoublePixelPacket::blue, _MagickPixelPacket::blue, BlueChannel, ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, ConcatenateString(), _Image::debug, DestroyCacheView(), DestroyImage(), DestroyString(), DirectClass, _Image::exception, _Image::filename, FormatLocaleString(), GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), GetOptimalKernelWidth1D(), GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetPixelRed, GRAYColorspace, _DoublePixelPacket::green, _MagickPixelPacket::green, GreenChannel, _DoublePixelPacket::index, _MagickPixelPacket::index, IndexChannel, InheritException(), LogMagickEvent(), magick_restrict, MagickAssumeAligned, MagickCoreSignature, MagickFalse, MagickPI, MagickSigma, MagickTrue, _Image::matte, MaxTextExtent, _DoublePixelPacket::opacity, _MagickPixelPacket::opacity, OpacityChannel, PerceptibleReciprocal(), _Image::progress_monitor, QuantumScale, _DoublePixelPacket::red, _MagickPixelPacket::red, RedChannel, RelinquishAlignedMemory(), ResourceLimitError, _Image::rows, SelectiveBlurImageTag, SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacketBias(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, TransformEvent, TransformImageColorspace(), and _Image::type.
Referenced by SelectiveBlurImage().
ShadeImage()
MagickExport Image * ShadeImage (const Image * image, const MagickBooleanType gray, const double azimuth, const double elevation, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), ClampToQuantum(), CloneImage(), _Image::columns, _Image::debug, DegreesToRadians(), DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelRed, GetShadeIntensity, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickTrue, _Image::progress_monitor, QuantumRange, QuantumScale, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelRed, ShadeImageTag, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, _PrimaryInfo::x, _PrimaryInfo::y, and _PrimaryInfo::z.
Referenced by PreviewImage().
SharpenImage()
MagickExport Image * SharpenImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
References DefaultChannels, and SharpenImageChannel().
Referenced by PreviewImage().
SharpenImageChannel()
MagickExport Image * SharpenImageChannel (const Image * image, const ChannelType channel, const double radius, const double sigma, ExceptionInfo * exception)
References AcquireAlignedMemory(), AcquireKernelInfo(), ConvolveMorphology, _Image::debug, DestroyKernelInfo(), _Image::filename, GetMagickModule, GetOptimalKernelWidth2D(), KernelInfo::height, LogMagickEvent(), MagickAssumeAligned, MagickCoreSignature, MagickFalse, MagickPI, MagickSigma, MorphologyImageChannel(), PerceptibleReciprocal(), ResourceLimitError, _ExceptionInfo::signature, _Image::signature, KernelInfo::signature, ThrowImageException, TraceEvent, KernelInfo::values, KernelInfo::width, KernelInfo::x, and KernelInfo::y.
Referenced by SharpenImage().
SpreadImage()
MagickExport Image * SpreadImage (const Image * image, const double radius, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireRandomInfoThreadSet(), AcquireVirtualCacheView(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DestroyRandomInfoThreadSet(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetMagickModule, GetMagickPixelPacket(), GetOpenMPThreadId(), GetOptimalKernelWidth1D(), GetPseudoRandomValue(), GetRandomSecretKey(), InheritException(), _Image::interpolate, InterpolateMagickPixelPacket(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), random_info, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelPacket(), _ExceptionInfo::signature, _Image::signature, SpreadImageTag, SyncCacheViewAuthenticPixels(), TraceEvent, _PointInfo::x, and _PointInfo::y.
Referenced by PreviewImage().
UnsharpMaskImage()
MagickExport Image * UnsharpMaskImage (const Image * image, const double radius, const double sigma, const double gain, const double threshold, ExceptionInfo * exception)
References DefaultChannels, and UnsharpMaskImageChannel().
UnsharpMaskImageChannel()
MagickExport Image * UnsharpMaskImageChannel (const Image * image, const ChannelType channel, const double radius, const double sigma, const double gain, const double threshold, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _DoublePixelPacket::blue, _MagickPixelPacket::blue, BlueChannel, BlurImageChannel(), ClampToQuantum(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _DoublePixelPacket::green, _MagickPixelPacket::green, GreenChannel, _DoublePixelPacket::index, _MagickPixelPacket::index, IndexChannel, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _DoublePixelPacket::opacity, _MagickPixelPacket::opacity, OpacityChannel, _Image::progress_monitor, QuantumRange, _DoublePixelPacket::red, _MagickPixelPacket::red, RedChannel, _Image::rows, SetImageProgress(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, SharpenImageTag, _Image::signature, SyncCacheViewAuthenticPixels(), SyncChannels, TraceEvent, and _Image::type.
Referenced by UnsharpMaskImage().