MagickCore: effect.h File Reference
effect.h File Reference
#include "magick/morphology.h"
Enumerations
enum PreviewType {
UndefinedPreview , RotatePreview , ShearPreview , RollPreview ,
HuePreview , SaturationPreview , BrightnessPreview , GammaPreview ,
SpiffPreview , DullPreview , GrayscalePreview , QuantizePreview ,
DespecklePreview , ReduceNoisePreview , AddNoisePreview , SharpenPreview ,
BlurPreview , ThresholdPreview , EdgeDetectPreview , SpreadPreview ,
SolarizePreview , ShadePreview , RaisePreview , SegmentPreview ,
SwirlPreview , ImplodePreview , WavePreview , OilPaintPreview ,
CharcoalDrawingPreview , JPEGPreview
}
Functions
MagickExport Image * AdaptiveBlurImage (const Image *, const double, const double, ExceptionInfo *)
MagickExport Image * AdaptiveBlurImageChannel (const Image *, const ChannelType, const double, const double, ExceptionInfo *)
MagickExport Image * AdaptiveSharpenImage (const Image *, const double, const double, ExceptionInfo *)
MagickExport Image * AdaptiveSharpenImageChannel (const Image *, const ChannelType, const double, const double, ExceptionInfo *)
MagickExport Image * BlurImage (const Image *, const double, const double, ExceptionInfo *)
MagickExport Image * BlurImageChannel (const Image *, const ChannelType, const double, const double, ExceptionInfo *)
MagickExport Image * ConvolveImage (const Image *, const size_t, const double *, ExceptionInfo *)
MagickExport Image * ConvolveImageChannel (const Image *, const ChannelType, const size_t, const double *, ExceptionInfo *)
MagickExport Image * DespeckleImage (const Image *, ExceptionInfo *)
MagickExport Image * EdgeImage (const Image *, const double, ExceptionInfo *)
MagickExport Image * EmbossImage (const Image *, const double, const double, ExceptionInfo *)
MagickExport Image * FilterImage (const Image *, const KernelInfo *, ExceptionInfo *)
MagickExport Image * FilterImageChannel (const Image *, const ChannelType, const KernelInfo *, ExceptionInfo *)
MagickExport Image * GaussianBlurImage (const Image *, const double, const double, ExceptionInfo *)
MagickExport Image * GaussianBlurImageChannel (const Image *, const ChannelType, const double, const double, ExceptionInfo *)
MagickExport Image * KuwaharaImage (const Image *, const double, const double, ExceptionInfo *)
MagickExport Image * KuwaharaImageChannel (const Image *, const ChannelType, const double, const double, ExceptionInfo *)
MagickExport Image * LocalContrastImage (const Image *, const double, const double, ExceptionInfo *)
MagickExport Image * MotionBlurImage (const Image *, const double, const double, const double, ExceptionInfo *)
MagickExport Image * MotionBlurImageChannel (const Image *, const ChannelType, const double, const double, const double, ExceptionInfo *)
MagickExport Image * PreviewImage (const Image *, const PreviewType, ExceptionInfo *)
MagickExport Image * RotationalBlurImage (const Image *, const double, ExceptionInfo *)
MagickExport Image * RotationalBlurImageChannel (const Image *, const ChannelType, const double, ExceptionInfo *)
MagickExport Image * SelectiveBlurImage (const Image *, const double, const double, const double, ExceptionInfo *)
MagickExport Image * SelectiveBlurImageChannel (const Image *, const ChannelType, const double, const double, const double, ExceptionInfo *)
MagickExport Image * ShadeImage (const Image *, const MagickBooleanType, const double, const double, ExceptionInfo *)
MagickExport Image * SharpenImage (const Image *, const double, const double, ExceptionInfo *)
MagickExport Image * SharpenImageChannel (const Image *, const ChannelType, const double, const double, ExceptionInfo *)
MagickExport Image * SpreadImage (const Image *, const double, ExceptionInfo *)
MagickExport Image * UnsharpMaskImage (const Image *, const double, const double, const double, const double, ExceptionInfo *)
MagickExport Image * UnsharpMaskImageChannel (const Image *, const ChannelType, const double, const double, const double, const double, ExceptionInfo *)
Enumeration Type Documentation
PreviewType
enum PreviewType
Enumerator
UndefinedPreview
RotatePreview
ShearPreview
RollPreview
HuePreview
SaturationPreview
BrightnessPreview
GammaPreview
SpiffPreview
DullPreview
GrayscalePreview
QuantizePreview
DespecklePreview
ReduceNoisePreview
AddNoisePreview
SharpenPreview
BlurPreview
ThresholdPreview
EdgeDetectPreview
SpreadPreview
SolarizePreview
ShadePreview
RaisePreview
SegmentPreview
SwirlPreview
ImplodePreview
WavePreview
OilPaintPreview
CharcoalDrawingPreview
JPEGPreview
Function Documentation
AdaptiveBlurImage()
MagickExport Image * AdaptiveBlurImage (const Image * , const double , const double , ExceptionInfo *)
AdaptiveBlurImageChannel()
MagickExport Image * AdaptiveBlurImageChannel (const Image * , const ChannelType, const double , const double , ExceptionInfo *)
AdaptiveSharpenImage()
MagickExport Image * AdaptiveSharpenImage (const Image * , const double , const double , ExceptionInfo *)
AdaptiveSharpenImageChannel()
MagickExport Image * AdaptiveSharpenImageChannel (const Image * , const ChannelType, const double , const double , ExceptionInfo *)
BlurImage()
MagickExport Image * BlurImage (const Image * , const double , const double , ExceptionInfo *)
BlurImageChannel()
MagickExport Image * BlurImageChannel (const Image * , const ChannelType, const double , const double , ExceptionInfo *)
ConvolveImage()
MagickExport Image * ConvolveImage (const Image * , const size_t, const double * , ExceptionInfo *)
ConvolveImageChannel()
MagickExport Image * ConvolveImageChannel (const Image * , const ChannelType, const size_t, const double * , ExceptionInfo *)
DespeckleImage()
MagickExport Image * DespeckleImage (const Image * , ExceptionInfo *)
EdgeImage()
MagickExport Image * EdgeImage (const Image * , const double , ExceptionInfo *)
EmbossImage()
MagickExport Image * EmbossImage (const Image * , const double , const double , ExceptionInfo *)
FilterImage()
MagickExport Image * FilterImage (const Image * , const KernelInfo * , ExceptionInfo *)
FilterImageChannel()
MagickExport Image * FilterImageChannel (const Image * , const ChannelType, const KernelInfo * , ExceptionInfo *)
GaussianBlurImage()
MagickExport Image * GaussianBlurImage (const Image * , const double , const double , ExceptionInfo *)
GaussianBlurImageChannel()
MagickExport Image * GaussianBlurImageChannel (const Image * , const ChannelType, const double , const double , ExceptionInfo *)
KuwaharaImage()
MagickExport Image * KuwaharaImage (const Image * , const double , const double , ExceptionInfo *)
KuwaharaImageChannel()
MagickExport Image * KuwaharaImageChannel (const Image * , const ChannelType, const double , const double , ExceptionInfo *)
LocalContrastImage()
MagickExport Image * LocalContrastImage (const Image * , const double , const double , ExceptionInfo *)
MotionBlurImage()
MagickExport Image * MotionBlurImage (const Image * , const double , const double , const double , ExceptionInfo *)
MotionBlurImageChannel()
MagickExport Image * MotionBlurImageChannel (const Image * , const ChannelType, const double , const double , const double , ExceptionInfo *)
PreviewImage()
MagickExport Image * PreviewImage (const Image * , const PreviewType, ExceptionInfo *)
RotationalBlurImage()
MagickExport Image * RotationalBlurImage (const Image * , const double , ExceptionInfo *)
RotationalBlurImageChannel()
MagickExport Image * RotationalBlurImageChannel (const Image * , const ChannelType, const double , ExceptionInfo *)
SelectiveBlurImage()
MagickExport Image * SelectiveBlurImage (const Image * , const double , const double , const double , ExceptionInfo *)
SelectiveBlurImageChannel()
MagickExport Image * SelectiveBlurImageChannel (const Image * , const ChannelType, const double , const double , const double , ExceptionInfo *)
ShadeImage()
MagickExport Image * ShadeImage (const Image * , const MagickBooleanType, const double , const double , ExceptionInfo *)
SharpenImage()
MagickExport Image * SharpenImage (const Image * , const double , const double , ExceptionInfo *)
SharpenImageChannel()
MagickExport Image * SharpenImageChannel (const Image * , const ChannelType, const double , const double , ExceptionInfo *)
SpreadImage()
MagickExport Image * SpreadImage (const Image * , const double , ExceptionInfo *)
UnsharpMaskImage()
MagickExport Image * UnsharpMaskImage (const Image * , const double , const double , const double , const double , ExceptionInfo *)
UnsharpMaskImageChannel()
MagickExport Image * UnsharpMaskImageChannel (const Image * image, const ChannelType, const double radius, const double sigma, const double gain, const double threshold, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _DoublePixelPacket::blue, _MagickPixelPacket::blue, BlueChannel, BlurImageChannel(), ClampToQuantum(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _DoublePixelPacket::green, _MagickPixelPacket::green, GreenChannel, _DoublePixelPacket::index, _MagickPixelPacket::index, IndexChannel, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _DoublePixelPacket::opacity, _MagickPixelPacket::opacity, OpacityChannel, _Image::progress_monitor, QuantumRange, _DoublePixelPacket::red, _MagickPixelPacket::red, RedChannel, _Image::rows, SetImageProgress(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, SharpenImageTag, _Image::signature, SyncCacheViewAuthenticPixels(), SyncChannels, TraceEvent, and _Image::type.
Referenced by UnsharpMaskImage().