MagickCore: enhance.h File Reference
enhance.h File Reference
#include "magick/pixel.h"
Functions
MagickExport MagickBooleanType AutoGammaImage (Image *)
MagickExport MagickBooleanType AutoGammaImageChannel (Image *, const ChannelType)
MagickExport MagickBooleanType AutoLevelImage (Image *)
MagickExport MagickBooleanType AutoLevelImageChannel (Image *, const ChannelType)
MagickExport MagickBooleanType BrightnessContrastImage (Image *, const double, const double)
MagickExport MagickBooleanType BrightnessContrastImageChannel (Image *, const ChannelType, const double, const double)
MagickExport MagickBooleanType ClutImage (Image *, const Image *)
MagickExport MagickBooleanType ClutImageChannel (Image *, const ChannelType, const Image *)
MagickExport MagickBooleanType ColorDecisionListImage (Image *, const char *)
MagickExport MagickBooleanType ContrastImage (Image *, const MagickBooleanType)
MagickExport MagickBooleanType ContrastStretchImage (Image *, const char *)
MagickExport MagickBooleanType ContrastStretchImageChannel (Image *, const ChannelType, const double, const double)
MagickExport MagickBooleanType EqualizeImage (Image *image)
MagickExport MagickBooleanType EqualizeImageChannel (Image *image, const ChannelType)
MagickExport MagickBooleanType GammaImage (Image *, const char *)
MagickExport MagickBooleanType GammaImageChannel (Image *, const ChannelType, const double)
MagickExport MagickBooleanType GrayscaleImage (Image *, const PixelIntensityMethod)
MagickExport MagickBooleanType HaldClutImage (Image *, const Image *)
MagickExport MagickBooleanType HaldClutImageChannel (Image *, const ChannelType, const Image *)
MagickExport MagickBooleanType LevelImage (Image *, const char *)
MagickExport MagickBooleanType LevelImageChannel (Image *, const ChannelType, const double, const double, const double)
MagickExport MagickBooleanType LevelizeImage (Image *, const double, const double, const double)
MagickExport MagickBooleanType LevelizeImageChannel (Image *, const ChannelType, const double, const double, const double)
MagickExport MagickBooleanType LevelColorsImage (Image *, const MagickPixelPacket *, const MagickPixelPacket *, const MagickBooleanType)
MagickExport MagickBooleanType LevelColorsImageChannel (Image *, const ChannelType, const MagickPixelPacket *, const MagickPixelPacket *, const MagickBooleanType)
MagickExport MagickBooleanType LinearStretchImage (Image *, const double, const double)
MagickExport MagickBooleanType ModulateImage (Image *, const char *)
MagickExport MagickBooleanType NegateImage (Image *, const MagickBooleanType)
MagickExport MagickBooleanType NegateImageChannel (Image *, const ChannelType, const MagickBooleanType)
MagickExport MagickBooleanType NormalizeImage (Image *)
MagickExport MagickBooleanType NormalizeImageChannel (Image *, const ChannelType)
MagickExport MagickBooleanType SigmoidalContrastImage (Image *, const MagickBooleanType, const char *)
MagickExport MagickBooleanType SigmoidalContrastImageChannel (Image *, const ChannelType, const MagickBooleanType, const double, const double)
MagickExport Image * EnhanceImage (const Image *, ExceptionInfo *)
Function Documentation
AutoGammaImage()
MagickExport MagickBooleanType AutoGammaImage (Image *)
AutoGammaImageChannel()
MagickExport MagickBooleanType AutoGammaImageChannel (Image * , const ChannelType)
AutoLevelImage()
MagickExport MagickBooleanType AutoLevelImage (Image *)
AutoLevelImageChannel()
MagickExport MagickBooleanType AutoLevelImageChannel (Image * , const ChannelType)
BrightnessContrastImage()
MagickExport MagickBooleanType BrightnessContrastImage (Image * , const double , const double)
BrightnessContrastImageChannel()
MagickExport MagickBooleanType BrightnessContrastImageChannel (Image * , const ChannelType, const double , const double)
ClutImage()
MagickExport MagickBooleanType ClutImage (Image * , const Image *)
ClutImageChannel()
MagickExport MagickBooleanType ClutImageChannel (Image * , const ChannelType, const Image *)
ColorDecisionListImage()
MagickExport MagickBooleanType ColorDecisionListImage (Image * , const char *)
ContrastImage()
MagickExport MagickBooleanType ContrastImage (Image * , const MagickBooleanType)
ContrastStretchImage()
MagickExport MagickBooleanType ContrastStretchImage (Image * , const char *)
ContrastStretchImageChannel()
MagickExport MagickBooleanType ContrastStretchImageChannel (Image * , const ChannelType, const double , const double)
EnhanceImage()
MagickExport Image * EnhanceImage (const Image * image, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), _MagickPixelPacket::blue, CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, EnhanceImageTag, EnhancePixel, _Image::exception, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, _MagickPixelPacket::green, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickTrue, _MagickPixelPacket::opacity, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _MagickPixelPacket::red, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
EqualizeImage()
MagickExport MagickBooleanType EqualizeImage (Image * image)
EqualizeImageChannel()
MagickExport MagickBooleanType EqualizeImageChannel (Image * image, const ChannelType)
GammaImage()
MagickExport MagickBooleanType GammaImage (Image * , const char *)
GammaImageChannel()
MagickExport MagickBooleanType GammaImageChannel (Image * , const ChannelType, const double)
GrayscaleImage()
MagickExport MagickBooleanType GrayscaleImage (Image * , const PixelIntensityMethod)
HaldClutImage()
MagickExport MagickBooleanType HaldClutImage (Image * , const Image *)
HaldClutImageChannel()
MagickExport MagickBooleanType HaldClutImageChannel (Image * , const ChannelType, const Image *)
LevelColorsImage()
MagickExport MagickBooleanType LevelColorsImage (Image * , const MagickPixelPacket * , const MagickPixelPacket * , const MagickBooleanType)
LevelColorsImageChannel()
MagickExport MagickBooleanType LevelColorsImageChannel (Image * , const ChannelType, const MagickPixelPacket * , const MagickPixelPacket * , const MagickBooleanType)
LevelImage()
MagickExport MagickBooleanType LevelImage (Image * , const char *)
LevelImageChannel()
MagickExport MagickBooleanType LevelImageChannel (Image * , const ChannelType, const double , const double , const double)
LevelizeImage()
MagickExport MagickBooleanType LevelizeImage (Image * , const double , const double , const double)
LevelizeImageChannel()
MagickExport MagickBooleanType LevelizeImageChannel (Image * , const ChannelType, const double , const double , const double)
LinearStretchImage()
MagickExport MagickBooleanType LinearStretchImage (Image * , const double , const double)
ModulateImage()
MagickExport MagickBooleanType ModulateImage (Image * , const char *)
NegateImage()
MagickExport MagickBooleanType NegateImage (Image * , const MagickBooleanType)
NegateImageChannel()
MagickExport MagickBooleanType NegateImageChannel (Image * , const ChannelType, const MagickBooleanType)
NormalizeImage()
MagickExport MagickBooleanType NormalizeImage (Image *)
NormalizeImageChannel()
MagickExport MagickBooleanType NormalizeImageChannel (Image * , const ChannelType)
SigmoidalContrastImage()
MagickExport MagickBooleanType SigmoidalContrastImage (Image * , const MagickBooleanType, const char *)
SigmoidalContrastImageChannel()
MagickExport MagickBooleanType SigmoidalContrastImageChannel (Image * image, const ChannelType, const MagickBooleanType, const double contrast, const double midpoint)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), _PixelPacket::blue, BlueChannel, ClampToQuantum(), CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _PixelPacket::green, GreenChannel, IndexChannel, InverseScaledSigmoidal(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickTrue, MaxMap, _PixelPacket::opacity, OpacityChannel, _Image::progress_monitor, PseudoClass, QuantumScale, _PixelPacket::red, RedChannel, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, ScaledSigmoidal, SetImageProgress(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, SigmoidalContrastImageTag, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), ThrowBinaryException, and TraceEvent.
Referenced by SigmoidalContrastImage().