MagickCore: enhance.c File Reference
enhance.c File Reference
#include "magick/studio.h"
#include "magick/accelerate-private.h"
#include "magick/artifact.h"
#include "magick/attribute.h"
#include "magick/cache.h"
#include "magick/cache-view.h"
#include "magick/channel.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colorspace.h"
#include "magick/colorspace-private.h"
#include "magick/composite-private.h"
#include "magick/enhance.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/fx.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/histogram.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/memory_.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/opencl.h"
#include "magick/opencl-private.h"
#include "magick/option.h"
#include "magick/pixel-accessor.h"
#include "magick/pixel-private.h"
#include "magick/quantum.h"
#include "magick/quantum-private.h"
#include "magick/resample.h"
#include "magick/resample-private.h"
#include "magick/resource_.h"
#include "magick/statistic.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/thread-private.h"
#include "magick/threshold.h"
#include "magick/token.h"
#include "magick/xml-tree.h"
Macros
#define BrightnessContastImageTag "BrightnessContast/Image"
#define ColorDecisionListCorrectImageTag "ColorDecisionList/Image"
#define ClutImageTag "Clut/Image"
#define ContrastImageTag "Contrast/Image"
#define MaxRange(color) ((MagickRealType) ScaleQuantumToMap((Quantum) (color)))
#define ContrastStretchImageTag "ContrastStretch/Image"
#define EnhancePixel(weight)
#define EnhanceImageTag "Enhance/Image"
#define EqualizeImageTag "Equalize/Image"
#define GammaImageTag "Gamma/Image"
#define GrayscaleImageTag "Grayscale/Image"
#define HaldClutImageTag "Clut/Image"
#define LevelImageTag "Level/Image"
#define LevelizeImageTag "Levelize/Image"
#define LevelizeValue(x)
#define LinearStretchImageTag "LinearStretch/Image"
#define ModulateImageTag "Modulate/Image"
#define NegateImageTag "Negate/Image"
#define Sigmoidal(a, b, x) (1.0/(1.0+exp((a)*((b)-(x)))))
#define ScaledSigmoidal(a, b, x)
#define SigmoidalContrastImageTag "SigmoidalContrast/Image"
Functions
MagickExport MagickBooleanType AutoGammaImage (Image *image)
MagickExport MagickBooleanType AutoGammaImageChannel (Image *image, const ChannelType channel)
MagickExport MagickBooleanType AutoLevelImage (Image *image)
MagickExport MagickBooleanType AutoLevelImageChannel (Image *image, const ChannelType channel)
MagickExport MagickBooleanType BrightnessContrastImage (Image *image, const double brightness, const double contrast)
MagickExport MagickBooleanType BrightnessContrastImageChannel (Image *image, const ChannelType channel, const double brightness, const double contrast)
MagickExport MagickBooleanType ColorDecisionListImage (Image *image, const char *color_correction_collection)
MagickExport MagickBooleanType ClutImage (Image *image, const Image *clut_image)
MagickExport MagickBooleanType ClutImageChannel (Image *image, const ChannelType channel, const Image *clut_image)
static void Contrast (const int sign, Quantum *red, Quantum *green, Quantum *blue)
MagickExport MagickBooleanType ContrastImage (Image *image, const MagickBooleanType sharpen)
MagickExport MagickBooleanType ContrastStretchImage (Image *image, const char *levels)
MagickExport MagickBooleanType ContrastStretchImageChannel (Image *image, const ChannelType channel, const double black_point, const double white_point)
MagickExport Image * EnhanceImage (const Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType EqualizeImage (Image *image)
MagickExport MagickBooleanType EqualizeImageChannel (Image *image, const ChannelType channel)
static double gamma_pow (const double value, const double gamma)
MagickExport MagickBooleanType GammaImage (Image *image, const char *level)
MagickExport MagickBooleanType GammaImageChannel (Image *image, const ChannelType channel, const double gamma)
MagickExport MagickBooleanType GrayscaleImage (Image *image, const PixelIntensityMethod method)
MagickExport MagickBooleanType HaldClutImage (Image *image, const Image *hald_image)
MagickExport MagickBooleanType HaldClutImageChannel (Image *image, const ChannelType channel, const Image *hald_image)
MagickExport MagickBooleanType LevelImage (Image *image, const char *levels)
static double LevelPixel (const double black_point, const double white_point, const double gamma, const MagickRealType pixel)
MagickExport MagickBooleanType LevelImageChannel (Image *image, const ChannelType channel, const double black_point, const double white_point, const double gamma)
MagickExport MagickBooleanType LevelizeImage (Image *image, const double black_point, const double white_point, const double gamma)
MagickExport MagickBooleanType LevelizeImageChannel (Image *image, const ChannelType channel, const double black_point, const double white_point, const double gamma)
MagickExport MagickBooleanType LevelColorsImage (Image *image, const MagickPixelPacket *black_color, const MagickPixelPacket *white_color, const MagickBooleanType invert)
MagickExport MagickBooleanType LevelColorsImageChannel (Image *image, const ChannelType channel, const MagickPixelPacket *black_color, const MagickPixelPacket *white_color, const MagickBooleanType invert)
MagickExport MagickBooleanType LinearStretchImage (Image *image, const double black_point, const double white_point)
static void ModulateHCL (const double percent_hue, const double percent_chroma, const double percent_luma, Quantum *red, Quantum *green, Quantum *blue)
static void ModulateHCLp (const double percent_hue, const double percent_chroma, const double percent_luma, Quantum *red, Quantum *green, Quantum *blue)
static void ModulateHSB (const double percent_hue, const double percent_saturation, const double percent_brightness, Quantum *red, Quantum *green, Quantum *blue)
static void ModulateHSI (const double percent_hue, const double percent_saturation, const double percent_intensity, Quantum *red, Quantum *green, Quantum *blue)
static void ModulateHSL (const double percent_hue, const double percent_saturation, const double percent_lightness, Quantum *red, Quantum *green, Quantum *blue)
static void ModulateHSV (const double percent_hue, const double percent_saturation, const double percent_value, Quantum *red, Quantum *green, Quantum *blue)
static void ModulateHWB (const double percent_hue, const double percent_whiteness, const double percent_blackness, Quantum *red, Quantum *green, Quantum *blue)
static void ModulateLCHab (const double percent_luma, const double percent_chroma, const double percent_hue, Quantum *red, Quantum *green, Quantum *blue)
static void ModulateLCHuv (const double percent_luma, const double percent_chroma, const double percent_hue, Quantum *red, Quantum *green, Quantum *blue)
MagickExport MagickBooleanType ModulateImage (Image *image, const char *modulate)
MagickExport MagickBooleanType NegateImage (Image *image, const MagickBooleanType grayscale)
MagickExport MagickBooleanType NegateImageChannel (Image *image, const ChannelType channel, const MagickBooleanType grayscale)
MagickExport MagickBooleanType NormalizeImage (Image *image)
MagickExport MagickBooleanType NormalizeImageChannel (Image *image, const ChannelType channel)
static double InverseScaledSigmoidal (const double a, const double b, const double x)
MagickExport MagickBooleanType SigmoidalContrastImage (Image *image, const MagickBooleanType sharpen, const char *levels)
MagickExport MagickBooleanType SigmoidalContrastImageChannel (Image *image, const ChannelType channel, const MagickBooleanType sharpen, const double contrast, const double midpoint)
Macro Definition Documentation
BrightnessContastImageTag
#define BrightnessContastImageTag "BrightnessContast/Image"
ClutImageTag
#define ClutImageTag "Clut/Image"
ColorDecisionListCorrectImageTag
#define ColorDecisionListCorrectImageTag "ColorDecisionList/Image"
ContrastImageTag
#define ContrastImageTag "Contrast/Image"
ContrastStretchImageTag
#define ContrastStretchImageTag "ContrastStretch/Image"
EnhanceImageTag
#define EnhanceImageTag "Enhance/Image"
EnhancePixel
#define EnhancePixel (weight)
Value:
  mean=QuantumScale*((double) GetPixelRed(r)+pixel.red)/2.0; \
  distance=QuantumScale*((double) GetPixelRed(r)-pixel.red); \
  distance_squared=(4.0+mean)*distance*distance; \
  mean=QuantumScale*((double) GetPixelGreen(r)+pixel.green)/2.0; \
  distance=QuantumScale*((double) GetPixelGreen(r)-pixel.green); \
  distance_squared+=(7.0-mean)*distance*distance; \
  mean=QuantumScale*((double) GetPixelBlue(r)+pixel.blue)/2.0; \
  distance=QuantumScale*((double) GetPixelBlue(r)-pixel.blue); \
  distance_squared+=(5.0-mean)*distance*distance; \
  mean=QuantumScale*((double) GetPixelOpacity(r)+pixel.opacity)/2.0; \
  distance=QuantumScale*((double) GetPixelOpacity(r)-pixel.opacity); \
  distance_squared+=(5.0-mean)*distance*distance; \
  if (distance_squared < 0.069) \
    { \
      aggregate.red+=(weight)*GetPixelRed(r); \
      aggregate.green+=(weight)*GetPixelGreen(r); \
      aggregate.blue+=(weight)*GetPixelBlue(r); \
      aggregate.opacity+=(weight)*GetPixelOpacity(r); \
      total_weight+=(weight); \
    } \
  r++;
EqualizeImageTag
#define EqualizeImageTag "Equalize/Image"
GammaImageTag
#define GammaImageTag "Gamma/Image"
GrayscaleImageTag
#define GrayscaleImageTag "Grayscale/Image"
HaldClutImageTag
#define HaldClutImageTag "Clut/Image"
LevelImageTag
#define LevelImageTag "Level/Image"
LevelizeImageTag
#define LevelizeImageTag "Levelize/Image"
LevelizeValue
#define LevelizeValue (x)
Value:
  ClampToQuantum(((MagickRealType) gamma_pow((double) \
  (QuantumScale*(x)),gamma))*(white_point-black_point)+black_point)
LinearStretchImageTag
#define LinearStretchImageTag "LinearStretch/Image"
MaxRange
#define MaxRange (color) ((MagickRealType) ScaleQuantumToMap((Quantum) (color)))
ModulateImageTag
#define ModulateImageTag "Modulate/Image"
NegateImageTag
#define NegateImageTag "Negate/Image"
ScaledSigmoidal
#define ScaledSigmoidal (a, b, x)
Value:
  (                    \
  (Sigmoidal((a),(b),(x))-Sigmoidal((a),(b),0.0)) / \
  (Sigmoidal((a),(b),1.0)-Sigmoidal((a),(b),0.0)) )
Sigmoidal
#define Sigmoidal (a, b, x) (1.0/(1.0+exp((a)*((b)-(x)))))
SigmoidalContrastImageTag
#define SigmoidalContrastImageTag "SigmoidalContrast/Image"
Function Documentation
AutoGammaImage()
MagickExport MagickBooleanType AutoGammaImage (Image * image)
References AutoGammaImageChannel(), and DefaultChannels.
AutoGammaImageChannel()
MagickExport MagickBooleanType AutoGammaImageChannel (Image * image, const ChannelType channel)
References BlueChannel, CMYKColorspace, _Image::colorspace, _Image::exception, GetImageChannelMean(), GreenChannel, IndexChannel, LevelImageChannel(), MagickFalse, MagickTrue, _Image::matte, OpacityChannel, QuantumRange, QuantumScale, RedChannel, and SyncChannels.
Referenced by AutoGammaImage().
AutoLevelImage()
MagickExport MagickBooleanType AutoLevelImage (Image * image)
References AutoLevelImageChannel(), and DefaultChannels.
Referenced by AdaptiveBlurImageChannel(), and AdaptiveSharpenImageChannel().
AutoLevelImageChannel()
MagickExport MagickBooleanType AutoLevelImageChannel (Image * image, const ChannelType channel)
References MinMaxStretchImage().
Referenced by AutoLevelImage().
BrightnessContrastImage()
MagickExport MagickBooleanType BrightnessContrastImage (Image * image, const double brightness, const double contrast)
References BrightnessContrastImageChannel(), and DefaultChannels.
BrightnessContrastImageChannel()
MagickExport MagickBooleanType BrightnessContrastImageChannel (Image * image, const ChannelType channel, const double brightness, const double contrast)
References _Image::debug, _Image::exception, _Image::filename, FunctionImageChannel(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickPI, PolynomialFunction, _Image::signature, and TraceEvent.
Referenced by BrightnessContrastImage().
ClutImage()
MagickExport MagickBooleanType ClutImage (Image * image, const Image * clut_image)
References ClutImageChannel(), and DefaultChannels.
ClutImageChannel()
MagickExport MagickBooleanType ClutImageChannel (Image * image, const ChannelType channel, const Image * clut_image)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), ActivateAlphaChannel, adjust(), BlueChannel, ClampPixelBlue, ClampPixelGreen, ClampPixelOpacity, ClampPixelRed, ClampToQuantum(), ClutImageTag, CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickPixelPacket(), GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, GreenChannel, IndexChannel, IntegerInterpolatePixel, _Image::interpolate, InterpolateMagickPixelPacket(), IsGrayColorspace(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickPixelIntensity(), MagickPixelIntensityToQuantum(), MagickTrue, _Image::matte, MaxMap, OpacityChannel, _Image::progress_monitor, RedChannel, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageAlphaChannel(), SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacket(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), ThrowBinaryException, TraceEvent, and UndefinedInterpolatePixel.
Referenced by ClutImage().
ColorDecisionListImage()
MagickExport MagickBooleanType ColorDecisionListImage (Image * image, const char * color_correction_collection)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), _PixelPacket::blue, ClampToQuantum(), ColorDecisionListCorrectImageTag, _Image::colormap, _Image::colors, _Image::columns, _Image::debug, DestroyCacheView(), DestroyXMLTree(), _Image::exception, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetNextToken(), GetPixelBlue, GetPixelGreen, GetPixelRed, GetXMLTreeChild(), GetXMLTreeContent(), _PixelPacket::green, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, MaxMap, MaxTextExtent, NewXMLTree(), _Image::progress_monitor, PseudoClass, _PixelPacket::red, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetPixelBlue, SetPixelGreen, SetPixelRed, _Image::signature, _Image::storage_class, StringToDouble(), SyncCacheViewAuthenticPixels(), ThrowBinaryException, TraceEvent, and TransformEvent.
Contrast()
static void Contrast (const int sign, Quantum * red, Quantum * green, Quantum * blue) static
References ConvertHSBToRGB(), ConvertRGBToHSB(), and MagickPI.
Referenced by ContrastImage().
ContrastImage()
MagickExport MagickBooleanType ContrastImage (Image * image, const MagickBooleanType sharpen)
References AcquireAuthenticCacheView(), _PixelPacket::blue, _Image::colormap, _Image::colors, _Image::columns, Contrast(), ContrastImageTag, _Image::debug, DestroyCacheView(), _Image::exception, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelRed, _PixelPacket::green, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::progress_monitor, PseudoClass, _PixelPacket::red, _Image::rows, SetImageProgress(), SetPixelBlue, SetPixelGreen, SetPixelRed, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by PreviewImage(), and SepiaToneImage().
ContrastStretchImage()
MagickExport MagickBooleanType ContrastStretchImage (Image * image, const char * levels)
References _Image::columns, ContrastStretchImageChannel(), DefaultChannels, MagickFalse, ParseGeometry(), PercentValue, QuantumRange, _GeometryInfo::rho, _Image::rows, _GeometryInfo::sigma, and SigmaValue.
ContrastStretchImageChannel()
MagickExport MagickBooleanType ContrastStretchImageChannel (Image * image, const ChannelType channel, const double black_point, const double white_point)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), _MagickPixelPacket::blue, _PixelPacket::blue, _QuantumPixelPacket::blue, BlueChannel, ClampToQuantum(), CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, ContrastStretchImageTag, _Image::debug, DestroyCacheView(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetPixelRed, GRAYColorspace, _MagickPixelPacket::green, _PixelPacket::green, _QuantumPixelPacket::green, GreenChannel, _MagickPixelPacket::index, _QuantumPixelPacket::index, IndexChannel, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, MaxMap, MaxRange, _MagickPixelPacket::opacity, _PixelPacket::opacity, _QuantumPixelPacket::opacity, OpacityChannel, _Image::progress_monitor, PseudoClass, QuantumRange, _MagickPixelPacket::red, _PixelPacket::red, _QuantumPixelPacket::red, RedChannel, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageColorspace(), SetImageGray(), SetImageProgress(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), SyncChannels, ThrowBinaryException, and TraceEvent.
Referenced by ContrastStretchImage(), and NormalizeImageChannel().
EnhanceImage()
MagickExport Image * EnhanceImage (const Image * image, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), _MagickPixelPacket::blue, CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, EnhanceImageTag, EnhancePixel, _Image::exception, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, _MagickPixelPacket::green, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickTrue, _MagickPixelPacket::opacity, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _MagickPixelPacket::red, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
EqualizeImage()
MagickExport MagickBooleanType EqualizeImage (Image * image)
References DefaultChannels, and EqualizeImageChannel().
EqualizeImageChannel()
MagickExport MagickBooleanType EqualizeImageChannel (Image * image, const ChannelType channel)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, _PixelPacket::blue, _QuantumPixelPacket::blue, BlueChannel, ClampToQuantum(), CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), EqualizeImageTag, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetPixelRed, _MagickPixelPacket::green, _PixelPacket::green, _QuantumPixelPacket::green, GreenChannel, _MagickPixelPacket::index, _QuantumPixelPacket::index, IndexChannel, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, MaxMap, _MagickPixelPacket::opacity, _PixelPacket::opacity, _QuantumPixelPacket::opacity, OpacityChannel, _Image::progress_monitor, PseudoClass, _MagickPixelPacket::red, _PixelPacket::red, _QuantumPixelPacket::red, RedChannel, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), SyncChannels, ThrowBinaryException, and TraceEvent.
Referenced by EmbossImage(), and EqualizeImage().
gamma_pow()
static double gamma_pow (const double value, const double gamma) inline static
Referenced by GammaImageChannel(), and LevelPixel().
GammaImage()
MagickExport MagickBooleanType GammaImage (Image * image, const char * level)
References _MagickPixelPacket::blue, BlueChannel, _Image::debug, _Image::filename, GammaImageChannel(), GetMagickModule, _MagickPixelPacket::green, GreenChannel, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, ParseGeometry(), _MagickPixelPacket::red, RedChannel, _GeometryInfo::rho, _GeometryInfo::sigma, SigmaValue, _Image::signature, TraceEvent, _GeometryInfo::xi, and XiValue.
GammaImageChannel()
MagickExport MagickBooleanType GammaImageChannel (Image * image, const ChannelType channel, const double gamma)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), _PixelPacket::blue, BlueChannel, ClampToQuantum(), CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::exception, _Image::filename, _Image::gamma, gamma_pow(), GammaImageTag, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _PixelPacket::green, GreenChannel, IndexChannel, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, MaxMap, _PixelPacket::opacity, OpacityChannel, PerceptibleReciprocal(), _Image::progress_monitor, PseudoClass, QuantumRange, QuantumScale, _PixelPacket::red, RedChannel, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), SyncChannels, ThrowBinaryException, and TraceEvent.
Referenced by GammaImage(), and PreviewImage().
GrayscaleImage()
MagickExport MagickBooleanType GrayscaleImage (Image * image, const PixelIntensityMethod method)
References AcquireAuthenticCacheView(), AveragePixelIntensityMethod, BrightnessPixelIntensityMethod, ClampToQuantum(), _Image::colorspace, _Image::columns, _Image::debug, DecodePixelGamma(), DestroyCacheView(), DirectClass, EncodePixelGamma(), _Image::exception, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GRAYColorspace, GrayscaleImageTag, GrayscaleType, _Image::intensity, LightnessPixelIntensityMethod, LinearGRAYColorspace, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickMax, MagickMin, MagickTrue, MSPixelIntensityMethod, _Image::progress_monitor, PseudoClass, QuantumRange, Rec601LumaPixelIntensityMethod, Rec601LuminancePixelIntensityMethod, Rec709LumaPixelIntensityMethod, Rec709LuminancePixelIntensityMethod, RGBColorspace, RMSPixelIntensityMethod, _Image::rows, SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelGray, _Image::signature, sRGBColorspace, _Image::storage_class, SyncCacheViewAuthenticPixels(), SyncImage(), TraceEvent, and _Image::type.
Referenced by CharcoalImage().
HaldClutImage()
MagickExport MagickBooleanType HaldClutImage (Image * image, const Image * hald_image)
References DefaultChannels, and HaldClutImageChannel().
HaldClutImageChannel()
MagickExport MagickBooleanType HaldClutImageChannel (Image * image, const ChannelType channel, const Image * hald_image)
References AcquireAuthenticCacheView(), _MagickPixelPacket::blue, BlueChannel, ClampToQuantum(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickPixelPacket(), GetPixelBlue, GetPixelGreen, GetPixelRed, _MagickPixelPacket::green, GreenChannel, HaldClutImageTag, _MagickPixelPacket::index, IndexChannel, _Image::interpolate, InterpolateMagickPixelPacket(), IsGrayColorspace(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickMin, MagickPixelCompositeAreaBlend(), MagickTrue, _Image::matte, NearestNeighborInterpolatePixel, _MagickPixelPacket::opacity, OpacityChannel, OpaqueAlphaChannel, _Image::progress_monitor, QuantumScale, _MagickPixelPacket::red, RedChannel, _Image::rows, SetImageAlphaChannel(), SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), TraceEvent, and UndefinedInterpolatePixel.
Referenced by HaldClutImage().
InverseScaledSigmoidal()
static double InverseScaledSigmoidal (const double a, const double b, const double x) inline static
References MagickEpsilon, and Sigmoidal.
Referenced by SigmoidalContrastImageChannel().
LevelColorsImage()
MagickExport MagickBooleanType LevelColorsImage (Image * image, const MagickPixelPacket * black_color, const MagickPixelPacket * white_color, const MagickBooleanType invert)
References DefaultChannels, and LevelColorsImageChannel().
Referenced by SetImageAlphaChannel().
LevelColorsImageChannel()
MagickExport MagickBooleanType LevelColorsImageChannel (Image * image, const ChannelType channel, const MagickPixelPacket * black_color, const MagickPixelPacket * white_color, const MagickBooleanType invert)
References _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _Image::colorspace, _MagickPixelPacket::colorspace, _Image::debug, _Image::filename, GetMagickModule, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, IsGrayColorspace(), LevelImageChannel(), LevelizeImageChannel(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _MagickPixelPacket::opacity, OpacityChannel, _MagickPixelPacket::red, RedChannel, SetImageColorspace(), _Image::signature, sRGBColorspace, and TraceEvent.
Referenced by LevelColorsImage(), and LevelImageColors().
LevelImage()
MagickExport MagickBooleanType LevelImage (Image * image, const char * levels)
References AspectValue, _Image::columns, DefaultChannels, LevelImageChannel(), LevelizeImage(), MagickFalse, ParseGeometry(), PercentValue, QuantumRange, _GeometryInfo::rho, _Image::rows, _GeometryInfo::sigma, SigmaValue, _GeometryInfo::xi, and XiValue.
LevelImageChannel()
MagickExport MagickBooleanType LevelImageChannel (Image * image, const ChannelType channel, const double black_point, const double white_point, const double gamma)
References AcquireAuthenticCacheView(), _PixelPacket::blue, BlueChannel, ClampImage(), ClampToQuantum(), CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelRed, _PixelPacket::green, GreenChannel, IndexChannel, LevelImageTag, LevelPixel(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _PixelPacket::opacity, OpacityChannel, _Image::progress_monitor, PseudoClass, QuantumRange, _PixelPacket::red, RedChannel, _Image::rows, SetImageProgress(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelRed, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by AutoGammaImageChannel(), LevelColorsImageChannel(), LevelImage(), LinearStretchImage(), and MinMaxStretchImage().
LevelizeImage()
MagickExport MagickBooleanType LevelizeImage (Image * image, const double black_point, const double white_point, const double gamma)
References DefaultChannels, and LevelizeImageChannel().
Referenced by LevelImage().
LevelizeImageChannel()
MagickExport MagickBooleanType LevelizeImageChannel (Image * image, const ChannelType channel, const double black_point, const double white_point, const double gamma)
References AcquireAuthenticCacheView(), _PixelPacket::blue, BlueChannel, CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelRed, _PixelPacket::green, GreenChannel, IndexChannel, LevelizeImageTag, LevelizeValue, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _PixelPacket::opacity, OpacityChannel, _Image::progress_monitor, PseudoClass, QuantumRange, _PixelPacket::red, RedChannel, _Image::rows, SetImageProgress(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelRed, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by LevelColorsImageChannel(), and LevelizeImage().
LevelPixel()
static double LevelPixel (const double black_point, const double white_point, const double gamma, const MagickRealType pixel) inline static
References gamma_pow(), PerceptibleReciprocal(), and QuantumRange.
Referenced by LevelImageChannel().
LinearStretchImage()
MagickExport MagickBooleanType LinearStretchImage (Image * image, const double black_point, const double white_point)
References AcquireQuantumMemory(), ClampToQuantum(), _Image::columns, DefaultChannels, _Image::exception, _Image::filename, GetPixelIntensity(), GetVirtualPixels(), LevelImageChannel(), magick_restrict, MagickCoreSignature, MaxMap, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, _Image::signature, and ThrowBinaryException.
ModulateHCL()
static void ModulateHCL (const double percent_hue, const double percent_chroma, const double percent_luma, Quantum * red, Quantum * green, Quantum * blue) inline static
References ConvertHCLToRGB(), and ConvertRGBToHCL().
Referenced by ModulateImage().
ModulateHCLp()
static void ModulateHCLp (const double percent_hue, const double percent_chroma, const double percent_luma, Quantum * red, Quantum * green, Quantum * blue) inline static
References ConvertHCLpToRGB(), and ConvertRGBToHCLp().
Referenced by ModulateImage().
ModulateHSB()
static void ModulateHSB (const double percent_hue, const double percent_saturation, const double percent_brightness, Quantum * red, Quantum * green, Quantum * blue) inline static
References ConvertHSBToRGB(), and ConvertRGBToHSB().
Referenced by ModulateImage().
ModulateHSI()
static void ModulateHSI (const double percent_hue, const double percent_saturation, const double percent_intensity, Quantum * red, Quantum * green, Quantum * blue) inline static
References ConvertHSIToRGB(), and ConvertRGBToHSI().
Referenced by ModulateImage().
ModulateHSL()
static void ModulateHSL (const double percent_hue, const double percent_saturation, const double percent_lightness, Quantum * red, Quantum * green, Quantum * blue) inline static
References ConvertHSLToRGB(), and ConvertRGBToHSL().
Referenced by ModulateImage().
ModulateHSV()
static void ModulateHSV (const double percent_hue, const double percent_saturation, const double percent_value, Quantum * red, Quantum * green, Quantum * blue) inline static
References ConvertHSVToRGB(), and ConvertRGBToHSV().
Referenced by ModulateImage().
ModulateHWB()
static void ModulateHWB (const double percent_hue, const double percent_whiteness, const double percent_blackness, Quantum * red, Quantum * green, Quantum * blue) inline static
References ConvertHWBToRGB(), and ConvertRGBToHWB().
Referenced by ModulateImage().
ModulateImage()
MagickExport MagickBooleanType ModulateImage (Image * image, const char * modulate)
References AcquireAuthenticCacheView(), _PixelPacket::blue, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::exception, _Image::filename, GetCacheViewAuthenticPixels(), GetImageArtifact(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelRed, _PixelPacket::green, HCLColorspace, HCLpColorspace, HSBColorspace, HSIColorspace, HSLColorspace, HSVColorspace, HWBColorspace, IssRGBCompatibleColorspace(), LCHabColorspace, LCHColorspace, LCHuvColorspace, LogMagickEvent(), magick_restrict, MagickColorspaceOptions, MagickCoreSignature, MagickFalse, MagickTrue, ModulateHCL(), ModulateHCLp(), ModulateHSB(), ModulateHSI(), ModulateHSL(), ModulateHSV(), ModulateHWB(), ModulateImageTag, ModulateLCHab(), ModulateLCHuv(), ParseCommandOption(), ParseGeometry(), _Image::progress_monitor, PseudoClass, _PixelPacket::red, _GeometryInfo::rho, _Image::rows, SetImageColorspace(), SetImageProgress(), SetPixelBlue, SetPixelGreen, SetPixelRed, _GeometryInfo::sigma, SigmaValue, _Image::signature, sRGBColorspace, _Image::storage_class, SyncCacheViewAuthenticPixels(), TraceEvent, UndefinedColorspace, _GeometryInfo::xi, and XiValue.
Referenced by PreviewImage().
ModulateLCHab()
static void ModulateLCHab (const double percent_luma, const double percent_chroma, const double percent_hue, Quantum * red, Quantum * green, Quantum * blue) inline static
References ConvertLCHabToRGB(), and ConvertRGBToLCHab().
Referenced by ModulateImage().
ModulateLCHuv()
static void ModulateLCHuv (const double percent_luma, const double percent_chroma, const double percent_hue, Quantum * red, Quantum * green, Quantum * blue) inline static
References ConvertLCHuvToRGB(), and ConvertRGBToLCHuv().
Referenced by ModulateImage().
NegateImage()
MagickExport MagickBooleanType NegateImage (Image * image, const MagickBooleanType grayscale)
References DefaultChannels, and NegateImageChannel().
Referenced by CharcoalImage(), ClipImagePath(), DrawClippingMask(), DrawCompositeMask(), and SketchImage().
NegateImageChannel()
MagickExport MagickBooleanType NegateImageChannel (Image * image, const ChannelType channel, const MagickBooleanType grayscale)
References AcquireAuthenticCacheView(), _PixelPacket::blue, BlueChannel, CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, _Image::debug, DefaultChannels, DestroyCacheView(), _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _PixelPacket::green, GreenChannel, IndexChannel, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, NegateImageTag, OpacityChannel, _Image::progress_monitor, PseudoClass, QuantumRange, _PixelPacket::red, RedChannel, _Image::rows, SetImageProgress(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by MontageImageList(), and NegateImage().
NormalizeImage()
MagickExport MagickBooleanType NormalizeImage (Image * image)
References DefaultChannels, and NormalizeImageChannel().
Referenced by CharcoalImage(), SepiaToneImage(), SetImageType(), and SketchImage().
NormalizeImageChannel()
MagickExport MagickBooleanType NormalizeImageChannel (Image * image, const ChannelType channel)
References _Image::columns, ContrastStretchImageChannel(), and _Image::rows.
Referenced by NormalizeImage().
SigmoidalContrastImage()
MagickExport MagickBooleanType SigmoidalContrastImage (Image * image, const MagickBooleanType sharpen, const char * levels)
References DefaultChannels, ParseGeometry(), PercentValue, QuantumRange, _GeometryInfo::rho, _GeometryInfo::sigma, SigmaValue, and SigmoidalContrastImageChannel().
SigmoidalContrastImageChannel()
MagickExport MagickBooleanType SigmoidalContrastImageChannel (Image * image, const ChannelType channel, const MagickBooleanType sharpen, const double contrast, const double midpoint)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), _PixelPacket::blue, BlueChannel, ClampToQuantum(), CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _PixelPacket::green, GreenChannel, IndexChannel, InverseScaledSigmoidal(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickTrue, MaxMap, _PixelPacket::opacity, OpacityChannel, _Image::progress_monitor, PseudoClass, QuantumScale, _PixelPacket::red, RedChannel, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, ScaledSigmoidal, SetImageProgress(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, SigmoidalContrastImageTag, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), ThrowBinaryException, and TraceEvent.
Referenced by SigmoidalContrastImage().