MagickCore: exception-private.h File Reference
exception-private.h File Reference
#include "magick/log.h"
#include "magick/magick.h"
#include "magick/string_.h"
Macros
#define ThrowBinaryException(severity, tag, context)
#define ThrowBinaryImageException(severity, tag, context)
#define ThrowFatalException(severity, tag)
#define ThrowFileException(exception, severity, tag, context)
#define ThrowImageException(severity, tag)
#define ThrowReaderException(severity, tag)
#define ThrowWriterException(severity, tag)
Functions
MagickPrivate MagickBooleanType ClearExceptionInfo (ExceptionInfo *, MagickBooleanType)
MagickPrivate MagickBooleanType ExceptionComponentGenesis (void)
MagickPrivate void ExceptionComponentTerminus (void)
MagickPrivate void InitializeExceptionInfo (ExceptionInfo *)
Macro Definition Documentation
ThrowBinaryException
#define ThrowBinaryException (severity, tag, context)
Value:
{ \
  (void) ThrowMagickException(exception,GetMagickModule(),severity, \
    tag == (const char *) NULL ? "unknown" : tag,"`%s'",context); \
  return(MagickFalse); \
}
ThrowBinaryImageException
#define ThrowBinaryImageException (severity, tag, context)
Value:
{ \
  if (image != (Image *) NULL) \
    (void) ThrowMagickException(&image->exception,GetMagickModule(),severity, \
       tag == (const char *) NULL ? "unknown" : tag,"`%s'",context); \
  return(MagickFalse); \
}
ThrowFatalException
#define ThrowFatalException (severity, tag)
Value:
{ \
  char \
    *fatal_message; \
 \
  ExceptionInfo \
    *fatal_exception; \
 \
  fatal_exception=AcquireExceptionInfo(); \
  fatal_message=GetExceptionMessage(errno); \
  (void) ThrowMagickException(fatal_exception,GetMagickModule(),severity, \
    tag == (const char *) NULL ? "unknown" : tag,"`%s'",fatal_message); \
  fatal_message=DestroyString(fatal_message); \
  CatchException(fatal_exception); \
  (void) DestroyExceptionInfo(fatal_exception); \
  MagickCoreTerminus(); \
  _exit((int) (severity-FatalErrorException)+1); \
}
ThrowFileException
#define ThrowFileException (exception, severity, tag, context)
Value:
{ \
  char \
    *message; \
 \
  message=GetExceptionMessage(errno); \
  (void) ThrowMagickException(exception,GetMagickModule(),severity, \
    tag == (const char *) NULL ? "unknown" : tag,"`%s': %s",context,message); \
  message=DestroyString(message); \
}
ThrowImageException
#define ThrowImageException (severity, tag)
Value:
{ \
  (void) ThrowMagickException(exception,GetMagickModule(),severity, \
    tag == (const char *) NULL ? "unknown" : tag,"`%s'",image->filename); \
  return((Image *) NULL); \
}
ThrowReaderException
#define ThrowReaderException (severity, tag)
Value:
{ \
  (void) ThrowMagickException(exception,GetMagickModule(),severity, \
    tag == (const char *) NULL ? "unknown" : tag,"`%s'",image_info->filename); \
  if ((image) != (Image *) NULL) \
    { \
      (void) CloseBlob(image); \
      image=DestroyImageList(image); \
    } \
  return((Image *) NULL); \
}
ThrowWriterException
#define ThrowWriterException (severity, tag)
Value:
{ \
  (void) ThrowMagickException(&image->exception,GetMagickModule(),severity, \
    tag == (const char *) NULL ? "unknown" : tag,"`%s'",image->filename); \
  if (image_info->adjoin != MagickFalse) \
    while (image->previous != (Image *) NULL) \
      image=image->previous; \
  (void) CloseBlob(image); \
  return(MagickFalse); \
}
Function Documentation
ClearExceptionInfo()
MagickPrivate MagickBooleanType ClearExceptionInfo (ExceptionInfo * , MagickBooleanType)
Referenced by DestroyImage().
ExceptionComponentGenesis()
MagickPrivate MagickBooleanType ExceptionComponentGenesis (void)
References AllocateSemaphoreInfo(), exception_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
ExceptionComponentTerminus()
MagickPrivate void ExceptionComponentTerminus (void)
Referenced by MagickCoreTerminus().
InitializeExceptionInfo()
MagickPrivate void InitializeExceptionInfo (ExceptionInfo * exception)
References AllocateSemaphoreInfo(), _ExceptionInfo::exceptions, MagickCoreSignature, NewLinkedList(), _ExceptionInfo::semaphore, _ExceptionInfo::severity, _ExceptionInfo::signature, and UndefinedException.
Referenced by AcquireExceptionInfo(), AcquireImage(), CloneExceptionInfo(), and CloneImage().