MagickCore: feature.h File Reference
feature.h File Reference
Data Structures
struct _ChannelFeatures
Typedefs
typedef struct _ChannelFeatures ChannelFeatures
Functions
MagickExport ChannelFeatures * GetImageChannelFeatures (const Image *, const size_t, ExceptionInfo *)
MagickExport Image * CannyEdgeImage (const Image *, const double, const double, const double, const double, ExceptionInfo *)
MagickExport Image * HoughLineImage (const Image *, const size_t, const size_t, const size_t, ExceptionInfo *)
MagickExport Image * MeanShiftImage (const Image *, const size_t, const size_t, const double, ExceptionInfo *)
Typedef Documentation
ChannelFeatures
typedef struct _ChannelFeatures ChannelFeatures
Function Documentation
CannyEdgeImage()
MagickExport Image * CannyEdgeImage (const Image * , const double , const double , const double , const double , ExceptionInfo *)
GetImageChannelFeatures()
MagickExport ChannelFeatures * GetImageChannelFeatures (const Image * image, const size_t, ExceptionInfo * exception)
References AcquireQuantumMemory(), AcquireVirtualCacheView(), _ChannelFeatures::angular_second_moment, BlackChannel, _LongPixelPacket::blue, BlueChannel, CMYKColorspace, _Image::colorspace, _Image::columns, CompositeChannels, _ChannelFeatures::contrast, _ChannelFeatures::correlation, _Image::debug, DestroyCacheView(), _ChannelFeatures::difference_entropy, _ChannelFeatures::difference_variance, _ChannelFeatures::entropy, _Image::filename, GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _LongPixelPacket::green, GreenChannel, _LongPixelPacket::index, IndexChannel, _ChannelFeatures::inverse_difference_moment, LogMagickEvent(), magick_restrict, MagickAbsoluteValue, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickLog10(), MagickTrue, _Image::matte, _ChannelFeatures::maximum_correlation_coefficient, MaxMap, _ChannelFeatures::measure_of_correlation_1, _ChannelFeatures::measure_of_correlation_2, _LongPixelPacket::opacity, OpacityChannel, PerceptibleReciprocal(), _LongPixelPacket::red, RedChannel, RelinquishMagickMemory(), ResourceLimitError, ResourceLimitFatalError, _Image::rows, _Image::signature, _ChannelFeatures::sum_average, _ChannelFeatures::sum_entropy, _ChannelFeatures::sum_variance, ThrowFatalException, ThrowMagickException(), TraceEvent, and _ChannelFeatures::variance_sum_of_squares.
Referenced by IdentifyImage().
HoughLineImage()
MagickExport Image * HoughLineImage (const Image * , const size_t, const size_t, const size_t, ExceptionInfo *)
MeanShiftImage()
MagickExport Image * MeanShiftImage (const Image * image, const size_t, const size_t, const double color_distance, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, _PixelPacket::blue, ClampToQuantum(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), GetOneCacheViewVirtualPixel(), _MagickPixelPacket::green, _PixelPacket::green, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickRound(), MagickTrue, MaxMeanShiftIterations, MeanShiftImageTag, _MagickPixelPacket::opacity, _PixelPacket::opacity, PerceptibleReciprocal(), _Image::progress_monitor, QuantumScale, _MagickPixelPacket::red, _PixelPacket::red, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacket(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, _PointInfo::x, and _PointInfo::y.