MagickCore: feature.c File Reference
feature.c File Reference
#include "magick/studio.h"
#include "magick/animate.h"
#include "magick/artifact.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/cache.h"
#include "magick/cache-private.h"
#include "magick/cache-view.h"
#include "magick/channel.h"
#include "magick/client.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colorspace.h"
#include "magick/colorspace-private.h"
#include "magick/composite.h"
#include "magick/composite-private.h"
#include "magick/compress.h"
#include "magick/constitute.h"
#include "magick/deprecate.h"
#include "magick/display.h"
#include "magick/draw.h"
#include "magick/enhance.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/feature.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/list.h"
#include "magick/image-private.h"
#include "magick/magic.h"
#include "magick/magick.h"
#include "magick/matrix.h"
#include "magick/memory_.h"
#include "magick/module.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/morphology-private.h"
#include "magick/option.h"
#include "magick/paint.h"
#include "magick/pixel-private.h"
#include "magick/profile.h"
#include "magick/property.h"
#include "magick/quantize.h"
#include "magick/random_.h"
#include "magick/resource_.h"
#include "magick/segment.h"
#include "magick/semaphore.h"
#include "magick/signature-private.h"
#include "magick/string_.h"
#include "magick/thread-private.h"
#include "magick/timer.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/version.h"
Data Structures
struct _CannyInfo
Macros
#define CannyEdgeImageTag "CannyEdge/Image"
#define Log10Epsilon (1.0e-11)
#define BoundingBox "viewbox"
#define HoughLineImageTag "HoughLine/Image"
#define MaxMeanShiftIterations 100
#define MeanShiftImageTag "MeanShift/Image"
Typedefs
typedef struct _CannyInfo CannyInfo
Functions
static MagickBooleanType IsAuthenticPixel (const Image *image, const ssize_t x, const ssize_t y)
static MagickBooleanType TraceEdges (Image *edge_image, CacheView *edge_view, MatrixInfo *canny_cache, const ssize_t x, const ssize_t y, const double lower_threshold, ExceptionInfo *exception)
MagickExport Image * CannyEdgeImage (const Image *image, const double radius, const double sigma, const double lower_percent, const double upper_percent, ExceptionInfo *exception)
static double MagickLog10 (const double x)
MagickExport ChannelFeatures * GetImageChannelFeatures (const Image *image, const size_t distance, ExceptionInfo *exception)
static double MagickRound (double x)
static Image * RenderHoughLines (const ImageInfo *image_info, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport Image * HoughLineImage (const Image *image, const size_t width, const size_t height, const size_t threshold, ExceptionInfo *exception)
MagickExport Image * MeanShiftImage (const Image *image, const size_t width, const size_t height, const double color_distance, ExceptionInfo *exception)
Macro Definition Documentation
BoundingBox
#define BoundingBox "viewbox"
CannyEdgeImageTag
#define CannyEdgeImageTag "CannyEdge/Image"
HoughLineImageTag
#define HoughLineImageTag "HoughLine/Image"
Log10Epsilon
#define Log10Epsilon (1.0e-11)
MaxMeanShiftIterations
#define MaxMeanShiftIterations 100
MeanShiftImageTag
#define MeanShiftImageTag "MeanShift/Image"
Typedef Documentation
CannyInfo
typedef struct _CannyInfo CannyInfo
Function Documentation
CannyEdgeImage()
MagickExport Image * CannyEdgeImage (const Image * image, const double radius, const double sigma, const double lower_percent, const double upper_percent, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireKernelInfo(), AcquireMatrixInfo(), AcquireVirtualCacheView(), CannyEdgeImageTag, _Image::columns, ConvolveMorphology, DeactivateAlphaChannel, _Image::debug, DefaultChannels, DestroyCacheView(), DestroyImage(), DestroyKernelInfo(), DestroyMatrixInfo(), _Image::filename, FormatLocaleString(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetMagickModule, GetMatrixElement(), GetPixelIntensity(), GRAYColorspace, _CannyInfo::intensity, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickTrue, _CannyInfo::magnitude, MaxTextExtent, MorphologyImageChannel(), _CannyInfo::orientation, _Image::progress_monitor, ResourceLimitError, _Image::rows, SetImageAlphaChannel(), SetImageProgress(), SetMatrixElement(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEdges(), TraceEvent, and TransformImageColorspace().
GetImageChannelFeatures()
MagickExport ChannelFeatures * GetImageChannelFeatures (const Image * image, const size_t distance, ExceptionInfo * exception)
References AcquireQuantumMemory(), AcquireVirtualCacheView(), _ChannelFeatures::angular_second_moment, BlackChannel, _LongPixelPacket::blue, BlueChannel, CMYKColorspace, _Image::colorspace, _Image::columns, CompositeChannels, _ChannelFeatures::contrast, _ChannelFeatures::correlation, _Image::debug, DestroyCacheView(), _ChannelFeatures::difference_entropy, _ChannelFeatures::difference_variance, _ChannelFeatures::entropy, _Image::filename, GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _LongPixelPacket::green, GreenChannel, _LongPixelPacket::index, IndexChannel, _ChannelFeatures::inverse_difference_moment, LogMagickEvent(), magick_restrict, MagickAbsoluteValue, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickLog10(), MagickTrue, _Image::matte, _ChannelFeatures::maximum_correlation_coefficient, MaxMap, _ChannelFeatures::measure_of_correlation_1, _ChannelFeatures::measure_of_correlation_2, _LongPixelPacket::opacity, OpacityChannel, PerceptibleReciprocal(), _LongPixelPacket::red, RedChannel, RelinquishMagickMemory(), ResourceLimitError, ResourceLimitFatalError, _Image::rows, _Image::signature, _ChannelFeatures::sum_average, _ChannelFeatures::sum_entropy, _ChannelFeatures::sum_variance, ThrowFatalException, ThrowMagickException(), TraceEvent, and _ChannelFeatures::variance_sum_of_squares.
Referenced by IdentifyImage().
HoughLineImage()
MagickExport Image * HoughLineImage (const Image * image, const size_t width, const size_t height, const size_t threshold, ExceptionInfo * exception)
References AcquireImageInfo(), AcquireMatrixInfo(), AcquireUniqueFileResource(), AcquireVirtualCacheView(), AppendImageToList(), _Image::background_color, _ImageInfo::background_color, _Image::columns, _Image::debug, DegreesToRadians(), DestroyCacheView(), DestroyImageInfo(), DestroyMatrixInfo(), _Image::filename, _ImageInfo::filename, FormatLocaleString(), GetCacheViewVirtualPixels(), GetFirstImageInList(), GetImageArtifact(), GetMagickModule, GetMatrixElement(), GetPixelIntensity(), HoughLineImageTag, IsMagickTrue(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickRound(), MagickTrue, MatrixToImage(), MaxTextExtent, NullMatrix(), _Image::progress_monitor, QuantumRange, RelinquishUniqueFileResource(), RenderHoughLines(), ResourceLimitError, _Image::rows, SetImageOption(), SetImageProgress(), SetMatrixElement(), _ExceptionInfo::signature, _Image::signature, ThrowImageException, TraceEvent, _PointInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
IsAuthenticPixel()
static MagickBooleanType IsAuthenticPixel (const Image * image, const ssize_t x, const ssize_t y) inline static
References _Image::columns, MagickFalse, MagickTrue, and _Image::rows.
Referenced by TraceEdges().
MagickLog10()
static double MagickLog10 (const double x) inline static
References Log10Epsilon.
Referenced by GetImageChannelFeatures().
MagickRound()
static double MagickRound (double x) inline static
Referenced by HoughLineImage(), and MeanShiftImage().
MeanShiftImage()
MagickExport Image * MeanShiftImage (const Image * image, const size_t width, const size_t height, const double color_distance, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, _PixelPacket::blue, ClampToQuantum(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), GetOneCacheViewVirtualPixel(), _MagickPixelPacket::green, _PixelPacket::green, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickRound(), MagickTrue, MaxMeanShiftIterations, MeanShiftImageTag, _MagickPixelPacket::opacity, _PixelPacket::opacity, PerceptibleReciprocal(), _Image::progress_monitor, QuantumScale, _MagickPixelPacket::red, _PixelPacket::red, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacket(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, _PointInfo::x, and _PointInfo::y.
RenderHoughLines()
static Image * RenderHoughLines (const ImageInfo * image_info, const size_t columns, const size_t rows, ExceptionInfo * exception) static
References AcquireImage(), AcquireQuantumMemory(), _DrawInfo::affine, CloneDrawInfo(), CloseBlob(), _Image::columns, DefaultResolution, DestroyDrawInfo(), DestroyImageList(), DrawImage(), _Image::filename, FileToString(), GetBlobSize(), GetBlobStreamData(), GetFirstImageInList(), MagickFalse, OpenBlob(), _DrawInfo::primitive, ReadBinaryBlobMode, _Image::rows, SetImageBackgroundColor(), SetImageExtent(), _AffineMatrix::sx, _AffineMatrix::sy, _Image::x_resolution, and _Image::y_resolution.
Referenced by HoughLineImage().
TraceEdges()
static MagickBooleanType TraceEdges (Image * edge_image, CacheView * edge_view, MatrixInfo * canny_cache, const ssize_t x, const ssize_t y, const double lower_threshold, ExceptionInfo * exception) static
References _PixelPacket::blue, GetCacheViewAuthenticPixels(), GetMatrixElement(), GetPixelIntensity(), _PixelPacket::green, _CannyInfo::intensity, IsAuthenticPixel(), MagickFalse, MagickTrue, QuantumRange, _PixelPacket::red, SetMatrixElement(), SyncCacheViewAuthenticPixels(), _CannyInfo::x, and _CannyInfo::y.
Referenced by CannyEdgeImage().