MagickCore: fourier.c File Reference
fourier.c File Reference
#include "magick/studio.h"
#include "magick/artifact.h"
#include "magick/attribute.h"
#include "magick/blob.h"
#include "magick/cache.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/fourier.h"
#include "magick/log.h"
#include "magick/memory_.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/pixel-accessor.h"
#include "magick/pixel-private.h"
#include "magick/property.h"
#include "magick/quantum-private.h"
#include "magick/resource_.h"
#include "magick/string-private.h"
#include "magick/thread-private.h"
Data Structures
struct _FourierInfo
Macros
#define ComplexImageTag "Complex/Image"
Typedefs
typedef struct _FourierInfo FourierInfo
Functions
MagickExport Image * ComplexImages (const Image *images, const ComplexOperator op, ExceptionInfo *exception)
MagickExport Image * ForwardFourierTransformImage (const Image *image, const MagickBooleanType modulus, ExceptionInfo *exception)
MagickExport Image * InverseFourierTransformImage (const Image *magnitude_image, const Image *phase_image, const MagickBooleanType modulus, ExceptionInfo *exception)
Macro Definition Documentation
ComplexImageTag
#define ComplexImageTag "Complex/Image"
Typedef Documentation
FourierInfo
typedef struct _FourierInfo FourierInfo
Function Documentation
ComplexImages()
MagickExport Image * ComplexImages (const Image * images, const ComplexOperator op, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AddComplexOperator, AppendImageToList(), CloneImage(), _Image::columns, ComplexImageTag, ConjugateComplexOperator, _Image::debug, _Image::depth, DestroyCacheView(), DestroyImageList(), DirectClass, DivideComplexOperator, _Image::filename, GetCacheViewVirtualPixels(), GetImageArtifact(), GetMagickModule, ImageError, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickMin, MagickPI, MagickTrue, MagnitudePhaseComplexOperator, _Image::matte, MultiplyComplexOperator, NewImageList(), _Image::next, PerceptibleReciprocal(), _Image::progress_monitor, QuantumRange, QuantumScale, QueueCacheViewAuthenticPixels(), RealImaginaryComplexOperator, _Image::rows, SetImageProgress(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, StringToDouble(), SubtractComplexOperator, SyncCacheViewAuthenticPixels(), ThrowMagickException(), and TraceEvent.
ForwardFourierTransformImage()
MagickExport Image * ForwardFourierTransformImage (const Image * image, const MagickBooleanType modulus, ExceptionInfo * exception)
References AppendImageToList(), BlueChannel, CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::depth, DestroyImage(), DestroyImageList(), DirectClass, _Image::filename, GetMagickModule, GrayChannels, GreenChannel, IndexChannel, IsGrayImage(), MagickFalse, MagickTrue, _Image::matte, MissingDelegateWarning, NewImageList(), OpacityChannel, RedChannel, _Image::rows, _Image::storage_class, and ThrowMagickException().
InverseFourierTransformImage()
MagickExport Image * InverseFourierTransformImage (const Image * magnitude_image, const Image * phase_image, const MagickBooleanType modulus, ExceptionInfo * exception)
References BlueChannel, CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyImage(), _Image::filename, GetMagickModule, GrayChannels, GreenChannel, ImageError, IndexChannel, IsGrayImage(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, MissingDelegateWarning, OpacityChannel, RedChannel, _Image::rows, _Image::signature, ThrowMagickException(), and TraceEvent.