MagickCore: fourier.h File Reference
fourier.h File Reference
Enumerations
enum ComplexOperator {
UndefinedComplexOperator , AddComplexOperator , ConjugateComplexOperator , DivideComplexOperator ,
MagnitudePhaseComplexOperator , MultiplyComplexOperator , RealImaginaryComplexOperator , SubtractComplexOperator
}
Functions
MagickExport Image * ComplexImages (const Image *, const ComplexOperator, ExceptionInfo *)
MagickExport Image * ForwardFourierTransformImage (const Image *, const MagickBooleanType, ExceptionInfo *)
MagickExport Image * InverseFourierTransformImage (const Image *, const Image *, const MagickBooleanType, ExceptionInfo *)
Enumeration Type Documentation
ComplexOperator
enum ComplexOperator
Enumerator
UndefinedComplexOperator
AddComplexOperator
ConjugateComplexOperator
DivideComplexOperator
MagnitudePhaseComplexOperator
MultiplyComplexOperator
RealImaginaryComplexOperator
SubtractComplexOperator
Function Documentation
ComplexImages()
MagickExport Image * ComplexImages (const Image * , const ComplexOperator, ExceptionInfo *)
ForwardFourierTransformImage()
MagickExport Image * ForwardFourierTransformImage (const Image * , const MagickBooleanType, ExceptionInfo *)
InverseFourierTransformImage()
MagickExport Image * InverseFourierTransformImage (const Image * magnitude_image, const Image * phase_image, const MagickBooleanType, ExceptionInfo * exception)
References BlueChannel, CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyImage(), _Image::filename, GetMagickModule, GrayChannels, GreenChannel, ImageError, IndexChannel, IsGrayImage(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, MissingDelegateWarning, OpacityChannel, RedChannel, _Image::rows, _Image::signature, ThrowMagickException(), and TraceEvent.