MagickCore: fx-private.h File Reference
fx-private.h File Reference
Typedefs
typedef struct _FxInfo FxInfo
Functions
MagickExport FxInfo * AcquireFxInfo (const Image *, const char *)
MagickExport FxInfo * DestroyFxInfo (FxInfo *)
MagickExport MagickBooleanType FxEvaluateExpression (FxInfo *, double *, ExceptionInfo *)
MagickExport MagickBooleanType FxEvaluateChannelExpression (FxInfo *, const ChannelType, const ssize_t, const ssize_t, double *, ExceptionInfo *)
Typedef Documentation
FxInfo
typedef struct _FxInfo FxInfo
Function Documentation
AcquireFxInfo()
MagickExport FxInfo * AcquireFxInfo (const Image * , const char *)
Referenced by GetImageProperty(), and InterpretImageProperties().
DestroyFxInfo()
MagickExport FxInfo * DestroyFxInfo (FxInfo * fx_info)
References _FxInfo::colors, DestroyCacheView(), DestroyExceptionInfo(), DestroyRandomInfo(), DestroySplayTree(), DestroyString(), _FxInfo::exception, _FxInfo::expression, GetImageListLength(), _FxInfo::images, _FxInfo::random_info, RelinquishMagickMemory(), _FxInfo::symbols, and _FxInfo::view.
Referenced by DestroyFxThreadSet(), GetImageProperty(), and InterpretImageProperties().
FxEvaluateChannelExpression()
MagickExport MagickBooleanType FxEvaluateChannelExpression (FxInfo * fx_info, const ChannelType, const ssize_t, const ssize_t, double * alpha, ExceptionInfo * exception)
References _FxInfo::expression, FxEvaluateSubexpression(), MagickFalse, MagickTrue, OptionError, and _ExceptionInfo::severity.
Referenced by FxEvaluateExpression(), FxImageChannel(), FxPreprocessExpression(), GetImageProperty(), and InterpretImageProperties().
FxEvaluateExpression()
MagickExport MagickBooleanType FxEvaluateExpression (FxInfo * , double * , ExceptionInfo *)