MagickCore: fx.h File Reference
fx.h File Reference
#include "magick/draw.h"
Functions
MagickExport Image * FxImage (const Image *, const char *, ExceptionInfo *)
MagickExport Image * FxImageChannel (const Image *, const ChannelType, const char *, ExceptionInfo *)
Function Documentation
FxImage()
MagickExport Image * FxImage (const Image * , const char * , ExceptionInfo *)
FxImageChannel()
MagickExport Image * FxImageChannel (const Image * image, const ChannelType, const char * expression, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireFxThreadSet(), BlueChannel, ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyFxThreadSet(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, FxEvaluateChannelExpression(), FxImageTag, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetOpenMPThreadId(), GreenChannel, IndexChannel, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OpacityChannel, _Image::progress_monitor, QuantumRange, RedChannel, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by FxImage().