MagickCore: gem-private.h File Reference
gem-private.h File Reference
#include "magick/pixel-accessor.h"
#include "magick/visual-effects.h"
Macros
#define D65X 0.950456
#define D65Y 1.0
#define D65Z 1.088754
#define CIEEpsilon (216.0/24389.0)
#define CIEK (24389.0/27.0)
Functions
static void ConvertLabToXYZ (const double L, const double a, const double b, double *X, double *Y, double *Z)
static void ConvertXYZToLuv (const double X, const double Y, const double Z, double *L, double *u, double *v)
static void ConvertRGBToXYZ (const Quantum red, const Quantum green, const Quantum blue, double *X, double *Y, double *Z)
static void ConvertXYZToLab (const double X, const double Y, const double Z, double *L, double *a, double *b)
static void ConvertLuvToXYZ (const double L, const double u, const double v, double *X, double *Y, double *Z)
static void ConvertXYZToRGB (const double X, const double Y, const double Z, Quantum *red, Quantum *green, Quantum *blue)
Macro Definition Documentation
CIEEpsilon
#define CIEEpsilon (216.0/24389.0)
CIEK
#define CIEK (24389.0/27.0)
D65X
#define D65X 0.950456
D65Y
#define D65Y 1.0
D65Z
#define D65Z 1.088754
Function Documentation
ConvertLabToXYZ()
static void ConvertLabToXYZ (const double L, const double a, const double b, double * X, double * Y, double * Z) inline static
References CIEEpsilon, CIEK, D65X, D65Y, and D65Z.
Referenced by ConvertLabToRGB(), and ConvertLCHabToXYZ().
ConvertLuvToXYZ()
static void ConvertLuvToXYZ (const double L, const double u, const double v, double * X, double * Y, double * Z) inline static
References CIEEpsilon, CIEK, D65X, D65Y, D65Z, and PerceptibleReciprocal().
Referenced by ConvertLCHuvToXYZ(), and ConvertLuvToRGB().
ConvertRGBToXYZ()
static void ConvertRGBToXYZ (const Quantum red, const Quantum green, const Quantum blue, double * X, double * Y, double * Z) inline static
References DecodePixelGamma(), and QuantumScale.
Referenced by ConvertRGBToLab(), ConvertRGBToLCHab(), ConvertRGBToLCHuv(), ConvertRGBToLMS(), ConvertRGBToLuv(), ConvertRGBToxyY(), and RGBTransformImage().
ConvertXYZToLab()
static void ConvertXYZToLab (const double X, const double Y, const double Z, double * L, double * a, double * b) inline static
References CIEEpsilon, CIEK, D65X, D65Y, and D65Z.
Referenced by ConvertRGBToLab(), and ConvertXYZToLCHab().
ConvertXYZToLuv()
static void ConvertXYZToLuv (const double X, const double Y, const double Z, double * L, double * u, double * v) inline static
References CIEEpsilon, CIEK, D65X, D65Y, D65Z, and PerceptibleReciprocal().
Referenced by ConvertRGBToLuv(), and ConvertXYZToLCHuv().
ConvertXYZToRGB()
static void ConvertXYZToRGB (const double X, const double Y, const double Z, Quantum * red, Quantum * green, Quantum * blue) inline static
References ClampToQuantum(), EncodePixelGamma(), and QuantumRange.
Referenced by ConvertLabToRGB(), ConvertLCHabToRGB(), ConvertLCHuvToRGB(), ConvertLMSToRGB(), ConvertLuvToRGB(), ConvertxyYToRGB(), and TransformRGBImage().