MagickCore: gem.h File Reference
gem.h File Reference
#include "magick/random_.h"
#include "magick/visual-effects.h"
Functions
MagickExport double ExpandAffine (const AffineMatrix *)
MagickExport double GenerateDifferentialNoise (RandomInfo *, const Quantum, const NoiseType, const MagickRealType)
MagickExport size_t GetOptimalKernelWidth (const double, const double)
MagickExport size_t GetOptimalKernelWidth1D (const double, const double)
MagickExport size_t GetOptimalKernelWidth2D (const double, const double)
MagickExport void ConvertHCLToRGB (const double, const double, const double, Quantum *, Quantum *, Quantum *)
MagickExport void ConvertHCLpToRGB (const double, const double, const double, Quantum *, Quantum *, Quantum *)
MagickExport void ConvertHSBToRGB (const double, const double, const double, Quantum *, Quantum *, Quantum *)
MagickExport void ConvertHSIToRGB (const double, const double, const double, Quantum *, Quantum *, Quantum *)
MagickExport void ConvertHSLToRGB (const double, const double, const double, Quantum *, Quantum *, Quantum *)
MagickExport void ConvertHSVToRGB (const double, const double, const double, Quantum *, Quantum *, Quantum *)
MagickExport void ConvertHWBToRGB (const double, const double, const double, Quantum *, Quantum *, Quantum *)
MagickExport void ConvertLCHabToRGB (const double, const double, const double, Quantum *, Quantum *, Quantum *)
MagickExport void ConvertLCHuvToRGB (const double, const double, const double, Quantum *, Quantum *, Quantum *)
MagickExport void ConvertRGBToHCL (const Quantum, const Quantum, const Quantum, double *, double *, double *)
MagickExport void ConvertRGBToHCLp (const Quantum, const Quantum, const Quantum, double *, double *, double *)
MagickExport void ConvertRGBToHSB (const Quantum, const Quantum, const Quantum, double *, double *, double *)
MagickExport void ConvertRGBToHSI (const Quantum, const Quantum, const Quantum, double *, double *, double *)
MagickExport void ConvertRGBToHSL (const Quantum, const Quantum, const Quantum, double *, double *, double *)
MagickExport void ConvertRGBToHSV (const Quantum, const Quantum, const Quantum, double *, double *, double *)
MagickExport void ConvertRGBToHWB (const Quantum, const Quantum, const Quantum, double *, double *, double *)
MagickExport void ConvertRGBToLCHab (const Quantum, const Quantum, const Quantum, double *, double *, double *)
MagickExport void ConvertRGBToLCHuv (const Quantum, const Quantum, const Quantum, double *, double *, double *)
Function Documentation
ConvertHCLpToRGB()
MagickExport void ConvertHCLpToRGB (const double , const double , const double , Quantum * , Quantum * , Quantum *)
ConvertHCLToRGB()
MagickExport void ConvertHCLToRGB (const double , const double , const double , Quantum * , Quantum * , Quantum *)
ConvertHSBToRGB()
MagickExport void ConvertHSBToRGB (const double , const double , const double , Quantum * , Quantum * , Quantum *)
ConvertHSIToRGB()
MagickExport void ConvertHSIToRGB (const double , const double , const double , Quantum * , Quantum * , Quantum *)
ConvertHSLToRGB()
MagickExport void ConvertHSLToRGB (const double , const double , const double , Quantum * , Quantum * , Quantum *)
ConvertHSVToRGB()
MagickExport void ConvertHSVToRGB (const double , const double , const double , Quantum * , Quantum * , Quantum *)
ConvertHWBToRGB()
MagickExport void ConvertHWBToRGB (const double , const double , const double , Quantum * , Quantum * , Quantum *)
ConvertLCHabToRGB()
MagickExport void ConvertLCHabToRGB (const double , const double , const double , Quantum * , Quantum * , Quantum *)
ConvertLCHuvToRGB()
MagickExport void ConvertLCHuvToRGB (const double , const double , const double , Quantum * , Quantum * , Quantum *)
ConvertRGBToHCL()
MagickExport void ConvertRGBToHCL (const Quantum, const Quantum, const Quantum, double * , double * , double *)
ConvertRGBToHCLp()
MagickExport void ConvertRGBToHCLp (const Quantum, const Quantum, const Quantum, double * , double * , double *)
ConvertRGBToHSB()
MagickExport void ConvertRGBToHSB (const Quantum, const Quantum, const Quantum, double * , double * , double *)
ConvertRGBToHSI()
MagickExport void ConvertRGBToHSI (const Quantum, const Quantum, const Quantum, double * , double * , double *)
ConvertRGBToHSL()
MagickExport void ConvertRGBToHSL (const Quantum, const Quantum, const Quantum, double * , double * , double *)
ConvertRGBToHSV()
MagickExport void ConvertRGBToHSV (const Quantum, const Quantum, const Quantum, double * , double * , double *)
ConvertRGBToHWB()
MagickExport void ConvertRGBToHWB (const Quantum, const Quantum, const Quantum, double * , double * , double *)
ConvertRGBToLCHab()
MagickExport void ConvertRGBToLCHab (const Quantum, const Quantum, const Quantum, double * , double * , double *)
ConvertRGBToLCHuv()
MagickExport void ConvertRGBToLCHuv (const Quantum, const Quantum, const Quantum, double * luma, double * chroma, double * hue)
References ConvertRGBToXYZ(), and ConvertXYZToLCHuv().
Referenced by ModulateLCHuv(), and RGBTransformImage().
ExpandAffine()
MagickExport double ExpandAffine (const AffineMatrix *)
GenerateDifferentialNoise()
MagickExport double GenerateDifferentialNoise (RandomInfo * random_info, const Quantum, const NoiseType, const MagickRealType)
References GaussianNoise, GetPseudoRandomValue(), ImpulseNoise, LaplacianNoise, MagickEpsilon, MagickPI, MultiplicativeGaussianNoise, PerceptibleReciprocal(), PoissonNoise, QuantumRange, QuantumScale, random_info, RandomNoise, SigmaGaussian, SigmaImpulse, SigmaLaplacian, SigmaMultiplicativeGaussian, SigmaPoisson, SigmaRandom, SigmaUniform, TauGaussian, and UniformNoise.
Referenced by AddNoiseImageChannel(), and ApplyEvaluateOperator().
GetOptimalKernelWidth()
MagickExport size_t GetOptimalKernelWidth (const double , const double)
GetOptimalKernelWidth1D()
MagickExport size_t GetOptimalKernelWidth1D (const double , const double)
GetOptimalKernelWidth2D()
MagickExport size_t GetOptimalKernelWidth2D (const double radius, const double sigma)
References GetMagickModule, LogMagickEvent(), Magick2PI, MagickEpsilon, PerceptibleReciprocal(), QuantumScale, and TraceEvent.
Referenced by AcquireKernelBuiltIn(), AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), OilPaintImage(), SharpenImageChannel(), and StatisticImageChannel().