MagickCore: gem.c File Reference
gem.c File Reference
#include "magick/studio.h"
#include "magick/color-private.h"
#include "magick/draw.h"
#include "magick/gem.h"
#include "magick/gem-private.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/log.h"
#include "magick/memory_.h"
#include "magick/pixel-private.h"
#include "magick/quantum.h"
#include "magick/random_.h"
#include "magick/resize.h"
#include "magick/transform.h"
#include "magick/signature-private.h"
Macros
#define SigmaUniform (attenuate*0.015625)
#define SigmaGaussian (attenuate*0.015625)
#define SigmaImpulse (attenuate*0.1)
#define SigmaLaplacian (attenuate*0.0390625)
#define SigmaMultiplicativeGaussian (attenuate*0.5)
#define SigmaPoisson (attenuate*12.5)
#define SigmaRandom (attenuate)
#define TauGaussian (attenuate*0.078125)
Functions
MagickExport void ConvertHCLToRGB (const double hue, const double chroma, const double luma, Quantum *red, Quantum *green, Quantum *blue)
MagickExport void ConvertHCLpToRGB (const double hue, const double chroma, const double luma, Quantum *red, Quantum *green, Quantum *blue)
MagickExport void ConvertHSBToRGB (const double hue, const double saturation, const double brightness, Quantum *red, Quantum *green, Quantum *blue)
MagickExport void ConvertHSIToRGB (const double hue, const double saturation, const double intensity, Quantum *red, Quantum *green, Quantum *blue)
MagickExport void ConvertHSLToRGB (const double hue, const double saturation, const double lightness, Quantum *red, Quantum *green, Quantum *blue)
MagickExport void ConvertHSVToRGB (const double hue, const double saturation, const double value, Quantum *red, Quantum *green, Quantum *blue)
MagickExport void ConvertHWBToRGB (const double hue, const double whiteness, const double blackness, Quantum *red, Quantum *green, Quantum *blue)
static void ConvertLCHabToXYZ (const double luma, const double chroma, const double hue, double *X, double *Y, double *Z)
MagickExport void ConvertLCHabToRGB (const double luma, const double chroma, const double hue, Quantum *red, Quantum *green, Quantum *blue)
static void ConvertLCHuvToXYZ (const double luma, const double chroma, const double hue, double *X, double *Y, double *Z)
MagickExport void ConvertLCHuvToRGB (const double luma, const double chroma, const double hue, Quantum *red, Quantum *green, Quantum *blue)
MagickExport void ConvertRGBToHCL (const Quantum red, const Quantum green, const Quantum blue, double *hue, double *chroma, double *luma)
MagickExport void ConvertRGBToHCLp (const Quantum red, const Quantum green, const Quantum blue, double *hue, double *chroma, double *luma)
MagickExport void ConvertRGBToHSB (const Quantum red, const Quantum green, const Quantum blue, double *hue, double *saturation, double *brightness)
MagickExport void ConvertRGBToHSI (const Quantum red, const Quantum green, const Quantum blue, double *hue, double *saturation, double *intensity)
MagickExport void ConvertRGBToHSL (const Quantum red, const Quantum green, const Quantum blue, double *hue, double *saturation, double *lightness)
MagickExport void ConvertRGBToHSV (const Quantum red, const Quantum green, const Quantum blue, double *hue, double *saturation, double *value)
MagickExport void ConvertRGBToHWB (const Quantum red, const Quantum green, const Quantum blue, double *hue, double *whiteness, double *blackness)
static void ConvertXYZToLCHab (const double X, const double Y, const double Z, double *luma, double *chroma, double *hue)
MagickExport void ConvertRGBToLCHab (const Quantum red, const Quantum green, const Quantum blue, double *luma, double *chroma, double *hue)
static void ConvertXYZToLCHuv (const double X, const double Y, const double Z, double *luma, double *chroma, double *hue)
MagickExport void ConvertRGBToLCHuv (const Quantum red, const Quantum green, const Quantum blue, double *luma, double *chroma, double *hue)
MagickExport double ExpandAffine (const AffineMatrix *affine)
MagickExport double GenerateDifferentialNoise (RandomInfo *random_info, const Quantum pixel, const NoiseType noise_type, const MagickRealType attenuate)
MagickExport size_t GetOptimalKernelWidth1D (const double radius, const double sigma)
MagickExport size_t GetOptimalKernelWidth2D (const double radius, const double sigma)
MagickExport size_t GetOptimalKernelWidth (const double radius, const double sigma)
Macro Definition Documentation
SigmaGaussian
#define SigmaGaussian (attenuate*0.015625)
SigmaImpulse
#define SigmaImpulse (attenuate*0.1)
SigmaLaplacian
#define SigmaLaplacian (attenuate*0.0390625)
SigmaMultiplicativeGaussian
#define SigmaMultiplicativeGaussian (attenuate*0.5)
SigmaPoisson
#define SigmaPoisson (attenuate*12.5)
SigmaRandom
#define SigmaRandom (attenuate)
SigmaUniform
#define SigmaUniform (attenuate*0.015625)
TauGaussian
#define TauGaussian (attenuate*0.078125)
Function Documentation
ConvertHCLpToRGB()
MagickExport void ConvertHCLpToRGB (const double hue, const double chroma, const double luma, Quantum * red, Quantum * green, Quantum * blue)
References ClampToQuantum(), and QuantumRange.
Referenced by ModulateHCLp(), and TransformRGBImage().
ConvertHCLToRGB()
MagickExport void ConvertHCLToRGB (const double hue, const double chroma, const double luma, Quantum * red, Quantum * green, Quantum * blue)
References ClampToQuantum(), and QuantumRange.
Referenced by ModulateHCL(), QueryMagickColorCompliance(), and TransformRGBImage().
ConvertHSBToRGB()
MagickExport void ConvertHSBToRGB (const double hue, const double saturation, const double brightness, Quantum * red, Quantum * green, Quantum * blue)
References ClampToQuantum(), MagickEpsilon, and QuantumRange.
Referenced by Contrast(), ModulateHSB(), QueryMagickColorCompliance(), and TransformRGBImage().
ConvertHSIToRGB()
MagickExport void ConvertHSIToRGB (const double hue, const double saturation, const double intensity, Quantum * red, Quantum * green, Quantum * blue)
References ClampToQuantum(), MagickPI, and QuantumRange.
Referenced by ModulateHSI(), and TransformRGBImage().
ConvertHSLToRGB()
MagickExport void ConvertHSLToRGB (const double hue, const double saturation, const double lightness, Quantum * red, Quantum * green, Quantum * blue)
References ClampToQuantum(), and QuantumRange.
Referenced by ModulateHSL(), QueryMagickColorCompliance(), and TransformRGBImage().
ConvertHSVToRGB()
MagickExport void ConvertHSVToRGB (const double hue, const double saturation, const double value, Quantum * red, Quantum * green, Quantum * blue)
References ClampToQuantum(), and QuantumRange.
Referenced by ModulateHSV(), QueryMagickColorCompliance(), and TransformRGBImage().
ConvertHWBToRGB()
MagickExport void ConvertHWBToRGB (const double hue, const double whiteness, const double blackness, Quantum * red, Quantum * green, Quantum * blue)
References CastDoubleToLong(), ClampToQuantum(), MagickEpsilon, and QuantumRange.
Referenced by ModulateHWB(), QueryMagickColorCompliance(), and TransformRGBImage().
ConvertLCHabToRGB()
MagickExport void ConvertLCHabToRGB (const double luma, const double chroma, const double hue, Quantum * red, Quantum * green, Quantum * blue)
References ConvertLCHabToXYZ(), and ConvertXYZToRGB().
Referenced by ModulateLCHab(), and TransformRGBImage().
ConvertLCHabToXYZ()
static void ConvertLCHabToXYZ (const double luma, const double chroma, const double hue, double * X, double * Y, double * Z) inline static
References ConvertLabToXYZ(), and MagickPI.
Referenced by ConvertLCHabToRGB().
ConvertLCHuvToRGB()
MagickExport void ConvertLCHuvToRGB (const double luma, const double chroma, const double hue, Quantum * red, Quantum * green, Quantum * blue)
References ConvertLCHuvToXYZ(), and ConvertXYZToRGB().
Referenced by ModulateLCHuv(), and TransformRGBImage().
ConvertLCHuvToXYZ()
static void ConvertLCHuvToXYZ (const double luma, const double chroma, const double hue, double * X, double * Y, double * Z) inline static
References ConvertLuvToXYZ(), and MagickPI.
Referenced by ConvertLCHuvToRGB().
ConvertRGBToHCL()
MagickExport void ConvertRGBToHCL (const Quantum red, const Quantum green, const Quantum blue, double * hue, double * chroma, double * luma)
References MagickEpsilon, MagickMax, MagickMin, and QuantumScale.
Referenced by ModulateHCL(), and RGBTransformImage().
ConvertRGBToHCLp()
MagickExport void ConvertRGBToHCLp (const Quantum red, const Quantum green, const Quantum blue, double * hue, double * chroma, double * luma)
References MagickEpsilon, MagickMax, MagickMin, and QuantumScale.
Referenced by ModulateHCLp(), and RGBTransformImage().
ConvertRGBToHSB()
MagickExport void ConvertRGBToHSB (const Quantum red, const Quantum green, const Quantum blue, double * hue, double * saturation, double * brightness)
References MagickEpsilon, and QuantumScale.
Referenced by Contrast(), ModulateHSB(), and RGBTransformImage().
ConvertRGBToHSI()
MagickExport void ConvertRGBToHSI (const Quantum red, const Quantum green, const Quantum blue, double * hue, double * saturation, double * intensity)
References MagickMin, MagickPI, and QuantumScale.
Referenced by ModulateHSI(), and RGBTransformImage().
ConvertRGBToHSL()
MagickExport void ConvertRGBToHSL (const Quantum red, const Quantum green, const Quantum blue, double * hue, double * saturation, double * lightness)
References MagickEpsilon, MagickMax, MagickMin, and QuantumScale.
Referenced by FxGetSymbol(), ModulateHSL(), and RGBTransformImage().
ConvertRGBToHSV()
MagickExport void ConvertRGBToHSV (const Quantum red, const Quantum green, const Quantum blue, double * hue, double * saturation, double * value)
References MagickEpsilon, MagickMax, MagickMin, and QuantumScale.
Referenced by ModulateHSV(), and RGBTransformImage().
ConvertRGBToHWB()
MagickExport void ConvertRGBToHWB (const Quantum red, const Quantum green, const Quantum blue, double * hue, double * whiteness, double * blackness)
References MagickEpsilon, MagickMax, MagickMin, and QuantumScale.
Referenced by ModulateHWB(), and RGBTransformImage().
ConvertRGBToLCHab()
MagickExport void ConvertRGBToLCHab (const Quantum red, const Quantum green, const Quantum blue, double * luma, double * chroma, double * hue)
References ConvertRGBToXYZ(), and ConvertXYZToLCHab().
Referenced by ModulateLCHab(), and RGBTransformImage().
ConvertRGBToLCHuv()
MagickExport void ConvertRGBToLCHuv (const Quantum red, const Quantum green, const Quantum blue, double * luma, double * chroma, double * hue)
References ConvertRGBToXYZ(), and ConvertXYZToLCHuv().
Referenced by ModulateLCHuv(), and RGBTransformImage().
ConvertXYZToLCHab()
static void ConvertXYZToLCHab (const double X, const double Y, const double Z, double * luma, double * chroma, double * hue) inline static
References ConvertXYZToLab(), and MagickPI.
Referenced by ConvertRGBToLCHab().
ConvertXYZToLCHuv()
static void ConvertXYZToLCHuv (const double X, const double Y, const double Z, double * luma, double * chroma, double * hue) inline static
References ConvertXYZToLuv(), and MagickPI.
Referenced by ConvertRGBToLCHuv().
ExpandAffine()
MagickExport double ExpandAffine (const AffineMatrix * affine)
References _AffineMatrix::rx, _AffineMatrix::ry, _AffineMatrix::sx, and _AffineMatrix::sy.
Referenced by DrawBoundingRectangles(), DrawDashPolygon(), DrawPolygonPrimitive(), DrawPrimitive(), RenderMVGContent(), RenderPostscript(), and TraceStrokePolygon().
GenerateDifferentialNoise()
MagickExport double GenerateDifferentialNoise (RandomInfo * random_info, const Quantum pixel, const NoiseType noise_type, const MagickRealType attenuate)
References GaussianNoise, GetPseudoRandomValue(), ImpulseNoise, LaplacianNoise, MagickEpsilon, MagickPI, MultiplicativeGaussianNoise, PerceptibleReciprocal(), PoissonNoise, QuantumRange, QuantumScale, random_info, RandomNoise, SigmaGaussian, SigmaImpulse, SigmaLaplacian, SigmaMultiplicativeGaussian, SigmaPoisson, SigmaRandom, SigmaUniform, TauGaussian, and UniformNoise.
Referenced by AddNoiseImageChannel(), and ApplyEvaluateOperator().
GetOptimalKernelWidth()
MagickExport size_t GetOptimalKernelWidth (const double radius, const double sigma)
References GetOptimalKernelWidth1D().
GetOptimalKernelWidth1D()
MagickExport size_t GetOptimalKernelWidth1D (const double radius, const double sigma)
References GetMagickModule, LogMagickEvent(), MagickEpsilon, MagickSQ2PI, PerceptibleReciprocal(), QuantumScale, and TraceEvent.
Referenced by AcquireKernelBuiltIn(), EdgeImage(), EmbossImage(), GetOptimalKernelWidth(), MotionBlurImageChannel(), SelectiveBlurImageChannel(), and SpreadImage().
GetOptimalKernelWidth2D()
MagickExport size_t GetOptimalKernelWidth2D (const double radius, const double sigma)
References GetMagickModule, LogMagickEvent(), Magick2PI, MagickEpsilon, PerceptibleReciprocal(), QuantumScale, and TraceEvent.
Referenced by AcquireKernelBuiltIn(), AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), OilPaintImage(), SharpenImageChannel(), and StatisticImageChannel().