MagickCore: geometry.c File Reference
geometry.c File Reference
#include "magick/studio.h"
#include "magick/constitute.h"
#include "magick/draw.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/geometry.h"
#include "magick/image-private.h"
#include "magick/memory_.h"
#include "magick/pixel-accessor.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/token.h"
Macros
#define MagickPageSize(name, geometry) { (name), sizeof(name)-1, (geometry) }
Functions
MagickExport MagickStatusType GetGeometry (const char *geometry, ssize_t *x, ssize_t *y, size_t *width, size_t *height)
MagickExport char * GetPageGeometry (const char *page_geometry)
MagickExport void GravityAdjustGeometry (const size_t width, const size_t height, const GravityType gravity, RectangleInfo *region)
MagickExport MagickBooleanType IsGeometry (const char *geometry)
MagickExport MagickBooleanType IsSceneGeometry (const char *geometry, const MagickBooleanType pedantic)
MagickExport MagickStatusType ParseAbsoluteGeometry (const char *geometry, RectangleInfo *region_info)
MagickExport MagickStatusType ParseAffineGeometry (const char *geometry, AffineMatrix *affine_matrix, ExceptionInfo *exception)
MagickExport MagickStatusType ParseGeometry (const char *geometry, GeometryInfo *geometry_info)
MagickExport MagickStatusType ParseGravityGeometry (const Image *image, const char *geometry, RectangleInfo *region_info, ExceptionInfo *exception)
MagickExport MagickStatusType ParseMetaGeometry (const char *geometry, ssize_t *x, ssize_t *y, size_t *width, size_t *height)
MagickExport MagickStatusType ParsePageGeometry (const Image *image, const char *geometry, RectangleInfo *region_info, ExceptionInfo *exception)
MagickExport MagickStatusType ParseRegionGeometry (const Image *image, const char *geometry, RectangleInfo *region_info, ExceptionInfo *exception)
MagickExport void SetGeometry (const Image *image, RectangleInfo *geometry)
MagickExport void SetGeometryInfo (GeometryInfo *geometry_info)
Macro Definition Documentation
MagickPageSize
#define MagickPageSize (name, geometry) { (name), sizeof(name)-1, (geometry) }
Function Documentation
GetGeometry()
MagickExport MagickStatusType GetGeometry (const char * geometry, ssize_t * x, ssize_t * y, size_t * width, size_t * height)
References AreaValue, AspectRatioValue, AspectValue, CopyMagickString(), DecimalValue, GreaterValue, HeightValue, LessValue, LocaleNCompare(), MaxTextExtent, MinimumValue, NoValue, PercentValue, SeparatorValue, StringToDouble(), WidthValue, XNegative, XValue, YNegative, and YValue.
Referenced by GetMontageGeometry(), GetPageGeometry(), MontageImageList(), ParseAbsoluteGeometry(), and ParseMetaGeometry().
GetPageGeometry()
MagickExport char * GetPageGeometry (const char * page_geometry)
References AcquireString(), ConcatenateMagickString(), CopyMagickString(), FormatLocaleString(), GetGeometry(), GetMagickModule, GreaterValue, _RectangleInfo::height, LocaleNCompare(), LogMagickEvent(), MagickPageSize, MaxTextExtent, TraceEvent, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by AcquireImage(), GetMagickProperty(), PostscriptGeometry(), SetImageProperty(), and SyncImageSettings().
GravityAdjustGeometry()
MagickExport void GravityAdjustGeometry (const size_t width, const size_t height, const GravityType gravity, RectangleInfo * region)
References CenterGravity, EastGravity, ForgetGravity, _RectangleInfo::height, NorthEastGravity, NorthGravity, NorthWestGravity, SouthEastGravity, SouthGravity, SouthWestGravity, StaticGravity, WestGravity, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by AppendImages(), GetEdgeBackgroundFactor(), ParseGravityGeometry(), SmushImages(), SmushXGap(), and SmushYGap().
IsGeometry()
MagickExport MagickBooleanType IsGeometry (const char * geometry)
References MagickFalse, MagickTrue, NoValue, and ParseGeometry().
Referenced by GetPathComponent(), OpenBlob(), and SetImageInfo().
IsSceneGeometry()
MagickExport MagickBooleanType IsSceneGeometry (const char * geometry, const MagickBooleanType pedantic)
References IsNaN, MAGICK_SSIZE_MAX, MAGICK_SSIZE_MIN, MagickFalse, MagickTrue, and StringToDouble().
Referenced by GetPathComponent(), ReadImage(), and SetImageInfo().
ParseAbsoluteGeometry()
MagickExport MagickStatusType ParseAbsoluteGeometry (const char * geometry, RectangleInfo * region_info)
References GetGeometry(), _RectangleInfo::height, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by AcquireImage(), CropToFitImage(), DistortImage(), GetEdgeBoundingBox(), GetMagickProperty(), GradientImage(), MontageImageList(), ParseGravityGeometry(), ParsePageGeometry(), ReadImage(), ResetImagePage(), SetImageProperty(), SyncImageSettings(), ThumbnailImage(), and WriteStreamImage().
ParseAffineGeometry()
MagickExport MagickStatusType ParseAffineGeometry (const char * geometry, AffineMatrix * affine_matrix, ExceptionInfo * exception)
References GetAffineMatrix(), GetMagickModule, GetNextToken(), MagickEpsilon, MaxTextExtent, NoValue, OptionError, _AffineMatrix::rx, _AffineMatrix::ry, StringToDouble(), _AffineMatrix::sx, _AffineMatrix::sy, ThrowMagickException(), _AffineMatrix::tx, _AffineMatrix::ty, XValue, and YValue.
ParseGeometry()
MagickExport MagickStatusType ParseGeometry (const char * geometry, GeometryInfo * geometry_info)
References AreaValue, AspectRatioValue, AspectValue, _GeometryInfo::chi, ChiNegative, ChiValue, CopyMagickString(), DecimalValue, GreaterValue, LessValue, LocaleNCompare(), MaxTextExtent, MinimumValue, NoValue, PercentValue, PerceptibleReciprocal(), _GeometryInfo::psi, PsiNegative, PsiValue, _GeometryInfo::rho, RhoValue, SeparatorValue, _GeometryInfo::sigma, SigmaValue, StringToDouble(), _GeometryInfo::xi, XiNegative, and XiValue.
Referenced by AcquireImage(), AnnotateImage(), BlackThresholdImageChannel(), ChannelThresholdImage(), ColorizeImage(), CompositeImageChannel(), ContrastStretchImage(), DrawBoundingRectangles(), FxGetSymbol(), GammaImage(), IsGeometry(), LevelImage(), ModulateImage(), ParseGravityGeometry(), ParseKernelArray(), ParseKernelName(), ParseMetaGeometry(), RandomThresholdImageChannel(), ReadImage(), RenderPostscript(), SampleImage(), ScaleGeometryKernelInfo(), SetImageProperty(), SigmoidalContrastImage(), SyncImageSettings(), ThresholdImageChannel(), TintImage(), and WhiteThresholdImageChannel().
ParseGravityGeometry()
MagickExport MagickStatusType ParseGravityGeometry (const Image * image, const char * geometry, RectangleInfo * region_info, ExceptionInfo * exception)
References AspectRatioValue, _Image::columns, GetMagickModule, _Image::gravity, GravityAdjustGeometry(), _RectangleInfo::height, NoValue, OptionError, _Image::page, ParseAbsoluteGeometry(), ParseGeometry(), PercentValue, _GeometryInfo::rho, RhoValue, _Image::rows, SetGeometry(), _GeometryInfo::sigma, SigmaValue, ThrowMagickException(), UndefinedGravity, _RectangleInfo::width, _PointInfo::x, XValue, _PointInfo::y, and YValue.
Referenced by CropImageToTiles(), DrawPrimitive(), and MontageImageList().
ParseMetaGeometry()
MagickExport MagickStatusType ParseMetaGeometry (const char * geometry, ssize_t * x, ssize_t * y, size_t * width, size_t * height)
References AreaValue, AspectRatioValue, AspectValue, CastDoubleToUnsigned(), GetGeometry(), GetMagickModule, GreaterValue, LessValue, LogMagickEvent(), MagickEpsilon, MagickMax, MinimumValue, NoValue, ParseGeometry(), PercentValue, PerceptibleReciprocal(), _GeometryInfo::rho, RhoValue, SetGeometryInfo(), _GeometryInfo::sigma, SigmaValue, TraceEvent, _PointInfo::x, and _PointInfo::y.
Referenced by GetMagickGeometry(), MontageImageList(), ParseImageGeometry(), ParsePageGeometry(), ParseRegionGeometry(), ParseSizeGeometry(), and PreviewImage().
ParsePageGeometry()
MagickExport MagickStatusType ParsePageGeometry (const Image * image, const char * geometry, RectangleInfo * region_info, ExceptionInfo * exception)
References _Image::columns, GetMagickModule, _RectangleInfo::height, HeightValue, NoValue, OptionError, _Image::page, ParseAbsoluteGeometry(), ParseMetaGeometry(), PercentValue, _Image::rows, SeparatorValue, SetGeometry(), ThrowMagickException(), _RectangleInfo::width, WidthValue, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by AnnotateImage(), and GetImageGeometry().
ParseRegionGeometry()
MagickExport MagickStatusType ParseRegionGeometry (const Image * image, const char * geometry, RectangleInfo * region_info, ExceptionInfo * exception)
References GetMagickModule, _RectangleInfo::height, NoValue, OptionError, ParseMetaGeometry(), SetGeometry(), ThrowMagickException(), _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by GetImageGeometry(), MontageImageList(), ReadImage(), and TransformImage().
SetGeometry()
MagickExport void SetGeometry (const Image * image, RectangleInfo * geometry)
References _Image::columns, _Image::debug, _Image::filename, GetMagickModule, _RectangleInfo::height, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::rows, _Image::signature, TraceEvent, and _RectangleInfo::width.
Referenced by AnnotateImage(), AppendImages(), DrawPrimitive(), ExtractSubimageFromImage(), GetEdgeBoundingBox(), GetSimilarityMetric(), KuwaharaImageChannel(), MontageImageList(), ParseGravityGeometry(), ParsePageGeometry(), ParseRegionGeometry(), ParseSizeGeometry(), PreviewImage(), ReadImage(), ShaveImage(), SimilarityMetricImage(), SmushImages(), SmushXGap(), and SmushYGap().
SetGeometryInfo()
MagickExport void SetGeometryInfo (GeometryInfo * geometry_info)
References GetMagickModule, LogMagickEvent(), and TraceEvent.
Referenced by AnnotateImage(), CompositeImageChannel(), ParseCSSColor(), ParseKernelArray(), ParseKernelName(), ParseMetaGeometry(), and ScaleGeometryKernelInfo().