MagickCore: geometry.h File Reference
geometry.h File Reference
Data Structures
struct _AffineMatrix
struct _GeometryInfo
struct _OffsetInfo
struct _RectangleInfo
Typedefs
typedef struct _AffineMatrix AffineMatrix
typedef struct _GeometryInfo GeometryInfo
typedef struct _OffsetInfo OffsetInfo
typedef struct _RectangleInfo RectangleInfo
Enumerations
enum GeometryFlags {
NoValue = 0x0000 , XValue = 0x0001 , XiValue = 0x0001 , YValue = 0x0002 ,
PsiValue = 0x0002 , WidthValue = 0x0004 , RhoValue = 0x0004 , HeightValue = 0x0008 ,
SigmaValue = 0x0008 , ChiValue = 0x0010 , XiNegative = 0x0020 , XNegative = 0x0020 ,
PsiNegative = 0x0040 , YNegative = 0x0040 , ChiNegative = 0x0080 , PercentValue = 0x1000 ,
AspectValue = 0x2000 , NormalizeValue = 0x2000 , LessValue = 0x4000 , GreaterValue = 0x8000 ,
MinimumValue = 0x10000 , CorrelateNormalizeValue = 0x10000 , AreaValue = 0x20000 , DecimalValue = 0x40000 ,
SeparatorValue = 0x80000 , AspectRatioValue = 0x100000 , AlphaValue = 0x200000 , AllValues = 0x7fffffff
}
enum GravityType {
UndefinedGravity , ForgetGravity = 0 , NorthWestGravity = 1 , NorthGravity = 2 ,
NorthEastGravity = 3 , WestGravity = 4 , CenterGravity = 5 , EastGravity = 6 ,
SouthWestGravity = 7 , SouthGravity = 8 , SouthEastGravity = 9 , StaticGravity = 10
}
Functions
MagickExport char * GetPageGeometry (const char *)
MagickExport MagickBooleanType IsGeometry (const char *)
MagickExport MagickBooleanType IsSceneGeometry (const char *, const MagickBooleanType)
MagickExport MagickStatusType GetGeometry (const char *, ssize_t *, ssize_t *, size_t *, size_t *)
MagickExport MagickStatusType ParseAbsoluteGeometry (const char *, RectangleInfo *)
MagickExport MagickStatusType ParseAffineGeometry (const char *, AffineMatrix *, ExceptionInfo *)
MagickExport MagickStatusType ParseGeometry (const char *, GeometryInfo *)
MagickExport MagickStatusType ParseGravityGeometry (const Image *, const char *, RectangleInfo *, ExceptionInfo *)
MagickExport MagickStatusType ParseMetaGeometry (const char *, ssize_t *, ssize_t *, size_t *, size_t *)
MagickExport MagickStatusType ParsePageGeometry (const Image *, const char *, RectangleInfo *, ExceptionInfo *)
MagickExport MagickStatusType ParseRegionGeometry (const Image *, const char *, RectangleInfo *, ExceptionInfo *)
MagickExport void GravityAdjustGeometry (const size_t, const size_t, const GravityType, RectangleInfo *)
MagickExport void SetGeometry (const Image *, RectangleInfo *)
MagickExport void SetGeometryInfo (GeometryInfo *)
Typedef Documentation
AffineMatrix
typedef struct _AffineMatrix AffineMatrix
GeometryInfo
typedef struct _GeometryInfo GeometryInfo
OffsetInfo
typedef struct _OffsetInfo OffsetInfo
RectangleInfo
typedef struct _RectangleInfo RectangleInfo
Enumeration Type Documentation
GeometryFlags
enum GeometryFlags
Enumerator
NoValue
XValue
XiValue
YValue
PsiValue
WidthValue
RhoValue
HeightValue
SigmaValue
ChiValue
XiNegative
XNegative
PsiNegative
YNegative
ChiNegative
PercentValue
AspectValue
NormalizeValue
LessValue
GreaterValue
MinimumValue
CorrelateNormalizeValue
AreaValue
DecimalValue
SeparatorValue
AspectRatioValue
AlphaValue
AllValues
GravityType
enum GravityType
Enumerator
UndefinedGravity
ForgetGravity
NorthWestGravity
NorthGravity
NorthEastGravity
WestGravity
CenterGravity
EastGravity
SouthWestGravity
SouthGravity
SouthEastGravity
StaticGravity
Function Documentation
GetGeometry()
MagickExport MagickStatusType GetGeometry (const char * , ssize_t * , ssize_t * , size_t * , size_t *)
GetPageGeometry()
MagickExport char * GetPageGeometry (const char * page_geometry)
References AcquireString(), ConcatenateMagickString(), CopyMagickString(), FormatLocaleString(), GetGeometry(), GetMagickModule, GreaterValue, _RectangleInfo::height, LocaleNCompare(), LogMagickEvent(), MagickPageSize, MaxTextExtent, TraceEvent, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by AcquireImage(), GetMagickProperty(), PostscriptGeometry(), SetImageProperty(), and SyncImageSettings().
GravityAdjustGeometry()
MagickExport void GravityAdjustGeometry (const size_t, const size_t, const GravityType, RectangleInfo *)
IsGeometry()
MagickExport MagickBooleanType IsGeometry (const char *)
IsSceneGeometry()
MagickExport MagickBooleanType IsSceneGeometry (const char * geometry, const MagickBooleanType)
References IsNaN, MAGICK_SSIZE_MAX, MAGICK_SSIZE_MIN, MagickFalse, MagickTrue, and StringToDouble().
Referenced by GetPathComponent(), ReadImage(), and SetImageInfo().
ParseAbsoluteGeometry()
MagickExport MagickStatusType ParseAbsoluteGeometry (const char * , RectangleInfo *)
ParseAffineGeometry()
MagickExport MagickStatusType ParseAffineGeometry (const char * , AffineMatrix * , ExceptionInfo *)
ParseGeometry()
MagickExport MagickStatusType ParseGeometry (const char * , GeometryInfo *)
ParseGravityGeometry()
MagickExport MagickStatusType ParseGravityGeometry (const Image * , const char * , RectangleInfo * , ExceptionInfo *)
ParseMetaGeometry()
MagickExport MagickStatusType ParseMetaGeometry (const char * , ssize_t * , ssize_t * , size_t * , size_t *)
ParsePageGeometry()
MagickExport MagickStatusType ParsePageGeometry (const Image * , const char * , RectangleInfo * , ExceptionInfo *)
ParseRegionGeometry()
MagickExport MagickStatusType ParseRegionGeometry (const Image * image, const char * geometry, RectangleInfo * region_info, ExceptionInfo * exception)
References GetMagickModule, _RectangleInfo::height, NoValue, OptionError, ParseMetaGeometry(), SetGeometry(), ThrowMagickException(), _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by GetImageGeometry(), MontageImageList(), ReadImage(), and TransformImage().
SetGeometry()
MagickExport void SetGeometry (const Image * , RectangleInfo *)
SetGeometryInfo()
MagickExport void SetGeometryInfo (GeometryInfo * geometry_info)
References GetMagickModule, LogMagickEvent(), and TraceEvent.
Referenced by AnnotateImage(), CompositeImageChannel(), ParseCSSColor(), ParseKernelArray(), ParseKernelName(), ParseMetaGeometry(), and ScaleGeometryKernelInfo().