MagickCore: hashmap.h File Reference
hashmap.h File Reference
Macros
#define SmallHashmapSize 17
#define MediumHashmapSize 509
#define LargeHashmapSize 8191
#define HugeHashmapSize 131071
Typedefs
typedef struct _HashmapInfo HashmapInfo
typedef struct _LinkedListInfo LinkedListInfo
Functions
MagickExport HashmapInfo * DestroyHashmap (HashmapInfo *)
MagickExport HashmapInfo * NewHashmap (const size_t, size_t(*)(const void *), MagickBooleanType(*)(const void *, const void *), void *(*)(void *), void *(*)(void *))
MagickExport LinkedListInfo * DestroyLinkedList (LinkedListInfo *, void *(*)(void *))
MagickExport LinkedListInfo * NewLinkedList (const size_t)
MagickExport MagickBooleanType AppendValueToLinkedList (LinkedListInfo *, const void *)
MagickExport MagickBooleanType CompareHashmapString (const void *, const void *)
MagickExport MagickBooleanType CompareHashmapStringInfo (const void *, const void *)
MagickExport MagickBooleanType InsertValueInLinkedList (LinkedListInfo *, const size_t, const void *)
MagickExport MagickBooleanType InsertValueInSortedLinkedList (LinkedListInfo *, int(*)(const void *, const void *), void **, const void *)
MagickExport MagickBooleanType IsHashmapEmpty (const HashmapInfo *)
MagickExport MagickBooleanType IsLinkedListEmpty (const LinkedListInfo *)
MagickExport MagickBooleanType LinkedListToArray (LinkedListInfo *, void **)
MagickExport MagickBooleanType PutEntryInHashmap (HashmapInfo *, const void *, const void *)
MagickExport size_t GetNumberOfElementsInLinkedList (const LinkedListInfo *)
MagickExport size_t GetNumberOfEntriesInHashmap (const HashmapInfo *)
MagickExport size_t HashPointerType (const void *)
MagickExport size_t HashStringType (const void *)
MagickExport size_t HashStringInfoType (const void *)
MagickExport void ClearLinkedList (LinkedListInfo *, void *(*)(void *))
MagickExport void * GetLastValueInLinkedList (LinkedListInfo *)
MagickExport void * GetNextKeyInHashmap (HashmapInfo *)
MagickExport void * GetNextValueInHashmap (HashmapInfo *)
MagickExport void * GetNextValueInLinkedList (LinkedListInfo *)
MagickExport void * GetValueFromHashmap (HashmapInfo *, const void *)
MagickExport void * GetValueFromLinkedList (LinkedListInfo *, const size_t)
MagickExport void * RemoveElementByValueFromLinkedList (LinkedListInfo *, const void *)
MagickExport void * RemoveElementFromLinkedList (LinkedListInfo *, const size_t)
MagickExport void * RemoveEntryFromHashmap (HashmapInfo *, const void *)
MagickExport void * RemoveLastElementFromLinkedList (LinkedListInfo *)
MagickExport void ResetHashmapIterator (HashmapInfo *)
MagickExport void ResetLinkedListIterator (LinkedListInfo *)
Macro Definition Documentation
HugeHashmapSize
#define HugeHashmapSize 131071
LargeHashmapSize
#define LargeHashmapSize 8191
MediumHashmapSize
#define MediumHashmapSize 509
SmallHashmapSize
#define SmallHashmapSize 17
Typedef Documentation
HashmapInfo
typedef struct _HashmapInfo HashmapInfo
LinkedListInfo
typedef struct _LinkedListInfo LinkedListInfo
Function Documentation
AppendValueToLinkedList()
MagickExport MagickBooleanType AppendValueToLinkedList (LinkedListInfo * , const void *)
ClearLinkedList()
MagickExport void ClearLinkedList (LinkedListInfo * , void * *)(void *)
CompareHashmapString()
MagickExport MagickBooleanType CompareHashmapString (const void * , const void *)
CompareHashmapStringInfo()
MagickExport MagickBooleanType CompareHashmapStringInfo (const void * , const void *)
DestroyHashmap()
MagickExport HashmapInfo * DestroyHashmap (HashmapInfo *)
DestroyLinkedList()
MagickExport LinkedListInfo * DestroyLinkedList (LinkedListInfo * , void * *)(void *)
GetLastValueInLinkedList()
MagickExport void * GetLastValueInLinkedList (LinkedListInfo *)
GetNextKeyInHashmap()
MagickExport void * GetNextKeyInHashmap (HashmapInfo *)
GetNextValueInHashmap()
MagickExport void * GetNextValueInHashmap (HashmapInfo *)
GetNextValueInLinkedList()
MagickExport void * GetNextValueInLinkedList (LinkedListInfo *)
GetNumberOfElementsInLinkedList()
MagickExport size_t GetNumberOfElementsInLinkedList (const LinkedListInfo *)
GetNumberOfEntriesInHashmap()
MagickExport size_t GetNumberOfEntriesInHashmap (const HashmapInfo *)
GetValueFromHashmap()
MagickExport void * GetValueFromHashmap (HashmapInfo * , const void *)
GetValueFromLinkedList()
MagickExport void * GetValueFromLinkedList (LinkedListInfo * , const size_t)
HashPointerType()
MagickExport size_t HashPointerType (const void *)
HashStringInfoType()
MagickExport size_t HashStringInfoType (const void * string_info)
References AcquireSignatureInfo(), DestroySignatureInfo(), FinalizeSignature(), GetSignatureDigest(), GetStringInfoDatum(), and UpdateSignature().
HashStringType()
MagickExport size_t HashStringType (const void *)
InsertValueInLinkedList()
MagickExport MagickBooleanType InsertValueInLinkedList (LinkedListInfo * , const size_t, const void *)
InsertValueInSortedLinkedList()
MagickExport MagickBooleanType InsertValueInSortedLinkedList (LinkedListInfo * , int(*)(const void *, const void *) , void ** , const void *)
IsHashmapEmpty()
MagickExport MagickBooleanType IsHashmapEmpty (const HashmapInfo *)
IsLinkedListEmpty()
MagickExport MagickBooleanType IsLinkedListEmpty (const LinkedListInfo *)
LinkedListToArray()
MagickExport MagickBooleanType LinkedListToArray (LinkedListInfo * , void **)
NewHashmap()
MagickExport HashmapInfo * NewHashmap (const size_t, size_t(*)(const void *) , MagickBooleanType(*)(const void *, const void *) , void * *)(void *, void * *)(void *)
NewLinkedList()
MagickExport LinkedListInfo * NewLinkedList (const size_t)
References AcquireMagickMemory(), AllocateSemaphoreInfo(), _LinkedListInfo::capacity, _LinkedListInfo::elements, _LinkedListInfo::head, MagickCoreSignature, _LinkedListInfo::next, ResourceLimitFatalError, _LinkedListInfo::semaphore, _LinkedListInfo::signature, _LinkedListInfo::tail, and ThrowFatalException.
Referenced by AcquireColorCache(), AcquireConfigureCache(), AcquireDelegateCache(), AcquireMagicCache(), AcquireMimeCache(), AcquirePolicyCache(), GetConfigureOptions(), GetConfigurePaths(), GetExceptionInfo(), GetLocaleOptions(), IncreaseHashmapCapacity(), InitializeExceptionInfo(), and PutEntryInHashmap().
PutEntryInHashmap()
MagickExport MagickBooleanType PutEntryInHashmap (HashmapInfo * hashmap_info, const void * key, const void * value)
References AcquireMagickMemory(), _HashmapInfo::capacity, _HashmapInfo::compare, _LinkedListInfo::elements, _HashmapInfo::entries, GetNextValueInLinkedList(), _EntryInfo::hash, _HashmapInfo::hash, _LinkedListInfo::head, IncreaseHashmapCapacity(), InsertValueInLinkedList(), _EntryInfo::key, LockSemaphoreInfo(), MagickCoreSignature, MagickFalse, MagickTrue, _HashmapInfo::map, NewLinkedList(), _LinkedListInfo::next, _HashmapInfo::relinquish_key, _HashmapInfo::relinquish_value, RelinquishMagickMemory(), RemoveElementFromLinkedList(), _HashmapInfo::semaphore, _HashmapInfo::signature, UnlockSemaphoreInfo(), and _EntryInfo::value.
RemoveElementByValueFromLinkedList()
MagickExport void * RemoveElementByValueFromLinkedList (LinkedListInfo * , const void *)
RemoveElementFromLinkedList()
MagickExport void * RemoveElementFromLinkedList (LinkedListInfo * , const size_t)
RemoveEntryFromHashmap()
MagickExport void * RemoveEntryFromHashmap (HashmapInfo * , const void *)
RemoveLastElementFromLinkedList()
MagickExport void * RemoveLastElementFromLinkedList (LinkedListInfo *)
ResetHashmapIterator()
MagickExport void ResetHashmapIterator (HashmapInfo *)
ResetLinkedListIterator()
MagickExport void ResetLinkedListIterator (LinkedListInfo * list_info)
References _LinkedListInfo::head, LockSemaphoreInfo(), MagickCoreSignature, _LinkedListInfo::next, _LinkedListInfo::semaphore, _LinkedListInfo::signature, and UnlockSemaphoreInfo().
Referenced by CatchException(), CheckEventLogging(), GetColorCompliance(), GetColorInfoList(), GetColorList(), GetConfigureInfo(), GetConfigureInfoList(), GetConfigureList(), GetConfigureOptions(), GetDelegateInfo(), GetDelegateInfoList(), GetDelegateList(), GetLocaleOptions(), GetLogInfo(), GetLogInfoList(), GetLogList(), GetMagicInfo(), GetMagicInfoList(), GetMagicList(), GetMimeInfo(), GetMimeInfoList(), GetMimeList(), GetPolicyInfo(), GetPolicyInfoList(), GetPolicyList(), InheritException(), IsRightsAuthorized(), QueryMagickColorname(), and SetMagickSecurityPolicy().