MagickCore: histogram.h File Reference
histogram.h File Reference
Data Structures
struct _ColorPacket
Typedefs
typedef struct _ColorPacket ColorPacket
Functions
MagickExport ColorPacket * GetImageHistogram (const Image *, size_t *, ExceptionInfo *)
MagickExport Image * UniqueImageColors (const Image *, ExceptionInfo *)
MagickExport MagickBooleanType IdentifyPaletteImage (const Image *, ExceptionInfo *)
MagickExport MagickBooleanType IsHistogramImage (const Image *, ExceptionInfo *)
MagickExport MagickBooleanType IsPaletteImage (const Image *, ExceptionInfo *)
MagickExport MagickBooleanType MinMaxStretchImage (Image *, const ChannelType, const double, const double)
MagickExport size_t GetNumberColors (const Image *, FILE *, ExceptionInfo *)
Typedef Documentation
ColorPacket
typedef struct _ColorPacket ColorPacket
Function Documentation
GetImageHistogram()
MagickExport ColorPacket * GetImageHistogram (const Image * image, size_t * number_colors, ExceptionInfo * exception)
References AcquireQuantumMemory(), ClassifyImageColors(), _CubeInfo::colors, DefineImageHistogram(), DestroyCubeInfo(), _Image::filename, GetMagickModule, ResourceLimitError, _CubeInfo::root, and ThrowMagickException().
Referenced by GetNumberColors().
GetNumberColors()
MagickExport size_t GetNumberColors (const Image * image, FILE * file, ExceptionInfo * exception)
References BlueChannel, ClassifyImageColors(), CMYKColorspace, _CubeInfo::colors, _MagickPixelPacket::colorspace, ConcatenateColorComponent(), ConcatenateMagickString(), CopyMagickString(), _ColorPacket::count, DestroyCubeInfo(), FormatLocaleFile(), GetColorTuple(), GetImageHistogram(), GetMagickPixelPacket(), GreenChannel, HistogramCompare(), HistogramImageTag, _ColorPacket::index, IndexChannel, MagickFalse, MagickTrue, _MagickPixelPacket::matte, MaxTextExtent, NoCompliance, OpacityChannel, _ColorPacket::pixel, _Image::progress_monitor, QueryMagickColorname(), RedChannel, RelinquishMagickMemory(), SetImageProgress(), SetMagickPixelPacket(), and SVGCompliance.
Referenced by GetImageQuantizeError(), GetMagickProperty(), GetMagickPropertyLetter(), and IdentifyImage().
IdentifyPaletteImage()
MagickExport MagickBooleanType IdentifyPaletteImage (const Image * , ExceptionInfo *)
IsHistogramImage()
MagickExport MagickBooleanType IsHistogramImage (const Image * , ExceptionInfo *)
IsPaletteImage()
MagickExport MagickBooleanType IsPaletteImage (const Image * , ExceptionInfo *)
MinMaxStretchImage()
MagickExport MagickBooleanType MinMaxStretchImage (Image * image, const ChannelType, const double black_value, const double white_value)
References BlueChannel, CMYKColorspace, _Image::colorspace, _Image::exception, GetImageChannelRange(), GreenChannel, IndexChannel, LevelImageChannel(), MagickEpsilon, MagickFalse, MagickTrue, _Image::matte, OpacityChannel, RedChannel, and SyncChannels.
Referenced by AutoLevelImageChannel().
UniqueImageColors()
MagickExport Image * UniqueImageColors (const Image * image, ExceptionInfo * exception)
References AcquireVirtualCacheView(), ClassifyImageColors(), CloneImage(), _CubeInfo::colors, DestroyCacheView(), DestroyCubeInfo(), DestroyImage(), DirectClass, _Image::exception, InheritException(), MagickFalse, MagickTrue, _CubeInfo::root, SetImageStorageClass(), and UniqueColorsToImage().