MagickCore: histogram.c File Reference
histogram.c File Reference
#include "magick/studio.h"
#include "magick/cache-view.h"
#include "magick/color-private.h"
#include "magick/enhance.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/hashmap.h"
#include "magick/histogram.h"
#include "magick/image.h"
#include "magick/list.h"
#include "magick/memory_.h"
#include "magick/monitor-private.h"
#include "magick/pixel-private.h"
#include "magick/prepress.h"
#include "magick/quantize.h"
#include "magick/registry.h"
#include "magick/semaphore.h"
#include "magick/splay-tree.h"
#include "magick/statistic.h"
#include "magick/string_.h"
Data Structures
struct _NodeInfo
struct _Nodes
struct _CubeInfo
Macros
#define MaxTreeDepth 8
#define NodesInAList 1536
#define EvaluateImageTag " Compute image colors... "
#define MaximumUniqueColors 1024
#define HistogramImageTag "Histogram/Image"
#define UniqueColorsImageTag "UniqueColors/Image"
Typedefs
typedef struct _NodeInfo NodeInfo
typedef struct _Nodes Nodes
typedef struct _CubeInfo CubeInfo
Functions
static CubeInfo * GetCubeInfo (void)
static NodeInfo * GetNodeInfo (CubeInfo *, const size_t)
static void DestroyColorCube (const Image *, NodeInfo *)
static size_t ColorToNodeId (const Image *image, const MagickPixelPacket *pixel, size_t index)
static MagickBooleanType IsMagickColorMatch (const MagickPixelPacket *p, const MagickPixelPacket *q)
static CubeInfo * ClassifyImageColors (const Image *image, ExceptionInfo *exception)
static void DefineImageHistogram (const Image *image, NodeInfo *node_info, ColorPacket **histogram)
static CubeInfo * DestroyCubeInfo (const Image *image, CubeInfo *cube_info)
MagickExport ColorPacket * GetImageHistogram (const Image *image, size_t *number_colors, ExceptionInfo *exception)
static MagickBooleanType CheckImageColors (const Image *image, ExceptionInfo *exception, size_t max_colors)
MagickExport MagickBooleanType IdentifyPaletteImage (const Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType IsHistogramImage (const Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType IsPaletteImage (const Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType MinMaxStretchImage (Image *image, const ChannelType channel, const double black_value, const double white_value)
static int HistogramCompare (const void *x, const void *y)
MagickExport size_t GetNumberColors (const Image *image, FILE *file, ExceptionInfo *exception)
static void UniqueColorsToImage (Image *unique_image, CacheView *unique_view, CubeInfo *cube_info, const NodeInfo *node_info, ExceptionInfo *exception)
MagickExport Image * UniqueImageColors (const Image *image, ExceptionInfo *exception)
Macro Definition Documentation
EvaluateImageTag
#define EvaluateImageTag " Compute image colors... "
HistogramImageTag
#define HistogramImageTag "Histogram/Image"
MaximumUniqueColors
#define MaximumUniqueColors 1024
MaxTreeDepth
#define MaxTreeDepth 8
NodesInAList
#define NodesInAList 1536
UniqueColorsImageTag
#define UniqueColorsImageTag "UniqueColors/Image"
Typedef Documentation
CubeInfo
typedef struct _CubeInfo CubeInfo
NodeInfo
typedef struct _NodeInfo NodeInfo
Nodes
typedef struct _Nodes Nodes
Function Documentation
CheckImageColors()
static MagickBooleanType CheckImageColors (const Image * image, ExceptionInfo * exception, size_t max_colors) static
References AcquireQuantumMemory(), AcquireVirtualCacheView(), _NodeInfo::child, CMYKColorspace, _CubeInfo::colors, _Image::colors, _Image::colorspace, ColorToNodeId(), _Image::columns, _ColorPacket::count, DestroyCacheView(), DestroyCubeInfo(), _Image::filename, GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetCubeInfo(), GetMagickModule, GetMagickPixelPacket(), GetNodeInfo(), GetPixelIndex, _ColorPacket::index, IsMagickColorMatch(), _NodeInfo::list, MagickFalse, MagickTrue, MaxTreeDepth, _NodeInfo::number_unique, _ColorPacket::pixel, PseudoClass, ResizeQuantumMemory(), ResourceLimitError, _CubeInfo::root, _Image::rows, SetMagickPixelPacket(), _Image::storage_class, and ThrowMagickException().
Referenced by IdentifyPaletteImage().
ClassifyImageColors()
static CubeInfo * ClassifyImageColors (const Image * image, ExceptionInfo * exception) static
References AcquireQuantumMemory(), AcquireVirtualCacheView(), _NodeInfo::child, CMYKColorspace, _CubeInfo::colors, _Image::colorspace, ColorToNodeId(), _Image::columns, _ColorPacket::count, _Image::debug, DestroyCacheView(), EvaluateImageTag, _NodeInfo::extent, _Image::filename, GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetCubeInfo(), GetMagickModule, GetMagickPixelPacket(), GetNodeInfo(), GetPixelIndex, _ColorPacket::index, IsMagickColorMatch(), _NodeInfo::list, LogMagickEvent(), MagickCoreSignature, MagickFalse, MaxTreeDepth, _NodeInfo::number_unique, _ColorPacket::pixel, PseudoClass, ResizeQuantumMemory(), ResourceLimitError, _CubeInfo::root, _Image::rows, SetImageProgress(), SetMagickPixelPacket(), _Image::signature, _Image::storage_class, ThrowMagickException(), and TraceEvent.
Referenced by GetImageHistogram(), GetNumberColors(), and UniqueImageColors().
ColorToNodeId()
static size_t ColorToNodeId (const Image * image, const MagickPixelPacket * pixel, size_t index) inline static
References _MagickPixelPacket::blue, ClampToQuantum(), _MagickPixelPacket::green, MagickFalse, _Image::matte, _MagickPixelPacket::opacity, and _MagickPixelPacket::red.
Referenced by CheckImageColors(), ClassifyImageColors(), and IsHistogramImage().
DefineImageHistogram()
static void DefineImageHistogram (const Image * image, NodeInfo * node_info, ColorPacket ** histogram) static
References _NodeInfo::child, _ColorPacket::count, DefineImageHistogram(), _ColorPacket::index, _NodeInfo::level, _NodeInfo::list, MagickFalse, _Image::matte, MaxTreeDepth, _NodeInfo::number_unique, and _ColorPacket::pixel.
Referenced by DefineImageHistogram(), and GetImageHistogram().
DestroyColorCube()
static void DestroyColorCube (const Image * image, NodeInfo * node_info) static
References _NodeInfo::child, DestroyColorCube(), _NodeInfo::list, MagickFalse, _Image::matte, and RelinquishMagickMemory().
Referenced by DestroyColorCube(), and DestroyCubeInfo().
DestroyCubeInfo()
static CubeInfo * DestroyCubeInfo (const Image * image, CubeInfo * cube_info) static
References DestroyColorCube(), _Nodes::next, _CubeInfo::node_queue, RelinquishMagickMemory(), and _CubeInfo::root.
Referenced by CheckImageColors(), GetImageHistogram(), GetNumberColors(), IsHistogramImage(), and UniqueImageColors().
GetCubeInfo()
static CubeInfo * GetCubeInfo (void) static
References AcquireMagickMemory(), GetNodeInfo(), and _CubeInfo::root.
Referenced by CheckImageColors(), ClassifyImageColors(), and IsHistogramImage().
GetImageHistogram()
MagickExport ColorPacket * GetImageHistogram (const Image * image, size_t * number_colors, ExceptionInfo * exception)
References AcquireQuantumMemory(), ClassifyImageColors(), _CubeInfo::colors, DefineImageHistogram(), DestroyCubeInfo(), _Image::filename, GetMagickModule, ResourceLimitError, _CubeInfo::root, and ThrowMagickException().
Referenced by GetNumberColors().
GetNodeInfo()
static NodeInfo * GetNodeInfo (CubeInfo * cube_info, const size_t level) static
References AcquireMagickMemory(), _CubeInfo::free_nodes, _NodeInfo::level, _Nodes::next, _CubeInfo::node_info, _CubeInfo::node_queue, _Nodes::nodes, and NodesInAList.
Referenced by CheckImageColors(), ClassifyImageColors(), GetCubeInfo(), and IsHistogramImage().
GetNumberColors()
MagickExport size_t GetNumberColors (const Image * image, FILE * file, ExceptionInfo * exception)
References BlueChannel, ClassifyImageColors(), CMYKColorspace, _CubeInfo::colors, _MagickPixelPacket::colorspace, ConcatenateColorComponent(), ConcatenateMagickString(), CopyMagickString(), _ColorPacket::count, DestroyCubeInfo(), FormatLocaleFile(), GetColorTuple(), GetImageHistogram(), GetMagickPixelPacket(), GreenChannel, HistogramCompare(), HistogramImageTag, _ColorPacket::index, IndexChannel, MagickFalse, MagickTrue, _MagickPixelPacket::matte, MaxTextExtent, NoCompliance, OpacityChannel, _ColorPacket::pixel, _Image::progress_monitor, QueryMagickColorname(), RedChannel, RelinquishMagickMemory(), SetImageProgress(), SetMagickPixelPacket(), and SVGCompliance.
Referenced by GetImageQuantizeError(), GetMagickProperty(), GetMagickPropertyLetter(), and IdentifyImage().
HistogramCompare()
static int HistogramCompare (const void * x, const void * y) static
References _PixelPacket::blue, _ColorPacket::count, _PixelPacket::green, _ColorPacket::pixel, and _PixelPacket::red.
Referenced by GetNumberColors().
IdentifyPaletteImage()
MagickExport MagickBooleanType IdentifyPaletteImage (const Image * image, ExceptionInfo * exception)
References CheckImageColors(), _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
Referenced by IdentifyImageType().
IsHistogramImage()
MagickExport MagickBooleanType IsHistogramImage (const Image * image, ExceptionInfo * exception)
References AcquireQuantumMemory(), AcquireVirtualCacheView(), _NodeInfo::child, CMYKColorspace, _CubeInfo::colors, _Image::colors, _Image::colorspace, ColorToNodeId(), _Image::columns, _ColorPacket::count, _Image::debug, DestroyCacheView(), DestroyCubeInfo(), _Image::filename, GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetCubeInfo(), GetMagickModule, GetMagickPixelPacket(), GetNodeInfo(), GetPixelIndex, _ColorPacket::index, IsMagickColorMatch(), _NodeInfo::list, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, MaximumUniqueColors, MaxTreeDepth, _NodeInfo::number_unique, _ColorPacket::pixel, PseudoClass, ResizeQuantumMemory(), ResourceLimitError, _CubeInfo::root, _Image::rows, SetMagickPixelPacket(), _Image::signature, _Image::storage_class, ThrowMagickException(), and TraceEvent.
Referenced by IdentifyImage().
IsMagickColorMatch()
static MagickBooleanType IsMagickColorMatch (const MagickPixelPacket * p, const MagickPixelPacket * q) inline static
References AbsolutePixelValue(), _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, MagickEpsilon, MagickFalse, MagickTrue, _MagickPixelPacket::matte, _MagickPixelPacket::opacity, OpaqueOpacity, _MagickPixelPacket::red, and TransparentOpacity.
Referenced by CheckImageColors(), ClassifyImageColors(), and IsHistogramImage().
IsPaletteImage()
MagickExport MagickBooleanType IsPaletteImage (const Image * image, ExceptionInfo * exception)
References _Image::colors, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), magick_unreferenced, MagickCoreSignature, MagickFalse, MagickTrue, PseudoClass, _Image::signature, _Image::storage_class, and TraceEvent.
Referenced by CompressImageColormap(), and GetImageType().
MinMaxStretchImage()
MagickExport MagickBooleanType MinMaxStretchImage (Image * image, const ChannelType channel, const double black_value, const double white_value)
References BlueChannel, CMYKColorspace, _Image::colorspace, _Image::exception, GetImageChannelRange(), GreenChannel, IndexChannel, LevelImageChannel(), MagickEpsilon, MagickFalse, MagickTrue, _Image::matte, OpacityChannel, RedChannel, and SyncChannels.
Referenced by AutoLevelImageChannel().
UniqueColorsToImage()
static void UniqueColorsToImage (Image * unique_image, CacheView * unique_view, CubeInfo * cube_info, const NodeInfo * node_info, ExceptionInfo * exception) static
References _NodeInfo::child, CMYKColorspace, _CubeInfo::colors, _Image::colorspace, GetCacheViewAuthenticIndexQueue(), _ColorPacket::index, _NodeInfo::level, _NodeInfo::list, magick_restrict, MagickFalse, MagickTrue, _Image::matte, MaxTreeDepth, _NodeInfo::number_unique, _ColorPacket::pixel, _CubeInfo::progress, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), SetImageProgress(), SyncCacheViewAuthenticPixels(), UniqueColorsImageTag, UniqueColorsToImage(), and _CubeInfo::x.
Referenced by UniqueColorsToImage(), and UniqueImageColors().
UniqueImageColors()
MagickExport Image * UniqueImageColors (const Image * image, ExceptionInfo * exception)
References AcquireVirtualCacheView(), ClassifyImageColors(), CloneImage(), _CubeInfo::colors, DestroyCacheView(), DestroyCubeInfo(), DestroyImage(), DirectClass, _Image::exception, InheritException(), MagickFalse, MagickTrue, _CubeInfo::root, SetImageStorageClass(), and UniqueColorsToImage().