MagickCore: identify.c File Reference
identify.c File Reference
#include "magick/studio.h"
#include "magick/annotate.h"
#include "magick/artifact.h"
#include "magick/attribute.h"
#include "magick/blob.h"
#include "magick/cache.h"
#include "magick/client.h"
#include "magick/coder.h"
#include "magick/color.h"
#include "magick/configure.h"
#include "magick/constitute.h"
#include "magick/decorate.h"
#include "magick/delegate.h"
#include "magick/draw.h"
#include "magick/effect.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/feature.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/histogram.h"
#include "magick/identify.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/locale_.h"
#include "magick/log.h"
#include "magick/magic.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/module.h"
#include "magick/monitor.h"
#include "magick/montage.h"
#include "magick/option.h"
#include "magick/pixel-private.h"
#include "magick/prepress.h"
#include "magick/profile.h"
#include "magick/property.h"
#include "magick/quantize.h"
#include "magick/quantum.h"
#include "magick/random_.h"
#include "magick/registry.h"
#include "magick/resize.h"
#include "magick/resource_.h"
#include "magick/signature.h"
#include "magick/statistic.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/timer.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/version.h"
Macros
#define PrintFeature(feature)
#define FeaturesFormat
#define StatisticsFormat
Functions
static ChannelStatistics * GetLocationStatistics (const Image *image, const StatisticType type, ExceptionInfo *exception)
static ssize_t PrintChannelFeatures (FILE *file, const ChannelType channel, const char *name, const ChannelFeatures *channel_features)
static ssize_t PrintChannelLocations (FILE *file, const Image *image, const ChannelType channel, const char *name, const StatisticType type, const size_t max_locations, const ChannelStatistics *channel_statistics)
static ssize_t PrintChannelMoments (FILE *file, const ChannelType channel, const char *name, const double scale, const ChannelMoments *channel_moments)
static ssize_t PrintChannelPerceptualHash (FILE *file, const ChannelType channel, const char *name, const ChannelPerceptualHash *channel_phash)
static ssize_t PrintChannelStatistics (FILE *file, const ChannelType channel, const char *name, const double scale, const ChannelStatistics *channel_statistics)
MagickExport MagickBooleanType IdentifyImage (Image *image, FILE *file, const MagickBooleanType verbose)
Macro Definition Documentation
FeaturesFormat
#define FeaturesFormat
Value:
  "    %s:\n" \
  "      Angular Second Moment:\n" \
  "        %.*g, %.*g, %.*g, %.*g, %.*g\n" \
  "      Contrast:\n" \
  "        %.*g, %.*g, %.*g, %.*g, %.*g\n" \
  "      Correlation:\n" \
  "        %.*g, %.*g, %.*g, %.*g, %.*g\n" \
  "      Sum of Squares Variance:\n" \
  "        %.*g, %.*g, %.*g, %.*g, %.*g\n" \
  "      Inverse Difference Moment:\n" \
  "        %.*g, %.*g, %.*g, %.*g, %.*g\n" \
  "      Sum Average:\n" \
  "        %.*g, %.*g, %.*g, %.*g, %.*g\n" \
  "      Sum Variance:\n" \
  "        %.*g, %.*g, %.*g, %.*g, %.*g\n" \
  "      Sum Entropy:\n" \
  "        %.*g, %.*g, %.*g, %.*g, %.*g\n" \
  "      Entropy:\n" \
  "        %.*g, %.*g, %.*g, %.*g, %.*g\n" \
  "      Difference Variance:\n" \
  "        %.*g, %.*g, %.*g, %.*g, %.*g\n" \
  "      Difference Entropy:\n" \
  "        %.*g, %.*g, %.*g, %.*g, %.*g\n" \
  "      Information Measure of Correlation 1:\n" \
  "        %.*g, %.*g, %.*g, %.*g, %.*g\n" \
  "      Information Measure of Correlation 2:\n" \
  "        %.*g, %.*g, %.*g, %.*g, %.*g\n" \
  "      Maximum Correlation Coefficient:\n" \
  "        %.*g, %.*g, %.*g, %.*g, %.*g\n"
PrintFeature
#define PrintFeature (feature)
Value:
  GetMagickPrecision(),(feature)[0], \
  GetMagickPrecision(),(feature)[1], \
  GetMagickPrecision(),(feature)[2], \
  GetMagickPrecision(),(feature)[3], \
  GetMagickPrecision(),((feature)[0]+(feature)[1]+(feature)[2]+(feature)[3])/4.0 \
StatisticsFormat
#define StatisticsFormat
Value:
  "    %s:\n      min: %.*g  (%.*g)\n      " \
  "max: %.*g (%.*g)\n      mean: %.*g (%.*g)\n      " \
  "standard deviation: %.*g (%.*g)\n      kurtosis: %.*g\n      " \
  "skewness: %.*g\n      entropy: %.*g\n"
Function Documentation
GetLocationStatistics()
static ChannelStatistics * GetLocationStatistics (const Image * image, const StatisticType type, ExceptionInfo * exception) static
References AcquireQuantumMemory(), BlackChannel, BlueChannel, CMYKColorspace, _Image::colorspace, _Image::columns, CompositeChannels, _Image::debug, _Image::filename, GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, GetVirtualIndexQueue(), GetVirtualPixels(), GreenChannel, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickMaximumValue, _Image::matte, _ChannelStatistics::maxima, MaximumStatistic, _ChannelStatistics::minima, MinimumStatistic, OpacityChannel, RedChannel, ResourceLimitFatalError, _Image::rows, _Image::signature, ThrowFatalException, and TraceEvent.
Referenced by IdentifyImage().
IdentifyImage()
MagickExport MagickBooleanType IdentifyImage (Image * image, FILE * file, const MagickBooleanType verbose)
References AcquireExceptionInfo(), AcquireImageInfo(), AcquireQuantumMemory(), AlphaChannel, _Image::background_color, BlackChannel, _ChromaticityInfo::blue_primary, BlueChannel, _Image::border_color, _Image::chromaticity, CloneString(), CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _MagickPixelPacket::colorspace, _Image::columns, CommandOptionToMnemonic(), _Image::compose, CompositeChannels, _Image::compression, ConcatenateColorComponent(), ConcatenateMagickString(), CopyMagickString(), CyanChannel, _Image::debug, _Image::delay, _Image::depth, _ChannelStatistics::depth, DestroyExceptionInfo(), DestroyImage(), DestroyImageInfo(), DestroyString(), DirectClass, _Image::directory, _Image::dispose, _Image::duration, _Image::endian, _Image::error, _Image::exception, _Image::extent, _Image::extract_info, _Image::filename, _ImageInfo::filename, FormatLocaleFile(), FormatLocaleString(), FormatMagickSize(), _Image::gamma, GetColorTuple(), GetElapsedTime(), GetImageArtifact(), GetImageChannelFeatures(), GetImageChannelMoments(), GetImageChannelPerceptualHash(), GetImageChannelStatistics(), GetImageDepth(), GetImageListLength(), GetImageProfile(), GetImageProperty(), GetImageRegistry(), GetImageTotalInkDensity(), GetLocationStatistics(), GetMagickDescription(), GetMagickInfo(), GetMagickMimeType(), GetMagickModule, GetMagickPixelPacket(), GetMagickPrecision(), GetMagickVersion(), GetNextImageArtifact(), GetNextImageInList(), GetNextImageProfile(), GetNextImageProperty(), GetNextImageRegistry(), GetNumberColors(), GetPathComponent(), GetPixelOpacity, GetPreviousImageInList(), GetStringInfoDatum(), GetStringInfoLength(), GetTimerInfo(), GetUserTime(), GetVirtualIndexQueue(), GetVirtualPixels(), GrayChannel, GRAYColorspace, _ChromaticityInfo::green_primary, GreenChannel, _RectangleInfo::height, IdentifyImageType(), IndexChannel, _Image::intensity, _Image::interlace, IsHistogramImage(), IsMagickTrue(), _Image::iterations, LinearGRAYColorspace, LocaleCompare(), LogMagickEvent(), MagentaChannel, _Image::magick, _Image::magick_columns, _Image::magick_filename, magick_restrict, _Image::magick_rows, MagickBooleanOptions, MagickClassOptions, MagickColorspaceOptions, MagickComposeOptions, MagickCompressOptions, MAGICKCORE_QUANTUM_DEPTH, MagickCoreSignature, MagickDisposeOptions, MagickEndianOptions, MagickEpsilon, MagickFalse, MagickIntentOptions, MagickInterlaceOptions, MagickMin, MagickOrientationOptions, MagickPixelIntensityOptions, MagickResolutionOptions, MagickStatisticOptions, MagickTrue, MagickTypeOptions, _Image::matte, _MagickPixelPacket::matte, _Image::matte_color, MaxTextExtent, _ErrorInfo::mean_error_per_pixel, _Image::montage, _Image::next, _ErrorInfo::normalized_maximum_error, _ErrorInfo::normalized_mean_error, OpacityChannel, _Image::orientation, _Image::page, ParseCommandOption(), _Image::previous, PrintChannelFeatures(), PrintChannelLocations(), PrintChannelMoments(), PrintChannelPerceptualHash(), PrintChannelStatistics(), PrintStringInfo(), PseudoClass, _Image::quality, QuantumRange, QueryColorname(), QueryMagickColorname(), ReadImage(), _ChromaticityInfo::red_primary, RedChannel, registry, RelinquishMagickMemory(), _Image::rendering_intent, ResetImageArtifactIterator(), ResetImageProfileIterator(), ResetImagePropertyIterator(), ResetImageRegistryIterator(), RGBColorspace, _Image::rows, _Image::scene, sentinel, SetMagickPixelPacket(), SetWarningHandler(), _Image::signature, SignatureImage(), _ImageInfo::size, _Image::storage_class, StringRegistryType, StringToList(), StringToUnsignedLong(), SVGCompliance, TailPath, _Image::taint, _Image::ticks_per_second, _Image::tile_offset, _Image::timer, _Image::total_colors, TraceEvent, _Image::transparent_color, TransparentOpacity, _Image::type, UndefinedColorspace, UndefinedCompressionQuality, UndefinedType, _Image::units, _ChromaticityInfo::white_point, _RectangleInfo::width, _RectangleInfo::x, _PrimaryInfo::x, X11Compliance, _Image::x_resolution, _RectangleInfo::y, _PrimaryInfo::y, _Image::y_resolution, and YellowChannel.
Referenced by DescribeImage(), PingImage(), ReadImage(), and WriteImage().
PrintChannelFeatures()
static ssize_t PrintChannelFeatures (FILE * file, const ChannelType channel, const char * name, const ChannelFeatures * channel_features) static
References FeaturesFormat, FormatLocaleFile(), and PrintFeature.
Referenced by IdentifyImage().
PrintChannelLocations()
static ssize_t PrintChannelLocations (FILE * file, const Image * image, const ChannelType channel, const char * name, const StatisticType type, const size_t max_locations, const ChannelStatistics * channel_statistics) static
References AcquireExceptionInfo(), AlphaChannel, _PixelPacket::blue, BlueChannel, _Image::columns, FormatLocaleFile(), GetMagickPrecision(), GetVirtualPixels(), _PixelPacket::green, GreenChannel, MagickFalse, MagickTrue, _ChannelStatistics::maxima, MaximumStatistic, _ChannelStatistics::mean, MeanStatistic, _ChannelStatistics::minima, MinimumStatistic, _PixelPacket::opacity, QuantumScale, _PixelPacket::red, RedChannel, and _Image::rows.
Referenced by IdentifyImage().
PrintChannelMoments()
static ssize_t PrintChannelMoments (FILE * file, const ChannelType channel, const char * name, const double scale, const ChannelMoments * channel_moments) static
References FormatLocaleFile(), GetMagickPrecision(), and MaximumNumberOfImageMoments.
Referenced by IdentifyImage().
PrintChannelPerceptualHash()
static ssize_t PrintChannelPerceptualHash (FILE * file, const ChannelType channel, const char * name, const ChannelPerceptualHash * channel_phash) static
References FormatLocaleFile(), GetMagickPrecision(), and MaximumNumberOfPerceptualHashes.
Referenced by IdentifyImage().
PrintChannelStatistics()
static ssize_t PrintChannelStatistics (FILE * file, const ChannelType channel, const char * name, const double scale, const ChannelStatistics * channel_statistics) static
References ClampToQuantum(), FormatLocaleFile(), GetMagickPrecision(), QuantumRange, and StatisticsFormat.
Referenced by IdentifyImage().