MagickCore: image-view.h File Reference
image-view.h File Reference
Typedefs
typedef struct _ImageView ImageView
typedef MagickBooleanType(* DuplexTransferImageViewMethod) (const ImageView *, const ImageView *, ImageView *, const ssize_t, const int, void *)
typedef MagickBooleanType(*)(* GetImageViewMethod) (const ImageView *, const ssize_t, const int, void *)
typedef MagickBooleanType(*)(*)(* SetImageViewMethod) (ImageView *, const ssize_t, const int, void *)
typedef MagickBooleanType(*)(*)(*)(* TransferImageViewMethod) (const ImageView *, ImageView *, const ssize_t, const int, void *)
typedef MagickBooleanType(*)(*)(*)(*)(* UpdateImageViewMethod) (ImageView *, const ssize_t, const int, void *)
Functions
MagickExport char * GetImageViewException (const ImageView *, ExceptionType *)
MagickExport const IndexPacket * GetImageViewVirtualIndexes (const ImageView *)
MagickExport const PixelPacket * GetImageViewVirtualPixels (const ImageView *)
MagickExport Image * GetImageViewImage (const ImageView *)
MagickExport ImageView * CloneImageView (const ImageView *)
MagickExport ImageView * DestroyImageView (ImageView *)
MagickExport ImageView * NewImageView (Image *)
MagickExport ImageView * NewImageViewRegion (Image *, const ssize_t, const ssize_t, const size_t, const size_t)
MagickExport IndexPacket * GetImageViewAuthenticIndexes (const ImageView *)
MagickExport MagickBooleanType DuplexTransferImageViewIterator (ImageView *, ImageView *, ImageView *, DuplexTransferImageViewMethod, void *)
MagickExport MagickBooleanType GetImageViewIterator (ImageView *, GetImageViewMethod, void *)
MagickExport MagickBooleanType IsImageView (const ImageView *)
MagickExport MagickBooleanType SetImageViewIterator (ImageView *, SetImageViewMethod, void *)
MagickExport MagickBooleanType TransferImageViewIterator (ImageView *, ImageView *, TransferImageViewMethod, void *)
MagickExport MagickBooleanType UpdateImageViewIterator (ImageView *, UpdateImageViewMethod, void *)
MagickExport PixelPacket * GetImageViewAuthenticPixels (const ImageView *)
MagickExport RectangleInfo GetImageViewExtent (const ImageView *)
MagickExport void SetImageViewDescription (ImageView *, const char *)
MagickExport void SetImageViewThreads (ImageView *, const size_t)
Typedef Documentation
DuplexTransferImageViewMethod
typedef MagickBooleanType(* DuplexTransferImageViewMethod) (const ImageView *, const ImageView *, ImageView *, const ssize_t, const int, void *)
GetImageViewMethod
typedef MagickBooleanType(*)(* GetImageViewMethod) (const ImageView *, const ssize_t, const int, void *)
ImageView
typedef struct _ImageView ImageView
SetImageViewMethod
typedef MagickBooleanType(*)(*)(* SetImageViewMethod) (ImageView *, const ssize_t, const int, void *)
TransferImageViewMethod
typedef MagickBooleanType(*)(*)(*)(* TransferImageViewMethod) (const ImageView *, ImageView *, const ssize_t, const int, void *)
UpdateImageViewMethod
typedef MagickBooleanType(*)(*)(*)(*)(* UpdateImageViewMethod) (ImageView *, const ssize_t, const int, void *)
Function Documentation
CloneImageView()
MagickExport ImageView * CloneImageView (const ImageView *)
DestroyImageView()
MagickExport ImageView * DestroyImageView (ImageView *)
DuplexTransferImageViewIterator()
MagickExport MagickBooleanType DuplexTransferImageViewIterator (ImageView * , ImageView * , ImageView * , DuplexTransferImageViewMethod , void *)
GetImageViewAuthenticIndexes()
MagickExport IndexPacket * GetImageViewAuthenticIndexes (const ImageView * image_view)
References GetCacheViewAuthenticIndexQueue(), MagickCoreSignature, _ImageView::signature, and _ImageView::view.
GetImageViewAuthenticPixels()
MagickExport PixelPacket * GetImageViewAuthenticPixels (const ImageView * image_view)
References GetCacheViewAuthenticPixelQueue(), MagickCoreSignature, _ImageView::signature, and _ImageView::view.
GetImageViewException()
MagickExport char * GetImageViewException (const ImageView * image_view, ExceptionType * severity)
References AcquireQuantumMemory(), ConcatenateMagickString(), CopyMagickString(), _ExceptionInfo::description, _ImageView::exception, GetLocaleExceptionMessage(), MagickCoreSignature, MaxTextExtent, _ExceptionInfo::reason, ResourceLimitFatalError, _ExceptionInfo::severity, _ImageView::signature, and ThrowFatalException.
GetImageViewExtent()
MagickExport RectangleInfo GetImageViewExtent (const ImageView * image_view)
References _ImageView::extent, MagickCoreSignature, and _ImageView::signature.
GetImageViewImage()
MagickExport Image * GetImageViewImage (const ImageView * image_view)
References _ImageView::image, MagickCoreSignature, and _ImageView::signature.
GetImageViewIterator()
MagickExport MagickBooleanType GetImageViewIterator (ImageView * , GetImageViewMethod , void *)
GetImageViewVirtualIndexes()
MagickExport const IndexPacket * GetImageViewVirtualIndexes (const ImageView * image_view)
References GetCacheViewVirtualIndexQueue(), MagickCoreSignature, _ImageView::signature, and _ImageView::view.
GetImageViewVirtualPixels()
MagickExport const PixelPacket * GetImageViewVirtualPixels (const ImageView * image_view)
References GetCacheViewVirtualPixelQueue(), MagickCoreSignature, _ImageView::signature, and _ImageView::view.
IsImageView()
MagickExport MagickBooleanType IsImageView (const ImageView *)
NewImageView()
MagickExport ImageView * NewImageView (Image *)
NewImageViewRegion()
MagickExport ImageView * NewImageViewRegion (Image * image, const ssize_t, const ssize_t, const size_t, const size_t)
References AcquireExceptionInfo(), AcquireMagickMemory(), AcquireVirtualCacheView(), ConstantString(), _ImageView::debug, _ImageView::description, _ImageView::exception, _ImageView::extent, GetMagickResourceLimit(), _RectangleInfo::height, _ImageView::image, IsEventLogging(), MagickCoreSignature, _ImageView::number_threads, ResourceLimitFatalError, _ImageView::signature, _Image::signature, ThreadResource, ThrowFatalException, _ImageView::view, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
SetImageViewDescription()
MagickExport void SetImageViewDescription (ImageView * , const char *)
SetImageViewIterator()
MagickExport MagickBooleanType SetImageViewIterator (ImageView * , SetImageViewMethod , void *)
SetImageViewThreads()
MagickExport void SetImageViewThreads (ImageView * image_view, const size_t)
References GetMagickResourceLimit(), MagickCoreSignature, _ImageView::number_threads, _ImageView::signature, and ThreadResource.
TransferImageViewIterator()
MagickExport MagickBooleanType TransferImageViewIterator (ImageView * , ImageView * , TransferImageViewMethod , void *)
UpdateImageViewIterator()
MagickExport MagickBooleanType UpdateImageViewIterator (ImageView * source, UpdateImageViewMethod update, void * context)
References _ImageView::description, DirectClass, _ImageView::exception, _ImageView::extent, GetCacheViewAuthenticPixels(), GetCacheViewException(), GetOpenMPThreadId(), _RectangleInfo::height, _ImageView::image, InheritException(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::progress_monitor, SetImageProgress(), SetImageStorageClass(), _ImageView::signature, SyncCacheViewAuthenticPixels(), _ImageView::view, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.