MagickCore: image-view.c File Reference
image-view.c File Reference
#include "magick/studio.h"
#include "magick/MagickCore.h"
#include "magick/exception-private.h"
#include "magick/monitor-private.h"
#include "magick/thread-private.h"
Data Structures
struct _ImageView
Functions
MagickExport ImageView * CloneImageView (const ImageView *image_view)
MagickExport ImageView * DestroyImageView (ImageView *image_view)
MagickExport MagickBooleanType DuplexTransferImageViewIterator (ImageView *source, ImageView *duplex, ImageView *destination, DuplexTransferImageViewMethod transfer, void *context)
MagickExport IndexPacket * GetImageViewAuthenticIndexes (const ImageView *image_view)
MagickExport PixelPacket * GetImageViewAuthenticPixels (const ImageView *image_view)
MagickExport char * GetImageViewException (const ImageView *image_view, ExceptionType *severity)
MagickExport RectangleInfo GetImageViewExtent (const ImageView *image_view)
MagickExport Image * GetImageViewImage (const ImageView *image_view)
MagickExport MagickBooleanType GetImageViewIterator (ImageView *source, GetImageViewMethod get, void *context)
MagickExport const IndexPacket * GetImageViewVirtualIndexes (const ImageView *image_view)
MagickExport const PixelPacket * GetImageViewVirtualPixels (const ImageView *image_view)
MagickExport MagickBooleanType IsImageView (const ImageView *image_view)
MagickExport ImageView * NewImageView (Image *image)
MagickExport ImageView * NewImageViewRegion (Image *image, const ssize_t x, const ssize_t y, const size_t width, const size_t height)
MagickExport void SetImageViewDescription (ImageView *image_view, const char *description)
MagickExport MagickBooleanType SetImageViewIterator (ImageView *destination, SetImageViewMethod set, void *context)
MagickExport void SetImageViewThreads (ImageView *image_view, const size_t number_threads)
MagickExport MagickBooleanType TransferImageViewIterator (ImageView *source, ImageView *destination, TransferImageViewMethod transfer, void *context)
MagickExport MagickBooleanType UpdateImageViewIterator (ImageView *source, UpdateImageViewMethod update, void *context)
Function Documentation
CloneImageView()
MagickExport ImageView * CloneImageView (const ImageView * image_view)
References AcquireExceptionInfo(), AcquireMagickMemory(), CloneCacheView(), ConstantString(), _ImageView::debug, _ImageView::description, _ImageView::exception, _ImageView::extent, InheritException(), MagickCoreSignature, _ImageView::number_threads, ResourceLimitFatalError, _ImageView::signature, ThrowFatalException, and _ImageView::view.
DestroyImageView()
MagickExport ImageView * DestroyImageView (ImageView * image_view)
References _ImageView::description, DestroyCacheView(), DestroyExceptionInfo(), DestroyString(), _ImageView::exception, MagickCoreSignature, RelinquishMagickMemory(), _ImageView::signature, and _ImageView::view.
DuplexTransferImageViewIterator()
MagickExport MagickBooleanType DuplexTransferImageViewIterator (ImageView * source, ImageView * duplex, ImageView * destination, DuplexTransferImageViewMethod transfer, void * context)
References _ImageView::description, DirectClass, _ImageView::exception, _ImageView::extent, GetCacheViewAuthenticPixels(), GetCacheViewException(), GetCacheViewVirtualPixels(), GetOpenMPThreadId(), _RectangleInfo::height, _ImageView::image, InheritException(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::progress_monitor, SetImageProgress(), SetImageStorageClass(), _ImageView::signature, SyncCacheViewAuthenticPixels(), _ImageView::view, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
GetImageViewAuthenticIndexes()
MagickExport IndexPacket * GetImageViewAuthenticIndexes (const ImageView * image_view)
References GetCacheViewAuthenticIndexQueue(), MagickCoreSignature, _ImageView::signature, and _ImageView::view.
GetImageViewAuthenticPixels()
MagickExport PixelPacket * GetImageViewAuthenticPixels (const ImageView * image_view)
References GetCacheViewAuthenticPixelQueue(), MagickCoreSignature, _ImageView::signature, and _ImageView::view.
GetImageViewException()
MagickExport char * GetImageViewException (const ImageView * image_view, ExceptionType * severity)
References AcquireQuantumMemory(), ConcatenateMagickString(), CopyMagickString(), _ExceptionInfo::description, _ImageView::exception, GetLocaleExceptionMessage(), MagickCoreSignature, MaxTextExtent, _ExceptionInfo::reason, ResourceLimitFatalError, _ExceptionInfo::severity, _ImageView::signature, and ThrowFatalException.
GetImageViewExtent()
MagickExport RectangleInfo GetImageViewExtent (const ImageView * image_view)
References _ImageView::extent, MagickCoreSignature, and _ImageView::signature.
GetImageViewImage()
MagickExport Image * GetImageViewImage (const ImageView * image_view)
References _ImageView::image, MagickCoreSignature, and _ImageView::signature.
GetImageViewIterator()
MagickExport MagickBooleanType GetImageViewIterator (ImageView * source, GetImageViewMethod get, void * context)
References _ImageView::description, _ImageView::exception, _ImageView::extent, GetCacheViewVirtualPixels(), GetOpenMPThreadId(), _RectangleInfo::height, _ImageView::image, MagickCoreSignature, MagickFalse, MagickTrue, _Image::progress_monitor, SetImageProgress(), _ImageView::signature, _ImageView::view, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
GetImageViewVirtualIndexes()
MagickExport const IndexPacket * GetImageViewVirtualIndexes (const ImageView * image_view)
References GetCacheViewVirtualIndexQueue(), MagickCoreSignature, _ImageView::signature, and _ImageView::view.
GetImageViewVirtualPixels()
MagickExport const PixelPacket * GetImageViewVirtualPixels (const ImageView * image_view)
References GetCacheViewVirtualPixelQueue(), MagickCoreSignature, _ImageView::signature, and _ImageView::view.
IsImageView()
MagickExport MagickBooleanType IsImageView (const ImageView * image_view)
References MagickCoreSignature, MagickFalse, MagickTrue, and _ImageView::signature.
NewImageView()
MagickExport ImageView * NewImageView (Image * image)
References AcquireExceptionInfo(), AcquireMagickMemory(), AcquireVirtualCacheView(), _Image::columns, ConstantString(), _ImageView::debug, _ImageView::description, _ImageView::exception, _ImageView::extent, GetMagickResourceLimit(), _RectangleInfo::height, _ImageView::image, IsEventLogging(), MagickCoreSignature, _ImageView::number_threads, ResourceLimitFatalError, _Image::rows, _ImageView::signature, _Image::signature, ThreadResource, ThrowFatalException, _ImageView::view, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
NewImageViewRegion()
MagickExport ImageView * NewImageViewRegion (Image * image, const ssize_t x, const ssize_t y, const size_t width, const size_t height)
References AcquireExceptionInfo(), AcquireMagickMemory(), AcquireVirtualCacheView(), ConstantString(), _ImageView::debug, _ImageView::description, _ImageView::exception, _ImageView::extent, GetMagickResourceLimit(), _RectangleInfo::height, _ImageView::image, IsEventLogging(), MagickCoreSignature, _ImageView::number_threads, ResourceLimitFatalError, _ImageView::signature, _Image::signature, ThreadResource, ThrowFatalException, _ImageView::view, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
SetImageViewDescription()
MagickExport void SetImageViewDescription (ImageView * image_view, const char * description)
References ConstantString(), _ImageView::description, MagickCoreSignature, and _ImageView::signature.
SetImageViewIterator()
MagickExport MagickBooleanType SetImageViewIterator (ImageView * destination, SetImageViewMethod set, void * context)
References _ImageView::description, DirectClass, _ImageView::exception, _ImageView::extent, GetCacheViewAuthenticPixels(), GetCacheViewException(), GetOpenMPThreadId(), _RectangleInfo::height, _ImageView::image, InheritException(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::progress_monitor, SetImageProgress(), SetImageStorageClass(), _ImageView::signature, SyncCacheViewAuthenticPixels(), _ImageView::view, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
SetImageViewThreads()
MagickExport void SetImageViewThreads (ImageView * image_view, const size_t number_threads)
References GetMagickResourceLimit(), MagickCoreSignature, _ImageView::number_threads, _ImageView::signature, and ThreadResource.
TransferImageViewIterator()
MagickExport MagickBooleanType TransferImageViewIterator (ImageView * source, ImageView * destination, TransferImageViewMethod transfer, void * context)
References _ImageView::description, DirectClass, _ImageView::exception, _ImageView::extent, GetCacheViewAuthenticPixels(), GetCacheViewException(), GetCacheViewVirtualPixels(), GetOpenMPThreadId(), _RectangleInfo::height, _ImageView::image, InheritException(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::progress_monitor, SetImageProgress(), SetImageStorageClass(), _ImageView::signature, SyncCacheViewAuthenticPixels(), _ImageView::view, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
UpdateImageViewIterator()
MagickExport MagickBooleanType UpdateImageViewIterator (ImageView * source, UpdateImageViewMethod update, void * context)
References _ImageView::description, DirectClass, _ImageView::exception, _ImageView::extent, GetCacheViewAuthenticPixels(), GetCacheViewException(), GetOpenMPThreadId(), _RectangleInfo::height, _ImageView::image, InheritException(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::progress_monitor, SetImageProgress(), SetImageStorageClass(), _ImageView::signature, SyncCacheViewAuthenticPixels(), _ImageView::view, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.