MagickCore: image.c File Reference
image.c File Reference
#include "magick/studio.h"
#include "magick/animate.h"
#include "magick/artifact.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/cache.h"
#include "magick/cache-private.h"
#include "magick/cache-view.h"
#include "magick/channel.h"
#include "magick/client.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colormap.h"
#include "magick/colorspace.h"
#include "magick/colorspace-private.h"
#include "magick/composite.h"
#include "magick/composite-private.h"
#include "magick/compress.h"
#include "magick/constitute.h"
#include "magick/delegate.h"
#include "magick/deprecate.h"
#include "magick/display.h"
#include "magick/draw.h"
#include "magick/enhance.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/histogram.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/magic.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/memory-private.h"
#include "magick/module.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/option.h"
#include "magick/paint.h"
#include "magick/pixel-accessor.h"
#include "magick/pixel-private.h"
#include "magick/profile.h"
#include "magick/property.h"
#include "magick/quantize.h"
#include "magick/random_.h"
#include "magick/resource_.h"
#include "magick/segment.h"
#include "magick/semaphore.h"
#include "magick/signature-private.h"
#include "magick/statistic.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/thread-private.h"
#include "magick/threshold.h"
#include "magick/timer.h"
#include "magick/timer-private.h"
#include "magick/token.h"
#include "magick/token-private.h"
#include "magick/utility.h"
#include "magick/version.h"
#include "magick/xwindow-private.h"
Macros
#define AppendImageTag "Append/Image"
#define ClipImagePathTag "ClipPath/Image"
#define CopyImageTag "Copy/Image"
#define SmushImageTag "Smush/Image"
Functions
MagickExport Image * AcquireImage (const ImageInfo *image_info)
MagickExport ImageInfo * AcquireImageInfo (void)
MagickExport void AcquireNextImage (const ImageInfo *image_info, Image *image)
MagickExport Image * AppendImages (const Image *images, const MagickBooleanType stack, ExceptionInfo *exception)
MagickExport ExceptionType CatchImageException (Image *image)
MagickExport MagickBooleanType ClipImage (Image *image)
MagickExport MagickBooleanType ClipImagePath (Image *image, const char *pathname, const MagickBooleanType inside)
MagickExport Image * CloneImage (const Image *image, const size_t columns, const size_t rows, const MagickBooleanType detach, ExceptionInfo *exception)
MagickExport ImageInfo * CloneImageInfo (const ImageInfo *image_info)
MagickExport MagickBooleanType CopyImagePixels (Image *image, const Image *source_image, const RectangleInfo *geometry, const OffsetInfo *offset, ExceptionInfo *exception)
MagickExport Image * DestroyImage (Image *image)
MagickExport ImageInfo * DestroyImageInfo (ImageInfo *image_info)
MagickExport void DisassociateImageStream (Image *image)
MagickExport Image * GetImageClipMask (const Image *image, ExceptionInfo *exception)
MagickExport void GetImageException (Image *image, ExceptionInfo *exception)
MagickExport void GetImageInfo (ImageInfo *image_info)
MagickExport FILE * GetImageInfoFile (const ImageInfo *image_info)
MagickExport Image * GetImageMask (const Image *image, ExceptionInfo *exception)
MagickExport size_t GetImageChannels (Image *image)
MagickExport ssize_t GetImageReferenceCount (Image *image)
MagickExport VirtualPixelMethod GetImageVirtualPixelMethod (const Image *image)
MagickExport size_t InterpretImageFilename (const ImageInfo *image_info, Image *image, const char *format, int value, char *filename)
MagickExport MagickBooleanType IsHighDynamicRangeImage (const Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType IsImageObject (const Image *image)
MagickExport MagickBooleanType IsTaintImage (const Image *image)
MagickExport MagickBooleanType ModifyImage (Image **image, ExceptionInfo *exception)
MagickExport Image * NewMagickImage (const ImageInfo *image_info, const size_t width, const size_t height, const MagickPixelPacket *background)
MagickExport Image * ReferenceImage (Image *image)
MagickExport MagickBooleanType ResetImagePage (Image *image, const char *page)
MagickExport MagickBooleanType ResetImagePixels (Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType SetImageBackgroundColor (Image *image)
MagickExport MagickBooleanType SetImageChannels (Image *image, const size_t channels)
MagickExport MagickBooleanType SetImageColor (Image *image, const MagickPixelPacket *color)
MagickExport MagickBooleanType SetImageStorageClass (Image *image, const ClassType storage_class)
MagickExport MagickBooleanType SetImageClipMask (Image *image, const Image *clip_mask)
MagickExport MagickBooleanType SetImageExtent (Image *image, const size_t columns, const size_t rows)
MagickExport MagickBooleanType SetImageInfo (ImageInfo *image_info, const unsigned int frames, ExceptionInfo *exception)
MagickExport void SetImageInfoBlob (ImageInfo *image_info, const void *blob, const size_t length)
MagickExport void SetImageInfoFile (ImageInfo *image_info, FILE *file)
MagickExport MagickBooleanType SetImageMask (Image *image, const Image *mask)
MagickExport MagickBooleanType SetImageOpacity (Image *image, const Quantum opacity)
MagickExport VirtualPixelMethod SetImageVirtualPixelMethod (const Image *image, const VirtualPixelMethod virtual_pixel_method)
static ssize_t SmushXGap (const Image *smush_image, const Image *images, const ssize_t offset, ExceptionInfo *exception)
static ssize_t SmushYGap (const Image *smush_image, const Image *images, const ssize_t offset, ExceptionInfo *exception)
MagickExport Image * SmushImages (const Image *images, const MagickBooleanType stack, const ssize_t offset, ExceptionInfo *exception)
MagickExport MagickBooleanType StripImage (Image *image)
static IndexPacket PushColormapIndex (Image *image, const size_t index, MagickBooleanType *range_exception)
MagickExport MagickBooleanType SyncImage (Image *image)
MagickExport MagickBooleanType SyncImagesSettings (ImageInfo *image_info, Image *images)
MagickExport MagickBooleanType SyncImageSettings (const ImageInfo *image_info, Image *image)
Macro Definition Documentation
AppendImageTag
#define AppendImageTag "Append/Image"
ClipImagePathTag
#define ClipImagePathTag "ClipPath/Image"
CopyImageTag
#define CopyImageTag "Copy/Image"
SmushImageTag
#define SmushImageTag "Smush/Image"
Function Documentation
AcquireImage()
MagickExport Image * AcquireImage (const ImageInfo * image_info)
References AcquireCriticalMemory(), AcquirePixelCache(), AllocateSemaphoreInfo(), _Image::background_color, _ImageInfo::background_color, BackgroundColor, _Image::blob, _ChromaticityInfo::blue_primary, _Image::blur, _Image::border_color, _ImageInfo::border_color, BorderColor, _Image::cache, _ImageInfo::cache, CastDoubleToLong(), _Image::chromaticity, _Image::client_data, _ImageInfo::client_data, CloneBlobInfo(), ClonePixelCacheMethods(), _Image::colorspace, _Image::columns, _Image::compose, _Image::compression, _ImageInfo::compression, CopyMagickString(), _Image::debug, _Image::delay, _ImageInfo::density, _Image::depth, _ImageInfo::depth, DestroyString(), DirectClass, _Image::dispose, _Image::dither, _ImageInfo::dither, _Image::endian, _ImageInfo::endian, _Image::exception, _ImageInfo::extract, _Image::extract_info, _ImageInfo::file, _Image::filename, _ImageInfo::filename, _Image::gamma, GetImageOption(), GetMagickModule, GetMagickTime(), GetPageGeometry(), GetTimerInfo(), GreaterValue, _ChromaticityInfo::green_primary, _RectangleInfo::height, InitializeExceptionInfo(), _Image::interlace, _ImageInfo::interlace, IsEventLogging(), LessValue, LogMagickEvent(), _Image::magick, _ImageInfo::magick, _Image::magick_filename, MAGICKCORE_QUANTUM_DEPTH, MagickCoreSignature, MagickDisposeOptions, MagickFalse, MagickTrue, _Image::matte_color, _ImageInfo::matte_color, MatteColor, MaxTextExtent, NoInterlace, _Image::offset, OverCompositeOp, _Image::page, _ImageInfo::page, ParseAbsoluteGeometry(), ParseCommandOption(), ParseGeometry(), PerceptualIntent, _Image::ping, _ImageInfo::ping, _Image::progress_monitor, _ImageInfo::progress_monitor, _Image::quality, _ImageInfo::quality, QueryColorDatabase(), _ChromaticityInfo::red_primary, _Image::reference_count, _Image::rendering_intent, _GeometryInfo::rho, RhoValue, _Image::rows, _Image::semaphore, SetBlobExempt(), _GeometryInfo::sigma, SigmaValue, _Image::signature, _ImageInfo::size, sRGBColorspace, _Image::storage_class, Swap, SyncImageSettings(), _Image::ticks_per_second, _Image::timer, _Image::timestamp, TraceEvent, _Image::transparent_color, _ImageInfo::transparent_color, TransparentColor, UndefinedTicksPerSecond, _Image::units, _ImageInfo::units, _ChromaticityInfo::white_point, _RectangleInfo::width, _RectangleInfo::x, _PrimaryInfo::x, _Image::x_resolution, XValue, _RectangleInfo::y, _PrimaryInfo::y, _Image::y_resolution, YValue, and _PrimaryInfo::z.
Referenced by AcquireNextImage(), AcquireStreamInfo(), AllocateImage(), ConstituteImage(), DrawClippingMask(), DrawCompositeMask(), DrawPatternPath(), MatrixToImage(), MontageImageList(), NewMagickImage(), OpenDistributeCache(), ReadImage(), RenderHoughLines(), and SetImageInfo().
AcquireImageInfo()
MagickExport ImageInfo * AcquireImageInfo (void)
References AcquireMagickMemory(), GetImageInfo(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by ClipImagePath(), CloneImageInfo(), DrawPatternPath(), DrawPrimitive(), GlobExpression(), HoughLineImage(), IdentifyImage(), MontageImages(), PreviewImage(), RenderPostscript(), and SetImageType().
AcquireNextImage()
MagickExport void AcquireNextImage (const ImageInfo * image_info, Image * image)
References AcquireImage(), _Image::blob, CopyMagickString(), _Image::debug, DestroyBlob(), _Image::endian, _Image::filename, _ImageInfo::filename, GetMagickModule, GetNextImageInList(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MaxTextExtent, _Image::next, _Image::previous, ReferenceBlob(), _Image::scene, _Image::signature, and TraceEvent.
Referenced by AllocateNextImage(), and MontageImageList().
AppendImages()
MagickExport Image * AppendImages (const Image * images, const MagickBooleanType stack, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AppendImageTag, CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, _Image::depth, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetNextImageInList(), GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _Image::gravity, GravityAdjustGeometry(), InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OpaqueOpacity, _Image::page, QueueCacheViewAuthenticPixels(), _Image::rows, SetGeometry(), SetImageBackgroundColor(), SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), TraceEvent, _RectangleInfo::x, and _RectangleInfo::y.
CatchImageException()
MagickExport ExceptionType CatchImageException (Image * image)
References AcquireExceptionInfo(), CatchException(), _Image::debug, DestroyExceptionInfo(), _Image::filename, GetImageException(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ExceptionInfo::severity, _Image::signature, and TraceEvent.
ClipImage()
MagickExport MagickBooleanType ClipImage (Image * image)
References ClipImagePath(), and MagickTrue.
ClipImagePath()
MagickExport MagickBooleanType ClipImagePath (Image * image, const char * pathname, const MagickBooleanType inside)
References AcquireImageInfo(), AcquireString(), BlobToImage(), ConcatenateMagickString(), CopyMagickString(), _Image::debug, DestroyImage(), DestroyImageInfo(), DestroyString(), DirectClass, _Image::exception, _Image::filename, _ImageInfo::filename, FormatLocaleString(), GetImageProperty(), GetMagickModule, LogMagickEvent(), _Image::magick_filename, MagickCoreSignature, MagickFalse, MagickTrue, MaxTextExtent, NegateImage(), OptionError, PseudoClass, SetImageClipMask(), SetImageStorageClass(), _Image::signature, _Image::storage_class, SyncImage(), ThrowFileException, and TraceEvent.
Referenced by ClipImage(), and ClipPathImage().
CloneImage()
MagickExport Image * CloneImage (const Image * image, const size_t columns, const size_t rows, const MagickBooleanType detach, ExceptionInfo * exception)
References AcquireCriticalMemory(), AcquireQuantumMemory(), AllocateSemaphoreInfo(), _Image::ascii85, Ascii85Initialize(), _Image::blob, _Image::cache, CastDoubleToLong(), _Image::channels, _Image::client_data, _Image::clip_mask, CloneBlobInfo(), CloneImage(), CloneImageArtifacts(), CloneImageProfiles(), CloneImageProperties(), ClonePixelCache(), CloneString(), _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, CopyMagickString(), CorruptImageError, _Image::debug, DestroyImage(), _Image::directory, _Image::dither, _Image::exception, _Image::extent, _Image::filename, GetMagickModule, GetTimerInfo(), _RectangleInfo::height, InheritException(), InitializeExceptionInfo(), IsEventLogging(), _Image::list, LogMagickEvent(), _Image::magick, _Image::magick_columns, _Image::magick_filename, _Image::magick_rows, MagickCoreSignature, MagickFalse, MagickTrue, _Image::mask, _Image::matte, MaxTextExtent, _Image::montage, NewImageList(), _Image::next, _Image::page, _Image::ping, _Image::previous, _Image::progress_monitor, _Image::reference_count, ReferenceBlob(), ReferencePixelCache(), ResourceLimitError, _Image::rows, _Image::semaphore, SetImageExtent(), _ExceptionInfo::signature, _Image::signature, _Image::storage_class, ThrowImageException, ThrowMagickException(), _Image::tile_offset, _Image::timer, TraceEvent, _Image::type, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by AcquireImageCanvas(), AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), AddNoiseImageChannel(), AppendImages(), AutoOrientImage(), BlueShiftImage(), BorderImage(), ChopImage(), CloneDrawInfo(), CloneImage(), CloneImageList(), CloneImages(), CoalesceImages(), ColorFloodfillImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImageChannels(), CompareImageLayers(), ComplexImages(), CompositeImageChannel(), CompositeLayers(), ConnectedComponentsImage(), ConsolidateCMYKImages(), CropImage(), CropImageToTiles(), DeskewImage(), DespeckleImage(), DisposeImages(), DistortImage(), DistortResizeImage(), DrawStrokePolygon(), EnhanceImage(), ExcerptImage(), ExtentImage(), FilterImageChannel(), FlipImage(), FloodfillPaintImage(), FlopImage(), ForwardFourierTransformImage(), FrameImage(), FxImageChannel(), GetEdgeBoundingBox(), GetImageClipMask(), GetImageList(), GetImageMask(), HuffmanEncodeImage(), ImplodeImage(), InjectImageBlob(), IntegralRotateImage(), InterpolativeResizeImage(), InverseFourierTransformImage(), KuwaharaImageChannel(), LocalContrastImage(), MagnifyImage(), MatteFloodfillImage(), MeanShiftImage(), MergeImageLayers(), ModifyImage(), MontageImageList(), MorphImages(), MorphologyApply(), MotionBlurImageChannel(), OilPaintImage(), OptimizeImageTransparency(), OptimizeLayerFrames(), PolaroidImage(), PreviewImage(), ResizeImage(), RollImage(), RotateImage(), RotationalBlurImageChannel(), SampleImage(), ScaleImage(), SelectiveBlurImageChannel(), SeparateImage(), SeparateImages(), SepiaToneImage(), SetImageClipMask(), SetImageMask(), ShadeImage(), ShadowImage(), ShearImage(), SimilarityMetricImage(), SketchImage(), SmushImages(), SparseColorImage(), SpliceImage(), SpreadImage(), StatisticImageChannel(), SteganoImage(), StereoAnaglyphImage(), SwirlImage(), TextureImage(), TintImage(), TransformImage(), TransposeImage(), TransverseImage(), TrimImage(), UniqueImageColors(), VignetteImage(), WaveImage(), and WaveletDenoiseImage().
CloneImageInfo()
MagickExport ImageInfo * CloneImageInfo (const ImageInfo * image_info)
References AcquireImageInfo(), _ImageInfo::adjoin, _ImageInfo::antialias, _ImageInfo::authenticate, _ImageInfo::background_color, _ImageInfo::blob, _ImageInfo::border_color, _ImageInfo::cache, _ImageInfo::channel, _ImageInfo::client_data, CloneImageOptions(), CloneString(), CloneStringInfo(), _ImageInfo::colors, _ImageInfo::colorspace, _ImageInfo::compression, CopyMagickString(), _ImageInfo::debug, _ImageInfo::density, _ImageInfo::depth, _ImageInfo::dither, _ImageInfo::endian, _ImageInfo::extract, _ImageInfo::file, _ImageInfo::filename, _ImageInfo::font, _ImageInfo::fuzz, _ImageInfo::group, _ImageInfo::interlace, IsEventLogging(), _ImageInfo::length, _ImageInfo::magick, _ImageInfo::matte_color, MaxTextExtent, _ImageInfo::monochrome, _ImageInfo::number_scenes, _ImageInfo::orientation, _ImageInfo::page, _ImageInfo::pen, _ImageInfo::ping, _ImageInfo::pointsize, _ImageInfo::preview_type, _ImageInfo::profile, _ImageInfo::progress_monitor, _ImageInfo::quality, ReferencePixelCache(), _ImageInfo::sampling_factor, _ImageInfo::scene, _ImageInfo::scenes, _ImageInfo::server_name, SetImageInfoBlob(), SetImageInfoFile(), _ImageInfo::signature, _ImageInfo::size, _ImageInfo::stream, _ImageInfo::subimage, _ImageInfo::subrange, _ImageInfo::temporary, _ImageInfo::texture, _ImageInfo::transparent_color, _ImageInfo::type, _ImageInfo::unique, _ImageInfo::units, _ImageInfo::verbose, _ImageInfo::view, _ImageInfo::virtual_pixel_method, and _ImageInfo::zero.
Referenced by BlobToImage(), GetDrawInfo(), GetImageRegistry(), ImagesToBlob(), ImageToBlob(), InjectImageBlob(), InterpretImageProperties(), InvokeDelegate(), MontageImageList(), PingBlob(), PingImage(), PingImages(), ReadImage(), ReadImages(), ReadInlineImage(), ReadStream(), SetImageRegistry(), StreamImage(), WriteImage(), WriteImages(), WriteStream(), and WriteStreamImage().
CopyImagePixels()
MagickExport MagickBooleanType CopyImagePixels (Image * image, const Image * source_image, const RectangleInfo * geometry, const OffsetInfo * offset, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), CMYKColorspace, _Image::colorspace, _Image::columns, CopyImageTag, _Image::debug, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, _RectangleInfo::height, LogMagickEvent(), magick_restrict, MagickFalse, MagickTrue, OptionError, _Image::progress_monitor, _Image::rows, SetImageProgress(), SetImageStorageClass(), SyncCacheViewAuthenticPixels(), ThrowBinaryException, TraceEvent, _RectangleInfo::width, _OffsetInfo::x, _RectangleInfo::x, _OffsetInfo::y, and _RectangleInfo::y.
DestroyImage()
MagickExport Image * DestroyImage (Image * image)
References _Image::ascii85, ClearExceptionInfo(), _Image::clip_mask, _Image::colormap, _Image::debug, DestroyBlob(), DestroyImage(), DestroyImageArtifacts(), DestroyImagePixels(), DestroyImageProfiles(), DestroyImageProperties(), DestroySemaphoreInfo(), DestroyString(), _Image::directory, _Image::exception, _Image::filename, _Image::geometry, GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::mask, _Image::montage, _Image::reference_count, RelinquishMagickMemory(), _Image::semaphore, _Image::signature, TraceEvent, and UnlockSemaphoreInfo().
Referenced by AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), AddNoiseImageChannel(), AppendImages(), BlueShiftImage(), BorderImage(), CannyEdgeImage(), CharcoalImage(), ChopImage(), ClipImagePath(), CloneImage(), CoalesceImages(), ColorFloodfillImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImageChannels(), CompareImageLayers(), CompositeImageChannel(), CompositeLayers(), ConnectedComponentsImage(), ConstituteImage(), CropImage(), CropToFitImage(), DeleteImageFromList(), DeskewImage(), DespeckleImage(), DestroyCacheView(), DestroyDrawInfo(), DestroyImage(), DestroyResampleFilter(), DestroyStreamInfo(), DisposeImages(), DistortImage(), DistortResizeImage(), DrawClipPath(), DrawClippingMask(), DrawCompositeMask(), DrawPatternPath(), DrawPrimitive(), DrawStrokePolygon(), EnhanceImage(), EvaluateImages(), ExcerptImage(), ExtentImage(), FilterImageChannel(), FlipImage(), FloodfillPaintImage(), FlopImage(), ForwardFourierTransformImage(), FrameImage(), FxImageChannel(), GetEdgeBackgroundFactor(), GetEdgeBoundingBox(), GetImageChannelPerceptualHash(), GetSimilarityMetric(), HuffmanEncodeImage(), IdentifyImage(), ImplodeImage(), InjectImageBlob(), IntegralRotateImage(), InterpolateMagickPixelPacket(), InterpolatePixelColor(), InterpolativeResizeImage(), InverseFourierTransformImage(), KuwaharaImageChannel(), LocalContrastImage(), MagnifyImage(), MatrixToImage(), MatteFloodfillImage(), MeanShiftImage(), MontageImageList(), MorphImages(), MorphologyApply(), MotionBlurImageChannel(), NewMagickImage(), OilPaintImage(), OptimizeImageTransparency(), OptimizeLayerFrames(), PolaroidImage(), PolynomialImageChannel(), PreviewImage(), ReadImage(), RenderMVGContent(), RenderPostscript(), ReplaceImageInList(), ReplaceImageInListReturnLast(), ResamplePixelColor(), ResizeImage(), RollImage(), RotateImage(), RotationalBlurImageChannel(), SampleImage(), ScaleImage(), SelectiveBlurImageChannel(), SeparateImage(), SepiaToneImage(), SetImageClipMask(), SetImageInfo(), SetImageMask(), ShadeImage(), ShadowImage(), ShearImage(), ShearRotateImage(), SimilarityMetricImage(), SketchImage(), SmushImages(), SparseColorImage(), SpliceImage(), SpreadImage(), StatisticImageChannel(), SteganoImage(), StereoAnaglyphImage(), StreamImage(), SwirlImage(), TextureImage(), ThumbnailImage(), TintImage(), TransformImage(), TransposeImage(), TransverseImage(), UniqueImageColors(), UnsharpMaskImageChannel(), VignetteImage(), WaveImage(), and WaveletDenoiseImage().
DestroyImageInfo()
MagickExport ImageInfo * DestroyImageInfo (ImageInfo * image_info)
References _ImageInfo::authenticate, _ImageInfo::cache, _ImageInfo::debug, _ImageInfo::density, DestroyImageOptions(), DestroyPixelCache(), DestroyString(), DestroyStringInfo(), _ImageInfo::extract, _ImageInfo::filename, _ImageInfo::font, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ImageInfo::page, _ImageInfo::profile, RelinquishMagickMemory(), _ImageInfo::sampling_factor, _ImageInfo::scenes, _ImageInfo::server_name, _ImageInfo::signature, _ImageInfo::size, _ImageInfo::texture, TraceEvent, and _ImageInfo::view.
Referenced by BlobToImage(), ClipImagePath(), DestroyDrawInfo(), DestroyRegistryNode(), DrawPatternPath(), DrawPrimitive(), GlobExpression(), HoughLineImage(), IdentifyImage(), ImagesToBlob(), ImageToBlob(), InjectImageBlob(), InterpretImageProperties(), InvokeDelegate(), MontageImageList(), MontageImages(), PingBlob(), PingImage(), PingImages(), PreviewImage(), ReadImage(), ReadImages(), ReadInlineImage(), ReadStream(), RenderPostscript(), SetImageType(), StreamImage(), WriteImage(), WriteImages(), WriteStream(), and WriteStreamImage().
DisassociateImageStream()
MagickExport void DisassociateImageStream (Image * image)
References _Image::debug, DisassociateBlob(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
Referenced by WriteImage().
GetImageChannels()
MagickExport size_t GetImageChannels (Image * image)
References _Image::channels, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
GetImageClipMask()
MagickExport Image * GetImageClipMask (const Image * image, ExceptionInfo * exception)
References _Image::clip_mask, CloneImage(), _Image::debug, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::signature, and TraceEvent.
GetImageException()
MagickExport void GetImageException (Image * image, ExceptionInfo * exception)
References _Image::debug, _Image::exception, _Image::filename, GetMagickModule, GetNextImageInList(), InheritException(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _ExceptionInfo::severity, _ExceptionInfo::signature, _Image::signature, TraceEvent, and UndefinedException.
Referenced by CatchImageException(), and WriteImages().
GetImageInfo()
MagickExport void GetImageInfo (ImageInfo * image_info)
References AcquireExceptionInfo(), _ImageInfo::adjoin, _ImageInfo::antialias, _ImageInfo::background_color, BackgroundColor, _ImageInfo::border_color, BorderColor, _ImageInfo::channel, _ImageInfo::debug, DefaultChannels, DestroyExceptionInfo(), DestroyString(), _ImageInfo::dither, GetEnvironmentValue(), GetMagickModule, _ImageInfo::interlace, IsEventLogging(), IsStringTrue(), LogMagickEvent(), MagickCoreSignature, MagickTrue, _ImageInfo::matte_color, MatteColor, NoInterlace, _ImageInfo::quality, QueryColorDatabase(), _ImageInfo::signature, _ImageInfo::synchronize, TraceEvent, _ImageInfo::transparent_color, TransparentColor, and UndefinedCompressionQuality.
Referenced by AcquireImageInfo().
GetImageInfoFile()
MagickExport FILE * GetImageInfoFile (const ImageInfo * image_info)
References _ImageInfo::file.
GetImageMask()
MagickExport Image * GetImageMask (const Image * image, ExceptionInfo * exception)
References CloneImage(), _Image::debug, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::mask, _Image::signature, and TraceEvent.
GetImageReferenceCount()
MagickExport ssize_t GetImageReferenceCount (Image * image)
References _Image::debug, _Image::filename, GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::reference_count, _Image::semaphore, _Image::signature, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ModifyImage().
GetImageVirtualPixelMethod()
MagickExport VirtualPixelMethod GetImageVirtualPixelMethod (const Image * image)
References _Image::debug, _Image::filename, GetMagickModule, GetPixelCacheVirtualMethod(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
Referenced by AcquireResampleFilter(), AcquireVirtualCacheView(), and DistortResizeImage().
InterpretImageFilename()
MagickExport size_t InterpretImageFilename (const ImageInfo * image_info, Image * image, const char * format, int value, char * filename)
References ConcatenateMagickString(), CopyMagickString(), FormatLocaleString(), GetImageArtifact(), GetImageOption(), GetImageProperty(), LocaleNCompare(), MagickFalse, MagickTrue, and MaxTextExtent.
Referenced by OpenBlob(), PingImages(), ReadImages(), and SetImageInfo().
IsHighDynamicRangeImage()
MagickExport MagickBooleanType IsHighDynamicRangeImage (const Image * image, ExceptionInfo * exception)
References AcquireVirtualCacheView(), _MagickPixelPacket::blue, CMYKColorspace, _MagickPixelPacket::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), _MagickPixelPacket::green, _MagickPixelPacket::index, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _MagickPixelPacket::matte, _MagickPixelPacket::opacity, QuantumRange, _MagickPixelPacket::red, _Image::rows, SetMagickPixelPacket(), _Image::signature, and TraceEvent.
IsImageObject()
MagickExport MagickBooleanType IsImageObject (const Image * image)
References _Image::debug, GetMagickModule, GetNextImageInList(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::signature, and TraceEvent.
IsTaintImage()
MagickExport MagickBooleanType IsTaintImage (const Image * image)
References CopyMagickString(), _Image::debug, _Image::filename, GetMagickModule, GetNextImageInList(), LocaleCompare(), LogMagickEvent(), _Image::magick, MagickCoreSignature, MagickFalse, MagickTrue, MaxTextExtent, _Image::signature, _Image::taint, and TraceEvent.
Referenced by WriteImage().
ModifyImage()
MagickExport MagickBooleanType ModifyImage (Image ** image, ExceptionInfo * exception)
References CloneImage(), GetImageReferenceCount(), GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, TraceEvent, and UnlockSemaphoreInfo().
NewMagickImage()
MagickExport Image * NewMagickImage (const ImageInfo * image_info, const size_t width, const size_t height, const MagickPixelPacket * background)
References AcquireAuthenticCacheView(), AcquireImage(), _Image::colorspace, _MagickPixelPacket::colorspace, _Image::columns, _ImageInfo::debug, _Image::depth, _MagickPixelPacket::depth, DestroyCacheView(), DestroyImage(), _Image::exception, _Image::fuzz, _MagickPixelPacket::fuzz, GetCacheViewAuthenticIndexQueue(), GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _MagickPixelPacket::matte, QueueCacheViewAuthenticPixels(), _Image::rows, SetPixelPacket(), _ImageInfo::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
PushColormapIndex()
static IndexPacket PushColormapIndex (Image * image, const size_t index, MagickBooleanType * range_exception) inline static
References MagickTrue.
Referenced by SyncImage().
ReferenceImage()
MagickExport Image * ReferenceImage (Image * image)
References _Image::debug, GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::reference_count, _Image::semaphore, _Image::signature, TraceEvent, and UnlockSemaphoreInfo().
Referenced by AcquireResampleFilter(), AcquireVirtualCacheView(), CloneCacheView(), and OptimizeLayerFrames().
ResetImagePage()
MagickExport MagickBooleanType ResetImagePage (Image * image, const char * page)
References AspectValue, _Image::columns, _Image::debug, _Image::filename, GetMagickModule, _RectangleInfo::height, HeightValue, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::page, ParseAbsoluteGeometry(), _Image::rows, _Image::signature, TraceEvent, _RectangleInfo::width, WidthValue, _RectangleInfo::x, XValue, _RectangleInfo::y, and YValue.
ResetImagePixels()
MagickExport MagickBooleanType ResetImagePixels (Image * image, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquirePixelCachePixels(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), GetCacheViewAuthenticIndexQueue(), GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, PseudoClass, QueueCacheViewAuthenticPixels(), _Image::rows, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by ConstituteImage().
SetImageBackgroundColor()
MagickExport MagickBooleanType SetImageBackgroundColor (Image * image)
References AcquireAuthenticCacheView(), _Image::background_color, CMYKColorspace, _Image::colorspace, _Image::columns, ConvertRGBToCMYK(), _Image::debug, DestroyCacheView(), DirectClass, _Image::exception, GetCacheViewAuthenticIndexQueue(), GetMagickModule, GetMagickPixelPacket(), IsGrayColorspace(), IsPixelGray(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _PixelPacket::opacity, OpaqueAlphaChannel, OpaqueOpacity, QueueCacheViewAuthenticPixels(), RGBColorspace, _Image::rows, SetImageAlphaChannel(), SetImageStorageClass(), SetMagickPixelPacket(), SetPixelIndex, SetPixelPacket(), _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, and TransformImageColorspace().
Referenced by AppendImages(), CoalesceImages(), CombineImages(), CompareImageLayers(), CropImage(), DisposeImages(), DrawClippingMask(), DrawCompositeMask(), DrawPatternPath(), ExtentImage(), MergeImageLayers(), MontageImageList(), OptimizeImageTransparency(), OptimizeLayerFrames(), PolaroidImage(), RenderHoughLines(), SmushImages(), SpliceImage(), TrimImage(), and VignetteImage().
SetImageChannels()
MagickExport MagickBooleanType SetImageChannels (Image * image, const size_t channels)
References _Image::channels, and MagickTrue.
SetImageClipMask()
MagickExport MagickBooleanType SetImageClipMask (Image * image, const Image * clip_mask)
References _Image::clip_mask, CloneImage(), _Image::columns, _Image::debug, DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetMagickModule, ImageError, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, NewImageList(), _Image::rows, SetImageStorageClass(), _Image::signature, ThrowBinaryImageException, and TraceEvent.
Referenced by ClipImagePath(), DrawClipPath(), DrawClippingMask(), DrawPrimitive(), and RenderMVGContent().
SetImageColor()
MagickExport MagickBooleanType SetImageColor (Image * image, const MagickPixelPacket * color)
References AcquireAuthenticCacheView(), _Image::colorspace, _MagickPixelPacket::colorspace, _Image::columns, _Image::debug, _Image::depth, _MagickPixelPacket::depth, DestroyCacheView(), _Image::exception, _Image::fuzz, _MagickPixelPacket::fuzz, GetCacheViewAuthenticIndexQueue(), GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _MagickPixelPacket::matte, QueueCacheViewAuthenticPixels(), _Image::rows, SetPixelPacket(), _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
SetImageExtent()
MagickExport MagickBooleanType SetImageExtent (Image * image, const size_t columns, const size_t rows)
References _Image::columns, _Image::depth, _Image::exception, _Image::filename, GetMagickModule, ImageError, _Image::rows, SyncImagePixelCache(), ThrowBinaryImageException, and ThrowMagickException().
Referenced by CloneImage(), ConstituteImage(), DrawClippingMask(), DrawCompositeMask(), PolaroidImage(), and RenderHoughLines().
SetImageInfo()
MagickExport MagickBooleanType SetImageInfo (ImageInfo * image_info, const unsigned int frames, ExceptionInfo * exception)
References AcquireExceptionInfo(), AcquireImage(), _ImageInfo::adjoin, _ImageInfo::affirm, CanonicalPath, CloneString(), CloseBlob(), CopyMagickString(), _ImageInfo::debug, DestroyExceptionInfo(), DestroyImage(), _ImageInfo::endian, ExplicitFormatType, ExtensionPath, _ImageInfo::extract, _Image::filename, _ImageInfo::filename, _MagickInfo::format_type, GetDelegateInfo(), GetMagicInfo(), GetMagickAdjoin(), GetMagickEndianSupport(), GetMagickInfo(), GetMagickModule, GetMagicName(), GetPathComponent(), ImageToFile(), InterpretImageFilename(), IsBlobExempt(), IsBlobSeekable(), IsGeometry(), IsGlob(), IsMagickConflict(), IsSceneGeometry(), LocaleCompare(), LocaleUpper(), LogMagickEvent(), _ImageInfo::magick, MagickCoreSignature, MagickFalse, MagickPath, MagickTrue, MaxTextExtent, _ImageInfo::number_scenes, OpenBlob(), ReadBinaryBlobMode, ReadBlob(), RelinquishUniqueFileResource(), _ImageInfo::scene, _ImageInfo::scenes, SeekBlob(), SetImageInfoFile(), _ImageInfo::signature, StringToUnsignedLong(), SubcanonicalPath, _ImageInfo::subimage, SubimagePath, _ImageInfo::subrange, Swap, _ImageInfo::temporary, TraceEvent, UndefinedEndian, and UndefinedFormatType.
Referenced by BlobToImage(), DrawPrimitive(), GlobExpression(), ImagesToBlob(), ImageToBlob(), InvokeDelegate(), PingBlob(), PingImages(), ReadImage(), ReadImages(), WriteImage(), WriteImages(), and WriteStreamImage().
SetImageInfoBlob()
MagickExport void SetImageInfoBlob (ImageInfo * image_info, const void * blob, const size_t length)
References _ImageInfo::blob, _ImageInfo::debug, _ImageInfo::filename, GetMagickModule, _ImageInfo::length, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ImageInfo::signature, and TraceEvent.
Referenced by CloneImageInfo().
SetImageInfoFile()
MagickExport void SetImageInfoFile (ImageInfo * image_info, FILE * file)
References _ImageInfo::debug, _ImageInfo::file, _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ImageInfo::signature, and TraceEvent.
Referenced by CloneImageInfo(), InjectImageBlob(), and SetImageInfo().
SetImageMask()
MagickExport MagickBooleanType SetImageMask (Image * image, const Image * mask)
References CloneImage(), _Image::columns, _Image::debug, DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetMagickModule, ImageError, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::mask, NewImageList(), _Image::rows, SetImageStorageClass(), _Image::signature, ThrowBinaryImageException, and TraceEvent.
Referenced by CompareImageChannels(), DrawCompositeMask(), DrawPrimitive(), and RenderMVGContent().
SetImageOpacity()
MagickExport MagickBooleanType SetImageOpacity (Image * image, const Quantum opacity)
References AcquireAuthenticCacheView(), _Image::columns, _Image::debug, DestroyCacheView(), _Image::exception, GetCacheViewAuthenticPixels(), GetMagickModule, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _Image::rows, SetPixelOpacity, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by ConformMagickPixelPacket(), DrawPrimitive(), and SetImageAlphaChannel().
SetImageStorageClass()
MagickExport MagickBooleanType SetImageStorageClass (Image * image, const ClassType storage_class)
References _Image::debug, _Image::exception, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, _Image::storage_class, SyncImagePixelCache(), and TraceEvent.
Referenced by AcquireImageColormap(), AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), AddNoiseImageChannel(), AnnotateImage(), AppendImages(), BilevelImageChannel(), BlackThresholdImageChannel(), BlueShiftImage(), ClipImagePath(), ClutImageChannel(), ColorFloodfillImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImageChannels(), ComplexImages(), CompositeImageChannel(), ConsolidateCMYKImages(), CopyImagePixels(), DespeckleImage(), DistortImage(), DrawAffineImage(), DuplexTransferImageViewIterator(), EnhanceImage(), EvaluateImageChannel(), EvaluateImages(), FilterImageChannel(), FloodfillPaintImage(), FrameImage(), FunctionImageChannel(), FxImageChannel(), GrayscaleImage(), HaldClutImageChannel(), HorizontalFilter(), ImplodeImage(), ImportImagePixels(), InterpolativeResizeImage(), KuwaharaImageChannel(), LocalContrastImage(), MatteFloodfillImage(), MeanShiftImage(), MorphImages(), MorphologyApply(), MotionBlurImageChannel(), OilPaintImage(), OpaquePaintImageChannel(), OrderedPosterizeImageChannel(), PlasmaImage(), PolynomialImageChannel(), ProfileImage(), RaiseImage(), RandomThresholdImageChannel(), RenderMVGContent(), RGBTransformImage(), RotationalBlurImageChannel(), ScaleImage(), SelectiveBlurImageChannel(), SeparateImageChannel(), SepiaToneImage(), SetCacheViewStorageClass(), SetImage(), SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageClipMask(), SetImageMask(), SetImageType(), SetImageViewIterator(), ShadeImage(), ShearImage(), ShearRotateImage(), SimilarityMetricImage(), SmushImages(), SparseColorImage(), SpliceImage(), SpreadImage(), StatisticImageChannel(), SteganoImage(), StereoAnaglyphImage(), SwirlImage(), TextureImage(), ThresholdImageChannel(), TintImage(), TransferImageViewIterator(), TransformRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), UniqueImageColors(), UpdateImageViewIterator(), VerticalFilter(), VignetteImage(), WaveImage(), WaveletDenoiseImage(), and WhiteThresholdImageChannel().
SetImageVirtualPixelMethod()
MagickExport VirtualPixelMethod SetImageVirtualPixelMethod (const Image * image, const VirtualPixelMethod virtual_pixel_method)
References _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, SetPixelCacheVirtualMethod(), _Image::signature, and TraceEvent.
Referenced by DeskewImage(), DistortResizeImage(), RotateImage(), ShadowImage(), and TextureImage().
SmushImages()
MagickExport Image * SmushImages (const Image * images, const MagickBooleanType stack, const ssize_t offset, ExceptionInfo * exception)
References AcquireVirtualCacheView(), CloneImage(), _Image::columns, CompositeImage(), _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetMagickModule, GetNextImageInList(), _Image::gravity, GravityAdjustGeometry(), InheritException(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OverCompositeOp, _Image::previous, _Image::rows, SetGeometry(), SetImageBackgroundColor(), SetImageProgress(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, SmushImageTag, SmushXGap(), SmushYGap(), TraceEvent, _RectangleInfo::x, and _RectangleInfo::y.
SmushXGap()
static ssize_t SmushXGap (const Image * smush_image, const Image * images, const ssize_t offset, ExceptionInfo * exception) static
References AcquireVirtualCacheView(), _Image::columns, DestroyCacheView(), GetCacheViewVirtualPixels(), GetPixelOpacity, _Image::gravity, GravityAdjustGeometry(), _Image::previous, _Image::rows, SetGeometry(), TransparentOpacity, and _RectangleInfo::y.
Referenced by SmushImages().
SmushYGap()
static ssize_t SmushYGap (const Image * smush_image, const Image * images, const ssize_t offset, ExceptionInfo * exception) static
References AcquireVirtualCacheView(), _Image::columns, DestroyCacheView(), GetCacheViewVirtualPixels(), GetPixelOpacity, _Image::gravity, GravityAdjustGeometry(), _Image::previous, _Image::rows, SetGeometry(), TransparentOpacity, and _RectangleInfo::x.
Referenced by SmushImages().
StripImage()
MagickExport MagickBooleanType StripImage (Image * image)
References _Image::debug, DeleteImageProperty(), DestroyImageProfiles(), GetMagickModule, LogMagickEvent(), MagickFalse, SetImageArtifact(), and TraceEvent.
SyncImage()
MagickExport MagickBooleanType SyncImage (Image * image)
References AcquireAuthenticCacheView(), _Image::colormap, _Image::columns, CorruptImageWarning, _Image::debug, DestroyCacheView(), _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelIndex, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _Image::ping, PseudoClass, PushColormapIndex(), _Image::rows, SetPixelRgb, SetPixelRGBO, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), _Image::taint, ThrowMagickException(), and TraceEvent.
Referenced by AssignImageColors(), ClampImageChannel(), Classify(), ClipImagePath(), ConnectedComponentsImage(), GrayscaleImage(), OpaqueImage(), PerceptibleImageChannel(), RGBTransformImage(), SteganoImage(), and TransformRGBImage().
SyncImageSettings()
MagickExport MagickBooleanType SyncImageSettings (const ImageInfo * image_info, Image * image)
References _Image::background_color, _Image::bias, _Image::black_point_compensation, _ChromaticityInfo::blue_primary, _Image::border_color, _Image::chromaticity, _Image::colors, _Image::compose, _Image::compression, _Image::debug, _Image::depth, DestroyString(), _Image::endian, _Image::exception, _Image::filename, _Image::filter, FormatLocaleString(), _Image::fuzz, GetImageOption(), GetMagickModule, GetNextImageOption(), GetPageGeometry(), _Image::gravity, _ChromaticityInfo::green_primary, _Image::intensity, _Image::interlace, _Image::interpolate, _Image::iterations, LogMagickEvent(), MagickBooleanOptions, MagickComposeOptions, MagickCompressOptions, MagickCoreSignature, MagickEndianOptions, MagickFalse, MagickFilterOptions, MagickGravityOptions, MagickIntentOptions, MagickInterlaceOptions, MagickInterpolateOptions, MagickOrientationOptions, MagickPixelIntensityOptions, MagickResolutionOptions, MagickTrue, MagickTypeOptions, _Image::matte_color, MaxTextExtent, _Image::orientation, _Image::page, ParseAbsoluteGeometry(), ParseCommandOption(), ParseGeometry(), PixelsPerCentimeterResolution, PixelsPerInchResolution, _Image::quality, _ImageInfo::quality, QuantumRange, QueryColorDatabase(), _ChromaticityInfo::red_primary, _Image::rendering_intent, ResetImageOptionIterator(), _GeometryInfo::rho, _Image::scene, SetImageArtifact(), _GeometryInfo::sigma, SigmaValue, _Image::signature, _ImageInfo::signature, StringToDoubleInterval(), StringToUnsignedLong(), _Image::taint, _Image::tile_offset, TraceEvent, _Image::transparent_color, _Image::type, UndefinedCompressionQuality, UndefinedResolution, _Image::units, _ImageInfo::units, _ChromaticityInfo::white_point, _PrimaryInfo::x, _Image::x_resolution, _PrimaryInfo::y, and _Image::y_resolution.
Referenced by AcquireImage(), and SyncImagesSettings().
SyncImagesSettings()
MagickExport MagickBooleanType SyncImagesSettings (ImageInfo * image_info, Image * images)
References _Image::debug, DeleteImageOption(), _Image::filename, GetMagickModule, GetNextImageInList(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::signature, _ImageInfo::signature, SyncImageSettings(), and TraceEvent.