MagickCore: image-private.h File Reference
image-private.h File Reference
Macros
#define BackgroundColor "#ffffff" /* white */
#define BorderColor "#dfdfdf" /* gray */
#define DefaultResolution 72.0
#define DefaultTileFrame "15x15+3+3"
#define DefaultTileGeometry "120x120+4+3>"
#define DefaultTileLabel "%f\n%G\n%b"
#define ForegroundColor "#000" /* black */
#define LoadImagesTag "Load/Images"
#define LoadImageTag "Load/Image"
#define Magick2PI 6.28318530717958647692528676655900576839433879875020
#define MagickAbsoluteValue(x) ((x) < 0 ? -(x) : (x))
#define MagickMax(x, y) (((x) > (y)) ? (x) : (y))
#define MagickMin(x, y) (((x) < (y)) ? (x) : (y))
#define MagickPHI 1.61803398874989484820458683436563811772030917980576
#define MagickPI2 1.57079632679489661923132169163975144209858469968755
#define MagickPI 3.14159265358979323846264338327950288419716939937510
#define MagickSQ1_2 0.70710678118654752440084436210484903928483593768847
#define MagickSQ2 1.41421356237309504880168872420969807856967187537695
#define MagickSQ2PI 2.50662827463100024161235523934010416269302368164062
#define MAGICK_SIZE_MAX (SIZE_MAX)
#define MAGICK_SSIZE_MAX (SSIZE_MAX)
#define MAGICK_SSIZE_MIN (-(SSIZE_MAX)-1)
#define MatteColor "#bdbdbd" /* gray */
#define PSDensityGeometry "72.0x72.0"
#define PSPageGeometry "612x792"
#define SaveImagesTag "Save/Images"
#define SaveImageTag "Save/Image"
#define TransparentColor "#00000000" /* transparent black */
#define UndefinedCompressionQuality 0UL
#define UndefinedTicksPerSecond 100L
Functions
static size_t CastDoubleToLong (const double x)
static QuantumAny CastDoubleToQuantumAny (const double x)
static size_t CastDoubleToUnsigned (const double x)
static double DegreesToRadians (const double degrees)
static MagickRealType RadiansToDegrees (const MagickRealType radians)
static unsigned char ScaleColor5to8 (const unsigned int color)
static unsigned char ScaleColor6to8 (const unsigned int color)
static unsigned int ScaleColor8to5 (const unsigned char color)
static unsigned int ScaleColor8to6 (const unsigned char color)
Macro Definition Documentation
BackgroundColor
#define BackgroundColor "#ffffff" /* white */
BorderColor
#define BorderColor "#dfdfdf" /* gray */
DefaultResolution
#define DefaultResolution 72.0
DefaultTileFrame
#define DefaultTileFrame "15x15+3+3"
DefaultTileGeometry
#define DefaultTileGeometry "120x120+4+3>"
DefaultTileLabel
#define DefaultTileLabel "%f\n%G\n%b"
ForegroundColor
#define ForegroundColor "#000" /* black */
LoadImagesTag
#define LoadImagesTag "Load/Images"
LoadImageTag
#define LoadImageTag "Load/Image"
Magick2PI
#define Magick2PI 6.28318530717958647692528676655900576839433879875020
MAGICK_SIZE_MAX
#define MAGICK_SIZE_MAX (SIZE_MAX)
MAGICK_SSIZE_MAX
#define MAGICK_SSIZE_MAX (SSIZE_MAX)
MAGICK_SSIZE_MIN
#define MAGICK_SSIZE_MIN (-(SSIZE_MAX)-1)
MagickAbsoluteValue
#define MagickAbsoluteValue (x) ((x) < 0 ? -(x) : (x))
MagickMax
#define MagickMax (x, y) (((x) > (y)) ? (x) : (y))
MagickMin
#define MagickMin (x, y) (((x) < (y)) ? (x) : (y))
MagickPHI
#define MagickPHI 1.61803398874989484820458683436563811772030917980576
MagickPI
#define MagickPI 3.14159265358979323846264338327950288419716939937510
MagickPI2
#define MagickPI2 1.57079632679489661923132169163975144209858469968755
MagickSQ1_2
#define MagickSQ1_2 0.70710678118654752440084436210484903928483593768847
MagickSQ2
#define MagickSQ2 1.41421356237309504880168872420969807856967187537695
MagickSQ2PI
#define MagickSQ2PI 2.50662827463100024161235523934010416269302368164062
MatteColor
#define MatteColor "#bdbdbd" /* gray */
PSDensityGeometry
#define PSDensityGeometry "72.0x72.0"
PSPageGeometry
#define PSPageGeometry "612x792"
SaveImagesTag
#define SaveImagesTag "Save/Images"
SaveImageTag
#define SaveImageTag "Save/Image"
TransparentColor
#define TransparentColor "#00000000" /* transparent black */
UndefinedCompressionQuality
#define UndefinedCompressionQuality 0UL
UndefinedTicksPerSecond
#define UndefinedTicksPerSecond 100L
Function Documentation
CastDoubleToLong()
static size_t CastDoubleToLong (const double x) inline static
References IsNaN, MAGICK_SSIZE_MAX, and MAGICK_SSIZE_MIN.
Referenced by AcquireImage(), AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), CheckPrimitiveExtent(), CloneImage(), ConvertHWBToRGB(), CropToFitImage(), DrawAffineImage(), DrawGradientImage(), DrawPolygonPrimitive(), DrawPrimitive(), InterpolateMagickPixelPacket(), LogPrimitiveInfo(), MotionBlurImageChannel(), PixelRoundOffset(), PlasmaImageProxy(), ReadImage(), RenderMVGContent(), RenderPostscript(), SetImageProperty(), ShearImage(), ShearRotateImage(), TraceArcPath(), TraceStrokePolygon(), XShearImage(), and YShearImage().
CastDoubleToQuantumAny()
static QuantumAny CastDoubleToQuantumAny (const double x) inline static
References IsNaN.
CastDoubleToUnsigned()
static size_t CastDoubleToUnsigned (const double x) inline static
References IsNaN, and MAGICK_SIZE_MAX.
Referenced by AnnotateImage(), CropToFitImage(), FormatMagickCaption(), ParseMetaGeometry(), RenderMVGContent(), ShadowImage(), and ShearRotateImage().
DegreesToRadians()
static double DegreesToRadians (const double degrees) inline static
References MagickPI.
Referenced by CompositeImageChannel(), DeskewImage(), GenerateCoefficients(), GetStopColorOffset(), GradientImage(), HoughLineImage(), MotionBlurImageChannel(), RenderMVGContent(), RotateImage(), RotationalBlurImageChannel(), ShadeImage(), ShearImage(), ShearRotateImage(), SwirlImage(), TraceArcPath(), TraceEllipse(), and TraceStrokePolygon().
RadiansToDegrees()
static MagickRealType RadiansToDegrees (const MagickRealType radians) inline static
References MagickPI.
Referenced by DeskewImage(), GetImageChannelMoments(), and ScaleResampleFilter().
ScaleColor5to8()
static unsigned char ScaleColor5to8 (const unsigned int color) inline static
ScaleColor6to8()
static unsigned char ScaleColor6to8 (const unsigned int color) inline static
ScaleColor8to5()
static unsigned int ScaleColor8to5 (const unsigned char color) inline static
ScaleColor8to6()
static unsigned int ScaleColor8to6 (const unsigned char color) inline static