MagickCore: layer.h File Reference
layer.h File Reference
Enumerations
enum DisposeType {
UnrecognizedDispose , UndefinedDispose = 0 , NoneDispose = 1 , BackgroundDispose = 2 ,
PreviousDispose = 3
}
enum ImageLayerMethod {
UndefinedLayer , CoalesceLayer , CompareAnyLayer , CompareClearLayer ,
CompareOverlayLayer , DisposeLayer , OptimizeLayer , OptimizeImageLayer ,
OptimizePlusLayer , OptimizeTransLayer , RemoveDupsLayer , RemoveZeroLayer ,
CompositeLayer , MergeLayer , FlattenLayer , MosaicLayer ,
TrimBoundsLayer
}
Functions
MagickExport Image * CoalesceImages (const Image *, ExceptionInfo *)
MagickExport Image * DisposeImages (const Image *, ExceptionInfo *)
MagickExport Image * CompareImageLayers (const Image *, const ImageLayerMethod, ExceptionInfo *)
MagickExport Image * DeconstructImages (const Image *, ExceptionInfo *)
MagickExport Image * MergeImageLayers (Image *, const ImageLayerMethod, ExceptionInfo *)
MagickExport Image * OptimizeImageLayers (const Image *, ExceptionInfo *)
MagickExport Image * OptimizePlusImageLayers (const Image *, ExceptionInfo *)
MagickExport void CompositeLayers (Image *, const CompositeOperator, Image *, const ssize_t, const ssize_t, ExceptionInfo *)
MagickExport void OptimizeImageTransparency (const Image *, ExceptionInfo *)
MagickExport void RemoveDuplicateLayers (Image **, ExceptionInfo *)
MagickExport void RemoveZeroDelayLayers (Image **, ExceptionInfo *)
Enumeration Type Documentation
DisposeType
enum DisposeType
Enumerator
UnrecognizedDispose
UndefinedDispose
NoneDispose
BackgroundDispose
PreviousDispose
ImageLayerMethod
enum ImageLayerMethod
Enumerator
UndefinedLayer
CoalesceLayer
CompareAnyLayer
CompareClearLayer
CompareOverlayLayer
DisposeLayer
OptimizeLayer
OptimizeImageLayer
OptimizePlusLayer
OptimizeTransLayer
RemoveDupsLayer
RemoveZeroLayer
CompositeLayer
MergeLayer
FlattenLayer
MosaicLayer
TrimBoundsLayer
Function Documentation
CoalesceImages()
MagickExport Image * CoalesceImages (const Image * , ExceptionInfo *)
CompareImageLayers()
MagickExport Image * CompareImageLayers (const Image * , const ImageLayerMethod, ExceptionInfo *)
CompositeLayers()
MagickExport void CompositeLayers (Image * , const CompositeOperator, Image * , const ssize_t, const ssize_t, ExceptionInfo *)
DeconstructImages()
MagickExport Image * DeconstructImages (const Image * , ExceptionInfo *)
DisposeImages()
MagickExport Image * DisposeImages (const Image * , ExceptionInfo *)
MergeImageLayers()
MagickExport Image * MergeImageLayers (Image * , const ImageLayerMethod, ExceptionInfo *)
OptimizeImageLayers()
MagickExport Image * OptimizeImageLayers (const Image * , ExceptionInfo *)
OptimizeImageTransparency()
MagickExport void OptimizeImageTransparency (const Image * , ExceptionInfo *)
OptimizePlusImageLayers()
MagickExport Image * OptimizePlusImageLayers (const Image * image, ExceptionInfo * exception)
References OptimizeLayerFrames(), and OptimizePlusLayer.
RemoveDuplicateLayers()
MagickExport void RemoveDuplicateLayers (Image ** , ExceptionInfo *)
RemoveZeroDelayLayers()
MagickExport void RemoveZeroDelayLayers (Image ** images, ExceptionInfo * exception)
References _Image::delay, DeleteImageFromList(), _Image::filename, GetFirstImageInList(), GetMagickModule, GetNextImageInList(), LogMagickEvent(), MagickCoreSignature, MagickFalse, OptionWarning, _ExceptionInfo::signature, ThrowMagickException(), and TraceEvent.