MagickCore: list.c File Reference
list.c File Reference
#include "magick/studio.h"
#include "magick/artifact.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/memory_.h"
#include "magick/string_.h"
#include "magick/string-private.h"
Functions
MagickExport void AppendImageToList (Image **images, const Image *append)
MagickExport Image * CloneImageList (const Image *images, ExceptionInfo *exception)
MagickExport Image * CloneImages (const Image *images, const char *scenes, ExceptionInfo *exception)
MagickExport void DeleteImageFromList (Image **images)
MagickExport void DeleteImages (Image **images, const char *scenes, ExceptionInfo *exception)
MagickExport Image * DestroyImageList (Image *images)
MagickExport Image * DuplicateImages (Image *images, const size_t number_duplicates, const char *scenes, ExceptionInfo *exception)
MagickExport Image * GetFirstImageInList (const Image *images)
MagickExport Image * GetImageFromList (const Image *images, const ssize_t index)
MagickExport ssize_t GetImageIndexInList (const Image *images)
MagickExport size_t GetImageListLength (const Image *images)
MagickExport Image * GetLastImageInList (const Image *images)
MagickExport Image * GetNextImageInList (const Image *images)
MagickExport Image * GetPreviousImageInList (const Image *images)
MagickExport Image ** ImageListToArray (const Image *images, ExceptionInfo *exception)
MagickExport void InsertImageInList (Image **images, Image *insert)
MagickExport Image * NewImageList (void)
MagickExport void PrependImageToList (Image **images, Image *image)
MagickExport Image * RemoveImageFromList (Image **images)
MagickExport Image * RemoveFirstImageFromList (Image **images)
MagickExport Image * RemoveLastImageFromList (Image **images)
MagickExport void ReplaceImageInList (Image **images, Image *replace)
MagickExport void ReplaceImageInListReturnLast (Image **images, Image *replace)
MagickExport void ReverseImageList (Image **images)
MagickExport Image * SpliceImageIntoList (Image **images, const size_t length, const Image *splice)
MagickExport Image * SplitImageList (Image *images)
MagickExport void SyncImageList (Image *images)
MagickExport Image * SyncNextImageInList (const Image *images)
Function Documentation
AppendImageToList()
MagickExport void AppendImageToList (Image ** images, const Image * append)
References _Image::debug, _Image::filename, GetFirstImageInList(), GetLastImageInList(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::next, _Image::previous, _Image::signature, and TraceEvent.
Referenced by CloneImages(), CompareImageLayers(), ComplexImages(), CompositeLayers(), ConsolidateCMYKImages(), CropImageToTiles(), DisposeImages(), DuplicateImages(), ForwardFourierTransformImage(), HoughLineImage(), InsertImageInList(), MorphImages(), OptimizeLayerFrames(), PingImages(), PrependImageToList(), PreviewImage(), PushImageList(), ReadImages(), SeparateImages(), SpliceImageIntoList(), and TransformImages().
CloneImageList()
MagickExport Image * CloneImageList (const Image * images, ExceptionInfo * exception)
References CloneImage(), DestroyImageList(), MagickCoreSignature, MagickTrue, _Image::next, _Image::previous, and _Image::signature.
Referenced by GetImageRegistry(), PushImageList(), SetImageList(), SetImageRegistry(), SpliceImageList(), and UnshiftImageList().
CloneImages()
MagickExport Image * CloneImages (const Image * images, const char * scenes, ExceptionInfo * exception)
References AppendImageToList(), CloneImage(), _Image::debug, _Image::filename, GetFirstImageInList(), GetImageArtifact(), GetImageListLength(), GetMagickModule, GetNextImageInList(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, NewImageList(), OptionError, _ExceptionInfo::signature, _Image::signature, StringToDouble(), ThrowMagickException(), and TraceEvent.
Referenced by DuplicateImages(), and ReadImage().
DeleteImageFromList()
MagickExport void DeleteImageFromList (Image ** images)
References DestroyImage(), and RemoveImageFromList().
Referenced by DeleteImageList(), DeleteImages(), DestroyImageList(), RemoveDuplicateLayers(), and RemoveZeroDelayLayers().
DeleteImages()
MagickExport void DeleteImages (Image ** images, const char * scenes, ExceptionInfo * exception)
References AcquireQuantumMemory(), DeleteImageFromList(), GetFirstImageInList(), GetImageListLength(), GetMagickModule, GetNextImageInList(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, RelinquishMagickMemory(), ResourceLimitError, _ExceptionInfo::signature, ThrowMagickException(), and TraceEvent.
DestroyImageList()
MagickExport Image * DestroyImageList (Image * images)
References _Image::debug, DeleteImageFromList(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
Referenced by CloneImageList(), CoalesceImages(), CompareImageLayers(), ComplexImages(), DestroyImages(), DestroyRegistryNode(), DisposeImages(), DrawPrimitive(), ForwardFourierTransformImage(), MontageImageList(), MorphImages(), OptimizeLayerFrames(), PreviewImage(), ReadImage(), RelinquishImageRegistry(), and RenderHoughLines().
DuplicateImages()
MagickExport Image * DuplicateImages (Image * images, const size_t number_duplicates, const char * scenes, ExceptionInfo * exception)
References AppendImageToList(), CloneImages(), _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, NewImageList(), _ExceptionInfo::signature, _Image::signature, and TraceEvent.
GetFirstImageInList()
MagickExport Image * GetFirstImageInList (const Image * images)
References MagickCoreSignature, _Image::previous, and _Image::signature.
Referenced by AcquireFxInfo(), AppendImageToList(), BlobToImage(), CloneImages(), CoalesceImages(), CompareImageLayers(), DeleteImages(), DisposeImages(), GetImageFromList(), HoughLineImage(), ImageListToArray(), MontageImageList(), MorphImages(), OptimizeImageTransparency(), OptimizeLayerFrames(), PingBlob(), ReadImage(), RemoveDuplicateLayers(), RemoveZeroDelayLayers(), RenderHoughLines(), ReplaceImageInList(), ReplaceImageInListReturnLast(), TransformImage(), and WriteImages().
GetImageFromList()
MagickExport Image * GetImageFromList (const Image * images, const ssize_t index)
References _Image::debug, _Image::filename, GetFirstImageInList(), GetLastImageInList(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::next, _Image::previous, _Image::signature, and TraceEvent.
Referenced by FxGetSymbol(), and GetImageList().
GetImageIndexInList()
MagickExport ssize_t GetImageIndexInList (const Image * images)
References MagickCoreSignature, _Image::previous, and _Image::signature.
Referenced by FxGetSymbol(), GetImageListIndex(), and GetMagickPropertyLetter().
GetImageListLength()
MagickExport size_t GetImageListLength (const Image * images)
References _Image::debug, _Image::filename, GetLastImageInList(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::previous, _Image::signature, and TraceEvent.
Referenced by AcquireFxInfo(), AcquirePixelThreadSet(), CloneImages(), CompareImageLayers(), ConsolidateCMYKImages(), DeleteImages(), DestroyFxInfo(), DestroyPixelThreadSet(), EvaluateImages(), FxGetSymbol(), GetImageListSize(), GetMagickProperty(), GetMagickPropertyLetter(), GetNumberScenes(), IdentifyImage(), ImageListToArray(), ImagesToBlob(), InvokeDelegate(), MergeImageLayers(), MontageImageList(), MorphImages(), OpenPixelCache(), OptimizeLayerFrames(), PolynomialImageChannel(), QuantizeImages(), ReadImage(), ThumbnailImage(), and WriteImages().
GetLastImageInList()
MagickExport Image * GetLastImageInList (const Image * images)
References MagickCoreSignature, _Image::next, and _Image::signature.
Referenced by AppendImageToList(), CompositeLayers(), GetImageFromList(), GetImageListLength(), MorphImages(), ReplaceImageInList(), and ReplaceImageInListReturnLast().
GetNextImageInList()
MagickExport Image * GetNextImageInList (const Image * images)
References _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::next, _Image::signature, and TraceEvent.
Referenced by AcquireNextImage(), AppendImages(), BlobToImage(), CloneImages(), CoalesceImages(), CombineImages(), CompareImageLayers(), CompositeLayers(), ConsolidateCMYKImages(), DeleteImageList(), DeleteImages(), DisposeImages(), EvaluateImages(), GetImageException(), GetNextImage(), IdentifyImage(), InvokeDelegate(), IsImageObject(), IsTaintImage(), MergeImageLayers(), MontageImageList(), MorphImages(), OpenBlob(), OptimizeImageTransparency(), OptimizeLayerFrames(), PingBlob(), PolynomialImageChannel(), QuantizeImages(), ReadImage(), RemapImages(), RemoveDuplicateLayers(), RemoveZeroDelayLayers(), SetImageList(), SmushImages(), SpliceImageList(), SyncImagesSettings(), WriteImage(), and WriteImages().
GetPreviousImageInList()
MagickExport Image * GetPreviousImageInList (const Image * images)
References MagickCoreSignature, _Image::previous, and _Image::signature.
Referenced by CoalesceImages(), DeleteImageList(), GetPreviousImage(), HuffmanEncodeImage(), IdentifyImage(), OpenBlob(), SetImageList(), SpliceImageList(), and WriteImage().
ImageListToArray()
MagickExport Image ** ImageListToArray (const Image * images, ExceptionInfo * exception)
References AcquireQuantumMemory(), _Image::debug, _Image::filename, GetFirstImageInList(), GetImageListLength(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::next, ResourceLimitError, _Image::signature, ThrowMagickException(), and TraceEvent.
Referenced by MontageImageList(), and TransformImages().
InsertImageInList()
MagickExport void InsertImageInList (Image ** images, Image * insert)
References AppendImageToList(), _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, SplitImageList(), and TraceEvent.
Referenced by SetImageList().
NewImageList()
MagickExport Image * NewImageList (void)
Referenced by CloneDrawInfo(), CloneImage(), CloneImages(), ComplexImages(), ConsolidateCMYKImages(), CropImageToTiles(), DisposeImages(), DuplicateImages(), ForwardFourierTransformImage(), MontageImageList(), OptimizeLayerFrames(), PingImages(), PreviewImage(), ReadImage(), ReadImages(), ReadInlineImage(), SeparateImages(), SetImageClipMask(), SetImageMask(), and TransformImages().
PrependImageToList()
MagickExport void PrependImageToList (Image ** images, Image * image)
References AppendImageToList().
Referenced by UnshiftImageList().
RemoveFirstImageFromList()
MagickExport Image * RemoveFirstImageFromList (Image ** images)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::next, _Image::previous, and TraceEvent.
Referenced by DrawPrimitive(), and ShiftImageList().
RemoveImageFromList()
MagickExport Image * RemoveImageFromList (Image ** images)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::next, _Image::previous, and TraceEvent.
Referenced by DeleteImageFromList(), and SpliceImageIntoList().
RemoveLastImageFromList()
MagickExport Image * RemoveLastImageFromList (Image ** images)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::next, _Image::previous, and TraceEvent.
Referenced by PopImageList().
ReplaceImageInList()
MagickExport void ReplaceImageInList (Image ** images, Image * replace)
References _Image::debug, DestroyImage(), _Image::filename, GetFirstImageInList(), GetLastImageInList(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::next, _Image::previous, _Image::signature, and TraceEvent.
Referenced by ReadImage().
ReplaceImageInListReturnLast()
MagickExport void ReplaceImageInListReturnLast (Image ** images, Image * replace)
References _Image::debug, DestroyImage(), _Image::filename, GetFirstImageInList(), GetLastImageInList(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::next, _Image::previous, _Image::signature, and TraceEvent.
ReverseImageList()
MagickExport void ReverseImageList (Image ** images)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::next, _Image::previous, and TraceEvent.
SpliceImageIntoList()
MagickExport Image * SpliceImageIntoList (Image ** images, const size_t length, const Image * splice)
References AppendImageToList(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, RemoveImageFromList(), _Image::signature, SplitImageList(), and TraceEvent.
Referenced by SpliceImageList().
SplitImageList()
MagickExport Image * SplitImageList (Image * images)
References _Image::next, and _Image::previous.
Referenced by InsertImageInList(), and SpliceImageIntoList().
SyncImageList()
MagickExport void SyncImageList (Image * images)
References MagickCoreSignature, _Image::next, _Image::previous, _Image::scene, and _Image::signature.
SyncNextImageInList()
MagickExport Image * SyncNextImageInList (const Image * images)
References _Image::blob, _Image::compression, DestroyBlob(), _Image::endian, MagickCoreSignature, _Image::next, ReferenceBlob(), _Image::signature, UndefinedCompression, and UndefinedEndian.