MagickCore: list.h File Reference
list.h File Reference
Functions
MagickExport Image * CloneImageList (const Image *, ExceptionInfo *)
MagickExport Image * CloneImages (const Image *, const char *, ExceptionInfo *)
MagickExport Image * DestroyImageList (Image *)
MagickExport Image * DuplicateImages (Image *, const size_t, const char *, ExceptionInfo *)
MagickExport Image * GetFirstImageInList (const Image *) magick_attribute((__pure__))
MagickExport Image * GetImageFromList (const Image *, const ssize_t) magick_attribute((__pure__))
MagickExport Image * GetLastImageInList (const Image *) magick_attribute((__pure__))
MagickExport Image * GetNextImageInList (const Image *) magick_attribute((__pure__))
MagickExport Image * GetPreviousImageInList (const Image *) magick_attribute((__pure__))
MagickExport Image ** ImageListToArray (const Image *, ExceptionInfo *)
MagickExport Image * NewImageList (void) magick_attribute((__const__))
MagickExport Image * RemoveImageFromList (Image **)
MagickExport Image * RemoveLastImageFromList (Image **)
MagickExport Image * RemoveFirstImageFromList (Image **)
MagickExport Image * SpliceImageIntoList (Image **, const size_t, const Image *)
MagickExport Image * SplitImageList (Image *)
MagickExport Image * SyncNextImageInList (const Image *)
MagickExport size_t GetImageListLength (const Image *) magick_attribute((__pure__))
MagickExport ssize_t GetImageIndexInList (const Image *) magick_attribute((__pure__))
MagickExport void AppendImageToList (Image **, const Image *)
MagickExport void DeleteImageFromList (Image **)
MagickExport void DeleteImages (Image **, const char *, ExceptionInfo *)
MagickExport void InsertImageInList (Image **, Image *)
MagickExport void PrependImageToList (Image **, Image *)
MagickExport void ReplaceImageInList (Image **, Image *)
MagickExport void ReplaceImageInListReturnLast (Image **, Image *)
MagickExport void ReverseImageList (Image **)
MagickExport void SyncImageList (Image *)
Function Documentation
AppendImageToList()
MagickExport void AppendImageToList (Image ** , const Image *)
CloneImageList()
MagickExport Image * CloneImageList (const Image * , ExceptionInfo *)
CloneImages()
MagickExport Image * CloneImages (const Image * , const char * , ExceptionInfo *)
DeleteImageFromList()
MagickExport void DeleteImageFromList (Image **)
DeleteImages()
MagickExport void DeleteImages (Image ** , const char * , ExceptionInfo *)
DestroyImageList()
MagickExport Image * DestroyImageList (Image *)
DuplicateImages()
MagickExport Image * DuplicateImages (Image * , const size_t, const char * , ExceptionInfo *)
GetFirstImageInList()
MagickExport Image * GetFirstImageInList (const Image *)
GetImageFromList()
MagickExport Image * GetImageFromList (const Image * , const ssize_t)
GetImageIndexInList()
MagickExport ssize_t GetImageIndexInList (const Image * images)
References MagickCoreSignature, _Image::previous, and _Image::signature.
Referenced by FxGetSymbol(), GetImageListIndex(), and GetMagickPropertyLetter().
GetImageListLength()
MagickExport size_t GetImageListLength (const Image * images)
References _Image::debug, _Image::filename, GetLastImageInList(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::previous, _Image::signature, and TraceEvent.
Referenced by AcquireFxInfo(), AcquirePixelThreadSet(), CloneImages(), CompareImageLayers(), ConsolidateCMYKImages(), DeleteImages(), DestroyFxInfo(), DestroyPixelThreadSet(), EvaluateImages(), FxGetSymbol(), GetImageListSize(), GetMagickProperty(), GetMagickPropertyLetter(), GetNumberScenes(), IdentifyImage(), ImageListToArray(), ImagesToBlob(), InvokeDelegate(), MergeImageLayers(), MontageImageList(), MorphImages(), OpenPixelCache(), OptimizeLayerFrames(), PolynomialImageChannel(), QuantizeImages(), ReadImage(), ThumbnailImage(), and WriteImages().
GetLastImageInList()
MagickExport Image * GetLastImageInList (const Image *)
GetNextImageInList()
MagickExport Image * GetNextImageInList (const Image *)
GetPreviousImageInList()
MagickExport Image * GetPreviousImageInList (const Image *)
ImageListToArray()
MagickExport Image ** ImageListToArray (const Image * , ExceptionInfo *)
InsertImageInList()
MagickExport void InsertImageInList (Image ** , Image *)
NewImageList()
MagickExport Image * NewImageList (void)
PrependImageToList()
MagickExport void PrependImageToList (Image ** , Image *)
RemoveFirstImageFromList()
MagickExport Image * RemoveFirstImageFromList (Image **)
RemoveImageFromList()
MagickExport Image * RemoveImageFromList (Image **)
RemoveLastImageFromList()
MagickExport Image * RemoveLastImageFromList (Image **)
ReplaceImageInList()
MagickExport void ReplaceImageInList (Image ** , Image *)
ReplaceImageInListReturnLast()
MagickExport void ReplaceImageInListReturnLast (Image ** , Image *)
ReverseImageList()
MagickExport void ReverseImageList (Image **)
SpliceImageIntoList()
MagickExport Image * SpliceImageIntoList (Image ** , const size_t, const Image *)
SplitImageList()
MagickExport Image * SplitImageList (Image *)
SyncImageList()
MagickExport void SyncImageList (Image * images)
References MagickCoreSignature, _Image::next, _Image::previous, _Image::scene, and _Image::signature.
SyncNextImageInList()
MagickExport Image * SyncNextImageInList (const Image * images)
References _Image::blob, _Image::compression, DestroyBlob(), _Image::endian, MagickCoreSignature, _Image::next, ReferenceBlob(), _Image::signature, UndefinedCompression, and UndefinedEndian.