MagickCore: locale_.h File Reference
locale_.h File Reference
#include "magick/hashmap.h"
Data Structures
struct _LocaleInfo
Typedefs
typedef struct _LocaleInfo LocaleInfo
Functions
MagickExport char ** GetLocaleList (const char *, size_t *, ExceptionInfo *)
MagickExport const char * GetLocaleMessage (const char *)
MagickExport const LocaleInfo * GetLocaleInfo_ (const char *, ExceptionInfo *)
MagickExport const LocaleInfo ** GetLocaleInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport double InterpretLocaleValue (const char *magick_restrict, char **magick_restrict)
MagickExport int LocaleCompare (const char *, const char *) magick_attribute((__pure__))
MagickExport int LocaleLowercase (const int)
MagickExport int LocaleNCompare (const char *, const char *, const size_t) magick_attribute((__pure__))
MagickExport int LocaleUppercase (const int)
MagickExport LinkedListInfo * DestroyLocaleOptions (LinkedListInfo *)
MagickExport LinkedListInfo * GetLocaleOptions (const char *, ExceptionInfo *)
MagickExport MagickBooleanType ListLocaleInfo (FILE *, ExceptionInfo *)
MagickExport MagickBooleanType LocaleComponentGenesis (void)
MagickExport ssize_t FormatLocaleFile (FILE *, const char *magick_restrict,...) magick_attribute((__format__(__printf__
MagickExport ssize_t FormatLocaleFileList (FILE *, const char *magick_restrict, va_list) magick_attribute((__format__(__printf__
MagickExport ssize_t FormatLocaleString (char *magick_restrict, const size_t, const char *magick_restrict,...) magick_attribute((__format__(__printf__
MagickExport ssize_t FormatLocaleStringList (char *magick_restrict, const size_t, const char *magick_restrict, va_list) magick_attribute((__format__(__printf__
MagickExport ssize_t MagickExport void LocaleComponentTerminus (void)
MagickExport ssize_t MagickExport void LocaleLower (char *)
MagickExport ssize_t MagickExport void LocaleUpper (char *)
Typedef Documentation
LocaleInfo
typedef struct _LocaleInfo LocaleInfo
Function Documentation
DestroyLocaleOptions()
MagickExport LinkedListInfo * DestroyLocaleOptions (LinkedListInfo *)
FormatLocaleFile()
MagickExport ssize_t FormatLocaleFile (FILE * , const char * magick_restrict, ...)
FormatLocaleFileList()
MagickExport ssize_t FormatLocaleFileList (FILE * , const char * magick_restrict, va_list)
FormatLocaleString()
MagickExport ssize_t FormatLocaleString (char * magick_restrict, const size_t, const char * magick_restrict, ...)
FormatLocaleStringList()
MagickExport ssize_t FormatLocaleStringList (char * magick_restrict, const size_t, const char * magick_restrict, va_list)
GetLocaleInfo_()
MagickExport const LocaleInfo * GetLocaleInfo_ (const char * , ExceptionInfo *)
GetLocaleInfoList()
MagickExport const LocaleInfo ** GetLocaleInfoList (const char * pattern, size_t * number_messages, ExceptionInfo * exception)
References AcquireQuantumMemory(), GetLocaleInfo_(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), locale_cache, locale_semaphore, LocaleInfoCompare(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickTrue, ResetSplayTreeIterator(), _LocaleInfo::stealth, _LocaleInfo::tag, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListLocaleInfo().
GetLocaleList()
MagickExport char ** GetLocaleList (const char * pattern, size_t * number_messages, ExceptionInfo * exception)
References AcquireQuantumMemory(), ConstantString(), GetLocaleInfo_(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), locale_cache, locale_semaphore, LocaleTagCompare(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickTrue, _LocaleInfo::stealth, _LocaleInfo::tag, TraceEvent, and UnlockSemaphoreInfo().
GetLocaleMessage()
MagickExport const char * GetLocaleMessage (const char * tag)
References AcquireExceptionInfo(), DestroyExceptionInfo(), FormatLocaleString(), GetLocaleInfo_(), MaxTextExtent, and _LocaleInfo::message.
Referenced by GetLocaleExceptionMessage().
GetLocaleOptions()
MagickExport LinkedListInfo * GetLocaleOptions (const char * filename, ExceptionInfo * exception)
References AcquireStringInfo(), AppendValueToLinkedList(), ConfigureFileToStringInfo(), CopyMagickString(), DestroyLinkedList(), FormatLocaleString(), GetConfigurePaths(), GetMagickModule, GetNextValueInLinkedList(), LocaleEvent, LogMagickEvent(), MaxTextExtent, NewLinkedList(), RelinquishMagickMemory(), ResetLinkedListIterator(), SetStringInfoDatum(), SetStringInfoLength(), SetStringInfoPath(), and TraceEvent.
Referenced by AcquireLocaleSplayTree().
InterpretLocaleValue()
MagickExport double InterpretLocaleValue (const char * magick_restrict, char ** magick_restrict)
ListLocaleInfo()
MagickExport MagickBooleanType ListLocaleInfo (FILE * , ExceptionInfo *)
LocaleCompare()
MagickExport int LocaleCompare (const char * , const char *)
LocaleComponentGenesis()
MagickExport MagickBooleanType LocaleComponentGenesis (void)
References AllocateSemaphoreInfo(), locale_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
LocaleComponentTerminus()
MagickExport ssize_t MagickExport void LocaleComponentTerminus (void)
LocaleLower()
MagickExport ssize_t MagickExport void LocaleLower (char *)
LocaleLowercase()
MagickExport int LocaleLowercase (const int)
LocaleNCompare()
MagickExport int LocaleNCompare (const char * , const char * , const size_t)
LocaleUpper()
MagickExport ssize_t MagickExport void LocaleUpper (char * string)
References LocaleUppercase().
Referenced by InvokeDelegate(), and SetImageInfo().
LocaleUppercase()
MagickExport int LocaleUppercase (const int c)
Referenced by LocaleUpper(), and StoreToken().