MagickCore: locale.c File Reference
locale.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/client.h"
#include "magick/configure.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/hashmap.h"
#include "magick/image-private.h"
#include "magick/locale_.h"
#include "magick/log.h"
#include "magick/memory_.h"
#include "magick/nt-base-private.h"
#include "magick/semaphore.h"
#include "magick/splay-tree.h"
#include "magick/string_.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/xml-tree.h"
#include "magick/xml-tree-private.h"
Macros
#define LocaleFilename "locale.xml"
#define MaxRecursionDepth 200
Functions
static MagickBooleanType IsLocaleTreeInstantiated (ExceptionInfo *)
static MagickBooleanType LoadLocaleCache (SplayTreeInfo *, const char *, const char *, const char *, const size_t, ExceptionInfo *)
static void * DestroyLocaleNode (void *locale_info)
static SplayTreeInfo * AcquireLocaleSplayTree (const char *filename, const char *locale, ExceptionInfo *exception)
static void * DestroyOptions (void *message)
MagickExport LinkedListInfo * DestroyLocaleOptions (LinkedListInfo *messages)
MagickExport ssize_t FormatLocaleFileList (FILE *file, const char *magick_restrict format, va_list operands)
MagickExport ssize_t FormatLocaleFile (FILE *file, const char *magick_restrict format,...)
MagickExport ssize_t FormatLocaleStringList (char *magick_restrict string, const size_t length, const char *magick_restrict format, va_list operands)
MagickExport ssize_t FormatLocaleString (char *magick_restrict string, const size_t length, const char *magick_restrict format,...)
MagickExport const LocaleInfo * GetLocaleInfo_ (const char *tag, ExceptionInfo *exception)
static int LocaleInfoCompare (const void *x, const void *y)
MagickExport const LocaleInfo ** GetLocaleInfoList (const char *pattern, size_t *number_messages, ExceptionInfo *exception)
static int LocaleTagCompare (const void *x, const void *y)
MagickExport char ** GetLocaleList (const char *pattern, size_t *number_messages, ExceptionInfo *exception)
MagickExport const char * GetLocaleMessage (const char *tag)
MagickExport LinkedListInfo * GetLocaleOptions (const char *filename, ExceptionInfo *exception)
MagickExport const char * GetLocaleValue (const LocaleInfo *locale_info)
MagickExport double InterpretLocaleValue (const char *magick_restrict string, char **magick_restrict sentinal)
MagickExport MagickBooleanType ListLocaleInfo (FILE *file, ExceptionInfo *exception)
static void ChopLocaleComponents (char *path, const size_t components)
static void LocaleFatalErrorHandler (const ExceptionType magick_unused(severity), const char *reason, const char *description)
MagickExport int LocaleCompare (const char *p, const char *q)
MagickExport void LocaleLower (char *string)
MagickExport int LocaleLowercase (const int c)
MagickExport int LocaleNCompare (const char *p, const char *q, const size_t length)
MagickExport void LocaleUpper (char *string)
MagickExport int LocaleUppercase (const int c)
MagickExport MagickBooleanType LocaleComponentGenesis (void)
MagickExport void LocaleComponentTerminus (void)
Variables
static const char * LocaleMap
static const unsigned char AsciiMap []
static SemaphoreInfo * locale_semaphore = (SemaphoreInfo *) NULL
static SplayTreeInfo * locale_cache = (SplayTreeInfo *) NULL
Macro Definition Documentation
LocaleFilename
#define LocaleFilename "locale.xml"
MaxRecursionDepth
#define MaxRecursionDepth 200
Function Documentation
AcquireLocaleSplayTree()
static SplayTreeInfo * AcquireLocaleSplayTree (const char * filename, const char * locale, ExceptionInfo * exception) static
References CompareSplayTreeString(), DestroyLocaleNode(), DestroyLocaleOptions(), GetLocaleOptions(), GetNextValueInLinkedList(), GetNumberOfNodesInSplayTree(), GetStringInfoDatum(), GetStringInfoPath(), LoadLocaleCache(), LocaleMap, MagickTrue, NewSplayTree(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by IsLocaleTreeInstantiated().
ChopLocaleComponents()
static void ChopLocaleComponents (char * path, const size_t components) static
Referenced by LoadLocaleCache().
DestroyLocaleNode()
static void * DestroyLocaleNode (void * locale_info) static
References DestroyString(), _LocaleInfo::message, _LocaleInfo::path, RelinquishMagickMemory(), and _LocaleInfo::tag.
Referenced by AcquireLocaleSplayTree().
DestroyLocaleOptions()
MagickExport LinkedListInfo * DestroyLocaleOptions (LinkedListInfo * messages)
References DestroyLinkedList(), DestroyOptions(), GetMagickModule, LogMagickEvent(), and TraceEvent.
Referenced by AcquireLocaleSplayTree().
DestroyOptions()
static void * DestroyOptions (void * message) static
References DestroyStringInfo().
Referenced by DestroyLocaleOptions().
FormatLocaleFile()
MagickExport ssize_t FormatLocaleFile (FILE * file, const char *magick_restrict format, ...)
References FormatLocaleFileList().
Referenced by AcquireResizeFilter(), AutoThresholdImage(), Classify(), CloseMagickLog(), DefaultErrorHandler(), DefaultFatalErrorHandler(), DefaultWarningHandler(), DestroyLogElement(), DistortImage(), ExternalDelegateCommand(), FxEvaluateSubexpression(), GetNumberColors(), IdentifyImage(), ListCoderInfo(), ListColorInfo(), ListCommandOptions(), ListConfigureInfo(), ListDelegateInfo(), ListLocaleInfo(), ListLogInfo(), ListMagicInfo(), ListMagickInfo(), ListMagickResourceInfo(), ListMagickVersion(), ListMimeInfo(), ListPolicyInfo(), ListThresholdMapFile(), ListThresholdMaps(), ListTypeInfo(), LocaleFatalErrorHandler(), LockSemaphoreInfo(), LogMagickEventList(), MorphologyApply(), OptimizeLayerFrames(), ParseKernelName(), PrintChannelFeatures(), PrintChannelLocations(), PrintChannelMoments(), PrintChannelPerceptualHash(), PrintChannelStatistics(), PrintStringInfo(), RenderPostscript(), ResamplePixelColor(), ScaleGeometryKernelInfo(), ScaleResampleFilter(), ShowKernelInfo(), SparseColorImage(), and UnlockSemaphoreInfo().
FormatLocaleFileList()
MagickExport ssize_t FormatLocaleFileList (FILE * file, const char *magick_restrict format, va_list operands)
Referenced by FormatLocaleFile().
FormatLocaleString()
MagickExport ssize_t FormatLocaleString (char *magick_restrict string, const size_t length, const char *magick_restrict format, ...)
References FormatLocaleStringList().
Referenced by AcquireTypeCache(), AnnotateImage(), AppendImageFormat(), AutoThresholdImage(), BlobToImage(), BlurImageChannel(), CannyEdgeImage(), CanonicalXMLContent(), ClipImagePath(), ClonePixelCacheRepository(), ColorMatrixImage(), ConcatenateColorComponent(), ConcatentateHexColorComponent(), ConnectPixelCacheServer(), DeleteMagickRegistry(), DeskewImage(), DestroyPixelCache(), DistortImage(), DistributePixelCacheServer(), DrawPatternPath(), DrawPrimitive(), EncodePredefinedEntities(), FilterImageChannel(), FormatMagickSize(), FormatMagickTime(), FormatPixelSize(), FxChannelStatistics(), GaussianBlurImageChannel(), GetConfigureBlob(), GetConfigureOptions(), GetConfigurePaths(), GetExecutionPath(), GetEXIFProperty(), GetImageProperty(), GetLocaleExceptionMessage(), GetLocaleMessage(), GetLocaleOptions(), GetMagickHomeURL(), GetMagickProperty(), GetMagickPropertyLetter(), GetMagickRegistry(), GetPageGeometry(), GetPathTemplate(), HoughLineImage(), IdentifyImage(), ImagesToBlob(), ImageToBlob(), InjectImageBlob(), InterpretImageFilename(), InterpretImageProperties(), InvokeDelegate(), ListMagickResourceInfo(), ListTypeInfo(), MagickToMime(), MontageImageList(), MorphologyApply(), OpenBlob(), OpenPixelCache(), PingBlob(), PolaroidImage(), PreviewImage(), RenderMVGContent(), RenderPostscript(), SelectiveBlurImageChannel(), SetImageProgress(), SetMagickRegistry(), SetPixelCacheExtent(), StringToStrings(), SyncImageSettings(), ThrowMagickExceptionList(), ThumbnailImage(), TraceBezierCurve(), TracePSClippath(), TraceSVGClippath(), TranslateEvent(), TranslateFilename(), VignetteImage(), XMLTreeInfoToXML(), and XMLTreeTagToXML().
FormatLocaleStringList()
MagickExport ssize_t FormatLocaleStringList (char *magick_restrict string, const size_t length, const char *magick_restrict format, va_list operands)
Referenced by FormatImageAttribute(), FormatImageProperty(), FormatLocaleString(), and FormatString().
GetLocaleInfo_()
MagickExport const LocaleInfo * GetLocaleInfo_ (const char * tag, ExceptionInfo * exception)
References GetNextValueInSplayTree(), GetValueFromSplayTree(), IsLocaleTreeInstantiated(), locale_cache, locale_semaphore, LocaleCompare(), LockSemaphoreInfo(), MagickFalse, ResetSplayTreeIterator(), and UnlockSemaphoreInfo().
Referenced by GetLocaleInfoList(), GetLocaleList(), and GetLocaleMessage().
GetLocaleInfoList()
MagickExport const LocaleInfo ** GetLocaleInfoList (const char * pattern, size_t * number_messages, ExceptionInfo * exception)
References AcquireQuantumMemory(), GetLocaleInfo_(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), locale_cache, locale_semaphore, LocaleInfoCompare(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickTrue, ResetSplayTreeIterator(), _LocaleInfo::stealth, _LocaleInfo::tag, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListLocaleInfo().
GetLocaleList()
MagickExport char ** GetLocaleList (const char * pattern, size_t * number_messages, ExceptionInfo * exception)
References AcquireQuantumMemory(), ConstantString(), GetLocaleInfo_(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), locale_cache, locale_semaphore, LocaleTagCompare(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickTrue, _LocaleInfo::stealth, _LocaleInfo::tag, TraceEvent, and UnlockSemaphoreInfo().
GetLocaleMessage()
MagickExport const char * GetLocaleMessage (const char * tag)
References AcquireExceptionInfo(), DestroyExceptionInfo(), FormatLocaleString(), GetLocaleInfo_(), MaxTextExtent, and _LocaleInfo::message.
Referenced by GetLocaleExceptionMessage().
GetLocaleOptions()
MagickExport LinkedListInfo * GetLocaleOptions (const char * filename, ExceptionInfo * exception)
References AcquireStringInfo(), AppendValueToLinkedList(), ConfigureFileToStringInfo(), CopyMagickString(), DestroyLinkedList(), FormatLocaleString(), GetConfigurePaths(), GetMagickModule, GetNextValueInLinkedList(), LocaleEvent, LogMagickEvent(), MaxTextExtent, NewLinkedList(), RelinquishMagickMemory(), ResetLinkedListIterator(), SetStringInfoDatum(), SetStringInfoLength(), SetStringInfoPath(), and TraceEvent.
Referenced by AcquireLocaleSplayTree().
GetLocaleValue()
MagickExport const char * GetLocaleValue (const LocaleInfo * locale_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _LocaleInfo::message, _LocaleInfo::signature, and TraceEvent.
InterpretLocaleValue()
MagickExport double InterpretLocaleValue (const char *magick_restrict string, char **magick_restrict sentinal)
Referenced by GetDrawValue(), InterpretSiPrefixValue(), StringToDouble(), and StringToDoubleInterval().
IsLocaleTreeInstantiated()
static MagickBooleanType IsLocaleTreeInstantiated (ExceptionInfo * exception) static
References AcquireLocaleSplayTree(), ActivateSemaphoreInfo(), ConstantString(), DestroyString(), GetEnvironmentValue(), locale_cache, locale_semaphore, LocaleFilename, LockSemaphoreInfo(), MagickFalse, MagickTrue, and UnlockSemaphoreInfo().
Referenced by GetLocaleInfo_().
ListLocaleInfo()
MagickExport MagickBooleanType ListLocaleInfo (FILE * file, ExceptionInfo * exception)
References FormatLocaleFile(), GetLocaleInfoList(), LocaleCompare(), MagickFalse, MagickTrue, _LocaleInfo::path, and RelinquishMagickMemory().
LoadLocaleCache()
static MagickBooleanType LoadLocaleCache (SplayTreeInfo * cache, const char * xml, const char * filename, const char * locale, const size_t depth, ExceptionInfo * exception)
References AcquireMagickMemory(), AcquireString(), AddValueToSplayTree(), ChopLocaleComponents(), ConcatenateMagickString(), ConfigureError, ConfigureEvent, ConstantString(), CopyMagickString(), DirectorySeparator, FileToXML(), GetMagickModule, GetNextToken(), GetPathComponent(), HeadPath, LoadLocaleCache(), LocaleCompare(), LocaleFatalErrorHandler(), LocaleNCompare(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickMaxRecursionDepth, MagickMin, MagickTrue, MaxTextExtent, _LocaleInfo::message, _LocaleInfo::path, RelinquishMagickMemory(), ResourceLimitError, ResourceLimitFatalError, SetFatalErrorHandler(), _LocaleInfo::signature, _LocaleInfo::tag, ThrowFatalException, and ThrowMagickException().
Referenced by AcquireLocaleSplayTree(), and LoadLocaleCache().
LocaleCompare()
MagickExport int LocaleCompare (const char * p, const char * q)
References AsciiMap.
Referenced by AcquireStreamPixels(), AcquireVirtualMemory(), AppendImageFormat(), CoderCompare(), CoderInfoCompare(), ColorCompare(), ColorInfoCompare(), CompareHashmapString(), CompareSplayTreeString(), ConfigureCompare(), ConfigureInfoCompare(), DelegateCompare(), DelegateInfoCompare(), DeleteImageProfile(), DrawPrimitive(), ExpandFilenames(), ExportCharPixel(), ExportDoublePixel(), ExportFloatPixel(), ExportIntegerPixel(), ExportLongPixel(), ExportQuantumPixel(), ExportShortPixel(), FileCompare(), FileToBlob(), FileToImage(), FileToXML(), FxEvaluateSubexpression(), FxGetSymbol(), Get8BIMProperty(), GetCoderInfo(), GetColorCompliance(), GetCommandOptionFlags(), GetConfigureInfo(), GetDelegateInfo(), GetEXIFProperty(), GetLocaleInfo_(), GetLogInfo(), GetMagickInfo(), GetMagickProperty(), GetMVGMacros(), GetPolicyInfo(), GetQuantumInfo(), GetThresholdMapFile(), GetTypeInfo(), GetTypeInfoByFamily(), GlobExpression(), GradientImage(), HuffmanEncodeImage(), IdentifyImage(), ImageToFile(), ImportCharPixel(), ImportDoublePixel(), ImportFloatPixel(), ImportIntegerPixel(), ImportLongPixel(), ImportQuantumPixel(), ImportShortPixel(), InvokeDelegate(), InvokeDynamicImageFilter(), IsMagickTrue(), IsOptionMember(), IsPathAccessible(), IsSkipTag(), IsStringNotFalse(), IsStringTrue(), IsTaintImage(), ListCoderInfo(), ListColorInfo(), ListConfigureInfo(), ListDelegateInfo(), ListFiles(), ListLocaleInfo(), ListLogInfo(), ListMagicInfo(), ListPolicyInfo(), ListTypeInfo(), LoadCoderCache(), LoadColorCache(), LoadConfigureCache(), LoadDelegateCache(), LoadLocaleCache(), LoadLogCache(), LoadMagicCache(), LoadPolicyCache(), LoadTypeCache(), LocaleInfoCompare(), LocaleTagCompare(), LogCompare(), LogInfoCompare(), MagicCompare(), MagicInfoCompare(), MagickCompare(), MagickInfoCompare(), MontageImageList(), OpenBlob(), OpenPixelCache(), ParseCommandOption(), ParseKernelArray(), PingImages(), ProfileImage(), QueryMagickColorCompliance(), RandomChannelThresholdImage(), ReadImage(), ReadImages(), RegisterStaticModule(), RemoveImageProfile(), RenderMVGContent(), RenderType(), SetImageInfo(), SetImageOption(), SetImageProfileInternal(), SetImageProperty(), StreamImagePixels(), ThrowException(), ThumbnailImage(), TranslateEvent(), TypeCompare(), TypeInfoCompare(), UnregisterMagickInfo(), UnregisterStaticModule(), WriteImage(), and WriteTo8BimProfile().
LocaleComponentGenesis()
MagickExport MagickBooleanType LocaleComponentGenesis (void)
References AllocateSemaphoreInfo(), locale_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
LocaleComponentTerminus()
MagickExport void LocaleComponentTerminus (void)
References ActivateSemaphoreInfo(), DestroySemaphoreInfo(), DestroySplayTree(), locale_cache, locale_semaphore, LockSemaphoreInfo(), and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
LocaleFatalErrorHandler()
static void LocaleFatalErrorHandler (const ExceptionType magick_unusedseverity, const char * reason, const char * description) static
References FormatLocaleFile(), GetClientName(), and magick_unreferenced.
Referenced by LoadLocaleCache().
LocaleInfoCompare()
static int LocaleInfoCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetLocaleInfoList().
LocaleLower()
MagickExport void LocaleLower (char * string)
References LocaleLowercase().
Referenced by GetColorTuple(), GetMagickProperty(), MagickToMime(), QueryMagickColorCompliance(), SetImageProfileInternal(), and ThumbnailImage().
LocaleLowercase()
MagickExport int LocaleLowercase (const int c)
Referenced by GlobExpression(), LocaleLower(), and StoreToken().
LocaleNCompare()
MagickExport int LocaleNCompare (const char * p, const char * q, const size_t length)
References AsciiMap.
Referenced by DrawPrimitive(), FxChannelStatistics(), FxEvaluateSubexpression(), FxGetSymbol(), FxOperatorPrecedence(), GetGeometry(), GetImageProperty(), GetMagickProperty(), GetNextToken(), GetPageGeometry(), GetProfilesFromResourceBlock(), InterpretDelegateProperties(), InterpretImageFilename(), InterpretImageProperties(), IsFxFunction(), LoadCoderCache(), LoadColorCache(), LoadConfigureCache(), LoadDelegateCache(), LoadLocaleCache(), LoadLogCache(), LoadMagicCache(), LoadPolicyCache(), LoadTypeCache(), OpenBlob(), ParseCSSColor(), ParseGeometry(), ParseLogHandlers(), QueryMagickColorCompliance(), ReadInlineImage(), and WriteTo8BimProfile().
LocaleTagCompare()
static int LocaleTagCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetLocaleList().
LocaleUpper()
MagickExport void LocaleUpper (char * string)
References LocaleUppercase().
Referenced by InvokeDelegate(), and SetImageInfo().
LocaleUppercase()
MagickExport int LocaleUppercase (const int c)
Referenced by LocaleUpper(), and StoreToken().
Variable Documentation
AsciiMap
const unsigned char AsciiMap[] static
Initial value:
=
  {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b,
    0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
    0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23,
    0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f,
    0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b,
    0x3c, 0x3d, 0x3e, 0x3f, 0x40, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67,
    0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d, 0x6e, 0x6f, 0x70, 0x71, 0x72, 0x73,
    0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7a, 0x5b, 0x5c, 0x5d, 0x5e, 0x5f,
    0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b,
    0x6c, 0x6d, 0x6e, 0x6f, 0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77,
    0x78, 0x79, 0x7a, 0x7b, 0x7c, 0x7d, 0x7e, 0x7f, 0x80, 0x81, 0x82, 0x83,
    0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f,
    0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0x9b,
    0x9c, 0x9d, 0x9e, 0x9f, 0xa0, 0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7,
    0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf, 0xb0, 0xb1, 0xb2, 0xb3,
    0xb4, 0xb5, 0xb6, 0xb7, 0xb8, 0xb9, 0xba, 0xbb, 0xbc, 0xbd, 0xbe, 0xbf,
    0xc0, 0xe1, 0xe2, 0xe3, 0xe4, 0xc5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xeb,
    0xec, 0xed, 0xee, 0xef, 0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7,
    0xf8, 0xf9, 0xfa, 0xdb, 0xdc, 0xdd, 0xde, 0xdf, 0xe0, 0xe1, 0xe2, 0xe3,
    0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xeb, 0xec, 0xed, 0xee, 0xef,
    0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9, 0xfa, 0xfb,
    0xfc, 0xfd, 0xfe, 0xff,
  }
Referenced by LocaleCompare(), and LocaleNCompare().
locale_cache
SplayTreeInfo* locale_cache = (SplayTreeInfo *) NULL static
Referenced by GetLocaleInfo_(), GetLocaleInfoList(), GetLocaleList(), IsLocaleTreeInstantiated(), and LocaleComponentTerminus().
locale_semaphore
SemaphoreInfo* locale_semaphore = (SemaphoreInfo *) NULL static
Referenced by GetLocaleInfo_(), GetLocaleInfoList(), GetLocaleList(), IsLocaleTreeInstantiated(), LocaleComponentGenesis(), and LocaleComponentTerminus().
LocaleMap
const char* LocaleMap static
Initial value:
=
    "<?xml version=\"1.0\"?>"
    "<localemap>"
    "  <locale name=\"C\">"
    "    <Exception>"
    "     <Message name=\"\">"
    "     </Message>"
    "    </Exception>"
    "  </locale>"
    "</localemap>"
Referenced by AcquireLocaleSplayTree().