MagickCore: log.c File Reference
log.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/client.h"
#include "magick/configure.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/hashmap.h"
#include "magick/log.h"
#include "magick/memory_.h"
#include "magick/nt-base-private.h"
#include "magick/option.h"
#include "magick/semaphore.h"
#include "magick/timer.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/token.h"
#include "magick/thread_.h"
#include "magick/thread-private.h"
#include "magick/timer-private.h"
#include "magick/utility.h"
#include "magick/utility-private.h"
#include "magick/version.h"
#include "magick/xml-tree.h"
#include "magick/xml-tree-private.h"
Data Structures
struct _EventInfo
struct _HandlerInfo
struct _LogInfo
struct _LogMapInfo
Macros
#define LogFilename "log.xml"
#define MegabytesToBytes(value) ((MagickSizeType) (value)*1024*1024)
Typedefs
typedef struct _EventInfo EventInfo
typedef struct _HandlerInfo HandlerInfo
typedef struct _LogMapInfo LogMapInfo
Enumerations
enum LogHandlerType {
UndefinedHandler = 0x0000 , NoHandler = 0x0000 , ConsoleHandler = 0x0001 , StdoutHandler = 0x0002 ,
StderrHandler = 0x0004 , FileHandler = 0x0008 , DebugHandler = 0x0010 , EventHandler = 0x0020 ,
MethodHandler = 0x0040
}
Functions
static LogHandlerType ParseLogHandlers (static MagickBooleanType LoadLogCache(LinkedListInfo const char *)
MagickExport void CloseMagickLog (void)
static LogInfo * GetLogInfo (const char *name, ExceptionInfo *exception)
static int LogInfoCompare (const void *x, const void *y)
MagickExport const LogInfo ** GetLogInfoList (const char *pattern, size_t *number_preferences, ExceptionInfo *exception)
static int LogCompare (const void *x, const void *y)
MagickExport char ** GetLogList (const char *pattern, size_t *number_preferences, ExceptionInfo *exception)
MagickExport const char * GetLogName (void)
static void CheckEventLogging ()
static MagickBooleanType IsLogCacheInstantiated (ExceptionInfo *exception)
MagickExport MagickBooleanType IsEventLogging (void)
MagickExport MagickBooleanType ListLogInfo (FILE *file, ExceptionInfo *exception)
MagickExport MagickBooleanType LogComponentGenesis (void)
static void * DestroyLogElement (void *log_info)
MagickExport void LogComponentTerminus (void)
static char * TranslateEvent (const LogEventType magick_unused(type), const char *module, const char *function, const size_t line, const char *domain, const char *event)
static char * TranslateFilename (const LogInfo *log_info)
MagickExport MagickBooleanType LogMagickEventList (const LogEventType type, const char *module, const char *function, const size_t line, const char *format, va_list operands)
MagickExport MagickBooleanType LogMagickEvent (const LogEventType type, const char *module, const char *function, const size_t line, const char *format,...)
static MagickBooleanType LoadLogCache (LinkedListInfo *cache, const char *xml, const char *filename, const size_t depth, ExceptionInfo *exception)
static LogHandlerType ParseLogHandlers (const char *handlers)
MagickExport LogEventType SetLogEventMask (const char *events)
MagickExport void SetLogFormat (const char *format)
MagickExport void SetLogMethod (MagickLogMethod method)
MagickExport const char * SetLogName (const char *name)
Variables
static const HandlerInfo LogHandlers [32]
static const LogMapInfo LogMap []
static char log_name [MaxTextExtent] = "Magick"
static LinkedListInfo * log_cache = (LinkedListInfo *) NULL
static MagickBooleanType event_logging = MagickFalse
static SemaphoreInfo * log_semaphore = (SemaphoreInfo *) NULL
Macro Definition Documentation
LogFilename
#define LogFilename "log.xml"
MegabytesToBytes
#define MegabytesToBytes (value) ((MagickSizeType) (value)*1024*1024)
Typedef Documentation
EventInfo
typedef struct _EventInfo EventInfo
HandlerInfo
typedef struct _HandlerInfo HandlerInfo
LogMapInfo
typedef struct _LogMapInfo LogMapInfo
Enumeration Type Documentation
LogHandlerType
enum LogHandlerType
Enumerator
UndefinedHandler
NoHandler
ConsoleHandler
StdoutHandler
StderrHandler
FileHandler
DebugHandler
EventHandler
MethodHandler
Function Documentation
CheckEventLogging()
static void CheckEventLogging () inline static
References event_logging, _LogInfo::event_mask, GetNextValueInLinkedList(), IsLinkedListEmpty(), log_cache, MagickFalse, MagickTrue, NoEvents, and ResetLinkedListIterator().
Referenced by IsLogCacheInstantiated(), and SetLogEventMask().
CloseMagickLog()
MagickExport void CloseMagickLog (void)
References AcquireExceptionInfo(), DestroyExceptionInfo(), _LogInfo::file, FormatLocaleFile(), GetLogInfo(), IsEventLogging(), LockSemaphoreInfo(), log_semaphore, MagickFalse, and UnlockSemaphoreInfo().
DestroyLogElement()
static void * DestroyLogElement (void * log_info) static
References DestroySemaphoreInfo(), DestroyString(), _LogInfo::event_semaphore, _LogInfo::file, _LogInfo::filename, _LogInfo::format, FormatLocaleFile(), _LogInfo::path, and RelinquishMagickMemory().
Referenced by LogComponentTerminus().
GetLogInfo()
static LogInfo * GetLogInfo (const char * name, ExceptionInfo * exception) static
References GetNextValueInLinkedList(), InsertValueInLinkedList(), IsLogCacheInstantiated(), LocaleCompare(), LockSemaphoreInfo(), log_cache, log_semaphore, MagickFalse, _LogInfo::name, RemoveElementByValueFromLinkedList(), ResetLinkedListIterator(), and UnlockSemaphoreInfo().
Referenced by CloseMagickLog(), GetLogInfoList(), GetLogList(), LogComponentGenesis(), LogMagickEventList(), SetLogEventMask(), SetLogFormat(), SetLogMethod(), and TranslateEvent().
GetLogInfoList()
MagickExport const LogInfo ** GetLogInfoList (const char * pattern, size_t * number_preferences, ExceptionInfo * exception)
References AcquireQuantumMemory(), GetLogInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), log_cache, log_semaphore, LogInfoCompare(), LogMagickEvent(), MagickFalse, _LogInfo::name, ResetLinkedListIterator(), _LogInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListLogInfo().
GetLogList()
MagickExport char ** GetLogList (const char * pattern, size_t * number_preferences, ExceptionInfo * exception)
References AcquireQuantumMemory(), ConstantString(), GetLogInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), log_cache, log_semaphore, LogCompare(), LogMagickEvent(), MagickFalse, _LogInfo::name, ResetLinkedListIterator(), _LogInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
GetLogName()
MagickExport const char * GetLogName (void)
References log_name.
Referenced by TranslateEvent(), and TranslateFilename().
IsEventLogging()
MagickExport MagickBooleanType IsEventLogging (void)
References event_logging.
Referenced by AcquireDistributeCacheInfo(), AcquireImage(), AcquireMagickResource(), AcquirePixelCache(), AcquireResampleFilter(), AcquireVirtualCacheView(), AddChildToXMLTree(), CloneDrawInfo(), CloneImage(), CloneImageInfo(), CloneMontageInfo(), CloseMagickLog(), ConvertPathToPolygon(), ConvertPrimitiveToPath(), DeleteImageRegistry(), DrawPrimitive(), ExpandFilenames(), GetBlobInfo(), GetDrawInfo(), GetImageInfo(), GetImageRegistry(), GetMontageInfo(), GetNextImageRegistry(), ListMagickVersion(), LogMagickEvent(), NewImageView(), NewImageViewRegion(), NewSplayTree(), NewXMLTreeTag(), RegistryComponentTerminus(), RelinquishMagickResource(), RemoveImageRegistry(), ResetImageRegistryIterator(), and SetImageRegistry().
IsLogCacheInstantiated()
static MagickBooleanType IsLogCacheInstantiated (ExceptionInfo * exception) static
References ActivateSemaphoreInfo(), CheckEventLogging(), LockSemaphoreInfo(), log_cache, log_semaphore, LogFilename, MagickFalse, MagickTrue, and UnlockSemaphoreInfo().
Referenced by GetLogInfo().
ListLogInfo()
MagickExport MagickBooleanType ListLogInfo (FILE * file, ExceptionInfo * exception)
References FormatLocaleFile(), _LogInfo::generations, GetLogInfoList(), _LogInfo::limit, LocaleCompare(), LogHandlers, MagickFalse, MagickTrue, _LogInfo::path, and RelinquishMagickMemory().
LoadLogCache()
static MagickBooleanType LoadLogCache (LinkedListInfo * cache, const char * xml, const char * filename, const size_t depth, ExceptionInfo * exception) static
References AcquireMagickMemory(), AcquireString(), AppendValueToLinkedList(), ConcatenateMagickString(), ConfigureError, ConstantString(), CopyMagickString(), DestroyString(), DirectorySeparator, _LogInfo::event_mask, _LogInfo::filename, FileToXML(), _LogInfo::format, _LogInfo::generations, GetMagickModule, GetNextToken(), GetPathComponent(), GetTimerInfo(), _LogInfo::handler_mask, HeadPath, _LogInfo::limit, LoadLogCache(), LocaleCompare(), LocaleNCompare(), MagickCoreSignature, MagickFalse, MagickLogEventOptions, MagickMaxRecursionDepth, MagickTrue, MaxTextExtent, ParseCommandOption(), ParseLogHandlers(), _LogInfo::path, RelinquishMagickMemory(), ResourceLimitError, ResourceLimitFatalError, _LogInfo::signature, StringToUnsignedLong(), ThrowFatalException, ThrowMagickException(), and _LogInfo::timer.
Referenced by LoadLogCache().
LogCompare()
static int LogCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetLogList().
LogComponentGenesis()
MagickExport MagickBooleanType LogComponentGenesis (void)
References AcquireExceptionInfo(), AllocateSemaphoreInfo(), DestroyExceptionInfo(), GetLogInfo(), log_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
LogComponentTerminus()
MagickExport void LogComponentTerminus (void)
References ActivateSemaphoreInfo(), DestroyLinkedList(), DestroyLogElement(), DestroySemaphoreInfo(), event_logging, LockSemaphoreInfo(), log_cache, log_semaphore, MagickFalse, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
LogInfoCompare()
static int LogInfoCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetLogInfoList().
LogMagickEvent()
MagickExport MagickBooleanType LogMagickEvent (const LogEventType type, const char * module, const char * function, const size_t line, const char * format, ...)
References IsEventLogging(), LogMagickEventList(), MagickFalse, and module.
Referenced by AcquireImage(), AcquireImageColormap(), AcquireMagickResource(), AcquireMemory(), AcquireNextImage(), AcquireResampleFilter(), AcquireResizeFilter(), AcquireUniqueFileResource(), AcquireVirtualCacheView(), AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), AddNoiseImageChannel(), AddPathToXMLTree(), AffineTransformImage(), AllocateString(), AnimateImages(), AnnotateImage(), AppendImageFormat(), AppendImages(), AppendImageToList(), Ascii85Flush(), AttachBlob(), AutoThresholdImage(), Base64Decode(), Base64Encode(), BilevelImageChannel(), BlackThresholdImageChannel(), BlobToFile(), BlobToImage(), BlueShiftImage(), BlurImageChannel(), BorderImage(), BrightnessContrastImageChannel(), CannyEdgeImage(), CatchImageException(), ChannelThresholdImage(), CharcoalImage(), ChopImage(), ClampImageChannel(), ClassifyImageColors(), ClipImagePath(), ClipPixelCacheNexus(), CloneCacheView(), CloneImage(), CloneImageArtifacts(), CloneImageOptions(), CloneImageProfiles(), CloneImageProperties(), CloneImages(), CloneMemory(), ClonePixelCache(), ClonePixelCacheMethods(), ClonePixelCacheRepository(), CloneSplayTree(), CloseBlob(), ClutImageChannel(), CoalesceImages(), ColorDecisionListImage(), ColorFloodfillImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), CompareImageChannels(), CompareImageLayers(), ComplexImages(), CompositeImageChannel(), CompositeLayers(), CompressImageColormap(), ConnectedComponentsImage(), ConsolidateCMYKImages(), ConstituteImage(), ContrastImage(), ContrastStretchImageChannel(), CopyImagePixels(), CropImage(), CropImageToTiles(), CycleColormapImage(), DecipherImage(), DeleteImageArtifact(), DeleteImageList(), DeleteImageOption(), DeleteImageProfile(), DeleteImageProperty(), DeleteImageRegistry(), DeleteImages(), DeleteNodeByValueFromSplayTree(), DeleteNodeFromSplayTree(), DeskewImage(), DespeckleImage(), DestroyBlob(), DestroyCacheView(), DestroyDrawInfo(), DestroyImage(), DestroyImageArtifacts(), DestroyImageAttributes(), DestroyImageInfo(), DestroyImageList(), DestroyImageOptions(), DestroyImagePixelCache(), DestroyImagePixels(), DestroyImageProperties(), DestroyImages(), DestroyLocaleOptions(), DestroyMontageInfo(), DestroyPixelCache(), DestroyPixelStream(), DestroyQuantizeInfo(), DestroyRandomInfo(), DestroyResampleFilter(), DestroySignatureInfo(), DestroyStreamInfo(), DestroyTokenInfo(), DestroyXMLTree(), DestroyXMLTreeRoot(), DetachBlob(), DisassociateBlob(), DisassociateImageStream(), DispatchImage(), DisplayImages(), DisposeImages(), DistortImage(), DistortResizeImage(), DrawAffineImage(), DrawClippingMask(), DrawCompositeMask(), DrawDashPolygon(), DrawGradientImage(), DrawPatternPath(), DrawPolygonPrimitive(), DrawPrimitive(), DrawStrokePolygon(), DuplicateBlob(), DuplicateImages(), EdgeImage(), EmbossImage(), EncipherImage(), EnhanceImage(), EOFBlob(), EqualizeImageChannel(), ErrorBlob(), EvaluateImageChannel(), EvaluateImages(), ExcerptImage(), ExpandFilenames(), ExportImagePixels(), ExportQuantumPixels(), ExtentImage(), FileToBlob(), FileToImage(), FileToStringInfo(), FilterImageChannel(), FinalizeSignature(), FlipImage(), FloodfillPaintImage(), FlopImage(), FormatStringList(), FrameImage(), FunctionImageChannel(), FuzzyColorCompare(), FuzzyOpacityCompare(), FxImageChannel(), GammaImage(), GammaImageChannel(), GaussianBlurImageChannel(), GetAffineMatrix(), GetAuthenticIndexesFromStream(), GetAuthenticPixelsFromStream(), GetAuthenticPixelsStream(), GetBlobError(), GetBlobProperties(), GetBlobSize(), GetBlobStreamHandler(), GetCacheViewChannels(), GetCacheViewColorspace(), GetCacheViewException(), GetCacheViewExtent(), GetCacheViewStorageClass(), GetCoderInfoList(), GetCoderList(), GetColorInfoList(), GetColorList(), GetColorTuple(), GetConfigureBlob(), GetConfigureInfoList(), GetConfigureList(), GetConfigureOption(), GetConfigureOptions(), GetConfigurePaths(), GetConfigureValue(), GetDelegateCommand(), GetDelegateCommands(), GetDelegateInfoList(), GetDelegateList(), GetDelegateMode(), GetDelegateThreadSupport(), GetDrawInfo(), GetEdgeBoundingBox(), GetImageAlphaChannel(), GetImageArtifact(), GetImageAttribute(), GetImageBoundingBox(), GetImageChannelDepth(), GetImageChannelDistortion(), GetImageChannelDistortions(), GetImageChannelEntropy(), GetImageChannelExtrema(), GetImageChannelFeatures(), GetImageChannelKurtosis(), GetImageChannelMean(), GetImageChannelMoments(), GetImageChannelRange(), GetImageChannels(), GetImageChannelStatistics(), GetImageClipMask(), GetImageColorspaceType(), GetImageDecoder(), GetImageDynamicThreshold(), GetImageEncoder(), GetImageException(), GetImageExtent(), GetImageFromList(), GetImageGeometry(), GetImageInfo(), GetImageList(), GetImageListIndex(), GetImageListLength(), GetImageListSize(), GetImageMagick(), GetImageMask(), GetImageOption(), GetImageProfile(), GetImageProperty(), GetImageQuantizeError(), GetImageReferenceCount(), GetImageRegistry(), GetImageTotalInkDensity(), GetImageType(), GetImageVirtualPixelMethod(), GetLocaleInfoList(), GetLocaleList(), GetLocaleOptions(), GetLocaleValue(), GetLocationStatistics(), GetLogInfoList(), GetLogList(), GetMagicInfoList(), GetMagickAdjoin(), GetMagickBlobSupport(), GetMagickDescription(), GetMagickEndianSupport(), GetMagickGeometry(), GetMagickInfoList(), GetMagickList(), GetMagickMimeType(), GetMagickPrecision(), GetMagickPropertyLetter(), GetMagickRawSupport(), GetMagickSeekableStream(), GetMagickThreadSupport(), GetMagicList(), GetMagicName(), GetMimeDescription(), GetMimeInfoList(), GetMimeList(), GetMimeType(), GetMontageInfo(), GetMotionBlurKernel(), GetMultilineTypeMetrics(), GetNextImage(), GetNextImageArtifact(), GetNextImageInList(), GetNextImageOption(), GetNextImageProfile(), GetNextImageProperty(), GetNextImageRegistry(), GetNextKeyInSplayTree(), GetNextValueInSplayTree(), GetNextXMLTreeTag(), GetNumberOfNodesInSplayTree(), GetNumberScenes(), GetOptimalKernelWidth1D(), GetOptimalKernelWidth2D(), GetPageGeometry(), GetPathComponent(), GetPixelCacheChannels(), GetPixelCacheColorspace(), GetPixelCacheStorageClass(), GetPixelCacheTileSize(), GetPolicyInfoList(), GetPolicyList(), GetPolicyValue(), GetPreviousImage(), GetQuantizeInfo(), GetQuantumType(), GetRootValueFromSplayTree(), GetSignatureBlocksize(), GetSignatureDigest(), GetSignatureDigestsize(), GetThresholdMapFile(), GetTypeInfoList(), GetTypeList(), GetTypeMetrics(), GetValueFromSplayTree(), GetVirtualIndexesFromStream(), GetVirtualPixelsStream(), GetVirtualPixelStream(), GetXMLTreeAttribute(), GetXMLTreeAttributes(), GetXMLTreeChild(), GetXMLTreeContent(), GetXMLTreeOrdered(), GetXMLTreePath(), GetXMLTreeProcessingInstructions(), GetXMLTreeSibling(), GetXMLTreeTag(), GradientImage(), GrayscaleImage(), HaldClutImageChannel(), HoughLineImage(), HuffmanDecodeImage(), HuffmanEncodeImage(), IdentifyImage(), IdentifyImageGray(), IdentifyImageMonochrome(), IdentifyImageType(), IdentifyPaletteImage(), IdentityAffine(), ImageListToArray(), ImagesToBlob(), ImageToBlob(), ImageToFile(), ImplodeImage(), ImportImagePixels(), ImportQuantumPixels(), InitializeSignature(), InjectImageBlob(), InsertImageInList(), InterpolativeResizeImage(), InterpretDelegateProperties(), InterpretImageAttributes(), InterpretImageProperties(), InverseFourierTransformImage(), InvokeDelegate(), InvokeDynamicImageFilter(), IsBlobExempt(), IsBlobSeekable(), IsBlobTemporary(), IsHighDynamicRangeImage(), IsHistogramImage(), IsImageObject(), IsImageSimilar(), IsOpaqueImage(), IsPaletteImage(), IsRightsAuthorized(), IsSubimage(), IsTaintImage(), KuwaharaImageChannel(), LevelColorsImageChannel(), LevelImageChannel(), LevelizeImageChannel(), LiberateMemory(), LiberateSemaphoreInfo(), LiquidRescaleImage(), ListFiles(), ListThresholdMapFile(), LoadCoderCache(), LoadColorCache(), LoadConfigureCache(), LoadDelegateCache(), LoadLocaleCache(), LoadMagicCache(), LoadMimeCache(), LoadPolicyCache(), LoadTypeCache(), LocalContrastImage(), LogPathInfo(), LogPolygonInfo(), LogPrimitiveInfo(), LZWEncodeImage(), MagickIncarnate(), MagickMonitor(), MagnifyImage(), MapImage(), MapImages(), MaskPixelCacheNexus(), MatteFloodfillImage(), MeanShiftImage(), MergeImageLayers(), MinifyImage(), ModifyImage(), ModulateImage(), MontageImageList(), MorphImages(), MotionBlurImageChannel(), NegateImageChannel(), NewMagickImage(), OilPaintImage(), OpaqueImage(), OpaquePaintImageChannel(), OpenBlob(), OpenPixelCache(), OptimizeImageTransparency(), OptimizeLayerFrames(), OrderedPosterizeImageChannel(), PackbitsEncodeImage(), ParseImageGeometry(), ParseMetaGeometry(), ParseSizeGeometry(), PasskeyDecipherImage(), PasskeyEncipherImage(), PerceptibleImageChannel(), PersistPixelCache(), PingBlob(), PingImage(), PingImages(), PlasmaImage(), PolaroidImage(), PolynomialImageChannel(), PopImageList(), PosterizeImageChannel(), PostscriptGeometry(), PreviewImage(), ProfileImage(), PruneTagFromXMLTree(), PushImageList(), QuantizationError(), QuantizeImage(), QuantizeImages(), QueryMagickColorCompliance(), RaiseImage(), RandomChannelThresholdImage(), RandomThresholdImageChannel(), ReacquireMemory(), ReadImage(), ReadImages(), ReadPixelCacheIndexes(), ReadPixelCachePixels(), ReadStream(), ReferenceBlob(), ReferenceImage(), RegisterMagickInfo(), RegisterMagickSignalHandler(), RegistryComponentTerminus(), RelinquishMagickResource(), RelinquishUniqueFileResource(), RemapImage(), RemapImages(), RemoteDisplayCommand(), RemoveDuplicateLayers(), RemoveFirstImageFromList(), RemoveImageArtifact(), RemoveImageFromList(), RemoveImageOption(), RemoveImageProfile(), RemoveImageProperty(), RemoveImageRegistry(), RemoveLastImageFromList(), RemoveNodeByValueFromSplayTree(), RemoveNodeFromSplayTree(), RemoveZeroDelayLayers(), RenderMVGContent(), RenderPostscript(), ReplaceImageInList(), ReplaceImageInListReturnLast(), ResampleImage(), ResetImageArtifactIterator(), ResetImageOptionIterator(), ResetImageOptions(), ResetImagePage(), ResetImagePixels(), ResetImageProfileIterator(), ResetImagePropertyIterator(), ResetImageRegistryIterator(), ResetSplayTree(), ResetSplayTreeIterator(), ResizeImage(), ReverseImageList(), RGBTransformImage(), RollImage(), RotateImage(), RotationalBlurImageChannel(), SampleImage(), ScaleImage(), SeekBlob(), SegmentImage(), SelectiveBlurImageChannel(), SeparateImage(), SeparateImageChannel(), SeparateImages(), SepiaToneImage(), SetBlobExempt(), SetBlobExtent(), SetCacheAlphaChannel(), SetCacheThreshold(), SetCacheViewStorageClass(), SetCacheViewVirtualPixelMethod(), SetClientName(), SetClientPath(), SetGeometry(), SetGeometryInfo(), SetImage(), SetImageAlphaChannel(), SetImageArtifact(), SetImageAttribute(), SetImageBackgroundColor(), SetImageChannelDepth(), SetImageClipMask(), SetImageColor(), SetImageColorspace(), SetImageGray(), SetImageInfo(), SetImageInfoBlob(), SetImageInfoFile(), SetImageList(), SetImageMask(), SetImageMonochrome(), SetImageOpacity(), SetImageOption(), SetImageProfileInternal(), SetImageProperty(), SetImageRegistry(), SetImageStorageClass(), SetImageType(), SetImageVirtualPixelMethod(), SetMagickInfo(), SetMagickPrecision(), SetPixelCacheExtent(), SetPixelCacheMethods(), SetPixelCacheVirtualMethod(), SetQuantumDepth(), SetQuantumEndian(), SetQuantumFormat(), SetQuantumImageType(), SetQuantumPad(), SetResampleFilterInterpolateMethod(), SetResampleFilterVirtualPixelMethod(), SetXMLTreeAttribute(), SetXMLTreeContent(), ShadeImage(), ShadowImage(), SharpenImageChannel(), ShaveImage(), ShearImage(), ShearRotateImage(), ShiftImageList(), ShredFile(), SigmoidalContrastImageChannel(), SignatureImage(), SimilarityMetricImage(), SizeBlob(), SmushImages(), SolarizeImageChannel(), SortColormapByIntensity(), SparseColorImage(), SpliceImage(), SpliceImageIntoList(), SpliceImageList(), SpreadImage(), StatisticImageChannel(), SteganoImage(), StereoAnaglyphImage(), StreamImage(), StreamImagePixels(), Strip(), StripImage(), SwirlImage(), SyncAuthenticPixelsStream(), SyncBlob(), SyncImage(), SyncImageSettings(), SyncImagesSettings(), TellBlob(), TemporaryFilename(), TextureImage(), ThresholdImage(), ThresholdImageChannel(), ThrowMagickExceptionList(), ThumbnailImage(), TintImage(), TransformColorspace(), TransformImage(), TransformImageColorspace(), TransformImages(), TransformRGBImage(), TranslateText(), TransparentImage(), TransparentPaintImage(), TransparentPaintImageChroma(), TransposeImage(), TransverseImage(), TrimImage(), UnsharpMaskImageChannel(), UnshiftImageList(), ValidateColormapIndex(), VignetteImage(), WaveImage(), WaveletDenoiseImage(), WhiteThresholdImageChannel(), WriteImage(), WriteImages(), WritePixelCacheIndexes(), WritePixelCachePixels(), WriteStream(), XImportImage(), XMLTreeInfoToXML(), XShearImage(), YShearImage(), ZLIBEncodeImage(), and ZoomImage().
LogMagickEventList()
MagickExport MagickBooleanType LogMagickEventList (const LogEventType type, const char * module, const char * function, const size_t line, const char * format, va_list operands)
References AcquireExceptionInfo(), ActivateSemaphoreInfo(), _LogInfo::append, CommandOptionToMnemonic(), ConsoleHandler, ContinueTimer(), DebugHandler, DestroyExceptionInfo(), _LogInfo::event_mask, _LogInfo::event_semaphore, EventHandler, _LogInfo::file, FileHandler, fopen_utf8(), FormatLocaleFile(), _LogInfo::generation, GetLogInfo(), _LogInfo::handler_mask, IsPathAccessible(), _LogInfo::limit, LockSemaphoreInfo(), MagickFalse, MagickLogEventOptions, MagickTrue, MaxTextExtent, _LogInfo::method, MethodHandler, module, RelinquishMagickMemory(), StderrHandler, StdoutHandler, _LogInfo::timer, TranslateEvent(), TranslateFilename(), and UnlockSemaphoreInfo().
Referenced by LogMagickEvent().
ParseLogHandlers() [1/2]
static LogHandlerType ParseLogHandlers (const char * handlers) static
References LocaleNCompare(), LogHandlers, _HandlerInfo::name, NoHandler, and UndefinedHandler.
ParseLogHandlers() [2/2]
static LogHandlerType ParseLogHandlers (static MagickBooleanType LoadLogCache(LinkedListInfo const char *) static
Referenced by LoadLogCache().
SetLogEventMask()
MagickExport LogEventType SetLogEventMask (const char * events)
References AcquireExceptionInfo(), CheckEventLogging(), DestroyExceptionInfo(), _LogInfo::event_mask, GetLogInfo(), GetValueFromLinkedList(), LockSemaphoreInfo(), log_cache, log_semaphore, MagickLogEventOptions, MagickTrue, ParseCommandOption(), UndefinedEvents, and UnlockSemaphoreInfo().
Referenced by MagickCoreGenesis().
SetLogFormat()
MagickExport void SetLogFormat (const char * format)
References AcquireExceptionInfo(), ConstantString(), DestroyExceptionInfo(), DestroyString(), _LogInfo::format, GetLogInfo(), LockSemaphoreInfo(), log_semaphore, and UnlockSemaphoreInfo().
SetLogMethod()
MagickExport void SetLogMethod (MagickLogMethod method)
References AcquireExceptionInfo(), DestroyExceptionInfo(), GetLogInfo(), GetValueFromLinkedList(), _LogInfo::handler_mask, LockSemaphoreInfo(), log_cache, log_semaphore, _LogInfo::method, MethodHandler, and UnlockSemaphoreInfo().
SetLogName()
MagickExport const char * SetLogName (const char * name)
References CopyMagickString(), log_name, and MaxTextExtent.
TranslateEvent()
static char * TranslateEvent (const LogEventType magick_unusedtype, const char * module, const char * function, const size_t line, const char * domain, const char * event) static
References AcquireExceptionInfo(), AcquireString(), CopyMagickString(), DestroyExceptionInfo(), DirectorySeparator, _LogInfo::format, FormatLocaleString(), FormatMagickTime(), _LogInfo::generation, _LogInfo::generations, GetClientName(), GetElapsedTime(), GetLogInfo(), GetLogName(), GetMagickThreadSignature(), GetMagickTime(), GetUserTime(), LocaleCompare(), magick_unreferenced, MagickLibVersionText, MaxTextExtent, module, ResizeQuantumMemory(), and _LogInfo::timer.
Referenced by LogMagickEventList().
TranslateFilename()
static char * TranslateFilename (const LogInfo * log_info) static
References AcquireString(), CopyMagickString(), _LogInfo::filename, FormatLocaleString(), _LogInfo::generation, _LogInfo::generations, GetClientName(), GetLogName(), MagickLibVersionText, MaxTextExtent, and ResizeQuantumMemory().
Referenced by LogMagickEventList().
Variable Documentation
event_logging
MagickBooleanType event_logging = MagickFalse static
Referenced by CheckEventLogging(), IsEventLogging(), and LogComponentTerminus().
log_cache
LinkedListInfo* log_cache = (LinkedListInfo *) NULL static
Referenced by CheckEventLogging(), GetLogInfo(), GetLogInfoList(), GetLogList(), IsLogCacheInstantiated(), LogComponentTerminus(), SetLogEventMask(), and SetLogMethod().
log_name
char log_name[MaxTextExtent] = "Magick" static
Referenced by GetLogName(), and SetLogName().
log_semaphore
SemaphoreInfo* log_semaphore = (SemaphoreInfo *) NULL static
Referenced by CloseMagickLog(), GetLogInfo(), GetLogInfoList(), GetLogList(), IsLogCacheInstantiated(), LogComponentGenesis(), LogComponentTerminus(), SetLogEventMask(), SetLogFormat(), and SetLogMethod().
LogHandlers
const HandlerInfo LogHandlers[32] static
Referenced by ListLogInfo(), and ParseLogHandlers().
LogMap
const LogMapInfo LogMap[] static
Initial value:
=
  {
    { NoEvents, ConsoleHandler, "Magick-%g.log",
      "%t %r %u %v %d %c[%p]: %m/%f/%l/%d\\n  %e" }
  }