MagickCore: log.h File Reference
log.h File Reference
#include <stdarg.h>
#include "magick/exception.h"
Macros
#define GetMagickModule() __FILE__,__func__,(unsigned long) __LINE__
#define MagickLogFilename "log.xml"
Typedefs
typedef struct _LogInfo LogInfo
typedef void(* MagickLogMethod) (const LogEventType, const char *)
Enumerations
enum LogEventType {
UndefinedEvents , NoEvents = 0x00000 , TraceEvent = 0x00001 , AnnotateEvent = 0x00002 ,
BlobEvent = 0x00004 , CacheEvent = 0x00008 , CoderEvent = 0x00010 , ConfigureEvent = 0x00020 ,
DeprecateEvent = 0x00040 , DrawEvent = 0x00080 , ExceptionEvent = 0x00100 , ImageEvent = 0x00200 ,
LocaleEvent = 0x00400 , ModuleEvent = 0x00800 , PolicyEvent = 0x01000 , ResourceEvent = 0x02000 ,
TransformEvent = 0x04000 , UserEvent = 0x09000 , WandEvent = 0x10000 , X11Event = 0x20000 ,
AccelerateEvent = 0x40000 , AllEvents = 0x7fffffff
}
Functions
MagickExport char ** GetLogList (const char *, size_t *, ExceptionInfo *)
MagickExport const char * GetLogName (void)
MagickExport const char * SetLogName (const char *)
MagickExport const LogInfo ** GetLogInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport LogEventType SetLogEventMask (const char *)
MagickExport MagickBooleanType IsEventLogging (void) magick_attribute((__pure__))
MagickExport MagickBooleanType ListLogInfo (FILE *, ExceptionInfo *)
MagickExport MagickBooleanType LogComponentGenesis (void)
MagickExport MagickBooleanType LogMagickEvent (const LogEventType, const char *, const char *, const size_t, const char *,...) magick_attribute((__format__(__printf__
MagickExport MagickBooleanType LogMagickEventList (const LogEventType, const char *, const char *, const size_t, const char *, va_list) magick_attribute((__format__(__printf__
MagickExport MagickBooleanType MagickExport void CloseMagickLog (void)
MagickExport MagickBooleanType MagickExport void LogComponentTerminus (void)
MagickExport MagickBooleanType MagickExport void SetLogFormat (const char *)
MagickExport MagickBooleanType MagickExport void SetLogMethod (MagickLogMethod)
Macro Definition Documentation
GetMagickModule
#define GetMagickModule () __FILE__,__func__,(unsigned long) __LINE__
MagickLogFilename
#define MagickLogFilename "log.xml"
Typedef Documentation
LogInfo
typedef struct _LogInfo LogInfo
MagickLogMethod
typedef void(* MagickLogMethod) (const LogEventType, const char *)
Enumeration Type Documentation
LogEventType
enum LogEventType
Enumerator
UndefinedEvents
NoEvents
TraceEvent
AnnotateEvent
BlobEvent
CacheEvent
CoderEvent
ConfigureEvent
DeprecateEvent
DrawEvent
ExceptionEvent
ImageEvent
LocaleEvent
ModuleEvent
PolicyEvent
ResourceEvent
TransformEvent
UserEvent
WandEvent
X11Event
AccelerateEvent
AllEvents
Function Documentation
CloseMagickLog()
MagickExport MagickBooleanType MagickExport void CloseMagickLog (void)
GetLogInfoList()
MagickExport const LogInfo ** GetLogInfoList (const char * pattern, size_t * number_preferences, ExceptionInfo * exception)
References AcquireQuantumMemory(), GetLogInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), log_cache, log_semaphore, LogInfoCompare(), LogMagickEvent(), MagickFalse, _LogInfo::name, ResetLinkedListIterator(), _LogInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListLogInfo().
GetLogList()
MagickExport char ** GetLogList (const char * pattern, size_t * number_preferences, ExceptionInfo * exception)
References AcquireQuantumMemory(), ConstantString(), GetLogInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), log_cache, log_semaphore, LogCompare(), LogMagickEvent(), MagickFalse, _LogInfo::name, ResetLinkedListIterator(), _LogInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
GetLogName()
MagickExport const char * GetLogName (void)
IsEventLogging()
MagickExport MagickBooleanType IsEventLogging (void)
ListLogInfo()
MagickExport MagickBooleanType ListLogInfo (FILE * , ExceptionInfo *)
LogComponentGenesis()
MagickExport MagickBooleanType LogComponentGenesis (void)
LogComponentTerminus()
MagickExport MagickBooleanType MagickExport void LogComponentTerminus (void)
LogMagickEvent()
MagickExport MagickBooleanType LogMagickEvent (const LogEventType, const char * , const char * , const size_t, const char * , ...)
LogMagickEventList()
MagickExport MagickBooleanType LogMagickEventList (const LogEventType, const char * , const char * , const size_t, const char * , va_list)
SetLogEventMask()
MagickExport LogEventType SetLogEventMask (const char * events)
References AcquireExceptionInfo(), CheckEventLogging(), DestroyExceptionInfo(), _LogInfo::event_mask, GetLogInfo(), GetValueFromLinkedList(), LockSemaphoreInfo(), log_cache, log_semaphore, MagickLogEventOptions, MagickTrue, ParseCommandOption(), UndefinedEvents, and UnlockSemaphoreInfo().
Referenced by MagickCoreGenesis().
SetLogFormat()
MagickExport MagickBooleanType MagickExport void SetLogFormat (const char *)
SetLogMethod()
MagickExport MagickBooleanType MagickExport void SetLogMethod (MagickLogMethod method)
References AcquireExceptionInfo(), DestroyExceptionInfo(), GetLogInfo(), GetValueFromLinkedList(), _LogInfo::handler_mask, LockSemaphoreInfo(), log_cache, log_semaphore, _LogInfo::method, MethodHandler, and UnlockSemaphoreInfo().
SetLogName()
MagickExport const char * SetLogName (const char * name)
References CopyMagickString(), log_name, and MaxTextExtent.