MagickCore: mac.h File Reference
mac.h File Reference
#include <locale.h>
#include <Errors.h>
#include <Files.h>
#include <errno.h>
#include <stat.h>
Data Structures
struct _DIR
struct dirent
Macros
#define S_IREAD 00400
#define S_IWRITE 00200
Typedefs
typedef struct _DIR DIR
Functions
MagickExport Image * ReadPICTImage (const ImageInfo *, ExceptionInfo *)
MagickExport int Exit (int)
MagickExport int MACSystemCommand (const char *)
MagickExport MagickBooleanType MACIsMagickConflict (const char *)
MagickExport void MACErrorHandler (const ExceptionType, const char *, const char *)
MagickExport void MACWarningHandler (const ExceptionType, const char *, const char *)
MagickExport void ProcessPendingEvents (const char *)
MagickExport void SetApplicationType (const char *, const char *, OSType)
MagickExport DIR * opendir (const char *)
MagickExport long telldir (DIR *)
MagickExport struct dirent * readdir (DIR *)
MagickExport void seekdir (DIR *, long)
MagickExport void closedir (DIR *)
Macro Definition Documentation
S_IREAD
#define S_IREAD 00400
S_IWRITE
#define S_IWRITE 00200
Typedef Documentation
DIR
typedef struct _DIR DIR
Function Documentation
closedir()
MagickExport void closedir (DIR *)
Referenced by ListFiles().
Exit()
MagickExport int Exit (int)
MACErrorHandler()
MagickExport void MACErrorHandler (const ExceptionType, const char * , const char *)
MACIsMagickConflict()
MagickExport MagickBooleanType MACIsMagickConflict (const char *)
Referenced by IsMagickConflict().
MACSystemCommand()
MagickExport int MACSystemCommand (const char *)
MACWarningHandler()
MagickExport void MACWarningHandler (const ExceptionType, const char * , const char *)
opendir()
MagickExport DIR * opendir (const char *)
Referenced by ListFiles().
ProcessPendingEvents()
MagickExport void ProcessPendingEvents (const char *)
Referenced by MagickMonitor().
readdir()
MagickExport struct dirent * readdir (DIR *)
Referenced by MagickReadDirectory().
ReadPICTImage()
MagickExport Image * ReadPICTImage (const ImageInfo * , ExceptionInfo *)
seekdir()
MagickExport void seekdir (DIR * , long)
SetApplicationType()
MagickExport void SetApplicationType (const char * , const char * , OSType)
Referenced by OpenBlob().
telldir()
MagickExport long telldir (DIR *)