MagickCore: magic.c File Reference
magic.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/client.h"
#include "magick/configure.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/hashmap.h"
#include "magick/magic.h"
#include "magick/memory_.h"
#include "magick/semaphore.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/xml-tree.h"
#include "magick/xml-tree-private.h"
Data Structures
struct _MagicMapInfo
Macros
#define MagicFilename "magic.xml"
#define MagicPattern(magic) (const unsigned char *) (magic), sizeof(magic)-1
Typedefs
typedef struct _MagicMapInfo MagicMapInfo
Functions
static MagickBooleanType IsMagicCacheInstantiated (ExceptionInfo *)
static MagickBooleanType LoadMagicCache (LinkedListInfo *, const char *, const char *, const size_t, ExceptionInfo *)
static int CompareMagickInfoSize (const void *a, const void *b)
static LinkedListInfo * AcquireMagicCache (const char *filename, ExceptionInfo *exception)
MagickExport const MagicInfo * GetMagicInfo (const unsigned char *magic, const size_t length, ExceptionInfo *exception)
static int MagicInfoCompare (const void *x, const void *y)
MagickExport const MagicInfo ** GetMagicInfoList (const char *pattern, size_t *number_aliases, ExceptionInfo *exception)
static int MagicCompare (const void *x, const void *y)
MagickExport char ** GetMagicList (const char *pattern, size_t *number_aliases, ExceptionInfo *exception)
MagickExport const char * GetMagicName (const MagicInfo *magic_info)
MagickExport MagickBooleanType ListMagicInfo (FILE *file, ExceptionInfo *exception)
MagickExport MagickBooleanType MagicComponentGenesis (void)
static void * DestroyMagicElement (void *magic_info)
MagickExport void MagicComponentTerminus (void)
Variables
static const MagicMapInfo MagicMap []
static LinkedListInfo * magic_cache = (LinkedListInfo *) NULL
static SemaphoreInfo * magic_semaphore = (SemaphoreInfo *) NULL
Macro Definition Documentation
MagicFilename
#define MagicFilename "magic.xml"
MagicPattern
#define MagicPattern (magic) (const unsigned char *) (magic), sizeof(magic)-1
Typedef Documentation
MagicMapInfo
typedef struct _MagicMapInfo MagicMapInfo
Function Documentation
AcquireMagicCache()
static LinkedListInfo * AcquireMagicCache (const char * filename, ExceptionInfo * exception) static
References AcquireMagickMemory(), CompareMagickInfoSize(), CopyMagickString(), DestroyConfigureOptions(), _MagicInfo::exempt, GetConfigureOptions(), GetMagickModule, GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), InsertValueInSortedLinkedList(), _MagicMapInfo::length, _MagicInfo::length, LoadMagicCache(), _MagicMapInfo::magic, _MagicInfo::magic, MagickCoreSignature, MagickFalse, MagickTrue, MagicMap, MaxTextExtent, _MagicMapInfo::name, _MagicInfo::name, NewLinkedList(), _MagicMapInfo::offset, _MagicInfo::offset, _MagicInfo::path, ResourceLimitError, ResourceLimitFatalError, _MagicInfo::signature, _MagicInfo::target, ThrowFatalException, and ThrowMagickException().
Referenced by IsMagicCacheInstantiated().
CompareMagickInfoSize()
static int CompareMagickInfoSize (const void * a, const void * b) static
References _MagicInfo::length, and _MagicInfo::offset.
Referenced by AcquireMagicCache().
DestroyMagicElement()
static void * DestroyMagicElement (void * magic_info) static
References DestroyString(), _MagicInfo::exempt, _MagicInfo::magic, MagickFalse, _MagicInfo::name, _MagicInfo::path, RelinquishMagickMemory(), and _MagicInfo::target.
Referenced by MagicComponentTerminus().
GetMagicInfo()
MagickExport const MagicInfo * GetMagicInfo (const unsigned char * magic, const size_t length, ExceptionInfo * exception)
References GetNextValueInLinkedList(), InsertValueInLinkedList(), IsMagicCacheInstantiated(), _MagicInfo::length, LockSemaphoreInfo(), _MagicInfo::magic, magic_cache, magic_semaphore, MagickFalse, _MagicInfo::offset, RemoveElementByValueFromLinkedList(), ResetLinkedListIterator(), and UnlockSemaphoreInfo().
Referenced by GetMagicInfoList(), GetMagicList(), and SetImageInfo().
GetMagicInfoList()
MagickExport const MagicInfo ** GetMagicInfoList (const char * pattern, size_t * number_aliases, ExceptionInfo * exception)
References AcquireQuantumMemory(), GetMagicInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), magic_cache, magic_semaphore, MagicInfoCompare(), MagickFalse, _MagicInfo::name, ResetLinkedListIterator(), _MagicInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListMagicInfo().
GetMagicList()
MagickExport char ** GetMagicList (const char * pattern, size_t * number_aliases, ExceptionInfo * exception)
References AcquireQuantumMemory(), ConstantString(), GetMagicInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), magic_cache, magic_semaphore, MagicCompare(), MagickFalse, _MagicInfo::name, ResetLinkedListIterator(), _MagicInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
GetMagicName()
MagickExport const char * GetMagicName (const MagicInfo * magic_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagicInfo::name, _MagicInfo::signature, and TraceEvent.
Referenced by SetImageInfo().
IsMagicCacheInstantiated()
static MagickBooleanType IsMagicCacheInstantiated (ExceptionInfo * exception) static
References AcquireMagicCache(), ActivateSemaphoreInfo(), LockSemaphoreInfo(), magic_cache, magic_semaphore, MagicFilename, MagickFalse, MagickTrue, and UnlockSemaphoreInfo().
Referenced by GetMagicInfo().
ListMagicInfo()
MagickExport MagickBooleanType ListMagicInfo (FILE * file, ExceptionInfo * exception)
References FormatLocaleFile(), GetMagicInfoList(), LocaleCompare(), MagickFalse, MagickTrue, _MagicInfo::offset, _MagicInfo::path, RelinquishMagickMemory(), and _MagicInfo::target.
LoadMagicCache()
static MagickBooleanType LoadMagicCache (LinkedListInfo * cache, const char * xml, const char * filename, const size_t depth, ExceptionInfo * exception) static
References AcquireMagickMemory(), AcquireString(), AppendValueToLinkedList(), ConcatenateMagickString(), ConfigureError, ConfigureEvent, ConstantString(), CopyMagickString(), DirectorySeparator, _MagicInfo::exempt, FileToXML(), GetMagickModule, GetNextToken(), GetPathComponent(), HeadPath, IsMagickTrue(), _MagicInfo::length, LoadMagicCache(), LocaleCompare(), LocaleNCompare(), LogMagickEvent(), _MagicInfo::magic, MagickCoreSignature, MagickFalse, MagickMaxRecursionDepth, MagickTrue, MaxTextExtent, _MagicInfo::name, _MagicInfo::offset, _MagicInfo::path, RelinquishMagickMemory(), ResourceLimitError, ResourceLimitFatalError, _MagicInfo::signature, _MagicInfo::stealth, StringToLong(), _MagicInfo::target, ThrowFatalException, and ThrowMagickException().
Referenced by AcquireMagicCache(), and LoadMagicCache().
MagicCompare()
static int MagicCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetMagicList().
MagicComponentGenesis()
MagickExport MagickBooleanType MagicComponentGenesis (void)
References AllocateSemaphoreInfo(), magic_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
MagicComponentTerminus()
MagickExport void MagicComponentTerminus (void)
References ActivateSemaphoreInfo(), DestroyLinkedList(), DestroyMagicElement(), DestroySemaphoreInfo(), LockSemaphoreInfo(), magic_cache, magic_semaphore, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
MagicInfoCompare()
static int MagicInfoCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetMagicInfoList().
Variable Documentation
magic_cache
LinkedListInfo* magic_cache = (LinkedListInfo *) NULL static
Referenced by GetMagicInfo(), GetMagicInfoList(), GetMagicList(), IsMagicCacheInstantiated(), and MagicComponentTerminus().
magic_semaphore
SemaphoreInfo* magic_semaphore = (SemaphoreInfo *) NULL static
Referenced by GetMagicInfo(), GetMagicInfoList(), GetMagicList(), IsMagicCacheInstantiated(), MagicComponentGenesis(), and MagicComponentTerminus().
MagicMap
const MagicMapInfo MagicMap[] static
Referenced by AcquireMagicCache().