MagickCore: magick.h File Reference
magick.h File Reference
#include <stdarg.h>
#include "magick/semaphore.h"
Data Structures
struct _MagickInfo
Macros
#define magick_module module
Typedefs
typedef Image * DecodeImageHandler(const ImageInfo *, ExceptionInfo *)
typedef MagickBooleanType EncodeImageHandler(const ImageInfo *, Image *)
typedef MagickBooleanType IsImageFormatHandler(const unsigned char *, const size_t)
typedef struct _MagickInfo MagickInfo
Enumerations
enum MagickFormatType { UndefinedFormatType , ImplicitFormatType , ExplicitFormatType }
enum MagickThreadSupport { NoThreadSupport = 0x0000 , DecoderThreadSupport = 0x0001 , EncoderThreadSupport = 0x0002 }
Functions
MagickExport char ** GetMagickList (const char *, size_t *, ExceptionInfo *)
MagickExport const char * GetMagickDescription (const MagickInfo *)
MagickExport const char * GetMagickMimeType (const MagickInfo *)
MagickExport DecodeImageHandler * GetImageDecoder (const MagickInfo *) magick_attribute((__pure__))
MagickExport EncodeImageHandler * GetImageEncoder (const MagickInfo *) magick_attribute((__pure__))
MagickExport int GetMagickPrecision (void)
MagickExport int SetMagickPrecision (const int)
MagickExport MagickBooleanType GetImageMagick (const unsigned char *, const size_t, char *)
MagickExport MagickBooleanType GetMagickAdjoin (const MagickInfo *) magick_attribute((__pure__))
MagickExport MagickBooleanType GetMagickBlobSupport (const MagickInfo *) magick_attribute((__pure__))
MagickExport MagickBooleanType GetMagickEndianSupport (const MagickInfo *) magick_attribute((__pure__))
MagickExport MagickBooleanType GetMagickRawSupport (const MagickInfo *) magick_attribute((__pure__))
MagickExport MagickBooleanType GetMagickSeekableStream (const MagickInfo *) magick_attribute((__pure__))
MagickExport MagickBooleanType IsMagickCoreInstantiated (void) magick_attribute((__pure__))
MagickExport MagickBooleanType MagickComponentGenesis (void)
MagickExport MagickBooleanType UnregisterMagickInfo (const char *)
const MagickExport MagickInfo * GetMagickInfo (const char *, ExceptionInfo *)
const MagickExport MagickInfo ** GetMagickInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport MagickInfo * RegisterMagickInfo (MagickInfo *)
MagickExport MagickInfo * SetMagickInfo (const char *)
MagickExport MagickStatusType GetMagickThreadSupport (const MagickInfo *)
MagickExport void MagickComponentTerminus (void)
MagickExport void MagickCoreGenesis (const char *, const MagickBooleanType)
MagickExport void MagickCoreTerminus (void)
Macro Definition Documentation
magick_module
#define magick_module module
Typedef Documentation
DecodeImageHandler
typedef Image * DecodeImageHandler(const ImageInfo *, ExceptionInfo *)
EncodeImageHandler
typedef MagickBooleanType EncodeImageHandler(const ImageInfo *, Image *)
IsImageFormatHandler
typedef MagickBooleanType IsImageFormatHandler(const unsigned char *, const size_t)
MagickInfo
typedef struct _MagickInfo MagickInfo
Enumeration Type Documentation
MagickFormatType
enum MagickFormatType
Enumerator
UndefinedFormatType
ImplicitFormatType
ExplicitFormatType
MagickThreadSupport
enum MagickThreadSupport
Enumerator
NoThreadSupport
DecoderThreadSupport
EncoderThreadSupport
Function Documentation
GetImageDecoder()
MagickExport DecodeImageHandler * GetImageDecoder (const MagickInfo * magick_info)
References _MagickInfo::decoder, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagickInfo::signature, and TraceEvent.
Referenced by ReadImage().
GetImageEncoder()
MagickExport EncodeImageHandler * GetImageEncoder (const MagickInfo * magick_info)
References _MagickInfo::encoder, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagickInfo::signature, and TraceEvent.
Referenced by WriteImage().
GetImageMagick()
MagickExport MagickBooleanType GetImageMagick (const unsigned char * , const size_t, char *)
GetMagickAdjoin()
MagickExport MagickBooleanType GetMagickAdjoin (const MagickInfo *)
GetMagickBlobSupport()
MagickExport MagickBooleanType GetMagickBlobSupport (const MagickInfo *)
GetMagickDescription()
MagickExport const char * GetMagickDescription (const MagickInfo *)
GetMagickEndianSupport()
MagickExport MagickBooleanType GetMagickEndianSupport (const MagickInfo *)
GetMagickInfo()
const MagickExport MagickInfo * GetMagickInfo (const char * , ExceptionInfo *)
GetMagickInfoList()
const MagickExport MagickInfo ** GetMagickInfoList (const char * pattern, size_t * number_formats, ExceptionInfo * exception)
References AcquireQuantumMemory(), GetMagickInfo(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), magick_list, magick_semaphore, MagickFalse, MagickInfoCompare(), _MagickInfo::name, ResetSplayTreeIterator(), _MagickInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListMagickInfo().
GetMagickList()
MagickExport char ** GetMagickList (const char * pattern, size_t * number_formats, ExceptionInfo * exception)
References AcquireQuantumMemory(), ConstantString(), GetMagickInfo(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), magick_list, magick_semaphore, MagickCompare(), MagickFalse, _MagickInfo::name, ResetSplayTreeIterator(), _MagickInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
GetMagickMimeType()
MagickExport const char * GetMagickMimeType (const MagickInfo * magick_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagickInfo::mime_type, _MagickInfo::signature, and TraceEvent.
Referenced by IdentifyImage().
GetMagickPrecision()
MagickExport int GetMagickPrecision (void)
GetMagickRawSupport()
MagickExport MagickBooleanType GetMagickRawSupport (const MagickInfo *)
GetMagickSeekableStream()
MagickExport MagickBooleanType GetMagickSeekableStream (const MagickInfo *)
GetMagickThreadSupport()
MagickExport MagickStatusType GetMagickThreadSupport (const MagickInfo * magick_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagickInfo::signature, _MagickInfo::thread_support, and TraceEvent.
Referenced by ReadImage(), and WriteImage().
IsMagickCoreInstantiated()
MagickExport MagickBooleanType IsMagickCoreInstantiated (void)
MagickComponentGenesis()
MagickExport MagickBooleanType MagickComponentGenesis (void)
MagickComponentTerminus()
MagickExport void MagickComponentTerminus (void)
MagickCoreGenesis()
MagickExport void MagickCoreGenesis (const char * , const MagickBooleanType)
MagickCoreTerminus()
MagickExport void MagickCoreTerminus (void)
References AnnotateComponentTerminus(), AsynchronousResourceComponentTerminus(), CacheComponentTerminus(), CoderComponentTerminus(), ColorComponentTerminus(), ConfigureComponentTerminus(), DelegateComponentTerminus(), ExceptionComponentTerminus(), InitializeMagickMutex(), instantiate_magickcore, LocaleComponentTerminus(), LockMagickMutex(), LogComponentTerminus(), MagicComponentTerminus(), MagickComponentTerminus(), MagickFalse, MimeComponentTerminus(), ModuleComponentTerminus(), MonitorComponentTerminus(), PolicyComponentTerminus(), RandomComponentTerminus(), RegistryComponentTerminus(), ResourceComponentTerminus(), SemaphoreComponentTerminus(), TypeComponentTerminus(), UnlockMagickMutex(), and UnregisterStaticModules().
Referenced by DefaultFatalErrorHandler(), and DestroyMagick().
RegisterMagickInfo()
MagickExport MagickInfo * RegisterMagickInfo (MagickInfo *)
SetMagickInfo()
MagickExport MagickInfo * SetMagickInfo (const char * name)
References AcquireMagickMemory(), _MagickInfo::adjoin, _MagickInfo::blob_support, ConstantString(), DecoderThreadSupport, EncoderThreadSupport, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickTrue, _MagickInfo::name, ResourceLimitFatalError, _MagickInfo::signature, _MagickInfo::thread_support, ThrowFatalException, and TraceEvent.
Referenced by IsMagickTreeInstantiated().
SetMagickPrecision()
MagickExport int SetMagickPrecision (const int precision)
References DestroyString(), GetEnvironmentValue(), GetMagickModule, GetPolicyValue(), LogMagickEvent(), MagickPrecision, StringToInteger(), and TraceEvent.
Referenced by GetMagickPrecision().
UnregisterMagickInfo()
MagickExport MagickBooleanType UnregisterMagickInfo (const char * name)
References DeleteNodeByValueFromSplayTree(), GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), LocaleCompare(), LockSemaphoreInfo(), magick_list, magick_semaphore, MagickFalse, _MagickInfo::name, ResetSplayTreeIterator(), and UnlockSemaphoreInfo().