MagickCore: magick.c File Reference
magick.c File Reference
#include "magick/studio.h"
#include "magick/annotate.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/cache.h"
#include "magick/coder.h"
#include "magick/client.h"
#include "magick/configure.h"
#include "magick/constitute.h"
#include "magick/delegate.h"
#include "magick/draw.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/locale_.h"
#include "magick/log.h"
#include "magick/magic.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/mime.h"
#include "magick/module.h"
#include "magick/monitor-private.h"
#include "magick/mutex.h"
#include "magick/nt-base-private.h"
#include "magick/nt-feature.h"
#include "magick/opencl-private.h"
#include "magick/random_.h"
#include "magick/registry.h"
#include "magick/resource_.h"
#include "magick/policy.h"
#include "magick/semaphore.h"
#include "magick/semaphore-private.h"
#include "magick/signature-private.h"
#include "magick/splay-tree.h"
#include "magick/static.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/thread_.h"
#include "magick/thread-private.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/xwindow-private.h"
Macros
#define MAGICKCORE_RETSIGTYPE void
#define SIG_DFL ((SignalHandler *) 0)
#define SIG_ERR ((SignalHandler *) -1)
#define SIGMAX 64
#define MagickPrecision (4+MAGICKCORE_QUANTUM_DEPTH/8)
Typedefs
typedef MAGICKCORE_RETSIGTYPE SignalHandler(int)
Functions
static MagickBooleanType IsMagickTreeInstantiated (ExceptionInfo *)
MagickExport DecodeImageHandler * GetImageDecoder (const MagickInfo *magick_info)
MagickExport EncodeImageHandler * GetImageEncoder (const MagickInfo *magick_info)
MagickExport MagickBooleanType GetImageMagick (const unsigned char *magick, const size_t length, char *format)
MagickExport MagickBooleanType GetMagickAdjoin (const MagickInfo *magick_info)
MagickExport MagickBooleanType GetMagickBlobSupport (const MagickInfo *magick_info)
MagickExport const char * GetMagickDescription (const MagickInfo *magick_info)
MagickExport MagickBooleanType GetMagickEndianSupport (const MagickInfo *magick_info)
MagickExport const MagickInfo * GetMagickInfo (const char *name, ExceptionInfo *exception)
static int MagickInfoCompare (const void *x, const void *y)
MagickExport const MagickInfo ** GetMagickInfoList (const char *pattern, size_t *number_formats, ExceptionInfo *exception)
static int MagickCompare (const void *x, const void *y)
MagickExport char ** GetMagickList (const char *pattern, size_t *number_formats, ExceptionInfo *exception)
MagickExport const char * GetMagickMimeType (const MagickInfo *magick_info)
MagickExport int GetMagickPrecision (void)
MagickExport MagickBooleanType GetMagickRawSupport (const MagickInfo *magick_info)
MagickExport MagickBooleanType GetMagickSeekableStream (const MagickInfo *magick_info)
MagickExport MagickStatusType GetMagickThreadSupport (const MagickInfo *magick_info)
static void * DestroyMagickNode (void *magick_info)
MagickExport MagickBooleanType IsMagickConflict (const char *magick)
MagickExport MagickBooleanType ListMagickInfo (FILE *file, ExceptionInfo *exception)
MagickExport MagickBooleanType IsMagickCoreInstantiated (void)
MagickExport MagickBooleanType MagickComponentGenesis (void)
MagickExport void MagickComponentTerminus (void)
static SignalHandler * SetMagickSignalHandler (int signal_number, SignalHandler *handler)
static void MagickSignalHandler (int signal_number)
static SignalHandler * RegisterMagickSignalHandler (int signal_number)
MagickExport void MagickCoreGenesis (const char *path, const MagickBooleanType establish_signal_handlers)
MagickExport void MagickCoreTerminus (void)
MagickExport MagickInfo * RegisterMagickInfo (MagickInfo *magick_info)
MagickExport MagickInfo * SetMagickInfo (const char *name)
MagickExport int SetMagickPrecision (const int precision)
MagickExport MagickBooleanType UnregisterMagickInfo (const char *name)
Variables
static SemaphoreInfo * magick_semaphore = (SemaphoreInfo *) NULL
static SignalHandler * signal_handlers [SIGMAX] = { (SignalHandler *) NULL }
static SplayTreeInfo * magick_list = (SplayTreeInfo *) NULL
static volatile MagickBooleanType instantiate_magickcore = MagickFalse
static volatile MagickBooleanType magickcore_signal_in_progress = MagickFalse
static volatile MagickBooleanType magick_list_initialized = MagickFalse
Macro Definition Documentation
MAGICKCORE_RETSIGTYPE
#define MAGICKCORE_RETSIGTYPE void
MagickPrecision
#define MagickPrecision (4+MAGICKCORE_QUANTUM_DEPTH/8)
SIG_DFL
#define SIG_DFL ((SignalHandler *) 0)
SIG_ERR
#define SIG_ERR ((SignalHandler *) -1)
SIGMAX
#define SIGMAX 64
Typedef Documentation
SignalHandler
typedef MAGICKCORE_RETSIGTYPE SignalHandler(int)
Function Documentation
DestroyMagickNode()
static void * DestroyMagickNode (void * magick_info) static
References _MagickInfo::description, DestroySemaphoreInfo(), DestroyString(), _MagickInfo::magick_module, _MagickInfo::mime_type, _MagickInfo::name, _MagickInfo::note, RelinquishMagickMemory(), _MagickInfo::semaphore, and _MagickInfo::version.
Referenced by IsMagickTreeInstantiated().
GetImageDecoder()
MagickExport DecodeImageHandler * GetImageDecoder (const MagickInfo * magick_info)
References _MagickInfo::decoder, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagickInfo::signature, and TraceEvent.
Referenced by ReadImage().
GetImageEncoder()
MagickExport EncodeImageHandler * GetImageEncoder (const MagickInfo * magick_info)
References _MagickInfo::encoder, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagickInfo::signature, and TraceEvent.
Referenced by WriteImage().
GetImageMagick()
MagickExport MagickBooleanType GetImageMagick (const unsigned char * magick, const size_t length, char * format)
References AcquireExceptionInfo(), CopyMagickString(), DestroyExceptionInfo(), GetMagickInfo(), GetMagickModule, GetNextValueInSplayTree(), LockSemaphoreInfo(), LogMagickEvent(), _MagickInfo::magick, magick_list, magick_semaphore, MagickFalse, MagickTrue, MaxTextExtent, _MagickInfo::name, ResetSplayTreeIterator(), TraceEvent, and UnlockSemaphoreInfo().
GetMagickAdjoin()
MagickExport MagickBooleanType GetMagickAdjoin (const MagickInfo * magick_info)
References _MagickInfo::adjoin, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagickInfo::signature, and TraceEvent.
Referenced by ImagesToBlob(), and SetImageInfo().
GetMagickBlobSupport()
MagickExport MagickBooleanType GetMagickBlobSupport (const MagickInfo * magick_info)
References _MagickInfo::blob_support, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagickInfo::signature, and TraceEvent.
Referenced by BlobToImage(), ImagesToBlob(), ImageToBlob(), OpenBlob(), and PingBlob().
GetMagickDescription()
MagickExport const char * GetMagickDescription (const MagickInfo * magick_info)
References _MagickInfo::description, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagickInfo::signature, and TraceEvent.
Referenced by IdentifyImage().
GetMagickEndianSupport()
MagickExport MagickBooleanType GetMagickEndianSupport (const MagickInfo * magick_info)
References _MagickInfo::endian_support, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagickInfo::signature, and TraceEvent.
Referenced by ReadImage(), SetImageInfo(), and WriteImage().
GetMagickInfo()
MagickExport const MagickInfo * GetMagickInfo (const char * name, ExceptionInfo * exception)
References GetRootValueFromSplayTree(), GetValueFromSplayTree(), IsMagickTreeInstantiated(), LocaleCompare(), LockSemaphoreInfo(), magick_list, magick_semaphore, MagickFalse, OpenModule(), OpenModules(), RegisterStaticModule(), RegisterStaticModules(), and UnlockSemaphoreInfo().
Referenced by BlobToImage(), DrawPrimitive(), GetImageMagick(), GetMagickInfoList(), GetMagickList(), IdentifyImage(), ImagesToBlob(), ImageToBlob(), OpenBlob(), PingBlob(), ReadImage(), SetImageInfo(), and WriteImage().
GetMagickInfoList()
MagickExport const MagickInfo ** GetMagickInfoList (const char * pattern, size_t * number_formats, ExceptionInfo * exception)
References AcquireQuantumMemory(), GetMagickInfo(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), magick_list, magick_semaphore, MagickFalse, MagickInfoCompare(), _MagickInfo::name, ResetSplayTreeIterator(), _MagickInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListMagickInfo().
GetMagickList()
MagickExport char ** GetMagickList (const char * pattern, size_t * number_formats, ExceptionInfo * exception)
References AcquireQuantumMemory(), ConstantString(), GetMagickInfo(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), magick_list, magick_semaphore, MagickCompare(), MagickFalse, _MagickInfo::name, ResetSplayTreeIterator(), _MagickInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
GetMagickMimeType()
MagickExport const char * GetMagickMimeType (const MagickInfo * magick_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagickInfo::mime_type, _MagickInfo::signature, and TraceEvent.
Referenced by IdentifyImage().
GetMagickPrecision()
MagickExport int GetMagickPrecision (void)
References GetMagickModule, LogMagickEvent(), SetMagickPrecision(), and TraceEvent.
Referenced by AcquireResizeFilter(), AutoThresholdImage(), ConcatenateColorComponent(), DistortImage(), FormatMagickSize(), FxEvaluateSubexpression(), GetImageChannelDistortion(), GetImageProperty(), GetMagickProperty(), IdentifyImage(), InterpretImageProperties(), ListMagickVersion(), PrintChannelLocations(), PrintChannelMoments(), PrintChannelPerceptualHash(), PrintChannelStatistics(), SetResampleFilter(), and ShowKernelInfo().
GetMagickRawSupport()
MagickExport MagickBooleanType GetMagickRawSupport (const MagickInfo * magick_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagickInfo::raw, _MagickInfo::signature, and TraceEvent.
Referenced by ReadImage(), and WriteImage().
GetMagickSeekableStream()
MagickExport MagickBooleanType GetMagickSeekableStream (const MagickInfo * magick_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagickInfo::seekable_stream, _MagickInfo::signature, and TraceEvent.
Referenced by ReadImage(), and WriteImage().
GetMagickThreadSupport()
MagickExport MagickStatusType GetMagickThreadSupport (const MagickInfo * magick_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagickInfo::signature, _MagickInfo::thread_support, and TraceEvent.
Referenced by ReadImage(), and WriteImage().
IsMagickConflict()
MagickExport MagickBooleanType IsMagickConflict (const char * magick)
References MACIsMagickConflict(), MagickFalse, NTIsMagickConflict(), and VMSIsMagickConflict().
IsMagickCoreInstantiated()
MagickExport MagickBooleanType IsMagickCoreInstantiated (void)
References instantiate_magickcore.
Referenced by IsMagickInstantiated().
IsMagickTreeInstantiated()
static MagickBooleanType IsMagickTreeInstantiated (ExceptionInfo * exception) static
References ActivateSemaphoreInfo(), AddValueToSplayTree(), CompareSplayTreeString(), DestroyMagickNode(), GetModuleInfo(), LockSemaphoreInfo(), magick_list, magick_list_initialized, magick_semaphore, MagickFalse, MagickTrue, _MagickInfo::name, NewSplayTree(), ResourceLimitFatalError, SetMagickInfo(), _MagickInfo::stealth, ThrowFatalException, and UnlockSemaphoreInfo().
Referenced by GetMagickInfo().
ListMagickInfo()
MagickExport MagickBooleanType ListMagickInfo (FILE * file, ExceptionInfo * exception)
References _MagickInfo::blob_support, ClearMagickException(), ConcatenateMagickString(), CopyMagickString(), DestroyString(), FormatLocaleFile(), GetMagickInfoList(), magick_module, MagickFalse, MagickTrue, MaxTextExtent, _MagickInfo::name, RelinquishMagickMemory(), and StringToList().
MagickCompare()
static int MagickCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetMagickList().
MagickComponentGenesis()
MagickExport MagickBooleanType MagickComponentGenesis (void)
References AllocateSemaphoreInfo(), magick_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
MagickComponentTerminus()
MagickExport void MagickComponentTerminus (void)
References ActivateSemaphoreInfo(), DestroySemaphoreInfo(), DestroySplayTree(), LockSemaphoreInfo(), magick_list, magick_list_initialized, magick_semaphore, MagickFalse, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
MagickCoreGenesis()
MagickExport void MagickCoreGenesis (const char * path, const MagickBooleanType establish_signal_handlers)
References AnnotateComponentGenesis(), CacheComponentGenesis(), CoderComponentGenesis(), ColorComponentGenesis(), ConfigureComponentGenesis(), CopyMagickString(), DelegateComponentGenesis(), DestroyString(), DirectorySeparator, ExceptionComponentGenesis(), GetEnvironmentValue(), GetExecutionPath(), GetPathComponent(), HeadPath, InitializeMagickMutex(), instantiate_magickcore, IsPathAccessible(), LocaleComponentGenesis(), LockMagickMutex(), LogComponentGenesis(), MagicComponentGenesis(), MagickComponentGenesis(), MagickFalse, MagickTrue, MaxTextExtent, MimeComponentGenesis(), ModuleComponentGenesis(), MonitorComponentGenesis(), PolicyComponentGenesis(), RandomComponentGenesis(), RegisterMagickSignalHandler(), RegistryComponentGenesis(), ResourceComponentGenesis(), SemaphoreComponentGenesis(), SetClientName(), SetClientPath(), SetLogEventMask(), signal_handlers, TailPath, TypeComponentGenesis(), UnlockMagickMutex(), and XComponentGenesis().
Referenced by InitializeMagick(), and MagickIncarnate().
MagickCoreTerminus()
MagickExport void MagickCoreTerminus (void)
References AnnotateComponentTerminus(), AsynchronousResourceComponentTerminus(), CacheComponentTerminus(), CoderComponentTerminus(), ColorComponentTerminus(), ConfigureComponentTerminus(), DelegateComponentTerminus(), ExceptionComponentTerminus(), InitializeMagickMutex(), instantiate_magickcore, LocaleComponentTerminus(), LockMagickMutex(), LogComponentTerminus(), MagicComponentTerminus(), MagickComponentTerminus(), MagickFalse, MimeComponentTerminus(), ModuleComponentTerminus(), MonitorComponentTerminus(), PolicyComponentTerminus(), RandomComponentTerminus(), RegistryComponentTerminus(), ResourceComponentTerminus(), SemaphoreComponentTerminus(), TypeComponentTerminus(), UnlockMagickMutex(), and UnregisterStaticModules().
Referenced by DefaultFatalErrorHandler(), and DestroyMagick().
MagickInfoCompare()
static int MagickInfoCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetMagickInfoList().
MagickSignalHandler()
static void MagickSignalHandler (int signal_number) static
References AsynchronousResourceComponentTerminus(), magickcore_signal_in_progress, MagickFalse, MagickSignalHandler(), MagickTrue, SetMagickSignalHandler(), and signal_handlers.
Referenced by MagickSignalHandler(), and RegisterMagickSignalHandler().
RegisterMagickInfo()
MagickExport MagickInfo * RegisterMagickInfo (MagickInfo * magick_info)
References AddValueToSplayTree(), AllocateSemaphoreInfo(), DecoderThreadSupport, EncoderThreadSupport, GetMagickModule, LogMagickEvent(), magick_list, MagickCoreSignature, MagickFalse, _MagickInfo::name, ResourceLimitFatalError, _MagickInfo::semaphore, _MagickInfo::signature, _MagickInfo::thread_support, ThrowFatalException, and TraceEvent.
RegisterMagickSignalHandler()
static SignalHandler * RegisterMagickSignalHandler (int signal_number) static
References ConfigureEvent, GetMagickModule, LogMagickEvent(), MagickSignalHandler(), SetMagickSignalHandler(), SIG_DFL, and SIG_ERR.
Referenced by MagickCoreGenesis().
SetMagickInfo()
MagickExport MagickInfo * SetMagickInfo (const char * name)
References AcquireMagickMemory(), _MagickInfo::adjoin, _MagickInfo::blob_support, ConstantString(), DecoderThreadSupport, EncoderThreadSupport, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickTrue, _MagickInfo::name, ResourceLimitFatalError, _MagickInfo::signature, _MagickInfo::thread_support, ThrowFatalException, and TraceEvent.
Referenced by IsMagickTreeInstantiated().
SetMagickPrecision()
MagickExport int SetMagickPrecision (const int precision)
References DestroyString(), GetEnvironmentValue(), GetMagickModule, GetPolicyValue(), LogMagickEvent(), MagickPrecision, StringToInteger(), and TraceEvent.
Referenced by GetMagickPrecision().
SetMagickSignalHandler()
static SignalHandler * SetMagickSignalHandler (int signal_number, SignalHandler * handler) static
References SIG_DFL, and SIG_ERR.
Referenced by MagickSignalHandler(), and RegisterMagickSignalHandler().
UnregisterMagickInfo()
MagickExport MagickBooleanType UnregisterMagickInfo (const char * name)
References DeleteNodeByValueFromSplayTree(), GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), LocaleCompare(), LockSemaphoreInfo(), magick_list, magick_semaphore, MagickFalse, _MagickInfo::name, ResetSplayTreeIterator(), and UnlockSemaphoreInfo().
Variable Documentation
instantiate_magickcore
volatile MagickBooleanType instantiate_magickcore = MagickFalse static
Referenced by IsMagickCoreInstantiated(), MagickCoreGenesis(), and MagickCoreTerminus().
magick_list
SplayTreeInfo* magick_list = (SplayTreeInfo *) NULL static
Referenced by GetImageMagick(), GetMagickInfo(), GetMagickInfoList(), GetMagickList(), IsMagickTreeInstantiated(), MagickComponentTerminus(), RegisterMagickInfo(), and UnregisterMagickInfo().
magick_list_initialized
volatile MagickBooleanType magick_list_initialized = MagickFalse static
Referenced by IsMagickTreeInstantiated(), and MagickComponentTerminus().
magick_semaphore
SemaphoreInfo* magick_semaphore = (SemaphoreInfo *) NULL static
Referenced by GetImageMagick(), GetMagickInfo(), GetMagickInfoList(), GetMagickList(), IsMagickTreeInstantiated(), MagickComponentGenesis(), MagickComponentTerminus(), and UnregisterMagickInfo().
magickcore_signal_in_progress
volatile MagickBooleanType magickcore_signal_in_progress = MagickFalse static
Referenced by MagickSignalHandler().
signal_handlers
SignalHandler* signal_handlers[SIGMAX] = { (SignalHandler *) NULL } static
Referenced by MagickCoreGenesis(), and MagickSignalHandler().