MagickCore: magic.h File Reference
magic.h File Reference
Data Structures
struct _MagicInfo
Typedefs
typedef struct _MagicInfo MagicInfo
Functions
MagickExport char ** GetMagicList (const char *, size_t *, ExceptionInfo *)
MagickExport const char * GetMagicName (const MagicInfo *)
MagickExport MagickBooleanType ListMagicInfo (FILE *, ExceptionInfo *)
MagickExport MagickBooleanType MagicComponentGenesis (void)
MagickExport const MagicInfo * GetMagicInfo (const unsigned char *, const size_t, ExceptionInfo *)
MagickExport const MagicInfo ** GetMagicInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport void MagicComponentTerminus (void)
Typedef Documentation
MagicInfo
typedef struct _MagicInfo MagicInfo
Function Documentation
GetMagicInfo()
MagickExport const MagicInfo * GetMagicInfo (const unsigned char * , const size_t, ExceptionInfo *)
GetMagicInfoList()
MagickExport const MagicInfo ** GetMagicInfoList (const char * pattern, size_t * number_aliases, ExceptionInfo * exception)
References AcquireQuantumMemory(), GetMagicInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), magic_cache, magic_semaphore, MagicInfoCompare(), MagickFalse, _MagicInfo::name, ResetLinkedListIterator(), _MagicInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListMagicInfo().
GetMagicList()
MagickExport char ** GetMagicList (const char * pattern, size_t * number_aliases, ExceptionInfo * exception)
References AcquireQuantumMemory(), ConstantString(), GetMagicInfo(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), magic_cache, magic_semaphore, MagicCompare(), MagickFalse, _MagicInfo::name, ResetLinkedListIterator(), _MagicInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
GetMagicName()
MagickExport const char * GetMagicName (const MagicInfo * magic_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MagicInfo::name, _MagicInfo::signature, and TraceEvent.
Referenced by SetImageInfo().
ListMagicInfo()
MagickExport MagickBooleanType ListMagicInfo (FILE * , ExceptionInfo *)
MagicComponentGenesis()
MagickExport MagickBooleanType MagicComponentGenesis (void)
References AllocateSemaphoreInfo(), magic_semaphore, and MagickTrue.
Referenced by MagickCoreGenesis().
MagicComponentTerminus()
MagickExport void MagicComponentTerminus (void)
References ActivateSemaphoreInfo(), DestroyLinkedList(), DestroyMagicElement(), DestroySemaphoreInfo(), LockSemaphoreInfo(), magic_cache, magic_semaphore, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().