MagickCore: matrix.h File Reference
matrix.h File Reference
Typedefs
typedef struct _MatrixInfo MatrixInfo
Functions
MagickExport double ** AcquireMagickMatrix (const size_t, const size_t)
MagickExport double ** RelinquishMagickMatrix (double **, const size_t)
MagickExport Image * MatrixToImage (const MatrixInfo *, ExceptionInfo *)
MagickExport MagickBooleanType GaussJordanElimination (double **, double **, const size_t, const size_t)
MagickExport MagickBooleanType GetMatrixElement (const MatrixInfo *, const ssize_t, const ssize_t, void *)
MagickExport MagickBooleanType NullMatrix (MatrixInfo *)
MagickExport MagickBooleanType SetMatrixElement (const MatrixInfo *, const ssize_t, const ssize_t, const void *)
MagickExport MatrixInfo * AcquireMatrixInfo (const size_t, const size_t, const size_t, ExceptionInfo *)
MagickExport MatrixInfo * DestroyMatrixInfo (MatrixInfo *)
MagickExport size_t GetMatrixColumns (const MatrixInfo *)
MagickExport size_t GetMatrixRows (const MatrixInfo *)
MagickExport void LeastSquaresAddTerms (double **, double **, const double *, const double *, const size_t, const size_t)
Typedef Documentation
MatrixInfo
typedef struct _MatrixInfo MatrixInfo
Function Documentation
AcquireMagickMatrix()
MagickExport double ** AcquireMagickMatrix (const size_t, const size_t)
AcquireMatrixInfo()
MagickExport MatrixInfo * AcquireMatrixInfo (const size_t, const size_t, const size_t, ExceptionInfo *)
DestroyMatrixInfo()
MagickExport MatrixInfo * DestroyMatrixInfo (MatrixInfo * matrix_info)
References DestroySemaphoreInfo(), DiskCache, DiskResource, _MatrixInfo::elements, _MatrixInfo::file, _MatrixInfo::length, LockSemaphoreInfo(), MagickCoreSignature, MagickFalse, MapCache, _MatrixInfo::mapped, MapResource, MemoryCache, MemoryResource, _MatrixInfo::path, RelinquishMagickMemory(), RelinquishMagickResource(), RelinquishUniqueFileResource(), _MatrixInfo::semaphore, _MatrixInfo::signature, _MatrixInfo::type, UnlockSemaphoreInfo(), and UnmapBlob().
Referenced by AcquireMatrixInfo(), CannyEdgeImage(), ConnectedComponentsImage(), HoughLineImage(), and RadonTransform().
GaussJordanElimination()
MagickExport MagickBooleanType GaussJordanElimination (double ** , double ** , const size_t, const size_t)
GetMatrixColumns()
MagickExport size_t GetMatrixColumns (const MatrixInfo *)
GetMatrixElement()
MagickExport MagickBooleanType GetMatrixElement (const MatrixInfo * , const ssize_t, const ssize_t, void *)
GetMatrixRows()
MagickExport size_t GetMatrixRows (const MatrixInfo * matrix_info)
References MagickCoreSignature, _MatrixInfo::rows, and _MatrixInfo::signature.
Referenced by RadonProjection().
LeastSquaresAddTerms()
MagickExport void LeastSquaresAddTerms (double ** matrix, double ** vectors, const double * terms, const double * results, const size_t, const size_t)
Referenced by GenerateCoefficients().
MatrixToImage()
MagickExport Image * MatrixToImage (const MatrixInfo * matrix_info, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireImage(), _PixelPacket::blue, ClampToQuantum(), _Image::colorspace, _Image::columns, _MatrixInfo::columns, DestroyCacheView(), DestroyImage(), GetMatrixElement(), GRAYColorspace, _PixelPacket::green, MagickCoreSignature, MagickFalse, MagickTrue, QuantumRange, QueueCacheViewAuthenticPixels(), _PixelPacket::red, _Image::rows, _MatrixInfo::rows, _ExceptionInfo::signature, _MatrixInfo::signature, _MatrixInfo::stride, and SyncCacheViewAuthenticPixels().
Referenced by HoughLineImage().
NullMatrix()
MagickExport MagickBooleanType NullMatrix (MatrixInfo *)
RelinquishMagickMatrix()
MagickExport double ** RelinquishMagickMatrix (double ** matrix, const size_t)
References RelinquishMagickMemory().
Referenced by GenerateCoefficients().
SetMatrixElement()
MagickExport MagickBooleanType SetMatrixElement (const MatrixInfo * matrix_info, const ssize_t, const ssize_t, const void * value)
References _MatrixInfo::columns, DiskCache, _MatrixInfo::elements, _MatrixInfo::length, MagickCoreSignature, MagickFalse, MagickTrue, _MatrixInfo::signature, _MatrixInfo::stride, _MatrixInfo::type, and WriteMatrixElements().
Referenced by CannyEdgeImage(), ConnectedComponentsImage(), HoughLineImage(), RadonProjection(), RadonTransform(), and TraceEdges().