MagickCore: matrix.c File Reference
matrix.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/image-private.h"
#include "magick/matrix.h"
#include "magick/memory_.h"
#include "magick/pixel-private.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/thread-private.h"
#include "magick/utility.h"
Data Structures
struct _MatrixInfo
Macros
#define GaussJordanSwap(x, y)
Functions
static MagickOffsetType WriteMatrixElements (const MatrixInfo *magick_restrict matrix_info, const MagickOffsetType offset, const MagickSizeType length, const unsigned char *magick_restrict buffer)
static MagickBooleanType SetMatrixExtent (MatrixInfo *magick_restrict matrix_info, MagickSizeType length)
MagickExport MatrixInfo * AcquireMatrixInfo (const size_t columns, const size_t rows, const size_t stride, ExceptionInfo *exception)
MagickExport double ** AcquireMagickMatrix (const size_t number_rows, const size_t size)
MagickExport MatrixInfo * DestroyMatrixInfo (MatrixInfo *matrix_info)
MagickExport MagickBooleanType GaussJordanElimination (double **matrix, double **vectors, const size_t rank, const size_t number_vectors)
MagickExport size_t GetMatrixColumns (const MatrixInfo *matrix_info)
static ssize_t EdgeX (const ssize_t x, const size_t columns)
static ssize_t EdgeY (const ssize_t y, const size_t rows)
static MagickOffsetType ReadMatrixElements (const MatrixInfo *magick_restrict matrix_info, const MagickOffsetType offset, const MagickSizeType length, unsigned char *magick_restrict buffer)
MagickExport MagickBooleanType GetMatrixElement (const MatrixInfo *matrix_info, const ssize_t x, const ssize_t y, void *value)
MagickExport size_t GetMatrixRows (const MatrixInfo *matrix_info)
MagickExport void LeastSquaresAddTerms (double **matrix, double **vectors, const double *terms, const double *results, const size_t rank, const size_t number_vectors)
MagickExport Image * MatrixToImage (const MatrixInfo *matrix_info, ExceptionInfo *exception)
MagickExport MagickBooleanType NullMatrix (MatrixInfo *matrix_info)
MagickExport double ** RelinquishMagickMatrix (double **matrix, const size_t number_rows)
MagickExport MagickBooleanType SetMatrixElement (const MatrixInfo *matrix_info, const ssize_t x, const ssize_t y, const void *value)
Macro Definition Documentation
GaussJordanSwap
#define GaussJordanSwap (x, y)
Value:
{ \
  if ((x) != (y)) \
    { \
      (x)+=(y); \
      (y)=(x)-(y); \
      (x)=(x)-(y); \
    } \
}
Function Documentation
AcquireMagickMatrix()
MagickExport double ** AcquireMagickMatrix (const size_t number_rows, const size_t size)
References AcquireQuantumMemory(), and RelinquishMagickMemory().
Referenced by GenerateCoefficients().
AcquireMatrixInfo()
MagickExport MatrixInfo * AcquireMatrixInfo (const size_t columns, const size_t rows, const size_t stride, ExceptionInfo * exception)
References AcquireMagickMemory(), AcquireMagickResource(), AcquireUniqueFileResource(), AllocateSemaphoreInfo(), AreaResource, CacheError, _MatrixInfo::columns, DestroyMatrixInfo(), DestroyString(), DiskCache, DiskResource, _MatrixInfo::elements, _MatrixInfo::file, GetEnvironmentValue(), GetMagickModule, IOMode, IsStringTrue(), _MatrixInfo::length, MagickCoreSignature, MagickFalse, MagickTrue, MapBlob(), MapCache, _MatrixInfo::mapped, MapResource, MemoryCache, MemoryResource, _MatrixInfo::path, RelinquishMagickResource(), _MatrixInfo::rows, _MatrixInfo::semaphore, SetMatrixExtent(), _MatrixInfo::signature, _MatrixInfo::stride, _MatrixInfo::synchronize, ThrowMagickException(), and _MatrixInfo::type.
Referenced by CannyEdgeImage(), ConnectedComponentsImage(), HoughLineImage(), and RadonTransform().
DestroyMatrixInfo()
MagickExport MatrixInfo * DestroyMatrixInfo (MatrixInfo * matrix_info)
References DestroySemaphoreInfo(), DiskCache, DiskResource, _MatrixInfo::elements, _MatrixInfo::file, _MatrixInfo::length, LockSemaphoreInfo(), MagickCoreSignature, MagickFalse, MapCache, _MatrixInfo::mapped, MapResource, MemoryCache, MemoryResource, _MatrixInfo::path, RelinquishMagickMemory(), RelinquishMagickResource(), RelinquishUniqueFileResource(), _MatrixInfo::semaphore, _MatrixInfo::signature, _MatrixInfo::type, UnlockSemaphoreInfo(), and UnmapBlob().
Referenced by AcquireMatrixInfo(), CannyEdgeImage(), ConnectedComponentsImage(), HoughLineImage(), and RadonTransform().
EdgeX()
static ssize_t EdgeX (const ssize_t x, const size_t columns) inline static
Referenced by GetMatrixElement().
EdgeY()
static ssize_t EdgeY (const ssize_t y, const size_t rows) inline static
Referenced by GetMatrixElement().
GaussJordanElimination()
MagickExport MagickBooleanType GaussJordanElimination (double ** matrix, double ** vectors, const size_t rank, const size_t number_vectors)
References AcquireQuantumMemory(), GaussJordanSwap, MagickFalse, MagickTrue, PerceptibleReciprocal(), and RelinquishMagickMemory().
Referenced by GenerateCoefficients().
GetMatrixColumns()
MagickExport size_t GetMatrixColumns (const MatrixInfo * matrix_info)
References _MatrixInfo::columns, MagickCoreSignature, and _MatrixInfo::signature.
Referenced by RadonProjection().
GetMatrixElement()
MagickExport MagickBooleanType GetMatrixElement (const MatrixInfo * matrix_info, const ssize_t x, const ssize_t y, void * value)
References _MatrixInfo::columns, DiskCache, EdgeX(), EdgeY(), _MatrixInfo::elements, MagickCoreSignature, MagickFalse, MagickTrue, ReadMatrixElements(), _MatrixInfo::rows, _MatrixInfo::signature, _MatrixInfo::stride, and _MatrixInfo::type.
Referenced by CannyEdgeImage(), ConnectedComponentsImage(), HoughLineImage(), MatrixToImage(), RadonProjection(), and TraceEdges().
GetMatrixRows()
MagickExport size_t GetMatrixRows (const MatrixInfo * matrix_info)
References MagickCoreSignature, _MatrixInfo::rows, and _MatrixInfo::signature.
Referenced by RadonProjection().
LeastSquaresAddTerms()
MagickExport void LeastSquaresAddTerms (double ** matrix, double ** vectors, const double * terms, const double * results, const size_t rank, const size_t number_vectors)
Referenced by GenerateCoefficients().
MatrixToImage()
MagickExport Image * MatrixToImage (const MatrixInfo * matrix_info, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireImage(), _PixelPacket::blue, ClampToQuantum(), _Image::colorspace, _Image::columns, _MatrixInfo::columns, DestroyCacheView(), DestroyImage(), GetMatrixElement(), GRAYColorspace, _PixelPacket::green, MagickCoreSignature, MagickFalse, MagickTrue, QuantumRange, QueueCacheViewAuthenticPixels(), _PixelPacket::red, _Image::rows, _MatrixInfo::rows, _ExceptionInfo::signature, _MatrixInfo::signature, _MatrixInfo::stride, and SyncCacheViewAuthenticPixels().
Referenced by HoughLineImage().
NullMatrix()
MagickExport MagickBooleanType NullMatrix (MatrixInfo * matrix_info)
References DiskCache, _MatrixInfo::elements, _MatrixInfo::file, _MatrixInfo::length, MagickCoreSignature, MagickFalse, MagickTrue, _MatrixInfo::rows, _MatrixInfo::signature, and _MatrixInfo::type.
Referenced by HoughLineImage(), and RadonTransform().
ReadMatrixElements()
static MagickOffsetType ReadMatrixElements (const MatrixInfo *magick_restrict matrix_info, const MagickOffsetType offset, const MagickSizeType length, unsigned char *magick_restrict buffer) inline static
References LockSemaphoreInfo(), MAGICK_SSIZE_MAX, MagickMin, and UnlockSemaphoreInfo().
Referenced by GetMatrixElement().
RelinquishMagickMatrix()
MagickExport double ** RelinquishMagickMatrix (double ** matrix, const size_t number_rows)
References RelinquishMagickMemory().
Referenced by GenerateCoefficients().
SetMatrixElement()
MagickExport MagickBooleanType SetMatrixElement (const MatrixInfo * matrix_info, const ssize_t x, const ssize_t y, const void * value)
References _MatrixInfo::columns, DiskCache, _MatrixInfo::elements, _MatrixInfo::length, MagickCoreSignature, MagickFalse, MagickTrue, _MatrixInfo::signature, _MatrixInfo::stride, _MatrixInfo::type, and WriteMatrixElements().
Referenced by CannyEdgeImage(), ConnectedComponentsImage(), HoughLineImage(), RadonProjection(), RadonTransform(), and TraceEdges().
SetMatrixExtent()
static MagickBooleanType SetMatrixExtent (MatrixInfo *magick_restrict matrix_info, MagickSizeType length) static
References MagickFalse, MagickTrue, and WriteMatrixElements().
Referenced by AcquireMatrixInfo().
WriteMatrixElements()
static MagickOffsetType WriteMatrixElements (const MatrixInfo *magick_restrict matrix_info, const MagickOffsetType offset, const MagickSizeType length, const unsigned char *magick_restrict buffer) inline static
References LockSemaphoreInfo(), MAGICK_SSIZE_MAX, MagickMin, and UnlockSemaphoreInfo().
Referenced by SetMatrixElement(), and SetMatrixExtent().