MagickCore: memory_.h File Reference
memory_.h File Reference
#include <errno.h>
#include <assert.h>
Typedefs
typedef struct _MemoryInfo MemoryInfo
typedef void *(* AcquireMemoryHandler) (size_t) magick_alloc_size(1)
typedef void *(*)(* DestroyMemoryHandler) (void *)
typedef void *(*)(*) *(* ResizeMemoryHandler) (void *, size_t) magick_alloc_size(2)
typedef void *(*)(*) *(*) *(* AcquireAlignedMemoryHandler) (const size_t, const size_t)
typedef void *(*)(*) *(*) *(*)(* RelinquishAlignedMemoryHandler) (void *)
Functions
MagickExport MemoryInfo * AcquireVirtualMemory (const size_t, const size_t) magick_alloc_sizes(1
MagickExport MemoryInfo * RelinquishVirtualMemory (MemoryInfo *)
MagickExport size_t GetMaxMemoryRequest (void)
MagickExport void * AcquireAlignedMemory (const size_t, const size_t) magick_attribute((__malloc__)) magick_alloc_sizes(1
MagickExport void * AcquireMagickMemory (const size_t) magick_attribute((__malloc__)) magick_alloc_size(1)
MagickExport void * AcquireCriticalMemory (const size_t)
MagickExport void * AcquireQuantumMemory (const size_t, const size_t) magick_attribute((__malloc__)) magick_alloc_sizes(1
MagickExport void * CopyMagickMemory (void *magick_restrict, const void *magick_restrict, const size_t) magick_attribute((__nonnull__))
MagickExport void DestroyMagickMemory (void)
MagickExport void GetMagickMemoryMethods (AcquireMemoryHandler *, ResizeMemoryHandler *, DestroyMemoryHandler *)
MagickExport void * GetVirtualMemoryBlob (const MemoryInfo *)
MagickExport void * RelinquishAlignedMemory (void *)
MagickExport void * RelinquishMagickMemory (void *)
MagickExport void * ResetMagickMemory (void *, int, const size_t)
MagickExport void * ResizeMagickMemory (void *, const size_t) magick_attribute((__malloc__)) magick_alloc_size(2)
MagickExport void * ResizeQuantumMemory (void *, const size_t, const size_t) magick_attribute((__malloc__)) magick_alloc_sizes(2
MagickExport void SetMagickAlignedMemoryMethods (AcquireAlignedMemoryHandler, RelinquishAlignedMemoryHandler)
MagickExport void SetMagickMemoryMethods (AcquireMemoryHandler, ResizeMemoryHandler, DestroyMemoryHandler)
static MagickBooleanType HeapOverflowSanityCheck (const size_t count, const size_t quantum)
static MagickBooleanType HeapOverflowSanityCheckGetSize (const size_t count, const size_t quantum, size_t *const extent)
Typedef Documentation
AcquireAlignedMemoryHandler
typedef void *(*)(*) *(*) *(* AcquireAlignedMemoryHandler) (const size_t, const size_t)
AcquireMemoryHandler
typedef void *(* AcquireMemoryHandler) (size_t) magick_alloc_size(1)
DestroyMemoryHandler
typedef void *(*)(* DestroyMemoryHandler) (void *)
MemoryInfo
typedef struct _MemoryInfo MemoryInfo
RelinquishAlignedMemoryHandler
typedef void *(*)(*) *(*) *(*)(* RelinquishAlignedMemoryHandler) (void *)
ResizeMemoryHandler
typedef void *(*)(*) *(* ResizeMemoryHandler) (void *, size_t) magick_alloc_size(2)
Function Documentation
AcquireAlignedMemory()
MagickExport void * AcquireAlignedMemory (const size_t, const size_t)
AcquireCriticalMemory()
MagickExport void * AcquireCriticalMemory (const size_t)
AcquireMagickMemory()
MagickExport void * AcquireMagickMemory (const size_t)
AcquireQuantumMemory()
MagickExport void * AcquireQuantumMemory (const size_t, const size_t)
AcquireVirtualMemory()
MagickExport MemoryInfo * AcquireVirtualMemory (const size_t, const size_t)
CopyMagickMemory()
MagickExport void * CopyMagickMemory (void * magick_restrict, const void * magick_restrict, const size_t)
DestroyMagickMemory()
MagickExport void DestroyMagickMemory (void)
GetMagickMemoryMethods()
MagickExport void GetMagickMemoryMethods (AcquireMemoryHandler * , ResizeMemoryHandler * , DestroyMemoryHandler *)
GetMaxMemoryRequest()
MagickExport size_t GetMaxMemoryRequest (void)
References DestroyString(), GetPolicyValue(), MAGICK_SSIZE_MAX, MagickMax, MagickMin, MagickULLConstant, max_memory_request, MinMemoryRequest, and StringToSizeType().
Referenced by AcquireQuantumMemory(), AcquireVirtualMemory(), and ResizeQuantumMemory().
GetVirtualMemoryBlob()
MagickExport void * GetVirtualMemoryBlob (const MemoryInfo *)
HeapOverflowSanityCheck()
static MagickBooleanType HeapOverflowSanityCheck (const size_t count, const size_t quantum) inline static
References MagickFalse, and MagickTrue.
HeapOverflowSanityCheckGetSize()
static MagickBooleanType HeapOverflowSanityCheckGetSize (const size_t count, const size_t quantum, size_t *const extent) inline static
References _MemoryInfo::length, MagickFalse, and MagickTrue.
Referenced by AcquireAlignedMemory(), AcquireQuantumMemory(), AcquireVirtualMemory(), and ResizeQuantumMemory().
RelinquishAlignedMemory()
MagickExport void * RelinquishAlignedMemory (void *)
RelinquishMagickMemory()
MagickExport void * RelinquishMagickMemory (void *)
RelinquishVirtualMemory()
MagickExport MemoryInfo * RelinquishVirtualMemory (MemoryInfo * memory_info)
References AlignedVirtualMemory, _MemoryInfo::blob, _MemoryInfo::filename, _MemoryInfo::length, MagickCoreSignature, MapVirtualMemory, RelinquishAlignedMemory(), RelinquishMagickMemory(), RelinquishUniqueFileResource(), _MemoryInfo::signature, _MemoryInfo::type, UnalignedVirtualMemory, and UnmapBlob().
Referenced by AcquireVirtualMemory(), DespeckleImage(), DestroyCubeInfo(), DestroyQuantumPixels(), FloodfillPaintImage(), LocalContrastImage(), and WaveletDenoiseImage().
ResetMagickMemory()
MagickExport void * ResetMagickMemory (void * , int , const size_t)
ResizeMagickMemory()
MagickExport void * ResizeMagickMemory (void * , const size_t)
ResizeQuantumMemory()
MagickExport void * ResizeQuantumMemory (void * , const size_t, const size_t)
SetMagickAlignedMemoryMethods()
MagickExport void SetMagickAlignedMemoryMethods (AcquireAlignedMemoryHandler , RelinquishAlignedMemoryHandler)
SetMagickMemoryMethods()
MagickExport void SetMagickMemoryMethods (AcquireMemoryHandler acquire_memory_handler, ResizeMemoryHandler resize_memory_handler, DestroyMemoryHandler destroy_memory_handler)
References _MagickMemoryMethods::acquire_memory_handler, _MagickMemoryMethods::destroy_memory_handler, memory_methods, and _MagickMemoryMethods::resize_memory_handler.