MagickCore: memory.c File Reference
memory.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/image-private.h"
#include "magick/memory_.h"
#include "magick/memory-private.h"
#include "magick/policy.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/utility-private.h"
Data Structures
struct _DataSegmentInfo
struct _MagickMemoryMethods
struct _MemoryInfo
struct _MemoryPool
Macros
#define BlockFooter(block, size) ((size_t *) ((char *) (block)+(size)-2*sizeof(size_t)))
#define BlockHeader(block) ((size_t *) (block)-1)
#define BlockThreshold 1024
#define MaxBlockExponent 16
#define MaxBlocks ((BlockThreshold/(4*sizeof(size_t)))+MaxBlockExponent+1)
#define MaxSegments 1024
#define NextBlock(block) ((char *) (block)+SizeOfBlock(block))
#define NextBlockInList(block) (*(void **) (block))
#define PreviousBlock(block) ((char *) (block)-(*((size_t *) (block)-2)))
#define PreviousBlockBit 0x01
#define PreviousBlockInList(block) (*((void **) (block)+1))
#define SegmentSize (2*1024*1024)
#define SizeMask (~0x01)
#define SizeOfBlock(block) (*BlockHeader(block) & SizeMask)
#define ALIGNMENT_OVERHEAD (MAGICKCORE_MAX_ALIGNMENT_PADDING(CACHE_LINE_SIZE) + MAGICKCORE_SIZEOF_VOID_P)
#define AcquireAlignedMemory_Actual AcquireAlignedMemory_Generic
#define MinMemoryRequest "16MiB"
Typedefs
typedef struct _DataSegmentInfo DataSegmentInfo
typedef struct _MagickMemoryMethods MagickMemoryMethods
typedef struct _MemoryPool MemoryPool
Enumerations
enum VirtualMemoryType { UndefinedVirtualMemory , AlignedVirtualMemory , MapVirtualMemory , UnalignedVirtualMemory }
Functions
static void * reserve_space_for_actual_base_address (void *const p)
static void ** pointer_to_space_for_actual_base_address (void *const p)
static void * actual_base_address (void *const p)
static void * align_to_cache (void *const p)
static void * adjust (void *const p)
static void * AcquireAlignedMemory_Generic (const size_t size)
MagickExport void * AcquireAlignedMemory (const size_t count, const size_t quantum)
MagickExport void * AcquireMagickMemory (const size_t size)
MagickExport void * AcquireCriticalMemory (const size_t size)
MagickExport void * AcquireQuantumMemory (const size_t count, const size_t quantum)
MagickExport MemoryInfo * AcquireVirtualMemory (const size_t count, const size_t quantum)
MagickExport void * CopyMagickMemory (void *magick_restrict destination, const void *magick_restrict source, const size_t size)
MagickExport void DestroyMagickMemory (void)
MagickExport void GetMagickMemoryMethods (AcquireMemoryHandler *acquire_memory_handler, ResizeMemoryHandler *resize_memory_handler, DestroyMemoryHandler *destroy_memory_handler)
MagickExport size_t GetMaxMemoryRequest (void)
MagickExport void * GetVirtualMemoryBlob (const MemoryInfo *memory_info)
MagickExport void * RelinquishAlignedMemory (void *memory)
MagickExport void * RelinquishMagickMemory (void *memory)
MagickExport MemoryInfo * RelinquishVirtualMemory (MemoryInfo *memory_info)
MagickExport void * ResetMagickMemory (void *memory, int c, const size_t size)
MagickPrivate void ResetMaxMemoryRequest (void)
MagickPrivate void ResetVirtualAnonymousMemory (void)
MagickExport void * ResizeMagickMemory (void *memory, const size_t size)
MagickExport void * ResizeQuantumMemory (void *memory, const size_t count, const size_t quantum)
MagickExport void SetMagickAlignedMemoryMethods (AcquireAlignedMemoryHandler acquire_aligned_memory_handler, RelinquishAlignedMemoryHandler relinquish_aligned_memory_handler)
MagickExport void SetMagickMemoryMethods (AcquireMemoryHandler acquire_memory_handler, ResizeMemoryHandler resize_memory_handler, DestroyMemoryHandler destroy_memory_handler)
Variables
static size_t max_memory_request = 0
static size_t virtual_anonymous_memory = 0
static MagickMemoryMethods memory_methods
Macro Definition Documentation
AcquireAlignedMemory_Actual
#define AcquireAlignedMemory_Actual AcquireAlignedMemory_Generic
ALIGNMENT_OVERHEAD
#define ALIGNMENT_OVERHEAD (MAGICKCORE_MAX_ALIGNMENT_PADDING(CACHE_LINE_SIZE) + MAGICKCORE_SIZEOF_VOID_P)
BlockFooter
#define BlockFooter (block, size) ((size_t *) ((char *) (block)+(size)-2*sizeof(size_t)))
BlockHeader
#define BlockHeader (block) ((size_t *) (block)-1)
BlockThreshold
#define BlockThreshold 1024
MaxBlockExponent
#define MaxBlockExponent 16
MaxBlocks
#define MaxBlocks ((BlockThreshold/(4*sizeof(size_t)))+MaxBlockExponent+1)
MaxSegments
#define MaxSegments 1024
MinMemoryRequest
#define MinMemoryRequest "16MiB"
NextBlock
#define NextBlock (block) ((char *) (block)+SizeOfBlock(block))
NextBlockInList
#define NextBlockInList (block) (*(void **) (block))
PreviousBlock
#define PreviousBlock (block) ((char *) (block)-(*((size_t *) (block)-2)))
PreviousBlockBit
#define PreviousBlockBit 0x01
PreviousBlockInList
#define PreviousBlockInList (block) (*((void **) (block)+1))
SegmentSize
#define SegmentSize (2*1024*1024)
SizeMask
#define SizeMask (~0x01)
SizeOfBlock
#define SizeOfBlock (block) (*BlockHeader(block) & SizeMask)
Typedef Documentation
DataSegmentInfo
typedef struct _DataSegmentInfo DataSegmentInfo
MagickMemoryMethods
typedef struct _MagickMemoryMethods MagickMemoryMethods
MemoryPool
typedef struct _MemoryPool MemoryPool
Enumeration Type Documentation
VirtualMemoryType
enum VirtualMemoryType
Enumerator
UndefinedVirtualMemory
AlignedVirtualMemory
MapVirtualMemory
UnalignedVirtualMemory
Function Documentation
AcquireAlignedMemory()
MagickExport void * AcquireAlignedMemory (const size_t count, const size_t quantum)
References _MagickMemoryMethods::acquire_aligned_memory_handler, AcquireAlignedMemory_Actual, CACHE_LINE_SIZE, HeapOverflowSanityCheckGetSize(), MagickFalse, and memory_methods.
Referenced by AcquireCacheNexusPixels(), AcquireContributionThreadSet(), AcquireKernelBuiltIn(), AcquirePixelCache(), AcquirePixelCacheNexus(), AcquirePixelList(), AcquireRandomInfoThreadSet(), AcquireResampleFilterThreadSet(), AcquireStreamInfo(), AcquireStreamPixels(), AcquireVirtualCacheView(), AcquireVirtualMemory(), AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), CloneCacheView(), CloneKernelInfo(), CloneMagickPixelPacket(), ConvolveImageChannel(), EdgeImage(), EmbossImage(), FilterImageChannel(), GetMotionBlurKernel(), OpenPixelCache(), ParseKernelArray(), SelectiveBlurImageChannel(), SharpenImageChannel(), and WriteStreamImage().
AcquireAlignedMemory_Generic()
static void * AcquireAlignedMemory_Generic (const size_t size) inline static
References AcquireMagickMemory(), adjust(), ALIGNMENT_OVERHEAD, and pointer_to_space_for_actual_base_address().
AcquireCriticalMemory()
MagickExport void * AcquireCriticalMemory (const size_t size)
References AcquireMagickMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by AcquireDrawInfo(), AcquireFxInfo(), AcquireImage(), AcquireRandomInfo(), CheckPrimitiveExtent(), CloneDrawInfo(), CloneImage(), InitializeIntervalTree(), OptimalTau(), SetImageRegistry(), and TraceStrokePolygon().
AcquireMagickMemory()
MagickExport void * AcquireMagickMemory (const size_t size)
References _MagickMemoryMethods::acquire_memory_handler, ActivateSemaphoreInfo(), _MemoryPool::allocation, _MemoryPool::blocks, LockSemaphoreInfo(), MagickFalse, MaxBlocks, MaxSegments, memory_methods, _DataSegmentInfo::next, _DataSegmentInfo::previous, _MemoryPool::segment_pool, SegmentSize, SizeMask, and UnlockSemaphoreInfo().
Referenced by AcquireAlignedMemory_Generic(), AcquireCoderCache(), AcquireColorCache(), AcquireCriticalMemory(), AcquireDistributeCacheInfo(), AcquireExceptionInfo(), AcquireImageInfo(), AcquireKernelBuiltIn(), AcquireMagicCache(), AcquireMatrixInfo(), AcquirePixelList(), AcquirePolicyCache(), AcquirePolygonThreadSet(), AcquireQuantizeInfo(), AcquireQuantumInfo(), AcquireQuantumMemory(), AcquireResizeFilter(), AcquireSignatureInfo(), AcquireStreamInfo(), AcquireStringInfoContainer(), AcquireTimerInfo(), AcquireTokenInfo(), AddChildToXMLTree(), AddConfigureKey(), AddValueToSplayTree(), AppendValueToLinkedList(), Ascii85Initialize(), CloneBlobInfo(), CloneExceptionInfo(), CloneImageView(), CloneKernelInfo(), CloneMontageInfo(), CloneQuantizeInfo(), ConvertPathToPolygon(), CreateMagickThreadKey(), GetCubeInfo(), GetImageAttribute(), GetNodeInfo(), GetThresholdMapFile(), InsertValueInLinkedList(), InsertValueInSortedLinkedList(), ListFiles(), LoadCoderCache(), LoadColorCache(), LoadLocaleCache(), LoadLogCache(), LoadMagicCache(), LoadMimeCache(), LoadPolicyCache(), LoadTypeCache(), MagickCreateThreadKey(), NewHashmap(), NewImageView(), NewImageViewRegion(), NewLinkedList(), NewSplayTree(), NewXMLTreeTag(), ParseInternalDoctype(), ParseKernelArray(), ParseProcessingInstructions(), PutEntryInHashmap(), ReacquireMemory(), RenderMVGContent(), ResizeMagickMemory(), SetFxSymbolValue(), SetMagickInfo(), and ThrowException().
AcquireQuantumMemory()
MagickExport void * AcquireQuantumMemory (const size_t count, const size_t quantum)
References AcquireMagickMemory(), GetMaxMemoryRequest(), HeapOverflowSanityCheckGetSize(), and MagickFalse.
Referenced by AcquireContributionThreadSet(), AcquireFxInfo(), AcquireFxThreadSet(), AcquireHistogramThreadSet(), AcquireImageColormap(), AcquireMagickMatrix(), AcquirePixelCacheNexus(), AcquirePixelListThreadSet(), AcquirePixelThreadSet(), AcquirePolicyString(), AcquirePolygonThreadSet(), AcquireQuantumPixels(), AcquireResampleFilter(), AcquireSignatureInfo(), AcquireString(), AcquireStringInfo(), AcquireUniqueSymbolicLink(), AcquireVirtualMemory(), AllocateString(), AnnotateImage(), AutoThresholdImage(), BalanceSplayTree(), Base64Decode(), Base64Encode(), BlobToStringInfo(), CheckImageColors(), Classify(), ClassifyImageColors(), CloneDrawInfo(), CloneImage(), ClonePixelCacheOnDisk(), ClutImageChannel(), ColorDecisionListImage(), ColorFloodfillImage(), CompareImageLayers(), ConfigureFileToStringInfo(), ConnectedComponentsImage(), ConstantString(), ContrastStretchImageChannel(), ConvertLatin1ToUTF8(), ConvertPathToPolygon(), ConvertPrimitiveToPath(), ConvertUTF16ToUTF8(), CopyDelegateFile(), CreateMagickThreadKey(), DeleteImages(), DeskewImage(), DistortImage(), DrawDashPolygon(), EqualizeImageChannel(), EscapeParenthesis(), EscapeString(), ExpandFilenames(), ExportImagePixels(), FileToBlob(), FileToImage(), FileToXML(), GammaImageChannel(), GaussJordanElimination(), GenerateCoefficients(), Get8BIMProperty(), GetCoderInfoList(), GetCoderList(), GetColorInfoList(), GetColorList(), GetCommandOptions(), GetConfigureInfoList(), GetConfigureList(), GetDelegateInfoList(), GetDelegateList(), GetExecutionPath(), GetEXIFProperty(), GetImageChannelDepth(), GetImageChannelDistortion(), GetImageChannelDistortions(), GetImageChannelFeatures(), GetImageChannelMoments(), GetImageChannelPerceptualHash(), GetImageChannelStatistics(), GetImageDynamicThreshold(), GetImageHistogram(), GetImageViewException(), GetIPTCProperty(), GetLocaleInfoList(), GetLocaleList(), GetLocationStatistics(), GetLogInfoList(), GetLogList(), GetMagicInfoList(), GetMagickInfoList(), GetMagickList(), GetMagicList(), GetMimeInfoList(), GetMimeList(), GetNodeInfo(), GetPathComponents(), GetPolicyInfoList(), GetPolicyList(), GetThresholdMapFile(), GetTypeInfoList(), GetTypeList(), GradientImage(), HuffmanDecodeImage(), HuffmanEncodeImage(), IdentifyImage(), ImageListToArray(), ImagesToBlob(), ImageToBlob(), ImageToFile(), ImportImagePixels(), IncreaseHashmapCapacity(), InitializeIntervalTree(), InjectImageBlob(), IsHistogramImage(), IterateOverSplayTree(), KapurThreshold(), LinearStretchImage(), ListFiles(), LoadConfigureCache(), LoadDelegateCache(), LZWEncodeImage(), MatteFloodfillImage(), MontageImageList(), MorphologyPrimitive(), MotionBlurImageChannel(), NewHashmap(), NewXMLTree(), OptimalTau(), OptimizeLayerFrames(), OTSUThreshold(), PackbitsEncodeImage(), ParseEntities(), ParseInternalDoctype(), ParseProcessingInstructions(), popen_utf8(), ReduceImageColors(), RenderHoughLines(), RenderMVGContent(), RGBTransformImage(), RotationalBlurImageChannel(), SampleImage(), ScaleImage(), ScaleSpace(), SegmentImage(), SetGrayscaleImage(), SetImageChannelDepth(), SetStringInfoLength(), SetXMLTreeAttribute(), SigmoidalContrastImageChannel(), SortColormapByIntensity(), StreamImagePixels(), StringInfoToHexString(), StringInfoToString(), StringToArgv(), StringToArrayOfDoubles(), StringToStrings(), TraceBezier(), TraceStrokePolygon(), TransformRGBImage(), WaveImage(), and WaveletDenoiseImage().
AcquireVirtualMemory()
MagickExport MemoryInfo * AcquireVirtualMemory (const size_t count, const size_t quantum)
References AcquireAlignedMemory(), AcquireQuantumMemory(), AcquireUniqueFileResource(), AlignedVirtualMemory, _MemoryInfo::blob, DestroyString(), _MemoryInfo::filename, GetMaxMemoryRequest(), GetPolicyValue(), HeapOverflowSanityCheckGetSize(), IOMode, _MemoryInfo::length, LocaleCompare(), MagickAssumeAligned, MagickCoreSignature, MagickFalse, MapBlob(), MapVirtualMemory, RelinquishUniqueFileResource(), RelinquishVirtualMemory(), ResourceLimitFatalError, _MemoryInfo::signature, ThrowFatalException, _MemoryInfo::type, UnalignedVirtualMemory, and virtual_anonymous_memory.
Referenced by AcquireQuantumPixels(), DespeckleImage(), FloodfillPaintImage(), GetCubeInfo(), LocalContrastImage(), and WaveletDenoiseImage().
actual_base_address()
static void * actual_base_address (void *const p) inline static
References pointer_to_space_for_actual_base_address().
Referenced by RelinquishAlignedMemory().
adjust()
static void * adjust (void *const p) inline static
References align_to_cache(), and reserve_space_for_actual_base_address().
Referenced by AcquireAlignedMemory_Generic(), and ClutImageChannel().
align_to_cache()
static void * align_to_cache (void *const p) inline static
References CACHE_ALIGNED.
Referenced by adjust().
CopyMagickMemory()
MagickExport void * CopyMagickMemory (void *magick_restrict destination, const void *magick_restrict source, const size_t size)
DestroyMagickMemory()
MagickExport void DestroyMagickMemory (void)
References ActivateSemaphoreInfo(), _DataSegmentInfo::allocation, _MagickMemoryMethods::destroy_memory_handler, DestroySemaphoreInfo(), _DataSegmentInfo::length, LockSemaphoreInfo(), MagickFalse, _DataSegmentInfo::mapped, memory_methods, _MemoryPool::number_segments, _MemoryPool::segments, UnlockSemaphoreInfo(), and UnmapBlob().
GetMagickMemoryMethods()
MagickExport void GetMagickMemoryMethods (AcquireMemoryHandler * acquire_memory_handler, ResizeMemoryHandler * resize_memory_handler, DestroyMemoryHandler * destroy_memory_handler)
References _MagickMemoryMethods::acquire_memory_handler, _MagickMemoryMethods::destroy_memory_handler, memory_methods, and _MagickMemoryMethods::resize_memory_handler.
GetMaxMemoryRequest()
MagickExport size_t GetMaxMemoryRequest (void)
References DestroyString(), GetPolicyValue(), MAGICK_SSIZE_MAX, MagickMax, MagickMin, MagickULLConstant, max_memory_request, MinMemoryRequest, and StringToSizeType().
Referenced by AcquireQuantumMemory(), AcquireVirtualMemory(), and ResizeQuantumMemory().
GetVirtualMemoryBlob()
MagickExport void * GetVirtualMemoryBlob (const MemoryInfo * memory_info)
References _MemoryInfo::blob, MagickCoreSignature, and _MemoryInfo::signature.
Referenced by AcquireQuantumPixels(), DespeckleImage(), DestroyQuantumPixels(), FloodfillPaintImage(), GetCubeInfo(), GetQuantumPixels(), LocalContrastImage(), and WaveletDenoiseImage().
pointer_to_space_for_actual_base_address()
static void ** pointer_to_space_for_actual_base_address (void *const p) inline static
Referenced by AcquireAlignedMemory_Generic(), and actual_base_address().
RelinquishAlignedMemory()
MagickExport void * RelinquishAlignedMemory (void * memory)
References actual_base_address(), memory_methods, _MagickMemoryMethods::relinquish_aligned_memory_handler, and RelinquishMagickMemory().
Referenced by AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), DestroyCacheView(), DestroyContributionThreadSet(), DestroyKernelInfo(), DestroyPixelCache(), DestroyPixelCacheNexus(), DestroyPixelList(), DestroyPixelStream(), DestroyRandomInfoThreadSet(), DestroyResampleFilterThreadSet(), DestroyStreamInfo(), FilterImageChannel(), MotionBlurImageChannel(), RelinquishCacheNexusPixels(), RelinquishPixelCachePixels(), RelinquishStreamPixels(), RelinquishVirtualMemory(), SelectiveBlurImageChannel(), and WriteStreamImage().
RelinquishMagickMemory()
MagickExport void * RelinquishMagickMemory (void * memory)
References BlockFooter, BlockHeader, _MagickMemoryMethods::destroy_memory_handler, LockSemaphoreInfo(), memory_methods, NextBlock, PreviousBlock, PreviousBlockBit, SizeOfBlock, and UnlockSemaphoreInfo().
Referenced by access_utf8(), AcquireCoderCache(), AcquireFxInfo(), AcquireMagickMatrix(), AcquirePolygonThreadSet(), AcquireUniqueSymbolicLink(), AddPathToXMLTree(), AnnotateImage(), AutoThresholdImage(), BalanceSplayTree(), Base64Decode(), CanonicalXMLContent(), CheckPrimitiveExtent(), Classify(), ClearLinkedList(), ClonePixelCacheOnDisk(), ClutImageChannel(), ColorDecisionListImage(), ColorFloodfillImage(), CompareImageLayers(), ConnectedComponentsImage(), ContrastStretchImageChannel(), ConvertPathToPolygon(), CopyDelegateFile(), CreateMagickThreadKey(), DeleteImages(), DeleteMagickThreadKey(), DeleteNodeByValueFromSplayTree(), DeleteNodeFromSplayTree(), DeskewImage(), DestroyAttribute(), DestroyBlob(), DestroyCoderNode(), DestroyColorCube(), DestroyColorElement(), DestroyConfigureElement(), DestroyContributionThreadSet(), DestroyCubeInfo(), DestroyDelegate(), DestroyDistributeCacheInfo(), DestroyDrawInfo(), DestroyEdge(), DestroyExceptionElement(), DestroyExceptionInfo(), DestroyFxInfo(), DestroyFxThreadSet(), DestroyHashmap(), DestroyHistogramThreadSet(), DestroyImage(), DestroyImageInfo(), DestroyImageView(), DestroyKernelInfo(), DestroyLinkedList(), DestroyLocaleNode(), DestroyLogElement(), DestroyMagicElement(), DestroyMagickNode(), DestroyMatrixInfo(), DestroyMimeElement(), DestroyMontageInfo(), DestroyPixelCacheNexus(), DestroyPixelList(), DestroyPixelListThreadSet(), DestroyPixelThreadSet(), DestroyPolicyElement(), DestroyPolygonInfo(), DestroyPolygonThreadSet(), DestroyQuantizeInfo(), DestroyQuantumInfo(), DestroyQuantumPixels(), DestroyRandomInfo(), DestroyRegistryNode(), DestroyResampleFilter(), DestroyResizeFilter(), DestroySignatureInfo(), DestroySplayTree(), DestroyStreamInfo(), DestroyString(), DestroyStringInfo(), DestroyStringList(), DestroyThresholdMap(), DestroyTimerInfo(), DestroyTokenInfo(), DestroyTypeNode(), DestroyXMLTree(), DestroyXMLTreeAttributes(), DestroyXMLTreeRoot(), DistortImage(), DrawDashPolygon(), DrawStrokePolygon(), EqualizeImageChannel(), ExpandFilenames(), ExportImagePixels(), ExternalDelegateCommand(), FileToBlob(), FileToImage(), FileToXML(), fopen_utf8(), FreeNodes(), GammaImageChannel(), GaussJordanElimination(), GenerateCoefficients(), GetConfigureOptions(), GetConfigurePaths(), GetDelegateCommand(), GetExecutionPath(), GetHostname(), GetImageAttribute(), GetImageChannelDepth(), GetImageChannelDistortion(), GetImageChannelDistortions(), GetImageChannelEntropy(), GetImageChannelFeatures(), GetImageChannelMean(), GetImageChannelMoments(), GetImageChannelPerceptualHash(), GetImageChannelStatistics(), GetImageDynamicThreshold(), GetLocaleOptions(), GetMagickHomeURL(), GetMultilineTypeMetrics(), GetMVGMacros(), GetNormalizedCrossCorrelationDistortion(), GetNumberColors(), GetPerceptualHashDistortion(), GetXMLTreePath(), GetXMPProperty(), HuffmanDecodeImage(), HuffmanEncodeImage(), IdentifyImage(), ImagesToBlob(), ImageToBlob(), ImageToFile(), ImportImagePixels(), IncreaseHashmapCapacity(), InitializeIntervalTree(), InjectImageBlob(), InsertValueInSortedLinkedList(), InvokeDelegate(), IsOptionMember(), IterateOverSplayTree(), KapurThreshold(), LinearStretchImage(), ListCoderInfo(), ListColorInfo(), ListConfigureInfo(), ListDelegateInfo(), ListFiles(), ListLocaleInfo(), ListLogInfo(), ListMagicInfo(), ListMagickInfo(), ListMimeInfo(), ListPolicyInfo(), ListTypeInfo(), LoadCoderCache(), LoadColorCache(), LoadConfigureCache(), LoadDelegateCache(), LoadLocaleCache(), LoadLogCache(), LoadMagicCache(), LoadPolicyCache(), LoadTypeCache(), LogMagickEventList(), LZWEncodeImage(), MagickDeleteThreadKey(), MatteFloodfillImage(), MontageImageList(), MorphologyPrimitive(), MotionBlurImageChannel(), open_utf8(), OpenMagickStream(), OptimalTau(), OptimizeLayerFrames(), OTSUThreshold(), PackbitsEncodeImage(), ParseInternalDoctype(), popen_utf8(), PreviewImage(), PutEntryInHashmap(), ReacquireMemory(), ReadInlineImage(), ReduceImageColors(), RelinquishAlignedMemory(), RelinquishMagickMatrix(), RelinquishVirtualMemory(), remove_utf8(), RemoveElementByValueFromLinkedList(), RemoveElementFromLinkedList(), RemoveEntryFromHashmap(), RemoveLastElementFromLinkedList(), RemoveNodeByValueFromSplayTree(), RemoveNodeFromSplayTree(), rename_utf8(), RenderMVGContent(), RenderType(), ResetSplayTree(), ResizeMagickMemory(), ResizeQuantumMemory(), RGBTransformImage(), RotationalBlurImageChannel(), SampleImage(), ScaleImage(), ScaleSpace(), SegmentImage(), SetGrayscaleImage(), SetImageArtifact(), SetImageChannelDepth(), SetImageOption(), SetImageProfileInternal(), SetImageProperty(), SetImageRegistry(), SigmoidalContrastImageChannel(), SortColormapByIntensity(), SparseColorImage(), stat_utf8(), StreamImagePixels(), StringToArgv(), TraceBezier(), TraceStrokePolygon(), TransformImages(), TransformRGBImage(), WaveImage(), and WaveletDenoiseImage().
RelinquishVirtualMemory()
MagickExport MemoryInfo * RelinquishVirtualMemory (MemoryInfo * memory_info)
References AlignedVirtualMemory, _MemoryInfo::blob, _MemoryInfo::filename, _MemoryInfo::length, MagickCoreSignature, MapVirtualMemory, RelinquishAlignedMemory(), RelinquishMagickMemory(), RelinquishUniqueFileResource(), _MemoryInfo::signature, _MemoryInfo::type, UnalignedVirtualMemory, and UnmapBlob().
Referenced by AcquireVirtualMemory(), DespeckleImage(), DestroyCubeInfo(), DestroyQuantumPixels(), FloodfillPaintImage(), LocalContrastImage(), and WaveletDenoiseImage().
reserve_space_for_actual_base_address()
static void * reserve_space_for_actual_base_address (void *const p) inline static
Referenced by adjust().
ResetMagickMemory()
MagickExport void * ResetMagickMemory (void * memory, int c, const size_t size)
Referenced by TransformSignature().
ResetMaxMemoryRequest()
MagickPrivate void ResetMaxMemoryRequest (void)
References max_memory_request.
ResetVirtualAnonymousMemory()
MagickPrivate void ResetVirtualAnonymousMemory (void)
References virtual_anonymous_memory.
ResizeMagickMemory()
MagickExport void * ResizeMagickMemory (void * memory, const size_t size)
References AcquireMagickMemory(), LockSemaphoreInfo(), MagickFalse, memory_methods, RelinquishMagickMemory(), _MagickMemoryMethods::resize_memory_handler, ResourceLimitFatalError, ThrowFatalException, and UnlockSemaphoreInfo().
Referenced by ResizeQuantumMemory().
ResizeQuantumMemory()
MagickExport void * ResizeQuantumMemory (void * memory, const size_t count, const size_t quantum)
References GetMaxMemoryRequest(), HeapOverflowSanityCheckGetSize(), MagickFalse, RelinquishMagickMemory(), and ResizeMagickMemory().
Referenced by AcquireImageColormap(), CanonicalXMLContent(), CheckImageColors(), CheckPrimitiveExtent(), ClassifyImageColors(), CloneString(), ConcatenateString(), ConvertPathToPolygon(), ConvertPrimitiveToPath(), ConvertUTF16ToUTF8(), EncodePredefinedEntities(), ExpandFilenames(), FileToBlob(), FileToXML(), ImagesToBlob(), ImageToBlob(), IsHistogramImage(), ListFiles(), NewXMLTree(), ParseEntities(), ParseInternalDoctype(), ParseProcessingInstructions(), RenderMVGContent(), SetBlobExtent(), SetStringInfoLength(), SetXMLTreeAttribute(), StringToStrings(), SubstituteString(), TranslateEvent(), TranslateFilename(), WriteBlob(), XMLTreeInfoToXML(), and XMLTreeTagToXML().
SetMagickAlignedMemoryMethods()
MagickExport void SetMagickAlignedMemoryMethods (AcquireAlignedMemoryHandler acquire_aligned_memory_handler, RelinquishAlignedMemoryHandler relinquish_aligned_memory_handler)
References _MagickMemoryMethods::acquire_aligned_memory_handler, memory_methods, and _MagickMemoryMethods::relinquish_aligned_memory_handler.
SetMagickMemoryMethods()
MagickExport void SetMagickMemoryMethods (AcquireMemoryHandler acquire_memory_handler, ResizeMemoryHandler resize_memory_handler, DestroyMemoryHandler destroy_memory_handler)
References _MagickMemoryMethods::acquire_memory_handler, _MagickMemoryMethods::destroy_memory_handler, memory_methods, and _MagickMemoryMethods::resize_memory_handler.
Variable Documentation
max_memory_request
size_t max_memory_request = 0 static
Referenced by GetMaxMemoryRequest(), and ResetMaxMemoryRequest().
memory_methods
MagickMemoryMethods memory_methods static
Initial value:
=
  {
    (AcquireMemoryHandler) malloc,
    (ResizeMemoryHandler) realloc,
    (DestroyMemoryHandler) free,
    (AcquireAlignedMemoryHandler) NULL,
    (RelinquishAlignedMemoryHandler) NULL
  }
Referenced by AcquireAlignedMemory(), AcquireMagickMemory(), DestroyMagickMemory(), GetMagickMemoryMethods(), RelinquishAlignedMemory(), RelinquishMagickMemory(), ResizeMagickMemory(), SetMagickAlignedMemoryMethods(), and SetMagickMemoryMethods().
virtual_anonymous_memory
size_t virtual_anonymous_memory = 0 static
Referenced by AcquireVirtualMemory(), and ResetVirtualAnonymousMemory().