MagickCore: mime.h File Reference
mime.h File Reference
Typedefs
typedef struct _MimeInfo MimeInfo
Functions
MagickExport char ** GetMimeList (const char *, size_t *, ExceptionInfo *)
MagickExport char * MagickToMime (const char *)
MagickExport const char * GetMimeDescription (const MimeInfo *)
MagickExport const char * GetMimeType (const MimeInfo *)
MagickExport MagickBooleanType ListMimeInfo (FILE *, ExceptionInfo *)
MagickExport MagickBooleanType MimeComponentGenesis (void)
MagickExport const MimeInfo * GetMimeInfo (const char *, const unsigned char *, const size_t, ExceptionInfo *)
MagickExport const MimeInfo ** GetMimeInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport void MimeComponentTerminus (void)
Typedef Documentation
MimeInfo
typedef struct _MimeInfo MimeInfo
Function Documentation
GetMimeDescription()
MagickExport const char * GetMimeDescription (const MimeInfo *)
GetMimeInfo()
MagickExport const MimeInfo * GetMimeInfo (const char * , const unsigned char * , const size_t, ExceptionInfo *)
GetMimeInfoList()
MagickExport const MimeInfo ** GetMimeInfoList (const char * pattern, size_t * number_aliases, ExceptionInfo * exception)
References AcquireQuantumMemory(), GetMagickModule, GetMimeInfo(), GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, mime_cache, mime_semaphore, MimeInfoCompare(), ResetLinkedListIterator(), _MimeInfo::stealth, TraceEvent, _MimeInfo::type, and UnlockSemaphoreInfo().
Referenced by ListMimeInfo().
GetMimeList()
MagickExport char ** GetMimeList (const char * , size_t * , ExceptionInfo *)
GetMimeType()
MagickExport const char * GetMimeType (const MimeInfo * mime_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MimeInfo::signature, TraceEvent, and _MimeInfo::type.
Referenced by MagickToMime().
ListMimeInfo()
MagickExport MagickBooleanType ListMimeInfo (FILE * , ExceptionInfo *)
MagickToMime()
MagickExport char * MagickToMime (const char * magick)
References AcquireExceptionInfo(), ConstantString(), DestroyExceptionInfo(), FormatLocaleString(), GetMimeInfo(), GetMimeType(), LocaleLower(), and MaxTextExtent.
MimeComponentGenesis()
MagickExport MagickBooleanType MimeComponentGenesis (void)
References AllocateSemaphoreInfo(), MagickTrue, and mime_semaphore.
Referenced by MagickCoreGenesis().
MimeComponentTerminus()
MagickExport void MimeComponentTerminus (void)
References ActivateSemaphoreInfo(), DestroyLinkedList(), DestroyMimeElement(), DestroySemaphoreInfo(), LockSemaphoreInfo(), mime_cache, mime_semaphore, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().