MagickCore: mime.c File Reference
mime.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/client.h"
#include "magick/configure.h"
#include "magick/deprecate.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/hashmap.h"
#include "magick/memory_.h"
#include "magick/mime.h"
#include "magick/mime-private.h"
#include "magick/nt-base-private.h"
#include "magick/option.h"
#include "magick/semaphore.h"
#include "magick/string_.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/xml-tree.h"
#include "magick/xml-tree-private.h"
Data Structures
struct _MimeInfo
Macros
#define MimeFilename "mime.xml"
Functions
static MagickBooleanType IsMimeCacheInstantiated (ExceptionInfo *)
static MagickBooleanType LoadMimeCache (LinkedListInfo *, const char *, const char *, const size_t, ExceptionInfo *)
static LinkedListInfo * AcquireMimeCache (const char *filename, ExceptionInfo *exception)
MagickExport MagickBooleanType LoadMimeLists (const char *name, ExceptionInfo *exception)
MagickExport const MimeInfo * GetMimeInfo (const char *filename, const unsigned char *magic, const size_t length, ExceptionInfo *exception)
static int MimeInfoCompare (const void *x, const void *y)
MagickExport const MimeInfo ** GetMimeInfoList (const char *pattern, size_t *number_aliases, ExceptionInfo *exception)
static int MimeCompare (const void *x, const void *y)
MagickExport char ** GetMimeList (const char *pattern, size_t *number_aliases, ExceptionInfo *exception)
MagickExport const char * GetMimeDescription (const MimeInfo *mime_info)
MagickExport const char * GetMimeType (const MimeInfo *mime_info)
MagickExport MagickBooleanType ListMimeInfo (FILE *file, ExceptionInfo *exception)
MagickExport char * MagickToMime (const char *magick)
MagickExport MagickBooleanType MimeComponentGenesis (void)
static void * DestroyMimeElement (void *mime_info)
MagickExport void MimeComponentTerminus (void)
Variables
static const char * MimeMap
static LinkedListInfo * mime_cache = (LinkedListInfo *) NULL
static SemaphoreInfo * mime_semaphore = (SemaphoreInfo *) NULL
Macro Definition Documentation
MimeFilename
#define MimeFilename "mime.xml"
Function Documentation
AcquireMimeCache()
static LinkedListInfo * AcquireMimeCache (const char * filename, ExceptionInfo * exception) static
References DestroyConfigureOptions(), GetConfigureOptions(), GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), IsLinkedListEmpty(), LoadMimeCache(), MagickFalse, MagickTrue, MimeMap, NewLinkedList(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by IsMimeCacheInstantiated(), and LoadMimeLists().
DestroyMimeElement()
static void * DestroyMimeElement (void * mime_info) static
References _MimeInfo::description, DestroyString(), _MimeInfo::magic, _MimeInfo::path, _MimeInfo::pattern, RelinquishMagickMemory(), and _MimeInfo::type.
Referenced by MimeComponentTerminus().
GetMimeDescription()
MagickExport const char * GetMimeDescription (const MimeInfo * mime_info)
References _MimeInfo::description, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MimeInfo::signature, and TraceEvent.
GetMimeInfo()
MagickExport const MimeInfo * GetMimeInfo (const char * filename, const unsigned char * magic, const size_t length, ExceptionInfo * exception)
References ByteData, _MimeInfo::data_type, _MimeInfo::endian, _MimeInfo::extent, GetNextValueInLinkedList(), GlobExpression(), InsertValueInLinkedList(), IsMimeCacheInstantiated(), _MimeInfo::length, LockSemaphoreInfo(), LongData, LSBEndian, _MimeInfo::magic, MagickFalse, _MimeInfo::mask, mime_cache, mime_semaphore, MSBEndian, _MimeInfo::offset, _MimeInfo::pattern, _MimeInfo::priority, RemoveElementByValueFromLinkedList(), ResetLinkedListIterator(), ShortData, StringData, UndefinedEndian, UnlockSemaphoreInfo(), and _MimeInfo::value.
Referenced by GetMimeInfoList(), GetMimeList(), and MagickToMime().
GetMimeInfoList()
MagickExport const MimeInfo ** GetMimeInfoList (const char * pattern, size_t * number_aliases, ExceptionInfo * exception)
References AcquireQuantumMemory(), GetMagickModule, GetMimeInfo(), GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, mime_cache, mime_semaphore, MimeInfoCompare(), ResetLinkedListIterator(), _MimeInfo::stealth, TraceEvent, _MimeInfo::type, and UnlockSemaphoreInfo().
Referenced by ListMimeInfo().
GetMimeList()
MagickExport char ** GetMimeList (const char * pattern, size_t * number_aliases, ExceptionInfo * exception)
References AcquireQuantumMemory(), ConstantString(), GetMagickModule, GetMimeInfo(), GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, mime_cache, mime_semaphore, MimeCompare(), ResetLinkedListIterator(), _MimeInfo::stealth, TraceEvent, _MimeInfo::type, and UnlockSemaphoreInfo().
GetMimeType()
MagickExport const char * GetMimeType (const MimeInfo * mime_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, _MimeInfo::signature, TraceEvent, and _MimeInfo::type.
Referenced by MagickToMime().
IsMimeCacheInstantiated()
static MagickBooleanType IsMimeCacheInstantiated (ExceptionInfo * exception) static
References AcquireMimeCache(), ActivateSemaphoreInfo(), LockSemaphoreInfo(), MagickFalse, MagickTrue, mime_cache, mime_semaphore, MimeFilename, and UnlockSemaphoreInfo().
Referenced by GetMimeInfo().
ListMimeInfo()
MagickExport MagickBooleanType ListMimeInfo (FILE * file, ExceptionInfo * exception)
References FormatLocaleFile(), GetMimeInfoList(), MagickFalse, MagickTrue, _MimeInfo::path, and RelinquishMagickMemory().
LoadMimeCache()
static MagickBooleanType LoadMimeCache (LinkedListInfo * cache, const char * xml, const char * filename, const size_t depth, ExceptionInfo * exception)
References AcquireMagickMemory(), AcquireString(), AppendValueToLinkedList(), ConcatenateMagickString(), ConfigureError, ConfigureEvent, ConstantString(), CopyMagickString(), _MimeInfo::data_type, _MimeInfo::description, DestroyString(), DestroyXMLTree(), DirectorySeparator, _MimeInfo::endian, _MimeInfo::extent, FileToXML(), GetMagickModule, GetNextXMLTreeTag(), GetPathComponent(), GetXMLTreeAttribute(), GetXMLTreeChild(), HeadPath, IsMagickTrue(), _MimeInfo::length, LoadMimeCache(), LogMagickEvent(), _MimeInfo::magic, MagickCoreSignature, MagickDataTypeOptions, MagickEndianOptions, MagickFalse, MagickMaxRecursionDepth, MagickTrue, _MimeInfo::mask, MaxTextExtent, NewXMLTree(), _MimeInfo::offset, ParseCommandOption(), _MimeInfo::path, _MimeInfo::pattern, _MimeInfo::priority, ResourceLimitError, ResourceLimitFatalError, _MimeInfo::signature, _MimeInfo::stealth, StringData, SubstituteString(), ThrowFatalException, ThrowMagickException(), _MimeInfo::type, and _MimeInfo::value.
Referenced by AcquireMimeCache(), and LoadMimeCache().
LoadMimeLists()
MagickExport MagickBooleanType LoadMimeLists (const char * name, ExceptionInfo * exception)
References AcquireMimeCache(), MagickFalse, MagickTrue, and mime_cache.
MagickToMime()
MagickExport char * MagickToMime (const char * magick)
References AcquireExceptionInfo(), ConstantString(), DestroyExceptionInfo(), FormatLocaleString(), GetMimeInfo(), GetMimeType(), LocaleLower(), and MaxTextExtent.
MimeCompare()
static int MimeCompare (const void * x, const void * y) static
Referenced by GetMimeList().
MimeComponentGenesis()
MagickExport MagickBooleanType MimeComponentGenesis (void)
References AllocateSemaphoreInfo(), MagickTrue, and mime_semaphore.
Referenced by MagickCoreGenesis().
MimeComponentTerminus()
MagickExport void MimeComponentTerminus (void)
References ActivateSemaphoreInfo(), DestroyLinkedList(), DestroyMimeElement(), DestroySemaphoreInfo(), LockSemaphoreInfo(), mime_cache, mime_semaphore, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
MimeInfoCompare()
static int MimeInfoCompare (const void * x, const void * y) static
Referenced by GetMimeInfoList().
Variable Documentation
mime_cache
LinkedListInfo* mime_cache = (LinkedListInfo *) NULL static
Referenced by GetMimeInfo(), GetMimeInfoList(), GetMimeList(), IsMimeCacheInstantiated(), LoadMimeLists(), and MimeComponentTerminus().
mime_semaphore
SemaphoreInfo* mime_semaphore = (SemaphoreInfo *) NULL static
Referenced by GetMimeInfo(), GetMimeInfoList(), GetMimeList(), IsMimeCacheInstantiated(), MimeComponentGenesis(), and MimeComponentTerminus().
MimeMap
const char* MimeMap static
Initial value:
= (char *)
    "<?xml version=\"1.0\"?>"
    "<mimemap>"
    "</mimemap>"
Referenced by AcquireMimeCache().