MagickCore: module.c File Reference
module.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/coder.h"
#include "magick/client.h"
#include "magick/configure.h"
#include "magick/deprecate.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/log.h"
#include "magick/hashmap.h"
#include "magick/magic.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/module.h"
#include "magick/nt-base-private.h"
#include "magick/policy.h"
#include "magick/semaphore.h"
#include "magick/splay-tree.h"
#include "magick/static.h"
#include "magick/string_.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/utility-private.h"
Functions
size_t analyzeImage (Image **, const int, const char **, ExceptionInfo *)
MagickExport MagickBooleanType ListModuleInfo (FILE *magick_unused(file), ExceptionInfo *magick_unused(exception))
MagickExport MagickBooleanType InvokeDynamicImageFilter (const char *tag, Image **image, const int argc, const char **argv, ExceptionInfo *exception)
Function Documentation
analyzeImage()
size_t analyzeImage (Image ** , const int , const char ** , ExceptionInfo *)
Referenced by InvokeDynamicImageFilter().
InvokeDynamicImageFilter()
MagickExport MagickBooleanType InvokeDynamicImageFilter (const char * tag, Image ** image, const int argc, const char ** argv, ExceptionInfo * exception)
References analyzeImage(), CoderEvent, FilterPolicyDomain, GetMagickModule, IsRightsAuthorized(), LocaleCompare(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickImageFilterSignature, MagickTrue, ModuleError, PolicyError, ReadPolicyRights, ThrowMagickException(), and TraceEvent.
ListModuleInfo()
MagickExport MagickBooleanType ListModuleInfo (FILE * magick_unusedfile, ExceptionInfo * magick_unusedexception)
References magick_unreferenced, and MagickTrue.