MagickCore: monitor-private.h File Reference
monitor-private.h File Reference
Functions
MagickPrivate MagickBooleanType MonitorComponentGenesis (void)
MagickPrivate void MonitorComponentTerminus (void)
Function Documentation
MonitorComponentGenesis()
MagickPrivate MagickBooleanType MonitorComponentGenesis (void)
References ActivateSemaphoreInfo(), MagickTrue, and monitor_semaphore.
Referenced by MagickCoreGenesis().
MonitorComponentTerminus()
MagickPrivate void MonitorComponentTerminus (void)
References ActivateSemaphoreInfo(), DestroySemaphoreInfo(), LockSemaphoreInfo(), monitor_semaphore, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().