MagickCore: monitor.h File Reference
monitor.h File Reference
Typedefs
typedef MagickBooleanType(* MagickProgressMonitor) (const char *, const MagickOffsetType, const MagickSizeType, void *)
Functions
MagickExport MagickBooleanType SetImageProgress (const Image *, const char *, const MagickOffsetType, const MagickSizeType)
MagickExport MagickProgressMonitor SetImageProgressMonitor (Image *, const MagickProgressMonitor, void *)
MagickExport MagickProgressMonitor SetImageInfoProgressMonitor (ImageInfo *, const MagickProgressMonitor, void *)
static MagickBooleanType QuantumTick (const MagickOffsetType offset, const MagickSizeType span)
Typedef Documentation
MagickProgressMonitor
typedef MagickBooleanType(* MagickProgressMonitor) (const char *, const MagickOffsetType, const MagickSizeType, void *)
Function Documentation
QuantumTick()
static MagickBooleanType QuantumTick (const MagickOffsetType offset, const MagickSizeType span) inline static
References MagickFalse, and MagickTrue.
SetImageInfoProgressMonitor()
MagickExport MagickProgressMonitor SetImageInfoProgressMonitor (ImageInfo * image_info, const MagickProgressMonitor, void * client_data)
References _ImageInfo::client_data, and _ImageInfo::progress_monitor.
Referenced by ReadInlineImage().
SetImageProgress()
MagickExport MagickBooleanType SetImageProgress (const Image * image, const char * tag, const MagickOffsetType, const MagickSizeType)
References ActivateSemaphoreInfo(), _Image::client_data, _Image::filename, FormatLocaleString(), LockSemaphoreInfo(), MagickPathExtent, MagickTrue, monitor_semaphore, _Image::progress_monitor, and UnlockSemaphoreInfo().
Referenced by AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), AddNoiseImageChannel(), AppendImages(), AssignImageColors(), BilevelImageChannel(), BlackThresholdImageChannel(), BlueShiftImage(), CannyEdgeImage(), ChopImage(), ClampImageChannel(), Classify(), ClassifyImageColors(), ClutImageChannel(), ColorDecisionListImage(), ColorizeImage(), ColorMatrixImage(), CombineImages(), ComplexImages(), CompositeImageChannel(), ConnectedComponentsImage(), ContrastImage(), ContrastStretchImageChannel(), CopyImagePixels(), CropImage(), DespeckleImage(), DistortImage(), DuplexTransferImageViewIterator(), EnhanceImage(), EqualizeImageChannel(), EvaluateImageChannel(), EvaluateImages(), ExcerptImage(), FilterImageChannel(), FlipImage(), FlopImage(), FloydSteinbergDither(), FrameImage(), FunctionImageChannel(), FxImageChannel(), GammaImageChannel(), GetImageDynamicThreshold(), GetImageViewIterator(), GetNormalizedCrossCorrelationDistortion(), GetNumberColors(), GrayscaleImage(), HaldClutImageChannel(), HorizontalFilter(), HoughLineImage(), HuffmanDecodeImage(), HuffmanEncodeImage(), ImplodeImage(), IntegralRotateImage(), InterpolativeResizeImage(), IsImageSimilar(), KuwaharaImageChannel(), LevelImageChannel(), LevelizeImageChannel(), MagnifyImage(), MeanShiftImage(), MergeImageLayers(), ModulateImage(), MontageImageList(), MorphImages(), MorphologyPrimitive(), MorphologyPrimitiveDirect(), MotionBlurImageChannel(), NegateImageChannel(), OilPaintImage(), OpaqueImage(), OpaquePaintImageChannel(), OrderedPosterizeImageChannel(), PerceptibleImageChannel(), PolynomialImageChannel(), PosterizeImageChannel(), PreviewImage(), ProfileImage(), QuantizeImages(), RaiseImage(), RandomThresholdImageChannel(), ReduceImageColors(), RenderMVGContent(), RGBTransformImage(), RiemersmaDither(), RollImage(), RotationalBlurImageChannel(), SampleImage(), ScaleImage(), SelectiveBlurImageChannel(), SeparateImageChannel(), SepiaToneImage(), SetImageViewIterator(), ShadeImage(), ShadowImage(), SigmoidalContrastImageChannel(), SimilarityMetricImage(), SmushImages(), SolarizeImageChannel(), SparseColorImage(), SpliceImage(), SpreadImage(), StatisticImageChannel(), SteganoImage(), StereoAnaglyphImage(), SwirlImage(), TextureImage(), TintImage(), TransferImageViewIterator(), TransformRGBImage(), TransparentImage(), TransparentPaintImage(), TransparentPaintImageChroma(), TransposeImage(), TransverseImage(), UniqueColorsToImage(), UnsharpMaskImageChannel(), UpdateImageViewIterator(), VerticalFilter(), WaveImage(), WaveletDenoiseImage(), WhiteThresholdImageChannel(), WriteImages(), XShearImage(), and YShearImage().
SetImageProgressMonitor()
MagickExport MagickProgressMonitor SetImageProgressMonitor (Image * , const MagickProgressMonitor, void *)