MagickCore: montage.h File Reference
montage.h File Reference
Data Structures
struct _MontageInfo
Typedefs
typedef struct _MontageInfo MontageInfo
Enumerations
enum MontageMode { UndefinedMode , FrameMode , UnframeMode , ConcatenateMode }
Functions
MagickExport Image * MontageImages (const Image *, const MontageInfo *, ExceptionInfo *)
MagickExport Image * MontageImageList (const ImageInfo *, const MontageInfo *, const Image *, ExceptionInfo *)
MagickExport MontageInfo * CloneMontageInfo (const ImageInfo *, const MontageInfo *)
MagickExport MontageInfo * DestroyMontageInfo (MontageInfo *)
MagickExport void GetMontageInfo (const ImageInfo *, MontageInfo *)
Typedef Documentation
MontageInfo
typedef struct _MontageInfo MontageInfo
Enumeration Type Documentation
MontageMode
enum MontageMode
Enumerator
UndefinedMode
FrameMode
UnframeMode
ConcatenateMode
Function Documentation
CloneMontageInfo()
MagickExport MontageInfo * CloneMontageInfo (const ImageInfo * , const MontageInfo *)
DestroyMontageInfo()
MagickExport MontageInfo * DestroyMontageInfo (MontageInfo * montage_info)
References _MontageInfo::debug, DestroyString(), _MontageInfo::font, _MontageInfo::frame, _MontageInfo::geometry, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, RelinquishMagickMemory(), _MontageInfo::signature, _MontageInfo::texture, _MontageInfo::tile, _MontageInfo::title, and TraceEvent.
Referenced by PreviewImage().
GetMontageInfo()
MagickExport void GetMontageInfo (const ImageInfo * image_info, MontageInfo * montage_info)
References AcquireString(), _ImageInfo::background_color, _MontageInfo::background_color, _ImageInfo::border_color, _MontageInfo::border_color, CenterGravity, CopyMagickString(), _ImageInfo::debug, _MontageInfo::debug, DefaultTileGeometry, _ImageInfo::filename, _MontageInfo::filename, _MontageInfo::fill, _ImageInfo::font, _MontageInfo::font, _MontageInfo::geometry, GetMagickModule, _MontageInfo::gravity, IsEventLogging(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _ImageInfo::matte_color, _MontageInfo::matte_color, MaxTextExtent, _PixelPacket::opacity, OpaqueOpacity, _ImageInfo::pointsize, _MontageInfo::pointsize, _ImageInfo::signature, _MontageInfo::signature, _MontageInfo::stroke, TraceEvent, and TransparentOpacity.
Referenced by CloneMontageInfo().
MontageImageList()
MagickExport Image * MontageImageList (const ImageInfo * image_info, const MontageInfo * montage_info, const Image * images, ExceptionInfo * exception)
References AcquireImage(), AcquireNextImage(), AcquireQuantumMemory(), AcquireString(), AnnotateImage(), _TypeMetric::ascent, _Image::background_color, _ImageInfo::background_color, _MontageInfo::background_color, _ImageInfo::border_color, _MontageInfo::border_color, _MontageInfo::border_width, BorderImage(), CenterGravity, _Image::client_data, CloneDrawInfo(), CloneImage(), CloneImageInfo(), CloneString(), _Image::columns, _Image::compose, CompositeImage(), ConcatenateMagickString(), CopyMagickString(), _Image::debug, _TypeMetric::descent, DestroyDrawInfo(), DestroyImage(), DestroyImageInfo(), DestroyImageList(), DestroyString(), _Image::directory, DstOutCompositeOp, _Image::exception, _Image::filename, _ImageInfo::filename, _MontageInfo::filename, _DrawInfo::fill, _MontageInfo::fill, _DrawInfo::font, _MontageInfo::font, FormatLocaleString(), _MontageInfo::frame, FrameImage(), _DrawInfo::geometry, _MontageInfo::geometry, GetFirstImageInList(), GetGeometry(), GetImageListLength(), GetImageProperty(), GetMagickModule, GetMontageGeometry(), GetNextImageInList(), GetTypeMetrics(), _DrawInfo::gravity, _Image::gravity, _MontageInfo::gravity, _FrameInfo::height, _RectangleInfo::height, HeightValue, ImageListToArray(), InheritException(), _FrameInfo::inner_bevel, InterpretImageProperties(), LocaleCompare(), LogMagickEvent(), _Image::magick, MagickCoreSignature, MagickFalse, MagickMax, MagickMin, MagickTrue, MaxTextExtent, _Image::montage, MontageImageTag, MultilineCensus(), NegateImageChannel(), NewImageList(), OpacityChannel, _FrameInfo::outer_bevel, OverCompositeOp, _Image::page, ParseAbsoluteGeometry(), ParseGravityGeometry(), ParseMetaGeometry(), ParseRegionGeometry(), _DrawInfo::pointsize, _MontageInfo::pointsize, _Image::progress_monitor, PsiValue, QueryColorDatabase(), ReadImage(), RelinquishMagickMemory(), ResourceLimitError, RhoValue, _Image::rows, _Image::scene, SceneCompare(), SetGeometry(), SetImageBackgroundColor(), SetImageProgress(), SetImageProgressMonitor(), _MontageInfo::shadow, ShadowImage(), SigmaValue, _ExceptionInfo::signature, _Image::signature, _MontageInfo::signature, _DrawInfo::stroke, _MontageInfo::stroke, _DrawInfo::text, _MontageInfo::texture, TextureImage(), ThrowImageException, ThumbnailImage(), _MontageInfo::tile, TileImageTag, _MontageInfo::title, TraceEvent, UndefinedGravity, _FrameInfo::width, _RectangleInfo::width, _FrameInfo::x, _RectangleInfo::x, XiValue, _FrameInfo::y, and _RectangleInfo::y.
Referenced by MontageImages().
MontageImages()
MagickExport Image * MontageImages (const Image * , const MontageInfo * , ExceptionInfo *)