MagickCore: morphology-private.h File Reference
morphology-private.h File Reference
#include "magick/morphology.h"
Functions
MagickExport Image * MorphologyApply (const Image *, const ChannelType, const MorphologyMethod, const ssize_t, const KernelInfo *, const CompositeOperator, const double, ExceptionInfo *)
MagickExport void ZeroKernelNans (KernelInfo *)
Function Documentation
MorphologyApply()
MagickExport Image * MorphologyApply (const Image * image, const ChannelType, const MorphologyMethod, const ssize_t, const KernelInfo * kernel, const CompositeOperator, const double bias, ExceptionInfo * exception)
References BottomHatMorphology, CloneImage(), CloneKernelInfo(), CloseIntensityMorphology, CloseMorphology, _Image::columns, CommandOptionToMnemonic(), _Image::compose, CompositeImageChannel(), ConvolveMorphology, CopyOpacityCompositeOp, CorrelateMorphology, DeactivateAlphaChannel, DefaultChannels, DestroyImage(), DestroyKernelInfo(), DifferenceCompositeOp, DilateIntensityMorphology, DilateMorphology, DirectClass, DistanceMorphology, EdgeInMorphology, EdgeMorphology, EdgeOutMorphology, ErodeIntensityMorphology, ErodeMorphology, _Image::exception, FormatLocaleFile(), FormatLocaleString(), GetImageArtifact(), HitAndMissMorphology, InheritException(), IsMagickTrue(), LightenCompositeOp, MagickComposeOptions, MagickCoreSignature, MagickFalse, MagickMorphologyOptions, MagickTrue, MaxTextExtent, MorphologyPrimitive(), MorphologyPrimitiveDirect(), KernelInfo::next, NoCompositeOp, OpenIntensityMorphology, OpenMorphology, RotateKernelInfo(), _Image::rows, SetImageAlphaChannel(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, KernelInfo::signature, SmoothMorphology, ThickenMorphology, ThinningMorphology, TopHatMorphology, UndefinedCompositeOp, and VoronoiMorphology.
Referenced by MorphologyImageChannel().
ZeroKernelNans()
MagickExport void ZeroKernelNans (KernelInfo * kernel)
References KernelInfo::height, IsNaN, KernelInfo::next, KernelInfo::values, KernelInfo::width, and ZeroKernelNans().
Referenced by ZeroKernelNans().