MagickCore: morphology.h File Reference
morphology.h File Reference
#include "magick/geometry.h"
Data Structures
struct KernelInfo
Typedefs
typedef struct KernelInfo KernelInfo
Enumerations
enum KernelInfoType {
UndefinedKernel , UnityKernel , GaussianKernel , DoGKernel ,
LoGKernel , BlurKernel , CometKernel , LaplacianKernel ,
SobelKernel , FreiChenKernel , RobertsKernel , PrewittKernel ,
CompassKernel , KirschKernel , DiamondKernel , SquareKernel ,
RectangleKernel , OctagonKernel , DiskKernel , PlusKernel ,
CrossKernel , RingKernel , PeaksKernel , EdgesKernel ,
CornersKernel , DiagonalsKernel , LineEndsKernel , LineJunctionsKernel ,
RidgesKernel , ConvexHullKernel , ThinSEKernel , SkeletonKernel ,
ChebyshevKernel , ManhattanKernel , OctagonalKernel , EuclideanKernel ,
UserDefinedKernel , BinomialKernel
}
enum MorphologyMethod {
UndefinedMorphology , ConvolveMorphology , CorrelateMorphology , ErodeMorphology ,
DilateMorphology , ErodeIntensityMorphology , DilateIntensityMorphology , DistanceMorphology ,
OpenMorphology , CloseMorphology , OpenIntensityMorphology , CloseIntensityMorphology ,
SmoothMorphology , EdgeInMorphology , EdgeOutMorphology , EdgeMorphology ,
TopHatMorphology , BottomHatMorphology , HitAndMissMorphology , ThinningMorphology ,
ThickenMorphology , VoronoiMorphology , IterativeDistanceMorphology
}
Functions
MagickExport KernelInfo * AcquireKernelInfo (const char *)
MagickExport KernelInfo * AcquireKernelBuiltIn (const KernelInfoType, const GeometryInfo *)
MagickExport KernelInfo * CloneKernelInfo (const KernelInfo *)
MagickExport KernelInfo * DestroyKernelInfo (KernelInfo *)
MagickExport Image * MorphologyImage (const Image *, const MorphologyMethod, const ssize_t, const KernelInfo *, ExceptionInfo *)
MagickExport Image * MorphologyImageChannel (const Image *, const ChannelType, const MorphologyMethod, const ssize_t, const KernelInfo *, ExceptionInfo *)
MagickExport void ScaleGeometryKernelInfo (KernelInfo *, const char *)
MagickExport void ScaleKernelInfo (KernelInfo *, const double, const GeometryFlags)
MagickExport void ShowKernelInfo (const KernelInfo *)
MagickExport void UnityAddKernelInfo (KernelInfo *, const double)
Typedef Documentation
KernelInfo
typedef struct KernelInfo KernelInfo
Enumeration Type Documentation
KernelInfoType
enum KernelInfoType
Enumerator
UndefinedKernel
UnityKernel
GaussianKernel
DoGKernel
LoGKernel
BlurKernel
CometKernel
LaplacianKernel
SobelKernel
FreiChenKernel
RobertsKernel
PrewittKernel
CompassKernel
KirschKernel
DiamondKernel
SquareKernel
RectangleKernel
OctagonKernel
DiskKernel
PlusKernel
CrossKernel
RingKernel
PeaksKernel
EdgesKernel
CornersKernel
DiagonalsKernel
LineEndsKernel
LineJunctionsKernel
RidgesKernel
ConvexHullKernel
ThinSEKernel
SkeletonKernel
ChebyshevKernel
ManhattanKernel
OctagonalKernel
EuclideanKernel
UserDefinedKernel
BinomialKernel
MorphologyMethod
enum MorphologyMethod
Enumerator
UndefinedMorphology
ConvolveMorphology
CorrelateMorphology
ErodeMorphology
DilateMorphology
ErodeIntensityMorphology
DilateIntensityMorphology
DistanceMorphology
OpenMorphology
CloseMorphology
OpenIntensityMorphology
CloseIntensityMorphology
SmoothMorphology
EdgeInMorphology
EdgeOutMorphology
EdgeMorphology
TopHatMorphology
BottomHatMorphology
HitAndMissMorphology
ThinningMorphology
ThickenMorphology
VoronoiMorphology
IterativeDistanceMorphology
Function Documentation
AcquireKernelBuiltIn()
MagickExport KernelInfo * AcquireKernelBuiltIn (const KernelInfoType, const GeometryInfo *)
AcquireKernelInfo()
MagickExport KernelInfo * AcquireKernelInfo (const char *)
CloneKernelInfo()
MagickExport KernelInfo * CloneKernelInfo (const KernelInfo *)
DestroyKernelInfo()
MagickExport KernelInfo * DestroyKernelInfo (KernelInfo * kernel)
References DestroyKernelInfo(), KernelInfo::next, RelinquishAlignedMemory(), RelinquishMagickMemory(), and KernelInfo::values.
Referenced by AcquireKernelBuiltIn(), AcquireKernelInfo(), BlurImageChannel(), CannyEdgeImage(), CloneKernelInfo(), ConvolveImageChannel(), DestroyKernelInfo(), EdgeImage(), EmbossImage(), ExpandRotateKernelInfo(), GaussianBlurImageChannel(), MorphologyApply(), MorphologyImageChannel(), ParseKernelArray(), RecolorImage(), and SharpenImageChannel().
MorphologyImage()
MagickExport Image * MorphologyImage (const Image * , const MorphologyMethod, const ssize_t, const KernelInfo * , ExceptionInfo *)
MorphologyImageChannel()
MagickExport Image * MorphologyImageChannel (const Image * image, const ChannelType, const MorphologyMethod, const ssize_t, const KernelInfo * kernel, ExceptionInfo * exception)
References _Image::bias, CloneKernelInfo(), ConvolveMorphology, CorrelateMorphology, DestroyKernelInfo(), GetImageArtifact(), IsMagickTrue(), MagickComposeOptions, MagickFalse, MorphologyApply(), ParseCommandOption(), QuantumRange, ScaleGeometryKernelInfo(), ShowKernelInfo(), StringToDoubleInterval(), and UndefinedCompositeOp.
Referenced by BlurImageChannel(), CannyEdgeImage(), ConvolveImageChannel(), EdgeImage(), EmbossImage(), GaussianBlurImageChannel(), MorphologyImage(), and SharpenImageChannel().
ScaleGeometryKernelInfo()
MagickExport void ScaleGeometryKernelInfo (KernelInfo * , const char *)
ScaleKernelInfo()
MagickExport void ScaleKernelInfo (KernelInfo * , const double , const GeometryFlags)
ShowKernelInfo()
MagickExport void ShowKernelInfo (const KernelInfo *)
UnityAddKernelInfo()
MagickExport void UnityAddKernelInfo (KernelInfo * kernel, const double scale)
References CalcKernelMetaData(), KernelInfo::next, UnityAddKernelInfo(), KernelInfo::values, KernelInfo::width, KernelInfo::x, and KernelInfo::y.
Referenced by ScaleGeometryKernelInfo(), and UnityAddKernelInfo().