MagickCore: mutex.h File Reference
mutex.h File Reference
Functions
static void DestroyMagickMutex (void)
static void InitializeMagickMutex (void)
static void LockMagickMutex (void)
static void UnlockMagickMutex (void)
Function Documentation
DestroyMagickMutex()
static void DestroyMagickMutex (void) inline static
References MagickFalse.
Referenced by SemaphoreComponentTerminus().
InitializeMagickMutex()
static void InitializeMagickMutex (void) inline static
References MagickTrue.
Referenced by AcquireSemaphoreInfo(), LockMagickMutex(), MagickCoreGenesis(), MagickCoreTerminus(), and SemaphoreComponentGenesis().
LockMagickMutex()
static void LockMagickMutex (void) inline static
References InitializeMagickMutex(), MagickFalse, pthread_mutex_lock, ResourceLimitFatalError, and ThrowFatalException.
Referenced by AcquireSemaphoreInfo(), ActivateSemaphoreInfo(), DestroySemaphoreInfo(), MagickCoreGenesis(), and MagickCoreTerminus().
UnlockMagickMutex()
static void UnlockMagickMutex (void) inline static
References pthread_mutex_unlock, ResourceLimitFatalError, and ThrowFatalException.
Referenced by AcquireSemaphoreInfo(), ActivateSemaphoreInfo(), DestroySemaphoreInfo(), MagickCoreGenesis(), and MagickCoreTerminus().