MagickCore: option.h File Reference
option.h File Reference
Data Structures
struct _OptionInfo
Typedefs
typedef struct _OptionInfo OptionInfo
Enumerations
enum CommandOption {
MagickUndefinedOptions = -1 , MagickAlignOptions = 0 , MagickAlphaOptions , MagickBooleanOptions ,
MagickCacheOptions , MagickChannelOptions , MagickClassOptions , MagickClipPathOptions ,
MagickCoderOptions , MagickColorOptions , MagickColorspaceOptions , MagickCommandOptions ,
MagickComposeOptions , MagickCompressOptions , MagickConfigureOptions , MagickDataTypeOptions ,
MagickDebugOptions , MagickDecorateOptions , MagickDelegateOptions , MagickDirectionOptions ,
MagickDisposeOptions , MagickDistortOptions , MagickDitherOptions , MagickEndianOptions ,
MagickEvaluateOptions , MagickFillRuleOptions , MagickFilterOptions , MagickFontOptions ,
MagickFontsOptions , MagickFormatOptions , MagickFunctionOptions , MagickGravityOptions ,
MagickIntentOptions , MagickInterlaceOptions , MagickInterpolateOptions , MagickKernelOptions ,
MagickLayerOptions , MagickLineCapOptions , MagickLineJoinOptions , MagickListOptions ,
MagickLocaleOptions , MagickLogEventOptions , MagickLogOptions , MagickMagicOptions ,
MagickMethodOptions , MagickMetricOptions , MagickMimeOptions , MagickModeOptions ,
MagickModuleOptions , MagickMorphologyOptions , MagickNoiseOptions , MagickOrientationOptions ,
MagickPixelIntensityOptions , MagickPolicyOptions , MagickPolicyDomainOptions , MagickPolicyRightsOptions ,
MagickPreviewOptions , MagickPrimitiveOptions , MagickQuantumFormatOptions , MagickResolutionOptions ,
MagickResourceOptions , MagickSparseColorOptions , MagickStatisticOptions , MagickStorageOptions ,
MagickStretchOptions , MagickStyleOptions , MagickThresholdOptions , MagickTypeOptions ,
MagickValidateOptions , MagickVirtualPixelOptions , MagickComplexOptions , MagickIntensityOptions ,
MagickGradientOptions , MagickWeightOptions , MagickComplianceOptions , MagickAutoThresholdOptions
}
enum ValidateType {
UndefinedValidate , NoValidate = 0x00000 , ColorspaceValidate = 0x00001 , CompareValidate = 0x00002 ,
CompositeValidate = 0x00004 , ConvertValidate = 0x00008 , FormatsDiskValidate = 0x00010 , FormatsMapValidate = 0x00020 ,
FormatsMemoryValidate = 0x00040 , IdentifyValidate = 0x00080 , ImportExportValidate = 0x00100 , MontageValidate = 0x00200 ,
StreamValidate = 0x00400 , AllValidate = 0x7fffffff
}
enum CommandOptionFlags {
UndefinedOptionFlag = 0x0000 , FireOptionFlag = 0x0001 , ImageInfoOptionFlag = 0x0002 , DrawInfoOptionFlag = 0x0004 ,
QuantizeInfoOptionFlag = 0x0008 , GlobalOptionFlag = 0x0010 , SimpleOperatorOptionFlag = 0x0100 , ListOperatorOptionFlag = 0x0200 ,
SpecialOperatorOptionFlag = 0x0400 , GenesisOptionFlag = 0x0400 , NonConvertOptionFlag = 0x4000 , DeprecateOptionFlag = 0x8000
}
Functions
MagickExport char ** GetCommandOptions (const CommandOption)
MagickExport char * GetNextImageOption (const ImageInfo *)
MagickExport char * RemoveImageOption (ImageInfo *, const char *)
MagickExport const char * CommandOptionToMnemonic (const CommandOption, const ssize_t)
MagickExport const char * GetImageOption (const ImageInfo *, const char *)
MagickExport MagickBooleanType CloneImageOptions (ImageInfo *, const ImageInfo *)
MagickExport MagickBooleanType DefineImageOption (ImageInfo *, const char *)
MagickExport MagickBooleanType DeleteImageOption (ImageInfo *, const char *)
MagickExport MagickBooleanType IsCommandOption (const char *)
MagickExport MagickBooleanType IsOptionMember (const char *, const char *)
MagickExport MagickBooleanType ListCommandOptions (FILE *, const CommandOption, ExceptionInfo *)
MagickExport MagickBooleanType SetImageOption (ImageInfo *, const char *, const char *)
MagickExport ssize_t GetCommandOptionFlags (const CommandOption, const MagickBooleanType, const char *)
MagickExport ssize_t ParseChannelOption (const char *)
MagickExport ssize_t ParseCommandOption (const CommandOption, const MagickBooleanType, const char *)
MagickExport void DestroyImageOptions (ImageInfo *)
MagickExport void ResetImageOptions (const ImageInfo *)
MagickExport void ResetImageOptionIterator (const ImageInfo *)
Typedef Documentation
OptionInfo
typedef struct _OptionInfo OptionInfo
Enumeration Type Documentation
CommandOption
enum CommandOption
Enumerator
MagickUndefinedOptions
MagickAlignOptions
MagickAlphaOptions
MagickBooleanOptions
MagickCacheOptions
MagickChannelOptions
MagickClassOptions
MagickClipPathOptions
MagickCoderOptions
MagickColorOptions
MagickColorspaceOptions
MagickCommandOptions
MagickComposeOptions
MagickCompressOptions
MagickConfigureOptions
MagickDataTypeOptions
MagickDebugOptions
MagickDecorateOptions
MagickDelegateOptions
MagickDirectionOptions
MagickDisposeOptions
MagickDistortOptions
MagickDitherOptions
MagickEndianOptions
MagickEvaluateOptions
MagickFillRuleOptions
MagickFilterOptions
MagickFontOptions
MagickFontsOptions
MagickFormatOptions
MagickFunctionOptions
MagickGravityOptions
MagickIntentOptions
MagickInterlaceOptions
MagickInterpolateOptions
MagickKernelOptions
MagickLayerOptions
MagickLineCapOptions
MagickLineJoinOptions
MagickListOptions
MagickLocaleOptions
MagickLogEventOptions
MagickLogOptions
MagickMagicOptions
MagickMethodOptions
MagickMetricOptions
MagickMimeOptions
MagickModeOptions
MagickModuleOptions
MagickMorphologyOptions
MagickNoiseOptions
MagickOrientationOptions
MagickPixelIntensityOptions
MagickPolicyOptions
MagickPolicyDomainOptions
MagickPolicyRightsOptions
MagickPreviewOptions
MagickPrimitiveOptions
MagickQuantumFormatOptions
MagickResolutionOptions
MagickResourceOptions
MagickSparseColorOptions
MagickStatisticOptions
MagickStorageOptions
MagickStretchOptions
MagickStyleOptions
MagickThresholdOptions
MagickTypeOptions
MagickValidateOptions
MagickVirtualPixelOptions
MagickComplexOptions
MagickIntensityOptions
MagickGradientOptions
MagickWeightOptions
MagickComplianceOptions
MagickAutoThresholdOptions
CommandOptionFlags
enum CommandOptionFlags
Enumerator
UndefinedOptionFlag
FireOptionFlag
ImageInfoOptionFlag
DrawInfoOptionFlag
QuantizeInfoOptionFlag
GlobalOptionFlag
SimpleOperatorOptionFlag
ListOperatorOptionFlag
SpecialOperatorOptionFlag
GenesisOptionFlag
NonConvertOptionFlag
DeprecateOptionFlag
ValidateType
enum ValidateType
Enumerator
UndefinedValidate
NoValidate
ColorspaceValidate
CompareValidate
CompositeValidate
ConvertValidate
FormatsDiskValidate
FormatsMapValidate
FormatsMemoryValidate
IdentifyValidate
ImportExportValidate
MontageValidate
StreamValidate
AllValidate
Function Documentation
CloneImageOptions()
MagickExport MagickBooleanType CloneImageOptions (ImageInfo * , const ImageInfo *)
CommandOptionToMnemonic()
MagickExport const char * CommandOptionToMnemonic (const CommandOption, const ssize_t)
DefineImageOption()
MagickExport MagickBooleanType DefineImageOption (ImageInfo * , const char *)
DeleteImageOption()
MagickExport MagickBooleanType DeleteImageOption (ImageInfo * , const char *)
DestroyImageOptions()
MagickExport void DestroyImageOptions (ImageInfo *)
GetCommandOptionFlags()
MagickExport ssize_t GetCommandOptionFlags (const CommandOption, const MagickBooleanType, const char *)
GetCommandOptions()
MagickExport char ** GetCommandOptions (const CommandOption)
GetImageOption()
MagickExport const char * GetImageOption (const ImageInfo * image_info, const char * key)
References _ImageInfo::debug, _ImageInfo::filename, GetMagickModule, GetValueFromSplayTree(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _ImageInfo::options, _ImageInfo::signature, and TraceEvent.
Referenced by AcquireImage(), AcquireQuantizeInfo(), GetDrawInfo(), GetQuantumInfo(), InterpretImageFilename(), InterpretImageProperties(), ReadImage(), SetStreamBuffering(), SyncImageSettings(), and WriteImage().
GetNextImageOption()
MagickExport char * GetNextImageOption (const ImageInfo *)
IsCommandOption()
MagickExport MagickBooleanType IsCommandOption (const char *)
IsOptionMember()
MagickExport MagickBooleanType IsOptionMember (const char * , const char *)
ListCommandOptions()
MagickExport MagickBooleanType ListCommandOptions (FILE * , const CommandOption, ExceptionInfo *)
ParseChannelOption()
MagickExport ssize_t ParseChannelOption (const char *)
ParseCommandOption()
MagickExport ssize_t ParseCommandOption (const CommandOption, const MagickBooleanType, const char * options)
References CopyMagickString(), GetOptionInfo(), LocaleCompare(), MagickFalse, MagickTrue, MaxTextExtent, _OptionInfo::mnemonic, sentinel, and _OptionInfo::type.
Referenced by AcquireImage(), AcquireQuantizeInfo(), AcquireResizeFilter(), DrawPatternPath(), ExpandFilenames(), FxChannelStatistics(), GetDrawInfo(), GetImageProperty(), GetPolicyInfo(), GetQuantumInfo(), GradientImage(), IdentifyImage(), LoadLogCache(), LoadMimeCache(), LoadPolicyCache(), LoadTypeCache(), ModulateImage(), MorphologyImageChannel(), ParseChannelOption(), ParseKernelName(), QueryMagickColorCompliance(), ReadImage(), RenderMVGContent(), SetImageProperty(), SetLogEventMask(), and SyncImageSettings().
RemoveImageOption()
MagickExport char * RemoveImageOption (ImageInfo * image_info, const char * option)
References _ImageInfo::debug, _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ImageInfo::options, RemoveNodeFromSplayTree(), _ImageInfo::signature, and TraceEvent.
ResetImageOptionIterator()
MagickExport void ResetImageOptionIterator (const ImageInfo * image_info)
References _ImageInfo::debug, _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ImageInfo::options, ResetSplayTreeIterator(), _ImageInfo::signature, and TraceEvent.
Referenced by InterpretImageProperties(), and SyncImageSettings().
ResetImageOptions()
MagickExport void ResetImageOptions (const ImageInfo *)
SetImageOption()
MagickExport MagickBooleanType SetImageOption (ImageInfo * image_info, const char * option, const char * value)
References AddValueToSplayTree(), CloneString(), CompareSplayTreeString(), ConstantString(), _ImageInfo::debug, DeleteImageOption(), _ImageInfo::filename, GetMagickModule, LocaleCompare(), LogMagickEvent(), MagickCoreSignature, MagickFalse, NewSplayTree(), _ImageInfo::options, RelinquishMagickMemory(), _ImageInfo::signature, _ImageInfo::size, and TraceEvent.
Referenced by DefineImageOption(), HoughLineImage(), and SetImageType().