MagickCore: option.c File Reference
option.c File Reference
#include "magick/studio.h"
#include "magick/artifact.h"
#include "magick/cache.h"
#include "magick/color.h"
#include "magick/compare.h"
#include "magick/constitute.h"
#include "magick/distort.h"
#include "magick/draw.h"
#include "magick/effect.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/fourier.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/layer.h"
#include "magick/mime-private.h"
#include "magick/memory_.h"
#include "magick/monitor.h"
#include "magick/montage.h"
#include "magick/morphology.h"
#include "magick/option.h"
#include "magick/option-private.h"
#include "magick/policy.h"
#include "magick/property.h"
#include "magick/quantize.h"
#include "magick/quantum.h"
#include "magick/resample.h"
#include "magick/resource_.h"
#include "magick/splay-tree.h"
#include "magick/statistic.h"
#include "magick/string_.h"
#include "magick/threshold.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/visual-effects.h"
Functions
MagickExport MagickBooleanType CloneImageOptions (ImageInfo *image_info, const ImageInfo *clone_info)
MagickExport MagickBooleanType DefineImageOption (ImageInfo *image_info, const char *option)
MagickExport MagickBooleanType DeleteImageOption (ImageInfo *image_info, const char *option)
MagickExport void DestroyImageOptions (ImageInfo *image_info)
MagickExport const char * GetImageOption (const ImageInfo *image_info, const char *key)
static const OptionInfo * GetOptionInfo (const CommandOption option)
MagickExport ssize_t GetCommandOptionFlags (const CommandOption option, const MagickBooleanType list, const char *options)
MagickExport char ** GetCommandOptions (const CommandOption option)
MagickExport char * GetNextImageOption (const ImageInfo *image_info)
MagickExport MagickBooleanType IsCommandOption (const char *option)
MagickExport const char * CommandOptionToMnemonic (const CommandOption option, const ssize_t type)
MagickExport MagickBooleanType IsOptionMember (const char *option, const char *options)
MagickExport MagickBooleanType ListCommandOptions (FILE *file, const CommandOption option, ExceptionInfo *magick_unused(exception))
MagickExport ssize_t ParseChannelOption (const char *channels)
MagickExport ssize_t ParseCommandOption (const CommandOption option, const MagickBooleanType list, const char *options)
MagickExport char * RemoveImageOption (ImageInfo *image_info, const char *option)
MagickExport void ResetImageOptions (const ImageInfo *image_info)
MagickExport void ResetImageOptionIterator (const ImageInfo *image_info)
MagickExport MagickBooleanType SetImageOption (ImageInfo *image_info, const char *option, const char *value)
Variables
static const OptionInfo AlignOptions []
static const OptionInfo AlphaOptions []
static const OptionInfo AutoThresholdOptions []
static const OptionInfo BooleanOptions []
static const OptionInfo CacheOptions []
static const OptionInfo ChannelOptions []
static const OptionInfo ClassOptions []
static const OptionInfo ClipPathOptions []
static const OptionInfo ColorspaceOptions []
static const OptionInfo CommandOptions []
static const OptionInfo ComplexOptions []
static const OptionInfo ComplianceOptions []
static const OptionInfo ComposeOptions []
static const OptionInfo CompressOptions []
static const OptionInfo DataTypeOptions []
static const OptionInfo DecorateOptions []
static const OptionInfo DirectionOptions []
static const OptionInfo DisposeOptions []
static const OptionInfo DistortOptions []
static const OptionInfo DitherOptions []
static const OptionInfo EndianOptions []
static const OptionInfo EvaluateOptions []
static const OptionInfo FillRuleOptions []
static const OptionInfo FilterOptions []
static const OptionInfo FunctionOptions []
static const OptionInfo GradientOptions []
static const OptionInfo GravityOptions []
static const OptionInfo IntentOptions []
static const OptionInfo InterlaceOptions []
static const OptionInfo InterpolateOptions []
static const OptionInfo KernelOptions []
static const OptionInfo LayerOptions []
static const OptionInfo LineCapOptions []
static const OptionInfo LineJoinOptions []
static const OptionInfo ListOptions []
static const OptionInfo LogEventOptions []
static const OptionInfo MetricOptions []
static const OptionInfo MethodOptions []
static const OptionInfo ModeOptions []
static const OptionInfo MorphologyOptions []
static const OptionInfo NoiseOptions []
static const OptionInfo OrientationOptions []
static const OptionInfo PolicyDomainOptions []
static const OptionInfo PolicyRightsOptions []
static const OptionInfo PreviewOptions []
static const OptionInfo PrimitiveOptions []
static const OptionInfo QuantumFormatOptions []
static const OptionInfo PixelIntensityOptions []
static const OptionInfo ResolutionOptions []
static const OptionInfo ResourceOptions []
static const OptionInfo SparseColorOptions []
static const OptionInfo StatisticOptions []
static const OptionInfo StorageOptions []
static const OptionInfo StretchOptions []
static const OptionInfo StyleOptions []
static const OptionInfo TypeOptions []
static const OptionInfo ValidateOptions []
static const OptionInfo VirtualPixelOptions []
static const OptionInfo WeightOptions []
Function Documentation
CloneImageOptions()
MagickExport MagickBooleanType CloneImageOptions (ImageInfo * image_info, const ImageInfo * clone_info)
References CloneSplayTree(), ConstantString(), _ImageInfo::debug, DestroyImageOptions(), _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _ImageInfo::options, _ImageInfo::signature, and TraceEvent.
Referenced by CloneImageInfo().
CommandOptionToMnemonic()
MagickExport const char * CommandOptionToMnemonic (const CommandOption option, const ssize_t type)
References GetOptionInfo(), and _OptionInfo::mnemonic.
Referenced by AcquireMagickResource(), AcquireResizeFilter(), ClonePixelCacheRepository(), GenerateCoefficients(), GetColorTuple(), GetMagickProperty(), GetMagickPropertyLetter(), IdentifyImage(), IsRightsAuthorized(), ListPolicyInfo(), ListTypeInfo(), LogMagickEventList(), MorphologyApply(), OpenPixelCache(), OptimizeLayerFrames(), RelinquishMagickResource(), SetResampleFilter(), and ShowKernelInfo().
DefineImageOption()
MagickExport MagickBooleanType DefineImageOption (ImageInfo * image_info, const char * option)
References CopyMagickString(), MaxTextExtent, and SetImageOption().
DeleteImageOption()
MagickExport MagickBooleanType DeleteImageOption (ImageInfo * image_info, const char * option)
References _ImageInfo::debug, DeleteNodeFromSplayTree(), _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ImageInfo::options, _ImageInfo::signature, and TraceEvent.
Referenced by SetImageOption(), and SyncImagesSettings().
DestroyImageOptions()
MagickExport void DestroyImageOptions (ImageInfo * image_info)
References _ImageInfo::debug, DestroySplayTree(), _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ImageInfo::options, _ImageInfo::signature, and TraceEvent.
Referenced by CloneImageOptions(), and DestroyImageInfo().
GetCommandOptionFlags()
MagickExport ssize_t GetCommandOptionFlags (const CommandOption option, const MagickBooleanType list, const char * options)
References CopyMagickString(), _OptionInfo::flags, GetOptionInfo(), LocaleCompare(), MagickFalse, MagickTrue, MaxTextExtent, _OptionInfo::mnemonic, sentinel, and UndefinedOptionFlag.
GetCommandOptions()
MagickExport char ** GetCommandOptions (const CommandOption option)
References AcquireQuantumMemory(), AcquireString(), GetOptionInfo(), _OptionInfo::mnemonic, ResourceLimitFatalError, and ThrowFatalException.
GetImageOption()
MagickExport const char * GetImageOption (const ImageInfo * image_info, const char * key)
References _ImageInfo::debug, _ImageInfo::filename, GetMagickModule, GetValueFromSplayTree(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _ImageInfo::options, _ImageInfo::signature, and TraceEvent.
Referenced by AcquireImage(), AcquireQuantizeInfo(), GetDrawInfo(), GetQuantumInfo(), InterpretImageFilename(), InterpretImageProperties(), ReadImage(), SetStreamBuffering(), SyncImageSettings(), and WriteImage().
GetNextImageOption()
MagickExport char * GetNextImageOption (const ImageInfo * image_info)
References _ImageInfo::debug, _ImageInfo::filename, GetMagickModule, GetNextKeyInSplayTree(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _ImageInfo::options, _ImageInfo::signature, and TraceEvent.
Referenced by InterpretImageProperties(), and SyncImageSettings().
GetOptionInfo()
static const OptionInfo * GetOptionInfo (const CommandOption option) static
References AlignOptions, AlphaOptions, AutoThresholdOptions, BooleanOptions, CacheOptions, ChannelOptions, ClassOptions, ClipPathOptions, ColorspaceOptions, CommandOptions, ComplexOptions, ComplianceOptions, ComposeOptions, CompressOptions, DataTypeOptions, DecorateOptions, DirectionOptions, DisposeOptions, DistortOptions, DitherOptions, EndianOptions, EvaluateOptions, FillRuleOptions, FilterOptions, FunctionOptions, GradientOptions, GravityOptions, IntentOptions, InterlaceOptions, InterpolateOptions, KernelOptions, LayerOptions, LineCapOptions, LineJoinOptions, ListOptions, LogEventOptions, MagickAlignOptions, MagickAlphaOptions, MagickAutoThresholdOptions, MagickBooleanOptions, MagickCacheOptions, MagickChannelOptions, MagickClassOptions, MagickClipPathOptions, MagickColorspaceOptions, MagickCommandOptions, MagickComplexOptions, MagickComplianceOptions, MagickComposeOptions, MagickCompressOptions, MagickDataTypeOptions, MagickDebugOptions, MagickDecorateOptions, MagickDirectionOptions, MagickDisposeOptions, MagickDistortOptions, MagickDitherOptions, MagickEndianOptions, MagickEvaluateOptions, MagickFillRuleOptions, MagickFilterOptions, MagickFunctionOptions, MagickGradientOptions, MagickGravityOptions, MagickIntensityOptions, MagickIntentOptions, MagickInterlaceOptions, MagickInterpolateOptions, MagickKernelOptions, MagickLayerOptions, MagickLineCapOptions, MagickLineJoinOptions, MagickListOptions, MagickLogEventOptions, MagickMethodOptions, MagickMetricOptions, MagickModeOptions, MagickMorphologyOptions, MagickNoiseOptions, MagickOrientationOptions, MagickPixelIntensityOptions, MagickPolicyDomainOptions, MagickPolicyRightsOptions, MagickPreviewOptions, MagickPrimitiveOptions, MagickQuantumFormatOptions, MagickResolutionOptions, MagickResourceOptions, MagickSparseColorOptions, MagickStatisticOptions, MagickStorageOptions, MagickStretchOptions, MagickStyleOptions, MagickTypeOptions, MagickValidateOptions, MagickVirtualPixelOptions, MagickWeightOptions, MethodOptions, MetricOptions, ModeOptions, MorphologyOptions, NoiseOptions, OrientationOptions, PixelIntensityOptions, PolicyDomainOptions, PolicyRightsOptions, PreviewOptions, PrimitiveOptions, QuantumFormatOptions, ResolutionOptions, ResourceOptions, SparseColorOptions, StatisticOptions, StorageOptions, StretchOptions, StyleOptions, TypeOptions, ValidateOptions, VirtualPixelOptions, and WeightOptions.
Referenced by CommandOptionToMnemonic(), GetCommandOptionFlags(), GetCommandOptions(), ListCommandOptions(), and ParseCommandOption().
IsCommandOption()
MagickExport MagickBooleanType IsCommandOption (const char * option)
References MagickFalse, and MagickTrue.
IsOptionMember()
MagickExport MagickBooleanType IsOptionMember (const char * option, const char * options)
References ConstantString(), DestroyString(), GlobExpression(), LocaleCompare(), MagickFalse, MagickTrue, RelinquishMagickMemory(), StringToArgv(), and SubstituteString().
Referenced by ProfileImage().
ListCommandOptions()
MagickExport MagickBooleanType ListCommandOptions (FILE * file, const CommandOption option, ExceptionInfo * magick_unusedexception)
References FormatLocaleFile(), GetOptionInfo(), magick_unreferenced, MagickFalse, MagickTrue, and _OptionInfo::mnemonic.
ParseChannelOption()
MagickExport ssize_t ParseChannelOption (const char * channels)
References BlackChannel, BlueChannel, CyanChannel, GreenChannel, IndexChannel, MagentaChannel, MagickChannelOptions, MagickTrue, OpacityChannel, ParseCommandOption(), RedChannel, and YellowChannel.
ParseCommandOption()
MagickExport ssize_t ParseCommandOption (const CommandOption option, const MagickBooleanType list, const char * options)
References CopyMagickString(), GetOptionInfo(), LocaleCompare(), MagickFalse, MagickTrue, MaxTextExtent, _OptionInfo::mnemonic, sentinel, and _OptionInfo::type.
Referenced by AcquireImage(), AcquireQuantizeInfo(), AcquireResizeFilter(), DrawPatternPath(), ExpandFilenames(), FxChannelStatistics(), GetDrawInfo(), GetImageProperty(), GetPolicyInfo(), GetQuantumInfo(), GradientImage(), IdentifyImage(), LoadLogCache(), LoadMimeCache(), LoadPolicyCache(), LoadTypeCache(), ModulateImage(), MorphologyImageChannel(), ParseChannelOption(), ParseKernelName(), QueryMagickColorCompliance(), ReadImage(), RenderMVGContent(), SetImageProperty(), SetLogEventMask(), and SyncImageSettings().
RemoveImageOption()
MagickExport char * RemoveImageOption (ImageInfo * image_info, const char * option)
References _ImageInfo::debug, _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ImageInfo::options, RemoveNodeFromSplayTree(), _ImageInfo::signature, and TraceEvent.
ResetImageOptionIterator()
MagickExport void ResetImageOptionIterator (const ImageInfo * image_info)
References _ImageInfo::debug, _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ImageInfo::options, ResetSplayTreeIterator(), _ImageInfo::signature, and TraceEvent.
Referenced by InterpretImageProperties(), and SyncImageSettings().
ResetImageOptions()
MagickExport void ResetImageOptions (const ImageInfo * image_info)
References _ImageInfo::debug, _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ImageInfo::options, ResetSplayTree(), _ImageInfo::signature, and TraceEvent.
SetImageOption()
MagickExport MagickBooleanType SetImageOption (ImageInfo * image_info, const char * option, const char * value)
References AddValueToSplayTree(), CloneString(), CompareSplayTreeString(), ConstantString(), _ImageInfo::debug, DeleteImageOption(), _ImageInfo::filename, GetMagickModule, LocaleCompare(), LogMagickEvent(), MagickCoreSignature, MagickFalse, NewSplayTree(), _ImageInfo::options, RelinquishMagickMemory(), _ImageInfo::signature, _ImageInfo::size, and TraceEvent.
Referenced by DefineImageOption(), HoughLineImage(), and SetImageType().
Variable Documentation
AlignOptions
const OptionInfo AlignOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedAlign, UndefinedOptionFlag, MagickTrue },
    { "Center", CenterAlign, UndefinedOptionFlag, MagickFalse },
    { "End", RightAlign, UndefinedOptionFlag, MagickFalse },
    { "Left", LeftAlign, UndefinedOptionFlag, MagickFalse },
    { "Middle", CenterAlign, UndefinedOptionFlag, MagickFalse },
    { "Right", RightAlign, UndefinedOptionFlag, MagickFalse },
    { "Start", LeftAlign, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedAlign, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
AlphaOptions
const OptionInfo AlphaOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedAlphaChannel, UndefinedOptionFlag, MagickTrue },
    { "Activate", ActivateAlphaChannel, UndefinedOptionFlag, MagickFalse },
    { "Associate", AssociateAlphaChannel, UndefinedOptionFlag, MagickFalse },
    { "Background", BackgroundAlphaChannel, UndefinedOptionFlag, MagickFalse },
    { "Copy", CopyAlphaChannel, UndefinedOptionFlag, MagickFalse },
    { "Deactivate", DeactivateAlphaChannel, UndefinedOptionFlag, MagickFalse },
    { "Disassociate", DisassociateAlphaChannel, UndefinedOptionFlag, MagickFalse },
    { "Extract", ExtractAlphaChannel, UndefinedOptionFlag, MagickFalse },
    { "Flatten", FlattenAlphaChannel, UndefinedOptionFlag, MagickFalse },
    { "Off", DeactivateAlphaChannel, UndefinedOptionFlag, MagickFalse },
    { "On", ActivateAlphaChannel, UndefinedOptionFlag, MagickFalse },
    { "Opaque", OpaqueAlphaChannel, UndefinedOptionFlag, MagickFalse },
    { "Remove", RemoveAlphaChannel, UndefinedOptionFlag, MagickFalse },
    { "Set", SetAlphaChannel, UndefinedOptionFlag, MagickFalse },
    { "Shape", ShapeAlphaChannel, UndefinedOptionFlag, MagickFalse },
    { "Reset", SetAlphaChannel, DeprecateOptionFlag, MagickTrue },
    { "Transparent", TransparentAlphaChannel, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedAlphaChannel, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
AutoThresholdOptions
const OptionInfo AutoThresholdOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedThresholdMethod, UndefinedOptionFlag, MagickTrue },
    { "Kapur", KapurThresholdMethod, UndefinedOptionFlag, MagickFalse },
    { "OTSU", OTSUThresholdMethod, UndefinedOptionFlag, MagickFalse },
    { "Triangle", TriangleThresholdMethod, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedThresholdMethod, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
BooleanOptions
const OptionInfo BooleanOptions[] static
Initial value:
=
  {
    { "False", 0L, UndefinedOptionFlag, MagickFalse },
    { "True", 1L, UndefinedOptionFlag, MagickFalse },
    { "0", 0L, UndefinedOptionFlag, MagickFalse },
    { "1", 1L, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, 0L, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
CacheOptions
const OptionInfo CacheOptions[] static
Initial value:
=
  {
    { "Disk", DiskCache, UndefinedOptionFlag, MagickFalse },
    { "Distributed", DistributedCache, UndefinedOptionFlag, MagickFalse },
    { "Map", MapCache, UndefinedOptionFlag, MagickFalse },
    { "Memory", MemoryCache, UndefinedOptionFlag, MagickFalse },
    { "Ping", PingCache, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, MagickFalse, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
ChannelOptions
const OptionInfo ChannelOptions[] static
Referenced by GetOptionInfo().
ClassOptions
const OptionInfo ClassOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedClass, UndefinedOptionFlag, MagickTrue },
    { "DirectClass", DirectClass, UndefinedOptionFlag, MagickFalse },
    { "PseudoClass", PseudoClass, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedClass, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
ClipPathOptions
const OptionInfo ClipPathOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedPathUnits, UndefinedOptionFlag, MagickTrue },
    { "ObjectBoundingBox", ObjectBoundingBox, UndefinedOptionFlag, MagickFalse },
    { "UserSpace", UserSpace, UndefinedOptionFlag, MagickFalse },
    { "UserSpaceOnUse", UserSpaceOnUse, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedPathUnits, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
ColorspaceOptions
const OptionInfo ColorspaceOptions[] static
Referenced by GetOptionInfo().
CommandOptions
const OptionInfo CommandOptions[] static
Referenced by GetOptionInfo().
ComplexOptions
const OptionInfo ComplexOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedComplexOperator, UndefinedOptionFlag, MagickTrue },
    { "Add", AddComplexOperator, UndefinedOptionFlag, MagickFalse },
    { "Conjugate", ConjugateComplexOperator, UndefinedOptionFlag, MagickFalse },
    { "Divide", DivideComplexOperator, UndefinedOptionFlag, MagickFalse },
    { "MagnitudePhase", MagnitudePhaseComplexOperator, UndefinedOptionFlag, MagickFalse },
    { "Multiply", MultiplyComplexOperator, UndefinedOptionFlag, MagickFalse },
    { "RealImaginary", RealImaginaryComplexOperator, UndefinedOptionFlag, MagickFalse },
    { "Subtract", SubtractComplexOperator, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedComplexOperator, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
ComplianceOptions
const OptionInfo ComplianceOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedCompliance, UndefinedOptionFlag, MagickTrue },
    { "CSS", CSSCompliance, UndefinedOptionFlag, MagickFalse },
    { "No", NoCompliance, UndefinedOptionFlag, MagickFalse },
    { "MVG", MVGCompliance, UndefinedOptionFlag, MagickFalse },
    { "SVG", SVGCompliance, UndefinedOptionFlag, MagickFalse },
    { "X11", X11Compliance, UndefinedOptionFlag, MagickFalse },
    { "XPM", XPMCompliance, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedClass, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
ComposeOptions
const OptionInfo ComposeOptions[] static
Referenced by GetOptionInfo().
CompressOptions
const OptionInfo CompressOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedCompression, UndefinedOptionFlag, MagickTrue },
    { "B44A", B44ACompression, UndefinedOptionFlag, MagickFalse },
    { "B44", B44Compression, UndefinedOptionFlag, MagickFalse },
    { "BZip", BZipCompression, UndefinedOptionFlag, MagickFalse },
    { "DXT1", DXT1Compression, UndefinedOptionFlag, MagickFalse },
    { "DXT3", DXT3Compression, UndefinedOptionFlag, MagickFalse },
    { "DXT5", DXT5Compression, UndefinedOptionFlag, MagickFalse },
    { "Fax", FaxCompression, UndefinedOptionFlag, MagickFalse },
    { "Group4", Group4Compression, UndefinedOptionFlag, MagickFalse },
    { "JBIG1", JBIG1Compression, UndefinedOptionFlag, MagickFalse },
    { "JBIG2", JBIG2Compression, UndefinedOptionFlag, MagickFalse },
    { "JPEG2000", JPEG2000Compression, UndefinedOptionFlag, MagickFalse },
    { "JPEG", JPEGCompression, UndefinedOptionFlag, MagickFalse },
    { "LosslessJPEG", LosslessJPEGCompression, UndefinedOptionFlag, MagickFalse },
    { "Lossless", LosslessJPEGCompression, UndefinedOptionFlag, MagickFalse },
    { "LZMA", LZMACompression, UndefinedOptionFlag, MagickFalse },
    { "LZW", LZWCompression, UndefinedOptionFlag, MagickFalse },
    { "None", NoCompression, UndefinedOptionFlag, MagickFalse },
    { "Piz", PizCompression, UndefinedOptionFlag, MagickFalse },
    { "Pxr24", Pxr24Compression, UndefinedOptionFlag, MagickFalse },
    { "RLE", RLECompression, UndefinedOptionFlag, MagickFalse },
    { "RunlengthEncoded", RLECompression, UndefinedOptionFlag, MagickFalse },
    { "WebP", WebPCompression, UndefinedOptionFlag, MagickFalse },
    { "ZipS", ZipSCompression, UndefinedOptionFlag, MagickFalse },
    { "Zip", ZipCompression, UndefinedOptionFlag, MagickFalse },
    { "Zstd", ZstdCompression, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedCompression, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
DataTypeOptions
const OptionInfo DataTypeOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedData, UndefinedOptionFlag, MagickTrue },
    { "Byte", ByteData, UndefinedOptionFlag, MagickFalse },
    { "Long", LongData, UndefinedOptionFlag, MagickFalse },
    { "Short", ShortData, UndefinedOptionFlag, MagickFalse },
    { "String", StringData, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedData, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
DecorateOptions
const OptionInfo DecorateOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedDecoration, UndefinedOptionFlag, MagickTrue },
    { "LineThrough", LineThroughDecoration, UndefinedOptionFlag, MagickFalse },
    { "None", NoDecoration, UndefinedOptionFlag, MagickFalse },
    { "Overline", OverlineDecoration, UndefinedOptionFlag, MagickFalse },
    { "Underline", UnderlineDecoration, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedDecoration, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
DirectionOptions
const OptionInfo DirectionOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedDirection, UndefinedOptionFlag, MagickTrue },
    { "right-to-left", RightToLeftDirection, UndefinedOptionFlag, MagickFalse },
    { "left-to-right", LeftToRightDirection, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedDirection, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
DisposeOptions
const OptionInfo DisposeOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedDispose, UndefinedOptionFlag, MagickFalse },
    { "Background", BackgroundDispose, UndefinedOptionFlag, MagickFalse },
    { "None", NoneDispose, UndefinedOptionFlag, MagickFalse },
    { "Previous", PreviousDispose, UndefinedOptionFlag, MagickFalse },
    { "0", UndefinedDispose, UndefinedOptionFlag, MagickFalse },
    { "1", NoneDispose, UndefinedOptionFlag, MagickFalse },
    { "2", BackgroundDispose, UndefinedOptionFlag, MagickFalse },
    { "3", PreviousDispose, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedDispose, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
DistortOptions
const OptionInfo DistortOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedDistortion, UndefinedOptionFlag, MagickTrue },
    { "Affine", AffineDistortion, UndefinedOptionFlag, MagickFalse },
    { "AffineProjection", AffineProjectionDistortion, UndefinedOptionFlag, MagickFalse },
    { "ScaleRotateTranslate", ScaleRotateTranslateDistortion, UndefinedOptionFlag, MagickFalse },
    { "SRT", ScaleRotateTranslateDistortion, UndefinedOptionFlag, MagickFalse },
    { "Perspective", PerspectiveDistortion, UndefinedOptionFlag, MagickFalse },
    { "PerspectiveProjection", PerspectiveProjectionDistortion, UndefinedOptionFlag, MagickFalse },
    { "Bilinear", BilinearForwardDistortion, UndefinedOptionFlag, MagickTrue },
    { "BilinearForward", BilinearForwardDistortion, UndefinedOptionFlag, MagickFalse },
    { "BilinearReverse", BilinearReverseDistortion, UndefinedOptionFlag, MagickFalse },
    { "Polynomial", PolynomialDistortion, UndefinedOptionFlag, MagickFalse },
    { "Arc", ArcDistortion, UndefinedOptionFlag, MagickFalse },
    { "Polar", PolarDistortion, UndefinedOptionFlag, MagickFalse },
    { "DePolar", DePolarDistortion, UndefinedOptionFlag, MagickFalse },
    { "Barrel", BarrelDistortion, UndefinedOptionFlag, MagickFalse },
    { "Cylinder2Plane", Cylinder2PlaneDistortion, UndefinedOptionFlag, MagickTrue },
    { "Plane2Cylinder", Plane2CylinderDistortion, UndefinedOptionFlag, MagickTrue },
    { "BarrelInverse", BarrelInverseDistortion, UndefinedOptionFlag, MagickFalse },
    { "Shepards", ShepardsDistortion, UndefinedOptionFlag, MagickFalse },
    { "Resize", ResizeDistortion, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedDistortion, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
DitherOptions
const OptionInfo DitherOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedDitherMethod, UndefinedOptionFlag, MagickTrue },
    { "None", NoDitherMethod, UndefinedOptionFlag, MagickFalse },
    { "FloydSteinberg", FloydSteinbergDitherMethod, UndefinedOptionFlag, MagickFalse },
    { "Riemersma", RiemersmaDitherMethod, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedEndian, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
EndianOptions
const OptionInfo EndianOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedEndian, UndefinedOptionFlag, MagickTrue },
    { "LSB", LSBEndian, UndefinedOptionFlag, MagickFalse },
    { "MSB", MSBEndian, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedEndian, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
EvaluateOptions
const OptionInfo EvaluateOptions[] static
Referenced by GetOptionInfo().
FillRuleOptions
const OptionInfo FillRuleOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedRule, UndefinedOptionFlag, MagickTrue },
    { "Evenodd", EvenOddRule, UndefinedOptionFlag, MagickFalse },
    { "NonZero", NonZeroRule, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedRule, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
FilterOptions
const OptionInfo FilterOptions[] static
Referenced by GetOptionInfo().
FunctionOptions
const OptionInfo FunctionOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedFunction, UndefinedOptionFlag, MagickTrue },
    { "Polynomial", PolynomialFunction, UndefinedOptionFlag, MagickFalse },
    { "Sinusoid", SinusoidFunction, UndefinedOptionFlag, MagickFalse },
    { "ArcSin", ArcsinFunction, UndefinedOptionFlag, MagickFalse },
    { "ArcTan", ArctanFunction, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedFunction, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
GradientOptions
const OptionInfo GradientOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedGradient, UndefinedOptionFlag, MagickTrue },
    { "Linear", LinearGradient, UndefinedOptionFlag, MagickFalse },
    { "Radial", RadialGradient, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedRule, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
GravityOptions
const OptionInfo GravityOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedGravity, UndefinedOptionFlag, MagickTrue },
    { "None", UndefinedGravity, UndefinedOptionFlag, MagickFalse },
    { "Center", CenterGravity, UndefinedOptionFlag, MagickFalse },
    { "East", EastGravity, UndefinedOptionFlag, MagickFalse },
    { "Forget", ForgetGravity, UndefinedOptionFlag, MagickFalse },
    { "NorthEast", NorthEastGravity, UndefinedOptionFlag, MagickFalse },
    { "North", NorthGravity, UndefinedOptionFlag, MagickFalse },
    { "NorthWest", NorthWestGravity, UndefinedOptionFlag, MagickFalse },
    { "SouthEast", SouthEastGravity, UndefinedOptionFlag, MagickFalse },
    { "South", SouthGravity, UndefinedOptionFlag, MagickFalse },
    { "SouthWest", SouthWestGravity, UndefinedOptionFlag, MagickFalse },
    { "West", WestGravity, UndefinedOptionFlag, MagickFalse },
    { "Static", StaticGravity, UndefinedOptionFlag, MagickTrue },
    { (char *) NULL, UndefinedGravity, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
IntentOptions
const OptionInfo IntentOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedIntent, UndefinedOptionFlag, MagickTrue },
    { "Absolute", AbsoluteIntent, UndefinedOptionFlag, MagickFalse },
    { "Perceptual", PerceptualIntent, UndefinedOptionFlag, MagickFalse },
    { "Relative", RelativeIntent, UndefinedOptionFlag, MagickFalse },
    { "Saturation", SaturationIntent, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedIntent, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
InterlaceOptions
const OptionInfo InterlaceOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedInterlace, UndefinedOptionFlag, MagickTrue },
    { "Line", LineInterlace, UndefinedOptionFlag, MagickFalse },
    { "None", NoInterlace, UndefinedOptionFlag, MagickFalse },
    { "Plane", PlaneInterlace, UndefinedOptionFlag, MagickFalse },
    { "Partition", PartitionInterlace, UndefinedOptionFlag, MagickFalse },
    { "GIF", GIFInterlace, UndefinedOptionFlag, MagickFalse },
    { "JPEG", JPEGInterlace, UndefinedOptionFlag, MagickFalse },
    { "PNG", PNGInterlace, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedInterlace, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
InterpolateOptions
const OptionInfo InterpolateOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedInterpolatePixel, UndefinedOptionFlag, MagickTrue },
    { "Average", AverageInterpolatePixel, UndefinedOptionFlag, MagickFalse },
    { "Average4", AverageInterpolatePixel, UndefinedOptionFlag, MagickFalse },
    { "Average9", Average9InterpolatePixel, UndefinedOptionFlag, MagickFalse },
    { "Average16", Average16InterpolatePixel, UndefinedOptionFlag, MagickFalse },
    { "Background", BackgroundInterpolatePixel, UndefinedOptionFlag, MagickFalse },
    { "Bicubic", CatromInterpolatePixel, UndefinedOptionFlag, MagickTrue },
    { "Bilinear", BilinearInterpolatePixel, UndefinedOptionFlag, MagickFalse },
    { "Blend", BlendInterpolatePixel, UndefinedOptionFlag, MagickFalse },
    { "Catrom", CatromInterpolatePixel, UndefinedOptionFlag, MagickFalse },
    { "Integer", IntegerInterpolatePixel, UndefinedOptionFlag, MagickFalse },
    { "Mesh", MeshInterpolatePixel, UndefinedOptionFlag, MagickFalse },
    { "Nearest", NearestNeighborInterpolatePixel, UndefinedOptionFlag, MagickFalse },
    { "NearestNeighbor", NearestNeighborInterpolatePixel, UndefinedOptionFlag, MagickTrue },
    { "Spline", SplineInterpolatePixel, UndefinedOptionFlag, MagickFalse },
    { "Filter", FilterInterpolatePixel, UndefinedOptionFlag, MagickTrue },
    { (char *) NULL, UndefinedInterpolatePixel, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
KernelOptions
const OptionInfo KernelOptions[] static
Referenced by GetOptionInfo().
LayerOptions
const OptionInfo LayerOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedLayer, UndefinedOptionFlag, MagickTrue },
    { "Coalesce", CoalesceLayer, UndefinedOptionFlag, MagickFalse },
    { "CompareAny", CompareAnyLayer, UndefinedOptionFlag, MagickFalse },
    { "CompareClear", CompareClearLayer, UndefinedOptionFlag, MagickFalse },
    { "CompareOverlay", CompareOverlayLayer, UndefinedOptionFlag, MagickFalse },
    { "Dispose", DisposeLayer, UndefinedOptionFlag, MagickFalse },
    { "Optimize", OptimizeLayer, UndefinedOptionFlag, MagickFalse },
    { "OptimizeFrame", OptimizeImageLayer, UndefinedOptionFlag, MagickFalse },
    { "OptimizePlus", OptimizePlusLayer, UndefinedOptionFlag, MagickFalse },
    { "OptimizeTransparency", OptimizeTransLayer, UndefinedOptionFlag, MagickFalse },
    { "RemoveDups", RemoveDupsLayer, UndefinedOptionFlag, MagickFalse },
    { "RemoveZero", RemoveZeroLayer, UndefinedOptionFlag, MagickFalse },
    { "Composite", CompositeLayer, UndefinedOptionFlag, MagickFalse },
    { "Merge", MergeLayer, UndefinedOptionFlag, MagickFalse },
    { "Flatten", FlattenLayer, UndefinedOptionFlag, MagickFalse },
    { "Mosaic", MosaicLayer, UndefinedOptionFlag, MagickFalse },
    { "TrimBounds", TrimBoundsLayer, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedLayer, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
LineCapOptions
const OptionInfo LineCapOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedCap, UndefinedOptionFlag, MagickTrue },
    { "Butt", ButtCap, UndefinedOptionFlag, MagickFalse },
    { "Round", RoundCap, UndefinedOptionFlag, MagickFalse },
    { "Square", SquareCap, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedCap, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
LineJoinOptions
const OptionInfo LineJoinOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedJoin, UndefinedOptionFlag, MagickTrue },
    { "Bevel", BevelJoin, UndefinedOptionFlag, MagickFalse },
    { "Miter", MiterJoin, UndefinedOptionFlag, MagickFalse },
    { "Round", RoundJoin, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedJoin, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
ListOptions
const OptionInfo ListOptions[] static
Referenced by GetOptionInfo().
LogEventOptions
const OptionInfo LogEventOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedEvents, UndefinedOptionFlag, MagickTrue },
    { "All", (AllEvents &~ TraceEvent), UndefinedOptionFlag, MagickFalse },
    { "Annotate", AnnotateEvent, UndefinedOptionFlag, MagickFalse },
    { "Accelerate", AccelerateEvent, UndefinedOptionFlag, MagickFalse },
    { "Blob", BlobEvent, UndefinedOptionFlag, MagickFalse },
    { "Cache", CacheEvent, UndefinedOptionFlag, MagickFalse },
    { "Coder", CoderEvent, UndefinedOptionFlag, MagickFalse },
    { "Configure", ConfigureEvent, UndefinedOptionFlag, MagickFalse },
    { "Deprecate", DeprecateEvent, UndefinedOptionFlag, MagickFalse },
    { "Draw", DrawEvent, UndefinedOptionFlag, MagickFalse },
    { "Exception", ExceptionEvent, UndefinedOptionFlag, MagickFalse },
    { "Locale", LocaleEvent, UndefinedOptionFlag, MagickFalse },
    { "Module", ModuleEvent, UndefinedOptionFlag, MagickFalse },
    { "None", NoEvents, UndefinedOptionFlag, MagickFalse },
    { "Policy", PolicyEvent, UndefinedOptionFlag, MagickFalse },
    { "Resource", ResourceEvent, UndefinedOptionFlag, MagickFalse },
    { "Trace", TraceEvent, UndefinedOptionFlag, MagickFalse },
    { "Transform", TransformEvent, UndefinedOptionFlag, MagickFalse },
    { "User", UserEvent, UndefinedOptionFlag, MagickFalse },
    { "Wand", WandEvent, UndefinedOptionFlag, MagickFalse },
    { "X11", X11Event, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedEvents, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
MethodOptions
const OptionInfo MethodOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedMethod, UndefinedOptionFlag, MagickTrue },
    { "FillToBorder", FillToBorderMethod, UndefinedOptionFlag, MagickFalse },
    { "Floodfill", FloodfillMethod, UndefinedOptionFlag, MagickFalse },
    { "Point", PointMethod, UndefinedOptionFlag, MagickFalse },
    { "Replace", ReplaceMethod, UndefinedOptionFlag, MagickFalse },
    { "Reset", ResetMethod, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedMethod, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
MetricOptions
const OptionInfo MetricOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedErrorMetric, UndefinedOptionFlag, MagickTrue },
    { "AE", AbsoluteErrorMetric, UndefinedOptionFlag, MagickFalse },
    { "Fuzz", FuzzErrorMetric, UndefinedOptionFlag, MagickFalse },
    { "MAE", MeanAbsoluteErrorMetric, UndefinedOptionFlag, MagickFalse },
    { "MEPP", MeanErrorPerPixelMetric, UndefinedOptionFlag, MagickFalse },
    { "MSE", MeanSquaredErrorMetric, UndefinedOptionFlag, MagickFalse },
    { "NCC", NormalizedCrossCorrelationErrorMetric, UndefinedOptionFlag, MagickFalse },
    { "PAE", PeakAbsoluteErrorMetric, UndefinedOptionFlag, MagickFalse },
    { "PHASH", PerceptualHashErrorMetric, UndefinedOptionFlag, MagickFalse },
    { "PSNR", PeakSignalToNoiseRatioMetric, UndefinedOptionFlag, MagickFalse },
    { "RMSE", RootMeanSquaredErrorMetric, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedErrorMetric, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
ModeOptions
const OptionInfo ModeOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedMode, UndefinedOptionFlag, MagickTrue },
    { "Concatenate", ConcatenateMode, UndefinedOptionFlag, MagickFalse },
    { "Frame", FrameMode, UndefinedOptionFlag, MagickFalse },
    { "Unframe", UnframeMode, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedMode, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
MorphologyOptions
const OptionInfo MorphologyOptions[] static
Referenced by GetOptionInfo().
NoiseOptions
const OptionInfo NoiseOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedNoise, UndefinedOptionFlag, MagickTrue },
    { "Gaussian", GaussianNoise, UndefinedOptionFlag, MagickFalse },
    { "Impulse", ImpulseNoise, UndefinedOptionFlag, MagickFalse },
    { "Laplacian", LaplacianNoise, UndefinedOptionFlag, MagickFalse },
    { "Multiplicative", MultiplicativeGaussianNoise, UndefinedOptionFlag, MagickFalse },
    { "Poisson", PoissonNoise, UndefinedOptionFlag, MagickFalse },
    { "Random", RandomNoise, UndefinedOptionFlag, MagickFalse },
    { "Uniform", UniformNoise, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedNoise, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
OrientationOptions
const OptionInfo OrientationOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedOrientation, UndefinedOptionFlag, MagickTrue },
    { "TopLeft", TopLeftOrientation, UndefinedOptionFlag, MagickFalse },
    { "TopRight", TopRightOrientation, UndefinedOptionFlag, MagickFalse },
    { "BottomRight", BottomRightOrientation, UndefinedOptionFlag, MagickFalse },
    { "BottomLeft", BottomLeftOrientation, UndefinedOptionFlag, MagickFalse },
    { "LeftTop", LeftTopOrientation, UndefinedOptionFlag, MagickFalse },
    { "RightTop", RightTopOrientation, UndefinedOptionFlag, MagickFalse },
    { "RightBottom", RightBottomOrientation, UndefinedOptionFlag, MagickFalse },
    { "LeftBottom", LeftBottomOrientation, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedOrientation, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
PixelIntensityOptions
const OptionInfo PixelIntensityOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedPixelIntensityMethod, UndefinedOptionFlag, MagickTrue },
    { "Average", AveragePixelIntensityMethod, UndefinedOptionFlag, MagickFalse },
    { "Brightness", BrightnessPixelIntensityMethod, UndefinedOptionFlag, MagickFalse },
    { "Lightness", LightnessPixelIntensityMethod, UndefinedOptionFlag, MagickFalse },
    { "Mean", AveragePixelIntensityMethod, UndefinedOptionFlag, MagickFalse },
    { "MS", MSPixelIntensityMethod, UndefinedOptionFlag, MagickFalse },
    { "Rec601Luma", Rec601LumaPixelIntensityMethod, UndefinedOptionFlag, MagickFalse },
    { "Rec601Luminance", Rec601LuminancePixelIntensityMethod, UndefinedOptionFlag, MagickFalse },
    { "Rec709Luma", Rec709LumaPixelIntensityMethod, UndefinedOptionFlag, MagickFalse },
    { "Rec709Luminance", Rec709LuminancePixelIntensityMethod, UndefinedOptionFlag, MagickFalse },
    { "RMS", RMSPixelIntensityMethod, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedPixelIntensityMethod, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
PolicyDomainOptions
const OptionInfo PolicyDomainOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedPolicyDomain, UndefinedOptionFlag, MagickTrue },
    { "Cache", CachePolicyDomain, UndefinedOptionFlag, MagickFalse },
    { "Coder", CoderPolicyDomain, UndefinedOptionFlag, MagickFalse },
    { "Delegate", DelegatePolicyDomain, UndefinedOptionFlag, MagickFalse },
    { "Filter", FilterPolicyDomain, UndefinedOptionFlag, MagickFalse },
    { "Module", ModulePolicyDomain, UndefinedOptionFlag, MagickFalse },
    { "Path", PathPolicyDomain, UndefinedOptionFlag, MagickFalse },
    { "Resource", ResourcePolicyDomain, UndefinedOptionFlag, MagickFalse },
    { "System", SystemPolicyDomain, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedPolicyDomain, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
PolicyRightsOptions
const OptionInfo PolicyRightsOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedPolicyRights, UndefinedOptionFlag, MagickTrue },
    { "All", AllPolicyRights, UndefinedOptionFlag, MagickFalse },
    { "Execute", ExecutePolicyRights, UndefinedOptionFlag, MagickFalse },
    { "None", NoPolicyRights, UndefinedOptionFlag, MagickFalse },
    { "Read", ReadPolicyRights, UndefinedOptionFlag, MagickFalse },
    { "Write", WritePolicyRights, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedPolicyRights, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
PreviewOptions
const OptionInfo PreviewOptions[] static
Referenced by GetOptionInfo().
PrimitiveOptions
const OptionInfo PrimitiveOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedPrimitive, UndefinedOptionFlag, MagickTrue },
    { "Arc", ArcPrimitive, UndefinedOptionFlag, MagickFalse },
    { "Bezier", BezierPrimitive, UndefinedOptionFlag, MagickFalse },
    { "Circle", CirclePrimitive, UndefinedOptionFlag, MagickFalse },
    { "Color", ColorPrimitive, UndefinedOptionFlag, MagickFalse },
    { "Ellipse", EllipsePrimitive, UndefinedOptionFlag, MagickFalse },
    { "Image", ImagePrimitive, UndefinedOptionFlag, MagickFalse },
    { "Line", LinePrimitive, UndefinedOptionFlag, MagickFalse },
    { "Matte", MattePrimitive, UndefinedOptionFlag, MagickFalse },
    { "Path", PathPrimitive, UndefinedOptionFlag, MagickFalse },
    { "Point", PointPrimitive, UndefinedOptionFlag, MagickFalse },
    { "Polygon", PolygonPrimitive, UndefinedOptionFlag, MagickFalse },
    { "Polyline", PolylinePrimitive, UndefinedOptionFlag, MagickFalse },
    { "Rectangle", RectanglePrimitive, UndefinedOptionFlag, MagickFalse },
    { "RoundRectangle", RoundRectanglePrimitive, UndefinedOptionFlag, MagickFalse },
    { "Text", TextPrimitive, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedPrimitive, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
QuantumFormatOptions
const OptionInfo QuantumFormatOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedQuantumFormat, UndefinedOptionFlag, MagickTrue },
    { "FloatingPoint", FloatingPointQuantumFormat, UndefinedOptionFlag, MagickFalse },
    { "Signed", SignedQuantumFormat, UndefinedOptionFlag, MagickFalse },
    { "Unsigned", UnsignedQuantumFormat, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, FloatingPointQuantumFormat, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
ResolutionOptions
const OptionInfo ResolutionOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedResolution, UndefinedOptionFlag, MagickTrue },
    { "PixelsPerInch", PixelsPerInchResolution, UndefinedOptionFlag, MagickFalse },
    { "PixelsPerCentimeter", PixelsPerCentimeterResolution, UndefinedOptionFlag, MagickFalse },
    { "1", UndefinedResolution, UndefinedOptionFlag, MagickFalse },
    { "2", PixelsPerInchResolution, UndefinedOptionFlag, MagickFalse },
    { "3", PixelsPerCentimeterResolution, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedResolution, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
ResourceOptions
const OptionInfo ResourceOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedResource, UndefinedOptionFlag, MagickTrue },
    { "Area", AreaResource, UndefinedOptionFlag, MagickFalse },
    { "Disk", DiskResource, UndefinedOptionFlag, MagickFalse },
    { "File", FileResource, UndefinedOptionFlag, MagickFalse },
    { "Height", HeightResource, UndefinedOptionFlag, MagickFalse },
    { "Map", MapResource, UndefinedOptionFlag, MagickFalse },
    { "Memory", MemoryResource, UndefinedOptionFlag, MagickFalse },
    { "Thread", ThreadResource, UndefinedOptionFlag, MagickFalse },
    { "Throttle", ThrottleResource, UndefinedOptionFlag, MagickFalse },
    { "Time", TimeResource, UndefinedOptionFlag, MagickFalse },
    { "Width", WidthResource, UndefinedOptionFlag, MagickFalse },
    { "ListLength", ListLengthResource, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedResource, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
SparseColorOptions
const OptionInfo SparseColorOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedDistortion, UndefinedOptionFlag, MagickTrue },
    { "Barycentric", BarycentricColorInterpolate, UndefinedOptionFlag, MagickFalse },
    { "Bilinear", BilinearColorInterpolate, UndefinedOptionFlag, MagickFalse },
    { "Inverse", InverseColorInterpolate, UndefinedOptionFlag, MagickFalse },
    { "Shepards", ShepardsColorInterpolate, UndefinedOptionFlag, MagickFalse },
    { "Voronoi", VoronoiColorInterpolate, UndefinedOptionFlag, MagickFalse },
    { "Manhattan", ManhattanColorInterpolate, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedResource, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
StatisticOptions
const OptionInfo StatisticOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedStatistic, UndefinedOptionFlag, MagickTrue },
    { "Gradient", GradientStatistic, UndefinedOptionFlag, MagickFalse },
    { "Maximum", MaximumStatistic, UndefinedOptionFlag, MagickFalse },
    { "Mean", MeanStatistic, UndefinedOptionFlag, MagickFalse },
    { "Median", MedianStatistic, UndefinedOptionFlag, MagickFalse },
    { "Minimum", MinimumStatistic, UndefinedOptionFlag, MagickFalse },
    { "Mode", ModeStatistic, UndefinedOptionFlag, MagickFalse },
    { "Nonpeak", NonpeakStatistic, UndefinedOptionFlag, MagickFalse },
    { "RMS", RootMeanSquareStatistic, UndefinedOptionFlag, MagickFalse },
    { "RootMeanSquare", RootMeanSquareStatistic, UndefinedOptionFlag, MagickFalse },
    { "StandardDeviation", StandardDeviationStatistic, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedMethod, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
StorageOptions
const OptionInfo StorageOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedPixel, UndefinedOptionFlag, MagickTrue },
    { "Char", CharPixel, UndefinedOptionFlag, MagickFalse },
    { "Double", DoublePixel, UndefinedOptionFlag, MagickFalse },
    { "Float", FloatPixel, UndefinedOptionFlag, MagickFalse },
    { "Integer", IntegerPixel, UndefinedOptionFlag, MagickFalse },
    { "Long", LongPixel, UndefinedOptionFlag, MagickFalse },
    { "Quantum", QuantumPixel, UndefinedOptionFlag, MagickFalse },
    { "Short", ShortPixel, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedResource, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
StretchOptions
const OptionInfo StretchOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedStretch, UndefinedOptionFlag, MagickTrue },
    { "Any", AnyStretch, UndefinedOptionFlag, MagickFalse },
    { "Condensed", CondensedStretch, UndefinedOptionFlag, MagickFalse },
    { "Expanded", ExpandedStretch, UndefinedOptionFlag, MagickFalse },
    { "ExtraCondensed", ExtraCondensedStretch, UndefinedOptionFlag, MagickFalse },
    { "ExtraExpanded", ExtraExpandedStretch, UndefinedOptionFlag, MagickFalse },
    { "Normal", NormalStretch, UndefinedOptionFlag, MagickFalse },
    { "SemiCondensed", SemiCondensedStretch, UndefinedOptionFlag, MagickFalse },
    { "SemiExpanded", SemiExpandedStretch, UndefinedOptionFlag, MagickFalse },
    { "UltraCondensed", UltraCondensedStretch, UndefinedOptionFlag, MagickFalse },
    { "UltraExpanded", UltraExpandedStretch, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedStretch, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
StyleOptions
const OptionInfo StyleOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedStyle, UndefinedOptionFlag, MagickTrue },
    { "Any", AnyStyle, UndefinedOptionFlag, MagickFalse },
    { "Italic", ItalicStyle, UndefinedOptionFlag, MagickFalse },
    { "Normal", NormalStyle, UndefinedOptionFlag, MagickFalse },
    { "Oblique", ObliqueStyle, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedStyle, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
TypeOptions
const OptionInfo TypeOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedType, UndefinedOptionFlag, MagickTrue },
    { "Bilevel", BilevelType, UndefinedOptionFlag, MagickFalse },
    { "ColorSeparation", ColorSeparationType, UndefinedOptionFlag, MagickFalse },
    { "ColorSeparationAlpha", ColorSeparationMatteType, UndefinedOptionFlag, MagickFalse },
    { "ColorSeparationMatte", ColorSeparationMatteType, UndefinedOptionFlag, MagickFalse },
    { "Grayscale", GrayscaleType, UndefinedOptionFlag, MagickFalse },
    { "GrayscaleAlpha", GrayscaleMatteType, UndefinedOptionFlag, MagickFalse },
    { "GrayscaleMatte", GrayscaleMatteType, UndefinedOptionFlag, MagickFalse },
    { "Optimize", OptimizeType, UndefinedOptionFlag, MagickFalse },
    { "Palette", PaletteType, UndefinedOptionFlag, MagickFalse },
    { "PaletteBilevelAlpha", PaletteBilevelMatteType, UndefinedOptionFlag, MagickFalse },
    { "PaletteBilevelMatte", PaletteBilevelMatteType, UndefinedOptionFlag, MagickFalse },
    { "PaletteAlpha", PaletteMatteType, UndefinedOptionFlag, MagickFalse },
    { "PaletteMatte", PaletteMatteType, UndefinedOptionFlag, MagickFalse },
    { "TrueColorAlpha", TrueColorMatteType, UndefinedOptionFlag, MagickFalse },
    { "TrueColorMatte", TrueColorMatteType, UndefinedOptionFlag, MagickFalse },
    { "TrueColor", TrueColorType, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedType, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
ValidateOptions
const OptionInfo ValidateOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedValidate, UndefinedOptionFlag, MagickTrue },
    { "All", AllValidate, UndefinedOptionFlag, MagickFalse },
    { "Colorspace", ColorspaceValidate, UndefinedOptionFlag, MagickFalse },
    { "Compare", CompareValidate, UndefinedOptionFlag, MagickFalse },
    { "Composite", CompositeValidate, UndefinedOptionFlag, MagickFalse },
    { "Convert", ConvertValidate, UndefinedOptionFlag, MagickFalse },
    { "FormatsDisk", FormatsDiskValidate, UndefinedOptionFlag, MagickFalse },
    { "FormatsMap", FormatsMapValidate, UndefinedOptionFlag, MagickFalse },
    { "FormatsMemory", FormatsMemoryValidate, UndefinedOptionFlag, MagickFalse },
    { "Identify", IdentifyValidate, UndefinedOptionFlag, MagickFalse },
    { "ImportExport", ImportExportValidate, UndefinedOptionFlag, MagickFalse },
    { "Montage", MontageValidate, UndefinedOptionFlag, MagickFalse },
    { "None", NoValidate, UndefinedOptionFlag, MagickFalse },
    { "Stream", StreamValidate, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedValidate, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
VirtualPixelOptions
const OptionInfo VirtualPixelOptions[] static
Initial value:
=
  {
    { "Undefined", UndefinedVirtualPixelMethod, UndefinedOptionFlag, MagickTrue },
    { "Background", BackgroundVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { "Black", BlackVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { "Constant", BackgroundVirtualPixelMethod, DeprecateOptionFlag, MagickTrue },
    { "CheckerTile", CheckerTileVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { "Dither", DitherVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { "Edge", EdgeVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { "Gray", GrayVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { "HorizontalTile", HorizontalTileVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { "HorizontalTileEdge", HorizontalTileEdgeVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { "Mirror", MirrorVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { "None", TransparentVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { "Random", RandomVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { "Tile", TileVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { "Transparent", TransparentVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { "VerticalTile", VerticalTileVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { "VerticalTileEdge", VerticalTileEdgeVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { "White", WhiteVirtualPixelMethod, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, UndefinedVirtualPixelMethod, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().
WeightOptions
const OptionInfo WeightOptions[] static
Initial value:
=
  {
    { "Undefined", 0L, UndefinedOptionFlag, MagickTrue },
    { "Thin", 100L, UndefinedOptionFlag, MagickFalse },
    { "ExtraLight", 200L, UndefinedOptionFlag, MagickFalse },
    { "UltraLight", 200L, UndefinedOptionFlag, MagickFalse },
    { "Light", 300L, DeprecateOptionFlag, MagickTrue },
    { "Normal", 400L, UndefinedOptionFlag, MagickFalse },
    { "Regular", 400L, UndefinedOptionFlag, MagickFalse },
    { "Medium", 500L, UndefinedOptionFlag, MagickFalse },
    { "DemiBold", 600L, UndefinedOptionFlag, MagickFalse },
    { "SemiBold", 600L, UndefinedOptionFlag, MagickFalse },
    { "Bold", 700L, UndefinedOptionFlag, MagickFalse },
    { "ExtraBold", 800L, UndefinedOptionFlag, MagickFalse },
    { "UltraBold", 800L, UndefinedOptionFlag, MagickFalse },
    { "Heavy", 900L, UndefinedOptionFlag, MagickFalse },
    { "Black", 900L, UndefinedOptionFlag, MagickFalse },
    { (char *) NULL, 0L, UndefinedOptionFlag, MagickFalse }
  }
Referenced by GetOptionInfo().