MagickCore: paint.h File Reference
paint.h File Reference
#include "magick/color.h"
#include "magick/draw.h"
Functions
MagickExport Image * OilPaintImage (const Image *, const double, ExceptionInfo *)
MagickExport MagickBooleanType FloodfillPaintImage (Image *, const ChannelType, const DrawInfo *, const MagickPixelPacket *, const ssize_t, const ssize_t, const MagickBooleanType)
MagickExport MagickBooleanType GradientImage (Image *, const GradientType, const SpreadMethod, const PixelPacket *, const PixelPacket *)
MagickExport MagickBooleanType OpaquePaintImage (Image *, const MagickPixelPacket *, const MagickPixelPacket *, const MagickBooleanType)
MagickExport MagickBooleanType OpaquePaintImageChannel (Image *, const ChannelType, const MagickPixelPacket *, const MagickPixelPacket *, const MagickBooleanType)
MagickExport MagickBooleanType TransparentPaintImage (Image *, const MagickPixelPacket *, const Quantum, const MagickBooleanType)
MagickExport MagickBooleanType TransparentPaintImageChroma (Image *, const MagickPixelPacket *, const MagickPixelPacket *, const Quantum, const MagickBooleanType)
Function Documentation
FloodfillPaintImage()
MagickExport MagickBooleanType FloodfillPaintImage (Image * , const ChannelType, const DrawInfo * , const MagickPixelPacket * , const ssize_t, const ssize_t, const MagickBooleanType)
GradientImage()
MagickExport MagickBooleanType GradientImage (Image * , const GradientType, const SpreadMethod, const PixelPacket * , const PixelPacket *)
OilPaintImage()
MagickExport Image * OilPaintImage (const Image * image, const double radius, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireHistogramThreadSet(), AcquireVirtualCacheView(), ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyHistogramThreadSet(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetOpenMPThreadId(), GetOptimalKernelWidth2D(), GetPixelIndex, GetPixelIntensity(), InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, NumberPaintBins, OilPaintImageTag, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelIndex, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, and TraceEvent.
Referenced by PreviewImage().
OpaquePaintImage()
MagickExport MagickBooleanType OpaquePaintImage (Image * , const MagickPixelPacket * , const MagickPixelPacket * , const MagickBooleanType)
OpaquePaintImageChannel()
MagickExport MagickBooleanType OpaquePaintImageChannel (Image * , const ChannelType, const MagickPixelPacket * , const MagickPixelPacket * , const MagickBooleanType)
TransparentPaintImage()
MagickExport MagickBooleanType TransparentPaintImage (Image * , const MagickPixelPacket * , const Quantum, const MagickBooleanType)
TransparentPaintImageChroma()
MagickExport MagickBooleanType TransparentPaintImageChroma (Image * image, const MagickPixelPacket * low, const MagickPixelPacket * high, const Quantum, const MagickBooleanType)
References AcquireAuthenticCacheView(), _MagickPixelPacket::blue, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickPixelPacket(), _MagickPixelPacket::green, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _Image::progress_monitor, _MagickPixelPacket::red, ResetAlphaChannel, _Image::rows, SetImageAlphaChannel(), SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacket(), _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, and TransparentPaintImageTag.