MagickCore: paint.c File Reference
paint.c File Reference
#include "magick/studio.h"
#include "magick/artifact.h"
#include "magick/cache.h"
#include "magick/channel.h"
#include "magick/color-private.h"
#include "magick/colorspace-private.h"
#include "magick/composite.h"
#include "magick/composite-private.h"
#include "magick/draw.h"
#include "magick/draw-private.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/gem.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/option.h"
#include "magick/paint.h"
#include "magick/pixel-private.h"
#include "magick/resource_.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/thread-private.h"
Macros
#define MaxStacksize 524288UL
#define PushSegmentStack(up, left, right, delta)
#define NumberPaintBins 256
#define OilPaintImageTag "OilPaint/Image"
#define OpaquePaintImageTag "Opaque/Image"
#define TransparentPaintImageTag "Transparent/Image"
#define TransparentPaintImageTag "Transparent/Image"
Functions
MagickExport MagickBooleanType FloodfillPaintImage (Image *image, const ChannelType channel, const DrawInfo *draw_info, const MagickPixelPacket *target, const ssize_t x_offset, const ssize_t y_offset, const MagickBooleanType invert)
MagickExport MagickBooleanType GradientImage (Image *image, const GradientType type, const SpreadMethod method, const PixelPacket *start_color, const PixelPacket *stop_color)
static size_t ** DestroyHistogramThreadSet (size_t **histogram)
static size_t ** AcquireHistogramThreadSet (const size_t count)
MagickExport Image * OilPaintImage (const Image *image, const double radius, ExceptionInfo *exception)
MagickExport MagickBooleanType OpaquePaintImage (Image *image, const MagickPixelPacket *target, const MagickPixelPacket *fill, const MagickBooleanType invert)
MagickExport MagickBooleanType OpaquePaintImageChannel (Image *image, const ChannelType channel, const MagickPixelPacket *target, const MagickPixelPacket *fill, const MagickBooleanType invert)
MagickExport MagickBooleanType TransparentPaintImage (Image *image, const MagickPixelPacket *target, const Quantum opacity, const MagickBooleanType invert)
MagickExport MagickBooleanType TransparentPaintImageChroma (Image *image, const MagickPixelPacket *low, const MagickPixelPacket *high, const Quantum opacity, const MagickBooleanType invert)
Macro Definition Documentation
MaxStacksize
#define MaxStacksize 524288UL
NumberPaintBins
#define NumberPaintBins 256
OilPaintImageTag
#define OilPaintImageTag "OilPaint/Image"
OpaquePaintImageTag
#define OpaquePaintImageTag "Opaque/Image"
PushSegmentStack
#define PushSegmentStack (up, left, right, delta)
Value:
{ \
  if (s >= (segment_stack+MaxStacksize)) \
    ThrowBinaryException(DrawError,"SegmentStackOverflow",image->filename) \
  else \
    { \
      if ((((up)+(delta)) >= 0) && (((up)+(delta)) < (ssize_t) image->rows)) \
        { \
          s->x1=(double) (left); \
          s->y1=(double) (up); \
          s->x2=(double) (right); \
          s->y2=(double) (delta); \
          s++; \
        } \
    } \
}
TransparentPaintImageTag [1/2]
#define TransparentPaintImageTag "Transparent/Image"
TransparentPaintImageTag [2/2]
#define TransparentPaintImageTag "Transparent/Image"
Function Documentation
AcquireHistogramThreadSet()
static size_t ** AcquireHistogramThreadSet (const size_t count) static
References AcquireQuantumMemory(), DestroyHistogramThreadSet(), GetMagickResourceLimit(), and ThreadResource.
Referenced by OilPaintImage().
DestroyHistogramThreadSet()
static size_t ** DestroyHistogramThreadSet (size_t ** histogram) static
References GetMagickResourceLimit(), RelinquishMagickMemory(), and ThreadResource.
Referenced by AcquireHistogramThreadSet(), and OilPaintImage().
FloodfillPaintImage()
MagickExport MagickBooleanType FloodfillPaintImage (Image * image, const ChannelType channel, const DrawInfo * draw_info, const MagickPixelPacket * target, const ssize_t x_offset, const ssize_t y_offset, const MagickBooleanType invert)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AcquireVirtualMemory(), _MagickPixelPacket::blue, BlueChannel, ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, ConvertRGBToCMYK(), _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, _DrawInfo::fill, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetFillColor(), GetMagickModule, GetMagickPixelPacket(), GetPixelOpacity, GetVirtualMemoryBlob(), _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, IsGrayColorspace(), IsMagickColorSimilar(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, MaxStacksize, _MagickPixelPacket::opacity, _PixelPacket::opacity, OpacityChannel, OpaqueAlphaChannel, OpaqueOpacity, PushSegmentStack, _MagickPixelPacket::red, RedChannel, RelinquishVirtualMemory(), ResourceLimitError, _Image::rows, SetImageAlphaChannel(), SetImageColorspace(), SetImageStorageClass(), SetMagickPixelPacket(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _DrawInfo::signature, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), ThrowBinaryException, TraceEvent, TransparentOpacity, _SegmentInfo::x1, _SegmentInfo::x2, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by DrawPrimitive(), and PaintFloodfillImage().
GradientImage()
MagickExport MagickBooleanType GradientImage (Image * image, const GradientType type, const SpreadMethod method, const PixelPacket * start_color, const PixelPacket * stop_color)
References AcquireDrawInfo(), AcquireQuantumMemory(), _GradientInfo::angle, _GradientInfo::bounding_box, _GradientInfo::center, _StopInfo::color, _Image::columns, _Image::debug, DegreesToRadians(), DestroyDrawInfo(), DrawGradientImage(), EastGravity, _Image::filename, GetImageArtifact(), GetMagickModule, GetMagickPixelPacket(), _DrawInfo::gradient, _GradientInfo::gradient_vector, _RectangleInfo::height, LinearGradient, LocaleCompare(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickGravityOptions, MagickMax, MagickMin, NorthEastGravity, NorthGravity, NorthWestGravity, _GradientInfo::number_stops, _StopInfo::offset, ParseAbsoluteGeometry(), ParseCommandOption(), _GradientInfo::radii, _GradientInfo::radius, ResourceLimitError, _Image::rows, SetMagickPixelPacket(), _Image::signature, SouthEastGravity, SouthGravity, SouthWestGravity, _GradientInfo::spread, _GradientInfo::stops, StringToDouble(), ThrowBinaryImageException, TraceEvent, _GradientInfo::type, WestGravity, _RectangleInfo::width, _PointInfo::x, _SegmentInfo::x1, _SegmentInfo::x2, _PointInfo::y, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by RenderMVGContent().
OilPaintImage()
MagickExport Image * OilPaintImage (const Image * image, const double radius, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireHistogramThreadSet(), AcquireVirtualCacheView(), ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyHistogramThreadSet(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetOpenMPThreadId(), GetOptimalKernelWidth2D(), GetPixelIndex, GetPixelIntensity(), InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, NumberPaintBins, OilPaintImageTag, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelIndex, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, and TraceEvent.
Referenced by PreviewImage().
OpaquePaintImage()
MagickExport MagickBooleanType OpaquePaintImage (Image * image, const MagickPixelPacket * target, const MagickPixelPacket * fill, const MagickBooleanType invert)
References CompositeChannels, and OpaquePaintImageChannel().
OpaquePaintImageChannel()
MagickExport MagickBooleanType OpaquePaintImageChannel (Image * image, const ChannelType channel, const MagickPixelPacket * target, const MagickPixelPacket * fill, const MagickBooleanType invert)
References AcquireAuthenticCacheView(), _MagickPixelPacket::blue, BlueChannel, ClampToQuantum(), CMYKColorspace, _Image::colorspace, _Image::columns, ConformMagickPixelPacket(), _Image::debug, DestroyCacheView(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickPixelPacket(), _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, IsMagickColorSimilar(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _MagickPixelPacket::opacity, OpacityChannel, OpaquePaintImageTag, _Image::progress_monitor, _MagickPixelPacket::red, RedChannel, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacket(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by OpaquePaintImage(), PaintOpaqueImage(), and PaintOpaqueImageChannel().
TransparentPaintImage()
MagickExport MagickBooleanType TransparentPaintImage (Image * image, const MagickPixelPacket * target, const Quantum opacity, const MagickBooleanType invert)
References AcquireAuthenticCacheView(), _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickPixelPacket(), IsMagickColorSimilar(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OpaqueAlphaChannel, _Image::progress_monitor, _Image::rows, SetImageAlphaChannel(), SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacket(), _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, and TransparentPaintImageTag.
Referenced by PaintTransparentImage().
TransparentPaintImageChroma()
MagickExport MagickBooleanType TransparentPaintImageChroma (Image * image, const MagickPixelPacket * low, const MagickPixelPacket * high, const Quantum opacity, const MagickBooleanType invert)
References AcquireAuthenticCacheView(), _MagickPixelPacket::blue, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickPixelPacket(), _MagickPixelPacket::green, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _Image::progress_monitor, _MagickPixelPacket::red, ResetAlphaChannel, _Image::rows, SetImageAlphaChannel(), SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacket(), _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, and TransparentPaintImageTag.