MagickCore: pixel.c File Reference
pixel.c File Reference
#include "magick/studio.h"
#include "magick/property.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/color-private.h"
#include "magick/draw.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/cache.h"
#include "magick/colorspace-private.h"
#include "magick/constitute.h"
#include "magick/delegate.h"
#include "magick/geometry.h"
#include "magick/list.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/memory-private.h"
#include "magick/monitor.h"
#include "magick/option.h"
#include "magick/pixel.h"
#include "magick/pixel-private.h"
#include "magick/quantum.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/statistic.h"
#include "magick/stream.h"
#include "magick/string_.h"
#include "magick/transform.h"
#include "magick/utility.h"
Functions
MagickExport MagickPixelPacket * CloneMagickPixelPacket (const MagickPixelPacket *pixel)
MagickExport void ConformMagickPixelPacket (Image *image, const MagickPixelPacket *source, MagickPixelPacket *destination, ExceptionInfo *exception)
static double DecodeGamma (const double x)
MagickExport MagickRealType DecodePixelGamma (const MagickRealType pixel)
static double EncodeGamma (const double x)
MagickExport MagickRealType EncodePixelGamma (const MagickRealType pixel)
static MagickBooleanType ExportCharPixel (Image *image, const RectangleInfo *roi, const char *magick_restrict map, const QuantumType *quantum_map, void *pixels, ExceptionInfo *exception)
static MagickBooleanType ExportDoublePixel (Image *image, const RectangleInfo *roi, const char *magick_restrict map, const QuantumType *quantum_map, void *pixels, ExceptionInfo *exception)
static MagickBooleanType ExportFloatPixel (Image *image, const RectangleInfo *roi, const char *magick_restrict map, const QuantumType *quantum_map, void *pixels, ExceptionInfo *exception)
static MagickBooleanType ExportIntegerPixel (Image *image, const RectangleInfo *roi, const char *magick_restrict map, const QuantumType *quantum_map, void *pixels, ExceptionInfo *exception)
static MagickBooleanType ExportLongPixel (Image *image, const RectangleInfo *roi, const char *magick_restrict map, const QuantumType *quantum_map, void *pixels, ExceptionInfo *exception)
static MagickBooleanType ExportQuantumPixel (Image *image, const RectangleInfo *roi, const char *magick_restrict map, const QuantumType *quantum_map, void *pixels, ExceptionInfo *exception)
static MagickBooleanType ExportShortPixel (Image *image, const RectangleInfo *roi, const char *magick_restrict map, const QuantumType *quantum_map, void *pixels, ExceptionInfo *exception)
MagickExport MagickBooleanType ExportImagePixels (const Image *image, const ssize_t x, const ssize_t y, const size_t width, const size_t height, const char *map, const StorageType type, void *pixels, ExceptionInfo *exception)
MagickExport MagickRealType GetMagickPixelIntensity (const Image *image, const MagickPixelPacket *magick_restrict pixel)
MagickExport void GetMagickPixelPacket (const Image *image, MagickPixelPacket *pixel)
MagickExport MagickRealType GetPixelIntensity (const Image *image, const PixelPacket *magick_restrict pixel)
static MagickBooleanType ImportCharPixel (Image *image, const RectangleInfo *roi, const char *magick_restrict map, const QuantumType *quantum_map, const void *pixels, ExceptionInfo *exception)
static MagickBooleanType ImportDoublePixel (Image *image, const RectangleInfo *roi, const char *magick_restrict map, const QuantumType *quantum_map, const void *pixels, ExceptionInfo *exception)
static MagickBooleanType ImportFloatPixel (Image *image, const RectangleInfo *roi, const char *magick_restrict map, const QuantumType *quantum_map, const void *pixels, ExceptionInfo *exception)
static MagickBooleanType ImportIntegerPixel (Image *image, const RectangleInfo *roi, const char *magick_restrict map, const QuantumType *quantum_map, const void *pixels, ExceptionInfo *exception)
static MagickBooleanType ImportLongPixel (Image *image, const RectangleInfo *roi, const char *magick_restrict map, const QuantumType *quantum_map, const void *pixels, ExceptionInfo *exception)
static MagickBooleanType ImportQuantumPixel (Image *image, const RectangleInfo *roi, const char *magick_restrict map, const QuantumType *quantum_map, const void *pixels, ExceptionInfo *exception)
static MagickBooleanType ImportShortPixel (Image *image, const RectangleInfo *roi, const char *magick_restrict map, const QuantumType *quantum_map, const void *pixels, ExceptionInfo *exception)
MagickExport MagickBooleanType ImportImagePixels (Image *image, const ssize_t x, const ssize_t y, const size_t width, const size_t height, const char *map, const StorageType type, const void *pixels)
static void AlphaBlendMagickPixelPacket (const Image *image, const PixelPacket *color, const IndexPacket *indexes, MagickPixelPacket *pixel, MagickRealType *alpha)
static void CatromWeights (const MagickRealType x, MagickRealType(*weights)[4])
static void SplineWeights (const MagickRealType x, MagickRealType(*weights)[4])
static double MeshInterpolate (const PointInfo *delta, const double p, const double x, const double y)
MagickExport MagickBooleanType InterpolateMagickPixelPacket (const Image *magick_restrict image, const CacheView *image_view, const InterpolatePixelMethod method, const double x, const double y, MagickPixelPacket *pixel, ExceptionInfo *exception)
Function Documentation
AlphaBlendMagickPixelPacket()
static void AlphaBlendMagickPixelPacket (const Image * image, const PixelPacket * color, const IndexPacket * indexes, MagickPixelPacket * pixel, MagickRealType * alpha) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _Image::colorspace, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _MagickPixelPacket::green, _MagickPixelPacket::index, MagickFalse, _Image::matte, _MagickPixelPacket::opacity, PseudoClass, QuantumScale, _MagickPixelPacket::red, and _Image::storage_class.
Referenced by InterpolateMagickPixelPacket().
CatromWeights()
static void CatromWeights (const MagickRealType x, MagickRealType(*) weights[4]) inline static
Referenced by InterpolateMagickPixelPacket().
CloneMagickPixelPacket()
MagickExport MagickPixelPacket * CloneMagickPixelPacket (const MagickPixelPacket * pixel)
References AcquireAlignedMemory(), MagickAssumeAligned, ResourceLimitFatalError, and ThrowFatalException.
Referenced by FxGetSymbol().
ConformMagickPixelPacket()
MagickExport void ConformMagickPixelPacket (Image * image, const MagickPixelPacket * source, MagickPixelPacket * destination, ExceptionInfo * exception)
References CMYKColorspace, _Image::colorspace, _MagickPixelPacket::colorspace, ConvertCMYKToRGB(), ConvertRGBToCMYK(), IsGrayColorspace(), IsMagickGray(), IssRGBCompatibleColorspace(), MagickCoreSignature, MagickFalse, _Image::matte, _MagickPixelPacket::matte, OpaqueOpacity, SetImageOpacity(), _Image::signature, sRGBColorspace, and TransformImageColorspace().
Referenced by OpaquePaintImageChannel().
DecodeGamma()
static double DecodeGamma (const double x) inline static
Referenced by DecodePixelGamma().
DecodePixelGamma()
MagickExport MagickRealType DecodePixelGamma (const MagickRealType pixel)
References DecodeGamma(), QuantumRange, and QuantumScale.
Referenced by ConvertRGBToCMYK(), ConvertRGBToXYZ(), GetMagickPixelIntensity(), GetPixelIntensity(), GetPixelLuminance(), GrayscaleImage(), MagickPixelLuminance(), and RGBTransformImage().
EncodeGamma()
static double EncodeGamma (const double x) inline static
Referenced by EncodePixelGamma().
EncodePixelGamma()
MagickExport MagickRealType EncodePixelGamma (const MagickRealType pixel)
References EncodeGamma(), QuantumRange, and QuantumScale.
Referenced by ConvertXYZToRGB(), GetMagickPixelIntensity(), GetPixelIntensity(), GrayscaleImage(), MagickPixelLuma(), and TransformRGBImage().
ExportCharPixel()
static MagickBooleanType ExportCharPixel (Image * image, const RectangleInfo * roi, const char *magick_restrict map, const QuantumType * quantum_map, void * pixels, ExceptionInfo * exception) static
References AlphaQuantum, BlackQuantum, BlueQuantum, ClampToQuantum(), CMYKColorspace, _Image::colorspace, CyanQuantum, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetPixelRed, GetVirtualIndexQueue(), GetVirtualPixels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, magick_restrict, MagickFalse, MagickTrue, OpacityQuantum, RedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ExportImagePixels().
ExportDoublePixel()
static MagickBooleanType ExportDoublePixel (Image * image, const RectangleInfo * roi, const char *magick_restrict map, const QuantumType * quantum_map, void * pixels, ExceptionInfo * exception) static
References AlphaQuantum, BlackQuantum, BlueQuantum, CMYKColorspace, _Image::colorspace, CyanQuantum, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetPixelRed, GetVirtualIndexQueue(), GetVirtualPixels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, magick_restrict, MagickFalse, MagickTrue, OpacityQuantum, QuantumRange, QuantumScale, RedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ExportImagePixels().
ExportFloatPixel()
static MagickBooleanType ExportFloatPixel (Image * image, const RectangleInfo * roi, const char *magick_restrict map, const QuantumType * quantum_map, void * pixels, ExceptionInfo * exception) static
References AlphaQuantum, BlackQuantum, BlueQuantum, CMYKColorspace, _Image::colorspace, CyanQuantum, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetPixelRed, GetVirtualIndexQueue(), GetVirtualPixels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, magick_restrict, MagickFalse, MagickTrue, OpacityQuantum, QuantumScale, RedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ExportImagePixels().
ExportImagePixels()
MagickExport MagickBooleanType ExportImagePixels (const Image * image, const ssize_t x, const ssize_t y, const size_t width, const size_t height, const char * map, const StorageType type, void * pixels, ExceptionInfo * exception)
References AcquireQuantumMemory(), AlphaQuantum, BlackQuantum, BlueQuantum, CharPixel, CMYKColorspace, _Image::colorspace, CyanQuantum, _Image::debug, DoublePixel, ExportCharPixel(), ExportDoublePixel(), ExportFloatPixel(), ExportIntegerPixel(), ExportLongPixel(), ExportQuantumPixel(), ExportShortPixel(), _Image::filename, FloatPixel, GetMagickModule, GreenQuantum, _RectangleInfo::height, ImageError, IndexQuantum, IntegerPixel, LogMagickEvent(), LongPixel, MagentaQuantum, MagickCoreSignature, MagickFalse, OpacityQuantum, OptionError, QuantumPixel, RedQuantum, RelinquishMagickMemory(), ResourceLimitError, ShortPixel, _Image::signature, ThrowMagickException(), TraceEvent, UndefinedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by DispatchImage().
ExportIntegerPixel()
static MagickBooleanType ExportIntegerPixel (Image * image, const RectangleInfo * roi, const char *magick_restrict map, const QuantumType * quantum_map, void * pixels, ExceptionInfo * exception) static
References AlphaQuantum, BlackQuantum, BlueQuantum, ClampToQuantum(), CMYKColorspace, _Image::colorspace, CyanQuantum, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetPixelRed, GetVirtualIndexQueue(), GetVirtualPixels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, magick_restrict, MagickFalse, MagickTrue, OpacityQuantum, QuantumRange, RedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ExportImagePixels().
ExportLongPixel()
static MagickBooleanType ExportLongPixel (Image * image, const RectangleInfo * roi, const char *magick_restrict map, const QuantumType * quantum_map, void * pixels, ExceptionInfo * exception) static
References AlphaQuantum, BlackQuantum, BlueQuantum, ClampToQuantum(), CMYKColorspace, _Image::colorspace, CyanQuantum, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetPixelRed, GetVirtualIndexQueue(), GetVirtualPixels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, magick_restrict, MagickFalse, MagickTrue, OpacityQuantum, RedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ExportImagePixels().
ExportQuantumPixel()
static MagickBooleanType ExportQuantumPixel (Image * image, const RectangleInfo * roi, const char *magick_restrict map, const QuantumType * quantum_map, void * pixels, ExceptionInfo * exception) static
References AlphaQuantum, BlackQuantum, BlueQuantum, ClampToQuantum(), CMYKColorspace, _Image::colorspace, CyanQuantum, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetPixelRed, GetVirtualIndexQueue(), GetVirtualPixels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, magick_restrict, MagickFalse, MagickTrue, OpacityQuantum, RedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ExportImagePixels().
ExportShortPixel()
static MagickBooleanType ExportShortPixel (Image * image, const RectangleInfo * roi, const char *magick_restrict map, const QuantumType * quantum_map, void * pixels, ExceptionInfo * exception) static
References AlphaQuantum, BlackQuantum, BlueQuantum, ClampToQuantum(), CMYKColorspace, _Image::colorspace, CyanQuantum, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetPixelRed, GetVirtualIndexQueue(), GetVirtualPixels(), GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, magick_restrict, MagickFalse, MagickTrue, OpacityQuantum, RedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ExportImagePixels().
GetMagickPixelIntensity()
MagickExport MagickRealType GetMagickPixelIntensity (const Image * image, const MagickPixelPacket *magick_restrict pixel)
References AveragePixelIntensityMethod, BrightnessPixelIntensityMethod, DecodePixelGamma(), EncodePixelGamma(), _Image::intensity, LightnessPixelIntensityMethod, MagickMax, MagickMin, MSPixelIntensityMethod, QuantumRange, Rec601LumaPixelIntensityMethod, Rec601LuminancePixelIntensityMethod, Rec709LumaPixelIntensityMethod, Rec709LuminancePixelIntensityMethod, RGBColorspace, RMSPixelIntensityMethod, and sRGBColorspace.
Referenced by FxGetSymbol().
GetMagickPixelPacket()
MagickExport void GetMagickPixelPacket (const Image * image, MagickPixelPacket * pixel)
References _MagickPixelPacket::blue, _Image::colorspace, _MagickPixelPacket::colorspace, _Image::depth, _MagickPixelPacket::depth, DirectClass, _Image::fuzz, _MagickPixelPacket::fuzz, _MagickPixelPacket::green, _MagickPixelPacket::index, MAGICKCORE_QUANTUM_DEPTH, MagickFalse, _Image::matte, _MagickPixelPacket::matte, _MagickPixelPacket::opacity, OpaqueOpacity, _MagickPixelPacket::red, sRGBColorspace, _Image::storage_class, and _MagickPixelPacket::storage_class.
Referenced by AcquireColorCache(), AcquirePixelThreadSet(), AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), BlackThresholdImageChannel(), CheckImageColors(), ClassifyImageColors(), ClutImageChannel(), CompareImageBounds(), CompareImageChannels(), CompositeImageChannel(), ConnectedComponentsImage(), DistortImage(), DrawAffineImage(), DrawGradientImage(), EvaluateImages(), FilterImageChannel(), FloodfillPaintImage(), FrameImage(), FxGetSymbol(), GetEdgeBackgroundFactor(), GetImageBackgroundColor(), GetImageBoundingBox(), GetImageChannelMoments(), GetImageChannelRange(), GetImageDynamicThreshold(), GetImageProperty(), GetMedianPixelList(), GetNumberColors(), GetOneVirtualMagickPixel(), GradientImage(), HaldClutImageChannel(), IdentifyImage(), ImplodeImage(), InterpolateMagickPixelPacket(), InterpolatePixelColor(), InterpolativeResizeImage(), IsHighDynamicRangeImage(), IsHistogramImage(), IsImageSimilar(), KuwaharaImageChannel(), MaskPixelCacheNexus(), MeanShiftImage(), MorphologyPrimitiveDirect(), MotionBlurImageChannel(), OpaquePaintImageChannel(), PolynomialImageChannel(), QueryColorname(), QueryMagickColorCompliance(), RandomThresholdImageChannel(), ResamplePixelColor(), RGBTransformImage(), RotationalBlurImageChannel(), ScaleImage(), SelectiveBlurImageChannel(), SetImageAlphaChannel(), SetImageBackgroundColor(), SketchImage(), SparseColorImage(), SpreadImage(), StatisticImageChannel(), SwirlImage(), ThresholdImageChannel(), TransformRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), UnsharpMaskImageChannel(), WaveImage(), WhiteThresholdImageChannel(), XShearImage(), and YShearImage().
GetPixelIntensity()
MagickExport MagickRealType GetPixelIntensity (const Image * image, const PixelPacket *magick_restrict pixel)
References AveragePixelIntensityMethod, BrightnessPixelIntensityMethod, _Image::colorspace, DecodePixelGamma(), EncodePixelGamma(), GRAYColorspace, _Image::intensity, LightnessPixelIntensityMethod, LinearGRAYColorspace, MagickMax, MagickMin, MSPixelIntensityMethod, QuantumRange, Rec601LumaPixelIntensityMethod, Rec601LuminancePixelIntensityMethod, Rec709LumaPixelIntensityMethod, Rec709LuminancePixelIntensityMethod, RGBColorspace, RMSPixelIntensityMethod, and sRGBColorspace.
Referenced by AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AutoThresholdImage(), BilevelImageChannel(), CannyEdgeImage(), ClipPixelCacheNexus(), CombineImages(), ConsolidateCMYKImages(), ContrastStretchImageChannel(), EqualizeImageChannel(), ExportCharPixel(), ExportDoublePixel(), ExportFloatPixel(), ExportIntegerPixel(), ExportLongPixel(), ExportQuantumPixel(), ExportShortPixel(), HoughLineImage(), HuffmanEncodeImage(), IsIntensitySimilar(), LinearStretchImage(), MagnifyImage(), MaskPixelCacheNexus(), MorphologyPrimitive(), OilPaintImage(), PixelIntensityToQuantum(), RandomChannelThresholdImage(), RandomThresholdImageChannel(), RenderPostscript(), SelectiveBlurImageChannel(), SeparateImageChannel(), SepiaToneImage(), SteganoImage(), StreamImagePixels(), ThresholdImage(), ThresholdImageChannel(), and TraceEdges().
ImportCharPixel()
static MagickBooleanType ImportCharPixel (Image * image, const RectangleInfo * roi, const char *magick_restrict map, const QuantumType * quantum_map, const void * pixels, ExceptionInfo * exception) static
References AlphaQuantum, BlackQuantum, BlueQuantum, CyanQuantum, GetAuthenticIndexQueue(), GetAuthenticPixels(), GetPixelRed, GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, magick_restrict, MagickFalse, MagickTrue, OpacityQuantum, RedQuantum, SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ImportImagePixels().
ImportDoublePixel()
static MagickBooleanType ImportDoublePixel (Image * image, const RectangleInfo * roi, const char *magick_restrict map, const QuantumType * quantum_map, const void * pixels, ExceptionInfo * exception) static
References AlphaQuantum, BlackQuantum, BlueQuantum, ClampToQuantum(), CyanQuantum, GetAuthenticIndexQueue(), GetAuthenticPixels(), GetPixelRed, GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, magick_restrict, MagickFalse, MagickTrue, OpacityQuantum, QuantumRange, RedQuantum, SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ImportImagePixels().
ImportFloatPixel()
static MagickBooleanType ImportFloatPixel (Image * image, const RectangleInfo * roi, const char *magick_restrict map, const QuantumType * quantum_map, const void * pixels, ExceptionInfo * exception) static
References AlphaQuantum, BlackQuantum, BlueQuantum, ClampToQuantum(), CyanQuantum, GetAuthenticIndexQueue(), GetAuthenticPixels(), GetPixelRed, GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, magick_restrict, MagickFalse, MagickTrue, OpacityQuantum, QuantumRange, RedQuantum, SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ImportImagePixels().
ImportImagePixels()
MagickExport MagickBooleanType ImportImagePixels (Image * image, const ssize_t x, const ssize_t y, const size_t width, const size_t height, const char * map, const StorageType type, const void * pixels)
References AcquireQuantumMemory(), AlphaQuantum, BlackQuantum, BlueQuantum, CharPixel, CMYKColorspace, CyanQuantum, _Image::debug, DirectClass, DoublePixel, _Image::exception, _Image::filename, FloatPixel, GetMagickModule, GRAYColorspace, GreenQuantum, _RectangleInfo::height, ImportCharPixel(), ImportDoublePixel(), ImportFloatPixel(), ImportIntegerPixel(), ImportLongPixel(), ImportQuantumPixel(), ImportShortPixel(), IndexQuantum, IntegerPixel, LogMagickEvent(), LongPixel, MagentaQuantum, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OpacityQuantum, OptionError, QuantumPixel, RedQuantum, RelinquishMagickMemory(), ResourceLimitError, SetImageColorspace(), SetImageStorageClass(), ShortPixel, _Image::signature, ThrowBinaryException, ThrowMagickException(), TraceEvent, UndefinedQuantum, _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ConstituteImage().
ImportIntegerPixel()
static MagickBooleanType ImportIntegerPixel (Image * image, const RectangleInfo * roi, const char *magick_restrict map, const QuantumType * quantum_map, const void * pixels, ExceptionInfo * exception) static
References AlphaQuantum, BlackQuantum, BlueQuantum, CyanQuantum, GetAuthenticIndexQueue(), GetAuthenticPixels(), GetPixelRed, GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, magick_restrict, MagickFalse, MagickTrue, OpacityQuantum, RedQuantum, SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ImportImagePixels().
ImportLongPixel()
static MagickBooleanType ImportLongPixel (Image * image, const RectangleInfo * roi, const char *magick_restrict map, const QuantumType * quantum_map, const void * pixels, ExceptionInfo * exception) static
References AlphaQuantum, BlackQuantum, BlueQuantum, CyanQuantum, GetAuthenticIndexQueue(), GetAuthenticPixels(), GetPixelRed, GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, magick_restrict, MagickFalse, MagickTrue, OpacityQuantum, RedQuantum, SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ImportImagePixels().
ImportQuantumPixel()
static MagickBooleanType ImportQuantumPixel (Image * image, const RectangleInfo * roi, const char *magick_restrict map, const QuantumType * quantum_map, const void * pixels, ExceptionInfo * exception) static
References AlphaQuantum, BlackQuantum, BlueQuantum, CyanQuantum, GetAuthenticIndexQueue(), GetAuthenticPixels(), GetPixelRed, GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, magick_restrict, MagickFalse, MagickTrue, OpacityQuantum, RedQuantum, SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ImportImagePixels().
ImportShortPixel()
static MagickBooleanType ImportShortPixel (Image * image, const RectangleInfo * roi, const char *magick_restrict map, const QuantumType * quantum_map, const void * pixels, ExceptionInfo * exception) static
References AlphaQuantum, BlackQuantum, BlueQuantum, CyanQuantum, GetAuthenticIndexQueue(), GetAuthenticPixels(), GetPixelRed, GreenQuantum, _RectangleInfo::height, IndexQuantum, LocaleCompare(), MagentaQuantum, magick_restrict, MagickFalse, MagickTrue, OpacityQuantum, RedQuantum, SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, SyncAuthenticPixels(), _RectangleInfo::width, _RectangleInfo::x, _RectangleInfo::y, and YellowQuantum.
Referenced by ImportImagePixels().
InterpolateMagickPixelPacket()
MagickExport MagickBooleanType InterpolateMagickPixelPacket (const Image *magick_restrict image, const CacheView * image_view, const InterpolatePixelMethod method, const double x, const double y, MagickPixelPacket * pixel, ExceptionInfo * exception)
References AcquireVirtualCacheView(), AlphaBlendMagickPixelPacket(), Average16InterpolatePixel, Average9InterpolatePixel, AverageInterpolatePixel, BackgroundInterpolatePixel, BicubicInterpolatePixel, BilinearInterpolatePixel, BlendInterpolatePixel, _MagickPixelPacket::blue, CastDoubleToLong(), CatromInterpolatePixel, CatromWeights(), CMYKColorspace, DestroyCacheView(), DestroyImage(), ExcerptImage(), _Image::filter, FilterInterpolatePixel, GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickPixelPacket(), GetVirtualIndexQueue(), _MagickPixelPacket::green, _RectangleInfo::height, _MagickPixelPacket::index, IntegerInterpolatePixel, magick_restrict, MagickCoreSignature, MagickFalse, MagickPixelLuma(), MagickTrue, MeshInterpolate(), MeshInterpolatePixel, NearestNeighborInterpolatePixel, _MagickPixelPacket::opacity, PerceptibleReciprocal(), _MagickPixelPacket::red, ResizeImage(), SetMagickPixelPacket(), SplineInterpolatePixel, SplineWeights(), UndefinedInterpolatePixel, _RectangleInfo::width, _PointInfo::x, _RectangleInfo::x, _PointInfo::y, and _RectangleInfo::y.
Referenced by ClutImageChannel(), CompositeImageChannel(), DrawAffineImage(), FxGetSymbol(), HaldClutImageChannel(), ImplodeImage(), InterpolativeResizeImage(), KuwaharaImageChannel(), ResamplePixelColor(), SpreadImage(), SwirlImage(), and WaveImage().
MeshInterpolate()
static double MeshInterpolate (const PointInfo * delta, const double p, const double x, const double y) inline static
References _PointInfo::x, and _PointInfo::y.
Referenced by InterpolateMagickPixelPacket().
SplineWeights()
static void SplineWeights (const MagickRealType x, MagickRealType(*) weights[4]) inline static
Referenced by InterpolateMagickPixelPacket().