MagickCore: pixel.h File Reference
pixel.h File Reference
#include "magick/colorspace.h"
#include "magick/constitute.h"
Data Structures
struct _DoublePixelPacket
struct _LongPixelPacket
struct _MagickPixelPacket
struct _PixelPacket
struct _QuantumPixelPacket
Macros
#define MAGICK_PIXEL_BGRA 1
Typedefs
typedef struct _DoublePixelPacket DoublePixelPacket
typedef struct _LongPixelPacket LongPixelPacket
typedef struct _MagickPixelPacket MagickPixelPacket
typedef Quantum IndexPacket
typedef struct _PixelPacket PixelPacket
typedef struct _QuantumPixelPacket QuantumPixelPacket
typedef struct _CacheView CacheView_
Enumerations
enum InterpolatePixelMethod {
UndefinedInterpolatePixel , AverageInterpolatePixel , BicubicInterpolatePixel , BilinearInterpolatePixel ,
FilterInterpolatePixel , IntegerInterpolatePixel , MeshInterpolatePixel , NearestNeighborInterpolatePixel ,
SplineInterpolatePixel , Average9InterpolatePixel , Average16InterpolatePixel , BlendInterpolatePixel ,
BackgroundInterpolatePixel , CatromInterpolatePixel
}
enum PixelComponent {
PixelRed = 0 , PixelCyan = 0 , PixelGray = 0 , PixelY = 0 ,
PixelGreen = 1 , PixelMagenta = 1 , PixelCb = 1 , PixelBlue = 2 ,
PixelYellow = 2 , PixelCr = 2 , PixelAlpha = 3 , PixelBlack = 4 ,
PixelIndex = 4 , MaskPixelComponent = 5
}
enum PixelIntensityMethod {
UndefinedPixelIntensityMethod = 0 , AveragePixelIntensityMethod , BrightnessPixelIntensityMethod , LightnessPixelIntensityMethod ,
Rec601LumaPixelIntensityMethod , Rec601LuminancePixelIntensityMethod , Rec709LumaPixelIntensityMethod , Rec709LuminancePixelIntensityMethod ,
RMSPixelIntensityMethod , MSPixelIntensityMethod
}
Functions
MagickExport MagickBooleanType ExportImagePixels (const Image *, const ssize_t, const ssize_t, const size_t, const size_t, const char *, const StorageType, void *, ExceptionInfo *)
MagickExport MagickBooleanType ImportImagePixels (Image *, const ssize_t, const ssize_t, const size_t, const size_t, const char *, const StorageType, const void *)
MagickExport MagickBooleanType InterpolateMagickPixelPacket (const Image *magick_restrict, const CacheView_ *, const InterpolatePixelMethod, const double, const double, MagickPixelPacket *, ExceptionInfo *)
MagickExport MagickPixelPacket * CloneMagickPixelPacket (const MagickPixelPacket *)
MagickExport MagickRealType DecodePixelGamma (const MagickRealType) magick_hot_spot
MagickExport MagickRealType EncodePixelGamma (const MagickRealType) magick_hot_spot
MagickExport MagickRealType GetMagickPixelIntensity (const Image *image, const MagickPixelPacket *magick_restrict) magick_hot_spot
MagickExport MagickRealType GetPixelIntensity (const Image *image, const PixelPacket *magick_restrict) magick_hot_spot
MagickExport void ConformMagickPixelPacket (Image *, const MagickPixelPacket *, MagickPixelPacket *, ExceptionInfo *)
MagickExport void GetMagickPixelPacket (const Image *, MagickPixelPacket *)
Macro Definition Documentation
MAGICK_PIXEL_BGRA
#define MAGICK_PIXEL_BGRA 1
Typedef Documentation
CacheView_
typedef struct _CacheView CacheView_
DoublePixelPacket
typedef struct _DoublePixelPacket DoublePixelPacket
IndexPacket
typedef Quantum IndexPacket
LongPixelPacket
typedef struct _LongPixelPacket LongPixelPacket
MagickPixelPacket
typedef struct _MagickPixelPacket MagickPixelPacket
PixelPacket
typedef struct _PixelPacket PixelPacket
QuantumPixelPacket
typedef struct _QuantumPixelPacket QuantumPixelPacket
Enumeration Type Documentation
InterpolatePixelMethod
enum InterpolatePixelMethod
Enumerator
UndefinedInterpolatePixel
AverageInterpolatePixel
BicubicInterpolatePixel
BilinearInterpolatePixel
FilterInterpolatePixel
IntegerInterpolatePixel
MeshInterpolatePixel
NearestNeighborInterpolatePixel
SplineInterpolatePixel
Average9InterpolatePixel
Average16InterpolatePixel
BlendInterpolatePixel
BackgroundInterpolatePixel
CatromInterpolatePixel
PixelComponent
enum PixelComponent
Enumerator
PixelRed
PixelCyan
PixelGray
PixelY
PixelGreen
PixelMagenta
PixelCb
PixelBlue
PixelYellow
PixelCr
PixelAlpha
PixelBlack
PixelIndex
MaskPixelComponent
PixelIntensityMethod
enum PixelIntensityMethod
Enumerator
UndefinedPixelIntensityMethod
AveragePixelIntensityMethod
BrightnessPixelIntensityMethod
LightnessPixelIntensityMethod
Rec601LumaPixelIntensityMethod
Rec601LuminancePixelIntensityMethod
Rec709LumaPixelIntensityMethod
Rec709LuminancePixelIntensityMethod
RMSPixelIntensityMethod
MSPixelIntensityMethod
Function Documentation
CloneMagickPixelPacket()
MagickExport MagickPixelPacket * CloneMagickPixelPacket (const MagickPixelPacket * pixel)
References AcquireAlignedMemory(), MagickAssumeAligned, ResourceLimitFatalError, and ThrowFatalException.
Referenced by FxGetSymbol().
ConformMagickPixelPacket()
MagickExport void ConformMagickPixelPacket (Image * , const MagickPixelPacket * , MagickPixelPacket * , ExceptionInfo *)
DecodePixelGamma()
MagickExport MagickRealType DecodePixelGamma (const MagickRealType)
EncodePixelGamma()
MagickExport MagickRealType EncodePixelGamma (const MagickRealType)
ExportImagePixels()
MagickExport MagickBooleanType ExportImagePixels (const Image * , const ssize_t, const ssize_t, const size_t, const size_t, const char * , const StorageType, void * , ExceptionInfo *)
GetMagickPixelIntensity()
MagickExport MagickRealType GetMagickPixelIntensity (const Image * image, const MagickPixelPacket * magick_restrict)
GetMagickPixelPacket()
MagickExport void GetMagickPixelPacket (const Image * image, MagickPixelPacket * pixel)
References _MagickPixelPacket::blue, _Image::colorspace, _MagickPixelPacket::colorspace, _Image::depth, _MagickPixelPacket::depth, DirectClass, _Image::fuzz, _MagickPixelPacket::fuzz, _MagickPixelPacket::green, _MagickPixelPacket::index, MAGICKCORE_QUANTUM_DEPTH, MagickFalse, _Image::matte, _MagickPixelPacket::matte, _MagickPixelPacket::opacity, OpaqueOpacity, _MagickPixelPacket::red, sRGBColorspace, _Image::storage_class, and _MagickPixelPacket::storage_class.
Referenced by AcquireColorCache(), AcquirePixelThreadSet(), AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), AdaptiveThresholdImage(), BlackThresholdImageChannel(), CheckImageColors(), ClassifyImageColors(), ClutImageChannel(), CompareImageBounds(), CompareImageChannels(), CompositeImageChannel(), ConnectedComponentsImage(), DistortImage(), DrawAffineImage(), DrawGradientImage(), EvaluateImages(), FilterImageChannel(), FloodfillPaintImage(), FrameImage(), FxGetSymbol(), GetEdgeBackgroundFactor(), GetImageBackgroundColor(), GetImageBoundingBox(), GetImageChannelMoments(), GetImageChannelRange(), GetImageDynamicThreshold(), GetImageProperty(), GetMedianPixelList(), GetNumberColors(), GetOneVirtualMagickPixel(), GradientImage(), HaldClutImageChannel(), IdentifyImage(), ImplodeImage(), InterpolateMagickPixelPacket(), InterpolatePixelColor(), InterpolativeResizeImage(), IsHighDynamicRangeImage(), IsHistogramImage(), IsImageSimilar(), KuwaharaImageChannel(), MaskPixelCacheNexus(), MeanShiftImage(), MorphologyPrimitiveDirect(), MotionBlurImageChannel(), OpaquePaintImageChannel(), PolynomialImageChannel(), QueryColorname(), QueryMagickColorCompliance(), RandomThresholdImageChannel(), ResamplePixelColor(), RGBTransformImage(), RotationalBlurImageChannel(), ScaleImage(), SelectiveBlurImageChannel(), SetImageAlphaChannel(), SetImageBackgroundColor(), SketchImage(), SparseColorImage(), SpreadImage(), StatisticImageChannel(), SwirlImage(), ThresholdImageChannel(), TransformRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), UnsharpMaskImageChannel(), WaveImage(), WhiteThresholdImageChannel(), XShearImage(), and YShearImage().
GetPixelIntensity()
MagickExport MagickRealType GetPixelIntensity (const Image * image, const PixelPacket * magick_restrict)
ImportImagePixels()
MagickExport MagickBooleanType ImportImagePixels (Image * , const ssize_t, const ssize_t, const size_t, const size_t, const char * , const StorageType, const void *)
InterpolateMagickPixelPacket()
MagickExport MagickBooleanType InterpolateMagickPixelPacket (const Image * magick_restrict, const CacheView_ * , const InterpolatePixelMethod, const double , const double , MagickPixelPacket * , ExceptionInfo *)