MagickCore: pixel-accessor.h File Reference
pixel-accessor.h File Reference
#include <math.h>
#include "magick/gem.h"
#include "magick/pixel.h"
Macros
#define ClampPixelRed(pixel) ClampToQuantum((pixel)->red)
#define ClampPixelGreen(pixel) ClampToQuantum((pixel)->green)
#define ClampPixelBlue(pixel) ClampToQuantum((pixel)->blue)
#define ClampPixelIndex(indexes) ClampToQuantum(*(indexes))
#define ClampPixelOpacity(pixel) ClampToQuantum((pixel)->opacity)
#define GetPixela(pixel) ((pixel)->green)
#define GetPixelb(pixel) ((pixel)->blue)
#define GetPixelAlpha(pixel) (QuantumRange-(pixel)->opacity)
#define GetPixelBlack(indexes) (*(indexes))
#define GetPixelBlue(pixel) ((pixel)->blue)
#define GetPixelCb(pixel) ((pixel)->green)
#define GetPixelCr(pixel) ((pixel)->blue)
#define GetPixelCyan(pixel) ((pixel)->red)
#define GetPixelGray(pixel) ((pixel)->red)
#define GetPixelGreen(pixel) ((pixel)->green)
#define GetPixelIndex(indexes) (*(indexes))
#define GetPixelL(pixel) ((pixel)->red)
#define GetPixelLabel(pixel) ((ssize_t) (pixel)->red)
#define GetPixelMagenta(pixel) ((pixel)->green)
#define GetPixelNext(pixel) ((pixel)+1)
#define GetPixelOpacity(pixel) ((pixel)->opacity)
#define GetPixelRed(pixel) ((pixel)->red)
#define GetPixelRGB(pixel, packet)
#define GetPixelRGBO(pixel, packet)
#define GetPixelY(pixel) ((pixel)->red)
#define GetPixelYellow(pixel) ((pixel)->blue)
#define SetPixela(pixel, value) ((pixel)->green=(Quantum) (value))
#define SetPixelAlpha(pixel, value) ((pixel)->opacity=(Quantum) (QuantumRange-(value)))
#define SetPixelb(pixel, value) ((pixel)->blue=(Quantum) (value))
#define SetPixelBlack(indexes, value) (*(indexes)=(Quantum) (value))
#define SetPixelBlue(pixel, value) ((pixel)->blue=(Quantum) (value))
#define SetPixelCb(pixel, value) ((pixel)->green=(Quantum) (value))
#define SetPixelCr(pixel, value) ((pixel)->blue=(Quantum) (value))
#define SetPixelCyan(pixel, value) ((pixel)->red=(Quantum) (value))
#define SetPixelGray(pixel, value) ((pixel)->red=(pixel)->green=(pixel)->blue=(Quantum) (value))
#define SetPixelGreen(pixel, value) ((pixel)->green=(Quantum) (value))
#define SetPixelIndex(indexes, value) (*(indexes)=(IndexPacket) (value))
#define SetPixelL(pixel, value) ((pixel)->red=(Quantum) (value))
#define SetPixelMagenta(pixel, value) ((pixel)->green=(Quantum) (value))
#define SetPixelOpacity(pixel, value) ((pixel)->opacity=(Quantum) (value))
#define SetPixelRed(pixel, value) ((pixel)->red=(Quantum) (value))
#define SetPixelRgb(pixel, packet)
#define SetPixelRGBA(pixel, packet)
#define SetPixelRGBO(pixel, packet)
#define SetPixelYellow(pixel, value) ((pixel)->blue=(Quantum) (value))
#define SetPixelY(pixel, value) ((pixel)->red=(Quantum) (value))
Functions
static MagickRealType AbsolutePixelValue (const MagickRealType x)
static Quantum ClampPixel (const MagickRealType value)
static double PerceptibleReciprocal (const double x)
static MagickRealType GetPixelLuma (const Image *magick_restrict image, const PixelPacket *magick_restrict pixel)
static MagickRealType GetPixelLuminance (const Image *magick_restrict image, const PixelPacket *magick_restrict pixel)
static MagickBooleanType IsPixelAtDepth (const Quantum pixel, const QuantumAny range)
static MagickBooleanType IsPixelGray (const PixelPacket *pixel)
static MagickBooleanType IsPixelMonochrome (const PixelPacket *pixel)
static Quantum PixelPacketIntensity (const PixelPacket *pixel)
static void SetPixelViaMagickPixel (const Image *magick_restrict image, const MagickPixelPacket *magick_restrict magick_pixel, PixelPacket *magick_restrict pixel)
Macro Definition Documentation
ClampPixelBlue
#define ClampPixelBlue (pixel) ClampToQuantum((pixel)->blue)
ClampPixelGreen
#define ClampPixelGreen (pixel) ClampToQuantum((pixel)->green)
ClampPixelIndex
#define ClampPixelIndex (indexes) ClampToQuantum(*(indexes))
ClampPixelOpacity
#define ClampPixelOpacity (pixel) ClampToQuantum((pixel)->opacity)
ClampPixelRed
#define ClampPixelRed (pixel) ClampToQuantum((pixel)->red)
GetPixela
#define GetPixela (pixel) ((pixel)->green)
GetPixelAlpha
#define GetPixelAlpha (pixel) (QuantumRange-(pixel)->opacity)
GetPixelb
#define GetPixelb (pixel) ((pixel)->blue)
GetPixelBlack
#define GetPixelBlack (indexes) (*(indexes))
GetPixelBlue
#define GetPixelBlue (pixel) ((pixel)->blue)
GetPixelCb
#define GetPixelCb (pixel) ((pixel)->green)
GetPixelCr
#define GetPixelCr (pixel) ((pixel)->blue)
GetPixelCyan
#define GetPixelCyan (pixel) ((pixel)->red)
GetPixelGray
#define GetPixelGray (pixel) ((pixel)->red)
GetPixelGreen
#define GetPixelGreen (pixel) ((pixel)->green)
GetPixelIndex
#define GetPixelIndex (indexes) (*(indexes))
GetPixelL
#define GetPixelL (pixel) ((pixel)->red)
GetPixelLabel
#define GetPixelLabel (pixel) ((ssize_t) (pixel)->red)
GetPixelMagenta
#define GetPixelMagenta (pixel) ((pixel)->green)
GetPixelNext
#define GetPixelNext (pixel) ((pixel)+1)
GetPixelOpacity
#define GetPixelOpacity (pixel) ((pixel)->opacity)
GetPixelRed
#define GetPixelRed (pixel) ((pixel)->red)
GetPixelRGB
#define GetPixelRGB (pixel, packet)
Value:
{ \
  (packet)->red=GetPixelRed((pixel)); \
  (packet)->green=GetPixelGreen((pixel)); \
  (packet)->blue=GetPixelBlue((pixel)); \
}
GetPixelRGBO
#define GetPixelRGBO (pixel, packet)
Value:
{ \
  (packet)->red=GetPixelRed((pixel)); \
  (packet)->green=GetPixelGreen((pixel)); \
  (packet)->blue=GetPixelBlue((pixel)); \
  (packet)->opacity=GetPixelOpacity((pixel)); \
}
GetPixelY
#define GetPixelY (pixel) ((pixel)->red)
GetPixelYellow
#define GetPixelYellow (pixel) ((pixel)->blue)
SetPixela
#define SetPixela (pixel, value) ((pixel)->green=(Quantum) (value))
SetPixelAlpha
#define SetPixelAlpha (pixel, value) ((pixel)->opacity=(Quantum) (QuantumRange-(value)))
SetPixelb
#define SetPixelb (pixel, value) ((pixel)->blue=(Quantum) (value))
SetPixelBlack
#define SetPixelBlack (indexes, value) (*(indexes)=(Quantum) (value))
SetPixelBlue
#define SetPixelBlue (pixel, value) ((pixel)->blue=(Quantum) (value))
SetPixelCb
#define SetPixelCb (pixel, value) ((pixel)->green=(Quantum) (value))
SetPixelCr
#define SetPixelCr (pixel, value) ((pixel)->blue=(Quantum) (value))
SetPixelCyan
#define SetPixelCyan (pixel, value) ((pixel)->red=(Quantum) (value))
SetPixelGray
#define SetPixelGray (pixel, value) ((pixel)->red=(pixel)->green=(pixel)->blue=(Quantum) (value))
SetPixelGreen
#define SetPixelGreen (pixel, value) ((pixel)->green=(Quantum) (value))
SetPixelIndex
#define SetPixelIndex (indexes, value) (*(indexes)=(IndexPacket) (value))
SetPixelL
#define SetPixelL (pixel, value) ((pixel)->red=(Quantum) (value))
SetPixelMagenta
#define SetPixelMagenta (pixel, value) ((pixel)->green=(Quantum) (value))
SetPixelOpacity
#define SetPixelOpacity (pixel, value) ((pixel)->opacity=(Quantum) (value))
SetPixelRed
#define SetPixelRed (pixel, value) ((pixel)->red=(Quantum) (value))
SetPixelRgb
#define SetPixelRgb (pixel, packet)
Value:
{ \
  SetPixelRed(pixel,(packet)->red); \
  SetPixelGreen(pixel,(packet)->green); \
  SetPixelBlue(pixel,(packet)->blue); \
}
SetPixelRGBA
#define SetPixelRGBA (pixel, packet)
Value:
{ \
  SetPixelRed(pixel,(packet)->red); \
  SetPixelGreen(pixel,(packet)->green); \
  SetPixelBlue(pixel,(packet)->blue); \
  SetPixelAlpha(pixel,(QuantumRange-(packet)->opacity)); \
}
SetPixelRGBO
#define SetPixelRGBO (pixel, packet)
Value:
{ \
  SetPixelRed(pixel,(packet)->red); \
  SetPixelGreen(pixel,(packet)->green); \
  SetPixelBlue(pixel,(packet)->blue); \
  SetPixelOpacity(pixel,(packet)->opacity); \
}
SetPixelY
#define SetPixelY (pixel, value) ((pixel)->red=(Quantum) (value))
SetPixelYellow
#define SetPixelYellow (pixel, value) ((pixel)->blue=(Quantum) (value))
Function Documentation
AbsolutePixelValue()
static MagickRealType AbsolutePixelValue (const MagickRealType x) inline static
Referenced by IsColorEqual(), IsMagickColorEqual(), IsMagickColorMatch(), IsMagickGray(), IsPixelGray(), and IsPixelMonochrome().
ClampPixel()
static Quantum ClampPixel (const MagickRealType value) inline static
References QuantumRange.
Referenced by CacheOffset(), ClampImageChannel(), ClassifyImageColors(), ColorToNodeId(), CompositeImageChannel(), FloydSteinbergDither(), RiemersmaDither(), SetImageChannelDepth(), and SparseColorImage().
GetPixelLuma()
static MagickRealType GetPixelLuma (const Image *magick_restrict image, const PixelPacket *magick_restrict pixel) inline static
Referenced by AssignImageColors(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), KuwaharaImageChannel(), and LocalContrastImage().
GetPixelLuminance()
static MagickRealType GetPixelLuminance (const Image *magick_restrict image, const PixelPacket *magick_restrict pixel) inline static
References DecodePixelGamma(), and sRGBColorspace.
IsPixelAtDepth()
static MagickBooleanType IsPixelAtDepth (const Quantum pixel, const QuantumAny range) inline static
References MagickFalse, MagickTrue, and QuantumRange.
Referenced by GetImageChannelDepth(), and GetImageChannelStatistics().
IsPixelGray()
static MagickBooleanType IsPixelGray (const PixelPacket * pixel) inline static
References AbsolutePixelValue(), _PixelPacket::blue, _PixelPacket::green, MagickEpsilon, MagickFalse, MagickTrue, QuantumScale, and _PixelPacket::red.
Referenced by ColorizeImage(), DistortImage(), DrawPrimitive(), FrameImage(), IdentifyImageGray(), SetImageBackgroundColor(), SetPixelCacheVirtualMethod(), and TintImage().
IsPixelMonochrome()
static MagickBooleanType IsPixelMonochrome (const PixelPacket * pixel) inline static
References AbsolutePixelValue(), _PixelPacket::blue, _PixelPacket::green, MagickEpsilon, MagickFalse, MagickTrue, QuantumRange, QuantumScale, and _PixelPacket::red.
Referenced by IdentifyImageGray(), and IdentifyImageMonochrome().
PerceptibleReciprocal()
static double PerceptibleReciprocal (const double x) inline static
References MagickEpsilon.
Referenced by AcquireResizeFilter(), AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), ApplyEvaluateOperator(), ApplyPixelCompositeMask(), AutoThresholdImage(), ColorBurn(), ColorDodge(), ComplexImages(), CompositeDarken(), CompositeDifference(), CompositeIn(), CompositeLighten(), CompositeLinearDodge(), CompositeMinus(), CompositeModulusAdd(), CompositeModulusSubtract(), CompositeOut(), CompositeXor(), ConvertLuvToXYZ(), ConvertRGBToCMYK(), ConvertRGBToxyY(), ConvertxyYToRGB(), ConvertXYZToLuv(), DefineImageColormap(), DistortImage(), Divide(), DrawDashPolygon(), DrawGradientImage(), EmbossImage(), FilterImageChannel(), FxEvaluateSubexpression(), FxGetSymbol(), GammaImageChannel(), GaussJordanElimination(), GenerateDifferentialNoise(), GetCubeInfo(), GetImageChannelFeatures(), GetImageChannelMoments(), GetImageChannelStatistics(), GetImageQuantizeError(), GetMagickProperty(), GetMeanErrorPerPixel(), GetNormalizedCrossCorrelationDistortion(), GetOpacityPixel(), GetOptimalKernelWidth1D(), GetOptimalKernelWidth2D(), GetResizeFilterWeight(), GetStopColorOffset(), HorizontalFilter(), ImplodeImage(), ImportQuantumPixels(), InterpolateMagickPixelPacket(), InterpolatePixelColor(), InverseAffineMatrix(), InvertAffineCoefficients(), InvertPerspectiveCoefficients(), IsImagesEqual(), LevelPixel(), MagickCompositeOver(), MagickPixelCompositeOver(), MagickPixelCompositePlus(), MeanShiftImage(), MorphologyPrimitive(), MotionBlurImageChannel(), OptimalTau(), OptimizeLayerFrames(), ParseGeometry(), ParseMetaGeometry(), PegtopLight(), RemoveDuplicateLayers(), RGBTransformImage(), RotationalBlurImageChannel(), ScaleAnyToQuantum(), ScaleImage(), ScaleResampleFilter(), SelectiveBlurImageChannel(), SetImageAlphaChannel(), SharpenImageChannel(), SoftLight(), TraceArcPath(), TraceEllipse(), TraceStrokePolygon(), TransformRGBImage(), VerticalFilter(), VividLight(), and WaveImage().
PixelPacketIntensity()
static Quantum PixelPacketIntensity (const PixelPacket * pixel) inline static
References _PixelPacket::blue, ClampToQuantum(), _PixelPacket::green, and _PixelPacket::red.
Referenced by IntensityCompare(), and TintImage().
SetPixelViaMagickPixel()
static void SetPixelViaMagickPixel (const Image *magick_restrict image, const MagickPixelPacket *magick_restrict magick_pixel, PixelPacket *magick_restrict pixel) inline static
References ClampToQuantum(), and MagickFalse.