MagickCore: pixel-private.h File Reference
pixel-private.h File Reference
#include "magick/image.h"
#include "magick/color.h"
#include "magick/image-private.h"
#include "magick/memory_.h"
#include "magick/pixel-accessor.h"
#include "magick/quantum-private.h"
Functions
static MagickBooleanType IsGrayPixel (const PixelPacket *pixel)
static MagickBooleanType IsMonochromePixel (const PixelPacket *pixel)
static void SetMagickPixelPacket (const Image *image, const PixelPacket *color, const IndexPacket *index, MagickPixelPacket *pixel)
static void SetMagickPixelPacketBias (const Image *image, MagickPixelPacket *pixel)
static void SetPixelPacket (const Image *image, const MagickPixelPacket *pixel, PixelPacket *color, IndexPacket *index)
Function Documentation
IsGrayPixel()
static MagickBooleanType IsGrayPixel (const PixelPacket * pixel) inline static
References GetPixelBlue, GetPixelGreen, GetPixelRed, MagickEpsilon, MagickFalse, and MagickTrue.
Referenced by SetImageGray().
IsMonochromePixel()
static MagickBooleanType IsMonochromePixel (const PixelPacket * pixel) inline static
References GetPixelBlue, GetPixelGreen, GetPixelRed, MagickEpsilon, MagickFalse, MagickTrue, and QuantumRange.
Referenced by SetImageGray(), and SetImageMonochrome().
SetMagickPixelPacket()
static void SetMagickPixelPacket (const Image * image, const PixelPacket * color, const IndexPacket * index, MagickPixelPacket * pixel) inline static
References _MagickPixelPacket::blue, CMYKColorspace, _Image::colorspace, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _MagickPixelPacket::green, _MagickPixelPacket::index, _MagickPixelPacket::opacity, and _MagickPixelPacket::red.
Referenced by CheckImageColors(), ClassifyImageColors(), ClutImageChannel(), CompareImageBounds(), CompareImageChannels(), DistortImage(), DrawAffineImage(), DrawGradientImage(), FloodfillPaintImage(), FrameImage(), GetEdgeBackgroundFactor(), GetImageBoundingBox(), GetImageChannelMoments(), GetImageChannelRange(), GetNumberColors(), GetOneVirtualMagickPixel(), GradientImage(), IdentifyImage(), InterpolateMagickPixelPacket(), InterpolatePixelColor(), IsHighDynamicRangeImage(), IsHistogramImage(), IsImageSimilar(), MaskPixelCacheNexus(), MeanShiftImage(), MorphologyPrimitiveDirect(), OpaquePaintImageChannel(), QueryColorname(), ResamplePixelColor(), RGBTransformImage(), SetImageAlphaChannel(), SetImageBackgroundColor(), SparseColorImage(), StatisticImageChannel(), TransformRGBImage(), TransparentPaintImage(), TransparentPaintImageChroma(), XShearImage(), and YShearImage().
SetMagickPixelPacketBias()
static void SetMagickPixelPacketBias (const Image * image, MagickPixelPacket * pixel) inline static
References _Image::bias, _MagickPixelPacket::blue, _MagickPixelPacket::green, _MagickPixelPacket::index, _MagickPixelPacket::opacity, and _MagickPixelPacket::red.
Referenced by AdaptiveBlurImageChannel(), AdaptiveSharpenImageChannel(), FilterImageChannel(), and SelectiveBlurImageChannel().
SetPixelPacket()
static void SetPixelPacket (const Image * image, const MagickPixelPacket * pixel, PixelPacket * color, IndexPacket * index) inline static
References _MagickPixelPacket::blue, ClampToQuantum(), CMYKColorspace, _Image::colorspace, _MagickPixelPacket::green, _MagickPixelPacket::index, _MagickPixelPacket::opacity, PseudoClass, _MagickPixelPacket::red, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, and _Image::storage_class.
Referenced by CompareImageChannels(), CompositeImageChannel(), DistortImage(), DrawAffineImage(), FrameImage(), ImplodeImage(), InterpolativeResizeImage(), KuwaharaImageChannel(), MorphologyPrimitiveDirect(), NewMagickImage(), RGBTransformImage(), SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageColor(), SketchImage(), SparseColorImage(), SpreadImage(), SwirlImage(), TransformRGBImage(), WaveImage(), XShearImage(), and YShearImage().