MagickCore: policy.h File Reference
policy.h File Reference
#include "magick/pixel.h"
#include "magick/exception.h"
Typedefs
typedef struct _PolicyInfo PolicyInfo
Enumerations
enum PolicyDomain {
UndefinedPolicyDomain , CoderPolicyDomain , DelegatePolicyDomain , FilterPolicyDomain ,
PathPolicyDomain , ResourcePolicyDomain , SystemPolicyDomain , CachePolicyDomain ,
ModulePolicyDomain
}
enum PolicyRights {
UndefinedPolicyRights = 0x00 , NoPolicyRights = 0x00 , ReadPolicyRights = 0x01 , WritePolicyRights = 0x02 ,
ExecutePolicyRights = 0x04 , AllPolicyRights = 0xff
}
Functions
MagickExport char * GetPolicyValue (const char *name)
MagickExport char ** GetPolicyList (const char *, size_t *, ExceptionInfo *)
MagickExport const PolicyInfo ** GetPolicyInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport MagickBooleanType IsRightsAuthorized (const PolicyDomain, const PolicyRights, const char *)
MagickExport MagickBooleanType ListPolicyInfo (FILE *, ExceptionInfo *)
MagickExport MagickBooleanType PolicyComponentGenesis (void)
MagickExport MagickBooleanType SetMagickSecurityPolicy (const char *, ExceptionInfo *)
MagickExport void PolicyComponentTerminus (void)
Typedef Documentation
PolicyInfo
typedef struct _PolicyInfo PolicyInfo
Enumeration Type Documentation
PolicyDomain
enum PolicyDomain
Enumerator
UndefinedPolicyDomain
CoderPolicyDomain
DelegatePolicyDomain
FilterPolicyDomain
PathPolicyDomain
ResourcePolicyDomain
SystemPolicyDomain
CachePolicyDomain
ModulePolicyDomain
PolicyRights
enum PolicyRights
Enumerator
UndefinedPolicyRights
NoPolicyRights
ReadPolicyRights
WritePolicyRights
ExecutePolicyRights
AllPolicyRights
Function Documentation
GetPolicyInfoList()
MagickExport const PolicyInfo ** GetPolicyInfoList (const char * pattern, size_t * number_policies, ExceptionInfo * exception)
References AcquireQuantumMemory(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GetPolicyInfo(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _PolicyInfo::name, policy_cache, policy_semaphore, ResetLinkedListIterator(), _PolicyInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ListPolicyInfo().
GetPolicyList()
MagickExport char ** GetPolicyList (const char * pattern, size_t * number_policies, ExceptionInfo * exception)
References AcquirePolicyString(), AcquireQuantumMemory(), GetMagickModule, GetNextValueInLinkedList(), GetNumberOfElementsInLinkedList(), GetPolicyInfo(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _PolicyInfo::name, policy_cache, policy_semaphore, ResetLinkedListIterator(), _PolicyInfo::stealth, TraceEvent, and UnlockSemaphoreInfo().
GetPolicyValue()
MagickExport char * GetPolicyValue (const char * name)
IsRightsAuthorized()
MagickExport MagickBooleanType IsRightsAuthorized (const PolicyDomain, const PolicyRights, const char *)
ListPolicyInfo()
MagickExport MagickBooleanType ListPolicyInfo (FILE * , ExceptionInfo *)
PolicyComponentGenesis()
MagickExport MagickBooleanType PolicyComponentGenesis (void)
PolicyComponentTerminus()
MagickExport void PolicyComponentTerminus (void)
References ActivateSemaphoreInfo(), DestroyLinkedList(), DestroyPolicyElement(), DestroySemaphoreInfo(), LockSemaphoreInfo(), policy_cache, policy_semaphore, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
SetMagickSecurityPolicy()
MagickExport MagickBooleanType SetMagickSecurityPolicy (const char * policy, ExceptionInfo * exception)
References _PolicyInfo::domain, GetNextValueInLinkedList(), IsPolicyCacheInstantiated(), LoadPolicyCache(), LockSemaphoreInfo(), MagickFalse, policy_cache, policy_semaphore, ResetLinkedListIterator(), ResourceComponentGenesis(), UndefinedPolicyDomain, and UnlockSemaphoreInfo().