MagickCore: prepress.h File Reference
prepress.h File Reference
Functions
MagickExport double GetImageTotalInkDensity (Image *image)
Function Documentation
GetImageTotalInkDensity()
MagickExport double GetImageTotalInkDensity (Image * image)
References AcquireVirtualCacheView(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::exception, _Image::filename, GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelRed, ImageError, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::rows, _Image::signature, ThrowMagickException(), and TraceEvent.
Referenced by IdentifyImage().