MagickCore: property.c File Reference
property.c File Reference
#include "magick/studio.h"
#include "magick/artifact.h"
#include "magick/attribute.h"
#include "magick/cache.h"
#include "magick/cache-private.h"
#include "magick/color.h"
#include "magick/colorspace-private.h"
#include "magick/compare.h"
#include "magick/constitute.h"
#include "magick/draw.h"
#include "magick/effect.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/fx.h"
#include "magick/fx-private.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/histogram.h"
#include "magick/image.h"
#include "magick/layer.h"
#include "magick/list.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/monitor.h"
#include "magick/montage.h"
#include "magick/option.h"
#include "magick/policy.h"
#include "magick/profile.h"
#include "magick/property.h"
#include "magick/quantum.h"
#include "magick/resource_.h"
#include "magick/splay-tree.h"
#include "magick/signature-private.h"
#include "magick/statistic.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/version.h"
#include "magick/xml-tree.h"
Macros
#define MaxDirectoryStack 16
#define EXIF_DELIMITER "\n"
#define EXIF_NUM_FORMATS 12
#define EXIF_FMT_BYTE 1
#define EXIF_FMT_STRING 2
#define EXIF_FMT_USHORT 3
#define EXIF_FMT_ULONG 4
#define EXIF_FMT_URATIONAL 5
#define EXIF_FMT_SBYTE 6
#define EXIF_FMT_UNDEFINED 7
#define EXIF_FMT_SSHORT 8
#define EXIF_FMT_SLONG 9
#define EXIF_FMT_SRATIONAL 10
#define EXIF_FMT_SINGLE 11
#define EXIF_FMT_DOUBLE 12
#define TAG_EXIF_OFFSET 0x8769
#define TAG_GPS_OFFSET 0x8825
#define TAG_INTEROP_OFFSET 0xa005
#define EXIFMultipleValues(size, format, arg)
#define EXIFMultipleFractions(size, format, arg1, arg2)
#define WarnNoImageInfoReturn(format, arg)
#define ExtendInterpretText(string_length)
#define AppendKeyValue2Text(key, value)
#define AppendString2Text(string)
Functions
MagickExport MagickBooleanType CloneImageProperties (Image *image, const Image *clone_image)
MagickExport MagickBooleanType DefineImageProperty (Image *image, const char *property)
MagickExport MagickBooleanType DeleteImageProperty (Image *image, const char *property)
MagickExport void DestroyImageProperties (Image *image)
MagickExport MagickBooleanType FormatImageProperty (Image *image, const char *property, const char *format,...)
static char * TracePSClippath (const unsigned char *, size_t, const size_t, const size_t)
static char * TraceSVGClippath (const unsigned char *, size_t, const size_t, const size_t)
static MagickBooleanType GetIPTCProperty (const Image *image, const char *key)
static int ReadPropertyByte (const unsigned char **p, size_t *length)
static signed int ReadPropertyMSBLong (const unsigned char **p, size_t *length)
static signed short ReadPropertyMSBShort (const unsigned char **p, size_t *length)
static MagickBooleanType Get8BIMProperty (const Image *image, const char *key)
static signed int ReadPropertySignedLong (const EndianType endian, const unsigned char *buffer)
static unsigned int ReadPropertyUnsignedLong (const EndianType endian, const unsigned char *buffer)
static signed short ReadPropertySignedShort (const EndianType endian, const unsigned char *buffer)
static unsigned short ReadPropertyUnsignedShort (const EndianType endian, const unsigned char *buffer)
static MagickBooleanType GetEXIFProperty (const Image *image, const char *property)
static MagickBooleanType GetICCProperty (const Image *image, const char *property)
static MagickBooleanType SkipXMPValue (const char *value)
static MagickBooleanType GetXMPProperty (const Image *image, const char *property)
static char * TracePSClippath (const unsigned char *blob, size_t length, const size_t magick_unused(columns), const size_t magick_unused(rows))
static void TraceBezierCurve (char *message, PointInfo *last, PointInfo *point)
MagickExport const char * GetImageProperty (const Image *image, const char *property)
static const char * GetMagickPropertyLetter (const ImageInfo *image_info, Image *image, const char letter)
MagickExport const char * GetMagickProperty (const ImageInfo *image_info, Image *image, const char *property)
MagickExport char * GetNextImageProperty (const Image *image)
MagickExport char * InterpretImageProperties (const ImageInfo *image_info, Image *image, const char *embed_text)
MagickExport char * RemoveImageProperty (Image *image, const char *property)
MagickExport void ResetImagePropertyIterator (const Image *image)
MagickExport MagickBooleanType SetImageProperty (Image *image, const char *property, const char *value)
Macro Definition Documentation
AppendKeyValue2Text
#define AppendKeyValue2Text (key, value)
Value:
{ \
  size_t length=strlen(key)+strlen(value)+2; \
  if ((size_t) (q-interpret_text+length+1) >= extent) \
    { \
      extent+=length; \
      interpret_text=(char *) ResizeQuantumMemory(interpret_text,extent+ \
        MaxTextExtent,sizeof(*interpret_text)); \
      if (interpret_text == (char *) NULL) \
        { \
          if (property_info != image_info) \
            property_info=DestroyImageInfo(property_info); \
          return((char *) NULL); \
        } \
      q=interpret_text+strlen(interpret_text); \
     } \
   q+=FormatLocaleString(q,extent,"%s=%s\n",(key),(value)); \
}
AppendString2Text
#define AppendString2Text (string)
Value:
{ \
  size_t length=strlen((string)); \
  if ((size_t) (q-interpret_text+length+1) >= extent) \
    { \
      extent+=length; \
      interpret_text=(char *) ResizeQuantumMemory(interpret_text,extent+ \
        MaxTextExtent,sizeof(*interpret_text)); \
      if (interpret_text == (char *) NULL) \
        { \
          if (property_info != image_info) \
            property_info=DestroyImageInfo(property_info); \
          return((char *) NULL); \
        } \
      q=interpret_text+strlen(interpret_text); \
    } \
  (void) CopyMagickString(q,(string),extent); \
  q+=length; \
}
EXIF_DELIMITER
#define EXIF_DELIMITER "\n"
EXIF_FMT_BYTE
#define EXIF_FMT_BYTE 1
EXIF_FMT_DOUBLE
#define EXIF_FMT_DOUBLE 12
EXIF_FMT_SBYTE
#define EXIF_FMT_SBYTE 6
EXIF_FMT_SINGLE
#define EXIF_FMT_SINGLE 11
EXIF_FMT_SLONG
#define EXIF_FMT_SLONG 9
EXIF_FMT_SRATIONAL
#define EXIF_FMT_SRATIONAL 10
EXIF_FMT_SSHORT
#define EXIF_FMT_SSHORT 8
EXIF_FMT_STRING
#define EXIF_FMT_STRING 2
EXIF_FMT_ULONG
#define EXIF_FMT_ULONG 4
EXIF_FMT_UNDEFINED
#define EXIF_FMT_UNDEFINED 7
EXIF_FMT_URATIONAL
#define EXIF_FMT_URATIONAL 5
EXIF_FMT_USHORT
#define EXIF_FMT_USHORT 3
EXIF_NUM_FORMATS
#define EXIF_NUM_FORMATS 12
EXIFMultipleFractions
#define EXIFMultipleFractions (size, format, arg1, arg2)
Value:
{ \
   ssize_t \
     component; \
 \
   size_t \
     length; \
 \
   unsigned char \
     *p1; \
 \
   length=0; \
   p1=p; \
   for (component=0; component < components; component++) \
   { \
     length+=FormatLocaleString(buffer+length,MaxTextExtent-length, \
       format", ",(arg1),(arg2)); \
     if (length >= (MaxTextExtent-1)) \
       length=MaxTextExtent-1; \
     p1+=size; \
   } \
   if (length > 1) \
     buffer[length-2]='\0'; \
   value=AcquireString(buffer); \
}
EXIFMultipleValues
#define EXIFMultipleValues (size, format, arg)
Value:
{ \
   ssize_t \
     component; \
 \
   size_t \
     length; \
 \
   unsigned char \
     *p1; \
 \
   length=0; \
   p1=p; \
   for (component=0; component < components; component++) \
   { \
     length+=FormatLocaleString(buffer+length,MaxTextExtent-length, \
       format", ",arg); \
     if (length >= (MaxTextExtent-1)) \
       length=MaxTextExtent-1; \
     p1+=size; \
   } \
   if (length > 1) \
     buffer[length-2]='\0'; \
   value=AcquireString(buffer); \
}
ExtendInterpretText
#define ExtendInterpretText (string_length)
Value:
{ \
  size_t length=(string_length); \
  if ((size_t) (q-interpret_text+length+1) >= extent) \
    { \
      extent+=length; \
      interpret_text=(char *) ResizeQuantumMemory(interpret_text,extent+ \
        MaxTextExtent,sizeof(*interpret_text)); \
      if (interpret_text == (char *) NULL) \
        { \
          if (property_info != image_info) \
            property_info=DestroyImageInfo(property_info); \
          return((char *) NULL); \
        } \
      q=interpret_text+strlen(interpret_text); \
   } \
}
MaxDirectoryStack
#define MaxDirectoryStack 16
TAG_EXIF_OFFSET
#define TAG_EXIF_OFFSET 0x8769
TAG_GPS_OFFSET
#define TAG_GPS_OFFSET 0x8825
TAG_INTEROP_OFFSET
#define TAG_INTEROP_OFFSET 0xa005
WarnNoImageInfoReturn
#define WarnNoImageInfoReturn (format, arg)
Value:
  if (image_info == (ImageInfo *) NULL ) { \
    (void) ThrowMagickException(&image->exception,GetMagickModule(), \
      OptionWarning,"NoImageInfoForProperty",format,arg); \
    return((const char *) NULL); \
  }
Function Documentation
CloneImageProperties()
MagickExport MagickBooleanType CloneImageProperties (Image * image, const Image * clone_image)
References _Image::background_color, _Image::bias, _Image::black_point_compensation, _Image::blur, _Image::border_color, _Image::chromaticity, _Image::client_data, CloneSplayTree(), CloneString(), _Image::compose, _Image::compression, ConstantString(), CopyMagickString(), _Image::debug, _Image::delay, _Image::depth, DestroyImageProperties(), _Image::directory, _Image::dispose, _Image::endian, _Image::error, _Image::extract_info, _Image::filename, _Image::filter, _Image::fuzz, _Image::gamma, _Image::geometry, GetMagickModule, _Image::gravity, _Image::intensity, _Image::interlace, _Image::interpolate, _Image::iterations, LogMagickEvent(), _Image::magick_filename, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte_color, MaxTextExtent, _Image::montage, _Image::offset, _Image::orientation, _Image::page, _Image::progress_monitor, _Image::properties, _Image::quality, _Image::rendering_intent, _Image::scene, _Image::signature, _Image::start_loop, _Image::taint, _Image::ticks_per_second, _Image::tile_offset, _Image::total_colors, TraceEvent, _Image::transparent_color, _Image::units, _Image::x_resolution, and _Image::y_resolution.
Referenced by CloneImage(), CloneImageAttributes(), CoalesceImages(), and DisposeImages().
DefineImageProperty()
MagickExport MagickBooleanType DefineImageProperty (Image * image, const char * property)
References CopyMagickString(), MaxTextExtent, and SetImageProperty().
DeleteImageProperty()
MagickExport MagickBooleanType DeleteImageProperty (Image * image, const char * property)
References _Image::debug, DeleteNodeFromSplayTree(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::properties, _Image::signature, and TraceEvent.
Referenced by DeleteImageAttribute(), PreviewImage(), ReadImage(), SetImageProperty(), SignatureImage(), StripImage(), and ThumbnailImage().
DestroyImageProperties()
MagickExport void DestroyImageProperties (Image * image)
References _Image::debug, DestroySplayTree(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::properties, _Image::signature, and TraceEvent.
Referenced by CloneImageProperties(), and DestroyImage().
FormatImageProperty()
MagickExport MagickBooleanType FormatImageProperty (Image * image, const char * property, const char * format, ...)
References FormatLocaleStringList(), MaxTextExtent, and SetImageProperty().
Referenced by GetImageChannelDistortion().
Get8BIMProperty()
static MagickBooleanType Get8BIMProperty (const Image * image, const char * key) static
References AcquireQuantumMemory(), _Image::columns, CopyMagickString(), DestroyString(), GetImageProfile(), GetStringInfoDatum(), GetStringInfoLength(), LocaleCompare(), MagickFalse, MagickMax, MagickMin, MagickTrue, MaxTextExtent, ReadPropertyByte(), ReadPropertyMSBLong(), ReadPropertyMSBShort(), _Image::rows, SetImageProperty(), StringToLong(), TracePSClippath(), and TraceSVGClippath().
Referenced by GetImageProperty().
GetEXIFProperty()
static MagickBooleanType GetEXIFProperty (const Image * image, const char * property) static
References AcquireQuantumMemory(), AcquireString(), AddValueToSplayTree(), DestroySplayTree(), DestroyString(), EXIF_FMT_BYTE, EXIF_FMT_DOUBLE, EXIF_FMT_SBYTE, EXIF_FMT_SINGLE, EXIF_FMT_SLONG, EXIF_FMT_SRATIONAL, EXIF_FMT_SSHORT, EXIF_FMT_STRING, EXIF_FMT_ULONG, EXIF_FMT_UNDEFINED, EXIF_FMT_URATIONAL, EXIF_FMT_USHORT, EXIFMultipleFractions, EXIFMultipleValues, FormatLocaleString(), GetImageProfile(), GetStringInfoDatum(), GetStringInfoLength(), GetValueFromSplayTree(), LocaleCompare(), LSBEndian, MagickFalse, MagickTrue, MaxDirectoryStack, MaxTextExtent, MSBEndian, NewSplayTree(), _Image::properties, ReadPropertyByte(), ReadPropertySignedLong(), ReadPropertySignedShort(), ReadPropertyUnsignedLong(), ReadPropertyUnsignedShort(), SetImageProperty(), SubstituteString(), TAG_EXIF_OFFSET, TAG_GPS_OFFSET, and TAG_INTEROP_OFFSET.
Referenced by GetImageProperty().
GetICCProperty()
static MagickBooleanType GetICCProperty (const Image * image, const char * property) static
References GetImageProfile(), GetStringInfoDatum(), GetStringInfoLength(), magick_unreferenced, MagickFalse, MagickMin, MagickPathExtent, MagickTrue, and SetImageProperty().
Referenced by GetImageProperty().
GetImageProperty()
MagickExport const char * GetImageProperty (const Image * image, const char * property)
References AcquireFxInfo(), BlackChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DefaultChannels, DestroyFxInfo(), _Image::filename, FormatLocaleString(), FxEvaluateChannelExpression(), Get8BIMProperty(), GetColorTuple(), GetEXIFProperty(), GetICCProperty(), GetImageArtifact(), GetIPTCProperty(), GetMagickModule, GetMagickPixelPacket(), GetMagickPrecision(), GetNextValueInSplayTree(), GetValueFromSplayTree(), GetXMPProperty(), _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, LocaleNCompare(), LogMagickEvent(), MagickComplianceOptions, MagickCoreSignature, MagickFalse, MagickTrue, MaxTextExtent, _MagickPixelPacket::opacity, OpacityChannel, ParseCommandOption(), _Image::properties, QuantumRange, QueryMagickColorname(), _MagickPixelPacket::red, RedChannel, ResetSplayTreeIterator(), _Image::rows, SetImageProperty(), _Image::signature, and TraceEvent.
Referenced by ClipImagePath(), GetImageAttribute(), GetMagickPropertyLetter(), IdentifyImage(), InterpretImageFilename(), InterpretImageProperties(), MontageImageList(), PolaroidImage(), ProfileImage(), ReadImage(), RGBTransformImage(), SetImageGray(), SetImageMonochrome(), and TransformRGBImage().
GetIPTCProperty()
static MagickBooleanType GetIPTCProperty (const Image * image, const char * key) static
References AcquireQuantumMemory(), ConcatenateString(), CopyMagickString(), DestroyString(), GetImageProfile(), GetStringInfoDatum(), GetStringInfoLength(), MagickFalse, MagickTrue, and SetImageProperty().
Referenced by GetImageProperty().
GetMagickProperty()
MagickExport const char * GetMagickProperty (const ImageInfo * image_info, Image * image, const char * property)
References BasePath, _ImageInfo::channel, _Image::colors, _Image::colorspace, _Image::columns, CommandOptionToMnemonic(), _Image::compose, _Image::compression, ConcatenateMagickString(), CopyMagickString(), _Image::depth, _Image::exception, ExtensionPath, _Image::filename, _ImageInfo::filename, FormatLocaleString(), FormatMagickSize(), _Image::gamma, GetBlobSize(), GetImageArtifact(), GetImageBoundingBox(), GetImageChannelEntropy(), GetImageChannelKurtosis(), GetImageChannelMean(), GetImageChannelRange(), GetImageDepth(), GetImageListLength(), GetImageProfile(), GetMagickCopyright(), GetMagickPrecision(), GetMagickPropertyLetter(), GetMagickVersion(), GetNextImageProfile(), GetNumberColors(), GetPageGeometry(), GetPathComponent(), GetStringInfoDatum(), GetStringInfoLength(), _ImageInfo::group, HeadPath, _RectangleInfo::height, IdentifyImageType(), _Image::interlace, IsOpaqueImage(), LocaleCompare(), LocaleLower(), LocaleNCompare(), _Image::magick, _Image::magick_columns, _Image::magick_filename, _Image::magick_rows, MagickColorspaceOptions, MagickComposeOptions, MagickCompressOptions, MagickFalse, MagickIntentOptions, MagickInterlaceOptions, MagickOrientationOptions, MagickPathExtent, MagickResolutionOptions, MagickTypeOptions, _Image::matte, MaxTextExtent, _ImageInfo::number_scenes, _Image::orientation, _Image::page, ParseAbsoluteGeometry(), PerceptibleReciprocal(), _Image::quality, _Image::rendering_intent, ResetImageProfileIterator(), _Image::rows, _Image::scene, _ImageInfo::scene, SetImageArtifact(), _ImageInfo::unique, _Image::units, _RectangleInfo::width, _RectangleInfo::x, _Image::x_resolution, _RectangleInfo::y, _Image::y_resolution, and _ImageInfo::zero.
Referenced by InterpretImageProperties().
GetMagickPropertyLetter()
static const char * GetMagickPropertyLetter (const ImageInfo * image_info, Image * image, const char letter) static
References BasePath, _Image::colorspace, _Image::columns, CommandOptionToMnemonic(), _Image::compression, CopyMagickString(), _Image::debug, _Image::delay, _Image::depth, _Image::dispose, _Image::exception, ExtensionPath, _Image::extent, _Image::filename, _ImageInfo::filename, FormatLocaleString(), FormatMagickSize(), GetBlobSize(), GetImageArtifact(), GetImageBoundingBox(), GetImageIndexInList(), GetImageListLength(), GetImageProperty(), GetMagickModule, GetNumberColors(), GetPathComponent(), GRAYColorspace, HeadPath, _RectangleInfo::height, LogMagickEvent(), _Image::magick, _Image::magick_columns, _Image::magick_filename, _Image::magick_rows, MagickBooleanOptions, MagickClassOptions, MagickColorspaceOptions, MagickCompressOptions, MAGICKCORE_QUANTUM_DEPTH, MagickCoreSignature, MagickDisposeOptions, MagickEpsilon, MagickFalse, MagickPathExtent, MagickResolutionOptions, _Image::matte, MaxTextExtent, _Image::next, _ImageInfo::number_scenes, _Image::page, _Image::quality, _Image::rows, _Image::scene, _ImageInfo::scene, SetImageArtifact(), SetImageGray(), _Image::signature, SignatureImage(), _Image::storage_class, TailPath, TraceEvent, _ImageInfo::unique, _Image::units, WarnNoImageInfoReturn, _RectangleInfo::width, _RectangleInfo::x, _Image::x_resolution, _RectangleInfo::y, _Image::y_resolution, and _ImageInfo::zero.
Referenced by GetMagickProperty(), and InterpretImageProperties().
GetNextImageProperty()
MagickExport char * GetNextImageProperty (const Image * image)
References _Image::debug, _Image::filename, GetMagickModule, GetNextKeyInSplayTree(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::properties, _Image::signature, and TraceEvent.
Referenced by GetNextImageAttribute(), IdentifyImage(), and InterpretImageProperties().
GetXMPProperty()
static MagickBooleanType GetXMPProperty (const Image * image, const char * property) static
References AcquireExceptionInfo(), AddValueToSplayTree(), CompareSplayTreeString(), ConstantString(), DestroyExceptionInfo(), DestroyString(), DestroyXMLTree(), GetImageProfile(), GetNextXMLTreeTag(), GetStringInfoLength(), GetXMLTreeChild(), GetXMLTreeContent(), GetXMLTreeSibling(), GetXMLTreeTag(), MagickFalse, NewSplayTree(), NewXMLTree(), _Image::properties, RelinquishMagickMemory(), SkipXMPValue(), StringInfoToString(), and SubstituteString().
Referenced by GetImageProperty().
InterpretImageProperties()
MagickExport char * InterpretImageProperties (const ImageInfo * image_info, Image * image, const char * embed_text)
References AcquireFxInfo(), AcquireString(), AppendKeyValue2Text, AppendString2Text, CloneImageInfo(), ConstantString(), _Image::debug, DefaultChannels, DestroyFxInfo(), DestroyImageInfo(), DestroyString(), _Image::exception, ExtendInterpretText, _Image::filename, FileToString(), FormatLocaleString(), FxEvaluateChannelExpression(), GetImageArtifact(), GetImageOption(), GetImageProperty(), GetMagickModule, GetMagickPrecision(), GetMagickProperty(), GetMagickPropertyLetter(), GetNextImageArtifact(), GetNextImageOption(), GetNextImageProperty(), GlobExpression(), IsGlob(), IsPathAccessible(), IsRightsAuthorized(), LocaleNCompare(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickPathExtent, MagickTrue, MaxTextExtent, OptionError, OptionWarning, PathPolicyDomain, PolicyError, ReadPolicyRights, ResetImageArtifactIterator(), ResetImageOptionIterator(), ResetImagePropertyIterator(), _Image::signature, ThrowMagickException(), and TraceEvent.
Referenced by InterpretImageAttributes(), MontageImageList(), PolaroidImage(), ReadImage(), and TranslateText().
ReadPropertyByte()
static int ReadPropertyByte (const unsigned char ** p, size_t * length) inline static
Referenced by Get8BIMProperty(), and GetEXIFProperty().
ReadPropertyMSBLong()
static signed int ReadPropertyMSBLong (const unsigned char ** p, size_t * length) inline static
Referenced by Get8BIMProperty(), TracePSClippath(), and TraceSVGClippath().
ReadPropertyMSBShort()
static signed short ReadPropertyMSBShort (const unsigned char ** p, size_t * length) inline static
Referenced by Get8BIMProperty(), TracePSClippath(), and TraceSVGClippath().
ReadPropertySignedLong()
static signed int ReadPropertySignedLong (const EndianType endian, const unsigned char * buffer) inline static
References LSBEndian.
Referenced by GetEXIFProperty().
ReadPropertySignedShort()
static signed short ReadPropertySignedShort (const EndianType endian, const unsigned char * buffer) inline static
References LSBEndian.
Referenced by GetEXIFProperty().
ReadPropertyUnsignedLong()
static unsigned int ReadPropertyUnsignedLong (const EndianType endian, const unsigned char * buffer) inline static
References LSBEndian.
Referenced by GetEXIFProperty().
ReadPropertyUnsignedShort()
static unsigned short ReadPropertyUnsignedShort (const EndianType endian, const unsigned char * buffer) inline static
References LSBEndian.
Referenced by GetEXIFProperty().
RemoveImageProperty()
MagickExport char * RemoveImageProperty (Image * image, const char * property)
References _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::properties, RemoveNodeFromSplayTree(), _Image::signature, and TraceEvent.
ResetImagePropertyIterator()
MagickExport void ResetImagePropertyIterator (const Image * image)
References _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::properties, ResetSplayTreeIterator(), _Image::signature, and TraceEvent.
Referenced by IdentifyImage(), InterpretImageProperties(), and ResetImageAttributeIterator().
SetImageProperty()
MagickExport MagickBooleanType SetImageProperty (Image * image, const char * property, const char * value)
References AddValueToSplayTree(), _Image::background_color, _Image::bias, CastDoubleToLong(), CompareSplayTreeString(), _Image::compose, _Image::compression, ConstantString(), _Image::debug, _Image::delay, DeleteImageProperty(), _Image::depth, DestroyString(), _Image::dispose, _Image::exception, _Image::filename, _Image::gamma, GetMagickModule, GetPageGeometry(), _Image::gravity, GreaterValue, _Image::intensity, _Image::interpolate, _Image::iterations, LessValue, LocaleCompare(), LogMagickEvent(), MagickColorspaceOptions, MagickComposeOptions, MagickCompressOptions, MagickCoreSignature, MagickDisposeOptions, MagickFalse, MagickGravityOptions, MagickIntentOptions, MagickInterpolateOptions, MagickPixelIntensityOptions, MagickResolutionOptions, MagickTrue, MagickTypeOptions, NewSplayTree(), _Image::page, ParseAbsoluteGeometry(), ParseCommandOption(), ParseGeometry(), _Image::properties, QuantumRange, QueryColorDatabase(), RelinquishMagickMemory(), _Image::rendering_intent, _GeometryInfo::rho, RhoValue, SetImageColorspace(), _GeometryInfo::sigma, SigmaValue, _Image::signature, StringToDouble(), StringToDoubleInterval(), StringToUnsignedLong(), _Image::ticks_per_second, _Image::tile_offset, TraceEvent, _Image::type, _Image::units, _Image::x_resolution, and _Image::y_resolution.
Referenced by AutoThresholdImage(), DefineImageProperty(), FormatImageAttribute(), FormatImageAttributeList(), FormatImageProperty(), FormatImagePropertyList(), Get8BIMProperty(), GetEXIFProperty(), GetICCProperty(), GetImageProperty(), GetIPTCProperty(), PreviewImage(), ReadImage(), SetImageAttribute(), SignatureImage(), and ThumbnailImage().
SkipXMPValue()
static MagickBooleanType SkipXMPValue (const char * value) static
References MagickFalse, and MagickTrue.
Referenced by GetXMPProperty().
TraceBezierCurve()
static void TraceBezierCurve (char * message, PointInfo * last, PointInfo * point) inline static
References FormatLocaleString(), MagickPathExtent, _PointInfo::x, and _PointInfo::y.
Referenced by TraceSVGClippath().
TracePSClippath() [1/2]
static char * TracePSClippath (const unsigned char * , size_t , const size_t, const size_t) static
Referenced by Get8BIMProperty().
TracePSClippath() [2/2]
static char * TracePSClippath (const unsigned char * blob, size_t length, const size_t magick_unusedcolumns, const size_t magick_unusedrows) static
References AcquireString(), ConcatenateString(), DestroyString(), FormatLocaleString(), magick_unreferenced, MagickFalse, MagickMin, MagickTrue, MaxTextExtent, ReadPropertyMSBLong(), ReadPropertyMSBShort(), _PointInfo::x, and _PointInfo::y.
TraceSVGClippath()
static char * TraceSVGClippath (const unsigned char * blob, size_t length, const size_t columns, const size_t rows)
References AcquireString(), ConcatenateString(), DestroyString(), FormatLocaleString(), MagickFalse, MagickMin, MagickTrue, MaxTextExtent, ReadPropertyMSBLong(), ReadPropertyMSBShort(), TraceBezierCurve(), _PointInfo::x, and _PointInfo::y.
Referenced by Get8BIMProperty().