MagickCore: property.h File Reference
property.h File Reference
Functions
MagickExport char * GetNextImageProperty (const Image *)
MagickExport char * InterpretImageProperties (const ImageInfo *, Image *, const char *)
MagickExport char * RemoveImageProperty (Image *, const char *)
MagickExport const char * GetImageProperty (const Image *, const char *)
MagickExport const char * GetMagickProperty (const ImageInfo *, Image *, const char *)
MagickExport MagickBooleanType CloneImageProperties (Image *, const Image *)
MagickExport MagickBooleanType DefineImageProperty (Image *, const char *)
MagickExport MagickBooleanType DeleteImageProperty (Image *, const char *)
MagickExport MagickBooleanType FormatImageProperty (Image *, const char *, const char *,...) magick_attribute((__format__(__printf__
MagickExport MagickBooleanType SetImageProperty (Image *, const char *, const char *)
MagickExport void DestroyImageProperties (Image *)
MagickExport void ResetImagePropertyIterator (const Image *)
Function Documentation
CloneImageProperties()
MagickExport MagickBooleanType CloneImageProperties (Image * , const Image *)
DefineImageProperty()
MagickExport MagickBooleanType DefineImageProperty (Image * , const char *)
DeleteImageProperty()
MagickExport MagickBooleanType DeleteImageProperty (Image * , const char *)
DestroyImageProperties()
MagickExport void DestroyImageProperties (Image *)
FormatImageProperty()
MagickExport MagickBooleanType FormatImageProperty (Image * , const char * , const char * , ...)
GetImageProperty()
MagickExport const char * GetImageProperty (const Image * , const char *)
GetMagickProperty()
MagickExport const char * GetMagickProperty (const ImageInfo * image_info, Image * image, const char * property)
References BasePath, _ImageInfo::channel, _Image::colors, _Image::colorspace, _Image::columns, CommandOptionToMnemonic(), _Image::compose, _Image::compression, ConcatenateMagickString(), CopyMagickString(), _Image::depth, _Image::exception, ExtensionPath, _Image::filename, _ImageInfo::filename, FormatLocaleString(), FormatMagickSize(), _Image::gamma, GetBlobSize(), GetImageArtifact(), GetImageBoundingBox(), GetImageChannelEntropy(), GetImageChannelKurtosis(), GetImageChannelMean(), GetImageChannelRange(), GetImageDepth(), GetImageListLength(), GetImageProfile(), GetMagickCopyright(), GetMagickPrecision(), GetMagickPropertyLetter(), GetMagickVersion(), GetNextImageProfile(), GetNumberColors(), GetPageGeometry(), GetPathComponent(), GetStringInfoDatum(), GetStringInfoLength(), _ImageInfo::group, HeadPath, _RectangleInfo::height, IdentifyImageType(), _Image::interlace, IsOpaqueImage(), LocaleCompare(), LocaleLower(), LocaleNCompare(), _Image::magick, _Image::magick_columns, _Image::magick_filename, _Image::magick_rows, MagickColorspaceOptions, MagickComposeOptions, MagickCompressOptions, MagickFalse, MagickIntentOptions, MagickInterlaceOptions, MagickOrientationOptions, MagickPathExtent, MagickResolutionOptions, MagickTypeOptions, _Image::matte, MaxTextExtent, _ImageInfo::number_scenes, _Image::orientation, _Image::page, ParseAbsoluteGeometry(), PerceptibleReciprocal(), _Image::quality, _Image::rendering_intent, ResetImageProfileIterator(), _Image::rows, _Image::scene, _ImageInfo::scene, SetImageArtifact(), _ImageInfo::unique, _Image::units, _RectangleInfo::width, _RectangleInfo::x, _Image::x_resolution, _RectangleInfo::y, _Image::y_resolution, and _ImageInfo::zero.
Referenced by InterpretImageProperties().
GetNextImageProperty()
MagickExport char * GetNextImageProperty (const Image *)
InterpretImageProperties()
MagickExport char * InterpretImageProperties (const ImageInfo * , Image * , const char *)
RemoveImageProperty()
MagickExport char * RemoveImageProperty (Image * image, const char * property)
References _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::properties, RemoveNodeFromSplayTree(), _Image::signature, and TraceEvent.
ResetImagePropertyIterator()
MagickExport void ResetImagePropertyIterator (const Image * image)
References _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::properties, ResetSplayTreeIterator(), _Image::signature, and TraceEvent.
Referenced by IdentifyImage(), InterpretImageProperties(), and ResetImageAttributeIterator().
SetImageProperty()
MagickExport MagickBooleanType SetImageProperty (Image * image, const char * property, const char * value)
References AddValueToSplayTree(), _Image::background_color, _Image::bias, CastDoubleToLong(), CompareSplayTreeString(), _Image::compose, _Image::compression, ConstantString(), _Image::debug, _Image::delay, DeleteImageProperty(), _Image::depth, DestroyString(), _Image::dispose, _Image::exception, _Image::filename, _Image::gamma, GetMagickModule, GetPageGeometry(), _Image::gravity, GreaterValue, _Image::intensity, _Image::interpolate, _Image::iterations, LessValue, LocaleCompare(), LogMagickEvent(), MagickColorspaceOptions, MagickComposeOptions, MagickCompressOptions, MagickCoreSignature, MagickDisposeOptions, MagickFalse, MagickGravityOptions, MagickIntentOptions, MagickInterpolateOptions, MagickPixelIntensityOptions, MagickResolutionOptions, MagickTrue, MagickTypeOptions, NewSplayTree(), _Image::page, ParseAbsoluteGeometry(), ParseCommandOption(), ParseGeometry(), _Image::properties, QuantumRange, QueryColorDatabase(), RelinquishMagickMemory(), _Image::rendering_intent, _GeometryInfo::rho, RhoValue, SetImageColorspace(), _GeometryInfo::sigma, SigmaValue, _Image::signature, StringToDouble(), StringToDoubleInterval(), StringToUnsignedLong(), _Image::ticks_per_second, _Image::tile_offset, TraceEvent, _Image::type, _Image::units, _Image::x_resolution, and _Image::y_resolution.
Referenced by AutoThresholdImage(), DefineImageProperty(), FormatImageAttribute(), FormatImageAttributeList(), FormatImageProperty(), FormatImagePropertyList(), Get8BIMProperty(), GetEXIFProperty(), GetICCProperty(), GetImageProperty(), GetIPTCProperty(), PreviewImage(), ReadImage(), SetImageAttribute(), SignatureImage(), and ThumbnailImage().