MagickCore: quantum.c File Reference
quantum.c File Reference
#include "magick/studio.h"
#include "magick/attribute.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/color-private.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/cache.h"
#include "magick/cache-private.h"
#include "magick/colorspace.h"
#include "magick/colorspace-private.h"
#include "magick/constitute.h"
#include "magick/delegate.h"
#include "magick/geometry.h"
#include "magick/list.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/monitor.h"
#include "magick/option.h"
#include "magick/pixel.h"
#include "magick/pixel-private.h"
#include "magick/property.h"
#include "magick/quantum.h"
#include "magick/quantum-private.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/statistic.h"
#include "magick/stream.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/thread-private.h"
#include "magick/utility.h"
Macros
#define QuantumSignature 0xab
Functions
static void DestroyQuantumPixels (QuantumInfo *)
MagickExport QuantumInfo * AcquireQuantumInfo (const ImageInfo *image_info, Image *image)
static MagickBooleanType AcquireQuantumPixels (QuantumInfo *quantum_info, const size_t extent)
MagickExport QuantumInfo * DestroyQuantumInfo (QuantumInfo *quantum_info)
MagickExport size_t GetQuantumExtent (const Image *image, const QuantumInfo *quantum_info, const QuantumType quantum_type)
MagickExport EndianType GetQuantumEndian (const QuantumInfo *quantum_info)
MagickExport QuantumFormatType GetQuantumFormat (const QuantumInfo *quantum_info)
MagickExport void GetQuantumInfo (const ImageInfo *image_info, QuantumInfo *quantum_info)
MagickExport unsigned char * GetQuantumPixels (const QuantumInfo *quantum_info)
MagickExport QuantumType GetQuantumType (Image *image, ExceptionInfo *exception)
MagickPrivate void ResetQuantumState (QuantumInfo *quantum_info)
MagickExport void SetQuantumAlphaType (QuantumInfo *quantum_info, const QuantumAlphaType type)
MagickExport MagickBooleanType SetQuantumDepth (const Image *image, QuantumInfo *quantum_info, const size_t depth)
MagickExport MagickBooleanType SetQuantumEndian (const Image *image, QuantumInfo *quantum_info, const EndianType endian)
MagickExport MagickBooleanType SetQuantumFormat (const Image *image, QuantumInfo *quantum_info, const QuantumFormatType format)
MagickExport void SetQuantumImageType (Image *image, const QuantumType quantum_type)
MagickExport void SetQuantumPack (QuantumInfo *quantum_info, const MagickBooleanType pack)
MagickExport MagickBooleanType SetQuantumPad (const Image *image, QuantumInfo *quantum_info, const size_t pad)
MagickExport void SetQuantumMinIsWhite (QuantumInfo *quantum_info, const MagickBooleanType min_is_white)
MagickExport void SetQuantumQuantum (QuantumInfo *quantum_info, const size_t quantum)
MagickExport void SetQuantumScale (QuantumInfo *quantum_info, const double scale)
Macro Definition Documentation
QuantumSignature
#define QuantumSignature 0xab
Function Documentation
AcquireQuantumInfo()
MagickExport QuantumInfo * AcquireQuantumInfo (const ImageInfo * image_info, Image * image)
References AcquireMagickMemory(), _Image::depth, DestroyQuantumInfo(), _Image::endian, _QuantumInfo::endian, GetQuantumInfo(), MagickCoreSignature, MagickFalse, ResourceLimitFatalError, SetQuantumDepth(), _QuantumInfo::signature, and ThrowFatalException.
Referenced by PopImagePixels(), PushImagePixels(), SignatureImage(), and StreamImage().
AcquireQuantumPixels()
static MagickBooleanType AcquireQuantumPixels (QuantumInfo * quantum_info, const size_t extent) static
References AcquireQuantumMemory(), AcquireVirtualMemory(), DestroyQuantumPixels(), _QuantumInfo::extent, GetMagickResourceLimit(), GetVirtualMemoryBlob(), MagickCoreSignature, MagickFalse, MagickTrue, _QuantumInfo::number_threads, _QuantumInfo::pixels, QuantumSignature, _QuantumInfo::signature, and ThreadResource.
Referenced by SetQuantumDepth().
DestroyQuantumInfo()
MagickExport QuantumInfo * DestroyQuantumInfo (QuantumInfo * quantum_info)
References DestroyQuantumPixels(), DestroySemaphoreInfo(), MagickCoreSignature, _QuantumInfo::pixels, RelinquishMagickMemory(), _QuantumInfo::semaphore, and _QuantumInfo::signature.
Referenced by AcquireQuantumInfo(), DestroyStreamInfo(), PopImagePixels(), PushImagePixels(), SignatureImage(), and StreamImage().
DestroyQuantumPixels()
static void DestroyQuantumPixels (QuantumInfo * quantum_info) static
References _QuantumInfo::extent, GetVirtualMemoryBlob(), MagickCoreSignature, _QuantumInfo::number_threads, _QuantumInfo::pixels, QuantumSignature, RelinquishMagickMemory(), RelinquishVirtualMemory(), and _QuantumInfo::signature.
Referenced by AcquireQuantumPixels(), DestroyQuantumInfo(), and SetQuantumDepth().
GetQuantumEndian()
MagickExport EndianType GetQuantumEndian (const QuantumInfo * quantum_info)
References _QuantumInfo::endian, MagickCoreSignature, and _QuantumInfo::signature.
GetQuantumExtent()
MagickExport size_t GetQuantumExtent (const Image * image, const QuantumInfo * quantum_info, const QuantumType quantum_type)
References BGRAQuantum, BGRQuantum, CbYCrAQuantum, CbYCrQuantum, CbYCrYQuantum, CMYKAQuantum, CMYKQuantum, _Image::columns, _QuantumInfo::depth, GrayAlphaQuantum, IndexAlphaQuantum, MagickCoreSignature, MagickFalse, _QuantumInfo::pack, RGBAQuantum, RGBOQuantum, RGBQuantum, and _QuantumInfo::signature.
Referenced by ExportQuantumPixels(), and ImportQuantumPixels().
GetQuantumFormat()
MagickExport QuantumFormatType GetQuantumFormat (const QuantumInfo * quantum_info)
References _QuantumInfo::format, MagickCoreSignature, and _QuantumInfo::signature.
GetQuantumInfo()
MagickExport void GetQuantumInfo (const ImageInfo * image_info, QuantumInfo * quantum_info)
References AllocateSemaphoreInfo(), _ImageInfo::endian, _QuantumInfo::endian, _QuantumInfo::format, GetImageOption(), LocaleCompare(), MagickCoreSignature, MagickFalse, MagickQuantumFormatOptions, MagickTrue, _QuantumInfo::maximum, _QuantumInfo::min_is_white, _QuantumInfo::minimum, _QuantumInfo::pack, ParseCommandOption(), _QuantumInfo::quantum, QuantumRange, ResetQuantumState(), _QuantumInfo::scale, _QuantumInfo::semaphore, _QuantumInfo::signature, and StringToDouble().
Referenced by AcquireQuantumInfo().
GetQuantumPixels()
MagickExport unsigned char * GetQuantumPixels (const QuantumInfo * quantum_info)
References GetOpenMPThreadId(), GetVirtualMemoryBlob(), MagickCoreSignature, _QuantumInfo::pixels, and _QuantumInfo::signature.
Referenced by ExportQuantumPixels(), ImportQuantumPixels(), and SignatureImage().
GetQuantumType()
MagickExport QuantumType GetQuantumType (Image * image, ExceptionInfo * exception)
References CMYKAQuantum, CMYKColorspace, CMYKQuantum, _Image::colorspace, _Image::debug, _Image::filename, GetMagickModule, GrayAlphaQuantum, GrayQuantum, IndexAlphaQuantum, IndexQuantum, IsGrayColorspace(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::matte, PseudoClass, RGBAQuantum, RGBQuantum, _Image::signature, _Image::storage_class, and TraceEvent.
ResetQuantumState()
MagickPrivate void ResetQuantumState (QuantumInfo * quantum_info)
References _QuantumState::bits, _QuantumState::inverse_scale, MagickCoreSignature, MagickEpsilon, _QuantumState::mask, _QuantumState::pixel, _QuantumInfo::scale, _QuantumInfo::signature, and _QuantumInfo::state.
Referenced by ExportQuantumPixels(), GetQuantumInfo(), and ImportQuantumPixels().
SetQuantumAlphaType()
MagickExport void SetQuantumAlphaType (QuantumInfo * quantum_info, const QuantumAlphaType type)
References _QuantumInfo::alpha_type, MagickCoreSignature, and _QuantumInfo::signature.
SetQuantumDepth()
MagickExport MagickBooleanType SetQuantumDepth (const Image * image, QuantumInfo * quantum_info, const size_t depth)
References AcquireQuantumPixels(), _Image::columns, _Image::debug, _QuantumInfo::depth, DestroyQuantumPixels(), _Image::filename, FloatingPointQuantumFormat, _QuantumInfo::format, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickMax, MagickMin, _QuantumInfo::pad, _QuantumInfo::pixels, _Image::rows, _Image::signature, _QuantumInfo::signature, and TraceEvent.
Referenced by AcquireQuantumInfo(), SetQuantumEndian(), SetQuantumFormat(), and SetQuantumPad().
SetQuantumEndian()
MagickExport MagickBooleanType SetQuantumEndian (const Image * image, QuantumInfo * quantum_info, const EndianType endian)
References _Image::debug, _QuantumInfo::depth, _QuantumInfo::endian, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, SetQuantumDepth(), _Image::signature, _QuantumInfo::signature, and TraceEvent.
SetQuantumFormat()
MagickExport MagickBooleanType SetQuantumFormat (const Image * image, QuantumInfo * quantum_info, const QuantumFormatType format)
References _Image::debug, _QuantumInfo::depth, _Image::filename, _QuantumInfo::format, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, SetQuantumDepth(), _Image::signature, _QuantumInfo::signature, and TraceEvent.
SetQuantumImageType()
MagickExport void SetQuantumImageType (Image * image, const QuantumType quantum_type)
References BilevelType, BlackQuantum, CMYKAQuantum, CMYKQuantum, ColorSeparationType, CyanQuantum, _Image::debug, _Image::depth, _Image::filename, GetMagickModule, GrayAlphaQuantum, GrayQuantum, GrayscaleType, IndexAlphaQuantum, IndexQuantum, LogMagickEvent(), MagentaQuantum, MagickCoreSignature, MagickFalse, PaletteType, _Image::signature, TraceEvent, TrueColorType, _Image::type, and YellowQuantum.
SetQuantumMinIsWhite()
MagickExport void SetQuantumMinIsWhite (QuantumInfo * quantum_info, const MagickBooleanType min_is_white)
References MagickCoreSignature, _QuantumInfo::min_is_white, and _QuantumInfo::signature.
SetQuantumPack()
MagickExport void SetQuantumPack (QuantumInfo * quantum_info, const MagickBooleanType pack)
References MagickCoreSignature, _QuantumInfo::pack, and _QuantumInfo::signature.
SetQuantumPad()
MagickExport MagickBooleanType SetQuantumPad (const Image * image, QuantumInfo * quantum_info, const size_t pad)
References _Image::debug, _QuantumInfo::depth, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _QuantumInfo::pad, SetQuantumDepth(), _Image::signature, _QuantumInfo::signature, and TraceEvent.
SetQuantumQuantum()
MagickExport void SetQuantumQuantum (QuantumInfo * quantum_info, const size_t quantum)
References MagickCoreSignature, _QuantumInfo::quantum, and _QuantumInfo::signature.
SetQuantumScale()
MagickExport void SetQuantumScale (QuantumInfo * quantum_info, const double scale)
References MagickCoreSignature, _QuantumInfo::scale, and _QuantumInfo::signature.