MagickCore: quantize.h File Reference
quantize.h File Reference
#include "magick/colorspace.h"
Data Structures
struct _QuantizeInfo
Typedefs
typedef struct _QuantizeInfo QuantizeInfo
Enumerations
enum DitherMethod { UndefinedDitherMethod , NoDitherMethod , RiemersmaDitherMethod , FloydSteinbergDitherMethod }
Functions
MagickExport MagickBooleanType CompressImageColormap (Image *)
MagickExport MagickBooleanType GetImageQuantizeError (Image *)
MagickExport MagickBooleanType PosterizeImage (Image *, const size_t, const MagickBooleanType)
MagickExport MagickBooleanType PosterizeImageChannel (Image *, const ChannelType, const size_t, const MagickBooleanType)
MagickExport MagickBooleanType QuantizeImage (const QuantizeInfo *, Image *)
MagickExport MagickBooleanType QuantizeImages (const QuantizeInfo *, Image *)
MagickExport MagickBooleanType RemapImage (const QuantizeInfo *, Image *, const Image *)
MagickExport MagickBooleanType RemapImages (const QuantizeInfo *, Image *, const Image *)
MagickExport QuantizeInfo * AcquireQuantizeInfo (const ImageInfo *)
MagickExport QuantizeInfo * CloneQuantizeInfo (const QuantizeInfo *)
MagickExport QuantizeInfo * DestroyQuantizeInfo (QuantizeInfo *)
MagickExport void GetQuantizeInfo (QuantizeInfo *)
Typedef Documentation
QuantizeInfo
typedef struct _QuantizeInfo QuantizeInfo
Enumeration Type Documentation
DitherMethod
enum DitherMethod
Enumerator
UndefinedDitherMethod
NoDitherMethod
RiemersmaDitherMethod
FloydSteinbergDitherMethod
Function Documentation
AcquireQuantizeInfo()
MagickExport QuantizeInfo * AcquireQuantizeInfo (const ImageInfo *)
CloneQuantizeInfo()
MagickExport QuantizeInfo * CloneQuantizeInfo (const QuantizeInfo *)
CompressImageColormap()
MagickExport MagickBooleanType CompressImageColormap (Image *)
DestroyQuantizeInfo()
MagickExport QuantizeInfo * DestroyQuantizeInfo (QuantizeInfo * quantize_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, RelinquishMagickMemory(), _QuantizeInfo::signature, and TraceEvent.
Referenced by DestroyCubeInfo(), PosterizeImageChannel(), and SetImageType().
GetImageQuantizeError()
MagickExport MagickBooleanType GetImageQuantizeError (Image *)
GetQuantizeInfo()
MagickExport void GetQuantizeInfo (QuantizeInfo * quantize_info)
References _QuantizeInfo::colorspace, _QuantizeInfo::dither, _QuantizeInfo::dither_method, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _QuantizeInfo::measure_error, _QuantizeInfo::number_colors, RiemersmaDitherMethod, _QuantizeInfo::signature, TraceEvent, and UndefinedColorspace.
Referenced by AcquireQuantizeInfo(), CloneQuantizeInfo(), CompressImageColormap(), MapImage(), MapImages(), and PreviewImage().
PosterizeImage()
MagickExport MagickBooleanType PosterizeImage (Image * , const size_t, const MagickBooleanType)
PosterizeImageChannel()
MagickExport MagickBooleanType PosterizeImageChannel (Image * , const ChannelType, const size_t, const MagickBooleanType)
QuantizeImage()
MagickExport MagickBooleanType QuantizeImage (const QuantizeInfo * , Image *)
QuantizeImages()
MagickExport MagickBooleanType QuantizeImages (const QuantizeInfo * , Image *)
RemapImage()
MagickExport MagickBooleanType RemapImage (const QuantizeInfo * , Image * , const Image *)
RemapImages()
MagickExport MagickBooleanType RemapImages (const QuantizeInfo * quantize_info, Image * images, const Image * remap_image)
References AssignImageColors(), ClassifyImageColors(), _CubeInfo::colors, _Image::debug, DestroyCubeInfo(), _Image::exception, _Image::filename, GetCubeInfo(), GetMagickModule, GetNextImageInList(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MaxTreeDepth, _QuantizeInfo::number_colors, _CubeInfo::quantize_info, QuantizeImages(), ResourceLimitError, _Image::signature, ThrowBinaryImageException, and TraceEvent.
Referenced by AffinityImages(), and MapImages().