MagickCore: quantum-import.c File Reference
quantum-import.c File Reference
#include "magick/studio.h"
#include "magick/property.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/color-private.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/cache.h"
#include "magick/constitute.h"
#include "magick/delegate.h"
#include "magick/geometry.h"
#include "magick/list.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/monitor.h"
#include "magick/option.h"
#include "magick/pixel.h"
#include "magick/pixel-private.h"
#include "magick/quantum.h"
#include "magick/quantum-private.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/statistic.h"
#include "magick/stream.h"
#include "magick/string_.h"
#include "magick/utility.h"
Functions
static IndexPacket PushColormapIndex (const Image *image, const size_t index, MagickBooleanType *range_exception)
static const unsigned char * PushDoublePixel (const QuantumInfo *quantum_info, const unsigned char *magick_restrict pixels, double *pixel)
static float ScaleFloatPixel (const QuantumInfo *quantum_info, const unsigned char *quantum)
static const unsigned char * PushQuantumFloatPixel (const QuantumInfo *quantum_info, const unsigned char *magick_restrict pixels, float *pixel)
static const unsigned char * PushQuantumFloat24Pixel (const QuantumInfo *quantum_info, const unsigned char *magick_restrict pixels, float *pixel)
static const unsigned char * PushQuantumPixel (QuantumInfo *quantum_info, const unsigned char *magick_restrict pixels, unsigned int *quantum)
static const unsigned char * PushQuantumLongPixel (QuantumInfo *quantum_info, const unsigned char *magick_restrict pixels, unsigned int *quantum)
static void ImportAlphaQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q)
static void ImportBGRQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q)
static void ImportBGRAQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q)
static void ImportBGROQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q)
static void ImportBlackQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q, IndexPacket *magick_restrict indexes, ExceptionInfo *exception)
static void ImportBlueQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q)
static void ImportCbYCrYQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q)
static void ImportCMYKQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q, IndexPacket *magick_restrict indexes, ExceptionInfo *exception)
static void ImportCMYKAQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q, IndexPacket *magick_restrict indexes, ExceptionInfo *exception)
static void ImportCMYKOQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q, IndexPacket *magick_restrict indexes, ExceptionInfo *exception)
static void ImportGrayQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q)
static void ImportGrayAlphaQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q)
static void ImportGreenQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q)
static void ImportIndexQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q, IndexPacket *magick_restrict indexes, ExceptionInfo *exception)
static void ImportIndexAlphaQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q, IndexPacket *magick_restrict indexes, ExceptionInfo *exception)
static void ImportRedQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q)
static void ImportRGBQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q)
static void ImportRGBAQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q)
static void ImportRGBOQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q)
MagickExport size_t ImportQuantumPixels (Image *image, CacheView *image_view, const QuantumInfo *quantum_info, const QuantumType quantum_type, const unsigned char *magick_restrict pixels, ExceptionInfo *exception)
Function Documentation
ImportAlphaQuantum()
static void ImportAlphaQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q) static
References ClampToQuantum(), _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetQuantumRange(), HalfToSinglePrecision(), _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, ScaleAnyToQuantum(), and SetPixelAlpha.
Referenced by ImportQuantumPixels().
ImportBGRAQuantum()
static void ImportBGRAQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q) static
References ClampToQuantum(), _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetQuantumRange(), HalfToSinglePrecision(), MagickFalse, _QuantumInfo::pack, _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, ScaleAnyToQuantum(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, and SetPixelRed.
Referenced by ImportQuantumPixels().
ImportBGROQuantum()
static void ImportBGROQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q) static
References ClampToQuantum(), _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetQuantumRange(), HalfToSinglePrecision(), MagickFalse, _QuantumInfo::pack, _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, ScaleAnyToQuantum(), SetPixelBlue, SetPixelGreen, SetPixelOpacity, and SetPixelRed.
Referenced by ImportQuantumPixels().
ImportBGRQuantum()
static void ImportBGRQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q) static
References ClampToQuantum(), _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetQuantumRange(), HalfToSinglePrecision(), MagickFalse, OpaqueOpacity, _QuantumInfo::pack, _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumLongPixel(), PushQuantumPixel(), PushShortPixel(), _QuantumInfo::quantum, QuantumRange, ScaleAnyToQuantum(), SetPixelBlue, SetPixelGreen, SetPixelOpacity, and SetPixelRed.
Referenced by ImportQuantumPixels().
ImportBlackQuantum()
static void ImportBlackQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q, IndexPacket *magick_restrict indexes, ExceptionInfo * exception) static
References ClampToQuantum(), CMYKColorspace, _Image::colorspace, _QuantumInfo::depth, _QuantumInfo::endian, _Image::filename, FloatingPointQuantumFormat, _QuantumInfo::format, GetMagickModule, GetQuantumRange(), HalfToSinglePrecision(), ImageError, _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, ScaleAnyToQuantum(), SetPixelIndex, and ThrowMagickException().
Referenced by ImportQuantumPixels().
ImportBlueQuantum()
static void ImportBlueQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q) static
References ClampToQuantum(), _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetQuantumRange(), HalfToSinglePrecision(), _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, ScaleAnyToQuantum(), and SetPixelBlue.
Referenced by ImportQuantumPixels().
ImportCbYCrYQuantum()
static void ImportCbYCrYQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q) static
References _Image::depth, _QuantumInfo::depth, _QuantumInfo::endian, GetQuantumRange(), MagickFalse, _QuantumInfo::pack, _QuantumInfo::pad, PushLongPixel(), PushQuantumPixel(), ScaleAnyToQuantum(), SetPixelBlue, SetPixelGreen, and SetPixelRed.
Referenced by ImportQuantumPixels().
ImportCMYKAQuantum()
static void ImportCMYKAQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q, IndexPacket *magick_restrict indexes, ExceptionInfo * exception) static
References ClampToQuantum(), CMYKColorspace, _Image::colorspace, _Image::depth, _QuantumInfo::depth, _QuantumInfo::endian, _Image::filename, FloatingPointQuantumFormat, _QuantumInfo::format, GetMagickModule, GetQuantumRange(), HalfToSinglePrecision(), ImageError, _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, ScaleAnyToQuantum(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelRed, and ThrowMagickException().
Referenced by ImportQuantumPixels().
ImportCMYKOQuantum()
static void ImportCMYKOQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q, IndexPacket *magick_restrict indexes, ExceptionInfo * exception) static
References ClampToQuantum(), CMYKColorspace, _Image::colorspace, _Image::depth, _QuantumInfo::depth, _QuantumInfo::endian, _Image::filename, FloatingPointQuantumFormat, _QuantumInfo::format, GetMagickModule, GetQuantumRange(), HalfToSinglePrecision(), ImageError, _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, ScaleAnyToQuantum(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, and ThrowMagickException().
Referenced by ImportQuantumPixels().
ImportCMYKQuantum()
static void ImportCMYKQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q, IndexPacket *magick_restrict indexes, ExceptionInfo * exception) static
References ClampToQuantum(), CMYKColorspace, _Image::colorspace, _QuantumInfo::depth, _QuantumInfo::endian, _Image::filename, FloatingPointQuantumFormat, _QuantumInfo::format, GetMagickModule, GetQuantumRange(), HalfToSinglePrecision(), ImageError, _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, ScaleAnyToQuantum(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelRed, and ThrowMagickException().
Referenced by ImportQuantumPixels().
ImportGrayAlphaQuantum()
static void ImportGrayAlphaQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q) static
References ClampToQuantum(), _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetPixelRed, GetQuantumRange(), HalfToSinglePrecision(), OpaqueOpacity, _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, ScaleAnyToQuantum(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelOpacity, SetPixelRed, and TransparentOpacity.
Referenced by ImportQuantumPixels().
ImportGrayQuantum()
static void ImportGrayQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q) static
References ClampToQuantum(), _QuantumInfo::depth, _Image::endian, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetPixelRed, GetQuantumRange(), HalfToSinglePrecision(), LSBEndian, MagickFalse, _QuantumInfo::min_is_white, OpaqueOpacity, _QuantumInfo::pack, _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, ScaleAnyToQuantum(), SetPixelBlue, SetPixelGreen, SetPixelOpacity, SetPixelRed, and SignedQuantumFormat.
Referenced by ImportQuantumPixels().
ImportGreenQuantum()
static void ImportGreenQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q) static
References ClampToQuantum(), _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetQuantumRange(), HalfToSinglePrecision(), _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, ScaleAnyToQuantum(), and SetPixelGreen.
Referenced by ImportQuantumPixels().
ImportIndexAlphaQuantum()
static void ImportIndexAlphaQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q, IndexPacket *magick_restrict indexes, ExceptionInfo * exception) static
References ClampToQuantum(), _Image::colormap, CorruptImageError, _QuantumInfo::depth, _QuantumInfo::endian, _Image::filename, FloatingPointQuantumFormat, _QuantumInfo::format, GetMagickModule, GetPixelIndex, GetPixelRed, GetQuantumRange(), HalfToSinglePrecision(), ImageError, MagickFalse, _QuantumInfo::min_is_white, OpaqueOpacity, _QuantumInfo::pad, PseudoClass, PushCharPixel(), PushColormapIndex(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, ScaleAnyToQuantum(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, SetPixelRGBO, _Image::storage_class, ThrowMagickException(), and TransparentOpacity.
Referenced by ImportQuantumPixels().
ImportIndexQuantum()
static void ImportIndexQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q, IndexPacket *magick_restrict indexes, ExceptionInfo * exception) static
References ClampToQuantum(), _Image::colormap, CorruptImageError, _QuantumInfo::depth, _QuantumInfo::endian, _Image::filename, FloatingPointQuantumFormat, _QuantumInfo::format, GetMagickModule, GetPixelIndex, HalfToSinglePrecision(), ImageError, MagickFalse, _QuantumInfo::min_is_white, _QuantumInfo::pad, PseudoClass, PushCharPixel(), PushColormapIndex(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, SetPixelIndex, SetPixelRGBO, _Image::storage_class, and ThrowMagickException().
Referenced by ImportQuantumPixels().
ImportQuantumPixels()
MagickExport size_t ImportQuantumPixels (Image * image, CacheView * image_view, const QuantumInfo * quantum_info, const QuantumType quantum_type, const unsigned char *magick_restrict pixels, ExceptionInfo * exception)
References _QuantumInfo::alpha_type, AlphaQuantum, AssociatedQuantumAlpha, BGRAQuantum, BGROQuantum, BGRQuantum, BlackQuantum, BlueQuantum, CbYCrAQuantum, CbYCrQuantum, CbYCrYQuantum, ClampToQuantum(), CMYKAQuantum, CMYKColorspace, CMYKOQuantum, CMYKQuantum, _Image::colorspace, CyanQuantum, _Image::debug, _Image::filename, GetAuthenticIndexQueue(), GetAuthenticPixelQueue(), GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixelQueue(), GetCacheViewExtent(), GetImageExtent(), GetMagickModule, GetPixelAlpha, GetPixelBlack, GetPixelBlue, GetPixelGreen, GetPixelRed, GetQuantumExtent(), GetQuantumPixels(), GrayAlphaQuantum, GrayQuantum, GreenQuantum, ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGROQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCbYCrYQuantum(), ImportCMYKAQuantum(), ImportCMYKOQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBOQuantum(), ImportRGBQuantum(), IndexAlphaQuantum, IndexQuantum, LogMagickEvent(), MagentaQuantum, magick_restrict, MagickCoreSignature, MagickFalse, PerceptibleReciprocal(), QuantumScale, RedQuantum, ResetQuantumState(), RGBAQuantum, RGBOQuantum, RGBQuantum, SetPixelBlack, SetPixelBlue, SetPixelGreen, SetPixelRed, _Image::signature, _QuantumInfo::signature, TraceEvent, and YellowQuantum.
Referenced by PushImagePixels().
ImportRedQuantum()
static void ImportRedQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q) static
References ClampToQuantum(), _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetQuantumRange(), HalfToSinglePrecision(), _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, ScaleAnyToQuantum(), and SetPixelRed.
Referenced by ImportQuantumPixels().
ImportRGBAQuantum()
static void ImportRGBAQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q) static
References ClampToQuantum(), _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetQuantumRange(), HalfToSinglePrecision(), MagickFalse, _QuantumInfo::pack, _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, ScaleAnyToQuantum(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, and SetPixelRed.
Referenced by ImportQuantumPixels().
ImportRGBOQuantum()
static void ImportRGBOQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q) static
References ClampToQuantum(), _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetQuantumRange(), HalfToSinglePrecision(), MagickFalse, _QuantumInfo::pack, _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumPixel(), PushShortPixel(), QuantumRange, ScaleAnyToQuantum(), SetPixelBlue, SetPixelGreen, SetPixelOpacity, and SetPixelRed.
Referenced by ImportQuantumPixels().
ImportRGBQuantum()
static void ImportRGBQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const unsigned char *magick_restrict p, PixelPacket *magick_restrict q) static
References ClampToQuantum(), _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetQuantumRange(), HalfToSinglePrecision(), MagickFalse, OpaqueOpacity, _QuantumInfo::pack, _QuantumInfo::pad, PushCharPixel(), PushDoublePixel(), PushLongPixel(), PushQuantumFloat24Pixel(), PushQuantumFloatPixel(), PushQuantumLongPixel(), PushQuantumPixel(), PushShortPixel(), _QuantumInfo::quantum, QuantumRange, ScaleAnyToQuantum(), SetPixelBlue, SetPixelGreen, SetPixelOpacity, and SetPixelRed.
Referenced by ImportQuantumPixels().
PushColormapIndex()
static IndexPacket PushColormapIndex (const Image * image, const size_t index, MagickBooleanType * range_exception) inline static
References MagickTrue.
Referenced by ImportIndexAlphaQuantum(), and ImportIndexQuantum().
PushDoublePixel()
static const unsigned char * PushDoublePixel (const QuantumInfo * quantum_info, const unsigned char *magick_restrict pixels, double * pixel) inline static
References _QuantumInfo::endian, LSBEndian, _QuantumInfo::minimum, and _QuantumInfo::scale.
Referenced by ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGROQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCMYKAQuantum(), ImportCMYKOQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBOQuantum(), and ImportRGBQuantum().
PushQuantumFloat24Pixel()
static const unsigned char * PushQuantumFloat24Pixel (const QuantumInfo * quantum_info, const unsigned char *magick_restrict pixels, float * pixel) inline static
References _QuantumInfo::endian, LSBEndian, and ScaleFloatPixel().
Referenced by ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGROQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCMYKAQuantum(), ImportCMYKOQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBOQuantum(), and ImportRGBQuantum().
PushQuantumFloatPixel()
static const unsigned char * PushQuantumFloatPixel (const QuantumInfo * quantum_info, const unsigned char *magick_restrict pixels, float * pixel) inline static
References _QuantumInfo::endian, LSBEndian, and ScaleFloatPixel().
Referenced by ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGROQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCMYKAQuantum(), ImportCMYKOQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBOQuantum(), and ImportRGBQuantum().
PushQuantumLongPixel()
static const unsigned char * PushQuantumLongPixel (QuantumInfo * quantum_info, const unsigned char *magick_restrict pixels, unsigned int * quantum) inline static
References _QuantumState::bits, _QuantumInfo::depth, _QuantumInfo::endian, _QuantumState::mask, _QuantumState::pixel, PushLongPixel(), and _QuantumInfo::state.
Referenced by ImportBGRQuantum(), and ImportRGBQuantum().
PushQuantumPixel()
static const unsigned char * PushQuantumPixel (QuantumInfo * quantum_info, const unsigned char *magick_restrict pixels, unsigned int * quantum) inline static
References _QuantumState::bits, _QuantumInfo::depth, _QuantumState::pixel, and _QuantumInfo::state.
Referenced by ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGROQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCbYCrYQuantum(), ImportCMYKAQuantum(), ImportCMYKOQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBOQuantum(), and ImportRGBQuantum().
ScaleFloatPixel()
static float ScaleFloatPixel (const QuantumInfo * quantum_info, const unsigned char * quantum) inline static
References _QuantumInfo::minimum, and _QuantumInfo::scale.
Referenced by PushQuantumFloat24Pixel(), and PushQuantumFloatPixel().