MagickCore: quantum-export.c File Reference
quantum-export.c File Reference
#include "magick/studio.h"
#include "magick/property.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/color-private.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/cache.h"
#include "magick/constitute.h"
#include "magick/delegate.h"
#include "magick/geometry.h"
#include "magick/list.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/monitor.h"
#include "magick/option.h"
#include "magick/pixel.h"
#include "magick/pixel-private.h"
#include "magick/quantum.h"
#include "magick/quantum-private.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/statistic.h"
#include "magick/stream.h"
#include "magick/string_.h"
#include "magick/utility.h"
Functions
static unsigned char * PopDoublePixel (QuantumInfo *quantum_info, const double pixel, unsigned char *magick_restrict pixels)
static unsigned char * PopFloatPixel (QuantumInfo *quantum_info, const float pixel, unsigned char *magick_restrict pixels)
static unsigned char * PopQuantumPixel (QuantumInfo *quantum_info, const QuantumAny pixel, unsigned char *magick_restrict pixels)
static unsigned char * PopQuantumLongPixel (QuantumInfo *quantum_info, const size_t pixel, unsigned char *magick_restrict pixels)
static void ExportAlphaQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q)
static void ExportBGRQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q)
static void ExportBGRAQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q)
static void ExportBGROQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q)
static void ExportBlackQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, const IndexPacket *magick_restrict indexes, unsigned char *magick_restrict q, ExceptionInfo *exception)
static void ExportBlueQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q)
static void ExportCbYCrYQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q)
static void ExportCMYKQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, const IndexPacket *magick_restrict indexes, unsigned char *magick_restrict q, ExceptionInfo *exception)
static void ExportCMYKAQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, const IndexPacket *magick_restrict indexes, unsigned char *magick_restrict q, ExceptionInfo *exception)
static void ExportCMYKOQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, const IndexPacket *magick_restrict indexes, unsigned char *magick_restrict q, ExceptionInfo *exception)
static void ExportGrayQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q)
static void ExportGrayAlphaQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q)
static void ExportGreenQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q)
static void ExportIndexQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, const IndexPacket *magick_restrict indexes, unsigned char *magick_restrict q, ExceptionInfo *exception)
static void ExportIndexAlphaQuantum (const Image *image, QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, const IndexPacket *magick_restrict indexes, unsigned char *magick_restrict q, ExceptionInfo *exception)
static void ExportOpacityQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q)
static void ExportRedQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q)
static void ExportRGBQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q)
static void ExportRGBAQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q)
static void ExportRGBOQuantum (QuantumInfo *quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q)
MagickExport size_t ExportQuantumPixels (const Image *image, const CacheView *image_view, const QuantumInfo *quantum_info, const QuantumType quantum_type, unsigned char *magick_restrict pixels, ExceptionInfo *exception)
Function Documentation
ExportAlphaQuantum()
static void ExportAlphaQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q) static
References _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetPixelAlpha, GetPixelOpacity, GetQuantumRange(), _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumPixel(), PopShortPixel(), QuantumRange, QuantumScale, ScaleQuantumToAny(), and SinglePrecisionToHalf().
Referenced by ExportQuantumPixels().
ExportBGRAQuantum()
static void ExportBGRAQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q) static
References _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelRed, GetQuantumRange(), MagickFalse, _QuantumInfo::pack, _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumLongPixel(), PopQuantumPixel(), PopShortPixel(), _QuantumInfo::quantum, QuantumScale, ScaleQuantumToAny(), and SinglePrecisionToHalf().
Referenced by ExportQuantumPixels().
ExportBGROQuantum()
static void ExportBGROQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q) static
References _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetPixelBlue, GetPixelGreen, GetPixelOpacity, GetPixelRed, GetQuantumRange(), MagickFalse, _QuantumInfo::pack, _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumLongPixel(), PopQuantumPixel(), PopShortPixel(), _QuantumInfo::quantum, QuantumScale, ScaleQuantumToAny(), and SinglePrecisionToHalf().
Referenced by ExportQuantumPixels().
ExportBGRQuantum()
static void ExportBGRQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q) static
References _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetPixelBlue, GetPixelGreen, GetPixelRed, GetQuantumRange(), MagickFalse, _QuantumInfo::pack, _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumLongPixel(), PopQuantumPixel(), PopShortPixel(), _QuantumInfo::quantum, QuantumScale, ScaleQuantumToAny(), and SinglePrecisionToHalf().
Referenced by ExportQuantumPixels().
ExportBlackQuantum()
static void ExportBlackQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, const IndexPacket *magick_restrict indexes, unsigned char *magick_restrict q, ExceptionInfo * exception) static
References CMYKColorspace, _Image::colorspace, _QuantumInfo::depth, _QuantumInfo::endian, _Image::filename, FloatingPointQuantumFormat, _QuantumInfo::format, GetMagickModule, GetPixelIndex, GetQuantumRange(), ImageError, _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumPixel(), PopShortPixel(), QuantumScale, ScaleQuantumToAny(), SinglePrecisionToHalf(), and ThrowMagickException().
Referenced by ExportQuantumPixels().
ExportBlueQuantum()
static void ExportBlueQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q) static
References _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetPixelBlue, GetQuantumRange(), _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumPixel(), PopShortPixel(), QuantumScale, ScaleQuantumToAny(), and SinglePrecisionToHalf().
Referenced by ExportQuantumPixels().
ExportCbYCrYQuantum()
static void ExportCbYCrYQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q) static
References _QuantumInfo::depth, _QuantumInfo::endian, GetPixelBlue, GetPixelGreen, GetPixelRed, GetQuantumRange(), MagickFalse, _QuantumInfo::pack, _QuantumInfo::pad, PopLongPixel(), PopQuantumPixel(), and ScaleQuantumToAny().
Referenced by ExportQuantumPixels().
ExportCMYKAQuantum()
static void ExportCMYKAQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, const IndexPacket *magick_restrict indexes, unsigned char *magick_restrict q, ExceptionInfo * exception) static
References CMYKColorspace, _Image::colorspace, _QuantumInfo::depth, _QuantumInfo::endian, _Image::filename, FloatingPointQuantumFormat, _QuantumInfo::format, GetMagickModule, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelRed, GetQuantumRange(), ImageError, _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumPixel(), PopShortPixel(), QuantumScale, ScaleQuantumToAny(), SinglePrecisionToHalf(), and ThrowMagickException().
Referenced by ExportQuantumPixels().
ExportCMYKOQuantum()
static void ExportCMYKOQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, const IndexPacket *magick_restrict indexes, unsigned char *magick_restrict q, ExceptionInfo * exception) static
References CMYKColorspace, _Image::colorspace, _QuantumInfo::depth, _QuantumInfo::endian, _Image::filename, FloatingPointQuantumFormat, _QuantumInfo::format, GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, GetQuantumRange(), ImageError, _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumPixel(), PopShortPixel(), QuantumScale, ScaleQuantumToAny(), SinglePrecisionToHalf(), and ThrowMagickException().
Referenced by ExportQuantumPixels().
ExportCMYKQuantum()
static void ExportCMYKQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, const IndexPacket *magick_restrict indexes, unsigned char *magick_restrict q, ExceptionInfo * exception) static
References CMYKColorspace, _Image::colorspace, _QuantumInfo::depth, _QuantumInfo::endian, _Image::filename, FloatingPointQuantumFormat, _QuantumInfo::format, GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelRed, GetQuantumRange(), ImageError, _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumPixel(), PopShortPixel(), QuantumScale, ScaleQuantumToAny(), SinglePrecisionToHalf(), and ThrowMagickException().
Referenced by ExportQuantumPixels().
ExportGrayAlphaQuantum()
static void ExportGrayAlphaQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q) static
References ClampToQuantum(), _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetPixelAlpha, GetPixelLuma(), GetPixelOpacity, GetQuantumRange(), MagickFalse, _QuantumInfo::min_is_white, OpaqueOpacity, _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumPixel(), PopShortPixel(), QuantumRange, QuantumScale, ScaleQuantumToAny(), and SinglePrecisionToHalf().
Referenced by ExportQuantumPixels().
ExportGrayQuantum()
static void ExportGrayQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q) static
References ClampToQuantum(), _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetPixelLuma(), GetQuantumRange(), MagickFalse, _QuantumInfo::min_is_white, _QuantumInfo::pack, _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumPixel(), PopShortPixel(), QuantumRange, QuantumScale, ScaleQuantumToAny(), and SinglePrecisionToHalf().
Referenced by ExportQuantumPixels().
ExportGreenQuantum()
static void ExportGreenQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q) static
References _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetPixelGreen, GetQuantumRange(), _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumPixel(), PopShortPixel(), QuantumScale, ScaleQuantumToAny(), and SinglePrecisionToHalf().
Referenced by ExportQuantumPixels().
ExportIndexAlphaQuantum()
static void ExportIndexAlphaQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, const IndexPacket *magick_restrict indexes, unsigned char *magick_restrict q, ExceptionInfo * exception) static
References _QuantumInfo::depth, _QuantumInfo::endian, _Image::filename, FloatingPointQuantumFormat, _QuantumInfo::format, GetMagickModule, GetPixelAlpha, GetPixelIndex, GetPixelOpacity, GetQuantumRange(), ImageError, _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumPixel(), PopShortPixel(), PseudoClass, QuantumRange, QuantumScale, ScaleQuantumToAny(), SinglePrecisionToHalf(), _Image::storage_class, ThrowMagickException(), and TransparentOpacity.
Referenced by ExportQuantumPixels().
ExportIndexQuantum()
static void ExportIndexQuantum (const Image * image, QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, const IndexPacket *magick_restrict indexes, unsigned char *magick_restrict q, ExceptionInfo * exception) static
References _QuantumInfo::depth, _QuantumInfo::endian, _Image::filename, FloatingPointQuantumFormat, _QuantumInfo::format, GetMagickModule, GetPixelIndex, ImageError, _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumPixel(), PopShortPixel(), PseudoClass, QuantumScale, SinglePrecisionToHalf(), _Image::storage_class, and ThrowMagickException().
Referenced by ExportQuantumPixels().
ExportOpacityQuantum()
static void ExportOpacityQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q) static
References _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetPixelOpacity, GetQuantumRange(), _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumPixel(), PopShortPixel(), QuantumScale, ScaleQuantumToAny(), and SinglePrecisionToHalf().
Referenced by ExportQuantumPixels().
ExportQuantumPixels()
MagickExport size_t ExportQuantumPixels (const Image * image, const CacheView * image_view, const QuantumInfo * quantum_info, const QuantumType quantum_type, unsigned char *magick_restrict pixels, ExceptionInfo * exception)
References _QuantumInfo::alpha_type, AlphaQuantum, AssociatedQuantumAlpha, BGRAQuantum, BGROQuantum, BGRQuantum, BlackQuantum, BlueQuantum, CbYCrAQuantum, CbYCrQuantum, CbYCrYQuantum, ClampToQuantum(), CMYKAQuantum, CMYKOQuantum, CMYKQuantum, _Image::columns, CyanQuantum, _Image::debug, ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGROQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCbYCrYQuantum(), ExportCMYKAQuantum(), ExportCMYKOQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportIndexQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), ExportRGBOQuantum(), ExportRGBQuantum(), _Image::filename, GetAuthenticPixelQueue(), GetCacheViewExtent(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixelQueue(), GetImageExtent(), GetMagickModule, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelRed, GetQuantumExtent(), GetQuantumPixels(), GetVirtualIndexQueue(), GetVirtualPixelQueue(), GrayAlphaQuantum, GrayQuantum, GreenQuantum, IndexAlphaQuantum, IndexQuantum, LogMagickEvent(), MagentaQuantum, magick_restrict, MagickCoreSignature, MagickFalse, OpacityQuantum, QuantumScale, RedQuantum, ResetQuantumState(), RGBAQuantum, RGBOQuantum, RGBQuantum, SetPixelBlue, SetPixelGreen, SetPixelRed, _Image::signature, _QuantumInfo::signature, TraceEvent, and YellowQuantum.
Referenced by PopImagePixels(), and SignatureImage().
ExportRedQuantum()
static void ExportRedQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q) static
References _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetPixelRed, GetQuantumRange(), _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumPixel(), PopShortPixel(), QuantumScale, ScaleQuantumToAny(), and SinglePrecisionToHalf().
Referenced by ExportQuantumPixels().
ExportRGBAQuantum()
static void ExportRGBAQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q) static
References _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelRed, GetQuantumRange(), MagickFalse, _QuantumInfo::pack, _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumLongPixel(), PopQuantumPixel(), PopShortPixel(), _QuantumInfo::quantum, QuantumScale, ScaleQuantumToAny(), and SinglePrecisionToHalf().
Referenced by ExportQuantumPixels().
ExportRGBOQuantum()
static void ExportRGBOQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q) static
References _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetPixelBlue, GetPixelGreen, GetPixelOpacity, GetPixelRed, GetQuantumRange(), MagickFalse, _QuantumInfo::pack, _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumLongPixel(), PopQuantumPixel(), PopShortPixel(), _QuantumInfo::quantum, QuantumScale, ScaleQuantumToAny(), and SinglePrecisionToHalf().
Referenced by ExportQuantumPixels().
ExportRGBQuantum()
static void ExportRGBQuantum (QuantumInfo * quantum_info, const MagickSizeType number_pixels, const PixelPacket *magick_restrict p, unsigned char *magick_restrict q) static
References _QuantumInfo::depth, _QuantumInfo::endian, FloatingPointQuantumFormat, _QuantumInfo::format, GetPixelBlue, GetPixelGreen, GetPixelRed, GetQuantumRange(), MagickFalse, _QuantumInfo::pack, _QuantumInfo::pad, PopCharPixel(), PopDoublePixel(), PopFloatPixel(), PopLongPixel(), PopQuantumLongPixel(), PopQuantumPixel(), PopShortPixel(), _QuantumInfo::quantum, QuantumScale, ScaleQuantumToAny(), and SinglePrecisionToHalf().
Referenced by ExportQuantumPixels().
PopDoublePixel()
static unsigned char * PopDoublePixel (QuantumInfo * quantum_info, const double pixel, unsigned char *magick_restrict pixels) inline static
References _QuantumInfo::endian, _QuantumState::inverse_scale, LSBEndian, _QuantumInfo::minimum, and _QuantumInfo::state.
Referenced by ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGROQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCMYKAQuantum(), ExportCMYKOQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportIndexQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), ExportRGBOQuantum(), and ExportRGBQuantum().
PopFloatPixel()
static unsigned char * PopFloatPixel (QuantumInfo * quantum_info, const float pixel, unsigned char *magick_restrict pixels) inline static
References _QuantumInfo::endian, _QuantumState::inverse_scale, LSBEndian, _QuantumInfo::minimum, and _QuantumInfo::state.
Referenced by ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGROQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCMYKAQuantum(), ExportCMYKOQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportIndexQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), ExportRGBOQuantum(), and ExportRGBQuantum().
PopQuantumLongPixel()
static unsigned char * PopQuantumLongPixel (QuantumInfo * quantum_info, const size_t pixel, unsigned char *magick_restrict pixels) inline static
References _QuantumState::bits, _QuantumInfo::depth, _QuantumInfo::endian, _QuantumState::mask, _QuantumState::pixel, PopLongPixel(), and _QuantumInfo::state.
Referenced by ExportBGRAQuantum(), ExportBGROQuantum(), ExportBGRQuantum(), ExportRGBAQuantum(), ExportRGBOQuantum(), and ExportRGBQuantum().
PopQuantumPixel()
static unsigned char * PopQuantumPixel (QuantumInfo * quantum_info, const QuantumAny pixel, unsigned char *magick_restrict pixels) inline static
References _QuantumState::bits, _QuantumInfo::depth, and _QuantumInfo::state.
Referenced by ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGROQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCbYCrYQuantum(), ExportCMYKAQuantum(), ExportCMYKOQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportIndexQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), ExportRGBOQuantum(), and ExportRGBQuantum().