MagickCore: quantum-private.h File Reference
quantum-private.h File Reference
#include "magick/memory_.h"
#include "magick/cache.h"
#include "magick/image-private.h"
#include "magick/pixel-accessor.h"
Data Structures
struct _QuantumState
struct _QuantumInfo
Macros
#define ExponentBias (127-15)
#define ExponentMask 0x7c00
#define ExponentShift 23
#define SignBitShift 31
#define SignificandShift 13
#define SignificandMask 0x00000400
Typedefs
typedef struct _QuantumState QuantumState
Functions
MagickPrivate void ResetQuantumState (QuantumInfo *)
static MagickSizeType GetQuantumRange (const size_t depth)
static float HalfToSinglePrecision (const unsigned short half)
static unsigned char * PopCharPixel (const unsigned char pixel, unsigned char *magick_restrict pixels)
static unsigned char * PopLongPixel (const EndianType endian, const unsigned int pixel, unsigned char *magick_restrict pixels)
static unsigned char * PopShortPixel (const EndianType endian, const unsigned short pixel, unsigned char *magick_restrict pixels)
static const unsigned char * PushCharPixel (const unsigned char *magick_restrict pixels, unsigned char *magick_restrict pixel)
static const unsigned char * PushLongPixel (const EndianType endian, const unsigned char *magick_restrict pixels, unsigned int *magick_restrict pixel)
static const unsigned char * PushShortPixel (const EndianType endian, const unsigned char *magick_restrict pixels, unsigned short *magick_restrict pixel)
static const unsigned char * PushFloatPixel (const EndianType endian, const unsigned char *magick_restrict pixels, MagickFloatType *magick_restrict pixel)
static Quantum ScaleAnyToQuantum (const QuantumAny quantum, const QuantumAny range)
static QuantumAny ScaleQuantumToAny (const Quantum quantum, const QuantumAny range)
static unsigned short SinglePrecisionToHalf (const float value)
Macro Definition Documentation
ExponentBias
#define ExponentBias (127-15)
ExponentMask
#define ExponentMask 0x7c00
ExponentShift
#define ExponentShift 23
SignBitShift
#define SignBitShift 31
SignificandMask
#define SignificandMask 0x00000400
SignificandShift
#define SignificandShift 13
Typedef Documentation
QuantumState
typedef struct _QuantumState QuantumState
Function Documentation
GetQuantumRange()
static MagickSizeType GetQuantumRange (const size_t depth) inline static
References MagickMin.
Referenced by ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGROQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCbYCrYQuantum(), ExportCMYKAQuantum(), ExportCMYKOQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), ExportRGBOQuantum(), ExportRGBQuantum(), GetImageChannelDepth(), GetImageChannelStatistics(), ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGROQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCbYCrYQuantum(), ImportCMYKAQuantum(), ImportCMYKOQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBOQuantum(), ImportRGBQuantum(), QueryMagickColorCompliance(), and SetImageChannelDepth().
HalfToSinglePrecision()
static float HalfToSinglePrecision (const unsigned short half) inline static
References ExponentBias, ExponentShift, SignBitShift, SignificandMask, and SignificandShift.
Referenced by ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGROQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCMYKAQuantum(), ImportCMYKOQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBOQuantum(), and ImportRGBQuantum().
PopCharPixel()
static unsigned char * PopCharPixel (const unsigned char pixel, unsigned char *magick_restrict pixels) inline static
Referenced by ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGROQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCMYKAQuantum(), ExportCMYKOQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportIndexQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), ExportRGBOQuantum(), and ExportRGBQuantum().
PopLongPixel()
static unsigned char * PopLongPixel (const EndianType endian, const unsigned int pixel, unsigned char *magick_restrict pixels) inline static
References LSBEndian.
Referenced by ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGROQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCbYCrYQuantum(), ExportCMYKAQuantum(), ExportCMYKOQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportIndexQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), ExportRGBOQuantum(), ExportRGBQuantum(), and PopQuantumLongPixel().
PopShortPixel()
static unsigned char * PopShortPixel (const EndianType endian, const unsigned short pixel, unsigned char *magick_restrict pixels) inline static
References LSBEndian.
Referenced by ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGROQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCMYKAQuantum(), ExportCMYKOQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportIndexQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), ExportRGBOQuantum(), and ExportRGBQuantum().
PushCharPixel()
static const unsigned char * PushCharPixel (const unsigned char *magick_restrict pixels, unsigned char *magick_restrict pixel) inline static
Referenced by ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGROQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCMYKAQuantum(), ImportCMYKOQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBOQuantum(), and ImportRGBQuantum().
PushFloatPixel()
static const unsigned char * PushFloatPixel (const EndianType endian, const unsigned char *magick_restrict pixels, MagickFloatType *magick_restrict pixel) inline static
References LSBEndian.
PushLongPixel()
static const unsigned char * PushLongPixel (const EndianType endian, const unsigned char *magick_restrict pixels, unsigned int *magick_restrict pixel) inline static
References LSBEndian.
Referenced by ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGROQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCbYCrYQuantum(), ImportCMYKAQuantum(), ImportCMYKOQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBOQuantum(), ImportRGBQuantum(), and PushQuantumLongPixel().
PushShortPixel()
static const unsigned char * PushShortPixel (const EndianType endian, const unsigned char *magick_restrict pixels, unsigned short *magick_restrict pixel) inline static
References LSBEndian.
Referenced by ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGROQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCMYKAQuantum(), ImportCMYKOQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportIndexQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBOQuantum(), and ImportRGBQuantum().
ResetQuantumState()
MagickPrivate void ResetQuantumState (QuantumInfo * quantum_info)
References _QuantumState::bits, _QuantumState::inverse_scale, MagickCoreSignature, MagickEpsilon, _QuantumState::mask, _QuantumState::pixel, _QuantumInfo::scale, _QuantumInfo::signature, and _QuantumInfo::state.
Referenced by ExportQuantumPixels(), GetQuantumInfo(), and ImportQuantumPixels().
ScaleAnyToQuantum()
static Quantum ScaleAnyToQuantum (const QuantumAny quantum, const QuantumAny range) inline static
References PerceptibleReciprocal(), and QuantumRange.
Referenced by GetImageChannelDepth(), ImportAlphaQuantum(), ImportBGRAQuantum(), ImportBGROQuantum(), ImportBGRQuantum(), ImportBlackQuantum(), ImportBlueQuantum(), ImportCbYCrYQuantum(), ImportCMYKAQuantum(), ImportCMYKOQuantum(), ImportCMYKQuantum(), ImportGrayAlphaQuantum(), ImportGrayQuantum(), ImportGreenQuantum(), ImportIndexAlphaQuantum(), ImportRedQuantum(), ImportRGBAQuantum(), ImportRGBOQuantum(), ImportRGBQuantum(), QueryMagickColorCompliance(), and SetImageChannelDepth().
ScaleQuantumToAny()
static QuantumAny ScaleQuantumToAny (const Quantum quantum, const QuantumAny range) inline static
References IsNaN, MagickULLConstant, and QuantumRange.
Referenced by ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGROQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCbYCrYQuantum(), ExportCMYKAQuantum(), ExportCMYKOQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), ExportRGBOQuantum(), ExportRGBQuantum(), GetImageChannelDepth(), and SetImageChannelDepth().
SinglePrecisionToHalf()
static unsigned short SinglePrecisionToHalf (const float value) inline static
References ExponentBias, ExponentMask, ExponentShift, and SignificandShift.
Referenced by ExportAlphaQuantum(), ExportBGRAQuantum(), ExportBGROQuantum(), ExportBGRQuantum(), ExportBlackQuantum(), ExportBlueQuantum(), ExportCMYKAQuantum(), ExportCMYKOQuantum(), ExportCMYKQuantum(), ExportGrayAlphaQuantum(), ExportGrayQuantum(), ExportGreenQuantum(), ExportIndexAlphaQuantum(), ExportIndexQuantum(), ExportOpacityQuantum(), ExportRedQuantum(), ExportRGBAQuantum(), ExportRGBOQuantum(), and ExportRGBQuantum().