MagickCore: random.c File Reference
random.c File Reference
#include "magick/studio.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/image-private.h"
#include "magick/memory_.h"
#include "magick/memory-private.h"
#include "magick/random_.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/signature-private.h"
#include "magick/string_.h"
#include "magick/thread_.h"
#include "magick/thread-private.h"
#include "magick/utility-private.h"
Data Structures
struct _RandomInfo
Macros
#define PseudoRandomHash SHA256Hash
#define RandomEntropyLevel 9
#define RandomFilename "reservoir.xdm"
#define RandomFiletype "random"
#define RandomProtocolMajorVersion 1
#define RandomProtocolMinorVersion 0
#define MaxEntropyExtent 64
#define RandomROTL(x, k) (((x) << (k)) | ((x) >> (64-(k))))
Functions
static StringInfo * GenerateEntropicChaos (RandomInfo *)
MagickExport RandomInfo * AcquireRandomInfo (void)
MagickExport RandomInfo * DestroyRandomInfo (RandomInfo *random_info)
static ssize_t ReadRandom (int file, unsigned char *source, size_t length)
MagickExport double GetPseudoRandomValue (RandomInfo *magick_restrict random_info)
MagickPrivate double GetRandomInfoNormalize (const RandomInfo *random_info)
MagickPrivate unsigned long * GetRandomInfoSeed (RandomInfo *random_info)
MagickExport StringInfo * GetRandomKey (RandomInfo *random_info, const size_t length)
MagickExport unsigned long GetRandomSecretKey (const RandomInfo *random_info)
MagickExport double GetRandomValue (RandomInfo *random_info)
MagickExport MagickBooleanType RandomComponentGenesis (void)
MagickExport void RandomComponentTerminus (void)
static void IncrementRandomNonce (StringInfo *nonce)
MagickExport void SetRandomKey (RandomInfo *random_info, const size_t length, unsigned char *key)
MagickExport void SeedPseudoRandomGenerator (const unsigned long seed)
MagickExport void SetRandomSecretKey (const unsigned long key)
MagickExport void SetRandomTrueRandom (const MagickBooleanType true_random)
Variables
char ** environ
static SemaphoreInfo * random_semaphore = (SemaphoreInfo *) NULL
static unsigned long secret_key = ~0UL
static MagickBooleanType gather_true_random = MagickFalse
Macro Definition Documentation
MaxEntropyExtent
#define MaxEntropyExtent 64
PseudoRandomHash
#define PseudoRandomHash SHA256Hash
RandomEntropyLevel
#define RandomEntropyLevel 9
RandomFilename
#define RandomFilename "reservoir.xdm"
RandomFiletype
#define RandomFiletype "random"
RandomProtocolMajorVersion
#define RandomProtocolMajorVersion 1
RandomProtocolMinorVersion
#define RandomProtocolMinorVersion 0
RandomROTL
#define RandomROTL (x, k) (((x) << (k)) | ((x) >> (64-(k))))
Function Documentation
AcquireRandomInfo()
MagickExport RandomInfo * AcquireRandomInfo (void)
References AcquireCriticalMemory(), AcquireSignatureInfo(), AcquireStringInfo(), AllocateSemaphoreInfo(), DestroySignatureInfo(), DestroyStringInfo(), FinalizeSignature(), GenerateEntropicChaos(), GetRandomKey(), GetSignatureDigest(), GetSignatureDigestsize(), GetStringInfoDatum(), InitializeSignature(), MagickCoreSignature, MagickMin, MagickULLConstant, _RandomInfo::nonce, _RandomInfo::normalize, _RandomInfo::protocol_major, _RandomInfo::protocol_minor, random_info, RandomProtocolMajorVersion, RandomProtocolMinorVersion, _RandomInfo::reservoir, ResetStringInfo(), ResourceLimitFatalError, _RandomInfo::secret_key, secret_key, _RandomInfo::seed, _RandomInfo::semaphore, SetStringInfo(), SetStringInfoDatum(), SetStringInfoLength(), _RandomInfo::signature, _RandomInfo::signature_info, ThrowFatalException, _RandomInfo::timestamp, and UpdateSignature().
Referenced by AcquireFxInfo(), AcquireRandomInfoThreadSet(), AcquireUniqueFileResource(), DistributePixelCacheClient(), GetVirtualPixelCacheNexus(), PlasmaImage(), RandomChannelThresholdImage(), and ShredFile().
DestroyRandomInfo()
MagickExport RandomInfo * DestroyRandomInfo (RandomInfo * random_info)
References DestroySemaphoreInfo(), DestroySignatureInfo(), DestroyStringInfo(), GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickCoreSignature, _RandomInfo::nonce, random_info, RelinquishMagickMemory(), _RandomInfo::reservoir, _RandomInfo::seed, _RandomInfo::semaphore, _RandomInfo::signature, _RandomInfo::signature_info, TraceEvent, and UnlockSemaphoreInfo().
Referenced by DestroyFxInfo(), DestroyPixelCache(), DestroyRandomInfoThreadSet(), DistributePixelCacheClient(), PlasmaImage(), RandomChannelThresholdImage(), ResourceComponentTerminus(), and ShredFile().
GenerateEntropicChaos()
static StringInfo * GenerateEntropicChaos (RandomInfo * random_info) static
References AcquireString(), AcquireStringInfo(), ConcatenateStringInfo(), DestroyString(), DestroyStringInfo(), environ, gather_true_random, GetMagickThreadId(), GetStringInfoDatum(), LockSemaphoreInfo(), MagickFalse, MaxEntropyExtent, O_BINARY, open_utf8(), random_info, ReadRandom(), _RandomInfo::semaphore, SetStringInfoDatum(), SetStringInfoLength(), StringToStringInfo(), and UnlockSemaphoreInfo().
Referenced by AcquireRandomInfo().
GetPseudoRandomValue()
MagickExport double GetPseudoRandomValue (RandomInfo *magick_restrict random_info)
References _RandomInfo::normalize, random_info, RandomROTL, and _RandomInfo::seed.
Referenced by FxEvaluateSubexpression(), GenerateDifferentialNoise(), PlasmaPixel(), RandomChannelThresholdImage(), RandomThresholdImageChannel(), RandomX(), RandomY(), SketchImage(), and SpreadImage().
GetRandomInfoNormalize()
MagickPrivate double GetRandomInfoNormalize (const RandomInfo * random_info)
References _RandomInfo::normalize, and random_info.
GetRandomInfoSeed()
MagickPrivate unsigned long * GetRandomInfoSeed (RandomInfo * random_info)
References random_info, and _RandomInfo::seed.
GetRandomKey()
MagickExport StringInfo * GetRandomKey (RandomInfo * random_info, const size_t length)
References AcquireStringInfo(), GetStringInfoDatum(), random_info, and SetRandomKey().
Referenced by AcquireRandomInfo(), AcquireUniqueFileResource(), DistributePixelCacheClient(), and ShredFile().
GetRandomSecretKey()
MagickExport unsigned long GetRandomSecretKey (const RandomInfo * random_info)
References random_info, and _RandomInfo::secret_key.
Referenced by AddNoiseImageChannel(), EvaluateImageChannel(), EvaluateImages(), RandomThresholdImageChannel(), SketchImage(), and SpreadImage().
GetRandomValue()
MagickExport double GetRandomValue (RandomInfo * random_info)
References random_info, and SetRandomKey().
IncrementRandomNonce()
static void IncrementRandomNonce (StringInfo * nonce) inline static
References GetStringInfoDatum(), GetStringInfoLength(), RandomFatalError, and ThrowFatalException.
Referenced by SetRandomKey().
RandomComponentGenesis()
MagickExport MagickBooleanType RandomComponentGenesis (void)
References AllocateSemaphoreInfo(), MagickTrue, and random_semaphore.
Referenced by MagickCoreGenesis().
RandomComponentTerminus()
MagickExport void RandomComponentTerminus (void)
References ActivateSemaphoreInfo(), DestroySemaphoreInfo(), and random_semaphore.
Referenced by MagickCoreTerminus().
ReadRandom()
static ssize_t ReadRandom (int file, unsigned char * source, size_t length) static
Referenced by GenerateEntropicChaos().
SeedPseudoRandomGenerator()
MagickExport void SeedPseudoRandomGenerator (const unsigned long seed)
References SetRandomSecretKey().
SetRandomKey()
MagickExport void SetRandomKey (RandomInfo * random_info, const size_t length, unsigned char * key)
References FinalizeSignature(), GetSignatureDigest(), GetSignatureDigestsize(), GetStringInfoDatum(), _RandomInfo::i, IncrementRandomNonce(), InitializeSignature(), LockSemaphoreInfo(), _RandomInfo::nonce, random_info, _RandomInfo::reservoir, _RandomInfo::semaphore, SetStringInfo(), _RandomInfo::signature_info, UnlockSemaphoreInfo(), and UpdateSignature().
Referenced by GetRandomKey(), and GetRandomValue().
SetRandomSecretKey()
MagickExport void SetRandomSecretKey (const unsigned long key)
References secret_key.
Referenced by SeedPseudoRandomGenerator().
SetRandomTrueRandom()
MagickExport void SetRandomTrueRandom (const MagickBooleanType true_random)
References gather_true_random.
Variable Documentation
environ
char** environ extern
Referenced by GenerateEntropicChaos().
gather_true_random
MagickBooleanType gather_true_random = MagickFalse static
Referenced by GenerateEntropicChaos(), and SetRandomTrueRandom().
random_semaphore
SemaphoreInfo* random_semaphore = (SemaphoreInfo *) NULL static
Referenced by RandomComponentGenesis(), and RandomComponentTerminus().
secret_key
unsigned long secret_key = ~0UL static
Referenced by AcquireRandomInfo(), and SetRandomSecretKey().