MagickCore: random-private.h File Reference
random-private.h File Reference
#include "magick/thread-private.h"
Functions
static RandomInfo ** DestroyRandomInfoThreadSet (RandomInfo **random_info)
static RandomInfo ** AcquireRandomInfoThreadSet (void)
MagickExport unsigned long * GetRandomInfoSeed (RandomInfo *)
MagickExport double GetRandomInfoNormalize (const RandomInfo *)
Function Documentation
AcquireRandomInfoThreadSet()
static RandomInfo ** AcquireRandomInfoThreadSet (void) inline static
References AcquireAlignedMemory(), AcquireRandomInfo(), GetMagickResourceLimit(), random_info, ResourceLimitFatalError, ThreadResource, and ThrowFatalException.
Referenced by AddNoiseImageChannel(), EvaluateImageChannel(), EvaluateImages(), RandomThresholdImageChannel(), SketchImage(), and SpreadImage().
DestroyRandomInfoThreadSet()
static RandomInfo ** DestroyRandomInfoThreadSet (RandomInfo ** random_info) inline static
References DestroyRandomInfo(), GetMagickResourceLimit(), random_info, RelinquishAlignedMemory(), and ThreadResource.
Referenced by AddNoiseImageChannel(), EvaluateImageChannel(), EvaluateImages(), RandomThresholdImageChannel(), SketchImage(), and SpreadImage().
GetRandomInfoNormalize()
MagickExport double GetRandomInfoNormalize (const RandomInfo * random_info)
References _RandomInfo::normalize, and random_info.
GetRandomInfoSeed()
MagickExport unsigned long * GetRandomInfoSeed (RandomInfo * random_info)
References random_info, and _RandomInfo::seed.