MagickCore: random_.h File Reference
random_.h File Reference
#include "magick/string_.h"
Typedefs
typedef struct _RandomInfo RandomInfo
Functions
MagickExport double GetRandomValue (RandomInfo *)
MagickExport double GetPseudoRandomValue (RandomInfo *magick_restrict)
MagickExport MagickBooleanType RandomComponentGenesis (void)
MagickExport RandomInfo * AcquireRandomInfo (void)
MagickExport RandomInfo * DestroyRandomInfo (RandomInfo *)
MagickExport StringInfo * GetRandomKey (RandomInfo *, const size_t)
MagickExport unsigned long GetRandomSecretKey (const RandomInfo *)
MagickExport void RandomComponentTerminus (void)
MagickExport void SeedPseudoRandomGenerator (const unsigned long)
MagickExport void SetRandomKey (RandomInfo *, const size_t, unsigned char *)
MagickExport void SetRandomSecretKey (const unsigned long)
MagickExport void SetRandomTrueRandom (const MagickBooleanType)
Typedef Documentation
RandomInfo
typedef struct _RandomInfo RandomInfo
Function Documentation
AcquireRandomInfo()
MagickExport RandomInfo * AcquireRandomInfo (void)
DestroyRandomInfo()
MagickExport RandomInfo * DestroyRandomInfo (RandomInfo * random_info)
References DestroySemaphoreInfo(), DestroySignatureInfo(), DestroyStringInfo(), GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickCoreSignature, _RandomInfo::nonce, random_info, RelinquishMagickMemory(), _RandomInfo::reservoir, _RandomInfo::seed, _RandomInfo::semaphore, _RandomInfo::signature, _RandomInfo::signature_info, TraceEvent, and UnlockSemaphoreInfo().
Referenced by DestroyFxInfo(), DestroyPixelCache(), DestroyRandomInfoThreadSet(), DistributePixelCacheClient(), PlasmaImage(), RandomChannelThresholdImage(), ResourceComponentTerminus(), and ShredFile().
GetPseudoRandomValue()
MagickExport double GetPseudoRandomValue (RandomInfo * magick_restrict)
GetRandomKey()
MagickExport StringInfo * GetRandomKey (RandomInfo * random_info, const size_t)
References AcquireStringInfo(), GetStringInfoDatum(), random_info, and SetRandomKey().
Referenced by AcquireRandomInfo(), AcquireUniqueFileResource(), DistributePixelCacheClient(), and ShredFile().
GetRandomSecretKey()
MagickExport unsigned long GetRandomSecretKey (const RandomInfo * random_info)
References random_info, and _RandomInfo::secret_key.
Referenced by AddNoiseImageChannel(), EvaluateImageChannel(), EvaluateImages(), RandomThresholdImageChannel(), SketchImage(), and SpreadImage().
GetRandomValue()
MagickExport double GetRandomValue (RandomInfo *)
RandomComponentGenesis()
MagickExport MagickBooleanType RandomComponentGenesis (void)
References AllocateSemaphoreInfo(), MagickTrue, and random_semaphore.
Referenced by MagickCoreGenesis().
RandomComponentTerminus()
MagickExport void RandomComponentTerminus (void)
SeedPseudoRandomGenerator()
MagickExport void SeedPseudoRandomGenerator (const unsigned long)
SetRandomKey()
MagickExport void SetRandomKey (RandomInfo * , const size_t, unsigned char *)
SetRandomSecretKey()
MagickExport void SetRandomSecretKey (const unsigned long)
SetRandomTrueRandom()
MagickExport void SetRandomTrueRandom (const MagickBooleanType)
References gather_true_random.