MagickCore: registry.h File Reference
registry.h File Reference
Enumerations
enum RegistryType { UndefinedRegistryType , ImageRegistryType , ImageInfoRegistryType , StringRegistryType }
Functions
MagickExport char * GetNextImageRegistry (void)
MagickExport MagickBooleanType DefineImageRegistry (const RegistryType, const char *, ExceptionInfo *)
MagickExport MagickBooleanType DeleteImageRegistry (const char *)
MagickExport MagickBooleanType RegistryComponentGenesis (void)
MagickExport MagickBooleanType SetImageRegistry (const RegistryType, const char *, const void *, ExceptionInfo *)
MagickExport void * GetImageRegistry (const RegistryType, const char *, ExceptionInfo *)
MagickExport void RegistryComponentTerminus (void)
MagickExport void * RemoveImageRegistry (const char *)
MagickExport void ResetImageRegistryIterator (void)
Enumeration Type Documentation
RegistryType
enum RegistryType
Enumerator
UndefinedRegistryType
ImageRegistryType
ImageInfoRegistryType
StringRegistryType
Function Documentation
DefineImageRegistry()
MagickExport MagickBooleanType DefineImageRegistry (const RegistryType, const char * , ExceptionInfo *)
DeleteImageRegistry()
MagickExport MagickBooleanType DeleteImageRegistry (const char *)
GetImageRegistry()
MagickExport void * GetImageRegistry (const RegistryType, const char * , ExceptionInfo *)
GetNextImageRegistry()
MagickExport char * GetNextImageRegistry (void)
References GetMagickModule, GetNextKeyInSplayTree(), IsEventLogging(), LogMagickEvent(), MagickFalse, registry, and TraceEvent.
Referenced by IdentifyImage().
RegistryComponentGenesis()
MagickExport MagickBooleanType RegistryComponentGenesis (void)
RegistryComponentTerminus()
MagickExport void RegistryComponentTerminus (void)
RemoveImageRegistry()
MagickExport void * RemoveImageRegistry (const char *)
ResetImageRegistryIterator()
MagickExport void ResetImageRegistryIterator (void)
References GetMagickModule, IsEventLogging(), LogMagickEvent(), MagickFalse, registry, ResetSplayTreeIterator(), and TraceEvent.
Referenced by IdentifyImage().
SetImageRegistry()
MagickExport MagickBooleanType SetImageRegistry (const RegistryType, const char * key, const void * value, ExceptionInfo * exception)
References AcquireCriticalMemory(), ActivateSemaphoreInfo(), AddValueToSplayTree(), CloneImageInfo(), CloneImageList(), CompareSplayTreeString(), ConstantString(), DestroyRegistryNode(), GetMagickModule, ImageInfoRegistryType, ImageRegistryType, IsEventLogging(), LockSemaphoreInfo(), LogMagickEvent(), MagickCoreSignature, MagickFalse, NewSplayTree(), registry, registry_semaphore, RegistryError, RelinquishMagickMemory(), _Image::signature, _ImageInfo::signature, _RegistryInfo::signature, StringRegistryType, ThrowMagickException(), TraceEvent, _RegistryInfo::type, UnlockSemaphoreInfo(), and _RegistryInfo::value.
Referenced by DefineImageRegistry(), and SetMagickRegistry().