MagickCore: registry.c File Reference
registry.c File Reference
#include "magick/studio.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/image.h"
#include "magick/list.h"
#include "magick/memory_.h"
#include "magick/memory-private.h"
#include "magick/registry.h"
#include "magick/splay-tree.h"
#include "magick/string_.h"
#include "magick/utility.h"
Data Structures
struct _RegistryInfo
Typedefs
typedef struct _RegistryInfo RegistryInfo
Functions
MagickExport MagickBooleanType DefineImageRegistry (const RegistryType type, const char *option, ExceptionInfo *exception)
MagickExport MagickBooleanType DeleteImageRegistry (const char *key)
MagickExport void * GetImageRegistry (const RegistryType type, const char *key, ExceptionInfo *exception)
MagickExport char * GetNextImageRegistry (void)
MagickExport MagickBooleanType RegistryComponentGenesis (void)
MagickExport void RegistryComponentTerminus (void)
MagickExport void * RemoveImageRegistry (const char *key)
MagickExport void ResetImageRegistryIterator (void)
static void * DestroyRegistryNode (void *registry_info)
MagickExport MagickBooleanType SetImageRegistry (const RegistryType type, const char *key, const void *value, ExceptionInfo *exception)
Variables
static SplayTreeInfo * registry = (SplayTreeInfo *) NULL
static SemaphoreInfo * registry_semaphore = (SemaphoreInfo *) NULL
Typedef Documentation
RegistryInfo
typedef struct _RegistryInfo RegistryInfo
Function Documentation
DefineImageRegistry()
MagickExport MagickBooleanType DefineImageRegistry (const RegistryType type, const char * option, ExceptionInfo * exception)
References CopyMagickString(), MaxTextExtent, and SetImageRegistry().
DeleteImageRegistry()
MagickExport MagickBooleanType DeleteImageRegistry (const char * key)
References DeleteNodeFromSplayTree(), GetMagickModule, IsEventLogging(), LogMagickEvent(), MagickFalse, registry, and TraceEvent.
Referenced by DeleteMagickRegistry().
DestroyRegistryNode()
static void * DestroyRegistryNode (void * registry_info) static
References DestroyImageInfo(), DestroyImageList(), ImageInfoRegistryType, ImageRegistryType, RelinquishMagickMemory(), StringRegistryType, _RegistryInfo::type, and _RegistryInfo::value.
Referenced by SetImageRegistry().
GetImageRegistry()
MagickExport void * GetImageRegistry (const RegistryType type, const char * key, ExceptionInfo * exception)
References CloneImageInfo(), CloneImageList(), ConstantString(), GetMagickModule, GetValueFromSplayTree(), ImageInfoRegistryType, ImageRegistryType, IsEventLogging(), LogMagickEvent(), MagickFalse, registry, StringRegistryType, TraceEvent, _RegistryInfo::type, and _RegistryInfo::value.
Referenced by GetHostname(), GetImageFromMagickRegistry(), GetMagickRegistry(), GetPathTemplate(), IdentifyImage(), and OpenPixelCache().
GetNextImageRegistry()
MagickExport char * GetNextImageRegistry (void)
References GetMagickModule, GetNextKeyInSplayTree(), IsEventLogging(), LogMagickEvent(), MagickFalse, registry, and TraceEvent.
Referenced by IdentifyImage().
RegistryComponentGenesis()
MagickExport MagickBooleanType RegistryComponentGenesis (void)
References AllocateSemaphoreInfo(), MagickTrue, and registry_semaphore.
Referenced by MagickCoreGenesis().
RegistryComponentTerminus()
MagickExport void RegistryComponentTerminus (void)
References ActivateSemaphoreInfo(), DestroySemaphoreInfo(), DestroySplayTree(), GetMagickModule, IsEventLogging(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, registry, registry_semaphore, TraceEvent, and UnlockSemaphoreInfo().
Referenced by DestroyMagickRegistry(), and MagickCoreTerminus().
RemoveImageRegistry()
MagickExport void * RemoveImageRegistry (const char * key)
References GetMagickModule, IsEventLogging(), LogMagickEvent(), MagickFalse, registry, RemoveNodeFromSplayTree(), and TraceEvent.
ResetImageRegistryIterator()
MagickExport void ResetImageRegistryIterator (void)
References GetMagickModule, IsEventLogging(), LogMagickEvent(), MagickFalse, registry, ResetSplayTreeIterator(), and TraceEvent.
Referenced by IdentifyImage().
SetImageRegistry()
MagickExport MagickBooleanType SetImageRegistry (const RegistryType type, const char * key, const void * value, ExceptionInfo * exception)
References AcquireCriticalMemory(), ActivateSemaphoreInfo(), AddValueToSplayTree(), CloneImageInfo(), CloneImageList(), CompareSplayTreeString(), ConstantString(), DestroyRegistryNode(), GetMagickModule, ImageInfoRegistryType, ImageRegistryType, IsEventLogging(), LockSemaphoreInfo(), LogMagickEvent(), MagickCoreSignature, MagickFalse, NewSplayTree(), registry, registry_semaphore, RegistryError, RelinquishMagickMemory(), _Image::signature, _ImageInfo::signature, _RegistryInfo::signature, StringRegistryType, ThrowMagickException(), TraceEvent, _RegistryInfo::type, UnlockSemaphoreInfo(), and _RegistryInfo::value.
Referenced by DefineImageRegistry(), and SetMagickRegistry().
Variable Documentation
registry
SplayTreeInfo* registry = (SplayTreeInfo *) NULL static
Referenced by DeleteImageRegistry(), DestroyDistributeCache(), DistributePixelCacheClient(), GetImageRegistry(), GetNextImageRegistry(), IdentifyImage(), OpenDistributeCache(), ReadDistributeCacheIndexes(), ReadDistributeCachePixels(), RegistryComponentTerminus(), RemoveImageRegistry(), ResetImageRegistryIterator(), SetImageRegistry(), WriteDistributeCacheIndexes(), and WriteDistributeCachePixels().
registry_semaphore
SemaphoreInfo* registry_semaphore = (SemaphoreInfo *) NULL static
Referenced by RegistryComponentGenesis(), RegistryComponentTerminus(), and SetImageRegistry().