MagickCore: resample-private.h File Reference
resample-private.h File Reference
#include <string.h>
#include "magick/thread-private.h"
Functions
static ResampleFilter ** DestroyResampleFilterThreadSet (ResampleFilter **filter)
static ResampleFilter ** AcquireResampleFilterThreadSet (const Image *image, const VirtualPixelMethod method, const MagickBooleanType interpolate, ExceptionInfo *exception)
Function Documentation
AcquireResampleFilterThreadSet()
static ResampleFilter ** AcquireResampleFilterThreadSet (const Image * image, const VirtualPixelMethod method, const MagickBooleanType interpolate, ExceptionInfo * exception) inline static
References AcquireAlignedMemory(), AcquireResampleFilter(), GetMagickResourceLimit(), MagickFalse, PointFilter, ResourceLimitFatalError, SetResampleFilter(), SetResampleFilterVirtualPixelMethod(), ThreadResource, ThrowFatalException, and UndefinedVirtualPixelMethod.
Referenced by DistortImage().
DestroyResampleFilterThreadSet()
static ResampleFilter ** DestroyResampleFilterThreadSet (ResampleFilter ** filter) inline static
References DestroyResampleFilter(), GetMagickResourceLimit(), RelinquishAlignedMemory(), and ThreadResource.
Referenced by DistortImage().