MagickCore: resample.c File Reference
resample.c File Reference
#include "magick/studio.h"
#include "magick/artifact.h"
#include "magick/color-private.h"
#include "magick/cache.h"
#include "magick/draw.h"
#include "magick/exception-private.h"
#include "magick/gem.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/log.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/pixel.h"
#include "magick/pixel-private.h"
#include "magick/quantum.h"
#include "magick/random_.h"
#include "magick/resample.h"
#include "magick/resize.h"
#include "magick/resize-private.h"
#include "magick/resource_.h"
#include "magick/transform.h"
#include "magick/signature-private.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/option.h"
Data Structures
struct _ResampleFilter
Macros
#define EWA 1 /* Normal EWA handling - raw or clamped */
#define EWA_CLAMP 1 /* EWA Clamping from Nicolas Robidoux */
#define FILTER_LUT 1 /* Use a LUT rather then direct filter calls */
#define DEBUG_ELLIPSE 0 /* output ellipse info for debug */
#define DEBUG_HIT_MISS 0 /* output hit/miss pixels (as gnuplot commands) */
#define DEBUG_NO_PIXEL_HIT 0 /* Make pixels that fail to hit anything - RED */
#define WLUT_WIDTH 1024 /* size of the filter cache */
#define DEBUG_HIT_MISS 0 /* only valid if DEBUG_ELLIPSE is enabled */
Functions
MagickExport ResampleFilter * AcquireResampleFilter (const Image *image, ExceptionInfo *exception)
MagickExport ResampleFilter * DestroyResampleFilter (ResampleFilter *resample_filter)
MagickExport MagickBooleanType ResamplePixelColor (ResampleFilter *resample_filter, const double u0, const double v0, MagickPixelPacket *pixel)
static void ClampUpAxes (const double dux, const double dvx, const double duy, const double dvy, double *major_mag, double *minor_mag, double *major_unit_x, double *major_unit_y, double *minor_unit_x, double *minor_unit_y)
MagickExport void ScaleResampleFilter (ResampleFilter *resample_filter, const double dux, const double duy, const double dvx, const double dvy)
MagickExport void SetResampleFilter (ResampleFilter *resample_filter, const FilterTypes filter, const double blur)
MagickExport MagickBooleanType SetResampleFilterInterpolateMethod (ResampleFilter *resample_filter, const InterpolatePixelMethod method)
MagickExport MagickBooleanType SetResampleFilterVirtualPixelMethod (ResampleFilter *resample_filter, const VirtualPixelMethod method)
Macro Definition Documentation
DEBUG_ELLIPSE
#define DEBUG_ELLIPSE 0 /* output ellipse info for debug */
DEBUG_HIT_MISS [1/2]
#define DEBUG_HIT_MISS 0 /* output hit/miss pixels (as gnuplot commands) */
DEBUG_HIT_MISS [2/2]
#define DEBUG_HIT_MISS 0 /* only valid if DEBUG_ELLIPSE is enabled */
DEBUG_NO_PIXEL_HIT
#define DEBUG_NO_PIXEL_HIT 0 /* Make pixels that fail to hit anything - RED */
EWA
#define EWA 1 /* Normal EWA handling - raw or clamped */
EWA_CLAMP
#define EWA_CLAMP 1 /* EWA Clamping from Nicolas Robidoux */
FILTER_LUT
#define FILTER_LUT 1 /* Use a LUT rather then direct filter calls */
WLUT_WIDTH
#define WLUT_WIDTH 1024 /* size of the filter cache */
Function Documentation
AcquireResampleFilter()
MagickExport ResampleFilter * AcquireResampleFilter (const Image * image, ExceptionInfo * exception)
References AcquireQuantumMemory(), AcquireVirtualCacheView(), _ResampleFilter::average_defined, _Image::blur, _Image::columns, _Image::debug, _ResampleFilter::debug, _ResampleFilter::exception, _Image::filename, _Image::filter, GetImageVirtualPixelMethod(), GetMagickModule, _ResampleFilter::image, _ResampleFilter::image_area, _Image::interpolate, IsEventLogging(), LogMagickEvent(), MagickCoreSignature, MagickFalse, ReferenceImage(), ResourceLimitFatalError, _Image::rows, SetResampleFilter(), SetResampleFilterInterpolateMethod(), SetResampleFilterVirtualPixelMethod(), _ExceptionInfo::signature, _Image::signature, _ResampleFilter::signature, ThrowFatalException, TraceEvent, and _ResampleFilter::view.
Referenced by AcquireResampleFilterThreadSet(), and CompositeImageChannel().
ClampUpAxes()
static void ClampUpAxes (const double dux, const double dvx, const double duy, const double dvy, double * major_mag, double * minor_mag, double * major_unit_x, double * major_unit_y, double * minor_unit_x, double * minor_unit_y) inline static
Referenced by ScaleResampleFilter().
DestroyResampleFilter()
MagickExport ResampleFilter * DestroyResampleFilter (ResampleFilter * resample_filter)
References _ResampleFilter::debug, DestroyCacheView(), DestroyImage(), DestroyResizeFilter(), _Image::filename, GetMagickModule, _ResampleFilter::image, LogMagickEvent(), MagickCoreSignature, MagickFalse, RelinquishMagickMemory(), _ResampleFilter::signature, TraceEvent, and _ResampleFilter::view.
Referenced by CompositeImageChannel(), and DestroyResampleFilterThreadSet().
ResamplePixelColor()
MagickExport MagickBooleanType ResamplePixelColor (ResampleFilter * resample_filter, const double u0, const double v0, MagickPixelPacket * pixel)
References _ResampleFilter::A, AcquireVirtualCacheView(), _ResampleFilter::average_defined, _ResampleFilter::average_pixel, AverageInterpolatePixel, _ResampleFilter::B, _Image::background_color, BackgroundVirtualPixelMethod, BlackVirtualPixelMethod, _MagickPixelPacket::blue, _PixelPacket::blue, BoxFilter, _ResampleFilter::C, CheckerTileVirtualPixelMethod, ClampToQuantum(), CMYKColorspace, _MagickPixelPacket::colorspace, _Image::columns, ConstantVirtualPixelMethod, DestroyCacheView(), DestroyImage(), DitherVirtualPixelMethod, _ResampleFilter::do_interpolate, EdgeVirtualPixelMethod, _Image::exception, _ResampleFilter::exception, _ResampleFilter::filter_lut, FormatLocaleFile(), GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickPixelPacket(), GetResizeFilterWeight(), GrayVirtualPixelMethod, _MagickPixelPacket::green, _PixelPacket::green, HorizontalTileEdgeVirtualPixelMethod, HorizontalTileVirtualPixelMethod, _ResampleFilter::image, _MagickPixelPacket::index, IntegerInterpolatePixel, _ResampleFilter::interpolate, InterpolateMagickPixelPacket(), _ResampleFilter::limit_reached, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickTrue, MaskVirtualPixelMethod, _MagickPixelPacket::matte, MirrorVirtualPixelMethod, _MagickPixelPacket::opacity, _PixelPacket::opacity, QuantumRange, QuantumScale, RandomVirtualPixelMethod, _MagickPixelPacket::red, _PixelPacket::red, ResizeImage(), _Image::rows, SetMagickPixelPacket(), _ResampleFilter::signature, _ResampleFilter::slope, TileVirtualPixelMethod, TransparentVirtualPixelMethod, _ResampleFilter::Ulimit, UndefinedVirtualPixelMethod, _ResampleFilter::Uwidth, VerticalTileEdgeVirtualPixelMethod, VerticalTileVirtualPixelMethod, _ResampleFilter::view, _ResampleFilter::virtual_pixel, _ResampleFilter::Vlimit, WhiteVirtualPixelMethod, and WLUT_WIDTH.
Referenced by CompositeImageChannel(), and DistortImage().
ScaleResampleFilter()
MagickExport void ScaleResampleFilter (ResampleFilter * resample_filter, const double dux, const double duy, const double dvx, const double dvy)
References _ResampleFilter::A, _ResampleFilter::B, _ResampleFilter::C, ClampUpAxes(), _ResampleFilter::filter, FormatLocaleFile(), _ResampleFilter::image_area, _ResampleFilter::limit_reached, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickMaximumValue, MagickPI, MagickTrue, PerceptibleReciprocal(), PointFilter, RadiansToDegrees(), _ResampleFilter::signature, _ResampleFilter::slope, _ResampleFilter::support, _ResampleFilter::Ulimit, _ResampleFilter::Uwidth, _ResampleFilter::Vlimit, and WLUT_WIDTH.
Referenced by CompositeImageChannel(), and SetResampleFilter().
SetResampleFilter()
MagickExport void SetResampleFilter (ResampleFilter * resample_filter, const FilterTypes filter, const double blur)
References AcquireResizeFilter(), CommandOptionToMnemonic(), DestroyResizeFilter(), _ResampleFilter::do_interpolate, _ResampleFilter::exception, _ResampleFilter::filter, _ResampleFilter::filter_lut, GetImageArtifact(), GetMagickModule, GetMagickPrecision(), GetResizeFilterSupport(), GetResizeFilterWeight(), _ResampleFilter::image, IsMagickTrue(), MagickCoreSignature, MagickFalse, MagickFilterOptions, MagickTrue, ModuleError, PointFilter, RobidouxFilter, ScaleResampleFilter(), _ResampleFilter::signature, _ResampleFilter::support, ThrowMagickException(), UndefinedFilter, and WLUT_WIDTH.
Referenced by AcquireResampleFilter(), AcquireResampleFilterThreadSet(), and CompositeImageChannel().
SetResampleFilterInterpolateMethod()
MagickExport MagickBooleanType SetResampleFilterInterpolateMethod (ResampleFilter * resample_filter, const InterpolatePixelMethod method)
References _ResampleFilter::debug, _Image::filename, GetMagickModule, _ResampleFilter::image, _ResampleFilter::interpolate, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _ResampleFilter::signature, and TraceEvent.
Referenced by AcquireResampleFilter().
SetResampleFilterVirtualPixelMethod()
MagickExport MagickBooleanType SetResampleFilterVirtualPixelMethod (ResampleFilter * resample_filter, const VirtualPixelMethod method)
References _ResampleFilter::debug, _Image::filename, GetMagickModule, _ResampleFilter::image, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, SetCacheViewVirtualPixelMethod(), _ResampleFilter::signature, TraceEvent, UndefinedVirtualPixelMethod, _ResampleFilter::view, and _ResampleFilter::virtual_pixel.
Referenced by AcquireResampleFilter(), and AcquireResampleFilterThreadSet().