MagickCore: resize.h File Reference
resize.h File Reference
Typedefs
typedef struct _ResizeFilter ResizeFilter
Functions
MagickExport Image * AdaptiveResizeImage (const Image *, const size_t, const size_t, ExceptionInfo *)
MagickExport Image * InterpolativeResizeImage (const Image *, const size_t, const size_t, const InterpolatePixelMethod, ExceptionInfo *)
MagickExport Image * LiquidRescaleImage (const Image *, const size_t, const size_t, const double, const double, ExceptionInfo *)
MagickExport Image * MagnifyImage (const Image *, ExceptionInfo *)
MagickExport Image * MinifyImage (const Image *, ExceptionInfo *)
MagickExport Image * ResampleImage (const Image *, const double, const double, const FilterTypes, const double, ExceptionInfo *)
MagickExport Image * ResizeImage (const Image *, const size_t, const size_t, const FilterTypes, const double, ExceptionInfo *)
MagickExport Image * SampleImage (const Image *, const size_t, const size_t, ExceptionInfo *)
MagickExport Image * ScaleImage (const Image *, const size_t, const size_t, ExceptionInfo *)
MagickExport Image * ThumbnailImage (const Image *, const size_t, const size_t, ExceptionInfo *)
Typedef Documentation
ResizeFilter
typedef struct _ResizeFilter ResizeFilter
Function Documentation
AdaptiveResizeImage()
MagickExport Image * AdaptiveResizeImage (const Image * , const size_t, const size_t, ExceptionInfo *)
InterpolativeResizeImage()
MagickExport Image * InterpolativeResizeImage (const Image * , const size_t, const size_t, const InterpolatePixelMethod, ExceptionInfo *)
LiquidRescaleImage()
MagickExport Image * LiquidRescaleImage (const Image * , const size_t, const size_t, const double , const double , ExceptionInfo *)
MagnifyImage()
MagickExport Image * MagnifyImage (const Image * , ExceptionInfo *)
MinifyImage()
MagickExport Image * MinifyImage (const Image * , ExceptionInfo *)
ResampleImage()
MagickExport Image * ResampleImage (const Image * , const double , const double , const FilterTypes, const double , ExceptionInfo *)
ResizeImage()
MagickExport Image * ResizeImage (const Image * , const size_t, const size_t, const FilterTypes, const double , ExceptionInfo *)
SampleImage()
MagickExport Image * SampleImage (const Image * , const size_t, const size_t, ExceptionInfo *)
ScaleImage()
MagickExport Image * ScaleImage (const Image * , const size_t, const size_t, ExceptionInfo *)
ThumbnailImage()
MagickExport Image * ThumbnailImage (const Image * image, const size_t, const size_t, ExceptionInfo * exception)
References _Image::blur, _Image::columns, ConcatenateMagickString(), CopyMagickString(), _Image::debug, DeleteImageProfile(), DeleteImageProperty(), _Image::depth, DestroyImage(), _Image::filename, _Image::filter, FormatLocaleString(), FormatMagickSize(), GetBlobSize(), GetImageListLength(), GetMagickModule, GetNextImageProfile(), GetPathAttributes(), GetPathComponent(), _Image::interlace, LocaleCompare(), LocaleLower(), LogMagickEvent(), _Image::magick, _Image::magick_columns, _Image::magick_filename, _Image::magick_rows, MagickAuthoritativeURL, MagickCoreSignature, MagickFalse, _Image::matte, MaxTextExtent, NoInterlace, OpaqueAlphaChannel, _Image::page, ParseAbsoluteGeometry(), ResetImageProfileIterator(), ResizeImage(), _Image::rows, SampleFactor, SampleImage(), SetImageAlphaChannel(), SetImageProperty(), _ExceptionInfo::signature, _Image::signature, TailPath, and TraceEvent.
Referenced by MontageImageList(), and PreviewImage().