MagickCore: resize.c File Reference
resize.c File Reference
#include "magick/studio.h"
#include "magick/accelerate-private.h"
#include "magick/artifact.h"
#include "magick/blob.h"
#include "magick/cache.h"
#include "magick/cache-view.h"
#include "magick/channel.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/draw.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/gem.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/memory_.h"
#include "magick/memory-private.h"
#include "magick/magick.h"
#include "magick/pixel-private.h"
#include "magick/property.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/nt-base-private.h"
#include "magick/pixel.h"
#include "magick/option.h"
#include "magick/resample.h"
#include "magick/resample-private.h"
#include "magick/resize.h"
#include "magick/resize-private.h"
#include "magick/resource_.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/thread-private.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/version.h"
Data Structures
struct _ResizeFilter
struct _ContributionInfo
Macros
#define InterpolativeResizeImageTag "Resize/Image"
#define MagnifyImageTag "Magnify/Image"
#define ResampleImageTag "Resample/Image"
#define ResizeImageTag "Resize/Image"
#define SampleImageTag "Sample/Image"
#define ScaleImageTag "Scale/Image"
#define SampleFactor 5
Typedefs
typedef struct _ContributionInfo ContributionInfo
Functions
static MagickRealType I0 (MagickRealType x)
static MagickRealType BesselOrderOne (MagickRealType)
static MagickRealType Sinc (const MagickRealType, const ResizeFilter *)
static MagickRealType SincFast (const MagickRealType, const ResizeFilter *)
static MagickRealType Blackman (const MagickRealType x, const ResizeFilter *magick_unused(resize_filter))
static MagickRealType Bohman (const MagickRealType x, const ResizeFilter *magick_unused(resize_filter))
static MagickRealType Box (const MagickRealType magick_unused(x), const ResizeFilter *magick_unused(resize_filter))
static MagickRealType Cosine (const MagickRealType x, const ResizeFilter *magick_unused(resize_filter))
static MagickRealType CubicBC (const MagickRealType x, const ResizeFilter *resize_filter)
static MagickRealType Gaussian (const MagickRealType x, const ResizeFilter *resize_filter)
static MagickRealType Hanning (const MagickRealType x, const ResizeFilter *magick_unused(resize_filter))
static MagickRealType Hamming (const MagickRealType x, const ResizeFilter *magick_unused(resize_filter))
static MagickRealType Jinc (const MagickRealType x, const ResizeFilter *magick_unused(resize_filter))
static MagickRealType Kaiser (const MagickRealType x, const ResizeFilter *resize_filter)
static MagickRealType Lagrange (const MagickRealType x, const ResizeFilter *resize_filter)
static MagickRealType Quadratic (const MagickRealType x, const ResizeFilter *magick_unused(resize_filter))
static MagickRealType Sinc (const MagickRealType x, const ResizeFilter *magick_unused(resize_filter))
static MagickRealType SincFast (const MagickRealType x, const ResizeFilter *magick_unused(resize_filter))
static MagickRealType Triangle (const MagickRealType x, const ResizeFilter *magick_unused(resize_filter))
static MagickRealType Welsh (const MagickRealType x, const ResizeFilter *magick_unused(resize_filter))
MagickExport ResizeFilter * AcquireResizeFilter (const Image *image, const FilterTypes filter, const MagickRealType blur, const MagickBooleanType cylindrical, ExceptionInfo *exception)
MagickExport Image * AdaptiveResizeImage (const Image *image, const size_t columns, const size_t rows, ExceptionInfo *exception)
static MagickRealType J1 (MagickRealType x)
static MagickRealType P1 (MagickRealType x)
static MagickRealType Q1 (MagickRealType x)
MagickExport ResizeFilter * DestroyResizeFilter (ResizeFilter *resize_filter)
MagickExport MagickRealType * GetResizeFilterCoefficient (const ResizeFilter *resize_filter)
MagickExport MagickRealType GetResizeFilterBlur (const ResizeFilter *resize_filter)
MagickExport MagickRealType GetResizeFilterScale (const ResizeFilter *resize_filter)
MagickExport MagickRealType GetResizeFilterWindowSupport (const ResizeFilter *resize_filter)
MagickExport ResizeWeightingFunctionType GetResizeFilterWeightingType (const ResizeFilter *resize_filter)
MagickExport ResizeWeightingFunctionType GetResizeFilterWindowWeightingType (const ResizeFilter *resize_filter)
MagickExport MagickRealType GetResizeFilterSupport (const ResizeFilter *resize_filter)
MagickExport MagickRealType GetResizeFilterWeight (const ResizeFilter *resize_filter, const MagickRealType x)
MagickExport Image * InterpolativeResizeImage (const Image *image, const size_t columns, const size_t rows, const InterpolatePixelMethod method, ExceptionInfo *exception)
MagickExport Image * LiquidRescaleImage (const Image *image, const size_t magick_unused(columns), const size_t magick_unused(rows), const double magick_unused(delta_x), const double magick_unused(rigidity), ExceptionInfo *exception)
MagickExport Image * MagnifyImage (const Image *image, ExceptionInfo *exception)
MagickExport Image * MinifyImage (const Image *image, ExceptionInfo *exception)
MagickExport Image * ResampleImage (const Image *image, const double x_resolution, const double y_resolution, const FilterTypes filter, const double blur, ExceptionInfo *exception)
static ContributionInfo ** DestroyContributionThreadSet (ContributionInfo **contribution)
static ContributionInfo ** AcquireContributionThreadSet (const size_t count)
static MagickBooleanType HorizontalFilter (const ResizeFilter *magick_restrict resize_filter, const Image *magick_restrict image, Image *magick_restrict resize_image, const MagickRealType x_factor, const MagickSizeType span, MagickOffsetType *magick_restrict offset, ExceptionInfo *exception)
static MagickBooleanType VerticalFilter (const ResizeFilter *magick_restrict resize_filter, const Image *magick_restrict image, Image *magick_restrict resize_image, const MagickRealType y_factor, const MagickSizeType span, MagickOffsetType *magick_restrict offset, ExceptionInfo *exception)
MagickExport Image * ResizeImage (const Image *image, const size_t columns, const size_t rows, const FilterTypes filter, const double blur, ExceptionInfo *exception)
MagickExport Image * SampleImage (const Image *image, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport Image * ScaleImage (const Image *image, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport Image * ThumbnailImage (const Image *image, const size_t columns, const size_t rows, ExceptionInfo *exception)
Macro Definition Documentation
InterpolativeResizeImageTag
#define InterpolativeResizeImageTag "Resize/Image"
MagnifyImageTag
#define MagnifyImageTag "Magnify/Image"
ResampleImageTag
#define ResampleImageTag "Resample/Image"
ResizeImageTag
#define ResizeImageTag "Resize/Image"
SampleFactor
#define SampleFactor 5
SampleImageTag
#define SampleImageTag "Sample/Image"
ScaleImageTag
#define ScaleImageTag "Scale/Image"
Typedef Documentation
ContributionInfo
typedef struct _ContributionInfo ContributionInfo
Function Documentation
AcquireContributionThreadSet()
static ContributionInfo ** AcquireContributionThreadSet (const size_t count) static
References AcquireAlignedMemory(), AcquireQuantumMemory(), DestroyContributionThreadSet(), GetMagickResourceLimit(), MagickAssumeAligned, and ThreadResource.
Referenced by HorizontalFilter(), and VerticalFilter().
AcquireResizeFilter()
MagickExport ResizeFilter * AcquireResizeFilter (const Image * image, const FilterTypes filter, const MagickRealType blur, const MagickBooleanType cylindrical, ExceptionInfo * exception)
References AcquireMagickMemory(), Blackman(), BlackmanFilter, BlackmanWeightingFunction, _ResizeFilter::blur, Bohman(), BohmanFilter, BohmanWeightingFunction, Box(), BoxFilter, BoxWeightingFunction, CatromFilter, _ResizeFilter::coefficient, CommandOptionToMnemonic(), Cosine(), CosineFilter, CosineWeightingFunction, CubicBC(), CubicBCWeightingFunction, CubicFilter, _Image::debug, DeleteImageArtifact(), _Image::filename, _ResizeFilter::filter, _ResizeFilter::filterWeightingType, FormatLocaleFile(), Gaussian(), GaussianFilter, GaussianWeightingFunction, GetImageArtifact(), GetMagickModule, GetMagickPrecision(), GetResizeFilterSupport(), GetResizeFilterWeight(), Hamming(), HammingFilter, HammingWeightingFunction, Hanning(), HanningFilter, HanningWeightingFunction, HermiteFilter, I0(), IsMagickTrue(), Jinc(), JincFilter, JincWeightingFunction, Kaiser(), KaiserFilter, KaiserWeightingFunction, Lagrange(), LagrangeFilter, LagrangeWeightingFunction, Lanczos2Filter, Lanczos2SharpFilter, LanczosFilter, LanczosRadiusFilter, LanczosSharpFilter, LogMagickEvent(), Magick2PI, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickFilterOptions, MagickPI, MagickSQ1_2, MitchellFilter, ParseCommandOption(), PerceptibleReciprocal(), PointFilter, Quadratic(), QuadraticFilter, QuadraticWeightingFunction, ResourceLimitFatalError, RobidouxFilter, RobidouxSharpFilter, _ResizeFilter::scale, SentinelFilter, _ExceptionInfo::signature, _Image::signature, _ResizeFilter::signature, Sinc(), SincFast(), SincFastFilter, SincFastWeightingFunction, SincFilter, SincWeightingFunction, SplineFilter, StringToDouble(), StringToLong(), _ResizeFilter::support, ThrowFatalException, TraceEvent, Triangle(), TriangleFilter, TriangleWeightingFunction, UndefinedFilter, Welsh(), WelshFilter, WelshWeightingFunction, _ResizeFilter::window, _ResizeFilter::window_support, and _ResizeFilter::windowWeightingType.
Referenced by ResizeImage().
AdaptiveResizeImage()
MagickExport Image * AdaptiveResizeImage (const Image * image, const size_t columns, const size_t rows, ExceptionInfo * exception)
References InterpolativeResizeImage(), and MeshInterpolatePixel.
BesselOrderOne()
static MagickRealType BesselOrderOne (MagickRealType x)
References J1(), MagickPI, P1(), and Q1().
Referenced by Jinc().
Blackman()
static MagickRealType Blackman (const MagickRealType x, const ResizeFilter * magick_unusedresize_filter) static
References magick_unreferenced, and MagickPI.
Referenced by AcquireResizeFilter().
Bohman()
static MagickRealType Bohman (const MagickRealType x, const ResizeFilter * magick_unusedresize_filter) static
References magick_unreferenced, and MagickPI.
Referenced by AcquireResizeFilter().
Box()
static MagickRealType Box (const MagickRealType magick_unusedx, const ResizeFilter * magick_unusedresize_filter) static
References magick_unreferenced.
Referenced by AcquireResizeFilter(), and GetResizeFilterWeight().
Cosine()
static MagickRealType Cosine (const MagickRealType x, const ResizeFilter * magick_unusedresize_filter) static
References magick_unreferenced, and MagickPI2.
Referenced by AcquireResizeFilter().
CubicBC()
static MagickRealType CubicBC (const MagickRealType x, const ResizeFilter * resize_filter) static
References _ResizeFilter::coefficient.
Referenced by AcquireResizeFilter().
DestroyContributionThreadSet()
static ContributionInfo ** DestroyContributionThreadSet (ContributionInfo ** contribution) static
References GetMagickResourceLimit(), RelinquishAlignedMemory(), RelinquishMagickMemory(), and ThreadResource.
Referenced by AcquireContributionThreadSet(), HorizontalFilter(), and VerticalFilter().
DestroyResizeFilter()
MagickExport ResizeFilter * DestroyResizeFilter (ResizeFilter * resize_filter)
References MagickCoreSignature, RelinquishMagickMemory(), and _ResizeFilter::signature.
Referenced by DestroyResampleFilter(), ResizeImage(), and SetResampleFilter().
Gaussian()
static MagickRealType Gaussian (const MagickRealType x, const ResizeFilter * resize_filter) static
References _ResizeFilter::coefficient.
Referenced by AcquireResizeFilter().
GetResizeFilterBlur()
MagickExport MagickRealType GetResizeFilterBlur (const ResizeFilter * resize_filter)
References _ResizeFilter::blur, MagickCoreSignature, and _ResizeFilter::signature.
GetResizeFilterCoefficient()
MagickExport MagickRealType * GetResizeFilterCoefficient (const ResizeFilter * resize_filter)
References _ResizeFilter::coefficient, MagickCoreSignature, and _ResizeFilter::signature.
GetResizeFilterScale()
MagickExport MagickRealType GetResizeFilterScale (const ResizeFilter * resize_filter)
References MagickCoreSignature, _ResizeFilter::scale, and _ResizeFilter::signature.
GetResizeFilterSupport()
MagickExport MagickRealType GetResizeFilterSupport (const ResizeFilter * resize_filter)
References _ResizeFilter::blur, MagickCoreSignature, _ResizeFilter::signature, and _ResizeFilter::support.
Referenced by AcquireResizeFilter(), HorizontalFilter(), and VerticalFilter().
GetResizeFilterWeight()
MagickExport MagickRealType GetResizeFilterWeight (const ResizeFilter * resize_filter, const MagickRealType x)
References _ResizeFilter::blur, Box(), _ResizeFilter::filter, MagickCoreSignature, MagickEpsilon, PerceptibleReciprocal(), _ResizeFilter::scale, _ResizeFilter::signature, _ResizeFilter::window, and _ResizeFilter::window_support.
Referenced by AcquireResizeFilter(), HorizontalFilter(), ResamplePixelColor(), SetResampleFilter(), and VerticalFilter().
GetResizeFilterWeightingType()
MagickExport ResizeWeightingFunctionType GetResizeFilterWeightingType (const ResizeFilter * resize_filter)
References _ResizeFilter::filterWeightingType, MagickCoreSignature, and _ResizeFilter::signature.
GetResizeFilterWindowSupport()
MagickExport MagickRealType GetResizeFilterWindowSupport (const ResizeFilter * resize_filter)
References MagickCoreSignature, _ResizeFilter::signature, and _ResizeFilter::window_support.
GetResizeFilterWindowWeightingType()
MagickExport ResizeWeightingFunctionType GetResizeFilterWindowWeightingType (const ResizeFilter * resize_filter)
References MagickCoreSignature, _ResizeFilter::signature, and _ResizeFilter::windowWeightingType.
Hamming()
static MagickRealType Hamming (const MagickRealType x, const ResizeFilter * magick_unusedresize_filter) static
References magick_unreferenced, and MagickPI.
Referenced by AcquireResizeFilter().
Hanning()
static MagickRealType Hanning (const MagickRealType x, const ResizeFilter * magick_unusedresize_filter) static
References magick_unreferenced, and MagickPI.
Referenced by AcquireResizeFilter().
HorizontalFilter()
static MagickBooleanType HorizontalFilter (const ResizeFilter *magick_restrict resize_filter, const Image *magick_restrict image, Image *magick_restrict resize_image, const MagickRealType x_factor, const MagickSizeType span, MagickOffsetType *magick_restrict offset, ExceptionInfo * exception) static
References AcquireAuthenticCacheView(), AcquireContributionThreadSet(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, ClampToQuantum(), CMYKColorspace, DestroyCacheView(), DestroyContributionThreadSet(), DirectClass, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetOpenMPThreadId(), GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, GetResizeFilterSupport(), GetResizeFilterWeight(), _MagickPixelPacket::green, _MagickPixelPacket::index, InheritException(), magick_restrict, MagickEpsilon, MagickFalse, MagickMax, MagickMin, MagickTrue, _MagickPixelPacket::opacity, PerceptibleReciprocal(), PseudoClass, QuantumScale, QueueCacheViewAuthenticPixels(), _MagickPixelPacket::red, ResizeImageTag, ResourceLimitError, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, SyncCacheViewAuthenticPixels(), and ThrowMagickException().
Referenced by ResizeImage().
I0()
static MagickRealType I0 (MagickRealType x) static
References MagickEpsilon.
Referenced by AcquireResizeFilter(), and Kaiser().
InterpolativeResizeImage()
MagickExport Image * InterpolativeResizeImage (const Image * image, const size_t columns, const size_t rows, const InterpolatePixelMethod method, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetMagickModule, GetMagickPixelPacket(), InheritException(), InterpolateMagickPixelPacket(), InterpolativeResizeImageTag, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelPacket(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, _PointInfo::x, and _PointInfo::y.
Referenced by AdaptiveResizeImage().
J1()
static MagickRealType J1 (MagickRealType x) static
Referenced by BesselOrderOne().
Jinc()
static MagickRealType Jinc (const MagickRealType x, const ResizeFilter * magick_unusedresize_filter) static
References BesselOrderOne(), magick_unreferenced, and MagickPI.
Referenced by AcquireResizeFilter().
Kaiser()
static MagickRealType Kaiser (const MagickRealType x, const ResizeFilter * resize_filter) static
References _ResizeFilter::coefficient, and I0().
Referenced by AcquireResizeFilter().
Lagrange()
static MagickRealType Lagrange (const MagickRealType x, const ResizeFilter * resize_filter) static
References _ResizeFilter::support, and _ResizeFilter::window_support.
Referenced by AcquireResizeFilter().
LiquidRescaleImage()
MagickExport Image * LiquidRescaleImage (const Image * image, const size_t magick_unusedcolumns, const size_t magick_unusedrows, const double magick_unuseddelta_x, const double magick_unusedrigidity, ExceptionInfo * exception)
References _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MissingDelegateError, _ExceptionInfo::signature, _Image::signature, ThrowMagickException(), and TraceEvent.
MagnifyImage()
MagickExport Image * MagnifyImage (const Image * image, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelIntensity(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickTrue, MagnifyImageTag, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
MinifyImage()
MagickExport Image * MinifyImage (const Image * image, ExceptionInfo * exception)
References _Image::columns, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, ResizeImage(), _Image::rows, _ExceptionInfo::signature, _Image::signature, SplineFilter, and TraceEvent.
P1()
static MagickRealType P1 (MagickRealType x) static
Referenced by BesselOrderOne().
Q1()
static MagickRealType Q1 (MagickRealType x) static
Referenced by BesselOrderOne().
Quadratic()
static MagickRealType Quadratic (const MagickRealType x, const ResizeFilter * magick_unusedresize_filter) static
References magick_unreferenced.
Referenced by AcquireResizeFilter().
ResampleImage()
MagickExport Image * ResampleImage (const Image * image, const double x_resolution, const double y_resolution, const FilterTypes filter, const double blur, ExceptionInfo * exception)
References _Image::columns, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, ResizeImage(), _Image::rows, _ExceptionInfo::signature, _Image::signature, TraceEvent, _Image::x_resolution, and _Image::y_resolution.
ResizeImage()
MagickExport Image * ResizeImage (const Image * image, const size_t columns, const size_t rows, const FilterTypes filter, const double blur, ExceptionInfo * exception)
References AcquireResizeFilter(), CloneImage(), _Image::columns, _Image::debug, DestroyImage(), DestroyResizeFilter(), _Image::filename, GetMagickModule, HorizontalFilter(), ImageError, LanczosFilter, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, MitchellFilter, PointFilter, PseudoClass, _Image::rows, _ExceptionInfo::signature, _Image::signature, _Image::storage_class, ThrowImageException, TraceEvent, _Image::type, UndefinedFilter, and VerticalFilter().
Referenced by InterpolateMagickPixelPacket(), InterpolatePixelColor(), MinifyImage(), MorphImages(), ReadImage(), ResampleImage(), ResamplePixelColor(), ThumbnailImage(), TransformImage(), and ZoomImage().
SampleImage()
MagickExport Image * SampleImage (const Image * image, const size_t columns, const size_t rows, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), AcquireVirtualCacheView(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualPixels(), GetImageArtifact(), GetMagickModule, GetPixelIndex, ImageError, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickTrue, ParseGeometry(), _Image::progress_monitor, PseudoClass, QueueCacheViewAuthenticPixels(), RelinquishMagickMemory(), ResourceLimitError, _GeometryInfo::rho, _Image::rows, SampleImageTag, SetImageProgress(), SetPixelIndex, _GeometryInfo::sigma, SigmaValue, _ExceptionInfo::signature, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, _Image::type, _PointInfo::x, and _PointInfo::y.
Referenced by ThumbnailImage().
ScaleImage()
MagickExport Image * ScaleImage (const Image * image, const size_t columns, const size_t rows, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, ClampToQuantum(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _MagickPixelPacket::green, _MagickPixelPacket::index, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _MagickPixelPacket::opacity, PerceptibleReciprocal(), QuantumScale, QueueCacheViewAuthenticPixels(), _MagickPixelPacket::red, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, ScaleImageTag, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, _Image::type, _PointInfo::x, and _PointInfo::y.
Sinc() [1/2]
static MagickRealType Sinc (const MagickRealType x, const ResizeFilter * magick_unusedresize_filter) static
References magick_unreferenced, and MagickPI.
Sinc() [2/2]
static MagickRealType Sinc (const MagickRealType, const ResizeFilter *)
Referenced by AcquireResizeFilter().
SincFast() [1/2]
static MagickRealType SincFast (const MagickRealType x, const ResizeFilter * magick_unusedresize_filter) static
References magick_unreferenced, and MagickPI.
SincFast() [2/2]
static MagickRealType SincFast (const MagickRealType, const ResizeFilter *)
Referenced by AcquireResizeFilter().
ThumbnailImage()
MagickExport Image * ThumbnailImage (const Image * image, const size_t columns, const size_t rows, ExceptionInfo * exception)
References _Image::blur, _Image::columns, ConcatenateMagickString(), CopyMagickString(), _Image::debug, DeleteImageProfile(), DeleteImageProperty(), _Image::depth, DestroyImage(), _Image::filename, _Image::filter, FormatLocaleString(), FormatMagickSize(), GetBlobSize(), GetImageListLength(), GetMagickModule, GetNextImageProfile(), GetPathAttributes(), GetPathComponent(), _Image::interlace, LocaleCompare(), LocaleLower(), LogMagickEvent(), _Image::magick, _Image::magick_columns, _Image::magick_filename, _Image::magick_rows, MagickAuthoritativeURL, MagickCoreSignature, MagickFalse, _Image::matte, MaxTextExtent, NoInterlace, OpaqueAlphaChannel, _Image::page, ParseAbsoluteGeometry(), ResetImageProfileIterator(), ResizeImage(), _Image::rows, SampleFactor, SampleImage(), SetImageAlphaChannel(), SetImageProperty(), _ExceptionInfo::signature, _Image::signature, TailPath, and TraceEvent.
Referenced by MontageImageList(), and PreviewImage().
Triangle()
static MagickRealType Triangle (const MagickRealType x, const ResizeFilter * magick_unusedresize_filter) static
References magick_unreferenced.
Referenced by AcquireResizeFilter().
VerticalFilter()
static MagickBooleanType VerticalFilter (const ResizeFilter *magick_restrict resize_filter, const Image *magick_restrict image, Image *magick_restrict resize_image, const MagickRealType y_factor, const MagickSizeType span, MagickOffsetType *magick_restrict offset, ExceptionInfo * exception) static
References AcquireAuthenticCacheView(), AcquireContributionThreadSet(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, ClampToQuantum(), CMYKColorspace, DestroyCacheView(), DestroyContributionThreadSet(), DirectClass, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetOpenMPThreadId(), GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, GetResizeFilterSupport(), GetResizeFilterWeight(), _MagickPixelPacket::green, _MagickPixelPacket::index, InheritException(), magick_restrict, MagickEpsilon, MagickFalse, MagickMax, MagickMin, MagickTrue, _MagickPixelPacket::opacity, PerceptibleReciprocal(), PseudoClass, QuantumScale, QueueCacheViewAuthenticPixels(), _MagickPixelPacket::red, ResizeImageTag, ResourceLimitError, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, SyncCacheViewAuthenticPixels(), and ThrowMagickException().
Referenced by ResizeImage().
Welsh()
static MagickRealType Welsh (const MagickRealType x, const ResizeFilter * magick_unusedresize_filter) static
References magick_unreferenced.
Referenced by AcquireResizeFilter().