MagickCore: resize-private.h File Reference
resize-private.h File Reference
Enumerations
enum ResizeWeightingFunctionType {
BoxWeightingFunction = 0 , TriangleWeightingFunction , CubicBCWeightingFunction , HanningWeightingFunction ,
HammingWeightingFunction , BlackmanWeightingFunction , GaussianWeightingFunction , QuadraticWeightingFunction ,
JincWeightingFunction , SincWeightingFunction , SincFastWeightingFunction , KaiserWeightingFunction ,
WelshWeightingFunction , BohmanWeightingFunction , LagrangeWeightingFunction , CosineWeightingFunction ,
LastWeightingFunction
}
Functions
MagickExport MagickRealType * GetResizeFilterCoefficient (const ResizeFilter *)
MagickExport MagickRealType GetResizeFilterBlur (const ResizeFilter *)
MagickExport MagickRealType GetResizeFilterScale (const ResizeFilter *)
MagickExport MagickRealType GetResizeFilterWindowSupport (const ResizeFilter *)
MagickExport MagickRealType GetResizeFilterSupport (const ResizeFilter *)
MagickExport MagickRealType GetResizeFilterWeight (const ResizeFilter *, const MagickRealType)
MagickExport ResizeFilter * AcquireResizeFilter (const Image *, const FilterTypes, const MagickRealType, const MagickBooleanType, ExceptionInfo *)
MagickExport ResizeFilter * DestroyResizeFilter (ResizeFilter *)
MagickExport ResizeWeightingFunctionType GetResizeFilterWeightingType (const ResizeFilter *)
MagickExport ResizeWeightingFunctionType GetResizeFilterWindowWeightingType (const ResizeFilter *)
Enumeration Type Documentation
ResizeWeightingFunctionType
enum ResizeWeightingFunctionType
Enumerator
BoxWeightingFunction
TriangleWeightingFunction
CubicBCWeightingFunction
HanningWeightingFunction
HammingWeightingFunction
BlackmanWeightingFunction
GaussianWeightingFunction
QuadraticWeightingFunction
JincWeightingFunction
SincWeightingFunction
SincFastWeightingFunction
KaiserWeightingFunction
WelshWeightingFunction
BohmanWeightingFunction
LagrangeWeightingFunction
CosineWeightingFunction
LastWeightingFunction
Function Documentation
AcquireResizeFilter()
MagickExport ResizeFilter * AcquireResizeFilter (const Image * , const FilterTypes, const MagickRealType, const MagickBooleanType, ExceptionInfo *)
Referenced by SetResampleFilter().
DestroyResizeFilter()
MagickExport ResizeFilter * DestroyResizeFilter (ResizeFilter * resize_filter)
References MagickCoreSignature, RelinquishMagickMemory(), and _ResizeFilter::signature.
Referenced by DestroyResampleFilter(), ResizeImage(), and SetResampleFilter().
GetResizeFilterBlur()
MagickExport MagickRealType GetResizeFilterBlur (const ResizeFilter *)
GetResizeFilterCoefficient()
MagickExport MagickRealType * GetResizeFilterCoefficient (const ResizeFilter *)
GetResizeFilterScale()
MagickExport MagickRealType GetResizeFilterScale (const ResizeFilter *)
GetResizeFilterSupport()
MagickExport MagickRealType GetResizeFilterSupport (const ResizeFilter *)
Referenced by SetResampleFilter().
GetResizeFilterWeight()
MagickExport MagickRealType GetResizeFilterWeight (const ResizeFilter * resize_filter, const MagickRealType)
References _ResizeFilter::blur, Box(), _ResizeFilter::filter, MagickCoreSignature, MagickEpsilon, PerceptibleReciprocal(), _ResizeFilter::scale, _ResizeFilter::signature, _ResizeFilter::window, and _ResizeFilter::window_support.
Referenced by AcquireResizeFilter(), HorizontalFilter(), ResamplePixelColor(), SetResampleFilter(), and VerticalFilter().
GetResizeFilterWeightingType()
MagickExport ResizeWeightingFunctionType GetResizeFilterWeightingType (const ResizeFilter *)
GetResizeFilterWindowSupport()
MagickExport MagickRealType GetResizeFilterWindowSupport (const ResizeFilter *)
GetResizeFilterWindowWeightingType()
MagickExport ResizeWeightingFunctionType GetResizeFilterWindowWeightingType (const ResizeFilter * resize_filter)
References MagickCoreSignature, _ResizeFilter::signature, and _ResizeFilter::windowWeightingType.