MagickCore: resource_.h File Reference
resource_.h File Reference
Macros
#define MagickResourceInfinity (MagickULLConstant(~0) >> 1)
Enumerations
enum ResourceType {
UndefinedResource , AreaResource , DiskResource , FileResource ,
MapResource , MemoryResource , ThreadResource , TimeResource ,
ThrottleResource , WidthResource , HeightResource , ListLengthResource
}
Functions
MagickExport int AcquireUniqueFileResource (char *)
MagickExport MagickBooleanType AcquireMagickResource (const ResourceType, const MagickSizeType)
MagickExport MagickBooleanType GetPathTemplate (char *)
MagickExport MagickBooleanType ListMagickResourceInfo (FILE *, ExceptionInfo *)
MagickExport MagickBooleanType RelinquishUniqueFileResource (const char *)
MagickExport MagickBooleanType ResourceComponentGenesis (void)
MagickExport MagickBooleanType SetMagickResourceLimit (const ResourceType, const MagickSizeType)
MagickExport MagickSizeType GetMagickResource (const ResourceType)
MagickExport MagickSizeType GetMagickResourceLimit (const ResourceType)
MagickExport void AsynchronousResourceComponentTerminus (void)
MagickExport void RelinquishMagickResource (const ResourceType, const MagickSizeType)
MagickExport void ResourceComponentTerminus (void)
Macro Definition Documentation
MagickResourceInfinity
#define MagickResourceInfinity (MagickULLConstant(~0) >> 1)
Enumeration Type Documentation
ResourceType
enum ResourceType
Enumerator
UndefinedResource
AreaResource
DiskResource
FileResource
MapResource
MemoryResource
ThreadResource
TimeResource
ThrottleResource
WidthResource
HeightResource
ListLengthResource
Function Documentation
AcquireMagickResource()
MagickExport MagickBooleanType AcquireMagickResource (const ResourceType, const MagickSizeType)
AcquireUniqueFileResource()
MagickExport int AcquireUniqueFileResource (char * path)
References AcquireRandomInfo(), ActivateSemaphoreInfo(), AddValueToSplayTree(), CompareSplayTreeString(), ConstantString(), DestroyStringInfo(), DestroyTemporaryResources(), FileResource, GetMagickModule, GetPathTemplate(), GetRandomKey(), GetStringInfoDatum(), GetStringInfoLength(), LockSemaphoreInfo(), LogMagickEvent(), MagickPathTemplate, NewSplayTree(), O_BINARY, O_NOFOLLOW, open_utf8(), random_info, resource_semaphore, ResourceEvent, S_MODE, temporary_resources, TMP_MAX, and UnlockSemaphoreInfo().
Referenced by AcquireMatrixInfo(), AcquireUniqueFilename(), AcquireUniqueSymbolicLink(), AcquireVirtualMemory(), BlobToFile(), HoughLineImage(), ImagesToBlob(), ImageToBlob(), ImageToFile(), InjectImageBlob(), OpenPixelCacheOnDisk(), PreviewImage(), and RenderPostscript().
AsynchronousResourceComponentTerminus()
MagickExport void AsynchronousResourceComponentTerminus (void)
GetMagickResource()
MagickExport MagickSizeType GetMagickResource (const ResourceType)
GetMagickResourceLimit()
MagickExport MagickSizeType GetMagickResourceLimit (const ResourceType)
References ActivateSemaphoreInfo(), _ResourceInfo::area_limit, AreaResource, _ResourceInfo::disk_limit, DiskResource, _ResourceInfo::file_limit, FileResource, _ResourceInfo::height_limit, HeightResource, _ResourceInfo::list_length_limit, ListLengthResource, LockSemaphoreInfo(), _ResourceInfo::map_limit, MapResource, _ResourceInfo::memory_limit, MemoryResource, resource_info, resource_semaphore, _ResourceInfo::thread_limit, ThreadResource, _ResourceInfo::throttle_limit, ThrottleResource, _ResourceInfo::time_limit, TimeResource, UnlockSemaphoreInfo(), _ResourceInfo::width_limit, and WidthResource.
Referenced by AcquireContributionThreadSet(), AcquireFxThreadSet(), AcquireHistogramThreadSet(), AcquirePixelCache(), AcquirePixelListThreadSet(), AcquirePixelThreadSet(), AcquirePolygonThreadSet(), AcquireQuantumPixels(), AcquireRandomInfoThreadSet(), AcquireResampleFilterThreadSet(), AcquireVirtualCacheView(), DestroyContributionThreadSet(), DestroyFxThreadSet(), DestroyHistogramThreadSet(), DestroyPixelListThreadSet(), DestroyPixelThreadSet(), DestroyPolygonThreadSet(), DestroyRandomInfoThreadSet(), DestroyResampleFilterThreadSet(), GetImageChannelDepth(), GetImagePixelCache(), NewImageView(), NewImageViewRegion(), OpenPixelCache(), and SetImageViewThreads().
GetPathTemplate()
MagickExport MagickBooleanType GetPathTemplate (char *)
ListMagickResourceInfo()
MagickExport MagickBooleanType ListMagickResourceInfo (FILE * , ExceptionInfo *)
RelinquishMagickResource()
MagickExport void RelinquishMagickResource (const ResourceType, const MagickSizeType)
RelinquishUniqueFileResource()
MagickExport MagickBooleanType RelinquishUniqueFileResource (const char *)
ResourceComponentGenesis()
MagickExport MagickBooleanType ResourceComponentGenesis (void)
ResourceComponentTerminus()
MagickExport void ResourceComponentTerminus (void)
References ActivateSemaphoreInfo(), DestroyRandomInfo(), DestroySemaphoreInfo(), DestroySplayTree(), FileResource, LockSemaphoreInfo(), NumberOfResourceTypes, random_info, resource_semaphore, temporary_resources, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
SetMagickResourceLimit()
MagickExport MagickBooleanType SetMagickResourceLimit (const ResourceType, const MagickSizeType)
References ActivateSemaphoreInfo(), _ResourceInfo::area_limit, AreaResource, DestroyString(), _ResourceInfo::disk_limit, DiskResource, _ResourceInfo::file_limit, FileResource, GetOpenMPMaximumThreads(), GetPolicyValue(), _ResourceInfo::height_limit, HeightResource, _ResourceInfo::list_length_limit, ListLengthResource, LockSemaphoreInfo(), MAGICK_SSIZE_MAX, MagickFalse, MagickMax, MagickMin, MagickTrue, _ResourceInfo::map_limit, MapResource, _ResourceInfo::memory_limit, MemoryResource, ResetPixelCacheEpoch(), resource_info, resource_semaphore, StringToSizeType(), _ResourceInfo::thread_limit, ThreadResource, _ResourceInfo::throttle_limit, ThrottleResource, _ResourceInfo::time_limit, TimeResource, UnlockSemaphoreInfo(), _ResourceInfo::width_limit, and WidthResource.
Referenced by ResourceComponentGenesis(), and SetCacheThreshold().