MagickCore: resource.c File Reference
resource.c File Reference
#include "magick/studio.h"
#include "magick/cache.h"
#include "magick/cache-private.h"
#include "magick/configure.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/hashmap.h"
#include "magick/log.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/memory_.h"
#include "magick/nt-base-private.h"
#include "magick/option.h"
#include "magick/policy.h"
#include "magick/random_.h"
#include "magick/registry.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/signature-private.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/splay-tree.h"
#include "magick/thread-private.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/utility-private.h"
Data Structures
struct _ResourceInfo
Macros
#define MagickPathTemplate "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" /* min 6 X's */
#define NumberOfResourceTypes (sizeof(resource_semaphore)/sizeof(*resource_semaphore))
#define O_NOFOLLOW 0
#define TMP_MAX 238328
Typedefs
typedef struct _ResourceInfo ResourceInfo
Functions
MagickExport MagickBooleanType AcquireMagickResource (const ResourceType type, const MagickSizeType size)
MagickExport void AsynchronousResourceComponentTerminus (void)
static void * DestroyTemporaryResources (void *temporary_resource)
MagickExport MagickBooleanType GetPathTemplate (char *path)
MagickExport int AcquireUniqueFileResource (char *path)
MagickExport MagickSizeType GetMagickResource (const ResourceType type)
MagickExport MagickSizeType GetMagickResourceLimit (const ResourceType type)
static ssize_t FormatPixelSize (const MagickSizeType size, const MagickBooleanType bi, char *format)
MagickExport MagickBooleanType ListMagickResourceInfo (FILE *file, ExceptionInfo *magick_unused(exception))
MagickExport void RelinquishMagickResource (const ResourceType type, const MagickSizeType size)
MagickExport MagickBooleanType RelinquishUniqueFileResource (const char *path)
MagickExport MagickBooleanType ResourceComponentGenesis (void)
MagickExport void ResourceComponentTerminus (void)
MagickExport MagickBooleanType SetMagickResourceLimit (const ResourceType type, const MagickSizeType limit)
Variables
static RandomInfo * random_info = (RandomInfo *) NULL
static ResourceInfo resource_info
static SemaphoreInfo * resource_semaphore []
static SplayTreeInfo * temporary_resources = (SplayTreeInfo *) NULL
Macro Definition Documentation
MagickPathTemplate
#define MagickPathTemplate "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" /* min 6 X's */
NumberOfResourceTypes
#define NumberOfResourceTypes (sizeof(resource_semaphore)/sizeof(*resource_semaphore))
O_NOFOLLOW
#define O_NOFOLLOW 0
TMP_MAX
#define TMP_MAX 238328
Typedef Documentation
ResourceInfo
typedef struct _ResourceInfo ResourceInfo
Function Documentation
AcquireMagickResource()
MagickExport MagickBooleanType AcquireMagickResource (const ResourceType type, const MagickSizeType size)
References ActivateSemaphoreInfo(), _ResourceInfo::area, _ResourceInfo::area_limit, AreaResource, CommandOptionToMnemonic(), _ResourceInfo::disk, _ResourceInfo::disk_limit, DiskResource, _ResourceInfo::file, _ResourceInfo::file_limit, FileResource, FormatMagickSize(), GetMagickModule, _ResourceInfo::height, _ResourceInfo::height_limit, HeightResource, IsEventLogging(), _ResourceInfo::list_length, _ResourceInfo::list_length_limit, ListLengthResource, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickResourceInfinity, MagickResourceOptions, MagickTrue, _ResourceInfo::map, _ResourceInfo::map_limit, MapResource, MaxTextExtent, _ResourceInfo::memory, _ResourceInfo::memory_limit, MemoryResource, resource_info, resource_semaphore, ResourceEvent, _ResourceInfo::thread, _ResourceInfo::thread_limit, ThreadResource, _ResourceInfo::throttle, _ResourceInfo::throttle_limit, ThrottleResource, _ResourceInfo::time, _ResourceInfo::time_limit, TimeResource, UnlockSemaphoreInfo(), _ResourceInfo::width, _ResourceInfo::width_limit, and WidthResource.
Referenced by AcquireMatrixInfo(), CloneBlobInfo(), GetMultilineTypeMetrics(), OpenBlob(), OpenPixelCache(), OpenPixelCacheOnDisk(), PersistPixelCache(), SetBlobExtent(), and WaveletDenoiseImage().
AcquireUniqueFileResource()
MagickExport int AcquireUniqueFileResource (char * path)
References AcquireRandomInfo(), ActivateSemaphoreInfo(), AddValueToSplayTree(), CompareSplayTreeString(), ConstantString(), DestroyStringInfo(), DestroyTemporaryResources(), FileResource, GetMagickModule, GetPathTemplate(), GetRandomKey(), GetStringInfoDatum(), GetStringInfoLength(), LockSemaphoreInfo(), LogMagickEvent(), MagickPathTemplate, NewSplayTree(), O_BINARY, O_NOFOLLOW, open_utf8(), random_info, resource_semaphore, ResourceEvent, S_MODE, temporary_resources, TMP_MAX, and UnlockSemaphoreInfo().
Referenced by AcquireMatrixInfo(), AcquireUniqueFilename(), AcquireUniqueSymbolicLink(), AcquireVirtualMemory(), BlobToFile(), HoughLineImage(), ImagesToBlob(), ImageToBlob(), ImageToFile(), InjectImageBlob(), OpenPixelCacheOnDisk(), PreviewImage(), and RenderPostscript().
AsynchronousResourceComponentTerminus()
MagickExport void AsynchronousResourceComponentTerminus (void)
References GetNextKeyInSplayTree(), ResetSplayTreeIterator(), ShredFile(), and temporary_resources.
Referenced by MagickCoreTerminus(), and MagickSignalHandler().
DestroyTemporaryResources()
static void * DestroyTemporaryResources (void * temporary_resource) static
References DestroyString(), and ShredFile().
Referenced by AcquireUniqueFileResource().
FormatPixelSize()
static ssize_t FormatPixelSize (const MagickSizeType size, const MagickBooleanType bi, char * format) static
References FormatLocaleString(), MagickFalse, and MaxTextExtent.
Referenced by ListMagickResourceInfo().
GetMagickResource()
MagickExport MagickSizeType GetMagickResource (const ResourceType type)
References ActivateSemaphoreInfo(), _ResourceInfo::area, AreaResource, _ResourceInfo::disk, DiskResource, _ResourceInfo::file, FileResource, _ResourceInfo::height, HeightResource, _ResourceInfo::list_length, ListLengthResource, LockSemaphoreInfo(), _ResourceInfo::map, MapResource, _ResourceInfo::memory, MemoryResource, resource_info, resource_semaphore, _ResourceInfo::thread, ThreadResource, _ResourceInfo::throttle, ThrottleResource, _ResourceInfo::time, TimeResource, UnlockSemaphoreInfo(), _ResourceInfo::width, and WidthResource.
GetMagickResourceLimit()
MagickExport MagickSizeType GetMagickResourceLimit (const ResourceType type)
References ActivateSemaphoreInfo(), _ResourceInfo::area_limit, AreaResource, _ResourceInfo::disk_limit, DiskResource, _ResourceInfo::file_limit, FileResource, _ResourceInfo::height_limit, HeightResource, _ResourceInfo::list_length_limit, ListLengthResource, LockSemaphoreInfo(), _ResourceInfo::map_limit, MapResource, _ResourceInfo::memory_limit, MemoryResource, resource_info, resource_semaphore, _ResourceInfo::thread_limit, ThreadResource, _ResourceInfo::throttle_limit, ThrottleResource, _ResourceInfo::time_limit, TimeResource, UnlockSemaphoreInfo(), _ResourceInfo::width_limit, and WidthResource.
Referenced by AcquireContributionThreadSet(), AcquireFxThreadSet(), AcquireHistogramThreadSet(), AcquirePixelCache(), AcquirePixelListThreadSet(), AcquirePixelThreadSet(), AcquirePolygonThreadSet(), AcquireQuantumPixels(), AcquireRandomInfoThreadSet(), AcquireResampleFilterThreadSet(), AcquireVirtualCacheView(), DestroyContributionThreadSet(), DestroyFxThreadSet(), DestroyHistogramThreadSet(), DestroyPixelListThreadSet(), DestroyPixelThreadSet(), DestroyPolygonThreadSet(), DestroyRandomInfoThreadSet(), DestroyResampleFilterThreadSet(), GetImageChannelDepth(), GetImagePixelCache(), NewImageView(), NewImageViewRegion(), OpenPixelCache(), and SetImageViewThreads().
GetPathTemplate()
MagickExport MagickBooleanType GetPathTemplate (char * path)
References AcquireExceptionInfo(), CloneString(), ConstantString(), DestroyExceptionInfo(), DestroyString(), DirectorySeparator, FormatLocaleString(), GetEnvironmentValue(), GetImageRegistry(), GetPathAttributes(), GetPolicyValue(), MagickFalse, MagickPathTemplate, MagickTrue, MaxTextExtent, S_ISDIR, and StringRegistryType.
Referenced by AcquireUniqueFileResource().
ListMagickResourceInfo()
MagickExport MagickBooleanType ListMagickResourceInfo (FILE * file, ExceptionInfo * magick_unusedexception)
References ActivateSemaphoreInfo(), _ResourceInfo::area_limit, CopyMagickString(), _ResourceInfo::disk_limit, _ResourceInfo::file_limit, FileResource, FormatLocaleFile(), FormatLocaleString(), FormatMagickSize(), FormatPixelSize(), _ResourceInfo::height_limit, _ResourceInfo::list_length_limit, LockSemaphoreInfo(), magick_unreferenced, MagickFalse, MagickResourceInfinity, MagickTrue, _ResourceInfo::map_limit, MaxTextExtent, _ResourceInfo::memory_limit, resource_info, resource_semaphore, _ResourceInfo::thread_limit, _ResourceInfo::throttle_limit, _ResourceInfo::time_limit, UnlockSemaphoreInfo(), and _ResourceInfo::width_limit.
RelinquishMagickResource()
MagickExport void RelinquishMagickResource (const ResourceType type, const MagickSizeType size)
References ActivateSemaphoreInfo(), _ResourceInfo::area, _ResourceInfo::area_limit, AreaResource, CommandOptionToMnemonic(), _ResourceInfo::disk, _ResourceInfo::disk_limit, DiskResource, _ResourceInfo::file, _ResourceInfo::file_limit, FileResource, FormatMagickSize(), GetMagickModule, _ResourceInfo::height, _ResourceInfo::height_limit, HeightResource, IsEventLogging(), _ResourceInfo::list_length, _ResourceInfo::list_length_limit, ListLengthResource, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MagickResourceOptions, MagickTrue, _ResourceInfo::map, _ResourceInfo::map_limit, MapResource, MaxTextExtent, _ResourceInfo::memory, _ResourceInfo::memory_limit, MemoryResource, resource_info, resource_semaphore, ResourceEvent, _ResourceInfo::thread, _ResourceInfo::thread_limit, ThreadResource, _ResourceInfo::throttle, _ResourceInfo::throttle_limit, ThrottleResource, _ResourceInfo::time, _ResourceInfo::time_limit, TimeResource, UnlockSemaphoreInfo(), _ResourceInfo::width, _ResourceInfo::width_limit, and WidthResource.
Referenced by AcquireMatrixInfo(), ClosePixelCacheOnDisk(), DestroyBlob(), DestroyMatrixInfo(), DetachBlob(), OpenBlob(), OpenPixelCache(), RelinquishPixelCachePixels(), and SetBlobExtent().
RelinquishUniqueFileResource()
MagickExport MagickBooleanType RelinquishUniqueFileResource (const char * path)
References access_utf8(), ActivateSemaphoreInfo(), AppendImageFormat(), CopyMagickString(), DeleteNodeFromSplayTree(), FileResource, GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, MaxTextExtent, resource_semaphore, ResourceEvent, ShredFile(), temporary_resources, and UnlockSemaphoreInfo().
Referenced by AcquireUniqueSymbolicLink(), AcquireVirtualMemory(), BlobToImage(), DestroyMatrixInfo(), HoughLineImage(), ImagesToBlob(), ImageToBlob(), InjectImageBlob(), InvokeDelegate(), PingBlob(), PreviewImage(), ReadImage(), RelinquishPixelCachePixels(), RelinquishVirtualMemory(), RenderPostscript(), SetImageInfo(), TemporaryFilename(), and WriteImage().
ResourceComponentGenesis()
MagickExport MagickBooleanType ResourceComponentGenesis (void)
References ActivateSemaphoreInfo(), AreaResource, DestroyString(), DiskResource, FileResource, GetEnvironmentValue(), GetMagickPageSize(), GetOpenMPMaximumThreads(), _ResourceInfo::height_limit, HeightResource, ListLengthResource, MagickMax, MagickResourceInfinity, MagickTrue, MapResource, MemoryResource, NumberOfResourceTypes, resource_info, resource_semaphore, SetMagickResourceLimit(), StringToSizeType(), ThreadResource, ThrottleResource, TimeResource, _ResourceInfo::width_limit, and WidthResource.
Referenced by MagickCoreGenesis(), and SetMagickSecurityPolicy().
ResourceComponentTerminus()
MagickExport void ResourceComponentTerminus (void)
References ActivateSemaphoreInfo(), DestroyRandomInfo(), DestroySemaphoreInfo(), DestroySplayTree(), FileResource, LockSemaphoreInfo(), NumberOfResourceTypes, random_info, resource_semaphore, temporary_resources, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
SetMagickResourceLimit()
MagickExport MagickBooleanType SetMagickResourceLimit (const ResourceType type, const MagickSizeType limit)
References ActivateSemaphoreInfo(), _ResourceInfo::area_limit, AreaResource, DestroyString(), _ResourceInfo::disk_limit, DiskResource, _ResourceInfo::file_limit, FileResource, GetOpenMPMaximumThreads(), GetPolicyValue(), _ResourceInfo::height_limit, HeightResource, _ResourceInfo::list_length_limit, ListLengthResource, LockSemaphoreInfo(), MAGICK_SSIZE_MAX, MagickFalse, MagickMax, MagickMin, MagickTrue, _ResourceInfo::map_limit, MapResource, _ResourceInfo::memory_limit, MemoryResource, ResetPixelCacheEpoch(), resource_info, resource_semaphore, StringToSizeType(), _ResourceInfo::thread_limit, ThreadResource, _ResourceInfo::throttle_limit, ThrottleResource, _ResourceInfo::time_limit, TimeResource, UnlockSemaphoreInfo(), _ResourceInfo::width_limit, and WidthResource.
Referenced by ResourceComponentGenesis(), and SetCacheThreshold().
Variable Documentation
random_info
RandomInfo* random_info = (RandomInfo *) NULL static
Referenced by AcquireRandomInfo(), AcquireRandomInfoThreadSet(), AcquireUniqueFileResource(), AddNoiseImageChannel(), ApplyEvaluateOperator(), DestroyRandomInfo(), DestroyRandomInfoThreadSet(), DistributePixelCacheClient(), EvaluateImageChannel(), EvaluateImages(), GenerateDifferentialNoise(), GenerateEntropicChaos(), GetPseudoRandomValue(), GetRandomInfoNormalize(), GetRandomInfoSeed(), GetRandomKey(), GetRandomSecretKey(), GetRandomValue(), PlasmaImage(), PlasmaImageProxy(), PlasmaPixel(), RandomChannelThresholdImage(), RandomThresholdImageChannel(), RandomX(), RandomY(), ResourceComponentTerminus(), SetRandomKey(), ShredFile(), SketchImage(), and SpreadImage().
resource_info
ResourceInfo resource_info static
Initial value:
=
  {
    MagickULLConstant(0),
    MagickULLConstant(0),
    MagickULLConstant(0),
    MagickULLConstant(0),
    MagickULLConstant(0),
    MagickULLConstant(0),
    MagickULLConstant(0),
    MagickULLConstant(0),
    MagickULLConstant(0),
    MagickULLConstant(0),
    MagickULLConstant(0),
    MAGICK_SSIZE_MAX/sizeof(PixelPacket),
    MAGICK_SSIZE_MAX/sizeof(PixelPacket),
    MagickResourceInfinity,
    MagickULLConstant(3072)*1024*1024,
    MagickULLConstant(1536)*1024*1024,
    MagickULLConstant(3072)*1024*1024,
    MagickResourceInfinity,
    MagickULLConstant(768),
    MagickULLConstant(1),
    MagickULLConstant(0),
    MagickResourceInfinity
  }
Referenced by AcquireMagickResource(), GetMagickResource(), GetMagickResourceLimit(), ListMagickResourceInfo(), RelinquishMagickResource(), ResourceComponentGenesis(), and SetMagickResourceLimit().
resource_semaphore
SemaphoreInfo* resource_semaphore[] static
Initial value:
= {
     (SemaphoreInfo *) NULL,
     (SemaphoreInfo *) NULL,
     (SemaphoreInfo *) NULL,
     (SemaphoreInfo *) NULL,
     (SemaphoreInfo *) NULL,
     (SemaphoreInfo *) NULL,
     (SemaphoreInfo *) NULL,
     (SemaphoreInfo *) NULL,
     (SemaphoreInfo *) NULL,
     (SemaphoreInfo *) NULL,
     (SemaphoreInfo *) NULL,
     (SemaphoreInfo *) NULL
  }
Referenced by AcquireMagickResource(), AcquireUniqueFileResource(), GetMagickResource(), GetMagickResourceLimit(), ListMagickResourceInfo(), RelinquishMagickResource(), RelinquishUniqueFileResource(), ResourceComponentGenesis(), ResourceComponentTerminus(), and SetMagickResourceLimit().
temporary_resources
SplayTreeInfo* temporary_resources = (SplayTreeInfo *) NULL static
Referenced by AcquireUniqueFileResource(), AsynchronousResourceComponentTerminus(), RelinquishUniqueFileResource(), and ResourceComponentTerminus().