MagickCore: segment.c File Reference
segment.c File Reference
#include "magick/studio.h"
#include "magick/cache.h"
#include "magick/color.h"
#include "magick/colormap.h"
#include "magick/colorspace.h"
#include "magick/colorspace-private.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/memory_.h"
#include "magick/memory-private.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/quantize.h"
#include "magick/quantum.h"
#include "magick/quantum-private.h"
#include "magick/resource_.h"
#include "magick/segment.h"
#include "magick/string_.h"
#include "magick/thread-private.h"
Data Structures
struct _ExtentPacket
struct _Cluster
struct _IntervalTree
struct _ZeroCrossing
Macros
#define MaxDimension 3
#define DeltaTau 0.5f
#define WeightingExponent 2.5
#define SegmentPower(ratio) pow(ratio,(double) (1.0/(weighting_exponent-1.0)));
#define Tau 5.2f
#define SegmentImageTag "Segment/Image"
#define ThrowClassifyException(severity, tag, label)
Typedefs
typedef struct _ExtentPacket ExtentPacket
typedef struct _Cluster Cluster
typedef struct _IntervalTree IntervalTree
typedef struct _ZeroCrossing ZeroCrossing
Functions
static MagickRealType OptimalTau (const ssize_t *, const double, const double, const double, const double, short *)
static ssize_t DefineRegion (const short *, ExtentPacket *)
static void FreeNodes (IntervalTree *)
static void InitializeHistogram (const Image *, ssize_t **, ExceptionInfo *)
static void ScaleSpace (const ssize_t *, const MagickRealType, MagickRealType *)
static void ZeroCrossHistogram (MagickRealType *, const MagickRealType, short *)
static MagickBooleanType Classify (Image *image, short **extrema, const MagickRealType cluster_threshold, const MagickRealType weighting_exponent, const MagickBooleanType verbose)
static void ConsolidateCrossings (ZeroCrossing *zero_crossing, const size_t number_crossings)
static void DerivativeHistogram (const MagickRealType *histogram, MagickRealType *derivative)
MagickExport MagickBooleanType GetImageDynamicThreshold (const Image *image, const double cluster_threshold, const double smooth_threshold, MagickPixelPacket *pixel, ExceptionInfo *exception)
static void InitializeList (IntervalTree **list, ssize_t *number_nodes, IntervalTree *node)
static void MeanStability (IntervalTree *node)
static void Stability (IntervalTree *node)
static IntervalTree * InitializeIntervalTree (const ZeroCrossing *zero_crossing, const size_t number_crossings)
static void ActiveNodes (IntervalTree **list, ssize_t *number_nodes, IntervalTree *node)
MagickExport MagickBooleanType SegmentImage (Image *image, const ColorspaceType colorspace, const MagickBooleanType verbose, const double cluster_threshold, const double smooth_threshold)
Variables
static const int Blue = 2
static const int Green = 1
static const int Red = 0
static const int SafeMargin = 3
static const int TreeLength = 600
Macro Definition Documentation
DeltaTau
#define DeltaTau 0.5f
MaxDimension
#define MaxDimension 3
SegmentImageTag
#define SegmentImageTag "Segment/Image"
SegmentPower
#define SegmentPower (ratio) pow(ratio,(double) (1.0/(weighting_exponent-1.0)));
Tau
#define Tau 5.2f
ThrowClassifyException
#define ThrowClassifyException (severity, tag, label)
Value:
{\
  for (cluster=head; cluster != (Cluster *) NULL; cluster=next_cluster) \
  { \
    next_cluster=cluster->next; \
    cluster=(Cluster *) RelinquishMagickMemory(cluster); \
  } \
  if (squares != (MagickRealType *) NULL) \
    { \
      squares-=255; \
      free_squares=squares; \
      free_squares=(MagickRealType *) RelinquishMagickMemory(free_squares); \
    } \
  ThrowBinaryException(severity,tag,label); \
}
WeightingExponent
#define WeightingExponent 2.5
Typedef Documentation
Cluster
typedef struct _Cluster Cluster
ExtentPacket
typedef struct _ExtentPacket ExtentPacket
IntervalTree
typedef struct _IntervalTree IntervalTree
ZeroCrossing
typedef struct _ZeroCrossing ZeroCrossing
Function Documentation
ActiveNodes()
static void ActiveNodes (IntervalTree ** list, ssize_t * number_nodes, IntervalTree * node) static
References ActiveNodes(), _IntervalTree::child, _IntervalTree::mean_stability, _IntervalTree::sibling, and _IntervalTree::stability.
Referenced by ActiveNodes(), and OptimalTau().
Classify()
static MagickBooleanType Classify (Image * image, short ** extrema, const MagickRealType cluster_threshold, const MagickRealType weighting_exponent, const MagickBooleanType verbose) static
References AcquireAuthenticCacheView(), AcquireImageColormap(), AcquireQuantumMemory(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, _PixelPacket::blue, _Cluster::blue, Blue, _ExtentPacket::center, _Image::colormap, _Image::colors, _Image::columns, _Cluster::count, DefineRegion(), DestroyCacheView(), _Image::exception, _Image::filename, FormatLocaleFile(), GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), _MagickPixelPacket::green, _PixelPacket::green, _Cluster::green, Green, _Cluster::id, ImageError, _ExtentPacket::index, _ExtentPacket::left, magick_restrict, MagickFalse, MagickTrue, MaxDimension, _Cluster::next, _Image::progress_monitor, _MagickPixelPacket::red, _PixelPacket::red, _Cluster::red, Red, RelinquishMagickMemory(), ResourceLimitError, _ExtentPacket::right, _Image::rows, SafeMargin, SegmentImageTag, SegmentPower, SetImageProgress(), SetPixelIndex, SyncCacheViewAuthenticPixels(), SyncImage(), and ThrowClassifyException.
Referenced by SegmentImage().
ConsolidateCrossings()
static void ConsolidateCrossings (ZeroCrossing * zero_crossing, const size_t number_crossings) static
References _ZeroCrossing::crossings, MagickMax, and MagickMin.
Referenced by OptimalTau().
DefineRegion()
static ssize_t DefineRegion (const short * extrema, ExtentPacket * extents) static
References _ExtentPacket::center, _ExtentPacket::index, _ExtentPacket::left, MagickFalse, MagickTrue, and _ExtentPacket::right.
Referenced by Classify(), and GetImageDynamicThreshold().
DerivativeHistogram()
static void DerivativeHistogram (const MagickRealType * histogram, MagickRealType * derivative) static
Referenced by OptimalTau().
FreeNodes()
static void FreeNodes (IntervalTree * node) static
References _IntervalTree::child, FreeNodes(), RelinquishMagickMemory(), and _IntervalTree::sibling.
Referenced by FreeNodes(), InitializeIntervalTree(), and OptimalTau().
GetImageDynamicThreshold()
MagickExport MagickBooleanType GetImageDynamicThreshold (const Image * image, const double cluster_threshold, const double smooth_threshold, MagickPixelPacket * pixel, ExceptionInfo * exception)
References AcquireQuantumMemory(), _MagickPixelPacket::blue, _PixelPacket::blue, _Cluster::blue, Blue, _ExtentPacket::center, _Image::columns, _Cluster::count, _Image::debug, DefineRegion(), DeltaTau, _Image::filename, GetMagickModule, GetMagickPixelPacket(), GetVirtualPixels(), _MagickPixelPacket::green, _PixelPacket::green, _Cluster::green, Green, _Cluster::id, _ExtentPacket::index, InitializeHistogram(), _ExtentPacket::left, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, MaxDimension, _Cluster::next, OptimalTau(), _MagickPixelPacket::red, _PixelPacket::red, _Cluster::red, Red, RelinquishMagickMemory(), ResourceLimitError, _ExtentPacket::right, _Image::rows, SafeMargin, SegmentImageTag, SetImageProgress(), _Image::signature, Tau, ThrowMagickException(), and TraceEvent.
Referenced by ThresholdImageChannel().
InitializeHistogram()
static void InitializeHistogram (const Image * image, ssize_t ** histogram, ExceptionInfo * exception)
References Blue, _Image::columns, GetPixelBlue, GetPixelGreen, GetPixelRed, GetVirtualPixels(), Green, Red, and _Image::rows.
Referenced by GetImageDynamicThreshold(), and SegmentImage().
InitializeIntervalTree()
static IntervalTree * InitializeIntervalTree (const ZeroCrossing * zero_crossing, const size_t number_crossings) static
References AcquireCriticalMemory(), AcquireQuantumMemory(), _IntervalTree::child, FreeNodes(), InitializeList(), _IntervalTree::left, _IntervalTree::mean_stability, MeanStability(), RelinquishMagickMemory(), _IntervalTree::right, _IntervalTree::sibling, _IntervalTree::stability, Stability(), _IntervalTree::tau, _ZeroCrossing::tau, and TreeLength.
Referenced by OptimalTau().
InitializeList()
static void InitializeList (IntervalTree ** list, ssize_t * number_nodes, IntervalTree * node) static
References _IntervalTree::child, InitializeList(), and _IntervalTree::sibling.
Referenced by InitializeIntervalTree(), and InitializeList().
MeanStability()
static void MeanStability (IntervalTree * node) static
References _IntervalTree::child, _IntervalTree::mean_stability, MeanStability(), _IntervalTree::sibling, and _IntervalTree::stability.
Referenced by InitializeIntervalTree(), and MeanStability().
OptimalTau()
static MagickRealType OptimalTau (const ssize_t * histogram, const double max_tau, const double min_tau, const double delta_tau, const double smooth_threshold, short * extrema) static
References AcquireCriticalMemory(), AcquireQuantumMemory(), ActiveNodes(), _IntervalTree::child, ConsolidateCrossings(), _ZeroCrossing::crossings, DerivativeHistogram(), FreeNodes(), _ZeroCrossing::histogram, InitializeIntervalTree(), _IntervalTree::left, MagickFalse, MagickTrue, PerceptibleReciprocal(), RelinquishMagickMemory(), _IntervalTree::right, ScaleSpace(), _IntervalTree::tau, _ZeroCrossing::tau, TreeLength, and ZeroCrossHistogram().
Referenced by GetImageDynamicThreshold(), and SegmentImage().
ScaleSpace()
static void ScaleSpace (const ssize_t * histogram, const MagickRealType tau, MagickRealType * scale_histogram)
References AcquireQuantumMemory(), MagickAbsoluteValue, MagickEpsilon, MagickPI, RelinquishMagickMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by OptimalTau().
SegmentImage()
MagickExport MagickBooleanType SegmentImage (Image * image, const ColorspaceType colorspace, const MagickBooleanType verbose, const double cluster_threshold, const double smooth_threshold)
References AcquireQuantumMemory(), Blue, Classify(), _Image::colorspace, _Image::debug, DeltaTau, _Image::exception, _Image::filename, GetMagickModule, Green, InitializeHistogram(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MaxDimension, OptimalTau(), Red, RelinquishMagickMemory(), ResourceLimitError, _Image::signature, Tau, ThrowBinaryImageException, TraceEvent, TransformImageColorspace(), and WeightingExponent.
Referenced by PreviewImage().
Stability()
static void Stability (IntervalTree * node) static
References _IntervalTree::child, _IntervalTree::sibling, _IntervalTree::stability, Stability(), and _IntervalTree::tau.
Referenced by InitializeIntervalTree(), and Stability().
ZeroCrossHistogram()
static void ZeroCrossHistogram (MagickRealType * second_derivative, const MagickRealType smooth_threshold, short * crossings)
Referenced by OptimalTau().
Variable Documentation
Blue
const int Blue = 2 static
Referenced by Classify(), GetImageDynamicThreshold(), InitializeHistogram(), and SegmentImage().
Green
const int Green = 1 static
Referenced by Classify(), GetImageDynamicThreshold(), InitializeHistogram(), and SegmentImage().
Red
const int Red = 0 static
Referenced by Classify(), GetImageDynamicThreshold(), InitializeHistogram(), and SegmentImage().
SafeMargin
const int SafeMargin = 3 static
Referenced by Classify(), and GetImageDynamicThreshold().
TreeLength
const int TreeLength = 600 static
Referenced by InitializeIntervalTree(), and OptimalTau().