MagickCore: segment.h File Reference
segment.h File Reference
Functions
MagickExport MagickBooleanType GetImageDynamicThreshold (const Image *, const double, const double, MagickPixelPacket *, ExceptionInfo *)
MagickExport MagickBooleanType SegmentImage (Image *, const ColorspaceType, const MagickBooleanType, const double, const double)
Function Documentation
GetImageDynamicThreshold()
MagickExport MagickBooleanType GetImageDynamicThreshold (const Image * , const double , const double , MagickPixelPacket * , ExceptionInfo *)
SegmentImage()
MagickExport MagickBooleanType SegmentImage (Image * image, const ColorspaceType, const MagickBooleanType, const double cluster_threshold, const double smooth_threshold)
References AcquireQuantumMemory(), Blue, Classify(), _Image::colorspace, _Image::debug, DeltaTau, _Image::exception, _Image::filename, GetMagickModule, Green, InitializeHistogram(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MaxDimension, OptimalTau(), Red, RelinquishMagickMemory(), ResourceLimitError, _Image::signature, Tau, ThrowBinaryImageException, TraceEvent, TransformImageColorspace(), and WeightingExponent.
Referenced by PreviewImage().