MagickCore: semaphore.c File Reference
semaphore.c File Reference
#include "magick/studio.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/memory_.h"
#include "magick/memory-private.h"
#include "magick/mutex.h"
#include "magick/semaphore.h"
#include "magick/semaphore-private.h"
#include "magick/string_.h"
#include "magick/thread_.h"
#include "magick/thread-private.h"
#include "magick/utility-private.h"
Data Structures
struct SemaphoreInfo
Macros
#define AlignedExtent(size, alignment) (((size)+((alignment)-1)) & ~((alignment)-1))
Functions
MagickExport void ActivateSemaphoreInfo (SemaphoreInfo **semaphore_info)
static void * AcquireSemaphoreMemory (const size_t count, const size_t quantum)
static void * RelinquishSemaphoreMemory (void *memory)
MagickExport SemaphoreInfo * AllocateSemaphoreInfo (void)
MagickExport void LockSemaphoreInfo (SemaphoreInfo *semaphore_info)
MagickExport void DestroySemaphoreInfo (SemaphoreInfo **semaphore_info)
MagickExport MagickBooleanType SemaphoreComponentGenesis (void)
MagickExport void SemaphoreComponentTerminus (void)
MagickExport void UnlockSemaphoreInfo (SemaphoreInfo *semaphore_info)
Macro Definition Documentation
AlignedExtent
#define AlignedExtent (size, alignment) (((size)+((alignment)-1)) & ~((alignment)-1))
Function Documentation
AcquireSemaphoreMemory()
static void * AcquireSemaphoreMemory (const size_t count, const size_t quantum) static
References AlignedExtent, and CACHE_LINE_SIZE.
Referenced by AllocateSemaphoreInfo().
ActivateSemaphoreInfo()
MagickExport void ActivateSemaphoreInfo (SemaphoreInfo ** semaphore_info)
References AllocateSemaphoreInfo(), LockMagickMutex(), and UnlockMagickMutex().
Referenced by AcquireMagickMemory(), AcquireMagickResource(), AcquireUniqueFileResource(), AnnotateComponentTerminus(), CacheComponentTerminus(), ClearExceptionInfo(), CoderComponentTerminus(), ColorComponentTerminus(), ConfigureComponentTerminus(), DelegateComponentTerminus(), DestroyMagickMemory(), ExceptionComponentTerminus(), GetMagickResource(), GetMagickResourceLimit(), IsCoderTreeInstantiated(), IsColorCacheInstantiated(), IsConfigureCacheInstantiated(), IsDelegateCacheInstantiated(), IsLocaleTreeInstantiated(), IsLogCacheInstantiated(), IsMagicCacheInstantiated(), IsMagickTreeInstantiated(), IsMimeCacheInstantiated(), IsPolicyCacheInstantiated(), IsTypeTreeInstantiated(), ListMagickResourceInfo(), LocaleComponentTerminus(), LogComponentTerminus(), LogMagickEventList(), MagicComponentTerminus(), MagickComponentTerminus(), MimeComponentTerminus(), MonitorComponentGenesis(), MonitorComponentTerminus(), PolicyComponentTerminus(), RandomComponentTerminus(), RegistryComponentTerminus(), RelinquishMagickResource(), RelinquishUniqueFileResource(), RenderX11(), ResourceComponentGenesis(), ResourceComponentTerminus(), SetErrorHandler(), SetFatalErrorHandler(), SetImageProgress(), SetImageRegistry(), SetMagickResourceLimit(), SetWarningHandler(), and TypeComponentTerminus().
AllocateSemaphoreInfo()
MagickExport SemaphoreInfo * AllocateSemaphoreInfo (void)
References AcquireSemaphoreMemory(), GetMagickThreadId(), SemaphoreInfo::id, MagickCoreSignature, SemaphoreInfo::mutex, pthread_mutex_init, pthread_mutexattr_destroy, pthread_mutexattr_init, SemaphoreInfo::reference_count, ResourceLimitFatalError, SemaphoreInfo::signature, and ThrowFatalException.
Referenced by AcquireImage(), AcquireMatrixInfo(), AcquirePixelCache(), AcquireRandomInfo(), AcquireSemaphoreInfo(), ActivateSemaphoreInfo(), AnnotateComponentGenesis(), CacheComponentGenesis(), CloneImage(), CoderComponentGenesis(), ColorComponentGenesis(), ConfigureComponentGenesis(), DelegateComponentGenesis(), ExceptionComponentGenesis(), GetBlobInfo(), GetExceptionInfo(), GetImagePixelCache(), GetQuantumInfo(), InitializeExceptionInfo(), LoadDelegateCache(), LocaleComponentGenesis(), LogComponentGenesis(), MagicComponentGenesis(), MagickComponentGenesis(), MimeComponentGenesis(), NewHashmap(), NewLinkedList(), NewSplayTree(), PolicyComponentGenesis(), RandomComponentGenesis(), RegisterMagickInfo(), RegistryComponentGenesis(), and TypeComponentGenesis().
DestroySemaphoreInfo()
MagickExport void DestroySemaphoreInfo (SemaphoreInfo ** semaphore_info)
References LockMagickMutex(), MagickCoreSignature, pthread_mutex_destroy, RelinquishSemaphoreMemory(), and UnlockMagickMutex().
Referenced by AnnotateComponentTerminus(), CacheComponentTerminus(), ClearExceptionInfo(), CoderComponentTerminus(), ColorComponentTerminus(), ConfigureComponentTerminus(), DelegateComponentTerminus(), DestroyBlob(), DestroyDelegate(), DestroyHashmap(), DestroyImage(), DestroyLinkedList(), DestroyLogElement(), DestroyMagickMemory(), DestroyMagickNode(), DestroyMatrixInfo(), DestroyPixelCache(), DestroyPixelStream(), DestroyQuantumInfo(), DestroyRandomInfo(), DestroySplayTree(), ExceptionComponentTerminus(), GetImagePixelCache(), IncreaseHashmapCapacity(), LocaleComponentTerminus(), LogComponentTerminus(), MagicComponentTerminus(), MagickComponentTerminus(), MimeComponentTerminus(), MonitorComponentTerminus(), PolicyComponentTerminus(), RandomComponentTerminus(), RegistryComponentTerminus(), ResourceComponentTerminus(), and TypeComponentTerminus().
LockSemaphoreInfo()
MagickExport void LockSemaphoreInfo (SemaphoreInfo * semaphore_info)
References FormatLocaleFile(), GetMagickThreadId(), SemaphoreInfo::id, IsMagickThreadEqual(), MagickCoreSignature, MagickFalse, SemaphoreInfo::mutex, pthread_mutex_lock, SemaphoreInfo::reference_count, and SemaphoreInfo::signature.
Referenced by AcquireMagickMemory(), AcquireMagickResource(), AcquireUniqueFileResource(), AddValueToSplayTree(), AppendValueToLinkedList(), CatchException(), ClearExceptionInfo(), ClearLinkedList(), ClearMagickException(), CloneBlobInfo(), CloneSplayTree(), CloseMagickLog(), CoderComponentTerminus(), ColorComponentTerminus(), ConfigureComponentTerminus(), DelegateComponentTerminus(), DeleteNodeByValueFromSplayTree(), DeleteNodeFromSplayTree(), DestroyBlob(), DestroyHashmap(), DestroyImage(), DestroyLinkedList(), DestroyMagickMemory(), DestroyMatrixInfo(), DestroyPixelCache(), DestroyPixelStream(), DestroyRandomInfo(), DestroySplayTree(), DisassociateBlob(), ExceptionComponentTerminus(), GenerateEntropicChaos(), GetCoderInfoList(), GetCoderList(), GetColorCompliance(), GetColorInfoList(), GetColorList(), GetConfigureInfo(), GetConfigureInfoList(), GetConfigureList(), GetDelegateInfo(), GetDelegateInfoList(), GetDelegateList(), GetImageMagick(), GetImagePixelCache(), GetImageReferenceCount(), GetLastValueInLinkedList(), GetLocaleInfo_(), GetLocaleInfoList(), GetLocaleList(), GetLogInfo(), GetLogInfoList(), GetLogList(), GetMagicInfo(), GetMagicInfoList(), GetMagickInfo(), GetMagickInfoList(), GetMagickList(), GetMagickResource(), GetMagickResourceLimit(), GetMagicList(), GetMimeInfo(), GetMimeInfoList(), GetMimeList(), GetNextKeyInHashmap(), GetNextKeyInSplayTree(), GetNextValueInHashmap(), GetNextValueInLinkedList(), GetNextValueInSplayTree(), GetPolicyInfo(), GetPolicyInfoList(), GetPolicyList(), GetRootValueFromSplayTree(), GetTypeInfoByFamily(), GetTypeInfoList(), GetTypeList(), GetValueFromHashmap(), GetValueFromLinkedList(), GetValueFromSplayTree(), IncreaseHashmapCapacity(), InheritException(), InsertValueInLinkedList(), InsertValueInSortedLinkedList(), IsCoderTreeInstantiated(), IsColorCacheInstantiated(), IsConfigureCacheInstantiated(), IsDelegateCacheInstantiated(), IsLocaleTreeInstantiated(), IsLogCacheInstantiated(), IsMagicCacheInstantiated(), IsMagickTreeInstantiated(), IsMimeCacheInstantiated(), IsPolicyCacheInstantiated(), IsRightsAuthorized(), IsTypeTreeInstantiated(), LinkedListToArray(), ListMagickResourceInfo(), LocaleComponentTerminus(), LogComponentTerminus(), LogMagickEventList(), MagicComponentTerminus(), MagickComponentTerminus(), MimeComponentTerminus(), ModifyImage(), MonitorComponentTerminus(), PolicyComponentTerminus(), PutEntryInHashmap(), ReadImage(), ReadMatrixElements(), ReadPixelCacheIndexes(), ReadPixelCachePixels(), ReferenceBlob(), ReferenceImage(), ReferencePixelCache(), RegistryComponentTerminus(), RelinquishMagickMemory(), RelinquishMagickResource(), RelinquishUniqueFileResource(), RemoveElementByValueFromLinkedList(), RemoveElementFromLinkedList(), RemoveEntryFromHashmap(), RemoveLastElementFromLinkedList(), RemoveNodeByValueFromSplayTree(), RemoveNodeFromSplayTree(), RenderX11(), ResetHashmapIterator(), ResetLinkedListIterator(), ResetSplayTree(), ResetSplayTreeIterator(), ResizeMagickMemory(), ResourceComponentTerminus(), SetErrorHandler(), SetFatalErrorHandler(), SetImageProgress(), SetImageRegistry(), SetLogEventMask(), SetLogFormat(), SetLogMethod(), SetMagickResourceLimit(), SetMagickSecurityPolicy(), SetRandomKey(), SetWarningHandler(), ThrowException(), TypeComponentTerminus(), UnregisterMagickInfo(), WriteImage(), WriteMatrixElements(), WritePixelCacheIndexes(), and WritePixelCachePixels().
RelinquishSemaphoreMemory()
static void * RelinquishSemaphoreMemory (void * memory) static
Referenced by DestroySemaphoreInfo().
SemaphoreComponentGenesis()
MagickExport MagickBooleanType SemaphoreComponentGenesis (void)
References InitializeMagickMutex(), and MagickTrue.
Referenced by MagickCoreGenesis().
SemaphoreComponentTerminus()
MagickExport void SemaphoreComponentTerminus (void)
References DestroyMagickMutex().
Referenced by MagickCoreTerminus().
UnlockSemaphoreInfo()
MagickExport void UnlockSemaphoreInfo (SemaphoreInfo * semaphore_info)
References FormatLocaleFile(), SemaphoreInfo::id, IsMagickThreadEqual(), MagickCoreSignature, MagickFalse, SemaphoreInfo::mutex, pthread_mutex_unlock, SemaphoreInfo::reference_count, and SemaphoreInfo::signature.
Referenced by AcquireMagickMemory(), AcquireMagickResource(), AcquireUniqueFileResource(), AddValueToSplayTree(), AppendValueToLinkedList(), CatchException(), ClearExceptionInfo(), ClearLinkedList(), ClearMagickException(), CloneBlobInfo(), CloneSplayTree(), CloseMagickLog(), CoderComponentTerminus(), ColorComponentTerminus(), ConfigureComponentTerminus(), DelegateComponentTerminus(), DeleteNodeByValueFromSplayTree(), DeleteNodeFromSplayTree(), DestroyBlob(), DestroyHashmap(), DestroyImage(), DestroyLinkedList(), DestroyMagickMemory(), DestroyMatrixInfo(), DestroyPixelCache(), DestroyPixelStream(), DestroyRandomInfo(), DestroySplayTree(), DisassociateBlob(), ExceptionComponentTerminus(), GenerateEntropicChaos(), GetCoderInfoList(), GetCoderList(), GetColorCompliance(), GetColorInfoList(), GetColorList(), GetConfigureInfo(), GetConfigureInfoList(), GetConfigureList(), GetDelegateInfo(), GetDelegateInfoList(), GetDelegateList(), GetImageMagick(), GetImagePixelCache(), GetImageReferenceCount(), GetLastValueInLinkedList(), GetLocaleInfo_(), GetLocaleInfoList(), GetLocaleList(), GetLogInfo(), GetLogInfoList(), GetLogList(), GetMagicInfo(), GetMagicInfoList(), GetMagickInfo(), GetMagickInfoList(), GetMagickList(), GetMagickResource(), GetMagickResourceLimit(), GetMagicList(), GetMimeInfo(), GetMimeInfoList(), GetMimeList(), GetNextKeyInHashmap(), GetNextKeyInSplayTree(), GetNextValueInHashmap(), GetNextValueInLinkedList(), GetNextValueInSplayTree(), GetPolicyInfo(), GetPolicyInfoList(), GetPolicyList(), GetRootValueFromSplayTree(), GetTypeInfoByFamily(), GetTypeInfoList(), GetTypeList(), GetValueFromHashmap(), GetValueFromLinkedList(), GetValueFromSplayTree(), IncreaseHashmapCapacity(), InheritException(), InsertValueInLinkedList(), InsertValueInSortedLinkedList(), IsCoderTreeInstantiated(), IsColorCacheInstantiated(), IsConfigureCacheInstantiated(), IsDelegateCacheInstantiated(), IsLocaleTreeInstantiated(), IsLogCacheInstantiated(), IsMagicCacheInstantiated(), IsMagickTreeInstantiated(), IsMimeCacheInstantiated(), IsPolicyCacheInstantiated(), IsRightsAuthorized(), IsTypeTreeInstantiated(), LiberateSemaphoreInfo(), LinkedListToArray(), ListMagickResourceInfo(), LocaleComponentTerminus(), LogComponentTerminus(), LogMagickEventList(), MagicComponentTerminus(), MagickComponentTerminus(), MimeComponentTerminus(), ModifyImage(), MonitorComponentTerminus(), PolicyComponentTerminus(), PutEntryInHashmap(), ReadImage(), ReadMatrixElements(), ReadPixelCacheIndexes(), ReadPixelCachePixels(), ReferenceBlob(), ReferenceImage(), ReferencePixelCache(), RegistryComponentTerminus(), RelinquishMagickMemory(), RelinquishMagickResource(), RelinquishSemaphoreInfo(), RelinquishUniqueFileResource(), RemoveElementByValueFromLinkedList(), RemoveElementFromLinkedList(), RemoveEntryFromHashmap(), RemoveLastElementFromLinkedList(), RemoveNodeByValueFromSplayTree(), RemoveNodeFromSplayTree(), RenderX11(), ResetHashmapIterator(), ResetLinkedListIterator(), ResetSplayTree(), ResetSplayTreeIterator(), ResizeMagickMemory(), ResourceComponentTerminus(), SetErrorHandler(), SetFatalErrorHandler(), SetImageProgress(), SetImageRegistry(), SetLogEventMask(), SetLogFormat(), SetLogMethod(), SetMagickResourceLimit(), SetMagickSecurityPolicy(), SetRandomKey(), SetWarningHandler(), ThrowException(), TypeComponentTerminus(), UnregisterMagickInfo(), WriteImage(), WriteMatrixElements(), WritePixelCacheIndexes(), and WritePixelCachePixels().