MagickCore: shear.h File Reference
shear.h File Reference
Functions
MagickExport Image * DeskewImage (const Image *, const double, ExceptionInfo *)
MagickExport Image * IntegralRotateImage (const Image *, size_t, ExceptionInfo *)
MagickExport Image * ShearImage (const Image *, const double, const double, ExceptionInfo *)
MagickExport Image * ShearRotateImage (const Image *, const double, ExceptionInfo *)
Function Documentation
DeskewImage()
MagickExport Image * DeskewImage (const Image * , const double , ExceptionInfo *)
IntegralRotateImage()
MagickExport Image * IntegralRotateImage (const Image * , size_t , ExceptionInfo *)
ShearImage()
MagickExport Image * ShearImage (const Image * , const double , const double , ExceptionInfo *)
ShearRotateImage()
MagickExport Image * ShearRotateImage (const Image * image, const double degrees, ExceptionInfo * exception)
References _Image::background_color, _Image::border_color, BorderImage(), CastDoubleToLong(), CastDoubleToUnsigned(), _Image::columns, _Image::compose, CopyCompositeOp, CropToFitImage(), _Image::debug, DegreesToRadians(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetMagickModule, _RectangleInfo::height, InheritException(), IntegralRotateImage(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OpaqueAlphaChannel, _Image::page, ResourceLimitError, _Image::rows, SetImageAlphaChannel(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, ThrowImageException, TraceEvent, _RectangleInfo::width, _PointInfo::x, _RectangleInfo::x, XShearImage(), _PointInfo::y, _RectangleInfo::y, and YShearImage().