MagickCore: signature-private.h File Reference
signature-private.h File Reference
#include "magick/string_.h"
Macros
#define MagickCoreSignatureSize 64
Typedefs
typedef struct _SignatureInfo SignatureInfo
Functions
MagickExport MagickBooleanType SignatureImage (Image *)
MagickExport SignatureInfo * AcquireSignatureInfo (void)
MagickExport SignatureInfo * DestroySignatureInfo (SignatureInfo *)
MagickExport const StringInfo * GetSignatureDigest (const SignatureInfo *)
MagickExport unsigned int GetSignatureBlocksize (const SignatureInfo *)
MagickExport unsigned int GetSignatureDigestsize (const SignatureInfo *)
MagickExport void InitializeSignature (SignatureInfo *)
MagickExport void FinalizeSignature (SignatureInfo *)
MagickExport void SetSignatureDigest (SignatureInfo *, const StringInfo *)
MagickExport void UpdateSignature (SignatureInfo *, const StringInfo *)
Macro Definition Documentation
MagickCoreSignatureSize
#define MagickCoreSignatureSize 64
Typedef Documentation
SignatureInfo
typedef struct _SignatureInfo SignatureInfo
Function Documentation
AcquireSignatureInfo()
MagickExport SignatureInfo * AcquireSignatureInfo (void)
Referenced by AcquireRandomInfo(), HashStringInfoType(), and HashStringType().
DestroySignatureInfo()
MagickExport SignatureInfo * DestroySignatureInfo (SignatureInfo * signature_info)
References _SignatureInfo::accumulator, DestroyStringInfo(), _SignatureInfo::digest, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _SignatureInfo::message, RelinquishMagickMemory(), _SignatureInfo::signature, and TraceEvent.
Referenced by AcquireRandomInfo(), DestroyRandomInfo(), HashStringInfoType(), HashStringType(), and SignatureImage().
FinalizeSignature()
MagickExport void FinalizeSignature (SignatureInfo *)
Referenced by AcquireRandomInfo(), HashStringInfoType(), HashStringType(), and SetRandomKey().
GetSignatureBlocksize()
MagickExport unsigned int GetSignatureBlocksize (const SignatureInfo *)
GetSignatureDigest()
MagickExport const StringInfo * GetSignatureDigest (const SignatureInfo * signature_info)
References _SignatureInfo::digest, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _SignatureInfo::signature, and TraceEvent.
Referenced by AcquireRandomInfo(), HashStringInfoType(), HashStringType(), SetRandomKey(), and SignatureImage().
GetSignatureDigestsize()
MagickExport unsigned int GetSignatureDigestsize (const SignatureInfo * signature_info)
References _SignatureInfo::digestsize, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _SignatureInfo::signature, and TraceEvent.
Referenced by AcquireRandomInfo(), and SetRandomKey().
InitializeSignature()
MagickExport void InitializeSignature (SignatureInfo *)
Referenced by AcquireRandomInfo(), and SetRandomKey().
SetSignatureDigest()
MagickExport void SetSignatureDigest (SignatureInfo * , const StringInfo *)
SignatureImage()
MagickExport MagickBooleanType SignatureImage (Image * image)
References AcquireQuantumInfo(), AcquireSignatureInfo(), AcquireStringInfo(), AcquireVirtualCacheView(), CMYKAQuantum, CMYKColorspace, CMYKQuantum, _Image::colorspace, _Image::columns, _Image::debug, DeleteImageProperty(), DestroyCacheView(), DestroyQuantumInfo(), DestroySignatureInfo(), DestroyString(), DestroyStringInfo(), _Image::exception, ExportQuantumPixels(), _QuantumInfo::extent, _Image::filename, FinalizeSignature(), GetCacheViewVirtualPixels(), GetMagickModule, GetQuantumPixels(), GetSignatureDigest(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, ResourceLimitError, RGBAQuantum, RGBQuantum, _Image::rows, SetImageProperty(), SetStringInfoDatum(), SetStringInfoLength(), _Image::signature, StringInfoToHexString(), ThrowBinaryException, TraceEvent, and UpdateSignature().
Referenced by GetMagickPropertyLetter(), and IdentifyImage().
UpdateSignature()
MagickExport void UpdateSignature (SignatureInfo * signature_info, const StringInfo * message)
References _SignatureInfo::extent, GetStringInfoDatum(), GetStringInfoLength(), _SignatureInfo::high_order, _SignatureInfo::low_order, MagickCoreSignature, _SignatureInfo::message, SetStringInfoDatum(), _SignatureInfo::signature, TransformSignature(), and Trunc32.
Referenced by AcquireRandomInfo(), HashStringInfoType(), HashStringType(), SetRandomKey(), and SignatureImage().