MagickCore: signature.c File Reference
signature.c File Reference
#include "magick/studio.h"
#include "magick/cache.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/property.h"
#include "magick/image.h"
#include "magick/memory_.h"
#include "magick/quantum.h"
#include "magick/quantum-private.h"
#include "magick/signature.h"
#include "magick/signature-private.h"
#include "magick/string_.h"
#include "magick/timer-private.h"
Data Structures
struct _SignatureInfo
Macros
#define SignatureBlocksize 64
#define SignatureDigestsize 32
#define Ch(x, y, z) (((x) & (y)) ^ (~(x) & (z)))
#define Maj(x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
#define RotateRight(x, n) (Trunc32(((x) >> n) | ((x) << (32-n))))
#define Sigma0(x) (RotateRight(x,7) ^ RotateRight(x,18) ^ Trunc32((x) >> 3))
#define Sigma1(x) (RotateRight(x,17) ^ RotateRight(x,19) ^ Trunc32((x) >> 10))
#define Suma0(x) (RotateRight(x,2) ^ RotateRight(x,13) ^ RotateRight(x,22))
#define Suma1(x) (RotateRight(x,6) ^ RotateRight(x,11) ^ RotateRight(x,25))
#define Trunc32(x) ((unsigned int) ((x) & 0xffffffffU))
Functions
static void TransformSignature (SignatureInfo *)
MagickExport SignatureInfo * AcquireSignatureInfo (void)
MagickExport SignatureInfo * DestroySignatureInfo (SignatureInfo *signature_info)
MagickExport void FinalizeSignature (SignatureInfo *signature_info)
MagickExport unsigned int GetSignatureBlocksize (const SignatureInfo *signature_info)
MagickExport const StringInfo * GetSignatureDigest (const SignatureInfo *signature_info)
MagickExport unsigned int GetSignatureDigestsize (const SignatureInfo *signature_info)
MagickExport void InitializeSignature (SignatureInfo *signature_info)
MagickExport void SetSignatureDigest (SignatureInfo *signature_info, const StringInfo *digest)
MagickExport MagickBooleanType SignatureImage (Image *image)
MagickExport void UpdateSignature (SignatureInfo *signature_info, const StringInfo *message)
Macro Definition Documentation
Ch
#define Ch (x, y, z) (((x) & (y)) ^ (~(x) & (z)))
Maj
#define Maj (x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
RotateRight
#define RotateRight (x, n) (Trunc32(((x) >> n) | ((x) << (32-n))))
Sigma0
#define Sigma0 (x) (RotateRight(x,7) ^ RotateRight(x,18) ^ Trunc32((x) >> 3))
Sigma1
#define Sigma1 (x) (RotateRight(x,17) ^ RotateRight(x,19) ^ Trunc32((x) >> 10))
SignatureBlocksize
#define SignatureBlocksize 64
SignatureDigestsize
#define SignatureDigestsize 32
Suma0
#define Suma0 (x) (RotateRight(x,2) ^ RotateRight(x,13) ^ RotateRight(x,22))
Suma1
#define Suma1 (x) (RotateRight(x,6) ^ RotateRight(x,11) ^ RotateRight(x,25))
Trunc32
#define Trunc32 (x) ((unsigned int) ((x) & 0xffffffffU))
Function Documentation
AcquireSignatureInfo()
MagickExport SignatureInfo * AcquireSignatureInfo (void)
References _SignatureInfo::accumulator, AcquireMagickMemory(), AcquireQuantumMemory(), AcquireStringInfo(), _SignatureInfo::blocksize, _SignatureInfo::digest, _SignatureInfo::digestsize, InitializeSignature(), _SignatureInfo::lsb_first, MagickCoreSignature, MagickFalse, MagickTrue, _SignatureInfo::message, ResourceLimitFatalError, _SignatureInfo::signature, SignatureBlocksize, SignatureDigestsize, ThrowFatalException, and _SignatureInfo::timestamp.
Referenced by SignatureImage().
DestroySignatureInfo()
MagickExport SignatureInfo * DestroySignatureInfo (SignatureInfo * signature_info)
References _SignatureInfo::accumulator, DestroyStringInfo(), _SignatureInfo::digest, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _SignatureInfo::message, RelinquishMagickMemory(), _SignatureInfo::signature, and TraceEvent.
Referenced by AcquireRandomInfo(), DestroyRandomInfo(), HashStringInfoType(), HashStringType(), and SignatureImage().
FinalizeSignature()
MagickExport void FinalizeSignature (SignatureInfo * signature_info)
References _SignatureInfo::accumulator, _SignatureInfo::digest, GetMagickModule, GetStringInfoDatum(), GetStringInfoLength(), _SignatureInfo::high_order, LogMagickEvent(), _SignatureInfo::low_order, MagickCoreSignature, _SignatureInfo::message, _SignatureInfo::signature, SignatureDigestsize, TraceEvent, and TransformSignature().
Referenced by SignatureImage().
GetSignatureBlocksize()
MagickExport unsigned int GetSignatureBlocksize (const SignatureInfo * signature_info)
References _SignatureInfo::blocksize, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _SignatureInfo::signature, and TraceEvent.
GetSignatureDigest()
MagickExport const StringInfo * GetSignatureDigest (const SignatureInfo * signature_info)
References _SignatureInfo::digest, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _SignatureInfo::signature, and TraceEvent.
Referenced by AcquireRandomInfo(), HashStringInfoType(), HashStringType(), SetRandomKey(), and SignatureImage().
GetSignatureDigestsize()
MagickExport unsigned int GetSignatureDigestsize (const SignatureInfo * signature_info)
References _SignatureInfo::digestsize, GetMagickModule, LogMagickEvent(), MagickCoreSignature, _SignatureInfo::signature, and TraceEvent.
Referenced by AcquireRandomInfo(), and SetRandomKey().
InitializeSignature()
MagickExport void InitializeSignature (SignatureInfo * signature_info)
References _SignatureInfo::accumulator, _SignatureInfo::extent, GetMagickModule, _SignatureInfo::high_order, LogMagickEvent(), _SignatureInfo::low_order, MagickCoreSignature, _SignatureInfo::signature, and TraceEvent.
Referenced by AcquireSignatureInfo().
SetSignatureDigest()
MagickExport void SetSignatureDigest (SignatureInfo * signature_info, const StringInfo * digest)
References _SignatureInfo::digest, MagickCoreSignature, SetStringInfo(), and _SignatureInfo::signature.
SignatureImage()
MagickExport MagickBooleanType SignatureImage (Image * image)
References AcquireQuantumInfo(), AcquireSignatureInfo(), AcquireStringInfo(), AcquireVirtualCacheView(), CMYKAQuantum, CMYKColorspace, CMYKQuantum, _Image::colorspace, _Image::columns, _Image::debug, DeleteImageProperty(), DestroyCacheView(), DestroyQuantumInfo(), DestroySignatureInfo(), DestroyString(), DestroyStringInfo(), _Image::exception, ExportQuantumPixels(), _QuantumInfo::extent, _Image::filename, FinalizeSignature(), GetCacheViewVirtualPixels(), GetMagickModule, GetQuantumPixels(), GetSignatureDigest(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, ResourceLimitError, RGBAQuantum, RGBQuantum, _Image::rows, SetImageProperty(), SetStringInfoDatum(), SetStringInfoLength(), _Image::signature, StringInfoToHexString(), ThrowBinaryException, TraceEvent, and UpdateSignature().
Referenced by GetMagickPropertyLetter(), and IdentifyImage().
TransformSignature()
static void TransformSignature (SignatureInfo * signature_info) static
References _SignatureInfo::accumulator, Ch, DisableMSCWarning, GetStringInfoDatum(), _SignatureInfo::lsb_first, MagickFalse, Maj, _SignatureInfo::message, ResetMagickMemory(), RestoreMSCWarning, Sigma0, Sigma1, Suma0, Suma1, and Trunc32.
Referenced by FinalizeSignature(), and UpdateSignature().
UpdateSignature()
MagickExport void UpdateSignature (SignatureInfo * signature_info, const StringInfo * message)
References _SignatureInfo::extent, GetStringInfoDatum(), GetStringInfoLength(), _SignatureInfo::high_order, _SignatureInfo::low_order, MagickCoreSignature, _SignatureInfo::message, SetStringInfoDatum(), _SignatureInfo::signature, TransformSignature(), and Trunc32.
Referenced by AcquireRandomInfo(), HashStringInfoType(), HashStringType(), SetRandomKey(), and SignatureImage().