MagickCore: splay-tree.h File Reference
splay-tree.h File Reference
Typedefs
typedef struct _SplayTreeInfo SplayTreeInfo
Functions
MagickExport MagickBooleanType AddValueToSplayTree (SplayTreeInfo *, const void *, const void *)
MagickExport MagickBooleanType DeleteNodeByValueFromSplayTree (SplayTreeInfo *, const void *)
MagickExport MagickBooleanType DeleteNodeFromSplayTree (SplayTreeInfo *, const void *)
MagickExport const void * GetNextKeyInSplayTree (SplayTreeInfo *)
MagickExport const void * GetNextValueInSplayTree (SplayTreeInfo *)
MagickExport const void * GetRootValueFromSplayTree (SplayTreeInfo *)
MagickExport const void * GetValueFromSplayTree (SplayTreeInfo *, const void *)
MagickExport int CompareSplayTreeString (const void *, const void *)
MagickExport int CompareSplayTreeStringInfo (const void *, const void *)
MagickExport SplayTreeInfo * CloneSplayTree (SplayTreeInfo *, void *(*)(void *), void *(*)(void *))
MagickExport SplayTreeInfo * DestroySplayTree (SplayTreeInfo *)
MagickExport SplayTreeInfo * NewSplayTree (int(*)(const void *, const void *), void *(*)(void *), void *(*)(void *))
MagickExport size_t GetNumberOfNodesInSplayTree (const SplayTreeInfo *)
MagickExport void * RemoveNodeByValueFromSplayTree (SplayTreeInfo *, const void *)
MagickExport void * RemoveNodeFromSplayTree (SplayTreeInfo *, const void *)
MagickExport void ResetSplayTree (SplayTreeInfo *)
MagickExport void ResetSplayTreeIterator (SplayTreeInfo *)
Typedef Documentation
SplayTreeInfo
typedef struct _SplayTreeInfo SplayTreeInfo
Function Documentation
AddValueToSplayTree()
MagickExport MagickBooleanType AddValueToSplayTree (SplayTreeInfo * , const void * , const void *)
CloneSplayTree()
MagickExport SplayTreeInfo * CloneSplayTree (SplayTreeInfo * , void * *)(void *, void * *)(void *)
CompareSplayTreeString()
MagickExport int CompareSplayTreeString (const void * , const void *)
CompareSplayTreeStringInfo()
MagickExport int CompareSplayTreeStringInfo (const void * target, const void * source)
References CompareStringInfo().
DeleteNodeByValueFromSplayTree()
MagickExport MagickBooleanType DeleteNodeByValueFromSplayTree (SplayTreeInfo * , const void *)
DeleteNodeFromSplayTree()
MagickExport MagickBooleanType DeleteNodeFromSplayTree (SplayTreeInfo * splay_tree, const void * key)
References _SplayTreeInfo::compare, _SplayTreeInfo::debug, GetMagickModule, _NodeInfo::key, _SplayTreeInfo::key, _NodeInfo::left, LockSemaphoreInfo(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _SplayTreeInfo::nodes, _SplayTreeInfo::relinquish_key, _SplayTreeInfo::relinquish_value, RelinquishMagickMemory(), _NodeInfo::right, _SplayTreeInfo::root, _SplayTreeInfo::semaphore, _SplayTreeInfo::signature, SplaySplayTree(), TraceEvent, UnlockSemaphoreInfo(), and _NodeInfo::value.
Referenced by DeleteImageArtifact(), DeleteImageOption(), DeleteImageProfile(), DeleteImageProperty(), DeleteImageRegistry(), DestroyDistributeCache(), and RelinquishUniqueFileResource().
DestroySplayTree()
MagickExport SplayTreeInfo * DestroySplayTree (SplayTreeInfo *)
GetNextKeyInSplayTree()
MagickExport const void * GetNextKeyInSplayTree (SplayTreeInfo *)
GetNextValueInSplayTree()
MagickExport const void * GetNextValueInSplayTree (SplayTreeInfo *)
GetNumberOfNodesInSplayTree()
MagickExport size_t GetNumberOfNodesInSplayTree (const SplayTreeInfo * splay_tree)
References _SplayTreeInfo::debug, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _SplayTreeInfo::nodes, _SplayTreeInfo::signature, and TraceEvent.
Referenced by AcquireLocaleSplayTree(), AcquireTypeCache(), GetCoderInfoList(), GetCoderList(), GetLocaleInfoList(), GetLocaleList(), GetMagickInfoList(), GetMagickList(), GetTypeInfoList(), GetTypeList(), and UnregisterMagickInfo().
GetRootValueFromSplayTree()
MagickExport const void * GetRootValueFromSplayTree (SplayTreeInfo *)
GetValueFromSplayTree()
MagickExport const void * GetValueFromSplayTree (SplayTreeInfo * splay_tree, const void * key)
References _SplayTreeInfo::compare, _SplayTreeInfo::debug, GetMagickModule, _NodeInfo::key, LockSemaphoreInfo(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _SplayTreeInfo::root, _SplayTreeInfo::semaphore, _SplayTreeInfo::signature, SplaySplayTree(), TraceEvent, UnlockSemaphoreInfo(), and _NodeInfo::value.
Referenced by FxGetSymbol(), GetCoderInfo(), GetEXIFProperty(), GetFxSymbolValue(), GetImageArtifact(), GetImageAttribute(), GetImageOption(), GetImageProfile(), GetImageProperty(), GetImageRegistry(), GetLocaleInfo_(), GetMagickInfo(), GetTypeInfo(), ReadDistributeCacheIndexes(), ReadDistributeCachePixels(), RenderMVGContent(), SetFxSymbolValue(), SyncExifProfile(), WriteDistributeCacheIndexes(), WriteDistributeCachePixels(), and WriteTo8BimProfile().
NewSplayTree()
MagickExport SplayTreeInfo * NewSplayTree (int(*)(const void *, const void *) , void * *)(void *, void * *)(void *)
RemoveNodeByValueFromSplayTree()
MagickExport void * RemoveNodeByValueFromSplayTree (SplayTreeInfo * , const void *)
RemoveNodeFromSplayTree()
MagickExport void * RemoveNodeFromSplayTree (SplayTreeInfo * , const void *)
ResetSplayTree()
MagickExport void ResetSplayTree (SplayTreeInfo *)
ResetSplayTreeIterator()
MagickExport void ResetSplayTreeIterator (SplayTreeInfo * splay_tree)
References _SplayTreeInfo::debug, GetFirstSplayTreeNode(), GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _SplayTreeInfo::next, _SplayTreeInfo::semaphore, _SplayTreeInfo::signature, TraceEvent, and UnlockSemaphoreInfo().
Referenced by AsynchronousResourceComponentTerminus(), GetCoderInfoList(), GetCoderList(), GetImageArtifact(), GetImageMagick(), GetImageProperty(), GetLocaleInfo_(), GetLocaleInfoList(), GetMagickInfoList(), GetMagickList(), GetTypeInfoByFamily(), GetTypeInfoList(), GetTypeList(), ResetImageArtifactIterator(), ResetImageOptionIterator(), ResetImageProfileIterator(), ResetImagePropertyIterator(), ResetImageRegistryIterator(), and UnregisterMagickInfo().