MagickCore: statistic.c File Reference
statistic.c File Reference
#include "magick/studio.h"
#include "magick/accelerate-private.h"
#include "magick/animate.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/cache.h"
#include "magick/cache-private.h"
#include "magick/cache-view.h"
#include "magick/client.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colorspace.h"
#include "magick/colorspace-private.h"
#include "magick/composite.h"
#include "magick/composite-private.h"
#include "magick/compress.h"
#include "magick/constitute.h"
#include "magick/deprecate.h"
#include "magick/display.h"
#include "magick/draw.h"
#include "magick/enhance.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/list.h"
#include "magick/image-private.h"
#include "magick/magic.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/module.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/option.h"
#include "magick/paint.h"
#include "magick/pixel-private.h"
#include "magick/profile.h"
#include "magick/property.h"
#include "magick/quantize.h"
#include "magick/random_.h"
#include "magick/random-private.h"
#include "magick/resource_.h"
#include "magick/segment.h"
#include "magick/semaphore.h"
#include "magick/signature-private.h"
#include "magick/statistic.h"
#include "magick/string_.h"
#include "magick/thread-private.h"
#include "magick/timer.h"
#include "magick/utility.h"
#include "magick/version.h"
Data Structures
struct _ListNode
struct _SkipList
struct _PixelList
Macros
#define EvaluateImageTag "Evaluate/Image"
#define FunctionImageTag "Function/Image "
#define MaxNumberImageMoments 8
#define Log10Epsilon (1.0e-11)
#define PolynomialImageTag "Polynomial/Image"
#define ListChannels 5
#define StatisticImageTag "Statistic/Image"
Typedefs
typedef struct _ListNode ListNode
typedef struct _SkipList SkipList
typedef struct _PixelList PixelList
Functions
static MagickPixelPacket ** DestroyPixelThreadSet (const Image *images, MagickPixelPacket **pixels)
static MagickPixelPacket ** AcquirePixelThreadSet (const Image *images)
static double EvaluateMax (const double x, const double y)
static int IntensityCompare (const void *x, const void *y)
static MagickRealType ApplyEvaluateOperator (RandomInfo *random_info, const Quantum pixel, const MagickEvaluateOperator op, const MagickRealType value)
static Image * AcquireImageCanvas (const Image *images, ExceptionInfo *exception)
MagickExport MagickBooleanType EvaluateImage (Image *image, const MagickEvaluateOperator op, const double value, ExceptionInfo *exception)
MagickExport Image * EvaluateImages (const Image *images, const MagickEvaluateOperator op, ExceptionInfo *exception)
MagickExport MagickBooleanType EvaluateImageChannel (Image *image, const ChannelType channel, const MagickEvaluateOperator op, const double value, ExceptionInfo *exception)
static Quantum ApplyFunction (Quantum pixel, const MagickFunction function, const size_t number_parameters, const double *parameters, ExceptionInfo *exception)
MagickExport MagickBooleanType FunctionImage (Image *image, const MagickFunction function, const size_t number_parameters, const double *parameters, ExceptionInfo *exception)
MagickExport MagickBooleanType FunctionImageChannel (Image *image, const ChannelType channel, const MagickFunction function, const size_t number_parameters, const double *parameters, ExceptionInfo *exception)
MagickExport MagickBooleanType GetImageEntropy (const Image *image, double *entropy, ExceptionInfo *exception)
MagickExport MagickBooleanType GetImageChannelEntropy (const Image *image, const ChannelType channel, double *entropy, ExceptionInfo *exception)
MagickExport MagickBooleanType GetImageExtrema (const Image *image, size_t *minima, size_t *maxima, ExceptionInfo *exception)
MagickExport MagickBooleanType GetImageChannelExtrema (const Image *image, const ChannelType channel, size_t *minima, size_t *maxima, ExceptionInfo *exception)
MagickExport MagickBooleanType GetImageKurtosis (const Image *image, double *kurtosis, double *skewness, ExceptionInfo *exception)
MagickExport MagickBooleanType GetImageChannelKurtosis (const Image *image, const ChannelType channel, double *kurtosis, double *skewness, ExceptionInfo *exception)
MagickExport MagickBooleanType GetImageMean (const Image *image, double *mean, double *standard_deviation, ExceptionInfo *exception)
MagickExport MagickBooleanType GetImageChannelMean (const Image *image, const ChannelType channel, double *mean, double *standard_deviation, ExceptionInfo *exception)
MagickExport ChannelMoments * GetImageChannelMoments (const Image *image, ExceptionInfo *exception)
static double MagickLog10 (const double x)
MagickExport ChannelPerceptualHash * GetImageChannelPerceptualHash (const Image *image, ExceptionInfo *exception)
MagickExport MagickBooleanType GetImageRange (const Image *image, double *minima, double *maxima, ExceptionInfo *exception)
MagickExport MagickBooleanType GetImageChannelRange (const Image *image, const ChannelType channel, double *minima, double *maxima, ExceptionInfo *exception)
MagickExport ChannelStatistics * GetImageChannelStatistics (const Image *image, ExceptionInfo *exception)
MagickExport Image * PolynomialImage (const Image *images, const size_t number_terms, const double *terms, ExceptionInfo *exception)
MagickExport Image * PolynomialImageChannel (const Image *images, const ChannelType channel, const size_t number_terms, const double *terms, ExceptionInfo *exception)
static PixelList * DestroyPixelList (PixelList *pixel_list)
static PixelList ** DestroyPixelListThreadSet (PixelList **pixel_list)
static PixelList * AcquirePixelList (const size_t width, const size_t height)
static PixelList ** AcquirePixelListThreadSet (const size_t width, const size_t height)
static void AddNodePixelList (PixelList *pixel_list, const ssize_t channel, const size_t color)
static void GetMaximumPixelList (PixelList *pixel_list, MagickPixelPacket *pixel)
static void GetMeanPixelList (PixelList *pixel_list, MagickPixelPacket *pixel)
static void GetMedianPixelList (PixelList *pixel_list, MagickPixelPacket *pixel)
static void GetMinimumPixelList (PixelList *pixel_list, MagickPixelPacket *pixel)
static void GetModePixelList (PixelList *pixel_list, MagickPixelPacket *pixel)
static void GetNonpeakPixelList (PixelList *pixel_list, MagickPixelPacket *pixel)
static void GetRootMeanSquarePixelList (PixelList *pixel_list, MagickPixelPacket *pixel)
static void GetStandardDeviationPixelList (PixelList *pixel_list, MagickPixelPacket *pixel)
static void InsertPixelList (const Image *image, const PixelPacket *pixel, const IndexPacket *indexes, PixelList *pixel_list)
static void ResetPixelList (PixelList *pixel_list)
MagickExport Image * StatisticImage (const Image *image, const StatisticType type, const size_t width, const size_t height, ExceptionInfo *exception)
MagickExport Image * StatisticImageChannel (const Image *image, const ChannelType channel, const StatisticType type, const size_t width, const size_t height, ExceptionInfo *exception)
Macro Definition Documentation
EvaluateImageTag
#define EvaluateImageTag "Evaluate/Image"
FunctionImageTag
#define FunctionImageTag "Function/Image "
ListChannels
#define ListChannels 5
Log10Epsilon
#define Log10Epsilon (1.0e-11)
MaxNumberImageMoments
#define MaxNumberImageMoments 8
PolynomialImageTag
#define PolynomialImageTag "Polynomial/Image"
StatisticImageTag
#define StatisticImageTag "Statistic/Image"
Typedef Documentation
ListNode
typedef struct _ListNode ListNode
PixelList
typedef struct _PixelList PixelList
SkipList
typedef struct _SkipList SkipList
Function Documentation
AcquireImageCanvas()
static Image * AcquireImageCanvas (const Image * images, ExceptionInfo * exception) static
References CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, MagickFalse, MagickTrue, _Image::matte, _Image::next, and _Image::rows.
Referenced by EvaluateImages(), and PolynomialImageChannel().
AcquirePixelList()
static PixelList * AcquirePixelList (const size_t width, const size_t height) static
References AcquireAlignedMemory(), AcquireMagickMemory(), DestroyPixelList(), _PixelList::length, ListChannels, _PixelList::lists, MagickCoreSignature, _SkipList::nodes, and _PixelList::signature.
Referenced by AcquirePixelListThreadSet().
AcquirePixelListThreadSet()
static PixelList ** AcquirePixelListThreadSet (const size_t width, const size_t height) static
References AcquirePixelList(), AcquireQuantumMemory(), DestroyPixelListThreadSet(), GetMagickResourceLimit(), and ThreadResource.
Referenced by StatisticImageChannel().
AcquirePixelThreadSet()
static MagickPixelPacket ** AcquirePixelThreadSet (const Image * images) static
References AcquireQuantumMemory(), _Image::columns, DestroyPixelThreadSet(), GetImageListLength(), GetMagickPixelPacket(), GetMagickResourceLimit(), MagickMax, _Image::next, and ThreadResource.
Referenced by EvaluateImages(), and PolynomialImageChannel().
AddNodePixelList()
static void AddNodePixelList (PixelList * pixel_list, const ssize_t channel, const size_t color) static
References _ListNode::count, _SkipList::level, _PixelList::lists, _ListNode::next, _SkipList::nodes, _PixelList::seed, _ListNode::signature, and _PixelList::signature.
Referenced by InsertPixelList().
ApplyEvaluateOperator()
static MagickRealType ApplyEvaluateOperator (RandomInfo * random_info, const Quantum pixel, const MagickEvaluateOperator op, const MagickRealType value) static
References AbsEvaluateOperator, AddEvaluateOperator, AddModulusEvaluateOperator, AndEvaluateOperator, CosineEvaluateOperator, DivideEvaluateOperator, EvaluateMax(), ExponentialEvaluateOperator, GaussianNoise, GaussianNoiseEvaluateOperator, GenerateDifferentialNoise(), ImpulseNoise, ImpulseNoiseEvaluateOperator, InverseLogEvaluateOperator, LaplacianNoise, LaplacianNoiseEvaluateOperator, LeftShiftEvaluateOperator, LogEvaluateOperator, MagickEpsilon, MagickMin, MagickPI, MaxEvaluateOperator, MeanEvaluateOperator, MedianEvaluateOperator, MinEvaluateOperator, MultiplicativeGaussianNoise, MultiplicativeNoiseEvaluateOperator, MultiplyEvaluateOperator, OrEvaluateOperator, PerceptibleReciprocal(), PoissonNoise, PoissonNoiseEvaluateOperator, PowEvaluateOperator, QuantumRange, QuantumScale, random_info, RightShiftEvaluateOperator, RootMeanSquareEvaluateOperator, SetEvaluateOperator, SineEvaluateOperator, SubtractEvaluateOperator, SumEvaluateOperator, ThresholdBlackEvaluateOperator, ThresholdEvaluateOperator, ThresholdWhiteEvaluateOperator, UndefinedEvaluateOperator, UniformNoise, UniformNoiseEvaluateOperator, and XorEvaluateOperator.
Referenced by EvaluateImageChannel(), and EvaluateImages().
ApplyFunction()
static Quantum ApplyFunction (Quantum pixel, const MagickFunction function, const size_t number_parameters, const double * parameters, ExceptionInfo * exception) static
References ArcsinFunction, ArctanFunction, ClampToQuantum(), MagickPI, PolynomialFunction, QuantumRange, QuantumScale, SinusoidFunction, and UndefinedFunction.
Referenced by FunctionImageChannel().
DestroyPixelList()
static PixelList * DestroyPixelList (PixelList * pixel_list) static
References ListChannels, _PixelList::lists, _SkipList::nodes, RelinquishAlignedMemory(), and RelinquishMagickMemory().
Referenced by AcquirePixelList(), and DestroyPixelListThreadSet().
DestroyPixelListThreadSet()
static PixelList ** DestroyPixelListThreadSet (PixelList ** pixel_list) static
References DestroyPixelList(), GetMagickResourceLimit(), RelinquishMagickMemory(), and ThreadResource.
Referenced by AcquirePixelListThreadSet(), and StatisticImageChannel().
DestroyPixelThreadSet()
static MagickPixelPacket ** DestroyPixelThreadSet (const Image * images, MagickPixelPacket ** pixels) static
References GetImageListLength(), GetMagickResourceLimit(), MagickMax, RelinquishMagickMemory(), and ThreadResource.
Referenced by AcquirePixelThreadSet(), EvaluateImages(), and PolynomialImageChannel().
EvaluateImage()
MagickExport MagickBooleanType EvaluateImage (Image * image, const MagickEvaluateOperator op, const double value, ExceptionInfo * exception)
References CompositeChannels, and EvaluateImageChannel().
EvaluateImageChannel()
MagickExport MagickBooleanType EvaluateImageChannel (Image * image, const ChannelType channel, const MagickEvaluateOperator op, const double value, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireRandomInfoThreadSet(), ApplyEvaluateOperator(), BlueChannel, ClampToQuantum(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyRandomInfoThreadSet(), DirectClass, EvaluateImageTag, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetOpenMPThreadId(), GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, GetRandomSecretKey(), GreenChannel, IndexChannel, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, MeanEvaluateOperator, OpacityChannel, _Image::progress_monitor, random_info, RedChannel, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by EvaluateImage().
EvaluateImages()
MagickExport Image * EvaluateImages (const Image * images, const MagickEvaluateOperator op, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireImageCanvas(), AcquirePixelThreadSet(), AcquireRandomInfoThreadSet(), AcquireVirtualCacheView(), AddEvaluateOperator, ApplyEvaluateOperator(), _MagickPixelPacket::blue, ClampToQuantum(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DestroyPixelThreadSet(), DestroyRandomInfoThreadSet(), DirectClass, EvaluateImageTag, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetImageListLength(), GetMagickModule, GetMagickPixelPacket(), GetNextImageInList(), GetOpenMPThreadId(), GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelRed, GetRandomSecretKey(), _MagickPixelPacket::green, _MagickPixelPacket::index, InheritException(), IntensityCompare(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, MeanEvaluateOperator, MedianEvaluateOperator, MultiplyEvaluateOperator, _MagickPixelPacket::opacity, _Image::progress_monitor, QuantumScale, QueueCacheViewAuthenticPixels(), random_info, _MagickPixelPacket::red, ResourceLimitError, RootMeanSquareEvaluateOperator, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowMagickException(), and TraceEvent.
Referenced by AverageImages(), MaximumImages(), and MinimumImages().
EvaluateMax()
static double EvaluateMax (const double x, const double y) inline static
Referenced by ApplyEvaluateOperator(), and GetImageChannelStatistics().
FunctionImage()
MagickExport MagickBooleanType FunctionImage (Image * image, const MagickFunction function, const size_t number_parameters, const double * parameters, ExceptionInfo * exception)
References CompositeChannels, and FunctionImageChannel().
FunctionImageChannel()
MagickExport MagickBooleanType FunctionImageChannel (Image * image, const ChannelType channel, const MagickFunction function, const size_t number_parameters, const double * parameters, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), ApplyFunction(), BlueChannel, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::exception, _Image::filename, FunctionImageTag, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, GreenChannel, IndexChannel, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OpacityChannel, _Image::progress_monitor, RedChannel, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by BrightnessContrastImageChannel(), and FunctionImage().
GetImageChannelEntropy()
MagickExport MagickBooleanType GetImageChannelEntropy (const Image * image, const ChannelType channel, double * entropy, ExceptionInfo * exception)
References BlackChannel, BlueChannel, CMYKColorspace, _Image::colorspace, CompositeChannels, _Image::debug, _ChannelStatistics::entropy, _Image::filename, GetImageChannelStatistics(), GetMagickModule, GreenChannel, IndexChannel, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OpacityChannel, RedChannel, RelinquishMagickMemory(), _Image::signature, and TraceEvent.
Referenced by GetImageEntropy(), and GetMagickProperty().
GetImageChannelExtrema()
MagickExport MagickBooleanType GetImageChannelExtrema (const Image * image, const ChannelType channel, size_t * minima, size_t * maxima, ExceptionInfo * exception)
References _Image::debug, _Image::filename, GetImageChannelRange(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _Image::signature, and TraceEvent.
Referenced by GetImageExtrema().
GetImageChannelKurtosis()
MagickExport MagickBooleanType GetImageChannelKurtosis (const Image * image, const ChannelType channel, double * kurtosis, double * skewness, ExceptionInfo * exception)
References BlueChannel, CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, _Image::filename, GetMagickModule, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, GetVirtualIndexQueue(), GetVirtualPixels(), GreenChannel, IndexChannel, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, OpacityChannel, RedChannel, _Image::rows, _Image::signature, and TraceEvent.
Referenced by FxChannelStatistics(), GetImageKurtosis(), and GetMagickProperty().
GetImageChannelMean()
MagickExport MagickBooleanType GetImageChannelMean (const Image * image, const ChannelType channel, double * mean, double * standard_deviation, ExceptionInfo * exception)
References BlackChannel, BlueChannel, CMYKColorspace, _Image::colorspace, CompositeChannels, _Image::debug, _Image::filename, GetImageChannelStatistics(), GetMagickModule, GreenChannel, IndexChannel, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _ChannelStatistics::mean, OpacityChannel, QuantumRange, RedChannel, RelinquishMagickMemory(), _Image::signature, _ChannelStatistics::standard_deviation, and TraceEvent.
Referenced by AutoGammaImageChannel(), FxChannelStatistics(), GetImageMean(), and GetMagickProperty().
GetImageChannelMoments()
MagickExport ChannelMoments * GetImageChannelMoments (const Image * image, ExceptionInfo * exception)
References AcquireQuantumMemory(), _MagickPixelPacket::blue, BlueChannel, _ChannelMoments::centroid, CMYKColorspace, _Image::colorspace, _Image::columns, CompositeChannels, _Image::debug, _ChannelMoments::ellipse_angle, _ChannelMoments::ellipse_axis, _ChannelMoments::ellipse_eccentricity, _ChannelMoments::ellipse_intensity, _Image::filename, GetMagickModule, GetMagickPixelPacket(), GetVirtualIndexQueue(), GetVirtualPixels(), _MagickPixelPacket::green, GreenChannel, _ChannelMoments::I, _MagickPixelPacket::index, IndexChannel, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickPI, _Image::matte, _MagickPixelPacket::opacity, OpacityChannel, PerceptibleReciprocal(), QuantumScale, RadiansToDegrees(), _MagickPixelPacket::red, RedChannel, RelinquishMagickMemory(), _Image::rows, SetMagickPixelPacket(), _Image::signature, TraceEvent, _PointInfo::x, and _PointInfo::y.
Referenced by GetImageChannelPerceptualHash(), and IdentifyImage().
GetImageChannelPerceptualHash()
MagickExport ChannelPerceptualHash * GetImageChannelPerceptualHash (const Image * image, ExceptionInfo * exception)
References AcquireQuantumMemory(), BlurImage(), CompositeChannels, _Image::depth, DestroyImage(), GetImageChannelMoments(), HCLpColorspace, MagickFalse, MagickLog10(), MaximumNumberOfImageMoments, RelinquishMagickMemory(), sRGBColorspace, and TransformImageColorspace().
Referenced by GetPerceptualHashDistortion(), and IdentifyImage().
GetImageChannelRange()
MagickExport MagickBooleanType GetImageChannelRange (const Image * image, const ChannelType channel, double * minima, double * maxima, ExceptionInfo * exception)
References _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, _Image::filename, GetMagickModule, GetMagickPixelPacket(), GetVirtualIndexQueue(), GetVirtualPixels(), _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickMaximumValue, MagickTrue, _Image::matte, _MagickPixelPacket::opacity, OpacityChannel, QuantumRange, _MagickPixelPacket::red, RedChannel, _Image::rows, SetMagickPixelPacket(), _Image::signature, and TraceEvent.
Referenced by FxChannelStatistics(), GetImageChannelExtrema(), GetImageRange(), GetMagickProperty(), and MinMaxStretchImage().
GetImageChannelStatistics()
MagickExport ChannelStatistics * GetImageChannelStatistics (const Image * image, ExceptionInfo * exception)
References AcquireQuantumMemory(), BlackChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _Image::colorspace, _Image::columns, CompositeChannels, _Image::debug, _ChannelStatistics::depth, _ChannelStatistics::entropy, EvaluateMax(), _Image::filename, GetMagickModule, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelRed, GetQuantumRange(), GetVirtualIndexQueue(), GetVirtualPixels(), _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, IsPixelAtDepth(), _ChannelStatistics::kurtosis, LogMagickEvent(), magick_restrict, MAGICKCORE_QUANTUM_DEPTH, MagickCoreSignature, MagickFalse, MagickLog10(), MagickMaximumValue, MagickMin, _Image::matte, _ChannelStatistics::maxima, MaxMap, _ChannelStatistics::mean, _ChannelStatistics::minima, _MagickPixelPacket::opacity, OpacityChannel, PerceptibleReciprocal(), _MagickPixelPacket::red, RedChannel, RelinquishMagickMemory(), _Image::rows, _Image::signature, _ChannelStatistics::skewness, _ChannelStatistics::standard_deviation, _ChannelStatistics::sum, _ChannelStatistics::sum_cubed, _ChannelStatistics::sum_fourth_power, _ChannelStatistics::sum_squared, TraceEvent, and _ChannelStatistics::variance.
Referenced by GetImageChannelEntropy(), GetImageChannelMean(), GetNormalizedCrossCorrelationDistortion(), and IdentifyImage().
GetImageEntropy()
MagickExport MagickBooleanType GetImageEntropy (const Image * image, double * entropy, ExceptionInfo * exception)
References CompositeChannels, and GetImageChannelEntropy().
GetImageExtrema()
MagickExport MagickBooleanType GetImageExtrema (const Image * image, size_t * minima, size_t * maxima, ExceptionInfo * exception)
References CompositeChannels, and GetImageChannelExtrema().
GetImageKurtosis()
MagickExport MagickBooleanType GetImageKurtosis (const Image * image, double * kurtosis, double * skewness, ExceptionInfo * exception)
References CompositeChannels, and GetImageChannelKurtosis().
GetImageMean()
MagickExport MagickBooleanType GetImageMean (const Image * image, double * mean, double * standard_deviation, ExceptionInfo * exception)
References CompositeChannels, and GetImageChannelMean().
GetImageRange()
MagickExport MagickBooleanType GetImageRange (const Image * image, double * minima, double * maxima, ExceptionInfo * exception)
References CompositeChannels, and GetImageChannelRange().
GetMaximumPixelList()
static void GetMaximumPixelList (PixelList * pixel_list, MagickPixelPacket * pixel) static
References _MagickPixelPacket::blue, _ListNode::count, _MagickPixelPacket::green, _MagickPixelPacket::index, _PixelList::length, ListChannels, _PixelList::lists, _ListNode::next, _SkipList::nodes, _MagickPixelPacket::opacity, and _MagickPixelPacket::red.
Referenced by StatisticImageChannel().
GetMeanPixelList()
static void GetMeanPixelList (PixelList * pixel_list, MagickPixelPacket * pixel) static
References _MagickPixelPacket::blue, _ListNode::count, _MagickPixelPacket::green, _MagickPixelPacket::index, _PixelList::length, ListChannels, _PixelList::lists, _ListNode::next, _SkipList::nodes, _MagickPixelPacket::opacity, and _MagickPixelPacket::red.
Referenced by StatisticImageChannel().
GetMedianPixelList()
static void GetMedianPixelList (PixelList * pixel_list, MagickPixelPacket * pixel) static
References _MagickPixelPacket::blue, _ListNode::count, GetMagickPixelPacket(), _MagickPixelPacket::green, _MagickPixelPacket::index, _PixelList::length, ListChannels, _PixelList::lists, _ListNode::next, _SkipList::nodes, _MagickPixelPacket::opacity, and _MagickPixelPacket::red.
Referenced by StatisticImageChannel().
GetMinimumPixelList()
static void GetMinimumPixelList (PixelList * pixel_list, MagickPixelPacket * pixel) static
References _MagickPixelPacket::blue, _ListNode::count, _MagickPixelPacket::green, _MagickPixelPacket::index, _PixelList::length, ListChannels, _PixelList::lists, _ListNode::next, _SkipList::nodes, _MagickPixelPacket::opacity, and _MagickPixelPacket::red.
Referenced by StatisticImageChannel().
GetModePixelList()
static void GetModePixelList (PixelList * pixel_list, MagickPixelPacket * pixel) static
References _MagickPixelPacket::blue, _ListNode::count, _MagickPixelPacket::green, _MagickPixelPacket::index, _PixelList::length, _PixelList::lists, _ListNode::next, _SkipList::nodes, _MagickPixelPacket::opacity, and _MagickPixelPacket::red.
Referenced by StatisticImageChannel().
GetNonpeakPixelList()
static void GetNonpeakPixelList (PixelList * pixel_list, MagickPixelPacket * pixel) static
References _MagickPixelPacket::blue, _ListNode::count, _MagickPixelPacket::green, _MagickPixelPacket::index, _PixelList::length, _PixelList::lists, _ListNode::next, _SkipList::nodes, _MagickPixelPacket::opacity, and _MagickPixelPacket::red.
Referenced by StatisticImageChannel().
GetRootMeanSquarePixelList()
static void GetRootMeanSquarePixelList (PixelList * pixel_list, MagickPixelPacket * pixel) static
References _MagickPixelPacket::blue, _ListNode::count, _MagickPixelPacket::green, _MagickPixelPacket::index, _PixelList::length, ListChannels, _PixelList::lists, _ListNode::next, _SkipList::nodes, _MagickPixelPacket::opacity, and _MagickPixelPacket::red.
Referenced by StatisticImageChannel().
GetStandardDeviationPixelList()
static void GetStandardDeviationPixelList (PixelList * pixel_list, MagickPixelPacket * pixel) static
References _MagickPixelPacket::blue, _ListNode::count, _MagickPixelPacket::green, _MagickPixelPacket::index, _PixelList::length, ListChannels, _PixelList::lists, _ListNode::next, _SkipList::nodes, _MagickPixelPacket::opacity, and _MagickPixelPacket::red.
Referenced by StatisticImageChannel().
InsertPixelList()
static void InsertPixelList (const Image * image, const PixelPacket * pixel, const IndexPacket * indexes, PixelList * pixel_list) inline static
References AddNodePixelList(), CMYKColorspace, _Image::colorspace, _ListNode::count, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _PixelList::lists, _SkipList::nodes, _ListNode::signature, and _PixelList::signature.
Referenced by StatisticImageChannel().
IntensityCompare()
static int IntensityCompare (const void * x, const void * y) static
References MagickPixelIntensity().
Referenced by EvaluateImages().
MagickLog10()
static double MagickLog10 (const double x) inline static
References Log10Epsilon.
Referenced by GetImageChannelPerceptualHash(), and GetImageChannelStatistics().
PolynomialImage()
MagickExport Image * PolynomialImage (const Image * images, const size_t number_terms, const double * terms, ExceptionInfo * exception)
References DefaultChannels, and PolynomialImageChannel().
PolynomialImageChannel()
MagickExport Image * PolynomialImageChannel (const Image * images, const ChannelType channel, const size_t number_terms, const double * terms, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireImageCanvas(), AcquirePixelThreadSet(), AcquireVirtualCacheView(), _PixelPacket::blue, BlueChannel, ClampToQuantum(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DestroyPixelThreadSet(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetImageListLength(), GetMagickModule, GetMagickPixelPacket(), GetNextImageInList(), GetOpenMPThreadId(), _PixelPacket::green, GreenChannel, IndexChannel, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _PixelPacket::opacity, OpacityChannel, PolynomialImageTag, _Image::progress_monitor, QuantumRange, QuantumScale, QueueCacheViewAuthenticPixels(), _PixelPacket::red, RedChannel, ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowMagickException(), and TraceEvent.
Referenced by PolynomialImage().
ResetPixelList()
static void ResetPixelList (PixelList * pixel_list) static
References _SkipList::level, _PixelList::lists, _ListNode::next, _SkipList::nodes, _PixelList::seed, and _PixelList::signature.
Referenced by StatisticImageChannel().
StatisticImage()
MagickExport Image * StatisticImage (const Image * image, const StatisticType type, const size_t width, const size_t height, ExceptionInfo * exception)
References DefaultChannels, and StatisticImageChannel().
Referenced by DeskewImage(), MedianFilterImage(), ModeImage(), PreviewImage(), and ReduceNoiseImage().
StatisticImageChannel()
MagickExport Image * StatisticImageChannel (const Image * image, const ChannelType channel, const StatisticType type, const size_t width, const size_t height, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquirePixelListThreadSet(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, BlueChannel, ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DestroyPixelListThreadSet(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), GetMaximumPixelList(), GetMeanPixelList(), GetMedianPixelList(), GetMinimumPixelList(), GetModePixelList(), GetNonpeakPixelList(), GetOpenMPThreadId(), GetOptimalKernelWidth2D(), GetRootMeanSquarePixelList(), GetStandardDeviationPixelList(), GradientStatistic, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, InheritException(), InsertPixelList(), LogMagickEvent(), magick_restrict, MagickAbsoluteValue, MagickCoreSignature, MagickFalse, MagickTrue, MaximumStatistic, MeanStatistic, MedianStatistic, MinimumStatistic, ModeStatistic, NonpeakStatistic, _MagickPixelPacket::opacity, OpacityChannel, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _MagickPixelPacket::red, RedChannel, ResetPixelList(), ResourceLimitError, RootMeanSquareStatistic, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacket(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, StandardDeviationStatistic, StatisticImageTag, SyncCacheViewAuthenticPixels(), ThrowImageException, and TraceEvent.
Referenced by StatisticImage().