MagickCore: statistic.h File Reference
statistic.h File Reference
#include "magick/draw.h"
Data Structures
struct _ChannelStatistics
struct _ChannelMoments
struct _ChannelPerceptualHash
Macros
#define MaximumNumberOfImageMoments 8
#define MaximumNumberOfPerceptualHashes 7
Typedefs
typedef struct _ChannelStatistics ChannelStatistics
typedef struct _ChannelMoments ChannelMoments
typedef struct _ChannelPerceptualHash ChannelPerceptualHash
Enumerations
enum MagickEvaluateOperator {
UndefinedEvaluateOperator , AddEvaluateOperator , AndEvaluateOperator , DivideEvaluateOperator ,
LeftShiftEvaluateOperator , MaxEvaluateOperator , MinEvaluateOperator , MultiplyEvaluateOperator ,
OrEvaluateOperator , RightShiftEvaluateOperator , SetEvaluateOperator , SubtractEvaluateOperator ,
XorEvaluateOperator , PowEvaluateOperator , LogEvaluateOperator , ThresholdEvaluateOperator ,
ThresholdBlackEvaluateOperator , ThresholdWhiteEvaluateOperator , GaussianNoiseEvaluateOperator , ImpulseNoiseEvaluateOperator ,
LaplacianNoiseEvaluateOperator , MultiplicativeNoiseEvaluateOperator , PoissonNoiseEvaluateOperator , UniformNoiseEvaluateOperator ,
CosineEvaluateOperator , SineEvaluateOperator , AddModulusEvaluateOperator , MeanEvaluateOperator ,
AbsEvaluateOperator , ExponentialEvaluateOperator , MedianEvaluateOperator , SumEvaluateOperator ,
RootMeanSquareEvaluateOperator , InverseLogEvaluateOperator
}
enum MagickFunction {
UndefinedFunction , PolynomialFunction , SinusoidFunction , ArcsinFunction ,
ArctanFunction
}
enum StatisticType {
UndefinedStatistic , GradientStatistic , MaximumStatistic , MeanStatistic ,
MedianStatistic , MinimumStatistic , ModeStatistic , NonpeakStatistic ,
StandardDeviationStatistic , RootMeanSquareStatistic
}
Functions
MagickExport ChannelStatistics * GetImageChannelStatistics (const Image *, ExceptionInfo *)
MagickExport ChannelMoments * GetImageChannelMoments (const Image *, ExceptionInfo *)
MagickExport ChannelPerceptualHash * GetImageChannelPerceptualHash (const Image *, ExceptionInfo *)
MagickExport Image * EvaluateImages (const Image *, const MagickEvaluateOperator, ExceptionInfo *)
MagickExport Image * PolynomialImage (const Image *, const size_t, const double *, ExceptionInfo *)
MagickExport Image * PolynomialImageChannel (const Image *, const ChannelType, const size_t, const double *, ExceptionInfo *)
MagickExport Image * StatisticImage (const Image *, const StatisticType, const size_t, const size_t, ExceptionInfo *)
MagickExport Image * StatisticImageChannel (const Image *, const ChannelType, const StatisticType, const size_t, const size_t, ExceptionInfo *)
MagickExport MagickBooleanType EvaluateImage (Image *, const MagickEvaluateOperator, const double, ExceptionInfo *)
MagickExport MagickBooleanType EvaluateImageChannel (Image *, const ChannelType, const MagickEvaluateOperator, const double, ExceptionInfo *)
MagickExport MagickBooleanType FunctionImage (Image *, const MagickFunction, const size_t, const double *, ExceptionInfo *)
MagickExport MagickBooleanType FunctionImageChannel (Image *, const ChannelType, const MagickFunction, const size_t, const double *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageChannelEntropy (const Image *, const ChannelType, double *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageChannelExtrema (const Image *, const ChannelType, size_t *, size_t *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageChannelMean (const Image *, const ChannelType, double *, double *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageChannelKurtosis (const Image *, const ChannelType, double *, double *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageChannelRange (const Image *, const ChannelType, double *, double *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageEntropy (const Image *, double *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageExtrema (const Image *, size_t *, size_t *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageMean (const Image *, double *, double *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageKurtosis (const Image *, double *, double *, ExceptionInfo *)
MagickExport MagickBooleanType GetImageRange (const Image *, double *, double *, ExceptionInfo *)
Macro Definition Documentation
MaximumNumberOfImageMoments
#define MaximumNumberOfImageMoments 8
MaximumNumberOfPerceptualHashes
#define MaximumNumberOfPerceptualHashes 7
Typedef Documentation
ChannelMoments
typedef struct _ChannelMoments ChannelMoments
ChannelPerceptualHash
typedef struct _ChannelPerceptualHash ChannelPerceptualHash
ChannelStatistics
typedef struct _ChannelStatistics ChannelStatistics
Enumeration Type Documentation
MagickEvaluateOperator
enum MagickEvaluateOperator
Enumerator
UndefinedEvaluateOperator
AddEvaluateOperator
AndEvaluateOperator
DivideEvaluateOperator
LeftShiftEvaluateOperator
MaxEvaluateOperator
MinEvaluateOperator
MultiplyEvaluateOperator
OrEvaluateOperator
RightShiftEvaluateOperator
SetEvaluateOperator
SubtractEvaluateOperator
XorEvaluateOperator
PowEvaluateOperator
LogEvaluateOperator
ThresholdEvaluateOperator
ThresholdBlackEvaluateOperator
ThresholdWhiteEvaluateOperator
GaussianNoiseEvaluateOperator
ImpulseNoiseEvaluateOperator
LaplacianNoiseEvaluateOperator
MultiplicativeNoiseEvaluateOperator
PoissonNoiseEvaluateOperator
UniformNoiseEvaluateOperator
CosineEvaluateOperator
SineEvaluateOperator
AddModulusEvaluateOperator
MeanEvaluateOperator
AbsEvaluateOperator
ExponentialEvaluateOperator
MedianEvaluateOperator
SumEvaluateOperator
RootMeanSquareEvaluateOperator
InverseLogEvaluateOperator
MagickFunction
enum MagickFunction
Enumerator
UndefinedFunction
PolynomialFunction
SinusoidFunction
ArcsinFunction
ArctanFunction
StatisticType
enum StatisticType
Enumerator
UndefinedStatistic
GradientStatistic
MaximumStatistic
MeanStatistic
MedianStatistic
MinimumStatistic
ModeStatistic
NonpeakStatistic
StandardDeviationStatistic
RootMeanSquareStatistic
Function Documentation
EvaluateImage()
MagickExport MagickBooleanType EvaluateImage (Image * , const MagickEvaluateOperator, const double , ExceptionInfo *)
EvaluateImageChannel()
MagickExport MagickBooleanType EvaluateImageChannel (Image * , const ChannelType, const MagickEvaluateOperator, const double , ExceptionInfo *)
EvaluateImages()
MagickExport Image * EvaluateImages (const Image * , const MagickEvaluateOperator, ExceptionInfo *)
FunctionImage()
MagickExport MagickBooleanType FunctionImage (Image * , const MagickFunction, const size_t, const double * , ExceptionInfo *)
FunctionImageChannel()
MagickExport MagickBooleanType FunctionImageChannel (Image * , const ChannelType, const MagickFunction, const size_t, const double * , ExceptionInfo *)
GetImageChannelEntropy()
MagickExport MagickBooleanType GetImageChannelEntropy (const Image * , const ChannelType, double * , ExceptionInfo *)
GetImageChannelExtrema()
MagickExport MagickBooleanType GetImageChannelExtrema (const Image * , const ChannelType, size_t * , size_t * , ExceptionInfo *)
GetImageChannelKurtosis()
MagickExport MagickBooleanType GetImageChannelKurtosis (const Image * , const ChannelType, double * , double * , ExceptionInfo *)
GetImageChannelMean()
MagickExport MagickBooleanType GetImageChannelMean (const Image * , const ChannelType, double * , double * , ExceptionInfo *)
GetImageChannelMoments()
MagickExport ChannelMoments * GetImageChannelMoments (const Image * image, ExceptionInfo * exception)
References AcquireQuantumMemory(), _MagickPixelPacket::blue, BlueChannel, _ChannelMoments::centroid, CMYKColorspace, _Image::colorspace, _Image::columns, CompositeChannels, _Image::debug, _ChannelMoments::ellipse_angle, _ChannelMoments::ellipse_axis, _ChannelMoments::ellipse_eccentricity, _ChannelMoments::ellipse_intensity, _Image::filename, GetMagickModule, GetMagickPixelPacket(), GetVirtualIndexQueue(), GetVirtualPixels(), _MagickPixelPacket::green, GreenChannel, _ChannelMoments::I, _MagickPixelPacket::index, IndexChannel, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickPI, _Image::matte, _MagickPixelPacket::opacity, OpacityChannel, PerceptibleReciprocal(), QuantumScale, RadiansToDegrees(), _MagickPixelPacket::red, RedChannel, RelinquishMagickMemory(), _Image::rows, SetMagickPixelPacket(), _Image::signature, TraceEvent, _PointInfo::x, and _PointInfo::y.
Referenced by GetImageChannelPerceptualHash(), and IdentifyImage().
GetImageChannelPerceptualHash()
MagickExport ChannelPerceptualHash * GetImageChannelPerceptualHash (const Image * image, ExceptionInfo * exception)
References AcquireQuantumMemory(), BlurImage(), CompositeChannels, _Image::depth, DestroyImage(), GetImageChannelMoments(), HCLpColorspace, MagickFalse, MagickLog10(), MaximumNumberOfImageMoments, RelinquishMagickMemory(), sRGBColorspace, and TransformImageColorspace().
Referenced by GetPerceptualHashDistortion(), and IdentifyImage().
GetImageChannelRange()
MagickExport MagickBooleanType GetImageChannelRange (const Image * , const ChannelType, double * , double * , ExceptionInfo *)
GetImageChannelStatistics()
MagickExport ChannelStatistics * GetImageChannelStatistics (const Image * image, ExceptionInfo * exception)
References AcquireQuantumMemory(), BlackChannel, _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _Image::colorspace, _Image::columns, CompositeChannels, _Image::debug, _ChannelStatistics::depth, _ChannelStatistics::entropy, EvaluateMax(), _Image::filename, GetMagickModule, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelRed, GetQuantumRange(), GetVirtualIndexQueue(), GetVirtualPixels(), _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, IsPixelAtDepth(), _ChannelStatistics::kurtosis, LogMagickEvent(), magick_restrict, MAGICKCORE_QUANTUM_DEPTH, MagickCoreSignature, MagickFalse, MagickLog10(), MagickMaximumValue, MagickMin, _Image::matte, _ChannelStatistics::maxima, MaxMap, _ChannelStatistics::mean, _ChannelStatistics::minima, _MagickPixelPacket::opacity, OpacityChannel, PerceptibleReciprocal(), _MagickPixelPacket::red, RedChannel, RelinquishMagickMemory(), _Image::rows, _Image::signature, _ChannelStatistics::skewness, _ChannelStatistics::standard_deviation, _ChannelStatistics::sum, _ChannelStatistics::sum_cubed, _ChannelStatistics::sum_fourth_power, _ChannelStatistics::sum_squared, TraceEvent, and _ChannelStatistics::variance.
Referenced by GetImageChannelEntropy(), GetImageChannelMean(), GetNormalizedCrossCorrelationDistortion(), and IdentifyImage().
GetImageEntropy()
MagickExport MagickBooleanType GetImageEntropy (const Image * , double * , ExceptionInfo *)
GetImageExtrema()
MagickExport MagickBooleanType GetImageExtrema (const Image * , size_t * , size_t * , ExceptionInfo *)
GetImageKurtosis()
MagickExport MagickBooleanType GetImageKurtosis (const Image * , double * , double * , ExceptionInfo *)
GetImageMean()
MagickExport MagickBooleanType GetImageMean (const Image * , double * , double * , ExceptionInfo *)
GetImageRange()
MagickExport MagickBooleanType GetImageRange (const Image * image, double * minima, double * maxima, ExceptionInfo * exception)
References CompositeChannels, and GetImageChannelRange().
PolynomialImage()
MagickExport Image * PolynomialImage (const Image * , const size_t, const double * , ExceptionInfo *)
PolynomialImageChannel()
MagickExport Image * PolynomialImageChannel (const Image * , const ChannelType, const size_t, const double * , ExceptionInfo *)
StatisticImage()
MagickExport Image * StatisticImage (const Image * , const StatisticType, const size_t, const size_t, ExceptionInfo *)
StatisticImageChannel()
MagickExport Image * StatisticImageChannel (const Image * image, const ChannelType, const StatisticType, const size_t, const size_t, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquirePixelListThreadSet(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, BlueChannel, ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DestroyPixelListThreadSet(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), GetMaximumPixelList(), GetMeanPixelList(), GetMedianPixelList(), GetMinimumPixelList(), GetModePixelList(), GetNonpeakPixelList(), GetOpenMPThreadId(), GetOptimalKernelWidth2D(), GetRootMeanSquarePixelList(), GetStandardDeviationPixelList(), GradientStatistic, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, InheritException(), InsertPixelList(), LogMagickEvent(), magick_restrict, MagickAbsoluteValue, MagickCoreSignature, MagickFalse, MagickTrue, MaximumStatistic, MeanStatistic, MedianStatistic, MinimumStatistic, ModeStatistic, NonpeakStatistic, _MagickPixelPacket::opacity, OpacityChannel, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _MagickPixelPacket::red, RedChannel, ResetPixelList(), ResourceLimitError, RootMeanSquareStatistic, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetMagickPixelPacket(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, StandardDeviationStatistic, StatisticImageTag, SyncCacheViewAuthenticPixels(), ThrowImageException, and TraceEvent.
Referenced by StatisticImage().