MagickCore: static.c File Reference
static.c File Reference
#include "magick/studio.h"
#include "magick/coder.h"
#include "magick/exception-private.h"
#include "magick/image.h"
#include "magick/module.h"
#include "magick/policy.h"
#include "magick/static.h"
#include "magick/string_.h"
Functions
ModuleExport size_t RegisterUndefinedImage (void)
ModuleExport void UnregisterUndefinedImage (void)
MagickExport MagickBooleanType RegisterStaticModule (const char *module, ExceptionInfo *exception)
MagickExport void RegisterStaticModules (void)
MagickExport MagickBooleanType UnregisterStaticModule (const char *module)
MagickExport void UnregisterStaticModules (void)
Variables
struct {
const char * module
MagickBooleanType registered
size_t(* register_module)(void)
void(* unregister_module)(void)
} MagickModules []
Function Documentation
RegisterStaticModule()
MagickExport MagickBooleanType RegisterStaticModule (const char * module, ExceptionInfo * exception)
References CopyMagickString(), GetCoderInfo(), GetMagickModule, IsRightsAuthorized(), LocaleCompare(), MagickFalse, MagickModules, MagickPathExtent, MagickTrue, module, ModulePolicyDomain, _CoderInfo::name, PolicyError, ReadPolicyRights, register_module, registered, ThrowMagickException(), and WritePolicyRights.
Referenced by GetMagickInfo().
RegisterStaticModules()
MagickExport void RegisterStaticModules (void)
References IsRightsAuthorized(), MagickFalse, MagickModules, MagickTrue, module, ModulePolicyDomain, ReadPolicyRights, register_module, registered, and WritePolicyRights.
Referenced by GetMagickInfo().
RegisterUndefinedImage()
ModuleExport size_t RegisterUndefinedImage (void)
References MagickImageCoderSignature.
UnregisterStaticModule()
MagickExport MagickBooleanType UnregisterStaticModule (const char * module)
References LocaleCompare(), MagickFalse, MagickModules, MagickTrue, module, and registered.
UnregisterStaticModules()
MagickExport void UnregisterStaticModules (void)
References MagickFalse, MagickModules, and registered.
Referenced by MagickCoreTerminus().
UnregisterUndefinedImage()
ModuleExport void UnregisterUndefinedImage (void)
Variable Documentation
struct { ... } MagickModules[]
Referenced by RegisterStaticModule(), RegisterStaticModules(), UnregisterStaticModule(), and UnregisterStaticModules().
module
const char* module
Referenced by LogMagickEvent(), LogMagickEventList(), RegisterStaticModule(), RegisterStaticModules(), ThrowMagickException(), ThrowMagickExceptionList(), TranslateEvent(), and UnregisterStaticModule().
register_module
size_t(* register_module) (void) (void)
Referenced by RegisterStaticModule(), and RegisterStaticModules().
registered
MagickBooleanType registered
Referenced by RegisterStaticModule(), RegisterStaticModules(), UnregisterStaticModule(), and UnregisterStaticModules().
unregister_module
void(* unregister_module) (void) (void)