MagickCore: stream-private.h File Reference
stream-private.h File Reference
Typedefs
typedef struct _StreamInfo StreamInfo
Functions
MagickExport const void * GetStreamInfoClientData (StreamInfo *)
MagickExport Image * StreamImage (const ImageInfo *, StreamInfo *, ExceptionInfo *)
MagickExport MagickBooleanType OpenStream (const ImageInfo *, StreamInfo *, const char *, ExceptionInfo *)
MagickExport StreamInfo * AcquireStreamInfo (const ImageInfo *)
MagickExport StreamInfo * DestroyStreamInfo (StreamInfo *)
MagickExport void SetStreamInfoClientData (StreamInfo *, const void *)
MagickExport void SetStreamInfoMap (StreamInfo *, const char *)
MagickExport void SetStreamInfoStorageType (StreamInfo *, const StorageType)
Typedef Documentation
StreamInfo
typedef struct _StreamInfo StreamInfo
Function Documentation
AcquireStreamInfo()
MagickExport StreamInfo * AcquireStreamInfo (const ImageInfo *)
DestroyStreamInfo()
MagickExport StreamInfo * DestroyStreamInfo (StreamInfo * stream_info)
References CloseBlob(), DestroyImage(), DestroyQuantumInfo(), DestroyString(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, _StreamInfo::map, _StreamInfo::pixels, _StreamInfo::quantum_info, RelinquishAlignedMemory(), RelinquishMagickMemory(), _StreamInfo::signature, _StreamInfo::stream, and TraceEvent.
GetStreamInfoClientData()
MagickExport const void * GetStreamInfoClientData (StreamInfo * stream_info)
References _StreamInfo::client_data, MagickCoreSignature, and _StreamInfo::signature.
OpenStream()
MagickExport MagickBooleanType OpenStream (const ImageInfo * image_info, StreamInfo * stream_info, const char * filename, ExceptionInfo * exception)
References CopyMagickString(), _Image::filename, MaxTextExtent, OpenBlob(), _StreamInfo::stream, and WriteBinaryBlobMode.
SetStreamInfoClientData()
MagickExport void SetStreamInfoClientData (StreamInfo * , const void *)
SetStreamInfoMap()
MagickExport void SetStreamInfoMap (StreamInfo * , const char *)
SetStreamInfoStorageType()
MagickExport void SetStreamInfoStorageType (StreamInfo * stream_info, const StorageType)
References MagickCoreSignature, _StreamInfo::signature, and _StreamInfo::storage_type.
StreamImage()
MagickExport Image * StreamImage (const ImageInfo * image_info, StreamInfo * stream_info, ExceptionInfo * exception)
References AcquireQuantumInfo(), _ImageInfo::client_data, CloneImageInfo(), _ImageInfo::debug, DestroyImage(), DestroyImageInfo(), DestroyQuantumInfo(), _StreamInfo::exception, _ImageInfo::filename, GetMagickModule, _StreamInfo::image_info, LogMagickEvent(), MagickCoreSignature, MagickFalse, _StreamInfo::quantum_info, ReadStream(), _ImageInfo::signature, _StreamInfo::signature, TraceEvent, and WriteStreamImage().