MagickCore: stream.h File Reference
stream.h File Reference
Typedefs
typedef size_t(* StreamHandler) (const Image *, const void *, const size_t)
Functions
MagickExport Image * ReadStream (const ImageInfo *, StreamHandler, ExceptionInfo *)
MagickExport MagickBooleanType WriteStream (const ImageInfo *, Image *, StreamHandler)
Typedef Documentation
StreamHandler
typedef size_t(* StreamHandler) (const Image *, const void *, const size_t)
Function Documentation
ReadStream()
MagickExport Image * ReadStream (const ImageInfo * image_info, StreamHandler stream, ExceptionInfo * exception)
References AcquirePixelCache(), _ImageInfo::cache, CloneImageInfo(), _ImageInfo::debug, _CacheMethods::destroy_pixel_handler, DestroyImageInfo(), DestroyPixelStream(), _ImageInfo::filename, _CacheMethods::get_authentic_indexes_from_handler, _CacheMethods::get_authentic_pixels_from_handler, _CacheMethods::get_authentic_pixels_handler, _CacheMethods::get_one_authentic_pixel_from_handler, _CacheMethods::get_one_virtual_pixel_from_handler, _CacheMethods::get_virtual_indexes_from_handler, _CacheMethods::get_virtual_pixel_handler, _CacheMethods::get_virtual_pixels_handler, GetAuthenticIndexesFromStream(), GetAuthenticPixelsFromStream(), GetAuthenticPixelsStream(), GetMagickModule, GetOneAuthenticPixelFromStream(), GetOneVirtualPixelFromStream(), GetPixelCacheMethods(), GetVirtualIndexesFromStream(), GetVirtualPixelsStream(), GetVirtualPixelStream(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheMethods::queue_authentic_pixels_handler, QueueAuthenticPixelsStream(), ReadImage(), SetPixelCacheMethods(), _ExceptionInfo::signature, _ImageInfo::signature, _ImageInfo::stream, _CacheMethods::sync_authentic_pixels_handler, SyncAuthenticPixelsStream(), and TraceEvent.
Referenced by PingBlob(), PingImage(), and StreamImage().
WriteStream()
MagickExport MagickBooleanType WriteStream (const ImageInfo * image_info, Image * image, StreamHandler stream)
References CloneImageInfo(), _ImageInfo::debug, DestroyImageInfo(), _ImageInfo::filename, GetMagickModule, LogMagickEvent(), _ImageInfo::magick, MagickCoreSignature, MagickFalse, _Image::signature, _ImageInfo::signature, _ImageInfo::stream, TraceEvent, and WriteImage().