MagickCore: stream.c File Reference
stream.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/cache.h"
#include "magick/cache-private.h"
#include "magick/color-private.h"
#include "magick/composite-private.h"
#include "magick/constitute.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/geometry.h"
#include "magick/memory_.h"
#include "magick/memory-private.h"
#include "magick/pixel.h"
#include "magick/policy.h"
#include "magick/quantum.h"
#include "magick/quantum-private.h"
#include "magick/semaphore.h"
#include "magick/stream.h"
#include "magick/stream-private.h"
#include "magick/string_.h"
Data Structures
struct _StreamInfo
Functions
static const PixelPacket * GetVirtualPixelStream (const Image *, const VirtualPixelMethod, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
static MagickBooleanType StreamImagePixels (const StreamInfo *, const Image *, ExceptionInfo *)
static MagickBooleanType SyncAuthenticPixelsStream (Image *, ExceptionInfo *)
static PixelPacket * QueueAuthenticPixelsStream (Image *, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *)
MagickExport StreamInfo * AcquireStreamInfo (const ImageInfo *image_info)
static void RelinquishStreamPixels (CacheInfo *cache_info)
static void DestroyPixelStream (Image *image)
MagickExport StreamInfo * DestroyStreamInfo (StreamInfo *stream_info)
static IndexPacket * GetAuthenticIndexesFromStream (const Image *image)
static PixelPacket * GetAuthenticPixelsStream (Image *image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
static PixelPacket * GetAuthenticPixelsFromStream (const Image *image)
static MagickBooleanType GetOneAuthenticPixelFromStream (Image *image, const ssize_t x, const ssize_t y, PixelPacket *pixel, ExceptionInfo *exception)
static MagickBooleanType GetOneVirtualPixelFromStream (const Image *image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, PixelPacket *pixel, ExceptionInfo *exception)
MagickExport const void * GetStreamInfoClientData (StreamInfo *stream_info)
static const PixelPacket * GetVirtualPixelsStream (const Image *image)
static const IndexPacket * GetVirtualIndexesFromStream (const Image *image)
static MagickBooleanType AcquireStreamPixels (CacheInfo *cache_info, ExceptionInfo *exception)
static const PixelPacket * GetVirtualPixelStream (const Image *image, const VirtualPixelMethod magick_unused(virtual_pixel_method), const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo *exception)
MagickExport MagickBooleanType OpenStream (const ImageInfo *image_info, StreamInfo *stream_info, const char *filename, ExceptionInfo *exception)
static MagickBooleanType ValidatePixelCacheMorphology (const Image *magick_restrict image)
MagickExport Image * ReadStream (const ImageInfo *image_info, StreamHandler stream, ExceptionInfo *exception)
MagickExport void SetStreamInfoClientData (StreamInfo *stream_info, const void *client_data)
MagickExport void SetStreamInfoMap (StreamInfo *stream_info, const char *map)
MagickExport void SetStreamInfoStorageType (StreamInfo *stream_info, const StorageType storage_type)
static size_t WriteStreamImage (const Image *image, const void *pixels, const size_t columns)
MagickExport Image * StreamImage (const ImageInfo *image_info, StreamInfo *stream_info, ExceptionInfo *exception)
MagickExport MagickBooleanType WriteStream (const ImageInfo *image_info, Image *image, StreamHandler stream)
Variables
static ssize_t cache_anonymous_memory = (-1)
Function Documentation
AcquireStreamInfo()
MagickExport StreamInfo * AcquireStreamInfo (const ImageInfo * image_info)
References AcquireAlignedMemory(), AcquireImage(), AcquireMagickMemory(), CharPixel, ConstantString(), MagickAssumeAligned, MagickCoreSignature, _StreamInfo::map, _StreamInfo::pixels, ResourceLimitFatalError, _StreamInfo::signature, _StreamInfo::storage_type, _StreamInfo::stream, and ThrowFatalException.
AcquireStreamPixels()
static MagickBooleanType AcquireStreamPixels (CacheInfo * cache_info, ExceptionInfo * exception) inline static
References AcquireAlignedMemory(), cache_anonymous_memory, DestroyString(), _CacheInfo::filename, GetMagickModule, GetPolicyValue(), IOMode, _CacheInfo::length, LocaleCompare(), MagickAssumeAligned, MagickFalse, MagickTrue, MapBlob(), _CacheInfo::mapped, MissingDelegateError, _CacheInfo::pixels, ResourceLimitError, and ThrowMagickException().
Referenced by GetVirtualPixelStream(), and QueueAuthenticPixelsStream().
DestroyPixelStream()
static void DestroyPixelStream (Image * image) static
References _Image::cache, _Image::debug, DestroyPixelCacheNexus(), DestroySemaphoreInfo(), _CacheInfo::file_semaphore, _Image::filename, GetMagickModule, LockSemaphoreInfo(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _CacheInfo::nexus_info, _CacheInfo::number_threads, _CacheInfo::reference_count, RelinquishAlignedMemory(), RelinquishStreamPixels(), _CacheInfo::semaphore, _CacheInfo::signature, _Image::signature, TraceEvent, and UnlockSemaphoreInfo().
Referenced by ReadStream().
DestroyStreamInfo()
MagickExport StreamInfo * DestroyStreamInfo (StreamInfo * stream_info)
References CloseBlob(), DestroyImage(), DestroyQuantumInfo(), DestroyString(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, _StreamInfo::map, _StreamInfo::pixels, _StreamInfo::quantum_info, RelinquishAlignedMemory(), RelinquishMagickMemory(), _StreamInfo::signature, _StreamInfo::stream, and TraceEvent.
GetAuthenticIndexesFromStream()
static IndexPacket * GetAuthenticIndexesFromStream (const Image * image) static
References _Image::cache, _Image::debug, _Image::filename, GetMagickModule, _CacheInfo::indexes, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheInfo::signature, _Image::signature, and TraceEvent.
Referenced by ReadStream().
GetAuthenticPixelsFromStream()
static PixelPacket * GetAuthenticPixelsFromStream (const Image * image) static
References _Image::cache, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheInfo::pixels, _CacheInfo::signature, _Image::signature, and TraceEvent.
Referenced by ReadStream().
GetAuthenticPixelsStream()
static PixelPacket * GetAuthenticPixelsStream (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception) static
References _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, QueueAuthenticPixelsStream(), _Image::signature, and TraceEvent.
Referenced by GetOneAuthenticPixelFromStream(), and ReadStream().
GetOneAuthenticPixelFromStream()
static MagickBooleanType GetOneAuthenticPixelFromStream (Image * image, const ssize_t x, const ssize_t y, PixelPacket * pixel, ExceptionInfo * exception) static
References _Image::background_color, GetAuthenticPixelsStream(), MagickCoreSignature, MagickFalse, MagickTrue, and _Image::signature.
Referenced by ReadStream().
GetOneVirtualPixelFromStream()
static MagickBooleanType GetOneVirtualPixelFromStream (const Image * image, const VirtualPixelMethod virtual_pixel_method, const ssize_t x, const ssize_t y, PixelPacket * pixel, ExceptionInfo * exception) static
References _Image::background_color, GetVirtualPixelStream(), MagickCoreSignature, MagickFalse, MagickTrue, and _Image::signature.
Referenced by ReadStream().
GetStreamInfoClientData()
MagickExport const void * GetStreamInfoClientData (StreamInfo * stream_info)
References _StreamInfo::client_data, MagickCoreSignature, and _StreamInfo::signature.
GetVirtualIndexesFromStream()
static const IndexPacket * GetVirtualIndexesFromStream (const Image * image) static
References _Image::cache, _Image::debug, _Image::filename, GetMagickModule, _CacheInfo::indexes, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheInfo::signature, _Image::signature, and TraceEvent.
Referenced by ReadStream().
GetVirtualPixelsStream()
static const PixelPacket * GetVirtualPixelsStream (const Image * image) static
References _Image::cache, _Image::debug, _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheInfo::pixels, _CacheInfo::signature, _Image::signature, and TraceEvent.
Referenced by ReadStream().
GetVirtualPixelStream() [1/2]
static const PixelPacket * GetVirtualPixelStream (const Image * , const VirtualPixelMethod, const ssize_t, const ssize_t, const size_t, const size_t, ExceptionInfo *) static
Referenced by GetOneVirtualPixelFromStream(), and ReadStream().
GetVirtualPixelStream() [2/2]
static const PixelPacket * GetVirtualPixelStream (const Image * image, const VirtualPixelMethod magick_unusedvirtual_pixel_method, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception) static
References AcquireStreamPixels(), _CacheInfo::active_index_channel, _Image::cache, CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, _Image::filename, GetMagickModule, _CacheInfo::indexes, _CacheInfo::length, LogMagickEvent(), magick_unreferenced, MagickCoreSignature, MagickFalse, MagickTrue, _CacheInfo::pixels, PseudoClass, RelinquishStreamPixels(), _Image::rows, _CacheInfo::signature, _Image::signature, _Image::storage_class, StreamError, ThrowMagickException(), and TraceEvent.
OpenStream()
MagickExport MagickBooleanType OpenStream (const ImageInfo * image_info, StreamInfo * stream_info, const char * filename, ExceptionInfo * exception)
References CopyMagickString(), _Image::filename, MaxTextExtent, OpenBlob(), _StreamInfo::stream, and WriteBinaryBlobMode.
QueueAuthenticPixelsStream()
static PixelPacket * QueueAuthenticPixelsStream (Image * image, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, ExceptionInfo * exception) static
References AcquireStreamPixels(), _CacheInfo::active_index_channel, _Image::cache, _CacheInfo::channels, _Image::channels, CMYKColorspace, _CacheInfo::colorspace, _Image::colorspace, _CacheInfo::columns, _Image::columns, _Image::filename, GetBlobStreamHandler(), GetMagickModule, _CacheInfo::indexes, _CacheInfo::length, MagickCoreSignature, MagickFalse, MagickTrue, _CacheInfo::pixels, PseudoClass, RelinquishStreamPixels(), _CacheInfo::rows, _Image::rows, _CacheInfo::signature, _CacheInfo::storage_class, _Image::storage_class, StreamError, ThrowMagickException(), UndefinedClass, and ValidatePixelCacheMorphology().
Referenced by GetAuthenticPixelsStream(), and ReadStream().
ReadStream()
MagickExport Image * ReadStream (const ImageInfo * image_info, StreamHandler stream, ExceptionInfo * exception)
References AcquirePixelCache(), _ImageInfo::cache, CloneImageInfo(), _ImageInfo::debug, _CacheMethods::destroy_pixel_handler, DestroyImageInfo(), DestroyPixelStream(), _ImageInfo::filename, _CacheMethods::get_authentic_indexes_from_handler, _CacheMethods::get_authentic_pixels_from_handler, _CacheMethods::get_authentic_pixels_handler, _CacheMethods::get_one_authentic_pixel_from_handler, _CacheMethods::get_one_virtual_pixel_from_handler, _CacheMethods::get_virtual_indexes_from_handler, _CacheMethods::get_virtual_pixel_handler, _CacheMethods::get_virtual_pixels_handler, GetAuthenticIndexesFromStream(), GetAuthenticPixelsFromStream(), GetAuthenticPixelsStream(), GetMagickModule, GetOneAuthenticPixelFromStream(), GetOneVirtualPixelFromStream(), GetPixelCacheMethods(), GetVirtualIndexesFromStream(), GetVirtualPixelsStream(), GetVirtualPixelStream(), LogMagickEvent(), MagickCoreSignature, MagickFalse, _CacheMethods::queue_authentic_pixels_handler, QueueAuthenticPixelsStream(), ReadImage(), SetPixelCacheMethods(), _ExceptionInfo::signature, _ImageInfo::signature, _ImageInfo::stream, _CacheMethods::sync_authentic_pixels_handler, SyncAuthenticPixelsStream(), and TraceEvent.
Referenced by PingBlob(), PingImage(), and StreamImage().
RelinquishStreamPixels()
static void RelinquishStreamPixels (CacheInfo * cache_info) inline static
References _CacheInfo::indexes, _CacheInfo::length, MagickFalse, _CacheInfo::mapped, _CacheInfo::pixels, RelinquishAlignedMemory(), and UnmapBlob().
Referenced by DestroyPixelStream(), GetVirtualPixelStream(), and QueueAuthenticPixelsStream().
SetStreamInfoClientData()
MagickExport void SetStreamInfoClientData (StreamInfo * stream_info, const void * client_data)
References _StreamInfo::client_data, MagickCoreSignature, and _StreamInfo::signature.
SetStreamInfoMap()
MagickExport void SetStreamInfoMap (StreamInfo * stream_info, const char * map)
References CloneString(), MagickCoreSignature, _StreamInfo::map, and _StreamInfo::signature.
SetStreamInfoStorageType()
MagickExport void SetStreamInfoStorageType (StreamInfo * stream_info, const StorageType storage_type)
References MagickCoreSignature, _StreamInfo::signature, and _StreamInfo::storage_type.
StreamImage()
MagickExport Image * StreamImage (const ImageInfo * image_info, StreamInfo * stream_info, ExceptionInfo * exception)
References AcquireQuantumInfo(), _ImageInfo::client_data, CloneImageInfo(), _ImageInfo::debug, DestroyImage(), DestroyImageInfo(), DestroyQuantumInfo(), _StreamInfo::exception, _ImageInfo::filename, GetMagickModule, _StreamInfo::image_info, LogMagickEvent(), MagickCoreSignature, MagickFalse, _StreamInfo::quantum_info, ReadStream(), _ImageInfo::signature, _StreamInfo::signature, TraceEvent, and WriteStreamImage().
StreamImagePixels()
static MagickBooleanType StreamImagePixels (const StreamInfo * stream_info, const Image * image, ExceptionInfo * exception) static
References AcquireQuantumMemory(), AlphaQuantum, BlackQuantum, BlueQuantum, CharPixel, ClampToQuantum(), CMYKColorspace, _Image::colorspace, CyanQuantum, _Image::debug, DoublePixel, _Image::filename, FloatPixel, GetAuthenticPixelQueue(), GetImageExtent(), GetMagickModule, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetPixelRed, GetVirtualIndexQueue(), GreenQuantum, ImageError, IndexQuantum, IntegerPixel, LocaleCompare(), LogMagickEvent(), LongPixel, MagentaQuantum, MagickCoreSignature, MagickFalse, MagickTrue, _StreamInfo::map, _QuantumInfo::minimum, OpacityQuantum, OptionError, _StreamInfo::pixels, _StreamInfo::quantum_info, QuantumPixel, QuantumScale, RedQuantum, RelinquishMagickMemory(), ResourceLimitError, _QuantumInfo::scale, ShortPixel, _Image::signature, _StreamInfo::signature, _StreamInfo::storage_type, ThrowMagickException(), TraceEvent, UndefinedQuantum, and YellowQuantum.
Referenced by WriteStreamImage().
SyncAuthenticPixelsStream()
static MagickBooleanType SyncAuthenticPixelsStream (Image * image, ExceptionInfo * exception)
References _Image::cache, _CacheInfo::columns, _Image::debug, _Image::filename, GetBlobStreamHandler(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _CacheInfo::pixels, _CacheInfo::signature, _Image::signature, StreamError, ThrowMagickException(), and TraceEvent.
Referenced by ReadStream().
ValidatePixelCacheMorphology()
static MagickBooleanType ValidatePixelCacheMorphology (const Image *magick_restrict image) inline static
References magick_restrict, MagickFalse, and MagickTrue.
Referenced by QueueAuthenticPixelsStream().
WriteStream()
MagickExport MagickBooleanType WriteStream (const ImageInfo * image_info, Image * image, StreamHandler stream)
References CloneImageInfo(), _ImageInfo::debug, DestroyImageInfo(), _ImageInfo::filename, GetMagickModule, LogMagickEvent(), _ImageInfo::magick, MagickCoreSignature, MagickFalse, _Image::signature, _ImageInfo::signature, _ImageInfo::stream, TraceEvent, and WriteImage().
WriteStreamImage()
static size_t WriteStreamImage (const Image * image, const void * pixels, const size_t columns) static
References AcquireAlignedMemory(), _Image::cache, CharPixel, _Image::client_data, CloneImageInfo(), _CacheInfo::columns, DestroyImageInfo(), DoublePixel, _StreamInfo::exception, _ImageInfo::extract, _StreamInfo::extract_info, FloatPixel, _RectangleInfo::height, _StreamInfo::image, _StreamInfo::image_info, IntegerPixel, LongPixel, MagickAssumeAligned, MagickCoreSignature, _StreamInfo::map, ParseAbsoluteGeometry(), _StreamInfo::pixels, QuantumPixel, RelinquishAlignedMemory(), _CacheInfo::rows, SetImageInfo(), ShortPixel, _CacheInfo::signature, _StreamInfo::storage_type, _StreamInfo::stream, StreamImagePixels(), _RectangleInfo::width, WriteBlob(), _RectangleInfo::x, _RectangleInfo::y, and _StreamInfo::y.
Referenced by StreamImage().
Variable Documentation
cache_anonymous_memory
ssize_t cache_anonymous_memory = (-1) static
Referenced by AcquireStreamPixels().