MagickCore: string.c File Reference
string.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/locale_.h"
#include "magick/log.h"
#include "magick/memory_.h"
#include "magick/nt-base.h"
#include "magick/nt-base-private.h"
#include "magick/property.h"
#include "magick/resource_.h"
#include "magick/signature-private.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/utility-private.h"
Macros
#define CharsPerLine 0x14
Functions
MagickExport char * AcquireString (const char *source)
static StringInfo * AcquireStringInfoContainer ()
MagickExport StringInfo * AcquireStringInfo (const size_t length)
MagickExport StringInfo * BlobToStringInfo (const void *blob, const size_t length)
MagickExport char * CloneString (char **destination, const char *source)
MagickExport StringInfo * CloneStringInfo (const StringInfo *string_info)
MagickExport int CompareStringInfo (const StringInfo *target, const StringInfo *source)
MagickExport size_t ConcatenateMagickString (char *magick_restrict destination, const char *magick_restrict source, const size_t length)
MagickExport MagickBooleanType ConcatenateString (char **magick_restrict destination, const char *magick_restrict source)
MagickExport void ConcatenateStringInfo (StringInfo *string_info, const StringInfo *source)
MagickExport StringInfo * ConfigureFileToStringInfo (const char *filename)
MagickExport char * ConstantString (const char *source)
MagickExport size_t CopyMagickString (char *magick_restrict destination, const char *magick_restrict source, const size_t length)
MagickExport char * DestroyString (char *string)
MagickExport StringInfo * DestroyStringInfo (StringInfo *string_info)
MagickExport char ** DestroyStringList (char **list)
MagickExport char * EscapeString (const char *source, const char escape)
MagickExport char * FileToString (const char *filename, const size_t extent, ExceptionInfo *exception)
MagickExport StringInfo * FileToStringInfo (const char *filename, const size_t extent, ExceptionInfo *exception)
MagickExport ssize_t FormatMagickSize (const MagickSizeType size, const MagickBooleanType bi, char *format)
MagickExport char * GetEnvironmentValue (const char *name)
MagickExport unsigned char * GetStringInfoDatum (const StringInfo *string_info)
MagickExport size_t GetStringInfoLength (const StringInfo *string_info)
MagickExport const char * GetStringInfoName (const StringInfo *string_info)
MagickExport const char * GetStringInfoPath (const StringInfo *string_info)
MagickExport double InterpretSiPrefixValue (const char *magick_restrict string, char **magick_restrict sentinal)
MagickExport MagickBooleanType IsStringTrue (const char *value)
MagickExport MagickBooleanType IsStringNotFalse (const char *value)
MagickExport void PrintStringInfo (FILE *file, const char *id, const StringInfo *string_info)
MagickExport void ResetStringInfo (StringInfo *string_info)
MagickExport char * SanitizeString (const char *source)
MagickExport void SetStringInfo (StringInfo *string_info, const StringInfo *source)
MagickExport void SetStringInfoDatum (StringInfo *string_info, const unsigned char *source)
MagickExport void SetStringInfoLength (StringInfo *string_info, const size_t length)
MagickExport void SetStringInfoName (StringInfo *string_info, const char *name)
MagickExport void SetStringInfoPath (StringInfo *string_info, const char *path)
MagickExport StringInfo * SplitStringInfo (StringInfo *string_info, const size_t offset)
MagickExport char * StringInfoToString (const StringInfo *string_info)
MagickExport char * StringInfoToHexString (const StringInfo *string_info)
MagickExport char ** StringToArgv (const char *text, int *argc)
MagickExport double * StringToArrayOfDoubles (const char *string, ssize_t *count, ExceptionInfo *exception)
MagickExport char * StringToken (const char *delimiters, char **string)
MagickExport char ** StringToList (const char *text)
MagickExport char ** StringToStrings (const char *text, size_t *count)
MagickExport StringInfo * StringToStringInfo (const char *string)
MagickExport void StripString (char *message)
MagickExport MagickBooleanType SubstituteString (char **string, const char *search, const char *replace)
Variables
static const unsigned char AsciiMap []
Macro Definition Documentation
CharsPerLine
#define CharsPerLine 0x14
Function Documentation
AcquireString()
MagickExport char * AcquireString (const char * source)
References AcquireQuantumMemory(), MaxTextExtent, ResourceLimitFatalError, and ThrowFatalException.
Referenced by CanonicalXMLContent(), ClipImagePath(), CloneMontageInfo(), CloneString(), ColorMatrixImage(), ConcatenateString(), DrawPatternPath(), EncodePredefinedEntities(), ExpandFilenames(), FilterImageChannel(), FormatMagickCaption(), FxEvaluateSubexpression(), FxGetSymbol(), GenerateEntropicChaos(), GetCommandOptions(), GetDrawInfo(), GetEXIFProperty(), GetHostname(), GetMontageInfo(), GetMVGMacros(), GetPageGeometry(), GlobExpression(), InterpretDelegateProperties(), InterpretImageProperties(), ListFiles(), LoadCoderCache(), LoadColorCache(), LoadConfigureCache(), LoadDelegateCache(), LoadLocaleCache(), LoadLogCache(), LoadMagicCache(), LoadMimeCache(), LoadTypeCache(), MontageImageList(), PolaroidImage(), QueryMagickColorCompliance(), RenderMVGContent(), SanitizeDelegateString(), SanitizeString(), SelectiveBlurImageChannel(), StringToArgv(), TracePSClippath(), TraceSVGClippath(), TranslateEvent(), TranslateFilename(), VignetteImage(), and XMLTreeInfoToXML().
AcquireStringInfo()
MagickExport StringInfo * AcquireStringInfo (const size_t length)
References AcquireQuantumMemory(), AcquireStringInfoContainer(), _StringInfo::datum, _StringInfo::length, MagickPathExtent, MaxTextExtent, ResourceLimitFatalError, and ThrowFatalException.
Referenced by AcquireRandomInfo(), AcquireSignatureInfo(), CloneStringInfo(), ConnectPixelCacheServer(), GenerateEntropicChaos(), GetConfigureOptions(), GetLocaleOptions(), GetMagickCoreSignature(), GetProfilesFromResourceBlock(), GetRandomKey(), ProfileImage(), SetsRGBImageProfile(), SignatureImage(), SplitStringInfo(), StringToStringInfo(), and WriteTo8BimProfile().
AcquireStringInfoContainer()
static StringInfo * AcquireStringInfoContainer () static
References AcquireMagickMemory(), MagickCoreSignature, ResourceLimitFatalError, _StringInfo::signature, and ThrowFatalException.
Referenced by AcquireStringInfo(), BlobToStringInfo(), ConfigureFileToStringInfo(), and FileToStringInfo().
BlobToStringInfo()
MagickExport StringInfo * BlobToStringInfo (const void * blob, const size_t length)
References AcquireQuantumMemory(), AcquireStringInfoContainer(), _StringInfo::datum, DestroyStringInfo(), _StringInfo::length, MagickPathExtent, MaxTextExtent, ResourceLimitFatalError, and ThrowFatalException.
CloneString()
MagickExport char * CloneString (char ** destination, const char * source)
References AcquireString(), DestroyString(), MaxTextExtent, ResizeQuantumMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by AnnotateImage(), CloneDrawInfo(), CloneImage(), CloneImageInfo(), CloneImageProperties(), CloneStringInfo(), DrawClippingMask(), DrawCompositeMask(), DrawPatternPath(), DrawPrimitive(), GetDrawInfo(), GetPathTemplate(), IdentifyImage(), MontageImageList(), PolaroidImage(), PreviewImage(), RenderMVGContent(), RenderPostscript(), RenderType(), SetImageInfo(), SetImageOption(), and SetStreamInfoMap().
CloneStringInfo()
MagickExport StringInfo * CloneStringInfo (const StringInfo * string_info)
References AcquireStringInfo(), CloneString(), _StringInfo::datum, _StringInfo::length, MagickCoreSignature, _StringInfo::name, _StringInfo::path, and _StringInfo::signature.
Referenced by CloneImageInfo(), CloneImageProfiles(), SetImageProfileInternal(), and WriteTo8BimProfile().
CompareStringInfo()
MagickExport int CompareStringInfo (const StringInfo * target, const StringInfo * source)
References _StringInfo::datum, _StringInfo::length, MagickCoreSignature, MagickMin, and _StringInfo::signature.
Referenced by CompareHashmapStringInfo(), CompareSplayTreeStringInfo(), and ProfileImage().
ConcatenateMagickString()
MagickExport size_t ConcatenateMagickString (char *magick_restrict destination, const char *magick_restrict source, const size_t length)
References magick_restrict.
Referenced by AcquireUniqueSymbolicLink(), ClipImagePath(), ConcatenateColorComponent(), ConcatentateHexColorComponent(), ExpandFilename(), ExpandFilenames(), ExternalDelegateCommand(), FormatMagickCaption(), GetColorTuple(), GetConfigurePaths(), GetExecutionPath(), GetImageViewException(), GetMagickProperty(), GetNumberColors(), GetPageGeometry(), IdentifyImage(), InterpretImageFilename(), ListDelegateInfo(), ListMagickInfo(), LoadCoderCache(), LoadColorCache(), LoadConfigureCache(), LoadDelegateCache(), LoadLocaleCache(), LoadLogCache(), LoadMagicCache(), LoadMimeCache(), LoadPolicyCache(), LoadTypeCache(), MontageImageList(), SetTypeNodePath(), ThrowMagickExceptionList(), and ThumbnailImage().
ConcatenateString()
MagickExport MagickBooleanType ConcatenateString (char **magick_restrict destination, const char *magick_restrict source)
References AcquireString(), MagickTrue, MaxTextExtent, ResizeQuantumMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by CanonicalXMLContent(), ColorMatrixImage(), ExpandFilenames(), FilterImageChannel(), GetIPTCProperty(), ParseCharacterContent(), RenderMVGContent(), SelectiveBlurImageChannel(), TracePSClippath(), and TraceSVGClippath().
ConcatenateStringInfo()
MagickExport void ConcatenateStringInfo (StringInfo * string_info, const StringInfo * source)
References _StringInfo::datum, _StringInfo::length, MagickCoreSignature, ResourceLimitFatalError, SetStringInfoLength(), _StringInfo::signature, and ThrowFatalException.
Referenced by GenerateEntropicChaos(), and GetMagickCoreSignature().
ConfigureFileToStringInfo()
MagickExport StringInfo * ConfigureFileToStringInfo (const char * filename)
References AcquireQuantumMemory(), AcquireStringInfoContainer(), CopyMagickString(), _StringInfo::datum, DestroyString(), _StringInfo::length, MAGICK_SSIZE_MAX, MagickMin, MapBlob(), MaxTextExtent, O_BINARY, open_utf8(), _StringInfo::path, ReadMode, and UnmapBlob().
Referenced by GetConfigureOptions(), and GetLocaleOptions().
ConstantString()
MagickExport char * ConstantString (const char * source)
References AcquireQuantumMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by AcquireCoderCache(), AcquireFxInfo(), AcquireFxThreadSet(), AcquireStreamInfo(), AcquireUniqueFileResource(), AddChildToXMLTree(), CloneImageArtifacts(), CloneImageOptions(), CloneImageProfiles(), CloneImageProperties(), CloneImageView(), ExpandFilenames(), FxGetSymbol(), GetCoderList(), GetColorList(), GetConfigureList(), GetConfigureOption(), GetConfigurePaths(), GetDelegateList(), GetEnvironmentValue(), GetExceptionMessage(), GetImageAttribute(), GetImageRegistry(), GetLocaleList(), GetLogList(), GetMagickHomeURL(), GetMagickList(), GetMagicList(), GetMimeList(), GetMVGMacros(), GetPathTemplate(), GetThresholdMapFile(), GetTypeList(), GetXMLTreeAttributes(), GetXMPProperty(), InterpretDelegateProperties(), InterpretImageProperties(), IsLocaleTreeInstantiated(), IsOptionMember(), LoadCoderCache(), LoadColorCache(), LoadConfigureCache(), LoadDelegateCache(), LoadLocaleCache(), LoadLogCache(), LoadMagicCache(), LoadMimeCache(), LoadTypeCache(), MagickToMime(), NewImageView(), NewImageViewRegion(), NewXMLTree(), NewXMLTreeTag(), ParseEntities(), ParseInternalDoctype(), ParseOpenTag(), ParseProcessingInstructions(), SetFxSymbolValue(), SetImageArtifact(), SetImageOption(), SetImageProfileInternal(), SetImageProperty(), SetImageRegistry(), SetImageViewDescription(), SetLogFormat(), SetMagickInfo(), SetStringInfoName(), SetTypeNodePath(), SetXMLTreeAttribute(), SetXMLTreeContent(), ThrowException(), and WriteTo8BimProfile().
CopyMagickString()
MagickExport size_t CopyMagickString (char *magick_restrict destination, const char *magick_restrict source, const size_t length)
References magick_restrict.
Referenced by AcquireDistributeCacheInfo(), AcquireImage(), AcquireMagicCache(), AcquireNextImage(), AcquireTypeCache(), AllocateString(), AppendImageFormat(), BlobToImage(), ClipImagePath(), CloneImage(), CloneImageInfo(), CloneImageProperties(), CloneMontageInfo(), ConfigureFileToStringInfo(), ConnectedComponentsImage(), DefineImageArtifact(), DefineImageOption(), DefineImageProperty(), DefineImageRegistry(), DistributePixelCacheClient(), DrawPrimitive(), ExpandFilename(), ExpandFilenames(), ExternalDelegateCommand(), FileToStringInfo(), FormatMagickCaption(), FxChannelStatistics(), FxEvaluateSubexpression(), FxGetSymbol(), Get8BIMProperty(), GetColorCompliance(), GetCommandOptionFlags(), GetConfigureBlob(), GetConfigureOptions(), GetConfigurePaths(), GetExceptionMessage(), GetExecutionPath(), GetGeometry(), GetImageMagick(), GetImageViewException(), GetIPTCProperty(), GetLocaleOptions(), GetMagickProperty(), GetMagickPropertyLetter(), GetMontageInfo(), GetMVGMacros(), GetNumberColors(), GetPageGeometry(), GetPathComponent(), GetPathComponents(), GetPolicyInfo(), GlobExpression(), IdentifyImage(), ImagesToBlob(), ImageToBlob(), InjectImageBlob(), InterpretImageFilename(), InvokeDelegate(), IsTaintImage(), ListDelegateInfo(), ListMagickInfo(), ListMagickResourceInfo(), LoadCoderCache(), LoadColorCache(), LoadConfigureCache(), LoadDelegateCache(), LoadLocaleCache(), LoadLogCache(), LoadMagicCache(), LoadMimeCache(), LoadPolicyCache(), LoadTypeCache(), MagickCoreGenesis(), MontageImageList(), OpenBlob(), OpenStream(), ParseCommandOption(), ParseEntities(), ParseGeometry(), ParseProcessingInstructions(), PersistPixelCache(), PingBlob(), PingImages(), PreviewImage(), QueryMagickColorCompliance(), QueryMagickColorname(), ReadImage(), ReadImages(), RegisterStaticModule(), RelinquishUniqueFileResource(), RenderMVGContent(), SetClientName(), SetClientPath(), SetImageInfo(), SetImageProfileInternal(), SetLogName(), SetStringInfoPath(), StringToStrings(), ThrowMagickExceptionList(), ThumbnailImage(), TranslateEvent(), TranslateFilename(), WriteImage(), and WriteImages().
DestroyString()
MagickExport char * DestroyString (char * string)
References RelinquishMagickMemory().
Referenced by AcquireDistributeCacheInfo(), AcquireFxThreadSet(), AcquireImage(), AcquireKernelInfo(), AcquireMatrixInfo(), AcquirePixelCache(), AcquireStreamPixels(), AcquireTypeCache(), AcquireUniqueSymbolicLink(), AcquireVirtualMemory(), AddPathToXMLTree(), AnnotateImage(), CanonicalXMLContent(), ClipImagePath(), CloneString(), ColorMatrixImage(), ConfigureFileToStringInfo(), ConnectPixelCacheServer(), DestroyAttribute(), DestroyCoderNode(), DestroyColorElement(), DestroyConfigureElement(), DestroyDelegate(), DestroyDrawInfo(), DestroyExceptionElement(), DestroyFxInfo(), DestroyImage(), DestroyImageInfo(), DestroyImageView(), DestroyLocaleNode(), DestroyLogElement(), DestroyMagicElement(), DestroyMagickNode(), DestroyMimeElement(), DestroyMontageInfo(), DestroyPolicyElement(), DestroyStreamInfo(), DestroyStringInfo(), DestroyStringList(), DestroyTemporaryResources(), DestroyThresholdMap(), DestroyTypeNode(), DestroyXMLTree(), DestroyXMLTreeAttributes(), DestroyXMLTreeRoot(), DistributePixelCacheClient(), DrawClippingMask(), DrawPrimitive(), EncodePredefinedEntities(), ExpandFilename(), ExpandFilenames(), ExternalDelegateCommand(), FilterImageChannel(), FormatMagickCaption(), FxGetSymbol(), GenerateEntropicChaos(), Get8BIMProperty(), GetConfigureBlob(), GetConfigurePaths(), GetDelegateCommand(), GetEXIFProperty(), GetHostname(), GetImageInfo(), GetIPTCProperty(), GetMaxMemoryRequest(), GetMultilineTypeMetrics(), GetMVGMacros(), GetPathTemplate(), GetXMLTreePath(), GetXMPProperty(), GlobExpression(), IdentifyImage(), InterpretDelegateProperties(), InterpretImageProperties(), InvokeDelegate(), IsLocaleTreeInstantiated(), IsOptionMember(), ListDelegateInfo(), ListMagickInfo(), LoadLogCache(), LoadMimeCache(), MagickCoreGenesis(), MontageImageList(), NewXMLTree(), OpenBlob(), OpenPixelCache(), ParseCharacterContent(), ParseInternalDoctype(), PolaroidImage(), QueryMagickColorCompliance(), ReadImage(), RenderMVGContent(), RenderPostscript(), RenderType(), ResourceComponentGenesis(), SelectiveBlurImageChannel(), SetImageProperty(), SetLogFormat(), SetMagickPrecision(), SetMagickResourceLimit(), SetTypeNodePath(), SetXMLTreeAttribute(), SetXMLTreeContent(), ShredFile(), SignatureImage(), StringToArgv(), SyncImageSettings(), TracePSClippath(), and TraceSVGClippath().
DestroyStringInfo()
MagickExport StringInfo * DestroyStringInfo (StringInfo * string_info)
References _StringInfo::datum, DestroyString(), MagickCoreSignature, _StringInfo::name, RelinquishMagickMemory(), and _StringInfo::signature.
Referenced by AcquireRandomInfo(), AcquireUniqueFileResource(), BlobToStringInfo(), ConnectPixelCacheServer(), DestroyImageInfo(), DestroyOptions(), DestroyProfile(), DestroyRandomInfo(), DestroySignatureInfo(), DistributePixelCacheClient(), FileToStringInfo(), GenerateEntropicChaos(), GetMagickCoreSignature(), GetProfilesFromResourceBlock(), HashStringType(), ProfileImage(), SetsRGBImageProfile(), ShredFile(), SignatureImage(), and WriteTo8BimProfile().
DestroyStringList()
MagickExport char ** DestroyStringList (char ** list)
References DestroyString(), and RelinquishMagickMemory().
EscapeString()
MagickExport char * EscapeString (const char * source, const char escape)
References AcquireQuantumMemory(), MaxTextExtent, ResourceLimitFatalError, and ThrowFatalException.
FileToString()
MagickExport char * FileToString (const char * filename, const size_t extent, ExceptionInfo * exception)
References FileToBlob().
Referenced by AcquireFxThreadSet(), AcquireKernelInfo(), AcquireTypeCache(), ExpandFilenames(), InterpretImageProperties(), LoadTypeCache(), RenderHoughLines(), and RenderMVGContent().
FileToStringInfo()
MagickExport StringInfo * FileToStringInfo (const char * filename, const size_t extent, ExceptionInfo * exception)
References AcquireStringInfoContainer(), CopyMagickString(), _StringInfo::datum, DestroyStringInfo(), FileToBlob(), GetMagickModule, _StringInfo::length, LogMagickEvent(), MaxTextExtent, _StringInfo::path, and TraceEvent.
FormatMagickSize()
MagickExport ssize_t FormatMagickSize (const MagickSizeType size, const MagickBooleanType bi, char * format)
References FormatLocaleString(), GetMagickPrecision(), MagickFalse, and MaxTextExtent.
Referenced by AcquireMagickResource(), GetMagickProperty(), GetMagickPropertyLetter(), IdentifyImage(), ListMagickResourceInfo(), OpenPixelCache(), RelinquishMagickResource(), SetPixelCacheExtent(), and ThumbnailImage().
GetEnvironmentValue()
MagickExport char * GetEnvironmentValue (const char * name)
References ConstantString().
Referenced by AcquireMatrixInfo(), AcquirePixelCache(), AcquireTypeCache(), ExpandFilename(), GetConfigureBlob(), GetConfigurePaths(), GetImageInfo(), GetPathTemplate(), IsLocaleTreeInstantiated(), MagickCoreGenesis(), ResourceComponentGenesis(), SetMagickPrecision(), and ShredFile().
GetStringInfoDatum()
MagickExport unsigned char * GetStringInfoDatum (const StringInfo * string_info)
References _StringInfo::datum, MagickCoreSignature, and _StringInfo::signature.
Referenced by AcquireCoderCache(), AcquireColorCache(), AcquireConfigureCache(), AcquireDelegateCache(), AcquireLocaleSplayTree(), AcquireMagicCache(), AcquireMimeCache(), AcquirePolicyCache(), AcquireRandomInfo(), AcquireTypeCache(), AcquireUniqueFileResource(), ConnectPixelCacheServer(), DistributePixelCacheClient(), FinalizeSignature(), GenerateEntropicChaos(), Get8BIMProperty(), GetEXIFProperty(), GetICCProperty(), GetIPTCProperty(), GetMagickCoreSignature(), GetMagickProperty(), GetProfilesFromResourceBlock(), GetRandomKey(), GetThresholdMap(), HashStringInfoType(), HashStringType(), IdentifyImage(), IncrementRandomNonce(), ListThresholdMaps(), ProfileImage(), ReadImage(), SetImageProfileInternal(), SetRandomKey(), ShredFile(), Sync8BimProfile(), SyncExifProfile(), TransformSignature(), UpdateSignature(), and WriteTo8BimProfile().
GetStringInfoLength()
MagickExport size_t GetStringInfoLength (const StringInfo * string_info)
References _StringInfo::length, MagickCoreSignature, and _StringInfo::signature.
Referenced by AcquireUniqueFileResource(), FinalizeSignature(), Get8BIMProperty(), GetEXIFProperty(), GetICCProperty(), GetIPTCProperty(), GetMagickCoreSignature(), GetMagickProperty(), GetProfilesFromResourceBlock(), GetXMPProperty(), IdentifyImage(), IncrementRandomNonce(), ProfileImage(), ReadImage(), SetImageProfileInternal(), Sync8BimProfile(), SyncExifProfile(), UpdateSignature(), and WriteTo8BimProfile().
GetStringInfoName()
MagickExport const char * GetStringInfoName (const StringInfo * string_info)
References MagickCoreSignature, _StringInfo::name, and _StringInfo::signature.
GetStringInfoPath()
MagickExport const char * GetStringInfoPath (const StringInfo * string_info)
References MagickCoreSignature, _StringInfo::path, and _StringInfo::signature.
Referenced by AcquireCoderCache(), AcquireColorCache(), AcquireConfigureCache(), AcquireDelegateCache(), AcquireLocaleSplayTree(), AcquireMagicCache(), AcquireMimeCache(), AcquirePolicyCache(), AcquireTypeCache(), GetThresholdMap(), and ListThresholdMaps().
InterpretSiPrefixValue()
MagickExport double InterpretSiPrefixValue (const char *magick_restrict string, char **magick_restrict sentinal)
References InterpretLocaleValue(), and MagickEpsilon.
Referenced by FxEvaluateSubexpression(), and SiPrefixToDoubleInterval().
IsStringNotFalse()
MagickExport MagickBooleanType IsStringNotFalse (const char * value)
References LocaleCompare(), MagickFalse, and MagickTrue.
Referenced by SetImageGray(), and SetImageMonochrome().
IsStringTrue()
MagickExport MagickBooleanType IsStringTrue (const char * value)
References LocaleCompare(), MagickFalse, and MagickTrue.
Referenced by AcquireMatrixInfo(), AcquirePixelCache(), AutoThresholdImage(), ConnectedComponentsImage(), DrawPolygonPrimitive(), and GetImageInfo().
PrintStringInfo()
MagickExport void PrintStringInfo (FILE * file, const char * id, const StringInfo * string_info)
References CharsPerLine, _StringInfo::datum, FormatLocaleFile(), _StringInfo::length, MagickCoreSignature, MagickMin, and _StringInfo::signature.
Referenced by IdentifyImage().
ResetStringInfo()
MagickExport void ResetStringInfo (StringInfo * string_info)
References _StringInfo::datum, _StringInfo::length, MagickCoreSignature, and _StringInfo::signature.
Referenced by AcquireRandomInfo(), and ShredFile().
SanitizeString()
MagickExport char * SanitizeString (const char * source)
References AcquireString().
Referenced by ExternalDelegateCommand(), and OpenBlob().
SetStringInfo()
MagickExport void SetStringInfo (StringInfo * string_info, const StringInfo * source)
References _StringInfo::datum, _StringInfo::length, MagickCoreSignature, MagickMin, and _StringInfo::signature.
Referenced by AcquireRandomInfo(), SetRandomKey(), SetSignatureDigest(), and SplitStringInfo().
SetStringInfoDatum()
MagickExport void SetStringInfoDatum (StringInfo * string_info, const unsigned char * source)
References _StringInfo::datum, _StringInfo::length, MagickCoreSignature, and _StringInfo::signature.
Referenced by AcquireRandomInfo(), GenerateEntropicChaos(), GetConfigureOptions(), GetLocaleOptions(), GetProfilesFromResourceBlock(), ProfileImage(), SetsRGBImageProfile(), SignatureImage(), StringToStringInfo(), and UpdateSignature().
SetStringInfoLength()
MagickExport void SetStringInfoLength (StringInfo * string_info, const size_t length)
References AcquireQuantumMemory(), _StringInfo::datum, _StringInfo::length, MagickCoreSignature, MaxTextExtent, ResizeQuantumMemory(), ResourceLimitFatalError, _StringInfo::signature, and ThrowFatalException.
Referenced by AcquireRandomInfo(), ConcatenateStringInfo(), GenerateEntropicChaos(), GetConfigureOptions(), GetLocaleOptions(), GetMagickCoreSignature(), SignatureImage(), and SplitStringInfo().
SetStringInfoName()
MagickExport void SetStringInfoName (StringInfo * string_info, const char * name)
References ConstantString(), MagickCoreSignature, _StringInfo::name, and _StringInfo::signature.
SetStringInfoPath()
MagickExport void SetStringInfoPath (StringInfo * string_info, const char * path)
References CopyMagickString(), MagickCoreSignature, MaxTextExtent, _StringInfo::path, and _StringInfo::signature.
Referenced by GetConfigureOptions(), and GetLocaleOptions().
SplitStringInfo()
MagickExport StringInfo * SplitStringInfo (StringInfo * string_info, const size_t offset)
References AcquireStringInfo(), _StringInfo::datum, _StringInfo::length, MagickCoreSignature, MaxTextExtent, SetStringInfo(), SetStringInfoLength(), and _StringInfo::signature.
StringInfoToHexString()
MagickExport char * StringInfoToHexString (const StringInfo * string_info)
References AcquireQuantumMemory(), _StringInfo::datum, _StringInfo::length, MaxTextExtent, ResourceLimitFatalError, and ThrowFatalException.
Referenced by SignatureImage().
StringInfoToString()
MagickExport char * StringInfoToString (const StringInfo * string_info)
References AcquireQuantumMemory(), _StringInfo::datum, _StringInfo::length, and MaxTextExtent.
Referenced by GetXMPProperty().
StringToArgv()
MagickExport char ** StringToArgv (const char * text, int * argc)
References AcquireQuantumMemory(), AcquireString(), DestroyString(), MaxTextExtent, RelinquishMagickMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by ExpandFilenames(), ExternalDelegateCommand(), GetHostname(), IsOptionMember(), and RenderType().
StringToArrayOfDoubles()
MagickExport double * StringToArrayOfDoubles (const char * string, ssize_t * count, ExceptionInfo * exception)
References AcquireQuantumMemory(), GetMagickModule, MagickCoreSignature, ResourceLimitError, _ExceptionInfo::signature, StringToDouble(), and ThrowMagickException().
StringToken()
MagickExport char * StringToken (const char * delimiters, char ** string)
StringToList()
MagickExport char ** StringToList (const char * text)
References StringToStrings().
Referenced by GetDelegateCommand(), IdentifyImage(), InvokeDelegate(), ListDelegateInfo(), and ListMagickInfo().
StringToStringInfo()
MagickExport StringInfo * StringToStringInfo (const char * string)
References AcquireStringInfo(), and SetStringInfoDatum().
Referenced by GenerateEntropicChaos(), and HashStringType().
StringToStrings()
MagickExport char ** StringToStrings (const char * text, size_t * count)
References AcquireQuantumMemory(), CharsPerLine, CopyMagickString(), FormatLocaleString(), MagickMin, MagickPathExtent, ResizeQuantumMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by GetMultilineTypeMetrics(), and StringToList().
StripString()
MagickExport void StripString (char * message)
Referenced by FxGetSymbol(), and ListDelegateInfo().
SubstituteString()
MagickExport MagickBooleanType SubstituteString (char ** string, const char * search, const char * replace)
References MagickFalse, MagickTrue, MaxTextExtent, ResizeQuantumMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by AcquireFxInfo(), GetEXIFProperty(), GetHostname(), GetXMPProperty(), IsOptionMember(), LoadDelegateCache(), LoadMimeCache(), QueryMagickColorCompliance(), and SetTypeNodePath().
Variable Documentation
AsciiMap
const unsigned char AsciiMap[] static
Initial value:
=
  {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b,
    0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
    0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22, 0x23,
    0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f,
    0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b,
    0x3c, 0x3d, 0x3e, 0x3f, 0x40, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67,
    0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d, 0x6e, 0x6f, 0x70, 0x71, 0x72, 0x73,
    0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7a, 0x5b, 0x5c, 0x5d, 0x5e, 0x5f,
    0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b,
    0x6c, 0x6d, 0x6e, 0x6f, 0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77,
    0x78, 0x79, 0x7a, 0x7b, 0x7c, 0x7d, 0x7e, 0x7f, 0x80, 0x81, 0x82, 0x83,
    0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f,
    0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0x9b,
    0x9c, 0x9d, 0x9e, 0x9f, 0xa0, 0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7,
    0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf, 0xb0, 0xb1, 0xb2, 0xb3,
    0xb4, 0xb5, 0xb6, 0xb7, 0xb8, 0xb9, 0xba, 0xbb, 0xbc, 0xbd, 0xbe, 0xbf,
    0xc0, 0xe1, 0xe2, 0xe3, 0xe4, 0xc5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xeb,
    0xec, 0xed, 0xee, 0xef, 0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7,
    0xf8, 0xf9, 0xfa, 0xdb, 0xdc, 0xdd, 0xde, 0xdf, 0xe0, 0xe1, 0xe2, 0xe3,
    0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xeb, 0xec, 0xed, 0xee, 0xef,
    0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9, 0xfa, 0xfb,
    0xfc, 0xfd, 0xfe, 0xff,
  }