MagickCore: string-private.h File Reference
string-private.h File Reference
#include <string.h>
#include "magick/locale_.h"
Functions
static double SiPrefixToDoubleInterval (const char *string, const double interval)
static const char * StringLocateSubstring (const char *haystack, const char *needle)
static double StringToDouble (const char *magick_restrict string, char **magick_restrict sentinal)
static double StringToDoubleInterval (const char *string, const double interval)
static int StringToInteger (const char *magick_restrict value)
static long StringToLong (const char *magick_restrict value)
static size_t StringToSizeType (const char *string, const double interval)
static unsigned long StringToUnsignedLong (const char *magick_restrict value)
Function Documentation
SiPrefixToDoubleInterval()
static double SiPrefixToDoubleInterval (const char * string, const double interval) inline static
References InterpretSiPrefixValue().
Referenced by StringToSizeType().
StringLocateSubstring()
static const char * StringLocateSubstring (const char * haystack, const char * needle) inline static
Referenced by LoadColorCache().
StringToDouble()
static double StringToDouble (const char *magick_restrict string, char **magick_restrict sentinal) inline static
References InterpretLocaleValue().
Referenced by AcquireResizeFilter(), AddNoiseImageChannel(), CloneImages(), ColorDecisionListImage(), ComplexImages(), ConnectedComponentsImage(), DistortImage(), FxGetSymbol(), GenerateCoefficients(), GetEdgeBoundingBox(), GetGeometry(), GetMagickTime(), GetNextToken(), GetQuantumInfo(), GradientImage(), IsSceneGeometry(), ParseAffineGeometry(), ParseCSSColor(), ParseGeometry(), ParseKernelArray(), RGBTransformImage(), SetImageProperty(), SimilarityMetricImage(), StringToArrayOfDoubles(), and TransformRGBImage().
StringToDoubleInterval()
static double StringToDoubleInterval (const char * string, const double interval) inline static
References InterpretLocaleValue().
Referenced by FloydSteinbergDither(), MorphologyImageChannel(), SetImageProperty(), and SyncImageSettings().
StringToInteger()
static int StringToInteger (const char *magick_restrict value) inline static
Referenced by SetMagickPrecision(), and ShredFile().
StringToLong()
static long StringToLong (const char *magick_restrict value) inline static
Referenced by AcquireResizeFilter(), AddPathToXMLTree(), DeskewImage(), Get8BIMProperty(), GetHostname(), GetThresholdMapFile(), GetXMLTreePath(), LoadMagicCache(), OpenBlob(), ReadImage(), RenderMVGContent(), and TracePath().
StringToSizeType()
static size_t StringToSizeType (const char * string, const double interval) inline static
References MagickULLConstant, and SiPrefixToDoubleInterval().
Referenced by GetMaxMemoryRequest(), ResourceComponentGenesis(), and SetMagickResourceLimit().
StringToUnsignedLong()
static unsigned long StringToUnsignedLong (const char *magick_restrict value) inline static
Referenced by GetDrawInfo(), GetThresholdMapFile(), IdentifyImage(), LoadLogCache(), LoadTypeCache(), RenderMVGContent(), SetImageInfo(), SetImageProperty(), SetStreamBuffering(), and SyncImageSettings().