MagickCore: string_.h File Reference
string_.h File Reference
#include <stdarg.h>
#include <time.h>
#include "magick/exception.h"
Data Structures
struct _StringInfo
Typedefs
typedef struct _StringInfo StringInfo
Functions
MagickExport char * AcquireString (const char *)
MagickExport char * CloneString (char **, const char *)
MagickExport char * ConstantString (const char *)
MagickExport char * DestroyString (char *)
MagickExport char ** DestroyStringList (char **)
MagickExport char * EscapeString (const char *, const char)
MagickExport char * FileToString (const char *, const size_t, ExceptionInfo *)
MagickExport char * GetEnvironmentValue (const char *)
MagickExport char * SanitizeString (const char *)
MagickExport char * StringInfoToHexString (const StringInfo *)
MagickExport char * StringInfoToString (const StringInfo *)
MagickExport char ** StringToArgv (const char *, int *)
MagickExport char * StringToken (const char *, char **)
MagickExport char ** StringToList (const char *)
MagickExport char ** StringToStrings (const char *, size_t *)
MagickExport const char * GetStringInfoName (const StringInfo *)
MagickExport const char * GetStringInfoPath (const StringInfo *)
MagickExport double InterpretSiPrefixValue (const char *magick_restrict, char **magick_restrict)
MagickExport double * StringToArrayOfDoubles (const char *, ssize_t *, ExceptionInfo *)
MagickExport int CompareStringInfo (const StringInfo *, const StringInfo *)
MagickExport MagickBooleanType ConcatenateString (char **magick_restrict, const char *magick_restrict)
MagickExport MagickBooleanType IsStringTrue (const char *) magick_attribute((__pure__))
MagickExport MagickBooleanType IsStringNotFalse (const char *) magick_attribute((__pure__))
MagickExport MagickBooleanType SubstituteString (char **, const char *, const char *)
MagickExport size_t ConcatenateMagickString (char *magick_restrict, const char *magick_restrict, const size_t) magick_attribute((__nonnull__))
MagickExport size_t CopyMagickString (char *magick_restrict, const char *magick_restrict, const size_t) magick_attribute((__nonnull__))
MagickExport size_t GetStringInfoLength (const StringInfo *)
MagickExport ssize_t FormatMagickSize (const MagickSizeType, const MagickBooleanType, char *)
MagickExport StringInfo * AcquireStringInfo (const size_t)
MagickExport StringInfo * BlobToStringInfo (const void *, const size_t)
MagickExport StringInfo * CloneStringInfo (const StringInfo *)
MagickExport StringInfo * ConfigureFileToStringInfo (const char *)
MagickExport StringInfo * DestroyStringInfo (StringInfo *)
MagickExport StringInfo * FileToStringInfo (const char *, const size_t, ExceptionInfo *)
MagickExport StringInfo * SplitStringInfo (StringInfo *, const size_t)
MagickExport StringInfo * StringToStringInfo (const char *)
MagickExport unsigned char * GetStringInfoDatum (const StringInfo *)
MagickExport void ConcatenateStringInfo (StringInfo *, const StringInfo *) magick_attribute((__nonnull__))
MagickExport void PrintStringInfo (FILE *file, const char *, const StringInfo *)
MagickExport void ResetStringInfo (StringInfo *)
MagickExport void SetStringInfo (StringInfo *, const StringInfo *)
MagickExport void SetStringInfoDatum (StringInfo *, const unsigned char *)
MagickExport void SetStringInfoLength (StringInfo *, const size_t)
MagickExport void SetStringInfoName (StringInfo *, const char *)
MagickExport void SetStringInfoPath (StringInfo *, const char *)
MagickExport void StripString (char *)
Typedef Documentation
StringInfo
typedef struct _StringInfo StringInfo
Function Documentation
AcquireString()
MagickExport char * AcquireString (const char *)
AcquireStringInfo()
MagickExport StringInfo * AcquireStringInfo (const size_t)
BlobToStringInfo()
MagickExport StringInfo * BlobToStringInfo (const void * , const size_t)
CloneString()
MagickExport char * CloneString (char ** , const char *)
CloneStringInfo()
MagickExport StringInfo * CloneStringInfo (const StringInfo *)
CompareStringInfo()
MagickExport int CompareStringInfo (const StringInfo * target, const StringInfo * source)
References _StringInfo::datum, _StringInfo::length, MagickCoreSignature, MagickMin, and _StringInfo::signature.
Referenced by CompareHashmapStringInfo(), CompareSplayTreeStringInfo(), and ProfileImage().
ConcatenateMagickString()
MagickExport size_t ConcatenateMagickString (char * magick_restrict, const char * magick_restrict, const size_t)
ConcatenateString()
MagickExport MagickBooleanType ConcatenateString (char ** magick_restrict, const char * magick_restrict)
ConcatenateStringInfo()
MagickExport void ConcatenateStringInfo (StringInfo * , const StringInfo *)
ConfigureFileToStringInfo()
MagickExport StringInfo * ConfigureFileToStringInfo (const char *)
ConstantString()
MagickExport char * ConstantString (const char *)
CopyMagickString()
MagickExport size_t CopyMagickString (char * magick_restrict, const char * magick_restrict, const size_t)
DestroyString()
MagickExport char * DestroyString (char *)
DestroyStringInfo()
MagickExport StringInfo * DestroyStringInfo (StringInfo *)
DestroyStringList()
MagickExport char ** DestroyStringList (char **)
EscapeString()
MagickExport char * EscapeString (const char * , const char)
FileToString()
MagickExport char * FileToString (const char * , const size_t, ExceptionInfo *)
FileToStringInfo()
MagickExport StringInfo * FileToStringInfo (const char * , const size_t, ExceptionInfo *)
FormatMagickSize()
MagickExport ssize_t FormatMagickSize (const MagickSizeType, const MagickBooleanType, char * format)
References FormatLocaleString(), GetMagickPrecision(), MagickFalse, and MaxTextExtent.
Referenced by AcquireMagickResource(), GetMagickProperty(), GetMagickPropertyLetter(), IdentifyImage(), ListMagickResourceInfo(), OpenPixelCache(), RelinquishMagickResource(), SetPixelCacheExtent(), and ThumbnailImage().
GetEnvironmentValue()
MagickExport char * GetEnvironmentValue (const char *)
GetStringInfoDatum()
MagickExport unsigned char * GetStringInfoDatum (const StringInfo * string_info)
References _StringInfo::datum, MagickCoreSignature, and _StringInfo::signature.
Referenced by AcquireCoderCache(), AcquireColorCache(), AcquireConfigureCache(), AcquireDelegateCache(), AcquireLocaleSplayTree(), AcquireMagicCache(), AcquireMimeCache(), AcquirePolicyCache(), AcquireRandomInfo(), AcquireTypeCache(), AcquireUniqueFileResource(), ConnectPixelCacheServer(), DistributePixelCacheClient(), FinalizeSignature(), GenerateEntropicChaos(), Get8BIMProperty(), GetEXIFProperty(), GetICCProperty(), GetIPTCProperty(), GetMagickCoreSignature(), GetMagickProperty(), GetProfilesFromResourceBlock(), GetRandomKey(), GetThresholdMap(), HashStringInfoType(), HashStringType(), IdentifyImage(), IncrementRandomNonce(), ListThresholdMaps(), ProfileImage(), ReadImage(), SetImageProfileInternal(), SetRandomKey(), ShredFile(), Sync8BimProfile(), SyncExifProfile(), TransformSignature(), UpdateSignature(), and WriteTo8BimProfile().
GetStringInfoLength()
MagickExport size_t GetStringInfoLength (const StringInfo * string_info)
References _StringInfo::length, MagickCoreSignature, and _StringInfo::signature.
Referenced by AcquireUniqueFileResource(), FinalizeSignature(), Get8BIMProperty(), GetEXIFProperty(), GetICCProperty(), GetIPTCProperty(), GetMagickCoreSignature(), GetMagickProperty(), GetProfilesFromResourceBlock(), GetXMPProperty(), IdentifyImage(), IncrementRandomNonce(), ProfileImage(), ReadImage(), SetImageProfileInternal(), Sync8BimProfile(), SyncExifProfile(), UpdateSignature(), and WriteTo8BimProfile().
GetStringInfoName()
MagickExport const char * GetStringInfoName (const StringInfo *)
GetStringInfoPath()
MagickExport const char * GetStringInfoPath (const StringInfo * string_info)
References MagickCoreSignature, _StringInfo::path, and _StringInfo::signature.
Referenced by AcquireCoderCache(), AcquireColorCache(), AcquireConfigureCache(), AcquireDelegateCache(), AcquireLocaleSplayTree(), AcquireMagicCache(), AcquireMimeCache(), AcquirePolicyCache(), AcquireTypeCache(), GetThresholdMap(), and ListThresholdMaps().
InterpretSiPrefixValue()
MagickExport double InterpretSiPrefixValue (const char * magick_restrict, char ** magick_restrict)
IsStringNotFalse()
MagickExport MagickBooleanType IsStringNotFalse (const char *)
IsStringTrue()
MagickExport MagickBooleanType IsStringTrue (const char *)
PrintStringInfo()
MagickExport void PrintStringInfo (FILE * file, const char * , const StringInfo *)
ResetStringInfo()
MagickExport void ResetStringInfo (StringInfo *)
SanitizeString()
MagickExport char * SanitizeString (const char *)
SetStringInfo()
MagickExport void SetStringInfo (StringInfo * , const StringInfo *)
SetStringInfoDatum()
MagickExport void SetStringInfoDatum (StringInfo * , const unsigned char *)
SetStringInfoLength()
MagickExport void SetStringInfoLength (StringInfo * , const size_t)
SetStringInfoName()
MagickExport void SetStringInfoName (StringInfo * , const char *)
SetStringInfoPath()
MagickExport void SetStringInfoPath (StringInfo * , const char *)
SplitStringInfo()
MagickExport StringInfo * SplitStringInfo (StringInfo * , const size_t)
StringInfoToHexString()
MagickExport char * StringInfoToHexString (const StringInfo *)
StringInfoToString()
MagickExport char * StringInfoToString (const StringInfo *)
StringToArgv()
MagickExport char ** StringToArgv (const char * , int *)
StringToArrayOfDoubles()
MagickExport double * StringToArrayOfDoubles (const char * string, ssize_t * count, ExceptionInfo * exception)
References AcquireQuantumMemory(), GetMagickModule, MagickCoreSignature, ResourceLimitError, _ExceptionInfo::signature, StringToDouble(), and ThrowMagickException().
StringToken()
MagickExport char * StringToken (const char * , char **)
StringToList()
MagickExport char ** StringToList (const char *)
StringToStringInfo()
MagickExport StringInfo * StringToStringInfo (const char * string)
References AcquireStringInfo(), and SetStringInfoDatum().
Referenced by GenerateEntropicChaos(), and HashStringType().
StringToStrings()
MagickExport char ** StringToStrings (const char * text, size_t * count)
References AcquireQuantumMemory(), CharsPerLine, CopyMagickString(), FormatLocaleString(), MagickMin, MagickPathExtent, ResizeQuantumMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by GetMultilineTypeMetrics(), and StringToList().
StripString()
MagickExport void StripString (char * message)
Referenced by FxGetSymbol(), and ListDelegateInfo().
SubstituteString()
MagickExport MagickBooleanType SubstituteString (char ** string, const char * search, const char * replace)
References MagickFalse, MagickTrue, MaxTextExtent, ResizeQuantumMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by AcquireFxInfo(), GetEXIFProperty(), GetHostname(), GetXMPProperty(), IsOptionMember(), LoadDelegateCache(), LoadMimeCache(), QueryMagickColorCompliance(), and SetTypeNodePath().