MagickCore: _ResizeFilter Struct Reference
_ResizeFilter Struct Reference
Data Fields
MagickRealType(* filter)(const MagickRealType, const ResizeFilter *)
MagickRealType(*)(*) window (const MagickRealType, const ResizeFilter *)
MagickRealType(*)(*) support
MagickRealType(*)(*) window_support
MagickRealType(*)(*) scale
MagickRealType(*)(*) blur
MagickRealType(*)(*) coefficient [7]
ResizeWeightingFunctionType filterWeightingType
ResizeWeightingFunctionType windowWeightingType
size_t signature
Field Documentation
blur
MagickRealType(*)(*) _ResizeFilter::blur
Referenced by AcquireResizeFilter(), GetResizeFilterBlur(), GetResizeFilterSupport(), and GetResizeFilterWeight().
coefficient
MagickRealType(*)(*) _ResizeFilter::coefficient[7]
Referenced by AcquireResizeFilter(), CubicBC(), Gaussian(), GetResizeFilterCoefficient(), and Kaiser().
filter
MagickRealType(* _ResizeFilter::filter) (const MagickRealType, const ResizeFilter *)
Referenced by AcquireResizeFilter(), and GetResizeFilterWeight().
filterWeightingType
ResizeWeightingFunctionType _ResizeFilter::filterWeightingType
Referenced by AcquireResizeFilter(), and GetResizeFilterWeightingType().
scale
MagickRealType(*)(*) _ResizeFilter::scale
Referenced by AcquireResizeFilter(), GetResizeFilterScale(), and GetResizeFilterWeight().
signature
size_t _ResizeFilter::signature
Referenced by AcquireResizeFilter(), DestroyResizeFilter(), GetResizeFilterBlur(), GetResizeFilterCoefficient(), GetResizeFilterScale(), GetResizeFilterSupport(), GetResizeFilterWeight(), GetResizeFilterWeightingType(), GetResizeFilterWindowSupport(), and GetResizeFilterWindowWeightingType().
support
MagickRealType(*)(*) _ResizeFilter::support
Referenced by AcquireResizeFilter(), GetResizeFilterSupport(), and Lagrange().
window
MagickRealType(*)(*) _ResizeFilter::window(const MagickRealType, const ResizeFilter *)
Referenced by AcquireResizeFilter(), and GetResizeFilterWeight().
window_support
MagickRealType(*)(*) _ResizeFilter::window_support
Referenced by AcquireResizeFilter(), GetResizeFilterWeight(), GetResizeFilterWindowSupport(), and Lagrange().
windowWeightingType
ResizeWeightingFunctionType _ResizeFilter::windowWeightingType
Referenced by AcquireResizeFilter(), and GetResizeFilterWindowWeightingType().
The documentation for this struct was generated from the following file:
resize.c