MagickCore: thread.c File Reference
thread.c File Reference
#include "magick/studio.h"
#include "magick/memory_.h"
#include "magick/thread_.h"
#include "magick/thread-private.h"
Data Structures
struct _MagickThreadValue
Typedefs
typedef struct _MagickThreadValue MagickThreadValue
Functions
MagickExport MagickBooleanType MagickCreateThreadKey (MagickThreadKey *key)
MagickExport MagickBooleanType MagickDeleteThreadKey (MagickThreadKey key)
MagickExport void * MagickGetThreadValue (MagickThreadKey key)
MagickExport MagickBooleanType MagickSetThreadValue (MagickThreadKey key, const void *value)
MagickExport MagickBooleanType CreateMagickThreadKey (MagickThreadKey *key, void(*destructor)(void *))
MagickExport MagickBooleanType DeleteMagickThreadKey (MagickThreadKey key)
MagickExport void * GetMagickThreadValue (MagickThreadKey key)
MagickExport MagickBooleanType SetMagickThreadValue (MagickThreadKey key, const void *value)
Typedef Documentation
MagickThreadValue
typedef struct _MagickThreadValue MagickThreadValue
Function Documentation
CreateMagickThreadKey()
MagickExport MagickBooleanType CreateMagickThreadKey (MagickThreadKey * key, void(*)(void *) destructor)
References AcquireMagickMemory(), AcquireQuantumMemory(), GetOpenMPMaximumThreads(), magick_unreferenced, MagickFalse, MagickTrue, pthread_key_create, and RelinquishMagickMemory().
DeleteMagickThreadKey()
MagickExport MagickBooleanType DeleteMagickThreadKey (MagickThreadKey key)
References _MagickThreadValue::destructor, MagickFalse, MagickTrue, _MagickThreadValue::number_threads, pthread_key_delete, RelinquishMagickMemory(), and _MagickThreadValue::values.
GetMagickThreadValue()
MagickExport void * GetMagickThreadValue (MagickThreadKey key)
References GetOpenMPThreadId(), pthread_getspecific, and _MagickThreadValue::values.
MagickCreateThreadKey()
MagickExport MagickBooleanType MagickCreateThreadKey (MagickThreadKey * key)
References AcquireMagickMemory(), MagickFalse, MagickTrue, and pthread_key_create.
MagickDeleteThreadKey()
MagickExport MagickBooleanType MagickDeleteThreadKey (MagickThreadKey key)
References MagickFalse, MagickTrue, pthread_key_delete, and RelinquishMagickMemory().
MagickGetThreadValue()
MagickExport void * MagickGetThreadValue (MagickThreadKey key)
References pthread_getspecific.
MagickSetThreadValue()
MagickExport MagickBooleanType MagickSetThreadValue (MagickThreadKey key, const void * value)
References MagickFalse, MagickTrue, and pthread_setspecific.
SetMagickThreadValue()
MagickExport MagickBooleanType SetMagickThreadValue (MagickThreadKey key, const void * value)
References GetOpenMPThreadId(), MagickFalse, MagickTrue, pthread_setspecific, and _MagickThreadValue::values.