MagickCore: threshold.c File Reference
threshold.c File Reference
#include "magick/studio.h"
#include "magick/artifact.h"
#include "magick/blob.h"
#include "magick/cache-view.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colormap.h"
#include "magick/colorspace.h"
#include "magick/colorspace-private.h"
#include "magick/configure.h"
#include "magick/constitute.h"
#include "magick/decorate.h"
#include "magick/draw.h"
#include "magick/enhance.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/effect.h"
#include "magick/fx.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/log.h"
#include "magick/memory_.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/montage.h"
#include "magick/option.h"
#include "magick/pixel-private.h"
#include "magick/property.h"
#include "magick/quantize.h"
#include "magick/quantum.h"
#include "magick/random_.h"
#include "magick/random-private.h"
#include "magick/resize.h"
#include "magick/resource_.h"
#include "magick/segment.h"
#include "magick/shear.h"
#include "magick/signature-private.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/thread-private.h"
#include "magick/threshold.h"
#include "magick/transform.h"
#include "magick/xml-tree.h"
Data Structures
struct _ThresholdMap
Macros
#define ThresholdsFilename "thresholds.xml"
#define ThresholdImageTag "Threshold/Image"
#define MaxIntensity 255
#define ThresholdImageTag "Threshold/Image"
#define ThresholdImageTag "Threshold/Image"
#define ClampImageTag "Clamp/Image"
#define DitherImageTag "Dither/Image"
#define PerceptibleImageTag "Perceptible/Image"
#define ThresholdImageTag "Threshold/Image"
#define ThresholdImageTag "Threshold/Image"
Functions
MagickExport Image * AdaptiveThresholdImage (const Image *image, const size_t width, const size_t height, const ssize_t offset, ExceptionInfo *exception)
static double KapurThreshold (const Image *image, const double *histogram, ExceptionInfo *exception)
static double OTSUThreshold (const Image *image, const double *histogram, ExceptionInfo *exception)
static double TriangleThreshold (const Image *image, const double *histogram)
MagickExport MagickBooleanType AutoThresholdImage (Image *image, const AutoThresholdMethod method, ExceptionInfo *exception)
MagickExport MagickBooleanType BilevelImage (Image *image, const double threshold)
MagickExport MagickBooleanType BilevelImageChannel (Image *image, const ChannelType channel, const double threshold)
MagickExport MagickBooleanType BlackThresholdImage (Image *image, const char *threshold)
MagickExport MagickBooleanType BlackThresholdImageChannel (Image *image, const ChannelType channel, const char *thresholds, ExceptionInfo *exception)
MagickExport MagickBooleanType ClampImage (Image *image)
MagickExport MagickBooleanType ClampImageChannel (Image *image, const ChannelType channel)
MagickExport ThresholdMap * DestroyThresholdMap (ThresholdMap *map)
MagickExport ThresholdMap * GetThresholdMapFile (const char *xml, const char *filename, const char *map_id, ExceptionInfo *exception)
MagickExport ThresholdMap * GetThresholdMap (const char *map_id, ExceptionInfo *exception)
MagickBooleanType ListThresholdMapFile (FILE *file, const char *xml, const char *filename, ExceptionInfo *exception)
MagickExport MagickBooleanType ListThresholdMaps (FILE *file, ExceptionInfo *exception)
MagickExport MagickBooleanType OrderedDitherImage (Image *image)
MagickExport MagickBooleanType OrderedDitherImageChannel (Image *image, const ChannelType channel, ExceptionInfo *exception)
MagickExport MagickBooleanType OrderedPosterizeImage (Image *image, const char *threshold_map, ExceptionInfo *exception)
MagickExport MagickBooleanType OrderedPosterizeImageChannel (Image *image, const ChannelType channel, const char *threshold_map, ExceptionInfo *exception)
static Quantum PerceptibleThreshold (const Quantum quantum, const double epsilon)
MagickExport MagickBooleanType PerceptibleImage (Image *image, const double epsilon)
MagickExport MagickBooleanType PerceptibleImageChannel (Image *image, const ChannelType channel, const double epsilon)
MagickExport MagickBooleanType RandomThresholdImage (Image *image, const char *thresholds, ExceptionInfo *exception)
MagickExport MagickBooleanType RandomThresholdImageChannel (Image *image, const ChannelType channel, const char *thresholds, ExceptionInfo *exception)
MagickExport MagickBooleanType WhiteThresholdImage (Image *image, const char *threshold)
MagickExport MagickBooleanType WhiteThresholdImageChannel (Image *image, const ChannelType channel, const char *thresholds, ExceptionInfo *exception)
Variables
static const char * MinimalThresholdMap
Macro Definition Documentation
ClampImageTag
#define ClampImageTag "Clamp/Image"
DitherImageTag
#define DitherImageTag "Dither/Image"
MaxIntensity
#define MaxIntensity 255
PerceptibleImageTag
#define PerceptibleImageTag "Perceptible/Image"
ThresholdImageTag [1/5]
#define ThresholdImageTag "Threshold/Image"
ThresholdImageTag [2/5]
#define ThresholdImageTag "Threshold/Image"
ThresholdImageTag [3/5]
#define ThresholdImageTag "Threshold/Image"
ThresholdImageTag [4/5]
#define ThresholdImageTag "Threshold/Image"
ThresholdImageTag [5/5]
#define ThresholdImageTag "Threshold/Image"
ThresholdsFilename
#define ThresholdsFilename "thresholds.xml"
Function Documentation
AdaptiveThresholdImage()
MagickExport Image * AdaptiveThresholdImage (const Image * image, const size_t width, const size_t height, const ssize_t offset, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _MagickPixelPacket::green, _MagickPixelPacket::index, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _MagickPixelPacket::opacity, _Image::progress_monitor, QuantumRange, _MagickPixelPacket::red, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThresholdImageTag, and TraceEvent.
AutoThresholdImage()
MagickExport MagickBooleanType AutoThresholdImage (Image * image, const AutoThresholdMethod method, ExceptionInfo * exception)
References AcquireQuantumMemory(), AcquireVirtualCacheView(), BilevelImage(), ClampToQuantum(), _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, FormatLocaleFile(), FormatLocaleString(), GetCacheViewVirtualPixels(), GetImageArtifact(), GetMagickModule, GetMagickPrecision(), GetPixelIntensity(), IsStringTrue(), KapurThreshold(), KapurThresholdMethod, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickPathExtent, MagickTrue, MaxIntensity, OTSUThreshold(), OTSUThresholdMethod, PerceptibleReciprocal(), QuantumRange, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageProperty(), _Image::signature, ThrowBinaryException, TraceEvent, TriangleThreshold(), and TriangleThresholdMethod.
BilevelImage()
MagickExport MagickBooleanType BilevelImage (Image * image, const double threshold)
References BilevelImageChannel(), and DefaultChannels.
Referenced by AutoThresholdImage(), and PreviewImage().
BilevelImageChannel()
MagickExport MagickBooleanType BilevelImageChannel (Image * image, const ChannelType channel, const double threshold)
References AcquireAuthenticCacheView(), BlueChannel, CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelAlpha, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetPixelRed, GreenChannel, IndexChannel, IsGrayColorspace(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, OpacityChannel, OpaqueOpacity, _Image::progress_monitor, QuantumRange, RedChannel, _Image::rows, SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), SyncChannels, ThresholdImageTag, TraceEvent, and TransparentOpacity.
Referenced by BilevelImage(), ChannelThresholdImage(), and SetImageType().
BlackThresholdImage()
MagickExport MagickBooleanType BlackThresholdImage (Image * image, const char * threshold)
References BlackThresholdImageChannel(), DefaultChannels, and _Image::exception.
BlackThresholdImageChannel()
MagickExport MagickBooleanType BlackThresholdImageChannel (Image * image, const ChannelType channel, const char * thresholds, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), _MagickPixelPacket::blue, BlueChannel, _GeometryInfo::chi, ChiValue, CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickPixelPacket(), GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, IsGrayColorspace(), IsMagickGray(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _MagickPixelPacket::opacity, OpacityChannel, ParseGeometry(), PercentValue, _Image::progress_monitor, _GeometryInfo::psi, PsiValue, QuantumRange, _MagickPixelPacket::red, RedChannel, _GeometryInfo::rho, _Image::rows, SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _GeometryInfo::sigma, SigmaValue, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), ThresholdImageTag, TraceEvent, _GeometryInfo::xi, and XiValue.
Referenced by BlackThresholdImage().
ClampImage()
MagickExport MagickBooleanType ClampImage (Image * image)
References ClampImageChannel(), and DefaultChannels.
Referenced by CharcoalImage(), LevelImageChannel(), and SketchImage().
ClampImageChannel()
MagickExport MagickBooleanType ClampImageChannel (Image * image, const ChannelType channel)
References AcquireAuthenticCacheView(), BlueChannel, ClampImageTag, ClampPixel(), CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, GreenChannel, IndexChannel, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, OpacityChannel, _Image::progress_monitor, PseudoClass, RedChannel, _Image::rows, SetImageProgress(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), SyncImage(), and TraceEvent.
Referenced by ClampImage().
DestroyThresholdMap()
MagickExport ThresholdMap * DestroyThresholdMap (ThresholdMap * map)
References _ThresholdMap::description, DestroyString(), _ThresholdMap::levels, _ThresholdMap::map_id, and RelinquishMagickMemory().
Referenced by GetThresholdMapFile(), and OrderedPosterizeImageChannel().
GetThresholdMap()
MagickExport ThresholdMap * GetThresholdMap (const char * map_id, ExceptionInfo * exception)
References DestroyConfigureOptions(), GetConfigureOptions(), GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), GetThresholdMapFile(), MinimalThresholdMap, and ThresholdsFilename.
Referenced by OrderedPosterizeImageChannel().
GetThresholdMapFile()
MagickExport ThresholdMap * GetThresholdMapFile (const char * xml, const char * filename, const char * map_id, ExceptionInfo * exception)
References AcquireMagickMemory(), AcquireQuantumMemory(), ConfigureEvent, ConstantString(), _ThresholdMap::description, DestroyThresholdMap(), DestroyXMLTree(), _ThresholdMap::divisor, GetMagickModule, GetNextXMLTreeTag(), GetXMLTreeAttribute(), GetXMLTreeChild(), GetXMLTreeContent(), _ThresholdMap::height, _ThresholdMap::levels, LocaleCompare(), LogMagickEvent(), _ThresholdMap::map_id, NewXMLTree(), OptionError, ResourceLimitFatalError, StringToLong(), StringToUnsignedLong(), ThrowFatalException, ThrowMagickException(), and _ThresholdMap::width.
Referenced by GetThresholdMap().
KapurThreshold()
static double KapurThreshold (const Image * image, const double * histogram, ExceptionInfo * exception) static
References AcquireQuantumMemory(), _Image::filename, GetMagickModule, MagickMinimumValue, MaxIntensity, RelinquishMagickMemory(), ResourceLimitError, and ThrowMagickException().
Referenced by AutoThresholdImage().
ListThresholdMapFile()
MagickBooleanType ListThresholdMapFile (FILE * file, const char * xml, const char * filename, ExceptionInfo * exception)
References ConfigureEvent, DestroyXMLTree(), FormatLocaleFile(), GetMagickModule, GetNextXMLTreeTag(), GetXMLTreeAttribute(), GetXMLTreeChild(), GetXMLTreeContent(), LogMagickEvent(), MagickFalse, MagickTrue, NewXMLTree(), OptionError, and ThrowMagickException().
Referenced by ListThresholdMaps().
ListThresholdMaps()
MagickExport MagickBooleanType ListThresholdMaps (FILE * file, ExceptionInfo * exception)
References DestroyConfigureOptions(), FormatLocaleFile(), GetConfigureOptions(), GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), ListThresholdMapFile(), MagickFalse, MagickTrue, and ThresholdsFilename.
OrderedDitherImage()
MagickExport MagickBooleanType OrderedDitherImage (Image * image)
References DefaultChannels, _Image::exception, and OrderedDitherImageChannel().
OrderedDitherImageChannel()
MagickExport MagickBooleanType OrderedDitherImageChannel (Image * image, const ChannelType channel, ExceptionInfo * exception)
References OrderedPosterizeImageChannel().
Referenced by OrderedDitherImage().
OrderedPosterizeImage()
MagickExport MagickBooleanType OrderedPosterizeImage (Image * image, const char * threshold_map, ExceptionInfo * exception)
References DefaultChannels, and OrderedPosterizeImageChannel().
OrderedPosterizeImageChannel()
MagickExport MagickBooleanType OrderedPosterizeImageChannel (Image * image, const ChannelType channel, const char * threshold_map, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), _LongPixelPacket::blue, BlueChannel, ClampToQuantum(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyThresholdMap(), DirectClass, DitherImageTag, _ThresholdMap::divisor, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, GetThresholdMap(), _LongPixelPacket::green, GreenChannel, _ThresholdMap::height, _LongPixelPacket::index, IndexChannel, InheritException(), _ThresholdMap::levels, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, MaxTextExtent, _LongPixelPacket::opacity, OpacityChannel, OptionError, _Image::progress_monitor, QuantumRange, QuantumScale, _LongPixelPacket::red, RedChannel, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowMagickException(), TraceEvent, and _ThresholdMap::width.
Referenced by OrderedDitherImageChannel(), OrderedPosterizeImage(), and RandomThresholdImageChannel().
OTSUThreshold()
static double OTSUThreshold (const Image * image, const double * histogram, ExceptionInfo * exception) static
References AcquireQuantumMemory(), _Image::filename, GetMagickModule, MaxIntensity, RelinquishMagickMemory(), ResourceLimitError, and ThrowMagickException().
Referenced by AutoThresholdImage().
PerceptibleImage()
MagickExport MagickBooleanType PerceptibleImage (Image * image, const double epsilon)
References DefaultChannels, and PerceptibleImageChannel().
PerceptibleImageChannel()
MagickExport MagickBooleanType PerceptibleImageChannel (Image * image, const ChannelType channel, const double epsilon)
References AcquireAuthenticCacheView(), BlueChannel, CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, GreenChannel, IndexChannel, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, OpacityChannel, PerceptibleImageTag, PerceptibleThreshold(), _Image::progress_monitor, PseudoClass, RedChannel, _Image::rows, SetImageProgress(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _Image::signature, _Image::storage_class, SyncCacheViewAuthenticPixels(), SyncImage(), and TraceEvent.
Referenced by PerceptibleImage().
PerceptibleThreshold()
static Quantum PerceptibleThreshold (const Quantum quantum, const double epsilon) inline static
Referenced by PerceptibleImageChannel().
RandomThresholdImage()
MagickExport MagickBooleanType RandomThresholdImage (Image * image, const char * thresholds, ExceptionInfo * exception)
References DefaultChannels, and RandomThresholdImageChannel().
RandomThresholdImageChannel()
MagickExport MagickBooleanType RandomThresholdImageChannel (Image * image, const ChannelType channel, const char * thresholds, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireImageColormap(), AcquireRandomInfoThreadSet(), _MagickPixelPacket::blue, BlueChannel, CMYKColorspace, _Image::colormap, _Image::colorspace, _Image::columns, CompositeChannels, _Image::debug, DestroyCacheView(), DestroyRandomInfoThreadSet(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickPixelPacket(), GetOpenMPThreadId(), GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelIntensity(), GetPixelOpacity, GetPixelRed, GetPseudoRandomValue(), GetRandomSecretKey(), _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _MagickPixelPacket::opacity, OpacityChannel, OrderedPosterizeImageChannel(), ParseGeometry(), _Image::progress_monitor, QuantumRange, random_info, _MagickPixelPacket::red, RedChannel, ResourceLimitError, _GeometryInfo::rho, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, SetPixelRGBO, _GeometryInfo::sigma, SigmaValue, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThresholdImageTag, ThrowBinaryException, and TraceEvent.
Referenced by RandomThresholdImage().
TriangleThreshold()
static double TriangleThreshold (const Image * image, const double * histogram) static
References magick_unreferenced, and MaxIntensity.
Referenced by AutoThresholdImage().
WhiteThresholdImage()
MagickExport MagickBooleanType WhiteThresholdImage (Image * image, const char * threshold)
References DefaultChannels, _Image::exception, and WhiteThresholdImageChannel().
WhiteThresholdImageChannel()
MagickExport MagickBooleanType WhiteThresholdImageChannel (Image * image, const ChannelType channel, const char * thresholds, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), _MagickPixelPacket::blue, BlueChannel, _GeometryInfo::chi, ChiValue, CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickPixelPacket(), GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, IsGrayColorspace(), IsMagickGray(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _MagickPixelPacket::opacity, OpacityChannel, ParseGeometry(), PercentValue, _Image::progress_monitor, _GeometryInfo::psi, PsiValue, QuantumRange, _MagickPixelPacket::red, RedChannel, _GeometryInfo::rho, _Image::rows, SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _GeometryInfo::sigma, SigmaValue, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), ThresholdImageTag, TraceEvent, _GeometryInfo::xi, and XiValue.
Referenced by WhiteThresholdImage().
Variable Documentation
MinimalThresholdMap
const char* MinimalThresholdMap static
Initial value:
=
    "<?xml version=\"1.0\"?>"
    "<thresholds>"
    "  <threshold map=\"threshold\" alias=\"1x1\">"
    "    <description>Threshold 1x1 (non-dither)</description>"
    "    <levels width=\"1\" height=\"1\" divisor=\"2\">"
    "        1"
    "    </levels>"
    "  </threshold>"
    "  <threshold map=\"checks\" alias=\"2x1\">"
    "    <description>Checkerboard 2x1 (dither)</description>"
    "    <levels width=\"2\" height=\"2\" divisor=\"3\">"
    "       1 2"
    "       2 1"
    "    </levels>"
    "  </threshold>"
    "</thresholds>"
Referenced by GetThresholdMap().