MagickCore: thread-private.h File Reference
thread-private.h File Reference
#include "magick/cache.h"
#include "magick/image-private.h"
#include "magick/resource_.h"
#include "magick/thread_.h"
Macros
#define magick_number_threads(source, destination, chunk, multithreaded)
#define MagickCachePrefetch(address, mode, locality)
Typedefs
typedef size_t MagickMutexType
Functions
static MagickThreadType GetMagickThreadId (void)
static size_t GetMagickThreadSignature (void)
static MagickBooleanType IsMagickThreadEqual (const MagickThreadType id)
static size_t GetOpenMPMaximumThreads (void)
static int GetOpenMPThreadId (void)
static void SetOpenMPMaximumThreads (const int threads)
static void SetOpenMPNested (const int value)
Macro Definition Documentation
magick_number_threads
#define magick_number_threads (source, destination, chunk, multithreaded)
Value:
  num_threads((multithreaded) == 0 ? 1 : \
    ((GetImagePixelCacheType(source) != MemoryCache) && \
     (GetImagePixelCacheType(source) != MapCache)) || \
    ((GetImagePixelCacheType(destination) != MemoryCache) && \
     (GetImagePixelCacheType(destination) != MapCache)) ? \
    MagickMax(MagickMin(GetMagickResourceLimit(ThreadResource),2),1) : \
    MagickMax(MagickMin((ssize_t) GetMagickResourceLimit(ThreadResource),(ssize_t) (chunk)/64),1))
MagickCachePrefetch
#define MagickCachePrefetch (address, mode, locality)
Typedef Documentation
MagickMutexType
typedef size_t MagickMutexType
Function Documentation
GetMagickThreadId()
static MagickThreadType GetMagickThreadId (void) inline static
References pthread_self.
Referenced by AcquirePixelCache(), AllocateSemaphoreInfo(), GenerateEntropicChaos(), and LockSemaphoreInfo().
GetMagickThreadSignature()
static size_t GetMagickThreadSignature (void) inline static
References pthread_self.
Referenced by TranslateEvent().
GetOpenMPMaximumThreads()
static size_t GetOpenMPMaximumThreads (void) inline static
Referenced by AcquirePixelCache(), AcquireVirtualCacheView(), CreateMagickThreadKey(), LocalContrastImage(), MorphologyPrimitive(), ResourceComponentGenesis(), SetMagickResourceLimit(), and WaveletDenoiseImage().
GetOpenMPThreadId()
static int GetOpenMPThreadId (void) inline static
Referenced by AddNoiseImageChannel(), ClonePixelCacheRepository(), DistortImage(), DrawPolygonPrimitive(), DuplexTransferImageViewIterator(), EvaluateImageChannel(), EvaluateImages(), FloydSteinbergDither(), FxImageChannel(), GetAuthenticIndexesFromCache(), GetAuthenticIndexQueue(), GetAuthenticPixelQueue(), GetAuthenticPixels(), GetAuthenticPixelsCache(), GetAuthenticPixelsFromCache(), GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixelQueue(), GetCacheViewAuthenticPixels(), GetCacheViewExtent(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixelQueue(), GetCacheViewVirtualPixels(), GetImageChannelDepth(), GetImageExtent(), GetImageViewIterator(), GetMagickThreadValue(), GetOneAuthenticPixelFromCache(), GetOneCacheViewAuthenticPixel(), GetOneCacheViewVirtualMethodPixel(), GetOneCacheViewVirtualPixel(), GetOneVirtualMagickPixel(), GetOneVirtualMethodPixel(), GetOneVirtualPixel(), GetOneVirtualPixelFromCache(), GetQuantumPixels(), GetVirtualIndexesFromCache(), GetVirtualIndexQueue(), GetVirtualPixelCache(), GetVirtualPixelQueue(), GetVirtualPixels(), GetVirtualPixelsCache(), HorizontalFilter(), LocalContrastImage(), MorphologyPrimitive(), OilPaintImage(), PolynomialImageChannel(), ProfileImage(), QueueAuthenticPixels(), QueueAuthenticPixelsCache(), QueueCacheViewAuthenticPixels(), RandomThresholdImageChannel(), SetImageViewIterator(), SetMagickThreadValue(), SketchImage(), SpreadImage(), StatisticImageChannel(), SyncAuthenticPixels(), SyncAuthenticPixelsCache(), SyncCacheViewAuthenticPixels(), TransferImageViewIterator(), UpdateImageViewIterator(), VerticalFilter(), and WaveletDenoiseImage().
IsMagickThreadEqual()
static MagickBooleanType IsMagickThreadEqual (const MagickThreadType id) inline static
References MagickFalse, MagickTrue, pthread_equal, and pthread_self.
Referenced by LockSemaphoreInfo(), and UnlockSemaphoreInfo().
SetOpenMPMaximumThreads()
static void SetOpenMPMaximumThreads (const int threads) inline static
SetOpenMPNested()
static void SetOpenMPNested (const int value) inline static