MagickCore: threshold.h File Reference
threshold.h File Reference
Typedefs
typedef struct _ThresholdMap ThresholdMap
Enumerations
enum AutoThresholdMethod { UndefinedThresholdMethod , KapurThresholdMethod , OTSUThresholdMethod , TriangleThresholdMethod }
Functions
MagickExport Image * AdaptiveThresholdImage (const Image *, const size_t, const size_t, const ssize_t, ExceptionInfo *)
MagickExport ThresholdMap * DestroyThresholdMap (ThresholdMap *)
MagickExport ThresholdMap * GetThresholdMap (const char *, ExceptionInfo *)
MagickExport MagickBooleanType AutoThresholdImage (Image *, const AutoThresholdMethod, ExceptionInfo *)
MagickExport MagickBooleanType BilevelImage (Image *, const double)
MagickExport MagickBooleanType BilevelImageChannel (Image *, const ChannelType, const double)
MagickExport MagickBooleanType BlackThresholdImage (Image *, const char *)
MagickExport MagickBooleanType BlackThresholdImageChannel (Image *, const ChannelType, const char *, ExceptionInfo *)
MagickExport MagickBooleanType ClampImage (Image *)
MagickExport MagickBooleanType ClampImageChannel (Image *, const ChannelType)
MagickExport MagickBooleanType ListThresholdMaps (FILE *, ExceptionInfo *)
MagickExport MagickBooleanType OrderedDitherImage (Image *)
MagickExport MagickBooleanType OrderedDitherImageChannel (Image *, const ChannelType, ExceptionInfo *)
MagickExport MagickBooleanType OrderedPosterizeImage (Image *, const char *, ExceptionInfo *)
MagickExport MagickBooleanType OrderedPosterizeImageChannel (Image *, const ChannelType, const char *, ExceptionInfo *)
MagickExport MagickBooleanType PerceptibleImage (Image *, const double)
MagickExport MagickBooleanType PerceptibleImageChannel (Image *, const ChannelType, const double)
MagickExport MagickBooleanType RandomThresholdImage (Image *, const char *, ExceptionInfo *)
MagickExport MagickBooleanType RandomThresholdImageChannel (Image *, const ChannelType, const char *, ExceptionInfo *)
MagickExport MagickBooleanType WhiteThresholdImage (Image *, const char *)
MagickExport MagickBooleanType WhiteThresholdImageChannel (Image *, const ChannelType, const char *, ExceptionInfo *)
Typedef Documentation
ThresholdMap
typedef struct _ThresholdMap ThresholdMap
Enumeration Type Documentation
AutoThresholdMethod
enum AutoThresholdMethod
Enumerator
UndefinedThresholdMethod
KapurThresholdMethod
OTSUThresholdMethod
TriangleThresholdMethod
Function Documentation
AdaptiveThresholdImage()
MagickExport Image * AdaptiveThresholdImage (const Image * image, const size_t, const size_t, const ssize_t, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetMagickPixelPacket(), GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _MagickPixelPacket::green, _MagickPixelPacket::index, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _MagickPixelPacket::opacity, _Image::progress_monitor, QuantumRange, _MagickPixelPacket::red, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThresholdImageTag, and TraceEvent.
AutoThresholdImage()
MagickExport MagickBooleanType AutoThresholdImage (Image * , const AutoThresholdMethod, ExceptionInfo *)
BilevelImage()
MagickExport MagickBooleanType BilevelImage (Image * , const double)
BilevelImageChannel()
MagickExport MagickBooleanType BilevelImageChannel (Image * , const ChannelType, const double)
BlackThresholdImage()
MagickExport MagickBooleanType BlackThresholdImage (Image * , const char *)
BlackThresholdImageChannel()
MagickExport MagickBooleanType BlackThresholdImageChannel (Image * , const ChannelType, const char * , ExceptionInfo *)
ClampImage()
MagickExport MagickBooleanType ClampImage (Image *)
ClampImageChannel()
MagickExport MagickBooleanType ClampImageChannel (Image * , const ChannelType)
DestroyThresholdMap()
MagickExport ThresholdMap * DestroyThresholdMap (ThresholdMap *)
GetThresholdMap()
MagickExport ThresholdMap * GetThresholdMap (const char * map_id, ExceptionInfo * exception)
References DestroyConfigureOptions(), GetConfigureOptions(), GetNextValueInLinkedList(), GetStringInfoDatum(), GetStringInfoPath(), GetThresholdMapFile(), MinimalThresholdMap, and ThresholdsFilename.
Referenced by OrderedPosterizeImageChannel().
ListThresholdMaps()
MagickExport MagickBooleanType ListThresholdMaps (FILE * , ExceptionInfo *)
OrderedDitherImage()
MagickExport MagickBooleanType OrderedDitherImage (Image *)
OrderedDitherImageChannel()
MagickExport MagickBooleanType OrderedDitherImageChannel (Image * , const ChannelType, ExceptionInfo *)
OrderedPosterizeImage()
MagickExport MagickBooleanType OrderedPosterizeImage (Image * , const char * , ExceptionInfo *)
OrderedPosterizeImageChannel()
MagickExport MagickBooleanType OrderedPosterizeImageChannel (Image * , const ChannelType, const char * , ExceptionInfo *)
PerceptibleImage()
MagickExport MagickBooleanType PerceptibleImage (Image * , const double)
PerceptibleImageChannel()
MagickExport MagickBooleanType PerceptibleImageChannel (Image * , const ChannelType, const double)
RandomThresholdImage()
MagickExport MagickBooleanType RandomThresholdImage (Image * , const char * , ExceptionInfo *)
RandomThresholdImageChannel()
MagickExport MagickBooleanType RandomThresholdImageChannel (Image * , const ChannelType, const char * , ExceptionInfo *)
WhiteThresholdImage()
MagickExport MagickBooleanType WhiteThresholdImage (Image * , const char *)
WhiteThresholdImageChannel()
MagickExport MagickBooleanType WhiteThresholdImageChannel (Image * image, const ChannelType, const char * thresholds, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), _MagickPixelPacket::blue, BlueChannel, _GeometryInfo::chi, ChiValue, CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickPixelPacket(), GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _MagickPixelPacket::green, GreenChannel, _MagickPixelPacket::index, IndexChannel, IsGrayColorspace(), IsMagickGray(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _MagickPixelPacket::opacity, OpacityChannel, ParseGeometry(), PercentValue, _Image::progress_monitor, _GeometryInfo::psi, PsiValue, QuantumRange, _MagickPixelPacket::red, RedChannel, _GeometryInfo::rho, _Image::rows, SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _GeometryInfo::sigma, SigmaValue, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), ThresholdImageTag, TraceEvent, _GeometryInfo::xi, and XiValue.
Referenced by WhiteThresholdImage().