MagickCore: timer.h File Reference
timer.h File Reference
Data Structures
struct _Timer
struct _TimerInfo
Typedefs
typedef struct _Timer Timer
typedef struct _TimerInfo TimerInfo
Enumerations
enum TimerState { UndefinedTimerState , StoppedTimerState , RunningTimerState }
Functions
MagickExport double GetElapsedTime (TimerInfo *)
MagickExport double GetUserTime (TimerInfo *)
MagickExport MagickBooleanType ContinueTimer (TimerInfo *)
MagickExport ssize_t FormatMagickTime (const time_t, const size_t, char *)
MagickExport TimerInfo * AcquireTimerInfo (void)
MagickExport TimerInfo * DestroyTimerInfo (TimerInfo *)
MagickExport void GetTimerInfo (TimerInfo *)
MagickExport void ResetTimer (TimerInfo *)
MagickExport void StartTimer (TimerInfo *, const MagickBooleanType)
Typedef Documentation
Timer
typedef struct _Timer Timer
TimerInfo
typedef struct _TimerInfo TimerInfo
Enumeration Type Documentation
TimerState
enum TimerState
Enumerator
UndefinedTimerState
StoppedTimerState
RunningTimerState
Function Documentation
AcquireTimerInfo()
MagickExport TimerInfo * AcquireTimerInfo (void)
ContinueTimer()
MagickExport MagickBooleanType ContinueTimer (TimerInfo * time_info)
References _TimerInfo::elapsed, MagickCoreSignature, MagickFalse, MagickTrue, RunningTimerState, _TimerInfo::signature, _Timer::start, _TimerInfo::state, _Timer::stop, StoppedTimerState, _Timer::total, UndefinedTimerState, and _TimerInfo::user.
Referenced by LogMagickEventList().
DestroyTimerInfo()
MagickExport TimerInfo * DestroyTimerInfo (TimerInfo * timer_info)
References MagickCoreSignature, RelinquishMagickMemory(), and _TimerInfo::signature.
FormatMagickTime()
MagickExport ssize_t FormatMagickTime (const time_t, const size_t, char * timestamp)
References FormatLocaleString(), and GetMagickUTCtime().
Referenced by ReadImage(), and TranslateEvent().
GetElapsedTime()
MagickExport double GetElapsedTime (TimerInfo *)
GetTimerInfo()
MagickExport void GetTimerInfo (TimerInfo *)
GetUserTime()
MagickExport double GetUserTime (TimerInfo * time_info)
References MagickCoreSignature, RunningTimerState, _TimerInfo::signature, _TimerInfo::state, StopTimer(), _Timer::total, UndefinedTimerState, and _TimerInfo::user.
Referenced by IdentifyImage(), and TranslateEvent().
ResetTimer()
MagickExport void ResetTimer (TimerInfo *)
StartTimer()
MagickExport void StartTimer (TimerInfo * time_info, const MagickBooleanType)
References _TimerInfo::elapsed, ElapsedTime(), MagickCoreSignature, MagickFalse, RunningTimerState, _TimerInfo::signature, _Timer::start, _TimerInfo::state, _Timer::total, _TimerInfo::user, and UserTime().
Referenced by GetTimerInfo().