MagickCore: timer.c File Reference
timer.c File Reference
#include "magick/studio.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/locale_.h"
#include "magick/log.h"
#include "magick/memory_.h"
#include "magick/nt-base-private.h"
#include "magick/string-private.h"
#include "magick/timer.h"
#include "magick/timer-private.h"
Macros
#define CLOCKS_PER_SEC 100
Functions
static double UserTime (void)
static void StopTimer (TimerInfo *)
MagickExport TimerInfo * AcquireTimerInfo (void)
MagickExport MagickBooleanType ContinueTimer (TimerInfo *time_info)
MagickExport TimerInfo * DestroyTimerInfo (TimerInfo *timer_info)
static double ElapsedTime (void)
MagickExport ssize_t FormatMagickTime (const time_t time, const size_t length, char *timestamp)
MagickExport double GetElapsedTime (TimerInfo *time_info)
MagickExport time_t GetMagickTime (void)
MagickExport void GetTimerInfo (TimerInfo *time_info)
MagickExport double GetUserTime (TimerInfo *time_info)
MagickExport void ResetTimer (TimerInfo *time_info)
MagickExport void StartTimer (TimerInfo *time_info, const MagickBooleanType reset)
Macro Definition Documentation
CLOCKS_PER_SEC
#define CLOCKS_PER_SEC 100
Function Documentation
AcquireTimerInfo()
MagickExport TimerInfo * AcquireTimerInfo (void)
References AcquireMagickMemory(), GetTimerInfo(), MagickCoreSignature, ResourceLimitFatalError, _TimerInfo::signature, and ThrowFatalException.
ContinueTimer()
MagickExport MagickBooleanType ContinueTimer (TimerInfo * time_info)
References _TimerInfo::elapsed, MagickCoreSignature, MagickFalse, MagickTrue, RunningTimerState, _TimerInfo::signature, _Timer::start, _TimerInfo::state, _Timer::stop, StoppedTimerState, _Timer::total, UndefinedTimerState, and _TimerInfo::user.
Referenced by LogMagickEventList().
DestroyTimerInfo()
MagickExport TimerInfo * DestroyTimerInfo (TimerInfo * timer_info)
References MagickCoreSignature, RelinquishMagickMemory(), and _TimerInfo::signature.
ElapsedTime()
static double ElapsedTime (void) static
References CLOCKS_PER_SEC.
Referenced by StartTimer(), and StopTimer().
FormatMagickTime()
MagickExport ssize_t FormatMagickTime (const time_t time, const size_t length, char * timestamp)
References FormatLocaleString(), and GetMagickUTCtime().
Referenced by ReadImage(), and TranslateEvent().
GetElapsedTime()
MagickExport double GetElapsedTime (TimerInfo * time_info)
References _TimerInfo::elapsed, MagickCoreSignature, RunningTimerState, _TimerInfo::signature, _TimerInfo::state, StopTimer(), _Timer::total, and UndefinedTimerState.
Referenced by IdentifyImage(), and TranslateEvent().
GetMagickTime()
MagickExport time_t GetMagickTime (void)
References MagickFalse, MagickTrue, and StringToDouble().
Referenced by AcquireImage(), GetBlobInfo(), GetImagePixelCache(), and TranslateEvent().
GetTimerInfo()
MagickExport void GetTimerInfo (TimerInfo * time_info)
References MagickCoreSignature, MagickTrue, _TimerInfo::signature, StartTimer(), _TimerInfo::state, and UndefinedTimerState.
Referenced by AcquireImage(), AcquireTimerInfo(), CloneImage(), IdentifyImage(), and LoadLogCache().
GetUserTime()
MagickExport double GetUserTime (TimerInfo * time_info)
References MagickCoreSignature, RunningTimerState, _TimerInfo::signature, _TimerInfo::state, StopTimer(), _Timer::total, UndefinedTimerState, and _TimerInfo::user.
Referenced by IdentifyImage(), and TranslateEvent().
ResetTimer()
MagickExport void ResetTimer (TimerInfo * time_info)
References _TimerInfo::elapsed, MagickCoreSignature, _TimerInfo::signature, _Timer::stop, StopTimer(), and _TimerInfo::user.
Referenced by PingImage().
StartTimer()
MagickExport void StartTimer (TimerInfo * time_info, const MagickBooleanType reset)
References _TimerInfo::elapsed, ElapsedTime(), MagickCoreSignature, MagickFalse, RunningTimerState, _TimerInfo::signature, _Timer::start, _TimerInfo::state, _Timer::total, _TimerInfo::user, and UserTime().
Referenced by GetTimerInfo().
StopTimer()
static void StopTimer (TimerInfo * time_info) static
References _TimerInfo::elapsed, ElapsedTime(), MagickCoreSignature, MagickEpsilon, RunningTimerState, _TimerInfo::signature, _Timer::start, _TimerInfo::state, _Timer::stop, StoppedTimerState, _Timer::total, _TimerInfo::user, and UserTime().
Referenced by GetElapsedTime(), GetUserTime(), and ResetTimer().
UserTime()
static double UserTime (void) static
References CLOCKS_PER_SEC.
Referenced by StartTimer(), and StopTimer().