MagickCore: token-private.h File Reference
token-private.h File Reference
Data Structures
struct UTFInfo
Macros
#define EILSEQ ENOENT
#define MaxMultibyteCodes 6
Functions
static unsigned char * ConvertLatin1ToUTF8 (const unsigned char *magick_restrict content)
static int GetNextUTFCode (const char *magick_restrict text, unsigned int *magick_restrict octets)
static int GetUTFCode (const char *magick_restrict text)
static unsigned int GetUTFOctets (const char *magick_restrict text)
static MagickBooleanType IsUTFSpace (int code)
static MagickBooleanType IsUTFValid (int code)
static MagickBooleanType IsUTFAscii (int code)
Variables
static UTFInfo utf_info [MaxMultibyteCodes]
Macro Definition Documentation
EILSEQ
#define EILSEQ ENOENT
MaxMultibyteCodes
#define MaxMultibyteCodes 6
Function Documentation
ConvertLatin1ToUTF8()
static unsigned char * ConvertLatin1ToUTF8 (const unsigned char *magick_restrict content) inline static
References AcquireQuantumMemory(), and magick_restrict.
Referenced by CanonicalXMLContent().
GetNextUTFCode()
static int GetNextUTFCode (const char *magick_restrict text, unsigned int *magick_restrict octets) inline static
References UTFInfo::code_value, EILSEQ, MaxMultibyteCodes, utf_info, and UTFInfo::utf_mask.
Referenced by GetUTFCode(), and GetUTFOctets().
GetUTFCode()
static int GetUTFCode (const char *magick_restrict text) inline static
References GetNextUTFCode().
Referenced by FormatMagickCaption(), and GlobExpression().
GetUTFOctets()
static unsigned int GetUTFOctets (const char *magick_restrict text) inline static
References GetNextUTFCode().
Referenced by FormatMagickCaption(), and GlobExpression().
IsUTFAscii()
static MagickBooleanType IsUTFAscii (int code) inline static
References MagickFalse, and MagickTrue.
IsUTFSpace()
static MagickBooleanType IsUTFSpace (int code) inline static
References MagickFalse, and MagickTrue.
Referenced by FormatMagickCaption().
IsUTFValid()
static MagickBooleanType IsUTFValid (int code) inline static
References MagickFalse, and MagickTrue.
Variable Documentation
utf_info
UTFInfo utf_info[MaxMultibyteCodes] static
Initial value:
=
  {
    { 0x80, 0x00, 0x000007f, 0x0000000 },
    { 0xE0, 0xC0, 0x00007ff, 0x0000080 },
    { 0xF0, 0xE0, 0x000ffff, 0x0000800 },
    { 0xF8, 0xF0, 0x01fffff, 0x0010000 },
    { 0xFC, 0xF8, 0x03fffff, 0x0200000 },
    { 0xFE, 0xFC, 0x7ffffff, 0x4000000 },
  }
Referenced by GetNextUTFCode().