MagickCore: token.h File Reference
token.h File Reference
Typedefs
typedef struct _TokenInfo TokenInfo
Functions
MagickExport int Tokenizer (TokenInfo *, const unsigned int, char *, const size_t, const char *, const char *, const char *, const char *, const char, char *, int *, char *)
MagickExport MagickBooleanType GlobExpression (const char *magick_restrict, const char *magick_restrict, const MagickBooleanType) magick_attribute((__pure__))
MagickExport MagickBooleanType IsGlob (const char *) magick_attribute((__pure__))
MagickExport MagickBooleanType IsMagickTrue (const char *) magick_attribute((__pure__))
MagickExport size_t GetNextToken (const char *magick_restrict, const char **magick_restrict, const size_t, char *magick_restrict) magick_hot_spot
MagickExport TokenInfo * AcquireTokenInfo (void)
MagickExport TokenInfo * DestroyTokenInfo (TokenInfo *)
Typedef Documentation
TokenInfo
typedef struct _TokenInfo TokenInfo
Function Documentation
AcquireTokenInfo()
MagickExport TokenInfo * AcquireTokenInfo (void)
DestroyTokenInfo()
MagickExport TokenInfo * DestroyTokenInfo (TokenInfo * token_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, RelinquishMagickMemory(), _TokenInfo::signature, and TraceEvent.
GetNextToken()
MagickExport size_t GetNextToken (const char * magick_restrict, const char ** magick_restrict, const size_t, char * magick_restrict)
GlobExpression()
MagickExport MagickBooleanType GlobExpression (const char * magick_restrict, const char * magick_restrict, const MagickBooleanType)
IsGlob()
MagickExport MagickBooleanType IsGlob (const char *)
IsMagickTrue()
MagickExport MagickBooleanType IsMagickTrue (const char * value)
References LocaleCompare(), MagickFalse, and MagickTrue.
Referenced by AcquireResizeFilter(), CompositeImageChannel(), ConnectedComponentsImage(), DeskewImage(), HoughLineImage(), IdentifyImage(), LoadCoderCache(), LoadColorCache(), LoadConfigureCache(), LoadDelegateCache(), LoadMagicCache(), LoadMimeCache(), LoadPolicyCache(), LoadTypeCache(), MorphologyApply(), MorphologyImageChannel(), SetResampleFilter(), and WriteImage().
Tokenizer()
MagickExport int Tokenizer (TokenInfo * , const unsigned int , char * , const size_t, const char * , const char * , const char * , const char * , const char , char * , int * , char *)