MagickCore: token.c File Reference
token.c File Reference
#include "magick/studio.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/memory_.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/token.h"
#include "magick/token-private.h"
#include "magick/utility.h"
Data Structures
struct _TokenInfo
Macros
#define IN_WHITE 0
#define IN_TOKEN 1
#define IN_QUOTE 2
#define IN_OZONE 3
Functions
MagickExport TokenInfo * AcquireTokenInfo (void)
MagickExport TokenInfo * DestroyTokenInfo (TokenInfo *token_info)
MagickExport magick_hot_spot size_t GetNextToken (const char *magick_restrict start, const char **magick_restrict end, const size_t extent, char *magick_restrict token)
MagickExport MagickBooleanType GlobExpression (const char *magick_restrict expression, const char *magick_restrict pattern, const MagickBooleanType case_insensitive)
MagickExport MagickBooleanType IsGlob (const char *path)
MagickExport MagickBooleanType IsMagickTrue (const char *value)
static ssize_t sindex (int c, const char *string)
static void StoreToken (TokenInfo *token_info, char *string, size_t max_token_length, int c)
MagickExport int Tokenizer (TokenInfo *token_info, const unsigned flag, char *token, const size_t max_token_length, const char *line, const char *white, const char *break_set, const char *quote, const char escape, char *breaker, int *next, char *quoted)
Macro Definition Documentation
IN_OZONE
#define IN_OZONE 3
IN_QUOTE
#define IN_QUOTE 2
IN_TOKEN
#define IN_TOKEN 1
IN_WHITE
#define IN_WHITE 0
Function Documentation
AcquireTokenInfo()
MagickExport TokenInfo * AcquireTokenInfo (void)
References AcquireMagickMemory(), MagickCoreSignature, ResourceLimitFatalError, _TokenInfo::signature, and ThrowFatalException.
DestroyTokenInfo()
MagickExport TokenInfo * DestroyTokenInfo (TokenInfo * token_info)
References GetMagickModule, LogMagickEvent(), MagickCoreSignature, RelinquishMagickMemory(), _TokenInfo::signature, and TraceEvent.
GetNextToken()
MagickExport magick_hot_spot size_t GetNextToken (const char *magick_restrict start, const char **magick_restrict end, const size_t extent, char *magick_restrict token)
References DirectorySeparator, LocaleNCompare(), magick_restrict, and StringToDouble().
Referenced by AcquireKernelInfo(), ColorDecisionListImage(), GetMagickToken(), GetMVGMacros(), LoadCoderCache(), LoadColorCache(), LoadConfigureCache(), LoadDelegateCache(), LoadLocaleCache(), LoadLogCache(), LoadMagicCache(), LoadPolicyCache(), LoadTypeCache(), ParseAffineGeometry(), ParseKernelArray(), ParseKernelName(), RenderMVGContent(), and TracePath().
GlobExpression()
MagickExport MagickBooleanType GlobExpression (const char *magick_restrict expression, const char *magick_restrict pattern, const MagickBooleanType case_insensitive)
References AcquireExceptionInfo(), AcquireImageInfo(), AcquireString(), CopyMagickString(), DestroyExceptionInfo(), DestroyImageInfo(), DestroyString(), _ImageInfo::filename, GetUTFCode(), GetUTFOctets(), GlobExpression(), LocaleCompare(), LocaleLowercase(), magick_restrict, MagickFalse, MagickMin, MagickTrue, MaxTextExtent, and SetImageInfo().
Referenced by GetCoderInfoList(), GetCoderList(), GetColorInfoList(), GetColorList(), GetConfigureInfoList(), GetConfigureList(), GetDelegateInfoList(), GetDelegateList(), GetLocaleInfoList(), GetLocaleList(), GetLogInfoList(), GetLogList(), GetMagicInfoList(), GetMagickInfoList(), GetMagickList(), GetMagicList(), GetMimeInfo(), GetMimeInfoList(), GetMimeList(), GetPolicyInfoList(), GetPolicyList(), GetTypeInfoList(), GetTypeList(), GlobExpression(), InterpretImageProperties(), IsOptionMember(), IsRightsAuthorized(), and ListFiles().
IsGlob()
MagickExport MagickBooleanType IsGlob (const char * path)
References IsPathAccessible(), MagickFalse, and MagickTrue.
Referenced by ExpandFilenames(), InterpretImageProperties(), and SetImageInfo().
IsMagickTrue()
MagickExport MagickBooleanType IsMagickTrue (const char * value)
References LocaleCompare(), MagickFalse, and MagickTrue.
Referenced by AcquireResizeFilter(), CompositeImageChannel(), ConnectedComponentsImage(), DeskewImage(), HoughLineImage(), IdentifyImage(), LoadCoderCache(), LoadColorCache(), LoadConfigureCache(), LoadDelegateCache(), LoadMagicCache(), LoadMimeCache(), LoadPolicyCache(), LoadTypeCache(), MorphologyApply(), MorphologyImageChannel(), SetResampleFilter(), and WriteImage().
sindex()
static ssize_t sindex (int c, const char * string) static
Referenced by Tokenizer().
StoreToken()
static void StoreToken (TokenInfo * token_info, char * string, size_t max_token_length, int c) static
References _TokenInfo::flag, IN_QUOTE, LocaleLowercase(), LocaleUppercase(), _TokenInfo::offset, and _TokenInfo::state.
Referenced by Tokenizer().
Tokenizer()
MagickExport int Tokenizer (TokenInfo * token_info, const unsigned flag, char * token, const size_t max_token_length, const char * line, const char * white, const char * break_set, const char * quote, const char escape, char * breaker, int * next, char * quoted)
References _TokenInfo::flag, IN_OZONE, IN_QUOTE, IN_TOKEN, IN_WHITE, MagickFalse, MagickTrue, _TokenInfo::offset, _TokenInfo::quote, sindex(), _TokenInfo::state, and StoreToken().