MagickCore: transform.h File Reference
transform.h File Reference
Functions
MagickExport Image * AutoOrientImage (const Image *, const OrientationType, ExceptionInfo *)
MagickExport Image * ChopImage (const Image *, const RectangleInfo *, ExceptionInfo *)
MagickExport Image * ConsolidateCMYKImages (const Image *, ExceptionInfo *)
MagickExport Image * CropImage (const Image *, const RectangleInfo *, ExceptionInfo *)
MagickExport Image * CropImageToTiles (const Image *, const char *, ExceptionInfo *)
MagickExport Image * ExcerptImage (const Image *, const RectangleInfo *, ExceptionInfo *)
MagickExport Image * ExtentImage (const Image *, const RectangleInfo *, ExceptionInfo *)
MagickExport Image * FlipImage (const Image *, ExceptionInfo *)
MagickExport Image * FlopImage (const Image *, ExceptionInfo *)
MagickExport Image * RollImage (const Image *, const ssize_t, const ssize_t, ExceptionInfo *)
MagickExport Image * ShaveImage (const Image *, const RectangleInfo *, ExceptionInfo *)
MagickExport Image * SpliceImage (const Image *, const RectangleInfo *, ExceptionInfo *)
MagickExport Image * TransposeImage (const Image *, ExceptionInfo *)
MagickExport Image * TransverseImage (const Image *, ExceptionInfo *)
MagickExport Image * TrimImage (const Image *, ExceptionInfo *)
MagickExport MagickBooleanType TransformImage (Image **, const char *, const char *)
MagickExport MagickBooleanType TransformImages (Image **, const char *, const char *)
Function Documentation
AutoOrientImage()
MagickExport Image * AutoOrientImage (const Image * , const OrientationType, ExceptionInfo *)
ChopImage()
MagickExport Image * ChopImage (const Image * , const RectangleInfo * , ExceptionInfo *)
ConsolidateCMYKImages()
MagickExport Image * ConsolidateCMYKImages (const Image * , ExceptionInfo *)
CropImage()
MagickExport Image * CropImage (const Image * , const RectangleInfo * , ExceptionInfo *)
CropImageToTiles()
MagickExport Image * CropImageToTiles (const Image * , const char * , ExceptionInfo *)
ExcerptImage()
MagickExport Image * ExcerptImage (const Image * , const RectangleInfo * , ExceptionInfo *)
ExtentImage()
MagickExport Image * ExtentImage (const Image * , const RectangleInfo * , ExceptionInfo *)
FlipImage()
MagickExport Image * FlipImage (const Image * , ExceptionInfo *)
FlopImage()
MagickExport Image * FlopImage (const Image * , ExceptionInfo *)
RollImage()
MagickExport Image * RollImage (const Image * , const ssize_t, const ssize_t, ExceptionInfo *)
ShaveImage()
MagickExport Image * ShaveImage (const Image * , const RectangleInfo * , ExceptionInfo *)
SpliceImage()
MagickExport Image * SpliceImage (const Image * , const RectangleInfo * , ExceptionInfo *)
TransformImage()
MagickExport MagickBooleanType TransformImage (Image ** , const char * , const char *)
TransformImages()
MagickExport MagickBooleanType TransformImages (Image ** images, const char * crop_geometry, const char * image_geometry)
References AppendImageToList(), _Image::exception, GetMagickModule, ImageListToArray(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, NewImageList(), RelinquishMagickMemory(), TraceEvent, and TransformImage().
TransposeImage()
MagickExport Image * TransposeImage (const Image * , ExceptionInfo *)
TransverseImage()
MagickExport Image * TransverseImage (const Image * , ExceptionInfo *)
TrimImage()
MagickExport Image * TrimImage (const Image * image, ExceptionInfo * exception)
References _Image::background_color, CloneImage(), CropImage(), _Image::debug, _Image::filename, GetImageBoundingBox(), GetMagickModule, _RectangleInfo::height, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _PixelPacket::opacity, _Image::page, SetImageBackgroundColor(), _Image::signature, TraceEvent, TransparentOpacity, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by PolaroidImage().