MagickCore: transform.c File Reference
transform.c File Reference
#include "magick/studio.h"
#include "magick/attribute.h"
#include "magick/cache.h"
#include "magick/cache-view.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colorspace-private.h"
#include "magick/composite.h"
#include "magick/distort.h"
#include "magick/draw.h"
#include "magick/effect.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/geometry.h"
#include "magick/image.h"
#include "magick/memory_.h"
#include "magick/layer.h"
#include "magick/list.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/pixel-private.h"
#include "magick/property.h"
#include "magick/resource_.h"
#include "magick/resize.h"
#include "magick/statistic.h"
#include "magick/string_.h"
#include "magick/thread-private.h"
#include "magick/transform.h"
Macros
#define ChopImageTag "Chop/Image"
#define CropImageTag "Crop/Image"
#define ExcerptImageTag "Excerpt/Image"
#define FlipImageTag "Flip/Image"
#define FlopImageTag "Flop/Image"
#define RollImageTag "Roll/Image"
#define SpliceImageTag "Splice/Image"
#define TransposeImageTag "Transpose/Image"
#define TransverseImageTag "Transverse/Image"
Functions
MagickExport Image * AutoOrientImage (const Image *image, const OrientationType orientation, ExceptionInfo *exception)
MagickExport Image * ChopImage (const Image *image, const RectangleInfo *chop_info, ExceptionInfo *exception)
MagickExport Image * ConsolidateCMYKImages (const Image *images, ExceptionInfo *exception)
MagickExport Image * CropImage (const Image *image, const RectangleInfo *geometry, ExceptionInfo *exception)
static ssize_t PixelRoundOffset (double x)
MagickExport Image * CropImageToTiles (const Image *image, const char *crop_geometry, ExceptionInfo *exception)
MagickExport Image * ExcerptImage (const Image *image, const RectangleInfo *geometry, ExceptionInfo *exception)
MagickExport Image * ExtentImage (const Image *image, const RectangleInfo *geometry, ExceptionInfo *exception)
MagickExport Image * FlipImage (const Image *image, ExceptionInfo *exception)
MagickExport Image * FlopImage (const Image *image, ExceptionInfo *exception)
static MagickBooleanType CopyImageRegion (Image *destination, const Image *source, const size_t columns, const size_t rows, const ssize_t sx, const ssize_t sy, const ssize_t dx, const ssize_t dy, ExceptionInfo *exception)
MagickExport Image * RollImage (const Image *image, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo *exception)
MagickExport Image * ShaveImage (const Image *image, const RectangleInfo *shave_info, ExceptionInfo *exception)
MagickExport Image * SpliceImage (const Image *image, const RectangleInfo *geometry, ExceptionInfo *exception)
MagickExport MagickBooleanType TransformImage (Image **image, const char *crop_geometry, const char *image_geometry)
MagickExport MagickBooleanType TransformImages (Image **images, const char *crop_geometry, const char *image_geometry)
MagickExport Image * TransposeImage (const Image *image, ExceptionInfo *exception)
MagickExport Image * TransverseImage (const Image *image, ExceptionInfo *exception)
MagickExport Image * TrimImage (const Image *image, ExceptionInfo *exception)
Macro Definition Documentation
ChopImageTag
#define ChopImageTag "Chop/Image"
CropImageTag
#define CropImageTag "Crop/Image"
ExcerptImageTag
#define ExcerptImageTag "Excerpt/Image"
FlipImageTag
#define FlipImageTag "Flip/Image"
FlopImageTag
#define FlopImageTag "Flop/Image"
RollImageTag
#define RollImageTag "Roll/Image"
SpliceImageTag
#define SpliceImageTag "Splice/Image"
TransposeImageTag
#define TransposeImageTag "Transpose/Image"
TransverseImageTag
#define TransverseImageTag "Transverse/Image"
Function Documentation
AutoOrientImage()
MagickExport Image * AutoOrientImage (const Image * image, const OrientationType orientation, ExceptionInfo * exception)
References BottomLeftOrientation, BottomRightOrientation, CloneImage(), FlipImage(), FlopImage(), LeftBottomOrientation, LeftTopOrientation, MagickCoreSignature, MagickTrue, _Image::orientation, RightBottomOrientation, RightTopOrientation, RotateImage(), _ExceptionInfo::signature, _Image::signature, TopLeftOrientation, TopRightOrientation, TransposeImage(), TransverseImage(), and UndefinedOrientation.
ChopImage()
MagickExport Image * ChopImage (const Image * image, const RectangleInfo * chop_info, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), ChopImageTag, CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelIndex, _RectangleInfo::height, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, OptionWarning, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, _Image::type, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
ConsolidateCMYKImages()
MagickExport Image * ConsolidateCMYKImages (const Image * images, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AppendImageToList(), ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::columns, _Image::debug, DestroyCacheView(), DirectClass, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetImageListLength(), GetMagickModule, GetNextImageInList(), GetPixelIntensity(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, NewImageList(), QuantumRange, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageColorspace(), SetImageStorageClass(), SetPixelIndex, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
CopyImageRegion()
static MagickBooleanType CopyImageRegion (Image * destination, const Image * source, const size_t columns, const size_t rows, const ssize_t sx, const ssize_t sy, const ssize_t dx, const ssize_t dy, ExceptionInfo * exception) static
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), DestroyCacheView(), GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), magick_restrict, MagickFalse, MagickTrue, and SyncCacheViewAuthenticPixels().
Referenced by RollImage().
CropImage()
MagickExport Image * CropImage (const Image * image, const RectangleInfo * geometry, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _Image::background_color, BackgroundDispose, CloneImage(), _Image::columns, CropImageTag, _Image::debug, DestroyCacheView(), DestroyImage(), _Image::dispose, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, _RectangleInfo::height, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, NoneDispose, _PixelPacket::opacity, OptionWarning, _Image::page, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageBackgroundColor(), SetImageProgress(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowMagickException(), TraceEvent, TransparentOpacity, _Image::type, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by CompareImageLayers(), CropImageToTiles(), CropToFitImage(), DeskewImage(), DistortResizeImage(), ExtractSubimageFromImage(), GetEdgeBackgroundFactor(), GetSimilarityMetric(), OptimizeLayerFrames(), ReadImage(), ShaveImage(), and TrimImage().
CropImageToTiles()
MagickExport Image * CropImageToTiles (const Image * image, const char * crop_geometry, ExceptionInfo * exception)
References AppendImageToList(), AreaValue, AspectValue, ClearMagickException(), CloneImage(), _Image::columns, CropImage(), _Image::debug, _Image::filename, GetMagickModule, _RectangleInfo::height, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, NewImageList(), _Image::page, ParseGravityGeometry(), PixelRoundOffset(), _Image::rows, _Image::signature, TraceEvent, _RectangleInfo::width, _PointInfo::x, _RectangleInfo::x, XValue, _PointInfo::y, _RectangleInfo::y, and YValue.
Referenced by TransformImage().
ExcerptImage()
MagickExport Image * ExcerptImage (const Image * image, const RectangleInfo * geometry, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), ExcerptImageTag, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetMagickModule, _RectangleInfo::height, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::progress_monitor, _Image::rows, SetImageProgress(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, _Image::type, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by InterpolateMagickPixelPacket(), and InterpolatePixelColor().
ExtentImage()
MagickExport Image * ExtentImage (const Image * image, const RectangleInfo * geometry, ExceptionInfo * exception)
References CloneImage(), _Image::compose, CompositeImage(), _Image::debug, DeleteImageProfile(), DestroyImage(), _Image::exception, _Image::filename, GetMagickModule, _RectangleInfo::height, InheritException(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, SetImageBackgroundColor(), _ExceptionInfo::signature, _Image::signature, TraceEvent, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
FlipImage()
MagickExport Image * FlipImage (const Image * image, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), _Image::filename, FlipImageTag, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, _RectangleInfo::height, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::page, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, _Image::type, and _RectangleInfo::y.
Referenced by AutoOrientImage().
FlopImage()
MagickExport Image * FlopImage (const Image * image, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), _Image::filename, FlopImageTag, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelIndex, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::page, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetPixelIndex, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, _Image::type, _RectangleInfo::width, and _RectangleInfo::x.
Referenced by AutoOrientImage(), and PolaroidImage().
PixelRoundOffset()
static ssize_t PixelRoundOffset (double x) inline static
References CastDoubleToLong().
Referenced by CropImageToTiles().
RollImage()
MagickExport Image * RollImage (const Image * image, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo * exception)
References CloneImage(), _Image::columns, CopyImageRegion(), _Image::debug, DestroyImage(), _Image::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, RollImageTag, _Image::rows, SetImageProgress(), _ExceptionInfo::signature, _Image::signature, TraceEvent, _Image::type, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by PreviewImage().
ShaveImage()
MagickExport Image * ShaveImage (const Image * image, const RectangleInfo * shave_info, ExceptionInfo * exception)
References _Image::columns, CropImage(), _Image::debug, _Image::filename, GetMagickModule, _RectangleInfo::height, LogMagickEvent(), MagickCoreSignature, MagickFalse, OptionWarning, _Image::page, _Image::rows, SetGeometry(), _Image::signature, ThrowImageException, TraceEvent, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
SpliceImage()
MagickExport Image * SpliceImage (const Image * image, const RectangleInfo * geometry, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), CenterGravity, CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, EastGravity, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, _Image::gravity, _RectangleInfo::height, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickMin, MagickTrue, _Image::matte, NorthEastGravity, NorthGravity, NorthWestGravity, OpaqueOpacity, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageBackgroundColor(), SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SouthEastGravity, SouthGravity, SouthWestGravity, SpliceImageTag, StaticGravity, SyncCacheViewAuthenticPixels(), TraceEvent, UndefinedGravity, WestGravity, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
TransformImage()
MagickExport MagickBooleanType TransformImage (Image ** image, const char * crop_geometry, const char * image_geometry)
References _Image::blur, CloneImage(), _Image::columns, CropImageToTiles(), DestroyImage(), _Image::exception, _Image::filter, GetFirstImageInList(), GetMagickModule, _RectangleInfo::height, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, ParseRegionGeometry(), ResizeImage(), _Image::rows, TraceEvent, and _RectangleInfo::width.
Referenced by DrawPrimitive(), RenderPostscript(), SketchImage(), and TransformImages().
TransformImages()
MagickExport MagickBooleanType TransformImages (Image ** images, const char * crop_geometry, const char * image_geometry)
References AppendImageToList(), _Image::exception, GetMagickModule, ImageListToArray(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, NewImageList(), RelinquishMagickMemory(), TraceEvent, and TransformImage().
TransposeImage()
MagickExport Image * TransposeImage (const Image * image, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, _RectangleInfo::height, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::page, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), _ExceptionInfo::signature, _Image::signature, Swap, SyncCacheViewAuthenticPixels(), TraceEvent, TransposeImageTag, _Image::type, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by AutoOrientImage().
TransverseImage()
MagickExport Image * TransverseImage (const Image * image, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelIndex, _RectangleInfo::height, LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::page, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _Image::rows, SetImageProgress(), SetPixelIndex, _ExceptionInfo::signature, _Image::signature, Swap, SyncCacheViewAuthenticPixels(), TraceEvent, TransverseImageTag, _Image::type, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by AutoOrientImage().
TrimImage()
MagickExport Image * TrimImage (const Image * image, ExceptionInfo * exception)
References _Image::background_color, CloneImage(), CropImage(), _Image::debug, _Image::filename, GetImageBoundingBox(), GetMagickModule, _RectangleInfo::height, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _PixelPacket::opacity, _Image::page, SetImageBackgroundColor(), _Image::signature, TraceEvent, TransparentOpacity, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by PolaroidImage().