MagickCore: type.c File Reference
type.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/client.h"
#include "magick/configure.h"
#include "magick/draw.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/hashmap.h"
#include "magick/image-private.h"
#include "magick/log.h"
#include "magick/memory_.h"
#include "magick/nt-base-private.h"
#include "magick/nt-feature.h"
#include "magick/option.h"
#include "magick/semaphore.h"
#include "magick/splay-tree.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/type.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/xml-tree.h"
Macros
#define MagickTypeFilename "type.xml"
Functions
static MagickBooleanType IsTypeTreeInstantiated (ExceptionInfo *)
static MagickBooleanType LoadTypeCache (SplayTreeInfo *, const char *, const char *, const size_t, ExceptionInfo *)
static void * DestroyTypeNode (void *type_info)
static SplayTreeInfo * AcquireTypeCache (const char *filename, ExceptionInfo *exception)
MagickExport const TypeInfo * GetTypeInfo (const char *name, ExceptionInfo *exception)
MagickExport const TypeInfo * GetTypeInfoByFamily (const char *family, const StyleType style, const StretchType stretch, const size_t weight, ExceptionInfo *exception)
static int TypeInfoCompare (const void *x, const void *y)
MagickExport const TypeInfo ** GetTypeInfoList (const char *pattern, size_t *number_fonts, ExceptionInfo *exception)
static int TypeCompare (const void *x, const void *y)
MagickExport char ** GetTypeList (const char *pattern, size_t *number_fonts, ExceptionInfo *exception)
MagickExport MagickBooleanType ListTypeInfo (FILE *file, ExceptionInfo *exception)
static MagickBooleanType SetTypeNodePath (const char *filename, char *font_path, const char *token, char **target)
MagickExport MagickBooleanType TypeComponentGenesis (void)
MagickExport void TypeComponentTerminus (void)
Variables
static const char TypeMap []
static SemaphoreInfo * type_semaphore = (SemaphoreInfo *) NULL
static SplayTreeInfo * type_cache = (SplayTreeInfo *) NULL
Macro Definition Documentation
MagickTypeFilename
#define MagickTypeFilename "type.xml"
Function Documentation
AcquireTypeCache()
static SplayTreeInfo * AcquireTypeCache (const char * filename, ExceptionInfo * exception) static
References CompareSplayTreeString(), CopyMagickString(), DestroyConfigureOptions(), DestroyString(), DestroyTypeNode(), DirectorySeparator, FileToString(), FormatLocaleString(), GetConfigureOptions(), GetEnvironmentValue(), GetNextValueInLinkedList(), GetNumberOfNodesInSplayTree(), GetStringInfoDatum(), GetStringInfoPath(), LoadTypeCache(), MagickTrue, MaxTextExtent, NewSplayTree(), ResourceLimitFatalError, ThrowFatalException, and TypeMap.
Referenced by IsTypeTreeInstantiated().
DestroyTypeNode()
static void * DestroyTypeNode (void * type_info) static
References _TypeInfo::description, DestroyString(), _TypeInfo::encoding, _TypeInfo::family, _TypeInfo::format, _TypeInfo::foundry, _TypeInfo::glyphs, _TypeInfo::metrics, _TypeInfo::name, _TypeInfo::path, and RelinquishMagickMemory().
Referenced by AcquireTypeCache(), and LoadTypeCache().
GetTypeInfo()
MagickExport const TypeInfo * GetTypeInfo (const char * name, ExceptionInfo * exception)
References GetRootValueFromSplayTree(), GetValueFromSplayTree(), IsTypeTreeInstantiated(), LocaleCompare(), MagickFalse, and type_cache.
Referenced by GetTypeInfoByFamily(), GetTypeInfoList(), GetTypeList(), and RenderType().
GetTypeInfoByFamily()
MagickExport const TypeInfo * GetTypeInfoByFamily (const char * family, const StyleType style, const StretchType stretch, const size_t weight, ExceptionInfo * exception)
References AnyStretch, AnyStyle, _TypeInfo::family, GetMagickModule, GetNextValueInSplayTree(), GetTypeInfo(), GetTypeInfoByFamily(), ItalicStyle, LocaleCompare(), LockSemaphoreInfo(), MagickMax, MagickMin, NormalStretch, ObliqueStyle, ResetSplayTreeIterator(), _TypeInfo::stretch, _TypeInfo::style, ThrowMagickException(), type_cache, type_semaphore, TypeWarning, UltraExpandedStretch, UndefinedStretch, UndefinedStyle, UnlockSemaphoreInfo(), and _TypeInfo::weight.
Referenced by GetTypeInfoByFamily(), and RenderType().
GetTypeInfoList()
MagickExport const TypeInfo ** GetTypeInfoList (const char * pattern, size_t * number_fonts, ExceptionInfo * exception)
References AcquireQuantumMemory(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GetTypeInfo(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _TypeInfo::name, ResetSplayTreeIterator(), _TypeInfo::stealth, TraceEvent, type_cache, type_semaphore, TypeInfoCompare(), and UnlockSemaphoreInfo().
Referenced by ListTypeInfo().
GetTypeList()
MagickExport char ** GetTypeList (const char * pattern, size_t * number_fonts, ExceptionInfo * exception)
References AcquireQuantumMemory(), ConstantString(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GetTypeInfo(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _TypeInfo::name, ResetSplayTreeIterator(), _TypeInfo::stealth, TraceEvent, type_cache, type_semaphore, TypeCompare(), and UnlockSemaphoreInfo().
IsTypeTreeInstantiated()
static MagickBooleanType IsTypeTreeInstantiated (ExceptionInfo * exception) static
References AcquireTypeCache(), ActivateSemaphoreInfo(), LockSemaphoreInfo(), MagickFalse, MagickTrue, MagickTypeFilename, NTAcquireTypeCache(), type_cache, type_semaphore, and UnlockSemaphoreInfo().
Referenced by GetTypeInfo().
ListTypeInfo()
MagickExport MagickBooleanType ListTypeInfo (FILE * file, ExceptionInfo * exception)
References CommandOptionToMnemonic(), _TypeInfo::family, FormatLocaleFile(), FormatLocaleString(), GetTypeInfoList(), _TypeInfo::glyphs, LocaleCompare(), MagickFalse, MagickStretchOptions, MagickStyleOptions, MagickTrue, MaxTextExtent, _TypeInfo::name, _TypeInfo::path, RelinquishMagickMemory(), and _TypeInfo::weight.
LoadTypeCache()
static MagickBooleanType LoadTypeCache (SplayTreeInfo * cache, const char * xml, const char * filename, const size_t depth, ExceptionInfo * exception)
References AcquireExceptionInfo(), AcquireMagickMemory(), AcquireString(), AddValueToSplayTree(), ConcatenateMagickString(), ConfigureError, ConfigureEvent, ConstantString(), CopyMagickString(), _TypeInfo::description, DestroyExceptionInfo(), DestroyTypeNode(), DirectorySeparator, _TypeInfo::encoding, _TypeInfo::face, _TypeInfo::family, FileToString(), _TypeInfo::format, _TypeInfo::foundry, GetMagickModule, GetNextToken(), GetPathComponent(), _TypeInfo::glyphs, HeadPath, IsMagickTrue(), LoadTypeCache(), LocaleCompare(), LocaleNCompare(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickMaxRecursionDepth, MagickStretchOptions, MagickStyleOptions, MagickTrue, MagickWeightOptions, MaxTextExtent, _TypeInfo::metrics, _TypeInfo::name, ParseCommandOption(), _TypeInfo::path, RelinquishMagickMemory(), ResourceLimitError, ResourceLimitFatalError, SetTypeNodePath(), _TypeInfo::signature, _TypeInfo::stealth, _TypeInfo::stretch, StringToUnsignedLong(), _TypeInfo::style, ThrowFatalException, ThrowMagickException(), and _TypeInfo::weight.
Referenced by AcquireTypeCache(), and LoadTypeCache().
SetTypeNodePath()
static MagickBooleanType SetTypeNodePath (const char * filename, char * font_path, const char * token, char ** target) inline static
References ConcatenateMagickString(), ConstantString(), DestroyString(), DirectorySeparator, GetPathComponent(), HeadPath, IsPathAccessible(), MagickFalse, MagickTrue, MaxTextExtent, and SubstituteString().
Referenced by LoadTypeCache().
TypeCompare()
static int TypeCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetTypeList().
TypeComponentGenesis()
MagickExport MagickBooleanType TypeComponentGenesis (void)
References AllocateSemaphoreInfo(), MagickTrue, and type_semaphore.
Referenced by MagickCoreGenesis().
TypeComponentTerminus()
MagickExport void TypeComponentTerminus (void)
References ActivateSemaphoreInfo(), DestroySemaphoreInfo(), DestroySplayTree(), LockSemaphoreInfo(), type_cache, type_semaphore, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().
TypeInfoCompare()
static int TypeInfoCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by GetTypeInfoList().
Variable Documentation
type_cache
SplayTreeInfo* type_cache = (SplayTreeInfo *) NULL static
Referenced by GetTypeInfo(), GetTypeInfoByFamily(), GetTypeInfoList(), GetTypeList(), IsTypeTreeInstantiated(), and TypeComponentTerminus().
type_semaphore
SemaphoreInfo* type_semaphore = (SemaphoreInfo *) NULL static
Referenced by GetTypeInfoByFamily(), GetTypeInfoList(), GetTypeList(), IsTypeTreeInstantiated(), TypeComponentGenesis(), and TypeComponentTerminus().
TypeMap
const char TypeMap[] static
Initial value:
=
    "<?xml version=\"1.0\"?>"
    "<typemap>"
    "  <type stealth=\"True\" name=\"fixed\" family=\"helvetica\"/>"
    "  <type stealth=\"True\" name=\"helvetica\" family=\"helvetica\"/>"
    "</typemap>"
Referenced by AcquireTypeCache().