MagickCore: type.h File Reference
type.h File Reference
Data Structures
struct _TypeInfo
Typedefs
typedef struct _TypeInfo TypeInfo
Enumerations
enum StretchType {
UndefinedStretch , NormalStretch , UltraCondensedStretch , ExtraCondensedStretch ,
CondensedStretch , SemiCondensedStretch , SemiExpandedStretch , ExpandedStretch ,
ExtraExpandedStretch , UltraExpandedStretch , AnyStretch
}
enum StyleType {
UndefinedStyle , NormalStyle , ItalicStyle , ObliqueStyle ,
AnyStyle , BoldStyle
}
Functions
MagickExport char ** GetTypeList (const char *, size_t *, ExceptionInfo *)
MagickExport MagickBooleanType ListTypeInfo (FILE *, ExceptionInfo *)
MagickExport MagickBooleanType TypeComponentGenesis (void)
MagickExport const TypeInfo * GetTypeInfo (const char *, ExceptionInfo *)
MagickExport const TypeInfo * GetTypeInfoByFamily (const char *, const StyleType, const StretchType, const size_t, ExceptionInfo *)
MagickExport const TypeInfo ** GetTypeInfoList (const char *, size_t *, ExceptionInfo *)
MagickExport void TypeComponentTerminus (void)
Typedef Documentation
TypeInfo
typedef struct _TypeInfo TypeInfo
Enumeration Type Documentation
StretchType
enum StretchType
Enumerator
UndefinedStretch
NormalStretch
UltraCondensedStretch
ExtraCondensedStretch
CondensedStretch
SemiCondensedStretch
SemiExpandedStretch
ExpandedStretch
ExtraExpandedStretch
UltraExpandedStretch
AnyStretch
StyleType
enum StyleType
Enumerator
UndefinedStyle
NormalStyle
ItalicStyle
ObliqueStyle
AnyStyle
BoldStyle
Function Documentation
GetTypeInfo()
MagickExport const TypeInfo * GetTypeInfo (const char * , ExceptionInfo *)
GetTypeInfoByFamily()
MagickExport const TypeInfo * GetTypeInfoByFamily (const char * , const StyleType, const StretchType, const size_t, ExceptionInfo *)
GetTypeInfoList()
MagickExport const TypeInfo ** GetTypeInfoList (const char * pattern, size_t * number_fonts, ExceptionInfo * exception)
References AcquireQuantumMemory(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GetTypeInfo(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _TypeInfo::name, ResetSplayTreeIterator(), _TypeInfo::stealth, TraceEvent, type_cache, type_semaphore, TypeInfoCompare(), and UnlockSemaphoreInfo().
Referenced by ListTypeInfo().
GetTypeList()
MagickExport char ** GetTypeList (const char * pattern, size_t * number_fonts, ExceptionInfo * exception)
References AcquireQuantumMemory(), ConstantString(), GetMagickModule, GetNextValueInSplayTree(), GetNumberOfNodesInSplayTree(), GetTypeInfo(), GlobExpression(), LockSemaphoreInfo(), LogMagickEvent(), MagickFalse, _TypeInfo::name, ResetSplayTreeIterator(), _TypeInfo::stealth, TraceEvent, type_cache, type_semaphore, TypeCompare(), and UnlockSemaphoreInfo().
ListTypeInfo()
MagickExport MagickBooleanType ListTypeInfo (FILE * , ExceptionInfo *)
TypeComponentGenesis()
MagickExport MagickBooleanType TypeComponentGenesis (void)
References AllocateSemaphoreInfo(), MagickTrue, and type_semaphore.
Referenced by MagickCoreGenesis().
TypeComponentTerminus()
MagickExport void TypeComponentTerminus (void)
References ActivateSemaphoreInfo(), DestroySemaphoreInfo(), DestroySplayTree(), LockSemaphoreInfo(), type_cache, type_semaphore, and UnlockSemaphoreInfo().
Referenced by MagickCoreTerminus().