MagickCore: utility.h File Reference
utility.h File Reference
Enumerations
enum PathType {
UndefinedPath , MagickPath , RootPath , HeadPath ,
TailPath , BasePath , ExtensionPath , SubimagePath ,
CanonicalPath , SubcanonicalPath
}
Functions
MagickExport char * Base64Encode (const unsigned char *, const size_t, size_t *)
MagickExport char ** GetPathComponents (const char *, size_t *)
MagickExport char ** ListFiles (const char *, const char *, size_t *)
MagickExport MagickBooleanType AcquireUniqueFilename (char *)
MagickExport MagickBooleanType AcquireUniqueSymbolicLink (const char *, char *)
MagickExport MagickBooleanType ExpandFilenames (int *, char ***)
MagickExport MagickBooleanType GetPathAttributes (const char *, void *)
MagickExport MagickBooleanType GetExecutionPath (char *, const size_t)
MagickExport MagickBooleanType IsPathAccessible (const char *)
MagickExport size_t MultilineCensus (const char *) magick_attribute((__pure__))
MagickExport ssize_t GetMagickPageSize (void)
MagickExport unsigned char * Base64Decode (const char *, size_t *)
MagickExport void AppendImageFormat (const char *, char *)
MagickExport void ChopPathComponents (char *, const size_t)
MagickExport void ExpandFilename (char *)
MagickExport void GetPathComponent (const char *, PathType, char *)
MagickExport void MagickDelay (const MagickSizeType)
Enumeration Type Documentation
PathType
enum PathType
Enumerator
UndefinedPath
MagickPath
RootPath
HeadPath
TailPath
BasePath
ExtensionPath
SubimagePath
CanonicalPath
SubcanonicalPath
Function Documentation
AcquireUniqueFilename()
MagickExport MagickBooleanType AcquireUniqueFilename (char *)
AcquireUniqueSymbolicLink()
MagickExport MagickBooleanType AcquireUniqueSymbolicLink (const char * , char *)
AppendImageFormat()
MagickExport void AppendImageFormat (const char * , char *)
Base64Decode()
MagickExport unsigned char * Base64Decode (const char * source, size_t * length)
References AcquireQuantumMemory(), Base64, GetMagickModule, LogMagickEvent(), RelinquishMagickMemory(), and TraceEvent.
Referenced by ReadInlineImage().
Base64Encode()
MagickExport char * Base64Encode (const unsigned char * , const size_t, size_t *)
ChopPathComponents()
MagickExport void ChopPathComponents (char * , const size_t)
ExpandFilename()
MagickExport void ExpandFilename (char *)
ExpandFilenames()
MagickExport MagickBooleanType ExpandFilenames (int * , char ***)
GetExecutionPath()
MagickExport MagickBooleanType GetExecutionPath (char * , const size_t)
GetMagickPageSize()
MagickExport ssize_t GetMagickPageSize (void)
Referenced by PersistPixelCache(), and ResourceComponentGenesis().
GetPathAttributes()
MagickExport MagickBooleanType GetPathAttributes (const char * , void *)
GetPathComponent()
MagickExport void GetPathComponent (const char * , PathType , char *)
GetPathComponents()
MagickExport char ** GetPathComponents (const char * , size_t *)
IsPathAccessible()
MagickExport MagickBooleanType IsPathAccessible (const char * path)
References access_utf8(), GetPathAttributes(), LocaleCompare(), MagickFalse, MagickTrue, and S_ISREG.
Referenced by ExpandFilenames(), GetConfigureBlob(), GetExecutionPath(), GetMagickHomeURL(), GetPathComponent(), InterpretImageProperties(), IsGlob(), LogMagickEventList(), MagickCoreGenesis(), ReadImage(), RenderType(), SetTypeNodePath(), and WriteImage().
ListFiles()
MagickExport char ** ListFiles (const char * directory, const char * pattern, size_t * number_entries)
References AcquireMagickMemory(), AcquireQuantumMemory(), AcquireString(), closedir(), dirent::d_name, FileCompare(), GetMagickModule, GlobExpression(), IsPathDirectory(), LocaleCompare(), LogMagickEvent(), MagickFalse, MagickReadDirectory(), MagickTrue, opendir(), RelinquishMagickMemory(), ResizeQuantumMemory(), ResourceLimitFatalError, ThrowFatalException, and TraceEvent.
Referenced by ExpandFilenames().
MagickDelay()
MagickExport void MagickDelay (const MagickSizeType)
References CLOCKS_PER_SEC.
Referenced by GetImagePixelCache(), and InvokeDelegate().
MultilineCensus()
MagickExport size_t MultilineCensus (const char * label)
Referenced by MontageImageList().