MagickCore: utility.c File Reference
utility.c File Reference
#include "magick/studio.h"
#include "magick/property.h"
#include "magick/blob.h"
#include "magick/color.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/geometry.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/log.h"
#include "magick/memory_.h"
#include "magick/nt-base-private.h"
#include "magick/option.h"
#include "magick/policy.h"
#include "magick/random_.h"
#include "magick/registry.h"
#include "magick/resource_.h"
#include "magick/semaphore.h"
#include "magick/signature-private.h"
#include "magick/statistic.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/token.h"
#include "magick/utility.h"
#include "magick/utility-private.h"
Functions
static int IsPathDirectory (const char *)
MagickExport MagickBooleanType AcquireUniqueFilename (char *path)
MagickExport MagickBooleanType AcquireUniqueSymbolicLink (const char *source, char *destination)
MagickExport void AppendImageFormat (const char *format, char *filename)
MagickExport unsigned char * Base64Decode (const char *source, size_t *length)
MagickExport char * Base64Encode (const unsigned char *blob, const size_t blob_length, size_t *encode_length)
MagickExport void ChopPathComponents (char *path, const size_t components)
MagickExport void ExpandFilename (char *path)
MagickExport MagickBooleanType ExpandFilenames (int *number_arguments, char ***arguments)
MagickExport MagickBooleanType GetExecutionPath (char *path, const size_t extent)
MagickExport ssize_t GetMagickPageSize (void)
MagickExport MagickBooleanType GetPathAttributes (const char *path, void *attributes)
MagickExport void GetPathComponent (const char *path, PathType type, char *component)
MagickExport char ** GetPathComponents (const char *path, size_t *number_components)
MagickExport MagickBooleanType IsPathAccessible (const char *path)
static int FileCompare (const void *x, const void *y)
MagickExport char ** ListFiles (const char *directory, const char *pattern, size_t *number_entries)
MagickExport void MagickDelay (const MagickSizeType milliseconds)
MagickExport size_t MultilineCensus (const char *label)
MagickPrivate MagickBooleanType ShredFile (const char *path)
Variables
static const char Base64 [] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
Function Documentation
AcquireUniqueFilename()
MagickExport MagickBooleanType AcquireUniqueFilename (char * path)
References AcquireUniqueFileResource(), MagickFalse, and MagickTrue.
Referenced by AcquireUniqueSymbolicLink(), InvokeDelegate(), TemporaryFilename(), and WriteImage().
AcquireUniqueSymbolicLink()
MagickExport MagickBooleanType AcquireUniqueSymbolicLink (const char * source, char * destination)
References AcquireQuantumMemory(), AcquireUniqueFilename(), AcquireUniqueFileResource(), ConcatenateMagickString(), DestroyString(), DirectorySeparator, GetPolicyValue(), MagickFalse, MagickMaxBufferExtent, MagickMin, MagickTrue, MaxTextExtent, O_BINARY, open_utf8(), RelinquishMagickMemory(), and RelinquishUniqueFileResource().
Referenced by InvokeDelegate().
AppendImageFormat()
MagickExport void AppendImageFormat (const char * format, char * filename)
References CopyMagickString(), ExtensionPath, FormatLocaleString(), GetMagickModule, GetPathComponent(), LocaleCompare(), LogMagickEvent(), MaxTextExtent, RootPath, and TraceEvent.
Referenced by RelinquishUniqueFileResource().
Base64Decode()
MagickExport unsigned char * Base64Decode (const char * source, size_t * length)
References AcquireQuantumMemory(), Base64, GetMagickModule, LogMagickEvent(), RelinquishMagickMemory(), and TraceEvent.
Referenced by ReadInlineImage().
Base64Encode()
MagickExport char * Base64Encode (const unsigned char * blob, const size_t blob_length, size_t * encode_length)
References AcquireQuantumMemory(), Base64, GetMagickModule, LogMagickEvent(), and TraceEvent.
Referenced by CanonicalXMLContent().
ChopPathComponents()
MagickExport void ChopPathComponents (char * path, const size_t components)
References GetPathComponent(), and HeadPath.
Referenced by GetConfigureBlob(), and GetConfigurePaths().
ExpandFilename()
MagickExport void ExpandFilename (char * path)
References ConcatenateMagickString(), CopyMagickString(), DestroyString(), DirectorySeparator, GetEnvironmentValue(), MagickPathExtent, and MaxTextExtent.
Referenced by ExpandFilenames().
ExpandFilenames()
MagickExport MagickBooleanType ExpandFilenames (int * number_arguments, char *** arguments)
References AcquireExceptionInfo(), AcquireQuantumMemory(), AcquireString(), ConcatenateMagickString(), ConcatenateString(), ConfigureEvent, ConstantString(), CopyMagickString(), DestroyExceptionInfo(), DestroyString(), DirectorySeparator, ExpandFilename(), FileToString(), getcwd_utf8(), GetMagickModule, GetPathComponent(), HeadPath, IsEventLogging(), IsGlob(), IsPathAccessible(), IsPathDirectory(), ListFiles(), LocaleCompare(), LogMagickEvent(), MagickCommandOptions, MagickFalse, MagickPath, MagickTrue, MaxTextExtent, OptionFatalError, ParseCommandOption(), RelinquishMagickMemory(), ResizeQuantumMemory(), ResourceLimitFatalError, StringToArgv(), SubimagePath, TailPath, ThrowFatalException, and TraceEvent.
FileCompare()
static int FileCompare (const void * x, const void * y) static
References LocaleCompare().
Referenced by ListFiles().
GetExecutionPath()
MagickExport MagickBooleanType GetExecutionPath (char * path, const size_t extent)
References AcquireQuantumMemory(), ConcatenateMagickString(), CopyMagickString(), DirectorySeparator, FormatLocaleString(), IsPathAccessible(), MaxTextExtent, PATH_MAX, and RelinquishMagickMemory().
Referenced by MagickCoreGenesis().
GetMagickPageSize()
MagickExport ssize_t GetMagickPageSize (void)
Referenced by PersistPixelCache(), and ResourceComponentGenesis().
GetPathAttributes()
MagickExport MagickBooleanType GetPathAttributes (const char * path, void * attributes)
References MagickFalse, MagickTrue, and stat_utf8().
Referenced by CopyDelegateFile(), DrawPrimitive(), FileToBlob(), GetBlobSize(), GetPathTemplate(), IsPathAccessible(), IsPathDirectory(), OpenBlob(), and ThumbnailImage().
GetPathComponent()
MagickExport void GetPathComponent (const char * path, PathType type, char * component)
References BasePath, CanonicalPath, CopyMagickString(), ExtensionPath, GetMagickModule, HeadPath, IsBasenameSeparator, IsGeometry(), IsMagickConflict(), IsPathAccessible(), IsPathDirectory(), IsSceneGeometry(), LogMagickEvent(), MagickFalse, MagickPath, MagickPathExtent, RootPath, SubcanonicalPath, SubimagePath, TailPath, TraceEvent, and UndefinedPath.
Referenced by AddPathToXMLTree(), AppendImageFormat(), ChopPathComponents(), ExpandFilenames(), GetMagickProperty(), GetMagickPropertyLetter(), GetXMLTreePath(), IdentifyImage(), LoadCoderCache(), LoadColorCache(), LoadConfigureCache(), LoadDelegateCache(), LoadLocaleCache(), LoadLogCache(), LoadMagicCache(), LoadMimeCache(), LoadPolicyCache(), LoadTypeCache(), MagickCoreGenesis(), OpenBlob(), ReadImage(), SetImageInfo(), SetTypeNodePath(), ThrowMagickExceptionList(), ThumbnailImage(), and WriteImage().
GetPathComponents()
MagickExport char ** GetPathComponents (const char * path, size_t * number_components)
References AcquireQuantumMemory(), CopyMagickString(), IsBasenameSeparator, MaxTextExtent, ResourceLimitFatalError, and ThrowFatalException.
Referenced by AddPathToXMLTree(), and GetXMLTreePath().
IsPathAccessible()
MagickExport MagickBooleanType IsPathAccessible (const char * path)
References access_utf8(), GetPathAttributes(), LocaleCompare(), MagickFalse, MagickTrue, and S_ISREG.
Referenced by ExpandFilenames(), GetConfigureBlob(), GetExecutionPath(), GetMagickHomeURL(), GetPathComponent(), InterpretImageProperties(), IsGlob(), LogMagickEventList(), MagickCoreGenesis(), ReadImage(), RenderType(), SetTypeNodePath(), and WriteImage().
IsPathDirectory()
static int IsPathDirectory (const char * path) static
References GetPathAttributes(), MagickFalse, and S_ISDIR.
Referenced by ExpandFilenames(), GetPathComponent(), and ListFiles().
ListFiles()
MagickExport char ** ListFiles (const char * directory, const char * pattern, size_t * number_entries)
References AcquireMagickMemory(), AcquireQuantumMemory(), AcquireString(), closedir(), dirent::d_name, FileCompare(), GetMagickModule, GlobExpression(), IsPathDirectory(), LocaleCompare(), LogMagickEvent(), MagickFalse, MagickReadDirectory(), MagickTrue, opendir(), RelinquishMagickMemory(), ResizeQuantumMemory(), ResourceLimitFatalError, ThrowFatalException, and TraceEvent.
Referenced by ExpandFilenames().
MagickDelay()
MagickExport void MagickDelay (const MagickSizeType milliseconds)
References CLOCKS_PER_SEC.
Referenced by GetImagePixelCache(), and InvokeDelegate().
MultilineCensus()
MagickExport size_t MultilineCensus (const char * label)
Referenced by MontageImageList().
ShredFile()
MagickPrivate MagickBooleanType ShredFile (const char * path)
References AcquireRandomInfo(), DestroyRandomInfo(), DestroyString(), DestroyStringInfo(), ExceptionEvent, GetEnvironmentValue(), GetMagickModule, GetPolicyValue(), GetRandomKey(), GetStringInfoDatum(), LogMagickEvent(), MagickFalse, MagickMaxBufferExtent, MagickMin, MagickTrue, O_BINARY, open_utf8(), random_info, remove_utf8(), ResetStringInfo(), S_MODE, and StringToInteger().
Referenced by AsynchronousResourceComponentTerminus(), DestroyTemporaryResources(), and RelinquishUniqueFileResource().
Variable Documentation
Base64
const char Base64[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/" static
Referenced by Base64Decode(), and Base64Encode().