MagickCore: utility-private.h File Reference
utility-private.h File Reference
#include "magick/memory_.h"
#include "magick/nt-base.h"
#include "magick/nt-base-private.h"
Functions
MagickPrivate MagickBooleanType ShredFile (const char *)
static int MagickReadDirectory (DIR *directory, struct dirent *entry, struct dirent **result)
static int access_utf8 (const char *path, int mode)
static FILE * fopen_utf8 (const char *path, const char *mode)
static void getcwd_utf8 (char *path, size_t extent)
static int open_utf8 (const char *path, int flags, mode_t mode)
static FILE * popen_utf8 (const char *command, const char *type)
static int remove_utf8 (const char *path)
static int rename_utf8 (const char *source, const char *destination)
static int stat_utf8 (const char *path, struct stat *attributes)
Function Documentation
access_utf8()
static int access_utf8 (const char * path, int mode) inline static
References RelinquishMagickMemory().
Referenced by InvokeDelegate(), IsPathAccessible(), and RelinquishUniqueFileResource().
fopen_utf8()
static FILE * fopen_utf8 (const char * path, const char * mode) inline static
References RelinquishMagickMemory().
Referenced by LogMagickEventList(), and OpenBlob().
getcwd_utf8()
static void getcwd_utf8 (char * path, size_t extent) inline static
References MaxTextExtent.
Referenced by ExpandFilenames().
MagickReadDirectory()
static int MagickReadDirectory (DIR * directory, struct dirent * entry, struct dirent ** result) inline static
References readdir().
Referenced by ListFiles().
open_utf8()
static int open_utf8 (const char * path, int flags, mode_t mode) inline static
References RelinquishMagickMemory().
Referenced by AcquireUniqueFileResource(), AcquireUniqueSymbolicLink(), BlobToFile(), ConfigureFileToStringInfo(), CopyDelegateFile(), FileToBlob(), FileToImage(), FileToXML(), GenerateEntropicChaos(), ImageToFile(), InjectImageBlob(), OpenPixelCacheOnDisk(), and ShredFile().
popen_utf8()
static FILE * popen_utf8 (const char * command, const char * type) inline static
References AcquireQuantumMemory(), and RelinquishMagickMemory().
Referenced by ExternalDelegateCommand(), and OpenBlob().
remove_utf8()
static int remove_utf8 (const char * path) inline static
References RelinquishMagickMemory().
Referenced by ShredFile().
rename_utf8()
static int rename_utf8 (const char * source, const char * destination) inline static
References RelinquishMagickMemory().
ShredFile()
MagickPrivate MagickBooleanType ShredFile (const char * path)
References AcquireRandomInfo(), DestroyRandomInfo(), DestroyString(), DestroyStringInfo(), ExceptionEvent, GetEnvironmentValue(), GetMagickModule, GetPolicyValue(), GetRandomKey(), GetStringInfoDatum(), LogMagickEvent(), MagickFalse, MagickMaxBufferExtent, MagickMin, MagickTrue, O_BINARY, open_utf8(), random_info, remove_utf8(), ResetStringInfo(), S_MODE, and StringToInteger().
Referenced by AsynchronousResourceComponentTerminus(), DestroyTemporaryResources(), and RelinquishUniqueFileResource().
stat_utf8()
static int stat_utf8 (const char * path, struct stat * attributes) inline static
References RelinquishMagickMemory().
Referenced by GetPathAttributes().