MagickCore: version.h File Reference
version.h File Reference
Macros
#define MagickPackageName "ImageMagick"
#define MagickCopyright "(C) 1999-2021 ImageMagick Studio LLC"
#define MagickLibVersion 0x69B
#define MagickLibVersionText "6.9.11"
#define MagickLibVersionNumber 6,0,0
#define MagickLibAddendum "-60"
#define MagickLibInterface 6
#define MagickLibMinInterface 6
#define MagickPlatform "x86_64"
#define MagickppLibVersionText "6.9.11"
#define MagickppLibVersionNumber 8:0:0
#define MagickppLibAddendum "-60"
#define MagickppLibInterface 8
#define MagickppLibMinInterface 8
#define MagickReleaseDate "2021-01-25"
#define MagickHomeURL "file:///usr/share/doc/ImageMagick-6/index.html"
#define MagickAuthoritativeLicense "https://imagemagick.org/script/license.php"
#define MagickAuthoritativeURL "https://imagemagick.org"
#define MagickQuantumDepth "Q?"
#define MagickQuantumRange "?"
#define MagickVersion
Functions
MagickExport char * GetMagickHomeURL (void)
MagickExport const char * GetMagickCopyright (void) magick_attribute((__const__))
MagickExport const char * GetMagickDelegates (void) magick_attribute((__const__))
MagickExport const char * GetMagickFeatures (void) magick_attribute((__const__))
MagickExport const char * GetMagickLicense (void) magick_attribute((__const__))
MagickExport const char * GetMagickPackageName (void) magick_attribute((__const__))
MagickExport const char * GetMagickQuantumDepth (size_t *)
MagickExport const char * GetMagickQuantumRange (size_t *)
MagickExport const char * GetMagickReleaseDate (void) magick_attribute((__const__))
MagickExport const char * GetMagickVersion (size_t *)
MagickExport void ListMagickVersion (FILE *)
Macro Definition Documentation
MagickAuthoritativeLicense
#define MagickAuthoritativeLicense "https://imagemagick.org/script/license.php"
MagickAuthoritativeURL
#define MagickAuthoritativeURL "https://imagemagick.org"
MagickCopyright
#define MagickCopyright "(C) 1999-2021 ImageMagick Studio LLC"
MagickHomeURL
#define MagickHomeURL "file:///usr/share/doc/ImageMagick-6/index.html"
MagickLibAddendum
#define MagickLibAddendum "-60"
MagickLibInterface
#define MagickLibInterface 6
MagickLibMinInterface
#define MagickLibMinInterface 6
MagickLibVersion
#define MagickLibVersion 0x69B
MagickLibVersionNumber
#define MagickLibVersionNumber 6,0,0
MagickLibVersionText
#define MagickLibVersionText "6.9.11"
MagickPackageName
#define MagickPackageName "ImageMagick"
MagickPlatform
#define MagickPlatform "x86_64"
MagickppLibAddendum
#define MagickppLibAddendum "-60"
MagickppLibInterface
#define MagickppLibInterface 8
MagickppLibMinInterface
#define MagickppLibMinInterface 8
MagickppLibVersionNumber
#define MagickppLibVersionNumber 8:0:0
MagickppLibVersionText
#define MagickppLibVersionText "6.9.11"
MagickQuantumDepth
#define MagickQuantumDepth "Q?"
MagickQuantumRange
#define MagickQuantumRange "?"
MagickReleaseDate
#define MagickReleaseDate "2021-01-25"
MagickVersion
#define MagickVersion
Value:
  MagickPackageName " " MagickLibVersionText MagickLibAddendum " " \
  MagickQuantumDepth " " MagickPlatform " " MagickReleaseDate " " \
  MagickAuthoritativeURL
Function Documentation
GetMagickCopyright()
MagickExport const char * GetMagickCopyright (void)
GetMagickDelegates()
MagickExport const char * GetMagickDelegates (void)
GetMagickFeatures()
MagickExport const char * GetMagickFeatures (void)
GetMagickHomeURL()
MagickExport char * GetMagickHomeURL (void)
References AcquireExceptionInfo(), ConstantString(), DestroyExceptionInfo(), DestroyLinkedList(), DirectorySeparator, FormatLocaleString(), GetConfigurePaths(), GetNextValueInLinkedList(), IsPathAccessible(), MagickFalse, MagickHomeURL, MagickURLFilename, MaxTextExtent, and RelinquishMagickMemory().
GetMagickLicense()
MagickExport const char * GetMagickLicense (void)
GetMagickPackageName()
MagickExport const char * GetMagickPackageName (void)
GetMagickQuantumDepth()
MagickExport const char * GetMagickQuantumDepth (size_t *)
GetMagickQuantumRange()
MagickExport const char * GetMagickQuantumRange (size_t *)
GetMagickReleaseDate()
MagickExport const char * GetMagickReleaseDate (void)
GetMagickVersion()
MagickExport const char * GetMagickVersion (size_t * version)
References MagickLibVersion, and MagickVersion.
Referenced by GetMagickProperty(), IdentifyImage(), and ListMagickVersion().
ListMagickVersion()
MagickExport void ListMagickVersion (FILE * file)
References FormatLocaleFile(), GetMagickCopyright(), GetMagickDelegates(), GetMagickFeatures(), GetMagickLicense(), GetMagickPrecision(), GetMagickVersion(), IsEventLogging(), MagickEpsilon, MagickFalse, MaxMap, MaxTextExtent, QuantumRange, and QuantumScale.