MagickCore: version.c File Reference
version.c File Reference
#include "magick/studio.h"
#include "magick/configure.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/hashmap.h"
#include "magick/locale_.h"
#include "magick/memory_.h"
#include "magick/option.h"
#include "magick/string_.h"
#include "magick/utility.h"
#include "magick/version.h"
#include "magick/version-private.h"
Macros
#define MagickURLFilename "index.html"
Functions
MagickExport const char * GetMagickCopyright (void)
MagickExport const char * GetMagickDelegates (void)
MagickExport const char * GetMagickFeatures (void)
MagickExport char * GetMagickHomeURL (void)
MagickExport const char * GetMagickLicense (void)
MagickExport const char * GetMagickPackageName (void)
MagickExport const char * GetMagickQuantumDepth (size_t *depth)
MagickExport const char * GetMagickQuantumRange (size_t *range)
MagickExport const char * GetMagickReleaseDate (void)
static unsigned int CRC32 (const unsigned char *message, const size_t length)
MagickExport unsigned int GetMagickCoreSignature (const StringInfo *nonce)
MagickExport const char * GetMagickVersion (size_t *version)
MagickExport void ListMagickVersion (FILE *file)
Macro Definition Documentation
MagickURLFilename
#define MagickURLFilename "index.html"
Function Documentation
CRC32()
static unsigned int CRC32 (const unsigned char * message, const size_t length) static
References MagickFalse, and MagickTrue.
Referenced by GetMagickCoreSignature().
GetMagickCopyright()
MagickExport const char * GetMagickCopyright (void)
References MagickCopyright.
Referenced by GetMagickProperty(), and ListMagickVersion().
GetMagickCoreSignature()
MagickExport unsigned int GetMagickCoreSignature (const StringInfo * nonce)
References AcquireStringInfo(), ConcatenateStringInfo(), CRC32(), DestroyStringInfo(), GetStringInfoDatum(), GetStringInfoLength(), MAGICKCORE_QUANTUM_DEPTH, MagickLibInterface, MaxTextExtent, and SetStringInfoLength().
Referenced by ConnectPixelCacheServer(), and DistributePixelCacheClient().
GetMagickDelegates()
MagickExport const char * GetMagickDelegates (void)
Referenced by AcquireConfigureCache(), and ListMagickVersion().
GetMagickFeatures()
MagickExport const char * GetMagickFeatures (void)
Referenced by AcquireConfigureCache(), and ListMagickVersion().
GetMagickHomeURL()
MagickExport char * GetMagickHomeURL (void)
References AcquireExceptionInfo(), ConstantString(), DestroyExceptionInfo(), DestroyLinkedList(), DirectorySeparator, FormatLocaleString(), GetConfigurePaths(), GetNextValueInLinkedList(), IsPathAccessible(), MagickFalse, MagickHomeURL, MagickURLFilename, MaxTextExtent, and RelinquishMagickMemory().
GetMagickLicense()
MagickExport const char * GetMagickLicense (void)
References MagickAuthoritativeLicense.
Referenced by ListMagickVersion().
GetMagickPackageName()
MagickExport const char * GetMagickPackageName (void)
References MagickPackageName.
GetMagickQuantumDepth()
MagickExport const char * GetMagickQuantumDepth (size_t * depth)
References MAGICKCORE_QUANTUM_DEPTH, and MagickQuantumDepth.
Referenced by AcquireConfigureCache().
GetMagickQuantumRange()
MagickExport const char * GetMagickQuantumRange (size_t * range)
References MagickQuantumRange, and QuantumRange.
GetMagickReleaseDate()
MagickExport const char * GetMagickReleaseDate (void)
References MagickReleaseDate.
GetMagickVersion()
MagickExport const char * GetMagickVersion (size_t * version)
References MagickLibVersion, and MagickVersion.
Referenced by GetMagickProperty(), IdentifyImage(), and ListMagickVersion().
ListMagickVersion()
MagickExport void ListMagickVersion (FILE * file)
References FormatLocaleFile(), GetMagickCopyright(), GetMagickDelegates(), GetMagickFeatures(), GetMagickLicense(), GetMagickPrecision(), GetMagickVersion(), IsEventLogging(), MagickEpsilon, MagickFalse, MaxMap, MaxTextExtent, QuantumRange, and QuantumScale.