MagickCore: vision.c File Reference
vision.c File Reference
#include "magick/studio.h"
#include "magick/artifact.h"
#include "magick/blob.h"
#include "magick/cache-view.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colormap.h"
#include "magick/colorspace.h"
#include "magick/constitute.h"
#include "magick/decorate.h"
#include "magick/distort.h"
#include "magick/draw.h"
#include "magick/enhance.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/effect.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/log.h"
#include "magick/matrix.h"
#include "magick/memory_.h"
#include "magick/memory-private.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/montage.h"
#include "magick/morphology.h"
#include "magick/morphology-private.h"
#include "magick/opencl-private.h"
#include "magick/paint.h"
#include "magick/pixel-accessor.h"
#include "magick/pixel-private.h"
#include "magick/property.h"
#include "magick/quantum.h"
#include "magick/resource_.h"
#include "magick/signature-private.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/thread-private.h"
#include "magick/token.h"
#include "magick/vision.h"
Data Structures
struct _CCObjectInfo
Macros
#define ConnectedComponentsImageTag "ConnectedComponents/Image"
Typedefs
typedef struct _CCObjectInfo CCObjectInfo
Functions
static int CCObjectInfoCompare (const void *x, const void *y)
MagickExport Image * ConnectedComponentsImage (const Image *image, const size_t connectivity, ExceptionInfo *exception)
Macro Definition Documentation
ConnectedComponentsImageTag
#define ConnectedComponentsImageTag "ConnectedComponents/Image"
Typedef Documentation
CCObjectInfo
typedef struct _CCObjectInfo CCObjectInfo
Function Documentation
CCObjectInfoCompare()
static int CCObjectInfoCompare (const void * x, const void * y) static
References _CCObjectInfo::area.
Referenced by ConnectedComponentsImage().
ConnectedComponentsImage()
MagickExport Image * ConnectedComponentsImage (const Image * image, const size_t connectivity, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireImageColormap(), AcquireMatrixInfo(), AcquireQuantumMemory(), AcquireVirtualCacheView(), _PixelPacket::blue, CCObjectInfoCompare(), ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, ConnectedComponentsImageTag, CopyMagickString(), _Image::debug, _Image::depth, DestroyCacheView(), DestroyImage(), DestroyMatrixInfo(), _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetColorTuple(), GetImageArtifact(), GetMagickModule, GetMagickPixelPacket(), GetMatrixElement(), _PixelPacket::green, _RectangleInfo::height, _CCObjectInfo::id, IsColorSimilar(), IsMagickColorSimilar(), IsMagickTrue(), IsStringTrue(), LogMagickEvent(), magick_restrict, MAGICKCORE_QUANTUM_DEPTH, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickMin, MagickPathExtent, MagickTrue, _Image::matte, MaxColormapSize, MaxTextExtent, _PixelPacket::opacity, _Image::progress_monitor, QuantumScale, QueryMagickColor(), QueueCacheViewAuthenticPixels(), _PixelPacket::red, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetMatrixElement(), _ExceptionInfo::signature, _Image::signature, StringToDouble(), SyncCacheViewAuthenticPixels(), SyncImage(), ThrowImageException, TraceEvent, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.