MagickCore: vision.h File Reference
vision.h File Reference
Functions
MagickExport Image * ConnectedComponentsImage (const Image *, const size_t, ExceptionInfo *)
Function Documentation
ConnectedComponentsImage()
MagickExport Image * ConnectedComponentsImage (const Image * image, const size_t, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireImageColormap(), AcquireMatrixInfo(), AcquireQuantumMemory(), AcquireVirtualCacheView(), _PixelPacket::blue, CCObjectInfoCompare(), ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, ConnectedComponentsImageTag, CopyMagickString(), _Image::debug, _Image::depth, DestroyCacheView(), DestroyImage(), DestroyMatrixInfo(), _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetColorTuple(), GetImageArtifact(), GetMagickModule, GetMagickPixelPacket(), GetMatrixElement(), _PixelPacket::green, _RectangleInfo::height, _CCObjectInfo::id, IsColorSimilar(), IsMagickColorSimilar(), IsMagickTrue(), IsStringTrue(), LogMagickEvent(), magick_restrict, MAGICKCORE_QUANTUM_DEPTH, MagickCoreSignature, MagickEpsilon, MagickFalse, MagickMin, MagickPathExtent, MagickTrue, _Image::matte, MaxColormapSize, MaxTextExtent, _PixelPacket::opacity, _Image::progress_monitor, QuantumScale, QueryMagickColor(), QueueCacheViewAuthenticPixels(), _PixelPacket::red, RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetMatrixElement(), _ExceptionInfo::signature, _Image::signature, StringToDouble(), SyncCacheViewAuthenticPixels(), SyncImage(), ThrowImageException, TraceEvent, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.