MagickCore: visual-effects.h File Reference
visual-effects.h File Reference
#include "magick/draw.h"
Enumerations
enum NoiseType {
UndefinedNoise , UniformNoise , GaussianNoise , MultiplicativeGaussianNoise ,
ImpulseNoise , LaplacianNoise , PoissonNoise , RandomNoise
}
Functions
MagickExport Image * AddNoiseImage (const Image *, const NoiseType, ExceptionInfo *)
MagickExport Image * AddNoiseImageChannel (const Image *, const ChannelType, const NoiseType, ExceptionInfo *)
MagickExport Image * BlueShiftImage (const Image *, const double, ExceptionInfo *)
MagickExport Image * CharcoalImage (const Image *, const double, const double, ExceptionInfo *)
MagickExport Image * ColorizeImage (const Image *, const char *, const PixelPacket, ExceptionInfo *)
MagickExport Image * ColorMatrixImage (const Image *, const KernelInfo *kernel, ExceptionInfo *)
MagickExport Image * ImplodeImage (const Image *, const double, ExceptionInfo *)
MagickExport Image * MorphImages (const Image *, const size_t, ExceptionInfo *)
MagickExport Image * PolaroidImage (const Image *, const DrawInfo *, const double, ExceptionInfo *)
MagickExport Image * SepiaToneImage (const Image *, const double, ExceptionInfo *)
MagickExport Image * ShadowImage (const Image *, const double, const double, const ssize_t, const ssize_t, ExceptionInfo *)
MagickExport Image * SketchImage (const Image *, const double, const double, const double, ExceptionInfo *)
MagickExport Image * SteganoImage (const Image *, const Image *, ExceptionInfo *)
MagickExport Image * StereoImage (const Image *, const Image *, ExceptionInfo *)
MagickExport Image * StereoAnaglyphImage (const Image *, const Image *, const ssize_t, const ssize_t, ExceptionInfo *)
MagickExport Image * SwirlImage (const Image *, double, ExceptionInfo *)
MagickExport Image * TintImage (const Image *, const char *, const PixelPacket, ExceptionInfo *)
MagickExport Image * VignetteImage (const Image *, const double, const double, const ssize_t, const ssize_t, ExceptionInfo *)
MagickExport Image * WaveImage (const Image *, const double, const double, ExceptionInfo *)
MagickExport Image * WaveletDenoiseImage (const Image *, const double, const double, ExceptionInfo *)
MagickExport MagickBooleanType PlasmaImage (Image *, const SegmentInfo *, size_t, size_t)
MagickExport MagickBooleanType SolarizeImage (Image *, const double)
MagickExport MagickBooleanType SolarizeImageChannel (Image *, const ChannelType, const double, ExceptionInfo *)
Enumeration Type Documentation
NoiseType
enum NoiseType
Enumerator
UndefinedNoise
UniformNoise
GaussianNoise
MultiplicativeGaussianNoise
ImpulseNoise
LaplacianNoise
PoissonNoise
RandomNoise
Function Documentation
AddNoiseImage()
MagickExport Image * AddNoiseImage (const Image * , const NoiseType, ExceptionInfo *)
AddNoiseImageChannel()
MagickExport Image * AddNoiseImageChannel (const Image * , const ChannelType, const NoiseType, ExceptionInfo *)
BlueShiftImage()
MagickExport Image * BlueShiftImage (const Image * , const double , ExceptionInfo *)
CharcoalImage()
MagickExport Image * CharcoalImage (const Image * , const double , const double , ExceptionInfo *)
ColorizeImage()
MagickExport Image * ColorizeImage (const Image * , const char * , const PixelPacket, ExceptionInfo *)
ColorMatrixImage()
MagickExport Image * ColorMatrixImage (const Image * , const KernelInfo * kernel, ExceptionInfo *)
ImplodeImage()
MagickExport Image * ImplodeImage (const Image * , const double , ExceptionInfo *)
MorphImages()
MagickExport Image * MorphImages (const Image * , const size_t, ExceptionInfo *)
PlasmaImage()
MagickExport MagickBooleanType PlasmaImage (Image * , const SegmentInfo * , size_t , size_t)
PolaroidImage()
MagickExport Image * PolaroidImage (const Image * , const DrawInfo * , const double , ExceptionInfo *)
SepiaToneImage()
MagickExport Image * SepiaToneImage (const Image * , const double , ExceptionInfo *)
ShadowImage()
MagickExport Image * ShadowImage (const Image * , const double , const double , const ssize_t, const ssize_t, ExceptionInfo *)
SketchImage()
MagickExport Image * SketchImage (const Image * , const double , const double , const double , ExceptionInfo *)
SolarizeImage()
MagickExport MagickBooleanType SolarizeImage (Image * , const double)
SolarizeImageChannel()
MagickExport MagickBooleanType SolarizeImageChannel (Image * image, const ChannelType, const double threshold, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), _PixelPacket::blue, BlueChannel, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelRed, _PixelPacket::green, GreenChannel, IsGrayColorspace(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::progress_monitor, PseudoClass, QuantumRange, _PixelPacket::red, RedChannel, _Image::rows, SetImageColorspace(), SetImageProgress(), SetPixelBlue, SetPixelGreen, SetPixelRed, _Image::signature, SolarizeImageTag, sRGBColorspace, _Image::storage_class, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by SolarizeImage().
SteganoImage()
MagickExport Image * SteganoImage (const Image * , const Image * , ExceptionInfo *)
StereoAnaglyphImage()
MagickExport Image * StereoAnaglyphImage (const Image * , const Image * , const ssize_t, const ssize_t, ExceptionInfo *)
StereoImage()
MagickExport Image * StereoImage (const Image * , const Image * , ExceptionInfo *)
SwirlImage()
MagickExport Image * SwirlImage (const Image * , double , ExceptionInfo *)
TintImage()
MagickExport Image * TintImage (const Image * , const char * , const PixelPacket, ExceptionInfo *)
VignetteImage()
MagickExport Image * VignetteImage (const Image * , const double , const double , const ssize_t, const ssize_t, ExceptionInfo *)
WaveImage()
MagickExport Image * WaveImage (const Image * , const double , const double , ExceptionInfo *)
WaveletDenoiseImage()
MagickExport Image * WaveletDenoiseImage (const Image * image, const double threshold, const double softness, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireMagickResource(), AcquireQuantumMemory(), AcquireVirtualMemory(), AddNoiseImageTag, ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetMagickModule, GetOpenMPMaximumThreads(), GetOpenMPThreadId(), GetPixelBlue, GetPixelGreen, GetPixelRed, GetVirtualMemoryBlob(), HatTransform(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickMax, MagickTrue, _Image::progress_monitor, RelinquishMagickMemory(), RelinquishVirtualMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, and WidthResource.