MagickCore: visual-effects.c File Reference
visual-effects.c File Reference
#include "magick/studio.h"
#include "magick/accelerate-private.h"
#include "magick/annotate.h"
#include "magick/artifact.h"
#include "magick/attribute.h"
#include "magick/cache.h"
#include "magick/cache-view.h"
#include "magick/channel.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colorspace.h"
#include "magick/colorspace-private.h"
#include "magick/composite.h"
#include "magick/decorate.h"
#include "magick/distort.h"
#include "magick/draw.h"
#include "magick/effect.h"
#include "magick/enhance.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/gem.h"
#include "magick/geometry.h"
#include "magick/layer.h"
#include "magick/list.h"
#include "magick/log.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/memory-private.h"
#include "magick/monitor.h"
#include "magick/monitor-private.h"
#include "magick/opencl-private.h"
#include "magick/option.h"
#include "magick/pixel-accessor.h"
#include "magick/pixel-private.h"
#include "magick/property.h"
#include "magick/quantum.h"
#include "magick/quantum-private.h"
#include "magick/random_.h"
#include "magick/random-private.h"
#include "magick/resample.h"
#include "magick/resample-private.h"
#include "magick/resize.h"
#include "magick/resource_.h"
#include "magick/splay-tree.h"
#include "magick/statistic.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/thread-private.h"
#include "magick/threshold.h"
#include "magick/transform.h"
#include "magick/utility.h"
#include "magick/visual-effects.h"
Macros
#define AddNoiseImageTag "AddNoise/Image"
#define BlueShiftImageTag "BlueShift/Image"
#define ColorizeImageTag "Colorize/Image"
#define ColorMatrixImageTag "ColorMatrix/Image"
#define ImplodeImageTag "Implode/Image"
#define MorphImageTag "Morph/Image"
#define SepiaToneImageTag "SepiaTone/Image"
#define ShadowImageTag "Shadow/Image"
#define SolarizeImageTag "Solarize/Image"
#define GetBit(alpha, i) ((((size_t) (alpha) >> (size_t) (i)) & 0x01) != 0)
#define SetBit(alpha, i, set)
#define SteganoImageTag "Stegano/Image"
#define StereoImageTag "Stereo/Image"
#define SwirlImageTag "Swirl/Image"
#define TintImageTag "Tint/Image"
#define WaveImageTag "Wave/Image"
Functions
MagickExport Image * AddNoiseImage (const Image *image, const NoiseType noise_type, ExceptionInfo *exception)
MagickExport Image * AddNoiseImageChannel (const Image *image, const ChannelType channel, const NoiseType noise_type, ExceptionInfo *exception)
MagickExport Image * BlueShiftImage (const Image *image, const double factor, ExceptionInfo *exception)
MagickExport Image * CharcoalImage (const Image *image, const double radius, const double sigma, ExceptionInfo *exception)
MagickExport Image * ColorizeImage (const Image *image, const char *opacity, const PixelPacket colorize, ExceptionInfo *exception)
MagickExport Image * ColorMatrixImage (const Image *image, const KernelInfo *color_matrix, ExceptionInfo *exception)
MagickExport Image * ImplodeImage (const Image *image, const double amount, ExceptionInfo *exception)
MagickExport Image * MorphImages (const Image *image, const size_t number_frames, ExceptionInfo *exception)
static Quantum PlasmaPixel (RandomInfo *magick_restrict random_info, const MagickRealType pixel, const double noise)
MagickExport MagickBooleanType PlasmaImageProxy (Image *image, CacheView *image_view, CacheView *u_view, CacheView *v_view, RandomInfo *magick_restrict random_info, const SegmentInfo *magick_restrict segment, size_t attenuate, size_t depth)
MagickExport MagickBooleanType PlasmaImage (Image *image, const SegmentInfo *segment, size_t attenuate, size_t depth)
MagickExport Image * PolaroidImage (const Image *image, const DrawInfo *draw_info, const double angle, ExceptionInfo *exception)
MagickExport Image * SepiaToneImage (const Image *image, const double threshold, ExceptionInfo *exception)
MagickExport Image * ShadowImage (const Image *image, const double opacity, const double sigma, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo *exception)
MagickExport Image * SketchImage (const Image *image, const double radius, const double sigma, const double angle, ExceptionInfo *exception)
MagickExport MagickBooleanType SolarizeImage (Image *image, const double threshold)
MagickExport MagickBooleanType SolarizeImageChannel (Image *image, const ChannelType channel, const double threshold, ExceptionInfo *exception)
MagickExport Image * SteganoImage (const Image *image, const Image *watermark, ExceptionInfo *exception)
MagickExport Image * StereoImage (const Image *left_image, const Image *right_image, ExceptionInfo *exception)
MagickExport Image * StereoAnaglyphImage (const Image *left_image, const Image *right_image, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo *exception)
MagickExport Image * SwirlImage (const Image *image, double degrees, ExceptionInfo *exception)
MagickExport Image * TintImage (const Image *image, const char *opacity, const PixelPacket tint, ExceptionInfo *exception)
MagickExport Image * VignetteImage (const Image *image, const double radius, const double sigma, const ssize_t x, const ssize_t y, ExceptionInfo *exception)
MagickExport Image * WaveImage (const Image *image, const double amplitude, const double wave_length, ExceptionInfo *exception)
static void HatTransform (const float *magick_restrict pixels, const size_t stride, const size_t extent, const size_t scale, float *kernel)
MagickExport Image * WaveletDenoiseImage (const Image *image, const double threshold, const double softness, ExceptionInfo *exception)
Macro Definition Documentation
AddNoiseImageTag
#define AddNoiseImageTag "AddNoise/Image"
BlueShiftImageTag
#define BlueShiftImageTag "BlueShift/Image"
ColorizeImageTag
#define ColorizeImageTag "Colorize/Image"
ColorMatrixImageTag
#define ColorMatrixImageTag "ColorMatrix/Image"
GetBit
#define GetBit (alpha, i) ((((size_t) (alpha) >> (size_t) (i)) & 0x01) != 0)
ImplodeImageTag
#define ImplodeImageTag "Implode/Image"
MorphImageTag
#define MorphImageTag "Morph/Image"
SepiaToneImageTag
#define SepiaToneImageTag "SepiaTone/Image"
SetBit
#define SetBit (alpha, i, set)
Value:
  (alpha)=(Quantum) ((set) != 0 ? (size_t) (alpha) \
  | (one << (size_t) (i)) : (size_t) (alpha) & ~(one << (size_t) (i)))
ShadowImageTag
#define ShadowImageTag "Shadow/Image"
SolarizeImageTag
#define SolarizeImageTag "Solarize/Image"
SteganoImageTag
#define SteganoImageTag "Stegano/Image"
StereoImageTag
#define StereoImageTag "Stereo/Image"
SwirlImageTag
#define SwirlImageTag "Swirl/Image"
TintImageTag
#define TintImageTag "Tint/Image"
WaveImageTag
#define WaveImageTag "Wave/Image"
Function Documentation
AddNoiseImage()
MagickExport Image * AddNoiseImage (const Image * image, const NoiseType noise_type, ExceptionInfo * exception)
References AddNoiseImageChannel(), and DefaultChannels.
AddNoiseImageChannel()
MagickExport Image * AddNoiseImageChannel (const Image * image, const ChannelType channel, const NoiseType noise_type, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireRandomInfoThreadSet(), AcquireVirtualCacheView(), AddNoiseImageTag, BlueChannel, ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DestroyRandomInfoThreadSet(), DirectClass, _Image::exception, _Image::filename, GenerateDifferentialNoise(), GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetImageArtifact(), GetMagickModule, GetOpenMPThreadId(), GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, GetRandomSecretKey(), GreenChannel, IndexChannel, InheritException(), IsGrayColorspace(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, OpacityChannel, _Image::progress_monitor, random_info, RedChannel, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, StringToDouble(), SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by AddNoiseImage().
BlueShiftImage()
MagickExport Image * BlueShiftImage (const Image * image, const double factor, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, BlueShiftImageTag, ClampToQuantum(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelRed, _MagickPixelPacket::green, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::progress_monitor, QueueCacheViewAuthenticPixels(), _MagickPixelPacket::red, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
CharcoalImage()
MagickExport Image * CharcoalImage (const Image * image, const double radius, const double sigma, ExceptionInfo * exception)
References BlurImage(), ClampImage(), _Image::debug, DestroyImage(), EdgeImage(), _Image::filename, GetMagickModule, GrayscaleImage(), _Image::intensity, LogMagickEvent(), MagickCoreSignature, MagickFalse, NegateImage(), NormalizeImage(), _ExceptionInfo::signature, _Image::signature, and TraceEvent.
Referenced by PreviewImage().
ColorizeImage()
MagickExport Image * ColorizeImage (const Image * image, const char * opacity, const PixelPacket colorize, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, _PixelPacket::blue, CloneImage(), ColorizeImageTag, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelOpacity, GetPixelRed, _MagickPixelPacket::green, _PixelPacket::green, InheritException(), IsGrayColorspace(), IsPixelGray(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _MagickPixelPacket::opacity, _PixelPacket::opacity, OpaqueAlphaChannel, OpaqueOpacity, ParseGeometry(), _Image::progress_monitor, _GeometryInfo::psi, PsiValue, QueueCacheViewAuthenticPixels(), _MagickPixelPacket::red, _PixelPacket::red, _GeometryInfo::rho, _Image::rows, SetImageAlphaChannel(), SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelOpacity, SetPixelRed, _GeometryInfo::sigma, SigmaValue, _ExceptionInfo::signature, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), TraceEvent, _GeometryInfo::xi, and XiValue.
ColorMatrixImage()
MagickExport Image * ColorMatrixImage (const Image * image, const KernelInfo * color_matrix, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireString(), AcquireVirtualCacheView(), ClampToQuantum(), CloneImage(), CMYKColorspace, ColorMatrixImageTag, _Image::colorspace, _Image::columns, ConcatenateString(), _Image::debug, DestroyCacheView(), DestroyImage(), DestroyString(), DirectClass, _Image::exception, _Image::filename, FormatLocaleString(), GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIndex, GetPixelOpacity, GetPixelRed, KernelInfo::height, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, MaxTextExtent, _Image::progress_monitor, QuantumRange, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelAlpha, SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, TransformEvent, KernelInfo::values, and KernelInfo::width.
Referenced by RecolorImage().
HatTransform()
static void HatTransform (const float *magick_restrict pixels, const size_t stride, const size_t extent, const size_t scale, float * kernel) inline static
References magick_restrict.
Referenced by WaveletDenoiseImage().
ImplodeImage()
MagickExport Image * ImplodeImage (const Image * image, const double amount, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _Image::background_color, CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickPixelPacket(), ImplodeImageTag, InheritException(), InterpolateMagickPixelPacket(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickPI, MagickTrue, _Image::matte, _PixelPacket::opacity, OpaqueOpacity, PerceptibleReciprocal(), _Image::progress_monitor, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelPacket(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), TraceEvent, UndefinedInterpolatePixel, _PointInfo::x, and _PointInfo::y.
Referenced by PreviewImage().
MorphImages()
MagickExport Image * MorphImages (const Image * image, const size_t number_frames, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), AppendImageToList(), _Image::blur, ClampToQuantum(), CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DestroyImageList(), DirectClass, _Image::exception, _Image::filename, _Image::filter, GetCacheViewAuthenticPixels(), GetCacheViewVirtualPixels(), GetFirstImageInList(), GetImageListLength(), GetLastImageInList(), GetMagickModule, GetNextImageInList(), GetPixelBlue, GetPixelGreen, GetPixelOpacity, GetPixelRed, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, MorphImageTag, _Image::progress_monitor, ResizeImage(), _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
PlasmaImage()
MagickExport MagickBooleanType PlasmaImage (Image * image, const SegmentInfo * segment, size_t attenuate, size_t depth)
References AcquireAuthenticCacheView(), AcquireRandomInfo(), AcquireVirtualCacheView(), _Image::debug, DestroyCacheView(), DestroyRandomInfo(), DirectClass, _Image::exception, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, PlasmaImageProxy(), random_info, SetImageStorageClass(), _Image::signature, and TraceEvent.
PlasmaImageProxy()
MagickExport MagickBooleanType PlasmaImageProxy (Image * image, CacheView * image_view, CacheView * u_view, CacheView * v_view, RandomInfo *magick_restrict random_info, const SegmentInfo *magick_restrict segment, size_t attenuate, size_t depth)
References _PixelPacket::blue, CastDoubleToLong(), _Image::exception, GetOneCacheViewVirtualPixel(), _PixelPacket::green, magick_restrict, MagickEpsilon, MagickFalse, MagickTrue, PlasmaImageProxy(), PlasmaPixel(), QuantumRange, QueueCacheViewAuthenticPixels(), random_info, _PixelPacket::red, SetPixelBlue, SetPixelGreen, SetPixelRed, SyncCacheViewAuthenticPixels(), _SegmentInfo::x1, _SegmentInfo::x2, _SegmentInfo::y1, and _SegmentInfo::y2.
Referenced by PlasmaImage(), and PlasmaImageProxy().
PlasmaPixel()
static Quantum PlasmaPixel (RandomInfo *magick_restrict random_info, const MagickRealType pixel, const double noise) inline static
References ClampToQuantum(), GetPseudoRandomValue(), and random_info.
Referenced by PlasmaImageProxy().
PolaroidImage()
MagickExport Image * PolaroidImage (const Image * image, const DrawInfo * draw_info, const double angle, ExceptionInfo * exception)
References AcquireString(), AnnotateImage(), _TypeMetric::ascent, _Image::background_color, _Image::border_color, CloneDrawInfo(), CloneImage(), CloneString(), _Image::columns, CompositeImage(), _Image::debug, _TypeMetric::descent, DestroyDrawInfo(), DestroyImage(), DestroyString(), _Image::exception, _Image::filename, FlopImage(), FormatLocaleString(), FormatMagickCaption(), _DrawInfo::geometry, GetImageProperty(), GetMagickModule, _DrawInfo::gravity, InheritException(), InterpretImageProperties(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickMax, MagickTrue, MaxTextExtent, OpaqueAlphaChannel, OverCompositeOp, QueryColorDatabase(), RotateImage(), _Image::rows, SetImageAlphaChannel(), SetImageBackgroundColor(), SetImageExtent(), ShadowImage(), _ExceptionInfo::signature, _Image::signature, _DrawInfo::text, TraceEvent, TrimImage(), UndefinedGravity, and WaveImage().
SepiaToneImage()
MagickExport Image * SepiaToneImage (const Image * image, const double threshold, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), ClampToQuantum(), CloneImage(), _Image::columns, ContrastImage(), _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelIntensity(), GetPixelOpacity, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, NormalizeImage(), _Image::progress_monitor, QuantumRange, QueueCacheViewAuthenticPixels(), _Image::rows, SepiaToneImageTag, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), and TraceEvent.
ShadowImage()
MagickExport Image * ShadowImage (const Image * image, const double opacity, const double sigma, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AlphaChannel, _Image::background_color, _PixelPacket::blue, BlurImageChannel(), _Image::border_color, BorderImage(), CastDoubleToUnsigned(), ClampToQuantum(), CloneImage(), _Image::colorspace, _Image::columns, _Image::compose, _Image::debug, DestroyCacheView(), DestroyImage(), EdgeVirtualPixelMethod, _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelAlpha, _PixelPacket::green, _RectangleInfo::height, IsGrayColorspace(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, _PixelPacket::opacity, OpaqueAlphaChannel, OverCompositeOp, _Image::page, _Image::progress_monitor, QuantumRange, QueryColorDatabase(), _PixelPacket::red, _Image::rows, SetImageAlphaChannel(), SetImageColorspace(), SetImageProgress(), SetImageVirtualPixelMethod(), SetPixelBlue, SetPixelGreen, SetPixelOpacity, SetPixelRed, ShadowImageTag, _ExceptionInfo::signature, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), TraceEvent, _RectangleInfo::width, _RectangleInfo::x, and _RectangleInfo::y.
Referenced by MontageImageList(), and PolaroidImage().
SketchImage()
MagickExport Image * SketchImage (const Image * image, const double radius, const double sigma, const double angle, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireRandomInfoThreadSet(), BlendCompositeOp, _MagickPixelPacket::blue, ClampImage(), CloneImage(), CMYKColorspace, ColorDodgeCompositeOp, _Image::colorspace, _Image::columns, CompositeImage(), DestroyCacheView(), DestroyImage(), DestroyRandomInfoThreadSet(), EdgeImage(), GetCacheViewAuthenticIndexQueue(), GetMagickPixelPacket(), GetOpenMPThreadId(), GetPseudoRandomValue(), GetRandomSecretKey(), _MagickPixelPacket::green, _MagickPixelPacket::index, magick_restrict, MagickFalse, MagickTrue, MotionBlurImage(), NegateImage(), NormalizeImage(), QuantumRange, QueueCacheViewAuthenticPixels(), random_info, _MagickPixelPacket::red, _Image::rows, SetImageArtifact(), SetPixelPacket(), SyncCacheViewAuthenticPixels(), and TransformImage().
SolarizeImage()
MagickExport MagickBooleanType SolarizeImage (Image * image, const double threshold)
References DefaultChannels, _Image::exception, and SolarizeImageChannel().
Referenced by PreviewImage().
SolarizeImageChannel()
MagickExport MagickBooleanType SolarizeImageChannel (Image * image, const ChannelType channel, const double threshold, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), _PixelPacket::blue, BlueChannel, _Image::colormap, _Image::colors, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), _Image::filename, GetCacheViewAuthenticPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelRed, _PixelPacket::green, GreenChannel, IsGrayColorspace(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::progress_monitor, PseudoClass, QuantumRange, _PixelPacket::red, RedChannel, _Image::rows, SetImageColorspace(), SetImageProgress(), SetPixelBlue, SetPixelGreen, SetPixelRed, _Image::signature, SolarizeImageTag, sRGBColorspace, _Image::storage_class, SyncCacheViewAuthenticPixels(), and TraceEvent.
Referenced by SolarizeImage().
SteganoImage()
MagickExport Image * SteganoImage (const Image * image, const Image * watermark, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), ClampToQuantum(), CloneImage(), _Image::columns, _Image::debug, _Image::depth, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetBit, GetCacheViewAuthenticPixels(), GetMagickModule, GetOneCacheViewVirtualPixel(), GetPixelBlue, GetPixelGreen, GetPixelIntensity(), GetPixelRed, InheritException(), LogMagickEvent(), MAGICKCORE_QUANTUM_DEPTH, MagickCoreSignature, MagickFalse, MagickTrue, _Image::offset, _Image::progress_monitor, PseudoClass, _Image::rows, SetBit, SetImageProgress(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, SteganoImageTag, _Image::storage_class, SyncCacheViewAuthenticPixels(), SyncImage(), and TraceEvent.
StereoAnaglyphImage()
MagickExport Image * StereoAnaglyphImage (const Image * left_image, const Image * right_image, const ssize_t x_offset, const ssize_t y_offset, ExceptionInfo * exception)
References CloneImage(), _Image::columns, _Image::debug, DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelOpacity, GetPixelRed, GetVirtualPixels(), ImageError, InheritException(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _Image::progress_monitor, QueueAuthenticPixels(), _Image::rows, SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelOpacity, SetPixelRed, _ExceptionInfo::signature, _Image::signature, sRGBColorspace, StereoImageTag, SyncAuthenticPixels(), ThrowImageException, and TraceEvent.
Referenced by StereoImage().
StereoImage()
MagickExport Image * StereoImage (const Image * left_image, const Image * right_image, ExceptionInfo * exception)
References StereoAnaglyphImage().
SwirlImage()
MagickExport Image * SwirlImage (const Image * image, double degrees, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _Image::background_color, CloneImage(), _Image::columns, _Image::debug, DegreesToRadians(), DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetMagickModule, GetMagickPixelPacket(), InheritException(), InterpolateMagickPixelPacket(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickMax, MagickTrue, _Image::matte, _PixelPacket::opacity, OpaqueOpacity, _Image::progress_monitor, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelPacket(), _ExceptionInfo::signature, _Image::signature, SwirlImageTag, SyncCacheViewAuthenticPixels(), TraceEvent, UndefinedInterpolatePixel, _PointInfo::x, and _PointInfo::y.
Referenced by PreviewImage().
TintImage()
MagickExport Image * TintImage (const Image * image, const char * opacity, const PixelPacket tint, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireVirtualCacheView(), _MagickPixelPacket::blue, _PixelPacket::blue, ClampToQuantum(), CloneImage(), _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewVirtualPixels(), GetMagickModule, GetPixelBlue, GetPixelGreen, GetPixelOpacity, GetPixelRed, _MagickPixelPacket::green, _PixelPacket::green, InheritException(), IsGrayColorspace(), IsPixelGray(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickTrue, _MagickPixelPacket::opacity, OpaqueOpacity, ParseGeometry(), PixelPacketIntensity(), _Image::progress_monitor, _GeometryInfo::psi, PsiValue, QuantumScale, QueueCacheViewAuthenticPixels(), _MagickPixelPacket::red, _PixelPacket::red, _GeometryInfo::rho, _Image::rows, SetImageColorspace(), SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelOpacity, SetPixelRed, _GeometryInfo::sigma, SigmaValue, _ExceptionInfo::signature, _Image::signature, sRGBColorspace, SyncCacheViewAuthenticPixels(), TintImageTag, TraceEvent, _GeometryInfo::xi, and XiValue.
VignetteImage()
MagickExport Image * VignetteImage (const Image * image, const double radius, const double sigma, const ssize_t x, const ssize_t y, ExceptionInfo * exception)
References AcquireString(), _Image::background_color, BlurImage(), CloneDrawInfo(), CloneImage(), _Image::colorspace, _Image::columns, CompositeImage(), CopyOpacityCompositeOp, _Image::debug, DestroyDrawInfo(), DestroyImage(), DirectClass, DrawImage(), _Image::exception, _Image::filename, _DrawInfo::fill, FlattenLayer, FormatLocaleString(), GetMagickModule, InheritException(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _Image::matte, MaxTextExtent, MergeImageLayers(), _DrawInfo::primitive, QueryColorDatabase(), _Image::rows, SetImageBackgroundColor(), SetImageStorageClass(), _ExceptionInfo::signature, _Image::signature, _DrawInfo::stroke, TraceEvent, and TransformImageColorspace().
WaveImage()
MagickExport Image * WaveImage (const Image * image, const double amplitude, const double wave_length, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireQuantumMemory(), AcquireVirtualCacheView(), _Image::background_color, BackgroundVirtualPixelMethod, CloneImage(), _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::exception, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetMagickModule, GetMagickPixelPacket(), InheritException(), InterpolateMagickPixelPacket(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickPI, MagickTrue, _Image::matte, _PixelPacket::opacity, OpaqueOpacity, PerceptibleReciprocal(), _Image::progress_monitor, QueueCacheViewAuthenticPixels(), RelinquishMagickMemory(), ResourceLimitError, _Image::rows, SetCacheViewVirtualPixelMethod(), SetImageProgress(), SetImageStorageClass(), SetPixelPacket(), _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, UndefinedInterpolatePixel, and WaveImageTag.
Referenced by PolaroidImage(), and PreviewImage().
WaveletDenoiseImage()
MagickExport Image * WaveletDenoiseImage (const Image * image, const double threshold, const double softness, ExceptionInfo * exception)
References AcquireAuthenticCacheView(), AcquireMagickResource(), AcquireQuantumMemory(), AcquireVirtualMemory(), AddNoiseImageTag, ClampToQuantum(), CloneImage(), CMYKColorspace, _Image::colorspace, _Image::columns, _Image::debug, DestroyCacheView(), DestroyImage(), DirectClass, _Image::filename, GetCacheViewAuthenticIndexQueue(), GetCacheViewAuthenticPixels(), GetCacheViewVirtualIndexQueue(), GetMagickModule, GetOpenMPMaximumThreads(), GetOpenMPThreadId(), GetPixelBlue, GetPixelGreen, GetPixelRed, GetVirtualMemoryBlob(), HatTransform(), LogMagickEvent(), magick_restrict, MagickCoreSignature, MagickFalse, MagickMax, MagickTrue, _Image::progress_monitor, RelinquishMagickMemory(), RelinquishVirtualMemory(), ResourceLimitError, _Image::rows, SetImageProgress(), SetImageStorageClass(), SetPixelBlue, SetPixelGreen, SetPixelIndex, SetPixelRed, _ExceptionInfo::signature, _Image::signature, SyncCacheViewAuthenticPixels(), ThrowImageException, TraceEvent, and WidthResource.