MagickCore: xml-tree.h File Reference
xml-tree.h File Reference
#include "magick/exception.h"
#include "magick/splay-tree.h"
Typedefs
typedef struct _XMLTreeInfo XMLTreeInfo
Functions
MagickExport char * CanonicalXMLContent (const char *, const MagickBooleanType)
MagickExport char * XMLTreeInfoToXML (XMLTreeInfo *)
MagickExport const char * GetXMLTreeAttribute (XMLTreeInfo *, const char *)
MagickExport const char * GetXMLTreeContent (XMLTreeInfo *)
MagickExport const char ** GetXMLTreeProcessingInstructions (XMLTreeInfo *, const char *)
MagickExport const char * GetXMLTreeTag (XMLTreeInfo *)
MagickExport MagickBooleanType GetXMLTreeAttributes (const XMLTreeInfo *, SplayTreeInfo *)
MagickExport XMLTreeInfo * AddChildToXMLTree (XMLTreeInfo *, const char *, const size_t)
MagickExport XMLTreeInfo * AddPathToXMLTree (XMLTreeInfo *, const char *, const size_t)
MagickExport XMLTreeInfo * DestroyXMLTree (XMLTreeInfo *)
MagickExport XMLTreeInfo * GetNextXMLTreeTag (XMLTreeInfo *)
MagickExport XMLTreeInfo * GetXMLTreeChild (XMLTreeInfo *, const char *)
MagickExport XMLTreeInfo * GetXMLTreeOrdered (XMLTreeInfo *)
MagickExport XMLTreeInfo * GetXMLTreePath (XMLTreeInfo *, const char *)
MagickExport XMLTreeInfo * GetXMLTreeSibling (XMLTreeInfo *)
MagickExport XMLTreeInfo * InsertTagIntoXMLTree (XMLTreeInfo *, XMLTreeInfo *, const size_t)
MagickExport XMLTreeInfo * NewXMLTree (const char *, ExceptionInfo *)
MagickExport XMLTreeInfo * NewXMLTreeTag (const char *)
MagickExport XMLTreeInfo * ParseTagFromXMLTree (XMLTreeInfo *)
MagickExport XMLTreeInfo * PruneTagFromXMLTree (XMLTreeInfo *)
MagickExport XMLTreeInfo * SetXMLTreeAttribute (XMLTreeInfo *, const char *, const char *)
MagickExport XMLTreeInfo * SetXMLTreeContent (XMLTreeInfo *, const char *)
Typedef Documentation
XMLTreeInfo
typedef struct _XMLTreeInfo XMLTreeInfo
Function Documentation
AddChildToXMLTree()
MagickExport XMLTreeInfo * AddChildToXMLTree (XMLTreeInfo * , const char * , const size_t)
AddPathToXMLTree()
MagickExport XMLTreeInfo * AddPathToXMLTree (XMLTreeInfo * , const char * , const size_t)
CanonicalXMLContent()
MagickExport char * CanonicalXMLContent (const char * , const MagickBooleanType)
DestroyXMLTree()
MagickExport XMLTreeInfo * DestroyXMLTree (XMLTreeInfo *)
GetNextXMLTreeTag()
MagickExport XMLTreeInfo * GetNextXMLTreeTag (XMLTreeInfo *)
GetXMLTreeAttribute()
MagickExport const char * GetXMLTreeAttribute (XMLTreeInfo * , const char *)
GetXMLTreeAttributes()
MagickExport MagickBooleanType GetXMLTreeAttributes (const XMLTreeInfo * xml_info, SplayTreeInfo * attributes)
References AddValueToSplayTree(), _XMLTreeInfo::attributes, ConstantString(), _XMLTreeInfo::debug, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _XMLTreeInfo::signature, and TraceEvent.
GetXMLTreeChild()
MagickExport XMLTreeInfo * GetXMLTreeChild (XMLTreeInfo * , const char *)
GetXMLTreeContent()
MagickExport const char * GetXMLTreeContent (XMLTreeInfo *)
GetXMLTreeOrdered()
MagickExport XMLTreeInfo * GetXMLTreeOrdered (XMLTreeInfo *)
GetXMLTreePath()
MagickExport XMLTreeInfo * GetXMLTreePath (XMLTreeInfo * , const char *)
GetXMLTreeProcessingInstructions()
MagickExport const char ** GetXMLTreeProcessingInstructions (XMLTreeInfo * , const char *)
GetXMLTreeSibling()
MagickExport XMLTreeInfo * GetXMLTreeSibling (XMLTreeInfo *)
GetXMLTreeTag()
MagickExport const char * GetXMLTreeTag (XMLTreeInfo * xml_info)
References _XMLTreeInfo::debug, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _XMLTreeInfo::signature, _XMLTreeInfo::tag, and TraceEvent.
Referenced by GetXMPProperty().
InsertTagIntoXMLTree()
MagickExport XMLTreeInfo * InsertTagIntoXMLTree (XMLTreeInfo * , XMLTreeInfo * , const size_t)
NewXMLTree()
MagickExport XMLTreeInfo * NewXMLTree (const char * , ExceptionInfo *)
NewXMLTreeTag()
MagickExport XMLTreeInfo * NewXMLTreeTag (const char *)
ParseTagFromXMLTree()
MagickExport XMLTreeInfo * ParseTagFromXMLTree (XMLTreeInfo *)
PruneTagFromXMLTree()
MagickExport XMLTreeInfo * PruneTagFromXMLTree (XMLTreeInfo *)
SetXMLTreeAttribute()
MagickExport XMLTreeInfo * SetXMLTreeAttribute (XMLTreeInfo * , const char * , const char *)
SetXMLTreeContent()
MagickExport XMLTreeInfo * SetXMLTreeContent (XMLTreeInfo * xml_info, const char * content)
References ConstantString(), _XMLTreeInfo::content, _XMLTreeInfo::debug, DestroyString(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _XMLTreeInfo::signature, and TraceEvent.
XMLTreeInfoToXML()
MagickExport char * XMLTreeInfoToXML (XMLTreeInfo * xml_info)
References AcquireString(), _XMLTreeRoot::attributes, _XMLTreeInfo::debug, FormatLocaleString(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MaxTextExtent, _XMLTreeInfo::ordered, _XMLTreeInfo::parent, _XMLTreeRoot::processing_instructions, ResizeQuantumMemory(), _XMLTreeRoot::root, _XMLTreeInfo::signature, _XMLTreeInfo::tag, TraceEvent, and XMLTreeTagToXML().