MagickCore: xml-tree-private.h File Reference
xml-tree-private.h File Reference
Functions
MagickPrivate char * FileToXML (const char *, const size_t)
Function Documentation
FileToXML()
MagickPrivate char * FileToXML (const char * filename, const size_t)
References AcquireQuantumMemory(), LocaleCompare(), MAGICK_SSIZE_MAX, MagickMaxBufferExtent, MagickMin, MapBlob(), MaxTextExtent, O_BINARY, _XMLTreeInfo::offset, open_utf8(), ReadMode, RelinquishMagickMemory(), ResizeQuantumMemory(), and UnmapBlob().
Referenced by LoadCoderCache(), LoadColorCache(), LoadConfigureCache(), LoadDelegateCache(), LoadLocaleCache(), LoadLogCache(), LoadMagicCache(), LoadMimeCache(), and LoadPolicyCache().