MagickCore: xml-tree.c File Reference
xml-tree.c File Reference
#include "magick/studio.h"
#include "magick/blob.h"
#include "magick/blob-private.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/image-private.h"
#include "magick/log.h"
#include "magick/memory_.h"
#include "magick/semaphore.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/token-private.h"
#include "magick/utility.h"
#include "magick/utility-private.h"
#include "magick/xml-tree.h"
#include "magick/xml-tree-private.h"
Data Structures
struct _XMLTreeInfo
struct _XMLTreeRoot
Macros
#define NumberPredefinedEntities 10
#define XMLWhitespace "\t\r\n "
Typedefs
typedef struct _XMLTreeRoot XMLTreeRoot
Functions
MagickExport XMLTreeInfo * AddChildToXMLTree (XMLTreeInfo *xml_info, const char *tag, const size_t offset)
MagickExport XMLTreeInfo * AddPathToXMLTree (XMLTreeInfo *xml_info, const char *path, const size_t offset)
MagickExport char * CanonicalXMLContent (const char *content, const MagickBooleanType pedantic)
static char ** DestroyXMLTreeAttributes (char **attributes)
static void DestroyXMLTreeChild (XMLTreeInfo *xml_info)
static void DestroyXMLTreeOrdered (XMLTreeInfo *xml_info)
static void DestroyXMLTreeRoot (XMLTreeInfo *xml_info)
MagickExport XMLTreeInfo * DestroyXMLTree (XMLTreeInfo *xml_info)
MagickPrivate char * FileToXML (const char *filename, const size_t extent)
MagickExport XMLTreeInfo * GetNextXMLTreeTag (XMLTreeInfo *xml_info)
MagickExport const char * GetXMLTreeAttribute (XMLTreeInfo *xml_info, const char *tag)
MagickExport MagickBooleanType GetXMLTreeAttributes (const XMLTreeInfo *xml_info, SplayTreeInfo *attributes)
MagickExport XMLTreeInfo * GetXMLTreeChild (XMLTreeInfo *xml_info, const char *tag)
MagickExport const char * GetXMLTreeContent (XMLTreeInfo *xml_info)
MagickExport XMLTreeInfo * GetXMLTreeOrdered (XMLTreeInfo *xml_info)
MagickExport XMLTreeInfo * GetXMLTreePath (XMLTreeInfo *xml_info, const char *path)
MagickExport const char ** GetXMLTreeProcessingInstructions (XMLTreeInfo *xml_info, const char *target)
MagickExport XMLTreeInfo * GetXMLTreeSibling (XMLTreeInfo *xml_info)
MagickExport const char * GetXMLTreeTag (XMLTreeInfo *xml_info)
MagickExport XMLTreeInfo * InsertTagIntoXMLTree (XMLTreeInfo *xml_info, XMLTreeInfo *child, const size_t offset)
static char * ConvertUTF16ToUTF8 (const char *content, size_t *length)
static char * ParseEntities (char *xml, char **entities, int state)
static void ParseCharacterContent (XMLTreeRoot *root, char *xml, const size_t length, const char state)
static XMLTreeInfo * ParseCloseTag (XMLTreeRoot *root, char *tag, ExceptionInfo *exception)
static MagickBooleanType ValidateEntities (char *tag, char *xml, const size_t depth, char **entities)
static void ParseProcessingInstructions (XMLTreeRoot *root, char *xml, size_t length)
static MagickBooleanType ParseInternalDoctype (XMLTreeRoot *root, char *xml, size_t length, ExceptionInfo *exception)
static void ParseOpenTag (XMLTreeRoot *root, char *tag, char **attributes)
static MagickBooleanType IsSkipTag (const char *tag)
MagickExport XMLTreeInfo * NewXMLTree (const char *xml, ExceptionInfo *exception)
MagickExport XMLTreeInfo * NewXMLTreeTag (const char *tag)
MagickExport XMLTreeInfo * PruneTagFromXMLTree (XMLTreeInfo *xml_info)
MagickExport XMLTreeInfo * SetXMLTreeAttribute (XMLTreeInfo *xml_info, const char *tag, const char *value)
MagickExport XMLTreeInfo * SetXMLTreeContent (XMLTreeInfo *xml_info, const char *content)
static char * EncodePredefinedEntities (const char *source, ssize_t offset, char **destination, size_t *length, size_t *extent, MagickBooleanType pedantic)
static char * XMLTreeTagToXML (XMLTreeInfo *xml_info, char **source, size_t *length, size_t *extent, size_t start, char ***attributes)
MagickExport char * XMLTreeInfoToXML (XMLTreeInfo *xml_info)
Variables
static char * sentinel [] = { (char *) NULL }
static const char * skip_tags [3]
Macro Definition Documentation
NumberPredefinedEntities
#define NumberPredefinedEntities 10
XMLWhitespace
#define XMLWhitespace "\t\r\n "
Typedef Documentation
XMLTreeRoot
typedef struct _XMLTreeRoot XMLTreeRoot
Function Documentation
AddChildToXMLTree()
MagickExport XMLTreeInfo * AddChildToXMLTree (XMLTreeInfo * xml_info, const char * tag, const size_t offset)
References AcquireMagickMemory(), _XMLTreeInfo::attributes, _XMLTreeInfo::child, ConstantString(), _XMLTreeInfo::content, _XMLTreeInfo::debug, InsertTagIntoXMLTree(), IsEventLogging(), MagickCoreSignature, _XMLTreeInfo::offset, sentinel, _XMLTreeInfo::signature, and _XMLTreeInfo::tag.
Referenced by AddPathToXMLTree(), and ParseOpenTag().
AddPathToXMLTree()
MagickExport XMLTreeInfo * AddPathToXMLTree (XMLTreeInfo * xml_info, const char * path, const size_t offset)
References AddChildToXMLTree(), CanonicalPath, _XMLTreeInfo::child, _XMLTreeInfo::debug, DestroyString(), GetMagickModule, GetPathComponent(), GetPathComponents(), GetXMLTreeChild(), GetXMLTreeOrdered(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MaxTextExtent, _XMLTreeInfo::offset, RelinquishMagickMemory(), _XMLTreeInfo::signature, StringToLong(), SubimagePath, _XMLTreeInfo::tag, and TraceEvent.
CanonicalXMLContent()
MagickExport char * CanonicalXMLContent (const char * content, const MagickBooleanType pedantic)
References AcquireString(), Base64Encode(), ConcatenateString(), _XMLTreeInfo::content, ConvertLatin1ToUTF8(), DestroyString(), FormatLocaleString(), MagickFalse, MaxTextExtent, RelinquishMagickMemory(), and ResizeQuantumMemory().
Referenced by EncodePredefinedEntities().
ConvertUTF16ToUTF8()
static char * ConvertUTF16ToUTF8 (const char * content, size_t * length) static
References AcquireQuantumMemory(), MaxTextExtent, and ResizeQuantumMemory().
Referenced by NewXMLTree().
DestroyXMLTree()
MagickExport XMLTreeInfo * DestroyXMLTree (XMLTreeInfo * xml_info)
References _XMLTreeInfo::attributes, _XMLTreeInfo::content, _XMLTreeInfo::debug, DestroyString(), DestroyXMLTreeAttributes(), DestroyXMLTreeChild(), DestroyXMLTreeOrdered(), DestroyXMLTreeRoot(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, RelinquishMagickMemory(), _XMLTreeInfo::signature, _XMLTreeInfo::tag, and TraceEvent.
Referenced by ColorDecisionListImage(), DestroyXMLTreeChild(), DestroyXMLTreeOrdered(), GetThresholdMapFile(), GetXMPProperty(), ListThresholdMapFile(), and LoadMimeCache().
DestroyXMLTreeAttributes()
static char ** DestroyXMLTreeAttributes (char ** attributes) static
References _XMLTreeInfo::attributes, DestroyString(), RelinquishMagickMemory(), and sentinel.
Referenced by DestroyXMLTree(), and NewXMLTree().
DestroyXMLTreeChild()
static void DestroyXMLTreeChild (XMLTreeInfo * xml_info) static
References _XMLTreeInfo::child, and DestroyXMLTree().
Referenced by DestroyXMLTree().
DestroyXMLTreeOrdered()
static void DestroyXMLTreeOrdered (XMLTreeInfo * xml_info) static
References DestroyXMLTree(), and _XMLTreeInfo::ordered.
Referenced by DestroyXMLTree().
DestroyXMLTreeRoot()
static void DestroyXMLTreeRoot (XMLTreeInfo * xml_info) static
References _XMLTreeInfo::attributes, _XMLTreeRoot::attributes, _XMLTreeInfo::debug, DestroyString(), _XMLTreeRoot::entities, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, NumberPredefinedEntities, _XMLTreeInfo::parent, _XMLTreeRoot::processing_instructions, RelinquishMagickMemory(), _XMLTreeInfo::signature, and TraceEvent.
Referenced by DestroyXMLTree().
EncodePredefinedEntities()
static char * EncodePredefinedEntities (const char * source, ssize_t offset, char ** destination, size_t * length, size_t * extent, MagickBooleanType pedantic) static
References AcquireString(), CanonicalXMLContent(), DestroyString(), FormatLocaleString(), MaxTextExtent, and ResizeQuantumMemory().
Referenced by XMLTreeTagToXML().
FileToXML()
MagickPrivate char * FileToXML (const char * filename, const size_t extent)
References AcquireQuantumMemory(), LocaleCompare(), MAGICK_SSIZE_MAX, MagickMaxBufferExtent, MagickMin, MapBlob(), MaxTextExtent, O_BINARY, _XMLTreeInfo::offset, open_utf8(), ReadMode, RelinquishMagickMemory(), ResizeQuantumMemory(), and UnmapBlob().
Referenced by LoadCoderCache(), LoadColorCache(), LoadConfigureCache(), LoadDelegateCache(), LoadLocaleCache(), LoadLogCache(), LoadMagicCache(), LoadMimeCache(), and LoadPolicyCache().
GetNextXMLTreeTag()
MagickExport XMLTreeInfo * GetNextXMLTreeTag (XMLTreeInfo * xml_info)
References _XMLTreeInfo::debug, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _XMLTreeInfo::next, _XMLTreeInfo::signature, and TraceEvent.
Referenced by GetThresholdMapFile(), GetXMPProperty(), ListThresholdMapFile(), and LoadMimeCache().
GetXMLTreeAttribute()
MagickExport const char * GetXMLTreeAttribute (XMLTreeInfo * xml_info, const char * tag)
References _XMLTreeInfo::attributes, _XMLTreeRoot::attributes, _XMLTreeInfo::debug, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _XMLTreeInfo::parent, _XMLTreeRoot::root, _XMLTreeInfo::signature, _XMLTreeInfo::tag, and TraceEvent.
Referenced by GetThresholdMapFile(), ListThresholdMapFile(), LoadMimeCache(), and XMLTreeTagToXML().
GetXMLTreeAttributes()
MagickExport MagickBooleanType GetXMLTreeAttributes (const XMLTreeInfo * xml_info, SplayTreeInfo * attributes)
References AddValueToSplayTree(), _XMLTreeInfo::attributes, ConstantString(), _XMLTreeInfo::debug, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MagickTrue, _XMLTreeInfo::signature, and TraceEvent.
GetXMLTreeChild()
MagickExport XMLTreeInfo * GetXMLTreeChild (XMLTreeInfo * xml_info, const char * tag)
References _XMLTreeInfo::child, _XMLTreeInfo::debug, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _XMLTreeInfo::sibling, _XMLTreeInfo::signature, _XMLTreeInfo::tag, and TraceEvent.
Referenced by AddPathToXMLTree(), ColorDecisionListImage(), GetThresholdMapFile(), GetXMLTreePath(), GetXMPProperty(), ListThresholdMapFile(), and LoadMimeCache().
GetXMLTreeContent()
MagickExport const char * GetXMLTreeContent (XMLTreeInfo * xml_info)
References _XMLTreeInfo::content, _XMLTreeInfo::debug, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _XMLTreeInfo::signature, and TraceEvent.
Referenced by ColorDecisionListImage(), GetThresholdMapFile(), GetXMPProperty(), and ListThresholdMapFile().
GetXMLTreeOrdered()
MagickExport XMLTreeInfo * GetXMLTreeOrdered (XMLTreeInfo * xml_info)
References _XMLTreeInfo::debug, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _XMLTreeInfo::ordered, _XMLTreeInfo::signature, and TraceEvent.
Referenced by AddPathToXMLTree(), and GetXMLTreePath().
GetXMLTreePath()
MagickExport XMLTreeInfo * GetXMLTreePath (XMLTreeInfo * xml_info, const char * path)
References CanonicalPath, _XMLTreeInfo::debug, DestroyString(), GetMagickModule, GetPathComponent(), GetPathComponents(), GetXMLTreeChild(), GetXMLTreeOrdered(), LogMagickEvent(), MagickCoreSignature, MagickFalse, MaxTextExtent, RelinquishMagickMemory(), _XMLTreeInfo::signature, StringToLong(), SubimagePath, and TraceEvent.
GetXMLTreeProcessingInstructions()
MagickExport const char ** GetXMLTreeProcessingInstructions (XMLTreeInfo * xml_info, const char * target)
References _XMLTreeInfo::debug, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _XMLTreeInfo::parent, _XMLTreeRoot::processing_instructions, _XMLTreeRoot::root, sentinel, _XMLTreeInfo::signature, and TraceEvent.
GetXMLTreeSibling()
MagickExport XMLTreeInfo * GetXMLTreeSibling (XMLTreeInfo * xml_info)
References _XMLTreeInfo::debug, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _XMLTreeInfo::sibling, _XMLTreeInfo::signature, and TraceEvent.
Referenced by GetXMPProperty().
GetXMLTreeTag()
MagickExport const char * GetXMLTreeTag (XMLTreeInfo * xml_info)
References _XMLTreeInfo::debug, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _XMLTreeInfo::signature, _XMLTreeInfo::tag, and TraceEvent.
Referenced by GetXMPProperty().
InsertTagIntoXMLTree()
MagickExport XMLTreeInfo * InsertTagIntoXMLTree (XMLTreeInfo * xml_info, XMLTreeInfo * child, const size_t offset)
References _XMLTreeInfo::child, _XMLTreeInfo::next, _XMLTreeInfo::offset, _XMLTreeInfo::ordered, _XMLTreeInfo::parent, _XMLTreeInfo::sibling, and _XMLTreeInfo::tag.
Referenced by AddChildToXMLTree().
IsSkipTag()
static MagickBooleanType IsSkipTag (const char * tag) inline static
References LocaleCompare(), MagickFalse, MagickTrue, and skip_tags.
Referenced by NewXMLTree().
NewXMLTree()
MagickExport XMLTreeInfo * NewXMLTree (const char * xml, ExceptionInfo * exception)
References AcquireQuantumMemory(), _XMLTreeRoot::attributes, ConstantString(), ConvertUTF16ToUTF8(), DestroyString(), DestroyXMLTreeAttributes(), _XMLTreeRoot::entities, GetMagickModule, IsSkipTag(), MagickFalse, NewXMLTreeTag(), _XMLTreeRoot::node, OptionWarning, ParseCharacterContent(), ParseCloseTag(), ParseEntities(), ParseInternalDoctype(), ParseOpenTag(), ParseProcessingInstructions(), ResizeQuantumMemory(), ResourceLimitError, _XMLTreeRoot::root, sentinel, _XMLTreeInfo::tag, ThrowMagickException(), and XMLWhitespace.
Referenced by ColorDecisionListImage(), GetThresholdMapFile(), GetXMPProperty(), ListThresholdMapFile(), and LoadMimeCache().
NewXMLTreeTag()
MagickExport XMLTreeInfo * NewXMLTreeTag (const char * tag)
References AcquireMagickMemory(), _XMLTreeInfo::attributes, _XMLTreeRoot::attributes, ConstantString(), _XMLTreeInfo::content, _XMLTreeRoot::debug, _XMLTreeRoot::entities, IsEventLogging(), MagickCoreSignature, _XMLTreeRoot::node, NumberPredefinedEntities, _XMLTreeRoot::processing_instructions, _XMLTreeRoot::root, sentinel, _XMLTreeRoot::signature, and _XMLTreeInfo::tag.
Referenced by NewXMLTree().
ParseCharacterContent()
static void ParseCharacterContent (XMLTreeRoot * root, char * xml, const size_t length, const char state) static
References ConcatenateString(), _XMLTreeInfo::content, DestroyString(), _XMLTreeRoot::entities, _XMLTreeRoot::node, ParseEntities(), and _XMLTreeInfo::tag.
Referenced by NewXMLTree().
ParseCloseTag()
static XMLTreeInfo * ParseCloseTag (XMLTreeRoot * root, char * tag, ExceptionInfo * exception) static
References GetMagickModule, _XMLTreeRoot::node, OptionWarning, _XMLTreeInfo::parent, _XMLTreeRoot::root, _XMLTreeInfo::tag, and ThrowMagickException().
Referenced by NewXMLTree().
ParseEntities()
static char * ParseEntities (char * xml, char ** entities, int state) static
References AcquireQuantumMemory(), ConstantString(), CopyMagickString(), ResizeQuantumMemory(), ResourceLimitFatalError, and ThrowFatalException.
Referenced by NewXMLTree(), ParseCharacterContent(), and ParseInternalDoctype().
ParseInternalDoctype()
static MagickBooleanType ParseInternalDoctype (XMLTreeRoot * root, char * xml, size_t length, ExceptionInfo * exception) static
References AcquireMagickMemory(), AcquireQuantumMemory(), _XMLTreeRoot::attributes, ConstantString(), DestroyString(), _XMLTreeRoot::entities, GetMagickModule, MagickFalse, MagickTrue, OptionWarning, ParseEntities(), ParseProcessingInstructions(), RelinquishMagickMemory(), ResizeQuantumMemory(), ResourceLimitError, ResourceLimitFatalError, sentinel, _XMLTreeRoot::standalone, ThrowFatalException, ThrowMagickException(), ValidateEntities(), and XMLWhitespace.
Referenced by NewXMLTree().
ParseOpenTag()
static void ParseOpenTag (XMLTreeRoot * root, char * tag, char ** attributes) static
References AddChildToXMLTree(), _XMLTreeInfo::attributes, ConstantString(), _XMLTreeInfo::content, _XMLTreeRoot::node, and _XMLTreeInfo::tag.
Referenced by NewXMLTree().
ParseProcessingInstructions()
static void ParseProcessingInstructions (XMLTreeRoot * root, char * xml, size_t length) static
References AcquireMagickMemory(), AcquireQuantumMemory(), ConstantString(), CopyMagickString(), MagickTrue, _XMLTreeRoot::processing_instructions, ResizeQuantumMemory(), ResourceLimitFatalError, _XMLTreeRoot::root, _XMLTreeRoot::standalone, _XMLTreeInfo::tag, ThrowFatalException, and XMLWhitespace.
Referenced by NewXMLTree(), and ParseInternalDoctype().
PruneTagFromXMLTree()
MagickExport XMLTreeInfo * PruneTagFromXMLTree (XMLTreeInfo * xml_info)
References _XMLTreeInfo::child, _XMLTreeInfo::debug, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _XMLTreeInfo::next, _XMLTreeInfo::ordered, _XMLTreeInfo::parent, _XMLTreeInfo::sibling, _XMLTreeInfo::signature, _XMLTreeInfo::tag, and TraceEvent.
SetXMLTreeAttribute()
MagickExport XMLTreeInfo * SetXMLTreeAttribute (XMLTreeInfo * xml_info, const char * tag, const char * value)
References AcquireQuantumMemory(), _XMLTreeInfo::attributes, ConstantString(), _XMLTreeInfo::debug, DestroyString(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, ResizeQuantumMemory(), ResourceLimitFatalError, sentinel, _XMLTreeInfo::signature, ThrowFatalException, and TraceEvent.
SetXMLTreeContent()
MagickExport XMLTreeInfo * SetXMLTreeContent (XMLTreeInfo * xml_info, const char * content)
References ConstantString(), _XMLTreeInfo::content, _XMLTreeInfo::debug, DestroyString(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _XMLTreeInfo::signature, and TraceEvent.
ValidateEntities()
static MagickBooleanType ValidateEntities (char * tag, char * xml, const size_t depth, char ** entities) static
References MagickFalse, MagickMaxRecursionDepth, MagickTrue, and ValidateEntities().
Referenced by ParseInternalDoctype(), and ValidateEntities().
XMLTreeInfoToXML()
MagickExport char * XMLTreeInfoToXML (XMLTreeInfo * xml_info)
References AcquireString(), _XMLTreeRoot::attributes, _XMLTreeInfo::debug, FormatLocaleString(), GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, MaxTextExtent, _XMLTreeInfo::ordered, _XMLTreeInfo::parent, _XMLTreeRoot::processing_instructions, ResizeQuantumMemory(), _XMLTreeRoot::root, _XMLTreeInfo::signature, _XMLTreeInfo::tag, TraceEvent, and XMLTreeTagToXML().
XMLTreeTagToXML()
static char * XMLTreeTagToXML (XMLTreeInfo * xml_info, char ** source, size_t * length, size_t * extent, size_t start, char *** attributes) static
References _XMLTreeInfo::attributes, _XMLTreeInfo::child, _XMLTreeInfo::content, EncodePredefinedEntities(), FormatLocaleString(), GetXMLTreeAttribute(), MagickFalse, MagickTrue, MaxTextExtent, _XMLTreeInfo::offset, _XMLTreeInfo::ordered, _XMLTreeInfo::parent, ResizeQuantumMemory(), _XMLTreeInfo::tag, and XMLTreeTagToXML().
Referenced by XMLTreeInfoToXML(), and XMLTreeTagToXML().
Variable Documentation
sentinel
char* sentinel[] = { (char *) NULL } static
Referenced by AddChildToXMLTree(), DestroyXMLTreeAttributes(), GetCommandOptionFlags(), GetXMLTreeProcessingInstructions(), IdentifyImage(), NewXMLTree(), NewXMLTreeTag(), ParseCommandOption(), ParseInternalDoctype(), and SetXMLTreeAttribute().
skip_tags
const char* skip_tags[3] static
Initial value:
=
  {
    "rdf:Bag",
    "rdf:Seq",
    (const char *) NULL
  }
Referenced by IsSkipTag().