MagickCore: xwindow.c File Reference
xwindow.c File Reference
#include "magick/studio.h"
#include "magick/animate.h"
#include "magick/artifact.h"
#include "magick/blob.h"
#include "magick/cache.h"
#include "magick/client.h"
#include "magick/color.h"
#include "magick/color-private.h"
#include "magick/colormap.h"
#include "magick/composite.h"
#include "magick/display.h"
#include "magick/distort.h"
#include "magick/exception.h"
#include "magick/exception-private.h"
#include "magick/geometry.h"
#include "magick/identify.h"
#include "magick/image.h"
#include "magick/image-private.h"
#include "magick/list.h"
#include "magick/locale_.h"
#include "magick/log.h"
#include "magick/magick.h"
#include "magick/memory_.h"
#include "magick/memory-private.h"
#include "magick/monitor.h"
#include "magick/nt-base-private.h"
#include "magick/option.h"
#include "magick/quantize.h"
#include "magick/quantum.h"
#include "magick/quantum-private.h"
#include "magick/resource_.h"
#include "magick/resize.h"
#include "magick/statistic.h"
#include "magick/string_.h"
#include "magick/string-private.h"
#include "magick/token.h"
#include "magick/transform.h"
#include "magick/utility.h"
#include "magick/widget.h"
#include "magick/xwindow.h"
#include "magick/xwindow-private.h"
#include "magick/version.h"
Functions
MagickExport Image * XImportImage (const ImageInfo *image_info, XImportInfo *ximage_info)
MagickPrivate MagickBooleanType XRenderImage (Image *image, const DrawInfo *draw_info, const PointInfo *offset, TypeMetric *metrics)
MagickExport MagickBooleanType XComponentGenesis (void)
MagickExport void XGetImportInfo (XImportInfo *ximage_info)
Function Documentation
XComponentGenesis()
MagickExport MagickBooleanType XComponentGenesis (void)
References MagickTrue.
Referenced by MagickCoreGenesis().
XGetImportInfo()
MagickExport void XGetImportInfo (XImportInfo * ximage_info)
References _XImportInfo::borders, _XImportInfo::descend, _XImportInfo::frame, MagickFalse, MagickTrue, _XImportInfo::screen, and _XImportInfo::silent.
XImportImage()
MagickExport Image * XImportImage (const ImageInfo * image_info, XImportInfo * ximage_info)
References _ImageInfo::debug, _ImageInfo::filename, GetMagickModule, LogMagickEvent(), MagickCoreSignature, MagickFalse, _ImageInfo::signature, and TraceEvent.
XRenderImage()
MagickPrivate MagickBooleanType XRenderImage (Image * image, const DrawInfo * draw_info, const PointInfo * offset, TypeMetric * metrics)
References _Image::exception, _Image::filename, GetMagickModule, MagickFalse, MissingDelegateError, and ThrowMagickException().
Referenced by RenderX11().