MagickWand: convert.c File Reference
convert.c File Reference
#include "wand/studio.h"
#include "wand/MagickWand.h"
#include "wand/mogrify-private.h"
#include "magick/exception-private.h"
#include "magick/string-private.h"
#include "magick/utility-private.h"
Macros
#define NotInitialized (unsigned int) (~0)
#define DestroyConvert()
#define ThrowConvertException(asperity, tag, option)
#define ThrowConvertInvalidArgumentException(option, argument)
Functions
static MagickBooleanType ConcatenateImages (int argc, char **argv, ExceptionInfo *exception)
static MagickBooleanType ConvertUsage (void)
WandExport MagickBooleanType ConvertImageCommand (ImageInfo *image_info, int argc, char **argv, char **metadata, ExceptionInfo *exception)
Macro Definition Documentation
DestroyConvert
#define DestroyConvert ()
Value:
{ \
  DestroyImageStack(); \
  for (i=0; i < (ssize_t) argc; i++) \
    argv[i]=DestroyString(argv[i]); \
  argv=(char **) RelinquishMagickMemory(argv); \
}
NotInitialized
#define NotInitialized (unsigned int) (~0)
ThrowConvertException
#define ThrowConvertException (asperity, tag, option)
Value:
{ \
  (void) ThrowMagickException(exception,GetMagickModule(),asperity,tag,"`%s'", \
    option); \
  DestroyConvert(); \
  return(MagickFalse); \
}
ThrowConvertInvalidArgumentException
#define ThrowConvertInvalidArgumentException (option, argument)
Value:
{ \
  (void) ThrowMagickException(exception,GetMagickModule(),OptionError, \
    "InvalidArgument","`%s': %s",option,argument); \
  DestroyConvert(); \
  return(MagickFalse); \
}
Function Documentation
ConcatenateImages()
static MagickBooleanType ConcatenateImages (int argc, char ** argv, ExceptionInfo * exception) static
Referenced by ConvertImageCommand().
ConvertImageCommand()
WandExport MagickBooleanType ConvertImageCommand (ImageInfo * image_info, int argc, char ** argv, char ** metadata, ExceptionInfo * exception)
References AppendImageStack, ConcatenateImages(), ConvertUsage(), DestroyConvert, FinalizeImageSettings, FireImageStack, MaxImageStackDepth, MaxTextExtent, MogrifyImageInfo(), NewImageStack, PopImageStack, PushImageStack, ReadCommandlLine, ThrowConvertException, and ThrowConvertInvalidArgumentException.
ConvertUsage()
static MagickBooleanType ConvertUsage (void) static
Referenced by ConvertImageCommand().