MagickWand: convert.h File Reference
convert.h File Reference
Functions
WandExport MagickBooleanType ConvertImageCommand (ImageInfo *, int, char **, char **, ExceptionInfo *)
Function Documentation
ConvertImageCommand()
WandExport MagickBooleanType ConvertImageCommand (ImageInfo * image_info, int argc, char ** argv, char ** metadata, ExceptionInfo * exception)
References AppendImageStack, ConcatenateImages(), ConvertUsage(), DestroyConvert, FinalizeImageSettings, FireImageStack, MaxImageStackDepth, MaxTextExtent, MogrifyImageInfo(), NewImageStack, PopImageStack, PushImageStack, ReadCommandlLine, ThrowConvertException, and ThrowConvertInvalidArgumentException.