MagickWand: drawing-wand.h File Reference
drawing-wand.h File Reference
#include "wand/pixel-wand.h"
Typedefs
typedef struct _DrawingWand DrawingWand
Functions
WandExport AlignType DrawGetTextAlignment (const DrawingWand *)
WandExport char * DrawGetClipPath (const DrawingWand *)
WandExport char * DrawGetDensity (const DrawingWand *)
WandExport char * DrawGetException (const DrawingWand *, ExceptionType *)
WandExport char * DrawGetFont (const DrawingWand *)
WandExport char * DrawGetFontFamily (const DrawingWand *)
WandExport char * DrawGetTextEncoding (const DrawingWand *)
WandExport char * DrawGetVectorGraphics (DrawingWand *)
WandExport ClipPathUnits DrawGetClipUnits (const DrawingWand *) magick_attribute((__pure__))
WandExport DecorationType DrawGetTextDecoration (const DrawingWand *) magick_attribute((__pure__))
WandExport DirectionType DrawGetTextDirection (const DrawingWand *)
WandExport double DrawGetFillOpacity (const DrawingWand *) magick_attribute((__pure__))
WandExport double DrawGetFontSize (const DrawingWand *) magick_attribute((__pure__))
WandExport double DrawGetOpacity (const DrawingWand *) magick_attribute((__pure__))
WandExport double * DrawGetStrokeDashArray (const DrawingWand *, size_t *)
WandExport double DrawGetStrokeDashOffset (const DrawingWand *) magick_attribute((__pure__))
WandExport double DrawGetStrokeOpacity (const DrawingWand *) magick_attribute((__pure__))
WandExport double DrawGetStrokeWidth (const DrawingWand *) magick_attribute((__pure__))
WandExport double DrawGetTextKerning (DrawingWand *) magick_attribute((__pure__))
WandExport double DrawGetTextInterlineSpacing (DrawingWand *) magick_attribute((__pure__))
WandExport double DrawGetTextInterwordSpacing (DrawingWand *) magick_attribute((__pure__))
WandExport DrawInfo * PeekDrawingWand (const DrawingWand *)
WandExport DrawingWand * AcquireDrawingWand (const DrawInfo *, Image *)
WandExport DrawingWand * CloneDrawingWand (const DrawingWand *)
WandExport DrawingWand * DestroyDrawingWand (DrawingWand *)
WandExport DrawingWand * NewDrawingWand (void)
WandExport ExceptionType DrawGetExceptionType (const DrawingWand *)
WandExport FillRule DrawGetClipRule (const DrawingWand *) magick_attribute((__pure__))
WandExport FillRule DrawGetFillRule (const DrawingWand *) magick_attribute((__pure__))
WandExport GravityType DrawGetGravity (const DrawingWand *) magick_attribute((__pure__))
WandExport LineCap DrawGetStrokeLineCap (const DrawingWand *) magick_attribute((__pure__))
WandExport LineJoin DrawGetStrokeLineJoin (const DrawingWand *) magick_attribute((__pure__))
WandExport MagickBooleanType DrawClearException (DrawingWand *)
WandExport MagickBooleanType DrawComposite (DrawingWand *, const CompositeOperator, const double, const double, const double, const double, MagickWand *)
WandExport MagickBooleanType DrawGetFontResolution (const DrawingWand *, double *, double *)
WandExport MagickBooleanType DrawGetStrokeAntialias (const DrawingWand *) magick_attribute((__pure__))
WandExport MagickBooleanType DrawGetTextAntialias (const DrawingWand *) magick_attribute((__pure__))
WandExport MagickBooleanType DrawPopPattern (DrawingWand *)
WandExport MagickBooleanType DrawPushPattern (DrawingWand *, const char *, const double, const double, const double, const double)
WandExport MagickBooleanType DrawRender (DrawingWand *)
WandExport MagickBooleanType DrawSetClipPath (DrawingWand *, const char *)
WandExport MagickBooleanType DrawSetDensity (DrawingWand *, const char *)
WandExport MagickBooleanType DrawSetFillPatternURL (DrawingWand *, const char *)
WandExport MagickBooleanType DrawSetFont (DrawingWand *, const char *)
WandExport MagickBooleanType DrawSetFontFamily (DrawingWand *, const char *)
WandExport MagickBooleanType DrawSetFontResolution (DrawingWand *, const double, const double)
WandExport MagickBooleanType DrawSetStrokeDashArray (DrawingWand *, const size_t, const double *)
WandExport MagickBooleanType DrawSetStrokePatternURL (DrawingWand *, const char *)
WandExport MagickBooleanType DrawSetVectorGraphics (DrawingWand *, const char *)
WandExport MagickBooleanType IsDrawingWand (const DrawingWand *)
WandExport MagickBooleanType PopDrawingWand (DrawingWand *)
WandExport MagickBooleanType PushDrawingWand (DrawingWand *)
WandExport StretchType DrawGetFontStretch (const DrawingWand *)
WandExport StyleType DrawGetFontStyle (const DrawingWand *)
WandExport size_t DrawGetFontWeight (const DrawingWand *) magick_attribute((__pure__))
WandExport size_t DrawGetStrokeMiterLimit (const DrawingWand *) magick_attribute((__pure__))
WandExport void ClearDrawingWand (DrawingWand *)
WandExport void DrawAffine (DrawingWand *, const AffineMatrix *)
WandExport void DrawAnnotation (DrawingWand *, const double, const double, const unsigned char *)
WandExport void DrawArc (DrawingWand *, const double, const double, const double, const double, const double, const double)
WandExport void DrawBezier (DrawingWand *, const size_t, const PointInfo *)
WandExport void DrawGetBorderColor (const DrawingWand *, PixelWand *)
WandExport void DrawCircle (DrawingWand *, const double, const double, const double, const double)
WandExport void DrawColor (DrawingWand *, const double, const double, const PaintMethod)
WandExport void DrawComment (DrawingWand *, const char *)
WandExport void DrawEllipse (DrawingWand *, const double, const double, const double, const double, const double, const double)
WandExport void DrawGetFillColor (const DrawingWand *, PixelWand *)
WandExport void DrawGetStrokeColor (const DrawingWand *, PixelWand *)
WandExport void DrawSetTextKerning (DrawingWand *, const double)
WandExport void DrawSetTextInterlineSpacing (DrawingWand *, const double)
WandExport void DrawSetTextInterwordSpacing (DrawingWand *, const double)
WandExport void DrawGetTextUnderColor (const DrawingWand *, PixelWand *)
WandExport void DrawLine (DrawingWand *, const double, const double, const double, const double)
WandExport void DrawMatte (DrawingWand *, const double, const double, const PaintMethod)
WandExport void DrawPathClose (DrawingWand *)
WandExport void DrawPathCurveToAbsolute (DrawingWand *, const double, const double, const double, const double, const double, const double)
WandExport void DrawPathCurveToRelative (DrawingWand *, const double, const double, const double, const double, const double, const double)
WandExport void DrawPathCurveToQuadraticBezierAbsolute (DrawingWand *, const double, const double, const double, const double)
WandExport void DrawPathCurveToQuadraticBezierRelative (DrawingWand *, const double, const double, const double, const double)
WandExport void DrawPathCurveToQuadraticBezierSmoothAbsolute (DrawingWand *, const double, const double)
WandExport void DrawPathCurveToQuadraticBezierSmoothRelative (DrawingWand *, const double, const double)
WandExport void DrawPathCurveToSmoothAbsolute (DrawingWand *, const double, const double, const double, const double)
WandExport void DrawPathCurveToSmoothRelative (DrawingWand *, const double, const double, const double, const double)
WandExport void DrawPathEllipticArcAbsolute (DrawingWand *, const double, const double, const double, const MagickBooleanType, const MagickBooleanType, const double, const double)
WandExport void DrawPathEllipticArcRelative (DrawingWand *, const double, const double, const double, const MagickBooleanType, const MagickBooleanType, const double, const double)
WandExport void DrawPathFinish (DrawingWand *)
WandExport void DrawPathLineToAbsolute (DrawingWand *, const double, const double)
WandExport void DrawPathLineToRelative (DrawingWand *, const double, const double)
WandExport void DrawPathLineToHorizontalAbsolute (DrawingWand *, const double)
WandExport void DrawPathLineToHorizontalRelative (DrawingWand *, const double)
WandExport void DrawPathLineToVerticalAbsolute (DrawingWand *, const double)
WandExport void DrawPathLineToVerticalRelative (DrawingWand *, const double)
WandExport void DrawPathMoveToAbsolute (DrawingWand *, const double, const double)
WandExport void DrawPathMoveToRelative (DrawingWand *, const double, const double)
WandExport void DrawPathStart (DrawingWand *)
WandExport void DrawPoint (DrawingWand *, const double, const double)
WandExport void DrawPolygon (DrawingWand *, const size_t, const PointInfo *)
WandExport void DrawPolyline (DrawingWand *, const size_t, const PointInfo *)
WandExport void DrawPopClipPath (DrawingWand *)
WandExport void DrawPopDefs (DrawingWand *)
WandExport void DrawPushClipPath (DrawingWand *, const char *)
WandExport void DrawPushDefs (DrawingWand *)
WandExport void DrawRectangle (DrawingWand *, const double, const double, const double, const double)
WandExport void DrawResetVectorGraphics (DrawingWand *)
WandExport void DrawRotate (DrawingWand *, const double)
WandExport void DrawRoundRectangle (DrawingWand *, double, double, double, double, double, double)
WandExport void DrawScale (DrawingWand *, const double, const double)
WandExport void DrawSetBorderColor (DrawingWand *, const PixelWand *)
WandExport void DrawSetClipRule (DrawingWand *, const FillRule)
WandExport void DrawSetClipUnits (DrawingWand *, const ClipPathUnits)
WandExport void DrawSetFillColor (DrawingWand *, const PixelWand *)
WandExport void DrawSetFillOpacity (DrawingWand *, const double)
WandExport void DrawSetFillRule (DrawingWand *, const FillRule)
WandExport void DrawSetFontSize (DrawingWand *, const double)
WandExport void DrawSetFontStretch (DrawingWand *, const StretchType)
WandExport void DrawSetFontStyle (DrawingWand *, const StyleType)
WandExport void DrawSetFontWeight (DrawingWand *, const size_t)
WandExport void DrawSetGravity (DrawingWand *, const GravityType)
WandExport void DrawSetOpacity (DrawingWand *, const double)
WandExport void DrawSetStrokeAntialias (DrawingWand *, const MagickBooleanType)
WandExport void DrawSetStrokeColor (DrawingWand *, const PixelWand *)
WandExport void DrawSetStrokeDashOffset (DrawingWand *, const double dashoffset)
WandExport void DrawSetStrokeLineCap (DrawingWand *, const LineCap)
WandExport void DrawSetStrokeLineJoin (DrawingWand *, const LineJoin)
WandExport void DrawSetStrokeMiterLimit (DrawingWand *, const size_t)
WandExport void DrawSetStrokeOpacity (DrawingWand *, const double)
WandExport void DrawSetStrokeWidth (DrawingWand *, const double)
WandExport void DrawSetTextAlignment (DrawingWand *, const AlignType)
WandExport void DrawSetTextAntialias (DrawingWand *, const MagickBooleanType)
WandExport void DrawSetTextDecoration (DrawingWand *, const DecorationType)
WandExport void DrawSetTextDirection (DrawingWand *, const DirectionType)
WandExport void DrawSetTextEncoding (DrawingWand *, const char *)
WandExport void DrawSetTextUnderColor (DrawingWand *, const PixelWand *)
WandExport void DrawSetViewbox (DrawingWand *, ssize_t, ssize_t, ssize_t, ssize_t)
WandExport void DrawSkewX (DrawingWand *, const double)
WandExport void DrawSkewY (DrawingWand *, const double)
WandExport void DrawTranslate (DrawingWand *, const double, const double)
Typedef Documentation
DrawingWand
typedef struct _DrawingWand DrawingWand
Function Documentation
AcquireDrawingWand()
WandExport DrawingWand * AcquireDrawingWand (const DrawInfo * , Image *)
ClearDrawingWand()
WandExport void ClearDrawingWand (DrawingWand *)
CloneDrawingWand()
WandExport DrawingWand * CloneDrawingWand (const DrawingWand *)
DestroyDrawingWand()
WandExport DrawingWand * DestroyDrawingWand (DrawingWand *)
DrawAffine()
WandExport void DrawAffine (DrawingWand * , const AffineMatrix *)
DrawAnnotation()
WandExport void DrawAnnotation (DrawingWand * , const double , const double , const unsigned char *)
DrawArc()
WandExport void DrawArc (DrawingWand * , const double , const double , const double , const double , const double , const double)
DrawBezier()
WandExport void DrawBezier (DrawingWand * , const size_t, const PointInfo *)
DrawCircle()
WandExport void DrawCircle (DrawingWand * , const double , const double , const double , const double)
DrawClearException()
WandExport MagickBooleanType DrawClearException (DrawingWand *)
DrawColor()
WandExport void DrawColor (DrawingWand * , const double , const double , const PaintMethod)
DrawComment()
WandExport void DrawComment (DrawingWand * , const char *)
DrawComposite()
WandExport MagickBooleanType DrawComposite (DrawingWand * , const CompositeOperator, const double , const double , const double , const double , MagickWand *)
DrawEllipse()
WandExport void DrawEllipse (DrawingWand * , const double , const double , const double , const double , const double , const double)
DrawGetBorderColor()
WandExport void DrawGetBorderColor (const DrawingWand * , PixelWand *)
DrawGetClipPath()
WandExport char * DrawGetClipPath (const DrawingWand *)
DrawGetClipRule()
WandExport FillRule DrawGetClipRule (const DrawingWand *)
DrawGetClipUnits()
WandExport ClipPathUnits DrawGetClipUnits (const DrawingWand * wand)
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
DrawGetDensity()
WandExport char * DrawGetDensity (const DrawingWand *)
DrawGetException()
WandExport char * DrawGetException (const DrawingWand * , ExceptionType *)
DrawGetExceptionType()
WandExport ExceptionType DrawGetExceptionType (const DrawingWand * wand)
References _DrawingWand::debug, _DrawingWand::exception, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
DrawGetFillColor()
WandExport void DrawGetFillColor (const DrawingWand * , PixelWand *)
DrawGetFillOpacity()
WandExport double DrawGetFillOpacity (const DrawingWand *)
DrawGetFillRule()
WandExport FillRule DrawGetFillRule (const DrawingWand * wand)
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
DrawGetFont()
WandExport char * DrawGetFont (const DrawingWand *)
DrawGetFontFamily()
WandExport char * DrawGetFontFamily (const DrawingWand *)
DrawGetFontResolution()
WandExport MagickBooleanType DrawGetFontResolution (const DrawingWand * , double * , double *)
DrawGetFontSize()
WandExport double DrawGetFontSize (const DrawingWand *)
DrawGetFontStretch()
WandExport StretchType DrawGetFontStretch (const DrawingWand * wand)
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
DrawGetFontStyle()
WandExport StyleType DrawGetFontStyle (const DrawingWand * wand)
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
DrawGetFontWeight()
WandExport size_t DrawGetFontWeight (const DrawingWand *)
DrawGetGravity()
WandExport GravityType DrawGetGravity (const DrawingWand * wand)
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
DrawGetOpacity()
WandExport double DrawGetOpacity (const DrawingWand *)
DrawGetStrokeAntialias()
WandExport MagickBooleanType DrawGetStrokeAntialias (const DrawingWand *)
DrawGetStrokeColor()
WandExport void DrawGetStrokeColor (const DrawingWand * , PixelWand *)
DrawGetStrokeDashArray()
WandExport double * DrawGetStrokeDashArray (const DrawingWand * , size_t *)
DrawGetStrokeDashOffset()
WandExport double DrawGetStrokeDashOffset (const DrawingWand *)
DrawGetStrokeLineCap()
WandExport LineCap DrawGetStrokeLineCap (const DrawingWand * wand)
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
DrawGetStrokeLineJoin()
WandExport LineJoin DrawGetStrokeLineJoin (const DrawingWand * wand)
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
DrawGetStrokeMiterLimit()
WandExport size_t DrawGetStrokeMiterLimit (const DrawingWand * wand)
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
DrawGetStrokeOpacity()
WandExport double DrawGetStrokeOpacity (const DrawingWand *)
DrawGetStrokeWidth()
WandExport double DrawGetStrokeWidth (const DrawingWand *)
DrawGetTextAlignment()
WandExport AlignType DrawGetTextAlignment (const DrawingWand * wand)
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
DrawGetTextAntialias()
WandExport MagickBooleanType DrawGetTextAntialias (const DrawingWand *)
DrawGetTextDecoration()
WandExport DecorationType DrawGetTextDecoration (const DrawingWand * wand)
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
DrawGetTextDirection()
WandExport DirectionType DrawGetTextDirection (const DrawingWand * wand)
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
DrawGetTextEncoding()
WandExport char * DrawGetTextEncoding (const DrawingWand *)
DrawGetTextInterlineSpacing()
WandExport double DrawGetTextInterlineSpacing (DrawingWand *)
DrawGetTextInterwordSpacing()
WandExport double DrawGetTextInterwordSpacing (DrawingWand * wand)
References CurrentContext, _DrawingWand::debug, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
DrawGetTextKerning()
WandExport double DrawGetTextKerning (DrawingWand *)
DrawGetTextUnderColor()
WandExport void DrawGetTextUnderColor (const DrawingWand * , PixelWand *)
DrawGetVectorGraphics()
WandExport char * DrawGetVectorGraphics (DrawingWand * wand)
References CurrentContext, _DrawingWand::debug, _DrawingWand::image, MaxTextExtent, _DrawingWand::mvg, _DrawingWand::name, SetMagickPixelPacket(), _DrawingWand::signature, and WandSignature.
DrawLine()
WandExport void DrawLine (DrawingWand * , const double , const double , const double , const double)
DrawMatte()
WandExport void DrawMatte (DrawingWand * , const double , const double , const PaintMethod)
DrawPathClose()
WandExport void DrawPathClose (DrawingWand *)
DrawPathCurveToAbsolute()
WandExport void DrawPathCurveToAbsolute (DrawingWand * , const double , const double , const double , const double , const double , const double)
DrawPathCurveToQuadraticBezierAbsolute()
WandExport void DrawPathCurveToQuadraticBezierAbsolute (DrawingWand * , const double , const double , const double , const double)
DrawPathCurveToQuadraticBezierRelative()
WandExport void DrawPathCurveToQuadraticBezierRelative (DrawingWand * , const double , const double , const double , const double)
DrawPathCurveToQuadraticBezierSmoothAbsolute()
WandExport void DrawPathCurveToQuadraticBezierSmoothAbsolute (DrawingWand * , const double , const double)
DrawPathCurveToQuadraticBezierSmoothRelative()
WandExport void DrawPathCurveToQuadraticBezierSmoothRelative (DrawingWand * , const double , const double)
DrawPathCurveToRelative()
WandExport void DrawPathCurveToRelative (DrawingWand * , const double , const double , const double , const double , const double , const double)
DrawPathCurveToSmoothAbsolute()
WandExport void DrawPathCurveToSmoothAbsolute (DrawingWand * , const double , const double , const double , const double)
DrawPathCurveToSmoothRelative()
WandExport void DrawPathCurveToSmoothRelative (DrawingWand * , const double , const double , const double , const double)
DrawPathEllipticArcAbsolute()
WandExport void DrawPathEllipticArcAbsolute (DrawingWand * , const double , const double , const double , const MagickBooleanType, const MagickBooleanType, const double , const double)
DrawPathEllipticArcRelative()
WandExport void DrawPathEllipticArcRelative (DrawingWand * , const double , const double , const double , const MagickBooleanType, const MagickBooleanType, const double , const double)
DrawPathFinish()
WandExport void DrawPathFinish (DrawingWand *)
DrawPathLineToAbsolute()
WandExport void DrawPathLineToAbsolute (DrawingWand * , const double , const double)
DrawPathLineToHorizontalAbsolute()
WandExport void DrawPathLineToHorizontalAbsolute (DrawingWand * , const double)
DrawPathLineToHorizontalRelative()
WandExport void DrawPathLineToHorizontalRelative (DrawingWand * , const double)
DrawPathLineToRelative()
WandExport void DrawPathLineToRelative (DrawingWand * , const double , const double)
DrawPathLineToVerticalAbsolute()
WandExport void DrawPathLineToVerticalAbsolute (DrawingWand * , const double)
DrawPathLineToVerticalRelative()
WandExport void DrawPathLineToVerticalRelative (DrawingWand * , const double)
DrawPathMoveToAbsolute()
WandExport void DrawPathMoveToAbsolute (DrawingWand * , const double , const double)
DrawPathMoveToRelative()
WandExport void DrawPathMoveToRelative (DrawingWand * , const double , const double)
DrawPathStart()
WandExport void DrawPathStart (DrawingWand *)
DrawPoint()
WandExport void DrawPoint (DrawingWand * , const double , const double)
DrawPolygon()
WandExport void DrawPolygon (DrawingWand * , const size_t, const PointInfo *)
DrawPolyline()
WandExport void DrawPolyline (DrawingWand * , const size_t, const PointInfo *)
DrawPopClipPath()
WandExport void DrawPopClipPath (DrawingWand *)
DrawPopDefs()
WandExport void DrawPopDefs (DrawingWand *)
DrawPopPattern()
WandExport MagickBooleanType DrawPopPattern (DrawingWand *)
DrawPushClipPath()
WandExport void DrawPushClipPath (DrawingWand * , const char *)
DrawPushDefs()
WandExport void DrawPushDefs (DrawingWand *)
DrawPushPattern()
WandExport MagickBooleanType DrawPushPattern (DrawingWand * , const char * , const double , const double , const double , const double)
DrawRectangle()
WandExport void DrawRectangle (DrawingWand * , const double , const double , const double , const double)
DrawRender()
WandExport MagickBooleanType DrawRender (DrawingWand *)
DrawResetVectorGraphics()
WandExport void DrawResetVectorGraphics (DrawingWand *)
DrawRotate()
WandExport void DrawRotate (DrawingWand * , const double)
DrawRoundRectangle()
WandExport void DrawRoundRectangle (DrawingWand * , double , double , double , double , double , double)
DrawScale()
WandExport void DrawScale (DrawingWand * , const double , const double)
DrawSetBorderColor()
WandExport void DrawSetBorderColor (DrawingWand * , const PixelWand *)
DrawSetClipPath()
WandExport MagickBooleanType DrawSetClipPath (DrawingWand * , const char *)
DrawSetClipRule()
WandExport void DrawSetClipRule (DrawingWand * , const FillRule)
DrawSetClipUnits()
WandExport void DrawSetClipUnits (DrawingWand * , const ClipPathUnits)
DrawSetDensity()
WandExport MagickBooleanType DrawSetDensity (DrawingWand * , const char *)
DrawSetFillColor()
WandExport void DrawSetFillColor (DrawingWand * , const PixelWand *)
DrawSetFillOpacity()
WandExport void DrawSetFillOpacity (DrawingWand * , const double)
DrawSetFillPatternURL()
WandExport MagickBooleanType DrawSetFillPatternURL (DrawingWand * , const char *)
DrawSetFillRule()
WandExport void DrawSetFillRule (DrawingWand * , const FillRule)
DrawSetFont()
WandExport MagickBooleanType DrawSetFont (DrawingWand * , const char *)
DrawSetFontFamily()
WandExport MagickBooleanType DrawSetFontFamily (DrawingWand * , const char *)
DrawSetFontResolution()
WandExport MagickBooleanType DrawSetFontResolution (DrawingWand * , const double , const double)
DrawSetFontSize()
WandExport void DrawSetFontSize (DrawingWand * , const double)
DrawSetFontStretch()
WandExport void DrawSetFontStretch (DrawingWand * , const StretchType)
DrawSetFontStyle()
WandExport void DrawSetFontStyle (DrawingWand * , const StyleType)
DrawSetFontWeight()
WandExport void DrawSetFontWeight (DrawingWand * , const size_t)
DrawSetGravity()
WandExport void DrawSetGravity (DrawingWand * , const GravityType)
DrawSetOpacity()
WandExport void DrawSetOpacity (DrawingWand * , const double)
DrawSetStrokeAntialias()
WandExport void DrawSetStrokeAntialias (DrawingWand * , const MagickBooleanType)
DrawSetStrokeColor()
WandExport void DrawSetStrokeColor (DrawingWand * , const PixelWand *)
DrawSetStrokeDashArray()
WandExport MagickBooleanType DrawSetStrokeDashArray (DrawingWand * , const size_t, const double *)
DrawSetStrokeDashOffset()
WandExport void DrawSetStrokeDashOffset (DrawingWand * , const double dashoffset)
DrawSetStrokeLineCap()
WandExport void DrawSetStrokeLineCap (DrawingWand * , const LineCap)
DrawSetStrokeLineJoin()
WandExport void DrawSetStrokeLineJoin (DrawingWand * , const LineJoin)
DrawSetStrokeMiterLimit()
WandExport void DrawSetStrokeMiterLimit (DrawingWand * , const size_t)
DrawSetStrokeOpacity()
WandExport void DrawSetStrokeOpacity (DrawingWand * , const double)
DrawSetStrokePatternURL()
WandExport MagickBooleanType DrawSetStrokePatternURL (DrawingWand * , const char *)
DrawSetStrokeWidth()
WandExport void DrawSetStrokeWidth (DrawingWand * , const double)
DrawSetTextAlignment()
WandExport void DrawSetTextAlignment (DrawingWand * , const AlignType)
DrawSetTextAntialias()
WandExport void DrawSetTextAntialias (DrawingWand * , const MagickBooleanType)
DrawSetTextDecoration()
WandExport void DrawSetTextDecoration (DrawingWand * , const DecorationType)
DrawSetTextDirection()
WandExport void DrawSetTextDirection (DrawingWand * , const DirectionType)
DrawSetTextEncoding()
WandExport void DrawSetTextEncoding (DrawingWand * , const char *)
DrawSetTextInterlineSpacing()
WandExport void DrawSetTextInterlineSpacing (DrawingWand * , const double)
DrawSetTextInterwordSpacing()
WandExport void DrawSetTextInterwordSpacing (DrawingWand * , const double)
DrawSetTextKerning()
WandExport void DrawSetTextKerning (DrawingWand * , const double)
DrawSetTextUnderColor()
WandExport void DrawSetTextUnderColor (DrawingWand * , const PixelWand *)
DrawSetVectorGraphics()
WandExport MagickBooleanType DrawSetVectorGraphics (DrawingWand * , const char *)
DrawSetViewbox()
WandExport void DrawSetViewbox (DrawingWand * , ssize_t , ssize_t , ssize_t , ssize_t)
DrawSkewX()
WandExport void DrawSkewX (DrawingWand * , const double)
DrawSkewY()
WandExport void DrawSkewY (DrawingWand * , const double)
DrawTranslate()
WandExport void DrawTranslate (DrawingWand * wand, const double x, const double y)
References _DrawingWand::debug, MVGPrintf(), _DrawingWand::name, _DrawingWand::signature, and WandSignature.
IsDrawingWand()
WandExport MagickBooleanType IsDrawingWand (const DrawingWand *)
NewDrawingWand()
WandExport DrawingWand * NewDrawingWand (void)
References AcquireWandId(), CurrentContext, _DrawingWand::debug, DefaultPathMode, _DrawingWand::destroy, DrawingWandId, _DrawingWand::exception, _DrawingWand::filter_off, _DrawingWand::graphic_context, _DrawingWand::id, _DrawingWand::image, _DrawingWand::indent_depth, _DrawingWand::index, MaxTextExtent, _DrawingWand::mvg, _DrawingWand::mvg_alloc, _DrawingWand::mvg_length, _DrawingWand::mvg_width, _DrawingWand::name, _DrawingWand::path_mode, _DrawingWand::path_operation, PathDefaultOperation, _DrawingWand::pattern_bounds, _DrawingWand::pattern_id, _DrawingWand::pattern_offset, _DrawingWand::signature, ThrowWandFatalException, and WandSignature.
Referenced by AcquireDrawingWand().
PeekDrawingWand()
WandExport DrawInfo * PeekDrawingWand (const DrawingWand * wand)
References CurrentContext, _DrawingWand::debug, _DrawingWand::mvg, _DrawingWand::name, _DrawingWand::signature, and WandSignature.
Referenced by DrawPeekGraphicWand(), MagickAffineTransformImage(), MagickAnnotateImage(), MagickDrawImage(), MagickPolaroidImage(), MagickQueryFontMetrics(), and MagickQueryMultilineFontMetrics().
PopDrawingWand()
WandExport MagickBooleanType PopDrawingWand (DrawingWand *)
PushDrawingWand()
WandExport MagickBooleanType PushDrawingWand (DrawingWand * wand)
References CurrentContext, _DrawingWand::debug, _DrawingWand::graphic_context, _DrawingWand::indent_depth, _DrawingWand::index, MVGPrintf(), _DrawingWand::name, _DrawingWand::signature, ThrowDrawException, and WandSignature.
Referenced by DrawPushGraphicContext().