MagickWand: magick-property.h File Reference
magick-property.h File Reference
Functions
WandExport char * MagickGetFilename (const MagickWand *)
WandExport char * MagickGetFormat (MagickWand *)
WandExport char * MagickGetFont (MagickWand *)
WandExport char * MagickGetHomeURL (void)
WandExport char * MagickGetImageArtifact (MagickWand *, const char *)
WandExport char ** MagickGetImageArtifacts (MagickWand *, const char *, size_t *)
WandExport char ** MagickGetImageProfiles (MagickWand *, const char *, size_t *)
WandExport char * MagickGetImageProperty (MagickWand *, const char *)
WandExport char ** MagickGetImageProperties (MagickWand *, const char *, size_t *)
WandExport char * MagickGetOption (MagickWand *, const char *)
WandExport char ** MagickGetOptions (MagickWand *, const char *, size_t *)
WandExport char * MagickQueryConfigureOption (const char *)
WandExport char ** MagickQueryConfigureOptions (const char *, size_t *)
WandExport char ** MagickQueryFonts (const char *, size_t *)
WandExport char ** MagickQueryFormats (const char *, size_t *)
WandExport ColorspaceType MagickGetColorspace (MagickWand *)
WandExport CompressionType MagickGetCompression (MagickWand *)
WandExport const char * MagickGetCopyright (void)
WandExport const char * MagickGetPackageName (void)
WandExport const char * MagickGetQuantumDepth (size_t *)
WandExport const char * MagickGetQuantumRange (size_t *)
WandExport const char * MagickGetReleaseDate (void)
WandExport const char * MagickGetVersion (size_t *)
WandExport double MagickGetPointsize (MagickWand *)
WandExport double * MagickGetSamplingFactors (MagickWand *, size_t *)
WandExport double * MagickQueryFontMetrics (MagickWand *, const DrawingWand *, const char *)
WandExport double * MagickQueryMultilineFontMetrics (MagickWand *, const DrawingWand *, const char *)
WandExport GravityType MagickGetGravity (MagickWand *)
WandExport ImageType MagickGetType (MagickWand *)
WandExport InterlaceType MagickGetInterlaceScheme (MagickWand *)
WandExport InterpolatePixelMethod MagickGetInterpolateMethod (MagickWand *)
WandExport OrientationType MagickGetOrientation (MagickWand *)
WandExport MagickBooleanType MagickDeleteImageArtifact (MagickWand *, const char *)
WandExport MagickBooleanType MagickDeleteImageProperty (MagickWand *, const char *)
WandExport MagickBooleanType MagickDeleteOption (MagickWand *, const char *)
WandExport MagickBooleanType MagickGetAntialias (const MagickWand *)
WandExport MagickBooleanType MagickGetPage (const MagickWand *, size_t *, size_t *, ssize_t *, ssize_t *)
WandExport MagickBooleanType MagickGetResolution (const MagickWand *, double *, double *)
WandExport MagickBooleanType MagickGetSize (const MagickWand *, size_t *, size_t *)
WandExport MagickBooleanType MagickGetSizeOffset (const MagickWand *, ssize_t *)
WandExport MagickBooleanType MagickProfileImage (MagickWand *, const char *, const void *, const size_t)
WandExport MagickBooleanType MagickSetAntialias (MagickWand *, const MagickBooleanType)
WandExport MagickBooleanType MagickSetBackgroundColor (MagickWand *, const PixelWand *)
WandExport MagickBooleanType MagickSetColorspace (MagickWand *, const ColorspaceType)
WandExport MagickBooleanType MagickSetCompression (MagickWand *, const CompressionType)
WandExport MagickBooleanType MagickSetCompressionQuality (MagickWand *, const size_t)
WandExport MagickBooleanType MagickSetDepth (MagickWand *, const size_t)
WandExport MagickBooleanType MagickSetExtract (MagickWand *, const char *)
WandExport MagickBooleanType MagickSetFilename (MagickWand *, const char *)
WandExport MagickBooleanType MagickSetFormat (MagickWand *, const char *)
WandExport MagickBooleanType MagickSetFont (MagickWand *, const char *)
WandExport MagickBooleanType MagickSetGravity (MagickWand *, const GravityType)
WandExport MagickBooleanType MagickSetImageArtifact (MagickWand *, const char *, const char *)
WandExport MagickBooleanType MagickSetImageProfile (MagickWand *, const char *, const void *, const size_t)
WandExport MagickBooleanType MagickSetImageProperty (MagickWand *, const char *, const char *)
WandExport MagickBooleanType MagickSetInterlaceScheme (MagickWand *, const InterlaceType)
WandExport MagickBooleanType MagickSetInterpolateMethod (MagickWand *, const InterpolatePixelMethod)
WandExport MagickBooleanType MagickSetOption (MagickWand *, const char *, const char *)
WandExport MagickBooleanType MagickSetOrientation (MagickWand *, const OrientationType)
WandExport MagickBooleanType MagickSetPage (MagickWand *, const size_t, const size_t, const ssize_t, const ssize_t)
WandExport MagickBooleanType MagickSetPassphrase (MagickWand *, const char *)
WandExport MagickBooleanType MagickSetPointsize (MagickWand *, const double)
WandExport MagickBooleanType MagickSetResolution (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickSetResourceLimit (const ResourceType type, const MagickSizeType limit)
WandExport MagickBooleanType MagickSetSamplingFactors (MagickWand *, const size_t, const double *)
WandExport MagickBooleanType MagickSetSecurityPolicy (MagickWand *, const char *)
WandExport MagickBooleanType MagickSetSize (MagickWand *, const size_t, const size_t)
WandExport MagickBooleanType MagickSetSizeOffset (MagickWand *, const size_t, const size_t, const ssize_t)
WandExport MagickBooleanType MagickSetType (MagickWand *, const ImageType)
WandExport MagickProgressMonitor MagickSetProgressMonitor (MagickWand *, const MagickProgressMonitor, void *)
WandExport MagickSizeType MagickGetResource (const ResourceType)
WandExport MagickSizeType MagickGetResourceLimit (const ResourceType)
WandExport PixelWand * MagickGetBackgroundColor (MagickWand *)
WandExport OrientationType MagickGetOrientationType (MagickWand *)
WandExport size_t MagickGetCompressionQuality (MagickWand *)
WandExport unsigned char * MagickGetImageProfile (MagickWand *, const char *, size_t *)
WandExport unsigned char * MagickRemoveImageProfile (MagickWand *, const char *, size_t *)
Function Documentation
MagickDeleteImageArtifact()
WandExport MagickBooleanType MagickDeleteImageArtifact (MagickWand * , const char *)
MagickDeleteImageProperty()
WandExport MagickBooleanType MagickDeleteImageProperty (MagickWand * , const char *)
MagickDeleteOption()
WandExport MagickBooleanType MagickDeleteOption (MagickWand * , const char *)
MagickGetAntialias()
WandExport MagickBooleanType MagickGetAntialias (const MagickWand *)
MagickGetBackgroundColor()
WandExport PixelWand * MagickGetBackgroundColor (MagickWand * wand)
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, NewPixelWand(), PixelSetQuantumColor(), _MagickWand::signature, and WandSignature.
MagickGetColorspace()
WandExport ColorspaceType MagickGetColorspace (MagickWand * wand)
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetCompression()
WandExport CompressionType MagickGetCompression (MagickWand * wand)
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetCompressionQuality()
WandExport size_t MagickGetCompressionQuality (MagickWand * wand)
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetCopyright()
WandExport const char * MagickGetCopyright (void)
MagickGetFilename()
WandExport char * MagickGetFilename (const MagickWand *)
MagickGetFont()
WandExport char * MagickGetFont (MagickWand *)
MagickGetFormat()
WandExport char * MagickGetFormat (MagickWand *)
MagickGetGravity()
WandExport GravityType MagickGetGravity (MagickWand * wand)
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetHomeURL()
WandExport char * MagickGetHomeURL (void)
MagickGetImageArtifact()
WandExport char * MagickGetImageArtifact (MagickWand * , const char *)
MagickGetImageArtifacts()
WandExport char ** MagickGetImageArtifacts (MagickWand * , const char * , size_t *)
MagickGetImageProfile()
WandExport unsigned char * MagickGetImageProfile (MagickWand * , const char * , size_t *)
MagickGetImageProfiles()
WandExport char ** MagickGetImageProfiles (MagickWand * , const char * , size_t *)
MagickGetImageProperties()
WandExport char ** MagickGetImageProperties (MagickWand * , const char * , size_t *)
MagickGetImageProperty()
WandExport char * MagickGetImageProperty (MagickWand * , const char *)
MagickGetInterlaceScheme()
WandExport InterlaceType MagickGetInterlaceScheme (MagickWand * wand)
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetInterpolateMethod()
WandExport InterpolatePixelMethod MagickGetInterpolateMethod (MagickWand * wand)
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetOption()
WandExport char * MagickGetOption (MagickWand * , const char *)
MagickGetOptions()
WandExport char ** MagickGetOptions (MagickWand * , const char * , size_t *)
MagickGetOrientation()
WandExport OrientationType MagickGetOrientation (MagickWand * wand)
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetOrientationType()
WandExport OrientationType MagickGetOrientationType (MagickWand *)
MagickGetPackageName()
WandExport const char * MagickGetPackageName (void)
MagickGetPage()
WandExport MagickBooleanType MagickGetPage (const MagickWand * , size_t * , size_t * , ssize_t * , ssize_t *)
MagickGetPointsize()
WandExport double MagickGetPointsize (MagickWand *)
MagickGetQuantumDepth()
WandExport const char * MagickGetQuantumDepth (size_t *)
MagickGetQuantumRange()
WandExport const char * MagickGetQuantumRange (size_t *)
MagickGetReleaseDate()
WandExport const char * MagickGetReleaseDate (void)
MagickGetResolution()
WandExport MagickBooleanType MagickGetResolution (const MagickWand * , double * , double *)
MagickGetResource()
WandExport MagickSizeType MagickGetResource (const ResourceType)
MagickGetResourceLimit()
WandExport MagickSizeType MagickGetResourceLimit (const ResourceType)
MagickGetSamplingFactors()
WandExport double * MagickGetSamplingFactors (MagickWand * , size_t *)
MagickGetSize()
WandExport MagickBooleanType MagickGetSize (const MagickWand * , size_t * , size_t *)
MagickGetSizeOffset()
WandExport MagickBooleanType MagickGetSizeOffset (const MagickWand * , ssize_t *)
MagickGetType()
WandExport ImageType MagickGetType (MagickWand * wand)
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetVersion()
WandExport const char * MagickGetVersion (size_t * version)
MagickProfileImage()
WandExport MagickBooleanType MagickProfileImage (MagickWand * , const char * , const void * , const size_t)
MagickQueryConfigureOption()
WandExport char * MagickQueryConfigureOption (const char *)
MagickQueryConfigureOptions()
WandExport char ** MagickQueryConfigureOptions (const char * , size_t *)
MagickQueryFontMetrics()
WandExport double * MagickQueryFontMetrics (MagickWand * , const DrawingWand * , const char *)
MagickQueryFonts()
WandExport char ** MagickQueryFonts (const char * , size_t *)
MagickQueryFormats()
WandExport char ** MagickQueryFormats (const char * pattern, size_t * number_formats)
MagickQueryMultilineFontMetrics()
WandExport double * MagickQueryMultilineFontMetrics (MagickWand * wand, const DrawingWand * drawing_wand, const char * text)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PeekDrawingWand(), _MagickWand::signature, and WandSignature.
MagickRemoveImageProfile()
WandExport unsigned char * MagickRemoveImageProfile (MagickWand * wand, const char * name, size_t * length)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickSetAntialias()
WandExport MagickBooleanType MagickSetAntialias (MagickWand * , const MagickBooleanType)
MagickSetBackgroundColor()
WandExport MagickBooleanType MagickSetBackgroundColor (MagickWand * , const PixelWand *)
MagickSetColorspace()
WandExport MagickBooleanType MagickSetColorspace (MagickWand * , const ColorspaceType)
MagickSetCompression()
WandExport MagickBooleanType MagickSetCompression (MagickWand * , const CompressionType)
MagickSetCompressionQuality()
WandExport MagickBooleanType MagickSetCompressionQuality (MagickWand * , const size_t)
MagickSetDepth()
WandExport MagickBooleanType MagickSetDepth (MagickWand * , const size_t)
MagickSetExtract()
WandExport MagickBooleanType MagickSetExtract (MagickWand * , const char *)
MagickSetFilename()
WandExport MagickBooleanType MagickSetFilename (MagickWand * , const char *)
MagickSetFont()
WandExport MagickBooleanType MagickSetFont (MagickWand * , const char *)
MagickSetFormat()
WandExport MagickBooleanType MagickSetFormat (MagickWand * , const char *)
MagickSetGravity()
WandExport MagickBooleanType MagickSetGravity (MagickWand * , const GravityType)
MagickSetImageArtifact()
WandExport MagickBooleanType MagickSetImageArtifact (MagickWand * , const char * , const char *)
MagickSetImageProfile()
WandExport MagickBooleanType MagickSetImageProfile (MagickWand * , const char * , const void * , const size_t)
MagickSetImageProperty()
WandExport MagickBooleanType MagickSetImageProperty (MagickWand * , const char * , const char *)
MagickSetInterlaceScheme()
WandExport MagickBooleanType MagickSetInterlaceScheme (MagickWand * , const InterlaceType)
MagickSetInterpolateMethod()
WandExport MagickBooleanType MagickSetInterpolateMethod (MagickWand * , const InterpolatePixelMethod)
MagickSetOption()
WandExport MagickBooleanType MagickSetOption (MagickWand * , const char * , const char *)
MagickSetOrientation()
WandExport MagickBooleanType MagickSetOrientation (MagickWand * , const OrientationType)
MagickSetPage()
WandExport MagickBooleanType MagickSetPage (MagickWand * , const size_t, const size_t, const ssize_t, const ssize_t)
MagickSetPassphrase()
WandExport MagickBooleanType MagickSetPassphrase (MagickWand * , const char *)
MagickSetPointsize()
WandExport MagickBooleanType MagickSetPointsize (MagickWand * , const double)
MagickSetProgressMonitor()
WandExport MagickProgressMonitor MagickSetProgressMonitor (MagickWand * wand, const MagickProgressMonitor, void * client_data)
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickSetResolution()
WandExport MagickBooleanType MagickSetResolution (MagickWand * , const double , const double)
MagickSetResourceLimit()
WandExport MagickBooleanType MagickSetResourceLimit (const ResourceType type, const MagickSizeType limit)
MagickSetSamplingFactors()
WandExport MagickBooleanType MagickSetSamplingFactors (MagickWand * , const size_t, const double *)
MagickSetSecurityPolicy()
WandExport MagickBooleanType MagickSetSecurityPolicy (MagickWand * , const char *)
MagickSetSize()
WandExport MagickBooleanType MagickSetSize (MagickWand * , const size_t, const size_t)
MagickSetSizeOffset()
WandExport MagickBooleanType MagickSetSizeOffset (MagickWand * , const size_t, const size_t, const ssize_t)
MagickSetType()
WandExport MagickBooleanType MagickSetType (MagickWand * wand, const ImageType)
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::name, _MagickWand::signature, and WandSignature.