MagickWand: magick-wand.c File Reference
magick-wand.c File Reference
#include "wand/studio.h"
#include "wand/MagickWand.h"
#include "wand/magick-wand-private.h"
#include "wand/wand.h"
Functions
WandExport void ClearMagickWand (MagickWand *wand)
WandExport MagickWand * CloneMagickWand (const MagickWand *wand)
WandExport MagickWand * DestroyMagickWand (MagickWand *wand)
WandExport MagickBooleanType IsMagickWand (const MagickWand *wand)
WandExport MagickBooleanType MagickClearException (MagickWand *wand)
WandExport char * MagickGetException (const MagickWand *wand, ExceptionType *severity)
WandExport ExceptionType MagickGetExceptionType (const MagickWand *wand)
WandExport ssize_t MagickGetIteratorIndex (MagickWand *wand)
WandExport char * MagickQueryConfigureOption (const char *option)
WandExport char ** MagickQueryConfigureOptions (const char *pattern, size_t *number_options)
WandExport double * MagickQueryFontMetrics (MagickWand *wand, const DrawingWand *drawing_wand, const char *text)
WandExport double * MagickQueryMultilineFontMetrics (MagickWand *wand, const DrawingWand *drawing_wand, const char *text)
WandExport char ** MagickQueryFonts (const char *pattern, size_t *number_fonts)
WandExport char ** MagickQueryFormats (const char *pattern, size_t *number_formats)
WandExport void * MagickRelinquishMemory (void *memory)
WandExport void MagickResetIterator (MagickWand *wand)
WandExport void MagickSetFirstIterator (MagickWand *wand)
WandExport MagickBooleanType MagickSetIteratorIndex (MagickWand *wand, const ssize_t index)
WandExport void MagickSetLastIterator (MagickWand *wand)
WandExport void MagickWandGenesis (void)
WandExport void MagickWandTerminus (void)
WandExport MagickWand * NewMagickWand (void)
WandExport MagickWand * NewMagickWandFromImage (const Image *image)
MagickExport MagickBooleanType IsMagickWandInstantiated (void)
Function Documentation
ClearMagickWand()
WandExport void ClearMagickWand (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::quantize_info, _MagickWand::signature, and WandSignature.
CloneMagickWand()
WandExport MagickWand * CloneMagickWand (const MagickWand * wand)
References AcquireWandId(), _MagickWand::debug, _MagickWand::exception, _MagickWand::id, _MagickWand::image_info, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, MagickWandId, MaxTextExtent, _MagickWand::name, _MagickWand::quantize_info, _MagickWand::signature, and WandSignature.
DestroyMagickWand()
WandExport MagickWand * DestroyMagickWand (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::id, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::quantize_info, RelinquishWandId(), _MagickWand::signature, and WandSignature.
IsMagickWand()
WandExport MagickBooleanType IsMagickWand (const MagickWand * wand)
References MagickWandId, _MagickWand::name, _MagickWand::signature, and WandSignature.
IsMagickWandInstantiated()
MagickExport MagickBooleanType IsMagickWandInstantiated (void)
MagickClearException()
WandExport MagickBooleanType MagickClearException (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetException()
WandExport char * MagickGetException (const MagickWand * wand, ExceptionType * severity)
References _MagickWand::debug, _MagickWand::exception, MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetExceptionType()
WandExport ExceptionType MagickGetExceptionType (const MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetIteratorIndex()
WandExport ssize_t MagickGetIteratorIndex (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
Referenced by MagickGetImageIndex().
MagickQueryConfigureOption()
WandExport char * MagickQueryConfigureOption (const char * option)
MagickQueryConfigureOptions()
WandExport char ** MagickQueryConfigureOptions (const char * pattern, size_t * number_options)
MagickQueryFontMetrics()
WandExport double * MagickQueryFontMetrics (MagickWand * wand, const DrawingWand * drawing_wand, const char * text)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PeekDrawingWand(), _MagickWand::signature, and WandSignature.
MagickQueryFonts()
WandExport char ** MagickQueryFonts (const char * pattern, size_t * number_fonts)
MagickQueryFormats()
WandExport char ** MagickQueryFormats (const char * pattern, size_t * number_formats)
MagickQueryMultilineFontMetrics()
WandExport double * MagickQueryMultilineFontMetrics (MagickWand * wand, const DrawingWand * drawing_wand, const char * text)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PeekDrawingWand(), _MagickWand::signature, and WandSignature.
MagickRelinquishMemory()
WandExport void * MagickRelinquishMemory (void * memory)
MagickResetIterator()
WandExport void MagickResetIterator (MagickWand * wand)
References _MagickWand::debug, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickSetFirstIterator()
WandExport void MagickSetFirstIterator (MagickWand * wand)
References _MagickWand::debug, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickSetIteratorIndex()
WandExport MagickBooleanType MagickSetIteratorIndex (MagickWand * wand, const ssize_t index)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::signature, and WandSignature.
Referenced by MagickSetImageIndex().
MagickSetLastIterator()
WandExport void MagickSetLastIterator (MagickWand * wand)
References _MagickWand::debug, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickWandGenesis()
WandExport void MagickWandGenesis (void)
MagickWandTerminus()
WandExport void MagickWandTerminus (void)
References DestroyWandIds().
NewMagickWand()
WandExport MagickWand * NewMagickWand (void)
References AcquireWandId(), _MagickWand::debug, _MagickWand::exception, _MagickWand::id, _MagickWand::image_info, _MagickWand::images, MagickWandId, MaxTextExtent, _MagickWand::name, _MagickWand::quantize_info, _MagickWand::signature, ThrowWandFatalException, and WandSignature.
Referenced by NewMagickWandFromImage().
NewMagickWandFromImage()
WandExport MagickWand * NewMagickWandFromImage (const Image * image)
References _MagickWand::exception, _MagickWand::images, and NewMagickWand().