MagickWand: MagickWand.h File Reference
MagickWand.h File Reference
#include "magick/magick-config.h"
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <stdint.h>
#include <math.h>
#include <sys/types.h>
#include <time.h>
#include "wand/method-attribute.h"
#include "magick/MagickCore.h"
#include "wand/animate.h"
#include "wand/compare.h"
#include "wand/composite.h"
#include "wand/conjure.h"
#include "wand/convert.h"
#include "wand/deprecate.h"
#include "wand/display.h"
#include "wand/drawing-wand.h"
#include "wand/identify.h"
#include "wand/import.h"
#include "wand/magick-property.h"
#include "wand/magick-image.h"
#include "wand/mogrify.h"
#include "wand/montage.h"
#include "wand/pixel-iterator.h"
#include "wand/pixel-wand.h"
#include "wand/stream.h"
#include "wand/wand-view.h"
Macros
#define MAGICKWAND_CONFIG_H
#define magick_restrict restrict
#define MAGICKWAND_CHECK_VERSION(major, minor, micro)
#define MAGICKWAND_POSIX_SUPPORT
Typedefs
typedef struct _MagickWand MagickWand
Functions
WandExport char * MagickGetException (const MagickWand *, ExceptionType *)
WandExport ExceptionType MagickGetExceptionType (const MagickWand *)
WandExport MagickBooleanType IsMagickWand (const MagickWand *)
WandExport MagickBooleanType IsMagickWandInstantiated (void)
WandExport MagickBooleanType MagickClearException (MagickWand *)
WandExport MagickBooleanType MagickSetIteratorIndex (MagickWand *, const ssize_t)
WandExport MagickWand * CloneMagickWand (const MagickWand *)
WandExport MagickWand * DestroyMagickWand (MagickWand *)
WandExport MagickWand * NewMagickWand (void)
WandExport MagickWand * NewMagickWandFromImage (const Image *)
WandExport ssize_t MagickGetIteratorIndex (MagickWand *)
WandExport void ClearMagickWand (MagickWand *)
WandExport void MagickWandGenesis (void)
WandExport void MagickWandTerminus (void)
WandExport void * MagickRelinquishMemory (void *)
WandExport void MagickResetIterator (MagickWand *)
WandExport void MagickSetFirstIterator (MagickWand *)
WandExport void MagickSetLastIterator (MagickWand *)
Macro Definition Documentation
magick_restrict
#define magick_restrict restrict
MAGICKWAND_CHECK_VERSION
#define MAGICKWAND_CHECK_VERSION (major, minor, micro)
Value:
  ((MAGICKWAND_MAJOR_VERSION > (major)) || \
    ((MAGICKWAND_MAJOR_VERSION == (major)) && \
     (MAGICKWAND_MINOR_VERSION > (minor))) || \
    ((MAGICKWAND_MAJOR_VERSION == (major)) && \
     (MAGICKWAND_MINOR_VERSION == (minor)) && \
     (MAGICKWAND_MICRO_VERSION >= (micro))))
MAGICKWAND_CONFIG_H
#define MAGICKWAND_CONFIG_H
MAGICKWAND_POSIX_SUPPORT
#define MAGICKWAND_POSIX_SUPPORT
Typedef Documentation
MagickWand
typedef struct _MagickWand MagickWand
Function Documentation
ClearMagickWand()
WandExport void ClearMagickWand (MagickWand *)
CloneMagickWand()
WandExport MagickWand * CloneMagickWand (const MagickWand *)
DestroyMagickWand()
WandExport MagickWand * DestroyMagickWand (MagickWand *)
IsMagickWand()
WandExport MagickBooleanType IsMagickWand (const MagickWand *)
IsMagickWandInstantiated()
WandExport MagickBooleanType IsMagickWandInstantiated (void)
MagickClearException()
WandExport MagickBooleanType MagickClearException (MagickWand *)
MagickGetException()
WandExport char * MagickGetException (const MagickWand * wand, ExceptionType * severity)
References _MagickWand::debug, _MagickWand::exception, MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetExceptionType()
WandExport ExceptionType MagickGetExceptionType (const MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetIteratorIndex()
WandExport ssize_t MagickGetIteratorIndex (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
Referenced by MagickGetImageIndex().
MagickRelinquishMemory()
WandExport void * MagickRelinquishMemory (void *)
MagickResetIterator()
WandExport void MagickResetIterator (MagickWand *)
MagickSetFirstIterator()
WandExport void MagickSetFirstIterator (MagickWand *)
MagickSetIteratorIndex()
WandExport MagickBooleanType MagickSetIteratorIndex (MagickWand * wand, const ssize_t)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::signature, and WandSignature.
Referenced by MagickSetImageIndex().
MagickSetLastIterator()
WandExport void MagickSetLastIterator (MagickWand * wand)
References _MagickWand::debug, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickWandGenesis()
WandExport void MagickWandGenesis (void)
MagickWandTerminus()
WandExport void MagickWandTerminus (void)
NewMagickWand()
WandExport MagickWand * NewMagickWand (void)
NewMagickWandFromImage()
WandExport MagickWand * NewMagickWandFromImage (const Image * image)
References _MagickWand::exception, _MagickWand::images, and NewMagickWand().