MagickWand: magick-image.c File Reference
magick-image.c File Reference
#include "wand/studio.h"
#include "wand/MagickWand.h"
#include "wand/magick-wand-private.h"
#include "wand/wand.h"
#include "wand/pixel-wand-private.h"
#include "magick/image-private.h"
Macros
#define MagickWandId "MagickWand"
Functions
static MagickWand * CloneMagickWandFromImages (const MagickWand *wand, Image *images)
WandExport Image * GetImageFromMagickWand (const MagickWand *wand)
WandExport MagickBooleanType MagickAdaptiveBlurImage (MagickWand *wand, const double radius, const double sigma)
WandExport MagickBooleanType MagickAdaptiveBlurImageChannel (MagickWand *wand, const ChannelType channel, const double radius, const double sigma)
WandExport MagickBooleanType MagickAdaptiveResizeImage (MagickWand *wand, const size_t columns, const size_t rows)
WandExport MagickBooleanType MagickAdaptiveSharpenImage (MagickWand *wand, const double radius, const double sigma)
WandExport MagickBooleanType MagickAdaptiveSharpenImageChannel (MagickWand *wand, const ChannelType channel, const double radius, const double sigma)
WandExport MagickBooleanType MagickAdaptiveThresholdImage (MagickWand *wand, const size_t width, const size_t height, const ssize_t offset)
static MagickBooleanType InsertImageInWand (MagickWand *wand, Image *images)
WandExport MagickBooleanType MagickAddImage (MagickWand *wand, const MagickWand *add_wand)
WandExport MagickBooleanType MagickAddNoiseImage (MagickWand *wand, const NoiseType noise_type)
WandExport MagickBooleanType MagickAddNoiseImageChannel (MagickWand *wand, const ChannelType channel, const NoiseType noise_type)
WandExport MagickBooleanType MagickAffineTransformImage (MagickWand *wand, const DrawingWand *drawing_wand)
WandExport MagickBooleanType MagickAnnotateImage (MagickWand *wand, const DrawingWand *drawing_wand, const double x, const double y, const double angle, const char *text)
WandExport MagickBooleanType MagickAnimateImages (MagickWand *wand, const char *server_name)
WandExport MagickWand * MagickAppendImages (MagickWand *wand, const MagickBooleanType stack)
WandExport MagickBooleanType MagickAutoGammaImage (MagickWand *wand)
WandExport MagickBooleanType MagickAutoGammaImageChannel (MagickWand *wand, const ChannelType channel)
WandExport MagickBooleanType MagickAutoLevelImage (MagickWand *wand)
WandExport MagickBooleanType MagickAutoLevelImageChannel (MagickWand *wand, const ChannelType channel)
WandExport MagickBooleanType MagickAutoOrientImage (MagickWand *wand)
WandExport MagickBooleanType MagickBlackThresholdImage (MagickWand *wand, const PixelWand *threshold)
WandExport MagickBooleanType MagickBlueShiftImage (MagickWand *wand, const double factor)
WandExport MagickBooleanType MagickBlurImage (MagickWand *wand, const double radius, const double sigma)
WandExport MagickBooleanType MagickBlurImageChannel (MagickWand *wand, const ChannelType channel, const double radius, const double sigma)
WandExport MagickBooleanType MagickBorderImage (MagickWand *wand, const PixelWand *bordercolor, const size_t width, const size_t height)
WandExport MagickBooleanType MagickBrightnessContrastImage (MagickWand *wand, const double brightness, const double contrast)
WandExport MagickBooleanType MagickBrightnessContrastImageChannel (MagickWand *wand, const ChannelType channel, const double brightness, const double contrast)
WandExport MagickBooleanType MagickCharcoalImage (MagickWand *wand, const double radius, const double sigma)
WandExport MagickBooleanType MagickChopImage (MagickWand *wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickClampImage (MagickWand *wand)
WandExport MagickBooleanType MagickClampImageChannel (MagickWand *wand, const ChannelType channel)
WandExport MagickBooleanType MagickClipImage (MagickWand *wand)
WandExport MagickBooleanType MagickClipImagePath (MagickWand *wand, const char *pathname, const MagickBooleanType inside)
WandExport MagickBooleanType MagickClutImage (MagickWand *wand, const MagickWand *clut_wand)
WandExport MagickBooleanType MagickClutImageChannel (MagickWand *wand, const ChannelType channel, const MagickWand *clut_wand)
WandExport MagickWand * MagickCoalesceImages (MagickWand *wand)
WandExport MagickBooleanType MagickColorDecisionListImage (MagickWand *wand, const char *color_correction_collection)
WandExport MagickBooleanType MagickColorizeImage (MagickWand *wand, const PixelWand *colorize, const PixelWand *opacity)
WandExport MagickBooleanType MagickColorMatrixImage (MagickWand *wand, const KernelInfo *color_matrix)
WandExport MagickWand * MagickCombineImages (MagickWand *wand, const ChannelType channel)
WandExport MagickBooleanType MagickCommentImage (MagickWand *wand, const char *comment)
WandExport MagickWand * MagickCompareImageChannels (MagickWand *wand, const MagickWand *reference, const ChannelType channel, const MetricType metric, double *distortion)
WandExport MagickWand * MagickCompareImageLayers (MagickWand *wand, const ImageLayerMethod method)
WandExport MagickWand * MagickCompareImages (MagickWand *wand, const MagickWand *reference, const MetricType metric, double *distortion)
WandExport MagickBooleanType MagickCompositeImage (MagickWand *wand, const MagickWand *source_wand, const CompositeOperator compose, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickCompositeImageChannel (MagickWand *wand, const ChannelType channel, const MagickWand *source_wand, const CompositeOperator compose, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickCompositeImageGravity (MagickWand *wand, const MagickWand *source_wand, const CompositeOperator compose, const GravityType gravity)
WandExport MagickBooleanType MagickCompositeLayers (MagickWand *wand, const MagickWand *source_wand, const CompositeOperator compose, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickContrastImage (MagickWand *wand, const MagickBooleanType sharpen)
WandExport MagickBooleanType MagickContrastStretchImage (MagickWand *wand, const double black_point, const double white_point)
WandExport MagickBooleanType MagickContrastStretchImageChannel (MagickWand *wand, const ChannelType channel, const double black_point, const double white_point)
WandExport MagickBooleanType MagickConvolveImage (MagickWand *wand, const size_t order, const double *kernel)
WandExport MagickBooleanType MagickConvolveImageChannel (MagickWand *wand, const ChannelType channel, const size_t order, const double *kernel)
WandExport MagickBooleanType MagickCropImage (MagickWand *wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickCycleColormapImage (MagickWand *wand, const ssize_t displace)
WandExport MagickBooleanType MagickConstituteImage (MagickWand *wand, const size_t columns, const size_t rows, const char *map, const StorageType storage, const void *pixels)
WandExport MagickBooleanType MagickDecipherImage (MagickWand *wand, const char *passphrase)
WandExport MagickWand * MagickDeconstructImages (MagickWand *wand)
WandExport MagickBooleanType MagickDeskewImage (MagickWand *wand, const double threshold)
WandExport MagickBooleanType MagickDespeckleImage (MagickWand *wand)
WandExport Image * MagickDestroyImage (Image *image)
WandExport MagickBooleanType MagickDisplayImage (MagickWand *wand, const char *server_name)
WandExport MagickBooleanType MagickDisplayImages (MagickWand *wand, const char *server_name)
WandExport MagickBooleanType MagickDistortImage (MagickWand *wand, const DistortImageMethod method, const size_t number_arguments, const double *arguments, const MagickBooleanType bestfit)
WandExport MagickBooleanType MagickDrawImage (MagickWand *wand, const DrawingWand *drawing_wand)
WandExport MagickBooleanType MagickEdgeImage (MagickWand *wand, const double radius)
WandExport MagickBooleanType MagickEmbossImage (MagickWand *wand, const double radius, const double sigma)
WandExport MagickBooleanType MagickEncipherImage (MagickWand *wand, const char *passphrase)
WandExport MagickBooleanType MagickEnhanceImage (MagickWand *wand)
WandExport MagickBooleanType MagickEqualizeImage (MagickWand *wand)
WandExport MagickBooleanType MagickEqualizeImageChannel (MagickWand *wand, const ChannelType channel)
WandExport MagickBooleanType MagickEvaluateImage (MagickWand *wand, const MagickEvaluateOperator op, const double value)
WandExport MagickWand * MagickEvaluateImages (MagickWand *wand, const MagickEvaluateOperator op)
WandExport MagickBooleanType MagickEvaluateImageChannel (MagickWand *wand, const ChannelType channel, const MagickEvaluateOperator op, const double value)
WandExport MagickBooleanType MagickExportImagePixels (MagickWand *wand, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, const char *map, const StorageType storage, void *pixels)
WandExport MagickBooleanType MagickExtentImage (MagickWand *wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickFilterImage (MagickWand *wand, const KernelInfo *kernel)
WandExport MagickBooleanType MagickFilterImageChannel (MagickWand *wand, const ChannelType channel, const KernelInfo *kernel)
WandExport MagickBooleanType MagickFlipImage (MagickWand *wand)
WandExport MagickBooleanType MagickFloodfillPaintImage (MagickWand *wand, const ChannelType channel, const PixelWand *fill, const double fuzz, const PixelWand *bordercolor, const ssize_t x, const ssize_t y, const MagickBooleanType invert)
WandExport MagickBooleanType MagickFlopImage (MagickWand *wand)
WandExport MagickBooleanType MagickForwardFourierTransformImage (MagickWand *wand, const MagickBooleanType magnitude)
WandExport MagickBooleanType MagickFrameImage (MagickWand *wand, const PixelWand *matte_color, const size_t width, const size_t height, const ssize_t inner_bevel, const ssize_t outer_bevel)
WandExport MagickBooleanType MagickFunctionImage (MagickWand *wand, const MagickFunction function, const size_t number_arguments, const double *arguments)
WandExport MagickBooleanType MagickFunctionImageChannel (MagickWand *wand, const ChannelType channel, const MagickFunction function, const size_t number_arguments, const double *arguments)
WandExport MagickWand * MagickFxImage (MagickWand *wand, const char *expression)
WandExport MagickWand * MagickFxImageChannel (MagickWand *wand, const ChannelType channel, const char *expression)
WandExport MagickBooleanType MagickGammaImage (MagickWand *wand, const double gamma)
WandExport MagickBooleanType MagickGammaImageChannel (MagickWand *wand, const ChannelType channel, const double gamma)
WandExport MagickBooleanType MagickGaussianBlurImage (MagickWand *wand, const double radius, const double sigma)
WandExport MagickBooleanType MagickGaussianBlurImageChannel (MagickWand *wand, const ChannelType channel, const double radius, const double sigma)
WandExport MagickWand * MagickGetImage (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageAlphaChannel (MagickWand *wand)
WandExport MagickWand * MagickGetImageClipMask (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageBackgroundColor (MagickWand *wand, PixelWand *background_color)
WandExport unsigned char * MagickGetImageBlob (MagickWand *wand, size_t *length)
WandExport unsigned char * MagickGetImagesBlob (MagickWand *wand, size_t *length)
WandExport MagickBooleanType MagickGetImageBluePrimary (MagickWand *wand, double *x, double *y)
WandExport MagickBooleanType MagickGetImageBorderColor (MagickWand *wand, PixelWand *border_color)
WandExport size_t MagickGetImageChannelDepth (MagickWand *wand, const ChannelType channel)
WandExport MagickBooleanType MagickGetImageChannelDistortion (MagickWand *wand, const MagickWand *reference, const ChannelType channel, const MetricType metric, double *distortion)
WandExport double * MagickGetImageChannelDistortions (MagickWand *wand, const MagickWand *reference, const MetricType metric)
WandExport ChannelFeatures * MagickGetImageChannelFeatures (MagickWand *wand, const size_t distance)
WandExport MagickBooleanType MagickGetImageChannelKurtosis (MagickWand *wand, const ChannelType channel, double *kurtosis, double *skewness)
WandExport MagickBooleanType MagickGetImageChannelMean (MagickWand *wand, const ChannelType channel, double *mean, double *standard_deviation)
WandExport MagickBooleanType MagickGetImageChannelRange (MagickWand *wand, const ChannelType channel, double *minima, double *maxima)
WandExport ChannelStatistics * MagickGetImageChannelStatistics (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageColormapColor (MagickWand *wand, const size_t index, PixelWand *color)
WandExport size_t MagickGetImageColors (MagickWand *wand)
WandExport ColorspaceType MagickGetImageColorspace (MagickWand *wand)
WandExport CompositeOperator MagickGetImageCompose (MagickWand *wand)
WandExport CompressionType MagickGetImageCompression (MagickWand *wand)
WandExport size_t MagickGetImageCompressionQuality (MagickWand *wand)
WandExport size_t MagickGetImageDelay (MagickWand *wand)
WandExport size_t MagickGetImageDepth (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageDistortion (MagickWand *wand, const MagickWand *reference, const MetricType metric, double *distortion)
WandExport DisposeType MagickGetImageDispose (MagickWand *wand)
WandExport EndianType MagickGetImageEndian (MagickWand *wand)
WandExport char * MagickGetImageFilename (MagickWand *wand)
WandExport char * MagickGetImageFormat (MagickWand *wand)
WandExport double MagickGetImageFuzz (MagickWand *wand)
WandExport double MagickGetImageGamma (MagickWand *wand)
WandExport GravityType MagickGetImageGravity (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageGreenPrimary (MagickWand *wand, double *x, double *y)
WandExport size_t MagickGetImageHeight (MagickWand *wand)
WandExport PixelWand ** MagickGetImageHistogram (MagickWand *wand, size_t *number_colors)
WandExport InterlaceType MagickGetImageInterlaceScheme (MagickWand *wand)
WandExport InterpolatePixelMethod MagickGetImageInterpolateMethod (MagickWand *wand)
WandExport size_t MagickGetImageIterations (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageLength (MagickWand *wand, MagickSizeType *length)
WandExport MagickBooleanType MagickGetImageMatteColor (MagickWand *wand, PixelWand *matte_color)
WandExport OrientationType MagickGetImageOrientation (MagickWand *wand)
WandExport MagickBooleanType MagickGetImagePage (MagickWand *wand, size_t *width, size_t *height, ssize_t *x, ssize_t *y)
WandExport MagickBooleanType MagickGetImagePixelColor (MagickWand *wand, const ssize_t x, const ssize_t y, PixelWand *color)
WandExport MagickBooleanType MagickGetImageRange (MagickWand *wand, double *minima, double *maxima)
WandExport MagickBooleanType MagickGetImageRedPrimary (MagickWand *wand, double *x, double *y)
WandExport MagickWand * MagickGetImageRegion (MagickWand *wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
WandExport RenderingIntent MagickGetImageRenderingIntent (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageResolution (MagickWand *wand, double *x, double *y)
WandExport size_t MagickGetImageScene (MagickWand *wand)
WandExport char * MagickGetImageSignature (MagickWand *wand)
WandExport size_t MagickGetImageTicksPerSecond (MagickWand *wand)
WandExport ImageType MagickGetImageType (MagickWand *wand)
WandExport ResolutionType MagickGetImageUnits (MagickWand *wand)
WandExport VirtualPixelMethod MagickGetImageVirtualPixelMethod (MagickWand *wand)
WandExport MagickBooleanType MagickGetImageWhitePoint (MagickWand *wand, double *x, double *y)
WandExport size_t MagickGetImageWidth (MagickWand *wand)
WandExport size_t MagickGetNumberImages (MagickWand *wand)
WandExport double MagickGetImageTotalInkDensity (MagickWand *wand)
WandExport MagickBooleanType MagickHaldClutImage (MagickWand *wand, const MagickWand *hald_wand)
WandExport MagickBooleanType MagickHaldClutImageChannel (MagickWand *wand, const ChannelType channel, const MagickWand *hald_wand)
WandExport MagickBooleanType MagickHasNextImage (MagickWand *wand)
WandExport MagickBooleanType MagickHasPreviousImage (MagickWand *wand)
WandExport char * MagickIdentifyImage (MagickWand *wand)
WandExport MagickBooleanType MagickImplodeImage (MagickWand *wand, const double amount)
WandExport MagickBooleanType MagickImportImagePixels (MagickWand *wand, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, const char *map, const StorageType storage, const void *pixels)
WandExport MagickBooleanType MagickInverseFourierTransformImage (MagickWand *magnitude_wand, MagickWand *phase_wand, const MagickBooleanType magnitude)
WandExport MagickBooleanType MagickLabelImage (MagickWand *wand, const char *label)
WandExport MagickBooleanType MagickLevelImage (MagickWand *wand, const double black_point, const double gamma, const double white_point)
WandExport MagickBooleanType MagickLevelImageChannel (MagickWand *wand, const ChannelType channel, const double black_point, const double gamma, const double white_point)
WandExport MagickBooleanType MagickLevelImageColors (MagickWand *wand, const PixelWand *black_color, const PixelWand *white_color, const MagickBooleanType invert)
WandExport MagickBooleanType MagickLevelImageColorsChannel (MagickWand *wand, const ChannelType channel, const PixelWand *black_color, const PixelWand *white_color, const MagickBooleanType invert)
WandExport MagickBooleanType MagickLevelizeImage (MagickWand *wand, const double black_point, const double gamma, const double white_point)
WandExport MagickBooleanType MagickLevelizeImageChannel (MagickWand *wand, const ChannelType channel, const double black_point, const double gamma, const double white_point)
WandExport MagickBooleanType MagickLinearStretchImage (MagickWand *wand, const double black_point, const double white_point)
WandExport MagickBooleanType MagickLiquidRescaleImage (MagickWand *wand, const size_t columns, const size_t rows, const double delta_x, const double rigidity)
WandExport MagickBooleanType MagickLocalContrastImage (MagickWand *wand, const double radius, const double strength)
WandExport MagickBooleanType MagickMagnifyImage (MagickWand *wand)
WandExport MagickWand * MagickMergeImageLayers (MagickWand *wand, const ImageLayerMethod method)
WandExport MagickBooleanType MagickMinifyImage (MagickWand *wand)
WandExport MagickBooleanType MagickModulateImage (MagickWand *wand, const double brightness, const double saturation, const double hue)
WandExport MagickWand * MagickMontageImage (MagickWand *wand, const DrawingWand *drawing_wand, const char *tile_geometry, const char *thumbnail_geometry, const MontageMode mode, const char *frame)
WandExport MagickWand * MagickMorphImages (MagickWand *wand, const size_t number_frames)
WandExport MagickBooleanType MagickMorphologyImage (MagickWand *wand, const MorphologyMethod method, const ssize_t iterations, const KernelInfo *kernel)
WandExport MagickBooleanType MagickMorphologyImageChannel (MagickWand *wand, const ChannelType channel, const MorphologyMethod method, const ssize_t iterations, const KernelInfo *kernel)
WandExport MagickBooleanType MagickMotionBlurImage (MagickWand *wand, const double radius, const double sigma, const double angle)
WandExport MagickBooleanType MagickMotionBlurImageChannel (MagickWand *wand, const ChannelType channel, const double radius, const double sigma, const double angle)
WandExport MagickBooleanType MagickNegateImage (MagickWand *wand, const MagickBooleanType gray)
WandExport MagickBooleanType MagickNegateImageChannel (MagickWand *wand, const ChannelType channel, const MagickBooleanType gray)
WandExport MagickBooleanType MagickNewImage (MagickWand *wand, const size_t width, const size_t height, const PixelWand *background)
WandExport MagickBooleanType MagickNextImage (MagickWand *wand)
WandExport MagickBooleanType MagickNormalizeImage (MagickWand *wand)
WandExport MagickBooleanType MagickNormalizeImageChannel (MagickWand *wand, const ChannelType channel)
WandExport MagickBooleanType MagickOilPaintImage (MagickWand *wand, const double radius)
WandExport MagickBooleanType MagickOpaquePaintImage (MagickWand *wand, const PixelWand *target, const PixelWand *fill, const double fuzz, const MagickBooleanType invert)
WandExport MagickBooleanType MagickOpaquePaintImageChannel (MagickWand *wand, const ChannelType channel, const PixelWand *target, const PixelWand *fill, const double fuzz, const MagickBooleanType invert)
WandExport MagickWand * MagickOptimizeImageLayers (MagickWand *wand)
WandExport MagickBooleanType MagickOptimizeImageTransparency (MagickWand *wand)
WandExport MagickBooleanType MagickOrderedPosterizeImage (MagickWand *wand, const char *threshold_map)
WandExport MagickBooleanType MagickOrderedPosterizeImageChannel (MagickWand *wand, const ChannelType channel, const char *threshold_map)
WandExport MagickBooleanType MagickPingImage (MagickWand *wand, const char *filename)
WandExport MagickBooleanType MagickPingImageBlob (MagickWand *wand, const void *blob, const size_t length)
WandExport MagickBooleanType MagickPingImageFile (MagickWand *wand, FILE *file)
WandExport MagickBooleanType MagickPolaroidImage (MagickWand *wand, const DrawingWand *drawing_wand, const double angle)
WandExport MagickBooleanType MagickPosterizeImage (MagickWand *wand, const size_t levels, const MagickBooleanType dither)
WandExport MagickWand * MagickPreviewImages (MagickWand *wand, const PreviewType preview)
WandExport MagickBooleanType MagickPreviousImage (MagickWand *wand)
WandExport MagickBooleanType MagickQuantizeImage (MagickWand *wand, const size_t number_colors, const ColorspaceType colorspace, const size_t treedepth, const MagickBooleanType dither, const MagickBooleanType measure_error)
WandExport MagickBooleanType MagickQuantizeImages (MagickWand *wand, const size_t number_colors, const ColorspaceType colorspace, const size_t treedepth, const MagickBooleanType dither, const MagickBooleanType measure_error)
WandExport MagickBooleanType MagickRaiseImage (MagickWand *wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y, const MagickBooleanType raise)
WandExport MagickBooleanType MagickRandomThresholdImage (MagickWand *wand, const double low, const double high)
WandExport MagickBooleanType MagickRandomThresholdImageChannel (MagickWand *wand, const ChannelType channel, const double low, const double high)
WandExport MagickBooleanType MagickReadImage (MagickWand *wand, const char *filename)
WandExport MagickBooleanType MagickReadImageBlob (MagickWand *wand, const void *blob, const size_t length)
WandExport MagickBooleanType MagickReadImageFile (MagickWand *wand, FILE *file)
WandExport MagickBooleanType MagickRemapImage (MagickWand *wand, const MagickWand *remap_wand, const DitherMethod method)
WandExport MagickBooleanType MagickRemoveImage (MagickWand *wand)
WandExport MagickBooleanType MagickResampleImage (MagickWand *wand, const double x_resolution, const double y_resolution, const FilterTypes filter, const double blur)
WandExport MagickBooleanType MagickResetImagePage (MagickWand *wand, const char *page)
WandExport MagickBooleanType MagickResizeImage (MagickWand *wand, const size_t columns, const size_t rows, const FilterTypes filter, const double blur)
WandExport MagickBooleanType MagickRollImage (MagickWand *wand, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickRotateImage (MagickWand *wand, const PixelWand *background, const double degrees)
WandExport MagickBooleanType MagickRotationalBlurImage (MagickWand *wand, const double angle)
WandExport MagickBooleanType MagickRotationalBlurImageChannel (MagickWand *wand, const ChannelType channel, const double angle)
WandExport MagickBooleanType MagickSampleImage (MagickWand *wand, const size_t columns, const size_t rows)
WandExport MagickBooleanType MagickScaleImage (MagickWand *wand, const size_t columns, const size_t rows)
MagickExport MagickBooleanType MagickSegmentImage (MagickWand *wand, const ColorspaceType colorspace, const MagickBooleanType verbose, const double cluster_threshold, const double smooth_threshold)
WandExport MagickBooleanType MagickSelectiveBlurImage (MagickWand *wand, const double radius, const double sigma, const double threshold)
WandExport MagickBooleanType MagickSelectiveBlurImageChannel (MagickWand *wand, const ChannelType channel, const double radius, const double sigma, const double threshold)
WandExport MagickBooleanType MagickSeparateImageChannel (MagickWand *wand, const ChannelType channel)
WandExport MagickBooleanType MagickSepiaToneImage (MagickWand *wand, const double threshold)
WandExport MagickBooleanType MagickSetImage (MagickWand *wand, const MagickWand *set_wand)
WandExport MagickBooleanType MagickSetImageAlphaChannel (MagickWand *wand, const AlphaChannelType alpha_type)
WandExport MagickBooleanType MagickSetImageBackgroundColor (MagickWand *wand, const PixelWand *background)
WandExport MagickBooleanType MagickSetImageBias (MagickWand *wand, const double bias)
WandExport MagickBooleanType MagickSetImageBluePrimary (MagickWand *wand, const double x, const double y)
WandExport MagickBooleanType MagickSetImageBorderColor (MagickWand *wand, const PixelWand *border)
WandExport MagickBooleanType MagickSetImageChannelDepth (MagickWand *wand, const ChannelType channel, const size_t depth)
WandExport MagickBooleanType MagickSetImageClipMask (MagickWand *wand, const MagickWand *clip_mask)
WandExport MagickBooleanType MagickSetImageColor (MagickWand *wand, const PixelWand *color)
WandExport MagickBooleanType MagickSetImageColormapColor (MagickWand *wand, const size_t index, const PixelWand *color)
WandExport MagickBooleanType MagickSetImageColorspace (MagickWand *wand, const ColorspaceType colorspace)
WandExport MagickBooleanType MagickSetImageCompose (MagickWand *wand, const CompositeOperator compose)
WandExport MagickBooleanType MagickSetImageCompression (MagickWand *wand, const CompressionType compression)
WandExport MagickBooleanType MagickSetImageCompressionQuality (MagickWand *wand, const size_t quality)
WandExport MagickBooleanType MagickSetImageDelay (MagickWand *wand, const size_t delay)
WandExport MagickBooleanType MagickSetImageDepth (MagickWand *wand, const size_t depth)
WandExport MagickBooleanType MagickSetImageDispose (MagickWand *wand, const DisposeType dispose)
WandExport MagickBooleanType MagickSetImageEndian (MagickWand *wand, const EndianType endian)
WandExport MagickBooleanType MagickSetImageExtent (MagickWand *wand, const size_t columns, const size_t rows)
WandExport MagickBooleanType MagickSetImageFilename (MagickWand *wand, const char *filename)
WandExport MagickBooleanType MagickSetImageFormat (MagickWand *wand, const char *format)
WandExport MagickBooleanType MagickSetImageFuzz (MagickWand *wand, const double fuzz)
WandExport MagickBooleanType MagickSetImageGamma (MagickWand *wand, const double gamma)
WandExport MagickBooleanType MagickSetImageGravity (MagickWand *wand, const GravityType gravity)
WandExport MagickBooleanType MagickSetImageGreenPrimary (MagickWand *wand, const double x, const double y)
WandExport MagickBooleanType MagickSetImageInterlaceScheme (MagickWand *wand, const InterlaceType interlace)
WandExport MagickBooleanType MagickSetImageInterpolateMethod (MagickWand *wand, const InterpolatePixelMethod method)
WandExport MagickBooleanType MagickSetImageIterations (MagickWand *wand, const size_t iterations)
WandExport MagickBooleanType MagickSetImageMatte (MagickWand *wand, const MagickBooleanType matte)
WandExport MagickBooleanType MagickSetImageMatteColor (MagickWand *wand, const PixelWand *matte)
WandExport MagickBooleanType MagickSetImageOpacity (MagickWand *wand, const double alpha)
WandExport MagickBooleanType MagickSetImageOrientation (MagickWand *wand, const OrientationType orientation)
WandExport MagickBooleanType MagickSetImagePage (MagickWand *wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickSetImagePixelColor (MagickWand *wand, const ssize_t x, const ssize_t y, const PixelWand *color)
WandExport MagickProgressMonitor MagickSetImageProgressMonitor (MagickWand *wand, const MagickProgressMonitor progress_monitor, void *client_data)
WandExport MagickBooleanType MagickSetImageRedPrimary (MagickWand *wand, const double x, const double y)
WandExport MagickBooleanType MagickSetImageRenderingIntent (MagickWand *wand, const RenderingIntent rendering_intent)
WandExport MagickBooleanType MagickSetImageResolution (MagickWand *wand, const double x_resolution, const double y_resolution)
WandExport MagickBooleanType MagickSetImageScene (MagickWand *wand, const size_t scene)
WandExport MagickBooleanType MagickSetImageTicksPerSecond (MagickWand *wand, const ssize_t ticks_per_second)
WandExport MagickBooleanType MagickSetImageType (MagickWand *wand, const ImageType image_type)
WandExport MagickBooleanType MagickSetImageUnits (MagickWand *wand, const ResolutionType units)
WandExport VirtualPixelMethod MagickSetImageVirtualPixelMethod (MagickWand *wand, const VirtualPixelMethod method)
WandExport MagickBooleanType MagickSetImageWhitePoint (MagickWand *wand, const double x, const double y)
WandExport MagickBooleanType MagickShadeImage (MagickWand *wand, const MagickBooleanType gray, const double asimuth, const double elevation)
WandExport MagickBooleanType MagickShadowImage (MagickWand *wand, const double opacity, const double sigma, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickSharpenImage (MagickWand *wand, const double radius, const double sigma)
WandExport MagickBooleanType MagickSharpenImageChannel (MagickWand *wand, const ChannelType channel, const double radius, const double sigma)
WandExport MagickBooleanType MagickShaveImage (MagickWand *wand, const size_t columns, const size_t rows)
WandExport MagickBooleanType MagickShearImage (MagickWand *wand, const PixelWand *background, const double x_shear, const double y_shear)
WandExport MagickBooleanType MagickSigmoidalContrastImage (MagickWand *wand, const MagickBooleanType sharpen, const double alpha, const double beta)
WandExport MagickBooleanType MagickSigmoidalContrastImageChannel (MagickWand *wand, const ChannelType channel, const MagickBooleanType sharpen, const double alpha, const double beta)
WandExport MagickWand * MagickSimilarityImage (MagickWand *wand, const MagickWand *reference, RectangleInfo *offset, double *similarity)
WandExport MagickBooleanType MagickSketchImage (MagickWand *wand, const double radius, const double sigma, const double angle)
WandExport MagickWand * MagickSmushImages (MagickWand *wand, const MagickBooleanType stack, const ssize_t offset)
WandExport MagickBooleanType MagickSolarizeImage (MagickWand *wand, const double threshold)
WandExport MagickBooleanType MagickSolarizeImageChannel (MagickWand *wand, const ChannelType channel, const double threshold)
WandExport MagickBooleanType MagickSparseColorImage (MagickWand *wand, const ChannelType channel, const SparseColorMethod method, const size_t number_arguments, const double *arguments)
WandExport MagickBooleanType MagickSpliceImage (MagickWand *wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickSpreadImage (MagickWand *wand, const double radius)
WandExport MagickBooleanType MagickStatisticImage (MagickWand *wand, const StatisticType type, const size_t width, const size_t height)
WandExport MagickBooleanType MagickStatisticImageChannel (MagickWand *wand, const ChannelType channel, const StatisticType type, const size_t width, const size_t height)
WandExport MagickWand * MagickSteganoImage (MagickWand *wand, const MagickWand *watermark_wand, const ssize_t offset)
WandExport MagickWand * MagickStereoImage (MagickWand *wand, const MagickWand *offset_wand)
WandExport MagickBooleanType MagickStripImage (MagickWand *wand)
WandExport MagickBooleanType MagickSwirlImage (MagickWand *wand, const double degrees)
WandExport MagickWand * MagickTextureImage (MagickWand *wand, const MagickWand *texture_wand)
WandExport MagickBooleanType MagickThresholdImage (MagickWand *wand, const double threshold)
WandExport MagickBooleanType MagickThresholdImageChannel (MagickWand *wand, const ChannelType channel, const double threshold)
WandExport MagickBooleanType MagickThumbnailImage (MagickWand *wand, const size_t columns, const size_t rows)
WandExport MagickBooleanType MagickTintImage (MagickWand *wand, const PixelWand *tint, const PixelWand *opacity)
WandExport MagickWand * MagickTransformImage (MagickWand *wand, const char *crop, const char *geometry)
WandExport MagickBooleanType MagickTransformImageColorspace (MagickWand *wand, const ColorspaceType colorspace)
WandExport MagickBooleanType MagickTransparentPaintImage (MagickWand *wand, const PixelWand *target, const double alpha, const double fuzz, const MagickBooleanType invert)
WandExport MagickBooleanType MagickTransposeImage (MagickWand *wand)
WandExport MagickBooleanType MagickTransverseImage (MagickWand *wand)
WandExport MagickBooleanType MagickTrimImage (MagickWand *wand, const double fuzz)
WandExport MagickBooleanType MagickUniqueImageColors (MagickWand *wand)
WandExport MagickBooleanType MagickUnsharpMaskImage (MagickWand *wand, const double radius, const double sigma, const double amount, const double threshold)
WandExport MagickBooleanType MagickUnsharpMaskImageChannel (MagickWand *wand, const ChannelType channel, const double radius, const double sigma, const double amount, const double threshold)
WandExport MagickBooleanType MagickVignetteImage (MagickWand *wand, const double black_point, const double white_point, const ssize_t x, const ssize_t y)
WandExport MagickBooleanType MagickWaveImage (MagickWand *wand, const double amplitude, const double wave_length)
WandExport MagickBooleanType MagickWhiteThresholdImage (MagickWand *wand, const PixelWand *threshold)
WandExport MagickBooleanType MagickWriteImage (MagickWand *wand, const char *filename)
WandExport MagickBooleanType MagickWriteImageFile (MagickWand *wand, FILE *file)
WandExport MagickBooleanType MagickWriteImages (MagickWand *wand, const char *filename, const MagickBooleanType adjoin)
WandExport MagickBooleanType MagickWriteImagesFile (MagickWand *wand, FILE *file)
Macro Definition Documentation
MagickWandId
#define MagickWandId "MagickWand"
Function Documentation
CloneMagickWandFromImages()
static MagickWand * CloneMagickWandFromImages (const MagickWand * wand, Image * images) static
References AcquireWandId(), _MagickWand::debug, _MagickWand::exception, _MagickWand::id, _MagickWand::image_info, _MagickWand::images, MagickWandId, MaxTextExtent, _MagickWand::name, _MagickWand::quantize_info, _MagickWand::signature, and WandSignature.
Referenced by MagickAppendImages(), MagickCoalesceImages(), MagickCombineImages(), MagickCompareImageChannels(), MagickCompareImageLayers(), MagickCompareImages(), MagickDeconstructImages(), MagickEvaluateImages(), MagickFxImageChannel(), MagickGetImage(), MagickGetImageClipMask(), MagickGetImageRegion(), MagickMergeImageLayers(), MagickMontageImage(), MagickMorphImages(), MagickOptimizeImageLayers(), MagickPreviewImages(), MagickSimilarityImage(), MagickSmushImages(), MagickSteganoImage(), MagickStereoImage(), MagickTextureImage(), and MagickTransformImage().
GetImageFromMagickWand()
WandExport Image * GetImageFromMagickWand (const MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
Referenced by DrawComposite(), NewPixelIterator(), and NewPixelRegionIterator().
InsertImageInWand()
static MagickBooleanType InsertImageInWand (MagickWand * wand, Image * images) inline static
References _MagickWand::images, and _MagickWand::insert_before.
Referenced by MagickAddImage(), MagickConstituteImage(), MagickNewImage(), MagickPingImage(), MagickPingImageBlob(), MagickPingImageFile(), MagickReadImage(), MagickReadImageBlob(), and MagickReadImageFile().
MagickAdaptiveBlurImage()
WandExport MagickBooleanType MagickAdaptiveBlurImage (MagickWand * wand, const double radius, const double sigma)
References MagickAdaptiveBlurImageChannel().
MagickAdaptiveBlurImageChannel()
WandExport MagickBooleanType MagickAdaptiveBlurImageChannel (MagickWand * wand, const ChannelType channel, const double radius, const double sigma)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickAdaptiveBlurImage().
MagickAdaptiveResizeImage()
WandExport MagickBooleanType MagickAdaptiveResizeImage (MagickWand * wand, const size_t columns, const size_t rows)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickAdaptiveSharpenImage()
WandExport MagickBooleanType MagickAdaptiveSharpenImage (MagickWand * wand, const double radius, const double sigma)
References MagickAdaptiveSharpenImageChannel().
MagickAdaptiveSharpenImageChannel()
WandExport MagickBooleanType MagickAdaptiveSharpenImageChannel (MagickWand * wand, const ChannelType channel, const double radius, const double sigma)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickAdaptiveSharpenImage().
MagickAdaptiveThresholdImage()
WandExport MagickBooleanType MagickAdaptiveThresholdImage (MagickWand * wand, const size_t width, const size_t height, const ssize_t offset)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickAddImage()
WandExport MagickBooleanType MagickAddImage (MagickWand * wand, const MagickWand * add_wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, InsertImageInWand(), _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickAddNoiseImage()
WandExport MagickBooleanType MagickAddNoiseImage (MagickWand * wand, const NoiseType noise_type)
References MagickAddNoiseImageChannel().
MagickAddNoiseImageChannel()
WandExport MagickBooleanType MagickAddNoiseImageChannel (MagickWand * wand, const ChannelType channel, const NoiseType noise_type)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickAddNoiseImage().
MagickAffineTransformImage()
WandExport MagickBooleanType MagickAffineTransformImage (MagickWand * wand, const DrawingWand * drawing_wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PeekDrawingWand(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickAnimateImages()
WandExport MagickBooleanType MagickAnimateImages (MagickWand * wand, const char * server_name)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickAnnotateImage()
WandExport MagickBooleanType MagickAnnotateImage (MagickWand * wand, const DrawingWand * drawing_wand, const double x, const double y, const double angle, const char * text)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, PeekDrawingWand(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickAppendImages()
WandExport MagickWand * MagickAppendImages (MagickWand * wand, const MagickBooleanType stack)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickAutoGammaImage()
WandExport MagickBooleanType MagickAutoGammaImage (MagickWand * wand)
References MagickAutoGammaImageChannel().
MagickAutoGammaImageChannel()
WandExport MagickBooleanType MagickAutoGammaImageChannel (MagickWand * wand, const ChannelType channel)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickAutoGammaImage().
MagickAutoLevelImage()
WandExport MagickBooleanType MagickAutoLevelImage (MagickWand * wand)
References MagickAutoLevelImageChannel().
MagickAutoLevelImageChannel()
WandExport MagickBooleanType MagickAutoLevelImageChannel (MagickWand * wand, const ChannelType channel)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickAutoLevelImage().
MagickAutoOrientImage()
WandExport MagickBooleanType MagickAutoOrientImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickBlackThresholdImage()
WandExport MagickBooleanType MagickBlackThresholdImage (MagickWand * wand, const PixelWand * threshold)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, PixelGetBlueQuantum(), PixelGetGreenQuantum(), PixelGetOpacityQuantum(), PixelGetRedQuantum(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickBlueShiftImage()
WandExport MagickBooleanType MagickBlueShiftImage (MagickWand * wand, const double factor)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickBlurImage()
WandExport MagickBooleanType MagickBlurImage (MagickWand * wand, const double radius, const double sigma)
References MagickBlurImageChannel().
MagickBlurImageChannel()
WandExport MagickBooleanType MagickBlurImageChannel (MagickWand * wand, const ChannelType channel, const double radius, const double sigma)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickBlurImage().
MagickBorderImage()
WandExport MagickBooleanType MagickBorderImage (MagickWand * wand, const PixelWand * bordercolor, const size_t width, const size_t height)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetQuantumColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickBrightnessContrastImage()
WandExport MagickBooleanType MagickBrightnessContrastImage (MagickWand * wand, const double brightness, const double contrast)
References MagickBrightnessContrastImageChannel().
MagickBrightnessContrastImageChannel()
WandExport MagickBooleanType MagickBrightnessContrastImageChannel (MagickWand * wand, const ChannelType channel, const double brightness, const double contrast)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickBrightnessContrastImage().
MagickCharcoalImage()
WandExport MagickBooleanType MagickCharcoalImage (MagickWand * wand, const double radius, const double sigma)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickChopImage()
WandExport MagickBooleanType MagickChopImage (MagickWand * wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickClampImage()
WandExport MagickBooleanType MagickClampImage (MagickWand * wand)
References MagickClampImageChannel().
MagickClampImageChannel()
WandExport MagickBooleanType MagickClampImageChannel (MagickWand * wand, const ChannelType channel)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickClampImage().
MagickClipImage()
WandExport MagickBooleanType MagickClipImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickClipImagePath()
WandExport MagickBooleanType MagickClipImagePath (MagickWand * wand, const char * pathname, const MagickBooleanType inside)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickClipPathImage().
MagickClutImage()
WandExport MagickBooleanType MagickClutImage (MagickWand * wand, const MagickWand * clut_wand)
References MagickClutImageChannel().
MagickClutImageChannel()
WandExport MagickBooleanType MagickClutImageChannel (MagickWand * wand, const ChannelType channel, const MagickWand * clut_wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickClutImage().
MagickCoalesceImages()
WandExport MagickWand * MagickCoalesceImages (MagickWand * wand)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickColorDecisionListImage()
WandExport MagickBooleanType MagickColorDecisionListImage (MagickWand * wand, const char * color_correction_collection)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickColorizeImage()
WandExport MagickBooleanType MagickColorizeImage (MagickWand * wand, const PixelWand * colorize, const PixelWand * opacity)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, PixelGetBlueQuantum(), PixelGetGreenQuantum(), PixelGetOpacityQuantum(), PixelGetQuantumColor(), PixelGetRedQuantum(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickColorMatrixImage()
WandExport MagickBooleanType MagickColorMatrixImage (MagickWand * wand, const KernelInfo * color_matrix)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickCombineImages()
WandExport MagickWand * MagickCombineImages (MagickWand * wand, const ChannelType channel)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickCommentImage()
WandExport MagickBooleanType MagickCommentImage (MagickWand * wand, const char * comment)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickCompareImageChannels()
WandExport MagickWand * MagickCompareImageChannels (MagickWand * wand, const MagickWand * reference, const ChannelType channel, const MetricType metric, double * distortion)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickCompareImageLayers()
WandExport MagickWand * MagickCompareImageLayers (MagickWand * wand, const ImageLayerMethod method)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickCompareImages()
WandExport MagickWand * MagickCompareImages (MagickWand * wand, const MagickWand * reference, const MetricType metric, double * distortion)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickCompositeImage()
WandExport MagickBooleanType MagickCompositeImage (MagickWand * wand, const MagickWand * source_wand, const CompositeOperator compose, const ssize_t x, const ssize_t y)
References MagickCompositeImageChannel().
MagickCompositeImageChannel()
WandExport MagickBooleanType MagickCompositeImageChannel (MagickWand * wand, const ChannelType channel, const MagickWand * source_wand, const CompositeOperator compose, const ssize_t x, const ssize_t y)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickCompositeImage().
MagickCompositeImageGravity()
WandExport MagickBooleanType MagickCompositeImageGravity (MagickWand * wand, const MagickWand * source_wand, const CompositeOperator compose, const GravityType gravity)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickCompositeLayers()
WandExport MagickBooleanType MagickCompositeLayers (MagickWand * wand, const MagickWand * source_wand, const CompositeOperator compose, const ssize_t x, const ssize_t y)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickConstituteImage()
WandExport MagickBooleanType MagickConstituteImage (MagickWand * wand, const size_t columns, const size_t rows, const char * map, const StorageType storage, const void * pixels)
References _MagickWand::debug, _MagickWand::exception, InsertImageInWand(), _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickContrastImage()
WandExport MagickBooleanType MagickContrastImage (MagickWand * wand, const MagickBooleanType sharpen)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickContrastStretchImage()
WandExport MagickBooleanType MagickContrastStretchImage (MagickWand * wand, const double black_point, const double white_point)
References MagickContrastStretchImageChannel().
MagickContrastStretchImageChannel()
WandExport MagickBooleanType MagickContrastStretchImageChannel (MagickWand * wand, const ChannelType channel, const double black_point, const double white_point)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickContrastStretchImage().
MagickConvolveImage()
WandExport MagickBooleanType MagickConvolveImage (MagickWand * wand, const size_t order, const double * kernel)
References MagickConvolveImageChannel().
MagickConvolveImageChannel()
WandExport MagickBooleanType MagickConvolveImageChannel (MagickWand * wand, const ChannelType channel, const size_t order, const double * kernel)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickConvolveImage().
MagickCropImage()
WandExport MagickBooleanType MagickCropImage (MagickWand * wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickCycleColormapImage()
WandExport MagickBooleanType MagickCycleColormapImage (MagickWand * wand, const ssize_t displace)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickDecipherImage()
WandExport MagickBooleanType MagickDecipherImage (MagickWand * wand, const char * passphrase)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickDeconstructImages()
WandExport MagickWand * MagickDeconstructImages (MagickWand * wand)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickDeskewImage()
WandExport MagickBooleanType MagickDeskewImage (MagickWand * wand, const double threshold)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickDespeckleImage()
WandExport MagickBooleanType MagickDespeckleImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickDestroyImage()
WandExport Image * MagickDestroyImage (Image * image)
MagickDisplayImage()
WandExport MagickBooleanType MagickDisplayImage (MagickWand * wand, const char * server_name)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickDisplayImages()
WandExport MagickBooleanType MagickDisplayImages (MagickWand * wand, const char * server_name)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickDistortImage()
WandExport MagickBooleanType MagickDistortImage (MagickWand * wand, const DistortImageMethod method, const size_t number_arguments, const double * arguments, const MagickBooleanType bestfit)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickDrawImage()
WandExport MagickBooleanType MagickDrawImage (MagickWand * wand, const DrawingWand * drawing_wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, PeekDrawingWand(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickEdgeImage()
WandExport MagickBooleanType MagickEdgeImage (MagickWand * wand, const double radius)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickEmbossImage()
WandExport MagickBooleanType MagickEmbossImage (MagickWand * wand, const double radius, const double sigma)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickEncipherImage()
WandExport MagickBooleanType MagickEncipherImage (MagickWand * wand, const char * passphrase)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickEnhanceImage()
WandExport MagickBooleanType MagickEnhanceImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickEqualizeImage()
WandExport MagickBooleanType MagickEqualizeImage (MagickWand * wand)
References MagickEqualizeImageChannel().
MagickEqualizeImageChannel()
WandExport MagickBooleanType MagickEqualizeImageChannel (MagickWand * wand, const ChannelType channel)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickEqualizeImage().
MagickEvaluateImage()
WandExport MagickBooleanType MagickEvaluateImage (MagickWand * wand, const MagickEvaluateOperator op, const double value)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickEvaluateImageChannel()
WandExport MagickBooleanType MagickEvaluateImageChannel (MagickWand * wand, const ChannelType channel, const MagickEvaluateOperator op, const double value)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickEvaluateImages()
WandExport MagickWand * MagickEvaluateImages (MagickWand * wand, const MagickEvaluateOperator op)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickExportImagePixels()
WandExport MagickBooleanType MagickExportImagePixels (MagickWand * wand, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, const char * map, const StorageType storage, void * pixels)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickGetImagePixels().
MagickExtentImage()
WandExport MagickBooleanType MagickExtentImage (MagickWand * wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickFilterImage()
WandExport MagickBooleanType MagickFilterImage (MagickWand * wand, const KernelInfo * kernel)
References MagickFilterImageChannel().
MagickFilterImageChannel()
WandExport MagickBooleanType MagickFilterImageChannel (MagickWand * wand, const ChannelType channel, const KernelInfo * kernel)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickFilterImage().
MagickFlipImage()
WandExport MagickBooleanType MagickFlipImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickFloodfillPaintImage()
WandExport MagickBooleanType MagickFloodfillPaintImage (MagickWand * wand, const ChannelType channel, const PixelWand * fill, const double fuzz, const PixelWand * bordercolor, const ssize_t x, const ssize_t y, const MagickBooleanType invert)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, PixelGetMagickColor(), PixelGetQuantumColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickPaintFloodfillImage().
MagickFlopImage()
WandExport MagickBooleanType MagickFlopImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickForwardFourierTransformImage()
WandExport MagickBooleanType MagickForwardFourierTransformImage (MagickWand * wand, const MagickBooleanType magnitude)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickFrameImage()
WandExport MagickBooleanType MagickFrameImage (MagickWand * wand, const PixelWand * matte_color, const size_t width, const size_t height, const ssize_t inner_bevel, const ssize_t outer_bevel)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetQuantumColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickFunctionImage()
WandExport MagickBooleanType MagickFunctionImage (MagickWand * wand, const MagickFunction function, const size_t number_arguments, const double * arguments)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickFunctionImageChannel()
WandExport MagickBooleanType MagickFunctionImageChannel (MagickWand * wand, const ChannelType channel, const MagickFunction function, const size_t number_arguments, const double * arguments)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickFxImage()
WandExport MagickWand * MagickFxImage (MagickWand * wand, const char * expression)
References MagickFxImageChannel().
MagickFxImageChannel()
WandExport MagickWand * MagickFxImageChannel (MagickWand * wand, const ChannelType channel, const char * expression)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
Referenced by MagickFxImage().
MagickGammaImage()
WandExport MagickBooleanType MagickGammaImage (MagickWand * wand, const double gamma)
References MagickGammaImageChannel().
MagickGammaImageChannel()
WandExport MagickBooleanType MagickGammaImageChannel (MagickWand * wand, const ChannelType channel, const double gamma)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickGammaImage().
MagickGaussianBlurImage()
WandExport MagickBooleanType MagickGaussianBlurImage (MagickWand * wand, const double radius, const double sigma)
References MagickGaussianBlurImageChannel().
MagickGaussianBlurImageChannel()
WandExport MagickBooleanType MagickGaussianBlurImageChannel (MagickWand * wand, const ChannelType channel, const double radius, const double sigma)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickGaussianBlurImage().
MagickGetImage()
WandExport MagickWand * MagickGetImage (MagickWand * wand)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageAlphaChannel()
WandExport MagickBooleanType MagickGetImageAlphaChannel (MagickWand * wand)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageBackgroundColor()
WandExport MagickBooleanType MagickGetImageBackgroundColor (MagickWand * wand, PixelWand * background_color)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, PixelSetQuantumColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageBlob()
WandExport unsigned char * MagickGetImageBlob (MagickWand * wand, size_t * length)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
Referenced by MagickWriteImageBlob().
MagickGetImageBluePrimary()
WandExport MagickBooleanType MagickGetImageBluePrimary (MagickWand * wand, double * x, double * y)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageBorderColor()
WandExport MagickBooleanType MagickGetImageBorderColor (MagickWand * wand, PixelWand * border_color)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, PixelSetQuantumColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageChannelDepth()
WandExport size_t MagickGetImageChannelDepth (MagickWand * wand, const ChannelType channel)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageChannelDistortion()
WandExport MagickBooleanType MagickGetImageChannelDistortion (MagickWand * wand, const MagickWand * reference, const ChannelType channel, const MetricType metric, double * distortion)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageChannelDistortions()
WandExport double * MagickGetImageChannelDistortions (MagickWand * wand, const MagickWand * reference, const MetricType metric)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageChannelFeatures()
WandExport ChannelFeatures * MagickGetImageChannelFeatures (MagickWand * wand, const size_t distance)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageChannelKurtosis()
WandExport MagickBooleanType MagickGetImageChannelKurtosis (MagickWand * wand, const ChannelType channel, double * kurtosis, double * skewness)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageChannelMean()
WandExport MagickBooleanType MagickGetImageChannelMean (MagickWand * wand, const ChannelType channel, double * mean, double * standard_deviation)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageChannelRange()
WandExport MagickBooleanType MagickGetImageChannelRange (MagickWand * wand, const ChannelType channel, double * minima, double * maxima)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageChannelStatistics()
WandExport ChannelStatistics * MagickGetImageChannelStatistics (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageClipMask()
WandExport MagickWand * MagickGetImageClipMask (MagickWand * wand)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageColormapColor()
WandExport MagickBooleanType MagickGetImageColormapColor (MagickWand * wand, const size_t index, PixelWand * color)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelSetQuantumColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageColors()
WandExport size_t MagickGetImageColors (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageColorspace()
WandExport ColorspaceType MagickGetImageColorspace (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageCompose()
WandExport CompositeOperator MagickGetImageCompose (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageCompression()
WandExport CompressionType MagickGetImageCompression (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageCompressionQuality()
WandExport size_t MagickGetImageCompressionQuality (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageDelay()
WandExport size_t MagickGetImageDelay (MagickWand * wand)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageDepth()
WandExport size_t MagickGetImageDepth (MagickWand * wand)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageDispose()
WandExport DisposeType MagickGetImageDispose (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageDistortion()
WandExport MagickBooleanType MagickGetImageDistortion (MagickWand * wand, const MagickWand * reference, const MetricType metric, double * distortion)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageEndian()
WandExport EndianType MagickGetImageEndian (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageFilename()
WandExport char * MagickGetImageFilename (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageFormat()
WandExport char * MagickGetImageFormat (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageFuzz()
WandExport double MagickGetImageFuzz (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageGamma()
WandExport double MagickGetImageGamma (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageGravity()
WandExport GravityType MagickGetImageGravity (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageGreenPrimary()
WandExport MagickBooleanType MagickGetImageGreenPrimary (MagickWand * wand, double * x, double * y)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageHeight()
WandExport size_t MagickGetImageHeight (MagickWand * wand)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageHistogram()
WandExport PixelWand ** MagickGetImageHistogram (MagickWand * wand, size_t * number_colors)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, NewPixelWands(), PixelSetColorCount(), PixelSetIndex(), PixelSetQuantumColor(), _MagickWand::signature, and WandSignature.
MagickGetImageInterlaceScheme()
WandExport InterlaceType MagickGetImageInterlaceScheme (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageInterpolateMethod()
WandExport InterpolatePixelMethod MagickGetImageInterpolateMethod (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageIterations()
WandExport size_t MagickGetImageIterations (MagickWand * wand)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageLength()
WandExport MagickBooleanType MagickGetImageLength (MagickWand * wand, MagickSizeType * length)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageMatteColor()
WandExport MagickBooleanType MagickGetImageMatteColor (MagickWand * wand, PixelWand * matte_color)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, PixelSetQuantumColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageOrientation()
WandExport OrientationType MagickGetImageOrientation (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImagePage()
WandExport MagickBooleanType MagickGetImagePage (MagickWand * wand, size_t * width, size_t * height, ssize_t * x, ssize_t * y)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImagePixelColor()
WandExport MagickBooleanType MagickGetImagePixelColor (MagickWand * wand, const ssize_t x, const ssize_t y, PixelWand * color)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelSetBlackQuantum(), PixelSetIndex(), PixelSetQuantumColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageRange()
WandExport MagickBooleanType MagickGetImageRange (MagickWand * wand, double * minima, double * maxima)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageRedPrimary()
WandExport MagickBooleanType MagickGetImageRedPrimary (MagickWand * wand, double * x, double * y)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageRegion()
WandExport MagickWand * MagickGetImageRegion (MagickWand * wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
Referenced by MagickRegionOfInterestImage().
MagickGetImageRenderingIntent()
WandExport RenderingIntent MagickGetImageRenderingIntent (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageResolution()
WandExport MagickBooleanType MagickGetImageResolution (MagickWand * wand, double * x, double * y)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImagesBlob()
WandExport unsigned char * MagickGetImagesBlob (MagickWand * wand, size_t * length)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageScene()
WandExport size_t MagickGetImageScene (MagickWand * wand)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageSignature()
WandExport char * MagickGetImageSignature (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageTicksPerSecond()
WandExport size_t MagickGetImageTicksPerSecond (MagickWand * wand)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageTotalInkDensity()
WandExport double MagickGetImageTotalInkDensity (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageType()
WandExport ImageType MagickGetImageType (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageUnits()
WandExport ResolutionType MagickGetImageUnits (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageVirtualPixelMethod()
WandExport VirtualPixelMethod MagickGetImageVirtualPixelMethod (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageWhitePoint()
WandExport MagickBooleanType MagickGetImageWhitePoint (MagickWand * wand, double * x, double * y)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetImageWidth()
WandExport size_t MagickGetImageWidth (MagickWand * wand)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickGetNumberImages()
WandExport size_t MagickGetNumberImages (MagickWand * wand)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickHaldClutImage()
WandExport MagickBooleanType MagickHaldClutImage (MagickWand * wand, const MagickWand * hald_wand)
References MagickHaldClutImageChannel().
MagickHaldClutImageChannel()
WandExport MagickBooleanType MagickHaldClutImageChannel (MagickWand * wand, const ChannelType channel, const MagickWand * hald_wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickHaldClutImage().
MagickHasNextImage()
WandExport MagickBooleanType MagickHasNextImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickHasPreviousImage()
WandExport MagickBooleanType MagickHasPreviousImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickIdentifyImage()
WandExport char * MagickIdentifyImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
Referenced by MagickDescribeImage().
MagickImplodeImage()
WandExport MagickBooleanType MagickImplodeImage (MagickWand * wand, const double amount)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickImportImagePixels()
WandExport MagickBooleanType MagickImportImagePixels (MagickWand * wand, const ssize_t x, const ssize_t y, const size_t columns, const size_t rows, const char * map, const StorageType storage, const void * pixels)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickSetImagePixels().
MagickInverseFourierTransformImage()
WandExport MagickBooleanType MagickInverseFourierTransformImage (MagickWand * magnitude_wand, MagickWand * phase_wand, const MagickBooleanType magnitude)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickLabelImage()
WandExport MagickBooleanType MagickLabelImage (MagickWand * wand, const char * label)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickLevelImage()
WandExport MagickBooleanType MagickLevelImage (MagickWand * wand, const double black_point, const double gamma, const double white_point)
References MagickLevelImageChannel().
MagickLevelImageChannel()
WandExport MagickBooleanType MagickLevelImageChannel (MagickWand * wand, const ChannelType channel, const double black_point, const double gamma, const double white_point)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickLevelImage().
MagickLevelImageColors()
WandExport MagickBooleanType MagickLevelImageColors (MagickWand * wand, const PixelWand * black_color, const PixelWand * white_color, const MagickBooleanType invert)
References MagickLevelImageColorsChannel().
MagickLevelImageColorsChannel()
WandExport MagickBooleanType MagickLevelImageColorsChannel (MagickWand * wand, const ChannelType channel, const PixelWand * black_color, const PixelWand * white_color, const MagickBooleanType invert)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetMagickColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickLevelImageColors().
MagickLevelizeImage()
WandExport MagickBooleanType MagickLevelizeImage (MagickWand * wand, const double black_point, const double gamma, const double white_point)
References MagickLevelizeImageChannel().
MagickLevelizeImageChannel()
WandExport MagickBooleanType MagickLevelizeImageChannel (MagickWand * wand, const ChannelType channel, const double black_point, const double gamma, const double white_point)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickLevelizeImage().
MagickLinearStretchImage()
WandExport MagickBooleanType MagickLinearStretchImage (MagickWand * wand, const double black_point, const double white_point)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickLiquidRescaleImage()
WandExport MagickBooleanType MagickLiquidRescaleImage (MagickWand * wand, const size_t columns, const size_t rows, const double delta_x, const double rigidity)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickLocalContrastImage()
WandExport MagickBooleanType MagickLocalContrastImage (MagickWand * wand, const double radius, const double strength)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickMagnifyImage()
WandExport MagickBooleanType MagickMagnifyImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickMergeImageLayers()
WandExport MagickWand * MagickMergeImageLayers (MagickWand * wand, const ImageLayerMethod method)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickMinifyImage()
WandExport MagickBooleanType MagickMinifyImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickModulateImage()
WandExport MagickBooleanType MagickModulateImage (MagickWand * wand, const double brightness, const double saturation, const double hue)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickMontageImage()
WandExport MagickWand * MagickMontageImage (MagickWand * wand, const DrawingWand * drawing_wand, const char * tile_geometry, const char * thumbnail_geometry, const MontageMode mode, const char * frame)
References CloneMagickWandFromImages(), _MagickWand::debug, DestroyPixelWand(), DrawGetFillColor(), DrawGetFont(), DrawGetFontSize(), DrawGetStrokeColor(), _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, NewPixelWand(), PixelGetQuantumColor(), _MagickWand::signature, and WandSignature.
MagickMorphImages()
WandExport MagickWand * MagickMorphImages (MagickWand * wand, const size_t number_frames)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickMorphologyImage()
WandExport MagickBooleanType MagickMorphologyImage (MagickWand * wand, const MorphologyMethod method, const ssize_t iterations, const KernelInfo * kernel)
References MagickMorphologyImageChannel().
MagickMorphologyImageChannel()
WandExport MagickBooleanType MagickMorphologyImageChannel (MagickWand * wand, const ChannelType channel, const MorphologyMethod method, const ssize_t iterations, const KernelInfo * kernel)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickMorphologyImage().
MagickMotionBlurImage()
WandExport MagickBooleanType MagickMotionBlurImage (MagickWand * wand, const double radius, const double sigma, const double angle)
References MagickMotionBlurImageChannel().
MagickMotionBlurImageChannel()
WandExport MagickBooleanType MagickMotionBlurImageChannel (MagickWand * wand, const ChannelType channel, const double radius, const double sigma, const double angle)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickMotionBlurImage().
MagickNegateImage()
WandExport MagickBooleanType MagickNegateImage (MagickWand * wand, const MagickBooleanType gray)
References MagickNegateImageChannel().
MagickNegateImageChannel()
WandExport MagickBooleanType MagickNegateImageChannel (MagickWand * wand, const ChannelType channel, const MagickBooleanType gray)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickNegateImage().
MagickNewImage()
WandExport MagickBooleanType MagickNewImage (MagickWand * wand, const size_t width, const size_t height, const PixelWand * background)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, InsertImageInWand(), _MagickWand::name, PixelGetMagickColor(), _MagickWand::signature, and WandSignature.
MagickNextImage()
WandExport MagickBooleanType MagickNextImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickNormalizeImage()
WandExport MagickBooleanType MagickNormalizeImage (MagickWand * wand)
References MagickNormalizeImageChannel().
MagickNormalizeImageChannel()
WandExport MagickBooleanType MagickNormalizeImageChannel (MagickWand * wand, const ChannelType channel)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickNormalizeImage().
MagickOilPaintImage()
WandExport MagickBooleanType MagickOilPaintImage (MagickWand * wand, const double radius)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickOpaquePaintImage()
WandExport MagickBooleanType MagickOpaquePaintImage (MagickWand * wand, const PixelWand * target, const PixelWand * fill, const double fuzz, const MagickBooleanType invert)
References MagickOpaquePaintImageChannel().
MagickOpaquePaintImageChannel()
WandExport MagickBooleanType MagickOpaquePaintImageChannel (MagickWand * wand, const ChannelType channel, const PixelWand * target, const PixelWand * fill, const double fuzz, const MagickBooleanType invert)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetMagickColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickOpaquePaintImage(), and MagickPaintOpaqueImageChannel().
MagickOptimizeImageLayers()
WandExport MagickWand * MagickOptimizeImageLayers (MagickWand * wand)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickOptimizeImageTransparency()
WandExport MagickBooleanType MagickOptimizeImageTransparency (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickOrderedPosterizeImage()
WandExport MagickBooleanType MagickOrderedPosterizeImage (MagickWand * wand, const char * threshold_map)
References MagickOrderedPosterizeImageChannel().
MagickOrderedPosterizeImageChannel()
WandExport MagickBooleanType MagickOrderedPosterizeImageChannel (MagickWand * wand, const ChannelType channel, const char * threshold_map)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickOrderedPosterizeImage().
MagickPingImage()
WandExport MagickBooleanType MagickPingImage (MagickWand * wand, const char * filename)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, InsertImageInWand(), MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickPingImageBlob()
WandExport MagickBooleanType MagickPingImageBlob (MagickWand * wand, const void * blob, const size_t length)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, InsertImageInWand(), _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickPingImageFile()
WandExport MagickBooleanType MagickPingImageFile (MagickWand * wand, FILE * file)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, InsertImageInWand(), _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickPolaroidImage()
WandExport MagickBooleanType MagickPolaroidImage (MagickWand * wand, const DrawingWand * drawing_wand, const double angle)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PeekDrawingWand(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickPosterizeImage()
WandExport MagickBooleanType MagickPosterizeImage (MagickWand * wand, const size_t levels, const MagickBooleanType dither)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickPreviewImages()
WandExport MagickWand * MagickPreviewImages (MagickWand * wand, const PreviewType preview)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickPreviousImage()
WandExport MagickBooleanType MagickPreviousImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::image_pending, _MagickWand::images, _MagickWand::insert_before, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickQuantizeImage()
WandExport MagickBooleanType MagickQuantizeImage (MagickWand * wand, const size_t number_colors, const ColorspaceType colorspace, const size_t treedepth, const MagickBooleanType dither, const MagickBooleanType measure_error)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickQuantizeImages()
WandExport MagickBooleanType MagickQuantizeImages (MagickWand * wand, const size_t number_colors, const ColorspaceType colorspace, const size_t treedepth, const MagickBooleanType dither, const MagickBooleanType measure_error)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickRaiseImage()
WandExport MagickBooleanType MagickRaiseImage (MagickWand * wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y, const MagickBooleanType raise)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickRandomThresholdImage()
WandExport MagickBooleanType MagickRandomThresholdImage (MagickWand * wand, const double low, const double high)
References MagickRandomThresholdImageChannel().
MagickRandomThresholdImageChannel()
WandExport MagickBooleanType MagickRandomThresholdImageChannel (MagickWand * wand, const ChannelType channel, const double low, const double high)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickRandomThresholdImage().
MagickReadImage()
WandExport MagickBooleanType MagickReadImage (MagickWand * wand, const char * filename)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, InsertImageInWand(), MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickReadImageBlob()
WandExport MagickBooleanType MagickReadImageBlob (MagickWand * wand, const void * blob, const size_t length)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, InsertImageInWand(), _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickReadImageFile()
WandExport MagickBooleanType MagickReadImageFile (MagickWand * wand, FILE * file)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, InsertImageInWand(), _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickRemapImage()
WandExport MagickBooleanType MagickRemapImage (MagickWand * wand, const MagickWand * remap_wand, const DitherMethod method)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickRemoveImage()
WandExport MagickBooleanType MagickRemoveImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickResampleImage()
WandExport MagickBooleanType MagickResampleImage (MagickWand * wand, const double x_resolution, const double y_resolution, const FilterTypes filter, const double blur)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickResetImagePage()
WandExport MagickBooleanType MagickResetImagePage (MagickWand * wand, const char * page)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickResizeImage()
WandExport MagickBooleanType MagickResizeImage (MagickWand * wand, const size_t columns, const size_t rows, const FilterTypes filter, const double blur)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickRollImage()
WandExport MagickBooleanType MagickRollImage (MagickWand * wand, const ssize_t x, const ssize_t y)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickRotateImage()
WandExport MagickBooleanType MagickRotateImage (MagickWand * wand, const PixelWand * background, const double degrees)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetQuantumColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickRotationalBlurImage()
WandExport MagickBooleanType MagickRotationalBlurImage (MagickWand * wand, const double angle)
References MagickRotationalBlurImageChannel().
Referenced by MagickRadialBlurImage().
MagickRotationalBlurImageChannel()
WandExport MagickBooleanType MagickRotationalBlurImageChannel (MagickWand * wand, const ChannelType channel, const double angle)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickRadialBlurImageChannel(), and MagickRotationalBlurImage().
MagickSampleImage()
WandExport MagickBooleanType MagickSampleImage (MagickWand * wand, const size_t columns, const size_t rows)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickScaleImage()
WandExport MagickBooleanType MagickScaleImage (MagickWand * wand, const size_t columns, const size_t rows)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSegmentImage()
MagickExport MagickBooleanType MagickSegmentImage (MagickWand * wand, const ColorspaceType colorspace, const MagickBooleanType verbose, const double cluster_threshold, const double smooth_threshold)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSelectiveBlurImage()
WandExport MagickBooleanType MagickSelectiveBlurImage (MagickWand * wand, const double radius, const double sigma, const double threshold)
References MagickSelectiveBlurImageChannel().
MagickSelectiveBlurImageChannel()
WandExport MagickBooleanType MagickSelectiveBlurImageChannel (MagickWand * wand, const ChannelType channel, const double radius, const double sigma, const double threshold)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickSelectiveBlurImage().
MagickSeparateImageChannel()
WandExport MagickBooleanType MagickSeparateImageChannel (MagickWand * wand, const ChannelType channel)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSepiaToneImage()
WandExport MagickBooleanType MagickSepiaToneImage (MagickWand * wand, const double threshold)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImage()
WandExport MagickBooleanType MagickSetImage (MagickWand * wand, const MagickWand * set_wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageAlphaChannel()
WandExport MagickBooleanType MagickSetImageAlphaChannel (MagickWand * wand, const AlphaChannelType alpha_type)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageBackgroundColor()
WandExport MagickBooleanType MagickSetImageBackgroundColor (MagickWand * wand, const PixelWand * background)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, PixelGetQuantumColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageBias()
WandExport MagickBooleanType MagickSetImageBias (MagickWand * wand, const double bias)
References _MagickWand::debug, _MagickWand::image_info, _MagickWand::images, MaxTextExtent, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageBluePrimary()
WandExport MagickBooleanType MagickSetImageBluePrimary (MagickWand * wand, const double x, const double y)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageBorderColor()
WandExport MagickBooleanType MagickSetImageBorderColor (MagickWand * wand, const PixelWand * border)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, PixelGetQuantumColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageChannelDepth()
WandExport MagickBooleanType MagickSetImageChannelDepth (MagickWand * wand, const ChannelType channel, const size_t depth)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageClipMask()
WandExport MagickBooleanType MagickSetImageClipMask (MagickWand * wand, const MagickWand * clip_mask)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageColor()
WandExport MagickBooleanType MagickSetImageColor (MagickWand * wand, const PixelWand * color)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetMagickColor(), _MagickWand::signature, and WandSignature.
MagickSetImageColormapColor()
WandExport MagickBooleanType MagickSetImageColormapColor (MagickWand * wand, const size_t index, const PixelWand * color)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, PixelGetQuantumColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageColorspace()
WandExport MagickBooleanType MagickSetImageColorspace (MagickWand * wand, const ColorspaceType colorspace)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageCompose()
WandExport MagickBooleanType MagickSetImageCompose (MagickWand * wand, const CompositeOperator compose)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageCompression()
WandExport MagickBooleanType MagickSetImageCompression (MagickWand * wand, const CompressionType compression)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageCompressionQuality()
WandExport MagickBooleanType MagickSetImageCompressionQuality (MagickWand * wand, const size_t quality)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageDelay()
WandExport MagickBooleanType MagickSetImageDelay (MagickWand * wand, const size_t delay)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageDepth()
WandExport MagickBooleanType MagickSetImageDepth (MagickWand * wand, const size_t depth)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageDispose()
WandExport MagickBooleanType MagickSetImageDispose (MagickWand * wand, const DisposeType dispose)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageEndian()
WandExport MagickBooleanType MagickSetImageEndian (MagickWand * wand, const EndianType endian)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageExtent()
WandExport MagickBooleanType MagickSetImageExtent (MagickWand * wand, const size_t columns, const size_t rows)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageFilename()
WandExport MagickBooleanType MagickSetImageFilename (MagickWand * wand, const char * filename)
References _MagickWand::debug, _MagickWand::images, MaxTextExtent, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageFormat()
WandExport MagickBooleanType MagickSetImageFormat (MagickWand * wand, const char * format)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageFuzz()
WandExport MagickBooleanType MagickSetImageFuzz (MagickWand * wand, const double fuzz)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageGamma()
WandExport MagickBooleanType MagickSetImageGamma (MagickWand * wand, const double gamma)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageGravity()
WandExport MagickBooleanType MagickSetImageGravity (MagickWand * wand, const GravityType gravity)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageGreenPrimary()
WandExport MagickBooleanType MagickSetImageGreenPrimary (MagickWand * wand, const double x, const double y)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageInterlaceScheme()
WandExport MagickBooleanType MagickSetImageInterlaceScheme (MagickWand * wand, const InterlaceType interlace)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageInterpolateMethod()
WandExport MagickBooleanType MagickSetImageInterpolateMethod (MagickWand * wand, const InterpolatePixelMethod method)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageIterations()
WandExport MagickBooleanType MagickSetImageIterations (MagickWand * wand, const size_t iterations)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageMatte()
WandExport MagickBooleanType MagickSetImageMatte (MagickWand * wand, const MagickBooleanType matte)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageMatteColor()
WandExport MagickBooleanType MagickSetImageMatteColor (MagickWand * wand, const PixelWand * matte)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, PixelGetQuantumColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageOpacity()
WandExport MagickBooleanType MagickSetImageOpacity (MagickWand * wand, const double alpha)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageOrientation()
WandExport MagickBooleanType MagickSetImageOrientation (MagickWand * wand, const OrientationType orientation)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImagePage()
WandExport MagickBooleanType MagickSetImagePage (MagickWand * wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImagePixelColor()
WandExport MagickBooleanType MagickSetImagePixelColor (MagickWand * wand, const ssize_t x, const ssize_t y, const PixelWand * color)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetBlackQuantum(), PixelGetIndex(), PixelGetQuantumColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageProgressMonitor()
WandExport MagickProgressMonitor MagickSetImageProgressMonitor (MagickWand * wand, const MagickProgressMonitor progress_monitor, void * client_data)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickSetImageRedPrimary()
WandExport MagickBooleanType MagickSetImageRedPrimary (MagickWand * wand, const double x, const double y)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageRenderingIntent()
WandExport MagickBooleanType MagickSetImageRenderingIntent (MagickWand * wand, const RenderingIntent rendering_intent)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageResolution()
WandExport MagickBooleanType MagickSetImageResolution (MagickWand * wand, const double x_resolution, const double y_resolution)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageScene()
WandExport MagickBooleanType MagickSetImageScene (MagickWand * wand, const size_t scene)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageTicksPerSecond()
WandExport MagickBooleanType MagickSetImageTicksPerSecond (MagickWand * wand, const ssize_t ticks_per_second)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageType()
WandExport MagickBooleanType MagickSetImageType (MagickWand * wand, const ImageType image_type)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageUnits()
WandExport MagickBooleanType MagickSetImageUnits (MagickWand * wand, const ResolutionType units)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSetImageVirtualPixelMethod()
WandExport VirtualPixelMethod MagickSetImageVirtualPixelMethod (MagickWand * wand, const VirtualPixelMethod method)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickSetImageWhitePoint()
WandExport MagickBooleanType MagickSetImageWhitePoint (MagickWand * wand, const double x, const double y)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickShadeImage()
WandExport MagickBooleanType MagickShadeImage (MagickWand * wand, const MagickBooleanType gray, const double asimuth, const double elevation)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickShadowImage()
WandExport MagickBooleanType MagickShadowImage (MagickWand * wand, const double opacity, const double sigma, const ssize_t x, const ssize_t y)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSharpenImage()
WandExport MagickBooleanType MagickSharpenImage (MagickWand * wand, const double radius, const double sigma)
References MagickSharpenImageChannel().
MagickSharpenImageChannel()
WandExport MagickBooleanType MagickSharpenImageChannel (MagickWand * wand, const ChannelType channel, const double radius, const double sigma)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickSharpenImage().
MagickShaveImage()
WandExport MagickBooleanType MagickShaveImage (MagickWand * wand, const size_t columns, const size_t rows)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickShearImage()
WandExport MagickBooleanType MagickShearImage (MagickWand * wand, const PixelWand * background, const double x_shear, const double y_shear)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetQuantumColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSigmoidalContrastImage()
WandExport MagickBooleanType MagickSigmoidalContrastImage (MagickWand * wand, const MagickBooleanType sharpen, const double alpha, const double beta)
References MagickSigmoidalContrastImageChannel().
MagickSigmoidalContrastImageChannel()
WandExport MagickBooleanType MagickSigmoidalContrastImageChannel (MagickWand * wand, const ChannelType channel, const MagickBooleanType sharpen, const double alpha, const double beta)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickSigmoidalContrastImage().
MagickSimilarityImage()
WandExport MagickWand * MagickSimilarityImage (MagickWand * wand, const MagickWand * reference, RectangleInfo * offset, double * similarity)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickSketchImage()
WandExport MagickBooleanType MagickSketchImage (MagickWand * wand, const double radius, const double sigma, const double angle)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSmushImages()
WandExport MagickWand * MagickSmushImages (MagickWand * wand, const MagickBooleanType stack, const ssize_t offset)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickSolarizeImage()
WandExport MagickBooleanType MagickSolarizeImage (MagickWand * wand, const double threshold)
References MagickSolarizeImageChannel().
MagickSolarizeImageChannel()
WandExport MagickBooleanType MagickSolarizeImageChannel (MagickWand * wand, const ChannelType channel, const double threshold)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickSolarizeImage().
MagickSparseColorImage()
WandExport MagickBooleanType MagickSparseColorImage (MagickWand * wand, const ChannelType channel, const SparseColorMethod method, const size_t number_arguments, const double * arguments)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSpliceImage()
WandExport MagickBooleanType MagickSpliceImage (MagickWand * wand, const size_t width, const size_t height, const ssize_t x, const ssize_t y)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSpreadImage()
WandExport MagickBooleanType MagickSpreadImage (MagickWand * wand, const double radius)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickStatisticImage()
WandExport MagickBooleanType MagickStatisticImage (MagickWand * wand, const StatisticType type, const size_t width, const size_t height)
References MagickStatisticImageChannel().
MagickStatisticImageChannel()
WandExport MagickBooleanType MagickStatisticImageChannel (MagickWand * wand, const ChannelType channel, const StatisticType type, const size_t width, const size_t height)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickStatisticImage().
MagickSteganoImage()
WandExport MagickWand * MagickSteganoImage (MagickWand * wand, const MagickWand * watermark_wand, const ssize_t offset)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickStereoImage()
WandExport MagickWand * MagickStereoImage (MagickWand * wand, const MagickWand * offset_wand)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickStripImage()
WandExport MagickBooleanType MagickStripImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickSwirlImage()
WandExport MagickBooleanType MagickSwirlImage (MagickWand * wand, const double degrees)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickTextureImage()
WandExport MagickWand * MagickTextureImage (MagickWand * wand, const MagickWand * texture_wand)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickThresholdImage()
WandExport MagickBooleanType MagickThresholdImage (MagickWand * wand, const double threshold)
References MagickThresholdImageChannel().
MagickThresholdImageChannel()
WandExport MagickBooleanType MagickThresholdImageChannel (MagickWand * wand, const ChannelType channel, const double threshold)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickThresholdImage().
MagickThumbnailImage()
WandExport MagickBooleanType MagickThumbnailImage (MagickWand * wand, const size_t columns, const size_t rows)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickTintImage()
WandExport MagickBooleanType MagickTintImage (MagickWand * wand, const PixelWand * tint, const PixelWand * opacity)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, PixelGetBlueQuantum(), PixelGetGreenQuantum(), PixelGetOpacityQuantum(), PixelGetQuantumColor(), PixelGetRedQuantum(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickTransformImage()
WandExport MagickWand * MagickTransformImage (MagickWand * wand, const char * crop, const char * geometry)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickTransformImageColorspace()
WandExport MagickBooleanType MagickTransformImageColorspace (MagickWand * wand, const ColorspaceType colorspace)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickTransparentPaintImage()
WandExport MagickBooleanType MagickTransparentPaintImage (MagickWand * wand, const PixelWand * target, const double alpha, const double fuzz, const MagickBooleanType invert)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, PixelGetMagickColor(), _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickPaintTransparentImage().
MagickTransposeImage()
WandExport MagickBooleanType MagickTransposeImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickTransverseImage()
WandExport MagickBooleanType MagickTransverseImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickTrimImage()
WandExport MagickBooleanType MagickTrimImage (MagickWand * wand, const double fuzz)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickUniqueImageColors()
WandExport MagickBooleanType MagickUniqueImageColors (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickUnsharpMaskImage()
WandExport MagickBooleanType MagickUnsharpMaskImage (MagickWand * wand, const double radius, const double sigma, const double amount, const double threshold)
References MagickUnsharpMaskImageChannel().
MagickUnsharpMaskImageChannel()
WandExport MagickBooleanType MagickUnsharpMaskImageChannel (MagickWand * wand, const ChannelType channel, const double radius, const double sigma, const double amount, const double threshold)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
Referenced by MagickUnsharpMaskImage().
MagickVignetteImage()
WandExport MagickBooleanType MagickVignetteImage (MagickWand * wand, const double black_point, const double white_point, const ssize_t x, const ssize_t y)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickWaveImage()
WandExport MagickBooleanType MagickWaveImage (MagickWand * wand, const double amplitude, const double wave_length)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickWhiteThresholdImage()
WandExport MagickBooleanType MagickWhiteThresholdImage (MagickWand * wand, const PixelWand * threshold)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, PixelGetBlueQuantum(), PixelGetGreenQuantum(), PixelGetOpacityQuantum(), PixelGetRedQuantum(), _MagickWand::signature, ThrowWandException, and WandSignature.
MagickWriteImage()
WandExport MagickBooleanType MagickWriteImage (MagickWand * wand, const char * filename)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, MaxTextExtent, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickWriteImageFile()
WandExport MagickBooleanType MagickWriteImageFile (MagickWand * wand, FILE * file)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickWriteImages()
WandExport MagickBooleanType MagickWriteImages (MagickWand * wand, const char * filename, const MagickBooleanType adjoin)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.
MagickWriteImagesFile()
WandExport MagickBooleanType MagickWriteImagesFile (MagickWand * wand, FILE * file)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.