MagickWand: magick-image.h File Reference
magick-image.h File Reference
Functions
WandExport ChannelFeatures * MagickGetImageChannelFeatures (MagickWand *, const size_t)
WandExport ChannelStatistics * MagickGetImageChannelStatistics (MagickWand *)
WandExport char * MagickGetImageFilename (MagickWand *)
WandExport char * MagickGetImageFormat (MagickWand *)
WandExport char * MagickGetImageSignature (MagickWand *)
WandExport char * MagickIdentifyImage (MagickWand *)
WandExport ColorspaceType MagickGetImageColorspace (MagickWand *)
WandExport CompositeOperator MagickGetImageCompose (MagickWand *)
WandExport CompressionType MagickGetImageCompression (MagickWand *)
WandExport DisposeType MagickGetImageDispose (MagickWand *)
WandExport double * MagickGetImageChannelDistortions (MagickWand *, const MagickWand *, const MetricType)
WandExport double MagickGetImageFuzz (MagickWand *)
WandExport double MagickGetImageGamma (MagickWand *)
WandExport double MagickGetImageTotalInkDensity (MagickWand *)
WandExport EndianType MagickGetImageEndian (MagickWand *)
WandExport GravityType MagickGetImageGravity (MagickWand *)
WandExport Image * MagickDestroyImage (Image *)
WandExport Image * GetImageFromMagickWand (const MagickWand *)
WandExport ImageType MagickGetImageType (MagickWand *)
WandExport InterlaceType MagickGetImageInterlaceScheme (MagickWand *)
WandExport InterpolatePixelMethod MagickGetImageInterpolateMethod (MagickWand *)
WandExport MagickBooleanType MagickAdaptiveBlurImage (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickAdaptiveBlurImageChannel (MagickWand *, const ChannelType, const double, const double)
WandExport MagickBooleanType MagickAdaptiveResizeImage (MagickWand *, const size_t, const size_t)
WandExport MagickBooleanType MagickAdaptiveSharpenImage (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickAdaptiveSharpenImageChannel (MagickWand *, const ChannelType, const double, const double)
WandExport MagickBooleanType MagickAdaptiveThresholdImage (MagickWand *, const size_t, const size_t, const ssize_t)
WandExport MagickBooleanType MagickAddImage (MagickWand *, const MagickWand *)
WandExport MagickBooleanType MagickAddNoiseImage (MagickWand *, const NoiseType)
WandExport MagickBooleanType MagickAddNoiseImageChannel (MagickWand *, const ChannelType, const NoiseType)
WandExport MagickBooleanType MagickAffineTransformImage (MagickWand *, const DrawingWand *)
WandExport MagickBooleanType MagickAnnotateImage (MagickWand *, const DrawingWand *, const double, const double, const double, const char *)
WandExport MagickBooleanType MagickAnimateImages (MagickWand *, const char *)
WandExport MagickBooleanType MagickAutoGammaImage (MagickWand *)
WandExport MagickBooleanType MagickAutoGammaImageChannel (MagickWand *, const ChannelType)
WandExport MagickBooleanType MagickAutoLevelImage (MagickWand *)
WandExport MagickBooleanType MagickAutoLevelImageChannel (MagickWand *, const ChannelType)
WandExport MagickBooleanType MagickAutoOrientImage (MagickWand *)
WandExport MagickBooleanType MagickBlackThresholdImage (MagickWand *, const PixelWand *)
WandExport MagickBooleanType MagickBlueShiftImage (MagickWand *, const double)
WandExport MagickBooleanType MagickBlurImage (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickBlurImageChannel (MagickWand *, const ChannelType, const double, const double)
WandExport MagickBooleanType MagickBorderImage (MagickWand *, const PixelWand *, const size_t, const size_t)
WandExport MagickBooleanType MagickBrightnessContrastImage (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickBrightnessContrastImageChannel (MagickWand *, const ChannelType, const double, const double)
WandExport MagickBooleanType MagickCharcoalImage (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickChopImage (MagickWand *, const size_t, const size_t, const ssize_t, const ssize_t)
WandExport MagickBooleanType MagickClampImage (MagickWand *)
WandExport MagickBooleanType MagickClampImageChannel (MagickWand *, const ChannelType)
WandExport MagickBooleanType MagickClipImage (MagickWand *)
WandExport MagickBooleanType MagickClipImagePath (MagickWand *, const char *, const MagickBooleanType)
WandExport MagickBooleanType MagickClutImage (MagickWand *, const MagickWand *)
WandExport MagickBooleanType MagickClutImageChannel (MagickWand *, const ChannelType, const MagickWand *)
WandExport MagickBooleanType MagickColorDecisionListImage (MagickWand *, const char *)
WandExport MagickBooleanType MagickColorizeImage (MagickWand *, const PixelWand *, const PixelWand *)
WandExport MagickBooleanType MagickColorMatrixImage (MagickWand *, const KernelInfo *)
WandExport MagickBooleanType MagickCommentImage (MagickWand *, const char *)
WandExport MagickBooleanType MagickCompositeImage (MagickWand *, const MagickWand *, const CompositeOperator, const ssize_t, const ssize_t)
WandExport MagickBooleanType MagickCompositeImageChannel (MagickWand *, const ChannelType, const MagickWand *, const CompositeOperator, const ssize_t, const ssize_t)
WandExport MagickBooleanType MagickCompositeImageGravity (MagickWand *, const MagickWand *, const CompositeOperator, const GravityType)
WandExport MagickBooleanType MagickCompositeLayers (MagickWand *, const MagickWand *, const CompositeOperator, const ssize_t, const ssize_t)
WandExport MagickBooleanType MagickConstituteImage (MagickWand *, const size_t, const size_t, const char *, const StorageType, const void *)
WandExport MagickBooleanType MagickContrastImage (MagickWand *, const MagickBooleanType)
WandExport MagickBooleanType MagickContrastStretchImage (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickContrastStretchImageChannel (MagickWand *, const ChannelType, const double, const double)
WandExport MagickBooleanType MagickConvolveImage (MagickWand *, const size_t, const double *)
WandExport MagickBooleanType MagickConvolveImageChannel (MagickWand *, const ChannelType, const size_t, const double *)
WandExport MagickBooleanType MagickCropImage (MagickWand *, const size_t, const size_t, const ssize_t, const ssize_t)
WandExport MagickBooleanType MagickCycleColormapImage (MagickWand *, const ssize_t)
WandExport MagickBooleanType MagickDecipherImage (MagickWand *, const char *)
WandExport MagickBooleanType MagickDeskewImage (MagickWand *, const double)
WandExport MagickBooleanType MagickDespeckleImage (MagickWand *)
WandExport MagickBooleanType MagickDisplayImage (MagickWand *, const char *)
WandExport MagickBooleanType MagickDisplayImages (MagickWand *, const char *)
WandExport MagickBooleanType MagickDistortImage (MagickWand *, const DistortImageMethod, const size_t, const double *, const MagickBooleanType)
WandExport MagickBooleanType MagickDrawImage (MagickWand *, const DrawingWand *)
WandExport MagickBooleanType MagickEdgeImage (MagickWand *, const double)
WandExport MagickBooleanType MagickEmbossImage (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickEncipherImage (MagickWand *, const char *)
WandExport MagickBooleanType MagickEnhanceImage (MagickWand *)
WandExport MagickBooleanType MagickEqualizeImage (MagickWand *)
WandExport MagickBooleanType MagickEqualizeImageChannel (MagickWand *, const ChannelType)
WandExport MagickBooleanType MagickEvaluateImage (MagickWand *, const MagickEvaluateOperator, const double)
WandExport MagickBooleanType MagickEvaluateImageChannel (MagickWand *, const ChannelType, const MagickEvaluateOperator, const double)
WandExport MagickBooleanType MagickExportImagePixels (MagickWand *, const ssize_t, const ssize_t, const size_t, const size_t, const char *, const StorageType, void *)
WandExport MagickBooleanType MagickExtentImage (MagickWand *, const size_t, const size_t, const ssize_t, const ssize_t)
WandExport MagickBooleanType MagickFilterImage (MagickWand *, const KernelInfo *)
WandExport MagickBooleanType MagickFilterImageChannel (MagickWand *, const ChannelType, const KernelInfo *)
WandExport MagickBooleanType MagickFlipImage (MagickWand *)
WandExport MagickBooleanType MagickFloodfillPaintImage (MagickWand *, const ChannelType, const PixelWand *, const double, const PixelWand *, const ssize_t, const ssize_t, const MagickBooleanType)
WandExport MagickBooleanType MagickFlopImage (MagickWand *)
WandExport MagickBooleanType MagickForwardFourierTransformImage (MagickWand *, const MagickBooleanType)
WandExport MagickBooleanType MagickFrameImage (MagickWand *, const PixelWand *, const size_t, const size_t, const ssize_t, const ssize_t)
WandExport MagickBooleanType MagickFunctionImage (MagickWand *, const MagickFunction, const size_t, const double *)
WandExport MagickBooleanType MagickFunctionImageChannel (MagickWand *, const ChannelType, const MagickFunction, const size_t, const double *)
WandExport MagickBooleanType MagickGammaImage (MagickWand *, const double)
WandExport MagickBooleanType MagickGammaImageChannel (MagickWand *, const ChannelType, const double)
WandExport MagickBooleanType MagickGaussianBlurImage (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickGaussianBlurImageChannel (MagickWand *, const ChannelType, const double, const double)
WandExport MagickBooleanType MagickGetImageAlphaChannel (MagickWand *)
WandExport MagickBooleanType MagickGetImageBackgroundColor (MagickWand *, PixelWand *)
WandExport MagickBooleanType MagickGetImageBluePrimary (MagickWand *, double *, double *)
WandExport MagickBooleanType MagickGetImageBorderColor (MagickWand *, PixelWand *)
WandExport MagickBooleanType MagickGetImageChannelDistortion (MagickWand *, const MagickWand *, const ChannelType, const MetricType, double *)
WandExport MagickBooleanType MagickGetImageChannelKurtosis (MagickWand *, const ChannelType, double *, double *)
WandExport MagickBooleanType MagickGetImageChannelMean (MagickWand *, const ChannelType, double *, double *)
WandExport MagickBooleanType MagickGetImageChannelRange (MagickWand *, const ChannelType, double *, double *)
WandExport MagickBooleanType MagickGetImageColormapColor (MagickWand *, const size_t, PixelWand *)
WandExport MagickBooleanType MagickGetImageDistortion (MagickWand *, const MagickWand *, const MetricType, double *)
WandExport MagickBooleanType MagickGetImageGreenPrimary (MagickWand *, double *, double *)
WandExport MagickBooleanType MagickGetImageMatteColor (MagickWand *, PixelWand *)
WandExport MagickBooleanType MagickGetImageLength (MagickWand *, MagickSizeType *)
WandExport MagickBooleanType MagickGetImagePage (MagickWand *, size_t *, size_t *, ssize_t *, ssize_t *)
WandExport MagickBooleanType MagickGetImagePixelColor (MagickWand *, const ssize_t, const ssize_t, PixelWand *)
WandExport MagickBooleanType MagickGetImageRange (MagickWand *, double *, double *)
WandExport MagickBooleanType MagickGetImageRedPrimary (MagickWand *, double *, double *)
WandExport MagickBooleanType MagickGetImageResolution (MagickWand *, double *, double *)
WandExport MagickBooleanType MagickGetImageWhitePoint (MagickWand *, double *, double *)
WandExport MagickBooleanType MagickHaldClutImage (MagickWand *, const MagickWand *)
WandExport MagickBooleanType MagickHaldClutImageChannel (MagickWand *, const ChannelType, const MagickWand *)
WandExport MagickBooleanType MagickHasNextImage (MagickWand *)
WandExport MagickBooleanType MagickHasPreviousImage (MagickWand *)
WandExport MagickBooleanType MagickImplodeImage (MagickWand *, const double)
WandExport MagickBooleanType MagickImportImagePixels (MagickWand *, const ssize_t, const ssize_t, const size_t, const size_t, const char *, const StorageType, const void *)
WandExport MagickBooleanType MagickInverseFourierTransformImage (MagickWand *, MagickWand *, const MagickBooleanType)
WandExport MagickBooleanType MagickLabelImage (MagickWand *, const char *)
WandExport MagickBooleanType MagickLevelImage (MagickWand *, const double, const double, const double)
WandExport MagickBooleanType MagickLevelImageChannel (MagickWand *, const ChannelType, const double, const double, const double)
WandExport MagickBooleanType MagickLevelImageColors (MagickWand *, const PixelWand *, const PixelWand *, const MagickBooleanType)
WandExport MagickBooleanType MagickLevelImageColorsChannel (MagickWand *, const ChannelType, const PixelWand *, const PixelWand *, const MagickBooleanType)
WandExport MagickBooleanType MagickLevelizeImage (MagickWand *, const double, const double, const double)
WandExport MagickBooleanType MagickLevelizeImageChannel (MagickWand *, const ChannelType, const double, const double, const double)
WandExport MagickBooleanType MagickLinearStretchImage (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickLiquidRescaleImage (MagickWand *, const size_t, const size_t, const double, const double)
WandExport MagickBooleanType MagickLocalContrastImage (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickMagnifyImage (MagickWand *)
WandExport MagickBooleanType MagickMedianFilterImage (MagickWand *, const double)
WandExport MagickBooleanType MagickMinifyImage (MagickWand *)
WandExport MagickBooleanType MagickModeImage (MagickWand *, const double)
WandExport MagickBooleanType MagickModulateImage (MagickWand *, const double, const double, const double)
WandExport MagickBooleanType MagickMorphologyImage (MagickWand *, const MorphologyMethod, const ssize_t, const KernelInfo *)
WandExport MagickBooleanType MagickMorphologyImageChannel (MagickWand *, const ChannelType, const MorphologyMethod, const ssize_t, const KernelInfo *)
WandExport MagickBooleanType MagickMotionBlurImage (MagickWand *, const double, const double, const double)
WandExport MagickBooleanType MagickMotionBlurImageChannel (MagickWand *, const ChannelType, const double, const double, const double)
WandExport MagickBooleanType MagickNegateImage (MagickWand *, const MagickBooleanType)
WandExport MagickBooleanType MagickNegateImageChannel (MagickWand *, const ChannelType, const MagickBooleanType)
WandExport MagickBooleanType MagickNewImage (MagickWand *, const size_t, const size_t, const PixelWand *)
WandExport MagickBooleanType MagickNextImage (MagickWand *)
WandExport MagickBooleanType MagickNormalizeImage (MagickWand *)
WandExport MagickBooleanType MagickNormalizeImageChannel (MagickWand *, const ChannelType)
WandExport MagickBooleanType MagickOilPaintImage (MagickWand *, const double)
WandExport MagickBooleanType MagickOpaquePaintImage (MagickWand *, const PixelWand *, const PixelWand *, const double, const MagickBooleanType)
WandExport MagickBooleanType MagickOpaquePaintImageChannel (MagickWand *, const ChannelType, const PixelWand *, const PixelWand *, const double, const MagickBooleanType)
WandExport MagickBooleanType MagickOrderedPosterizeImage (MagickWand *, const char *)
WandExport MagickBooleanType MagickOrderedPosterizeImageChannel (MagickWand *, const ChannelType, const char *)
WandExport MagickBooleanType MagickOptimizeImageTransparency (MagickWand *)
WandExport MagickBooleanType MagickTransparentPaintImage (MagickWand *, const PixelWand *, const double, const double, const MagickBooleanType invert)
WandExport MagickBooleanType MagickPingImage (MagickWand *, const char *)
WandExport MagickBooleanType MagickPingImageBlob (MagickWand *, const void *, const size_t)
WandExport MagickBooleanType MagickPingImageFile (MagickWand *, FILE *)
WandExport MagickBooleanType MagickPolaroidImage (MagickWand *, const DrawingWand *, const double)
WandExport MagickBooleanType MagickPosterizeImage (MagickWand *, const size_t, const MagickBooleanType)
WandExport MagickBooleanType MagickPreviousImage (MagickWand *)
WandExport MagickBooleanType MagickQuantizeImage (MagickWand *, const size_t, const ColorspaceType, const size_t, const MagickBooleanType, const MagickBooleanType)
WandExport MagickBooleanType MagickQuantizeImages (MagickWand *, const size_t, const ColorspaceType, const size_t, const MagickBooleanType, const MagickBooleanType)
WandExport MagickBooleanType MagickRaiseImage (MagickWand *, const size_t, const size_t, const ssize_t, const ssize_t, const MagickBooleanType)
WandExport MagickBooleanType MagickRandomThresholdImage (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickRandomThresholdImageChannel (MagickWand *, const ChannelType, const double, const double)
WandExport MagickBooleanType MagickReadImage (MagickWand *, const char *)
WandExport MagickBooleanType MagickReadImageBlob (MagickWand *, const void *, const size_t)
WandExport MagickBooleanType MagickReadImageFile (MagickWand *, FILE *)
WandExport MagickBooleanType MagickReduceNoiseImage (MagickWand *, const double)
WandExport MagickBooleanType MagickRemapImage (MagickWand *, const MagickWand *, const DitherMethod)
WandExport MagickBooleanType MagickRemoveImage (MagickWand *)
WandExport MagickBooleanType MagickResampleImage (MagickWand *, const double, const double, const FilterTypes, const double)
WandExport MagickBooleanType MagickResetImagePage (MagickWand *, const char *)
WandExport MagickBooleanType MagickResizeImage (MagickWand *, const size_t, const size_t, const FilterTypes, const double)
WandExport MagickBooleanType MagickRollImage (MagickWand *, const ssize_t, const ssize_t)
WandExport MagickBooleanType MagickRotateImage (MagickWand *, const PixelWand *, const double)
WandExport MagickBooleanType MagickRotationalBlurImage (MagickWand *, const double)
WandExport MagickBooleanType MagickRotationalBlurImageChannel (MagickWand *, const ChannelType, const double)
WandExport MagickBooleanType MagickSampleImage (MagickWand *, const size_t, const size_t)
WandExport MagickBooleanType MagickScaleImage (MagickWand *, const size_t, const size_t)
WandExport MagickBooleanType MagickSegmentImage (MagickWand *, const ColorspaceType, const MagickBooleanType, const double, const double)
WandExport MagickBooleanType MagickSelectiveBlurImage (MagickWand *, const double, const double, const double)
WandExport MagickBooleanType MagickSelectiveBlurImageChannel (MagickWand *, const ChannelType, const double, const double, const double)
WandExport MagickBooleanType MagickSeparateImageChannel (MagickWand *, const ChannelType)
WandExport MagickBooleanType MagickSepiaToneImage (MagickWand *, const double)
WandExport MagickBooleanType MagickSetImage (MagickWand *, const MagickWand *)
WandExport MagickBooleanType MagickSetImageAlphaChannel (MagickWand *, const AlphaChannelType)
WandExport MagickBooleanType MagickSetImageBackgroundColor (MagickWand *, const PixelWand *)
WandExport MagickBooleanType MagickSetImageBias (MagickWand *, const double)
WandExport MagickBooleanType MagickSetImageBluePrimary (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickSetImageBorderColor (MagickWand *, const PixelWand *)
WandExport MagickBooleanType MagickSetImageChannelDepth (MagickWand *, const ChannelType, const size_t)
WandExport MagickBooleanType MagickSetImageClipMask (MagickWand *, const MagickWand *)
WandExport MagickBooleanType MagickSetImageColor (MagickWand *, const PixelWand *)
WandExport MagickBooleanType MagickSetImageColormapColor (MagickWand *, const size_t, const PixelWand *)
WandExport MagickBooleanType MagickSetImageColorspace (MagickWand *, const ColorspaceType)
WandExport MagickBooleanType MagickSetImageCompose (MagickWand *, const CompositeOperator)
WandExport MagickBooleanType MagickSetImageCompression (MagickWand *, const CompressionType)
WandExport MagickBooleanType MagickSetImageDelay (MagickWand *, const size_t)
WandExport MagickBooleanType MagickSetImageDepth (MagickWand *, const size_t)
WandExport MagickBooleanType MagickSetImageDispose (MagickWand *, const DisposeType)
WandExport MagickBooleanType MagickSetImageCompressionQuality (MagickWand *, const size_t)
WandExport MagickBooleanType MagickSetImageEndian (MagickWand *, const EndianType)
WandExport MagickBooleanType MagickSetImageExtent (MagickWand *, const size_t, const size_t)
WandExport MagickBooleanType MagickSetImageFilename (MagickWand *, const char *)
WandExport MagickBooleanType MagickSetImageFormat (MagickWand *, const char *)
WandExport MagickBooleanType MagickSetImageFuzz (MagickWand *, const double)
WandExport MagickBooleanType MagickSetImageGamma (MagickWand *, const double)
WandExport MagickBooleanType MagickSetImageGravity (MagickWand *, const GravityType)
WandExport MagickBooleanType MagickSetImageGreenPrimary (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickSetImageInterlaceScheme (MagickWand *, const InterlaceType)
WandExport MagickBooleanType MagickSetImageInterpolateMethod (MagickWand *, const InterpolatePixelMethod)
WandExport MagickBooleanType MagickSetImageIterations (MagickWand *, const size_t)
WandExport MagickBooleanType MagickSetImageMatte (MagickWand *, const MagickBooleanType)
WandExport MagickBooleanType MagickSetImageMatteColor (MagickWand *, const PixelWand *)
WandExport MagickBooleanType MagickSetImageOpacity (MagickWand *, const double)
WandExport MagickBooleanType MagickSetImageOrientation (MagickWand *, const OrientationType)
WandExport MagickBooleanType MagickSetImagePage (MagickWand *, const size_t, const size_t, const ssize_t, const ssize_t)
WandExport MagickBooleanType MagickSetImageRedPrimary (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickSetImageRenderingIntent (MagickWand *, const RenderingIntent)
WandExport MagickBooleanType MagickSetImageResolution (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickSetImageScene (MagickWand *, const size_t)
WandExport MagickBooleanType MagickSetImagePixelColor (MagickWand *, const ssize_t, const ssize_t, const PixelWand *)
WandExport MagickBooleanType MagickSetImageTicksPerSecond (MagickWand *, const ssize_t)
WandExport MagickBooleanType MagickSetImageType (MagickWand *, const ImageType)
WandExport MagickBooleanType MagickSetImageUnits (MagickWand *, const ResolutionType)
WandExport MagickBooleanType MagickSetImageWhitePoint (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickShadeImage (MagickWand *, const MagickBooleanType, const double, const double)
WandExport MagickBooleanType MagickShadowImage (MagickWand *, const double, const double, const ssize_t, const ssize_t)
WandExport MagickBooleanType MagickSharpenImage (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickSharpenImageChannel (MagickWand *, const ChannelType, const double, const double)
WandExport MagickBooleanType MagickShaveImage (MagickWand *, const size_t, const size_t)
WandExport MagickBooleanType MagickShearImage (MagickWand *, const PixelWand *, const double, const double)
WandExport MagickBooleanType MagickSigmoidalContrastImage (MagickWand *, const MagickBooleanType, const double, const double)
WandExport MagickBooleanType MagickSigmoidalContrastImageChannel (MagickWand *, const ChannelType, const MagickBooleanType, const double, const double)
WandExport MagickBooleanType MagickSketchImage (MagickWand *, const double, const double, const double)
WandExport MagickBooleanType MagickSolarizeImage (MagickWand *, const double)
WandExport MagickBooleanType MagickSolarizeImageChannel (MagickWand *, const ChannelType, const double)
WandExport MagickBooleanType MagickSparseColorImage (MagickWand *, const ChannelType, const SparseColorMethod, const size_t, const double *)
WandExport MagickBooleanType MagickSpliceImage (MagickWand *, const size_t, const size_t, const ssize_t, const ssize_t)
WandExport MagickBooleanType MagickSpreadImage (MagickWand *, const double)
WandExport MagickBooleanType MagickStatisticImage (MagickWand *, const StatisticType, const size_t, const size_t)
WandExport MagickBooleanType MagickStatisticImageChannel (MagickWand *, const ChannelType, const StatisticType, const size_t, const size_t)
WandExport MagickBooleanType MagickStripImage (MagickWand *)
WandExport MagickBooleanType MagickSwirlImage (MagickWand *, const double)
WandExport MagickBooleanType MagickTintImage (MagickWand *, const PixelWand *, const PixelWand *)
WandExport MagickBooleanType MagickTransformImageColorspace (MagickWand *, const ColorspaceType)
WandExport MagickBooleanType MagickTransposeImage (MagickWand *)
WandExport MagickBooleanType MagickTransverseImage (MagickWand *)
WandExport MagickBooleanType MagickThresholdImage (MagickWand *, const double)
WandExport MagickBooleanType MagickThresholdImageChannel (MagickWand *, const ChannelType, const double)
WandExport MagickBooleanType MagickThumbnailImage (MagickWand *, const size_t, const size_t)
WandExport MagickBooleanType MagickTrimImage (MagickWand *, const double)
WandExport MagickBooleanType MagickUniqueImageColors (MagickWand *)
WandExport MagickBooleanType MagickUnsharpMaskImage (MagickWand *, const double, const double, const double, const double)
WandExport MagickBooleanType MagickUnsharpMaskImageChannel (MagickWand *, const ChannelType, const double, const double, const double, const double)
WandExport MagickBooleanType MagickVignetteImage (MagickWand *, const double, const double, const ssize_t, const ssize_t)
WandExport MagickBooleanType MagickWaveImage (MagickWand *, const double, const double)
WandExport MagickBooleanType MagickWhiteThresholdImage (MagickWand *, const PixelWand *)
WandExport MagickBooleanType MagickWriteImage (MagickWand *, const char *)
WandExport MagickBooleanType MagickWriteImageFile (MagickWand *, FILE *)
WandExport MagickBooleanType MagickWriteImages (MagickWand *, const char *, const MagickBooleanType)
WandExport MagickBooleanType MagickWriteImagesFile (MagickWand *, FILE *)
WandExport MagickProgressMonitor MagickSetImageProgressMonitor (MagickWand *, const MagickProgressMonitor, void *)
WandExport MagickWand * MagickAppendImages (MagickWand *, const MagickBooleanType)
WandExport MagickWand * MagickCoalesceImages (MagickWand *)
WandExport MagickWand * MagickCombineImages (MagickWand *, const ChannelType)
WandExport MagickWand * MagickCompareImageChannels (MagickWand *, const MagickWand *, const ChannelType, const MetricType, double *)
WandExport MagickWand * MagickCompareImages (MagickWand *, const MagickWand *, const MetricType, double *)
WandExport MagickWand * MagickCompareImageLayers (MagickWand *, const ImageLayerMethod)
WandExport MagickWand * MagickDeconstructImages (MagickWand *)
WandExport MagickWand * MagickEvaluateImages (MagickWand *, const MagickEvaluateOperator)
WandExport MagickWand * MagickFxImage (MagickWand *, const char *)
WandExport MagickWand * MagickFxImageChannel (MagickWand *, const ChannelType, const char *)
WandExport MagickWand * MagickGetImage (MagickWand *)
WandExport MagickWand * MagickGetImageClipMask (MagickWand *)
WandExport MagickWand * MagickGetImageRegion (MagickWand *, const size_t, const size_t, const ssize_t, const ssize_t)
WandExport MagickWand * MagickMergeImageLayers (MagickWand *, const ImageLayerMethod)
WandExport MagickWand * MagickMorphImages (MagickWand *, const size_t)
WandExport MagickWand * MagickMontageImage (MagickWand *, const DrawingWand *, const char *, const char *, const MontageMode, const char *)
WandExport MagickWand * MagickOptimizeImageLayers (MagickWand *)
WandExport MagickWand * MagickPreviewImages (MagickWand *wand, const PreviewType)
WandExport MagickWand * MagickSimilarityImage (MagickWand *, const MagickWand *, RectangleInfo *, double *)
WandExport MagickWand * MagickSmushImages (MagickWand *, const MagickBooleanType, const ssize_t)
WandExport MagickWand * MagickSteganoImage (MagickWand *, const MagickWand *, const ssize_t)
WandExport MagickWand * MagickStereoImage (MagickWand *, const MagickWand *)
WandExport MagickWand * MagickTextureImage (MagickWand *, const MagickWand *)
WandExport MagickWand * MagickTransformImage (MagickWand *, const char *, const char *)
WandExport OrientationType MagickGetImageOrientation (MagickWand *)
WandExport PixelWand ** MagickGetImageHistogram (MagickWand *, size_t *)
WandExport RenderingIntent MagickGetImageRenderingIntent (MagickWand *)
WandExport ResolutionType MagickGetImageUnits (MagickWand *)
WandExport size_t MagickGetImageColors (MagickWand *)
WandExport size_t MagickGetImageCompressionQuality (MagickWand *)
WandExport size_t MagickGetImageDelay (MagickWand *)
WandExport size_t MagickGetImageChannelDepth (MagickWand *, const ChannelType)
WandExport size_t MagickGetImageDepth (MagickWand *)
WandExport size_t MagickGetImageHeight (MagickWand *)
WandExport size_t MagickGetImageIterations (MagickWand *)
WandExport size_t MagickGetImageScene (MagickWand *)
WandExport size_t MagickGetImageTicksPerSecond (MagickWand *)
WandExport size_t MagickGetImageWidth (MagickWand *)
WandExport size_t MagickGetNumberImages (MagickWand *)
WandExport unsigned char * MagickGetImageBlob (MagickWand *, size_t *)
WandExport unsigned char * MagickGetImagesBlob (MagickWand *, size_t *)
WandExport VirtualPixelMethod MagickGetImageVirtualPixelMethod (MagickWand *)
WandExport VirtualPixelMethod MagickSetImageVirtualPixelMethod (MagickWand *, const VirtualPixelMethod)
Function Documentation
GetImageFromMagickWand()
WandExport Image * GetImageFromMagickWand (const MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
Referenced by DrawComposite(), NewPixelIterator(), and NewPixelRegionIterator().
MagickAdaptiveBlurImage()
WandExport MagickBooleanType MagickAdaptiveBlurImage (MagickWand * , const double , const double)
MagickAdaptiveBlurImageChannel()
WandExport MagickBooleanType MagickAdaptiveBlurImageChannel (MagickWand * , const ChannelType, const double , const double)
MagickAdaptiveResizeImage()
WandExport MagickBooleanType MagickAdaptiveResizeImage (MagickWand * , const size_t, const size_t)
MagickAdaptiveSharpenImage()
WandExport MagickBooleanType MagickAdaptiveSharpenImage (MagickWand * , const double , const double)
MagickAdaptiveSharpenImageChannel()
WandExport MagickBooleanType MagickAdaptiveSharpenImageChannel (MagickWand * , const ChannelType, const double , const double)
MagickAdaptiveThresholdImage()
WandExport MagickBooleanType MagickAdaptiveThresholdImage (MagickWand * , const size_t, const size_t, const ssize_t)
MagickAddImage()
WandExport MagickBooleanType MagickAddImage (MagickWand * , const MagickWand *)
MagickAddNoiseImage()
WandExport MagickBooleanType MagickAddNoiseImage (MagickWand * , const NoiseType)
MagickAddNoiseImageChannel()
WandExport MagickBooleanType MagickAddNoiseImageChannel (MagickWand * , const ChannelType, const NoiseType)
MagickAffineTransformImage()
WandExport MagickBooleanType MagickAffineTransformImage (MagickWand * , const DrawingWand *)
MagickAnimateImages()
WandExport MagickBooleanType MagickAnimateImages (MagickWand * , const char *)
MagickAnnotateImage()
WandExport MagickBooleanType MagickAnnotateImage (MagickWand * , const DrawingWand * , const double , const double , const double , const char *)
MagickAppendImages()
WandExport MagickWand * MagickAppendImages (MagickWand * , const MagickBooleanType)
MagickAutoGammaImage()
WandExport MagickBooleanType MagickAutoGammaImage (MagickWand *)
MagickAutoGammaImageChannel()
WandExport MagickBooleanType MagickAutoGammaImageChannel (MagickWand * , const ChannelType)
MagickAutoLevelImage()
WandExport MagickBooleanType MagickAutoLevelImage (MagickWand *)
MagickAutoLevelImageChannel()
WandExport MagickBooleanType MagickAutoLevelImageChannel (MagickWand * , const ChannelType)
MagickAutoOrientImage()
WandExport MagickBooleanType MagickAutoOrientImage (MagickWand *)
MagickBlackThresholdImage()
WandExport MagickBooleanType MagickBlackThresholdImage (MagickWand * , const PixelWand *)
MagickBlueShiftImage()
WandExport MagickBooleanType MagickBlueShiftImage (MagickWand * , const double)
MagickBlurImage()
WandExport MagickBooleanType MagickBlurImage (MagickWand * , const double , const double)
MagickBlurImageChannel()
WandExport MagickBooleanType MagickBlurImageChannel (MagickWand * , const ChannelType, const double , const double)
MagickBorderImage()
WandExport MagickBooleanType MagickBorderImage (MagickWand * , const PixelWand * , const size_t, const size_t)
MagickBrightnessContrastImage()
WandExport MagickBooleanType MagickBrightnessContrastImage (MagickWand * , const double , const double)
MagickBrightnessContrastImageChannel()
WandExport MagickBooleanType MagickBrightnessContrastImageChannel (MagickWand * , const ChannelType, const double , const double)
MagickCharcoalImage()
WandExport MagickBooleanType MagickCharcoalImage (MagickWand * , const double , const double)
MagickChopImage()
WandExport MagickBooleanType MagickChopImage (MagickWand * , const size_t, const size_t, const ssize_t, const ssize_t)
MagickClampImage()
WandExport MagickBooleanType MagickClampImage (MagickWand *)
MagickClampImageChannel()
WandExport MagickBooleanType MagickClampImageChannel (MagickWand * , const ChannelType)
MagickClipImage()
WandExport MagickBooleanType MagickClipImage (MagickWand *)
MagickClipImagePath()
WandExport MagickBooleanType MagickClipImagePath (MagickWand * , const char * , const MagickBooleanType)
MagickClutImage()
WandExport MagickBooleanType MagickClutImage (MagickWand * , const MagickWand *)
MagickClutImageChannel()
WandExport MagickBooleanType MagickClutImageChannel (MagickWand * , const ChannelType, const MagickWand *)
MagickCoalesceImages()
WandExport MagickWand * MagickCoalesceImages (MagickWand *)
MagickColorDecisionListImage()
WandExport MagickBooleanType MagickColorDecisionListImage (MagickWand * , const char *)
MagickColorizeImage()
WandExport MagickBooleanType MagickColorizeImage (MagickWand * , const PixelWand * , const PixelWand *)
MagickColorMatrixImage()
WandExport MagickBooleanType MagickColorMatrixImage (MagickWand * , const KernelInfo *)
MagickCombineImages()
WandExport MagickWand * MagickCombineImages (MagickWand * , const ChannelType)
MagickCommentImage()
WandExport MagickBooleanType MagickCommentImage (MagickWand * , const char *)
MagickCompareImageChannels()
WandExport MagickWand * MagickCompareImageChannels (MagickWand * , const MagickWand * , const ChannelType, const MetricType, double *)
MagickCompareImageLayers()
WandExport MagickWand * MagickCompareImageLayers (MagickWand * , const ImageLayerMethod)
MagickCompareImages()
WandExport MagickWand * MagickCompareImages (MagickWand * , const MagickWand * , const MetricType, double *)
MagickCompositeImage()
WandExport MagickBooleanType MagickCompositeImage (MagickWand * , const MagickWand * , const CompositeOperator, const ssize_t, const ssize_t)
MagickCompositeImageChannel()
WandExport MagickBooleanType MagickCompositeImageChannel (MagickWand * , const ChannelType, const MagickWand * , const CompositeOperator, const ssize_t, const ssize_t)
MagickCompositeImageGravity()
WandExport MagickBooleanType MagickCompositeImageGravity (MagickWand * , const MagickWand * , const CompositeOperator, const GravityType)
MagickCompositeLayers()
WandExport MagickBooleanType MagickCompositeLayers (MagickWand * , const MagickWand * , const CompositeOperator, const ssize_t, const ssize_t)
MagickConstituteImage()
WandExport MagickBooleanType MagickConstituteImage (MagickWand * , const size_t, const size_t, const char * , const StorageType, const void *)
MagickContrastImage()
WandExport MagickBooleanType MagickContrastImage (MagickWand * , const MagickBooleanType)
MagickContrastStretchImage()
WandExport MagickBooleanType MagickContrastStretchImage (MagickWand * , const double , const double)
MagickContrastStretchImageChannel()
WandExport MagickBooleanType MagickContrastStretchImageChannel (MagickWand * , const ChannelType, const double , const double)
MagickConvolveImage()
WandExport MagickBooleanType MagickConvolveImage (MagickWand * , const size_t, const double *)
MagickConvolveImageChannel()
WandExport MagickBooleanType MagickConvolveImageChannel (MagickWand * , const ChannelType, const size_t, const double *)
MagickCropImage()
WandExport MagickBooleanType MagickCropImage (MagickWand * , const size_t, const size_t, const ssize_t, const ssize_t)
MagickCycleColormapImage()
WandExport MagickBooleanType MagickCycleColormapImage (MagickWand * , const ssize_t)
MagickDecipherImage()
WandExport MagickBooleanType MagickDecipherImage (MagickWand * , const char *)
MagickDeconstructImages()
WandExport MagickWand * MagickDeconstructImages (MagickWand *)
MagickDeskewImage()
WandExport MagickBooleanType MagickDeskewImage (MagickWand * , const double)
MagickDespeckleImage()
WandExport MagickBooleanType MagickDespeckleImage (MagickWand *)
MagickDestroyImage()
WandExport Image * MagickDestroyImage (Image *)
MagickDisplayImage()
WandExport MagickBooleanType MagickDisplayImage (MagickWand * , const char *)
MagickDisplayImages()
WandExport MagickBooleanType MagickDisplayImages (MagickWand * , const char *)
MagickDistortImage()
WandExport MagickBooleanType MagickDistortImage (MagickWand * , const DistortImageMethod, const size_t, const double * , const MagickBooleanType)
MagickDrawImage()
WandExport MagickBooleanType MagickDrawImage (MagickWand * , const DrawingWand *)
MagickEdgeImage()
WandExport MagickBooleanType MagickEdgeImage (MagickWand * , const double)
MagickEmbossImage()
WandExport MagickBooleanType MagickEmbossImage (MagickWand * , const double , const double)
MagickEncipherImage()
WandExport MagickBooleanType MagickEncipherImage (MagickWand * , const char *)
MagickEnhanceImage()
WandExport MagickBooleanType MagickEnhanceImage (MagickWand *)
MagickEqualizeImage()
WandExport MagickBooleanType MagickEqualizeImage (MagickWand *)
MagickEqualizeImageChannel()
WandExport MagickBooleanType MagickEqualizeImageChannel (MagickWand * , const ChannelType)
MagickEvaluateImage()
WandExport MagickBooleanType MagickEvaluateImage (MagickWand * , const MagickEvaluateOperator, const double)
MagickEvaluateImageChannel()
WandExport MagickBooleanType MagickEvaluateImageChannel (MagickWand * , const ChannelType, const MagickEvaluateOperator, const double)
MagickEvaluateImages()
WandExport MagickWand * MagickEvaluateImages (MagickWand * , const MagickEvaluateOperator)
MagickExportImagePixels()
WandExport MagickBooleanType MagickExportImagePixels (MagickWand * , const ssize_t, const ssize_t, const size_t, const size_t, const char * , const StorageType, void *)
MagickExtentImage()
WandExport MagickBooleanType MagickExtentImage (MagickWand * , const size_t, const size_t, const ssize_t, const ssize_t)
MagickFilterImage()
WandExport MagickBooleanType MagickFilterImage (MagickWand * , const KernelInfo *)
MagickFilterImageChannel()
WandExport MagickBooleanType MagickFilterImageChannel (MagickWand * , const ChannelType, const KernelInfo *)
MagickFlipImage()
WandExport MagickBooleanType MagickFlipImage (MagickWand *)
MagickFloodfillPaintImage()
WandExport MagickBooleanType MagickFloodfillPaintImage (MagickWand * , const ChannelType, const PixelWand * , const double , const PixelWand * , const ssize_t, const ssize_t, const MagickBooleanType)
MagickFlopImage()
WandExport MagickBooleanType MagickFlopImage (MagickWand *)
MagickForwardFourierTransformImage()
WandExport MagickBooleanType MagickForwardFourierTransformImage (MagickWand * , const MagickBooleanType)
MagickFrameImage()
WandExport MagickBooleanType MagickFrameImage (MagickWand * , const PixelWand * , const size_t, const size_t, const ssize_t, const ssize_t)
MagickFunctionImage()
WandExport MagickBooleanType MagickFunctionImage (MagickWand * , const MagickFunction, const size_t, const double *)
MagickFunctionImageChannel()
WandExport MagickBooleanType MagickFunctionImageChannel (MagickWand * , const ChannelType, const MagickFunction, const size_t, const double *)
MagickFxImage()
WandExport MagickWand * MagickFxImage (MagickWand * , const char *)
MagickFxImageChannel()
WandExport MagickWand * MagickFxImageChannel (MagickWand * , const ChannelType, const char *)
MagickGammaImage()
WandExport MagickBooleanType MagickGammaImage (MagickWand * , const double)
MagickGammaImageChannel()
WandExport MagickBooleanType MagickGammaImageChannel (MagickWand * , const ChannelType, const double)
MagickGaussianBlurImage()
WandExport MagickBooleanType MagickGaussianBlurImage (MagickWand * , const double , const double)
MagickGaussianBlurImageChannel()
WandExport MagickBooleanType MagickGaussianBlurImageChannel (MagickWand * , const ChannelType, const double , const double)
MagickGetImage()
WandExport MagickWand * MagickGetImage (MagickWand *)
MagickGetImageAlphaChannel()
WandExport MagickBooleanType MagickGetImageAlphaChannel (MagickWand *)
MagickGetImageBackgroundColor()
WandExport MagickBooleanType MagickGetImageBackgroundColor (MagickWand * , PixelWand *)
MagickGetImageBlob()
WandExport unsigned char * MagickGetImageBlob (MagickWand * , size_t *)
MagickGetImageBluePrimary()
WandExport MagickBooleanType MagickGetImageBluePrimary (MagickWand * , double * , double *)
MagickGetImageBorderColor()
WandExport MagickBooleanType MagickGetImageBorderColor (MagickWand * , PixelWand *)
MagickGetImageChannelDepth()
WandExport size_t MagickGetImageChannelDepth (MagickWand * , const ChannelType)
MagickGetImageChannelDistortion()
WandExport MagickBooleanType MagickGetImageChannelDistortion (MagickWand * , const MagickWand * , const ChannelType, const MetricType, double *)
MagickGetImageChannelDistortions()
WandExport double * MagickGetImageChannelDistortions (MagickWand * , const MagickWand * , const MetricType)
MagickGetImageChannelFeatures()
WandExport ChannelFeatures * MagickGetImageChannelFeatures (MagickWand * wand, const size_t)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageChannelKurtosis()
WandExport MagickBooleanType MagickGetImageChannelKurtosis (MagickWand * , const ChannelType, double * , double *)
MagickGetImageChannelMean()
WandExport MagickBooleanType MagickGetImageChannelMean (MagickWand * , const ChannelType, double * , double *)
MagickGetImageChannelRange()
WandExport MagickBooleanType MagickGetImageChannelRange (MagickWand * , const ChannelType, double * , double *)
MagickGetImageChannelStatistics()
WandExport ChannelStatistics * MagickGetImageChannelStatistics (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageClipMask()
WandExport MagickWand * MagickGetImageClipMask (MagickWand *)
MagickGetImageColormapColor()
WandExport MagickBooleanType MagickGetImageColormapColor (MagickWand * , const size_t, PixelWand *)
MagickGetImageColors()
WandExport size_t MagickGetImageColors (MagickWand *)
MagickGetImageColorspace()
WandExport ColorspaceType MagickGetImageColorspace (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageCompose()
WandExport CompositeOperator MagickGetImageCompose (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageCompression()
WandExport CompressionType MagickGetImageCompression (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageCompressionQuality()
WandExport size_t MagickGetImageCompressionQuality (MagickWand *)
MagickGetImageDelay()
WandExport size_t MagickGetImageDelay (MagickWand *)
MagickGetImageDepth()
WandExport size_t MagickGetImageDepth (MagickWand *)
MagickGetImageDispose()
WandExport DisposeType MagickGetImageDispose (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageDistortion()
WandExport MagickBooleanType MagickGetImageDistortion (MagickWand * , const MagickWand * , const MetricType, double *)
MagickGetImageEndian()
WandExport EndianType MagickGetImageEndian (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageFilename()
WandExport char * MagickGetImageFilename (MagickWand *)
MagickGetImageFormat()
WandExport char * MagickGetImageFormat (MagickWand *)
MagickGetImageFuzz()
WandExport double MagickGetImageFuzz (MagickWand *)
MagickGetImageGamma()
WandExport double MagickGetImageGamma (MagickWand *)
MagickGetImageGravity()
WandExport GravityType MagickGetImageGravity (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageGreenPrimary()
WandExport MagickBooleanType MagickGetImageGreenPrimary (MagickWand * , double * , double *)
MagickGetImageHeight()
WandExport size_t MagickGetImageHeight (MagickWand *)
MagickGetImageHistogram()
WandExport PixelWand ** MagickGetImageHistogram (MagickWand * wand, size_t * number_colors)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, NewPixelWands(), PixelSetColorCount(), PixelSetIndex(), PixelSetQuantumColor(), _MagickWand::signature, and WandSignature.
MagickGetImageInterlaceScheme()
WandExport InterlaceType MagickGetImageInterlaceScheme (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageInterpolateMethod()
WandExport InterpolatePixelMethod MagickGetImageInterpolateMethod (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageIterations()
WandExport size_t MagickGetImageIterations (MagickWand *)
MagickGetImageLength()
WandExport MagickBooleanType MagickGetImageLength (MagickWand * , MagickSizeType *)
MagickGetImageMatteColor()
WandExport MagickBooleanType MagickGetImageMatteColor (MagickWand * , PixelWand *)
MagickGetImageOrientation()
WandExport OrientationType MagickGetImageOrientation (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImagePage()
WandExport MagickBooleanType MagickGetImagePage (MagickWand * , size_t * , size_t * , ssize_t * , ssize_t *)
MagickGetImagePixelColor()
WandExport MagickBooleanType MagickGetImagePixelColor (MagickWand * , const ssize_t, const ssize_t, PixelWand *)
MagickGetImageRange()
WandExport MagickBooleanType MagickGetImageRange (MagickWand * , double * , double *)
MagickGetImageRedPrimary()
WandExport MagickBooleanType MagickGetImageRedPrimary (MagickWand * , double * , double *)
MagickGetImageRegion()
WandExport MagickWand * MagickGetImageRegion (MagickWand * , const size_t, const size_t, const ssize_t, const ssize_t)
MagickGetImageRenderingIntent()
WandExport RenderingIntent MagickGetImageRenderingIntent (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageResolution()
WandExport MagickBooleanType MagickGetImageResolution (MagickWand * , double * , double *)
MagickGetImagesBlob()
WandExport unsigned char * MagickGetImagesBlob (MagickWand * wand, size_t * length)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageScene()
WandExport size_t MagickGetImageScene (MagickWand *)
MagickGetImageSignature()
WandExport char * MagickGetImageSignature (MagickWand *)
MagickGetImageTicksPerSecond()
WandExport size_t MagickGetImageTicksPerSecond (MagickWand *)
MagickGetImageTotalInkDensity()
WandExport double MagickGetImageTotalInkDensity (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageType()
WandExport ImageType MagickGetImageType (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageUnits()
WandExport ResolutionType MagickGetImageUnits (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickGetImageVirtualPixelMethod()
WandExport VirtualPixelMethod MagickGetImageVirtualPixelMethod (MagickWand *)
MagickGetImageWhitePoint()
WandExport MagickBooleanType MagickGetImageWhitePoint (MagickWand * , double * , double *)
MagickGetImageWidth()
WandExport size_t MagickGetImageWidth (MagickWand *)
MagickGetNumberImages()
WandExport size_t MagickGetNumberImages (MagickWand * wand)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickHaldClutImage()
WandExport MagickBooleanType MagickHaldClutImage (MagickWand * , const MagickWand *)
MagickHaldClutImageChannel()
WandExport MagickBooleanType MagickHaldClutImageChannel (MagickWand * , const ChannelType, const MagickWand *)
MagickHasNextImage()
WandExport MagickBooleanType MagickHasNextImage (MagickWand *)
MagickHasPreviousImage()
WandExport MagickBooleanType MagickHasPreviousImage (MagickWand *)
MagickIdentifyImage()
WandExport char * MagickIdentifyImage (MagickWand * wand)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, MaxTextExtent, _MagickWand::name, _MagickWand::signature, and WandSignature.
Referenced by MagickDescribeImage().
MagickImplodeImage()
WandExport MagickBooleanType MagickImplodeImage (MagickWand * , const double)
MagickImportImagePixels()
WandExport MagickBooleanType MagickImportImagePixels (MagickWand * , const ssize_t, const ssize_t, const size_t, const size_t, const char * , const StorageType, const void *)
MagickInverseFourierTransformImage()
WandExport MagickBooleanType MagickInverseFourierTransformImage (MagickWand * , MagickWand * , const MagickBooleanType)
MagickLabelImage()
WandExport MagickBooleanType MagickLabelImage (MagickWand * , const char *)
MagickLevelImage()
WandExport MagickBooleanType MagickLevelImage (MagickWand * , const double , const double , const double)
MagickLevelImageChannel()
WandExport MagickBooleanType MagickLevelImageChannel (MagickWand * , const ChannelType, const double , const double , const double)
MagickLevelImageColors()
WandExport MagickBooleanType MagickLevelImageColors (MagickWand * , const PixelWand * , const PixelWand * , const MagickBooleanType)
MagickLevelImageColorsChannel()
WandExport MagickBooleanType MagickLevelImageColorsChannel (MagickWand * , const ChannelType, const PixelWand * , const PixelWand * , const MagickBooleanType)
MagickLevelizeImage()
WandExport MagickBooleanType MagickLevelizeImage (MagickWand * , const double , const double , const double)
MagickLevelizeImageChannel()
WandExport MagickBooleanType MagickLevelizeImageChannel (MagickWand * , const ChannelType, const double , const double , const double)
MagickLinearStretchImage()
WandExport MagickBooleanType MagickLinearStretchImage (MagickWand * , const double , const double)
MagickLiquidRescaleImage()
WandExport MagickBooleanType MagickLiquidRescaleImage (MagickWand * , const size_t, const size_t, const double , const double)
MagickLocalContrastImage()
WandExport MagickBooleanType MagickLocalContrastImage (MagickWand * , const double , const double)
MagickMagnifyImage()
WandExport MagickBooleanType MagickMagnifyImage (MagickWand *)
MagickMedianFilterImage()
WandExport MagickBooleanType MagickMedianFilterImage (MagickWand * , const double)
MagickMergeImageLayers()
WandExport MagickWand * MagickMergeImageLayers (MagickWand * , const ImageLayerMethod)
MagickMinifyImage()
WandExport MagickBooleanType MagickMinifyImage (MagickWand *)
MagickModeImage()
WandExport MagickBooleanType MagickModeImage (MagickWand * , const double)
MagickModulateImage()
WandExport MagickBooleanType MagickModulateImage (MagickWand * , const double , const double , const double)
MagickMontageImage()
WandExport MagickWand * MagickMontageImage (MagickWand * , const DrawingWand * , const char * , const char * , const MontageMode, const char *)
MagickMorphImages()
WandExport MagickWand * MagickMorphImages (MagickWand * , const size_t)
MagickMorphologyImage()
WandExport MagickBooleanType MagickMorphologyImage (MagickWand * , const MorphologyMethod, const ssize_t, const KernelInfo *)
MagickMorphologyImageChannel()
WandExport MagickBooleanType MagickMorphologyImageChannel (MagickWand * , const ChannelType, const MorphologyMethod, const ssize_t, const KernelInfo *)
MagickMotionBlurImage()
WandExport MagickBooleanType MagickMotionBlurImage (MagickWand * , const double , const double , const double)
MagickMotionBlurImageChannel()
WandExport MagickBooleanType MagickMotionBlurImageChannel (MagickWand * , const ChannelType, const double , const double , const double)
MagickNegateImage()
WandExport MagickBooleanType MagickNegateImage (MagickWand * , const MagickBooleanType)
MagickNegateImageChannel()
WandExport MagickBooleanType MagickNegateImageChannel (MagickWand * , const ChannelType, const MagickBooleanType)
MagickNewImage()
WandExport MagickBooleanType MagickNewImage (MagickWand * , const size_t, const size_t, const PixelWand *)
MagickNextImage()
WandExport MagickBooleanType MagickNextImage (MagickWand *)
MagickNormalizeImage()
WandExport MagickBooleanType MagickNormalizeImage (MagickWand *)
MagickNormalizeImageChannel()
WandExport MagickBooleanType MagickNormalizeImageChannel (MagickWand * , const ChannelType)
MagickOilPaintImage()
WandExport MagickBooleanType MagickOilPaintImage (MagickWand * , const double)
MagickOpaquePaintImage()
WandExport MagickBooleanType MagickOpaquePaintImage (MagickWand * , const PixelWand * , const PixelWand * , const double , const MagickBooleanType)
MagickOpaquePaintImageChannel()
WandExport MagickBooleanType MagickOpaquePaintImageChannel (MagickWand * , const ChannelType, const PixelWand * , const PixelWand * , const double , const MagickBooleanType)
MagickOptimizeImageLayers()
WandExport MagickWand * MagickOptimizeImageLayers (MagickWand *)
MagickOptimizeImageTransparency()
WandExport MagickBooleanType MagickOptimizeImageTransparency (MagickWand *)
MagickOrderedPosterizeImage()
WandExport MagickBooleanType MagickOrderedPosterizeImage (MagickWand * , const char *)
MagickOrderedPosterizeImageChannel()
WandExport MagickBooleanType MagickOrderedPosterizeImageChannel (MagickWand * , const ChannelType, const char *)
MagickPingImage()
WandExport MagickBooleanType MagickPingImage (MagickWand * , const char *)
MagickPingImageBlob()
WandExport MagickBooleanType MagickPingImageBlob (MagickWand * , const void * , const size_t)
MagickPingImageFile()
WandExport MagickBooleanType MagickPingImageFile (MagickWand * , FILE *)
MagickPolaroidImage()
WandExport MagickBooleanType MagickPolaroidImage (MagickWand * , const DrawingWand * , const double)
MagickPosterizeImage()
WandExport MagickBooleanType MagickPosterizeImage (MagickWand * , const size_t, const MagickBooleanType)
MagickPreviewImages()
WandExport MagickWand * MagickPreviewImages (MagickWand * wand, const PreviewType)
MagickPreviousImage()
WandExport MagickBooleanType MagickPreviousImage (MagickWand *)
MagickQuantizeImage()
WandExport MagickBooleanType MagickQuantizeImage (MagickWand * , const size_t, const ColorspaceType, const size_t, const MagickBooleanType, const MagickBooleanType)
MagickQuantizeImages()
WandExport MagickBooleanType MagickQuantizeImages (MagickWand * , const size_t, const ColorspaceType, const size_t, const MagickBooleanType, const MagickBooleanType)
MagickRaiseImage()
WandExport MagickBooleanType MagickRaiseImage (MagickWand * , const size_t, const size_t, const ssize_t, const ssize_t, const MagickBooleanType)
MagickRandomThresholdImage()
WandExport MagickBooleanType MagickRandomThresholdImage (MagickWand * , const double , const double)
MagickRandomThresholdImageChannel()
WandExport MagickBooleanType MagickRandomThresholdImageChannel (MagickWand * , const ChannelType, const double , const double)
MagickReadImage()
WandExport MagickBooleanType MagickReadImage (MagickWand * , const char *)
MagickReadImageBlob()
WandExport MagickBooleanType MagickReadImageBlob (MagickWand * , const void * , const size_t)
MagickReadImageFile()
WandExport MagickBooleanType MagickReadImageFile (MagickWand * , FILE *)
MagickReduceNoiseImage()
WandExport MagickBooleanType MagickReduceNoiseImage (MagickWand * , const double)
MagickRemapImage()
WandExport MagickBooleanType MagickRemapImage (MagickWand * , const MagickWand * , const DitherMethod)
MagickRemoveImage()
WandExport MagickBooleanType MagickRemoveImage (MagickWand *)
MagickResampleImage()
WandExport MagickBooleanType MagickResampleImage (MagickWand * , const double , const double , const FilterTypes, const double)
MagickResetImagePage()
WandExport MagickBooleanType MagickResetImagePage (MagickWand * , const char *)
MagickResizeImage()
WandExport MagickBooleanType MagickResizeImage (MagickWand * , const size_t, const size_t, const FilterTypes, const double)
MagickRollImage()
WandExport MagickBooleanType MagickRollImage (MagickWand * , const ssize_t, const ssize_t)
MagickRotateImage()
WandExport MagickBooleanType MagickRotateImage (MagickWand * , const PixelWand * , const double)
MagickRotationalBlurImage()
WandExport MagickBooleanType MagickRotationalBlurImage (MagickWand * , const double)
MagickRotationalBlurImageChannel()
WandExport MagickBooleanType MagickRotationalBlurImageChannel (MagickWand * , const ChannelType, const double)
MagickSampleImage()
WandExport MagickBooleanType MagickSampleImage (MagickWand * , const size_t, const size_t)
MagickScaleImage()
WandExport MagickBooleanType MagickScaleImage (MagickWand * , const size_t, const size_t)
MagickSegmentImage()
WandExport MagickBooleanType MagickSegmentImage (MagickWand * , const ColorspaceType, const MagickBooleanType, const double , const double)
MagickSelectiveBlurImage()
WandExport MagickBooleanType MagickSelectiveBlurImage (MagickWand * , const double , const double , const double)
MagickSelectiveBlurImageChannel()
WandExport MagickBooleanType MagickSelectiveBlurImageChannel (MagickWand * , const ChannelType, const double , const double , const double)
MagickSeparateImageChannel()
WandExport MagickBooleanType MagickSeparateImageChannel (MagickWand * , const ChannelType)
MagickSepiaToneImage()
WandExport MagickBooleanType MagickSepiaToneImage (MagickWand * , const double)
MagickSetImage()
WandExport MagickBooleanType MagickSetImage (MagickWand * , const MagickWand *)
MagickSetImageAlphaChannel()
WandExport MagickBooleanType MagickSetImageAlphaChannel (MagickWand * , const AlphaChannelType)
MagickSetImageBackgroundColor()
WandExport MagickBooleanType MagickSetImageBackgroundColor (MagickWand * , const PixelWand *)
MagickSetImageBias()
WandExport MagickBooleanType MagickSetImageBias (MagickWand * , const double)
MagickSetImageBluePrimary()
WandExport MagickBooleanType MagickSetImageBluePrimary (MagickWand * , const double , const double)
MagickSetImageBorderColor()
WandExport MagickBooleanType MagickSetImageBorderColor (MagickWand * , const PixelWand *)
MagickSetImageChannelDepth()
WandExport MagickBooleanType MagickSetImageChannelDepth (MagickWand * , const ChannelType, const size_t)
MagickSetImageClipMask()
WandExport MagickBooleanType MagickSetImageClipMask (MagickWand * , const MagickWand *)
MagickSetImageColor()
WandExport MagickBooleanType MagickSetImageColor (MagickWand * , const PixelWand *)
MagickSetImageColormapColor()
WandExport MagickBooleanType MagickSetImageColormapColor (MagickWand * , const size_t, const PixelWand *)
MagickSetImageColorspace()
WandExport MagickBooleanType MagickSetImageColorspace (MagickWand * , const ColorspaceType)
MagickSetImageCompose()
WandExport MagickBooleanType MagickSetImageCompose (MagickWand * , const CompositeOperator)
MagickSetImageCompression()
WandExport MagickBooleanType MagickSetImageCompression (MagickWand * , const CompressionType)
MagickSetImageCompressionQuality()
WandExport MagickBooleanType MagickSetImageCompressionQuality (MagickWand * , const size_t)
MagickSetImageDelay()
WandExport MagickBooleanType MagickSetImageDelay (MagickWand * , const size_t)
MagickSetImageDepth()
WandExport MagickBooleanType MagickSetImageDepth (MagickWand * , const size_t)
MagickSetImageDispose()
WandExport MagickBooleanType MagickSetImageDispose (MagickWand * , const DisposeType)
MagickSetImageEndian()
WandExport MagickBooleanType MagickSetImageEndian (MagickWand * , const EndianType)
MagickSetImageExtent()
WandExport MagickBooleanType MagickSetImageExtent (MagickWand * , const size_t, const size_t)
MagickSetImageFilename()
WandExport MagickBooleanType MagickSetImageFilename (MagickWand * , const char *)
MagickSetImageFormat()
WandExport MagickBooleanType MagickSetImageFormat (MagickWand * , const char *)
MagickSetImageFuzz()
WandExport MagickBooleanType MagickSetImageFuzz (MagickWand * , const double)
MagickSetImageGamma()
WandExport MagickBooleanType MagickSetImageGamma (MagickWand * , const double)
MagickSetImageGravity()
WandExport MagickBooleanType MagickSetImageGravity (MagickWand * , const GravityType)
MagickSetImageGreenPrimary()
WandExport MagickBooleanType MagickSetImageGreenPrimary (MagickWand * , const double , const double)
MagickSetImageInterlaceScheme()
WandExport MagickBooleanType MagickSetImageInterlaceScheme (MagickWand * , const InterlaceType)
MagickSetImageInterpolateMethod()
WandExport MagickBooleanType MagickSetImageInterpolateMethod (MagickWand * , const InterpolatePixelMethod)
MagickSetImageIterations()
WandExport MagickBooleanType MagickSetImageIterations (MagickWand * , const size_t)
MagickSetImageMatte()
WandExport MagickBooleanType MagickSetImageMatte (MagickWand * , const MagickBooleanType)
MagickSetImageMatteColor()
WandExport MagickBooleanType MagickSetImageMatteColor (MagickWand * , const PixelWand *)
MagickSetImageOpacity()
WandExport MagickBooleanType MagickSetImageOpacity (MagickWand * , const double)
MagickSetImageOrientation()
WandExport MagickBooleanType MagickSetImageOrientation (MagickWand * , const OrientationType)
MagickSetImagePage()
WandExport MagickBooleanType MagickSetImagePage (MagickWand * , const size_t, const size_t, const ssize_t, const ssize_t)
MagickSetImagePixelColor()
WandExport MagickBooleanType MagickSetImagePixelColor (MagickWand * , const ssize_t, const ssize_t, const PixelWand *)
MagickSetImageProgressMonitor()
WandExport MagickProgressMonitor MagickSetImageProgressMonitor (MagickWand * wand, const MagickProgressMonitor, void * client_data)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickSetImageRedPrimary()
WandExport MagickBooleanType MagickSetImageRedPrimary (MagickWand * , const double , const double)
MagickSetImageRenderingIntent()
WandExport MagickBooleanType MagickSetImageRenderingIntent (MagickWand * , const RenderingIntent)
MagickSetImageResolution()
WandExport MagickBooleanType MagickSetImageResolution (MagickWand * , const double , const double)
MagickSetImageScene()
WandExport MagickBooleanType MagickSetImageScene (MagickWand * , const size_t)
MagickSetImageTicksPerSecond()
WandExport MagickBooleanType MagickSetImageTicksPerSecond (MagickWand * , const ssize_t)
MagickSetImageType()
WandExport MagickBooleanType MagickSetImageType (MagickWand * , const ImageType)
MagickSetImageUnits()
WandExport MagickBooleanType MagickSetImageUnits (MagickWand * , const ResolutionType)
MagickSetImageVirtualPixelMethod()
WandExport VirtualPixelMethod MagickSetImageVirtualPixelMethod (MagickWand * wand, const VirtualPixelMethod)
References _MagickWand::debug, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickSetImageWhitePoint()
WandExport MagickBooleanType MagickSetImageWhitePoint (MagickWand * , const double , const double)
MagickShadeImage()
WandExport MagickBooleanType MagickShadeImage (MagickWand * , const MagickBooleanType, const double , const double)
MagickShadowImage()
WandExport MagickBooleanType MagickShadowImage (MagickWand * , const double , const double , const ssize_t, const ssize_t)
MagickSharpenImage()
WandExport MagickBooleanType MagickSharpenImage (MagickWand * , const double , const double)
MagickSharpenImageChannel()
WandExport MagickBooleanType MagickSharpenImageChannel (MagickWand * , const ChannelType, const double , const double)
MagickShaveImage()
WandExport MagickBooleanType MagickShaveImage (MagickWand * , const size_t, const size_t)
MagickShearImage()
WandExport MagickBooleanType MagickShearImage (MagickWand * , const PixelWand * , const double , const double)
MagickSigmoidalContrastImage()
WandExport MagickBooleanType MagickSigmoidalContrastImage (MagickWand * , const MagickBooleanType, const double , const double)
MagickSigmoidalContrastImageChannel()
WandExport MagickBooleanType MagickSigmoidalContrastImageChannel (MagickWand * , const ChannelType, const MagickBooleanType, const double , const double)
MagickSimilarityImage()
WandExport MagickWand * MagickSimilarityImage (MagickWand * , const MagickWand * , RectangleInfo * , double *)
MagickSketchImage()
WandExport MagickBooleanType MagickSketchImage (MagickWand * , const double , const double , const double)
MagickSmushImages()
WandExport MagickWand * MagickSmushImages (MagickWand * , const MagickBooleanType, const ssize_t)
MagickSolarizeImage()
WandExport MagickBooleanType MagickSolarizeImage (MagickWand * , const double)
MagickSolarizeImageChannel()
WandExport MagickBooleanType MagickSolarizeImageChannel (MagickWand * , const ChannelType, const double)
MagickSparseColorImage()
WandExport MagickBooleanType MagickSparseColorImage (MagickWand * , const ChannelType, const SparseColorMethod, const size_t, const double *)
MagickSpliceImage()
WandExport MagickBooleanType MagickSpliceImage (MagickWand * , const size_t, const size_t, const ssize_t, const ssize_t)
MagickSpreadImage()
WandExport MagickBooleanType MagickSpreadImage (MagickWand * , const double)
MagickStatisticImage()
WandExport MagickBooleanType MagickStatisticImage (MagickWand * , const StatisticType, const size_t, const size_t)
MagickStatisticImageChannel()
WandExport MagickBooleanType MagickStatisticImageChannel (MagickWand * , const ChannelType, const StatisticType, const size_t, const size_t)
MagickSteganoImage()
WandExport MagickWand * MagickSteganoImage (MagickWand * , const MagickWand * , const ssize_t)
MagickStereoImage()
WandExport MagickWand * MagickStereoImage (MagickWand * , const MagickWand *)
MagickStripImage()
WandExport MagickBooleanType MagickStripImage (MagickWand *)
MagickSwirlImage()
WandExport MagickBooleanType MagickSwirlImage (MagickWand * , const double)
MagickTextureImage()
WandExport MagickWand * MagickTextureImage (MagickWand * , const MagickWand *)
MagickThresholdImage()
WandExport MagickBooleanType MagickThresholdImage (MagickWand * , const double)
MagickThresholdImageChannel()
WandExport MagickBooleanType MagickThresholdImageChannel (MagickWand * , const ChannelType, const double)
MagickThumbnailImage()
WandExport MagickBooleanType MagickThumbnailImage (MagickWand * , const size_t, const size_t)
MagickTintImage()
WandExport MagickBooleanType MagickTintImage (MagickWand * , const PixelWand * , const PixelWand *)
MagickTransformImage()
WandExport MagickWand * MagickTransformImage (MagickWand * wand, const char * crop, const char * geometry)
References CloneMagickWandFromImages(), _MagickWand::debug, _MagickWand::exception, _MagickWand::images, _MagickWand::name, _MagickWand::signature, and WandSignature.
MagickTransformImageColorspace()
WandExport MagickBooleanType MagickTransformImageColorspace (MagickWand * , const ColorspaceType)
MagickTransparentPaintImage()
WandExport MagickBooleanType MagickTransparentPaintImage (MagickWand * , const PixelWand * , const double , const double , const MagickBooleanType invert)
MagickTransposeImage()
WandExport MagickBooleanType MagickTransposeImage (MagickWand *)
MagickTransverseImage()
WandExport MagickBooleanType MagickTransverseImage (MagickWand *)
MagickTrimImage()
WandExport MagickBooleanType MagickTrimImage (MagickWand * , const double)
MagickUniqueImageColors()
WandExport MagickBooleanType MagickUniqueImageColors (MagickWand *)
MagickUnsharpMaskImage()
WandExport MagickBooleanType MagickUnsharpMaskImage (MagickWand * , const double , const double , const double , const double)
MagickUnsharpMaskImageChannel()
WandExport MagickBooleanType MagickUnsharpMaskImageChannel (MagickWand * , const ChannelType, const double , const double , const double , const double)
MagickVignetteImage()
WandExport MagickBooleanType MagickVignetteImage (MagickWand * , const double , const double , const ssize_t, const ssize_t)
MagickWaveImage()
WandExport MagickBooleanType MagickWaveImage (MagickWand * , const double , const double)
MagickWhiteThresholdImage()
WandExport MagickBooleanType MagickWhiteThresholdImage (MagickWand * , const PixelWand *)
MagickWriteImage()
WandExport MagickBooleanType MagickWriteImage (MagickWand * , const char *)
MagickWriteImageFile()
WandExport MagickBooleanType MagickWriteImageFile (MagickWand * , FILE *)
MagickWriteImages()
WandExport MagickBooleanType MagickWriteImages (MagickWand * , const char * , const MagickBooleanType)
MagickWriteImagesFile()
WandExport MagickBooleanType MagickWriteImagesFile (MagickWand * wand, FILE * file)
References _MagickWand::debug, _MagickWand::exception, _MagickWand::image_info, _MagickWand::images, _MagickWand::name, _MagickWand::signature, ThrowWandException, and WandSignature.