MagickWand: pixel-iterator.c File Reference
pixel-iterator.c File Reference
#include "wand/studio.h"
#include "wand/MagickWand.h"
#include "wand/magick-wand-private.h"
#include "wand/pixel-iterator.h"
#include "wand/pixel-wand.h"
#include "wand/wand.h"
Data Structures
struct _PixelIterator
Macros
#define PixelIteratorId "PixelIterator"
Functions
WandExport void ClearPixelIterator (PixelIterator *iterator)
WandExport PixelIterator * ClonePixelIterator (const PixelIterator *iterator)
WandExport PixelIterator * DestroyPixelIterator (PixelIterator *iterator)
WandExport MagickBooleanType IsPixelIterator (const PixelIterator *iterator)
WandExport PixelIterator * NewPixelIterator (MagickWand *wand)
WandExport MagickBooleanType PixelClearIteratorException (PixelIterator *iterator)
WandExport PixelIterator * NewPixelRegionIterator (MagickWand *wand, const ssize_t x, const ssize_t y, const size_t width, const size_t height)
WandExport PixelWand ** PixelGetCurrentIteratorRow (PixelIterator *iterator, size_t *number_wands)
WandExport char * PixelGetIteratorException (const PixelIterator *iterator, ExceptionType *severity)
WandExport ExceptionType PixelGetIteratorExceptionType (const PixelIterator *iterator)
WandExport ssize_t PixelGetIteratorRow (PixelIterator *iterator)
WandExport PixelWand ** PixelGetNextIteratorRow (PixelIterator *iterator, size_t *number_wands)
WandExport PixelWand ** PixelGetPreviousRow (PixelIterator *iterator)
WandExport PixelWand ** PixelGetPreviousIteratorRow (PixelIterator *iterator, size_t *number_wands)
WandExport void PixelResetIterator (PixelIterator *iterator)
WandExport void PixelSetFirstIteratorRow (PixelIterator *iterator)
WandExport MagickBooleanType PixelSetIteratorRow (PixelIterator *iterator, const ssize_t row)
WandExport void PixelSetLastIteratorRow (PixelIterator *iterator)
WandExport MagickBooleanType PixelSyncIterator (PixelIterator *iterator)
Macro Definition Documentation
PixelIteratorId
#define PixelIteratorId "PixelIterator"
Function Documentation
ClearPixelIterator()
WandExport void ClearPixelIterator (PixelIterator * iterator)
References _PixelIterator::active, _PixelIterator::debug, DestroyPixelWands(), _PixelIterator::exception, _PixelIterator::name, NewPixelWands(), _PixelIterator::pixel_wands, _PixelIterator::region, _PixelIterator::signature, WandSignature, and _PixelIterator::y.
ClonePixelIterator()
WandExport PixelIterator * ClonePixelIterator (const PixelIterator * iterator)
References AcquireWandId(), _PixelIterator::active, ClonePixelWands(), _PixelIterator::debug, _PixelIterator::exception, _PixelIterator::id, MaxTextExtent, _PixelIterator::name, _PixelIterator::pixel_wands, PixelIteratorId, _PixelIterator::region, _PixelIterator::signature, _PixelIterator::view, WandSignature, and _PixelIterator::y.
DestroyPixelIterator()
WandExport PixelIterator * DestroyPixelIterator (PixelIterator * iterator)
References _PixelIterator::debug, DestroyPixelWands(), _PixelIterator::exception, _PixelIterator::id, _PixelIterator::name, _PixelIterator::pixel_wands, _PixelIterator::region, RelinquishWandId(), _PixelIterator::signature, _PixelIterator::view, and WandSignature.
IsPixelIterator()
WandExport MagickBooleanType IsPixelIterator (const PixelIterator * iterator)
References _PixelIterator::name, PixelIteratorId, _PixelIterator::signature, and WandSignature.
NewPixelIterator()
WandExport PixelIterator * NewPixelIterator (MagickWand * wand)
References AcquireWandId(), _PixelIterator::debug, _PixelIterator::exception, GetImageFromMagickWand(), _PixelIterator::id, MaxTextExtent, _PixelIterator::name, NewPixelWands(), _PixelIterator::pixel_wands, PixelIteratorId, _PixelIterator::region, _PixelIterator::signature, ThrowWandFatalException, _PixelIterator::view, WandSignature, and _PixelIterator::y.
NewPixelRegionIterator()
WandExport PixelIterator * NewPixelRegionIterator (MagickWand * wand, const ssize_t x, const ssize_t y, const size_t width, const size_t height)
References AcquireWandId(), _PixelIterator::debug, _PixelIterator::exception, GetImageFromMagickWand(), _PixelIterator::id, MaxTextExtent, _PixelIterator::name, NewPixelWands(), _PixelIterator::pixel_wands, PixelIteratorId, _PixelIterator::region, _PixelIterator::signature, ThrowWandFatalException, _PixelIterator::view, WandSignature, and _PixelIterator::y.
PixelClearIteratorException()
WandExport MagickBooleanType PixelClearIteratorException (PixelIterator * iterator)
References _PixelIterator::debug, _PixelIterator::exception, _PixelIterator::name, _PixelIterator::signature, and WandSignature.
PixelGetCurrentIteratorRow()
WandExport PixelWand ** PixelGetCurrentIteratorRow (PixelIterator * iterator, size_t * number_wands)
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::exception, _PixelIterator::name, _PixelIterator::pixel_wands, PixelSetBlackQuantum(), PixelSetIndex(), PixelSetQuantumColor(), _PixelIterator::region, _PixelIterator::signature, _PixelIterator::view, WandSignature, and _PixelIterator::y.
PixelGetIteratorException()
WandExport char * PixelGetIteratorException (const PixelIterator * iterator, ExceptionType * severity)
References _PixelIterator::debug, _PixelIterator::exception, MaxTextExtent, _PixelIterator::name, _PixelIterator::signature, ThrowWandFatalException, and WandSignature.
Referenced by PixelIteratorGetException().
PixelGetIteratorExceptionType()
WandExport ExceptionType PixelGetIteratorExceptionType (const PixelIterator * iterator)
References _PixelIterator::debug, _PixelIterator::exception, _PixelIterator::name, _PixelIterator::signature, and WandSignature.
PixelGetIteratorRow()
WandExport ssize_t PixelGetIteratorRow (PixelIterator * iterator)
References _PixelIterator::debug, _PixelIterator::name, _PixelIterator::signature, WandSignature, and _PixelIterator::y.
PixelGetNextIteratorRow()
WandExport PixelWand ** PixelGetNextIteratorRow (PixelIterator * iterator, size_t * number_wands)
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::exception, _PixelIterator::name, _PixelIterator::pixel_wands, PixelSetBlackQuantum(), PixelSetIndex(), PixelSetIteratorRow(), PixelSetQuantumColor(), _PixelIterator::region, _PixelIterator::signature, _PixelIterator::view, WandSignature, and _PixelIterator::y.
Referenced by PixelGetNextRow().
PixelGetPreviousIteratorRow()
WandExport PixelWand ** PixelGetPreviousIteratorRow (PixelIterator * iterator, size_t * number_wands)
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::exception, _PixelIterator::name, _PixelIterator::pixel_wands, PixelSetBlackQuantum(), PixelSetIndex(), PixelSetIteratorRow(), PixelSetQuantumColor(), _PixelIterator::region, _PixelIterator::signature, _PixelIterator::view, WandSignature, and _PixelIterator::y.
Referenced by PixelGetPreviousRow().
PixelGetPreviousRow()
WandExport PixelWand ** PixelGetPreviousRow (PixelIterator * iterator)
References PixelGetPreviousIteratorRow().
PixelResetIterator()
WandExport void PixelResetIterator (PixelIterator * iterator)
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::name, _PixelIterator::signature, WandSignature, and _PixelIterator::y.
PixelSetFirstIteratorRow()
WandExport void PixelSetFirstIteratorRow (PixelIterator * iterator)
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::name, _PixelIterator::region, _PixelIterator::signature, WandSignature, and _PixelIterator::y.
PixelSetIteratorRow()
WandExport MagickBooleanType PixelSetIteratorRow (PixelIterator * iterator, const ssize_t row)
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::name, _PixelIterator::region, _PixelIterator::signature, WandSignature, and _PixelIterator::y.
Referenced by PixelGetNextIteratorRow(), and PixelGetPreviousIteratorRow().
PixelSetLastIteratorRow()
WandExport void PixelSetLastIteratorRow (PixelIterator * iterator)
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::name, _PixelIterator::region, _PixelIterator::signature, WandSignature, and _PixelIterator::y.
PixelSyncIterator()
WandExport MagickBooleanType PixelSyncIterator (PixelIterator * iterator)
References _PixelIterator::debug, _PixelIterator::exception, magick_restrict, _PixelIterator::name, _PixelIterator::pixel_wands, PixelGetBlackQuantum(), PixelGetQuantumColor(), _PixelIterator::region, _PixelIterator::signature, _PixelIterator::view, WandSignature, and _PixelIterator::y.