MagickWand: pixel-wand.h File Reference
pixel-wand.h File Reference
Typedefs
typedef struct _PixelWand PixelWand
Functions
WandExport char * PixelGetColorAsNormalizedString (const PixelWand *)
WandExport char * PixelGetColorAsString (const PixelWand *)
WandExport char * PixelGetException (const PixelWand *, ExceptionType *)
WandExport double PixelGetAlpha (const PixelWand *) magick_attribute((__pure__))
WandExport double PixelGetBlack (const PixelWand *) magick_attribute((__pure__))
WandExport double PixelGetBlue (const PixelWand *) magick_attribute((__pure__))
WandExport double PixelGetCyan (const PixelWand *) magick_attribute((__pure__))
WandExport double PixelGetFuzz (const PixelWand *) magick_attribute((__pure__))
WandExport double PixelGetGreen (const PixelWand *) magick_attribute((__pure__))
WandExport double PixelGetMagenta (const PixelWand *) magick_attribute((__pure__))
WandExport double PixelGetOpacity (const PixelWand *) magick_attribute((__pure__))
WandExport double PixelGetRed (const PixelWand *) magick_attribute((__pure__))
WandExport double PixelGetYellow (const PixelWand *) magick_attribute((__pure__))
WandExport ExceptionType PixelGetExceptionType (const PixelWand *)
WandExport IndexPacket PixelGetIndex (const PixelWand *)
WandExport MagickBooleanType IsPixelWand (const PixelWand *)
WandExport MagickBooleanType IsPixelWandSimilar (PixelWand *, PixelWand *, const double)
WandExport MagickBooleanType PixelClearException (PixelWand *)
WandExport MagickBooleanType PixelSetColor (PixelWand *, const char *)
WandExport PixelWand * ClonePixelWand (const PixelWand *)
WandExport PixelWand ** ClonePixelWands (const PixelWand **, const size_t)
WandExport PixelWand * DestroyPixelWand (PixelWand *)
WandExport PixelWand ** DestroyPixelWands (PixelWand **, const size_t)
WandExport PixelWand * NewPixelWand (void)
WandExport PixelWand ** NewPixelWands (const size_t)
WandExport Quantum PixelGetAlphaQuantum (const PixelWand *) magick_attribute((__pure__))
WandExport Quantum PixelGetBlackQuantum (const PixelWand *) magick_attribute((__pure__))
WandExport Quantum PixelGetBlueQuantum (const PixelWand *) magick_attribute((__pure__))
WandExport Quantum PixelGetCyanQuantum (const PixelWand *) magick_attribute((__pure__))
WandExport Quantum PixelGetGreenQuantum (const PixelWand *) magick_attribute((__pure__))
WandExport Quantum PixelGetMagentaQuantum (const PixelWand *) magick_attribute((__pure__))
WandExport Quantum PixelGetOpacityQuantum (const PixelWand *) magick_attribute((__pure__))
WandExport Quantum PixelGetRedQuantum (const PixelWand *) magick_attribute((__pure__))
WandExport Quantum PixelGetYellowQuantum (const PixelWand *) magick_attribute((__pure__))
WandExport size_t PixelGetColorCount (const PixelWand *) magick_attribute((__pure__))
WandExport void ClearPixelWand (PixelWand *)
WandExport void PixelGetHSL (const PixelWand *, double *, double *, double *)
WandExport void PixelGetMagickColor (const PixelWand *, MagickPixelPacket *)
WandExport void PixelGetQuantumColor (const PixelWand *, PixelPacket *)
WandExport void PixelSetAlpha (PixelWand *, const double)
WandExport void PixelSetAlphaQuantum (PixelWand *, const Quantum)
WandExport void PixelSetBlack (PixelWand *, const double)
WandExport void PixelSetBlackQuantum (PixelWand *, const Quantum)
WandExport void PixelSetBlue (PixelWand *, const double)
WandExport void PixelSetBlueQuantum (PixelWand *, const Quantum)
WandExport void PixelSetColorFromWand (PixelWand *, const PixelWand *)
WandExport void PixelSetColorCount (PixelWand *, const size_t)
WandExport void PixelSetCyan (PixelWand *, const double)
WandExport void PixelSetCyanQuantum (PixelWand *, const Quantum)
WandExport void PixelSetFuzz (PixelWand *, const double)
WandExport void PixelSetGreen (PixelWand *, const double)
WandExport void PixelSetGreenQuantum (PixelWand *, const Quantum)
WandExport void PixelSetHSL (PixelWand *, const double, const double, const double)
WandExport void PixelSetIndex (PixelWand *, const IndexPacket)
WandExport void PixelSetMagenta (PixelWand *, const double)
WandExport void PixelSetMagentaQuantum (PixelWand *, const Quantum)
WandExport void PixelSetMagickColor (PixelWand *, const MagickPixelPacket *)
WandExport void PixelSetOpacity (PixelWand *, const double)
WandExport void PixelSetOpacityQuantum (PixelWand *, const Quantum)
WandExport void PixelSetQuantumColor (PixelWand *, const PixelPacket *)
WandExport void PixelSetRed (PixelWand *, const double)
WandExport void PixelSetRedQuantum (PixelWand *, const Quantum)
WandExport void PixelSetYellow (PixelWand *, const double)
WandExport void PixelSetYellowQuantum (PixelWand *, const Quantum)
Typedef Documentation
PixelWand
typedef struct _PixelWand PixelWand
Function Documentation
ClearPixelWand()
WandExport void ClearPixelWand (PixelWand *)
ClonePixelWand()
WandExport PixelWand * ClonePixelWand (const PixelWand *)
ClonePixelWands()
WandExport PixelWand ** ClonePixelWands (const PixelWand ** , const size_t)
DestroyPixelWand()
WandExport PixelWand * DestroyPixelWand (PixelWand *)
DestroyPixelWands()
WandExport PixelWand ** DestroyPixelWands (PixelWand ** , const size_t)
IsPixelWand()
WandExport MagickBooleanType IsPixelWand (const PixelWand *)
IsPixelWandSimilar()
WandExport MagickBooleanType IsPixelWandSimilar (PixelWand * , PixelWand * , const double)
NewPixelWand()
WandExport PixelWand * NewPixelWand (void)
NewPixelWands()
WandExport PixelWand ** NewPixelWands (const size_t)
References NewPixelWand().
Referenced by AcquirePixelsThreadSet(), ClearPixelIterator(), MagickGetImageHistogram(), NewPixelIterator(), and NewPixelRegionIterator().
PixelClearException()
WandExport MagickBooleanType PixelClearException (PixelWand *)
PixelGetAlpha()
WandExport double PixelGetAlpha (const PixelWand *)
PixelGetAlphaQuantum()
WandExport Quantum PixelGetAlphaQuantum (const PixelWand *)
PixelGetBlack()
WandExport double PixelGetBlack (const PixelWand *)
PixelGetBlackQuantum()
WandExport Quantum PixelGetBlackQuantum (const PixelWand *)
PixelGetBlue()
WandExport double PixelGetBlue (const PixelWand *)
PixelGetBlueQuantum()
WandExport Quantum PixelGetBlueQuantum (const PixelWand *)
PixelGetColorAsNormalizedString()
WandExport char * PixelGetColorAsNormalizedString (const PixelWand *)
PixelGetColorAsString()
WandExport char * PixelGetColorAsString (const PixelWand *)
PixelGetColorCount()
WandExport size_t PixelGetColorCount (const PixelWand * wand)
References _PixelWand::count, _PixelWand::debug, _PixelWand::name, _PixelWand::signature, and WandSignature.
PixelGetCyan()
WandExport double PixelGetCyan (const PixelWand *)
PixelGetCyanQuantum()
WandExport Quantum PixelGetCyanQuantum (const PixelWand *)
PixelGetException()
WandExport char * PixelGetException (const PixelWand * wand, ExceptionType * severity)
References _PixelWand::debug, _PixelWand::exception, MaxTextExtent, _PixelWand::name, _PixelWand::signature, ThrowWandFatalException, and WandSignature.
PixelGetExceptionType()
WandExport ExceptionType PixelGetExceptionType (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::exception, _PixelWand::name, _PixelWand::signature, and WandSignature.
PixelGetFuzz()
WandExport double PixelGetFuzz (const PixelWand *)
PixelGetGreen()
WandExport double PixelGetGreen (const PixelWand *)
PixelGetGreenQuantum()
WandExport Quantum PixelGetGreenQuantum (const PixelWand *)
PixelGetHSL()
WandExport void PixelGetHSL (const PixelWand * , double * , double * , double *)
PixelGetIndex()
WandExport IndexPacket PixelGetIndex (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickSetImagePixelColor().
PixelGetMagenta()
WandExport double PixelGetMagenta (const PixelWand *)
PixelGetMagentaQuantum()
WandExport Quantum PixelGetMagentaQuantum (const PixelWand *)
PixelGetMagickColor()
WandExport void PixelGetMagickColor (const PixelWand * , MagickPixelPacket *)
PixelGetOpacity()
WandExport double PixelGetOpacity (const PixelWand *)
PixelGetOpacityQuantum()
WandExport Quantum PixelGetOpacityQuantum (const PixelWand *)
PixelGetQuantumColor()
WandExport void PixelGetQuantumColor (const PixelWand * , PixelPacket *)
PixelGetRed()
WandExport double PixelGetRed (const PixelWand *)
PixelGetRedQuantum()
WandExport Quantum PixelGetRedQuantum (const PixelWand *)
PixelGetYellow()
WandExport double PixelGetYellow (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetYellowQuantum()
WandExport Quantum PixelGetYellowQuantum (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetAlpha()
WandExport void PixelSetAlpha (PixelWand * , const double)
PixelSetAlphaQuantum()
WandExport void PixelSetAlphaQuantum (PixelWand * , const Quantum)
PixelSetBlack()
WandExport void PixelSetBlack (PixelWand * , const double)
PixelSetBlackQuantum()
WandExport void PixelSetBlackQuantum (PixelWand * , const Quantum)
PixelSetBlue()
WandExport void PixelSetBlue (PixelWand * , const double)
PixelSetBlueQuantum()
WandExport void PixelSetBlueQuantum (PixelWand * , const Quantum)
PixelSetColor()
WandExport MagickBooleanType PixelSetColor (PixelWand * wand, const char * color)
References _PixelWand::debug, _PixelWand::exception, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetColorCount()
WandExport void PixelSetColorCount (PixelWand * , const size_t)
PixelSetColorFromWand()
WandExport void PixelSetColorFromWand (PixelWand * , const PixelWand *)
PixelSetCyan()
WandExport void PixelSetCyan (PixelWand * , const double)
PixelSetCyanQuantum()
WandExport void PixelSetCyanQuantum (PixelWand * , const Quantum)
PixelSetFuzz()
WandExport void PixelSetFuzz (PixelWand * , const double)
PixelSetGreen()
WandExport void PixelSetGreen (PixelWand * , const double)
PixelSetGreenQuantum()
WandExport void PixelSetGreenQuantum (PixelWand * , const Quantum)
PixelSetHSL()
WandExport void PixelSetHSL (PixelWand * , const double , const double , const double)
PixelSetIndex()
WandExport void PixelSetIndex (PixelWand * , const IndexPacket)
PixelSetMagenta()
WandExport void PixelSetMagenta (PixelWand * , const double)
PixelSetMagentaQuantum()
WandExport void PixelSetMagentaQuantum (PixelWand * , const Quantum)
PixelSetMagickColor()
WandExport void PixelSetMagickColor (PixelWand * , const MagickPixelPacket *)
PixelSetOpacity()
WandExport void PixelSetOpacity (PixelWand * , const double)
PixelSetOpacityQuantum()
WandExport void PixelSetOpacityQuantum (PixelWand * , const Quantum)
PixelSetQuantumColor()
WandExport void PixelSetQuantumColor (PixelWand * , const PixelPacket *)
PixelSetRed()
WandExport void PixelSetRed (PixelWand * , const double)
PixelSetRedQuantum()
WandExport void PixelSetRedQuantum (PixelWand * , const Quantum)
PixelSetYellow()
WandExport void PixelSetYellow (PixelWand * , const double)
PixelSetYellowQuantum()
WandExport void PixelSetYellowQuantum (PixelWand * wand, const Quantum)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.