MagickWand: pixel-iterator.h File Reference
pixel-iterator.h File Reference
#include "wand/magick-wand.h"
#include "wand/pixel-wand.h"
Typedefs
typedef struct _PixelIterator PixelIterator
Functions
WandExport char * PixelGetIteratorException (const PixelIterator *, ExceptionType *)
WandExport ExceptionType PixelGetIteratorExceptionType (const PixelIterator *)
WandExport MagickBooleanType IsPixelIterator (const PixelIterator *)
WandExport MagickBooleanType PixelClearIteratorException (PixelIterator *)
WandExport MagickBooleanType PixelSetIteratorRow (PixelIterator *, const ssize_t)
WandExport MagickBooleanType PixelSyncIterator (PixelIterator *)
WandExport PixelIterator * ClonePixelIterator (const PixelIterator *)
WandExport PixelIterator * DestroyPixelIterator (PixelIterator *)
WandExport PixelIterator * NewPixelIterator (MagickWand *)
WandExport PixelIterator * NewPixelRegionIterator (MagickWand *, const ssize_t, const ssize_t, const size_t, const size_t)
WandExport PixelWand ** PixelGetCurrentIteratorRow (PixelIterator *, size_t *)
WandExport PixelWand ** PixelGetNextIteratorRow (PixelIterator *, size_t *)
WandExport PixelWand ** PixelGetPreviousIteratorRow (PixelIterator *, size_t *)
WandExport ssize_t PixelGetIteratorRow (PixelIterator *)
WandExport void ClearPixelIterator (PixelIterator *)
WandExport void PixelResetIterator (PixelIterator *)
WandExport void PixelSetFirstIteratorRow (PixelIterator *)
WandExport void PixelSetLastIteratorRow (PixelIterator *)
Typedef Documentation
PixelIterator
typedef struct _PixelIterator PixelIterator
Function Documentation
ClearPixelIterator()
WandExport void ClearPixelIterator (PixelIterator *)
ClonePixelIterator()
WandExport PixelIterator * ClonePixelIterator (const PixelIterator *)
DestroyPixelIterator()
WandExport PixelIterator * DestroyPixelIterator (PixelIterator *)
IsPixelIterator()
WandExport MagickBooleanType IsPixelIterator (const PixelIterator *)
NewPixelIterator()
WandExport PixelIterator * NewPixelIterator (MagickWand *)
NewPixelRegionIterator()
WandExport PixelIterator * NewPixelRegionIterator (MagickWand * wand, const ssize_t, const ssize_t, const size_t, const size_t)
References AcquireWandId(), _PixelIterator::debug, _PixelIterator::exception, GetImageFromMagickWand(), _PixelIterator::id, MaxTextExtent, _PixelIterator::name, NewPixelWands(), _PixelIterator::pixel_wands, PixelIteratorId, _PixelIterator::region, _PixelIterator::signature, ThrowWandFatalException, _PixelIterator::view, WandSignature, and _PixelIterator::y.
PixelClearIteratorException()
WandExport MagickBooleanType PixelClearIteratorException (PixelIterator *)
PixelGetCurrentIteratorRow()
WandExport PixelWand ** PixelGetCurrentIteratorRow (PixelIterator * , size_t *)
PixelGetIteratorException()
WandExport char * PixelGetIteratorException (const PixelIterator * iterator, ExceptionType * severity)
References _PixelIterator::debug, _PixelIterator::exception, MaxTextExtent, _PixelIterator::name, _PixelIterator::signature, ThrowWandFatalException, and WandSignature.
Referenced by PixelIteratorGetException().
PixelGetIteratorExceptionType()
WandExport ExceptionType PixelGetIteratorExceptionType (const PixelIterator * iterator)
References _PixelIterator::debug, _PixelIterator::exception, _PixelIterator::name, _PixelIterator::signature, and WandSignature.
PixelGetIteratorRow()
WandExport ssize_t PixelGetIteratorRow (PixelIterator * iterator)
References _PixelIterator::debug, _PixelIterator::name, _PixelIterator::signature, WandSignature, and _PixelIterator::y.
PixelGetNextIteratorRow()
WandExport PixelWand ** PixelGetNextIteratorRow (PixelIterator * , size_t *)
PixelGetPreviousIteratorRow()
WandExport PixelWand ** PixelGetPreviousIteratorRow (PixelIterator * iterator, size_t * number_wands)
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::exception, _PixelIterator::name, _PixelIterator::pixel_wands, PixelSetBlackQuantum(), PixelSetIndex(), PixelSetIteratorRow(), PixelSetQuantumColor(), _PixelIterator::region, _PixelIterator::signature, _PixelIterator::view, WandSignature, and _PixelIterator::y.
Referenced by PixelGetPreviousRow().
PixelResetIterator()
WandExport void PixelResetIterator (PixelIterator *)
PixelSetFirstIteratorRow()
WandExport void PixelSetFirstIteratorRow (PixelIterator *)
PixelSetIteratorRow()
WandExport MagickBooleanType PixelSetIteratorRow (PixelIterator * , const ssize_t)
PixelSetLastIteratorRow()
WandExport void PixelSetLastIteratorRow (PixelIterator * iterator)
References _PixelIterator::active, _PixelIterator::debug, _PixelIterator::name, _PixelIterator::region, _PixelIterator::signature, WandSignature, and _PixelIterator::y.
PixelSyncIterator()
WandExport MagickBooleanType PixelSyncIterator (PixelIterator * iterator)
References _PixelIterator::debug, _PixelIterator::exception, magick_restrict, _PixelIterator::name, _PixelIterator::pixel_wands, PixelGetBlackQuantum(), PixelGetQuantumColor(), _PixelIterator::region, _PixelIterator::signature, _PixelIterator::view, WandSignature, and _PixelIterator::y.