MagickWand: pixel-wand.c File Reference
pixel-wand.c File Reference
#include "wand/studio.h"
#include "wand/MagickWand.h"
#include "wand/magick-wand-private.h"
#include "wand/pixel-wand-private.h"
#include "wand/wand.h"
Data Structures
struct _PixelWand
Macros
#define PixelWandId "PixelWand"
Functions
WandExport void ClearPixelWand (PixelWand *wand)
WandExport PixelWand * ClonePixelWand (const PixelWand *wand)
WandExport PixelWand ** ClonePixelWands (const PixelWand **wands, const size_t number_wands)
WandExport PixelWand * DestroyPixelWand (PixelWand *wand)
WandExport PixelWand ** DestroyPixelWands (PixelWand **wand, const size_t number_wands)
WandExport MagickBooleanType IsPixelWandSimilar (PixelWand *p, PixelWand *q, const double fuzz)
WandExport MagickBooleanType IsPixelWand (const PixelWand *wand)
WandExport PixelWand * NewPixelWand (void)
WandExport PixelWand ** NewPixelWands (const size_t number_wands)
WandExport MagickBooleanType PixelClearException (PixelWand *wand)
WandExport double PixelGetAlpha (const PixelWand *wand)
WandExport Quantum PixelGetAlphaQuantum (const PixelWand *wand)
WandExport double PixelGetBlack (const PixelWand *wand)
WandExport Quantum PixelGetBlackQuantum (const PixelWand *wand)
WandExport double PixelGetBlue (const PixelWand *wand)
WandExport Quantum PixelGetBlueQuantum (const PixelWand *wand)
WandExport char * PixelGetColorAsString (const PixelWand *wand)
WandExport char * PixelGetColorAsNormalizedString (const PixelWand *wand)
WandExport size_t PixelGetColorCount (const PixelWand *wand)
WandExport double PixelGetCyan (const PixelWand *wand)
WandExport Quantum PixelGetCyanQuantum (const PixelWand *wand)
WandExport char * PixelGetException (const PixelWand *wand, ExceptionType *severity)
WandExport ExceptionType PixelGetExceptionType (const PixelWand *wand)
WandExport double PixelGetFuzz (const PixelWand *wand)
WandExport double PixelGetGreen (const PixelWand *wand)
WandExport Quantum PixelGetGreenQuantum (const PixelWand *wand)
WandExport void PixelGetHSL (const PixelWand *wand, double *hue, double *saturation, double *lightness)
WandExport IndexPacket PixelGetIndex (const PixelWand *wand)
WandExport double PixelGetMagenta (const PixelWand *wand)
WandExport Quantum PixelGetMagentaQuantum (const PixelWand *wand)
WandExport void PixelGetMagickColor (const PixelWand *wand, MagickPixelPacket *color)
WandExport double PixelGetOpacity (const PixelWand *wand)
WandExport Quantum PixelGetOpacityQuantum (const PixelWand *wand)
WandExport void PixelGetQuantumColor (const PixelWand *wand, PixelPacket *color)
WandExport double PixelGetRed (const PixelWand *wand)
WandExport Quantum PixelGetRedQuantum (const PixelWand *wand)
WandExport double PixelGetYellow (const PixelWand *wand)
WandExport Quantum PixelGetYellowQuantum (const PixelWand *wand)
WandExport void PixelSetAlpha (PixelWand *wand, const double alpha)
WandExport void PixelSetAlphaQuantum (PixelWand *wand, const Quantum opacity)
WandExport void PixelSetBlack (PixelWand *wand, const double black)
WandExport void PixelSetBlackQuantum (PixelWand *wand, const Quantum black)
WandExport void PixelSetBlue (PixelWand *wand, const double blue)
WandExport void PixelSetBlueQuantum (PixelWand *wand, const Quantum blue)
WandExport MagickBooleanType PixelSetColor (PixelWand *wand, const char *color)
WandExport void PixelSetColorCount (PixelWand *wand, const size_t count)
WandExport void PixelSetColorFromWand (PixelWand *wand, const PixelWand *color)
WandExport void PixelSetCyan (PixelWand *wand, const double cyan)
WandExport void PixelSetCyanQuantum (PixelWand *wand, const Quantum cyan)
WandExport void PixelSetFuzz (PixelWand *wand, const double fuzz)
WandExport void PixelSetGreen (PixelWand *wand, const double green)
WandExport void PixelSetGreenQuantum (PixelWand *wand, const Quantum green)
WandExport void PixelSetHSL (PixelWand *wand, const double hue, const double saturation, const double lightness)
WandExport void PixelSetIndex (PixelWand *wand, const IndexPacket index)
WandExport void PixelSetMagenta (PixelWand *wand, const double magenta)
WandExport void PixelSetMagentaQuantum (PixelWand *wand, const Quantum magenta)
WandExport void PixelSetMagickColor (PixelWand *wand, const MagickPixelPacket *color)
WandExport void PixelSetOpacity (PixelWand *wand, const double opacity)
WandExport void PixelSetOpacityQuantum (PixelWand *wand, const Quantum opacity)
WandExport void PixelSetQuantumColor (PixelWand *wand, const PixelPacket *color)
WandExport void PixelSetRed (PixelWand *wand, const double red)
WandExport void PixelSetRedQuantum (PixelWand *wand, const Quantum red)
WandExport void PixelSetYellow (PixelWand *wand, const double yellow)
WandExport void PixelSetYellowQuantum (PixelWand *wand, const Quantum yellow)
Macro Definition Documentation
PixelWandId
#define PixelWandId "PixelWand"
Function Documentation
ClearPixelWand()
WandExport void ClearPixelWand (PixelWand * wand)
References _PixelWand::debug, _PixelWand::exception, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
ClonePixelWand()
WandExport PixelWand * ClonePixelWand (const PixelWand * wand)
References AcquireWandId(), _PixelWand::count, _PixelWand::debug, _PixelWand::exception, _PixelWand::id, MaxTextExtent, _PixelWand::name, _PixelWand::pixel, PixelWandId, _PixelWand::signature, and WandSignature.
Referenced by ClonePixelWands().
ClonePixelWands()
WandExport PixelWand ** ClonePixelWands (const PixelWand ** wands, const size_t number_wands)
References ClonePixelWand().
Referenced by ClonePixelIterator(), ClonePixelView(), and CloneWandView().
DestroyPixelWand()
WandExport PixelWand * DestroyPixelWand (PixelWand * wand)
References _PixelWand::debug, _PixelWand::exception, _PixelWand::id, _PixelWand::name, RelinquishWandId(), _PixelWand::signature, and WandSignature.
Referenced by DestroyPixelWands(), and MagickMontageImage().
DestroyPixelWands()
WandExport PixelWand ** DestroyPixelWands (PixelWand ** wand, const size_t number_wands)
References DestroyPixelWand(), and WandSignature.
Referenced by ClearPixelIterator(), DestroyPixelIterator(), and DestroyPixelsThreadSet().
IsPixelWand()
WandExport MagickBooleanType IsPixelWand (const PixelWand * wand)
References _PixelWand::name, PixelWandId, _PixelWand::signature, and WandSignature.
IsPixelWandSimilar()
WandExport MagickBooleanType IsPixelWandSimilar (PixelWand * p, PixelWand * q, const double fuzz)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
NewPixelWand()
WandExport PixelWand * NewPixelWand (void)
References AcquireWandId(), _PixelWand::debug, _PixelWand::exception, _PixelWand::id, MaxTextExtent, _PixelWand::name, _PixelWand::pixel, PixelWandId, _PixelWand::signature, ThrowWandFatalException, and WandSignature.
Referenced by MagickGetBackgroundColor(), MagickMontageImage(), and NewPixelWands().
NewPixelWands()
WandExport PixelWand ** NewPixelWands (const size_t number_wands)
References NewPixelWand().
Referenced by AcquirePixelsThreadSet(), ClearPixelIterator(), MagickGetImageHistogram(), NewPixelIterator(), and NewPixelRegionIterator().
PixelClearException()
WandExport MagickBooleanType PixelClearException (PixelWand * wand)
References _PixelWand::debug, _PixelWand::exception, _PixelWand::name, _PixelWand::signature, and WandSignature.
PixelGetAlpha()
WandExport double PixelGetAlpha (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetAlphaQuantum()
WandExport Quantum PixelGetAlphaQuantum (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetBlack()
WandExport double PixelGetBlack (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetBlackQuantum()
WandExport Quantum PixelGetBlackQuantum (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by DuplexTransferPixelViewIterator(), DuplexTransferWandViewIterator(), MagickSetImagePixelColor(), PixelSyncIterator(), SetPixelViewIterator(), SetWandViewIterator(), TransferPixelViewIterator(), TransferWandViewIterator(), UpdatePixelViewIterator(), and UpdateWandViewIterator().
PixelGetBlue()
WandExport double PixelGetBlue (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetBlueQuantum()
WandExport Quantum PixelGetBlueQuantum (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickBlackThresholdImage(), MagickColorizeImage(), MagickTintImage(), and MagickWhiteThresholdImage().
PixelGetColorAsNormalizedString()
WandExport char * PixelGetColorAsNormalizedString (const PixelWand * wand)
References _PixelWand::debug, MaxTextExtent, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetColorAsString()
WandExport char * PixelGetColorAsString (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetColorCount()
WandExport size_t PixelGetColorCount (const PixelWand * wand)
References _PixelWand::count, _PixelWand::debug, _PixelWand::name, _PixelWand::signature, and WandSignature.
PixelGetCyan()
WandExport double PixelGetCyan (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetCyanQuantum()
WandExport Quantum PixelGetCyanQuantum (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetException()
WandExport char * PixelGetException (const PixelWand * wand, ExceptionType * severity)
References _PixelWand::debug, _PixelWand::exception, MaxTextExtent, _PixelWand::name, _PixelWand::signature, ThrowWandFatalException, and WandSignature.
PixelGetExceptionType()
WandExport ExceptionType PixelGetExceptionType (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::exception, _PixelWand::name, _PixelWand::signature, and WandSignature.
PixelGetFuzz()
WandExport double PixelGetFuzz (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetGreen()
WandExport double PixelGetGreen (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetGreenQuantum()
WandExport Quantum PixelGetGreenQuantum (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickBlackThresholdImage(), MagickColorizeImage(), MagickTintImage(), and MagickWhiteThresholdImage().
PixelGetHSL()
WandExport void PixelGetHSL (const PixelWand * wand, double * hue, double * saturation, double * lightness)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetIndex()
WandExport IndexPacket PixelGetIndex (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickSetImagePixelColor().
PixelGetMagenta()
WandExport double PixelGetMagenta (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetMagentaQuantum()
WandExport Quantum PixelGetMagentaQuantum (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetMagickColor()
WandExport void PixelGetMagickColor (const PixelWand * wand, MagickPixelPacket * color)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickFloodfillPaintImage(), MagickLevelImageColorsChannel(), MagickNewImage(), MagickOpaquePaintImageChannel(), MagickSetImageColor(), and MagickTransparentPaintImage().
PixelGetOpacity()
WandExport double PixelGetOpacity (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetOpacityQuantum()
WandExport Quantum PixelGetOpacityQuantum (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickBlackThresholdImage(), MagickColorizeImage(), MagickTintImage(), and MagickWhiteThresholdImage().
PixelGetQuantumColor()
WandExport void PixelGetQuantumColor (const PixelWand * wand, PixelPacket * color)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by DrawSetBorderColor(), DrawSetFillColor(), DrawSetStrokeColor(), DrawSetTextUnderColor(), DuplexTransferPixelViewIterator(), DuplexTransferWandViewIterator(), MagickBorderImage(), MagickColorFloodfillImage(), MagickColorizeImage(), MagickFloodfillPaintImage(), MagickFrameImage(), MagickMatteFloodfillImage(), MagickMontageImage(), MagickRotateImage(), MagickSetBackgroundColor(), MagickSetImageBackgroundColor(), MagickSetImageBorderColor(), MagickSetImageColormapColor(), MagickSetImageMatteColor(), MagickSetImagePixelColor(), MagickShearImage(), MagickTintImage(), PixelSyncIterator(), SetPixelViewIterator(), SetWandViewIterator(), TransferPixelViewIterator(), TransferWandViewIterator(), UpdatePixelViewIterator(), and UpdateWandViewIterator().
PixelGetRed()
WandExport double PixelGetRed (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetRedQuantum()
WandExport Quantum PixelGetRedQuantum (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by MagickBlackThresholdImage(), MagickColorizeImage(), MagickTintImage(), and MagickWhiteThresholdImage().
PixelGetYellow()
WandExport double PixelGetYellow (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelGetYellowQuantum()
WandExport Quantum PixelGetYellowQuantum (const PixelWand * wand)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetAlpha()
WandExport void PixelSetAlpha (PixelWand * wand, const double alpha)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetAlphaQuantum()
WandExport void PixelSetAlphaQuantum (PixelWand * wand, const Quantum opacity)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetBlack()
WandExport void PixelSetBlack (PixelWand * wand, const double black)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetBlackQuantum()
WandExport void PixelSetBlackQuantum (PixelWand * wand, const Quantum black)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by DuplexTransferPixelViewIterator(), DuplexTransferWandViewIterator(), GetPixelViewIterator(), GetWandViewIterator(), MagickGetImagePixelColor(), PixelGetCurrentIteratorRow(), PixelGetNextIteratorRow(), PixelGetPreviousIteratorRow(), TransferPixelViewIterator(), TransferWandViewIterator(), UpdatePixelViewIterator(), and UpdateWandViewIterator().
PixelSetBlue()
WandExport void PixelSetBlue (PixelWand * wand, const double blue)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetBlueQuantum()
WandExport void PixelSetBlueQuantum (PixelWand * wand, const Quantum blue)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetColor()
WandExport MagickBooleanType PixelSetColor (PixelWand * wand, const char * color)
References _PixelWand::debug, _PixelWand::exception, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetColorCount()
WandExport void PixelSetColorCount (PixelWand * wand, const size_t count)
References _PixelWand::count, _PixelWand::debug, _PixelWand::name, _PixelWand::signature, and WandSignature.
Referenced by MagickGetImageHistogram().
PixelSetColorFromWand()
WandExport void PixelSetColorFromWand (PixelWand * wand, const PixelWand * color)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetCyan()
WandExport void PixelSetCyan (PixelWand * wand, const double cyan)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetCyanQuantum()
WandExport void PixelSetCyanQuantum (PixelWand * wand, const Quantum cyan)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetFuzz()
WandExport void PixelSetFuzz (PixelWand * wand, const double fuzz)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetGreen()
WandExport void PixelSetGreen (PixelWand * wand, const double green)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetGreenQuantum()
WandExport void PixelSetGreenQuantum (PixelWand * wand, const Quantum green)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetHSL()
WandExport void PixelSetHSL (PixelWand * wand, const double hue, const double saturation, const double lightness)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetIndex()
WandExport void PixelSetIndex (PixelWand * wand, const IndexPacket index)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by DuplexTransferPixelViewIterator(), DuplexTransferWandViewIterator(), GetPixelViewIterator(), GetWandViewIterator(), MagickGetImageHistogram(), MagickGetImagePixelColor(), PixelGetCurrentIteratorRow(), PixelGetNextIteratorRow(), PixelGetPreviousIteratorRow(), TransferPixelViewIterator(), and TransferWandViewIterator().
PixelSetMagenta()
WandExport void PixelSetMagenta (PixelWand * wand, const double magenta)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetMagentaQuantum()
WandExport void PixelSetMagentaQuantum (PixelWand * wand, const Quantum magenta)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetMagickColor()
WandExport void PixelSetMagickColor (PixelWand * wand, const MagickPixelPacket * color)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetOpacity()
WandExport void PixelSetOpacity (PixelWand * wand, const double opacity)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetOpacityQuantum()
WandExport void PixelSetOpacityQuantum (PixelWand * wand, const Quantum opacity)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetQuantumColor()
WandExport void PixelSetQuantumColor (PixelWand * wand, const PixelPacket * color)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
Referenced by DrawGetBorderColor(), DrawGetFillColor(), DrawGetStrokeColor(), DrawGetTextUnderColor(), DuplexTransferPixelViewIterator(), DuplexTransferWandViewIterator(), GetPixelViewIterator(), GetWandViewIterator(), MagickGetBackgroundColor(), MagickGetImageBackgroundColor(), MagickGetImageBorderColor(), MagickGetImageColormapColor(), MagickGetImageHistogram(), MagickGetImageMatteColor(), MagickGetImagePixelColor(), PixelGetCurrentIteratorRow(), PixelGetNextIteratorRow(), PixelGetPreviousIteratorRow(), TransferPixelViewIterator(), TransferWandViewIterator(), UpdatePixelViewIterator(), and UpdateWandViewIterator().
PixelSetRed()
WandExport void PixelSetRed (PixelWand * wand, const double red)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetRedQuantum()
WandExport void PixelSetRedQuantum (PixelWand * wand, const Quantum red)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetYellow()
WandExport void PixelSetYellow (PixelWand * wand, const double yellow)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.
PixelSetYellowQuantum()
WandExport void PixelSetYellowQuantum (PixelWand * wand, const Quantum yellow)
References _PixelWand::debug, _PixelWand::name, _PixelWand::pixel, _PixelWand::signature, and WandSignature.