MagickWand: wand-view.c File Reference
wand-view.c File Reference
#include "wand/studio.h"
#include "wand/MagickWand.h"
#include "wand/magick-wand-private.h"
#include "wand/wand.h"
#include "magick/monitor-private.h"
#include "magick/thread-private.h"
Data Structures
struct _WandView
Macros
#define WandViewId "WandView"
Functions
WandExport WandView * CloneWandView (const WandView *wand_view)
static PixelWand *** DestroyPixelsThreadSet (PixelWand ***pixel_wands, const size_t number_wands, const size_t number_threads)
WandExport WandView * DestroyWandView (WandView *wand_view)
WandExport MagickBooleanType DuplexTransferWandViewIterator (WandView *source, WandView *duplex, WandView *destination, DuplexTransferWandViewMethod transfer, void *context)
WandExport char * GetWandViewException (const WandView *wand_view, ExceptionType *severity)
WandExport RectangleInfo GetWandViewExtent (const WandView *wand_view)
WandExport MagickBooleanType GetWandViewIterator (WandView *source, GetWandViewMethod get, void *context)
WandExport PixelWand ** GetWandViewPixels (const WandView *wand_view)
WandExport MagickWand * GetWandViewWand (const WandView *wand_view)
WandExport MagickBooleanType IsWandView (const WandView *wand_view)
static PixelWand *** AcquirePixelsThreadSet (const size_t number_wands, const size_t number_threads)
WandExport WandView * NewWandView (MagickWand *wand)
WandExport WandView * NewWandViewExtent (MagickWand *wand, const ssize_t x, const ssize_t y, const size_t width, const size_t height)
MagickExport void SetWandViewDescription (WandView *wand_view, const char *description)
WandExport MagickBooleanType SetWandViewIterator (WandView *destination, SetWandViewMethod set, void *context)
MagickExport void SetWandViewThreads (WandView *image_view, const size_t number_threads)
WandExport MagickBooleanType TransferWandViewIterator (WandView *source, WandView *destination, TransferWandViewMethod transfer, void *context)
WandExport MagickBooleanType UpdateWandViewIterator (WandView *source, UpdateWandViewMethod update, void *context)
Macro Definition Documentation
WandViewId
#define WandViewId "WandView"
Function Documentation
AcquirePixelsThreadSet()
static PixelWand *** AcquirePixelsThreadSet (const size_t number_wands, const size_t number_threads) static
References DestroyPixelsThreadSet(), and NewPixelWands().
Referenced by NewWandView(), and NewWandViewExtent().
CloneWandView()
WandExport WandView * CloneWandView (const WandView * wand_view)
References AcquireWandId(), ClonePixelWands(), _WandView::debug, _WandView::description, _WandView::exception, _WandView::extent, _WandView::id, MaxTextExtent, _WandView::name, _WandView::number_threads, _WandView::pixel_wands, _WandView::signature, _WandView::view, WandSignature, and WandViewId.
DestroyPixelsThreadSet()
static PixelWand *** DestroyPixelsThreadSet (PixelWand *** pixel_wands, const size_t number_wands, const size_t number_threads) static
References DestroyPixelWands().
Referenced by AcquirePixelsThreadSet(), and DestroyWandView().
DestroyWandView()
WandExport WandView * DestroyWandView (WandView * wand_view)
References DestroyPixelsThreadSet(), _WandView::exception, _WandView::extent, _WandView::id, _WandView::number_threads, _WandView::pixel_wands, RelinquishWandId(), _WandView::signature, _WandView::view, and WandSignature.
DuplexTransferWandViewIterator()
WandExport MagickBooleanType DuplexTransferWandViewIterator (WandView * source, WandView * duplex, WandView * destination, DuplexTransferWandViewMethod transfer, void * context)
References _WandView::description, _WandView::exception, _WandView::extent, _MagickWand::images, magick_restrict, _WandView::pixel_wands, PixelGetBlackQuantum(), PixelGetQuantumColor(), PixelSetBlackQuantum(), PixelSetIndex(), PixelSetQuantumColor(), _WandView::signature, _WandView::view, _WandView::wand, and WandSignature.
GetWandViewException()
WandExport char * GetWandViewException (const WandView * wand_view, ExceptionType * severity)
References _WandView::debug, _WandView::exception, MaxTextExtent, _WandView::name, _WandView::signature, ThrowWandFatalException, and WandSignature.
GetWandViewExtent()
WandExport RectangleInfo GetWandViewExtent (const WandView * wand_view)
References _WandView::extent, _WandView::signature, and WandSignature.
GetWandViewIterator()
WandExport MagickBooleanType GetWandViewIterator (WandView * source, GetWandViewMethod get, void * context)
References _WandView::description, _WandView::exception, _WandView::extent, _MagickWand::images, _WandView::pixel_wands, PixelSetBlackQuantum(), PixelSetIndex(), PixelSetQuantumColor(), _WandView::signature, _WandView::view, _WandView::wand, and WandSignature.
GetWandViewPixels()
WandExport PixelWand ** GetWandViewPixels (const WandView * wand_view)
References _WandView::pixel_wands, _WandView::signature, and WandSignature.
GetWandViewWand()
WandExport MagickWand * GetWandViewWand (const WandView * wand_view)
References _WandView::signature, _WandView::wand, and WandSignature.
IsWandView()
WandExport MagickBooleanType IsWandView (const WandView * wand_view)
References _WandView::name, _WandView::signature, WandSignature, and WandViewId.
NewWandView()
WandExport WandView * NewWandView (MagickWand * wand)
References AcquirePixelsThreadSet(), AcquireWandId(), _WandView::debug, _WandView::description, _WandView::exception, _WandView::extent, _WandView::id, _MagickWand::images, MaxTextExtent, _WandView::name, _WandView::number_threads, _WandView::pixel_wands, _MagickWand::signature, _WandView::signature, ThrowWandFatalException, _WandView::view, _WandView::wand, WandSignature, and WandViewId.
NewWandViewExtent()
WandExport WandView * NewWandViewExtent (MagickWand * wand, const ssize_t x, const ssize_t y, const size_t width, const size_t height)
References AcquirePixelsThreadSet(), AcquireWandId(), _WandView::debug, _WandView::description, _WandView::exception, _WandView::extent, _WandView::id, _MagickWand::images, MaxTextExtent, _WandView::name, _WandView::number_threads, _WandView::pixel_wands, _MagickWand::signature, _WandView::signature, ThrowWandFatalException, _WandView::view, _WandView::wand, WandSignature, and WandViewId.
SetWandViewDescription()
MagickExport void SetWandViewDescription (WandView * wand_view, const char * description)
References _WandView::description, _WandView::signature, and WandSignature.
SetWandViewIterator()
WandExport MagickBooleanType SetWandViewIterator (WandView * destination, SetWandViewMethod set, void * context)
References _WandView::description, _WandView::exception, _WandView::extent, _MagickWand::images, magick_restrict, _WandView::pixel_wands, PixelGetBlackQuantum(), PixelGetQuantumColor(), _WandView::signature, _WandView::view, _WandView::wand, and WandSignature.
SetWandViewThreads()
MagickExport void SetWandViewThreads (WandView * image_view, const size_t number_threads)
References _WandView::number_threads, and _WandView::signature.
TransferWandViewIterator()
WandExport MagickBooleanType TransferWandViewIterator (WandView * source, WandView * destination, TransferWandViewMethod transfer, void * context)
References _WandView::description, _WandView::exception, _WandView::extent, _MagickWand::images, magick_restrict, _WandView::pixel_wands, PixelGetBlackQuantum(), PixelGetQuantumColor(), PixelSetBlackQuantum(), PixelSetIndex(), PixelSetQuantumColor(), _WandView::signature, _WandView::view, _WandView::wand, and WandSignature.
UpdateWandViewIterator()
WandExport MagickBooleanType UpdateWandViewIterator (WandView * source, UpdateWandViewMethod update, void * context)
References _WandView::description, _WandView::exception, _WandView::extent, _MagickWand::images, magick_restrict, _WandView::pixel_wands, PixelGetBlackQuantum(), PixelGetQuantumColor(), PixelSetBlackQuantum(), PixelSetQuantumColor(), _WandView::signature, _WandView::view, _WandView::wand, and WandSignature.