MagickWand: wand-view.h File Reference
wand-view.h File Reference
Typedefs
typedef struct _WandView WandView
typedef MagickBooleanType(* DuplexTransferWandViewMethod) (const WandView *, const WandView *, WandView *, const ssize_t, const int, void *)
typedef MagickBooleanType(*)(* GetWandViewMethod) (const WandView *, const ssize_t, const int, void *)
typedef MagickBooleanType(*)(*)(* SetWandViewMethod) (WandView *, const ssize_t, const int, void *)
typedef MagickBooleanType(*)(*)(*)(* TransferWandViewMethod) (const WandView *, WandView *, const ssize_t, const int, void *)
typedef MagickBooleanType(*)(*)(*)(*)(* UpdateWandViewMethod) (WandView *, const ssize_t, const int, void *)
Functions
WandExport char * GetWandViewException (const WandView *, ExceptionType *)
WandExport MagickBooleanType DuplexTransferWandViewIterator (WandView *, WandView *, WandView *, DuplexTransferWandViewMethod, void *)
WandExport MagickBooleanType GetWandViewIterator (WandView *, GetWandViewMethod, void *)
WandExport MagickBooleanType IsWandView (const WandView *)
WandExport MagickBooleanType SetWandViewIterator (WandView *, SetWandViewMethod, void *)
WandExport MagickBooleanType TransferWandViewIterator (WandView *, WandView *, TransferWandViewMethod, void *)
WandExport MagickBooleanType UpdateWandViewIterator (WandView *, UpdateWandViewMethod, void *)
WandExport MagickWand * GetWandViewWand (const WandView *)
WandExport PixelWand ** GetWandViewPixels (const WandView *)
WandExport RectangleInfo GetWandViewExtent (const WandView *)
WandExport void SetWandViewDescription (WandView *, const char *)
WandExport void SetWandViewThreads (WandView *, const size_t)
WandExport WandView * CloneWandView (const WandView *)
WandExport WandView * DestroyWandView (WandView *)
WandExport WandView * NewWandView (MagickWand *)
WandExport WandView * NewWandViewExtent (MagickWand *, const ssize_t, const ssize_t, const size_t, const size_t)
Typedef Documentation
DuplexTransferWandViewMethod
typedef MagickBooleanType(* DuplexTransferWandViewMethod) (const WandView *, const WandView *, WandView *, const ssize_t, const int, void *)
GetWandViewMethod
typedef MagickBooleanType(*)(* GetWandViewMethod) (const WandView *, const ssize_t, const int, void *)
SetWandViewMethod
typedef MagickBooleanType(*)(*)(* SetWandViewMethod) (WandView *, const ssize_t, const int, void *)
TransferWandViewMethod
typedef MagickBooleanType(*)(*)(*)(* TransferWandViewMethod) (const WandView *, WandView *, const ssize_t, const int, void *)
UpdateWandViewMethod
typedef MagickBooleanType(*)(*)(*)(*)(* UpdateWandViewMethod) (WandView *, const ssize_t, const int, void *)
WandView
typedef struct _WandView WandView
Function Documentation
CloneWandView()
WandExport WandView * CloneWandView (const WandView *)
DestroyWandView()
WandExport WandView * DestroyWandView (WandView *)
DuplexTransferWandViewIterator()
WandExport MagickBooleanType DuplexTransferWandViewIterator (WandView * , WandView * , WandView * , DuplexTransferWandViewMethod , void *)
GetWandViewException()
WandExport char * GetWandViewException (const WandView * wand_view, ExceptionType * severity)
References _WandView::debug, _WandView::exception, MaxTextExtent, _WandView::name, _WandView::signature, ThrowWandFatalException, and WandSignature.
GetWandViewExtent()
WandExport RectangleInfo GetWandViewExtent (const WandView * wand_view)
References _WandView::extent, _WandView::signature, and WandSignature.
GetWandViewIterator()
WandExport MagickBooleanType GetWandViewIterator (WandView * , GetWandViewMethod , void *)
GetWandViewPixels()
WandExport PixelWand ** GetWandViewPixels (const WandView * wand_view)
References _WandView::pixel_wands, _WandView::signature, and WandSignature.
GetWandViewWand()
WandExport MagickWand * GetWandViewWand (const WandView * wand_view)
References _WandView::signature, _WandView::wand, and WandSignature.
IsWandView()
WandExport MagickBooleanType IsWandView (const WandView *)
NewWandView()
WandExport WandView * NewWandView (MagickWand *)
NewWandViewExtent()
WandExport WandView * NewWandViewExtent (MagickWand * wand, const ssize_t, const ssize_t, const size_t, const size_t)
References AcquirePixelsThreadSet(), AcquireWandId(), _WandView::debug, _WandView::description, _WandView::exception, _WandView::extent, _WandView::id, _MagickWand::images, MaxTextExtent, _WandView::name, _WandView::number_threads, _WandView::pixel_wands, _MagickWand::signature, _WandView::signature, ThrowWandFatalException, _WandView::view, _WandView::wand, WandSignature, and WandViewId.
SetWandViewDescription()
WandExport void SetWandViewDescription (WandView * , const char *)
SetWandViewIterator()
WandExport MagickBooleanType SetWandViewIterator (WandView * , SetWandViewMethod , void *)
SetWandViewThreads()
WandExport void SetWandViewThreads (WandView * image_view, const size_t)
References _WandView::number_threads, and _WandView::signature.
TransferWandViewIterator()
WandExport MagickBooleanType TransferWandViewIterator (WandView * , WandView * , TransferWandViewMethod , void *)
UpdateWandViewIterator()
WandExport MagickBooleanType UpdateWandViewIterator (WandView * source, UpdateWandViewMethod update, void * context)
References _WandView::description, _WandView::exception, _WandView::extent, _MagickWand::images, magick_restrict, _WandView::pixel_wands, PixelGetBlackQuantum(), PixelGetQuantumColor(), PixelSetBlackQuantum(), PixelSetQuantumColor(), _WandView::signature, _WandView::view, _WandView::wand, and WandSignature.